microsoft/fluentui

- packages/fluentui/CONTRIBUTING.md
- packages/fluentui/docs/src/examples/components/Toolbar/Visual/ToolbarExampleVariables.shorthand.steps.ts
- packages/fluentui/docs/src/examples/components/Toolbar/Visual/ToolbarExampleVariables.shorthand.tsx
Similar to #14848, another try to make this Screener test stable.
> chore: shows menus in ToolbarExampleVariables as a separate step

- scripts/screener/screener.steps.ts
This PR is a preparation for trying another changes as it's impossible to provide options for a default state in Screener.
No visual regressions in this PR.
> chore: rename default screenshots in Screener

- packages/fluentui/docs/src/examples/components/Toolbar/Visual/ToolbarExampleCompose.shorthand.steps.ts
- packages/fluentui/docs/src/examples/components/Toolbar/Visual/ToolbarExampleCompose.shorthand.tsx
#14877 made a VR test with the similar issue stable, trying the same approach there.
> chore: fix ToolbarExampleCompose VR test to be stable

- apps/vr-tests/src/stories/Button.stories.tsx
Adding a few more screener test cases. Leveraging these tests to find styling differences with v8 buttons
(optional)
> Add a few of screener tests for button

- change/@uifabric-charting-2020-09-09-11-17-25-user-gorraj-bug_4377550.json
- packages/charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx
- packages/charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx
Fix app crash when we focus on charts in IE 
charts in IE hover and focus
> Fix app crash when we focus on charts in IE 

- change/@uifabric-charting-2020-09-10-17-34-19-fix-pretty.json
- packages/charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx
- packages/charting/src/components/VerticalStackedBarChart/examples/VerticalStackedBarChart.Styled.Example.tsx
Seems like some code snuck in which was not run through prettier. Addressing.
> Charting with prettier code

- package.json
- scripts/beachball/index.ts
- scripts/package.json
- yarn.lock
Disallow major change type for all packages by default. Package can still override this in beachball config at package level.
Bumping beachball to latest to get the fix needed for this change.
(optional)
> Disallow major change type for all packages by default

- change/@fluentui-react-next-2020-09-15-13-38-54-chore-button-release-notes.json
- packages/react-next/RELEASE_NOTES.md
Just an initial set of updates for release notes.
> Updating react-next release notes for Button.

- packages/react-spinbutton/package.json
> Fix build: package version out of sync

- change/@fluentui-react-next-2020-09-17-14-14-00-feat-updating-react-next-examples.json
- packages/react-next/src/components/Coachmark/examples/Coachmark.Basic.Example.tsx
- packages/react-next/src/components/__snapshots__/Coachmark.Basic.Example.tsx.shot
1. Updating react-next's Coachmark.Basic.Example.tsx to match the v7 version.
2. Updating snapshots.
Porting: https://github.com/microsoft/fluentui/pull/13912
> Updating react-next's Coachmark basic example to a function component

- change/@fluentui-react-next-2020-09-21-12-02-46-fix-updating-react-next-example-imports.json
- packages/react-next/src/components/Coachmark/examples/Coachmark.Basic.Example.tsx
- packages/react-next/src/components/ExtendedPicker/examples/ExtendedPeoplePicker.Basic.Example.tsx
- packages/react-next/src/components/ExtendedPicker/examples/ExtendedPeoplePicker.Controlled.Example.tsx
- packages/react-next/src/components/FloatingPicker/PeoplePicker/examples/FloatingPeoplePicker.Basic.Example.tsx
- packages/react-next/src/components/Layer/examples/Layer.NestedLayers.Example.tsx
- packages/react-next/src/components/ResizeGroup/examples/ResizeGroup.VerticalOverflowSet.Example.tsx
- packages/react-next/src/components/TeachingBubble/examples/TeachingBubble.Wide.Example.tsx
- packages/react-next/src/components/TeachingBubble/examples/TeachingBubble.WideIllustration.Example.tsx
- packages/react-next/src/components/__snapshots__/ResizeGroup.VerticalOverflowSet.Example.tsx.shot
Updating react-next examples to import from @fluentui/react-next.
> Updating react-next example imports

- change/@fluentui-react-next-2020-09-18-16-25-30-pickers-fix.json
- packages/react-next/etc/react-next.api.md
- packages/react-next/src/components/ExtendedPicker/BaseExtendedPicker.tsx
- packages/react-next/src/components/FloatingPicker/BaseFloatingPicker.tsx
- packages/react-next/src/components/FloatingPicker/Suggestions/SuggestionsControl.tsx
- packages/react-next/src/components/SelectedItemsList/BaseSelectedItemsList.tsx
Fixes #14293
Fixes #14294
(optional)
> Floating Pickers: Make pickers strict mode compliant

- .github/CODEOWNERS
Update code owner from Aneesha to Xu
(optional)
> Update code owner from Aneesha to Xu

- change/@uifabric-react-cards-2020-09-23-09-38-16-fix-fixing_theme_package_update.json
- packages/react-cards/package.json
* Update theme package in all usages.
(optional)
> chore: update version of @fluentui/theme used in @uifabric/react-cards

- change/@fluentui-codemods-2020-09-21-14-36-13-codemods-config-fix.json
- packages/codemods/src/codeMods/mods/configMod/configMod.mod.ts
- packages/codemods/src/helpers/maybe.ts
- packages/codemods/src/helpers/result.ts
> Codemods: fix the config mod to still run if no matching mod name is found.

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Toolbar/Toolbar.tsx
The original issue #14064 is a VoiceOver issue. So all this PR did is to link it as one of our known issues. 
(optional)
> docs(toolbar): add known VO accessibilityIssues 

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams-dark/components/Provider/providerVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/colors.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Provider/providerVariables.ts
Give scrollbar new color according to design spec
codesandbox with scrollbar: https://codesandbox.io/s/quirky-minsky-1wwqk
(optional)
> fix(scrollbar): adjust color

- .devops/templates/cleanup.yml
- azure-pipelines.hotfix.yml
- azure-pipelines.perf-test.yml
- azure-pipelines.release.yml
- azure-pipelines.yml
At some point the "check for changed files" build step got lost, so add it back where appropriate to help detect issues (like the missing web-components API update).
We've also still had some trouble with "Directory not empty" errors, so add "workspace: clean: all" a couple more places AND add back the DeleteFiles step everywhere for good measure.
> Fail build on changed files and do more cleanup

- change/@uifabric-api-docs-2020-09-24-10-02-16-xgao-fix-doc.json
- packages/api-docs/config/api-docs.js
fix broken references (e.g. [ISemanticColor](https://developer.microsoft.com/en-us/fluentui#/controls/web/references/isemanticcolors)) due to newly added theme package.
http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/15213/merge/fabric-website/dist/index.html?devhost#/controls/web/references/isemanticcolors
> Website/doc: fix references from theme package.

- change/office-ui-fabric-react-2020-09-23-13-29-27-fix-Modal-removing-unused-eslint.json
- packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx
Removing an unused eslint-disable rule from office-ui-fabric-react `Modal`.
> Removing unused eslint-disable rule from OUFR Modal.base

- change/@fluentui-react-next-2020-09-21-16-44-18-fix-spin-button-plumb-event-information.json
- packages/react-next/etc/react-next.api.md
- packages/react-next/src/components/SpinButton/SpinButton.base.tsx
- packages/react-next/src/components/SpinButton/SpinButton.types.ts
1. Implementing event parameter to `updateValue` , `onIncrement`, and `onDecrement`. 
2. Updating  SpinButton.types to include event parameter.
Porting: https://github.com/microsoft/fluentui/pull/13811
> React-Next porting a patch to allow SpinButton to pass event information

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar-emotion-renderer/src/createEmotionRenderer.tsx
- packages/fluentui/react-northstar-fela-renderer/src/createFelaRenderer.tsx
- packages/fluentui/react-northstar-styles-renderer/src/noopRenderer.ts
- packages/fluentui/react-northstar-styles-renderer/src/types.ts
- packages/fluentui/react-northstar/src/components/Provider/Provider.tsx
- packages/fluentui/styles/src/mergeThemes.ts
This PR adds a cleanup for Fela renders to avoid reported memory leaks.
> fix: avoid memory leaks in Fela renderer in N*

- scripts/tasks/lint-imports.js
Make the lint-imports script also check exports to avoid issues such as the one fixed in #15230.
> Fix lint-imports script to also check exports

- scripts/just.config.ts
Fixing broken storybook deployed sites.
(optional)
> Fixing broken storybook deployed sites

- apps/test-bundles/webpack.config.js
bundle size tests are occasionally timing out ... this PR is to mitigate that for `7.0`
(optional)
> remove V8 related bundle tests for 7.0

- .github/PULL_REQUEST_TEMPLATE.md
update PR template with contribution process change info.
(optional)
> version 8 snap: update PR template

- packages/fluentui/docs/src/examples/components/Datepicker/BestPractices/DatepickerBestPractices.tsx
Add best practices section to `Datepicker` docsite page
> docs(Datepicker): Add best practices section

- change/@fluentui-codemods-2020-10-02-17-43-15-codemods-overflow.json
- packages/codemods/src/codeMods/tests/configMod/configMod.test.ts
- packages/codemods/src/command.ts
- packages/codemods/src/modRunner/runnerUtilities.ts
- packages/codemods/src/upgrade.ts
> Codemods: Fix issue where codemods will max out memory if attempting to save too many files.

- change/@fluentui-codemods-2020-10-05-19-54-21-codemods-tightenreturns.json
- packages/codemods/src/codeMods/mods/configMod/configMod.mod.ts
- packages/codemods/src/codeMods/mods/officeToFluentImport/officeToFluentImport.mod.ts
- packages/codemods/src/codeMods/mods/oldToNewButton/oldToNewButton.mod.ts
- packages/codemods/src/codeMods/mods/personaToAvatar/personaToAvatar.mod.ts
- packages/codemods/src/codeMods/tests/configMod/configMod.test.ts
- packages/codemods/src/codeMods/tests/utilities/importUtils.test.ts
- packages/codemods/src/codeMods/types.ts
- packages/codemods/src/codeMods/utilities/imports.ts
- packages/codemods/src/codeMods/utilities/props.ts
- packages/codemods/src/codeMods/utilities/transforms.ts
- packages/codemods/src/command.ts
- packages/codemods/src/helpers/result.ts
- packages/codemods/src/modRunner/runnerUtilities.ts
- packages/codemods/src/modRunner/tests/mocks/MockMods/CodeMod.mock.ts
- packages/codemods/src/upgrade.ts
> Codemods: Tighten return types for NoOp results.

- yarn.lock
Update some deps to fix security/governance alerts.
> Dep updates to fix security/governance alerts (7.0 edition)

- change/@fluentui-react-next-2020-10-09-17-48-19-fix-searchbox-typings.json
- change/office-ui-fabric-react-2020-10-09-17-48-19-fix-searchbox-typings.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.types.ts
- packages/react-next/etc/react-next.api.md
- packages/react-next/src/components/SearchBox/SearchBox.types.ts
Missed this in the last PR #15450.
> SearchBox: role typings fix

- change/@uifabric-tsx-editor-2020-10-13-15-50-14-xgao-button-polyfill.json
- packages/react-examples/src/react-button/demo/index.tsx
- packages/tsx-editor/src/utilities/defaultSupportedPackages.ts
Fix button IE polyfill demo
(optional)
> Fix button IE polyfill demo

- change/@fluentui-azure-themes-2020-10-13-16-49-40-xgao-7-cherry-picks.json
- change/@fluentui-theme-2020-10-12-13-41-45-xgao-theme-itheme-typing.json
- change/@fluentui-theme-samples-2020-10-13-16-49-40-xgao-7-cherry-picks.json
- change/@uifabric-mdl2-theme-2020-10-12-13-37-09-xgao-theme-packages.json
- packages/azure-themes/README.md
- packages/azure-themes/src/AzureCustomizations.ts
- packages/azure-themes/src/azure/AzureThemeDark.ts
- packages/azure-themes/src/azure/AzureThemeHighContrastDark.ts
- packages/azure-themes/src/azure/AzureThemeHighContrastLight.ts
- packages/azure-themes/src/azure/AzureThemeLight.ts
- packages/mdl2-theme/README.md
- packages/mdl2-theme/src/MDL2Customizations.ts
- packages/mdl2-theme/src/mdl2/MDL2Theme.ts
- packages/mdl2-theme/src/mdl2/styles/Label.styles.ts
- packages/theme-samples/src/DarkCustomizations/DarkCustomizations.ts
- packages/theme-samples/src/DefaultCustomizations.ts
- packages/theme-samples/src/TeamsCustomizations.ts
- packages/theme-samples/src/WordCustomizations.ts
- packages/theme/etc/theme.api.md
- packages/theme/src/types/IScheme.ts
- packages/theme/src/types/ITheme.ts
- packages/theme/src/types/Theme.ts
- packages/theme/src/types/index.ts
Cherry-pick from 7.0 to master: #15480, #15482
(optional)
> cherry-pick theme related PRs from 7.0 to master

- packages/fluentui/react-northstar/src/components/Video/Video.tsx
This is #15494 updated for 47_x branch
> fix(Video): cleanup src on component unmount [47.x]

- change/@uifabric-charting-2020-10-15-08-48-36-user-v-gorraj-LinechartTestcases.json
- packages/charting/src/components/LineChart/LineChart.test.tsx
- packages/charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
Test cases for charting: Line chart
Line chart
> Charting: Test cases for linechart

- scripts/rename-package.ts
Even more fixes! Make the rename script respect custom scopes instead of hardcoding from `@uifabric` to `@fluentui` (though that's still the default). Examples:
| Command | Old name | New name |
|-|-|-|
| `yarn rename-package utilities` |`@uifabric/utilities` | `@fluentui/utilities` |
| `yarn rename-package utilities stuff` |  `@uifabric/utilities` | `@fluentui/stuff` |
| `yarn rename-package @fluentui/utilities stuff` (NEW) | `@fluentui/utilities` | `@fluentui/stuff` |
| `yarn rename-package @fluentui/utilities @fluentui/stuff` (NEW) | `@fluentui/utilities` | `@fluentui/stuff` |
Note that this still won't work on packages without a scope in the name, but that shouldn't be too much of a problem.
Also rename the API file if it exists, and remove the prompting for names since it's probably …
> Super deluxe rename script fixes

- change/@fluentui-react-2020-10-19-15-38-50-feat-react-internal-remving-unused-disabled-lint-rules.json
- change/@fluentui-react-internal-2020-10-19-15-38-50-feat-react-internal-remving-unused-disabled-lint-rules.json
- packages/react-internal/src/components/Autofill/Autofill.test.tsx
- packages/react-internal/src/components/Autofill/Autofill.tsx
- packages/react-internal/src/components/ContextualMenu/ContextualMenu.base.tsx
- packages/react-internal/src/components/ContextualMenu/ContextualMenu.test.tsx
- packages/react-internal/src/components/ContextualMenu/ContextualMenu.types.ts
- packages/react-internal/src/components/ContextualMenu/ContextualMenuItem.types.ts
- packages/react-internal/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuItemWrapper.types.ts
- packages/react-internal/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.tsx
- packages/react-internal/src/components/ExtendedPicker/BaseExtendedPicker.tsx
- packages/react-internal/src/components/FloatingPicker/PeoplePicker/FloatingPeoplePicker.tsx
- packages/react-internal/src/components/FloatingPicker/PeoplePicker/PeoplePickerItems/SelectedItemDefault.tsx
- packages/react-internal/src/components/FloatingPicker/Suggestions/Suggestions.types.ts
- packages/react-internal/src/components/FloatingPicker/Suggestions/SuggestionsControl.tsx
- packages/react-internal/src/components/FloatingPicker/Suggestions/SuggestionsCore.tsx
- packages/react-internal/src/components/FloatingPicker/Suggestions/SuggestionsStore.ts
- packages/react-internal/src/components/FocusTrapZone/FocusTrapZone.test.tsx
- packages/react-internal/src/components/FocusTrapZone/FocusTrapZone.tsx
- packages/react-internal/src/components/Modal/Modal.styles.ts
- packages/react-internal/src/components/Modal/Modal.types.ts
- packages/react-internal/src/components/Panel/Panel.base.tsx
- packages/react-internal/src/components/pickers/PeoplePicker/PeoplePickerItems/SuggestionItemDefault.tsx
- packages/react/src/components/ComboBox/ComboBox.tsx
- packages/react/src/components/Dropdown/Dropdown.base.tsx
Removing unused disabled eslint rules from `react` and `react-internal` packages.
> Removing unused disabled eslint rules from react and react-internal packages

- change/@fluentui-react-internal-2020-10-20-13-37-56-fix-ref-conformance-react-internal-check.json
- packages/react-internal/etc/react-internal.api.md
- packages/react-internal/src/components/Check/Check.base.tsx
- packages/react-internal/src/components/Check/Check.test.tsx
- packages/react-internal/src/components/Check/Check.types.ts
- Adding a forwardRef to `Check`.
- Removing `disabledTests` from Check.test.tsx
`Check`
> [Ref-Conformance] Adding a forwardRef to react-internal Check

- change/@uifabric-experiments-2020-10-21-08-47-13-7.0.json
- packages/experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/__snapshots__/UnifiedPeoplePicker.test.tsx.snap
- packages/experiments/src/components/UnifiedPicker/UnifiedPicker.tsx
- packages/experiments/src/components/UnifiedPicker/__snapshots__/UnifiedPicker.test.tsx.snap
This change is a backport from V8, to support fixing an important bug in an app still using v7.  This change removes the MarqueeSelection (rubberband) selection from UnifiedPicker, which is not the right paradigm for mouse drag-selection in this control.  A proper drag-selection will be implemented in v8.  This change is minimal for v7, as having no drag-selection is better than the wrong one.
(optional)
> 7.0 - Remove MarqueeSelection from UnifiedPicker

- change/@fluentui-web-components-2020-09-29-23-07-40-users-chhol-export-design-system-interface.json
- change/@fluentui-web-components-2020-10-06-09-07-15-users-nirice-close-shadow-roots.json
- change/@fluentui-web-components-2020-10-06-21-36-07-users-chhol-add-skeleton-as-new-component.json
- change/@fluentui-web-components-2020-10-08-10-29-03-users-nicholasrice-fix-card-palette-generation.json
- change/@fluentui-web-components-2020-10-08-15-22-21-users-chhol-button-font-inheritance-issues.json
- change/@fluentui-web-components-2020-10-13-15-51-52-users-chhol-reset-dialog-to-open-mode.json
- change/@fluentui-web-components-2020-10-14-11-01-46-users-nicholasrice-update-card-background-behavior.json
- change/@fluentui-web-components-2020-10-20-09-05-46-fix-web-components-test.json
- packages/web-components/CHANGELOG.json
- packages/web-components/CHANGELOG.md
- Sync latest change logs from `7.0` branch. 
- Remove change files which are associated with already-published changes.
(optional)
> web-components: sync latest change logs and remove unneeded change files

- change/@fluentui-react-experiments-2020-10-22-13-19-40-u-nebhatna-fixInputSelection.json
- packages/react-examples/src/react-experiments/UnifiedPeoplePicker/DoubleUnifiedPeoplePicker.Example.tsx
- packages/react-experiments/src/components/UnifiedPicker/UnifiedPicker.tsx
- packages/react-experiments/src/components/UnifiedPicker/UnifiedPicker.types.ts
Fixing input selection in UnifiedPicker and also adding this to an example.
(optional)
> Fixing input selection in UnifiedPicker

- packages/a11y-testing/src/index.ts
Missed to delete a file from 7.0 branch
(optional)
> Missed to delete a file from 7.0 branch

- change/@fluentui-react-charting-2020-10-21-19-09-10-verticalBarChart.json
- packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx
- packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx
- packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.styles.ts
- packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.tsx
- packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.types.ts
- packages/react-charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap
- packages/react-charting/src/utilities/utilities.ts
- packages/react-examples/src/react-charting/VerticalBarChart/VerticalBarChart.Basic.Example.tsx
- packages/react-examples/src/react-charting/VerticalBarChart/VerticalBarChart.Dynamic.Example.tsx
- packages/react-examples/src/react-charting/VerticalBarChart/VerticalBarChart.Styled.Example.tsx
_Cherry-pick of #15295._
_Original PR description:_
Vertical bar chart code refactored. Implemented Cartesian chart in vertical bar chart base file. 
Includes - 
- Y min max values support.
- Customized callout support.
- Y axis tick count customizations
- Axis tick format support.
Vertical bar chart.
> Charting: Refactoring Vertical Bar Chart via implementation of Cartesian chart

- azure-pipelines.release.yml
- change/@fluentui-react-conformance-2020-10-20-09-58-43-rename-build.json
- change/@fluentui-react-examples-2020-10-16-11-19-05-uppdroptarget.json
- change/@fluentui-storybook-2020-10-20-09-58-43-rename-build.json
- change/@fluentui-storybook-2020-10-21-14-49-09-react-dom-dep.json
Enable release from master. The first release that happens will publish our v8 beta packages. Here is a branch to see [the publish result](https://github.com/microsoft/fluentui/compare/master...xugao:publish_beta?expand=1).
Also delete some change files which belong to now private packages.
(optional)
> Enable release from master

- change/@fluentui-react-charting-2020-10-21-19-09-10-verticalBarChart.json
- change/@fluentui-react-charting-2020-10-22-16-57-32-master.json
- packages/react-charting/src/HeatMapChart.ts
- packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx
- packages/react-charting/src/components/CommonComponents/CartesianChart.types.ts
- packages/react-charting/src/components/HeatMapChart/HeatMapChart.base.tsx
- packages/react-charting/src/components/HeatMapChart/HeatMapChart.styles.ts
- packages/react-charting/src/components/HeatMapChart/HeatMapChart.ts
- packages/react-charting/src/components/HeatMapChart/HeatMapChart.types.ts
- packages/react-charting/src/components/HeatMapChart/index.ts
- packages/react-charting/src/index.ts
- packages/react-charting/src/types/IDataPoint.ts
- packages/react-charting/src/utilities/ChartHoverCard/ChartHoverCard.base.tsx
- packages/react-charting/src/utilities/ChartHoverCard/ChartHoverCard.styles.ts
- packages/react-charting/src/utilities/ChartHoverCard/ChartHoverCard.types.ts
- packages/react-charting/src/utilities/utilities.ts
- packages/react-examples/src/react-charting/HeatMapChart/HeatMapChartBasic.Example.tsx
- packages/react-examples/src/react-charting/HeatMapChart/HeatMapChartPage.tsx
- packages/react-examples/src/react-charting/demo/AppDefinition.tsx
_Cherry-pick of #15296._
_Original PR description:_
added the new chart heat map
- added accessibility too according the figma
https://www.figma.com/file/BJaI0aMC0jXuwsJaGofqM7/Visualizations-(PS-%2B-CFR)?node-id=1153%3A6055
> Charting: Implementing HeatMapChart and introducing some APIs in CartesianChart to support it

- change/@uifabric-file-type-icons-2020-10-22-13-18-54-caperez-fluid_note_filetype_icon.json
- packages/file-type-icons/src/FileTypeIconMap.ts
- packages/file-type-icons/src/initializeFileTypeIcons.tsx
> Update fluid note filetype icon

- scripts/monorepo/runPublished.js
Add missing package to `run:publish`
(optional)
> Add missing package to run:publish 

- packages/fluentui/docs/src/components/ComponentPlayground/propGenerators.tsx
Backports the loader fixes for the docsite in #12417
(optional)
> Backport propGenerators fix for loader size

- packages/fluentui/docs/package.json
- packages/fluentui/docs/src/components/Sidebar/VersionDropdown.tsx
- packages/fluentui/docs/src/index.html
- yarn.lock
Add support for manifest fetching for the version dropdown component in docsite
(optional)
> Support doc versions manifest file for version dropdown

- packages/fluentui/docs/package.json
- packages/fluentui/docs/src/components/Sidebar/VersionDropdown.tsx
- packages/fluentui/docs/src/index.html
- yarn.lock
Add docversion manifest support for 0.47.x
(optional)
> Docversions manifest 47

- change/@fluentui-react-experiments-2020-10-22-13-57-57-u-nebhatna-remainingFluentBugs.json
- change/@fluentui-react-internal-2020-10-22-13-57-57-u-nebhatna-remainingFluentBugs.json
- packages/react-examples/src/react-experiments/UnifiedPeoplePicker/UnifiedPeoplePicker.Example.tsx
- packages/react-experiments/src/components/FloatingSuggestionsComposite/FloatingSuggestionsList/FloatingSuggestionsList.styles.ts
- packages/react-experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/__snapshots__/UnifiedPeoplePicker.test.tsx.snap
- packages/react-experiments/src/components/UnifiedPicker/UnifiedPicker.styles.ts
- packages/react-experiments/src/components/UnifiedPicker/UnifiedPicker.tsx
- packages/react-experiments/src/components/UnifiedPicker/__snapshots__/UnifiedPicker.test.tsx.snap
- packages/react-internal/etc/react-internal.api.md
- packages/react-internal/src/utilities/selection/SelectionZone.tsx
Adding an optional SelectionZone class name and also fixing remaining bugs in UnifiedPicker 
(optional)
> Adding an optional SelectionZone class name and also fixing remaining bugs in UnifiedPicker

- change/@fluentui-react-examples-2020-10-23-10-30-34-fixInputSelection7.0.json
- change/@uifabric-experiments-2020-10-23-10-30-34-fixInputSelection7.0.json
- packages/experiments/src/components/UnifiedPicker/UnifiedPicker.tsx
- packages/experiments/src/components/UnifiedPicker/UnifiedPicker.types.ts
- packages/react-examples/src/experiments/UnifiedPeoplePicker/DoubleUnifiedPeoplePicker.Example.tsx
v8 PR - https://github.com/microsoft/fluentui/pull/15650
Fixing input selection in UnifiedPicker and also adding this to an example.
> 7.0: Fixing input selection in the UnifiedPicker

- change/@fluentui-react-examples-2020-10-23-11-04-05-remainingFluentBugs7.0.json
- change/@uifabric-experiments-2020-10-23-11-04-05-remainingFluentBugs7.0.json
- change/office-ui-fabric-react-2020-10-23-11-04-05-remainingFluentBugs7.0.json
- packages/experiments/src/components/FloatingSuggestionsComposite/FloatingSuggestionsList/FloatingSuggestionsList.styles.ts
- packages/experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/__snapshots__/UnifiedPeoplePicker.test.tsx.snap
- packages/experiments/src/components/UnifiedPicker/UnifiedPicker.styles.ts
- packages/experiments/src/components/UnifiedPicker/UnifiedPicker.tsx
- packages/experiments/src/components/UnifiedPicker/__snapshots__/UnifiedPicker.test.tsx.snap
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx
- packages/react-examples/src/experiments/UnifiedPeoplePicker/UnifiedPeoplePicker.Example.tsx
v8 pr: https://github.com/microsoft/fluentui/pull/15652
Adding an optional SelectionZone class name and also fixing remaining bugs in UnifiedPicker
> 7.0: Adding an optional SelectionZone class name and also fixing remaining bugs in UnifiedPicker

- package.json
- yarn.lock
Hopefully this will fix some of the issues we've seen with errors being missed (so the build "succeeds" even though something failed) or logs getting eaten.
> Update lage to pick up some bug fixes (v7)

- package.json
- scripts/package.json
- yarn.lock
Hopefully this will fix some of the issues we've seen with errors being missed (so the build "succeeds" even though something failed) or logs getting eaten.
> Update lage to pick up some bug fixes

- change/@fluentui-file-type-icons-2020-10-23-17-34-12-fluidNoteFiletypeIcon.json
- packages/file-type-icons/src/FileTypeIconMap.ts
- packages/file-type-icons/src/initializeFileTypeIcons.tsx
_Cherry-pick of #15649._
_Original PR description:_
> Fluid note filetype icon

- packages/fluentui/e2e/e2eApi.ts
- packages/fluentui/e2e/tests/dialogInDialogWithDropdown-test.ts
- packages/fluentui/e2e/tests/dialogWithDropdown-test.ts
- packages/fluentui/e2e/tests/dropdownSearch-example.tsx
- packages/fluentui/e2e/tests/dropdownSearch-test.ts
- packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx
Backport #13800 to react-northstar 0.47.x
> Backport #13800 to react-northstar 0.47.x

- scripts/tasks/webpack.ts
Fix `find-free-port` import
(optional)
> Fix webpack dev server

- apps/public-docsite/webpack.serve.config.js
fix `public-docsite` dev webpack output folder path
(optional)
> public-docsite: fix dev webpack output folder path

- change/@fluentui-react-2020-10-27-17-18-03-export-window-provider.json
- change/@fluentui-react-internal-2020-10-27-17-18-03-export-window-provider.json
- packages/react-internal/etc/react-internal.api.md
- packages/react-internal/src/WindowProvider.ts
- packages/react-internal/src/components/FocusTrapZone/FocusTrapZone.tsx
- packages/react-internal/src/components/Layer/Layer.base.tsx
- packages/react-internal/src/components/ResizeGroup/ResizeGroup.base.tsx
- packages/react-internal/src/components/TeachingBubble/TeachingBubbleContent.base.tsx
- packages/react-internal/src/index.ts
- packages/react-internal/src/utilities/decorators/withResponsiveMode.tsx
- packages/react-internal/src/utilities/hooks/useResponsiveMode.tsx
- packages/react/src/WindowProvider.ts
Export window provider from `@fluentui/react` package (under `lib/WindowProvider`)
v7 PR: #15736
(optional)
> Export window provider from @fluentui/react package

- packages/fluentui/CHANGELOG.md
- packages/fluentui/docs/src/views/CategoryColorSchemes.tsx
- packages/fluentui/react-northstar/src/themes/teams-dark/colors.ts
- packages/fluentui/react-northstar/src/themes/teams-high-contrast/colors.ts
- packages/fluentui/react-northstar/src/themes/teams/categoryColors.ts
* Added new design token for category colors
* Fixed docs for category colors to display 'missing colors' which were always present
(optional)
> Add new design token for category colors, fix docs

- packages/fluentui/docs/src/components/Sidebar/VersionDropdown.tsx
Add depedency array to manifest fetch so it only tries once on render
(optional)
> Add depedency array to manifest fetch so it only tries once on render

- change/@uifabric-charting-2020-10-29-13-01-16-user-v-jasha-donutChartUTCases.json
- packages/charting/src/components/DonutChart/Arc/Arc.tsx
- packages/charting/src/components/DonutChart/DonutChart.base.tsx
- packages/charting/src/components/DonutChart/DonutChart.test.tsx
- packages/charting/src/components/DonutChart/Pie/Pie.tsx
- packages/charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap
Added basic unit test cases and snapshot test cases to the Donut chart. Little bit of code cleanup.
Donut chart
> Charting: Basic unit test cases for Donut chart

- change/@fluentui-codemods-2020-10-30-16-38-22-fix-codemods-not-savingsync.json
- packages/codemods/package.json
- packages/codemods/src/modRunner/tests/upgrade.test.ts
- packages/codemods/src/upgrade.ts
- yarn.lock
> Codemods: Fix an issue where files would not save synchronously.

- .github/CODEOWNERS
- change/@fluentui-theme-2020-11-02-15-23-47-stylesheet-prop.json
- packages/react-examples/src/react-theme-provider/ThemeProvider/ThemeProvider.doc.tsx
- packages/theme/etc/theme.api.md
- packages/theme/src/types/Theme.ts
`stylesheets` is still experimental and not ready for being public yet. We will likely rename it to something else soon. Also removed related code example from doc site for now. 
(optional)
> Mark stylesheets property in Theme as internal

- .github/CODEOWNERS
- change/@fluentui-theme-2020-11-02-16-46-06-7.0.json
- packages/theme/etc/theme.api.md
- packages/theme/src/types/Theme.ts
Mark stylesheets property in Theme as internal. 
cherry-pick from master: #15806
(optional)
> Mark stylesheets property in Theme as internal (7.0)

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-builder/src/components/Knobs.tsx
based on https://github.com/microsoft/fluentui/pull/15118/files
> feat(UIBuilder): Add accessibility props to ui builder

- packages/fluentui/docs/src/examples/components/Datepicker/Performance/DatepickerMinimal.perf.tsx
- packages/fluentui/docs/src/examples/components/Datepicker/Performance/index.tsx
- packages/fluentui/docs/src/examples/components/Datepicker/index.tsx
Add minimal perf test for `Datepicker`
(optional)
> feat(Datepicker): add minimal perf test

- packages/fluentui/docs/src/examples/components/Datepicker/Performance/DatepickerMinimal.perf.tsx
Set fixed date for perf example to avoid regression on daily basis 
(optional)
> fix(Datepicker): Fix perf example

- change/office-ui-fabric-react-2020-11-06-14-15-32-exports7.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Button/index.ts
- packages/office-ui-fabric-react/src/components/Callout/index.ts
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts
- packages/office-ui-fabric-react/src/components/ContextualMenu/index.ts
- packages/office-ui-fabric-react/src/components/Panel/index.ts
These files need to be exported to avoid deep imports (incompatible in fluentui/react)
> Add missing exports for CalloutContentBase, PanelBase and more

- change/@fluentui-react-examples-2020-11-07-00-28-54-user-v-sivsar-FixHeatMapBug.json
- change/@uifabric-charting-2020-11-07-00-28-54-user-v-sivsar-FixHeatMapBug.json
- packages/charting/src/components/CommonComponents/CartesianChart.base.tsx
- packages/charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
- packages/charting/src/components/HeatMapChart/HeatMapChart.base.tsx
- packages/charting/src/components/HeatMapChart/HeatMapChart.test.tsx
- packages/charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap
- packages/react-examples/src/charting/HeatMapChart/HeatMapChartBasic.Example.tsx
we deduces the type of the axis based on the data in the first array, but it misses the fact that first array may or may not have the data, due to which error occurs when the data is not present. so we need to move forward to next array and check if the data is there and then with the help of that data we need to deduce the type of the axis , if data is not present then we should move to next array
note:- I have updated the example by removing the data in first array.
**after fix**
**before fix**
Heatmap chart
> User/v sivsar/fix heat map bug

- .github/CODEOWNERS
Add @ling1726 to N* codeowners
> Add ling1726 to codeowners

- change/@fluentui-react-internal-2020-11-09-16-47-46-exports8.json
- packages/react-internal/etc/react-internal-compat.api.md
- packages/react-internal/etc/react-internal.api.md
- packages/react-internal/src/compat/components/Button/index.ts
- packages/react-internal/src/components/Callout/index.ts
- packages/react-internal/src/components/ContextualMenu/index.ts
- packages/react-internal/src/components/Panel/index.ts
These files need to be exported to avoid deep imports (incompatible in fluentui/react)
> Add missing exports to API

- change/@fluentui-react-experiments-2020-11-10-11-24-56-upp-hover-states.json
- packages/react-experiments/src/components/SelectedItemsList/SelectedPeopleList/Items/SelectedPersona.styles.ts
- packages/react-experiments/src/components/SelectedItemsList/SelectedPeopleList/__snapshots__/SelectedPeopleList.test.tsx.snap
- packages/react-experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/__snapshots__/UnifiedPeoplePicker.test.tsx.snap
Fixed and cleaned up SelectedPersona styles to have more consistent hover/active states in normal and HC themes.
Left: before, right: after
Normal:
Hover:
Selected:
Selected + hover:
Invalid:
Invalid + hover:
Invalid + selected:
Normal + high contrast:
Hover + high contrast:
Selected + high contrast:
Selected + hover + high contrast:
Invalid + high contrast:
Invalid + hover + high contrast:
Invalid + selected + high contrast:
> SelectedPersona: Fix hover/active states in normal and high contrast modes

- change/@uifabric-experiments-2020-11-10-15-06-04-upp-hover-states-7.0.json
- packages/experiments/src/components/SelectedItemsList/SelectedPeopleList/Items/SelectedPersona.styles.ts
- packages/experiments/src/components/SelectedItemsList/SelectedPeopleList/__snapshots__/SelectedPeopleList.test.tsx.snap
- packages/experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/__snapshots__/UnifiedPeoplePicker.test.tsx.snap
Backport PR #15902 to 7.0
Fixed and cleaned up SelectedPersona styles to have more consistent hover/active states in normal and HC themes.
Retested in storybook in normal and high contrast modes.
> 7.0: SelectedPersona: Fix hover/active states in normal and high contrast modes

- apps/vr-tests/src/stories/Callout.stories.tsx
> Callout: Fix failing vr test

- change/@fluentui-react-internal-2020-11-12-14-08-00-fix-build.json
- packages/react-internal/etc/react-internal.api.md
Fix build: react-internal.api.md is out of sync.
Root cause: the build of [this PR](https://github.com/microsoft/fluentui/pull/15770) is too old.
(optional)
> Fix build: react-internal.api.md is out of sync.

- change/@fluentui-react-button-2020-11-16-16-16-15-cherry-pick-button-fixes.json
- change/@fluentui-react-theme-provider-2020-11-16-16-16-15-cherry-pick-button-fixes.json
- packages/react-button/etc/react-button.api.md
- packages/react-button/src/components/Button/Button.test.tsx
- packages/react-button/src/components/Button/__snapshots__/Button.test.tsx.snap
- packages/react-button/src/components/CompoundButton/CompoundButton.tsx
- packages/react-button/src/components/CompoundButton/useCompoundButtonClasses.ts
- packages/react-button/src/components/MenuButton/MenuButton.tsx
- packages/react-button/src/components/MenuButton/useMenuButtonClasses.ts
- packages/react-button/src/components/ToggleButton/ToggleButton.tsx
- packages/react-button/src/components/ToggleButton/useToggleButtonClasses.tsx
- packages/react-theme-provider/src/makeVariantClasses.test.tsx
- packages/react-theme-provider/src/styleRenderers/useStyleRenderer.tsx
Cherry-pick changes from #15433
(optional)
> Button: updating styling hooks for derivative Buttons to abstract depending on button styling (cherry-pick from 7.0)

- change/@fluentui-react-cards-2020-11-18-13-46-59-cardBorderStyleToken.json
- packages/react-cards/src/next/useCardClasses.ts
Adding `borderStyle` token to `Card` styles.
(optional)
> Adding borderStyle token to Card styles.

- change/@fluentui-react-2020-11-18-12-29-27-pb-breadcrumb-fixes.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.base.tsx
- packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.types.ts
This is a cherry-pick of https://github.com/microsoft/fluentui/pull/15977 to 7.0 branch
\cc @khmakoto @xugao
> Allow for custom overflow button in breadcrumb with correct props

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Form/FormField.tsx
- packages/fluentui/react-northstar/test/specs/components/Form/FormField-test.tsx
`id` prop passed to `FormField` shorthand should be passed to `control`
(optional)
> fix(FormField): pass id to control

- apps/vr-tests/src/stories/Callout.stories.tsx
> Callout: Remove Callout stories animations to help with test flakiness

- packages/fluentui/projects-test/src/index.ts
Temporary disable the test until we will find out the reason of failure.
> chore: disable temporary project-test for CRA

- packages/fluentui/CHANGELOG.md
- packages/fluentui/docs/src/components/Sidebar/VersionDropdown.tsx
Silently handles failed manifest fetching for version dropdown in docsite
> Handle failed manifest fetches for version dropdown

- packages/react-examples/src/react/Nav/Nav.doc.tsx
- packages/react-examples/src/react/Nav/docs/NavBestPractices.md
- packages/react-examples/src/react/Nav/docs/NavDonts.md
- packages/react-examples/src/react/Nav/docs/NavDos.md
- packages/react-examples/src/react/Nav/docs/NavOverview.md
The Nav overview described some behaviors which aren't currently implemented. Replace that description with the one from the latest "editorial board" revisions. Also convert the best practices content from dos/don'ts to the newer format.
> Update Nav documentation to correctly reflect current behavior

- change/@fluentui-react-examples-2020-11-20-12-51-00-nav-docs-7.json
- packages/react-examples/src/office-ui-fabric-react/Nav/Nav.doc.tsx
- packages/react-examples/src/office-ui-fabric-react/Nav/docs/NavDonts.md
- packages/react-examples/src/office-ui-fabric-react/Nav/docs/NavDos.md
- packages/react-examples/src/office-ui-fabric-react/Nav/docs/NavOverview.md
- packages/react-examples/src/react/Nav/docs/NavBestPractices.md
The Nav overview described some behaviors which aren't currently implemented. Replace that description with the one from the latest "editorial board" revisions. Also convert the best practices content from dos/don'ts to the newer format.
(corresponding master change: #16032)
> (7.0) Update Nav documentation to correctly reflect current behavior

- change/@fluentui-react-focus-2020-11-24-17-15-45-fix-package-size.json
- packages/react-focus/.npmignore
Removing dist/storybook from the npm output.
> Fixing react-focus package size

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/RadioGroup/RadioGroup.tsx
Adding bug for JAWS radio group. More info in the bug itself.
> Adding JAWS bug for radiogroup

- apps/vr-tests/src/stories/Dropdown.stories.tsx
- change/office-ui-fabric-react-2020-12-01-18-25-58-dropdown-option-fix.json
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.styles.ts
> Dropdown: fix option text truncation for single-select (cherry-pick to 7.0)

- change/@fluentui-merge-styles-2020-12-01-16-51-16-15424-mergeStyles-important.json
- packages/merge-styles/src/styleToClassName.test.ts
- packages/merge-styles/src/styleToClassName.ts
Fix mergeStyles handling of !important for margin and padding
> Fix mergeStyles handling of !important for margin and padding

- change/@fluentui-react-2020-12-03-14-07-32-icombo.json
- packages/react/etc/react.api.md
- packages/react/src/components/ComboBox/index.ts
> Add missing ComboBox interfaces

- packages/react-examples/src/react-experiments/SelectedPeopleList/SelectedPeopleList.WithEdit.Example.tsx
- packages/react-examples/src/react-experiments/SelectedPeopleList/SelectedPeopleList.WithEditInContextMenu.Example.tsx
I'm going to look at rewriting how edit works and wanted to update the examples to use hooks before I did that.
> Update experiments SelectedPeopleList edit examples to be functional components

- azure-pipelines.perf-test.yml
On-going issue to resolve is [here](https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=160356&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=201f3784-6305-58ec-35b3-0b6912cdeffc&l=14).
(optional)
> Disabling perf-test temporarily to unblock CI

- azure-pipelines.perf-test.yml
Cherry-pick : #16167
(optional)
> Disabling perf-test temporarily to unblock CI (7.0)

- azure-pipelines.perf-test.yml
I switched the token used for perf-test to one from a different account. Seeing if that makes it work again.
> Try re-enabling perf-test build

- change/@fluentui-react-internal-2020-12-08-14-22-16-add-arialabel-topicker.json
- packages/react-examples/src/react/__snapshots__/Announced.SearchResults.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/PeoplePicker.Compact.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/PeoplePicker.Controlled.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/PeoplePicker.LimitedSearch.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/PeoplePicker.Normal.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/PeoplePicker.PreselectedItems.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/PeoplePicker.ProcessSelection.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/TagPicker.Basic.Example.tsx.shot
- packages/react-internal/etc/react-internal.api.md
- packages/react-internal/src/components/pickers/BasePicker.tsx
- packages/react-internal/src/components/pickers/BasePicker.types.ts
- packages/react-internal/src/components/pickers/PeoplePicker/__snapshots__/PeoplePicker.test.tsx.snap
- packages/react-internal/src/components/pickers/TagPicker/__snapshots__/TagPicker.test.tsx.snap
- packages/react-internal/src/components/pickers/__snapshots__/BasePicker.test.tsx.snap
> Pickers: add aria-label to root combobox element of basepicker.

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-icons-northstar/src/components/TvIcon.tsx
- packages/fluentui/react-icons-northstar/src/index.ts
> Added TvIcon

- packages/fluentui/docs/src/components/ComponentDoc/ComponentPerfExample/ComponentPerfExample.tsx
- packages/fluentui/docs/src/components/ComponentPlayground/componentGenerators.tsx
- packages/fluentui/docs/src/components/Sidebar/Sidebar.tsx
- packages/fluentui/docs/src/routes.tsx
> chore(Datepicker): backport docs site changes

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams/types.ts
Export missing split button toggle styles props
> Export split button toggle styles props

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams/types.ts
> chore(SplitButton): backport props

- packages/fluentui/CHANGELOG.md
- packages/fluentui/docs/src/examples/components/Checkbox/Visual/CheckboxExampleLabelFlexColumn.shorthand.tsx
- packages/fluentui/docs/src/examples/components/Checkbox/Visual/index.tsx
- packages/fluentui/docs/src/examples/components/Checkbox/index.tsx
- packages/fluentui/react-northstar/src/themes/teams/components/Checkbox/checkboxStyles.ts
* fix grid template in checkbox
* fix grid template in checkbox
* chagelog
Co-authored-by: Juraj Kapsiar <jukapsia@microsoft.com>
(optional)
> chore(Checkbox): backport "Wrong grid template in checkbox for label end"

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams/components/Menu/menuStyles.ts
* fix(MenuStyles): revert fix for IE11
* fix(MenuStyles): add changelog
* fix(MenuStyles): remove auto width
(optional)
> chore(Menu): backport style fix

- change/@fluentui-react-examples-2020-12-14-16-09-19-port-arialabel-picker.json
- change/office-ui-fabric-react-2020-12-14-11-54-04-port-arialabel-picker.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.types.ts
- packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/__snapshots__/PeoplePicker.test.tsx.snap
- packages/office-ui-fabric-react/src/components/pickers/TagPicker/__snapshots__/TagPicker.test.tsx.snap
- packages/office-ui-fabric-react/src/components/pickers/__snapshots__/BasePicker.test.tsx.snap
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Announced.SearchResults.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/PeoplePicker.Compact.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/PeoplePicker.Controlled.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/PeoplePicker.LimitedSearch.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/PeoplePicker.Normal.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/PeoplePicker.PreselectedItems.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/PeoplePicker.ProcessSelection.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/TagPicker.Basic.Example.tsx.shot
Port of https://github.com/microsoft/fluentui/pull/16187
(optional)
> (7.0) Pickers: Add ability to pass in aria-label

- apps/vr-tests/src/stories/Suggestions.stories.tsx
- change/office-ui-fabric-react-2020-12-16-03-37-49-cherrypicksuggestion.json
- packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx
- packages/office-ui-fabric-react/src/components/pickers/Suggestions/SuggestionsItem.tsx
- packages/office-ui-fabric-react/src/components/pickers/Suggestions/__snapshots__/Suggestions.test.tsx.snap
Cherrypick changes made in PR #16177 to the v7.0 branch.
> Cherrypick PR #16177 - Fix navigating across suggestion items in narrator scan mode

- apps/perf-test/package.json
- apps/perf-test/src/scenarioIterations.js
- apps/perf-test/src/scenarios/MakeStyles.tsx
Add basic perf test for `makeStyles`. Test code is simplified version of [this benchmark test](https://github.com/layershifter/react-native-web/blob/master/packages/benchmarks/src/implementations/make-styles/Box.js)
(optional)
> Add basic makeStyles perf test

- packages/fluentui/react-builder/src/components/Designer.tsx
- packages/fluentui/react-builder/src/components/Knobs.tsx
- packages/fluentui/react-builder/src/config.tsx
- scripts/gulp/plugins/util/docgen.ts
- scripts/gulp/plugins/util/docs-types.ts
- scripts/gulp/plugins/util/getComponentInfo.ts
- scripts/gulp/tasks/component-info.ts
- scripts/gulp/tasks/docs.ts
> improvement(PropsEditor): handle union and element type

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams/types.ts
> Export attachment body style props

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams/types.ts
> Cherry pick attachment body style type export

- packages/fluentui/react-northstar/src/components/Table/TableCell.tsx
- packages/fluentui/react-northstar/src/components/Table/TableRow.tsx
Co-authored-by: Lingfan Gao <lingfan.gao@microsoft.com>
(optional)
> Refactor table event propagation logic (#16264)

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx
> cherry pick dropdown onBlur typin

- packages/fluentui/react-northstar/src/components/Breadcrumb/Breadcrumb.tsx
- packages/fluentui/react-northstar/src/components/Breadcrumb/BreadcrumbDivider.tsx
- packages/fluentui/react-northstar/src/components/Breadcrumb/BreadcrumbItem.tsx
- packages/fluentui/react-northstar/src/components/Breadcrumb/BreadcrumbLink.tsx
Removing `Breadcrumb` unstable flag
(optional)
> chore(Breadcrumb): remove unstable flag

- yarn.lock
> Update caniuse database

- .devops/templates/variables.yml
- apps/perf-test/tasks/perf-test.ts
- azure-pipelines.perf-test.yml
- azure-pipelines.yml
Switch PR deploys and perf results to use the `fluentuipr` Azure storage account (and an Azure connection which only has access to that storage account). See master PR #16304 for more details.
> (7.0) Change Azure PR deploy storage

- packages/fluentui/react-bindings/src/hooks/useTriggerElement.tsx
- packages/fluentui/react-bindings/test/hooks/useTriggerElement-test.tsx
> fix(useTriggerElement): update condition (#16104)

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Chat/ChatMessage.tsx
> chore(Backport): Remove default value for chat header slot (#16321)

- change/@fluentui-web-components-2021-01-04-10-08-52-users-v-sedono-add-menu-disabled-example.json
- change/@fluentui-web-components-2021-01-04-12-10-28-users-v-sedono-add-menu-disabled-example.json
- packages/web-components/src/menu/fixtures/menu.html
Added a simple menu disabled example for easy visual check  the ensure disabled works as expected.
> chore (web components): add menu disabled example

- packages/fluentui/docs/src/examples/components/Avatar/Visual/AvatarStatusOverrideExample.shorthand.tsx
- packages/fluentui/docs/src/examples/components/Avatar/Visual/index.tsx
- packages/fluentui/docs/src/examples/components/Avatar/index.tsx
This PR introduces new `Avatar` VR test to ensure we are not introducing BC in the PR #16382 
(optional)
> chore(Avatar): add VR test for overrides

- azure-pipelines.hotfix.yml
- azure-pipelines.perf-test.yml
- azure-pipelines.release.yml
- azure-pipelines.yml
- yarn-ci.sh
> (7.0) Run yarn with timeout and retries

- scripts/screener/screener.api.ts
- scripts/screener/screener.steps.ts
- scripts/screener/screener.types.ts
> Add waitForSelector step to screener

- scripts/prettier.js
Adds proper documentation for our prettier script alias
**Before:**
**After:**
(optional)
> chore(scripts): improve prettier DX

- scripts/prettier.js
removing debug leftovers added in #16426. 
(optional)
> chore(scripts): remove debug code leftovers from prettier

- packages/react-examples/src/react/Image/docs/ImageDos.md
Fix the alignment of [image best practices do](https://developer.microsoft.com/en-us/fluentui#/controls/web/image)
Overview:
> docs(Image): align best practices Dos

- packages/fluentui/CHANGELOG.md
v0.51.3/v0.51.4's [changelog](https://github.com/microsoft/fluentui/blob/chore/0.51.x/packages/fluentui/CHANGELOG.md) is not yet in master. This PR puts them in
(optional)
> cleanup fluent UI change log since v51.2

- scripts/tasks/fluentui-publish.ts
v0 needs to be force published or lerna can't all the packages that need to be released.
Adding this in the repo to remove a manual release step for v0
(optional)
> Force publish v0

- change/@fluentui-web-components-2021-01-04-10-09-38-users-v-sedono-fix-add-storybook-manager-for-themeing.json
- change/@fluentui-web-components-2021-01-04-12-11-45-users-v-sedono-fix-add-storybook-manager-for-themeing.json
- packages/web-components/.storybook/manager.js
- packages/web-components/.storybook/theme.js
Adds the missing `manager.js` file for proper theming.
> chore (web components): add storybook manager for themeing

- packages/fluentui/projects-test/.gulp.js
- packages/fluentui/projects-test/gulpfile.ts
> chore: fix build via adding missing Gulp files

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-component-event-listener/src/useEventListener.ts
> chore(Backport): fix(useEventListener): avoid double handlers calls in React 17 #16514

- change/@fluentui-react-internal-2021-01-20-16-10-28-ttt.json
- packages/react-internal/src/components/Callout/CalloutContent.base.tsx
> fix a typo in CalloutContent.base.tsx

- change/@fluentui-react-2020-10-14-12-49-04-master.json
- change/@fluentui-react-internal-2020-10-12-20-18-58-master.json
Current master contains old change entries, this PR fixes it.
> fix changelog entries

- change/@uifabric-charting-2021-01-21-12-41-04-user-v-jasha-XaxisCallout.json
- packages/charting/src/components/LineChart/LineChart.base.tsx
Line chart: customized xAxisCalloutData updated for last circle id
Line chart
> Line chart: Last circle callout issue fixed

- packages/react-examples/src/react-link/Link/Link.Basic.Example.tsx
- packages/react-examples/src/react-link/__snapshots__/Link.Basic.Example.tsx.shot
> docs(react-examples): explicitly add behavior to Link rendered as button

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams/components/Accordion/accordionContentStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Accordion/accordionTitleStyles.ts
Adjusted margins for the Accordion title and content
> Accordion component visual polish

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Input/Input.tsx
- packages/fluentui/react-northstar/src/themes/teams/components/Input/clearIndicatorUrl.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Input/inputStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Input/inputVariables.ts
* Fixed paddings for the Input with icons left/right.
* Using CloseIcon for clear indicator.
* Using CheckmarkCircleIcon for successIndicator
> Input component visual polish

- packages/fluentui/react-northstar/src/components/Skeleton/Skeleton.tsx
This PR removes `UNSTABLE` warning from `Skeleton` docs
(optional)
> chore(Skeleton): remove UNSTABLE flag

- packages/fluentui/CHANGELOG.md
> chore: update changelog after 0.52.0 release

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams/components/Carousel/carouselVariables.ts
Add previous changelog and remove unused carousel variables
(optional)
> chore(Carousel): add previous changelog and remove unused variables

- scripts/tasks/jest.ts
ensure jest doesn't error out for packages without tests
(optional)
> Jest: default passWithNoTests to true for all

- apps/pr-deploy-site/package.json
- azure-pipelines.yml
- change/@fluentui-azure-themes-2021-01-27-16-14-23-fix-uifabric-refs.json
- change/@fluentui-monaco-editor-2021-01-27-16-14-23-fix-uifabric-refs.json
- change/@fluentui-react-avatar-2021-01-27-16-14-23-fix-uifabric-refs.json
- change/@fluentui-react-hooks-2021-01-27-16-14-23-fix-uifabric-refs.json
- change/@fluentui-react-monaco-editor-2021-01-27-16-14-23-fix-uifabric-refs.json
- package.json
- packages/azure-themes/README.md
- packages/monaco-editor/scripts/addMonacoWebpackConfig.js
- packages/react-avatar/LICENSE
- packages/react-avatar/src/version.ts
- packages/react-hooks/README.md
- packages/react-monaco-editor/src/components/TsxEditor.tsx
- packages/react-monaco-editor/src/utilities/defaultSupportedPackages.ts
Found a few references to `@uifabric` which were missed in previous passes and need to be replaced with `@fluentui`.
> Remove more @uifabric references

- packages/fluentui/CHANGELOG.md
This PR moves changelog entry to proper section
(optional)
> chore(Changelog): move change to right section

- apps/fabric-website/src/pages/Styles/FabricIconsPage/FabricIconsPage.tsx
- apps/fabric-website/src/pages/Styles/FabricIconsPage/docs/web/FabricIconsUsage.md
- change/@uifabric-fabric-website-2021-01-28-11-35-53-v7-icon-doc.json
This PR is to update the public docsite icon documentation in fluentui v7 to include information about the MDL2 svg icon set
(optional)
> update public docsite icon documentation

- .github/CODEOWNERS
> Update N* accessibility CODEOWNERS

- change/@fluentui-react-avatar-2021-01-28-17-25-20-extract-compose-into-utils.json
- change/@fluentui-react-image-2021-01-28-17-25-20-extract-compose-into-utils.json
- change/@fluentui-react-text-2021-01-28-17-25-20-extract-compose-into-utils.json
Update change type to `patch` instead of `prerelease` for version `0.*` packages.
Related change: #16696 
(optional)
> Fix change type in change files

- change/office-ui-fabric-react-2021-02-01-14-52-40-16263-v7.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Stack/StackItem/StackItem.tsx
- packages/office-ui-fabric-react/src/components/Stack/StackItem/StackItem.types.ts
- StackItem component is now able to handle native props.
> [v7.0]StackItem: allow passing native properties to the root element 

- change/@fluentui-react-internal-2021-01-29-13-25-57-16193.json
- packages/react-examples/src/react/__snapshots__/Separator.Basic.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/Separator.Icon.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/Separator.Theming.Example.tsx.shot
- packages/react-internal/src/components/Separator/Separator.styles.ts
> fix(react): Add high contrast overrides for the Separator

- apps/public-docsite/src/pages/Overviews/GetStartedPage/docs/web/GetStartedDevelopSimple.md
Update getting started section in the public-docsite to include updated step-by-step on how to boot up using our CRA template.
> docs(public-docsite): update getting started with CRA

- azure-pipelines.release.yml
Fix beachball publish script to ensure exit 1 properly. Bad build [here](https://uifabric.visualstudio.com/UI%20Fabric/_build/results?buildId=182298&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7f4965ee-4fd2-5264-ebd6-425522b8bb00)
(optional)
> Fix beachball publish script to have correct exit code

- azure-pipelines.release.yml
Fix beachball publish script to ensure exit 1 properly
(optional)
> Fix beachball publish script to have correct exit code (7.0)

- scripts/webpack/webpack-resources.js
Seems like I did the condition incorrectly. This would fix actually doing the TS Skipping correctly.
(optional)
> fixes the skip ts condition

- change/@fluentui-react-provider-a0c15744-d05c-4002-8c3b-b137795132c0.json
- packages/react-provider/package.json
Add beachball config to react-provider package and update the change file so its change type is `patch` as intended.
> Actually publish react-provider

- change/@fluentui-react-2021-02-03-12-45-40-m-10631.json
- packages/react/etc/react.api.md
- packages/react/src/components/Breadcrumb/Breadcrumb.base.tsx
- packages/react/src/components/Breadcrumb/Breadcrumb.test.tsx
- packages/react/src/components/Breadcrumb/Breadcrumb.types.ts
> Add additional prop support to IBreadcrumbItems

- change/@fluentui-react-make-styles-2021-02-04-16-26-17-fix-make-styles-test.json
- packages/react-make-styles/src/makeStyles.ts
Quick fix for now, might want to execute the selectors for testing in the future
(optional)
> Do not throw makestyles in tests

- change/@fluentui-react-examples-2021-02-04-16-21-51-m-16156.json
- change/@fluentui-react-internal-2021-02-04-16-21-51-m-16156.json
- packages/react-examples/src/react/__snapshots__/Icon.SvgFactory.Example.tsx.shot
- packages/react-internal/src/compat/components/Button/ButtonThemes.ts
> fix(react): Add missing styles for disabled buttons

- packages/fluentui/CHANGELOG.md
1-liner to correct my own mistake
remove a change in changelog 'unreleased' section, because it is published in 51.6
(optional)
> chore: correct changelog

- change/@fluentui-react-internal-2021-02-08-11-06-00-pragma-patch.json
- packages/react-internal/src/components/Stack/Stack.tsx
- packages/react-internal/src/components/Stack/StackItem/StackItem.tsx
- packages/react-internal/src/components/Text/Text.view.tsx
Added additional pragma to set runtime to classic
> Stack: Add jsxRuntime classic pragma

- apps/fabric-website/src/pages/Styles/FabricIconsPage/docs/web/FabricIconsOverview.md
- apps/fabric-website/src/pages/Styles/FabricIconsPage/docs/web/FabricIconsUsage.md
- change/@uifabric-fabric-website-2021-02-02-16-30-24-svg-icon-doc.json
This PR adds more info to the icon documentation for the @fluentui/react-icons-mdl2 set, mainly adding that this package has a less restrictive license and is open sourced.
> update icon documentation page with info about open source package

- change/@uifabric-utilities-2021-02-09-19-14-31-theme-provider-component-styles.json
- packages/utilities/src/merge.test.ts
- packages/utilities/src/merge.ts
Fix `merge` to correctly handle array value
master PR: #16911
Added UT
> Fix merge to correctly handle array value (7.0)

- change/@fluentui-utilities-2021-02-09-19-33-49-fix-merge.json
- packages/utilities/src/merge.test.ts
- packages/utilities/src/merge.ts
Fix `merge` to correctly handle array value
Added UT
> Fix merge to correctly handle array value

- change/@fluentui-react-link-2021-01-25-18-41-45-linkSpec.json
- packages/react-link/MIGRATION.md
- packages/react-link/README.md
- packages/react-link/SPEC.md
This PR adds the initial spec and migration guide for the `Link` component, while also updating the `README` with the latest information.
> Link: Adding initial SPEC.md and MIGRATION.md and updating README.md

- change/office-ui-fabric-react-2021-02-10-11-44-53-menuSectionRoleForFabric7.json
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx
Description of changes
Fix #16901
Focus areas to test
Checked that the menu read out x of x
porting https://github.com/microsoft/fluentui/pull/16905
> Menu section role for fabric7

- change/@fluentui-api-docs-d1659c50-76e9-4e0a-b429-4347233f080d.json
- change/@fluentui-azure-themes-ad916a35-fafb-44fb-8146-eae3f631af64.json
- change/@fluentui-codemods-84ba2358-c928-44f9-a0a8-987869767fa7.json
- change/@fluentui-public-docsite-21c89b07-d902-4b72-8d4e-991ea3e68bb8.json
- change/@fluentui-public-docsite-resources-3e2adea5-6208-46de-8183-2b86a8884a5f.json
- change/@fluentui-react-8ef9a74a-4944-45ac-be35-70173e5d4d39.json
- change/@fluentui-react-docsite-components-3c77d1e9-e22b-4793-81b5-b18a870c9eec.json
- change/@fluentui-react-examples-8f3a37fc-1612-4157-9d43-0bc0e6a786eb.json
- change/@fluentui-react-experiments-97f1421a-3bac-4ba1-bf37-5411849b8a3c.json
- change/@fluentui-react-icon-provider-13250591-74fe-4dd2-9f08-831c9582b3c4.json
- change/@fluentui-react-icons-mdl2-0148d40a-3672-49b6-ab25-27dc6b851672.json
- change/@fluentui-react-tabs-16e183c3-85e7-4d8d-a2c1-2d8be8448959.json
This change: https://github.com/microsoft/fluentui/commit/06e8eda9b5b6eefb3c3c9d34a92998e605a99e8f
Accidentally removed a number of change files. Restoring them so things are published correctly.
> Adding back accidentally removed change files.

- change/@fluentui-api-docs-2021-02-11-15-12-52-removeCardFromWebsite.json
- change/@fluentui-public-docsite-98e47bb5-b8a2-414b-b1ed-a9ee4fa5b61a.json
- change/@fluentui-public-docsite-resources-76be64a0-ca63-4638-9879-89953deaa062.json
- change/@fluentui-react-examples-3c9d1b81-3cec-48f0-be24-0748a6a923d8.json
- change/@fluentui-react-examples-d3e36918-e435-4045-a19e-0cf17226f2a3.json
This PR fixes some wrong change file types that got mistakenly updated in a merge.
> Fixing wrong file type in change file

- rfcs/convergence/focus-and-iteration-towers-2.0.md
_contributors: @khmakoto @xugao @miroslavstastny @jurokapsiar @dzearing @levithomason @paulgildea_
Since this RFC has useful context/history I'm pulling this over from #15929. I don't think this is particular contentious and I don't intend to leave this open for long. We have a few conversations going already on the implementation of these ideas.
In particular @layershifter 's questions over here: https://github.com/microsoft/fluentui/issues/15929#issuecomment-754001698 should be resolved. I think we are tackling most of the outstanding issues [with this work (16372)](https://github.com/microsoft/fluentui/issues/16372). If there are other technical concerns we need settle in order to start convergence let's make sure to get issues added to the [Feb …
> Increasing focus and iteration speed in convergence - Lean the Towers v2.0

- change/office-ui-fabric-react-2021-02-12-18-15-57-16878-v7.json
- packages/office-ui-fabric-react/src/components/Persona/PersonaCoin/PersonaCoin.base.tsx
- wrapped `mergeStyles` call in PersonaCoin with `memoizeFunction`.
> [v7.0] PersonaCoin: mergeStyles function is now memoized to prevent repeated calls on every render 

- packages/fluentui/ability-attributes/schema.json
- packages/fluentui/accessibility/src/behaviors/Button/buttonBehavior.ts
Before there were a11y errors related to the schema:
Now after the fix looks clean:
> Fix disabled focusable button schema

- azure-pipelines.release-fluentui.yml
> chore: update fluentui nightly build time to 5am Prague time

- change/@fluentui-react-menu-dcc14691-488b-4ea2-b732-3bbec4587d99.json
- packages/react-menu/src/components/MenuDivider/useMenuDividerStyles.ts
- packages/react-menu/src/components/MenuGroupHeader/useMenuGroupHeaderStyles.ts
Fixes prettier issues in `react-menu` that weren't caught (cause fixed in #17009)
(optional)
> Prettier issues

- change/@fluentui-react-2021-02-03-15-41-17-dropdown-multiselect-focus.json
- packages/react/src/components/Dropdown/Dropdown.styles.ts
Dropdown remove outline offset from focused multiselect item.
(optional)
> Dropdown multiselect focus

- scripts/create-package/plop-templates-node/package.json.hbs
- scripts/create-package/plop-templates-react/package.json.hbs
- ~[] Include a change request file using `$ yarn change`~
(optional)
> chore(scripts): remove jest deps from templates npm deps as they use single version policy

- change/@fluentui-make-styles-07fd37f8-a2c9-4fc6-ba56-6053498cd729.json
- package.json
- packages/fluentui/docs-components/src/CodeSnippet/formatCode.ts
- packages/fluentui/react-bindings/test/hooks/useCSS-test.tsx
- packages/fluentui/react-northstar-emotion-renderer/test/emotionRenderer-test.ts
- packages/make-styles/src/utils/test/snapshotSerializer.ts
- yarn.lock
Add a dep on the prettier typings and remove ts-ignores for prettier.
> Add typings for prettier

- change/@fluentui-react-file-type-icons-2021-01-19-12-06-55-caperez-update_filetype_cdn_version_v8.json
- packages/react-file-type-icons/src/initializeFileTypeIcons.tsx
> update filetype cdn version v8

- packages/fluentui/CHANGELOG.md
Fixing the changelog - moving docsite changes to proper location.
> Moving docs changes to proper location

- rfcs/README.md
@ecraig12345, @levithomason, @Hotell, and many more. I captured what we discussed in the Spec review office hours regarding RFC process and review/approvals. 
I also fleshed out the process a little bit and elaborated on why RFCs 😄  
Feedback and improvements are welcome! ❤️
> Update RFC README.md

- packages/fluentui/CHANGELOG.md
> chore(Changelog): remove dup entry

- yarn.lock
> chore(yarn): update lock

- packages/react-conformance/package.json
Making @fluentui/react-conformance package private to stop publishing it from v7 so that can be published it in V8.
> Make @fluentui/react-conformance private

- change/@fluentui-react-icons-mdl2-branded-99ccf1ef-1d38-4fa8-88c9-c70a93451190.json
- packages/react-icons-mdl2-branded/package.json
> Fix syncpack issues in react-icons-mdl2

- change/@fluentui-react-experiments-51638da7-a2a4-4d41-8d6b-5551f8e16621.json
- packages/react-experiments/src/components/UnifiedPicker/UnifiedPicker.tsx
…nt well
Implemented keyboard shortcut for Cut (Ctrl+X / Shift+Del) and also the keyboard shortcut for Delete
Cut / Copy / Paste / Delete / Backspace
> Implement keyboard shortcut for Cut in recipient well

- apps/public-docsite/src/pages/Overviews/GetStartedPage/docs/web/GetStartedDevelopSimple.md
- change/@fluentui-public-docsite-109554e5-6359-480f-b524-de721b8e4bf8.json
> Update GetStartedDevelopSimple.md (cherry-pick #16366)

- .github/CODEOWNERS
- scripts/fluentui-publish/index.ts
As title. The current fluent ui publish script for running `yarn syncpack:fix` and commit changes is wrong :(
(optional)
> chore: fix pipeline post publish script for committing syncpack change

- change/@fluentui-react-charting-9a3bf474-2ad5-4e8f-af58-bc3a6fd61908.json
- change/@fluentui-react-examples-319a80fa-8828-4235-923a-192403a827a0.json
- packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx
- packages/react-charting/src/components/CommonComponents/CartesianChart.styles.ts
- packages/react-charting/src/components/CommonComponents/CartesianChart.types.ts
- packages/react-charting/src/components/Legends/Legends.base.tsx
- packages/react-charting/src/components/Legends/Legends.styles.ts
- packages/react-charting/src/components/Legends/Legends.types.ts
- packages/react-charting/src/components/Legends/index.ts
- packages/react-charting/src/components/Legends/shape.tsx
- packages/react-charting/src/components/LineChart/LineChart.base.tsx
- packages/react-charting/src/components/LineChart/LineChart.types.ts
- packages/react-charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
- packages/react-charting/src/utilities/utilities.ts
- packages/react-examples/src/react-charting/LineChart/LineChart.Basic.Example.tsx
- packages/react-examples/src/react-charting/LineChart/LineChart.Events.Example.tsx
- packages/react-examples/src/react-charting/LineChart/LineChart.Multiple.Example.tsx
introduction new feature where each line will get unique shape so that we can distinguish the line apart from the color.
made this feature backward compatible with the help of prop `allowMultipleShapesForPoints` we can  turn this feature on and off
line chart.
legends
**after fix photos**
> User/v sivsar/legendes shapes for a11y 1

- change/@fluentui-azure-themes-b7cdb048-34e6-48aa-b43f-ef08c3ba220b.json
- packages/azure-themes/src/azure/AzureColors.ts
- packages/azure-themes/src/azure/styles/PrimaryButton.styles.ts
> fix(v8): AzureTheme: Primary Button for Dark Theme alignment

- change/@fluentui-react-experiments-6eb11be4-bbd9-4277-a71b-3ca7f0693c88.json
- packages/react-experiments/src/components/TilesList/TilesList.tsx
> fix(v8): Ensure all <div> elements in TilesList have role assigned

- change/@fluentui-react-de943561-e1cf-40f0-857d-16bd87258483.json
- change/@fluentui-react-examples-3ca2a8f2-6fa8-4558-894a-95ab5b9cb66f.json
- packages/react-examples/src/react/__snapshots__/DetailsList.DragDrop.Example.tsx.shot
- packages/react/src/components/DetailsList/DetailsHeader.base.tsx
- packages/react/src/components/DetailsList/DetailsHeader.test.tsx
Cherry pick of #16014 for release in v8
> Prevent '.ms-Icon' style overrides from conflicting with the "Move column" target (cherry-pick #16014)

- scripts/create-component/plop-templates-component/src/components/{{componentName}}/use{{componentName}}.ts.hbs
- scripts/create-component/plop-templates-component/src/components/{{componentName}}/use{{componentName}}Styles.ts.hbs
- scripts/create-component/plop-templates-component/src/components/{{componentName}}/{{componentName}}.tsx.hbs
- scripts/create-component/plop-templates-component/src/components/{{componentName}}/{{componentName}}.types.ts.hbs
- scripts/create-component/plop-templates-storybook/{{componentName}}.stories.tsx.hbs
Small tweaks/cleanup to the create-component script templates
> Update create-component template files

- .github/CODEOWNERS
* Update codeowners for create-package and create-component
* Add codeowner for react-avatar and react-tooltip
> Add codeowners for create-package and create-component

- change/@fluentui-codemods-2021-02-05-08-44-28-enable-repath-fluent-codemod.json
- packages/codemods/src/codeMods/mods/officeToFluentImport/officeToFluentImport.mod.ts
Since react-internal is moving into react, it is safe to re-enable this codemod.
(optional)
> Codemods: Enable repath fluent

- change/@fluentui-react-e5d1be67-d777-42f2-ab64-a7b07f4f746f.json
- packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx
Fix https://github.com/microsoft/fluentui/issues/16901
Checked that the menu read out x of x
> Add menu role internally to the menu section item

- change/@fluentui-react-examples-1307ccd0-712a-4ea9-a011-0b3e08358ec8.json
- packages/react-examples/.storybook/main.js
- packages/react-examples/.storybook/preview.js
- packages/react-examples/src/react-components/FluentUIComponents/Introduction.stories.mdx
- packages/react-examples/src/react-components/FluentUIComponents/QuickStart.stories.mdx
- packages/storybook/package.json
- yarn.lock
Replaces #17218 since I cannot push to that branch.
> docs(react-component): Add mdx docs to storybook

- package.json
- packages/fluentui/projects-test/package.json
- yarn.lock
> Update Lerna to fix security vulnerability.

- .github/CODEOWNERS
Updating CODEOWNERS to remove Xu's ownership. 
Redistributed ownership amongst 
- @dzearing  (Theming/Styling)
- @khmakoto (components)
- @behowell (components)
- @kubkon (perf)
- @Hotell (build)
Need to distribute out ownership. We will need to establish more structured ownership in the future, so consider this likely to be a temporary measure.
> Update CODEOWNERS to redistribute Xu's items

- change/office-ui-fabric-react-7c81fa5a-cfc2-4d7b-8a92-fe49d8fe8d3e.json
- packages/office-ui-fabric-react/src/components/Stack/Stack.tsx
- packages/office-ui-fabric-react/src/components/Stack/StackItem/StackItem.tsx
- packages/office-ui-fabric-react/src/components/Text/Text.view.tsx
cherry pick of [Stack/Text: Add jsxRuntime classic pragma](https://github.com/microsoft/fluentui/pull/16863) for v7.0
> Cherry Pick: Stack: Add jsxRuntime classic pragma #16863

- scripts/gulp/tasks/test-e2e.ts
Port for e2e tests is wrongly set
e2e tests
> Cypress port fix

- change/@fluentui-react-36237d62-d65c-41da-a377-5ba024c85269.json
- packages/react/src/components/Dropdown/Dropdown.test.tsx
- packages/react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Pass an explicit `dropdownWidth` to prevent inconsistency in Dropdown snapshots.
> Dropdown: fix intermittent test failure

- apps/fabric-website/src/styles/_base.scss
- common/changes/@uifabric/fabric-website/5.0_2021-03-10-19-26.json
> Docsite: style changes in prep for MWF for v5

- apps/fabric-website/src/components/Site/Site.module.scss
- change/@uifabric-fabric-website-2021-03-10-11-01-51-mwf-v6.json
> Docsite: styles for MWF stylesheet removal for v6.0

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams-dark/colors.ts
- packages/fluentui/react-northstar/src/themes/teams-high-contrast/colors.ts
- packages/fluentui/react-northstar/src/themes/teams/colors.ts
> Adding color slot: borderActive4

- rfcs/convergence/popper-js.md
This RFC proposes the use of the OSS library [popper](https://popper.js.org/docs/v2/modifiers/prevent-overflow/) in the convergence effort
(optional)
> RFC: Integrate Popper into Fluent

- change/@uifabric-azure-themes-2021-03-01-09-34-59-dark.json
- packages/azure-themes/src/azure/AzureColors.ts
- packages/azure-themes/src/azure/AzureThemeDark.ts
- packages/azure-themes/src/azure/IAzureSemanticColors.ts
- packages/azure-themes/src/azure/IExtendedSemanticColors.ts
- packages/azure-themes/src/azure/styles/DefaultButton.styles.ts
- IAzureSemanticColors.ts 
- Added focus.border to secondaryButton 
- IExtendedSemanticColors.ts 
-  Added ButtonBorderFocus 
- AzureColors.ts 
- Added GRAY_FAF9F8 
- Dark 
- SecondaryButton 
- Rest 
- Background: GRAY_111111 -> GRAY_1B1A19 
- Border: GRAY_979693-> GRAY_8A8886 
- Text: WHITE -> GRAY_F3F2F1 
- Hover 
- Color: WHITE -> GRAY_FAF9F8 
- Pressed 
-Text: WHITE -> GRAY_FAF9F8 
- Added focus 
- Light 
- SecondaryButton 
- Added focus 
- High Contrast Dark 
- SecondaryButton 
- Added focus 
- High Contrast Light 
- Secondary Button 
- Added focus 
- AzureThemeDark.ts 
- Added ButtonBorderFocus 
- DefaultButton.styles.ts 
- RootFocusted 
- Added inner border on focus 
- RootHovered 
- Took border away 
- This fixed both light and dark mode 
- RootPressed 
- Took border away 
- This …
> Dark Theme Default Button Update

- change/@fluentui-react-button-d680055b-9331-41dc-bf21-1441e08a8590.json
- packages/react-button/src/components/Button/useButtonStyles.ts
> Button - Updates styles from makeStylesCompat to makeStyles

- change/@fluentui-react-badge-844cefc4-c97a-4e54-9359-73fe45c97db4.json
- packages/react-badge/etc/react-badge.api.md
- packages/react-badge/src/components/Badge/useBadgeStyles.ts
- packages/react-badge/src/components/CounterBadge/__snapshots__/CounterBadge.test.tsx.snap
> Badge - Updates styles from makeStylesCompat to makeStyles

- change/@fluentui-react-utilities-9736763b-6b16-4d2d-964c-4b7530844475.json
- packages/react-utilities/README.md
- packages/react-utilities/src/compose/README.md
~~- [ ] Addresses an existing issue: Fixes #0000~~
This PR restores `README.md` file that describes components' hooks and compose utils. It was deleted by an accident in #16970, thanks to @JustSlone for pointing out this problem 👍
> docs: restore README for compose utils

- change/@fluentui-react-flex-b67e48eb-f824-48ec-a5ec-5212d250f586.json
- packages/react-flex/src/components/Flex/useFlexStyles.ts
> react-flex- Updates styles from makeStylesCompat to makeStyles

- change/@fluentui-react-badge-d8991dcf-068c-466f-8760-ba6a9fde0dcb.json
- packages/react-badge/etc/react-badge.api.md
- packages/react-badge/src/components/CounterBadge/useCounterBadgeStyles.ts
> CounterBadge - Updates styles from makeStylesCompat to makeStyles

- change/@fluentui-react-docsite-components-8a950f38-23e4-4933-9329-e47a5b63fee9.json
- change/@uifabric-example-app-base-15cd2aa8-d279-4000-8e0c-70c5cc7d0899.json
- packages/example-app-base/src/components/ApiReferencesTable/ApiReferencesTable.tsx
cherry-pick of https://github.com/microsoft/fluentui/pull/17420 for v7
> Add accessible names to docs site API tables for v7

- change/@fluentui-react-da054f50-18da-4838-95d8-52da1ba3e46c.json
- packages/react/src/components/Rating/Rating.base.tsx
> Rating: Enable bidirectional keyboarding

- change/@fluentui-react-9db5ec8b-0749-40f4-b1de-5b7748c2d3fb.json
- change/@fluentui-react-examples-d73c2e33-6174-45bb-a4e7-8c8dab935c72.json
- packages/react-examples/src/react/__snapshots__/Announced.LazyLoading.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/ProgressIndicator.Basic.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/ProgressIndicator.Indeterminate.Example.tsx.shot
- packages/react/etc/react.api.md
- packages/react/src/components/ProgressIndicator/ProgressIndicator.base.tsx
- packages/react/src/components/ProgressIndicator/__snapshots__/ProgressIndicator.test.tsx.snap
This PR derives the `aria-labelledby` and `aria-describedby` aria attributes for `ProgressIndicator` based on the `label` and `description` props passed to it.
> ProgressIndicator: Deriving aria-labelledby and aria-describedby

- apps/fabric-website/src/SiteDefinition/SiteDefinition.tsx
- apps/fabric-website/src/pages/Controls/ControlsAreaPage.tsx
- apps/fabric-website/src/pages/HomePage/HomePage.base.tsx
- apps/fabric-website/src/pages/Overviews/ControlsPage/ControlsPage.tsx
- change/@uifabric-example-app-base-0eabe1e2-aeab-4d6f-b4ab-058bc2b063b1.json
- change/@uifabric-fabric-website-b11e215c-d200-43b2-9ea7-fc20f2e8a91f.json
- change/@uifabric-styling-8f31cf46-7c69-42b6-a143-be399c60ac65.json
- packages/example-app-base/src/components/LoadingComponent/LoadingComponent.tsx
- packages/example-app-base/src/components/LoadingComponent/LoadingComponent.types.ts
- packages/example-app-base/src/components/Page/Page.tsx
- packages/example-app-base/src/components/Page/Page.types.ts
- packages/example-app-base/src/components/PageHeader/PageHeader.tsx
- packages/example-app-base/src/components/PageHeader/PageHeader.types.ts
- packages/example-app-base/src/styles/constants.ts
- packages/example-app-base/src/utilities/SiteDefinition.types.ts
- packages/styling/etc/styling.api.md
- packages/styling/src/styles/CommonStyles.ts
Cherry-pick of #15917: add a version switcher to the v7 website.
> Website: add version switcher in v7 site

- .github/CODEOWNERS
First step for using scoped team ownership instead of individuals
(optional)
> chore: use github teams for ownership

- apps/vr-tests/src/stories/z_Callout.stories.tsx
`Callout`: Replace visual regression test of `Callout` attached to an iframe to one where the `Callout` is attached to a rectangle.
> Callout: Replace visual regression test of Callout attached to an iframe to one where the Callout is attached to a rectangle

- change/@fluentui-react-menu-f6f5cf87-240e-46ee-800a-a79deffab5e2.json
- packages/react-menu/etc/react-menu.api.md
- packages/react-menu/src/components/Menu/useMenuStyles.ts
- packages/react-menu/src/components/MenuDivider/useMenuDividerStyles.ts
- packages/react-menu/src/components/MenuGroupHeader/useMenuGroupHeaderStyles.ts
- packages/react-menu/src/components/MenuItem/useMenuItemStyles.ts
- packages/react-menu/src/selectable/useCheckmarkStyles.ts
> react-menu - Updates styles from makeStylesCompat to makeStyles

- change/@fluentui-react-link-b387cac3-b369-4ddb-9086-84ebb69a5025.json
- packages/react-link/src/components/Link/useLinkStyles.ts
> react-link - Updates styles from makeStylesCompat to makeStyles

- change/@fluentui-azure-themes-06084aba-b448-4c1b-a821-44cbb38e8ff8.json
- change/@fluentui-react-examples-3af40091-ef18-4364-a4a9-916346d7d828.json
- packages/azure-themes/src/azure/AzureStyleSettings.ts
- packages/azure-themes/src/azure/styles/Tooltip.styles.ts
- packages/react-examples/src/azure-themes/stories/Themes/Themes.stories.tsx
- packages/react-examples/src/azure-themes/stories/components/tooltip.stories.tsx
- [ x ] Include a change request file using `$ yarn change`
Cherry Pick of #17493
(optional)
> Cherry Pick "Tooltip azure style #17493"

- change/@fluentui-react-text-ad06cd87-9155-49ad-b020-f64f89200e0f.json
- packages/react-text/src/components/Text/useTextStyles.ts
> react-text - Updates styles from makeStylesCompat to makeStyles

- change/@fluentui-react-badge-573a2e4d-377b-494b-9837-fde8b864283d.json
- packages/react-badge/etc/react-badge.api.md
- packages/react-badge/src/components/PresenceBadge/DefaultPresenceBadgeIcons.tsx
- packages/react-badge/src/components/PresenceBadge/__snapshots__/PresenceBadge.test.tsx.snap
- packages/react-badge/src/components/PresenceBadge/usePresenceBadgeStyles.ts
> react-badge - Updates styles from makeStylesCompat to makeStyles

- change/@fluentui-react-examples-98100a6e-20e0-4f27-a6ac-b2f144542ef6.json
- packages/react-examples/src/react-avatar/Avatar/Avatar.stories.tsx
- packages/react-examples/src/react-avatar/utils/StoryExample.tsx
- packages/react-examples/src/react-divider/Divider/Divider.stories.tsx
- packages/react-examples/src/react-make-styles/MakeStylesCompat/Basic.stories.tsx
- packages/react-examples/src/react-menu/MenuList/MenuList.stories.tsx
> react-examples - Updates styles from makeStylesCompat to makeStyles

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Alert/AlertDismissAction.tsx
> fix(Alert): add success to AlertDismissAction propTypes

- change/@fluentui-react-components-54d685cf-ca44-4a7e-8df0-a140e123bb42.json
- packages/react-components/etc/react-components.api.md
- packages/react-components/package.json
- packages/react-components/src/index.ts
- Adds `@fluentui/react-divider` component as dependency to `@fluentui/react-components`
- Re-export all from `@fluentui/react-divider`
> Adds react-divider to component suite package

- apps/test-bundles/webpack.config.js
- apps/test-bundles/webpackUtils.js
- azure-pipelines.bundlesize.yml
This PR adds `@fluentui/react-components` to Size Auditor checks i.e. introduces bundle size gates.
> chore: add @fluentui/react-components to size-auditor

- packages/fluentui/CHANGELOG.md
- packages/fluentui/docs/src/examples/components/Pill/Variations/PillExampleIcon.tsx
- packages/fluentui/docs/src/examples/components/Pill/Variations/PillExampleImage.tsx
- packages/fluentui/docs/src/examples/components/Pill/Variations/index.tsx
- packages/fluentui/react-northstar/src/components/Pill/Pill.tsx
- packages/fluentui/react-northstar/src/components/Pill/PillIcon.tsx
- packages/fluentui/react-northstar/src/components/Pill/PillImage.tsx
- packages/fluentui/react-northstar/src/index.ts
- packages/fluentui/react-northstar/src/themes/teams/componentStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/componentVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Pill/pillIconStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Pill/pillImageStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Pill/pillVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/types.ts
Add `PillImage` and `PillIcon` component and example
(optional)
> feat(Pill): add PillImage and PillIcon component

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-bindings/src/styles/resolveStyles.ts
This PR improves memory usage for Northstar components 📈
In `useStyles()` hook we have lazy evaluation of styles for slots: "icon" slot is not used during render, so styles for this slot will not be executed at all. This lazy evaluation is done via getters (`Object.defineProperty`) on `classes` & `styles` objects:
```tsx
Object.defineProperty(classes, slotName, {
get() {
/* ... */
}
});
```
However, the recent finding are showing that it's not the most efficient way for memory consumption. In our synthetic test there is a noticeable difference 😲
**`useStyles()` with `Proxy`**
**`useStyles()` with `Object.defineProperties`**
In terms of performance there is no difference between approaches:
| Example                                              | min    | avg    | median | max    |
| …
> perf: use Proxy in useStyles

- change/@fluentui-react-2021-03-31-14-30-55-keytip-memo.json
- packages/react/src/components/KeytipData/useKeytipRef.ts
Wrap useKeytipRef with useCallback
> Memoize useKeytipRef - fixes #17654

- change/office-ui-fabric-react-2021-03-31-14-38-19-keytip-memo-7.json
- packages/office-ui-fabric-react/src/components/KeytipData/useKeytipRef.ts
Wrap useKeytipRef with useCallback
Corresponding v8.0 change: https://github.com/microsoft/fluentui/pull/17655
> Memoize useKeytipRef - fixes #17654 in v7

- apps/fabric-website/package.json
- apps/fabric-website/webpack.config.js
- apps/fabric-website/webpack.serve.config.js
- change/@uifabric-example-app-base-fc8ee7ec-56eb-413e-86a8-a5f80d8b7636.json
- change/@uifabric-fabric-website-92159cf1-c85f-4242-a4ff-89202497b6ea.json
- packages/example-app-base/package.json
- yarn.lock
Pick up fix from #17660. This fix isn't actually needed in v7 but it's good to keep the version consistent.
> Update shared website setup package

- apps/fabric-website/package.json
- apps/fabric-website/webpack.config.js
- apps/fabric-website/webpack.serve.config.js
- change/@uifabric-example-app-base-38f17eff-57e8-425e-b2f8-8c8ef4348ec7.json
- change/@uifabric-fabric-website-21dc1cbe-4c72-4a73-bc4b-cf4444e28e22.json
- packages/example-app-base/package.json
- yarn.lock
Picking up shared website setup package changes from #17672 in master. This change isn't actually needed for 7.0, but keeping it in sync is good.
> Update version of shared website setup package again

- change/@fluentui-react-examples-4c0cd7ec-9044-4f86-934a-fa23ebad6cc1.json
- change/office-ui-fabric-react-e1d17d42-d71e-4e9c-a43c-9d1133915a70.json
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx
- packages/office-ui-fabric-react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/ChoiceGroup.Custom.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DatePicker.Basic.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DatePicker.WeekNumbers.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Dropdown.Basic.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Dropdown.Controlled.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Dropdown.ControlledMulti.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Dropdown.Custom.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Dropdown.Error.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Dropdown.Required.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Facepile.Basic.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Facepile.Overflow.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/ResizeGroup.OverflowSet.Example.tsx.shot
> Accessibility fix for Dropdown, v7

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams-dark/colors.ts
- packages/fluentui/react-northstar/src/themes/teams-high-contrast/colors.ts
- packages/fluentui/react-northstar/src/themes/teams/colors.ts
> Chore: adding new color tokens for Fluid

- apps/test-bundles/webpackUtils.js
This PR:
- adds `Menu` & `useFluent` exports to be tested with SizeAuditor
- fixes export name for `FluentProvider`
> chore: update entries for converged components in SA

- apps/test-bundles/webpackUtils.js
Adding `CompoundButton` and `ToggleButton` as part of the converged components to check for bundle size increases.
Check that `CompoundButton` and `ToggleButton` appear in size auditor checks.
> Adding CompoundButton and ToggleButton as part of the converged components to check for bundle size increases

- change/@fluentui-react-aa9d1a55-2458-4aca-acc5-95df8f332292.json
- packages/react/src/components/WeeklyDayPicker/WeeklyDayPicker.types.ts
A tiny fix for tsdoc for WeeklyDayPicker
> Tiny fix for doc in WeeklyDayPicker types

- apps/vr-tests/screener.local.config.js
> Remove key

- apps/vr-tests/screener.local.config.js
> Remove key v7

- apps/vr-tests/screener.local.config.js
> Remove key v6

- apps/vr-tests/screener.local.config.js
> Remove key v5

- apps/vr-tests/screener.local.config.js
> Remove key v4

- scripts/tasks/postprocess-amd.ts
Add handling for a couple more types of conditions that I missed in the previous PR.
> Fix AMD postprocessing

- change/@fluentui-react-add0d7da-c545-411f-b148-064f31c7afd6.json
- change/@fluentui-react-examples-023dba96-b0aa-4721-b834-981526f4d71b.json
- change/@fluentui-utilities-4bb0fe0a-faed-4b06-b6a7-b5ee4cc6961c.json
- packages/react-examples/src/react-experiments/Persona/Persona.Example.tsx
- packages/react-examples/src/react/Persona/Persona.Initials.Example.tsx
- packages/react-examples/src/react/__snapshots__/Persona.Initials.Example.tsx.shot
- packages/react/src/components/Persona/Persona.test.tsx
- packages/utilities/src/initials.test.ts
- packages/utilities/src/initials.ts
Account for email addresses between angled brackets in the display name. Do not want to use the email address to calculate the Display Name initials.
Display names with email addresses between () and {} and [] and <>, and display names without email addresses in the display name itself.
> Recipient pill initials

- packages/fluentui/react-northstar/src/components/Avatar/Avatar.tsx
- packages/fluentui/react-northstar/src/components/Avatar/AvatarImage.tsx
- packages/fluentui/react-northstar/src/themes/teams/types.ts
Added `AvatarImageStylesProps` and `AvatarStatusStylesProps` to `theme/types`. 
Added missing `size` prop to `AvatarImage`
(optional)
> fix(Avatar): fix Avatar* styles types and props

- change/@fluentui-react-components-491333e4-9f80-451f-8147-14c3023c908e.json
- packages/react-components/etc/react-components.api.md
- packages/react-components/package.json
- packages/react-components/src/index.ts
Add `react-accordion` to `react-component` for intial release
> Initial Release react-accordion

- packages/react-portal/package.json
> Fix dependency mismatch

- change/@fluentui-azure-themes-8761d6f8-3e22-4afb-a6fb-70b84f1f97b2.json
- packages/azure-themes/src/azure/AzureColors.ts
- packages/azure-themes/src/azure/styles/DropDown.styles.ts
AzureColors.ts
- Added GRAY_3B3A39
- Dark
- text
- error: Changed
- item
- hover: Changed
- selected: Changed
DropDown.styles.ts
Changes Below
- Change
- Color: RED_F63747 -> RED_F1707B
Before: 
After: 
- Change
- BackgroundColor
- Change
- BorderColor
- Placeholder
- Color
- Content
- Color
Before: 
After: 
- Change
- Color
Before: 
After: 
- Change
- BorderColor
- Color
Before: 
After: 
Before: 
After: 
- Change
- BackgroundColor
Before: 
After: 
- Change
- BackgroundColor
Before: 
After: 
- Change
- BackgroundColor
- Color
Before: 
After: 
- Change
- Color
Before: 
After: 
- Change
- Color
Before: 
After: 
Order: Selected, Hover, Disabled, Rest
All
- Change
- BackgroundColor
Before: 
After:
> Azure Theme Dropdown dark theme

- change/@fluentui-azure-themes-12d95ecd-2c77-4b6c-9238-cd192df49f30.json
- packages/azure-themes/src/azure/AzureColors.ts
- packages/azure-themes/src/azure/AzureThemeDark.ts
- packages/azure-themes/src/azure/AzureThemeHighContrastDark.ts
- packages/azure-themes/src/azure/AzureThemeHighContrastLight.ts
- packages/azure-themes/src/azure/AzureThemeLight.ts
- packages/azure-themes/src/azure/IAzureSemanticColors.ts
- packages/azure-themes/src/azure/IExtendedSemanticColors.ts
- packages/azure-themes/src/azure/styles/ChoiceGroupOptions.styles.ts
AzureColors.ts 
- Dark
- text
- bodyHovered: White -> GRAY_FAF9F8
- controlOutlines
- disabled: GRAY_808080_070 -> GRAY_484644
- choiceGroup
- circle
- hover: BLUE_3AA0F3 -> GRAY_A19F9D
- focus: Added
- HighContrastDark
- choiceGroup
- focus: Added
- Light
- choiceGroup
- focus: Added
- HighContrastLight
- choiceGroup
- focus: Added
AzureThemeDark.ts/AzureThemeHighContrastDark.ts/AzureThemeHighContrastLight.ts/AzureThemeLight.ts 
- choiceGroupFocusBorder: Added
IAzureSemanticColors.ts
- choiceGroup
- focus: Added
IExtendedSemanticColors.ts
- choiceGroupFocusBorder: Added  
ChoiceGroupOptions.styles.ts
Changes Bellow
- added padding so focus border is 4px from info
- Changes
- Color
- Circle
- Color
Before: 
After: 
- Changes
- Color
- Dot
- Color
- Circle
- Color
Before: 
After: 
- …
> Azure Themes Choice Group Dark

- change/@fluentui-react-components-18814828-6288-4726-8c32-16a673855f47.json
- packages/react-components/etc/react-components.api.md
- packages/react-components/package.json
- packages/react-components/src/index.ts
Export `Badge` in react-components.
> feat(react-components): Export Badge

- change/@fluentui-react-experiments-0c59de66-3908-4141-92bd-cb6afd653dd8.json
- packages/react-experiments/src/components/UnifiedPicker/UnifiedPicker.tsx
- packages/react-experiments/src/components/UnifiedPicker/hooks/useSelectedItems.ts
- Add a hook to select all of the selected items
- catch ctrl-a in onKeyDown in UnifiedPicker and call that function
> UnifiedPicker: Add select all

- change/@fluentui-react-utilities-f9b803d4-3649-4330-b4de-0af4818622ce.json
- packages/react-utilities/etc/react-utilities.api.md
- packages/react-utilities/src/hooks/useOnClickOutside.ts
Fixes SSR warnings in #17899
(optional)
> Remove default `document` in `useOnClickOutside`

- .github/CODEOWNERS
Reassign joschect's owned items to a temporary team while we work out a larger change to codeowners
> Reassign joschect's owned items

- apps/test-bundles/webpackUtils.js
> Add `Accordion` to size auditor

- change/@fluentui-react-b4b36946-39a4-4bf7-a1c8-28cc1157f37b.json
- packages/react/src/components/Slider/useSlider.ts
Cherrypick changes to the Slider component to v8
(optional)
> Fix Slider to trigger onChanged for Home and End keys

- change/office-ui-fabric-react-2021-04-26-13-35-08-panel-dismiss-bug-cherrypick.json
- packages/office-ui-fabric-react/src/components/Panel/Panel.base.tsx
Cherrypick Panel dismiss bug fix changes to v7
(optional)
> cherrypick hidden panel on dismiss bug to v7

- change/@fluentui-react-tabster-2f67d3ed-9b3c-413f-931f-7839326e6045.json
- packages/react-tabster/etc/react-tabster.api.md
- packages/react-tabster/package.json
- packages/react-tabster/src/hooks/useTabsterAttributes.ts
- yarn.lock
> chore: bump tabster in react-tabster

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-icons-northstar/src/components/FilesOneNoteIcon.tsx
- packages/fluentui/react-icons-northstar/src/index.ts
> Added FilesOneNoteIcon

- change/@fluentui-react-theme-provider-42d79dc0-960a-48ba-b7f4-8cc7e0f74f0e.json
- packages/react-theme-provider/src/components/ThemeProvider/useThemeProvider.test.tsx
- packages/react-theme-provider/src/components/ThemeProvider/useThemeProvider.ts
This PR fixes an issue with theme merging, currently we will pass an inner theme down without any merge 😥
https://codesandbox.io/s/fervent-http-jtniu?file=/src/App.tsx
> fix(ThemeProvider): fix theme merging

- packages/fluentui/react-northstar/src/components/List/List.tsx
only doc site added to  accessibility tab like:
> Documentation - adding screen reader bugs related to `List`

- change/@fluentui-babel-make-styles-50c9cbc3-3d69-4624-b787-192a7dac29a7.json
- packages/babel-make-styles/__fixtures__/compiled-optional-chaining/code.ts
- packages/babel-make-styles/__fixtures__/compiled-optional-chaining/output.ts
- packages/babel-make-styles/src/utils/evaluatePathsInVM.ts
This PR temporary disables hoisting for a Babel plugin as it breaks styles resolution in few cases. I added a fixture that reproduces a problem to fix it later.
> fix(babel-make-styles): temporary disable hoisting

- change/@fluentui-react-examples-43086bcb-5db8-4f0d-aac6-998649de38ba.json
- change/@fluentui-react-experiments-ef903c06-1f9c-4ec6-8207-a6c09d4023be.json
- packages/react-examples/src/react-experiments/UnifiedPeoplePicker/UnifiedPeoplePicker.WithEdit.Example.tsx
- packages/react-experiments/src/components/SelectedItemsList/SelectedItemsList.tsx
- add a null and undefined check to the replace function so that we don't try to add these
- add a case to one of the examples to test this
> SelectedItemsList: Don't try to replace with null or undefined item

- packages/fluentui/CHANGELOG.md
> chore: update changelog for N*

- rfcs/theme-tokens.md
> rfc: Converged theme component tokens

- packages/fluentui/CHANGELOG.md
Add changelog missed related to #17956 
(optional)
> chore: add missing changelog entry

- packages/fluentui/CHANGELOG.md
- packages/fluentui/accessibility/src/behaviors/Pill/pillBehavior.ts
- packages/fluentui/react-northstar/src/components/Pill/Pill.tsx
Actionable `Pill` were missing keyboard handling, this PR adds `performClick` to `pillBehavior` 
(optional)
> chore(Pill): add keyboard perfomClick

- change/@fluentui-react-menu-0923f2e3-dc91-4ffc-ae58-6602a5d5f633.json
- change/@fluentui-react-menu-458b438b-346f-4f5f-bcb5-2648bc13a0f3.json
- packages/react-menu/src/Menu.stories.tsx
Improves the readability of the code example for nested submenu
(optional)
> chore(Menu): Improve nested menu story

- packages/fluentui/docs/src/examples/components/Pill/BestPractices/PillBestPractices.tsx
Add new Best Practice for `PillGroup` instructing to use `aria-multiselectable` when more than one `Pill` is selectable
(optional)
> chore(PillGroup): add best practice 

- .github/CODEOWNERS
Now that there are determined crews and review groups, sets the
@teams-prg review group as owner for `react-menu`
(optional)
> chore(Menu): Update CODEOWNERS file

- packages/fluentui/CHANGELOG.md
- packages/fluentui/accessibility/src/behaviors/Pill/pillBehavior.ts
Add support for selection with space for selectable `Pill`
(optional)
> fix(PillBehavior): support selection with space key

- change/@fluentui-react-6e779b03-812d-4243-909e-4ce854d9bd64.json
- change/@fluentui-react-examples-0ce9ee2d-3e1d-49d9-83d2-02375494a16c.json
- change/@fluentui-react-toggle-9fffbc76-69e5-48f2-bf06-d2152072e01c.json
- packages/react-examples/src/react-tabs/__snapshots__/Tabs.AlwaysRender.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DetailsList.Grouped.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/Layer.Basic.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/Layer.Customized.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/Layer.Hosted.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/Pivot.AlwaysRender.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/TextField.ErrorMessage.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/Toggle.Basic.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/Toggle.CustomLabel.Example.tsx.shot
- packages/react-toggle/src/components/Toggle/Toggle.scss
- packages/react/src/components/Toggle/Toggle.styles.ts
- packages/react/src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
Continue the work done in #1630 to use break-word in more places
Similar to #1630 and #10994
> Break between words of inlineLabel of Toggle  

- change/office-ui-fabric-react-051c8b54-551f-44a8-8c6c-e94a0e421fe3.json
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
Port of #18132 to v7 by request
> fix(Combobox):  remove option aria-label for v7

- .github/CODEOWNERS
Add `@cxe-red` to CODEOWNERS for packages that are owned by one of the members of the crew.
> Update CODEOWNERS to include cxe-red

- change/@fluentui-react-ef007003-8eb0-4f9c-9f4d-71de8aa28b6e.json
- change/@fluentui-react-tabs-5328c68c-5b39-42af-a006-4fd2e3a2517a.json
- packages/react-tabs/src/components/Tabs/Tabs.base.tsx
- packages/react/src/components/Pivot/Pivot.base.tsx
Modified role prop of CommandButton in Pivot.Base and Tabs.Base
Reference for my changes:https://github.com/microsoft/fluentui/issues/16184#issuecomment-765029757
> Pivot: Changed role prop to incorporate link-role

- packages/fluentui/CHANGELOG.md
Add missing changelog entry related to #17782
(optional)
> chore(changelog): add missing entry 

- change/@fluentui-web-components-394d9a2e-c0a7-4064-81c7-a1db33bd7ba1.json
- packages/web-components/src/tabs/tab/tab.styles.ts
> (web-components) correct tabs font size and line height to base

- change/@fluentui-react-menu-822682bb-7ceb-4cd1-b9c1-1bacd3c443e5.json
- packages/react-menu/src/components/MenuItem/MenuItem.test.tsx
- packages/react-menu/src/components/MenuItem/useMenuItemStyles.ts
> fix(MenuItem): Don't select text with double click

- change/@fluentui-react-label-89c66f64-ce24-4fe6-a95a-d171a3597136.json
- packages/react-label/package.json
Making the react-label package public.
(optional)
> React label - Remove making package public

- .github/CODEOWNERS
- ~[ ] Addresses an existing issue: Fixes #0000~
(optional)
> chore: update codeowners for nx files

- .github/CODEOWNERS
CODEOWNERS: Mimicking structure and assignments used in master branch.
(optional)
> CODEOWNERS: Mimicking structure and assignments used in master branch

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams/components/Skeleton/utils/animations.ts
Add animations to `SkeletonText`
(optional)
> fix: add animations to SkeletonText

- packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx
> Doc - Adding JAWS dropdown bug

- azure-pipelines.release-fluentui.yml
- gulpfile.ts
- lage.config.js
- package.json
- packages/fluentui/docs/package.json
- packages/fluentui/react-bindings/package.json
- packages/fluentui/react-component-ref/package.json
- packages/fluentui/react-northstar/package.json
- scripts/gulp/tasks/docs.ts
- scripts/gulp/tasks/screener.ts
Reverts microsoft/fluentui#18263.
---
We need to tweak Lage settings before merging back:
> Revert "chore: speed up N* build"

- change/@uifabric-charting-b44397d9-fc65-462c-a2ce-1b8fee20fc17.json
- packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap
- packages/charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap
- packages/charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx
- packages/charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap
In SVG's, If we use aria-labelledby we need to add role also. To resolve Accessibility Insights for web, Added role and aria-label to the below charts.
Stacked bar chart
Multi stacked bar chart
Horizontal bar chart
Vertical bar chart
Stacked bar chart
Multi stacked bar chart
Horizontal bar chart
Vertical bar chart
> Charting: CherryPick  #18279. Accessibility aria-labelledby issue resolved in Stacked bar chart, Horizontal bar chart and Vertical bar chart.

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-bindings/src/hooks/useAutoControlled.ts
- packages/fluentui/react-bindings/test/hooks/useAutoControlled-test.tsx
Current value in the `useAutoControlled` hook was never being updated therefore function state updates where based on outdated state.
(optional)
> fix(useAutoControlled): update valueRef

- .github/CODEOWNERS
Adding react-label codeownership.
(optional)
> react-label: Updating codeowners to add react-label

- change/@fluentui-jest-serializer-make-styles-0b321544-3b6c-4892-b624-8d25504619ca.json
- change/@fluentui-react-menu-a2f9229e-9b17-4dd7-acf3-1c00e90f731e.json
- packages/fluentui/react-northstar/jest-setup.js
- packages/fluentui/react-northstar/jest.config.js
- packages/fluentui/react-northstar/test/setup.ts
- packages/fluentui/react-northstar/tsconfig.json
- packages/jest-serializer-make-styles/jest-setup.js
- packages/jest-serializer-make-styles/jest.config.js
- packages/jest-serializer-make-styles/src/index.test.tsx
- packages/jest-serializer-make-styles/tsconfig.json
- packages/react-menu/config/tests.js
- packages/react-menu/src/components/MenuItem/MenuItem.test.tsx
- packages/react-menu/tsconfig.json
- ~[ ] Addresses an existing issue: Fixes~
- unification how to setup jest-dom based on official docs and common industry practices
**Action points:** Add this setup to nx generators via prompt or by adding it later to any project within monorepo
(optional)
> chore: unify setting up jest-dom within monorepo

- change/@fluentui-react-components-f67c7b6b-ccec-4652-9b95-2ffddb51987c.json
- change/@fluentui-react-examples-ca43879c-751d-4d55-8b40-b0d806b765d1.json
- change/@fluentui-react-popover-7f60a1d5-938e-4314-aef2-95edbeb17e15.json
- packages/react-components/etc/react-components.api.md
- packages/react-components/package.json
- packages/react-components/src/index.ts
- packages/react-examples/.storybook/preview.js
- packages/react-popover/bundle-size/Popover.fixture.js
- packages/react-popover/package.json
- packages/react-popover/src/Popover.stories.tsx
* Publishes `@fluentui/react-popover`
* Exports component from `react-components`
* Create a bundle size fixture
(optional)
> feat(Popover): Publish react-popover

- change/@fluentui-react-menu-dd69fcac-4b53-45bf-adfe-2ad262dcbc61.json
- change/@fluentui-react-popover-c37c197b-c684-4d78-b1cf-f14fa9ff3640.json
- change/@fluentui-react-portal-69c993e4-e001-4480-9978-3aff984b264d.json
- packages/react-menu/src/components/MenuItem/useMenuItemStyles.ts
- packages/react-popover/tsconfig.json
- packages/react-portal/package.json
- packages/react-portal/src/components/Portal/usePortalMountNode.ts
Adds implementation of Focus indicator based on design spec for react-menu converged component
> Focus indicator implementation for react-menu

- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
- tools/types.ts
- follow up from last PR where we forgot about this one  (https://github.com/microsoft/fluentui/pull/18394)
(optional)
> feat(tools): remove package dependency from react-examples

- change/@fluentui-web-components-861ce175-84fa-4e22-a53c-fea1744825d2.json
- packages/web-components/src/select/select.styles.ts
Fixes a visual bug w/ combobox and select styles
(optional)
> (web-components) fix select style height overlap

- change/@fluentui-react-menu-4f9aab09-8da5-44ab-9310-3d59d16d93a7.json
- change/@fluentui-react-tabster-cbe4acf8-0863-40c6-b498-53940bc953de.json
- packages/react-menu/src/components/MenuItem/useMenuItemStyles.ts
- packages/react-tabster/etc/react-tabster.api.md
- packages/react-tabster/src/hooks/useFocusIndicatorStyle.ts
Updates focus indicator mechanism to create a style rule instead of wrap make style method
> Update focus indicator mechanism

- change/@fluentui-babel-make-styles-e2f1cc07-779b-485f-a83e-2c713ba24216.json
- packages/babel-make-styles/__fixtures__/function-mixin/mixins.ts
- packages/babel-make-styles/__fixtures__/function-mixin/output.ts
Merge of green #18321 caused master build to fail.
The reason is the branch was stale even though without conflicts.
> Fix build after #18321

- change/@fluentui-react-menu-bc30a5a7-6e96-41ab-a738-ea61bd34ef99.json
- change/@fluentui-react-menu-e39485fe-e387-422e-be88-fc4c9d1584d9.json
- packages/react-menu/bundle-size/Menu.Default.fixture.js
- packages/react-menu/bundle-size/Menu.Selectable.fixture.js
- packages/react-menu/package.json
Adds bundle size fixtures for default and selectable variants of `Menu`
(optional)
> chore(Menu): Add bundle size fixtures

- apps/vr-tests/.storybook/main.js
> Removes babel-make-style plugin from vr webpack

- tools/generators/migrate-converged-pkg/index.ts
> fix(tools): run formatter in migration generator

- change/@fluentui-react-examples-e4a6bd51-b806-4fd4-9c5f-68329bf915a1.json
- packages/react-examples/.storybook/preview.js
Centralized the Storybook story order to prevent duplication and confusion.
> Centralize Storybook story order

- tools/generators/migrate-converged-pkg/README.md
> docs(tools): add migrate-converged-pkg readme

- change/@fluentui-react-examples-c31c3522-5e8d-4a5e-964a-2fe12210a2cc.json
- packages/react-examples/src/react/DetailsList/docs/DetailsListBestPractices.md
Add DetailsList Best Practices a11y section on creating row headers
> Docs only: add some words about using isRowHeader for accessibility on DetailsList

- change/@fluentui-react-accordion-e8199943-785c-4408-8f99-65308aa4eb13.json
- change/@fluentui-react-examples-eb716a8c-2551-4a4b-a43d-3c12f083c483.json
- jest.config.js
- nx.json
- packages/react-accordion/.storybook/main.js
- packages/react-accordion/.storybook/preview.js
- packages/react-accordion/.storybook/tsconfig.json
- packages/react-accordion/config/api-extractor.local.json
- packages/react-accordion/jest.config.js
- packages/react-accordion/package.json
- packages/react-accordion/src/Accordion.stories.tsx
- packages/react-accordion/src/AccordionItem.stories.tsx
- packages/react-accordion/src/icons.stories.tsx
- packages/react-accordion/tsconfig.json
- packages/react-examples/package.json
- tsconfig.base.json
- workspace.json
Migrates react-accordion package.
> yarn nx workspace-generator migrate-converged-pkg
> Migrates react-accordion

- change/@fluentui-react-menu-5df2f706-21c9-4a0f-b37a-db1758a689c3.json
- nx.json
- packages/react-menu/.storybook/preview.js
- packages/react-menu/package.json
- packages/react-menu/tsconfig.json
- workspace.json
> chore(Menu): Migrate to new DX

- change/@fluentui-react-menu-b608a17d-e563-4aa6-9864-bf6f7f2ee14a.json
- packages/react-menu/src/components/Menu/Menu.test.tsx
- packages/react-menu/src/utils/useOnMenuEnter.ts
- packages/react-storybook/tsconfig.json
- tsconfig.base.json
- ~[] Addresses an existing issue: Fixes implements #~
(optional)
> chore: enable full strict mode for converged packages with new DX setup

- change/@fluentui-react-positioning-53589685-63f8-49d8-992f-b1820ca47429.json
- jest.config.js
- nx.json
- packages/react-positioning/.storybook/main.js
- packages/react-positioning/.storybook/preview.js
- packages/react-positioning/.storybook/tsconfig.json
- packages/react-positioning/config/api-extractor.local.json
- packages/react-positioning/jest.config.js
- packages/react-positioning/package.json
- packages/react-positioning/tsconfig.json
- workspace.json
> chore(usePopper): Migrate react-positioning to new DX

- change/@fluentui-react-accordion-743574af-7ef5-4c76-9b98-9c622de3a473.json
- change/@fluentui-react-aria-189f73f6-a931-4769-902f-b2a45797df27.json
- packages/react-accordion/package.json
- packages/react-accordion/src/components/AccordionHeader/__snapshots__/AccordionHeader.test.tsx.snap
- packages/react-accordion/src/components/AccordionHeader/useAccordionHeader.ts
- packages/react-accordion/src/components/AccordionHeader/useAccordionHeaderStyles.ts
- packages/react-aria/src/hooks/useARIAButton.ts
Refactors `react-accordion` to use `react-aria` to ensure 1st rule of ARIA
> react-accordion 1st rule of ARIA refactor

- change/@fluentui-react-menu-f5d949e7-54a1-4a9b-9635-d63c3c266571.json
- packages/react-menu/src/components/MenuItem/useMenuItem.tsx
- packages/react-menu/src/utils/DefaultIcons.tsx
Changes the direction of the chevron icon for submenus in RTL
(optional)
> fix(Menu): Change chevron icon for RTL

- change/@fluentui-react-434c69f9-76ec-4314-bd8c-4be217a8373f.json
- change/office-ui-fabric-react-87af3408-8c21-4731-8137-0f19f77075e1.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.types.ts
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts
> Cherry pick details list filter icon PR to v7

- change/office-ui-fabric-react-d5048feb-ecbd-40f3-aa9c-1d1ff61735fa.json
- packages/office-ui-fabric-react/src/components/Coachmark/Beak/Beak.styles.ts
This PR is to cherrypick the changes made in v8 to the Coachmark HC beak styling to v7
(optional)
> Cherrypick HC Coachmark Beak styling to v7

- change/@fluentui-babel-make-styles-56a36297-b23a-41fb-9855-07356f5d251b.json
- packages/babel-make-styles/suite-module/code.ts
- packages/babel-make-styles/suite-module/output.ts
This directory was included into #18397 due bad rebase.
> chore(babel-make-styles): remove directory

- change/@fluentui-react-accordion-350cfbaa-9fb0-49db-b276-56a2f5fec16e.json
- change/@fluentui-react-aria-73ebef73-acab-4a67-b3fe-35d81eb4d012.json
- change/@fluentui-react-divider-21be1ac5-aef5-4402-ac14-15662f3b8a3d.json
- change/@fluentui-react-image-32f065fc-be14-4662-bbcc-b3fd78d4722c.json
- change/@fluentui-react-menu-13187f58-6176-4555-9dfb-28289509edec.json
- change/@fluentui-react-portal-3a6fd745-6d1b-4d7c-90de-7bf6dfe9f80a.json
- change/@fluentui-react-positioning-d77fac0e-e6d4-4687-8f27-31d30f7dd7f8.json
- packages/react-accordion/package.json
- packages/react-aria/package.json
- packages/react-divider/package.json
- packages/react-image/package.json
- packages/react-menu/package.json
- packages/react-portal/package.json
- packages/react-positioning/package.json
- packages/react-text/package.json
- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
- Update build:local output path in `migrate-converged-pkg`
- Update build:local output in existing packages
- Generate api-extractor.json in  `migrate-converged-pkg`
(optional)
> fix(build): update target build path in migrate-converged-pkg

- change/@fluentui-react-badge-b407c208-ca0f-4837-825c-f2f5d6f42ca4.json
- packages/react-badge/src/components/PresenceBadge/usePresenceBadgeStyles.ts
Fix `PresenceBadge` border thickness 
(optional)
> fix(PresenceBadge): match design spec border

- tools/generators/migrate-converged-pkg/README.md
> fix(migrate-converged-pkg): update README

- change/@fluentui-react-f73da17c-dda5-43c4-b605-996d084e0241.json
- packages/react/src/components/Check/Check.test.tsx
- packages/react/src/components/Check/__snapshots__/Check.test.tsx.snap
Adding a basic snapshot test to the Check component.
> Testing - Implementing Check snapshot test

- packages/fluentui/react-northstar/src/themes/teams/colors.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Text/textVariables.ts
Fix low luminosity in dark themes updating red 200 value and using red foreground token as color.
> fix(TextStyles): Fix text error color

- packages/fluentui/CHANGELOG.md
Add missing entry for #18694 
(optional)
> chore(changelog): add missing entry

- change/@fluentui-react-badge-ee33ecf2-f7c6-43a9-8c2d-7e36c6c5e43e.json
- change/@fluentui-react-button-a8271621-51bb-416f-a92e-cee4cb8de4c1.json
- change/@fluentui-react-da710126-5d59-4504-9d4c-a2c63824b868.json
- change/@fluentui-react-slider-7591d198-57a1-45cf-b979-1eb3f6d5c4ba.json
- packages/react-badge/src/components/CounterBadge/CounterBadge.types.ts
- packages/react-button/src/components/ToggleButton/ToggleButton.types.ts
- packages/react-slider/src/components/Slider/Slider.types.ts
- packages/react/src/components/Button/Button.types.ts
- packages/react/src/components/Calendar/Calendar.types.ts
- packages/react/src/components/Calendar/CalendarDay/CalendarDay.types.ts
- packages/react/src/components/Calendar/CalendarMonth/CalendarMonth.types.ts
- packages/react/src/components/CalendarDayGrid/CalendarDayGrid.types.ts
- packages/react/src/components/Coachmark/Coachmark.types.ts
- packages/react/src/components/ColorPicker/ColorPicker.types.ts
- packages/react/src/components/CommandBar/CommandBar.types.ts
- packages/react/src/components/DatePicker/DatePicker.types.ts
- packages/react/src/components/DetailsList/DetailsList.types.ts
- packages/react/src/components/Panel/Panel.types.ts
- packages/react/src/components/Tooltip/Tooltip.types.ts
- packages/react/src/components/WeeklyDayPicker/WeeklyDayPicker.types.ts
Fixing interface doc comment typos in the: `react`, `react-button`, `react-badge`, and `react-slider` packages.
> Typos - Correcting interface doc comment typos in various packages

- .github/CODEOWNERS
> chore: update CODEOWNERS for makeStyles and *Provider packages

- change/@fluentui-react-examples-311adbf4-08e0-4b0d-bcad-0ee12d18ed75.json
- change/@uifabric-charting-33638693-9461-4271-af27-805cd9f5226f.json
- packages/charting/src/components/AreaChart/AreaChart.base.tsx
- packages/charting/src/components/CommonComponents/CartesianChart.base.tsx
- packages/charting/src/components/CommonComponents/CartesianChart.styles.ts
- packages/charting/src/components/CommonComponents/CartesianChart.types.ts
- packages/charting/src/components/Legends/Legends.types.ts
- packages/charting/src/components/Legends/shape.tsx
- packages/charting/src/components/LineChart/LineChart.base.tsx
- packages/charting/src/components/LineChart/LineChart.types.ts
- packages/charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
- packages/charting/src/types/IDataPoint.ts
- packages/charting/src/utilities/utilities.ts
- packages/react-examples/src/charting/LineChart/LineChart.Gap.Example.tsx
Cherry picking from https://github.com/microsoft/fluentui/pull/18665
LineChart, AreaChart
> Cherry pick from Add features to Line Chart (gaps, borders, line properties, etc.) #18665

- change/@fluentui-react-0508f92f-47d1-484e-920e-866370166b49.json
- change/@fluentui-react-examples-6af905cc-aeb2-4dbe-af83-ad729814d917.json
- packages/react-examples/src/react/__snapshots__/CommandBar.CommandBarButtonAs.Example.tsx.shot
- packages/react/src/components/TeachingBubble/TeachingBubble.styles.ts
- packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.deprecated.test.tsx.snap
- packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.test.tsx.snap
Added ellipsis for long word in TeachingBubble
(optional)
> Added overflow-wrap for long word in TeachingBubble

- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
> fix(tools): remove test:watch task  from converged pkg when migrating

- change/@fluentui-react-tabster-8f3d4302-5aff-41fe-a4db-6f812d42c757.json
- packages/react-tabster/package.json
- yarn.lock
> chore(tabster): Bump tabster version

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams-dark/siteVariables.ts
- packages/fluentui/react-northstar/src/themes/teams-high-contrast/siteVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/siteVariables.ts
> Adding Fluent Shadow values

- packages/fluentui/CHANGELOG.md
Prepare release react-northstar 0.57.0
(optional)
> chore: prepare release react-northstar 0.57.0

- change/@fluentui-web-components-e0f05aa7-a77d-4ae5-9437-c7b46f514f9f.json
- packages/web-components/src/horizontal-scroll/fixtures/horizontal-scroll.html
> fix horizontal scroll examples based on default flippers

- .codesandbox/ci.json
Update codesandbox node version to fix build errors in PRs
(partial fix of #18668)
> Fix codesandbox checkin task

- change/@fluentui-web-components-0b810df7-f841-4864-b129-7ab988e8f8e0.json
- packages/web-components/src/design-tokens.ts
Fixes an incidental change to typography custom property names for tokens.
(optional)
> correct typography design token names

- change/@fluentui-web-components-f81d3aa5-c0aa-46c6-972f-774e69c15d79.json
- packages/web-components/src/color/recipes/accent-fill.ts
Removed accent fill direction handling to standardize foreground text color
Accent fill controls like button
> (web-components) fix accent fill recipe

- change/@fluentui-react-examples-bd11d615-8cf3-40a2-83d3-a563860d877f.json
- packages/react-examples/src/react/Breadcrumb/Breadcrumb.Basic.Example.tsx
- packages/react-examples/src/react/Breadcrumb/docs/BreadcrumbBestPractices.md
- packages/react-examples/src/react/__snapshots__/Breadcrumb.Basic.Example.tsx.shot
- Adds accessibility section to docs site communicating team recommendation and how to add tabbing behavior.
- Adds extra example to demonstrate tabbing behavior by passing prop.
> Breadcrumb: Update doc and example to demonstrate how to add tab navigation behavior.

- change/@fluentui-web-components-d9a63f9e-3644-4bd4-b09c-79e1f9747175.json
- lint-staged.config.js
- package.json
- packages/web-components/package.json
- packages/web-components/src/color/recipes/neutral-fill-layer.spec.ts
- yarn.lock
Addresses feedback on dependencies and fixes a failing test
(optional)
> update dependencies and lint-staged config

- packages/react-examples/src/react-components/FluentUIComponents/QuickStart.stories.mdx
Fixes a typo on Developer/Quick Start page - closing tag doesn’t match the opening tag.
> Quick Start: fix closing tag

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams-dark/colors.ts
- packages/fluentui/react-northstar/src/themes/teams-high-contrast/colors.ts
- packages/fluentui/react-northstar/src/themes/teams/colors.ts
> feat(Colors): Add new color scheme tokens & color palette values

- packages/fluentui/CHANGELOG.md
Only amending changelog to related PR
https://github.com/microsoft/fluentui/pull/18934
> chore(changelog): Adding back data-is-focusable attribute 

- change/@fluentui-react-accordion-0b135005-6cc1-41a0-a5de-6215eb218e8a.json
- change/@fluentui-react-aria-1f16cbec-6a5c-441c-b31e-aba2558004cf.json
- change/@fluentui-react-utilities-6021096a-5846-499b-a218-b2aeab1e7738.json
- packages/react-accordion/etc/react-accordion.api.md
- packages/react-accordion/src/components/AccordionHeader/AccordionHeader.types.ts
- packages/react-accordion/src/components/AccordionHeader/useAccordionHeader.ts
- packages/react-aria/etc/react-aria.api.md
- packages/react-aria/src/hooks/useARIAButton.stories.tsx
- packages/react-aria/src/hooks/useARIAButton.test.tsx
- packages/react-aria/src/hooks/useARIAButton.ts
- packages/react-utilities/etc/react-utilities.api.md
- packages/react-utilities/src/compose/getSlots.test.tsx
- packages/react-utilities/src/compose/getSlots.ts
- packages/react-utilities/src/compose/resolveShorthand.ts
- packages/react-utilities/src/compose/types.ts
https://github.com/microsoft/fluentui/pull/18721#discussion_r665321636
> fix(react-utilities): simplify prop merging in getSlots()

- rfcs/convergence/authoring-stories.md
RFC for authoring stories mentioned Storybook limitations that don’t apply in the newest version. Bringing RFC up to date.
> Update authoring stories RFC

- .github/CODEOWNERS
- adds entries for missing packages:
- `bundle-size`
- `react-tabster`
- `react-positioning`
- `react-shared-contexts`
- `make-styles-webpack-loader`
- `react-portal`
- updates team's alias to include org name (_does not work properly without it as tries to use `@teams-prg` as a user???_)
> chore: update CODEOWNERS for teams-prg

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams/components/SplitButton/splitButtonToggleStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/SplitButton/splitButtonVariables.ts
⚠️⚠️ Possible breaking change
(optional)
> Fixed hover styles for Splitbutton Toggle button part (chevron)

- .github/CODEOWNERS
- ~[ ] Addresses an existing issue:~ 
- fixing bad search/replace. sorry about that
(optional)
> chore: fix cxe-prg org codeowners (mondays are hard lol)

- packages/fluentui/react-northstar-emotion-renderer/test/emotionRenderer-test.ts
This PR enables a commented test, now it works ¯\_(ツ)_/¯
> chore: enable test for Emotion renderer in N*

- .github/ISSUE_TEMPLATE/convergence_epic.md
New checkboxes to the template.
i.e.
```
```
- ~[ ] Addresses an existing issue: Fixes #0000~
Added new checkboxes to the template flow for convergence efforts. These flags help give an idea where in the convergence process the engineer is (preparation, implementation, validation). 
(optional)
> Added new flags for the convergence tracking.

- .github/ISSUE_TEMPLATE/convergence_epic.md
Add bundle size item to the Convergence Epic template
[Template](https://github.com/microsoft/fluentui/pull/18952/files?short_path=c148436#diff-c148436229bc07efc60c3cec19646b9c11e2dde891d372f38b035aece6207703)
> Convergence Epic template - Add bundle size reminder item

- change/@fluentui-keyboard-keys-8a75c623-aeb5-46ff-8a4e-ebc02a073b69.json
- change/@fluentui-react-aria-0812dedb-f470-4b34-a34d-b77a3a0e6bae.json
- packages/keyboard-keys/package.json
- packages/react-aria/package.json
- packages/react-aria/src/hooks/useARIAButton.test.tsx
- packages/react-aria/src/hooks/useARIAButton.ts
> chore(react-aria): Replace keyboard-key with keyboard-keys

- change/@fluentui-react-checkbox-f6c6d011-b46a-434d-8b84-c3024d91f5a4.json
- packages/react-checkbox/Spec.md
This PR modifies the `spec` for `Checkbox` to reflect the implementation from #18907.
> docs(react-checkbox): Updating spec to reflect Checkbox's implementation.

- change/@fluentui-react-05a7d92d-213d-45ca-b56d-e0d581556651.json
- packages/react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap
This PR updates `ComboBox`'s snapshots that are causing a build fail.
> fix(ComboBox): Updating snapshots.

- rfcs/convergence/ending-ie11-support.md
> RFC(IE11): Ending support for IE11 in Fluent v9

- change/@fluentui-babel-make-styles-0d7a3c82-36ca-429c-9a95-cc5f67ad6879.json
- change/@fluentui-babel-make-styles-5be3d29c-56dd-49b2-bd92-15dba231ca46.json
- packages/babel-make-styles/README.md
> docs(babel-make-styles): Add some troubleshooting for linaria

- change/@fluentui-react-tooltip-1116bfb1-2ac7-403c-8e39-0cc400333be5.json
- change/@fluentui-react-utilities-19735cf6-b683-4514-a328-4b72f4804de3.json
- packages/react-tooltip/src/components/Tooltip/useTooltip.tsx
- packages/react-utilities/etc/react-utilities.api.md
- packages/react-utilities/src/hooks/index.ts
- packages/react-utilities/src/hooks/useTimeout.test.ts
- packages/react-utilities/src/hooks/useTimeout.ts
Move useTimeout from react-tooltip into react-utilities and add tests
> Move useTimeout into react-utilities and add tests

- change/@fluentui-react-118fd1ed-b863-42fa-b9b2-bfcfc5162a21.json
- packages/react/src/components/Autofill/Autofill.tsx
Use nullish coalescing operator so 0 can be used as valid selection index.
Test both Japanese keyboard and English keyboard
Add and delete characters at beginning of string
Add and delete characters in middle of string
Add and delete characters at end of string
Check cursor position does not jump
> Autofill issues with IME characters

- jest.config.js
- nx.json
- packages/react-card/.storybook/main.js
- packages/react-card/.storybook/preview.js
- packages/react-card/.storybook/tsconfig.json
- packages/react-card/config/api-extractor.json
- packages/react-card/config/api-extractor.local.json
- packages/react-card/config/tests.js
- packages/react-card/etc/react-card.api.md
- packages/react-card/jest.config.js
- packages/react-card/package.json
- packages/react-card/src/common/isConformant.ts
- packages/react-card/src/components/Card/Card.test.tsx
- packages/react-card/src/components/Card/Card.tsx
- packages/react-card/src/components/CardBody/CardBody.tsx
- packages/react-card/src/components/CardFooter/CardFooter.tsx
- packages/react-card/src/components/CardHeader/CardHeader.tsx
- packages/react-card/src/components/CardPreview/CardPreview.tsx
- packages/react-card/tsconfig.json
- tsconfig.base.json
- workspace.json
Migration to new DX for react-card
> react-card: Migrate to new DX

- change/@fluentui-react-avatar-0ffa699e-96b1-4ac8-806d-0b8e9fbf61be.json
- change/@fluentui-react-badge-c4bfdc50-c744-4dc1-bc35-2e550867aec3.json
- change/@fluentui-react-button-c61baa0c-5d32-475b-84d6-cd32c5e61b42.json
- change/@fluentui-react-menu-433cd1b6-162d-47f8-92a6-e639571e8ee2.json
- change/@fluentui-react-theme-49347a7c-1779-4d0d-add0-7dfcdf25bd22.json
- packages/react-avatar/src/components/Avatar/useAvatarStyles.ts
- packages/react-badge/src/components/Badge/useBadgeStyles.ts
- packages/react-button/src/components/Button/useButtonStyles.ts
- packages/react-button/src/components/CompoundButton/useCompoundButtonStyles.ts
- packages/react-button/src/components/ToggleButton/useToggleButtonStyles.ts
- packages/react-menu/src/components/MenuPopover/useMenuPopoverStyles.ts
- packages/react-theme/etc/react-theme.api.md
- packages/react-theme/src/alias/dark.ts
- packages/react-theme/src/alias/highContrast.ts
- packages/react-theme/src/alias/light.ts
- packages/react-theme/src/alias/teamsDark.ts
- packages/react-theme/src/types.ts
Rename existing tokens [BREAKING CHANGE]:
```
strokeAccessible* -> transparentStroke*
neutralForegroundInvertedAccessible -> neutralForegroundOnBrand
```
Update existing token values:
```
neutralForeground4
neutralForegroundInverted 
```
Add new alias tokens:
```
neutralBackgroundInverted
neutralStencil1
neutralStencil2
```
> feat(react-theme): Update tokens

- .github/CODEOWNERS
> chore(react-theme): Add react-theme to CODEOWNERS

- change/@fluentui-react-button-2a3c1610-f416-4a84-8f62-7c8a99cb20c6.json
- packages/react-button/src/components/Button/useButtonStyles.ts
Fixes jumping behavior on Button focus indicator due to different button sizes
> bugfix(Button): Focus indicator jump

- .prettierignore
Added .gif to the ignored files for Prettier
> Prettier - Ignore .gif files

- packages/fluentui/react-northstar/src/components/Toolbar/Toolbar.tsx
> docs(toolbar): adding screen reader bugs related to radiogroup in toolbar 

- specs/Breadcrumb.md
- specs/Button.md
> fixed some typos in docs

- specs/Checkbox.md
- specs/Datepicker.md
> Fixed 2 typos

- .github/CODEOWNERS
Adds react-accordion to CODEOWNERS
> chore: adds react-accordion to CODEOWNERS

- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
- Fixes #18706
- implements partially https://github.com/microsoft/fluentui/issues/19103
(optional)
> feat(tools): add snapshot serializers and config/tests only when needed

- change/@fluentui-theme-1dff6552-90f7-4c37-8dd7-b97c680af791.json
- packages/theme/etc/theme.api.md
- packages/theme/src/types/Theme.ts
Added optional name property to ITheme type
(optional)
> Added optional name property to ITheme type

- change/office-ui-fabric-react-12cf9351-322c-4f2b-ae24-6297b018d19f.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Facepile/Facepile.base.tsx
- packages/office-ui-fabric-react/src/components/Facepile/Facepile.types.ts
Cherrypick of #19137 
(optional)
> A11y facepile cherrypick

- .github/CODEOWNERS
This PR adds cxe-red as codeowner to the `Facepile` component
> Add cxe-red as codeowners to Facepile

- change/@fluentui-react-charting-ae0dfbf4-e656-4ddd-a967-46cac243b074.json
- packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx
- packages/react-charting/src/components/StackedBarChart/StackedBarChart.base.tsx
- packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx
- packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx
While adding callout dismiss on escape, we need add one more prop to enable callout again.
Grouped vertical bar chart
Vertical stacked bar chart
Vertical bar chart
Horizontal bar chart
> Charting: Callout issue resolved in bar charts.

- apps/public-docsite/src/pages/Controls/AvatarPage/docs/ios/AvatarImplementation.md
- apps/public-docsite/src/pages/Controls/ButtonPage/docs/ios/ButtonImplementation.md
- apps/public-docsite/src/pages/Controls/ListCellsPage/docs/ios/ListCellsImplementation.md
- apps/public-docsite/src/pages/Controls/NavBarPage/docs/ios/NavBarImplementation.md
- apps/public-docsite/src/pages/Controls/PivotPage/docs/ios/PivotImplementation.md
- apps/public-docsite/src/pages/Controls/SeparatorPage/docs/ios/SeparatorImplementation.md
- apps/public-docsite/src/pages/Controls/SpinnerPage/docs/ios/SpinnerImplementation.md
- apps/public-docsite/src/pages/Controls/TextPage/docs/ios/TextImplementation.md
This fixes the broken links in ios documentation.
(optional)
> fix: ios broken links

- apps/public-docsite/src/pages/Controls/ButtonPage/docs/cross/ButtonUsage.md
- apps/public-docsite/src/pages/Controls/ButtonPage/docs/windows/ButtonImplementation.md
- apps/public-docsite/src/pages/Controls/ButtonPage/docs/windows/ButtonUsage.md
- apps/public-docsite/src/pages/Controls/LinkPage/docs/cross/LinkUsage.md
- apps/public-docsite/src/pages/Controls/LinkPage/docs/windows/LinkUsage.md
- apps/public-docsite/src/pages/Controls/PersonaPage/docs/cross/PersonaUsage.md
- apps/public-docsite/src/pages/Controls/SeparatorPage/docs/cross/SeparatorUsage.md
- apps/public-docsite/src/pages/Controls/TextPage/docs/cross/TextUsage.md
This fixes the broken links in documentation.
(optional)
> fix: fixed broken links

- rfcs/build-system/03-packaging-for-npm.md
- ~[ ] Addresses an existing issue~
- [📖 READ MODE](https://github.com/microsoft/fluentui/pull/19066/files?short_path=5f7207c#diff-5f7207c6bbe691ed5b44797f4f8faaca026360ebd954a2821d2d908056b8b561)
(optional)
> docs(rfcs): create packaging for npm registry

- rfcs/convergence/slot-null-rendering.md
Proposes changes in slot handling mechanisms to solve problems on `null rendering` scenarios
> RFC: Slot null rendering

- rfcs/convergence/slot-null-rendering.md
> Update slot-null-rendering RFC

- rfcs/convergence/simplify-prop-merging.md
Updates RFC: Simplify prop merging with slots, as followed by #19068
> Updates RFC: Simplify prop merging with slots

- change/@fluentui-react-provider-f78c00b6-c173-47c7-81b3-148a04575830.json
- packages/react-provider/etc/react-provider.api.md
- packages/react-provider/src/index.ts
This PR adds an export for `useTheme()` hook.
> fix: export useTheme() hook

- change/@uifabric-azure-themes-7cb019b3-3894-4565-a393-95ff446318e7.json
- packages/azure-themes/src/azure/AzureThemeDark.ts
- packages/azure-themes/src/azure/AzureThemeHighContrastDark.ts
- packages/azure-themes/src/azure/AzureThemeHighContrastLight.ts
- packages/azure-themes/src/azure/AzureThemeLight.ts
- packages/azure-themes/src/azure/styles/DefaultButton.styles.ts
- packages/azure-themes/src/azure/styles/PrimaryButton.styles.ts
Cherry pick of #19166 into 7.0 branch
> Cherry pick of #19015

- .github/CODEOWNERS
Moving ownership of the react-card component to our team, as I'll be working on it's convergence.
> react-card: Move ownership to cxe-prg team

- packages/react-card/package.json
Race condition allowed a version mismatch to be checked into master
(optional)
> fix(react-card): Fix babel-make-styles version mismatch

- change/@fluentui-react-text-72a7efbb-3db6-43ff-8e0e-5b555b04d8ba.json
- packages/react-text/package.json
> Text: Release 🎉

- packages/react-slider/etc/react-slider.api.md
- packages/react-slider/src/Slider.stories.tsx
- packages/react-slider/src/components/Slider/Slider.test.tsx
- packages/react-slider/src/components/Slider/Slider.types.ts
- packages/react-slider/src/components/Slider/__snapshots__/Slider.test.tsx.snap
- packages/react-slider/src/components/Slider/useSliderState.tsx
Implementing the `origin` prop to the **Slider** component:
> ( react-slider) - Adding origin prop

- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
- implements RFC proposal to migration generator https://github.com/microsoft/fluentui/pull/19066
(optional)
> feat(tools): update migration generator with new npmIgnoreConfig updates

- change/@fluentui-react-button-cc8a6258-92ba-4546-a211-7d55368ae675.json
- packages/react-button/src/components/Button/useButtonStyles.ts
This PR adds `fontFamily` styles to all `Button` components in `react-button`.
> Button: Adding font family styles

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Tooltip/Tooltip.tsx
Allow `Tooltip` to be configured a delay to open it. 
(optional)
> feat(Tooltip): add delay to open Tooltip 

- change/@fluentui-web-components-9f8f5391-7aba-49f3-bc0f-c9b091260370.json
- packages/web-components/src/design-system-provider/index.ts
changed the background on the card component to Canvas and the color to CanvasText 
(optional)
> fix: update background to Canvas and color to CanvasText in high contrast

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Tooltip/Tooltip.tsx
This is a follow up of PR #19478
It uses defaultProps to achieve a cleaner code
(optional)
> set Tooltip offset default prop

- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
- Fixes https://github.com/microsoft/fluentui/issues/19109
- Implements partially https://github.com/microsoft/fluentui/issues/19103
(optional)
> feat(tools): properly setup babel config for vNext packages

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams/components/Button/buttonStyles.ts
Add `active` styled for `text` button.
(optional)
> fix(buttonStyles): add pressed styles for text button

- change/@fluentui-merge-styles-0da7bc43-803f-44ac-9388-46a8fe7cc4a3.json
- packages/merge-styles/src/getVendorSettings.ts
Added a null check for userAgent which would previously give crash
(optional)
> UserAgent giving NPE

- change/@fluentui-react-menu-3676a1ea-cf06-4705-97f5-9e67f2356b40.json
- packages/react-menu/src/MenuList.stories.tsx
- packages/react-menu/src/components/Menu/useMenu.tsx
- packages/react-menu/src/components/MenuList/MenuList.types.ts
- packages/react-menu/src/components/MenuList/useMenuList.test.ts
- packages/react-menu/src/components/MenuList/useMenuList.ts
Implements for RFC #18974 for `Menu`.
> fix(Menu): use proper signature for event handlers

- change/@fluentui-react-utilities-3698a5c7-1c2b-4ccb-883b-666fb26bec7c.json
- packages/react-utilities/src/compose/README.md
This PR updates `packages/react-utilities/src/compose/README.md` to be aligned with latest changes.
- Adds details about handling of React context values
- Fixes formatting in snippets
- Removes mentions of deprecated utils
>  docs(composeUtils): update README

- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
- ~[ ] Addresses an existing issue:~ 
(optional)
> fix(tools): properly set babel-make-styles version for vNext

- change/@fluentui-react-components-60157968-c38f-4049-875a-b0b108d455fd.json
- packages/react-components/.storybook/main.js
- packages/react-components/.storybook/main.utils.js
- packages/react-components/.storybook/main.utils.test.js
- packages/react-components/.storybook/manager.js
- packages/react-components/.storybook/preview.js
- packages/react-components/.storybook/theme.js
- ~[ ] Addresses an existing issue~
- extracts logic from `main.js` which is now tested and makes automatic migrations easier to process
(optional)
> refactor(react-components): make storybook config easier to migrate with migration generator

- change/office-ui-fabric-react-48c3fdce-d9ea-4e2b-97e4-22c150b461f1.json
- packages/office-ui-fabric-react/src/utilities/decorators/withResponsiveMode.tsx
> Fix initialization of Responsive Mode on small screens

- change/@fluentui-react-popover-92dfd99c-a127-4d13-b8f4-ecbe42b68429.json
- change/@fluentui-react-provider-7ccfbe52-85d3-4452-91c9-8d54ae5070b2.json
- packages/react-popover/package.json
- packages/react-popover/src/common/isConformant.ts
- packages/react-popover/src/components/Popover/Popover.test.tsx
- packages/react-popover/src/components/Popover/Popover.tsx
- packages/react-popover/src/components/PopoverSurface/PopoverSurface.test.tsx
- packages/react-popover/src/components/PopoverSurface/__snapshots__/PopoverSurface.test.tsx.snap
- packages/react-popover/src/components/PopoverTrigger/PopoverTrigger.test.tsx
- packages/react-popover/src/components/PopoverTrigger/PopoverTrigger.tsx
- enables conformance tests for `Popover` & `PopoverTrigger` components
- enables new conformance test for `makeStyles()`
- adds comments to components
- minor tweaks to tests
> test(react-popover): enable "className" test for mergeClasses()

- change/@fluentui-react-menu-54a39443-5b65-442f-8a6f-eaa5331e1c27.json
- packages/react-menu/package.json
- packages/react-menu/src/common/isConformant.ts
- packages/react-menu/src/components/Menu/Menu.test.tsx
- packages/react-menu/src/components/MenuDivider/MenuDivider.test.tsx
- packages/react-menu/src/components/MenuGroup/MenuGroup.test.tsx
- packages/react-menu/src/components/MenuGroupHeader/MenuGroupHeader.test.tsx
- packages/react-menu/src/components/MenuItem/MenuItem.test.tsx
- packages/react-menu/src/components/MenuItemCheckbox/MenuItemCheckbox.test.tsx
- packages/react-menu/src/components/MenuItemRadio/MenuItemRadio.test.tsx
- packages/react-menu/src/components/MenuList/MenuList.test.tsx
- packages/react-menu/src/components/MenuTrigger/MenuTrigger.test.tsx
- enables new conformance test for `makeStyles()`
- minor tweaks to tests
> test(react-menu): enable "className" test for mergeClasses()

- change/@fluentui-react-provider-7ccfbe52-85d3-4452-91c9-8d54ae5070b2.json
- packages/react-provider/package.json
- packages/react-provider/src/common/isConformant.ts
- packages/react-provider/src/components/FluentProvider/FluentProvider.test.tsx
- enables new conformance test for `makeStyles()`
- cleanup Enzyme usages
> test(react-provider): enable "className" test for mergeClasses()

- change/@fluentui-react-accordion-98722492-d946-4b4c-aa2a-7ace94a14051.json
- packages/react-accordion/package.json
- packages/react-accordion/src/common/isConformant.ts
- packages/react-accordion/src/components/Accordion/Accordion.test.tsx
- packages/react-accordion/src/components/AccordionHeader/AccordionHeader.test.tsx
- packages/react-accordion/src/components/AccordionItem/AccordionItem.test.tsx
- packages/react-accordion/src/components/AccordionPanel/AccordionPanel.test.tsx
- enables new conformance test for `makeStyles()`
- cleanup Enzyme usages
> test(react-accordion): enable "className" test for mergeClasses()

- change/@fluentui-react-badge-9d134144-d435-41b6-b116-63526163aa46.json
- change/@fluentui-react-divider-42afa2be-28ba-4948-9eb0-0355e58a8f4b.json
- packages/react-badge/package.json
- packages/react-badge/src/common/isConformant.ts
- packages/react-divider/package.json
- packages/react-divider/src/common/isConformant.ts
_Extracted from #19575._ Enables new conformance test for `makeStyles()`.
> test(react-divider|react-badge): enable "className" test for mergeClasses()

- change/@fluentui-react-image-7c1ba35d-fc38-4d43-9b47-373e1a7562e8.json
- change/@fluentui-react-text-757fcbf0-34f7-4d50-b294-950f7e306296.json
- packages/react-card/package.json
- packages/react-card/src/common/isConformant.ts
- packages/react-image/package.json
- packages/react-image/src/common/isConformant.ts
- packages/react-text/package.json
- packages/react-text/src/common/isConformant.ts
- packages/react-text/src/components/Text/Text.test.tsx
_Extracted from #19575._ Enables new conformance test for `makeStyles()`.
> test(react-image,-text,-card): enable "className" test for mergeClasses()

- change/@fluentui-react-image-eec0bd3c-34a7-48c1-a0ba-02ba35409ecd.json
- packages/react-image/src/components/Image/Image.test.tsx
- packages/react-image/src/components/Image/__snapshots__/Image.test.tsx.snap
Added snapshot test for Image component. 
Image is a styling based component, thus no other unit tests are considered necessary. VR tests will be added in a separate PR.
> react-image: added unit tests

- scripts/create-component/plop-templates-component/src/common/isConformant.ts.hbs
- scripts/create-package/plop-templates-react/package.json.hbs
- scripts/create-package/plopfile.ts
_Initially this PR contained changes for all packages, but due huge amount of changed files was splitted into smaller chunks._
This PR enables new conformance test that was implemented in #19500 for converged packages in templates.
- updates existing generator to include `@fluentui/react-conformance-make-styles` as a dependency.
- updates templates to include new tests
> chore: Update package scaffolding to add mergeClasses conformance test

- packages/react-slider/README.md
Adding an examples section to the converged **Slider** component's README.md file to cover basic usage.
> (react-slider) - Adding examples to the README.md

- change/@fluentui-react-slider-9d4b6e4b-3360-462e-878a-7eef24050e68.json
- packages/react-slider/package.json
Removing `"private": true,` from the converged **Slider** component's package.
> (react-slider) - Updating package.json to public

- packages/fluentui/CHANGELOG.md
> chore: prepare release react-northstar 0.58.0

- change/@fluentui-react-slider-2413a417-d630-4ea4-90c6-ce3d6710998d.json
- packages/react-slider/MIGRATION.md
Adding a migration guide to the converged **Slider** component.
> (react-slider) - Adding MIGRATION.md

- change/@fluentui-web-components-39a73505-6dd7-40b6-986f-ac3e9a0a9107.json
- packages/web-components/src/tabs/tab-panel/tab-panel.styles.ts
Submitting this as requested in https://github.com/microsoft/fast/issues/5171.
> [web-components] Fix tab panel display

- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
Adds missing `isolatedModules` to tsconfig
(optional)
> fix(migrate-converged-pkg): Add missing `isolatedModules` to tsconfig

- change/@fluentui-react-switch-677854a4-845a-4d58-906a-32465556e521.json
- packages/react-switch/package.json
Removing `"private": true,` from the converged **Switch** component's package.
> (react-switch) - Updating package.json to public

- tools/generators/migrate-converged-pkg/index.ts
- tools/generators/migrate-fixed-versions/README.md
- tools/generators/migrate-fixed-versions/index.spec.ts
- tools/generators/migrate-fixed-versions/index.ts
- tools/generators/migrate-fixed-versions/schema.json
- tools/generators/migrate-fixed-versions/schema.ts
- tools/utils.ts
For more details, please check the `README.md` file for the generator
Creates a new NX generator `migrated-fixed` versions that migrates web
packages only from caret to fixed deependencies.
(optional)
> chore(release): New NX generator to migrate fixed version dependencies

- scripts/beachball/index.ts
An example of the generated changelog can be found in #19672
Enables the groupped changelog feature in beachball introduced in microsoft/beachball#286 for `@fluentui/react-components`
(optional)
> chore(react-components): Use beachball groupped changelog

- change/@fluentui-react-portal-5bcfe3d0-3d56-4a24-9cd9-2ca92290614e.json
- packages/react-portal/etc/react-portal.api.md
- packages/react-portal/src/components/Portal/Portal.types.ts
- packages/react-portal/src/components/Portal/usePortal.ts
Modifies `FluentProvider` to use simplified prop merging.
> chore(react-portal): use simplified prop merging

- change/@fluentui-react-provider-693ca60b-3600-4a5d-9704-3fb9c3b2cd47.json
- packages/react-provider/etc/react-provider.api.md
- packages/react-provider/src/components/FluentProvider/FluentProvider.test.tsx
- packages/react-provider/src/components/FluentProvider/FluentProvider.types.ts
- packages/react-provider/src/components/FluentProvider/renderFluentProvider.tsx
- packages/react-provider/src/components/FluentProvider/useFluentProvider.ts
- packages/react-provider/src/components/FluentProvider/useFluentProviderContextValues.ts
- packages/react-provider/src/components/FluentProvider/useFluentProviderStyles.ts
Modifies `FluentProvider` to use simplified prop merging.
> chore(react-provider): use simplified prop merging

- packages/fluentui/e2e/tests/popupIframeDismiss-example.tsx
- packages/fluentui/e2e/tests/popupIframeDismiss.spec.ts
We have hardcoded `src` attribute in e2e. This PR changes it to have custom DOM in e2e, to prevent opening third-party URL in tests
(optional)
> chore: update iframe content in e2e test

- .github/CODEOWNERS
sets teams-prg as codeowners for the `react-aria` package
(optional)
> chore(react-aria): Fix codeowners

- change/@fluentui-react-b41885f4-e7ac-4dfc-90de-0f524330a59b.json
- packages/react/src/components/ContextualMenu/ContextualMenuItem.base.tsx
Providing the defaultRenderer argument for the onRenderIcon of ContextualMenuItem.
(optional)
> defaultRenderer argument for the onRenderIcon of ContextualMenuItem

- rfcs/convergence/fixed-versions-for-prerelease.md
[**RENDERED PREVIEW**](https://github.com/ling1726/fluentui/blob/rfc/beta-fixed-versions/rfcs/convergence/fixed-versions-for-prerelease.md)
> RFC: Use fixed versions for `@fluentui` dependencies in prerelease

- packages/a11y-testing/src/facades/ComponentTestFacade.tsx
Adds keyup event to space click simulation to ensure compatibility with `@fluentui/react-aria`
> a11y-testing: Adds keyup event to space click simulation

- change/office-ui-fabric-react-24a1d857-4f53-43b4-b031-0586daed6ca6.json
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.test.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
- packages/office-ui-fabric-react/src/utilities/decorators/withViewport.tsx
Port of this change to 7.0.
https://github.com/microsoft/fluentui/commit/6b8eecf01a5bc2dc4bb0e5099a31efcdf5d974e8
> Ported viewport fix to 7.0

- change/@fluentui-web-components-51676107-d167-42f3-a337-756bb151da59.json
- packages/web-components/src/slider/slider.styles.ts
Fixes a math issues with the slider thumb
(optional)
> (web-components) fix slider thumb math

- change/@fluentui-web-components-753d73c0-5c1a-4df0-8dfd-f47f26ad3dbd.json
- packages/web-components/src/toolbar/toolbar.stories.ts
Updated web-components/toolbar story for new storybook organization
(optional)
> (web components) - fix toolbar storybook location

- change/@fluentui-make-styles-cb25c47f-2773-4482-96b5-5a7fd6a8725b.json
- change/@fluentui-react-shared-contexts-c4a43c7f-08e9-4702-b53c-1e07d8b36c45.json
- packages/make-styles/package.json
- packages/react-shared-contexts/package.json
> chore(make-styles): Remove unnecessary `@fluentui/test-utilities` dev dependency

- scripts/create-package/plopfile.ts
Updates types after @nrwl/workspace upgrade.
`yarn create-package` works
> fix(tooling): Update type import in create-package

- change/@fluentui-react-link-a13c9f93-8c38-40ff-8716-55af7ac2a5d3.json
- packages/react-link/src/components/Link/useLinkState.ts
didn't fail on that because the dependency wasn't even declared in
package.json
(optional)
> fix(Link): use `keyboard-keys` package

- packages/fluentui/CHANGELOG.md
> chore: prepare release react-northstar 0.59.x

- change/@fluentui-react-image-81933a6e-5604-47ea-a482-98bc3fe73d63.json
- packages/react-image/src/stories/Image.stories.tsx
- packages/react-image/src/stories/ImageApperanceShape.stories.tsx
- packages/react-image/src/stories/ImageBorderVariations.stories.tsx
- packages/react-image/src/stories/ImageDefault.stories.tsx
- packages/react-image/src/stories/ImageDescription.md
- packages/react-image/src/stories/ImageFallback.stories.tsx
- packages/react-image/src/stories/ImageFluid.stories.tsx
- packages/react-image/src/stories/ImageLayoutFit.stories.tsx
~~- [ ] Addresses an existing issue: Fixes #0000~~
Moving stories into separate files in order to comply with the following [RFC]( https://github.com/microsoft/fluentui/blob/master/rfcs/convergence/authoring-stories.md). This is an update to this PR: #19687
> react-image: separating stories into own files

- azure-pipelines.release-vnext.yml
#19855 was create 3 days ago which invalidated a paramter for component governance task
> Update azure-pipelines.release-vnext.yml for Azure Pipelines

- change/@fluentui-web-components-badb55a9-3702-4002-baab-fd99beb2c9c0.json
- packages/web-components/docs/api-report.md
- packages/web-components/package.json
- packages/web-components/src/custom-elements.ts
- yarn.lock
> (web-components) add additional param to all component registry

- change/@fluentui-react-tooltip-c04458af-c9b3-479c-b715-31aa036e3b60.json
- packages/react-tooltip/etc/react-tooltip.api.md
- packages/react-tooltip/src/Tooltip.stories.tsx
- packages/react-tooltip/src/components/Tooltip/Tooltip.types.ts
- packages/react-tooltip/src/components/Tooltip/renderTooltip.tsx
- packages/react-tooltip/src/components/Tooltip/useTooltip.tsx
- packages/react-tooltip/src/components/Tooltip/useTooltipStyles.ts
- Updated TooltipProps to replace inverted with appearance?: 'inverted'
- Update TooltipProps to replace pointing with withArrow
> Update TooltipProps for consistency

- change/@fluentui-react-link-69c8cebf-a9e1-4855-948c-a20f71de0759.json
- packages/react-link/SPEC.md
- packages/react-link/etc/react-link.api.md
- packages/react-link/src/Link.stories.tsx
- packages/react-link/src/components/Link/Link.types.ts
- packages/react-link/src/components/Link/useLink.ts
- packages/react-link/src/components/Link/useLinkStyles.ts
- Added Link appearance?:'subtle' to replace secondary
> Updated LinkProps for consistency

- change/@fluentui-react-popover-5f4185d6-50dc-49e5-a202-7753512ad738.json
- packages/react-popover/etc/react-popover.api.md
- packages/react-popover/src/components/Popover/Popover.types.ts
- packages/react-popover/src/components/Popover/renderPopover.tsx
- packages/react-popover/src/components/PopoverSurface/PopoverSurface.types.ts
- packages/react-popover/src/components/PopoverSurface/usePopoverSurface.ts
- packages/react-popover/src/components/PopoverSurface/usePopoverSurfaceStyles.ts
- packages/react-popover/src/popoverContext.ts
- Added PopoverProps appearance to replace brand and inverted mutually exclusive properties.
> Updated PopoverProps for consistency

- azure-pipelines.yml
> [v5]: Migrate to 1ES Hosted Pool

- azure-pipelines.yml
> [v6]: Migrate to 1ES Hosted Pool

- change/@fluentui-react-slider-27a702d4-7063-4483-ad79-9def218afff1.json
- packages/react-slider/src/components/Slider/Slider.test.tsx
Adding accessibility tests to the converged **Slider** component.
> (react-slider) - Adding accessibility tests

- change/@fluentui-react-checkbox-f702f678-e790-45fc-88a7-06ff6ed30e2e.json
- packages/react-checkbox/etc/react-checkbox.api.md
- packages/react-checkbox/src/common/isConformant.ts
- packages/react-checkbox/src/components/Checkbox/Checkbox.types.ts
- packages/react-checkbox/src/components/Checkbox/renderCheckbox.tsx
- packages/react-checkbox/src/components/Checkbox/useCheckbox.tsx
- packages/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts
Use simple prop merging as described in #19678
> refact: remove mergeProps from react-checkbox

- change/@fluentui-react-examples-b258e76e-d684-4cb5-980c-e93e5598fd0e.json
- change/@fluentui-react-examples-c0092f01-066c-49bc-b41b-a3a756cef037.json
> fix: Remove invalid changefiles

- change/@fluentui-react-file-type-icons-b57af6d7-a71f-41a0-919f-87aa7d0fa125.json
- packages/react-file-type-icons/src/FileIconType.ts
- packages/react-file-type-icons/src/FileTypeIconMap.ts
- packages/react-file-type-icons/src/getFileTypeIconProps.ts
- [X ] Include a change request file using `$ yarn change`
Adding Forms icon to react-file-type-icons
It can be referenced by supplying a type rather than an extension.
(optional)
> Adding form icon to react-file-type-icons

- change/@uifabric-file-type-icons-8eda3f14-1bc2-456e-9ea8-3e7808fc8e8b.json
- packages/file-type-icons/src/FileIconType.ts
- packages/file-type-icons/src/FileTypeIconMap.ts
- packages/file-type-icons/src/getFileTypeIconProps.ts
- [X ] Include a change request file using `$ yarn change`
Adding Forms icon to file-type-icons
Can be referenced by type rather than extension.
(optional)
> Add forms icon to file-type-icons

- change/@uifabric-file-type-icons-f4817902-73ca-48e4-ac33-112941fcb98b.json
- packages/file-type-icons/src/FileIconType.ts
- packages/file-type-icons/src/getFileTypeIconProps.ts
- [X ] Include a change request file using `$ yarn change`
Adding sway icon to file-type-icons.
(optional)
> Add sway icon to file-type-icons v7

- change/@fluentui-react-6be7fde0-2ae2-4a09-8b8e-caee6bb55618.json
- packages/react/README.md
and clarified where the 'how to build the repo' content now lives.
(optional)
> Fixed broken TOC link

- change/@fluentui-react-link-79091a3e-efe8-4911-a970-63ff27d657ac.json
- packages/a11y-testing/src/definitions/Link/linkBehaviorDefinition.ts
- packages/react-link/src/components/Link/Link.test.tsx
- packages/react-link/src/components/Link/__snapshots__/Link.test.tsx.snap
- packages/react-link/src/components/Link/useLinkState.ts
This PR fixes a bunch of issues found as part of a manual accessibility review of the `Link` component and adds/updates tests to reflect these and other behaviors.
> Link: Fixing issues found in a11y review

- change/@fluentui-react-5b09bf96-093b-4464-80c4-529cefe4cee9.json
- packages/react/etc/react.api.md
- packages/react/src/components/DetailsList/DetailsList.test.tsx
- packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
- packages/react/src/utilities/decorators/withViewport.tsx
Updated to only delay first measure if the delayFirstMeasure property is set.
DetailsList
> Opt in viewport delay

- change/@fluentui-react-5b09bf96-093b-4464-80c4-529cefe4cee9.json
- change/office-ui-fabric-react-aa25f03c-b959-44ca-86ab-24769601eb7d.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.test.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
- packages/office-ui-fabric-react/src/utilities/decorators/withViewport.tsx
Cherry pick of https://github.com/microsoft/fluentui/pull/19968 to 7.0 branch
(optional)
> Port opt in viewport delay

- change/@fluentui-react-badge-3e816a43-44c6-4076-92ee-572dd15ddeb6.json
- packages/react-badge/src/stories/BadgeDefault.stories.tsx
Enable Storybook Controls for the default story in Badge.
> Badge: enable Storybook Controls

- apps/vr-tests/src/stories/RangedSliderConverged.stories.tsx
Adding visual regression tests for the converged `RangedSlider` component.
> (react-slider) - Adding RangedSlider VR tests

- change/@fluentui-web-components-60c3911f-0fbc-46e2-8c3d-9d104fe05aef.json
- packages/web-components/src/text-area/text-area.styles.ts
Fixes an issue where syntax problems were causing styles to not be applied.
(optional)
> (web-components) fix text area padding syntax

- change/change-033e3a2d-a605-4e04-a072-e0bf2de57a3a.json
- packages/react-conformance/README.md
Updating the `react-conformance` README.md file.
> Updating react-conformance README.md

- change/@fluentui-react-examples-1b662f70-4d87-4c9a-a263-ece9971e24bc.json
- change/office-ui-fabric-react-e3d1bb6a-5545-4007-b2e8-f66e06e3b3a0.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.base.tsx
- packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.styles.ts
- packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.test.tsx
- packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.types.ts
- packages/office-ui-fabric-react/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
- packages/office-ui-fabric-react/src/components/TextField/TextField.base.tsx
- packages/office-ui-fabric-react/src/components/TextField/TextField.types.ts
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DatePicker.Basic.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DatePicker.Required.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DatePicker.WeekNumbers.Example.tsx.shot
> [v7] DatePicker: Calendar should now open when using swipe gesture on Talkback

- apps/vr-tests/src/stories/PeoplePicker.stories.tsx
- change/@fluentui-react-examples-8c45079a-b022-4bfd-8170-e9b8312e26e7.json
- change/office-ui-fabric-react-4b28580c-8245-4a0c-b165-3c5f1c5214e7.json
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.styles.ts
- packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/__snapshots__/PeoplePicker.test.tsx.snap
- packages/office-ui-fabric-react/src/components/pickers/TagPicker/__snapshots__/TagPicker.test.tsx.snap
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Announced.SearchResults.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/PeoplePicker.Compact.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/PeoplePicker.Controlled.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/PeoplePicker.LimitedSearch.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/PeoplePicker.List.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/PeoplePicker.Normal.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/PeoplePicker.PreselectedItems.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/PeoplePicker.ProcessSelection.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/TagPicker.Basic.Example.tsx.shot
- Port #19568 to 7.0 branch of picker placeholder style to fix color contract issues
Picker controls
> Port picker placeholder style

- packages/fluentui/docs/src/examples/components/Menu/States/MenuControlledExample.shorthand.tsx
- packages/fluentui/docs/src/examples/components/Menu/States/index.tsx
- packages/fluentui/react-northstar/src/components/Menu/MenuItem.tsx
Add an example for controlled menu open and fix the docs for menu item to reflect real usage. 
(optional)
> fix: update menu item docs to reflect how to use controlled state

- change/@fluentui-react-menu-ca9a2698-c47d-4b86-8109-8bc4e9de67f2.json
- change/@fluentui-react-popover-7ef3525f-e2ca-4377-b1c0-d4cf468258d5.json
- packages/react-menu/src/stories/MenuAnchorToTarget.stories.tsx
- packages/react-menu/src/stories/MenuControllingOpenAndClose.stories.tsx
- packages/react-menu/src/stories/MenuDescription.md
- packages/react-menu/src/stories/MenuMemoizedMenuItems.stories.tsx
- packages/react-menu/src/stories/MenuVisualDividerOnly.stories.tsx
- packages/react-popover/src/stories/PopoverControllingOpenAndClose.stories.tsx
> fix(Menu): documentation typos

- change/change-d7e3c66e-6c05-431a-93f1-171a9051a410.json
- packages/react-theme/src/themes/ThemeShadows.stories.tsx
Fixes shadows story after tokens rename in #20041 
(optional)
> docs(react-theme): fix shadows story

- change/change-d91a7e58-3969-4112-ac1e-a8b77f000388.json
- packages/react-avatar/src/Avatar.stories.tsx
Fix a regression after #19449.
From:
To:
> react-avatar: Fix stories after  #19449

- change/change-c410bb10-db85-4664-83e1-570f96912155.json
- packages/react-divider/etc/react-divider.api.md
- packages/react-divider/src/components/Divider/Divider.types.ts
- packages/react-divider/src/components/Divider/renderDivider.tsx
- packages/react-divider/src/components/Divider/useDivider.ts
https://github.com/microsoft/fluentui/pull/19960#issuecomment-926801744
> react-divider: follow up prop merging PR

- change/@fluentui-react-badge-6127adeb-8966-471a-8430-fb37876be13b.json
- packages/react-badge/etc/react-badge.api.md
- packages/react-badge/src/components/Badge/Badge.tsx
- packages/react-badge/src/components/CounterBadge/CounterBadge.tsx
- packages/react-badge/src/components/PresenceBadge/PresenceBadge.tsx
Adds `ForwardRefComponent` on component declaration as followed by https://github.com/microsoft/fluentui/pull/19923
> react-badge: Adjust signature to use ForwardRefComponent

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Carousel/Carousel.tsx
DisableClickableNav doesn't listed in ProtoTypes list causing warings in console.
(optional)
> Adding disableClickableNav to ProtoTypes list

- change/@fluentui-web-components-2c52d18d-0676-470c-a592-8483a8ce6d7a.json
- packages/web-components/src/_docs/getting-started/installation.stories.mdx
Minor content updates to web components' Installation document.
(optional)
> (web-components) - fix installation instruction docs story

- change/@fluentui-react-button-461575db-f5c4-4255-a3a5-18972bd8a7c4.json
- packages/react-button/etc/react-button.api.md
- packages/react-button/src/components/Button/Button.tsx
- packages/react-button/src/components/Button/useButton.ts
- packages/react-button/src/components/CompoundButton/CompoundButton.tsx
- packages/react-button/src/components/CompoundButton/useCompoundButton.ts
- packages/react-button/src/components/MenuButton/MenuButton.tsx
- packages/react-button/src/components/MenuButton/useMenuButton.tsx
- packages/react-button/src/components/SplitButton/SplitButton.tsx
- packages/react-button/src/components/SplitButton/useSplitButton.ts
- packages/react-button/src/components/ToggleButton/ToggleButton.tsx
- packages/react-button/src/components/ToggleButton/useToggleButton.ts
Adds `ForwardRefComponent` on component declaration as followed by https://github.com/microsoft/fluentui/pull/19923
> react-button: Adjust signature to use ForwardRefComponent

- change/@fluentui-babel-make-styles-ce70878d-8e69-45d1-ba2b-8b3ce02cfbe6.json
- change/@fluentui-make-styles-webpack-loader-b0076753-fae1-4e43-b3c3-3e8ea3cd06a6.json
- packages/babel-make-styles/package.json
- packages/make-styles-webpack-loader/package.json
- yarn.lock
Bump linaria versions to consume fix callstack/linaria#820
(optional)
> fix(babel-make-styles): Bump Linaria versions

- azure-pipelines.release-vnext.yml
> [v9 release pipeline]: Migrate to 1ES Hosted Pool

- change/@fluentui-web-components-991943ae-d31e-470f-b668-91932a12dc09.json
- packages/web-components/src/progress/progress-ring/progress-ring.styles.ts
- packages/web-components/src/progress/progress/progress.styles.ts
Updating the background color of Progress and Progress Ring ahead of the Sun Valley Fluent updates
(optional)
> (web components) update progress determinate color to accentFillRest

- .github/CODEOWNERS
~~- [ ] Addresses an existing issue: Fixes #0000~~
Adding `cxe-prg` team as codeowner for `react-radio` component.
> react-radio: updated codeowners

- change/@fluentui-web-components-1826d041-b4a6-4cd4-bff8-5e64cc71cd0a.json
- packages/web-components/.storybook/preview-body.html
- packages/web-components/.storybook/preview-head.html
- packages/web-components/.storybook/preview.js
- packages/web-components/public/switches.ts
- packages/web-components/src/anchor/anchor.stories.ts
- packages/web-components/src/card/fixtures/card.html
- packages/web-components/src/data-grid/fixtures/base.html
- packages/web-components/src/switch/switch.stories.ts
- packages/web-components/src/text-area/text-area.stories.ts
- packages/web-components/src/tree-view/tree-view.stories.ts
Fixed places where Brian Heston's changes were clobbered by earlier changes I made.
(optional)
> web-components: fix conflicts with visual update

- change/@fluentui-web-components-e876c14e-a8dc-4cbc-b324-a5382b15bc7b.json
- packages/web-components/src/styles/patterns/input.styles.ts
> (web components) fix cursor issue text field

- .github/CODEOWNERS
- nx.json
- package.json
- typings/README.md
- typings/custom-global/README.md
- typings/inline-style-expand-shorthand/index.d.ts
- typings/package.json
- typings/storybook__addons/index.d.ts
- typings/tsconfig.json
- workspace.json
- ~[ ] Addresses an existing issue:~
- makes `/typings` a proper package with CI checks
- for the rest pls see atomic commit messages
(optional)
> feat(typings): improve UX and enable CI checks

- packages/react-input/Spec-styling.md
- packages/react-input/etc/react-input.api.md
- packages/react-input/src/components/Input/Input.stories.tsx
- packages/react-input/src/components/Input/Input.types.ts
- packages/react-input/src/components/Input/__snapshots__/Input.test.tsx.snap
- packages/react-input/src/components/Input/renderInput.tsx
- packages/react-input/src/components/Input/useInput.ts
- packages/react-input/src/components/Input/useInputStyles.ts
Implement an initial round of changes based on the spec (#20035).
Note that bookends are not actually implemented yet. I'm also going to do the primary slot change separately.
> Input: implement changes based on spec

- packages/react-components/CHANGELOG.md
Documentation changes are not code that is shipped with the published
package, and should not pollute the changelog
(optional)
> chore(react-components): Remove doc related changelog entries

- change/@fluentui-react-button-1c22fee6-e864-44ba-a17b-870a36fa1401.json
- change/@fluentui-react-checkbox-553b2995-3092-41c6-ae3d-6040760a203e.json
- change/@fluentui-react-divider-dc0cfc63-6c4f-4bc8-b932-d39596abac11.json
- change/@fluentui-react-link-137c981e-bd74-4db1-8ea0-1514bcfc3342.json
- packages/react-button/etc/react-button.api.md
- packages/react-button/src/components/Button/__snapshots__/Button.test.tsx.snap
- packages/react-button/src/components/Button/index.ts
- packages/react-button/src/components/Button/useButtonStyles.ts
- packages/react-button/src/components/CompoundButton/index.ts
- packages/react-button/src/components/CompoundButton/useCompoundButtonStyles.ts
- packages/react-button/src/components/MenuButton/index.ts
- packages/react-button/src/components/MenuButton/useMenuButtonStyles.ts
- packages/react-button/src/components/SplitButton/index.ts
- packages/react-button/src/components/SplitButton/useSplitButtonStyles.ts
- packages/react-button/src/components/ToggleButton/index.ts
- packages/react-button/src/components/ToggleButton/useToggleButtonStyles.ts
- packages/react-checkbox/etc/react-checkbox.api.md
- packages/react-checkbox/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts
- packages/react-divider/etc/react-divider.api.md
- packages/react-divider/src/components/Divider/__snapshots__/Divider.test.tsx.snap
- packages/react-divider/src/components/Divider/useDividerStyles.ts
- packages/react-link/etc/react-link.api.md
- packages/react-link/src/components/Link/__snapshots__/Link.test.tsx.snap
- packages/react-link/src/components/Link/useLinkStyles.ts
✅ _Extracted from #20383, these changes passed conformance test on that PR_ 
This PR adds static classes to components `@fluentui/react-button`, `@fluentui/react-checkbox`, `@fluentui/react-divider` & `@fluentui/react-link`.
> feat(button, checkbox, divider, link): add static classes

- packages/fluentui/CHANGELOG.md
Adding missing changelog entry for #20230.
fyi @jurokapsiar
> Add changelog entry for focus border radius change

- change/office-ui-fabric-react-4617e8a0-e4df-4c14-9f0d-b8d1d53e981c.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.test.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.types.ts
- packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsRow.test.tsx.snap
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Announced.BulkOperations.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Announced.QuickActions.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Advanced.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Animation.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Basic.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.ColumnResize.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Compact.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.CustomColumns.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.CustomFooter.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.CustomRows.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Documents.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.NavigatingFocus.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.ProportionalColumns.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/FocusZone.List.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Text.Ramp.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Text.Weights.Example.tsx.shot
- packages/react-examples/src/react-focus/__snapshots__/FocusZone.List.Example.tsx.shot
> [v7] DetailsList aria-rowindex off-by-one fix

- change/@fluentui-react-menu-01ee7588-27c9-41b0-9b26-991881aeb28e.json
- packages/react-menu/etc/react-menu.api.md
- packages/react-menu/src/components/MenuList/MenuList.types.ts
Adds typings for arguments provided by `onCheckedValueChange` method.
> react-menu: onCheckedValueChange typings

- package.json
- yarn.lock
Bumps export to codesandbox addon which includes
microsoft/fluentui-storybook-addons#9 that will transform all exports in
stories to use `@fluentui/react-components`
(optional)
> chore(storybook): Bump export to codesandbox addon

- change/@fluentui-react-components-78530b38-3ba1-4ce5-ac77-dcbb631a32d9.json
- packages/react-components/.storybook/preview.js
- packages/react-components/src/Concepts/Positioning/Positioning.stories.tsx
> chore(docs): Rename `Positioning` docs to `Positinoing Components`

- package.json
- yarn.lock
Picks up change microsoft/fluentui-storybook-addons#11 which is a
temporary workaround for microsoft/fluentui-storybook-addons#12
(optional)
> chore(storybook): Bump export to codesandbox

- change/@fluentui-react-divider-d19eaff3-ee61-4476-a4ab-1c18d17f2222.json
- packages/react-divider/src/stories/DividerAlignContent.stories.tsx
- packages/react-divider/src/stories/DividerAppearance.stories.tsx
- packages/react-divider/src/stories/DividerCustomStyles.stories.tsx
- packages/react-divider/src/stories/DividerDefault.stories.tsx
- packages/react-divider/src/stories/DividerInset.stories.tsx
- packages/react-divider/src/stories/DividerVertical.stories.tsx
> chore(Divider): Remove unthemed white background in stories

- change/@fluentui-react-components-8a479f52-b328-4abe-a5bc-66cf4bbb0c6e.json
- packages/react-components/src/DocsComponents/FluentDocsPage.stories.tsx
update Fluent docs page to use makestyles and flex for layout
(optional)
> Docs: Fluentdoc style update

- change/@uifabric-file-type-icons-dfc2d37d-ab58-44fd-8787-3a0be5285440.json
- packages/file-type-icons/src/FileTypeIconMap.ts
- packages/file-type-icons/src/initializeFileTypeIcons.tsx
> New filetype icon for Loop files [v7]

- change/@fluentui-react-file-type-icons-4bc015c3-9bec-4fa4-a2c4-4afe2c6dc159.json
- packages/react-file-type-icons/src/FileTypeIconMap.ts
- packages/react-file-type-icons/src/initializeFileTypeIcons.tsx
> New filetype icon for Loop files [Fluent v8]

- change/@fluentui-react-divider-ecbf8e01-2833-4f4f-b748-9a66c6d72e18.json
- packages/react-divider/Spec.md
- packages/react-divider/src/components/Divider/Divider.types.ts
Divider: Updating Spec to reflect changes that have happened since it was first created.
> Divider: Updating Spec to reflect changes that have happened since it was first created

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Accordion/Accordion.tsx
- packages/fluentui/react-northstar/src/components/Accordion/AccordionContent.tsx
- packages/fluentui/react-northstar/src/components/Accordion/AccordionTitle.tsx
Properly pass ref in accordion components
(optional)
> refactor(Accordion): make accordion components to properly pass ref

- packages/fluentui/react-northstar/src/components/Alert/Alert.tsx
- packages/fluentui/react-northstar/src/components/Alert/AlertDismissAction.tsx
Refactoring `Alert` components to properly pass down refs
(optional)
> refactor: Alert component to properly pass ref

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Avatar/Avatar.tsx
- packages/fluentui/react-northstar/src/components/Avatar/AvatarIcon.tsx
- packages/fluentui/react-northstar/src/components/Avatar/AvatarImage.tsx
- packages/fluentui/react-northstar/src/components/Avatar/AvatarLabel.tsx
- packages/fluentui/react-northstar/src/components/Avatar/AvatarStatus.tsx
- packages/fluentui/react-northstar/src/components/Avatar/AvatarStatusIcon.tsx
`Avatar` components to properly pass down refs
(optional)
> fix: make avatar component to properly pass down ref

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Button/ButtonGroup.tsx
Fix `ButtonGroup` component to properly pass down ref. 
(optional)
> fix: ButtonGroup component to properly pass down ref

- nx.json
- workspace.json
- ~[ ] Addresses an existing issue:~
To mitigate overhead with additional files changes while running migrate-converged-pkg generator, this manually runs format on nx config files. which alphabetically orders projects
(optional)
> style(nx): run formater on config files

- change/@fluentui-react-components-606e9461-6701-4f81-bbeb-0f39f5270757.json
- packages/react-components/README.md
- packages/react-components/src/AccessibilityScenarios/Menu.stories.tsx
- packages/react-components/src/Concepts/Introduction.stories.mdx
Update status message for beta release to reflect state of the repo/packages
> fix(Docs): Update status message for beta release

- change/@fluentui-bundle-size-71b61350-cea8-4c89-8e0f-e9c410d44cef.json
- packages/bundle-size/src/utils/buildFixture.js
- packages/bundle-size/src/utils/buildFixture.test.js
Adds verification to compilation errors on webpack
> bundle-size: verify compilation errors

- change/@fluentui-make-styles-7c9c90d6-0994-4331-8525-804f4251486f.json
- packages/make-styles/package.json
- yarn.lock
Bumps rtl-css-js to consume changes from kentcdodds/rtl-css-js#62
(optional)
> fix(makeStyles): bump rtl-css-js

- change/@fluentui-react-efad88e8-840e-41a5-83d0-e2e794f7912d.json
- packages/react/src/components/ResizeGroup/ResizeGroup.base.tsx
> ResizeGroup: Adds root element ref to async.requestAnimationFrame invocation

- change/@fluentui-react-307ba9be-62e9-4f2b-ae20-b12104019cc1.json
- packages/react-examples/src/react/__snapshots__/DocumentCard.Compact.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DocumentCard.Complete.Example.tsx.shot
- packages/react/src/components/DocumentCard/DocumentCardPreview.base.tsx
Fixes spreading on `linkProps` on `DocumentCardPreviewBase` component
> Fixes spreading on `linkProps` on `DocumentCardPreviewBase` component

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Card/Card.tsx
- packages/fluentui/react-northstar/src/components/Card/CardBody.tsx
- packages/fluentui/react-northstar/src/components/Card/CardColumn.tsx
- packages/fluentui/react-northstar/src/components/Card/CardFooter.tsx
- packages/fluentui/react-northstar/src/components/Card/CardHeader.tsx
- packages/fluentui/react-northstar/src/components/Card/CardPreview.tsx
- packages/fluentui/react-northstar/src/components/Card/CardTopControls.tsx
Fix `Card` components to properly pass down refs
> fix: Card components to properly pass down ref

- change/office-ui-fabric-react-7386a048-c3bb-46b9-abb0-f4fdfa6275f7.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx
- packages/office-ui-fabric-react/src/components/Modal/Modal.test.tsx
- packages/office-ui-fabric-react/src/components/Modal/Modal.types.ts
Cherry-pick of this PR: #18298 to v7
> v7 - Fix for blocking modal/dialog always having 'alertdialog' role

- change/@fluentui-react-text-00169b13-dac3-465c-b9c0-898b76a7c8b8.json
- packages/react-text/.storybook/main.js
- packages/react-text/.storybook/tsconfig.json
- packages/react-text/jest.config.js
- packages/react-text/package.json
- packages/react-text/tsconfig.json
- packages/react-text/tsconfig.lib.json
- packages/react-text/tsconfig.spec.json
> react-text - Migrate converged packages to TS Solution style config

- packages/react-radio/.storybook/main.js
- packages/react-radio/.storybook/preview.js
- packages/react-radio/.storybook/tsconfig.json
- packages/react-radio/jest.config.js
- packages/react-radio/package.json
- packages/react-radio/tsconfig.json
- packages/react-radio/tsconfig.lib.json
- packages/react-radio/tsconfig.spec.json
~~- [ ] Include a change request file using `$ yarn change`~~ (private package)
Added migration to new DX ts configs for `react-radio` package
> react-radio: migrate converged packages to TS Solution style config

- change/@fluentui-react-91ebaf1d-631d-4ec7-8194-e46d9cd737e7.json
- packages/react/src/components/DetailsList/DetailsList.base.tsx
Includes an update in https://github.com/microsoft/fluentui/pull/20659 for v8
> fix(Detailslist): preserve selectAllButtonProps in group header props

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Chat/Chat.tsx
- packages/fluentui/react-northstar/src/components/Chat/ChatItem.tsx
- packages/fluentui/react-northstar/src/components/Chat/ChatMessage.tsx
Fix `Chat` components to properly pass down refs
(optional)
> fix: chat components to properly pass ref

- change/@fluentui-react-6f1bf2c7-4bc7-4dee-abd3-f5b4fcbedf88.json
- change/@fluentui-react-experiments-0d5f34f2-3c88-4d6b-9171-fcd8aa06ddb5.json
- packages/react-examples/src/react-focus/__snapshots__/FocusZone.List.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/Announced.BulkOperations.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/Announced.QuickActions.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DetailsList.Advanced.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DetailsList.Animation.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DetailsList.Basic.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DetailsList.ColumnResize.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DetailsList.Compact.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DetailsList.CustomColumns.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DetailsList.CustomFooter.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DetailsList.CustomGroupHeaders.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DetailsList.CustomRows.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DetailsList.Documents.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DetailsList.Grouped.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DetailsList.Grouped.Large.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DetailsList.NavigatingFocus.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/DetailsList.ProportionalColumns.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/GroupedList.CustomCheckbox.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/Text.Ramp.Example.tsx.shot
- packages/react-examples/src/react/__snapshots__/Text.Weights.Example.tsx.shot
- packages/react-experiments/src/components/Tile/Tile.tsx
- packages/react/etc/react.api.md
- packages/react/src/components/DetailsList/DetailsRow.base.tsx
- packages/react/src/components/DetailsList/DetailsRow.types.ts
- packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
- packages/react/src/components/DetailsList/__snapshots__/DetailsRow.test.tsx.snap
Added new prop `getRowAriaDescription` to DetailsRow component to add aria-description to the row div html
(optional)
> Added support for aria description to details row

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Datepicker/Datepicker.tsx
- packages/fluentui/react-northstar/src/components/Datepicker/DatepickerCalendar.tsx
- packages/fluentui/react-northstar/src/components/Datepicker/DatepickerCalendarHeader.tsx
Fix `Datepicker` components to properly pass ref to root slots 
(optional)
> fix: datepicker components to properly pass ref

- change/@fluentui-bundle-size-395323f7-094c-4e38-82d4-56e3640c8a8e.json
- package.json
- packages/bundle-size/package.json
- packages/bundle-size/src/commands/uploadReport.js
- yarn.lock
> bundle-size: adds missing dependencies

- .devops/templates/tools.yml
> chore: updating CI to node 14

- packages/react-examples/src/react/ScrollablePane/ScrollablePane.DetailsList.Example.tsx
Sets a missing prop so checkboxes have labels. Example-only change.
> ScrollablePane example: set checkbutton label for detailslist

- change/@fluentui-react-make-styles-bb29a443-6d63-44da-b0ac-a49004304a0b.json
- packages/react-make-styles/.npmignore
- packages/react-make-styles/.storybook/main.js
- packages/react-make-styles/.storybook/preview.js
- packages/react-make-styles/.storybook/tsconfig.json
- packages/react-make-styles/config/api-extractor.local.json
- packages/react-make-styles/jest.config.js
- packages/react-make-styles/package.json
- packages/react-make-styles/tsconfig.json
- packages/react-make-styles/tsconfig.lib.json
- packages/react-make-styles/tsconfig.spec.json
- Reverted changes in `.babelrc` (issue created ##20727)
- Reverted changes in `package.json#devDependencies` (the same problem, #20727)
> chore: run migration for @fluentui/react-make-styles

- change/@fluentui-react-badge-2e30a51b-3c1d-45ab-b09c-4d64fc8a4831.json
- packages/react-badge/.npmignore
- packages/react-badge/.storybook/main.js
- packages/react-badge/.storybook/preview.js
- packages/react-badge/.storybook/tsconfig.json
- packages/react-badge/config/api-extractor.local.json
- packages/react-badge/jest.config.js
- packages/react-badge/package.json
- packages/react-badge/src/stories/BadgeAppearance.stories.tsx
- packages/react-badge/src/stories/BadgeColor.stories.tsx
- packages/react-badge/src/stories/BadgeDefault.stories.tsx
- packages/react-badge/src/stories/BadgeIcon.stories.tsx
- packages/react-badge/src/stories/BadgeShapes.stories.tsx
- packages/react-badge/src/stories/BadgeSizes.stories.tsx
- packages/react-badge/src/stories/CounterBadgeAppearance.stories.tsx
- packages/react-badge/src/stories/CounterBadgeColor.stories.tsx
- packages/react-badge/src/stories/CounterBadgeDefault.stories.tsx
- packages/react-badge/src/stories/CounterBadgeDot.stories.tsx
- packages/react-badge/src/stories/CounterBadgeShapes.stories.tsx
- packages/react-badge/src/stories/CounterBadgeSizes.stories.tsx
- packages/react-badge/src/stories/PresenceBadgeDefault.stories.tsx
- packages/react-badge/src/stories/PresenceBadgeOutOfOffice.stories.tsx
- packages/react-badge/src/stories/PresenceBadgeSizes.stories.tsx
- packages/react-badge/src/stories/PresenceBadgeStatus.stories.tsx
- packages/react-badge/tsconfig.json
- packages/react-badge/tsconfig.lib.json
- packages/react-badge/tsconfig.spec.json
> chore(Badge): Migrate to solution style tsconfigs

- change/@fluentui-react-context-selector-6f8477f4-93fd-48fe-a004-095dd69bb7d6.json
- packages/react-context-selector/.babelrc.json
- packages/react-context-selector/.npmignore
- packages/react-context-selector/config/api-extractor.local.json
- packages/react-context-selector/jest.config.js
- packages/react-context-selector/package.json
- packages/react-context-selector/tsconfig.json
- packages/react-context-selector/tsconfig.lib.json
- packages/react-context-selector/tsconfig.spec.json
- Removed `.storybook` and related `package.json#scripts` (the same as #20724)
> chore: run migration for @fluentui/react-context-selector

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Flex/Flex.tsx
Fix `Flex` component to properly pass ref to root slot
(optional)
> fix: flex component to properly pass down ref

- change/@fluentui-keyboard-keys-489ea6dc-51a9-4fa1-8b26-98709142506d.json
- packages/keyboard-keys/.babelrc.json
- packages/keyboard-keys/.npmignore
- packages/keyboard-keys/config/api-extractor.local.json
- packages/keyboard-keys/config/tests.js
- packages/keyboard-keys/jest.config.js
- packages/keyboard-keys/package.json
- packages/keyboard-keys/tsconfig.json
- packages/keyboard-keys/tsconfig.lib.json
- packages/keyboard-keys/tsconfig.spec.json
- Removed Storybook related scripts & files
- Added `--passWithNoTests`
> chore: migrate @fluentui/keyboard-keys

- change/@fluentui-react-aria-b846e53f-7462-49de-8c81-8cc97493c9c3.json
- nx.json
- packages/react-aria/.babelrc.json
- packages/react-aria/.npmignore
- packages/react-aria/.storybook/main.js
- packages/react-aria/.storybook/preview.js
- packages/react-aria/.storybook/tsconfig.json
- packages/react-aria/config/api-extractor.json
- packages/react-aria/config/api-extractor.local.json
- packages/react-aria/jest.config.js
- packages/react-aria/package.json
- packages/react-aria/tsconfig.json
- packages/react-aria/tsconfig.lib.json
- packages/react-aria/tsconfig.spec.json
> chore: migrate @fluentui/react-aria

- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
> fix(tools): properly check for javascript files within isJs helper

- change/@fluentui-react-conformance-make-styles-b408f2b8-a6f0-4557-a2f4-d9bf2bb756bc.json
- packages/react-conformance-make-styles/.npmignore
- packages/react-conformance-make-styles/config/api-extractor.local.json
- packages/react-conformance-make-styles/jest.config.js
- packages/react-conformance-make-styles/package.json
- packages/react-conformance-make-styles/tsconfig.json
- packages/react-conformance-make-styles/tsconfig.lib.json
- packages/react-conformance-make-styles/tsconfig.spec.json
- Removed Storybook related in `package.json#scripts` (#20745)
- Removed `.babelrc` (#20746)
- Add `jest` to `tsconfig.lib.json#compilerOptions.types`
> chore: migrate @fluentui/react-conformance-make-styles

- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
Added the `--passWithNoTests` flag in the nx generator: `migrate-converged-pkg`.
> migrate-converged-pkg: added passWithNoTests flag

- tools/generators/migrate-converged-pkg/index.ts
- ~[ ] Addresses an existing issue: Fixes ~
- leftover or automerge https://github.com/microsoft/fluentui/pull/20762#discussion_r756272571
(optional)
> style(tools): remove console.log leftovers

- packages/react-storybook/.babelrc.json
- packages/react-storybook/.npmignore
- packages/react-storybook/.storybook/main.js
- packages/react-storybook/.storybook/tsconfig.json
- packages/react-storybook/config/api-extractor.local.json
- packages/react-storybook/jest.config.js
- packages/react-storybook/package.json
- packages/react-storybook/tsconfig.json
- packages/react-storybook/tsconfig.lib.json
- packages/react-storybook/tsconfig.spec.json
> chore: Migrate package @fluentui/react-storybook

- change/@fluentui-react-provider-0ac9b09d-83cf-4b70-b51f-dac7e01f3641.json
- packages/react-provider/src/stories/FluentProviderDefault.stories.tsx
- packages/react-provider/src/stories/FluentProviderDir.stories.tsx
- packages/react-provider/src/stories/FluentProviderFrame.stories.tsx
- packages/react-provider/src/stories/FluentProviderNested.stories.tsx
This PR updates stories to not use CSS shorthands. Also removes `codesandbox-dependency` comments.
> chore(react-provider): update stories to not use CSS shorthands

- change/@fluentui-react-components-23d94665-fbc3-4d37-95f7-5e5ed1c5eeee.json
- packages/react-components/src/Concepts/Positioning/PositioningCoverTarget.stories.tsx
- packages/react-components/src/Concepts/Positioning/PositioningShorthandPositions.stories.tsx
- packages/react-components/src/DocsComponents/FluentDocsHeader.stories.tsx
- packages/react-components/src/DocsComponents/FluentDocsPage.stories.tsx
- packages/react-components/src/DocsComponents/Toc.stories.tsx
This PR updates stories to not use CSS shorthands.
> chore(react-components): update stories to not use CSS shorthands in styles

- change/@fluentui-react-portal-103d126c-9b1b-499d-8f1a-d85917c7face.json
- packages/react-portal/src/stories/PortalDefault.stories.tsx
- packages/react-portal/src/stories/PortalNested.stories.tsx
This PR updates stories to not use CSS shorthands. Also removes `codesandbox-dependency` comments.
> chore(react-portal): update stories to not use CSS shorthands in styles

- packages/react-storybook-addon/.npmignore
- packages/react-storybook-addon/.storybook/main.js
- packages/react-storybook-addon/.storybook/tsconfig.json
- packages/react-storybook-addon/config/api-extractor.local.json
- packages/react-storybook-addon/jest.config.js
- packages/react-storybook-addon/package.json
- packages/react-storybook-addon/src/index.ts
- packages/react-storybook-addon/tsconfig.json
- packages/react-storybook-addon/tsconfig.lib.json
- packages/react-storybook-addon/tsconfig.spec.json
Ran `migrate-converged-pkg` for the `@fluentui/react-storybook-addon` package.
> chore: Migrate package @fluentui/react-storybook-addon

- rfcs/testing.md
This RFC aims to standardize how we do the tests and what the tests should focus on, on a high level.
[Preview](https://github.com/microsoft/fluentui/blob/2f98f1bd575a69b5e54128d6c1df079493c7504c/rfcs/testing.md)
> RFC - Standards for testing

- packages/react-tabs/Spec.md
- Authored react-tabs spec
[Spec Preview](https://github.com/microsoft/fluentui/blob/79be55d9c98511123aa05b56b171928c46fe367e/packages/react-tabs/Spec.md)
> react-tabs spec

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/MenuButton/MenuButton.tsx
Fix ` MenuButton`  to properly pass ref to root slot. 
(optional)
> fix: MenuButton to properly pass ref to root slot

- change/@fluentui-react-slider-e5eb2b9f-5c8e-43d2-b31a-39b735608627.json
- packages/react-slider/.npmignore
- packages/react-slider/.storybook/main.js
- packages/react-slider/.storybook/tsconfig.json
- packages/react-slider/config/api-extractor.local.json
- packages/react-slider/jest.config.js
- packages/react-slider/package.json
- packages/react-slider/tsconfig.json
- packages/react-slider/tsconfig.lib.json
- packages/react-slider/tsconfig.spec.json
Ran `migrate-converged-pkg` for the `@fluentui/react-slider` package.
> chore: run migration for @fluentui/react-slider

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Pill/Pill.tsx
- packages/fluentui/react-northstar/src/components/Pill/PillAction.tsx
- packages/fluentui/react-northstar/src/components/Pill/PillContent.tsx
- packages/fluentui/react-northstar/src/components/Pill/PillGroup.tsx
- packages/fluentui/react-northstar/src/components/Pill/PillIcon.tsx
- packages/fluentui/react-northstar/src/components/Pill/PillImage.tsx
Fix `Pill` components to properly pass ref to root slots.
(optional)
> fix: Pill components to properly pass down ref to root slot

- .github/CODEOWNERS
Tries to reduce bus factor
(optional)
> Add teams-prg and cxe-red as codeowners of `react-badge`

- change/@fluentui-react-avatar-bd3b5ed3-67de-4767-814a-7550603213db.json
- packages/react-avatar/.npmignore
- packages/react-avatar/.storybook/main.js
- packages/react-avatar/.storybook/preview.js
- packages/react-avatar/.storybook/tsconfig.json
- packages/react-avatar/config/api-extractor.local.json
- packages/react-avatar/jest.config.js
- packages/react-avatar/package.json
- packages/react-avatar/tsconfig.json
- packages/react-avatar/tsconfig.lib.json
- packages/react-avatar/tsconfig.spec.json
Migration of `react-avatar`, see linked issue.
> react-avatar: migrate converged packages to TS Solution style config

- change/@fluentui-react-tooltip-9b2e7c58-b7c8-4dd3-ae0f-0284872b2bc6.json
- packages/react-tooltip/.npmignore
- packages/react-tooltip/.storybook/main.js
- packages/react-tooltip/.storybook/tsconfig.json
- packages/react-tooltip/config/api-extractor.local.json
- packages/react-tooltip/jest.config.js
- packages/react-tooltip/package.json
- packages/react-tooltip/tsconfig.json
- packages/react-tooltip/tsconfig.lib.json
- packages/react-tooltip/tsconfig.spec.json
Ran `migrate-converged-pkg` for the `@fluentui/react-tooltip` package.
> chore: run migration for @fluentui/react-tooltip

- change/@uifabric-experiments-9f37ece4-21bf-4e15-95ba-9c3c88ca52c9.json
- change/office-ui-fabric-react-0e240943-914b-4d65-ba35-3c0aa2d26631.json
- packages/experiments/src/components/Tile/Tile.tsx
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.types.ts
- packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
- packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsRow.test.tsx.snap
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Announced.BulkOperations.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Announced.QuickActions.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Advanced.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Animation.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Basic.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.ColumnResize.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Compact.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.CustomColumns.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.CustomFooter.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.CustomGroupHeaders.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.CustomRows.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Documents.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Grouped.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Grouped.Large.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.NavigatingFocus.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.ProportionalColumns.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/FocusZone.List.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/GroupedList.CustomCheckbox.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Text.Ramp.Example.tsx.shot
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/Text.Weights.Example.tsx.shot
- packages/react-examples/src/react-focus/__snapshots__/FocusZone.List.Example.tsx.shot
> Cherry pick: that adds aria description for details row and Tile view

- packages/react-input/.npmignore
- packages/react-input/.storybook/main.js
- packages/react-input/.storybook/preview.js
- packages/react-input/.storybook/tsconfig.json
- packages/react-input/config/api-extractor.local.json
- packages/react-input/jest.config.js
- packages/react-input/package.json
- packages/react-input/tsconfig.json
- packages/react-input/tsconfig.lib.json
- packages/react-input/tsconfig.spec.json
~~- [ ] Include a change request file using `$ yarn change`~~ (private package)
Migration of `react-input`, check linked issue above.
> react-input: migrate converged packages to TS Solution style config

- change/@fluentui-react-switch-0a09552d-9570-44d6-bc7e-4b299f623a81.json
- packages/react-switch/.storybook/main.js
- packages/react-switch/.storybook/tsconfig.json
- packages/react-switch/jest.config.js
- packages/react-switch/package.json
- packages/react-switch/src/Switch.stories.tsx
- packages/react-switch/tsconfig.json
- packages/react-switch/tsconfig.lib.json
- packages/react-switch/tsconfig.spec.json
Ran `migrate-converged-pkg` for the `@fluentui/react-switch` package.
> chore: run migration for @fluentui/react-switch

- change/@fluentui-react-link-10b398c8-530e-47b1-a449-d0e91edf1358.json
- packages/react-link/.npmignore
- packages/react-link/.storybook/main.js
- packages/react-link/.storybook/preview.js
- packages/react-link/.storybook/tsconfig.json
- packages/react-link/config/api-extractor.json
- packages/react-link/config/api-extractor.local.json
- packages/react-link/jest.config.js
- packages/react-link/package.json
- packages/react-link/tsconfig.json
- packages/react-link/tsconfig.lib.json
- packages/react-link/tsconfig.spec.json
Ran `migrate-converged-pkg` for the `@fluentui/react-link` package.
> chore: run migration for @fluentui/react-link

- change/@fluentui-react-positioning-9f126186-944d-4afa-8fdf-b11ba731e674.json
- packages/react-positioning/src/createArrowStyles.ts
> fix: Popover, Tooltip: RTL arrow positioning broken

- change/@fluentui-react-divider-0fd1d54d-055b-41ed-ba31-3544c617f008.json
- packages/react-divider/.npmignore
- packages/react-divider/.storybook/main.js
- packages/react-divider/.storybook/preview.js
- packages/react-divider/.storybook/tsconfig.json
- packages/react-divider/config/api-extractor.json
- packages/react-divider/config/api-extractor.local.json
- packages/react-divider/jest.config.js
- packages/react-divider/package.json
- packages/react-divider/tsconfig.json
- packages/react-divider/tsconfig.lib.json
- packages/react-divider/tsconfig.spec.json
Migrating `react-divider`, see the linked issue above.
> react-divider: migrate converged packages to TS Solution style config

- change/@fluentui-react-checkbox-14a22af0-b249-4d10-b439-677ef71d976a.json
- packages/react-checkbox/.babelrc.json
- packages/react-checkbox/.npmignore
- packages/react-checkbox/.storybook/main.js
- packages/react-checkbox/.storybook/tsconfig.json
- packages/react-checkbox/config/api-extractor.local.json
- packages/react-checkbox/jest.config.js
- packages/react-checkbox/package.json
- packages/react-checkbox/tsconfig.json
- packages/react-checkbox/tsconfig.lib.json
- packages/react-checkbox/tsconfig.spec.json
Migration of `react-checkbox`, see linked issue above.
> react-checkbox: migrate converged packages to TS Solution style config

- change/@fluentui-react-menu-6444eccd-5175-42b5-aa6e-f782a8543cb5.json
- packages/react-menu/src/components/MenuItem/MenuItem.tsx
- packages/react-menu/src/components/MenuItem/useMenuItemStyles.ts
> fix(Menu): Call `useCheckmarkStyles` in `useMenuItemStyles`

- change/@fluentui-react-44f941a3-4706-4f1c-bf01-5d6d06975a09.json
- packages/react/src/components/SearchBox/SearchBox.styles.tsx
See for details https://github.com/microsoft/fluentui/issues/20938#issuecomment-987909119.
> SearchBox: disable pointer events when is focused

- apps/vr-tests/src/stories/Badge.stories.tsx
- change/@fluentui-react-badge-68715606-1e6e-4585-bd2b-45040dc3ce02.json
- packages/react-badge/package.json
- packages/react-badge/src/components/Badge/useBadgeStyles.ts
> fix(Badge): use updated tokens for ghost and outline variants

- change/@fluentui-react-menu-0f0bbbe2-77b9-4d88-8489-f48359369591.json
- packages/react-menu/e2e/selectors.ts
- packages/react-menu/etc/react-menu.api.md
- packages/react-menu/src/components/Menu/__snapshots__/Menu.test.tsx.snap
- packages/react-menu/src/components/MenuTrigger/MenuTrigger.test.tsx
- packages/react-menu/src/components/MenuTrigger/MenuTrigger.types.ts
- packages/react-menu/src/components/MenuTrigger/__snapshots__/MenuTrigger.test.tsx.snap
- packages/react-menu/src/components/MenuTrigger/useTriggerElement.test.tsx
- packages/react-menu/src/components/MenuTrigger/useTriggerElement.ts
Behaviour as in the issue
(optional)
> fix(Menu): set `aria-expanded` and `aria-haspopup` values correctly

- change/office-ui-fabric-react-579113f5-8058-4625-9203-afb7a4dfb932.json
- packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.styles.tsx
Backport of #20951. See for details https://github.com/microsoft/fluentui/issues/20938#issuecomment-987909119.
> SearchBox: disable pointer events when is focused (backport to v7)

- change/@fluentui-react-components-5236c016-fa0e-471b-9acb-9e2be4a7685d.json
- packages/react-components/src/Concepts/Accessibility/AccessibleExperiences.stories.mdx
Add more explanation links to V9 accessibility stories for better understanding of concepts
> docs(Accessibility) Add more explanation links to V9 accessibility stories

- tools/generators/version-bump/README.md
- tools/generators/version-bump/index.spec.ts
- tools/generators/version-bump/index.ts
- tools/generators/version-bump/schema.json
- tools/generators/version-bump/schema.ts
When bumping v9 packages, allows a set of packages to be excluded from the bump
(optional)
> chore: Add `exclude` argument for version bump generator

- rfcs/build-system/01_convergence_devstack.md
- [N/A] Addresses an existing issue: Fixes #0000
- [N/A] Include a change request file using `$ yarn change`
Fixed typo toolign -> tooling
(optional)
> Fixed typo

- change/@fluentui-react-utilities-e33198df-f7e7-4f3e-a3b5-f177e43f387f.json
- packages/react-utilities/package.json
- packages/react-utilities/src/hooks/useMount.test.tsx
- packages/react-utilities/src/hooks/useUnmount.test.tsx
> chore: Remove enzyme from react-utilities tests

- change/@fluentui-react-divider-86585826-b3c4-4272-93fa-4d7a13f34611.json
- packages/react-divider/src/stories/DividerAlignContent.stories.tsx
- packages/react-divider/src/stories/DividerAppearance.stories.tsx
- packages/react-divider/src/stories/DividerCustomStyles.stories.tsx
- packages/react-divider/src/stories/DividerDescription.md
- packages/react-divider/src/stories/DividerInset.stories.tsx
- packages/react-divider/src/stories/DividerVertical.stories.tsx
Added missing descriptions to stories for the divider component.
This slipped through during the documentation scrub.
(optional)
> Added missing descriptions to divider stories

- packages/fluentui/react-icons-northstar/README.md
Simple update for package name in the readme
> chore: update package name in readme

- .github/CODEOWNERS
Change CODEOWNERS file to reflect the new ownership of react-radio.
@microsoft/cxe-red let me know who/if you'd like to also have a specific person marked as an owner.
> chore(react-radio) - Change ownership

- .github/PULL_REQUEST_TEMPLATE.md
- based on team discussion this is initial step of simplifying PR template for all contributors
- please note that this is a living thing and we will iterate on it after trying out, thanks for understanding
- as there are various sources of truth for `CONTRIBUTING` guidelines I didn't create new one for now (https://github.com/microsoft/fluentui/wiki/Contributing, https://github.com/microsoft/fluentui/blob/master/packages/fluentui/CONTRIBUTING.md )
(optional)
> docs(.github): update PR template

- change/@fluentui-react-theme-6367506a-f6be-4858-acee-56a229d62667.json
- packages/react-theme/bundle-size/SingleThemeToken.fixture.js
#21026 added tokens to be used in `makeStyles()` calls. This PR adds a bundle size fixture to verify those tokens are correctly tree shaken
```sh
> yarn bundle-size
┌───────────────────────────┬───────────────┬───────────┐
│ Fixture                   │ Minified size │ GZIP size │
├───────────────────────────┼───────────────┼───────────┤
│ Single theme token import │ 69 B          │ 89 B      │
└───────────────────────────┴───────────────┴───────────┘
```
> chore(react-theme) Add theme tokens bundle size fixture

- change/@fluentui-react-55f24add-1f2f-4771-9a0e-f68612e8ad4e.json
- packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx
> Properly pass menu target to submenu items

- .github/CODEOWNERS
Updated the codeowners file to add cxe-coastal based on web focus areas.
> Updated code owners for cxe-coastal

- change/office-ui-fabric-react-aa8d05b4-7e68-423a-92ee-703fabc8ccd1.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts
- packages/office-ui-fabric-react/src/utilities/contextualMenu/contextualMenuUtility.ts
- packages/react-examples/src/office-ui-fabric-react/CommandBar/CommandBar.Basic.Example.tsx
- packages/react-examples/src/office-ui-fabric-react/__snapshots__/CommandBar.Basic.Example.tsx.shot
> Support ability to set a context menu item's event target to the Menu root

- packages/react-theme/src/tokens.test.ts
`tokens` exported by `react-theme` map all available design tokens to corresponding CSS variables.
Typings guarantee that all theme tokens are defined in the `tokens` object but there is no check the CSS variables have the expected name.
This PR adds a unit test which checks the format of the CSS variables in `tokens`.
> chore(react-theme): Test all tokens use correct CSS variables

- scripts/storybook/runner.js
follow up https://github.com/microsoft/fluentui/pull/21265#discussion_r785068871
> refactor(scripts): use inherit for stdio calls in sb runner

- change/@uifabric-date-time-0a9a1f78-209c-4ab3-beec-7d0e0fb4ec5b.json
- packages/date-time/src/components/CalendarDayGrid/CalendarGridDayCell.tsx
- packages/date-time/src/components/WeeklyDayPicker/__snapshots__/WeeklyDayPicker.test.tsx.snap
v7 backport of a v8 fix, by request: #20412
> v7: fix(Calendar): move gridcell role and focus target from button to td

- apps/perf-test/package.json
> chore: remove react-make-styles devDep from perf-test package

- packages/react-examples/src/react/Button/Button.IconWithTooltip.Example.tsx
- packages/react-examples/src/react/__snapshots__/Button.IconWithTooltip.Example.tsx.shot
The "Icon Button with Tooltip" example does not function properly with screen readers.
The example has been updated to provide a better method for using tooltips with icon buttons that works as expected with screen readers.
Fixes #21027
> Update IconButton Tooltip example

- azure-pipelines.hotfix.yml
- azure-pipelines.release-fluentui.yml
- azure-pipelines.release-vnext-nightly.yml
- azure-pipelines.release-vnext.yml
- azure-pipelines.release.yml
No SBom publish
Release pipelines publish SBom Manifest
> Add SBom generation

- azure-pipelines.hotfix.yml
- azure-pipelines.release.yml
> Add SBom generation (6.0)

- change/@fluentui-react-9793f996-9d92-4ec0-85ac-55accb3ce12d.json
- packages/react/etc/react.api.md
- packages/react/src/components/Facepile/Facepile.base.tsx
- packages/react/src/components/Facepile/Facepile.styles.ts
- packages/react/src/components/Facepile/Facepile.types.ts
- When passing either an `onRenderPersona`and/or `onRenderPersonaCoin` custom renderer to `Facepile` and wrapping each `Persona` in a `TooltipHost`, the tooltip is not visible when a `Persona` (which has an `onClick` attribute) receives keyboard focus. This is because the `TooltipHost` along with the `Persona` are descendents of the rendered `FacepileButton` which means that the `FacepileButton` receives keyboard focus instead, rendering the `TooltipHost` wrapper useless.
- This change adds a new prop called `onRenderPersonaWrapper` which allows consumers to do what `onRenderPersona` and `onRenderPersonaCoin` do but instead of wrapping the `Persona` itself, it wraps the `FacepileButton` which allows for the `TooltipHost` to render whenever the `FacepileButton` receives focus.
- …
> Facepile: Add prop which allows Personas wrapped in a TooltipHost to render that tooltip on keyboard focus.

- azure-pipelines.hotfix.yml
- azure-pipelines.yml
> Add SBom generation (5.79.1)

- azure-pipelines.hotfix.yml
- azure-pipelines.release.yml
> Add SBom generation (7.0)

- packages/fluentui/perf-test-northstar/package.json
> Remove v8 from northstar perf tests

- change/@fluentui-react-avatar-53b27f7e-1335-49ec-871f-fea26c11006d.json
- packages/react-avatar/MIGRATION.md
- packages/react-avatar/SPEC.md
Avatar has changed since the initial spec and migration guide were written.
Update Avatar's Spec.md and Migration.md to match the current state of Avatar.
* Part of #21237
> Update Avatar's Spec.md and Migration.md

- change/office-ui-fabric-react-6e3da868-8721-49ae-aae2-20c3e1e6e487.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.base.tsx
- packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.types.ts
> Cherry-pick Breadcrumb onRenderContent override support

- change/@fluentui-react-focus-6ee43bb0-ff7d-4fb9-9fba-6a9c10f34345.json
- packages/react-focus/src/components/FocusZone/FocusZone.tsx
Fixes an issue with FocusZone and keyboard event handling.
This PR cherry-picks the v8 changes in #21547 onto the 7.0 branch. See #21547 for details.
> Update FocusZone keyboard event handling (Cherrypick of #21547)

- apps/vr-tests-react-components/package.json
- change/@fluentui-react-components-dfb0d2bc-4933-4f59-a34f-b24111288eca.json
- packages/react-components/package.json
- packages/react-components/src/unstable/index.ts
Export the `Checkbox` component and related types from `@fluentui/react-components/unstable`
> Add Checkbox to react-components/unstable

- apps/vr-tests-react-components/package.json
- apps/vr-tests-react-components/src/stories/Positioning.stories.tsx
There are no  vr tests for positioning in v9
Adds positioning vr tests for v9
Fixes #
> chore: Add positioning vr-tests for v9

- .github/CODEOWNERS
Codeowners file was updated to set @microsoft/fluentui-northstar as code owners for N* files.
> chore: update CODEOWNERS for Fluent UI N*

- .github/CODEOWNERS
> Update codeowner team for charting library

- apps/vr-tests-react-components/src/stories/Radio.stories.tsx
Add screener tests for Radio and RadioGroup
> Add screener tests for Radio and RadioGroup

- .github/workflows/pr-housekeeping.yml
This PR fixes a typo in the PR housekeeping workflow name.
> Fixing typo in pr-housekeeping.yml

- .github/CODEOWNERS
This PR updates the CODEOWNERS file to remove errors from people without write access to the repository. It also assigns the correct reviewers for date time controls.
> Updating CODEOWNERS file to remove errors from people without write access to the repository

- packages/fluentui/docs/src/examples/components/Carousel/Variations/CarouselSlideAnimationExample.shorthand.tsx
- packages/fluentui/docs/src/examples/components/Carousel/Variations/index.tsx
- packages/fluentui/react-northstar/src/components/Carousel/Carousel.tsx
- packages/fluentui/react-northstar/src/components/Carousel/utils.ts
- packages/fluentui/react-northstar/test/specs/components/Carousel/Carousel-test.tsx
This PR should not change current `Carousel` animation behavior but allow user to define new kind of animations, as in the new example provided here.
> feat: add ability to change carousel animation

- change/@fluentui-web-components-45efd5aa-2bdc-492e-a61e-317b5fe39d24.json
- packages/web-components/package.json
- yarn.lock
> (web-components): update karma dependency version

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-bindings/src/compose/consts.ts
- packages/fluentui/react-builder/src/components/BrowserWindow.tsx
- packages/fluentui/react-northstar/src/types.ts
Replace ReactNodeArray type with ReactNode
> fix(types): Remove ReactNodeArray type

- apps/vr-tests-react-components/src/stories/Image.stories.tsx
- apps/vr-tests/src/stories/FolderCover.stories.tsx
- apps/vr-tests/src/stories/GroupedList.stories.tsx
- apps/vr-tests/src/stories/Image.stories.tsx
- apps/vr-tests/src/stories/List.stories.tsx
- apps/vr-tests/src/stories/TeachingBubble.stories.tsx
- apps/vr-tests/src/stories/Tile.stories.tsx
- packages/react-components/src/Concepts/Positioning/PositioningImperativePositionUpdate.stories.tsx
- packages/react-image/src/stories/ImageBlock.stories.tsx
- packages/react-image/src/stories/ImageDefault.stories.tsx
- packages/react-image/src/stories/ImageFit.stories.tsx
- packages/react-image/src/stories/ImageShadow.stories.tsx
due to ddos, we are using local CDN versions of these images
> update test images to use CDN images

- packages/fluentui/docs/package.json
- packages/fluentui/docs/src/index.ejs
- packages/fluentui/docs/src/index.tsx
- scripts/webpack/webpack.config.ts
- yarn.lock
After upgrade to React 16.14 (#21769) docsite was broken locally:
This PR fixes it 🚀
> fix: update configs for @fluentui/docs to run properly with React 16.14

- change/@uifabric-file-type-icons-491c5efe-0965-4fa5-b6db-8f332e3c9af6.json
- packages/file-type-icons/src/FileIconType.ts
- packages/file-type-icons/src/FileTypeIconMap.ts
- packages/file-type-icons/src/getFileTypeIconProps.ts
- packages/file-type-icons/src/initializeFileTypeIcons.tsx
This will be adding support of Stream Playlist icon
Fixes #
> Adding stream playlist icon support

- packages/fluentui/CHANGELOG.md
Prepare release 0.61.0 of @fluentui/react-northstar
> chore: prepare release react-northstar 0.61.0

- .github/dependabot.yml
- rfcs/build-system/dependency-management.md
Adds an RFC and Dependabot configuration.
Validate that Dependabot works as expected.
> RFC: Automated dependency version management

- change/@fluentui-date-time-utilities-fa79c638-e482-4f87-ac14-70e7580da31f.json
- packages/date-time-utilities/package.json
This is a bump of the date-time-utilities minor version (previous PR https://github.com/microsoft/fluentui/pull/22063 should have been minor and not patch).
> Minor version bump date time utilities

- change/@uifabric-file-type-icons-a9406eef-5281-4f09-8231-ffe184479da1.json
- packages/file-type-icons/src/FileTypeIconMap.ts
- packages/file-type-icons/src/initializeFileTypeIcons.tsx
Files with .nnb or .ipynb extensions get correct icon.
> Adding .ipynb filetype icon support to v7

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams-forced-colors/componentStyles.ts
- packages/fluentui/react-northstar/src/themes/teams-forced-colors/components/Slider/sliderStyles.ts
> fix: Add transparent borders to slider

- change/@fluentui-react-tabster-4ab45d8c-17b1-46af-8228-c6ced2005bf2.json
- packages/react-tabster/README.md
- packages/react-tabster/etc/react-tabster.api.md
- packages/react-tabster/src/hooks/useArrowNavigationGroup.ts
Add `grid` option to `UseArrowNavigationGroupOptions`
> feat(react-tabster): Add grid navigation

- change/@fluentui-react-radio-c4a42c00-807c-4540-b93f-405bb77c35c7.json
- packages/react-radio/etc/react-radio.api.md
- packages/react-radio/src/components/Radio/Radio.test.tsx
- packages/react-radio/src/components/Radio/Radio.types.ts
- packages/react-radio/src/components/Radio/useRadio.tsx
* Add an `onChange` wrapped event to `Radio`, per #18974
> Add onChange event prop to Radio

- common/changes/@uifabric/styling/hotfix_01-hotfix-5.135.6_2022-03-19-05-46.json
- common/changes/office-ui-fabric-react/hotfix_01-hotfix-5.135.6_2022-03-19-05-46.json
- packages/office-ui-fabric-react/src/components/Nav/Nav.styles.ts
- packages/office-ui-fabric-react/src/components/Nav/__snapshots__/Nav.test.tsx.snap
- packages/styling/src/interfaces/ISemanticColors.ts
- packages/styling/src/styles/theme.ts
Port #14933 from office-ui-fabric-react_v5.79.1 to hotfix/5.135.6
For #14933: Port #10008 to update Nav to latest redlines in office-ui-fabric-react/5.79.1
> Port #14933 (Port #10008 to update Nav to latest redlines) from office-ui-fabric-react_v5.79.1 to hotfix/5.135.6

- common/changes/office-ui-fabric-react/hotfix_02-hotfix-5.135.6_2022-03-19-06-11.json
- packages/office-ui-fabric-react/src/components/Dialog/DialogContent.base.tsx
- packages/office-ui-fabric-react/src/components/Dialog/__snapshots__/Dialog.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Panel/Panel.tsx
Port #14944 from office-ui-fabric-react_v5.79.1 to hotfix/5.135.6
For #14944: Port #5782 & #12395 to add aria-level=1 in Dialog/Panel of office-ui-fabric-react/5.79.1
> Port #14944 (Port #5782 & #12395 to add aria-level=1 in Dialog/Panel) from office-ui-fabric-react_v5.79.1 to hotfix/5.135.6

- common/changes/office-ui-fabric-react/hotfix_06-hotfix-5.135.6_2022-03-19-09-39.json
- packages/office-ui-fabric-react/src/components/ActivityItem/__snapshots__/ActivityItem.test.tsx.snap
- packages/office-ui-fabric-react/src/components/DocumentCard/__snapshots__/DocumentCard.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Facepile/__snapshots__/Facepile.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Persona/PersonaCoin/__snapshots__/PersonaCoin.deprecated.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Persona/PersonaCoin/__snapshots__/PersonaCoin.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Persona/PersonaInitialsColor.test.ts
- packages/office-ui-fabric-react/src/components/Persona/PersonaInitialsColor.ts
- packages/office-ui-fabric-react/src/components/Persona/__snapshots__/Persona.deprecated.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Persona/__snapshots__/Persona.test.tsx.snap
Port #16509 from office-ui-fabric-react_v5.79.1 to hotfix/5.135.6
For #16509, Port #8781 & #8905 to update color changes to PersonaInitialColors in office UI fabric react/5.79.1
> Port #16509 (Port #8781 & #8905 to update color changes to PersonaInitialColors) from office-ui-fabric-react_v5.79.1 to hotfix/5.135.6

- common/changes/office-ui-fabric-react/hotfix_10-hotfix-5.135.6_2022-03-20-06-56.json
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.tsx
Fix import path error in DetailsList/DetailsHeader
> Fix import path error in DetailsList/DetailsHeader

- change/office-ui-fabric-react-2aefc144-c899-461e-b312-814d78a83a07.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Layer/Layer.base.tsx
- packages/office-ui-fabric-react/src/components/Layer/Layer.notification.ts
- packages/office-ui-fabric-react/src/components/Layer/LayerHost.tsx
- packages/office-ui-fabric-react/src/components/Layer/LayerHost.types.ts
> [Cherry-pick] Ensure Layer uses the specific element for LayerHost, for advanced projection scenarios

- change/@uifabric-utilities-2bcf64f2-09d2-4ba5-a599-26aff3eea6bc.json
- packages/utilities/etc/utilities.api.md
- packages/utilities/src/selection/Selection.test.ts
- packages/utilities/src/selection/Selection.ts
- packages/utilities/src/selection/Selection.types.ts
> [Cherry-pick] Improve Selection with more micro-management capabilities

- packages/react-accordion/src/stories/Accordion.stories.tsx
- packages/react-accordion/src/stories/AccordionNavigation.stories.tsx
No behavioral changes.
1. Updates storybook for breaking changes introduced on https://github.com/microsoft/fluentui/pull/21729
> react-accordion: Updates Accordion storybook for navigation breaking change

- packages/react-toolbar/Spec.md
This PR adds `Toolbar` initial spec
> docs: add Toolbar spec

- change/office-ui-fabric-react-b9a45794-e721-4867-b35e-0d5540e81a1c.json
- packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/PeoplePickerItems/PeoplePickerItem.styles.ts
- packages/react-examples/src/office-ui-fabric-react/PeoplePicker/PeoplePicker.Normal.Example.tsx
> v7 cherry pick: Added secondary text styling

- packages/react-textarea/bundle-size/Textarea.fixture.js
- packages/react-textarea/package.json
This PR adds the `bundle-size` command to run bundle size fixtures.
Related issue: #21845
> react-textarea: Adding bundle size fixtures

- change/@fluentui-react-charting-0caef860-4f50-4dd7-931f-65eefe8d5139.json
- change/@fluentui-react-charting-a1dde850-c945-46b1-bd5f-eccf42fbdece.json
- packages/react-charting/README.md
> Update readme file for charting project

- apps/vr-tests-react-components/package.json
- apps/vr-tests-react-components/src/stories/Textarea.stories.tsx
This PR adds screener tests for Textarea. 
NOTE: something to be explored is the `resize` prop, should it be tested here?
Related issue: #21845
> react-textarea: Adding screener tests

- rfcs/react-components/convergence/upgrade-code-location.md
RFC for discussion at tech sync for upgrade code location.
> RFC - upgrade code location

- change/@fluentui-react-5bc01262-0d78-453f-95d9-2ffd62adb200.json
- packages/react/etc/react.api.md
- packages/react/src/components/Button/Button.test.tsx
- packages/react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/react/src/components/Layer/Layer.base.tsx
- packages/react/src/components/Layer/Layer.notification.ts
- packages/react/src/components/Layer/index.ts
- packages/react/src/components/Modal/__snapshots__/Modal.test.tsx.snap
Layers which are appended to the end of the document end up invalidating the `body` element, which causes massive recomputation of layout.
Now with the layer appends scoped within a div, the browser can isolate recomputation to only the container div, resulting in faster ContextualMenu rendering.
> Layer: render new layers in a host container div.

- change/@fluentui-react-tooltip-cde84203-627c-4703-9981-efe0a8fc3173.json
- packages/react-tooltip/src/stories/TooltipDescription.md
Updating Tooltip's documentation to add guidance on interactive content. This was brought up in #20127.
Related issue: #21238 and #20127.
> react-tooltip: Updating docs

- change/@uifabric-experiments-8df34765-eb85-4f6e-b8c1-758164d831fb.json
- change/office-ui-fabric-react-92f60eb5-35d4-45e0-b0bd-b1ebbed42b38.json
- packages/experiments/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/experiments/src/components/SelectedItemsList/SelectedPeopleList/SelectedPeopleList.test.tsx
- packages/experiments/src/components/SelectedItemsList/SelectedPeopleList/__snapshots__/SelectedPeopleList.test.tsx.snap
- packages/experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/__snapshots__/UnifiedPeoplePicker.test.tsx.snap
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.test.tsx
- packages/office-ui-fabric-react/src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Persona/Persona.test.tsx
- packages/office-ui-fabric-react/src/components/Persona/PersonaCoin/__snapshots__/PersonaCoin.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Persona/__snapshots__/Persona.deprecated.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Persona/__snapshots__/Persona.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Tooltip/TooltipHost.base.tsx
- packages/office-ui-fabric-react/src/components/Tooltip/TooltipHost.test.tsx
- packages/office-ui-fabric-react/src/components/Tooltip/__snapshots__/TooltipHost.test.tsx.snap
- packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/__snapshots__/PeoplePicker.test.tsx.snap
Tooltips are not properly read by VoiceOver on iOS and iPadOS
Cherry picks changes from https://github.com/microsoft/fluentui/pull/22216 to the 7.0 branch.
- #22216
> Cherry pick voiceover tooltip fix to 7.0

- package.json
- yarn.lock
chore(build) Update version of  to ^11.0.0
> chore(build) Update version of  to ^11.0.0

- packages/react-examples/README.md
react-examples doesn't contain any docs how is it setup nor how it supposed to work
we have basic "about" docs
[👀See the preview](https://github.com/microsoft/fluentui/pull/22374/files?short_path=03b7f09#diff-03b7f091cc1e9a87b7ac6886f06b3b14a128e54ccc39c8f869bdd83ea2d53d4e)
> docs: add some general info about how things work in this package

- rfcs/shared/build-system/03-packaging-for-npm.md
chapters haven't been unified for additions
chapters unified
Every sub-area contains 
- problem statement
- design proposal
- pros and cons
> docs(rfc): restructure packaging rfc for future additions

- change/@fluentui-react-avatar-b36be99f-60ba-4c16-b7b3-a9784afb5709.json
- packages/react-avatar/etc/react-avatar.api.md
- packages/react-avatar/src/AvatarGroup.ts
- packages/react-avatar/src/components/AvatarGroup/AvatarGroup.test.tsx
- packages/react-avatar/src/components/AvatarGroup/AvatarGroup.tsx
- packages/react-avatar/src/components/AvatarGroup/AvatarGroup.types.ts
- packages/react-avatar/src/components/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
- packages/react-avatar/src/components/AvatarGroup/index.ts
- packages/react-avatar/src/components/AvatarGroup/renderAvatarGroup.tsx
- packages/react-avatar/src/components/AvatarGroup/useAvatarGroup.ts
- packages/react-avatar/src/components/AvatarGroup/useAvatarGroupStyles.ts
- packages/react-avatar/src/index.ts
- packages/react-avatar/src/stories/AvatarGroup.stories.tsx
- packages/react-avatar/src/stories/AvatarGroupBestPractices.md
- packages/react-avatar/src/stories/AvatarGroupDefault.stories.tsx
This PR adds the AvatarGroup component to react-avatar and its spec file.
Related: #22240 #22320
> react-avatar: Adding AvatarGroup component.

- packages/react-examples/src/react/ChoiceGroup/ChoiceGroup.Icon.Example.tsx
> Fixed typo in ChoiceGroup example

- change/@fluentui-react-fed44d8e-845d-455b-b5ca-4832a9004939.json
- packages/react/src/utilities/ThemeProvider/makeStyles.ts
> Fix makestyles to re-register styles for objects upon theme change, and avoid memory leak

- change/@fluentui-react-tabster-c81c82d2-9aad-4456-a2fc-9aec50bbf774.json
- packages/react-tabster/package.json
- packages/react-tabster/src/hooks/useArrowNavigationGroup.ts
- packages/react-tabster/src/hooks/useFocusableGroup.ts
- yarn.lock
This PR upgrades the `tabster` dependency to its latest version.
> Upgrading tabster to latest version

- change/@fluentui-react-theme-14614f46-1e92-4db9-8a7a-1589aa7645cf.json
- packages/react-theme/src/alias/darkColor.ts
- packages/react-theme/src/alias/darkColorPalette.ts
- packages/react-theme/src/alias/highContrastColor.ts
- packages/react-theme/src/alias/highContrastColorPalette.ts
- packages/react-theme/src/alias/lightColor.ts
- packages/react-theme/src/alias/lightColorPalette.ts
- packages/react-theme/src/alias/teamsDarkColor.ts
- packages/react-theme/src/alias/teamsDarkColorPalette.ts
- packages/react-theme/src/global/colors.ts
- packages/react-theme/src/utils/createDarkTheme.ts
- packages/react-theme/src/utils/createHighContrastTheme.ts
- packages/react-theme/src/utils/createLightTheme.ts
- packages/react-theme/src/utils/createTeamsDarkTheme.ts
Update yellow shared color for accessibility:
> Fix(react-theme): update yellow shared color

- .github/CODEOWNERS
add cxe-red as  codeowners of utilities (and remove unused utilities/positioning)
> update codeownership of utilities

- change/office-ui-fabric-react-3496a2f3-c3fb-47c9-9d7e-eca093c5416b.json
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.cnstyles.ts
- packages/office-ui-fabric-react/src/components/ContextualMenu/__snapshots__/ContextualMenu.test.tsx.snap
> Cherrypick #22518 "Contextmenu high contrast styles update" to 7.0 

- packages/fluentui/e2e/cypress.json
Northstar test fails on first try
Northstar test fails on third try
Fixes #
> chore: Add retries to northstar e2e tests

- .prettierignore
- tools/generators/migrate-v8-pkg/files/constants.ts__tmpl__
- tools/generators/migrate-v8-pkg/index.spec.ts
- tools/generators/migrate-v8-pkg/index.ts
- tools/generators/migrate-v8-pkg/lib/utils.spec.ts
- tools/generators/migrate-v8-pkg/lib/utils.ts
- tools/generators/migrate-v8-pkg/schema.json
- tools/generators/migrate-v8-pkg/schema.ts
Follows 
- https://github.com/microsoft/fluentui/projects/44#card-78428029
- https://github.com/microsoft/fluentui/pull/22160
> feat(tools): add `--stats` to migrate-v8-pkg generator

- apps/vr-tests-react-components/src/stories/Button.stories.tsx
- change/@fluentui-react-button-e7a62fd5-8be6-462c-b1ae-f1a4bf24bddd.json
- packages/react-button/src/components/Button/useButtonStyles.ts
- packages/react-button/src/components/ToggleButton/useToggleButtonStyles.ts
- packages/react-components/src/DocsComponents/ThemePicker.stories.tsx
Fixes #22464, part of #21998
This PR fixes the text color for high contrast themes in the hover and active states for all `Buttons`, and in the checked states as well for `ToggleButtons`.
> fix(Button): Text color in HC mode for hover, active and checked states

- change/@fluentui-react-checkbox-82b53eb2-608d-4cbb-b524-f08be9e523b9.json
- packages/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts
> Checkbox: Fixing High Contrast disabled styles

- apps/public-docsite/src/styles/_base.scss
!important was a little bit much....trying upping the specificity by 1
> move from important to increasing specificity using body

- apps/public-docsite-v9/package.json
> chore: fix version mismatches

- rfcs/shared/build-system/03-packaging-for-npm.md
Adds shipping types RFC chapter
[Preview 👀](https://github.com/microsoft/fluentui/pull/22469/files?short_path=da942a8#diff-da942a8b306a106a49f511ada3834c66929e8adb5ec1202ce7b24d229fa8d836)
> docs(rfc): update packaging with shipping types rfc

- change/@fluentui-react-components-ecf0d9a5-9c82-4592-bf3b-cb2b5cbb71e6.json
- change/@fluentui-react-theme-f50926d9-9a4d-4bed-a744-cd596264dcee.json
- packages/react-components/etc/react-components.api.md
- packages/react-components/src/index.ts
- packages/react-theme/etc/react-theme.api.md
- packages/react-theme/src/global/index.ts
- packages/react-theme/src/global/typeographyStyles.ts
- packages/react-theme/src/index.ts
- packages/react-theme/src/types.ts
- Added typeography types
- Added typeography constants
- Exported typeography types and constants
Updated #22231
> Add global typeography constants

- .github/CODEOWNERS
Removing myself from code owners for date/calendar components.
> Remove evlevy from codeowners

- change/@fluentui-react-components-d5bd87e3-1ae7-4128-8f04-e0453d955727.json
- change/@fluentui-react-theme-8b1928b3-c74f-4d38-8b67-83bfcecac104.json
- packages/react-components/etc/react-components.api.md
- packages/react-components/src/index.ts
- packages/react-theme/etc/react-theme.api.md
- packages/react-theme/src/global/index.ts
- packages/react-theme/src/global/typographyStyles.ts
- packages/react-theme/src/index.ts
- packages/react-theme/src/types.ts
Misspelled typography, this PR fixes it.
I swear I wasn't trying to be ironic.
> Fixed typo in typography

- rfcs/shared/build-system/03-packaging-for-npm.md
- scripts/api-extractor/api-extractor.common.v-next.json
- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
- tools/types.ts
- Implements migration generator changes based on https://github.com/microsoft/fluentui/pull/22469
- prepares setup for gradual migration (api-extractor issues)
> feat(tools): apply d.ts rolluping setup in migration generator

- apps/public-docsite-v9/src/shims/ButtonShim.tsx
- apps/public-docsite-v9/src/shims/MenuShim.tsx
- apps/public-docsite-v9/src/stories/ButtonShim.stories.tsx
- apps/public-docsite-v9/src/stories/MenuButtonShim.stories.tsx
- Added MenuShim and MenuItemShim to support MenuButtonShim
- Added MenuButtonShim
- Added MenuButtonShim story
Note: There is more shimming for menu to be done as well as SplitButton and CompoundButton shims.
Updates ##22315
> Upgrade: Added MenuButtonShim

- rfcs/react-components/convergence/prop-string-union-naming.md
👀 [PREVIEW](https://github.com/spmonahan/fluentui/blob/d1c153725a225f51a28af7582f9ef7e882e03d1d/rfcs/react-components/convergence/prop-string-union-naming.md) 👀
> RFC: proposal for standard string union naming conventions

- change/@fluentui-react-slider-26d81dd4-fbf6-4174-bd06-0a50bfb3673b.json
- packages/react-components/react-slider/src/components/Slider/useSliderStyles.ts
Fixes #22589
New focus
Old hover
New Hover
> V9 Slider dark mode color and focus tweaks

- .github/CODEOWNERS
Update @ermercer alias with @microsoft/fluent-date-time team alias
> Update @ermercer alias

- change/@fluentui-react-theme-5596637b-8146-4364-8a0b-d49828bc5468.json
- packages/react-theme/src/global/spacings.ts
Don't know how, but the px unit was left off of spacings for the global tokens.  This add them.
Update #22231
> Fix spacing pixels

- yarn.lock
cherry-pick [4b82dac](https://github.com/microsoft/fluentui/commit/4b82dac0f1bcecba8cda7309c01eb98a3b7de46c) to 7.0 branch
> update yarn to use latest version of fabric core (#22755)

- apps/pr-deploy-site/just.config.ts
- apps/pr-deploy-site/pr-deploy-site.js
Update PR deploy site to use new v9 site
> change pr deploy to use v9 website

- change/@fluentui-react-tabs-096353d7-8745-4215-a671-7a5513300672.json
- packages/react-components/react-tabs/src/components/Tab/Tab.test.tsx
- packages/react-components/react-tabs/src/components/Tab/__snapshots__/Tab.test.tsx.snap
- packages/react-components/react-tabs/src/components/Tab/useTab.ts
- packages/react-components/react-tabs/src/components/TabList/TabList.test.tsx
- packages/react-components/react-tabs/src/components/TabList/__snapshots__/TabList.test.tsx.snap
- Added aria-selected true when selected, false when not selected, undefined when not selectable
- Added tests
Fixes #22053
> react-tabs: aria-selected attribute added

- apps/public-docsite-v9/src/Concepts/Upgrade/FromV8/Components/Theme.stories.mdx
- Added initial theme upgrade guide documentation
Upcoming: more example of the theme color mapping with examples.
Updates #22314
> Added initial theme upgrade documentation

- change/@fluentui-react-tabs-310ac94e-8966-40bd-9104-1832889dd07e.json
- packages/react-components/react-tabs/src/components/Tab/useTabStyles.ts
Updated to use pseudo-element selectors with 2 colons
> chore: react-tabs: updated to use correct pseudo-elements

- packages/react-components/react-tooltip/src/stories/TooltipPositioning.stories.tsx
Warnings about missing keys.
No warnings ✅
> docs(Tooltip): fix React keys in stories

- .github/CODEOWNERS
This PR adds Micah and me to the `react-label` codeowners.
> react-label: Add codeowner to react-label package

- packages/react-components/react-select/src/components/Select/useSelectStyles.ts
- Updated react-select to use new shared tokens
Updated #22231
> react-select: Updated to use shared tokens

- change/@fluentui-react-textarea-ac0b5dbd-40ae-41f7-ae97-0e1a7bf798f1.json
- packages/react-components/react-textarea/etc/react-textarea.api.md
- packages/react-components/react-textarea/src/components/Textarea/Textarea.types.ts
This PR adds the following changes:
* Removes Textarea commons type.
> react-textarea: Removing commons type from Textarea.

- change/@fluentui-react-b3835cb8-adcf-4ae3-8d53-7988acc98615.json
- packages/react/README.md
add change file to 7.0 so that a new release is created
since the last change was only an update to the yarn lock, no change file was created, so no release was made with the new packages.
> Add change file to 7.0 branch to initiate release

- scripts/create-component/create-component.ts
Fixes https://github.com/microsoft/fluentui/issues/22847
> fix(scripts): make create-component work for all affected v9 packages

- packages/react-combobox/src/components/ComboButton/useComboButtonStyles.ts
- packages/react-combobox/src/components/Listbox/useListboxStyles.ts
- packages/react-combobox/src/components/Option/useOptionStyles.ts
- packages/react-combobox/src/components/OptionGroup/useOptionGroupStyles.ts
- packages/react-combobox/src/utils/internalTokens.ts
- Updated react-combobox to use the react-theme tokens for spacing, duration, and motionCurves
Updates #22231
> react-combobox: Updated to use theme tokens

- packages/react-components/react-theme/src/themes/ThemeMotion.stories.tsx
Add Motion tokens stories to react-theme storybook:
Animation are disabled by default to protect viewers.
> doc(react-theme): Add Motion story

- change/@fluentui-priority-overflow-e9a31ace-ddda-4bb0-b95e-ed205d3ee9a9.json
- change/@fluentui-react-overflow-482ab493-8f48-4b56-a07a-c34d199f74ea.json
- packages/react-components/priority-overflow/package.json
- packages/react-components/react-overflow/package.json
@fluentui/priority-overflow and @fluentui/react-overflow were not published
@fluentui/priority-overflow and @fluentui/react-overflow will be published as beta
Fixes #
> feat: Release @fluentui/overflow and @fluentui/react-overflow in beta

- packages/react-components/react-alert/etc/react-alert.api.md
- packages/react-components/react-alert/src/components/Alert/Alert.types.ts
> Alert: remove commons type

- change/@fluentui-react-spinbutton-a155c88b-f568-45c8-a9b6-12760608da9c.json
- packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButtonStyles.ts
- Updated to use shared tokens for spacing
Updates #22231
> react-spinbutton: use spacing tokens

- apps/public-docsite-v9/src/Concepts/Upgrade/FromV0/Components/Checkbox.stories.mdx
- apps/public-docsite-v9/src/Concepts/Upgrade/FromV8/Components/Checkbox.stories.mdx
- change/@fluentui-react-checkbox-47a1d76f-11b9-4897-bfde-f774aab5063d.json
- packages/react-components/react-checkbox/README.md
- packages/react-components/react-checkbox/Spec.md
This PR adds the following changes:
* Updates spec to match implementation.
* Adds README information.
* Adds `v0->v9` and `v8->v9` upgrade guides.
> react-checkbox: Updating Spec and adding upgrade guide

- change/@fluentui-react-spinbutton-219484d8-96c2-48e0-9710-d6bde25ed0f5.json
- packages/react-components/react-spinbutton/package.json
- packages/react-components/react-spinbutton/src/stories/SpinButtonAppearance.stories.tsx
- packages/react-components/react-spinbutton/src/stories/SpinButtonBestPractices.md
The filledDarker and filledLighter "Appearance" stories have insufficient contrast with their backgrounds.
1. The filledDarker and filledLighter "Appreance" stories have sufficient contrast with their backgrounds.
2. Design guidance has been added to the story.
3. Do's and Don'ts for contrast have been added to Storybook
#22967
> react-spinbutton: update appearance stories

- packages/react-components/react-textarea/src/stories/TextareaControlled.stories.tsx
- packages/react-components/react-textarea/src/stories/TextareaDefault.stories.tsx
- packages/react-components/react-textarea/src/stories/TextareaDisabled.stories.tsx
- packages/react-components/react-textarea/src/stories/TextareaPlaceholder.stories.tsx
- packages/react-components/react-textarea/src/stories/TextareaResize.stories.tsx
- packages/react-components/react-textarea/src/stories/TextareaSize.stories.tsx
- packages/react-components/react-textarea/src/stories/TextareaUncontrolled.stories.tsx
This PR makes the following changes:
* Removes flex-gap from stories.
> react-textarea: Removing flex-gap from stories

- change/@fluentui-react-checkbox-1cba765d-8ea1-4287-af4a-b6fa0e59ef61.json
- packages/react-components/react-checkbox/src/Checkbox.stories.tsx
- packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts
This PR does the following:
* Replaces spacing constants with tokens.
> react-checkbox: Replacing spacing constants with tokens.

- .github/CODEOWNERS
Add @spmonahan to `react-input` CODEOWNERS.
> react-input: update codeowners

- change/@fluentui-react-spinbutton-56b5d3d3-9004-494e-a5fc-f282b61f651b.json
- packages/react-components/react-spinbutton/package.json
- packages/react-components/react-spinbutton/src/stories/SpinButtonAppearance.stories.tsx
Appearance story has complicated styles and an extra devDependency.
Appearance story has simplified styles and remove the unnecessary devDependency.
> SpinButton: Update Appearance Stories

- packages/fluentui/react-northstar/src/index.ts
Reverts microsoft/fluentui#23010
> Revert "Experiment: Test screener scoping for v0"

- packages/react/src/index.ts
Adds a comment to v8 to test screener scoping for master branch.
Fixes #
> Experiment: Test v8 screener scoping on master

- packages/react/src/index.ts
Reverts microsoft/fluentui#23014
> Revert "Experiment: Test v8 screener scoping on master"

- .github/CODEOWNERS
Move `react-dialog` to teams-prg
> chore(react-dialog): update CODEOWNERS

- packages/react-combobox/src/stories/Combobox.stories.tsx
- packages/react-combobox/src/stories/ComboboxAppearance.stories.tsx
- packages/react-combobox/src/stories/ComboboxBestPractices.md
- packages/react-combobox/src/stories/ComboboxCustomOptions.stories.tsx
- packages/react-combobox/src/stories/ComboboxGrouped.stories.tsx
- packages/react-combobox/src/stories/ComboboxMultiselect.stories.tsx
- packages/react-combobox/src/stories/ComboboxSize.stories.tsx
This PR adds stories for:
- Size
- Appearance (including new bg for filled variants)
- Grouped options
It also adds best practice wording for appearance, and adds story descriptions for the other stories.
> Combobox: add and update stories

- change/@uifabric-icons-8a5f4ef4-9047-4bd5-b37e-22f2994c0bfb.json
- packages/icons/src/index.ts
> Update window variable to use iconBaseUrl to avoid collision

- change/@fluentui-react-button-1fc68dee-32f8-40ab-adf4-c9e44a32b920.json
- packages/react-components/react-button/src/components/Button/useButtonStyles.ts
- packages/react-components/react-button/src/components/CompoundButton/useCompoundButtonStyles.ts
`Button` components use direct values in pixels for spacing.
`Button` components use spacing tokens for spacing.
> react-button: Using spacing tokens for button components

- apps/vr-tests-react-components/package.json
- change/@fluentui-react-components-fde1774d-c84a-4853-a18b-abce2af7196e.json
- change/@fluentui-react-input-bed71aa5-4608-4ce3-9537-40a32dd44e69.json
- change/@fluentui-react-spinbutton-c26351d8-d806-445e-939e-3b84c6e59bbb.json
- packages/react-components/react-components/etc/react-components.api.md
- packages/react-components/react-components/etc/react-components.unstable.api.md
- packages/react-components/react-components/package.json
- packages/react-components/react-components/src/index.ts
- packages/react-components/react-components/src/unstable/index.ts
- packages/react-components/react-input/README.md
- packages/react-components/react-input/package.json
- packages/react-components/react-input/src/stories/Input.stories.tsx
- packages/react-components/react-spinbutton/package.json
`Input` is a beta component
`Input` is a release candidate component
Fixes #22674
> Input: move to release candidate

- change/@fluentui-react-tabster-2673c19d-f19b-4bf3-b641-9a7cd8ec1266.json
- packages/react-components/react-tabster/package.json
- yarn.lock
Tabster dependency is ^1.3.3
Tabster dependency is ^1.4.0
> Tabster: update tabster dependency

- change/@fluentui-react-text-b805e9fd-9074-4856-ac82-eaf7557f6485.json
- packages/react-components/react-text/etc/react-text.api.md
- packages/react-components/react-text/src/components/Text/Text.types.ts
`Text` types are not alphabetically ordered.
`Text` types are alphabetically ordered.
> Text: Ordering types alphabetically

- change/@fluentui-react-textarea-32333097-b104-426a-8e15-31e7195b8b51.json
- packages/react-components/react-textarea/src/stories/Textarea.stories.tsx
- packages/react-components/react-textarea/src/stories/TextareaAppearance.stories.tsx
- packages/react-components/react-textarea/src/stories/TextareaBestPractices.md
> docs(react-textarea): formatting improvements

- change/@fluentui-react-alert-ecc54de5-4141-48a2-a000-2eb3f7a9db6a.json
- change/@fluentui-react-components-ce509762-cee7-4eed-873c-8d6495edb69a.json
- packages/react-components/react-alert/package.json
- packages/react-components/react-alert/src/stories/Alert.stories.tsx
- packages/react-components/react-alert/src/stories/AlertDescription.md
- packages/react-components/react-components/etc/react-components.unstable.api.md
- packages/react-components/react-components/package.json
- packages/react-components/react-components/src/unstable/index.ts
This PR publishes the `react-alert` package as an unstable component
> Publish react-alert as an unstable component

- packages/react-components/react-menu/src/stories/MenuControlledCheckboxItems.stories.tsx
- packages/react-components/react-menu/src/stories/MenuControlledRadioItems.stories.tsx
> docs(react-menu): fix stories

- packages/react-components/react-image/src/stories/ImageShadow.stories.tsx
> docs(react-image): fix path to an image in a story

- packages/react-components/react-checkbox/src/CheckboxChecked.stories.tsx
This PR updates `CheckboxChecked.stories.tsx` to use `data` parameter.
> docs(react-checkbox): use data.checked in the story

- change/@fluentui-react-accordion-7a8ed6bd-35ad-47f7-8143-0abd1a26afd0.json
- packages/react-components/react-accordion/src/components/Accordion/Accordion.types.ts
- packages/react-components/react-accordion/src/components/AccordionHeader/AccordionHeader.types.ts
- packages/react-components/react-accordion/src/components/AccordionItem/AccordionItem.types.ts
- packages/react-components/react-accordion/src/components/AccordionPanel/AccordionPanel.types.ts
- packages/react-components/react-accordion/src/stories/Accordion.stories.tsx
- packages/react-components/react-accordion/src/stories/AccordionCollapsible.stories.tsx
- packages/react-components/react-accordion/src/stories/AccordionDisabled.stories.tsx
- packages/react-components/react-accordion/src/stories/AccordionExpandIcon.stories.tsx
- packages/react-components/react-accordion/src/stories/AccordionInline.stories.tsx
- packages/react-components/react-accordion/src/stories/AccordionMultiple.stories.tsx
- packages/react-components/react-accordion/src/stories/AccordionNavigation.stories.tsx
- packages/react-components/react-accordion/src/stories/AccordionOpenItems.stories.tsx
- packages/react-components/react-accordion/src/stories/AccordionWithIcon.stories.tsx
> docs(react-accordion): cleanup examples & docs

- change/@fluentui-react-provider-eb4793e9-065d-40a9-86d4-e942bf3cd3dc.json
- packages/react-components/react-provider/src/stories/FluentProvider.stories.tsx
- packages/react-components/react-provider/src/stories/FluentProviderDescription.md
This PR adds generic `.md` files and fills component's description.
> docs(react-provider): add description

- change/@fluentui-react-tabs-12a35f48-3969-4f7d-8685-a4e2cc22d91a.json
- packages/react-components/react-tabs/src/stories/TabListBestPractices.md
- packages/react-components/react-tabs/src/stories/TabListWithOverflow.stories.tsx
> docs(Tablist): improve formatting

- apps/pr-deploy-site/just.config.ts
- apps/pr-deploy-site/pr-deploy-site.js
As we continue to do work on the theme designer, having a durable URL to view/share/get critique will be important.
> Add new V9 Theme Designer to the deploy site

- apps/public-docsite-v9/package.json
- packages/react-components/theme-designer/package.json
Fixes missing dependency upgrades from official release pipeline syncpack
> Manual updates from syncpack release

- packages/react-components/theme-designer/src/ThemeDesigner.tsx
- packages/react-components/theme-designer/src/components/Content/Content.tsx
- packages/react-components/theme-designer/src/components/Demo/Demo.tsx
- packages/react-components/theme-designer/src/components/Palette/Palette.stories.tsx
- packages/react-components/theme-designer/src/components/Palette/Palette.tsx
Added a color palette preview to the theme designer.
> Theme Designer: added color palette

- .storybook/main.js
- .storybook/preview.js
- package.json
- typings/storybook__addons/index.d.ts
- yarn.lock
Fixes #23180 by picking up changes from microsoft/fluentui-storybook-addons#17
> fix: Storybook codesandbox export should use unstable imports

- change/@fluentui-react-slider-ac382feb-de49-422f-8bda-5578b06a6d0c.json
- packages/react-components/react-slider/src/components/Slider/Slider.stories.tsx
- packages/react-components/react-slider/src/components/Slider/SliderBestPractices.md
- packages/react-components/react-slider/src/components/Slider/SliderDescription.md
> docs(react-slider): updates to docs

- packages/react-components/theme-designer/src/components/Content/Content.tsx
- packages/react-components/theme-designer/src/components/TokenBoxes/TokenBoxes.stories.tsx
- packages/react-components/theme-designer/src/components/TokenBoxes/TokenBoxes.tsx
very basic search working for theme designer tokens.
leaving as a draft for now until micah can look at my PR for the theme designer tokens themselves :)
> theme-designer: theme designer tokens
