microsoft/fluentui

apps/vr-tests/src/stories/Calendar.stories.tsx
change/@fluentui-react-59477c5e-6027-46d2-b7b8-61bd58df3848.json
packages/react/etc/react.api.md
packages/react/src/components/CalendarDayGrid/CalendarDayGrid.base.tsx
packages/react/src/components/CalendarDayGrid/CalendarDayGrid.styles.ts
packages/react/src/components/CalendarDayGrid/CalendarDayGrid.types.ts
packages/react/src/components/WeeklyDayPicker/__snapshots__/WeeklyDayPicker.test.tsx.snap

Commit fc6cc7d73c8d61587e26cd19b3bc9db3abd077a6 added an accessibility fix for focus rectangles around selected dates to improve contrast.
The border change caused cells to shift when clicked due to increasing the size of cells, and there were unnecessary borders between ranges of contiguous cells (like in Week selection).
This change utilizes the same logic as rounding the corners to see if there are contiguous selected cells in a region, and if cells are next to each other, removes the borders between them. It also moves the border to an :after element so that the cells don't change sizes on selection.
Before fix:
After fix:
(optional)

Improve calendar selection border

---

change/@fluentui-web-components-5dc3f7fb-7d68-4ca4-b499-a860985ffc30.json
packages/web-components/src/badge/badge.styles.ts

Set a transparent border to badge so when the component is in forced colors the system will set a border to the component
before
after
(optional)

fix: add border and adjust padding to badge component

---

change/@uifabric-charting-c20573f6-ed55-4c62-a7c0-148dcb6cb1a0.json
packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx
packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx
packages/charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx
packages/charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx

Cherry pick of [#19178](https://github.com/microsoft/fluentui/pull/19178)
While adding callout dismiss on escape, we need add one more prop to enable callout again.
Grouped vertical bar chart
Vertical stacked bar chart
Vertical bar chart
Horizontal bar chart

Charting: CherryPick  #19178: Charting: Callout issue resolved in bar charts. #19178

---

change/@uifabric-charting-33ef6ab3-ec52-4021-8304-61c4a1ead27d.json
packages/charting/src/components/Legends/Legends.base.tsx

Cherry pick of [#19199](https://github.com/microsoft/fluentui/pull/19199)
For overflow legend, previously NVDA reading like '2 overflow item section', now NVDA will read as "2 overflow item link collapsed."
Legends 
**After Change**

Charting: CherryPick #19199: Role added for overflow legends #19199

---

change/@uifabric-charting-cfb8ccb5-c54b-416e-ba85-9c0fdfad9770.json
packages/charting/src/components/StackedBarChart/MultiStackedBarChart.styles.ts
packages/charting/src/components/StackedBarChart/StackedBarChart.styles.ts
packages/charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap
packages/charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap

Cherry-pick of [#19202](https://github.com/microsoft/fluentui/pull/19202)
Focus visual for rectangles will be visible, border added on focus for Stacked bar and multi-stacked bar.
Stacked Bar Chart
Multi-Stacked Bar Chart
**After Changes**

Charting: CherryPick #19202: On focus, border will be visible for Stacked bar and multi-stacked bar chart #19202

---

apps/vr-tests/screener.local.config.js

For a while, running our VR tests locally with Screener was an impossibility. After some reverse engineering with the help of @Hotell (thanks!) we figured out several issues.
Screener automatically assumes your `start-storybook` binary is located in it's own folder. As such, this probably stopped working whenever we moved the dependencies out of `vr-tests`.
To fix this, we added the `storybookBinPath` config to manually tell Screener where to get the binary from.
Using the custom bin path now requires us to define our Storybook version. This can be achieved by using the `storybookVersion` prop but, due to [this](https://github.com/screener-io/screener-storybook/blob/master/src/storybook.js# …

Fix local Screener run

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/components/Tooltip/Tooltip.tsx

https://user-images.githubusercontent.com/28751745/128037587-89d302dd-0246-4a0b-b027-fdd69e8e3bd3.mov
Tooltip will open when mouse enters trigger, or mouse enters tooltip content.
Tooltip will close when mouse leaves trigger, or mouse leaves tooltip content.
There is a slight timeout for closing tooltip on mouse leave, by default it is 10s.
Tooltip is render right next to the trigger. So when user moves mouse to the edge between trigger and tooltip content, the below events can happen:
- mouseenter(1) trigger -> cause tooltip content render
- mouseleave trigger, mouseenter(2) tooltip content
The mouseleave will try to close the tooltip with a timeout: `setTimeout(() => {setOpen(false), mouseLeaveDelay})`
But the second mouseenter will clear the timeout. So the `setOpen(false)` is never …

fix(Tooltip): tooltip flicker in iframe

---

packages/react-slider/etc/react-slider.api.md
packages/react-slider/package.json
packages/react-slider/src/components/Slider/Slider.types.ts
packages/react-slider/src/components/Slider/renderSlider.tsx

`react-slider` is wrongly using the newest version of `getSlots` and `ComponentProps`. This PR modifies it to use compat version instead

fix(react-slider): use compat version of shorthands

---

apps/vr-tests/package.json
apps/vr-tests/src/stories/TextConverged.stories.tsx

Added visual regression tests for `react-text`
- A test for each `Text` prop
- A test for each wrapper

Text - Add VR tests

---

packages/fluentui/react-northstar/src/components/Carousel/Carousel.tsx
packages/fluentui/react-northstar/src/components/Carousel/CarouselNavigation.tsx

Requirement 1850100: Make store carousel banner navigator dots not clickable
Giving user an option that can making carousel navigator dots not clickable
(optional)

Adding a new property which allow user to make navagation unclickable

---

rfcs/convergence/root-as-slot.md

This RFC proposes to treat `root` as a _slot_ to simplify signature, improve `Typings` and avoid conflicts between `root` and other _slots_ signatures.
Main changes would be:
1. `root` becomes a regular slot on component state
2. Support references on every _slot_
3. Supports Custom Elements on every _slot_
4. Allows a restricted `as` prop on every slot
5. stops using `getNativeElementProps` on every slot

RFC: Root as a slot

---

change/@fluentui-react-8886f0c5-7c30-4f86-92aa-357aa55aae27.json
packages/react/src/components/Callout/CalloutContent.base.tsx

This is a port of my earlier fix (#18803) in the v7 branch to `master`.  In v8, the `CalloutContent` control has been reimplemented as a function component. Therefore, I couldn't do a cherry-pick merge at that time. 
However, the idea of the fix is the same. Within the logic to position the callout, if the `target` element has changed, we must not reuse the current `positions` object. 
Tooltip positioning.

Fix Callout positioning bug when the target element has changed.

---

change/@fluentui-react-popover-1e9b9806-4209-42fd-881c-220c074333f7.json
change/@fluentui-react-positioning-37abff55-efc3-42aa-911d-c671e42986bf.json
packages/react-popover/etc/react-popover.api.md
packages/react-popover/src/components/Popover/Popover.types.ts
packages/react-positioning/etc/react-positioning.api.md
packages/react-positioning/src/types.ts
packages/react-positioning/src/usePopper.ts

This PR is partially based on discussions in #19147.
- `PopperOptions` is not longer exported as it's private type, currently it was used in `react-popover` 😮 Interfaces are very similar with `PositioningProps`, but I want to prevent leaking private APIs
- `PopperOptions.containerRef` was renamed to `PopperOptions.popperRef`:
- `usePopper()` already returns `containerRef`
- if we will to expose `PopperOptions` (#19147), `containerRef` will be very confusing name
- `PopperOptions.positioningDependencies` was removed, as it's not implemented and will not be

fix(react-positioning): fix types

---

change/@fluentui-react-menu-0799b9c7-d4a8-430b-82f0-c3ca6941aa64.json
packages/react-menu/src/components/MenuPopover/useMenuPopoverStyles.ts

The design spec min height was actually calculated with a single menu item and relevant padding, so the min height set in CSS is actually not necessary and even wrong.
(optional)

fix(MenuPopover): Remove min-height value

---

package.json
yarn.lock

Storybook `6.3.x` had `@storybook/react-docgen-typescript-plugin` update its dependency of `react-docgen-typescript` to `^2.0.0` which caused an issue with `@default` JSDoc comments being completely ignored. This PR resolves `@storybook/react-docgen-typescript-plugin` to a version before it was upgraded to `react-docgen-typescript: ^2.0.0` . This is only a temporary fix as we wait for the issue to be resolved with react-docgen and storybook.
See this [comment](https://github.com/microsoft/fluentui/issues/19292#issuecomment-894590532) for investigation findings.

(temp fix): JSDoc @default values now properly displayed in Storybook docs and controls

---

change/@fluentui-azure-themes-6418b13a-0982-48b5-abf9-96b70c17f49c.json
packages/azure-themes/src/azure/AzureThemeDark.ts
packages/azure-themes/src/azure/AzureThemeHighContrastDark.ts
packages/azure-themes/src/azure/AzureThemeHighContrastLight.ts
packages/azure-themes/src/azure/AzureThemeLight.ts
packages/azure-themes/src/azure/styles/DefaultButton.styles.ts
packages/azure-themes/src/azure/styles/PrimaryButton.styles.ts
packages/react-examples/src/azure-themes/stories/Themes/Themes.stories.tsx

- Disabled PrimaryButton is shown as enabled when hovered under azure-themes. https://fabricweb.z5.web.core.windows.net/oufr/8.23.5/#/examples/button
Fix
- Moved disabled styles as the last styles, after hover styles;
- As azure-themes has already defined semantic colors, removed duplicated button styles using the same semantic colors.
- Azure themes storybook doesn't work. PrimaryButton below should have height of 24px under azure-themes.
ThemeProvider doesn't merge styles automatically, so inner ThemeProvider reset outer customizer styles.
https://github.com/microsoft/fluentui/blob/cf8d7a43d6de92501cef58200aff21fb3d1590a5/packages/react-examples/src/azure-themes/stories/Themes/Themes.stories.tsx#L152-L158
After fix

Azure themes stories

---

packages/fluentui/react-northstar/src/components/Form/FormButton.tsx

Compose `FormButton`  with button to allow the right props to be passed
(optional)

fix: use Button to compose FormButton

---

change/@fluentui-make-styles-webpack-loader-4d1b1fa5-0598-4790-93cd-887c501b3694.json
packages/make-styles-webpack-loader/src/webpackLoader.test.ts
packages/make-styles-webpack-loader/src/webpackLoader.ts

During tryouts in Teams codebase of loader I noticed significant performance penalty caused by the loader: ~370 seconds vs ~580 seconds for a build. This happened because we process an each file and building AST by Babel, even if a file does not contain `makeStyles()` calls.
This PR uses the same trick as Linaria to skip files without `makeStyles()` calls: https://github.com/callstack/linaria/blob/ff1268faf92408caf80ca272f5f87c306f75df79/packages/babel/src/transform.ts#L44-L46. It's not 100% accurate as checks via AST, but it's enough good to improve loader's perf.

perf(webpack-loader): early return on files without makeStyles() calls

---

change/@fluentui-react-charting-a27640fe-9b04-4440-9d99-879fc4afb588.json
packages/react-charting/src/components/AreaChart/AreaChart.base.tsx
packages/react-charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap
packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx
packages/react-charting/src/components/CommonComponents/CartesianChart.types.ts
packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx
packages/react-charting/src/components/LineChart/LineChart.base.tsx
packages/react-charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
packages/react-charting/src/components/StackedBarChart/StackedBarChart.base.tsx
packages/react-charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap
packages/react-charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap
packages/react-examples/src/react-charting/AreaChart/AreaChart.CustomAccessibility.Example.tsx
packages/react-examples/src/react-charting/LineChart/LineChart.CustomAccessibility.Example.tsx

1. For Stacked Bar Chart, Multi Stacked Bar Chart, Horizontal Bar Chart, Area Chart and Line Chart: Existing chart title property is used to describe the chart. So in narrator scan mode, when the focus goes to chart, it will read chart title, previously it read as "image".  
Area Chart
Line Chart
Stacked Bar Chart
Multi Stacked Bar chart
Horizontal Stacked Bar chart
https://user-images.githubusercontent.com/29042635/128512033-99f2e920-2634-4a90-9ccc-d3e76433bd8a.mp4
https://user-images.githubusercontent.com/29042635/128512057-0029333c-fdf4-4fb5-87dd-1eb8f6547268.mp4

Chart will be readable by chart title property 

---

change/@fluentui-react-examples-d780f035-74aa-451d-a517-aded00c64e6e.json
change/@uifabric-charting-5f2e26ab-3145-4094-9d1e-9fecb8b44eb0.json
packages/charting/src/components/AreaChart/AreaChart.base.tsx
packages/charting/src/components/CommonComponents/CartesianChart.base.tsx
packages/charting/src/components/CommonComponents/CartesianChart.types.ts
packages/charting/src/components/LineChart/LineChart.base.tsx
packages/charting/src/types/IDataPoint.ts
packages/charting/src/utilities/utilities.ts
packages/react-examples/src/charting/AreaChart/AreaChart.CustomAccessibility.Example.tsx
packages/react-examples/src/charting/AreaChart/AreaChartPage.tsx
packages/react-examples/src/charting/LineChart/LineChart.CustomAccessibility.Example.tsx
packages/react-examples/src/charting/LineChart/LineChartPage.tsx

Cherry pick of [#19245](https://github.com/microsoft/fluentui/pull/19245)
Changes are related to Line Chart accessibility and Area Chart Accessibility
1. Accessibility Data prop added for the Chart Data Callout and X-Axis Callout data. Accessibility Data props contain ariaLabel, ariaLabelledBy, and ariaDescribedBy props.
2. If the user is sending any custom accessibility data, then that will be used. else only visible data will be used by the narrator.
3. Custom Accessibility example is added for both the charts.
Area chart
Line chart
**Area Chart**
**Line Chart**
**Area Chart**
**Line Chart**

Charting: CherryPick #19245: Accessibility change for Area Chart and Line chart #19245

---

packages/react-slider/etc/react-slider.api.md
packages/react-slider/package.json
packages/react-slider/src/Slider.stories.tsx
packages/react-slider/src/components/Slider/Slider.test.tsx
packages/react-slider/src/components/Slider/Slider.types.ts
packages/react-slider/src/components/Slider/__snapshots__/Slider.test.tsx.snap
packages/react-slider/src/components/Slider/useSliderState.tsx
packages/react-slider/src/components/Slider/useSliderStyles.ts

Implementing the `vertical` prop to the **Slider component**:

(react-slider) - Adding vertical prop

---

packages/react-text/MIGRATION.md

Migration guide for `react-text`
[PREVIEW](https://github.com/microsoft/fluentui/blob/c87e74b5db4857c1e5a902acd8b913d0cf1ae359/packages/react-text/MIGRATION.md)

Text - Migration guide

---

change/@fluentui-react-0c00e5b1-2145-4f97-a331-c8a6eec95640.json
packages/react/etc/react.api.md
packages/react/src/components/Modal/Modal.types.ts
packages/react/src/components/Overlay/Overlay.types.ts

Fix typings for Overlay's `onClick` prop to match all other event handlers.
Since `onClick` (and all other handlers) are treated as plain JSX attributes, it should keep the default DOM Attribute typings that come with React. Modal had to update its typings as well, but previously they were silently incorrect, so this seems better :)

Overlay onclick type

---

packages/fluentui/CHANGELOG.md
packages/fluentui/docs/src/examples/components/Chat/Types/ChatExampleCompact.shorthand.tsx
packages/fluentui/docs/src/examples/components/Chat/Types/ChatExampleCompact.tsx
packages/fluentui/react-northstar-prototypes/src/prototypes/compactChat/CompactChatErrorState.tsx
packages/fluentui/react-northstar-prototypes/src/prototypes/compactChat/CompactChatSlots.tsx
packages/fluentui/react-northstar-prototypes/src/prototypes/compactChat/CompactChatWithAuthor.tsx
packages/fluentui/react-northstar-prototypes/src/prototypes/compactChat/CompactChatWithBadges.tsx
packages/fluentui/react-northstar-prototypes/src/prototypes/compactChat/CompactChatWithDetails.tsx
packages/fluentui/react-northstar-prototypes/src/prototypes/compactChat/CompactChatWithReactions.tsx
packages/fluentui/react-northstar-prototypes/src/prototypes/compactChat/CompactChatWithReadReceipts.tsx

Initially compact chat was supposed to only display given names of message authors, but due to potential problems with splitting names/detecting given name part, the current design spec displays full names in all chat densities.
This PR updates the examples and prototypes of compact chat to reflect that decision and avoid confusion.

Align author name in compact chat with design spec

---

change/@fluentui-react-menu-db8655b7-1e21-4be9-8877-36e8643e5b14.json
change/@fluentui-react-popover-8f203e6f-a2b7-417a-9ea9-b24441bce5db.json
packages/react-menu/src/components/MenuTrigger/MenuTrigger.test.tsx
packages/react-menu/src/components/MenuTrigger/useTriggerElement.ts
packages/react-popover/src/components/PopoverTrigger/PopoverTrigger.test.tsx
packages/react-popover/src/components/PopoverTrigger/usePopoverTrigger.ts

Previously trigger refs were cloned incorrectly using `child.props.ref`.
The correct property should be `child.ref` which is not correctly typed
by React
(optional)

fix(Menu, Popover): Clone ref correctly

---

rfcs/convergence/exposing-popper-options.md

This RFC proposes a solution to address #19145
[PREVIEW LINK](https://github.com/ling1726/fluentui/blob/rfc/popper-options/rfcs/convergence/exposing-popper-options.md)
(optional)

RFC: Configuring popper uniformly across v9

---

rfcs/convergence/authoring-stories.md

Adds relevant proposal from #18895 for hiding certain stories only
required for internal e2e testing to our storybook.
[**PREVIEW**](https://github.com/ling1726/fluentui/blob/rfc/internal-stories/rfcs/convergence/authoring-stories.md)
(optional)

RFC: Internal stories for E2E testing

---

change/@fluentui-react-examples-83a1cb68-b9ab-4838-ad86-f44660ebd66e.json
change/@uifabric-charting-be6c9ea5-ccef-4dd2-8f33-f563f903b1d7.json
packages/charting/src/components/AreaChart/AreaChart.base.tsx
packages/charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap
packages/charting/src/components/CommonComponents/CartesianChart.base.tsx
packages/charting/src/components/CommonComponents/CartesianChart.types.ts
packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx
packages/charting/src/components/LineChart/LineChart.base.tsx
packages/charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx
packages/charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap
packages/charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap
packages/react-examples/src/charting/AreaChart/AreaChart.CustomAccessibility.Example.tsx
packages/react-examples/src/charting/LineChart/LineChart.CustomAccessibility.Example.tsx

Cherry pick of [#19293](https://github.com/microsoft/fluentui/pull/19293)
1. For Stacked Bar Chart, Multi Stacked Bar Chart, Horizontal Bar Chart, Area Chart and Line Chart: Existing chart title property is used to describe the chart. So in narrator scan mode, when the focus goes to chart, it will read chart title, previously it read as "image".  
Area Chart
Line Chart
Stacked Bar Chart
Multi Stacked Bar chart
Horizontal Stacked Bar chart
https://user-images.githubusercontent.com/29042635/128512033-99f2e920-2634-4a90-9ccc-d3e76433bd8a.mp4
https://user-images.githubusercontent.com/29042635/128512057-0029333c-fdf4-4fb5-87dd-1eb8f6547268.mp4

Charting: CherryPick #19293: Chart will be readable by chart title property #19293

---

change/@fluentui-react-fa9343ef-d793-4210-ac39-3e0da4046737.json
packages/react-examples/src/react/__snapshots__/Announced.BulkOperations.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Announced.QuickActions.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Advanced.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Animation.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Basic.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.ColumnResize.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Compact.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.CustomColumns.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.CustomFooter.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.CustomGroupHeaders.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.CustomRows.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Documents.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Grouped.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Grouped.Large.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.NavigatingFocus.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.ProportionalColumns.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Shimmer.Application.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Text.Ramp.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Text.Weights.Example.tsx.shot
packages/react/src/components/DetailsList/DetailsColumn.base.tsx
packages/react/src/components/DetailsList/__snapshots__/DetailsHeader.test.tsx.snap
packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
packages/react/src/components/DetailsList/__snapshots__/DetailsRow.test.tsx.snap

This does two things:
1. Fixes the focus target when a columnheader's child is not a button (where previously it had been going onto the generic `<span>` element)
2. Does not set `aria-haspopup` if the value is false, and updates the `true` value to `menu` (which is what "true" functionally means).
Came across the second while investigating an issue that turned out to be unrelated, and it's mostly just housekeeping/better code practice. The first is the actual a11y fix.

fix(Detailslist): set correct focus target when column header has no focusable child

---

change/@fluentui-react-button-36853289-ff23-460d-b07c-160138e12073.json
packages/react-button/src/components/Button/useButtonStyles.ts

PR to update the tokens used for hc styling on focus for react-button
**Before**
**After**
(optional)

Update hc focus styling for vNext button

---

change/@fluentui-react-2ed65004-21d3-4d85-936c-d4e88831ff56.json
packages/react/src/components/MarqueeSelection/MarqueeSelection.base.tsx

If the page has a horizontal scrollbar (but not a vertical scrollbar), and the user has at least one item selected in a `DetailsList` wrapped with `MarqueeSelection`, these items will unexpectedly be unselected when the user drags the horizontal scrollbar to move the currently visible viewport.
This issue is fixed by extending `MarqueeSelection`'s scrollbar detection to include the horizontal scrollbar.

Fix horizontal scrollbar detection in MarqueeSelection

---

change/@fluentui-react-d9c85ed1-5885-443e-993f-2ce9c43a544b.json
packages/react/src/components/Callout/Callout.test.tsx
packages/react/src/components/Callout/CalloutContent.base.tsx

Callout was previously only calling `preventDismissOnEvent` for the `targetWindowBlur` dismissal, rather than anywhere `onDismiss` was called. This PR checks for it before each time `onDismiss` is called.
This fixes an issue a team was running into, where they could not prevent the ContextualMenu from dismissing after a window focus event.

fix(Callout): check preventDismissOnEvent before dismissing for all dismiss triggers

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/themes/teams-dark-v2/componentVariables.ts
packages/fluentui/react-northstar/src/themes/teams-dark-v2/components/Dialog/dialogVariables.ts

Fix contrast ratio for `Dialog` containing error `Text` in Dark V2
(optional)

fix(Dialog): fix contrast ratio for Dialog in dark v2

---

change/@fluentui-web-components-e70e1294-83c5-4c30-af76-4683b9c047c0.json
packages/web-components/src/listbox-option/listbox-option.styles.ts
packages/web-components/src/progress/progress/progress.styles.ts
packages/web-components/src/radio/radio.styles.ts
packages/web-components/src/select/select.styles.ts
packages/web-components/src/text-area/text-area.styles.ts
packages/web-components/src/text-field/text-field.styles.ts
packages/web-components/src/tree-item/tree-item.styles.ts

- Adds a consistent border radius to text area
- Fixes the disabled state of Option
- Fixes indeterminate progress bars
- Uses design tokens instead of the corresponding CSS custom properties
(optional)

Various style fixes

---

packages/react-slider/src/components/Slider/useSliderState.tsx

With the Slot null rendering implementation, the **Slider** component no longer requires a null render for children.

(react-slider) - Removing null children

---

change/@fluentui-web-components-66b00aa4-efa9-4c0c-8681-017ee0b3035d.json
packages/web-components/src/card/card.styles.ts

Ensures that we set the foreground color of text by default for card so it responds to the fill and its changes.
(optional)

ensure card has good default foreground text

---

change/@fluentui-react-button-07671e9e-e062-491d-bc90-15ce48a6d69f.json
packages/react-button/src/components/Button/useButtonStyles.ts

This PR is to update the default styling for the vNext button on focus, that got changed due to #19118. It fixes the default styling while maintaining the fixed hc focus styling
**Before**
**After**
(optional)

Fix default styling for button on focus

---

change/@fluentui-react-checkbox-6ceea7cf-85e0-4218-8b28-540a1591555d.json
packages/react-checkbox/src/components/Checkbox/Checkbox.test.tsx
packages/react-checkbox/src/components/Checkbox/useCheckbox.tsx

Adding `ev.stopPropagation()` to the Checkbox component's input change event. This prevents the events from bubbling up and calling multiple onChange events.

(react-checkbox) - Adding stopPropagation

---

change/@fluentui-react-b94672dd-7637-41d5-8c90-9de94a86da10.json
packages/react/src/components/OverflowSet/OverflowButton.tsx

"keytipsToRegister" is basically a queue to go through every time the OverflowButton updates, which means we should use a simple array instead of a "preserved" constant which is what useConst does. Without this the registering was being over-done for keytips that didn't need to be re-registered
(optional)

Use simple array for keytips to register instead of useConst

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/components/Tooltip/Tooltip.tsx

Default tooltip (no beak) should be 4px away from trigger. Currently it is 0. This PR updated to match design 
before:
after:
(optional)

fix(Tooltip): give 4px gap between trigger and default tooltip

---

change/@fluentui-react-charting-daa11c69-e8c0-49a8-acc8-3f3ec9dfabdb.json
packages/react-charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap
packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx
packages/react-charting/src/components/DonutChart/DonutChart.base.tsx
packages/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap
packages/react-charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
packages/react-charting/src/components/StackedBarChart/StackedBarChart.base.tsx
packages/react-charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap
packages/react-charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap

…the chart
Title stag removed from charting, which was used to denote about the chart.  Instead of that, ariaLabel used with SVG tag.
So with this changes, on chart focus, screen reader will announce chart title, but on hover tooltip wont show.
All Chart
**After changes:**

Fixed: On chart hover, chart title tooltip is showing

---

change/@fluentui-react-charting-028db1e8-c569-4685-908d-18da89ca1c93.json
packages/react-charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap
packages/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap
packages/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap
packages/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap
packages/react-charting/src/components/Legends/Legends.base.tsx
packages/react-charting/src/components/Legends/Legends.styles.ts
packages/react-charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
packages/react-charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap
packages/react-charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap
packages/react-charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap
packages/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChart.test.tsx.snap
packages/react-examples/src/react-charting/StackedBarChart/MultiStackedBarChartWithPlaceHolder.Example.tsx

Previously opacity=0.6 was added for non-selected legends, which was causing a luminosity ratio issue.
Now opacity removed, so whatever color user has passed that will directly use.
It's totally up to the user, legends color is passing the luminosity ratio or not. 
Legends

Opacity of non selected legends removed, to pass the accessibility luminosity ratio. 

---

change/@fluentui-react-charting-d6d058d3-c6c5-4fd0-ae05-ae45d379fef5.json
packages/react-charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap
packages/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap
packages/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap
packages/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap
packages/react-charting/src/components/Legends/Legends.base.tsx
packages/react-charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
packages/react-charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap
packages/react-charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap
packages/react-charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap
packages/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChart.test.tsx.snap

The original issue exists in NVDA tool itself, solving the issue that created the Fastpass issue in charts. So reverting the changes. 
The same issue has been raised on the NVDA GitHub page
Legends

Reverting : Legends will be focusable in browser mode

---

change/@uifabric-charting-27af0561-2974-46a8-983a-c5cd5cacbbf5.json
packages/charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap
packages/charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap
packages/charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap
packages/charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap
packages/charting/src/components/Legends/Legends.base.tsx
packages/charting/src/components/Legends/Legends.styles.ts
packages/charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
packages/charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap
packages/charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap
packages/charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap
packages/charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChart.test.tsx.snap

Cherry pick of [#19436](https://github.com/microsoft/fluentui/pull/19436)
Previously opacity=0.6 was added for non-selected legends, which was causing a luminosity ratio issue.
Now opacity removed, so whatever color user has passed that will directly use.
It's totally up to the user, legends color is passing the luminosity ratio or not. 
Legends

Charting: CherryPick #19436: Opacity of non selected legends removed, to pass the accessibility luminosity ratio. #19436

---

change/@uifabric-charting-d0ef98be-f764-497d-ae39-d218851ed8b5.json
packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx
packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx
packages/charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx
packages/charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap
packages/charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx

Cherry pick of [#19381](https://github.com/microsoft/fluentui/pull/19381)
If a data value is zero, then the chart element for that data point will not render. 
This is done because, Previously if the data point value was zero, that element was rendering but it was not visible because of 0 width. still, keyboard focus was showing the tooltip for that element. 
with new changes, as elements won't render, so the keyboard will focus on the visible elements only. 
Horizontal bar chart
Multistacked bar chart
Stacked bar chart
Vertical Bar chart
Vertical Stacked bar chart
(optional)

Charting: CherryPick #19381: Chart data point element will not render when data value is zero #19381

---

packages/react-slider/etc/react-slider.api.md
packages/react-slider/src/components/Slider/Slider.types.ts
packages/react-slider/src/components/Slider/renderSlider.tsx
packages/react-slider/src/components/Slider/useSlider.ts
packages/react-slider/src/components/Slider/useSliderState.tsx
packages/react-slider/src/components/Slider/useSliderStyles.ts

Temporarily reverting the `react-slider` package back to using `mergeProps` while the latest slot RFC under goes review.

(react-slider) - Temporarily reverting slot implementation to mergeProps

---

packages/react-switch/etc/react-switch.api.md
packages/react-switch/src/components/Switch/Switch.types.ts
packages/react-switch/src/components/Switch/renderSwitch.tsx
packages/react-switch/src/components/Switch/useSwitch.ts
packages/react-switch/src/components/Switch/useSwitchState.ts

Temporarily reverting the `react-switch` package back to using `mergeProps` while the latest slot RFC under goes review.

chore(react-switch): Temporarily revert slot implementation to mergeProps

---

change/@fluentui-react-checkbox-46f7d798-b9e5-4221-a332-7321149a23f7.json
packages/react-checkbox/etc/react-checkbox.api.md
packages/react-checkbox/src/components/Checkbox/Checkbox.types.ts
packages/react-checkbox/src/components/Checkbox/renderCheckbox.tsx
packages/react-checkbox/src/components/Checkbox/useCheckbox.tsx

Temporarily reverting the `react-checkbox` package back to using `mergeProps` while the latest slot RFC under goes review.

chore(react-checkbox): Temporarily revert slot implementation to mergeProps

---

packages/react-card/etc/react-card.api.md
packages/react-card/src/components/Card/Card.types.ts
packages/react-card/src/components/Card/renderCard.tsx

Temporarily reverting the `react-card` package back to using `mergeProps` while the latest slot RFC under goes review.

(react-card) - Temporarily reverting slot implementation to mergeProps

---

.storybook/main.js
tools/generators/migrate-converged-pkg/index.spec.ts
tools/generators/migrate-converged-pkg/index.ts

- adds builders support to root config for vNext
- adds builders support for package storybooks setup
(optional)

chore: add vNext storybook builders support and context awareness for migration generator

---

change/@fluentui-web-components-d1cf0365-cb5a-40ce-a1cb-4351ed582810.json
packages/web-components/build/transform-fragments.js

Fixes transform fragments script to address incorrect spacing which breaks certain templates.
(optional)

(web-components) fix transform fragment script issues causing template issues in the bundle

---

change/@fluentui-react-menu-1af90dd9-446b-4467-b80a-c2d4e9f43ff5.json
change/@fluentui-react-tabster-bee8acef-29f5-448f-9a51-58152289fa28.json
packages/react-menu/src/components/MenuList/__snapshots__/MenuList.test.tsx.snap
packages/react-tabster/etc/react-tabster.api.md
packages/react-tabster/package.json
packages/react-tabster/src/hooks/useArrowNavigationGroup.ts
packages/react-tabster/src/hooks/useFocusFinders.ts
packages/react-tabster/src/hooks/useTabsterAttributes.ts
yarn.lock

This PR updates `keyborg` & `tabster` packages in `@fluentui/react-tabster` to v1.

chore(react-tabster): update tabster

---

change/@fluentui-react-utilities-3f69e051-8560-427d-bb86-c70cb09c529b.json
packages/react-utilities/src/hooks/useOnClickOutside.test.ts
packages/react-utilities/src/hooks/useOnClickOutside.ts

Treats a right click equally as a normal click for the `useOnClickOutside`. Fixes bug for `Menu` and `Popover`
Before:
After:
(optional)

fix(useOnClickOutside): Treat right click/context menu as outside click

---

change/@fluentui-react-00695482-2fe3-44e4-bf1d-48d5d8a52851.json
packages/react/src/utilities/decorators/withResponsiveMode.tsx

Fixed an issue where, if the window was the smallest size, a call to `initializeResponsiveMode()` would actually set the responsive mode to `ResponsiveMode.large` due to a bad cascade of checks.
Validate behavior of `withResponsiveMode()`.

Fix initialization of Responsive Mode on small screens

---

change/@fluentui-react-button-d97e005b-38ee-4edf-a440-01eafa33783f.json
packages/react-button/package.json
packages/react-button/src/MenuButton.stories.tsx
packages/react-slider/.babelrc.json
packages/react-slider/.storybook/main.js
packages/react-slider/.storybook/preview.js
packages/react-slider/package.json
packages/react-slider/tsconfig.json

- executed `yarn nx workspace-generator migrate-converged-pkg --name=@fluentui/react-slider`
- Our nx migration generator was not invoked on react-slider (looks like those changes were done manually). this PR fixes it
(optional)

chore(react-slider): properly apply nx migrate-converged-pkg to adhere to new dx setup

---

change/@fluentui-react-button-9705570e-994a-4af4-a52c-8c035b902181.json
packages/react-button/etc/react-button.api.md
packages/react-button/src/components/Button/Button.types.ts
packages/react-button/src/components/Button/__snapshots__/Button.test.tsx.snap
packages/react-button/src/components/Button/useButton.ts
packages/react-button/src/components/CompoundButton/CompoundButton.tsx
packages/react-button/src/components/CompoundButton/CompoundButton.types.ts
packages/react-button/src/components/CompoundButton/useCompoundButton.ts
packages/react-button/src/components/MenuButton/MenuButton.tsx
packages/react-button/src/components/MenuButton/MenuButton.types.ts
packages/react-button/src/components/MenuButton/useMenuButton.ts
packages/react-button/src/components/ToggleButton/ToggleButton.tsx
packages/react-button/src/components/ToggleButton/ToggleButton.types.ts
packages/react-button/src/components/ToggleButton/useToggleButton.ts

This PR adds `type='button'` to all `Button` components, removes the `@docCategory` tags from the `Button` components API since it is not being used in `@fluentui/react-components` components and makes some minor fixes to some documentation existing in comments across the `@fluentui/react-button` package.

Button: Adding type=button to all button components, removing @docCategory tags from API and fixing some documentation in the comments

---

change/@fluentui-react-6112fdea-f8c4-4731-90f1-466f69c0e659.json
packages/react/src/components/Panel/Panel.base.tsx
packages/react/src/components/Panel/Panel.styles.ts
packages/react/src/components/Panel/__snapshots__/Panel.test.tsx.snap

- Moved navigation, header and footer inside scrollable content div.
- Added height based media queries that 'fixes' header and footer to panel when current viewport height meets the minimum set.
- Since navigation, header and footer are now inside the scrollable content - when user zooms in and the viewport height no longer meets the minimum, the navigation/header and footer are 'unfixed' and becomes part of the scrollable content.

Panel: header and footer now reflow properly when zoomed in

---

packages/fluentui/CHANGELOG.md
packages/fluentui/docs/src/examples/components/Tooltip/Types/TooltipExamplePointing.shorthand.steps.ts
packages/fluentui/react-northstar/src/themes/teams-high-contrast/components/Tooltip/tooltipContentVariables.ts

PR #19024 added 'subtle' style for tooltip and made it default. But HC theme was broken. This PR fixes it
Before:  
After:
(optional)

fix(Tooltip): fix default appearance in HC theme

---

tools/generators/migrate-converged-pkg/index.spec.ts
tools/generators/migrate-converged-pkg/index.ts
tools/generators/migrate-converged-pkg/schema.json

- ~[ ] Addresses an existing issue: Fixes #0000~
- fixes pattern violation in schema.json after nx 12.5 migration
- sets target and lib to ES2019 (current limitation caused by node 12 used in our CI) / #19367 
- adds empty line where prettier doesn't work to introduce less diffs when re-running migration on same package
(optional)

feat(tools): update generator to set es2019 and fix pattern json.schema violation

---

packages/react-slider/bundle-size/Slider.fixture.js
packages/react-slider/package.json

Adding a `Slider.fixture.js` file to measure the bundle size

(react-slider) - Adding bundle size tool

---

change/@fluentui-react-provider-61bad14d-8176-477a-b6c2-b3289f39bae0.json
change/@fluentui-react-provider-7ccfbe52-85d3-4452-91c9-8d54ae5070b2.json
packages/react-provider/etc/react-provider.api.md
packages/react-provider/src/components/FluentProvider/FluentProvider.types.ts
packages/react-provider/src/components/FluentProvider/renderFluentProvider.tsx
packages/react-provider/src/components/FluentProvider/useFluentProvider.ts
packages/react-provider/src/components/FluentProvider/useFluentProviderContextValues.test.ts
packages/react-provider/src/components/FluentProvider/useFluentProviderContextValues.ts
packages/react-provider/src/components/FluentProvider/useFluentProviderStyles.ts

The goal of this PR is to remove duplicate merging of classes in `useFluentProvider()`:
https://github.com/microsoft/fluentui/blob/37d516e954155f25ca242d5ba051e28446f1692b/packages/react-provider/src/components/FluentProvider/useFluentProvider.ts#L54-L55
When it was implemented `FluentProvider` and `ThemeProvider` where separate components and it had sense, now merging can be done in `useFluentProviderStyles()` as in other components.

refactor(FluentProvider): rework className handling

---

change/@fluentui-react-conformance-8f2ecf54-500c-487b-825b-cfc7bbadfff6.json
packages/react-conformance/src/isConformant.ts

This PR adds handling of `disabledTests` option for `extraTests`. 
This useful in a case with `react-menu`:
- in `src/common/isConformant.ts` we added extra tests for `makeStyles()`
- but they are not valid for `MenuTrigger` (it's not rendering DOM elements and styles)
- currently there is no way to disable these tests 😥

fix(react-conformance): handle "disabledTests" for "extraTests"

---

change/@fluentui-react-conformance-make-styles-7ce90afe-8ca6-4fa6-8991-46970cfb2bcf.json
packages/react-conformance-make-styles/src/classNameWins.ts
packages/react-conformance-make-styles/src/index.ts
packages/react-conformance-make-styles/src/overridesWin.ts

- renames `classname-wins` to `make-styles-overrides-win` (previous name was not clear, it's visible when a rule gets disabled, #19591)
- moves mock inside conformance test otherwise it causes strange issues in some tests, for example:
```
● MenuItemCheckbox › should merge checkmark slot props
expect(received).not.toBeNull()
Received: null
167 |     // Assert
168 |     const slot = container.querySelector(`.${className}`);
> 169 |     expect(slot).not.toBeNull();
|                      ^
170 |     expect(slot?.querySelector('svg')).not.toBeNull();
171 |   });
172 | });
at Object.<anonymous> (src/components/MenuItemCheckbox/MenuItemCheckbox.test.tsx:169:22)
```
This solution is temporary, once we will be able to use `jest.isolateModules()` (requires Jest 27, …

fix(react-conformance-make-styles): avoid collisions of mock

---

change/@fluentui-react-conformance-make-styles-14258c44-53f1-4c2b-ab7a-7d1cf2bc203f.json
packages/react-conformance-make-styles/src/index.ts
packages/react-conformance-make-styles/src/matchers/index.ts
packages/react-conformance-make-styles/src/matchers/toContainClassNameLastInCalls.test.ts
packages/react-conformance-make-styles/src/matchers/toContainClassNameLastInCalls.ts
packages/react-conformance-make-styles/src/matchers/toHaveMergeClassesCalledTimesWithClassName.test.ts
packages/react-conformance-make-styles/src/matchers/toHaveMergeClassesCalledTimesWithClassName.ts
packages/react-conformance-make-styles/src/overridesWin.ts

Originally #19575 enables new tests for all v9 components, on of edge cases that I met is usage in `react-text` components. There `useTextStyles()` and later a wrapper are calling `mergeClasses()` (that gives us two calls instead of one):
https://github.com/microsoft/fluentui/blob/b9762f72d53452b12d22fd2591fbc57376423048/packages/react-text/src/components/wrapper.tsx#L13-L15
As customers may compose our components in the same way - it's an expected usage.
The test itself counts calls of `mergeClasses()` **with** passed `className`:
```tsx
mergeClasses(styles.root, 'className') // callCount: 1
mergeClasses(styles.icon) // callCount: 1
mergeClasses(styles.image, 'className') // callCount: 2
```
This prevents us from scenarios when `className` could be passed to …

feat(react-conformance-make-styles): allow to configure number of mergeClasses() calls

---

.prettierignore
jest.preset.js
rfcs/build-system/03-packaging-for-npm.md
tools/generators/migrate-converged-pkg/index.spec.ts
tools/generators/migrate-converged-pkg/index.ts

Each converged package's jest cache was being stored under `<package root>/.cache/jest` rather than following the convention of `<package root>/node_modules/.cache/<tool name>` (used by babel, storybook, and others), which required extra ignores/exclusions of the cache folder in various config files.
Moving the jest cache under node_modules with the others increases consistency, allows removing the extra `.cache` directory from `.npmignore`, and potentially helps prevent other future issues. (I'm leaving `.cache` in `.gitignore` and `.vscode/settings.json` for now to prevent contamination from caches which already exist in people's local copies.)

Move jest cache under node_modules/.cache/jest

---

change/@fluentui-web-components-a35ba4d4-7670-4467-993c-98a0c728e0c3.json
packages/web-components/docs/api-report.md
packages/web-components/src/checkbox/checkbox.styles.ts
packages/web-components/src/color/recipes/neutral-stroke-strong.ts
packages/web-components/src/design-tokens.ts
packages/web-components/src/radio/radio.styles.ts
packages/web-components/src/switch/switch.styles.ts

The smaller input controls like checkbox and radio need to meet 3:1 contrast, but the current neutral stroke recipe wasn't designed for that. Added a "strong" recipe to meet contrast.
(optional)

(web-components) Increased contrast for small input controls

---

apps/perf-test/src/index.scenarios.tsx

The current implementation of perf tests checks that all scenarios exist on the checked branch. But there is no way to check those scenarios also exist on the baseline branch. If that happens, the perf test freezes waiting for the result.
Usual use case when this happens is when a new test is added in a branch.
There had been a timeout protecting us from that but that was removed in #13551.
This is more a workaround than a proper fix as there is no easy way to report an error to flamegrill so we just report a success - there will be wrong results reported by the flamegrill.
(optional)

fix(perf-test): Baseline perf test freezes for unknown test

---

change/@fluentui-react-utilities-48456c43-4765-4fb8-9154-794fcfd01fa6.json
packages/react-utilities/package.json
packages/react-utilities/src/utils/shouldPreventDefaultOnKeyDown.ts

Removes dependency from `@fluentui/keyboard-key` and switches to the converged `@fluentui/keyboard-keys` implemeting #18587 and bringing all converged dependencies to `alpha` to be ready to release for lockstep for #19106
(optional)

feat(react-utilities): use `event.key` for keyboard events

---

change/office-ui-fabric-react-36ea4ebd-740d-4c67-9927-43099f3423b0.json
packages/office-ui-fabric-react/src/components/Toggle/Toggle.base.tsx
packages/office-ui-fabric-react/src/components/Toggle/Toggle.test.tsx

This PR fixes and issue where, when passing an `id` after the element first rendered the `Toggle` component was not updating the id appropriately. It also adds a test to ensure this functionality does not regress in the future.

Toggle: Fixing issue where id was not changing if a different one was passed after first render

---

change/@fluentui-react-link-0d19f1a0-0e06-46d2-a260-d03ef2c4ce54.json
packages/react-link/package.json
packages/react-link/src/components/Link/useLinkState.ts

Removes dependency from `@fluentui/keyboard-key` and switches to the converged `@fluentui/keyboard-keys` implemeting #18587 and bringing all converged dependencies to `alpha` to be ready to release for lockstep for #19106
(optional)

refactor(Link): use `event.key` for keyboard event

---

change/@fluentui-react-button-878d6447-5a95-4a52-97b2-e1adc2e496f7.json
packages/react-button/package.json
packages/react-button/src/components/Button/useButtonState.ts

Removes dependency from `@fluentui/keyboard-key` and switches to the converged `@fluentui/keyboard-keys` implemeting #18587 and bringing all converged dependencies to `alpha` to be ready to release for lockstep for #19106
(optional)

refactor(Button): use `event.key` for keyboard event

---

change/@fluentui-react-positioning-55755323-ee08-4471-83d0-980f830a0009.json
packages/react-positioning/src/types.ts

Adds documentation to indicate that `align` does not have an effect without the `position` option
(optional)

chore(usePopper): Document that `align` does not work without `position`

---

apps/vr-tests/src/stories/Menu.stories.tsx
change/@fluentui-react-menu-7cad6973-e27c-43da-9dc4-8cc51f5d55f1.json
packages/react-menu/src/components/MenuItem/renderMenuItem.tsx
packages/react-menu/src/components/MenuItem/useMenuItem.tsx

During the migration of slots, the `required` prop broke the display of the submenu indicator for cases when the slot was `undefined` as a prop.
(optional)

fix(Menu): Missing submenu indicator slot

---

change/@fluentui-react-f8e8abf7-3b35-40f1-8480-654d2a0fa1e0.json
packages/react/src/components/Layer/Layer.base.tsx
packages/react/src/components/Layer/Layer.test.tsx

In v7, where Layer was a class component, the onLayerDidMount and onLayerMounted (deprecated) events were raised in the callback from setState.  This caused the events to be raised after the DOM was rendered and ready.
In v8, the events were raised immediately after the elements were inserted in the DOM, so the DOM was not rendered and ready.
I updated Layer to track the need to raise the events as state and added a useEffect to cause them to be raised after a render pass.  I also updated to remove the layer as an HTML element state.  I removed the potentially stale ref on that state and replaced it tracking the layer as a ref.  I updated the removeLayerElement to clear the ref when the layer was removed.
I added 3 unit tests to ensure the event is raised correctly:
- raises on …

fix(Layer): Put layer mount events after DOM updated

---

change/@fluentui-react-fefe26e6-3f62-4aaf-960c-63cc828c623f.json
packages/react-examples/src/react/__snapshots__/Checkbox.Basic.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Checkbox.Indeterminate.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Checkbox.Other.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Facepile.Basic.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/OverflowSet.Custom.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/PeoplePicker.Compact.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/PeoplePicker.Controlled.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/PeoplePicker.LimitedSearch.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/PeoplePicker.List.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/PeoplePicker.Normal.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/PeoplePicker.PreselectedItems.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/PeoplePicker.ProcessSelection.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Persona.Basic.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/ThemeProvider.Basic.Example.tsx.shot
packages/react/src/components/Checkbox/Checkbox.base.tsx
packages/react/src/components/Checkbox/Checkbox.test.tsx
packages/react/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
packages/react/src/components/ComboBox/ComboBox.test.tsx
packages/react/src/components/ComboBox/ComboBox.tsx
packages/react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap
packages/react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap

The Combobox currently doesn't apply `aria-selected` to the selected option for single-select combos. While fixing that, I ran into a number of interrelated issues that I also fixed:
- Removed `aria-checked={true/false}` on Checkbox (it's redundant to `checked`, and adds an undesired aria-checked to multiselect Combobox)
- Removed hover-to-select and -focus behavior on Combobox -- the selected state was mixed up with the hover state internally, and also the behavior creates a pretty awful trap for keyboard and SR users, where they essentially get yanked around if they accidentally bump their trackpad. Or just have their cursor in the wrong place on open 😅.
- Fixed the scroll-to-active-option behavior, which was broken b/c of timing issues with Combobox's update vs. Callout's mount.
- …

fix(Combobox): Add aria-selected to single-select combobox, fix scroll-to-view behavior on open

---

apps/public-docsite/src/pages/Overviews/GetStartedPage/docs/web/GetStartedDevelopSimple.md

Fix typo: when using yarn the command is "create react-app", not "create-react-app"

Fix typo: when using yarn the command is "create react-app"

---

change/@fluentui-react-87609c16-e599-49cf-91e0-2ac09923a565.json
packages/react-examples/src/react/__snapshots__/ChoiceGroup.Custom.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.CustomGroupHeaders.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Dropdown.Basic.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Dropdown.Controlled.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Dropdown.ControlledMulti.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Dropdown.Custom.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Dropdown.Error.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Dropdown.Required.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Facepile.Basic.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Facepile.Overflow.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/ResizeGroup.OverflowSet.Example.tsx.shot
packages/react/src/components/Dropdown/Dropdown.base.tsx
packages/react/src/components/Dropdown/Dropdown.test.tsx
packages/react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap

Currently the Dropdown has an `aria-live` attribute on the text value at all times, which means that (depending on the screen reader), all dropdowns present on the page will be announced on page load, and also when the value is updated or cleared by a secondary button/action, the new value will be read out.
This change updates the live region attribute to only be present when the Dropdown has focus, to prevent both of those behaviors.

fix(Dropdown): add aria-live only when focused

---

change/@fluentui-web-components-79361e82-0819-43b5-bb93-6fd3cad41bb0.json
packages/web-components/.storybook/preview-head.html
packages/web-components/src/design-tokens.ts

The fillColor design token was set to a fixed, dark position on the neutral palette. This ignored the baseLayerLuminance design token because it was not possible to only change that and have the design system respond. The ideal flow is that the luminance drives the layer colors and the layer colors are used as backgrounds for fixed sections of the app, even if there is only a single section (layer 1).
Also updated the Storybook wrapper to adjust the navigation text based on the updated fill color.
Default fillColor.

(web-components) Updated the default fill color to neutral layer 1

---

change/@fluentui-react-charting-44a56d43-4438-4700-9c3a-10fd3e6f9d07.json
packages/react-charting/src/components/LineChart/LineChart.base.tsx

In the line chart, Reverse focus order from legends will work with these changes.
Previously line dots were not rendered for non-active lines, which was removing the line chart tabIndex value. This causes the issue.
With new changes, line dots for all lines will render. If the line is selected then Opacity will be 1 for the line dots, and for non-active lines dots, it is 0.01. By this change, the focus indicator will be there.  With this opacity change, the visual appearance is the same as previous and the reverse focus is also working as expected. 
Line chart
https://user-images.githubusercontent.com/29042635/132668438-a802db51-e31f-4854-8347-29967a98e058.mp4
https://user-images.githubusercontent.com/29042635/132668852-29cb2049-cdd8-4c74-8538-f22ee2b …

Fixed: Reverse focus order is not proper in the line chart.

---

change/@uifabric-charting-4d52e727-3d45-4ffd-83cf-843de32420f5.json
packages/charting/src/components/LineChart/LineChart.base.tsx

Cherry pick of [#19708](https://github.com/microsoft/fluentui/pull/19708)
In the line chart, Reverse focus order from legends will work with these changes.
Previously line dots were not rendered for non-active lines, which was removing the line chart tabIndex value. This causes the issue.
With new changes, line dots for all lines will render. If the line is selected then Opacity will be 1 for the line dots, and for non-active lines dots, it is 0.01. By this change, the focus indicator will be there.  With this opacity change, the visual appearance is the same as previous and the reverse focus is also working as expected. 
Line chart
https://user-images.githubusercontent.com/29042635/132668438-a802db51-e31f-4854-8347-29967a98e058.mp4 …

Charting: CherryPick #19708: Fixed: Reverse focus order is not proper in the line chart. #19708

---

change/@fluentui-react-avatar-2b7719a5-f1e9-4e44-b076-cd1ab54986d0.json
change/@fluentui-react-button-d66ecce2-70f2-4d58-b7be-f7ec1fa2f642.json
change/@fluentui-react-link-f1fe2aeb-4e58-4498-a658-54330f6c94ee.json
change/@fluentui-react-slider-68923fec-6673-4d05-a8f8-e6699ed08b35.json
packages/react-avatar/README.md
packages/react-button/README.md
packages/react-link/README.md
packages/react-slider/README.md

Updating converged README.md files to mention exporting from `react-components` instead of `react`

Updating converged README.md files to mention exporting from react-components

---

packages/react-switch/bundle-size/Switch.fixture.js
packages/react-switch/package.json

Adding a `.fixture.js` file to the converged **Switch** component to measure bundle size.

(react-switch) - Adding bundle size tool

---

apps/vr-tests/package.json
apps/vr-tests/src/stories/SwitchNext.stories.tsx

Adding VR tests to the converged **Switch** component.

(react-switch) - Adding VR tests

---

change/@fluentui-react-slider-6cb39555-9ede-4b05-baac-0d9cad3907da.json
packages/react-slider/MIGRATION.md
packages/react-switch/MIGRATION.md

Adding a MIGRATION.md file to the converged **Switch** component and fixing a typo in the react-slider MIGRATION.md file.

(react-switch) - Adding MIGRATION.md

---

change/@fluentui-react-components-2ff28675-4b35-4a5e-b29a-c81f4fb3d320.json
packages/react-components/.gitignore
packages/react-components/config/pre-copy.json
packages/react-components/src/unstable/index.ts
packages/react-components/src/unstable/package.json
packages/react-components/src/unstable/tsconfig.json

Allows the following deep export:
```tsx
import { Switch } from '@fluentui/react-components/unstable'
```
Uses the `copy` task configuration to add a separate entrypoint so that both webpack and jest can load the unstable packages correctly.
The code snippet below shows how to export a component as an unstable one:
```tsx
// packages/react-components/src/unstable/index.ts
export * from '@fluentui/react-switch'
```

feat(react-components): Allow deep export of unstable components

---

tools/generators/migrate-fixed-versions/index.spec.ts
tools/generators/migrate-fixed-versions/index.ts

The migration generator for fixed versions needs to handle dev
dependencies because syncpack will fail on those too.
Also converged packages are used in quite a few utilities in the
monorepo such as perf test, vr test etc.... that also need to be
migrated since syncpack will fail
(optional)

fix(migrate-fixed-dependencies): Handle dev dependencies and utilities

---

packages/fluentui/docs-components/src/knobs/defaultComponents.tsx
packages/fluentui/docs/src/components/ComponentPlayground/ComponentPlaygroundTemplate.tsx

1. Set fixed width for knob input and selects
*Before*
*After*
2. Prevent Component Playground from growing past the layout horizontally
*Before*
*After*

Improve component playground overflow

---

packages/fluentui/docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx

* Use Provider with `darkTheme` for the styling of the Editor menu in ComponentExamples for more consistent design.
* Use regular (instead of tabs) menu for secondary actions
* Use "Undo"-icon for "Reset"-action
* Fix "GitHub-Edit"-link path
*Before*
*After*

Use Provider for editor-menu styling

---

change/office-ui-fabric-react-84d914cc-f2ba-48f5-9902-0cdc125df8d5.json
packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
packages/office-ui-fabric-react/src/components/pickers/BasePicker.types.ts
packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx
packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.types.ts

Cherrypick of https://github.com/microsoft/fluentui/pull/19671
Suggestions currently allow custom search for more text but not icon. This PR makes it so that the icon is also customizable.
(optional)

Cherrypick tschao/customize picker search for more icon

---

change/@fluentui-react-1fa89b42-50f3-4b05-bbf8-37e4f27e94a4.json
packages/react/src/components/ExtendedPicker/BaseExtendedPicker.tsx

In a popout window, users cannot use backspace to remove recipients. This is similar to [this ](https://github.com/microsoft/fluentui/pull/18428) issue that was fixed a couple of months ago. This is another component that needs this fix
(optional)

Backspace does not work in BaseExtendedPicker in projection popout windows

---

change/@fluentui-web-components-488199db-3435-4882-ad28-317c17da5050.json
packages/web-components/package.json
packages/web-components/src/anchor/index.ts
packages/web-components/src/badge/index.ts
packages/web-components/src/button/index.ts
packages/web-components/src/card/index.ts
packages/web-components/src/combobox/index.ts
packages/web-components/src/horizontal-scroll/index.ts
packages/web-components/src/number-field/index.ts
packages/web-components/src/select/index.ts
packages/web-components/src/text-area/index.ts
packages/web-components/src/text-field/index.ts
packages/web-components/src/tooltip/index.ts
yarn.lock

Adds support for base class reference in element composition
(optional)

(web components) add base class support to wc

---

packages/react-examples/src/react/ChoiceGroup/ChoiceGroup.Image.Example.tsx
packages/react-examples/src/react/ChoiceGroup/docs/ChoiceGroupBestPractices.md
packages/react-examples/src/react/__snapshots__/ChoiceGroup.Image.Example.tsx.shot

The ChoiceGroup image variant doesn't accommodate longer text strings, so I added guidance to keep text short, since translation or user styles can lengthen it. This was the solution proposed when consulting with design, since the current design doesn't have a way to handle longer text without significant alteration.
I also update the example to use the correct icon for pie chart, because why not :D

fix(ChoiceGroup): add better guidance for image + text strings, and update the example

---

change/@fluentui-react-aria-d39f839a-af89-4925-a42d-391800f58930.json
packages/react-aria/etc/react-aria.api.md
packages/react-aria/src/hooks/useARIAButton.ts
packages/react-aria/src/index.ts
packages/react-aria/src/utils/index.ts
packages/react-aria/src/utils/mergeARIADisabled.test.ts
packages/react-aria/src/utils/mergeARIADisabled.ts

Generalizes `mergeARIADisabled` to be used in future hooks

react-aria: mergeARIADisabled

---

change/@uifabric-azure-themes-12c9408d-21a4-41c3-8114-a0ecd39c89f6.json
packages/azure-themes/src/azure/AzureColors.ts
packages/azure-themes/src/azure/styles/DefaultButton.styles.ts
packages/azure-themes/src/azure/styles/DropDown.styles.ts
packages/azure-themes/src/azure/styles/TextField.styles.ts

PR created in response to #19656 
Per figma: Input border should be #8A8886, placeholder text: #605E5C
No changes made to other themes (dark, high contrast) and they remain the same.

Azure theme 7.0 placeholder text contrast ratio fix 

---

change/@fluentui-react-popover-cb1197d1-e7ff-49e4-8c18-5770c723dbc8.json
packages/react-popover/etc/react-popover.api.md
packages/react-popover/src/common/isConformant.ts
packages/react-popover/src/components/Popover/Popover.test.tsx
packages/react-popover/src/components/Popover/Popover.types.ts
packages/react-popover/src/components/Popover/__snapshots__/Popover.test.tsx.snap
packages/react-popover/src/components/Popover/usePopover.ts
packages/react-popover/src/components/PopoverSurface/PopoverSurface.tsx
packages/react-popover/src/components/PopoverSurface/PopoverSurface.types.ts
packages/react-popover/src/components/PopoverSurface/renderPopoverSurface.tsx
packages/react-popover/src/components/PopoverSurface/usePopoverSurface.ts
packages/react-popover/src/components/PopoverSurface/usePopoverSurfaceStyles.ts
packages/react-popover/src/components/PopoverTrigger/usePopoverTrigger.ts

refactor(Popover): Remove mergeProps and migrate to simple slots

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/themes/teams-dark/colors.ts
packages/fluentui/react-northstar/src/themes/teams-high-contrast/colors.ts
packages/fluentui/react-northstar/src/themes/teams/colors.ts

I recently added Red Foreground 3 color token in [this PR](https://github.com/microsoft/fluentui/pull/18827)
Design recently found out this color doesn't meet accessibility guidelines for its intended use and are going with a different solution for the banners/alerts

Breaking(Colors): Removing Red Foreground 3 color token

---

packages/react-examples/src/react/MessageBar/MessageBar.Basic.Example.tsx

Updates the Stack flex styles so the messagebars will reflow underneath the ChoiceGroup in the basic example at smaller viewport widths.

fix(MessageBar): tweak example page styles for reflow

---

packages/react-examples/src/react/ContextualMenu/ContextualMenu.Header.Example.tsx

Adds a one-sentence note to the ContextualMenu with headers example, since it seems that teams were confused about it vs. section headers, and there are a11y implications to the difference.

fix(ContextualMenu): add usage note to ContextualMenu header example

---

apps/vr-tests/src/stories/Menu.stories.tsx

Setting the ` open ` prop of both menus can result in race conditions in the positioning of the second menu with respect to the first
(optional)

fix(Menu): Manually open nested menu in vr-test

---

packages/fluentui/CHANGELOG.md
packages/fluentui/docs/src/examples/components/Chat/Types/ChatExampleCompact.shorthand.steps.ts
packages/fluentui/react-northstar/src/themes/teams/components/Chat/chatMessageStylesCompact.ts

Compact chat messages have a highlight effect applied on hover and focus.
This PR restricts the focus condition to keyboard-focus only, as the effect otherwise stays too long on the item.

Show highlight on keyboard-focus only

---

change/@fluentui-react-utilities-5deccccb-84e0-4d5d-9883-ffb340f5ca8c.json
packages/react-utilities/etc/react-utilities.api.md
packages/react-utilities/src/compose/types.ts

Includes `ExtractRef` typings to `react-utilities` to simplify component declaration:
```tsx
export const Button = React.forwardRef<ExtractRef<ButtonProps>, ButtonProps>((props, ref) => { /* ... */ });
export const useButton = (props: ButtonProps, ref: React.Ref<ExtractRef<ButtonProps>>) => {/* ... */}
```
Without `ExtractRef` there'd be a problem with spreading props from components that have `unions` as their props signature, which is the case for `react-button`, as follows:
```tsx
export const Default = (props: ButtonProps) => <Button {...props}>Button</Button>;
```
Without declaring `Button` signature with `ExtractRef` here, this `Default` component would have a conflict between `Button` reference declaration and the reference declaration provided by `ButtonProps`

react-utilities: `ExtractRef` Typings

---

change/@fluentui-web-components-befdf28c-0bd2-48cc-8075-55b3684202e2.json
packages/web-components/docs/api-report.md
packages/web-components/package.json
packages/web-components/src/custom-elements.ts
packages/web-components/src/index.ts
packages/web-components/src/styles/size.ts
packages/web-components/src/toolbar/fixtures/toolbar.html
packages/web-components/src/toolbar/index.ts
packages/web-components/src/toolbar/toolbar.stories.ts
packages/web-components/src/toolbar/toolbar.styles.ts
packages/web-components/src/toolbar/toolbar.vscode.definition.json
yarn.lock

Adds the Toolbar Component
Note:
The keyboarding sequence will be off until this FAST issue is solved:
https://github.com/microsoft/fast/issues/4983

feat: add web components toolbar

---

change/@fluentui-react-725467e3-020e-443b-b050-18b6ba611078.json
packages/react/src/components/DetailsList/DetailsList.test.tsx
packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
packages/react/src/utilities/decorators/withViewport.tsx

See the issue for more details of the investigation that led to this fix.
Introduced a delay of the initial viewport calculation. The delay is the the same amount as the delay in the debounced resize observer. This causes the viewport to get the initial calculation correct because the DetailsList has rendered.  The cascades to preventing DetailsList from having recalculate again.

Details list fix flickering hscroll

---

change/@fluentui-react-slider-209a5408-82e6-4813-98b8-decc9c9abacb.json
packages/react-slider/src/components/Slider/useSliderStyles.ts

Adding the missing `mark` background theme token for the converged **Slider**.

(react-slider) - Adding missing theme token for mark background

---

change/@fluentui-react-utilities-d8107bb6-f0d1-457d-a806-0529a229457d.json
packages/react-utilities/etc/react-utilities.api.md
packages/react-utilities/src/compose/types.ts

Removes `ExtractRef` Typings as it's no longer required after #19793

react-utilities: Removes ExtractRef typings

---

change/@fluentui-web-components-968fea0d-db58-4d9a-92e5-1f7dc21569f2.json
packages/web-components/src/color/palette.ts

This PR mirrors a change in FAST: https://github.com/microsoft/fast/pull/5199
This PR adds a caching mechanism to PaletteRGB.closestIndexOf(). In cases where the provided swatch is not an index of PaletteRGB.swatches, PaletteRGB.closestIndexOf() goes down a somewhat slow code-path to determine which swatch in the set of palette swatches has the closest relative luminance of the provided swatch. In practice, this is often redundant work by the palette and can be sped up significantly by implementing a table-based cache.

implement PaletteRGB.closestIndexOf cache

---

apps/perf-test/package.json
apps/vr-tests/package.json
scripts/package.json

Moves the eslint-plugin package to devDeps for all packages to avoid
having to maintain an extra version group for v9 in #19799
(optional)

chore(eslint-plugin): Move all usages to devdeps

---

packages/a11y-testing/package.json
packages/a11y-testing/src/facades/ComponentTestFacade.tsx

Clean up dependency separation between v9 and non-v9 packages in the
repo.
The usage of the `keyboard-keys` package was fairly limited and the string keys are self explanatory. The `keyboard-keys` package was intended to used in the web platform to reduce bundle size from duplicated strings.
(optional)

chore(a11y-testing): Remove dependency on `keyboard-keys`

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/components/Menu/MenuItem.tsx
packages/fluentui/react-northstar/test/specs/components/Menu/Menu-test.tsx

When the menu is constructed using children instead of shorthand, right arrow does not initially work to open the submenu. It starts working once menu gets opened and closed.
Repro:
open https://codesandbox.io/s/fluent-ui-example-forked-u54vd
Open the avatar/button menu
Press arrow down to navigate to Available
Press arrow right to open the submenu
Expected: Submenu opens
Actual: nothing happens
(optional)

fix: open submenu on arrow right for children api

---

apps/vr-tests/src/stories/Panel.stories.tsx
change/@fluentui-react-7932796b-f453-45d5-b72f-8c3191e35095.json
packages/react/src/components/Panel/Panel.styles.ts

- Expands the Panel `content` when `isFooterAtBottom` is passed as prop and minimum height required is met which then pins the footer at the bottom of the panel, mimicking original behavior.
- Adds VR test for `isFooterAtBottom` case.

Panel: isFooterAtBottom prop now working as expected

---

change/@fluentui-react-charting-7fabb26c-f9e4-4f37-b5be-589800ec4f3c.json
packages/react-charting/src/components/AreaChart/AreaChart.base.tsx

When a series of data is passed to the AreaChart component that uses dates for its x-axis, the following error can occur if all the dates in the series occur on the same day:
`TypeError: Cannot read property 'legend' of undefined`
This is due to `_createDataSet()` within `AreaChart.base.tsx` using Date::toLocaleDateString to group the points together for rendering the chart. This creates too many keys for within the stacked dataset, and causes the error above as an index is then out of bounds later in the rendering.
This PR updates `_createDataSet()` and the callout string to use Date::toLocaleString which resolves the grouping issue, and formats the callout date to include both date and time.
AreaChart

Charting: Fix AreaChart rendering when using dates with only differing times

---

.devops/templates/cleanup.yml
azure-pipelines.hotfix.yml
azure-pipelines.release.yml
azure-pipelines.yml
package.json

Rename the "check for changed files" step to "check for **modified** files" to reduce confusion with the unrelated "check change" (beachball change files) step.
Also rename "check change" to "verify change files" to be a bit clearer (open to better suggestions).

Rename "check for changed files" to "check for modified files"

---

change/@fluentui-react-theme-054eefde-31dc-4278-a07f-c512803787b2.json
packages/react-theme/src/global/borderRadius.ts

This PR updates the value of the `circular` border radius token in the global section of our theme from `50%` to `10000px` to reflect changes in the design tokens superset.

Theme: Updating value of borderRadius global token

---

rfcs/convergence/native-element-props.md

Alternate version of #18804 with a slightly different approach, and broadening the focus beyond input components in some aspects. This came after a discussion in the Redmond components crew sync and incorporates various people's feedback from the previous PR.
In its latest version, this PR proposes two possible solutions:
Allow setting a different "primary" slot where top-level props and ref are applied. Also explicitly expose the `root` slot in props. (`root` is always the root DOM element.)
```jsx
<Input id='foo' root={{ className: 'my-flex' }}/>
<div className='my-flex'>
<input id='foo' />
</div>
```
All components would have a `root` prop, whether or not it is required (different from the place where props are spread).
Define `root` as the native input element, and add a `wrapper` …

RFC: Customizing application of native element props and ref

---

.codesandbox/ci.json
package.json
scripts/beachball/index.ts
scripts/just.config.ts
scripts/monorepo/index.d.ts
scripts/monorepo/index.js
scripts/monorepo/isConvergedPackage.js

Start building a codesandbox template for react-components (https://codesandbox.io/s/fluentui-react-components-9-starter-spnyu) in CI.
Minor hiccup is that apparently converged packages always need to build commonjs due to babel-make-styles, and previously that wasn't included in the `--min` build (which `build:codesandbox` uses). So I updated `scripts/just.config.ts` to handle this.
Partial fix of #19863

Add react-components template to codesandbox CI

---

change/@fluentui-react-utilities-34d09e7a-440e-4cb2-a8ca-5e37f72cfb25.json
packages/react-utilities/etc/react-utilities.api.md
packages/react-utilities/src/compose/makeMergeProps.ts
packages/react-utilities/src/compose/resolveShorthand.ts
packages/react-utilities/src/compose/types.ts
packages/react-utilities/src/hooks/useBoolean.ts
packages/react-utilities/src/hooks/useControllableState.test.ts
packages/react-utilities/src/hooks/useOnClickOutside.ts
packages/react-utilities/src/ssr/SSRContext.tsx

Updates the definitions in react-utilities to use types instead of interfaces.
Per RFC: https://github.com/microsoft/fluentui/pull/19775
(optional)

React utilities interfaces to types

---

tools/generators/migrate-converged-pkg/index.spec.ts
tools/generators/migrate-converged-pkg/index.ts

Reverts microsoft/fluentui#19859
As mentioned [here](https://github.com/microsoft/fluentui/pull/19859#issuecomment-923252990), this is no longer required and should be reverted.

Revert "Add missing `.cache/` dir to `.npmignore` for `migrate-converged-pkg` generator"

---

change/@fluentui-react-button-fcf52db6-2000-4999-b7b5-8f4e23e762e7.json
packages/react-button/src/components/SplitButton/useSplitButtonStyles.ts

`SplitButton`: Adding missing verticalAlign=middle style.

SplitButton: Adding missing verticalAlign=middle style

---

change/@fluentui-react-switch-b245d71e-439a-4dcf-9f77-69b2d9743e7a.json
packages/react-switch/src/components/Switch/Switch.test.tsx
packages/react-switch/src/components/Switch/__snapshots__/Switch.test.tsx.snap
packages/react-switch/src/components/Switch/useSwitchState.ts

Adding `role="switch"` to the hidden input element in the converged **Switch**. Instead of representing `unchecked` and `checked` states, it will represent `on` and `off`.

(react-switch) - Adding switch role to the hidden input

---

scripts/monorepo/isConvergedPackage.js

In `isConvergedPackage`, restore handling for the case where `pathOrPackageJson` is undefined so that it defaults to `process.cwd()`. (This will fix codesandbox CI.)

Fix converged package check for default case

---

scripts/monorepo/runPublished.js

#19783 added a scope for v9 releases. However the changes to the filter comparator broke the scope generation for v8 releases.
For v8 any package not caught by the previous conditions should just be passed through, even web-components 🤔. Could be optimized more in the future but this should fix v8 releases and use the same scope as previously
(optional)

fix(runPublished): Filter condition was empty for v8 releases

---

.github/CODEOWNERS

- Updated to add @khmakoto anywhere @behowell is listed as code owner
- Added react-divider ownership to @microsoft/cxe-prg as shipping in react-components with the beta
- Alphabetized based on folder name within the components section for easier maintenance later
(optional)

Codeowners updated for ben oof

---

change/@fluentui-react-15221f83-6f67-4181-83b0-2c9a9e24b3ac.json
change/@fluentui-react-b27d2d56-1910-4bff-ae88-a1b025a6a37e.json
packages/react-examples/src/react/Callout/Callout.FocusTrap.Example.tsx
packages/react/src/components/FocusTrapZone/FocusTrapZone.tsx

This PR updates a bug in the `FocusTrapCallout` example that was making it impossible for all the buttons inside the callout to be tabbed to. It also makes a small fix in the `FocusTrapZone` comments that referenced `ComboBox` even though that component is unrelated to `FocusTrapZone`.

FocusTrapCallout: Updating example so that all focusable elements are tabbable

---

change/@fluentui-react-divider-a6a812b5-5d5b-4aa0-95a5-e66c6b5cb7d7.json
packages/react-divider/Spec.md
packages/react-divider/etc/react-divider.api.md
packages/react-divider/src/Divider.stories.tsx
packages/react-divider/src/components/Divider/Divider.test.tsx
packages/react-divider/src/components/Divider/Divider.types.ts
packages/react-divider/src/components/Divider/__snapshots__/Divider.test.tsx.snap
packages/react-divider/src/components/Divider/useDividerStyles.ts

- Added DividerProps appearance to remove default value as property is optional.
- Removed DividerProps important as not part of figma spec and confusing with appearance=strong.  Confirmed with Daisy.

Updated DividerProps for consistency

---

change/@fluentui-web-components-7d7304ec-799d-4f98-950d-42e8bf37b003.json
packages/web-components/src/_docs/getting-started/overview.stories.mdx
packages/web-components/src/_docs/integrations/ember.stories.mdx
packages/web-components/src/_docs/integrations/vue.stories.mdx
packages/web-components/src/combobox/combobox.stories.ts

Updated overview document to tie more closely with overall Fluent UI direction.

(web-components) - content update for overview docs

---

change/@fluentui-react-label-59bd42ce-de09-4e78-a509-37d30b17f238.json
change/@fluentui-react-link-7039887a-f2f0-46ef-b40f-9a7291518072.json
change/@fluentui-react-text-f6bb5423-e14a-42a1-86c9-6eebaf3975d0.json
change/@fluentui-react-utilities-a2a91420-444b-431c-b389-505dda1173cb.json
packages/react-link/src/components/Link/useLink.ts
packages/react-text/src/components/Text/useText.ts
packages/react-utilities/src/compose/getSlotsCompat.test.tsx
packages/react-utilities/src/compose/getSlotsCompat.ts
packages/react-utilities/src/utils/getNativeElementProps.test.ts
packages/react-utilities/src/utils/getNativeElementProps.ts

- Added `as` prop to allowed props of `getNativeElementProps`.
- Added `as` prop to the excluded props for `getSlotsCompat` as that would change the API for components that are not using simplified prop merging yet.
- Removed workaround for react-text and react-link.

Add `as` prop to allowed props from `getNativeElementProps`

---

change/@fluentui-react-popover-4546d06a-9706-49b4-8a2d-835b5e7aa87f.json
packages/react-popover/etc/react-popover.api.md
packages/react-popover/src/components/Popover/usePopover.ts
packages/react-popover/src/components/PopoverSurface/usePopoverSurface.ts
packages/react-popover/src/components/PopoverTrigger/PopoverTrigger.test.tsx
packages/react-popover/src/components/PopoverTrigger/usePopoverTrigger.ts

Removes lefover `defaultProps` usages from #19767
Also fixes an issue where user props can never override trigger props
(optional)

fix(Popover): Remove leftover defaultProps and fix trigger props merge

---

change/@fluentui-react-menu-9fe80bc5-0f79-4d2b-a7e1-ce4308a97031.json
packages/react-menu/etc/react-menu.api.md
packages/react-menu/src/components/MenuPopover/index.ts

The refactor to `MenuPopover` was done, later and it turns out that the
styling hook was never exported
(optional)

fix(Menu): export useMenuPopoverStyles

---

.github/CODEOWNERS

react-utilities has no codeowners currently. Assigning teams-prg currently since the initial work on setting up the package was done for components owned by the team. Happy to modify if needed. 
(optional)

chore(react-utilities): Add codeowners

---

rfcs/convergence/avatar-badge-shorthand.md

Preview: [**RFC: Avatar badge shorthand**](https://github.com/behowell/fluentui/blob/rfc-avatar-badge-shorthand/rfcs/convergence/avatar-badge-shorthand.md)
How should the shorthand for `Avatar`'s `badge` slot work?

RFC: Avatar badge shorthand

---

change/@fluentui-react-utilities-e9f87825-e984-4418-b49e-3f07402f1609.json
packages/react-utilities/etc/react-utilities.api.md
packages/react-utilities/src/compose/types.ts

Updates `ComponentState` typings by adding case for when props extends `ObjectShorthandProps`
There's a case for this in `react-checkbox` when a slot expects a custom property instead of an intrinsic one,
```tsx
export type CheckboxSlots = {
root: ObjectShorthandProps<LabelProps> | IntrinsicShorthandProps<'span'>;
};
```
`ObjectShorthandProps<LabelProps>` is not being properly handled by `ComponentState` as it's expected to unwrap `LabelProps` from `ObjectShorthandProps`

react-utilities - ComponentState fix on custom props

---

change/@fluentui-make-styles-600013d4-087f-46dd-b38c-648534d68e60.json
packages/make-styles/etc/make-styles.api.md
packages/make-styles/src/constants.ts
packages/make-styles/src/makeStaticStyles.test.ts
packages/make-styles/src/makeStyles.test.ts
packages/make-styles/src/mergeClasses.test.ts
packages/make-styles/src/mergeClasses.ts

This PR changes `SEQUENCE_PREFIX` to be `___` instead of `__`, this solves the problem with colliding classes when classes from CSS modules are used as input.

fix(mergeClasses): merge classes generated by CSS modules

---

packages/fluentui/CHANGELOG.md
packages/fluentui/e2e/tests/popupIframeInContent-example.tsx
packages/fluentui/e2e/tests/popupIframeInContent.spec.ts
packages/fluentui/react-northstar/src/components/Popup/Popup.tsx

Adds a check inside the `useIFrameFocus` hook callback in `Popup` to check that the iframe is not contained within the `Popup` or the triggger.
Nested popups should be handled by `elementContains` and virtual parents.
(optional)

fix(Popup): Should not dismiss when an iframe content is focused inside

---

change/@fluentui-react-popover-e3fa4fd2-c615-44bf-aa65-8311dd0f20b3.json
packages/react-popover/src/components/PopoverSurface/usePopoverSurfaceStyles.ts
packages/react-popover/src/stories/Popover.stories.tsx
packages/react-popover/src/stories/PopoverDefault.stories.tsx

Adds HC border around `PopoverSurface`, partially addresses issue #19959 to address arrow styling in HC
(optional)

fix(Popover): Add accessible border for HC

---

change/@fluentui-react-charting-362f2982-3f5a-49c8-abac-e01245712012.json
packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.styles.ts
packages/react-charting/src/components/StackedBarChart/StackedBarChart.styles.ts
packages/react-charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap
packages/react-charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap

For stacked bar chart and multi-stacked bar chart, legend container shifted left by 4px, so that keyboard focus should visible fully.
Stacked bar chart and multi-stacked bar chart

Legend container shifted left by 4 px for keyboard focus border

---

change/@uifabric-charting-13197f26-ffb0-4077-90c8-cb26dbe1d6d6.json
packages/charting/src/components/StackedBarChart/MultiStackedBarChart.styles.ts
packages/charting/src/components/StackedBarChart/StackedBarChart.styles.ts
packages/charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap
packages/charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap

Cherry pick of [#19963](https://github.com/microsoft/fluentui/pull/19963)
For stacked bar chart and multi-stacked bar chart, legend container shifted left by 4px, so that keyboard focus should visible fully.
Stacked bar chart and multi-stacked bar chart

Charting: CherryPick #19963: Legend container shifted left by 4 px for keyboard focus border #19963

---

change/@fluentui-react-charting-98dbe053-2d64-4d21-b16c-b3d50c3cb554.json
packages/react-charting/src/components/PieChart/Pie/Pie.tsx

Title tag was showing an extra tooltip on chart hover, so removed that. and added aria-label with svg tag for chart accessibility
(optional)

Pie chart: Title tag removed because of extra tooltip

---

change/@uifabric-charting-7367fe87-44d1-4a39-8407-a36e3351bda3.json
packages/charting/src/components/PieChart/Pie/Pie.tsx

Cherry pick of [#19965](https://github.com/microsoft/fluentui/pull/19965)
Title tag was showing an extra tooltip on chart hover, so removed that. and added aria-label with svg tag for chart accessibility
(optional)

Charting: CherryPick #19965: Pie chart: Title tag removed because of extra tooltip #19965

---

change/@fluentui-react-09f97422-25cb-432f-b1d0-190d1863f5d4.json
packages/react-examples/src/react-tabs/__snapshots__/Tabs.OverflowMenu.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Documents.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Dropdown.Error.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/FocusTrapZone.Box.Click.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/FocusTrapZone.Box.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/FocusTrapZone.Box.FocusOnCustomElement.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/FocusTrapZone.FocusZone.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/FocusTrapZone.Nested.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Pivot.OverflowMenu.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Shimmer.Application.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Toggle.Basic.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Toggle.CustomLabel.Example.tsx.shot
packages/react/src/components/Toggle/Toggle.base.tsx
packages/react/src/components/Toggle/Toggle.test.tsx
packages/react/src/components/Toggle/__snapshots__/Toggle.test.tsx.snap

The on/off state text should not be part of a toggle's accessible name, so I've updated the `ariaLabelledBy` logic to remove it. It's still used as a fallback if no other label is provided, but otherwise not included. More detail in the issue comments: https://github.com/microsoft/fluentui/issues/15109#issuecomment-924184328

fix(Toggle): remove on/off state text from label

---

change/@fluentui-react-file-type-icons-dec3f0e5-ff94-4a2a-80eb-f8111fedd5d5.json
packages/react-file-type-icons/src/FileIconType.ts
packages/react-file-type-icons/src/getFileTypeIconProps.ts

- [ X] Include a change request file using `$ yarn change`
Adding sway icon to react-file-type-icons.
Seems there was already an entry in the map file, but it was never hooked up.
(optional)

Add sway icon to react-file-type-icons

---

packages/react-examples/src/react/ComboBox/ComboBox.CustomStyled.Example.tsx
packages/react-examples/src/react/ComboBox/docs/ComboBoxBestPractices.md
packages/react-examples/src/react/Dropdown/Dropdown.Wrapping.Example.tsx
packages/react-examples/src/react/Dropdown/Dropdown.doc.tsx
packages/react-examples/src/react/Dropdown/docs/DropdownBestPractices.md
packages/react-examples/src/react/__snapshots__/ComboBox.CustomStyled.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Dropdown.Wrapping.Example.tsx.shot

Wrapping text + tooltips has a bunch of a11y issues, so I added some examples & docs to show how to opt out!
Previously made this change on PeoplePicker, this PR adds it to Combo & Dropdown

Add wrapped option text examples to Combobox and Dropdown

---

change/@fluentui-react-experiments-e6a050a9-2965-443d-9084-dd37f119c281.json
packages/react-experiments/src/components/LayoutGroup/LayoutGroup.tsx

Updated `LayoutGroup` to respect the `className` prop, appending the provided value after the mixins from the defined behavior.
`LayoutGroup`.

Support override className in LayoutGroup

---

change/@fluentui-react-5d671d2f-6433-4b73-80b6-bb442e1c1aec.json
packages/react/src/components/pickers/Suggestions/Suggestions.tsx

Pickers used to switch to the dialog role for the suggestions dropdown when there were no suggestions, but the changes in #19606 require a listbox parent.

fix(pickers): use listbox role when picker has no suggestions

---

change/@fluentui-react-8882060f-3a9e-4b9e-8a2b-94ddbf850342.json
packages/react/src/components/TeachingBubble/TeachingBubble.test.tsx
packages/react/src/components/TeachingBubble/TeachingBubbleContent.base.tsx
packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.deprecated.test.tsx.snap
packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.test.tsx.snap

Using `<TeachingBubble />` without providing `ariaDescribedBy` and `ariaLabelledBy` creates a dialog element without necessary ARIA attributes to conform to [WAI-ARIA 1.1](https://www.w3.org/TR/wai-aria-1.1/#dialog).
Nothing changes for users who already used these properties, but users who did not set them properly get a uniquely generated ID applied to relevant elements as needed.

TeachingBubble: Provide default aria attributes for TeachingBubble - 12841

---

change/@fluentui-react-211dc2fd-9965-4eb5-b08f-57a3b42d0f90.json
packages/react-examples/src/react-focus/__snapshots__/FocusZone.List.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Announced.BulkOperations.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Announced.QuickActions.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Advanced.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Animation.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Basic.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.ColumnResize.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Compact.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.CustomColumns.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.CustomFooter.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.CustomGroupHeaders.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.CustomRows.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Documents.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Grouped.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Grouped.Large.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.NavigatingFocus.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.ProportionalColumns.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/GroupedList.CustomCheckbox.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Text.Ramp.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Text.Weights.Example.tsx.shot
packages/react/src/components/DetailsList/DetailsRow.styles.ts
packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
packages/react/src/components/DetailsList/__snapshots__/DetailsRow.test.tsx.snap
packages/react/src/components/Link/Link.styles.ts

From an accessibility standpoint we cannot ensure that all dynamic content passed into `<DetailsRow />` will have sufficient contrast. Therefore it is up to the end user to ensure their components have proper contrast.
However, for the sake of DX we should provide some sensible defaults, and although a case could be made that `<DetailsRow />` should not posses styles for a component it may not even contain, it makes sense to ensure these styles are provided out of the box.
- `<Link />` component as a direct child of a row cell should always have sufficient contrast
- `<Link />` component nested as part of another component should not be affected (avoids regression)

fix(DetailsList): Sufficient Link contrast in selected rows - 12672

---

change/@fluentui-react-f8cd0d3f-b8f8-49ca-88d8-282c3354fb63.json
packages/react-examples/src/react/Callout/Callout.Basic.Example.tsx
packages/react/etc/react.api.md
packages/react/src/components/Callout/CalloutContent.base.tsx
packages/react/src/components/Callout/__snapshots__/Callout.test.tsx.snap
packages/react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap
packages/react/src/components/ContextualMenu/__snapshots__/ContextualMenu.test.tsx.snap
packages/react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
packages/react/src/components/HoverCard/__snapshots__/HoverCard.test.tsx.snap
packages/react/src/components/KeytipLayer/KeytipLayer.test.tsx
packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.test.tsx.snap
packages/react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
packages/react/src/utilities/positioning/positioning.test.ts
packages/react/src/utilities/positioning/positioning.ts
packages/react/src/utilities/positioning/positioning.types.ts

We have several positioning cases that are currently failing:
- When the element doesn't fit neatly on any side, the utility would leave it at the last side checked, even if that side was neither the original one, nor the best fit
- When the element doesn't fit neatly on any side, it would render partially offscreen, making that content entirely inaccessible
- When the callout shifted to overlay the target, the beak would still render, pointing at a random area
I updated the positioning utility and Callout with the following changes:
- When the bounding area is smaller than the positioned element, the positioning utility returns all left/top/right/bottom values, so the Callout can set all four sides within the bounds.
- CalloutContent sets its max height based on the callout, and not on …

Fix positioning utility to handle cases where the positioned element doesn't fit within bounds

---

change/@fluentui-merge-styles-c7dbbce3-56d8-4bb9-9a80-66f82e7896fe.json
change/@fluentui-theme-4bb61d02-e1d9-4ae5-832e-a916bcd9ef66.json
packages/merge-styles/README.md
packages/merge-styles/etc/merge-styles.api.md
packages/merge-styles/src/Stylesheet.test.ts
packages/merge-styles/src/Stylesheet.ts
packages/merge-styles/src/fontFace.test.ts
packages/merge-styles/src/fontFace.ts
packages/merge-styles/src/keyframes.test.ts
packages/merge-styles/src/keyframes.ts
packages/theme/src/types/IFabricConfig.ts

- Related to: #3692, #11411, #19476
The core of the problem lies in using `Stylesheet` as a singleton. As we live in a decentralised server/client ecosystem we have no way to ensure parity of state within a singleton. This PR introduces a way for client-side Stylesheet to try and rehydrate itself in case the server provided the serialized Stylesheet state. This increases the application bundle but is completely voluntary and has to be set by end user so it does not introduce a substantial size increase regression.
This, however, does not resolve the issue of state mismatch for decentralised server rendering such as Gatsby's Incremental Build or NextJS's ISR, which won't be possible unless we opt-in to className hashing.
I refactored the Stylesheet singleton a bit to allow for it's …

merge-styles: Improve SSR experience

---

change/office-ui-fabric-react-6f73eba5-e248-4c9d-a9d2-89a9ee0253b3.json
packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.styles.ts

cherry-pick of #17504 
- Offsetted border of selected row when focused in High Contrast Mode in order to improve visibility and  ensure users are aware of which row is in focus.
**Issue:** 
**Fix:**

[v7.0] DetailsList: selected row border now clearly visible when focused in High Contrast Mode

---

package.json
scripts/beachball/index.ts
yarn.lock

Enable the new `groupChanges` option added in https://github.com/microsoft/beachball/pull/584 -- this makes a single change file for each `yarn change` run, which will make PRs a bit easy to review. 
Example:
```json
{
"changes": [
{
"type": "prerelease",
"comment": "fake",
"packageName": "@fluentui/react-badge",
"email": "elcraig@microsoft.com",
"dependentChangeType": "patch"
},
{
"type": "prerelease",
"comment": "fake",
"packageName": "@fluentui/react-card",
"email": "elcraig@microsoft.com",
"dependentChangeType": "patch"
},
{
"type": "prerelease",
"comment": "fake",
"packageName": "@fluentui/react-components",
"email": "elcraig@microsoft.com",
"dependentChangeType": "patch"
}
]
}
```
([Current limitation](https://github.com/microsoft/beachball/issues/602) is that if you run `yarn …

Update beachball and enabled grouped change files

---

change/@fluentui-react-examples-76b4b323-5cf0-4ab6-9fc9-eeb55a7e79e2.json
change/office-ui-fabric-react-0f391bc5-3a99-4f6f-8dd7-291ac6463b0d.json
packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.base.tsx
packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.test.tsx
packages/office-ui-fabric-react/src/components/DetailsList/DetailsRowCheck.tsx
packages/react-examples/src/office-ui-fabric-react/__snapshots__/Announced.BulkOperations.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/Announced.QuickActions.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Advanced.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Animation.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Basic.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Compact.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.CustomColumns.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.CustomFooter.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.CustomGroupHeaders.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Grouped.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Grouped.Large.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.NavigatingFocus.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.ProportionalColumns.Example.tsx.shot

- [Y] Addresses an existing issue: Fixes #0000
- [Y] Include a change request file using `$ yarn change`
On a single select, the DetailList header section has a check box that is not selectable. This checkbox has aria attibutes but does not have a role attribute causing an accessibility issue [aria-allowed-attr](https://accessibilityinsights.io/info-examples/web/aria-allowed-attr/). The current fix is to remove those aria attributes and resolve the accessibility issue.
(optional)

remove aria attributes from DetailsRowCheck

---

change/@fluentui-react-814bb693-05b1-4c4b-9b33-a4695b4bf333.json
change/@fluentui-react-experiments-d2d23199-aaa3-4462-9e1c-6466930b4b33.json
packages/react-examples/src/react/__snapshots__/ComboBox.Basic.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/ComboBox.Controlled.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/ComboBox.ControlledMulti.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/ComboBox.CustomStyled.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/ComboBox.ErrorHandling.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/ComboBox.Inline.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/ComboBox.SelectAll.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/ComboBox.Toggles.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/ComboBox.Virtualized.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/TimePicker.Example.tsx.shot
packages/react-experiments/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
packages/react/src/components/ComboBox/ComboBox.tsx
packages/react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap

Updated ComboBox error message to be consistent with DropDown (correct ARIA approach)
- Updated to be role="alert"
- Updated div to be added/removed with error message
- Removed aria live and atomic attributes 
- Removed applying aria hidden when no error message
ComboBox
TimePicker (uses ComboBox)

Updated ComboBox error to have role="alert"

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/utils/whatInput.ts

Adds the `WhatInputEvents` to type event listeners with the events that
can be used by what-input
(optional)

fix(whatInput): Type event listeners

---

apps/public-docsite/src/utilities/createSite.tsx

The `fabric.min.css` stylesheet was interfering with component styles, so I updated createSite to order it before any other Fluent styles (which gives it lower priority for the same selector specificity). Fixes text spacing site-only issues for icons, and possibly other components :).

Reorder fabric.min.css insertion in Fluent docsite

---

change/@fluentui-react-examples-23675a69-2a9a-4da5-943f-3e3570356213.json
change/@uifabric-experiments-d9e03ae5-8e76-4b6b-9b18-30ebf49552ea.json
change/office-ui-fabric-react-5309a23c-12d1-4ee2-abb8-37e91b422075.json
packages/experiments/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
packages/office-ui-fabric-react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap
packages/react-examples/src/office-ui-fabric-react/__snapshots__/ComboBox.Basic.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/ComboBox.Controlled.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/ComboBox.ControlledMulti.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/ComboBox.CustomStyled.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/ComboBox.ErrorHandling.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/ComboBox.Toggles.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/ComboBox.Virtualized.Example.tsx.shot

- [ X Include a change request file using `$ yarn change`
Port to 7.0 of the following:
Updated ComboBox error message to be consistent with DropDown (correct ARIA approach)
- Updated to be role="alert"
- Updated div to be added/removed with error message
- Removed aria live and atomic attributes 
- Removed applying aria hidden when no error message
ComboBox

Port 'Updated ComboBox error to have role="alert"' to 7.0

---

change/@fluentui-react-accordion-32aca648-009d-4f30-b946-9d313d2c8512.json
change/@fluentui-react-button-7eabaa4b-cce6-4e23-933d-f28a827734a2.json
change/@fluentui-react-checkbox-cd4216e1-692d-4641-a4e1-36f668a0df13.json
change/@fluentui-react-link-cea407d9-dd47-4cf1-86e1-5fb33434985c.json
change/@fluentui-react-menu-54061d79-fc53-4f87-8238-3b84628e879b.json
change/@fluentui-react-slider-84f87cb9-85b4-4a59-b5fe-cae8fe8a97bb.json
change/@fluentui-react-switch-7f2bf0df-639d-409b-843b-66e3896f0dd7.json
change/@fluentui-react-tabster-c78ad5dc-ba5f-4995-a7b5-9189b74a6bab.json
packages/react-accordion/src/components/AccordionHeader/useAccordionHeaderStyles.ts
packages/react-button/src/components/Button/useButtonStyles.ts
packages/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts
packages/react-link/src/components/Link/useLinkStyles.ts
packages/react-menu/src/components/MenuItem/useMenuItemStyles.ts
packages/react-slider/src/components/RangedSlider/useRangedSliderStyles.ts
packages/react-slider/src/components/Slider/useSliderStyles.ts
packages/react-switch/src/components/Switch/useSwitchStyles.ts
packages/react-tabster/etc/react-tabster.api.md
packages/react-tabster/src/hooks/useFocusIndicatorStyle.ts

Update the default focus ring styles to match what's in the current
design token superset. 
Tries to unify the focus outline styles since **there are currently 4 different ways in the codebase how focus outlines are styled**
The new default style uses a pseudo element with a border. This seems to be the best way to mimic the native `outline` css prop with an option to configure the border radius, that works both for JS themes and windows high contrast mode.
Introduces the following patterns for usage:
```ts
import { createCustomFocusIndicatorStyle, createFocusOutlineStyle } from '@fluentui/react-tabster';
const useStyles = makeStyles({
// default focus outline
defaultOutline: theme => createFocusOutlineStyle(theme);
// configure the default focus outline;
configureOutline: theme => …
```

feat(react-tabster): Update default focus outline styles

---

change/change-b0a9f940-3c01-4d2c-9c94-1365bb8eccc0.json
packages/react-menu/src/components/MenuItem/useMenuItemStyles.ts

Removes `foregroundHover` token for HC focus
Before
After
(optional)

fix(Menu): focus HC text

---

scripts/beachball/index.ts

@fluentui/react-componnets@9.0.0-alpha.119 was released incorrectly
because beachball did not apply changes that were in the grouped
changefile. The grouped changelog in react-components was also not
updated.
The release did not pick up the changes in #20041 therefore the latest alpha is in a broken state since theme tokens were broken. Here is an example: https://codesandbox.io/s/white-sea-jkjzq?file=/src/App.js
(optional)

Revert grouped changefile in #20000

---

change/@fluentui-react-card-618cda7b-22af-4a3d-af7c-fc3e9e4f5fb9.json
packages/react-card/bundle-size/Card.All.fixture.js
packages/react-card/bundle-size/Card.fixture.js
packages/react-card/bundle-size/CardFooter.fixture.js
packages/react-card/bundle-size/CardHeader.fixture.js
packages/react-card/bundle-size/CardPreview.fixture.js
packages/react-card/package.json

Added bundle-size fixtures to Card and respective components

react-card - Bundle size fixtures

---

change/@fluentui-font-icons-mdl2-5e34f524-ecb9-42fe-b0e4-d36385e591a8.json
change/@fluentui-react-examples-6dfaeea4-eaeb-475f-b134-4c078244bf32.json
change/@fluentui-react-experiments-0f9d58c0-a55d-4fd5-bec2-cb20a24f6d6c.json
change/@fluentui-react-file-type-icons-ee0f06b1-41ec-4bb5-8589-8984afc410e5.json
packages/font-icons-mdl2/src/index.ts
packages/react-examples/src/react-experiments/TilesList/TilesList.Document.Example.tsx
packages/react-experiments/src/components/FolderCover/initializeFolderCovers.tsx
packages/react-file-type-icons/src/getFileTypeIconAsHTMLString.test.ts
packages/react-file-type-icons/src/initializeFileTypeIcons.tsx

We are shifting to no longer use akamaihd for hosting these assets inside of OneDrive.
This change updates the default URL to point to the location on the new CDN location.
Icon loading

Update BASE_URL to remove depreacted CDN

---

change/@fluentui-react-b1f79e0f-2c24-481e-9ce7-870a2a3d337b.json
packages/react/src/components/Callout/CalloutContent.base.tsx

- Updated the useBounds hook to watch for the targetWindow resize and invalidate the callback to update the cached measurements
- Fixed an issue with the usePosition hook that it was not clearing state when the callout is hidden.
Callout
ContextMenu

Fix callout window resize

---

change/@fluentui-react-experiments-238444d4-1823-4b81-9e2d-4890808aacfe.json
packages/react-experiments/src/components/Tile/Tile.scss
packages/react-experiments/src/components/Tile/Tile.tsx
packages/react-experiments/src/components/Tile/Tile.types.ts

Added disabled state(style) support for a Tile component. so that when one passes the `disabled` prop to this component, its opacity will be reduced by 50%.  This styling is required in order to easily distinguish them from not disabled ones to users. Below is the preview of the change,
Had similar PR for details row: https://github.com/microsoft/fluentui/pull/19979
Tile Component.
(optional)

Added disabled state(style: dimming) for Tile view

---

change/change-a30552b4-069a-4c00-ba6b-dc05bce14ef3.json
packages/react-avatar/src/Avatar.stories.tsx

Reimplements `getFilenameFromUrl` to follow `AvatarProps['image']` signature

react-avatar: Fix stories `getFilenameFromUrl` implementation

---

change/@uifabric-experiments-6a9d1c4e-ede9-42db-a18e-a7734acbd6d6.json
packages/experiments/src/components/LayoutGroup/LayoutGroup.tsx

Cherry-pick LayoutGroup className handling to 7.0

---

change/@fluentui-react-card-05596f5c-6705-41b9-be1a-37b5f9b346a9.json
packages/react-card/etc/react-card.api.md
packages/react-card/src/components/Card/Card.tsx
packages/react-card/src/components/CardFooter/CardFooter.tsx
packages/react-card/src/components/CardHeader/CardHeader.tsx
packages/react-card/src/components/CardPreview/CardPreview.tsx

Adds `ForwardRefComponent` on component declaration as followed by https://github.com/microsoft/fluentui/pull/19923

react-card: Adjust signature to use ForwardRefComponent

---

change/@fluentui-react-switch-c2b06fdf-4a4b-4510-909a-0554b6039369.json
packages/react-switch/etc/react-switch.api.md
packages/react-switch/src/components/Switch/Switch.tsx

Adds `ForwardRefComponent` on component declaration as followed by https://github.com/microsoft/fluentui/pull/19923

react-switch: Adjust signature to use ForwardRefComponent

---

change/@fluentui-web-components-409bc50a-f172-4042-9b98-b68548e4194c.json
packages/web-components/package.json
yarn.lock

Updates package version to ensure latest changes result in the correct selection of tree items.
(optional)

(web-components): fix tree view selection bug

---

change/@fluentui-make-styles-ad78d37d-58a7-46c5-83a2-cac7cce8fcff.json
change/@fluentui-react-make-styles-0c89fe8b-4478-430d-a761-fc6ead7c7eae.json
packages/make-styles/src/makeStyles.test.ts
packages/make-styles/src/renderer/rehydrateRendererCache.ts
packages/make-styles/src/runtime/compileKeyframeCSS.test.ts
packages/make-styles/src/runtime/compileKeyframeCSS.ts
packages/make-styles/src/runtime/resolveStyleRules.test.ts
packages/make-styles/src/runtime/resolveStyleRules.ts
packages/react-make-styles/README.md
packages/react-make-styles/src/createDOMRenderer.test.tsx
packages/react-make-styles/src/renderToStyleElements-node.test.tsx

This PR fixes insertion of keyframes to `style`. CSS rules that were generated previously contained multiple rules (due prefixing), that caused failures in `.insertRule()` calls.
This PR updates `compileKeyframesCSS()` to generate atomic rules instead:
```js
// Before
const rules = [
"@-webkit-keyframes foo{from{height:10px;}to{height:50px;}} @keyframes foo{from{height:10px;}to{height:50px;}}"
];
// After
const rules = [
"@-webkit-keyframes foo{from{height:10px;}to{height:50px;}}",
"@keyframes foo{from{height:10px;}to{height:50px;}}"
];
```

fix(makeStyles): fix insertion of keyframes

---

apps/public-docsite/src/components/Nav/Nav.tsx

The left nav on the [`@fluentui/react` website](https://developer.microsoft.com/en-us/fluentui#/controls/web/button) was using a regex to do case-insensitive comparisons against a user-typed search query, which caused problems if the search query happened to contain invalid regex syntax. Switch to using lowercase string comparisons instead.

Prevent crashes when searching website nav

---

change/@fluentui-react-card-1715b99c-f9b2-4638-b765-5ef2f6ef34aa.json
packages/react-card/etc/react-card.api.md
packages/react-card/src/components/Card/Card.types.ts
packages/react-card/src/components/Card/renderCard.tsx
packages/react-card/src/components/Card/useCard.ts
packages/react-card/src/components/Card/useCardStyles.ts
packages/react-card/src/components/CardFooter/CardFooter.types.ts
packages/react-card/src/components/CardFooter/__snapshots__/CardFooter.test.tsx.snap
packages/react-card/src/components/CardFooter/renderCardFooter.tsx
packages/react-card/src/components/CardFooter/useCardFooter.ts
packages/react-card/src/components/CardFooter/useCardFooterStyles.ts
packages/react-card/src/components/CardHeader/CardHeader.types.ts
packages/react-card/src/components/CardHeader/__snapshots__/CardHeader.test.tsx.snap
packages/react-card/src/components/CardHeader/renderCardHeader.tsx
packages/react-card/src/components/CardHeader/useCardHeader.ts
packages/react-card/src/components/CardHeader/useCardHeaderStyles.ts
packages/react-card/src/components/CardPreview/CardPreview.types.ts
packages/react-card/src/components/CardPreview/renderCardPreview.tsx
packages/react-card/src/components/CardPreview/useCardPreview.ts
packages/react-card/src/components/CardPreview/useCardPreviewStyles.ts

Implementation of https://github.com/microsoft/fluentui/pull/18642 and https://github.com/microsoft/fluentui/pull/19068.

react-card - Migrate Card to new prop merging / root as a slot

---

apps/public-docsite/src/components/Nav/Nav.tsx
change/@fluentui-react-docsite-components-a695e8d1-1d24-4570-aff8-501c7a7e3684.json
packages/react-docsite-components/src/components/Nav/Nav.types.ts

Clicking the X button on the search box on the v8 website nav sets the search query to undefined, which after another recent change started causing a crash. This PR fixes that issue (in `_onSearchQueryChanged `).
While looking at this I noticed a bunch of unnecessary/overcomplicated stuff in the website nav implementation, which I removed (the overall behavior it was trying to accomplish should be preserved). I also fixed some incorrect aria labels.

Fix clearing the search box on the website nav

---

change/@fluentui-react-3f616257-4ae0-4337-9048-f8c9f9a64aaa.json
packages/react-examples/src/react/__snapshots__/ColorPicker.Basic.Example.tsx.shot
packages/react/etc/react.api.md
packages/react/src/components/ColorPicker/ColorPicker.base.tsx
packages/react/src/components/ColorPicker/ColorPicker.test.tsx
packages/react/src/components/ColorPicker/ColorPicker.types.ts
packages/react/src/components/ColorPicker/__snapshots__/ColorPicker.test.tsx.snap
packages/react/src/components/TextField/TextField.base.tsx
packages/react/src/components/TextField/TextField.types.ts
packages/react/src/components/Tooltip/Tooltip.base.tsx
packages/react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap

Note: **DO NOT PORT TO v7**
this is a behavior change in the component, and introduces Tooltip (creating a bundle size impact in ColorPicker). For those reasons, it is not a candidate to add to v7.
The original issue was the silent auto-change of invalid entries on blur caused accessibility issues -- it was easy to miss, screen readers didn't announce anything, and ZoomText/magnifier users could easily be prevented from noticing it.
This change fixes it by putting the text input in an error state, and showing a tooltip with a brief error message. The tooltip has `role="alert"` so it will be announced, and since this happens while only focus is in the relevant input, pointer/keyboard tooltip access is not an issue.

fix(Colorpicker): Add error state and tooltip when invalid hex/RGBA values are manually entered

---

change/@fluentui-react-76856034-f760-4269-9692-1dc49b4d7fad.json
packages/react/src/components/CalendarDayGrid/CalendarGridDayCell.tsx
packages/react/src/components/WeeklyDayPicker/__snapshots__/WeeklyDayPicker.test.tsx.snap

Both NVDA and VoiceOver have developed recent, severe bugs where they do not read the contents of grid cells when `role="gridcell"` is nested within the `<td>` element. Our Calendar uses that pattern because of a past bug (I believe it was that screen readers read "button" when reaching a cell with a button within it). This PR reverses the change, and puts both `role="gridcell"` and the focuszone target back on the `<td>`.
Tested with NVDA, JAWS, and Narrator -- the experience in each was good with this change. Keyboard and pointer access is unaffected.
Testing with VoiceOver and Talkback as soon as the PR preview link is generated. I'll update the description with the results as soon as that happens. (I already verified on a JS Fiddle that moving the role around fixed the original …

fix(Calendar): move gridcell role and focus target from button to td

---

change/@fluentui-react-7e18ffdf-7154-4a18-9ffa-64d26fa7e78a.json
packages/react/src/components/ComboBox/ComboBox.tsx

The `HTMLElement.scrollIntoView` method has a side effect of sometimes scrolling the parent of the scrolling element, which for inline Combobox will cause the options menu to close. I switched to the safer `parent.offsetTop` scroll approach, which will never cause the page to scroll.

fix(Combobox): switch up scroll-into-view method to never scroll page+close parent combobox menu

---

change/office-ui-fabric-react-47b90c33-a32e-451d-91d4-77cd5349df7d.json
packages/office-ui-fabric-react/src/components/Slider/Slider.base.tsx

PR in master: #17966
This PR is to fix an issue where `onChanged` does not get triggered by the Home or End key, but can get triggered by the directional keys
(optional)

Fix Slider to fire onChanged when Home and End are pressed

---

change/@fluentui-web-components-9b0072b3-17e5-441c-bad4-32af33312546.json
packages/web-components/package.json
packages/web-components/src/_docs/integrations/webpack.stories.mdx
yarn.lock

Fixes web component integration docs to accommodate a breaking change they made in a minor version and updates the package to latest FAST packages.
(optional)

fix web components webpack integration docs

---

change/@fluentui-react-abd666f3-e56b-460d-bd34-16b402508058.json
packages/react/src/components/TimePicker/TimePicker.test.tsx
packages/react/src/components/TimePicker/TimePicker.tsx

TimePicker did not have functioning validation for hour inputs (e.g. 95:59:59 would not prompt an error message).
I think the original validation was not triggering because the RegExp was matching the 5:59:59 portion of 95:59:59 and was returning true.
I rewrote the RegExp and added more specific error messages to help with input formatting. Hopefully they work.
I'm not sure if this needs tests. I think I read for fluentui that it just needs a visual test? Anyhow these seem to render the correct error message. But please check as well. Or let me know if I should write tests :)
Thank you!
10.28.21 update: added tests :)

Adjust TimePicker regex and error message

---

change/@fluentui-react-f13b3b3e-5a7f-49ec-a19b-b514ee5e22f4.json
packages/react-examples/src/react/Pivot/Pivot.OverflowMenu.Example.tsx
packages/react-examples/src/react/__snapshots__/Pivot.OverflowMenu.Example.tsx.shot
packages/react/etc/react.api.md
packages/react/src/components/Pivot/Pivot.base.tsx
packages/react/src/components/Pivot/Pivot.types.ts

Follows the basic pattern of providing an overflow button label prop similar to what exists in components like Breadcrumb and Commandbar.

fix(Pivot): add prop for overflow button label

---

packages/react-input/Spec-styling.md
packages/react-input/Spec-variants.md
packages/react-input/Spec.md
rfcs/convergence/native-element-props.md

Add spec for Input.
Secondary things also included in this PR:
- `Spec-variants.md` under `react-input` has tentative notes about input variants we're not implementing right away. It's not intended to be 100% finished in this PR. A detailed spec and full comparison for any of these variants will be filled out once we're closer to implementing them.
- I made some minor updates to to the primary slot (native-element-props) RFC--just minor formatting and wording improvements, and adding a suggested test

Input spec

---

azure-pipelines.release-vnext-nightly.yml

since #19904 requires more discussion, creating this PR to start
versioning the nightly release pipeline for vNext in the repo.
This pipeline differs from the main release pipeline in the following
ways:
* Bumps packages in the pipeline to nightly versions
* No need for any github related auth or operations
(optional)

chore(release): vNext nightly pipeline

---

change/@fluentui-react-menu-4aae6737-d14b-431b-b989-5195c6c388f3.json
change/@fluentui-react-popover-d6f0341b-5357-4977-87db-d2ca82fcc7d2.json
packages/react-menu/etc/react-menu.api.md
packages/react-menu/src/components/Menu/Menu.test.tsx
packages/react-menu/src/components/MenuDivider/__snapshots__/MenuDivider.test.tsx.snap
packages/react-menu/src/components/MenuDivider/useMenuDividerStyles.ts
packages/react-menu/src/components/MenuGroup/MenuGroup.tsx
packages/react-menu/src/components/MenuGroup/__snapshots__/MenuGroup.test.tsx.snap
packages/react-menu/src/components/MenuGroup/index.ts
packages/react-menu/src/components/MenuGroup/useMenuGroupStyles.ts
packages/react-menu/src/components/MenuGroupHeader/__snapshots__/MenuGroupHeader.test.tsx.snap
packages/react-menu/src/components/MenuGroupHeader/useMenuGroupHeaderStyles.ts
packages/react-menu/src/components/MenuItem/__snapshots__/MenuItem.test.tsx.snap
packages/react-menu/src/components/MenuItem/useMenuItemStyles.ts
packages/react-menu/src/components/MenuItemCheckbox/MenuItemCheckbox.tsx
packages/react-menu/src/components/MenuItemCheckbox/__snapshots__/MenuItemCheckbox.test.tsx.snap
packages/react-menu/src/components/MenuItemCheckbox/index.ts
packages/react-menu/src/components/MenuItemCheckbox/useMenuItemCheckboxStyles.ts
packages/react-menu/src/components/MenuItemRadio/__snapshots__/MenuItemRadio.test.tsx.snap
packages/react-menu/src/components/MenuItemRadio/index.ts
packages/react-menu/src/components/MenuItemRadio/useMenuItemRadioStyles.ts
packages/react-menu/src/components/MenuList/__snapshots__/MenuList.test.tsx.snap
packages/react-menu/src/components/MenuList/useMenuListStyles.ts
packages/react-menu/src/components/MenuPopover/useMenuPopoverStyles.ts
packages/react-menu/src/components/MenuTrigger/MenuTrigger.test.tsx
packages/react-popover/etc/react-popover.api.md
packages/react-popover/src/components/Popover/Popover.test.tsx
packages/react-popover/src/components/PopoverSurface/__snapshots__/PopoverSurface.test.tsx.snap
packages/react-popover/src/components/PopoverSurface/usePopoverSurfaceStyles.ts
packages/react-popover/src/components/PopoverTrigger/PopoverTrigger.test.tsx

✅ _Extracted from #20383, these changes passed conformance test on that PR_
This PR adds static classes to components `@fluentui/react-menu` & `@fluentui/react-popover`.
Classes that are added to DOM are "chained" if they are composed:

feat(menu, popover): add static classes

---

.storybook/preview-head-template.html
change/@fluentui-react-accordion-495d25d1-ba87-4f9c-98f1-e77c35bb97bf.json
change/@fluentui-react-avatar-d04ec1d2-24ed-4000-b6c3-8a24808f0777.json
change/@fluentui-react-provider-10e09617-dfd2-4ada-bfd8-8d91dbe95b6d.json
packages/react-accordion/etc/react-accordion.api.md
packages/react-accordion/src/components/Accordion/Accordion.tsx
packages/react-accordion/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
packages/react-accordion/src/components/Accordion/index.ts
packages/react-accordion/src/components/Accordion/useAccordionStyles.ts
packages/react-accordion/src/components/AccordionHeader/__snapshots__/AccordionHeader.test.tsx.snap
packages/react-accordion/src/components/AccordionHeader/useAccordionHeaderStyles.ts
packages/react-accordion/src/components/AccordionItem/AccordionItem.tsx
packages/react-accordion/src/components/AccordionItem/__snapshots__/AccordionItem.test.tsx.snap
packages/react-accordion/src/components/AccordionItem/index.ts
packages/react-accordion/src/components/AccordionItem/useAccordionItemStyles.ts
packages/react-accordion/src/components/AccordionPanel/useAccordionPanelStyles.ts
packages/react-provider/etc/react-provider.api.md
packages/react-provider/src/components/FluentProvider/__snapshots__/FluentProvider.test.tsx.snap
packages/react-provider/src/components/FluentProvider/index.ts
packages/react-provider/src/components/FluentProvider/useFluentProviderStyles.ts
packages/react-provider/src/components/FluentProvider/useThemeStyleTag.test.ts
packages/react-provider/src/components/FluentProvider/useThemeStyleTag.ts

✅ _Extracted from #20383, these changes passed conformance test on that PR_ 
This PR adds static classes to components `@fluentui/react-accordion` & `@fluentui/react-provider`.

feat(accordion, provider): add static classes

---

change/@fluentui-react-avatar-d04ec1d2-24ed-4000-b6c3-8a24808f0777.json
change/@fluentui-react-badge-05f4fecb-a61c-47a3-9214-64f2056a2200.json
packages/react-avatar/etc/react-avatar.api.md
packages/react-avatar/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
packages/react-avatar/src/components/Avatar/useAvatarStyles.ts
packages/react-badge/etc/react-badge.api.md
packages/react-badge/src/components/Badge/__snapshots__/Badge.test.tsx.snap
packages/react-badge/src/components/Badge/useBadgeStyles.ts
packages/react-badge/src/components/CounterBadge/__snapshots__/CounterBadge.test.tsx.snap
packages/react-badge/src/components/CounterBadge/useCounterBadgeStyles.ts
packages/react-badge/src/components/PresenceBadge/__snapshots__/PresenceBadge.test.tsx.snap
packages/react-badge/src/components/PresenceBadge/usePresenceBadgeStyles.ts

✅ _Extracted from #20383, these changes passed conformance test on that PR_ 
This PR adds static classes to components `@fluentui/react-avatar` & `@fluentui/react-badge`.

feat(avatar, badge): add static classes

---

.storybook/preview.js
change/@fluentui-react-components-d47a7a2f-27ca-4961-944d-5b0e8c775c9a.json
packages/react-components/.storybook/main.js
packages/react-components/package.json
packages/react-storybook/etc/react-storybook.api.md
packages/react-storybook/src/decorators/index.ts
packages/react-storybook/src/decorators/withFluentProvider.tsx
packages/react-storybook/src/index.test.ts

The addon breaks the no build DX for storybook as described in #18357. This PR reverts the register of that
addon and only applying this addon to react-components breaks theming
for all other packages
(optional)

revert(react-storybook-addon): Remove addon and reintroduce `withFluentProvider`

---

change/@fluentui-react-charting-514752d2-399e-418c-83c8-5c85a6496a1e.json
packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx
packages/react-charting/src/utilities/utilities.ts

Now xAxis number will also be localized as per the culture pass.
All charts 
Showing result for Culture="pt-br"

D3 xAxis number localization

---

change/@fluentui-react-examples-c619834f-5e4a-4f24-ba5c-dd2c9d16d866.json
change/office-ui-fabric-react-eedaad9c-e940-42c8-a076-3b80ff71568a.json
packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx
packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.test.tsx
packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts
packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.base.tsx
packages/react-examples/src/office-ui-fabric-react/DetailsList/DetailsList.Grouped.Example.tsx
packages/react-examples/src/office-ui-fabric-react/DetailsList/DetailsList.Grouped.Large.Example.tsx
packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Grouped.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/DetailsList.Grouped.Large.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/GroupedList.CustomCheckbox.Example.tsx.shot

Cherry-pick bug fix from v8 to v7: [fix(DetailsList): add accessible name to group header checkboxes](https://github.com/microsoft/fluentui/pull/17979)
Ran:
- “yarn buildto *examples”
- “yarn update-snapshots”
- “yarn change”
N/A
cc: @smhigley

Cherry-pick fix v8 to v7: fix(DetailsList): add accessible name to group header checkboxes 

---

change/@fluentui-react-062ee806-811e-4a91-a570-68e2cd7e75b9.json
packages/react/etc/react.api.md
packages/react/src/components/DetailsList/DetailsRow.types.ts

This PR makes the `disabled` prop in `IDetailsRowStyleProps` optional as it was introduced as an unintended breaking change by making it required.

DetailsList: Making the disabled prop in IDetailsRowStyleProps optional as making it required is a breaking change

---

change/@fluentui-react-text-f57fa3f1-b465-4c6a-a0f1-a0e6518e427b.json
packages/react-text/etc/react-text.api.md
packages/react-text/src/components/Body/Body.tsx
packages/react-text/src/components/Body/__snapshots__/Body.test.tsx.snap
packages/react-text/src/components/Caption/Caption.tsx
packages/react-text/src/components/Caption/__snapshots__/Caption.test.tsx.snap
packages/react-text/src/components/Display/Display.tsx
packages/react-text/src/components/Display/__snapshots__/Display.test.tsx.snap
packages/react-text/src/components/Headline/Headline.tsx
packages/react-text/src/components/Headline/__snapshots__/Headline.test.tsx.snap
packages/react-text/src/components/LargeTitle/LargeTitle.tsx
packages/react-text/src/components/LargeTitle/__snapshots__/LargeTitle.test.tsx.snap
packages/react-text/src/components/Subheadline/Subheadline.tsx
packages/react-text/src/components/Subheadline/__snapshots__/Subheadline.test.tsx.snap
packages/react-text/src/components/Text/__snapshots__/Text.test.tsx.snap
packages/react-text/src/components/Text/useTextStyles.ts
packages/react-text/src/components/Title1/Title1.tsx
packages/react-text/src/components/Title1/__snapshots__/Title1.test.tsx.snap
packages/react-text/src/components/Title2/Title2.tsx
packages/react-text/src/components/Title2/__snapshots__/Title2.test.tsx.snap
packages/react-text/src/components/Title3/Title3.tsx
packages/react-text/src/components/Title3/__snapshots__/Title3.test.tsx.snap
packages/react-text/src/components/wrapper.tsx

✅ _Extracted from #20383, these changes passed conformance test on that PR_
This PR adds static classes to components `@fluentui/react-text`.
Classes that are added to DOM are "chained" if they are composed:
```html
<span class="fui-Title3 fui-Text"></span>
```
But as we discussed in offline it's not a problem.

feat(text): add static classes

---

change/@fluentui-react-card-83b7c016-46ba-42b5-a1d9-24aac93ceaf8.json
change/@fluentui-react-image-029983f6-5b54-46f2-abe6-ecfec3464c47.json
packages/react-card/etc/react-card.api.md
packages/react-card/src/components/Card/__snapshots__/Card.test.tsx.snap
packages/react-card/src/components/Card/useCardStyles.ts
packages/react-card/src/components/CardFooter/__snapshots__/CardFooter.test.tsx.snap
packages/react-card/src/components/CardFooter/useCardFooterStyles.ts
packages/react-card/src/components/CardHeader/__snapshots__/CardHeader.test.tsx.snap
packages/react-card/src/components/CardHeader/useCardHeaderStyles.ts
packages/react-card/src/components/CardPreview/__snapshots__/CardPreview.test.tsx.snap
packages/react-card/src/components/CardPreview/useCardPreviewStyles.ts
packages/react-image/etc/react-image.api.md
packages/react-image/src/components/Image/__snapshots__/Image.test.tsx.snap
packages/react-image/src/components/Image/useImageStyles.ts
packages/react-radio/etc/react-radio.api.md
packages/react-radio/src/components/Radio/__snapshots__/Radio.test.tsx.snap
packages/react-radio/src/components/Radio/useRadioStyles.ts

✅ _Extracted from #20383, these changes passed conformance test on that PR_ 
This PR adds static classes to components `@fluentui/react-card`, `@fluentui/react-image` & `@fluentui/react-radio`.

feat(card, image, radio): add static classes

---

change/@fluentui-react-popover-c7cc5d31-12ed-4abf-99d5-6ae5dfc0a045.json
packages/react-popover/e2e/Popover.e2e.ts
packages/react-popover/src/components/PopoverTrigger/PopoverTrigger.test.tsx
packages/react-popover/src/components/PopoverTrigger/usePopoverTrigger.ts

When `Popover` is being used with a focus trap the `PopoverSurface` uses
`role="dialog"` which should match the value of `aria-haspopup` in the
trigger element
(optional)

fix(Popover): use `dialog` as value for `aria-haspopup` for focus trap

---

change/@fluentui-react-ccae6604-374f-4fe3-b190-e04874862944.json
packages/react/src/components/pickers/Suggestions/Suggestions.tsx

This PR fixes an issue with `Suggestions` where after hitting the `load more results` button and the focus going back to the first item of those results you couldn't select it via pressing Enter on the keyboard. This was happening because the state was keeping an outdated value which needed clearing so the `keyDown` handling worked correctly.
This can be most easily tested in the `PeoplePicker with limited search` example
__Before: Had to up or down arrow to be able to select an element__
__After: Works as you would expect__

Suggestions: Fixing issue where you couldn't select focused option after hitting 'get more results' button

---

packages/fluentui/docs/src/context/ThemeContext.tsx
packages/fluentui/docs/src/views/ColorPalette.tsx
packages/fluentui/docs/src/views/ColorSchemes.tsx

As I understand it, teamsTheme is deprecated in favor of teamsV2Theme. I've received some requests to change the documentation website's default theme to the most current version, for example to help designers who are visiting the color scheme/palette pages and don't realize that they're looking at the old set of colors.

make teamsV2Theme the default docs theme

---

scripts/tasks/ts.ts

Despite the typescript docs claiming that the `pretty` option is true by default, for some reason this is NOT the case when `tsc` is invoked via `just-task`. (You can try this by intentionally creating a compiler error in some file in `packages/react` locally, then running `yarn build`.) 
EDIT: This appears to be by design (but undocumented) on typescript's side due to the way the tsc process is created within `just-scripts` `tscTask`, with the child's output captured rather than inherited (which is reasonable enough in general). So using `pretty: true` to force pretty output is probably the "right" solution here.
https://github.com/microsoft/TypeScript/blob/95ef2a503dd0cae9f106948cccee8a041078a472/src/executeCommandLine/executeCommandLine.ts#L70-L72 …

Re-enable typescript pretty option

---

change/@fluentui-react-8db5511b-b2a0-4d51-b419-2663c209a273.json
packages/react/src/utilities/positioning/positioning.test.ts
packages/react/src/utilities/positioning/positioning.ts

There was a missed logic step when both `directionalHintFixed` and `alignTargetEdge` are true, when the callout wasn't forcing itself within bounds. Currently, if both are true, the positioning utility will fully adhere to the passed-in directional hint, and not switch the callout to a different edge, no matter the available space. It will still add the correct dimensions to force the callout on screen, no matter how tiny it needs to be.

fix(positioning): handle case when directionalHintFixed and alignTargetEdge are true

---

change/@fluentui-react-9d677af6-df36-4950-906a-2dcfb28ee80f.json
packages/react/src/components/Dialog/Dialog.base.tsx
packages/react/src/components/Dialog/DialogContent.base.tsx
packages/react/src/components/Dialog/__snapshots__/Dialog.deprecated.test.tsx.snap

This PR removes the tooltip from the `Dialog` component's close button as it was covering space without offering any value. This PR also cleans up the code in `Dialog.base.tsx` a little bit by removing places where the same prop was being passed twice, first by passing the prop bespoke and then by spreading an object.

Dialog: Removing tooltip from close button

---

change/@fluentui-react-charting-a1060168-e41d-4848-8b96-92f5715c46d8.json
packages/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
packages/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.types.tsx
packages/react-examples/src/react-charting/GroupedVerticalBarChart/GroupedVerticalBarChart.Basic.Example.tsx

StackCallout functionality is implemented in the Group Vertical Bar chart, so on hover/focus all the Group bars callout content will be shown in the single callout. To do so, "**isCalloutForStack**" prop needs to be set to true. 
Basic example updated with this data.
(optional)

StackCallout implemented in Grouped Vertical Bar chart

---

change/@fluentui-react-components-80bdc7d7-c235-43dc-bbef-7e97bbe9825e.json
packages/react-components/.storybook/manager.js

Adds `manager.js` to `react-components` storybook configuration and adds
the custom theme correctly according to [storybook docs](https://storybook.js.org/docs/react/configure/theming#create-a-theme-quickstart)
(optional)

fix(storybook): Load custom storybook theme correctly

---

tools/generators/migrate-converged-pkg/index.spec.ts
tools/generators/migrate-converged-pkg/index.ts
typings/custom-global/index.d.ts
typings/static-assets/README.md
typings/static-assets/index.d.ts
typings/tsconfig.json

- custom-global types mixes legacy browser ECMA overrides and static-assets. V9 no longer needs legacy overrides as it supports only evergreen browsers.
- This PR creates new typings with narrow focus for static assets + accommodates those changes in our migration generator
(optional)

feat: separate static asset types to separate global package

---

change/@fluentui-react-a9ff1007-5e71-4fa7-ada7-384608fb4560.json
packages/react/src/components/Callout/CalloutContent.base.tsx
packages/react/src/components/Callout/CalloutContent.styles.ts
packages/react/src/components/Callout/__snapshots__/Callout.test.tsx.snap
packages/react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap
packages/react/src/components/ContextualMenu/__snapshots__/ContextualMenu.test.tsx.snap
packages/react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
packages/react/src/components/HoverCard/__snapshots__/HoverCard.test.tsx.snap
packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.test.tsx.snap
packages/react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap

If the Callout content changes without re-rendering, a `maxHeight` prevents it from growing offscreen. `maxHeight` is not applied if the positioning utility applies both `top` and `bottom` values, or if `calloutMaxHeight` is specified.

fix(Callout): add explicit maxHeight

---

change/@fluentui-react-92ffe159-fff9-4f25-880e-7eaba232046d.json
change/@fluentui-react-conformance-15daef73-c2fb-426a-a8dc-cf04fb9e45a4.json
change/@fluentui-react-focus-78f8d0d4-2547-4758-8f25-03aaf90c346f.json
packages/fluentui/react-northstar/test/specs/commonTests/isConformant.tsx
packages/react-conformance/src/defaultErrorMessages.tsx
packages/react-conformance/src/defaultTests.tsx
packages/react-focus/src/common/isConformant.ts
packages/react-input/etc/react-input.api.md
packages/react-input/src/components/Input/__snapshots__/Input.test.tsx.snap
packages/react-input/src/components/Input/useInputStyles.ts
packages/react/src/common/isConformant.ts

This PR adds a new conformance test and asserts for:
- each component has applied `className`, for example `fui-ComponentName`
- matching constants are exported for each component, for example `componentNameClassName`
- tests are applied only for v9 components
I left changes for `Input` component in this PR to be an example. For all other components it was already applied in separate PRs.

test: add conformance test for static classes

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/components/List/List.tsx
packages/fluentui/react-northstar/src/components/List/ListItem.tsx

Make `List` and `ListItem` a `forwardRef` component to properly pass ref to root slots.

fix: Pass ref for List and ListItem

---

change/@fluentui-make-styles-webpack-loader-614a0230-6dd7-4e4c-8bcf-4f0031dc206c.json
packages/make-styles-webpack-loader/__fixtures__/webpack-resolve-plugins/code.ts
packages/make-styles-webpack-loader/__fixtures__/webpack-resolve-plugins/color.ts
packages/make-styles-webpack-loader/__fixtures__/webpack-resolve-plugins/output.ts
packages/make-styles-webpack-loader/src/webpackLoader.test.ts
packages/make-styles-webpack-loader/src/webpackLoader.ts

Adds the resolve plugins from the current webpack compliation object to
`enhancedResolve` just like aliases are.
This will support third party resolve plugins like [ts-config-paths-webpack-plugin](https://github.com/dividab/tsconfig-paths-webpack-plugin)
(optional)

feat(make-styles-webpack-loader): support resolve plugins

---

change/@fluentui-react-3dda684b-13d5-4e3d-b808-93a50341503a.json
packages/react/src/components/Panel/Panel.base.tsx
packages/react/src/components/Panel/Panel.styles.ts
packages/react/src/components/Panel/__snapshots__/Panel.test.tsx.snap

- Removes styling that manually added height to `content` (added by #20136) to keep footer at the bottom of scrollable div but in turn caused the unnecessary scrollbar from occurring. Added `flex` property to scrollable class instead when `isFooterAtBottom` is passed and added `flexGrow` property to `content` to take up the rest of the space in the scrollable container thus pushing the `footer` to the bottom.
- restores `marginTop` attribute that was replaced by #19547.

Panel: fix isFooterAtBottom bug where unnecessary scrollbar is present

---

tools/generators/migrate-converged-pkg/index.spec.ts
tools/generators/migrate-converged-pkg/index.ts
tools/utils.ts

- implements solution style configs migrations within `migrate-converged-pkg` generator
- implements context aware addition of `@testing-library/jest-dom`
- adds context aware setup if `conformance` setup is being used
- adds `js` support to package scaffolding
- adds `e2e` setup support
- adds `type-check` npm script that uses TS build mode 
- requirement for solution style config implementation
- properly runs `tsc` per environment setup without leaking globals
- type checks all code in one run
**Exec migration:**
`yarn nx workspace-generator migrate-converged-pkg --name @fluentui/react-menu`
https://user-images.githubusercontent.com/1223799/140942359-515811d9-6496-46d7-871f-6f743f9e70a2.mov
**No leaking globals/proper isolated …

feat(tools): implement ts solution file config in migration generator

---

change/@fluentui-react-charting-2394eb4f-42a9-4dc9-93b2-0ddb0fc39be6.json
packages/react-charting/src/components/DonutChart/Arc/Arc.styles.ts
packages/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap

DonutChart valueInsideDonut text does not change to light color font in dark mode theme
DonutChart valueInsideDonut text does not change to light color font in dark mode theme
DonutChart

Resolved DonutChart valueInsideDonut text does not change to light color font in dark mode theme

---

change/@uifabric-charting-bccbb6a4-833b-41a6-9be6-3dc021ce4a9f.json
packages/charting/src/components/DonutChart/Arc/Arc.styles.ts
packages/charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap

**Original description**
Cherry Pick #20536 [](https://github.com/microsoft/fluentui/pull/20536)
DonutChart valueInsideDonut text does not change to light color font in dark mode theme
DonutChart valueInsideDonut text does not change to light color font in dark mode theme
DonutChart

Charting:CherryPick#20536:Resolved DonutChart valueInsideDonut text does not change to light color font in dark mode theme

---

tools/generators/migrate-converged-pkg/index.spec.ts
tools/generators/migrate-converged-pkg/index.ts

- Implements partially #19866, 
- implements https://github.com/microsoft/fluentui/issues/20560
- when running `migrate-converged-pkg` to migrate package setup to TS solution config files, this will automatically remove `@ts-ignores` pragmas that were need - thus allow proper TS checking and DX
(optional)

feat(tools): remove ts-ignore pragmas from stories during migration

---

change/@fluentui-react-menu-2094f79e-b1fa-4a56-b806-883848cdd7b9.json
packages/react-menu/package.json
packages/react-menu/src/components/Menu/useMenu.tsx

`@fluentui/react-menu` should not use `@fluentui/react-provider`, this PR switches dependency to `@fluentui/react-shared-contexts`.

chore(react-menu): use react-shared-contexts instead of react-provider

---

change/@fluentui-react-tabster-71025b3b-cee3-4063-9189-cbec3a3cbe5f.json
packages/react-tabster/package.json
packages/react-tabster/src/hooks/useTabster.ts
yarn.lock

Pulls the latest tabster version to use the changes in microsoft/tabster#64 So that focus sentinels are not used in all components that use tabster.
This will result in partners no longer having focus being stolen unless it's being used in a tabster API
(optional)

feat(react-tabster): Use uncontrolled tabbing by default

---

tools/generators/migrate-converged-pkg/README.md
tools/generators/migrate-converged-pkg/index.spec.ts
tools/generators/migrate-converged-pkg/index.ts
tools/generators/migrate-converged-pkg/schema.json
tools/generators/migrate-converged-pkg/schema.ts
tools/tsconfig.tools.json
tools/utils.ts

Adds support to run migration on multiple packages 
**Before:**
```sh
yarn nx workspace-generator migrate-converged-pkg --name=@fluentui/react-text
yarn nx workspace-generator migrate-converged-pkg --name=@fluentui/react-image
```
**After:**
```sh
yarn nx workspace-generator migrate-converged-pkg --name=@fluentui/react-text,@fluentui/react-image
```
(optional)

feat(tools): enable multiple package migration via --name option

---

azure-pipelines.release-vnext.yml
scripts/beachball/index.ts

Reverts microsoft/fluentui#20471
Since authentication failed during release

Revert "chore(release-vnext): Postpublish step to tag prereleases"

---

change/@fluentui-react-charting-dff810e5-e702-477a-acf1-479a99716cfa.json
packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx
packages/react-charting/src/components/CommonComponents/CartesianChart.types.ts
packages/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
packages/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap
packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx
packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx
packages/react-charting/src/utilities/utilities.ts

The issue is observed when the max y value is an odd number.
But while doing calculations, a decimal number is changed to an integer value, due to which the d3 y-axis scale is not set properly. 
**For example:** 
Suppose, the user passes the data having Y max value is 23, while calculation, it will round off to 24.
Previously all the calculations (like bar height) are done with 23 values, but while showing the y-Axis scale, 24 number was considered.  
With the new change, here the y-axis scale is set with the highest value which will be shown on Y-Axis. 
So all the calculations are done with 24. 
To achieve this, one more prop is added in the cartesian component. Which is used as a callback to set axis data in the individual chart components. And all the calculations are done with the …

Resolved : For vertical bar charts, yAxis height is not proper when highest value is odd number 

---

change/@fluentui-react-9957e130-fd74-4cc0-8e6f-2021ae9d778e.json
packages/react/src/components/Callout/Callout.types.ts

Callout: Specifying that gapSpace prop has pixels as its unit in prop comment.

Callout: Specifying that gapSpace prop has pixels as its unit in prop comment

---

change/@fluentui-react-theme-c199e306-7453-49a4-b630-972843705364.json
packages/react-theme/etc/react-theme.api.md
packages/react-theme/src/index.ts
packages/react-theme/src/themes/ThemeShadows.stories.tsx
packages/react-theme/src/types.ts
packages/react-theme/src/utils/createDarkTheme.ts
packages/react-theme/src/utils/createHighContrastTheme.ts
packages/react-theme/src/utils/createLightTheme.ts
packages/react-theme/src/utils/createTeamsDarkTheme.ts
packages/react-theme/src/utils/shadows.ts

1. Updates y-value for **shadow16** to 8px
2. Add **shadowNNBrand** tokens

feat(react-theme): update shadow design tokens

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/themes/teams/components/Dropdown/dropdownItemStyles.ts

Update color of checkable indicator for dropdown items on hover in high contrast theme:
before:
after:
(optional)

fix color for dropdown checkable indicator in hc theme

---

change/@fluentui-react-button-0f70bf9c-dbf4-4d42-b096-5c4396a59490.json
packages/react-button/etc/react-button.api.md
packages/react-button/package.json
packages/react-button/src/components/MenuButton/MenuButton.types.ts

Projects that were using `@fluentui/react-button` but not `@fluentui/react-menu` would resolve the `MenuButtonProps` type to `any` because `@fluentui/react-menu` was listed as a `devDependency`. Since we want types to be usable and we don't want to tightly couple `@fluentui/react-button` and `@fluentui/react-menu` this PR replicates the needed type in `@fluentui/react-button`.

MenuButton: Removing tight coupling with Menu by replicating type locally

---

change/@fluentui-react-ddb34d7a-c047-4443-a0cd-2eda22ec6308.json
packages/react-examples/src/react/__snapshots__/ChoiceGroup.Custom.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.CustomGroupHeaders.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Dropdown.Basic.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Dropdown.Controlled.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Dropdown.ControlledMulti.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Dropdown.Custom.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Dropdown.Error.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Dropdown.Required.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Dropdown.Wrapping.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Facepile.Basic.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/Facepile.Overflow.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/ResizeGroup.OverflowSet.Example.tsx.shot
packages/react/src/components/Dropdown/Dropdown.styles.ts
packages/react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap

The down caret icon in `Dropdown` was specified with the height of the component but absolutely positioned as `top: 1` which actually made it 1 pixel taller than the `Dropdown` itself. This created a scrollbar in high zoom settings. This PR fixes this by specifying `paddingTop: 1` and `top: 0` so that the caret is still in the same position but the its height is not taller than that of the component itself.

Dropdown: Removing unintended extra height

---

change/@fluentui-react-9b93e6fa-64a9-4967-a364-6a99b78f43e4.json
packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx

This PR fixes an issue where user-provided `focusZoneProps` were not being respected over the default ones used in `ContextualMenu`.

ContextualMenu: Allow focusZoneProps to override default values passed to FocusZone

---

apps/vr-tests/src/stories/z_Callout.stories.tsx
change/@fluentui-react-0305a692-42d9-499d-ac5a-9601e4bc626b.json
packages/react/src/components/Callout/CalloutContent.base.tsx

Setting the Callout's `maxHeight` to prevent it from overflowing offscreen would then affect the next positioning calculation, if the Callout's position or height changed while open. This change ensures subsequent position recalculations start from scratch, and re-apply maxHeight afterwards.
This is done through duplicating the element + removing the `maxHeight`, then using that element to calculate position. This is so style updates for the position calc do not affect the actual Callout DOM.
cc/ @dotnetjunky

fix(Callout): update both maxHeight and positions when positions recalc

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar-fela-renderer/src/felaInvokeKeyframesPlugin.ts

Optimized `felaInvokeKeyframesPlugin` to not create new objects but reuse existing one in `reduce`.
In local run in Teams it shows improvement from 3.8 ms to 0.8 ms for rendering a single button:
In JsBench it shows [~87% improvement](https://jsbench.me/jrkw691j6j/1):
Performance testing for cases when  `felaInvokeKeyframesPlugin` is called with many styles.

Optimized felaInvokeKeyframesPlugin reduced object creation

---

change/@fluentui-react-image-48abb98f-6703-4644-8a0f-8b709c9c9e8a.json
packages/react-image/.npmignore
packages/react-image/.storybook/main.js
packages/react-image/.storybook/tsconfig.json
packages/react-image/config/api-extractor.json
packages/react-image/config/api-extractor.local.json
packages/react-image/jest.config.js
packages/react-image/package.json
packages/react-image/tsconfig.json
packages/react-image/tsconfig.lib.json
packages/react-image/tsconfig.spec.json

Migration of ts config for `react-image` package.

react-image: migrate converged packages to TS Solution style config

---

change/@uifabric-charting-f7bb3167-4a4d-4bd0-b961-d34f5d07cac2.json
packages/charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
packages/charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap
packages/react-examples/src/charting/GroupedVerticalBarChart/GroupedVerticalBarChart.Basic.Example.tsx

Cherry pick of [#20652](https://github.com/microsoft/fluentui/pull/20652)
1. On passing barwidth value to the Group Vertical bar, previously all the bars of a single group were placed too far from each other.
Now With this change, all the bars will be only 2.5px distance from each other. 
This is achieved by setting the Single Group range bandwidth with the below calculation
Suppose, Barwidth is 10, and in single Group, 3 bars are there, and each bar required padding which sets as 2.5
So, total bandwidth = ( Barwidth + Padding ) * Total Bars in a single group
= ( 10 + 2.5 ) * 3
This is how the Inner group range is defined,  with this change bars are close to each other with 2.5Px padding.
And Single Group's X-Axis position is calculated as (to make Bar's in center of the Group x-axis …

Charting: CherryPick #20652: For Grouped Vertical Bar chart, bars will be grouped near to each other for barwidth value. #20652

---

change/@fluentui-react-cbc5b1a0-1178-4792-8db6-5db201a5fbed.json
packages/react/src/components/Dropdown/Dropdown.base.tsx

When the Dropdown Callout (the container for the list of Dropdown options) is positioned a callback on Dropdown is invoked to manage the focus state of options in the Dropdown. This callback will maintain focus on the currently selected option or, when the Dropdown is first opened, focus on the first selected option if there is one. There is a bug in this behavior when Dropdown has a dynamic width (e.g., width: "fit-content") that triggers "first opened" focus behavior. This bug causes screen readers like Narrator and keyboard navigation to be confusing and difficult to use because the focus jumps around in unexpected ways.
This commit introduces a new state variable in Dropdown, "_hasBeenPositioned", that tracks whether the Dropdown's Callout has already been positioned so that we can …

Dropdown focus

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/components/Embed/Embed.tsx

Fix: `Embed` component to properly pass down ref
(optional)

fix: embed component to properly pass ref

---

change/@fluentui-web-components-75f5fbe5-98ae-4794-ac36-659358e98ce8.json
packages/web-components/src/checkbox/checkbox.styles.ts
packages/web-components/src/divider/divider.styles.ts
packages/web-components/src/flipper/flipper.styles.ts
packages/web-components/src/listbox-option/listbox-option.styles.ts
packages/web-components/src/listbox/listbox.styles.ts
packages/web-components/src/menu-item/menu-item.styles.ts
packages/web-components/src/menu/menu.styles.ts
packages/web-components/src/progress/progress-ring/progress-ring.styles.ts
packages/web-components/src/progress/progress/progress.styles.ts
packages/web-components/src/radio-group/radio-group.styles.ts
packages/web-components/src/radio/radio.styles.ts
packages/web-components/src/slider/slider.styles.ts
packages/web-components/src/switch/switch.styles.ts

Removes margins from host `elements.`
(optional)

fix: remove margins on host elements

---

rfcs/convergence/no-css-shorthands-in-make-styles.md

This RFC proposed to forbid usage of CSS shorthands in `makeStyles()` calls. Check also #19402 for context.
---
[📖 Rendered preview](https://github.com/microsoft/fluentui/blob/rfc/no-css-shorthands-in-make-styles/rfcs/convergence/no-css-shorthands-in-make-styles.md)

RFC: Do not allow CSS shorthands in `makeStyles()` calls

---

apps/vr-tests/.storybook/preview.js
apps/vr-tests/src/stories/ColorPicker.stories.tsx
apps/vr-tests/src/stories/ComboBox.stories.tsx
apps/vr-tests/src/stories/SwitchConverged.stories.tsx
apps/vr-tests/src/stories/TextField.stories.tsx
apps/vr-tests/src/utilities/TestWrapperDecorator.tsx
apps/vr-tests/src/utilities/index.ts
apps/vr-tests/src/utilities/types.ts

`vr-tests/.storybook/preview.js` extends `@storybook/addons` with a custom `addStory` API. We had partial type definitions for this, but they weren't entirely complete/correct (types for custom options were missing), and `preview.js` itself didn't reference the types.
To fix, I added the types in a shared file `vr-tests/src/utilities/types.ts` and referenced them in both the `@storybook/addons` module augmentation (in `vr-tests/src/index.ts`) and where the `addStory` API is defined in `vr-tests/.storybook/preview.js`.
(It would also be possible to move the augmentation and types to `typings/storybook__addons`, but I don't think that's desirable in this case since `addStory` is specific to `vr-tests` and we ideally should remove it in the future.)
Adding custom option types revealed that …

Improve vr-tests addStory typings

---

azure-pipelines.yml
lage.config.js

We've had some trouble with [screener failures where the log output is truncated](https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=227445&view=logs&j=a8a82d6e-f5e1-5356-31e4-5989f531914b&t=36c8ed5a-d0ff-5b6c-53c8-f9f3a874675c&l=67200), making it impossible to see what went wrong. This is presumably due to some issue with output buffering in `lage`, but my previous investigations into this haven't been successful (it has multiple abstractions for process output handling that make it hard to follow). 
A workaround now that we have Screener and ScreenerNorthstar as separate jobs, we can go back to invoking the commands directly instead of using `lage` for the build orchestration.

Ensure output is preserved when running screener

---

change/@fluentui-react-6272d530-022c-4ca0-b288-c19a3578d2b6.json
packages/react/src/components/ChoiceGroup/ChoiceGroup.base.tsx

If ChoiceGroup was used entirely on its own, it does not have visible focus because it does not call useFocusRects or otherwise set focus visibility individually. This bug only shows up if it is not used together with ThemeProvider or another component that calls useFocusRects.

fix(ChoiceGroup): call useFocusRects to show focus outline

---

change/@fluentui-react-provider-56c89bdc-0547-4d22-ba0a-c2e0085e613b.json
packages/react-provider/.npmignore
packages/react-provider/.storybook/main.js
packages/react-provider/.storybook/preview.js
packages/react-provider/.storybook/tsconfig.json
packages/react-provider/config/api-extractor.local.json
packages/react-provider/jest.config.js
packages/react-provider/package.json
packages/react-provider/src/stories/FluentProviderDefault.stories.tsx
packages/react-provider/src/stories/FluentProviderFrame.stories.tsx
packages/react-provider/tsconfig.json
packages/react-provider/tsconfig.lib.json
packages/react-provider/tsconfig.spec.json

chore: run migration for @fluentui/react-provider

---

change/@fluentui-react-shared-contexts-0c7eab8e-ca2a-4a04-bf3b-e360b972888d.json
packages/react-shared-contexts/.npmignore
packages/react-shared-contexts/config/api-extractor.local.json
packages/react-shared-contexts/jest.config.js
packages/react-shared-contexts/package.json
packages/react-shared-contexts/tsconfig.json
packages/react-shared-contexts/tsconfig.lib.json
packages/react-shared-contexts/tsconfig.spec.json

- Removed `.storybook` and related `package.json#scripts` (issue created #20724)

chore: run migration for @fluentui/react-shared-contexts

---

.github/labeler.yml
.github/workflows/label-pr.yml
.github/workflows/pr-housekeeping.yml

In an effort to start automating monotonous labeling and organizational tasks, I'm introducing a labeler check to automatically add the label `Type: RFC` for any PR that contains an .md file in the root `rfcs` folder.
The plan is to later on extend this to automate all the things 🧹🙋.
This uses [Github's labeler action ](https://github.com/actions/labeler) to add the said label based on a glob defined in the `labeler.yml` on the root of the .github folder.
`pr-housekeeping.yml` defines the Github check to be run when the PR is created.
The `pull_request_target` trigger is a special trigger that allows for actions to have write permission on the issues, without compromising our workflows if changed by a PR. This special trigger always runs the code from the main branch and is therefore the …

Housekeeping workflow - Add labeler

---

change/@fluentui-react-theme-95bba881-0421-4475-bde5-0bbadf341b4b.json
packages/react-theme/.npmignore
packages/react-theme/.storybook/main.js
packages/react-theme/.storybook/preview.js
packages/react-theme/.storybook/tsconfig.json
packages/react-theme/config/api-extractor.local.json
packages/react-theme/jest.config.js
packages/react-theme/package.json
packages/react-theme/tsconfig.json
packages/react-theme/tsconfig.lib.json
packages/react-theme/tsconfig.spec.json

chore: migrate @fluentui/react-theme

---

tools/generators/migrate-converged-pkg/index.spec.ts
tools/generators/migrate-converged-pkg/index.ts

cypress tests don't necessary need to import anything. They are also not shipped along with the package. We should not fail build if there are no imports in test files
(optional)

chore: Disable `isolatedModules` for e2e tsconfig

---

change/@fluentui-cra-template-40467b48-9fa0-48c0-a783-7a3878481a16.json
packages/cra-template/scripts/test.ts
scripts/projects-test/packPackages.ts

- Running `yarn test` for the `cra-template` package yields an error for Windows users since non-Windows compatible commands are used in the test.
- `packPackages` now uses `npm-which` package for cross OS compatibility.
- now using `cross-env` package to set `CI=1` for cross OS compatibility.

cra-template: fix errors when running test using Windows OS

---

change/@uifabric-charting-5bce18ec-0c4e-4843-8c49-2ea7e97b93e1.json
packages/charting/src/components/CommonComponents/CartesianChart.base.tsx
packages/charting/src/utilities/utilities.ts

Cherry pick of [#20427](https://github.com/microsoft/fluentui/pull/20427)
Now xAxis number will also be localized as per the culture pass.
All charts 
Showing result for Culture="pt-br"

Charting: CherryPick #20427: D3 xAxis number localization #20427

---

change/@fluentui-react-charting-4b9ed43d-b2ea-43b7-ad60-d6cd173388c8.json
packages/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
packages/react-charting/src/types/IDataPoint.ts
packages/react-examples/src/react-charting/GroupedVerticalBarChart/GroupedVerticalBarChart.CustomAccessibility.Example.tsx

New prop added for GroupedVerticalBar chart series I,e **stackCallOutAccessibilityData**.
Recently Stack Callout is implemented in the GroupedVerticalBar chart, with that implementation, this prop was added.
Users can customize the accessibility data for the whole stack callout. 
Grouped Vertical Bar chart
**For Single Callout** 
**For Stacked Callout:**

StackCalloutAccessibility implemented in Group Vertical Bar chart

---

change/@fluentui-react-charting-1a7f0331-e960-45d7-9e3f-f84d09bf27a1.json
packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx
packages/react-charting/src/components/DonutChart/DonutChart.base.tsx
packages/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap
packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx

1. Callout content data focusable attribute sets as false because callout content is not for focus. 
2. For the Donut chart and Horizontal chart, the chart title is used with SVG tag, so on the focus of the chart, NVDA will announce the chart title.
(optional)

Callout content focusable sets false and Title aria-label added for Donut and Horizontal bar chart SVG tags

---

change/@fluentui-react-tabster-48b79843-9d37-473a-9867-25b6de014363.json
packages/react-tabster/.babelrc.json
packages/react-tabster/.npmignore
packages/react-tabster/.storybook/main.js
packages/react-tabster/.storybook/preview.js
packages/react-tabster/.storybook/tsconfig.json
packages/react-tabster/config/api-extractor.local.json
packages/react-tabster/config/tests.js
packages/react-tabster/e2e/tsconfig.json
packages/react-tabster/e2e/useKeyborg.e2e.ts
packages/react-tabster/jest.config.js
packages/react-tabster/package.json
packages/react-tabster/tsconfig.json
packages/react-tabster/tsconfig.lib.json
packages/react-tabster/tsconfig.spec.json

- Restored `--passWithNoTests`

chore: migrate @fluentui/react-tabster

---

change/@fluentui-make-styles-webpack-loader-94516228-2e64-4dc7-b0eb-4b29e75b8697.json
packages/make-styles-webpack-loader/.npmignore
packages/make-styles-webpack-loader/config/api-extractor.local.json
packages/make-styles-webpack-loader/jest.config.js
packages/make-styles-webpack-loader/package.json
packages/make-styles-webpack-loader/tsconfig.json
packages/make-styles-webpack-loader/tsconfig.lib.json
packages/make-styles-webpack-loader/tsconfig.spec.json

- Removed Storybook related in `package.json#scripts` (#20745)
- Removed `.babelrc` (#20746)
- Restored changes in `jest.config.js`  (#20760)

chore: migrate @fluentui/make-styles-webpack-loader

---

change/@fluentui-babel-make-styles-491f40e8-ca6d-43b6-8cc0-7c4d75f0b5ab.json
packages/babel-make-styles/.npmignore
packages/babel-make-styles/config/api-extractor.local.json
packages/babel-make-styles/jest.config.js
packages/babel-make-styles/package.json
packages/babel-make-styles/tsconfig.json
packages/babel-make-styles/tsconfig.lib.json
packages/babel-make-styles/tsconfig.spec.json

- Removed Storybook related in `package.json#scripts` (#20745)
- Removed `.babelrc` (#20746)

chore: run migration for @fluentui/babel-make-styles

---

change/@fluentui-jest-serializer-make-styles-18b8a2a0-fe05-4c69-b002-10fa9db10e89.json
packages/jest-serializer-make-styles/.npmignore
packages/jest-serializer-make-styles/config/api-extractor.local.json
packages/jest-serializer-make-styles/jest.config.js
packages/jest-serializer-make-styles/package.json
packages/jest-serializer-make-styles/tsconfig.json
packages/jest-serializer-make-styles/tsconfig.lib.json
packages/jest-serializer-make-styles/tsconfig.spec.json

- Removed Storybook related in `package.json#scripts` (#20745)
- Removed `.babelrc` (#20746)

chore: run migration for @fluentui/jest-serializer-make-styles

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/components/Accordion/AccordionContent.tsx
packages/fluentui/react-northstar/src/components/Accordion/AccordionTitle.tsx
packages/fluentui/react-northstar/test/specs/components/Accordion/Accordion-test.tsx

According to axe-core rules, dd/dt cannot have role `heading` assigned.
As dd/dt do not add any functionality, it should be ok to replace them with div.
screenshot tests

fix(Accordion): Use divs instead of dd/dt to comply with axe rules [BREAKING]

---

.devops/templates/tools.yml
change/@fluentui-eslint-plugin-bdc15f5d-ef63-4e26-89c5-6983d11bfd6a.json
package.json
packages/eslint-plugin/package.json
packages/eslint-plugin/src/configs/react.js
yarn.lock

Reverted CI node version back to 12. Version 14 errors when building `@fluentui/react-icons-mdl2`.
Removed usage of the plugin @rnx-kit/eslint-plugin as it requires node v14.

fix: Revert to node 12

---

change/@fluentui-babel-make-styles-0f380f7f-bdcf-47cc-90fe-13178669ca54.json
packages/babel-make-styles/__fixtures__/compiled-optional-chaining/code.ts
packages/babel-make-styles/__fixtures__/compiled-optional-chaining/output.ts
packages/babel-make-styles/__fixtures__/object-computed-keys/code.ts
packages/babel-make-styles/__fixtures__/object-computed-keys/output.ts
packages/babel-make-styles/__fixtures__/object-mixins/mixins.ts
packages/babel-make-styles/__fixtures__/object-mixins/output.ts
packages/babel-make-styles/__fixtures__/object-variables/code.ts
packages/babel-make-styles/__fixtures__/object-variables/output.ts
packages/babel-make-styles/__fixtures__/object/code.ts
packages/babel-make-styles/__fixtures__/object/output.ts

This PR updates Babel plugin fixtures to not use CSS shorthands as in #20573 we agreed to not support them.

chore(babel-make-styles): update fixtures

---

change/@fluentui-react-popover-acc8b8e5-c330-42f1-bed9-ddeca5f7ef3c.json
packages/react-popover/src/components/PopoverSurface/usePopoverSurfaceStyles.ts
packages/react-popover/src/stories/PopoverAnchorToCustomTarget.stories.tsx
packages/react-popover/src/stories/PopoverControllingOpenAndClose.stories.tsx
packages/react-popover/src/stories/PopoverCustomTrigger.stories.tsx
packages/react-popover/src/stories/PopoverDefault.stories.tsx
packages/react-popover/src/stories/PopoverInternalUpdateContent.stories.tsx
packages/react-popover/src/stories/PopoverNestedPopovers.stories.tsx
packages/react-popover/src/stories/PopoverTrappingFocus.stories.tsx

This PR:
- updates stories to not use CSS shorthands
- cleanups types, removes `codesandbox-dependency` comments

fix(react-popover): update styles to not use CSS shorthands

---

change/@fluentui-react-card-9c7aabc3-29bc-4b08-b8de-3987c7d51d7f.json
packages/react-card/src/components/Card/useCardStyles.ts
packages/react-card/src/components/CardFooter/useCardFooterStyles.ts
packages/react-card/src/components/CardHeader/useCardHeaderStyles.ts
packages/react-card/src/components/CardPreview/useCardPreviewStyles.ts

This PR updates styles to not use CSS shorthands.

fix(react-card): update styles to not use CSS shorthands

---

change/@fluentui-react-badge-62bec824-8a11-43c4-b060-980434512988.json
packages/react-badge/src/components/Badge/useBadgeStyles.ts
packages/react-badge/src/components/CounterBadge/useCounterBadgeStyles.ts
packages/react-badge/src/components/PresenceBadge/usePresenceBadgeStyles.ts

This PR updates styles to not use CSS shorthands.

fix(react-badge): update styles to not use CSS shorthands

---

change/@fluentui-react-menu-51a84edb-faf4-40ce-b165-89b7f4bfc088.json
packages/react-menu/src/components/MenuDivider/useMenuDividerStyles.ts
packages/react-menu/src/components/MenuItem/useMenuItemStyles.ts
packages/react-menu/src/components/MenuList/useMenuListStyles.ts
packages/react-menu/src/components/MenuPopover/useMenuPopoverStyles.ts
packages/react-menu/src/stories/MenuCustomTrigger.stories.tsx
packages/react-menu/src/stories/MenuInteraction.stories.tsx
packages/react-menu/src/stories/MenuRenderFunctionTrigger.stories.tsx

This PR:
- cleanups TODOs in stories

fix(react-menu): update styles to not use CSS shorthands

---

change/@uifabric-charting-5a27d57f-6740-4ee5-8fb2-bdd7e541a0bd.json
packages/charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
packages/charting/src/types/IDataPoint.ts
packages/react-examples/src/charting/GroupedVerticalBarChart/GroupedVerticalBarChart.CustomAccessibility.Example.tsx

Cherry pick of [#20585](https://github.com/microsoft/fluentui/pull/20585)
New prop added for GroupedVerticalBar chart series I,e **stackCallOutAccessibilityData**.
Recently Stack Callout is implemented in the GroupedVerticalBar chart, with that implementation, this prop was added.
Users can customize the accessibility data for the whole stack callout. 
Grouped Vertical Bar chart
**For Single Callout** 
**For Stacked Callout:**

Charting: CherryPick #20585: StackCalloutAccessibility implemented in Group Vertical Bar chart #20585

---

change/office-ui-fabric-react-2020-12-30-03-22-23-combobox-checkbox-option-7.json
packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.test.tsx
packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.types.ts
packages/office-ui-fabric-react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap
packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx
packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx
packages/office-ui-fabric-react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
packages/office-ui-fabric-react/src/utilities/selectableOption/SelectableDroppableText.types.ts
packages/react-examples/src/office-ui-fabric-react/ComboBox/ComboBox.Basic.Example.tsx
packages/react-examples/src/office-ui-fabric-react/ComboBox/ComboBox.Controlled.Example.tsx
packages/react-examples/src/office-ui-fabric-react/ComboBox/ComboBox.ControlledMulti.Example.tsx
packages/react-examples/src/office-ui-fabric-react/ComboBox/ComboBox.CustomStyled.Example.tsx
packages/react-examples/src/office-ui-fabric-react/ComboBox/ComboBox.ErrorHandling.Example.tsx
packages/react-examples/src/office-ui-fabric-react/ComboBox/ComboBox.Toggles.Example.tsx
packages/react-examples/src/office-ui-fabric-react/ComboBox/ComboBox.Virtualized.Example.tsx
packages/react-examples/src/office-ui-fabric-react/ComboBox/ComboBox.doc.tsx
packages/react-examples/src/office-ui-fabric-react/__snapshots__/ComboBox.Basic.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/ComboBox.Controlled.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/ComboBox.ControlledMulti.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/ComboBox.CustomStyled.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/ComboBox.ErrorHandling.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/ComboBox.Toggles.Example.tsx.shot
packages/react-examples/src/office-ui-fabric-react/__snapshots__/ComboBox.Virtualized.Example.tsx.shot

ComboBox tries to pass `role="option"` and some `data-*` props as top-level props to an option Checkbox in multi-select mode. As documented in #16307, Checkbox currently doesn't apply most native props, so these props aren't applied. This is definitely a problem (Accessibility Insights flags it) but probably got missed since none of the ComboBox examples on the website used multi-select.
Related changes:
- Fix a minor version of this issue in Dropdown, where `data-*` props are passed as top-level props to the Checkbox (the more significant issue with the role had already been fixed)
- Add multi-select ComboBox examples on the website, and fix the controlled examples to actually work with freeform mode
- Add snapshot tests for ComboBox and Dropdown's open states
(master version: #16331)

(7.0) ComboBox: fix multi-select checkbox role; improve docs and examples

---

change/@fluentui-react-2bc57354-2f2d-448d-b39e-6121f7a1ee42.json
packages/react-examples/src/react/Panel/Panel.Footer.Example.tsx
packages/react/src/components/Panel/Panel.styles.ts
packages/react/src/components/Panel/__snapshots__/Panel.test.tsx.snap

- Adds `z-index: 1` property to header/navigation bar when minimum height is met to ensure that contents with `position: relative`  (like Button) don't overlap with the header when scrolling down.
- There will now be a `footer` background when `footer` is "fixed" at the bottom to ensure that when dynamic content is added, that content does not overlap with the footer when scrolling down. 
-

Panel: Content no longer overlaps with header and footer when scrolling.

---

change/@fluentui-react-conformance-22f06fc8-ab9b-441d-930e-1131d6665e17.json
packages/react-conformance/src/defaultErrorMessages.tsx
packages/react-conformance/src/defaultTests.tsx
packages/react-input/Spec.md
packages/react-input/etc/react-input.api.md
packages/react-input/src/components/Input/Input.stories.tsx
packages/react-input/src/components/Input/Input.types.ts
packages/react-input/src/components/Input/useInput.ts
packages/react-input/src/components/Input/useInputStyles.ts

After a discussion in the input sync, we decided to change the name of `Input`'s `fieldSize` prop back to `size` for consistency across all components. 
`size` [overlaps with a native prop](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/size) which sets the width of the field in "number of characters." This isn't ideal, but we're going with it since the native prop isn't very useful in practice, and it was hard to find another reasonable/consistent name for the visual size prop. (If anyone needs the native functionality, we could add an `htmlSize` prop in the future.)
Also includes a test to prevent application of `size` as a native prop.

Input: Change fieldSize prop name back to size

---

change/@fluentui-react-tooltip-581f9543-2c4c-43f4-99ea-f593d94eb064.json
packages/react-tooltip/src/components/Tooltip/useTooltipStyles.ts
packages/react-tooltip/src/stories/TooltipAria.stories.tsx
packages/react-tooltip/src/stories/TooltipControlled.stories.tsx
packages/react-tooltip/src/stories/TooltipDefault.stories.tsx
packages/react-tooltip/src/stories/TooltipOnlyIfTruncated.stories.tsx
packages/react-tooltip/src/stories/TooltipPositioning.stories.tsx

This PR:
- updates stories to not use CSS shorthands
- removes `codesandbox-dependency` comments

fix(react-tooltip): update styles to not use CSS shorthands

---

change/@fluentui-react-button-791d358e-16fb-46a8-adbd-3e5c3c476632.json
packages/react-button/src/components/Button/stories/ButtonAppearance.stories.tsx
packages/react-button/src/components/Button/stories/ButtonBlock.stories.tsx
packages/react-button/src/components/Button/stories/ButtonDefault.stories.tsx
packages/react-button/src/components/Button/stories/ButtonDisabled.stories.tsx
packages/react-button/src/components/Button/stories/ButtonIcon.stories.tsx
packages/react-button/src/components/Button/stories/ButtonShape.stories.tsx
packages/react-button/src/components/Button/stories/ButtonSize.stories.tsx
packages/react-button/src/components/Button/useButtonStyles.ts
packages/react-button/src/components/CompoundButton/stories/CompoundButtonAppearance.stories.tsx
packages/react-button/src/components/CompoundButton/stories/CompoundButtonBlock.stories.tsx
packages/react-button/src/components/CompoundButton/stories/CompoundButtonDefault.stories.tsx
packages/react-button/src/components/CompoundButton/stories/CompoundButtonDisabled.stories.tsx
packages/react-button/src/components/CompoundButton/stories/CompoundButtonIcon.stories.tsx
packages/react-button/src/components/CompoundButton/stories/CompoundButtonShape.stories.tsx
packages/react-button/src/components/CompoundButton/stories/CompoundButtonSize.stories.tsx
packages/react-button/src/components/CompoundButton/stories/CompoundButtonWithLongText.stories.tsx
packages/react-button/src/components/CompoundButton/useCompoundButtonStyles.ts
packages/react-button/src/components/MenuButton/stories/MenuButtonAppearance.stories.tsx
packages/react-button/src/components/MenuButton/stories/MenuButtonBlock.stories.tsx
packages/react-button/src/components/MenuButton/stories/MenuButtonDefault.stories.tsx
packages/react-button/src/components/MenuButton/stories/MenuButtonDisabled.stories.tsx
packages/react-button/src/components/MenuButton/stories/MenuButtonIcon.stories.tsx
packages/react-button/src/components/MenuButton/stories/MenuButtonShape.stories.tsx
packages/react-button/src/components/MenuButton/stories/MenuButtonSize.stories.tsx
packages/react-button/src/components/MenuButton/stories/MenuButtonSizeLarge.stories.tsx
packages/react-button/src/components/MenuButton/stories/MenuButtonSizeMedium.stories.tsx
packages/react-button/src/components/MenuButton/stories/MenuButtonSizeSmall.stories.tsx
packages/react-button/src/components/MenuButton/stories/MenuButtonWithLongText.stories.tsx
packages/react-button/src/components/ToggleButton/useToggleButtonStyles.ts

fix(react-button): update styles to not use CSS shorthands

---

change/@fluentui-react-divider-11cbcc30-fbbe-4089-9bd0-cbefce7b1147.json
packages/react-divider/src/components/Divider/useDividerStyles.ts
packages/react-divider/src/stories/DividerAlignContent.stories.tsx
packages/react-divider/src/stories/DividerAppearance.stories.tsx
packages/react-divider/src/stories/DividerCustomStyles.stories.tsx
packages/react-divider/src/stories/DividerDefault.stories.tsx
packages/react-divider/src/stories/DividerInset.stories.tsx
packages/react-divider/src/stories/DividerVertical.stories.tsx

fix(react-divider): update styles to not use CSS shorthands

---

change/@fluentui-react-e62b6d7b-78cd-4608-875d-64734092f5fb.json
packages/react/etc/react.api.md
packages/react/src/Theme.ts

In #20665 we went away from `export *` everywhere, but unfortunately lost few re-exports and it's an unexpected breaking change 💥
```sh
PS office-ui-fabric-react> node 1.js
undefined
PS office-ui-fabric-react> node 1.js
{
black: '#000000',
gray220: '#11100f',
}
```

fix: restore missing exports in v8

---

change/@fluentui-react-image-f564a1b4-7542-42b2-b9aa-fa0421f9be5e.json
packages/react-image/src/components/Image/useImageStyles.ts
packages/react-image/src/stories/ImageBlock.stories.tsx
packages/react-image/src/stories/ImageBordered.stories.tsx
packages/react-image/src/stories/ImageDefault.stories.tsx
packages/react-image/src/stories/ImageFallback.stories.tsx
packages/react-image/src/stories/ImageFit.stories.tsx
packages/react-image/src/stories/ImageShadow.stories.tsx
packages/react-image/src/stories/ImageShape.stories.tsx

fix(react-image): update styles to not use CSS shorthands

---

change/@fluentui-react-avatar-8bb1e8aa-bfd9-4c42-aa44-390bae8c5d03.json
packages/react-avatar/src/AvatarActive.stories.tsx
packages/react-avatar/src/AvatarActiveAppearance.stories.tsx
packages/react-avatar/src/AvatarBadge.stories.tsx
packages/react-avatar/src/AvatarColor.stories.tsx
packages/react-avatar/src/AvatarColorBrand.stories.tsx
packages/react-avatar/src/AvatarColorColorful.stories.tsx
packages/react-avatar/src/AvatarColorNeutral.stories.tsx
packages/react-avatar/src/AvatarDefault.stories.tsx
packages/react-avatar/src/AvatarGetInitials.stories.tsx
packages/react-avatar/src/AvatarIcon.stories.tsx
packages/react-avatar/src/AvatarIdForColor.stories.tsx
packages/react-avatar/src/AvatarImage.stories.tsx
packages/react-avatar/src/AvatarName.stories.tsx
packages/react-avatar/src/AvatarShape.stories.tsx
packages/react-avatar/src/AvatarSize.stories.tsx
packages/react-avatar/src/components/Avatar/useAvatarStyles.ts

fix(react-avatar): update styles to not use CSS shorthands

---

change/@fluentui-codemods-c84885d7-44fa-4817-9bdb-34a26522cf13.json
packages/codemods/package.json
packages/codemods/src/codeMods/tests/mock/v9/mMakeStylesDeep.ts
packages/codemods/src/codeMods/tests/v9ThemeFlattening/v9ThemeFlattening.test.ts

Refactors the current test to not require an import from v9. The import itself is actually not important to the test.
(optional)

fix(codemods): Remove v9 make-styles dependency

---

change/@fluentui-react-positioning-a73e5056-5b35-45d3-b98a-637c6b67b2ec.json
change/@fluentui-react-tabster-e69fb0b0-ee22-4d15-8450-ed01fc8cd402.json
packages/react-positioning/src/createArrowStyles.ts
packages/react-tabster/src/hooks/useFocusIndicatorStyle.ts

This PR updates styles to not use CSS shorthands.

fix(react-positioning,react-tabster): update styles to not use CSS shorthands

---

change/@fluentui-react-text-f73e0a50-d72e-4f5b-bcf3-4c500cec695d.json
packages/react-text/src/components/Text/Text.test.tsx
packages/react-text/src/components/Text/useTextStyles.ts
packages/react-text/src/stories/Default.stories.tsx
packages/react-text/src/stories/TextFont.stories.tsx
packages/react-text/src/stories/TextItalic.stories.tsx
packages/react-text/src/stories/TextSize.stories.tsx
packages/react-text/src/stories/TextStrikeThrough.stories.tsx
packages/react-text/src/stories/TextTruncate.stories.tsx
packages/react-text/src/stories/TextTypography.stories.tsx
packages/react-text/src/stories/TextUnderline.stories.tsx
packages/react-text/src/stories/TextWeight.stories.tsx

fix(react-text): update styles to not use CSS shorthands

---

packages/fluentui/CHANGELOG.md
packages/fluentui/docs/src/components/ComponentDoc/ComponentProp/ComponentPropName.tsx
packages/fluentui/react-northstar/src/components/MenuButton/MenuButton.tsx
packages/fluentui/react-northstar/src/components/Popup/Popup.tsx

`className`, `styles` & `variables` were exposed on `Popup` component, but never really worked. This PR removes them from types.

fix(Popup): remove unsupported styling props

---

packages/fluentui/CHANGELOG.md
packages/fluentui/accessibility/src/behaviors/Carousel/carouselBehavior.ts
packages/fluentui/accessibility/test/behaviors/caroselBehavior-test.tsx
packages/fluentui/docs/src/examples/components/Carousel/BestPractices/CarouselBestPractices.tsx
packages/fluentui/docs/src/examples/components/Carousel/Types/CarouselExample.shorthand.tsx
packages/fluentui/docs/src/examples/components/Carousel/Types/CarouselPaginationExample.shorthand.tsx
packages/fluentui/docs/src/examples/components/Carousel/Variations/CarouselCircularExample.shorthand.tsx
packages/fluentui/docs/src/examples/components/Carousel/Variations/CarouselExampleWithFocusableElements.tsx
packages/fluentui/docs/src/examples/components/Carousel/Variations/CarouselThumbnailsExample.shorthand.tsx
packages/fluentui/e2e/tests/carouselClickableContent-example.tsx
packages/fluentui/react-northstar/src/components/Carousel/Carousel.tsx
packages/fluentui/react-northstar/src/themes/teams/components/Menu/menuItemIconStyles.ts

We initially should use native ARIA props, but somehow we overlooked this 🙉
```tsx
<Carousel ariaRoleDescription="carousel" ariaLabel="Portrait collection" />
```
```tsx
<Carousel aria-roledescription="carousel" aria-label="Portrait collection" />
```

fix(react-northstar): use native ARIA props

---

apps/vr-tests/package.json
apps/vr-tests/src/stories/InputConverged.stories.tsx
packages/react-input/Spec-styling.md
packages/react-input/Spec.md
packages/react-input/src/components/Input/useInputStyles.ts

Add hover styles and focus underline for Input, and add visual tests.
Input is supposed to have a very specific bottom focus border style which was a pain to implement. The comments within the styling file explain a lot of the reasoning behind the approach (and hopefully will help prevent accidental changes).

Input: add interaction styling and vr-tests

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/components/Video/Video.tsx

Fix `Video` component to properly pass ref to root slot
(optional)

fix: video component to properly pass ref to root slot

---

change/@fluentui-web-components-8052c655-9663-4c94-bc57-b4090f16ab2d.json
packages/web-components/src/tabs/tabs.stories.ts
packages/web-components/src/tabs/tabs.styles.ts

Aligns tabpanel to the top in vertical layout
(optional)

fix: vertical tabs from jumping

---

.storybook/preview-head-template.html
change/@fluentui-react-components-49ec8f54-7c30-4c2d-a8a4-7a29909b42fd.json
packages/react-components/src/DocsComponents/FluentDocsPage.stories.tsx

Remove edit controls from ArgsTable in docs.
The editors currently do not work as expected. We have a tracking issue #19309 to improve them, until that happens let's hide them to avoid confusion.

docs(storybook): hide editors in ArgsTable

---

change/@fluentui-date-time-utilities-7c5c9bb3-ffd3-45cc-9aef-cb226b301d7b.json
packages/date-time-utilities/src/timeFormatting/timeFormatting.test.ts

- ~[ ] Addresses an existing issue:~
- this package was failing on local machine if contributor wasn't based in USA or didnt have set locale to `en-US`
**Before:**
**After:**

test(date-time-utils): make test pass for every contributor

---

change/@fluentui-react-components-74838f56-ea28-4f5a-87d3-0262737d8baa.json
packages/react-components/.storybook/main.js

This PR disables SB addon as it breaks buildless experience to start Storybook, we should reenable it later.
Issue to enable back: https://github.com/microsoft/fluentui/issues/20896

chore: disable custom Storybook addon in react-components

---

change/@fluentui-react-94e9e9c3-4144-45ac-85d9-242011b8a27e.json
packages/react/src/utilities/positioning/positioning.test.ts
packages/react/src/utilities/positioning/positioning.ts

When the element is flush against the bounds on the opposite side of its anchor edge, allow finalizing the return edge. Changing the edge in this scenario doesn't change the positioning or visuals of the element but does allow the element to grow away from the bounds if necessary.
Any other use cases of `finalHeight` which is how we get in the scenario of not finalizing the return edge usually.

Positioning: Allow swapping anchor edge when on boundary and won't cause visual differences

---

change/@fluentui-react-slider-adb3b9a6-93c2-4a83-ac82-1978bd258e89.json
packages/react-input/src/components/Input/Input.stories.tsx
packages/react-input/src/components/Input/useInputStyles.ts
packages/react-radio/src/components/RadioItem/useRadioItemStyles.ts
packages/react-slider/src/RangedSlider.stories.tsx
packages/react-slider/src/Slider.stories.tsx
packages/react-slider/src/components/RangedSlider/useRangedSliderStyles.ts
packages/react-slider/src/components/Slider/useSliderStyles.ts

This PR updates styles to not use CSS shorthands in `@fluentui/react-slider`, `@fluentui/react-radio` and leftovers in `@fluentui/react-input`.

fix(slider|input|radio): use CSS shorthands in styles

---

apps/ts-minbar-test-react-components/src/index.ts
apps/ts-minbar-test-react/src/index.ts

In the ts-minbar tests, both the setup and the actual test were wrapped in the same try/catch, leading to misleading error messages if the setup failed.
Fix is to split the setup and the actual test into separate try/catch blocks. I also added more details to the actual test's error message.

Improve error messages for ts-minbar tests

---

change/@fluentui-azure-themes-e1e1c8ac-92f1-4423-aa03-d8234356ae79.json
packages/azure-themes/src/azure/Constants.ts
packages/azure-themes/src/azure/styles/Tooltip.styles.ts

Fixed tooltip styling for dark theme. All other themes unchanged with this change. 
Before: 
After: 
Other themes with new change:
Cherry-pick from #20860

Cherry-pick from #20860: Azure-theme tooltip dark theme fix

---

change/@uifabric-azure-themes-cc16cfa0-d0c6-4594-8bc9-2636f3fc6b47.json
packages/azure-themes/src/azure/Constants.ts
packages/azure-themes/src/azure/styles/Tooltip.styles.ts

Fixed tooltip styling for dark theme. All other themes unchanged with this change. 
Before: 
After: 
Other themes with new change:
Cherry-pick: #20861

Azure-theme tooltip dark theme fix (7.0)

---

change/@fluentui-react-theme-d84a9be2-458a-4000-8686-95f2ba2f0cfa.json
packages/react-theme/etc/react-theme.api.md
packages/react-theme/src/alias/dark.ts
packages/react-theme/src/alias/highContrast.ts
packages/react-theme/src/alias/light.ts
packages/react-theme/src/alias/teamsDark.ts
packages/react-theme/src/types.ts

Add border1 color token for all shared colors, e.g. `colorPaletteDarkRedBorder1` for dark red:

feat(react-theme) Add border1 color token for shared colors

---

change/@fluentui-react-menu-108a6441-1cfd-416b-bf2e-86d29fca5c90.json
packages/react-menu/e2e/Menu.e2e.ts
packages/react-menu/src/components/Menu/useMenu.tsx
packages/react-menu/src/components/MenuTrigger/useTriggerElement.ts

Reverts a part of #18618 where the first menu item was not focused on click, but was done for `Enter`
(optional)

fix(Menu): Focus on first menu item on click

---

change/@fluentui-babel-make-styles-e24db7df-1613-42dd-aa1a-a4ddb5b85b83.json
packages/babel-make-styles/__fixtures__/function-imported-keys/code.ts
packages/babel-make-styles/__fixtures__/function-imported-keys/consts.ts
packages/babel-make-styles/__fixtures__/function-imported-keys/output.ts
packages/babel-make-styles/__fixtures__/object-imported-keys/code.ts
packages/babel-make-styles/__fixtures__/object-imported-keys/consts.ts
packages/babel-make-styles/__fixtures__/object-imported-keys/output.ts
packages/babel-make-styles/src/plugin.ts

This PR adds to Babel plugin evaluation of computed keys on objects:
```tsx
const useStyles = makeStyles({
root: {
// 👇 regular key, no need to evaluate
":hover": { color: "red" },
// 👇 computed key, may come from an import
[selector]: { color: "red" }
}
});
```
New fixture was also added ✅

fix(makeStyles): correctly handle computed keys

---

change/@fluentui-react-ecc8a72e-6b2c-434a-8e2d-4594944b54ad.json
packages/react-examples/package.json
packages/react-examples/src/react/CommandBar/CommandBar.Basic.Example.tsx
packages/react-examples/src/react/__snapshots__/CommandBar.Basic.Example.tsx.shot
packages/react/etc/react.api.md
packages/react/src/components/Button/BaseButton.tsx
packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx
packages/react/src/components/ContextualMenu/ContextualMenu.tsx
packages/react/src/components/ContextualMenu/ContextualMenu.types.ts
packages/react/src/utilities/contextualMenu/contextualMenuUtility.ts

One common scenario for which `CommandBar` and `ContextualMenu` is used is to trigger the Browser's File System dialog, typically to Upload an item. Common practice is to generate an `input` element on the click, and then invoke `.click()` directly onto it. The browser will recognize that the activity is still within the 'trust period' of the UX event and launch the dialog. Since an Upload is long-lived, the best place to attach the `input` element is to the end of the DOM, as a hidden node, and to clean it up once the upload is complete.
This pattern is pretty easy to implement and fairly common, and works in most cases.
However, when a `CommandBar` is wrapped in a `FocusTrapZone`, the basic implementation of the scenario breaks: the `FocusTrapZone`'s global click handler intercepts the …

Support ability to set a context menu item's event target to the Menu root

---

change/@fluentui-bundle-size-f8a1b468-b3bf-466c-a6fc-ee3258d5da53.json
packages/bundle-size/src/utils/buildFixture.test.js

`buildFixture` was trying to test that the function would throw asynchronously. However, the `expect` call was never awaited, and the usage of `.rejects`  was incorrect.
Therefore the test always passed and the jest was left with an unresolved promise error
(optional)

fix(bundle-size): incorrect promise test

---

change/@fluentui-make-styles-901b66ec-0438-4a53-9088-395f1a048d8d.json
packages/make-styles/src/shorthands/border.ts
packages/make-styles/src/shorthands/borderBottom.ts
packages/make-styles/src/shorthands/borderColor.ts
packages/make-styles/src/shorthands/borderLeft.ts
packages/make-styles/src/shorthands/borderRadius.ts
packages/make-styles/src/shorthands/borderRight.ts
packages/make-styles/src/shorthands/borderStyle.ts
packages/make-styles/src/shorthands/borderTop.ts
packages/make-styles/src/shorthands/borderWidth.ts
packages/make-styles/src/shorthands/gap.ts
packages/make-styles/src/shorthands/margin.ts
packages/make-styles/src/shorthands/overflow.ts
packages/make-styles/src/shorthands/padding.ts

A minor improvement to shorthand functions to have proper return types instead of full object.

fix(makeStyles): improve return types for shorthand functions

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/components/Animation/Animation.tsx
packages/fluentui/react-northstar/test/__mocks__/react-transition-group.ts

Fix `Animation` to properly pass ref to root slot

fix: Animation to properly pass ref to root slot

---

change/@fluentui-react-ad24fc8e-0cbf-4ec4-a54b-e64f35b51637.json
packages/react-examples/src/react/__snapshots__/Checkbox.Indeterminate.Example.tsx.shot
packages/react/src/components/Checkbox/Checkbox.styles.ts

When a checked checkbox (controlled) is set to indeterminate, the checkmark opacity is set to 1, but should be 0. This is not noticed in most cases because the mark and background are the same color.
- Updated to opacity 0 when indeterminate (style rule only change)
(optional)

Fix #20043 - Checkbox checkmark should have opacity 0 in indeterminate state

---

.devops/templates/tools.yml
change/@fluentui-eslint-plugin-85794a53-50f5-4b78-b297-dfc48bad0916.json
package.json
packages/eslint-plugin/package.json
packages/eslint-plugin/src/configs/react.js
yarn.lock

create-react-app recently released v5.0 which is incompatible with node 12. We also can't pin create-react-app to v4 because it will throw and tell us to use the latest version 🤦
cra errors without latest version
https://github.com/facebook/create-react-app/blob/69321b0d55859db3058266437b90c43eb4f0dbb7/packages/create-react-app/createReactApp.js#L211
cra errors with node < 14
https://github.com/facebook/create-react-app/blob/69321b0d55859db3058266437b90c43eb4f0dbb7/packages/create-react-app/createReactApp.js#L253
Fixes #20834
Reverts microsoft/fluentui#20781

Upgrade to node 14 (i.e. revert "Revert to node 12")

---

change/@fluentui-web-components-2ae56d3f-5f09-4765-89cd-f5dbcf84acea.json
packages/web-components/src/flipper/flipper.styles.ts

Adds `pointer-events: none` to the `disabled` class
(optional)

fix: prevent disabled flipper from emitting event

---

change/@fluentui-babel-make-styles-640822ac-aebd-493a-8831-79760610f65b.json
packages/babel-make-styles/__fixtures__/object-sequence-expr/code.ts
packages/babel-make-styles/__fixtures__/object-sequence-expr/output.ts
packages/babel-make-styles/src/plugin.ts

This PR adds the ability to the `babel-make-styles` plugin to handle sequence expressions like the one below:
```ts
import { makeStyles, MakeStylesStyle } from '@fluentui/react-make-styles';
const switchClassName = 'fui-Switch';
let _a: Record<string, MakeStylesStyle>;
export const useStyles = makeStyles({
root:
((_a = {}),
(_a[':hover .' + switchClassName] = {
':before': {
backgroundColor: 'red',
},
}),
_a),
});
```
A new fixture to test this was also added

babel-make-styles: Correctly handling sequence expressions

---

change/@fluentui-react-8c6f90dd-1df8-4efd-b3de-f26cbd10596e.json
packages/react/src/components/ComboBox/ComboBox.tsx
packages/react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap

Adds `aria-multiselectable` to the listbox element of multiselect Comboboxes. Single-line change + snapshot update.

Add aria-multiselectable to multiselect Combobox

---

change/@fluentui-eslint-plugin-5733e325-0c8b-4b50-ad12-d52a70e3d28b.json
packages/eslint-plugin/src/configs/react.js
packages/eslint-plugin/src/utils/configHelpers.js

I noticed that our eslint plugin was classifying anything with `*.stories.tsx` as a test rather than an example, which is an artifact from when this extension was only used for stories in `vr-tests`. Update the classification in the plugin, and separately disable one relevant rule in `vr-tests`.

eslint-plugin: classify stories as examples not tests

---

apps/ssr-tests/just.config.ts
apps/ssr-tests/package.json
package.json
packages/fluentui/digest/package.json
packages/fluentui/perf-test/package.json
scripts/just.config.ts
scripts/tasks/api-extractor.ts
scripts/tasks/argv.ts
scripts/tasks/jest.ts
scripts/tasks/ts.ts
scripts/tasks/webpack.ts
yarn.lock

Update `just-scripts` to allow removing some of the more complex workarounds for build task customization.
- Use a [new API Extractor task option I added](https://github.com/microsoft/just/pull/563) to override API Extractor options for converged packages without overwriting any files on the disk. (API Extractor itself provides a way to do this, we just didn't have a way to access it via the task before.)
- Allow passing through arbitrary options to `jest`
- Factor out arg parsing into a separate helper with appropriate types, and use that in appropriate places
- Simplify how TS task args are calculated

Update just-scripts and remove some workarounds for customizing build tasks

---

change/@fluentui-react-a72f59c8-a71c-45c5-8372-f2ac3e1a1bd8.json
packages/react/etc/react.api.md
packages/react/src/components/ComboBox/ComboBox.test.tsx
packages/react/src/components/ComboBox/ComboBox.tsx
packages/react/src/components/ComboBox/ComboBox.types.ts

The [documentation](https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox) mentions that you can override autofill.onInputValueChange if you want to be notified of raw text input to the ComboBox. But the issue is that this overrides the [ComboBox's implementation of onInputValueChange](https://github.com/microsoft/fluentui/blob/HEAD/packages/react/src/components/ComboBox/ComboBox.tsx#L588) to the underlying autofill, causing a lot of issues. (Text does not update; up, down, left, right, enter keys don't work as expected)
The change provides a way to extend rather than override the underlying autofill's onInputValueChange prop. An additional prop (callback) is added to the ComboBoxProps and called from [_onInputChange](https://github.com/microsoft/fluentui/blob/HEAD/packages …

Combobox: Provide a callback to listen to raw text input

---

apps/ts-minbar-test-react-components/src/index.ts
apps/ts-minbar-test-react/src/index.ts
change/@fluentui-cra-template-48461590-a8b5-440d-8741-30860247bd1b.json
packages/cra-template/scripts/test.ts
packages/fluentui/projects-test/src/createReactApp.ts
packages/fluentui/projects-test/src/nextjs.ts
packages/fluentui/projects-test/src/rollup.ts
packages/fluentui/projects-test/src/typings.ts
scripts/gulp/sh.ts
scripts/projects-test/createReactApp.ts
scripts/projects-test/performBrowserTest.ts
scripts/projects-test/utils.ts

We were seeing intermittent errors running `yarn` in the test for `@fluentui/cra-template`, the TS minbar tests, and possibly also projects-test. Things like this:
`verb @fluentui/cra-template test |  error An unexpected error occurred: "ENOENT: no such file or directory, open '/home/cloudtest/.cache/yarn/v6/npm-@babel-runtime-7.16.3-b86f0db02a04187a3c17caa77de69840165d42d5-integrity/node_modules/@babel/runtime/.yarn-metadata.json'".`
`verb ts-minbar-test-react-components test |  error https://registry.yarnpkg.com/@babel/runtime/-/runtime-7.16.3.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "EEXIST: file already exists, mkdir '/home/cloudtest/.cache/yarn/v6/npm-@babel-runtime-7.16.3-b86f0db02a04187a3c17caa77de69840165d42d5-integrity/node_modules/@babel/ru …

Use a custom cache directory for each test that runs yarn

---

change/@fluentui-react-ab8e2990-b17d-4210-b514-30a0cb04b452.json
change/@fluentui-react-experiments-0b77bb7d-5bbe-457b-95c9-6a5970609121.json
change/@fluentui-react-hooks-c07633ea-c71c-4e99-9a4a-cc10394bf71c.json
change/@fluentui-test-utilities-493d57c1-c975-4c23-aea6-fd2dff463193.json
change/@fluentui-utilities-2d40b849-0e8a-4a69-a942-c4454fdde763.json
packages/react-experiments/src/components/FloatingSuggestionsComposite/FloatingSuggestionsComposite.test.tsx
packages/react-hooks/src/useUnmount.test.tsx
packages/react/__mocks__/@fluentui/utilities.ts
packages/react/src/common/testUtilities.ts
packages/react/src/components/ChoiceGroup/ChoiceGroup.test.tsx
packages/react/src/components/DetailsList/DetailsList.test.tsx
packages/react/src/components/Pivot/Pivot.test.tsx
packages/react/src/components/TextField/TextField.test.tsx
packages/react/src/components/pickers/BasePicker.test.tsx
packages/react/src/utilities/ThemeProvider/ThemeProvider.test.tsx
packages/test-utilities/src/safeMount.ts
packages/utilities/src/customizations/useCustomizationSettings.test.tsx
packages/utilities/src/styled.test.tsx
packages/utilities/src/useFocusRects.test.tsx

New edition of #17050. Copying the original description...
--------
While trying to run tests with React 17 (see #16886), I found a few instances where either:
- Tests were doing things incorrectly in ways that (for whatever reason) worked in master, but doesn't work after upgrading React/Jest
- Tests were doing things in a less than ideal way which outright stops working after upgrading React/Jest
This PR fixes those issues where it makes sense to go ahead and do so. Some common ones:
- React 17-related test utilities have a nice warning when you use the wrong `act` helper, which several tests were.
- When rendering with `react-dom`, should use `act` from `react-dom/test-utils`
- When rendering with Enzyme, should use `act` from `enzyme`
- React 17 and/or Jest 25 (and its jsdom version) …

Fix test issues discovered while trying to test React 17 (take 2)

---

apps/vr-tests/src/stories/InputConverged.stories.tsx
packages/react-input/Spec.md
packages/react-input/etc/react-input.api.md
packages/react-input/src/components/Input/Input.stories.tsx
packages/react-input/src/components/Input/Input.test.tsx
packages/react-input/src/components/Input/Input.types.ts
packages/react-input/src/components/Input/__snapshots__/Input.test.tsx.snap
packages/react-input/src/components/Input/renderInput.tsx
packages/react-input/src/components/Input/useInput.ts
packages/react-input/src/components/Input/useInputStyles.ts

- Set Input's primary slot to `input`
- Added an `onChange` callback with standard signature (since apparently I forgot to do that before)
- Fixed types of `value` and `defaultValue` to only accept strings (or undefined)
- Add tests for `value`, `defaultValue`, and `onChange`
- Updated the spec to reduce duplication with the types files and be clearer on certain points
- Removed `InputCommons`
One other change was getting rid of the `InputCommons` type. Everything is now in `InputProps`, and `InputState` uses `Required<Pick<InputProps, 'some' | 'prop' | 'names'>>`.
What got me thinking about this was noticing that components are inconsistent about how required/optional things are handled in commons and props--whether things are:
- optional in commons type (to reflect props) then do `type …

Input: implement primary slot

---

change/office-ui-fabric-react-5217a157-b9b8-4ab3-b9c4-5f7713d1f168.json
packages/office-ui-fabric-react/src/components/TeachingBubble/TeachingBubbleContent.base.tsx
packages/office-ui-fabric-react/src/components/TeachingBubble/__snapshots__/TeachingBubble.deprecated.test.tsx.snap
packages/office-ui-fabric-react/src/components/TeachingBubble/__snapshots__/TeachingBubble.test.tsx.snap
packages/react-examples/src/office-ui-fabric-react/__snapshots__/CommandBar.CommandBarButtonAs.Example.tsx.shot

Add aria-level to heading. Cherry-pick of #19374.
(optional)

Add aria-level to TeachingBubble heading

---

change/@fluentui-react-menu-faccd61d-d9b2-4508-bd9d-b8b5ac2a360b.json
packages/react-menu/e2e/Menu.e2e.ts
packages/react-menu/src/components/Menu/useMenu.tsx
packages/react-menu/src/stories/MenuBestPractices.md

In order to support different types of menu trigger such as split
items and have more flexibility with the component, the `Menu` component
no longer does a runtime check to find a `MenuTrigger`component.
Now the usage of the `Menu` must have `MenuTrigger` as the first child.
This is already implicitly the case in all the documentation examples.
Added a documentation snippet to state this explicitly in the `Menu`
docs.
Added a test to make sure that the usage of `Menu` without a
`MenuTrigger` is still possible and does not regress.
(optional)

breaking: MenuTrigger must be the first child of the `Menu`

---

packages/react-examples/src/react/CommandBar/CommandBar.SplitDisabled.Example.tsx
packages/react-examples/src/react/__snapshots__/CommandBar.SplitDisabled.Example.tsx.shot

Adds splitbutton menu button labels to the CommandBar example. Examples-only change.

Add splitbutton labels to Commandbar example

---

change/@fluentui-react-6185695e-90a7-4334-a2c0-b2f29e60efc6.json
packages/react-examples/src/react/__snapshots__/Separator.Basic.Example.tsx.shot
packages/react/src/components/Stack/Stack.test.tsx
packages/react/src/components/Stack/Stack.tsx
packages/react/src/components/Stack/__snapshots__/Stack.test.tsx.snap

This pull requests fixes issue #20586: When using a React.Fragment component to wrap a StackItem component, the parent Stack component logic ignores the inner StackItem(s) because it can only see the React.Fragment as children.
With this change the <Stack> logic will now ignore the React.Fragment and jump down to its children instead.

Fixing React.Fragment wrapping StackItems inside a Stack.

---

packages/react-input/src/components/Input/useInputStyles.ts

@spmonahan noticed that the disabled Input accidentally had hover and active styles. This PR fixes the issue by moving the hover and focus styles into separate rules which are only applied if the Input is not disabled.

Input: prevent hover/active styles when disabled

---

rfcs/react-components/convergence/event-handlers-arguments.md

We had a [previous RFC about event handler arguments](https://github.com/microsoft/fluentui/blob/master/rfcs/convergence/event-handlers-arguments.md) which established that event handlers should have the following signature:
- First param: an event (React.SyntheticEvent or DOM) or `null` (when an event object is missing)
- Second param: a `data` object where we provide minimum properties, for example `{ value: string }`
However, it was not explicit about whether **all** input components should expose a customized `onChange` handler with this signature, even if the changed value could be accessed as `event.target.value` without modification.
This PR proposes the clarification that all input components **should** expose a customized `onChange` with the agreed-upon signature.

RFC: Standardize onChange handlers for input components

---

change/@fluentui-react-avatar-c49124f1-8234-4517-8772-40dd06e2157e.json
packages/react-avatar/src/AvatarIcon.stories.tsx
packages/react-avatar/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
packages/react-avatar/src/components/Avatar/useAvatar.tsx
packages/react-avatar/src/components/Avatar/useAvatarStyles.ts

Split off from #21074 to update react-avatar in a different way. This sets `fontSize` on the icon slot using styles, instead of specifying a fontSize on the icon itself. This makes it so the icon is appropriately sized even if the user specifies a custom icon without a size.

Update Avatar to use resizable icons

---

apps/pr-deploy-site/just.config.ts
apps/pr-deploy-site/pr-deploy-site.js
change/@fluentui-react-components-ea4050e0-fb62-4709-a678-0baf10d7bcfa.json
change/@fluentui-react-input-c5b897ac-9f07-4c14-8dcf-16702a2e9e1a.json
packages/react-components/package.json
packages/react-components/src/unstable/index.ts
packages/react-input/package.json
packages/react-input/src/components/Input/Input.tsx
packages/react-input/src/stories/Input.stories.tsx

Publish the `@fluentui/react-input` package and add it to `@fluentui/react-components/unstable`.
Since Input is now available in the react-components storybook, I removed its separate pr-deploy-site entry.

Publish react-input and add to react-components under unstable

---

change/office-ui-fabric-react-5820edc7-b4f7-4378-bd2e-5b207c0da688.json
packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.test.tsx
packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx

- Adds a check so that the combobox cannot be opened if it is disabled (either focused)
- Adds a unit test for this case

Combobox(v7): adds check so it cannot be opened if disabled

---

change/@fluentui-react-badge-02ab58cb-4550-4fe4-a652-70fea147324e.json
change/@fluentui-react-card-44d69321-d166-4988-b3e9-9672c6f95f49.json
change/@fluentui-react-label-5af6dd84-ecda-4733-8732-7819f8368484.json
change/@fluentui-react-tooltip-db9f0c54-986d-407e-a0f0-c84cf44b74a5.json
packages/react-badge/src/components/CounterBadge/CounterBadge.types.ts
packages/react-card/etc/react-card.api.md
packages/react-card/src/components/Card/Card.types.ts
packages/react-components/src/unstable/index.ts
packages/react-label/Spec.md
packages/react-label/etc/react-label.api.md
packages/react-label/src/components/Label/Label.types.ts
packages/react-radio/etc/react-radio.api.md
packages/react-radio/src/components/Radio/Radio.types.ts
packages/react-radio/src/components/Radio/useRadio.ts
packages/react-tooltip/src/components/Tooltip/useTooltip.tsx

A few components still had outdated boilerplate from previous versions of the component template, such as `___DefaultedProps` types (or comments mentioning the type), `___ShorthandProps` types, or `@docCategory` tags. Remove those comments and types, as well as references to them in the specs where possible.
In types files where I was already making changes, if there was an empty `___Commons` type (which was where one of the outdated boilerplate comments was), I deleted that as well since it doesn't serve any purpose and can be added back later if needed without a breaking change. I can revert this part if desired.

Remove outdated or unused boilerplate comments and types

---

rfcs/convergence/make-styles-no-functions.md

This RFC targets to solve extensibility of theme of customers and simplify `makeStyles()` itself. This was already briefly discussed sometime ago, https://github.com/microsoft/fluentui/pull/19752#discussion_r709513133.
---
[RFC Preview](https://github.com/microsoft/fluentui/blob/rfc/mk-drop-fn/rfcs/convergence/make-styles-no-functions.md)

RFC: no functions in makeStyles()

---

rfcs/convergence/move-out-n-rename-makestyles.md

This RFC proposes to move out `makeStyles` CSS-in-JS to a separate repository and rename it.
[📃 RFC Preview](https://github.com/layershifter/office-ui-fabric-react/blob/rfc/move-out-makes/rfcs/convergence/move-out-n-rename-makestyles.md)

RFC: Rename and move out `makeStyles` to a separate repo

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/package.json
scripts/dangerjs/detectNonApprovedDependencies/approvedPackages.ts
yarn.lock

We uses react-transition-group `Transition` component `nodeRef` prop, which is released after 4.4.0.
Therefore this PR bumps react-transition-group to 4.4.1
(optional)

chore: bump react-transition-group from 4.3.0 to 4.4.1

---

change/@fluentui-react-conformance-7ec1375c-c01f-4dcd-b4a8-ef2c353b237d.json
packages/react-conformance/src/isConformant.ts
packages/react-conformance/src/types.ts
packages/react-conformance/src/utils/createTsProgram.ts

react-conformance is requesting tsconfig.json.
Before this PR, it always tries to look for tsconfig.json in `process.cwd()` and its ancestor directories. But this is not always the case: when running test from the root of a monorepo, `process.cwd()` is the project root, which does not always have tsconfig.json. 
This PR makes the path to tsconfig.json configurable through `tsconfigDir`. typescript `findConfigFile` will use tsconfigDir as starting point and work upwards to find the closest tsconfig.json.
This PR also changed the default starting point, from `process.cwd()` to component path.
(optional)

feat(react-conformance): add tsconfigDir config + change tsconfig default dir to componentPath

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/components/Chat/ChatMessage.tsx

`ChatMessage` should use value from chat context as default prop. This change is introduced by PR #20998.
However, when user input is explicitly undefined, for example `<ChatMessage accessibility={undefined} />, the `undefined` value will be used, which is incorrect.
This PR fixed it.
(optional)

fix(ChatMessage): use chat context as default value when user prop is explicitly undefined

---

scripts/beachball/index.ts

Enabling a beachball option I added awhile back: don't require change files for tests, stories, or specs. This doesn't catch all cases which don't require publishing, but it covers some of the most common ones to reduce unnecessary change file requirements.
Note that I intentionally didn't include other config files (such as tsconfig) here since changing those potentially ought to trigger publishing.

Ignore unpublished files in yarn change

---

change/@fluentui-web-components-30667c77-9cd4-4069-bc05-51c126377d24.json
packages/web-components/docs/api-report.md
packages/web-components/package.json
packages/web-components/src/component-definitions.js
packages/web-components/src/custom-elements.ts
packages/web-components/src/index.ts
packages/web-components/src/listbox/index.ts
packages/web-components/src/search/fixtures/search.html
packages/web-components/src/search/index.ts
packages/web-components/src/search/search.stories.ts
packages/web-components/src/search/search.styles.ts
packages/web-components/src/search/search.template.ts
packages/web-components/src/search/search.vscode.definition.json
yarn.lock

Adds `fluent-search` web component.
(optional)

feat: add `search` web component

---

change/@fluentui-react-components-1b3e39f8-2025-47cb-bf2e-c541853c97b8.json

This PR cleans up a change file for #21042 in the `@fluentui/react-components` package to indicate change as `type: none` since the change was affecting just stories and not published code.

react-components: Cleaning up change file to indicate change as type none since the change was affecting just stories and not published code

---

change/@fluentui-react-0b4f7a14-5ede-4e1d-9ed9-e83d9eaf95ea.json
packages/react-examples/src/react/__snapshots__/DetailsList.Grouped.Example.tsx.shot
packages/react/src/components/List/List.tsx

- removes `aria-label` attribute using the same logic as when `role` is removed.

GroupedList: removes aria-label attribute when rowgroup is empty.

---

change/@fluentui-react-tooltip-12cd10b5-3dc5-4754-8481-c51c14a5ed2f.json
packages/react-tooltip/src/components/Tooltip/private/constants.ts
packages/react-tooltip/src/components/Tooltip/useTooltip.tsx
packages/react-tooltip/src/components/Tooltip/useTooltipStyles.ts

PR feedback from @khmakoto - https://github.com/microsoft/fluentui/pull/21086#discussion_r779798499
> Not blocking for this PR: Is this a case for maybe exporting out of one file and importing into another while not exporting from the package itself so we don't have duplicate information?
Move the `arrowHeight` and `tooltipBorderRadius` constants into ./private/constants.ts. They aren't exported from the package, but are exported for use within the component code.

Tooltip: Move arrowHeight and tooltipBorderRadius into a common constants.ts file

---

apps/vr-tests/.storybook/main.js
package.json
scripts/package.json
yarn.lock

The goal is to make our env compatible with Node 16 to use native binaries on Apple M1 chips. Current version of `node-sass` is [not compatible with Node 16](https://github.com/sass/node-sass#node-version-support-policy) 😿 
- I also had to bump `sass-loader` as current version does not work with `node-sass@6`
- I also switched `vr-tests` to use Webpack 5 as `sass-loader@12` does not work with Webpack 4

chore: bump node-sass to v6

---

change/@fluentui-react-59dcc92e-109f-4a42-b52d-6a080b3c0cbc.json
packages/react/src/components/pickers/Suggestions/Suggestions.tsx
packages/react/src/components/pickers/Suggestions/__snapshots__/Suggestions.test.tsx.snap

- Moves `role=listbox`, `aria-label` and `suggestionsList` `id` permanently to the root (unlike before when it was only in the root when there are no suggestions available).
- Adds `role=option` to `searchForMoreText` button so it becomes a part of the listbox and is accessible to screen readers.

Pickers Suggestions: add searchForMoreText button to the suggestions listbox.

---

change/@fluentui-react-components-a3109946-9e50-442e-8917-9b82951226c7.json
packages/react-components/etc/react-components.api.md
packages/react-components/src/index.ts

Per agreement in discussion of #20964, as an intermediate step we want to stop exporting all Commons types from `@fluentui/react-components`. This reduces likelihood of breaking consumers with whatever final solution we choose, while keeping the Commons types in individual component packages' API report files.
The follow-up PR #21196 will introduce an eslint rule to prevent new re-exports of commons types from being added.

Stop exporting Commons types from react-components

---

change/@fluentui-react-input-80a0046e-4134-4acd-adfc-9e114bb26396.json
packages/react-input/src/components/Input/useInputStyles.ts
packages/react-input/src/stories/InputAppearance.stories.tsx
packages/react-input/src/stories/InputContentBeforeAfter.stories.tsx
packages/react-input/src/stories/InputDefault.stories.tsx
packages/react-input/src/stories/InputSize.stories.tsx

Fix some accessibility-related styling issues that came up while going through the checklist in #21174 with @smhigley. 
Also in the interest of demonstrating good patterns (not using placeholders, particularly as labels), remove placeholders from most of the stories.

Input: fix issues from a11y review

---

change/@fluentui-react-1675c06d-4fee-408f-8f9b-19a8b360d88e.json
packages/react/src/components/ComboBox/ComboBox.test.tsx
packages/react/src/components/ComboBox/ComboBox.tsx

- Adds a check so that the combobox cannot be opened if it is disabled (either focused)
- Adds a unit test for this case
Cherry pick of this PR #20839

Combobox(v8): adds check so it cannot be opened if disabled #17955

---

change/@fluentui-react-menu-1422f6f8-159f-4fbb-8ab3-58e24e923beb.json
change/@fluentui-react-popover-aaf223d9-a59d-4043-8673-01dcea0a4caa.json
change/@fluentui-react-tabster-262e9d2a-fb1e-4972-8236-654d9a3c2b85.json
packages/react-menu/e2e/support.js
packages/react-popover/e2e/support.js
packages/react-tabster/e2e/support.js
scripts/cypress.js
tools/generators/migrate-converged-pkg/index.spec.ts
tools/generators/migrate-converged-pkg/index.ts
tools/utils.ts

There's a [Cypress bug](https://github.com/cypress-io/cypress/issues/8599) where it improperly handles relative `supportFile` paths containing `..` segments on Windows non-WSL, causing an error like this (note the joining of two absolute paths):
```
Oops...we found an error preparing this test file:
..\..\scripts\cypress\support\index.js
The error was:
Error: EINVAL: invalid argument, mkdir 'C:\Users\elcraig\AppData\Roaming\Cypress\cy\production\projects\react-menu-63ba5bf5c951cc04cc81cc84c8c3f022\bundles\D:\git\fluentui\scripts\cypress\support'
```
I tried to debug the issue in Cypress but couldn't figure out which code was generating the bad path, so instead I implemented the workaround described in https://github.com/cypress-io/cypress/issues/8599#issuecomment-757977286: create …

Add workaround for Cypress issue on Windows (non-WSL)

---

change/@fluentui-web-components-0e8033b0-8a6d-486e-bb1f-c6d0054108b5.json
packages/web-components/src/tabs/tab-panel/tab-panel.styles.ts

I noticed the tab panel was using a smaller size, though it should be treated as normal content. I believe this was an error in the original styling.
(optional)

(web-components) Update tab panel to base type size

---

change/@fluentui-react-button-5cc8ef32-ce96-4881-bd8e-e9dbc462c7c6.json
packages/react-button/src/components/Button/stories/ButtonDisabled.stories.tsx
packages/react-button/src/components/Button/stories/ButtonIcon.stories.tsx
packages/react-button/src/components/Button/stories/ButtonSize.stories.tsx
packages/react-button/src/components/CompoundButton/stories/CompoundButtonDisabled.stories.tsx
packages/react-button/src/components/CompoundButton/stories/CompoundButtonIcon.stories.tsx
packages/react-button/src/components/MenuButton/stories/MenuButtonIcon.stories.tsx
packages/react-button/src/components/MenuButton/stories/MenuButtonSizeLarge.stories.tsx
packages/react-button/src/components/MenuButton/stories/MenuButtonSizeMedium.stories.tsx
packages/react-button/src/components/MenuButton/stories/MenuButtonSizeSmall.stories.tsx
packages/react-button/src/components/MenuButton/useMenuButton.tsx
packages/react-button/src/components/SplitButton/stories/SplitButtonIcon.stories.tsx
packages/react-button/src/components/SplitButton/stories/SplitButtonSizeLarge.stories.tsx
packages/react-button/src/components/SplitButton/stories/SplitButtonSizeMedium.stories.tsx
packages/react-button/src/components/SplitButton/stories/SplitButtonSizeSmall.stories.tsx
packages/react-button/src/components/ToggleButton/stories/ToggleButtonDisabled.stories.tsx
packages/react-button/src/components/ToggleButton/stories/ToggleButtonIcon.stories.tsx

react-button has hard-coded icon sizes
Remove the fixed-sized icons from react-button's stories. The Button's styles already apply a default size for the icons.
#21220

react-button: remove fixed-size icons

---

change/@fluentui-react-menu-9f983fe2-dde4-4d1d-a059-cb0132875ecf.json
packages/react-menu/src/components/MenuItem/useMenuItem.tsx
packages/react-menu/src/components/MenuItem/useMenuItemStyles.ts
packages/react-menu/src/stories/MenuAligningWithIcons.stories.tsx
packages/react-menu/src/stories/MenuAligningWithSelectableItems.stories.tsx
packages/react-menu/src/stories/MenuCheckboxItems.stories.tsx
packages/react-menu/src/stories/MenuControlledCheckboxItems.stories.tsx
packages/react-menu/src/stories/MenuControlledRadioItems.stories.tsx
packages/react-menu/src/stories/MenuGrouppingItems.stories.tsx
packages/react-menu/src/stories/MenuMemoizedMenuItems.stories.tsx
packages/react-menu/src/stories/MenuMenuItemsWithIcons.stories.tsx
packages/react-menu/src/stories/MenuRadioItems.stories.tsx
packages/react-menu/src/stories/MenuSelectionGroup.stories.tsx
packages/react-menu/src/stories/MenuVisualDividerOnly.stories.tsx

Icons provided to the MenuItem component won't be sized properly without explicitly specifying their size.
Add fontSize styling to MenuItem's `icon` and `submenuIndicator` slots. This provides a default size for icons provided by the user.
#21220

react-menu: remove fixed-size icons

---

change/@fluentui-react-components-c4676f9d-868b-4612-8296-8a30d56a2a12.json
packages/react-components/etc/react-components.api.md
packages/react-components/src/index.ts

This PR removes an export of `useTheme()` hook from `@fluentui/react-components`. The hook is still used internally, but should not be used in applications anymore.
```tsx
import { useTheme } from `@fluentui/react-components`;
const theme = useTheme();
//                          👇 an exact value, for example "#242424"
return <div style={{ color: theme.colorNeutralForeground1 }} />;
}
```
```tsx
import { tokens } from `@fluentui/react-components`;
//                          👇 a CSS variable, for example "var(--colorNeutralForeground1)"
return <div style={{ color: tokens.colorNeutralForeground1 }} />;
}
```
- `useTheme()` returned an exact value, for example `#242424`
- `tokens` is a set of CSS variables, for example `var(--colorNeutralForeground1)`
Fixes …

breaking: stop exporting useTheme() hook

---

apps/public-docsite/package.json
apps/public-docsite/src/components/IconGrid/IconGrid.module.scss
apps/public-docsite/src/components/IconGrid/IconGrid.tsx
apps/public-docsite/src/pages/Styles/FabricIconsPage/FabricIconsPage.tsx
apps/public-docsite/src/pages/Styles/FabricIconsPage/docs/web/FabricIconsOverview.md
apps/public-docsite/src/pages/Styles/FabricIconsPage/docs/web/FabricIconsSvgUsage.md
apps/public-docsite/src/pages/Styles/FabricIconsPage/docs/web/FabricIconsUsage.md
apps/public-docsite/tsconfig.json
apps/public-docsite/webpack.serve.config.js
change/@fluentui-react-icons-mdl2-8882c28b-5494-4624-b8e4-7c154b6a68cb.json
change/@fluentui-react-icons-mdl2-branded-9032da2d-4806-4448-99f8-1fd1b315a19f.json
package.json
packages/fluentui/perf-test/package.json
packages/react-icons-mdl2-branded/README.md
packages/react-icons-mdl2/README.md
packages/react-icons-mdl2/package.json
scripts/package.json
yarn.lock

This PR is a modified version of some work @tomi-msft and I started in #20862: 
- Clarify some text on the icons doc page for v8
- Add SVG icons (the MDL2 sets in this case) to the icon grid/search at the bottom of the page
Background: today, the text of the v8 doc site page about icons is kind of confusing and outdated in places, and it would have gotten a lot more complex if we added the new `@fluentui/react-icons` SVG icon set to the same page (as we started to do in #20862). Even though we ultimately we decided to put the react-icons docs in the v9 storybook instead (NOT included in this PR), some of the text clarification I'd started working on for the other PR should still be helpful.
I also reused some of the code we started working on in #20862 to display SVG icon sets in the icon …

Overhaul v8 icon doc text and add search for SVG icons

---

change/@fluentui-react-fcd957e6-b238-45ac-903b-58074ead0e6a.json
packages/react/src/components/SearchBox/SearchBox.base.tsx

There were two regressions with SearchBox's change event handling from v7 to v8:
- `onChange` is called twice (#17587)
- When the clear button is pressed, the new value of `''` is not passed to `onChange` (#19675)
The duplicate `onChange` issue is because for historical reasons, SearchBox handles both `onInput` and `onChange`. This is no longer necessary, but we can't modify it outside a major version due to risk of breaking partners (would be most likely to break only tests, but that's still very inconvenient for people). In v7 there was (essentially) debouncing code to work around this and only call `props.onChange` once, but this was removed in the function component conversion for v8.
The issue with not passing the new `''` value through to `onChange` on clear button press was because …

SearchBox: fix event handling regressions in v8

---

change/@fluentui-eslint-plugin-e581f6ba-1682-40b1-9526-48c87c70a3f0.json
packages/eslint-plugin/README.md
packages/eslint-plugin/src/rules/ban-imports.js
packages/react-components/.eslintrc.json
scripts/beachball/index.ts

To support removing exports of Commons types from `@fluentui/react-components` (#21194 / #21195), update our custom `ban-imports` ESLint rule to also run on re-exports, and to support regular expressions for banned names. 
Use the updated rule to ban references to Commons types in `@fluentui/react-components` index files.
**(NOTE: until #21195 merges, this will cause the PR build to fail)**
Also don't require change files for modifications to `.eslintrc.*` (such as the one in react-components in this PR) since this will never directly affect a published package.

Add eslint rule capability to ban exports of Commons types from react-components

---

change/@fluentui-react-card-44f41c2d-fa7d-4d71-af4c-4d1266a58268.json
packages/react-card/README.md
packages/react-card/src/Card.stories.tsx
packages/react-card/src/CardDescription.md

Card component did not have any notices regarding it still being an Alpha, as functionality is still missing. This created possible confusion given that due to lockstep versioning it's marked as a Beta component and soon to be RC.
Suggestions for the text/phrasing are more than welcome. 🙏
README and Storybook docs were updated to reflect the current status.

docs(react-card): Add Alpha notice to docs

---

change/@fluentui-react-components-9d99eb03-ece2-4410-be0a-ef3e876c43b3.json
packages/react-components/.storybook/main.js
packages/react-components/package.json
packages/react-storybook-addon/README.md
packages/react-storybook-addon/package.json
packages/react-storybook-addon/preset.js

- Theme switching doesn't work (react-storybook-addon) in `react-components` suite
- `babel-make-styles` doesn't work in `react-components` suite
- theme switching works
- babel-make-styles is enabled
**NOTE:**
- initial cold run will be a bit slower as all dependencies of `babel-make-styles` and `react-storybook-addon` will need to be build. every consecutive run will be pulled from cache so the time implications will be negligible
- Fixes #21227 
- Fixes #20886
- fixes partially #20896 - if our addon needs to consume other packages within monorepo, it looks like we won't be able to provide build-less experience

chore: re-enable react-storybook-addon and babel-make-styles for react-components

---

scripts/storybook/runner.js
tools/generators/migrate-converged-pkg/index.spec.ts
tools/generators/migrate-converged-pkg/index.ts

- babel-make-styles doesn't work in storybooks for vNext
- react-storybook-addon is not enabled for vNext
- storybook is invoked directly via `start-storybook` binary
this PR:
-  implements simple storybook runner that replace all `start-storybooks` ( until we overhaul how we build ), that will pre-build `babel-make-styles` and `react-storybook-addon` when running `storybook` command **only when it makes sense**.
- update migration-converged-pkg generator
> **NOTE:** 
> - This will add  cold/no-cache performance penalty as user will need to wait to build those. Any consecutive build will be fetched from cache thus the perf will be the same as with having "build-less" experience
**Demo:**
https://user-images.githubusercontent.com/1223799/149202754-4f84be64-8769-464c-b7f7-2f6b442152f2.mov
- …

feat: add storybook runner wrapper for vNext packages consumption

---

apps/vr-tests/src/stories/AvatarConverged.stories.tsx
apps/vr-tests/src/stories/Badge.stories.tsx
apps/vr-tests/src/stories/MenuConverged.stories.tsx

Some Screener tests are using fixed-size icons.
Replace the fixed sized icons with resizable versions. The components have already been updated to apply the correct size to their icon slots.
This is part of the work for #21220

Remove fixed-size icons from vr-tests

---

change/@fluentui-react-3b2991ef-caf7-43f9-aacf-62b7cf3451b1.json
packages/react-examples/src/react/ChoiceGroup/ChoiceGroup.Custom.Example.tsx
packages/react-examples/src/react/__snapshots__/ChoiceGroup.Custom.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/CommandBar.Basic.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/CommandBar.CommandBarButtonAs.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/FocusTrapZone.Box.Click.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/FocusTrapZone.Box.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/FocusTrapZone.Box.FocusOnCustomElement.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/FocusTrapZone.FocusZone.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/FocusTrapZone.Nested.Example.tsx.shot
packages/react/src/components/ChoiceGroup/ChoiceGroup.base.tsx
packages/react/src/components/Coachmark/__snapshots__/Coachmark.test.tsx.snap
packages/react/src/components/Dialog/__snapshots__/Dialog.deprecated.test.tsx.snap
packages/react/src/components/FocusTrapZone/FocusTrapZone.tsx
packages/react/src/components/HoverCard/__snapshots__/HoverCard.test.tsx.snap
packages/react/src/components/Modal/__snapshots__/Modal.test.tsx.snap
packages/react/src/components/Panel/__snapshots__/Panel.test.tsx.snap
packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.deprecated.test.tsx.snap
packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.test.tsx.snap

PR flow tips:
When `ChoiceGroup` is the child of an element that has focus clicking on an option will incorrectly draw a focus rectangle around the previously selected option. This is observable on the docs page for `ChoiceGroup` but not in an exported Codepen as described in #21193.
#20859 added code to check if an element is a sibling of `ChoiceGroup` but it only tested that the element under consideration was not a descendant of `ChoiceGroup`. This change updates this code to also check that the element being tested is not an ancestor of `ChoiceGroup`.
1. Pull this branch locally
2. Run `yarn start`
3. Select "@fluentui/public-docsite"
4. Open the docsite in your browser (this should happen automatically)
1. Under the "React" section click "Controls"
2. On the next page click through …

fix an issue with ChoiceGroup and focus rectangles

---

change/@fluentui-react-provider-799f4a36-cc2b-48d7-ba65-9b54b83ac24a.json
change/@fluentui-react-shared-contexts-2267ecce-105d-4bde-b47f-335b56635347.json
packages/react-provider/etc/react-provider.api.md
packages/react-provider/src/components/FluentProvider/FluentProvider.test.tsx
packages/react-provider/src/components/FluentProvider/FluentProvider.types.ts
packages/react-provider/src/components/FluentProvider/useFluentProvider.test.tsx
packages/react-provider/src/components/FluentProvider/useFluentProvider.ts
packages/react-provider/src/components/FluentProvider/useFluentProviderContextValues.test.ts
packages/react-provider/src/components/FluentProvider/useThemeStyleTag.ts
packages/react-shared-contexts/etc/react-shared-contexts.api.md
packages/react-shared-contexts/src/ThemeContext/ThemeContext.ts
packages/react-shared-contexts/src/ThemeContext/ThemeContext.types.ts
packages/react-shared-contexts/src/ThemeContext/index.ts

- `useTheme` returns always `Theme` which is not correct as runtime can return `undefined` /partial theme/ parent theme. This affects a chain of API's that are using it.
- `ThemeContext` has set `null` as default context value, whereas other contexts use `undefined`
- `ThemeContextValue` doesn't provide any value as it just extends `Theme`
- `useTheme` now returns `undefined` | `Partial<Theme>` | `Theme`
- if there has been no `theme` set in parent `FluentProvider` or child `FluentProvider` we will emit warning to user in development/test environment
- `ThemeContextValue` has been replaced with `Theme` 
Follows #21278

feat: redo FluentProvider theme api

---

scripts/projects-test/performBrowserTest.ts

- `performBrowserTest` currently uses `portfinder` to find an unused port to use; however, it utilizes the same port when being ran by multiple packages at the same time which seems to cause a race condition, causing intermittent timeout errors. A similar issue regarding the same ports being used has been filed to `portfinder` and this seems to be a known limitation of the module (see issue [here](https://github.com/http-party/node-portfinder/issues/118))
- When tests for two different packages are ran simultaneously, same port (8000) is used:
- `performBrowserTest` now uses `express` instead to provide an open port. Passing `0` to express' `app.listen` method lets the OS assign an arbitrary unused port which can be accessed via `server.address().port`.
- When tests for two different …

Fix: performBrowserTest now utilizes unused port provided by express.

---

apps/public-docsite/src/pages/HomePage/HomePage.base.tsx

fixes [13312](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/13312)
Adds an `aria-label` to the `_renderLink` function, and provides section-specific SR-only labels to the repeated "controls" and "get started" links.

fix(public-docsite): non-repeated link names on Fluent home page

---

change/@fluentui-web-components-e23b11e5-b929-428a-a271-c8f6931c8133.json
packages/web-components/src/combobox/combobox.styles.ts

There are unused declared variables in `combobox.styles.ts` that are causing issues when trying to merge branches:
Removes unused variables.
Fixes #

[web-components]: Remove unused declared variables in combobox

---

change/@fluentui-react-divider-8007dcbe-33ef-4d80-9b15-0cfca85bdc66.json
packages/react-divider/src/components/Divider/Divider.test.tsx
packages/react-divider/src/components/Divider/__snapshots__/Divider.test.tsx.snap
packages/react-divider/src/components/Divider/useDivider.ts

aria-orientation attribute is missing, making screen readers read a vertical divider as horizontal.
aria-orientation attribute is set for horizontal and vertical dividers, screen reader reads correctly.
Fixes #21291

Added aria-orientation to divider

---

change/@fluentui-react-accordion-92351cf0-bf2f-428a-8481-a180fbbd6468.json
packages/react-accordion/etc/react-accordion.api.md
packages/react-accordion/src/components/AccordionHeader/AccordionHeader.types.ts
packages/react-accordion/src/components/AccordionHeader/__snapshots__/AccordionHeader.test.tsx.snap
packages/react-accordion/src/components/AccordionHeader/renderAccordionHeader.tsx
packages/react-accordion/src/components/AccordionHeader/useAccordionHeader.tsx
packages/react-accordion/src/components/AccordionHeader/useAccordionHeaderStyles.ts

AccordionHeader currently has `children` property as a slot which is not encouraged by our API due to `children` being a common property shared between most components, therefore it's type should be well defined
Removes declaration of `children` as a slot and ensures it follows proper behaviors and no styles have been broken in the process
Fixes #21119

fix(Accordion): removes children as slot from AccordionHeader

---

change/@fluentui-cra-template-69213d33-73e4-4b2f-b41a-09cc17439a07.json
packages/cra-template/scripts/test.ts
packages/fluentui/projects-test/src/createReactApp.ts

The latest version of `mini-css-extractor-plugin` released today is causing the `cra-template` and `projects-test` packages builds to fail (see screenshot). An issue has already been filed for this (see [here](https://github.com/facebook/create-react-app/issues/11930)).
Uses workaround and adds `mini-css-extractor-plugin` version `2.4.5` to the resolutions section of the testApp's `package.json`.
Fixes #

temp fix: resolve mini-css-extractor-plugin to an older version for cra-template & projects-test

---

change/@fluentui-make-styles-6ed780fb-da77-4bcf-84b2-6337e72da9f5.json
packages/make-styles/src/mergeClasses.ts

`mergeClasses()` parses each passed argument to understand if passed classes are Atomic or not:
https://github.com/microsoft/fluentui/blob/5e128714ba386902c0650ce61dfdeedee71ec0c8/packages/make-styles/src/mergeClasses.ts#L47-L60
If classes are Atomic it will build cache key (1️⃣ `sequenceMatch`) and will extract mapping from properties to classes (2️⃣ `sequenceMappings`).
- (1) `sequenceMatch` works poorly with strings
- (2) `sequenceMappings` includes accessing objects & arrays and
Surprisingly it's not free to access objects & arrays in JavaScript (_at least in v8_) and strings are much cheaper (_it's actually the reason why we use them for key computation_). Taking this into account this PR splits works into two separate loops instead of a single - this makes cache key computation much …

perf(makeStyles): rework mergeClasses() to compute cache key faster

---

change/@fluentui-cra-template-cbd4d3f6-f50e-4c14-9ff8-387e2f41bb71.json
packages/cra-template/scripts/test.ts
packages/fluentui/projects-test/src/createReactApp.ts

- An older version of the `mini-css-extractor-plugin` was added to the the resolutions section of the test app's `package.json` for both `cra-template` and `projects-test` packages. The root issue has since been fixed in the latest version (see [comment](https://github.com/facebook/create-react-app/issues/11930#issuecomment-1014519316)) of `mini-css-extrator-plugin` so this temp fix is no longer needed. 
Removes temporary fix added in #21295
Fixes #

chore: remove temp fix for mini-css-extractor-plugin error

---

change/@fluentui-react-input-4f50d0b5-cd5f-411f-8f45-66cf55fae951.json
packages/react-input/package.json

The package.json of react-input has a configuration with just-script that are no longer needed for v9 components. 
This issue caused the CI to fail in this PR: https://github.com/microsoft/fluentui/pull/21123 
Removed the `"build-storybook": "just-scripts storybook:build"` from `react-input` package.

react-input: Removed config with just-scripts

---

change/@fluentui-react-tooltip-b682fed9-f100-424e-ad72-301cc3084a23.json
packages/react-tooltip/etc/react-tooltip.api.md
packages/react-tooltip/src/components/Tooltip/Tooltip.types.ts
packages/react-tooltip/src/components/Tooltip/useTooltip.tsx

* Tooltip's `inverted` prop had been removed but was added back by a merge conflict.
* Tooltip's `appearance` prop is an enum but doesn't have any value for `"normal"` besides `undefined`.
* Remove Tooltip's inverted prop in favor of the appearance prop
* Add a `normal` value for the appearance prop, and update its documentation

Remove Tooltip's inverted prop in favor of the appearance prop

---

apps/public-docsite/src/pages/Styles/ThemeSlotsPage/docs/web/ThemeSlotsOverview.md

String misspelling in: https://developer.microsoft.com/en-us/fluentui#/styles/web/colors/theme-slots
`When selecting colors, refer to the color accessibility guidance (PDF) to ensure that your text can be ready by everyone. `
Fixed String to read:
`When selecting colors, refer to the [color accessibility guidance (PDF) to ensure your text can be read by everyone. `
Fixes #19031

[FIX] String Misspelling in Theme Slots

---

.devops/templates/variables.yml
yarn.lock

This PR adds `BROWSERSLIST_IGNORE_OLD_DATA` to `.devops/templates/variables.yml`.
This prevents "Browserslist: caniuse-lite is outdated" that time to time causes CI failures once the database becomes outdated and blocks CI gates completely.
https://github.com/browserslist/browserslist/blob/3cba97f1eacb468b92b33acc6819624e5edd42b0/node.js#L375

chore: add BROWSERSLIST_IGNORE_OLD_DATA variable

---

apps/perf-test/package.json
apps/perf-test/src/scenarios/MakeStyles.tsx
change/@fluentui-babel-make-styles-ee9b3856-f3d4-4861-b40a-5d8804aed9a2.json
change/@fluentui-jest-serializer-make-styles-922bd6c1-bf07-40bf-9ee2-78f5c9e44260.json
change/@fluentui-react-make-styles-cdadc702-0cf1-4498-83d0-a686f679f21f.json
packages/babel-make-styles/__fixtures__/function-mixin/mixins.ts
packages/babel-make-styles/__fixtures__/object-mixins/mixins.ts
packages/babel-make-styles/__fixtures__/shared-mixins/mixins.ts
packages/babel-make-styles/package.json
packages/babel-make-styles/src/plugin.ts
packages/fluentui/docs/src/examples/components/Popup/Visual/PopperExamplePositioning.tsx
packages/fluentui/react-northstar-emotion-renderer/test/__snapshots__/emotionRenderer-test.ts.snap
packages/fluentui/react-northstar/src/components/ItemLayout/ItemLayout.tsx
packages/jest-serializer-make-styles/package.json
packages/jest-serializer-make-styles/src/index.ts
packages/react-conformance-make-styles/src/matchers/toContainClassNameLastInCalls.test.ts
packages/react-conformance-make-styles/src/matchers/toHaveMergeClassesCalledTimesWithClassName.test.ts
packages/react-make-styles/etc/react-make-styles.api.md
packages/react-make-styles/package.json
packages/react-make-styles/src/RendererContext.tsx
packages/react-make-styles/src/__styles.ts
packages/react-make-styles/src/createDOMRenderer.test.tsx
packages/react-make-styles/src/index.ts
packages/react-make-styles/src/makeStaticStyles.ts
packages/react-make-styles/src/makeStyles.ts
packages/react-make-styles/src/renderToStyleElements-node.test.tsx
packages/react-make-styles/src/renderToStyleElements.ts
yarn.lock

_This PR is extracted from #21318._
As we agreed to move out and rename `makeStyles` (#20882), it's time to do this ⏳ The migration will be done package by package, this PR replaces `@fluentui/make-styles` with `@griffel/core`, the next one (#21318) will delete `@fluentui/make-styles` at all.
The single difference in `@griffel/core` are renamed types: `MakeStyles*` => `Griffel*`.
This happened because of bump `rtl-css-js` & `stylis`: new versions simply contain more code. Affects only runtime version. 
- Typings changes are related to `csstype` bump
- Changes in snapshot are related to `stylis` bump (https://github.com/thysultan/stylis.js/pull/258)

chore: replace @fluentui/make-styles with @griffel/core

---

packages/fluentui/react-northstar/src/themes/teams/components/Menu/menuItemWrapperStyles.ts

`pointing` menu when having active styles is missing the pointing indicator:
Adding the pointing indicator when required:

fix: add missing pointing indicator for menu vertical active

---

rfcs/react-components/components/tooltip-api-alignment.md

This RFC proposes changes to API of `Tooltip` component based on findings in #21225:
- turn `content` to a real slot
- do not accept DOM props
```tsx
return (
<>
{/*  Before */}
<Tooltip content="Foo" />
<Tooltip content="Foo" className="bar" />
{/* After */}
<Tooltip content="Foo" />
<Tooltip content={{ children: 'Foo', className: 'bar' }} />
{/*      👆 if "className" will passed to "Tooltip" we will get a TS error */}
</>
);
}
```
-----
[📃 **RFC Preview**](https://github.com/layershifter/office-ui-fabric-react/blob/rfc/tooltip-api/rfcs/react-components/components/tooltip-api-alignment.md)

RFC: Align API of Tooltip component to allow composition

---

package.json
yarn.lock

Bumps tslib which unblocks tabster upgrade in #21319
tabster uses tslib ^2.3.1 which will cause duplicate tslib versions to be used in v8

chore: Bump tslib to 2.3.1

---

change/@fluentui-react-menu-154a57c9-4439-40a0-8587-74adcfe20434.json
packages/react-menu/src/components/MenuTrigger/MenuTrigger.test.tsx
packages/react-menu/src/components/MenuTrigger/__snapshots__/MenuTrigger.test.tsx.snap
packages/react-menu/src/components/MenuTrigger/useMenuTrigger.ts

Adds a check to `isTargetDisabled` to not only check the presence of
`aria-disabled` but its value
`SplitButton` is broken since `aria-disabled` will always be present on the trigger with `true` and `false` values. Since existing `MenuTrigger` only checks the presence of the attribute, the menu will never open.
`SplitButton` will open the menu correctly
Fixes #21350

fix: MenuTrigger should work correctly when `aria-disabled="true"`

---

.gitignore
tools/STYLE-GUIDE.md
tools/generators/workspace-generator/files/README.md__tmpl__
tools/generators/workspace-generator/files/index.ts__tmpl__
tools/generators/workspace-generator/files/lib/utils.spec.ts__tmpl__
tools/generators/workspace-generator/files/lib/utils.ts__tmpl__
tools/generators/workspace-generator/index.spec.ts
tools/generators/workspace-generator/index.ts
tools/jest.config.js
tools/utils.ts

Based on initiative to split our existing `migrate-converged-pkg` migration generator started in https://github.com/microsoft/fluentui/pull/20962, this PR:
- adds simple style guide how to structure our nx generators based on common OSS community patterns
- updates `workspace-generator`  generator to mirror that styleguide

docs(tools): add nx style-guide

---

change/@fluentui-react-positioning-8bf7e435-add2-4059-8c21-b1f66706a1d9.json
packages/react-positioning/src/createArrowStyles.ts

The high contrast arrow border for tooltip is wrong in RTL:
Don't flip the border's side for RTL, since RTL is already handled by popper.

Fix tooltip arrow's high contrast border in RTL

---

packages/react-slider/src/components/Slider/useSliderStyles.ts

Slider leverages background colors to show progress. High contrast by default removes those backgrounds. 
Fixes #21342 
Fixes #21341
Before (Default and disabled)
After:
Default
Disabled

Slider: Update high contrast styles for better a11y

---

change/@fluentui-react-ed573539-35ce-4c02-8b39-24fb92cb0716.json
packages/react/etc/react.api.md
packages/react/src/components/Breadcrumb/Breadcrumb.base.tsx
packages/react/src/components/Breadcrumb/Breadcrumb.types.ts

The `Breadcrumb` component defines an `onRenderItem` prop which is used as a render override for every crumb. It takes responsibility for rendering the whole link given the item, and allows basic changing of props or wrapping the output.
There is no way to target a specific crumb, other than by matching `key`, or to render custom content inside a crumb without replacing the whole render logic.
Added `onRender` and `onRenderContent` fields to `IBreadcrumbItem`, which are honored by the crumb render logic, so that individual crumbs can have custom render logic, either for the whole crumb or just the text content.
Also, added an `onRenderItemContent` field to `IBreadcrumbProps` for wholistic replacement, for consistency.
Fixes #

Allow override of Breadcrumb item content and per-item overrides

---

change/@fluentui-react-249e5fdc-e376-4786-8ac6-ef8519937ca0.json
packages/react/src/components/ComboBox/ComboBox.tsx
packages/react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap

- `Combobox` automatically applies a `title` attribute to each option item which causes an NVDA issue where the option item’s name is announced twice. 
- `Combobox` will only apply the `title` attribute to the option item only if the option item explicitly passes a `title` prop.
Fixes [10748](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/10748)

Combobox: remove default title attribute applied to options.

---

change/@fluentui-react-98c7b050-b677-41f4-8303-36efc8bbfee7.json
packages/react/src/components/CalendarDayGrid/CalendarGridDayCell.tsx
packages/react/src/components/WeeklyDayPicker/__snapshots__/WeeklyDayPicker.test.tsx.snap

I unintentionally un-did the `CalendarDayGridCell` `aria-readonly` fix from this PR: #20324 in a simultaneous calendar fix PR. This re-fixes the original fix.

fix(Calendar): re-remove aria-readonly on grid cells

---

change/@fluentui-react-divider-02ac1b84-8ea4-482b-b277-223375b8e172.json
packages/react-divider/src/components/Divider/useDividerStyles.ts

When the divider has a very long string as the content, it will take up all the available room before it wraps.
This causes the line to be pushed to zero width and hides the line.
The line segments on either side have a minimum width of 32px (based on recommendation from designer)
The content text alignment is set to centered (otherwise the line min width cause a left-aligned text which looks incorrect)
Related to #21105

divider: minimum line length

---

change/@fluentui-react-theme-1c0d1c53-1dfc-49b9-aa9d-b0786f2b51f3.json
packages/react-theme/etc/react-theme.api.md
packages/react-theme/src/alias/dark.ts
packages/react-theme/src/alias/highContrast.ts
packages/react-theme/src/alias/light.ts
packages/react-theme/src/alias/teamsDark.ts
packages/react-theme/src/tokens.ts
packages/react-theme/src/types.ts

1. add `colorNeutralForeground1Static` token
2. update `colorNeutralBackgroundInverted` token values
3. update `neutralStencil1` and `neutralStencil2` token values
_Note: There is a difference between spec (#e5e5e5) and impl (#e6e6e6) for Grey.90, which is known._

feat(react-theme): Add colorNeutralForeground1Static token

---

change/@fluentui-react-popover-3a0c4933-511e-46f3-bf8f-5fcdda876462.json
packages/react-popover/src/components/PopoverSurface/PopoverSurface.test.tsx
packages/react-popover/src/components/PopoverSurface/usePopoverSurface.ts

`aria-modal` is not set on the popover at all
`aria-modal="true"` is set on the popover when `trapFocus` is `true`
Addressed by #21107

fix: Set `aria-modal` on Popover if focus trap is enabled

---

.storybook/custom-loader.js
change/@fluentui-react-provider-49fd1cbe-761c-4dc3-8c7f-2a87766c6e05.json
package.json
packages/react-provider/.babelrc.json
packages/react-provider/etc/react-provider.api.md
packages/react-provider/jest.config.js
packages/react-provider/package.json
packages/react-provider/src/common/isConformant.ts
packages/react-provider/src/components/FluentProvider/FluentProvider.test.tsx
packages/react-provider/src/components/FluentProvider/FluentProvider.types.ts
packages/react-provider/src/components/FluentProvider/renderFluentProvider.tsx
packages/react-provider/src/components/FluentProvider/useFluentProviderContextValues.ts
packages/react-provider/src/components/FluentProvider/useFluentProviderStyles.ts
packages/react-provider/src/stories/FluentProviderDefault.stories.tsx
packages/react-provider/src/stories/FluentProviderDir.stories.tsx
packages/react-provider/src/stories/FluentProviderFrame.stories.tsx
packages/react-provider/src/stories/FluentProviderNested.stories.tsx
yarn.lock

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-provider` package.
- `@fluentui/react-make-styles` => `@griffel/core`
- New `TextDirectionProvider` was added to `FluentProvider`.
- Our existing hack storybook with "custom loader" was updated to handle `@griffel/babel-preset`
- **(2)** for `react-provider` it's expected as new context provider was added and additional logic, too
- **(1)** this will decrease after full migration as currently we have duplicate `__styles()` function in …

chore: migrate react-provider to use Griffel

---

change/@fluentui-react-provider-9a410062-0b56-435a-8468-9195cc7a448a.json
packages/react-provider/package.json
scripts/create-component/plop-templates/src/common/isConformant.ts.hbs
scripts/create-component/plop-templates/src/components/{{componentName}}/use{{componentName}}Styles.ts.hbs
scripts/create-package/plop-templates-react/.babelrc.json
scripts/create-package/plop-templates-react/jest.config.js
scripts/create-package/plop-templates-react/package.json.hbs
scripts/create-package/plopfile.ts
tools/generators/migrate-converged-pkg/index.spec.ts
tools/generators/migrate-converged-pkg/index.ts

This PR updates `create-package` script & templates and Nx generator use Griffel packages.
Changes that are applied to generator are matching changes in #21360.
Note: This PR does not implement migration from `make-styles` to Griffel.

chore: update generator to use Griffel

---

change/@fluentui-date-time-utilities-f5190288-ce6e-4607-8bad-7f8cd56f08af.json
change/@fluentui-react-b5938547-532d-41fa-b34e-d8d702171623.json
packages/date-time-utilities/etc/date-time-utilities.api.md
packages/date-time-utilities/src/dateValues/timeConstants.ts
packages/date-time-utilities/src/timeMath/timeMath.test.ts
packages/date-time-utilities/src/timeMath/timeMath.ts
packages/react-examples/src/react/TimePicker/TimePicker.Example.tsx
packages/react/etc/react.api.md
packages/react/src/components/TimePicker/TimePicker.tsx
packages/react/src/components/TimePicker/TimePicker.types.ts

Greetings, reviewer!
This pull request adds a default value prop and updates the onChange prop to the TimePicker control.
Users of this control can now supply the "starting default time" as a Date object. This new prop is `defaultValue?: Date`. If defaultValue is not supplied, the control will select the "starting default time" as `new Date()`.
Additionally, users can also track changes to the TimePicker control via the updated `onChange` callback function. This way, users can avoid the hassle of parsing their selected time and can instead receive an updated Date object on each selection. This updated prop is `onChange?: (event: React.FormEvent<IComboBox>, time: Date) => void`. It is called within the `onInputChange` function.
There PR also adds a new function within the TimePicker …

TimePicker Default Value and Update onChange

---

change/@fluentui-react-accordion-87c44b26-f9b8-4819-b689-92307876b78b.json
packages/react-accordion/.babelrc.json
packages/react-accordion/jest.config.js
packages/react-accordion/package.json
packages/react-accordion/src/common/isConformant.ts
packages/react-accordion/src/components/Accordion/useAccordionStyles.ts
packages/react-accordion/src/components/AccordionHeader/useAccordionHeaderStyles.ts
packages/react-accordion/src/components/AccordionItem/useAccordionItemStyles.ts
packages/react-accordion/src/components/AccordionPanel/useAccordionPanelStyles.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-accordion` package.
---

chore: migrate react-accordion to use Griffel

---

change/@fluentui-react-popover-a0804144-1806-4af5-bb61-8aaae1bb96f3.json
packages/react-popover/.babelrc.json
packages/react-popover/jest.config.js
packages/react-popover/package.json
packages/react-popover/src/common/isConformant.ts
packages/react-popover/src/components/PopoverSurface/usePopoverSurfaceStyles.ts
packages/react-popover/src/stories/PopoverAnchorToCustomTarget.stories.tsx
packages/react-popover/src/stories/PopoverControllingOpenAndClose.stories.tsx
packages/react-popover/src/stories/PopoverCustomTrigger.stories.tsx
packages/react-popover/src/stories/PopoverDefault.stories.tsx
packages/react-popover/src/stories/PopoverInternalUpdateContent.stories.tsx
packages/react-popover/src/stories/PopoverNestedPopovers.stories.tsx
packages/react-popover/src/stories/PopoverTrappingFocus.stories.tsx

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-popover` package.
---

chore: migrate react-popover to use Griffel

---

change/@fluentui-react-tabster-7b7fc54e-8f57-4f49-92c5-1e26e6e9ad90.json
packages/react-tabster/.babelrc.json
packages/react-tabster/etc/react-tabster.api.md
packages/react-tabster/jest.config.js
packages/react-tabster/package.json
packages/react-tabster/src/hooks/useFocusIndicatorStyle.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-tabster` package.
---

chore: migrate react-tabster to use Griffel

---

change/@fluentui-react-positioning-9a291fd5-6056-4028-900c-ae4734eb3e77.json
packages/react-positioning/.babelrc.json
packages/react-positioning/etc/react-positioning.api.md
packages/react-positioning/jest.config.js
packages/react-positioning/package.json
packages/react-positioning/src/createArrowStyles.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-positioning` package.
---

chore: migrate react-positioning to use Griffel

---

change/@fluentui-react-popover-ca31294d-f8a3-4d50-bb6d-0d42a16bd4e2.json
packages/react-popover/e2e/Popover.e2e.ts
packages/react-popover/src/components/PopoverSurface/PopoverSurface.test.tsx
packages/react-popover/src/components/PopoverSurface/__snapshots__/PopoverSurface.test.tsx.snap
packages/react-popover/src/components/PopoverSurface/usePopoverSurface.ts

Popover always has a `dialog` role. This announcement can be confusing if the there is no interactive content inside the popover.
Since all interactive popovers should use `trapFocus`, use `role="complementary"` when `trapFocus` is not false.
Addressed by #21107

fix: Use role=complementary for Popovers without focus traps

---

change/@fluentui-react-badge-b4e3ad27-6930-4b64-a41b-3f5c8e457165.json
packages/react-badge/.babelrc.json
packages/react-badge/jest.config.js
packages/react-badge/package.json
packages/react-badge/src/common/isConformant.ts
packages/react-badge/src/components/Badge/useBadgeStyles.ts
packages/react-badge/src/components/CounterBadge/useCounterBadgeStyles.ts
packages/react-badge/src/components/PresenceBadge/usePresenceBadgeStyles.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-badge` package.
---

chore: migrate react-badge to use Griffel

---

change/@fluentui-react-card-85862361-6d0b-4c7e-8e71-6dba14d096fa.json
packages/react-card/.babelrc.json
packages/react-card/jest.config.js
packages/react-card/package.json
packages/react-card/src/common/isConformant.ts
packages/react-card/src/components/Card/useCardStyles.ts
packages/react-card/src/components/CardFooter/useCardFooterStyles.ts
packages/react-card/src/components/CardHeader/useCardHeaderStyles.ts
packages/react-card/src/components/CardPreview/useCardPreviewStyles.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-card` package.
---

chore: migrate react-card to use Griffel

---

change/@fluentui-react-image-480ca1f4-1cec-45a2-a2fc-4522980965de.json
packages/react-image/.babelrc.json
packages/react-image/MIGRATION.md
packages/react-image/jest.config.js
packages/react-image/package.json
packages/react-image/src/common/isConformant.ts
packages/react-image/src/components/Image/useImageStyles.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-image` package.
---

chore: migrate react-image to use Griffel

---

.github/workflows/pr-housekeeping.yml

Version 1.2.0 had a bug where `pull_request` was the only acceptable target.
Version 1.2.2 has this issue fixed.
https://github.com/andrefcdias/add-to-milestone/pull/67

fix: update add-to-milestone to support pull_request_target

---

packages/react-slider/.babelrc.json
packages/react-slider/jest.config.js
packages/react-slider/package.json
packages/react-slider/src/common/isConformant.ts
packages/react-slider/src/components/Slider/useSliderStyles.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-slider` package.
---

chore: migrate react-slider to use Griffel

---

change/@fluentui-react-label-368bd8fc-a2ef-4159-b9c9-b51cefbeb446.json
packages/react-label/.babelrc.json
packages/react-label/jest.config.js
packages/react-label/package.json
packages/react-label/src/common/isConformant.ts
packages/react-label/src/components/Label/useLabelStyles.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-radio` package.
---

chore: migrate react-label to use Griffel

---

change/@fluentui-react-button-1624e91c-410a-4440-94cd-200b98766bc9.json
packages/react-button/.babelrc.json
packages/react-button/jest.config.js
packages/react-button/package.json
packages/react-button/src/common/isConformant.ts
packages/react-button/src/components/Button/useButtonStyles.ts
packages/react-button/src/components/CompoundButton/useCompoundButtonStyles.ts
packages/react-button/src/components/MenuButton/useMenuButtonStyles.ts
packages/react-button/src/components/SplitButton/useSplitButtonStyles.ts
packages/react-button/src/components/ToggleButton/useToggleButtonStyles.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-checkbox` package.
---

chore: migrate react-button to use Griffel

---

change/@fluentui-react-text-deb16e3d-c089-4d90-ad84-7ef467f659c9.json
packages/react-text/.babelrc.json
packages/react-text/MIGRATION.md
packages/react-text/jest.config.js
packages/react-text/package.json
packages/react-text/src/common/isConformant.ts
packages/react-text/src/components/Body/Body.tsx
packages/react-text/src/components/Caption/Caption.tsx
packages/react-text/src/components/Display/Display.tsx
packages/react-text/src/components/Headline/Headline.tsx
packages/react-text/src/components/LargeTitle/LargeTitle.tsx
packages/react-text/src/components/Subheadline/Subheadline.tsx
packages/react-text/src/components/Text/useTextStyles.ts
packages/react-text/src/components/Title1/Title1.tsx
packages/react-text/src/components/Title2/Title2.tsx
packages/react-text/src/components/Title3/Title3.tsx
packages/react-text/src/components/wrapper.tsx
packages/react-text/src/stories/Default.stories.tsx
packages/react-text/src/typographyStyles/typographyStyles.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-text` package.
---

chore: migrate react-text to use Griffel

---

change/@fluentui-react-checkbox-54181b52-9a19-48e5-8cc3-c2cea765d706.json
packages/react-checkbox/.babelrc.json
packages/react-checkbox/jest.config.js
packages/react-checkbox/package.json
packages/react-checkbox/src/common/isConformant.ts
packages/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-checkbox` package.
---

chore: migrate react-checkbox to use Griffel

---

change/@fluentui-react-switch-2d4f5aec-848b-43e6-bc09-a78eb573b3b3.json
packages/react-switch/.babelrc.json
packages/react-switch/jest.config.js
packages/react-switch/package.json
packages/react-switch/src/Switch.stories.tsx
packages/react-switch/src/common/isConformant.ts
packages/react-switch/src/components/Switch/useSwitchStyles.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-switch` package.
---

chore: migrate react-switch to use Griffel

---

change/@fluentui-react-input-9bef86de-9038-4127-8e8e-81f0881cb6da.json
packages/react-input/.babelrc.json
packages/react-input/jest.config.js
packages/react-input/package.json
packages/react-input/src/common/isConformant.ts
packages/react-input/src/components/Input/useInputStyles.ts
packages/react-input/src/stories/InputAppearance.stories.tsx
packages/react-input/src/stories/InputContentBeforeAfter.stories.tsx
packages/react-input/src/stories/InputSize.stories.tsx
packages/react-input/src/stories/InputType.stories.tsx

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-input` package.
---

chore: migrate react-input to use Griffel

---

packages/react-radio/.babelrc.json
packages/react-radio/jest.config.js
packages/react-radio/package.json
packages/react-radio/src/common/isConformant.ts
packages/react-radio/src/components/Radio/useRadioStyles.ts
packages/react-radio/src/components/RadioItem/useRadioItemStyles.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-radio` package.
---

chore: migrate react-radio to use Griffel

---

change/@fluentui-react-tooltip-d6140e21-2c99-4913-826d-8075c45c6fd4.json
packages/react-tooltip/.babelrc.json
packages/react-tooltip/jest.config.js
packages/react-tooltip/package.json
packages/react-tooltip/src/common/isConformant.ts
packages/react-tooltip/src/components/Tooltip/useTooltipStyles.ts
packages/react-tooltip/src/stories/TooltipAria.stories.tsx
packages/react-tooltip/src/stories/TooltipDefault.stories.tsx
packages/react-tooltip/src/stories/TooltipPositioning.stories.tsx

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-tooltip` package.
---

chore: migrate react-tooltip to use Griffel

---

change/@fluentui-react-avatar-40747d70-5829-4f5d-8a6d-da1153e4b710.json
packages/react-avatar/.babelrc.json
packages/react-avatar/jest.config.js
packages/react-avatar/package.json
packages/react-avatar/src/common/isConformant.ts
packages/react-avatar/src/components/Avatar/useAvatarStyles.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-avatar` package.
---

chore: migrate react-avatar to use Griffel

---

change/@fluentui-react-avatar-63302eb2-4c8b-47b4-ba87-d1755cea3fbd.json
packages/react-avatar/etc/react-avatar.api.md
packages/react-avatar/src/AvatarGetInitials.stories.tsx
packages/react-avatar/src/AvatarSize.stories.tsx
packages/react-avatar/src/components/Avatar/Avatar.test.tsx
packages/react-avatar/src/components/Avatar/Avatar.types.ts
packages/react-avatar/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
packages/react-avatar/src/components/Avatar/renderAvatar.tsx
packages/react-avatar/src/components/Avatar/useAvatar.tsx
packages/react-avatar/src/components/Avatar/useAvatarStyles.ts

* Avatar's `label` slot is confusingly named: its purpose is to display the initials, not a general purpose label
* Avatar doesn't have good accessibility
* Remove Avatar's `getInitials` prop. Instead, the user can just set `initials={myCustomInitialsFunction(name)}`
* Default the image's `alt` attribute to the name
* Update aria props to the initials and icon slots:
* Add `aria-hidden="true"` if the image is present
* If there's no image, add `role="img" aria-label={name}` to make the avatar appear as an image to accessibility tools.

Avatar: Rename `label` slot to `initials`, remove `getInitials` prop, and improve accessibility

---

apps/perf-test/package.json
packages/fluentui/perf-test/package.json

- Perf-test CI pipeline is failing since `react-icons` (which lives in another repo) is still using `react-make-styles` and has yet to migrate to Griffel. No packages in our repo trigger `react-make-styles` build anymore which is causing the error.
Temporarily adds `react-make-styles` as a dependency of the `perf-test` package. Should be removed once [PR ](https://github.com/microsoft/fluentui-system-icons/pull/393)to migrate `react-icons` to Griffel is merged. 
Fixes #

temp fix: Add react-make-styles as devDep to fix perf test pipeline

---

packages/react-spinbutton/.babelrc.json
packages/react-spinbutton/jest.config.js
packages/react-spinbutton/package.json
packages/react-spinbutton/src/common/isConformant.ts
packages/react-spinbutton/src/components/SpinButton/useSpinButtonStyles.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-spinbutton` package.
---

chore: migrate react-spinbutton to use Griffel

---

packages/react-popover/src/stories/PopoverNestedPopovers.stories.tsx
packages/react-popover/src/stories/PopoverTrappingFocus.stories.tsx

Interactive popovers should follow the WAI dialog pattern, so
`aria-labelledby` should be present so that the dialog is labelled by
the heading of the content.
Addressed by: #21107

docs: Interactive popover stories should use aria-labelledby

---

change/@fluentui-react-badge-d43aec0f-403d-43e0-a257-d246681911bf.json
packages/react-badge/src/BadgeBestPractices.md

Badges should not have long text, they are intended for short text or small numerical values. If a long text is added to a Badge it will result into a broken UI especially in zoom. 
This PR adds this information to the best practices so that it is explicitly mention how it should be used.
No change to the Badge functionality.
Fixes #21130

react-badge: Updated best practices for long text

---

change/@fluentui-react-portal-a4b331c9-24db-4100-808c-a711f9e7eeca.json
package.json
packages/react-portal/.babelrc.json
packages/react-portal/jest.config.js
packages/react-portal/package.json
packages/react-portal/src/stories/PortalDefault.stories.tsx
packages/react-portal/src/stories/PortalNested.stories.tsx

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-portal` package.
- `@fluentui/react-make-styles` => `@griffel/react` (only in stories)
As Griffel is not used as dependency in this package, `make-styles` packages were removed from configs.
---

chore: migrate react-portal to use Griffel

---

packages/react-dialog/.babelrc.json
packages/react-dialog/jest.config.js
packages/react-dialog/package.json
packages/react-dialog/src/common/isConformant.ts
packages/react-dialog/src/components/Dialog/useDialogStyles.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-dialog` package.
---

chore: migrate react-dialog to use Griffel

---

change/@fluentui-react-divider-de1f0901-ef09-4ac0-8399-2584219ca5c6.json
packages/react-divider/.babelrc.json
packages/react-divider/jest.config.js
packages/react-divider/package.json
packages/react-divider/src/common/isConformant.ts
packages/react-divider/src/components/Divider/useDividerStyles.ts
packages/react-divider/src/stories/DividerAlignContent.stories.tsx
packages/react-divider/src/stories/DividerAppearance.stories.tsx
packages/react-divider/src/stories/DividerCustomStyles.stories.tsx
packages/react-divider/src/stories/DividerDefault.stories.tsx
packages/react-divider/src/stories/DividerInset.stories.tsx
packages/react-divider/src/stories/DividerVertical.stories.tsx

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-divider` package.
---

chore: migrate react-divider to use Griffel

---

packages/react-tabs/.babelrc.json
packages/react-tabs/jest.config.js
packages/react-tabs/package.json
packages/react-tabs/src/common/isConformant.ts
packages/react-tabs/src/components/Tab/useTabStyles.ts
packages/react-tabs/src/components/TabList/useTabListStyles.ts
packages/react-tabs/src/stories/TabListAppearance.stories.tsx
packages/react-tabs/src/stories/TabListDefault.stories.tsx
packages/react-tabs/src/stories/TabListSizeMedium.stories.tsx
packages/react-tabs/src/stories/TabListSizeSmall.stories.tsx
packages/react-tabs/src/stories/TabListVertical.stories.tsx
packages/react-tabs/src/stories/TabListWithIcon.stories.tsx

This PR replaces `@fluentui/react-make-styles` with `@griffel/core` and related packages in `@fluentui/react-tabs` package.
---

chore: migrate react-tabs to use Griffel

---

change/@fluentui-react-avatar-56b839c4-963b-40e9-a27c-6002a17750c8.json
packages/react-avatar/etc/react-avatar.api.md
packages/react-avatar/src/components/Avatar/Avatar.types.ts
packages/react-avatar/src/index.ts
packages/react-avatar/src/utils/getInitials.ts

Export the `getInitials` function from `@fluentui/react-avatar` so users can optionally use it in their implementation
This is a follow-up from a comment on another PR for Avatar: https://github.com/microsoft/fluentui/pull/21346#discussion_r791924699

Avatar: Export the default getInitials implementation

---

change/@fluentui-react-components-03c79370-75d3-4a56-84bf-8fb29626fb8e.json
packages/react-components/.babelrc.json
packages/react-components/jest.config.js
packages/react-components/package.json

This PR replaces `@fluentui/*-make-styles` `devDependencies` with `@griffel/*` in `@fluentui/react-components` package.
Following packages were replaced (**only** `devDependencies`):
This solves build issue that happened in (#21470):
- `packages/react-components/jest.config.js` has `@fluentui/jest-serializer-make-styles`
- `@fluentui/react-components` does not have `@fluentui/jest-serializer-make-styles` in `devDependencies`
- nothing builds `@fluentui/jest-serializer-make-styles`, build fails 💥

chore: make-styles devDependencies in react-components

---

apps/vr-tests/.storybook/main.js
apps/vr-tests/package.json
azure-pipelines.yml
package.json
yarn.lock

This PR replaces usage of `@fluentui/make-styles-webpack-loader` with `@griffel/webpack-loader` in `vr-tests` package.
It will be deprecated and removed from Fluent codebase in a separate PR.
Yes ⬇️

chore: use Griffel webpack loader

---

change/@fluentui-react-tooltip-c42cbf2b-b2cc-41d6-ad2e-623d5f5bdd7c.json
packages/react-tooltip/etc/react-tooltip.api.md
packages/react-tooltip/src/common/isConformant.ts
packages/react-tooltip/src/components/Tooltip/Tooltip.test.tsx
packages/react-tooltip/src/components/Tooltip/Tooltip.tsx
packages/react-tooltip/src/components/Tooltip/Tooltip.types.ts
packages/react-tooltip/src/components/Tooltip/renderTooltip.tsx
packages/react-tooltip/src/components/Tooltip/useTooltip.tsx
packages/react-tooltip/src/components/Tooltip/useTooltipStyles.ts

This PR implements #21261 and aligns API of `Tooltip` component with other components that use Trigger pattern. `content` on `Tooltip` becomes a real slot.
```tsx
return (
<>
<Tooltip content="Foo" />
<Tooltip
content="Foo"
className="bar"
id="foo"
onClick={() => {
console.log("baz");
}}
/>
</>
);
}
```
```tsx
return (
<>
<Tooltip content="Foo" />
<Tooltip
content={{
children: "Foo",
className: "bar",
// 👆 if "className" will passed to "Tooltip" directly you will get a TS error
id: "foo",
onClick: () => {
console.log("baz");
}
}}
/>
</>
);
}
```

Tooltip: align API with other components that use triggers

---

change/@fluentui-react-91884cdd-2d97-41a6-827b-09f555e1032b.json
packages/react/src/components/Panel/Panel.styles.ts
packages/react/src/components/Panel/__snapshots__/Panel.test.tsx.snap

- Currently, the `header` of the `Panel` has a hardcoded `background-color` when it meets the height based media query. This was added to prevent the `content` from overlapping with the stickied `header` when scrolling down (see screenshot below) since by default, the `header`'s background color is **transparent**. However, this caused an issue where consumers get inconsistent background colors when they directly customize the `header` or the `main` root.
**`content` overlaps with `header` on scroll since `header` has a transparent background by default:**
- The `header` will now **inherit** its `background` from its parent. If its parent does not have a background color specified, it will directly inherit its background from `main`. This ensures that there's always a `background-color` …

Panel: Header now properly inherits background color from main

---

packages/react-slider/src/components/Slider/Slider.stories.tsx

Flex layout was causing issues in Safari. Grid layout is more predictable.  
Bug we're trying to avoid is being addressed by w3c right now. Looks like it could also be solved by giving the flex items an explicit flex basis (which we don't do due to how the story wrapper works)
https://github.com/w3c/csswg-drafts/issues/6822
Here is a repro of the bug when using a % height inside of a flexbox https://codepen.io/micahgodbolt/pen/oNogGVo

Slider story layoyut updates

---

change/@fluentui-react-button-6c840806-b17d-4402-85d5-cbc963eb57dd.json
packages/react-button/src/components/ToggleButton/ToggleButton.test.tsx
packages/react-button/src/components/ToggleButton/useToggleButton.ts

When `ToggleButton` was `disabledFocusable`, clicking it still triggered a change in `aria-pressed`.
After this PR, clicking on a `disabledFocusable` `ToggleButton` does no longer trigger a change in `aria-pressed`.
Fixes #21407

ToggleButton: Stopping aria-pressed from changing when ToggleButton is disabledFocusable

---

change/@fluentui-react-button-159dc420-be08-4472-9dbb-634db2fd56ca.json
packages/react-button/src/components/Button/useButtonStyles.ts

The `Button` components have a border radius of `2px` (`borderRadiusSmall` token) when they are passed in `size="small"`.
This PR changes this value to `4px` (`borderRadiusMedium` token) in accordance with changes made in the design specification for the `Button` component.
Fixes #20991

Button: Changing border radius of small button to borderRadiusMedium

---

change/@fluentui-react-cca25cf7-0a9d-4d36-8d45-ff8e0a2411da.json
packages/react/src/components/DetailsList/DetailsRow.styles.ts

In Windows high contrast mode, the link color on selected DetailsList rows was incorrect because of a mismatch of selector specificity between non-HCM and HCM styles. This fixes the high contrast selector specificity.
Fixes [10836](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/10836
Visual change:
to

fix(Detailslist): link high contrast selector specificity

---

change/@fluentui-react-6ab3ca9f-7a9a-46a4-b405-457d482d3d4f.json
packages/react-examples/src/react-focus/__snapshots__/FocusZone.Disabled.Example.tsx.shot
packages/react-examples/src/react-focus/__snapshots__/FocusZone.List.Example.tsx.shot
packages/react-examples/src/react-focus/__snapshots__/FocusZone.Tabbable.Example.tsx.shot
packages/react-examples/src/react/TextField/TextField.PrefixAndSuffix.Example.tsx
packages/react-examples/src/react/__snapshots__/ColorPicker.Basic.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Basic.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Compact.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/DetailsList.Documents.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/TextField.Basic.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/TextField.Borderless.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/TextField.Controlled.Example.tsx.shot
packages/react-examples/src/react/__snapshots__/TextField.CustomRender.Example.tsx.shot
packages/react/src/components/ColorPicker/__snapshots__/ColorPicker.test.tsx.snap
packages/react/src/components/TextField/TextField.base.tsx
packages/react/src/components/TextField/__snapshots__/TextField.test.tsx.snap

The Textfield prefix/suffix was not included in the accessible name or description of the input. This PR updates Textfield to build `aria-labelledby` to include prefix/suffix elements (if they exist), in addition to the label. It also removes the `ariaLabel` prop from the examples, where it was overridden by `aria-labelledby` in any case.
Fixes [13169](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/13169)

fix(Textfield): include prefix/suffix in accessible name

---

change/@fluentui-react-charting-a6d89901-e651-461a-ae5b-4072c54bbc39.json
packages/react-charting/src/components/AreaChart/AreaChart.base.tsx
packages/react-examples/src/react-charting/AreaChart/AreaChart.Styled.Example.tsx

When user pass custom radius for circle point, on hover all the circle are visible, here only active circle should visible. 
Only active circle will be visible even if user pass the custom radius for area chart point. 
https://user-images.githubusercontent.com/29042635/151368668-2188441c-891c-45f3-b4d3-ed52879d8be0.mp4
https://user-images.githubusercontent.com/29042635/151368697-fa893fcb-c149-440d-9c09-bf25b58b05e5.mp4
Fixes #

For point/circle custom radius, only active point/circle will be visible in area chart 

---

change/@uifabric-charting-395838cd-d70b-4a1b-9f42-d67d85e8bd2b.json
packages/charting/src/components/AreaChart/AreaChart.base.tsx
packages/react-examples/src/charting/AreaChart/AreaChart.Styled.Example.tsx

Cherry pick of [#21473](https://github.com/microsoft/fluentui/pull/21473)
When user pass custom radius for circle point, on hover all the circle are visible, here only active circle should visible. 
Only active circle will be visible even if user pass the custom radius for area chart point. 
https://user-images.githubusercontent.com/29042635/151368668-2188441c-891c-45f3-b4d3-ed52879d8be0.mp4
https://user-images.githubusercontent.com/29042635/151368697-fa893fcb-c149-440d-9c09-bf25b58b05e5.mp4
Fixes #

Charting: CherryPick #21473: For point/circle custom radius, only active point/circle will be visible in area chart

---

scripts/use-yarn-please.js

Running `yarn ...` commands on Windows fails.
Running `yarn ...` commands on Windows works.
The change updates the `spawnSync` command to [spawn in a shell which allows `cmd` files to be executed on Windows](https://nodejs.org/api/child_process.html#spawning-bat-and-cmd-files-on-windows) (`yarn` invokes a file called `yarn.cmd` on Windows)
Additionally, links to Yarn documentation in `use-yarn-please.js` have been updated to point to `https://classic.yarnpkg.com/...` as this is the docs site for Yarn 1.x and this project is using Yarn 1.x.
It appears a change in #17196 surfaced this issue.

Fix failing "yarn" commands on Windows

---

packages/fluentui/test-a-feature.md
scripts/tasks/check-for-modified-files.ts

I previously updated the name of the "check for modified files" step to remove the word "change" and reduce confusion with missing beachball change files.
But the error message itself still says "changed files," and at least in [this build](https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=234781&view=logs&j=e04f516c-d41f-56c0-01f7-6f5ba91e652f&t=343794f6-bec6-56c0-7ec6-a9e0b3d94ab5&l=22), the diff was missing (the blank line is supposed to be a diff).
```
[7:23:06 PM] x This build has files that are tracked by git that resulted in changed files.
[7:23:06 PM] x Check the following output and resolve the problem that caused these files to change
[7:23:06 PM] x Most likely you committed your files with --no-verify
[7:23:06 PM] x M  ../packages/fluentui/test-a-feature.md …
```

Update wording in check for modified files script to reduce confusion

---

change/@fluentui-react-button-cb98f8c3-450b-4c40-9613-e980b1357b50.json
packages/react-button/etc/react-button.api.md
packages/react-button/src/components/MenuButton/MenuButton.types.ts

`MenuButton` currently accepts a `ref` that is typed as `Ref<never> & Ref<HTMLButtonElement | HTMLAnchorElement>` which makes it impossible to satisfy with type-safety (i.e. need to type as `any`).
Thir PR fixes the issue by correctly typing `MenuButton` by removing the `MenuTriggerChildProps` type from its definition, as `MenuButton` already supports the attributes that type indicates while also removing the `Ref<never>` type that is screwing up the usage of `ref`.
You can try it out by doing:
```tsx
const ref = React.useRef<HTMLButtonElement | HTMLAnchorElement>(null);
...
<MenuButton ref={ref}>This is a Menu Button</MenuButton>
```
Which will complain before the changes in this PR, whilst working correctly after those changes.
Fixes #21484

MenuButton: Updating types so it properly supports ref

---

apps/vr-tests/src/stories/AvatarConverged.stories.tsx
change/@fluentui-react-avatar-c14f3a02-b7da-4d44-8f3b-83c101e3bc45.json
packages/react-avatar/etc/react-avatar.api.md
packages/react-avatar/src/AvatarActiveAppearance.stories.tsx
packages/react-avatar/src/components/Avatar/Avatar.types.ts
packages/react-avatar/src/components/Avatar/useAvatarStyles.ts

Avatar's `glow` and `ring-glow` activeAppearances are currently using temporary styles, as their visuals have not been finalized by design yet.
Remove `glow` and `ring-glow` for now. They will be added back later, once we have final visuals for them.
Fixes #21351

Avatar: Remove `glow` and `ring-glow` from activeAppearance, as their visuals are not yet finalized

---

change/@fluentui-react-button-35b6612e-1154-4058-b7d3-3fe3d42bdc47.json
packages/react-button/src/components/Button/useButtonStyles.ts
packages/react-button/src/components/CompoundButton/useCompoundButtonStyles.ts

This PR updates the styles of the `CompoundButton` component to match the latest design specification guidelines.
__Before:__
__After:__
This PR also removes the `buttonSpacing` object and replaces it with inline values. I will have a conversation with design on how to follow up with these values.
Fixes #20172

CompoundButton: Updating styles to match latest design spec.

---

change/@fluentui-react-components-05f4886b-95c5-4d2b-b774-d070055353cb.json
packages/react-components/etc/react-components.api.md
packages/react-components/package.json
packages/react-components/src/Concepts/Positioning/PositioningCoverTarget.stories.tsx
packages/react-components/src/Concepts/Positioning/PositioningShorthandPositions.stories.tsx
packages/react-components/src/DocsComponents/FluentDocsPage.stories.tsx
packages/react-components/src/Migrations/utils.stories.tsx
packages/react-components/src/index.ts

This PR replaces `@fluentui/react-make-styles` with `@griffel/react` in `@fluentui/react-components` package.
- `RenderProvider`, `RendererProviderProps` and `useRenderer` are not exported anymore. These APIs are internal to Griffel and should not be exposed to customers.
---

chore: migrate react-components to use Griffel

---

change/@fluentui-merge-styles-311979b9-ac34-4eab-9d7c-7e8a3b61f638.json
packages/merge-styles/etc/merge-styles.api.md
packages/merge-styles/src/IRawStyleBase.ts

I have followed other commits that add CSS properties like https://github.com/microsoft/fluentui/commit/50a43b5d1e13e6d507ab15477316bb5742fa6dbb, https://github.com/microsoft/fluentui/commit/dedb9ae121ac9fb983e35877fe4dbb6512fd8235 and https://github.com/microsoft/fluentui/commit/1959808480faf783fd56f51294f58467371538ad. Please, let me know if some more work is needed.
It is not possible to use logical margins CSS properties, e.g.
<Text styles={{ root: { marginInlineStart: '12px' } }}>
It should be possible to use logical margins CSS properties.
https://github.com/microsoft/fluentui/issues/21321
Fixes #21321

Add logical margins CSS properties to IRawStyleBase, resolves #21321

---

change/@fluentui-cra-template-3fe13ea3-f7da-4463-af0b-bf1f9990550d.json
package.json
packages/cra-template/template.json
packages/fluentui/react-northstar/test/specs/components/Form/FormField-test.tsx
yarn.lock

`@testing-library` deps were out of date.
`@testing-library` deps have been updated to the latest versions.
There was only one test change required, due to stricter behavior of the `toBeVisible` matcher.
Fixes #16949 (that issue also mentions upgrading jest to 27, but the jest upgrade is tracked separately by #18442)

Update testing-library deps to latest

---

change/@fluentui-cra-template-a130326a-e7ca-434d-bb78-5c568d837747.json
packages/cra-template/template.json
packages/fluentui/projects-test/src/createReactApp.ts

All builds are failing on `@fluentui/cra-template test` (northstar CRA projects-test will have a similar error):
```
TypeError: /tmp/cra-template--23641-701XsZoyanlh/test-app/node_modules/@fluentui/date-time-utilities/lib/dateFormatting/dateFormatting.types.js: Cannot read property 'originalPositionFor' of undefined
```
This also happens when create a new app using the published version of the template+packages, meaning it's an issue with some newly-released version of a `react-scripts` dependency, not an issue with our code.
Based on [this issue comment](https://github.com/aws-amplify/amplify-ui/issues/1242#issuecomment-1028471472) it seems to be some issue with the newly-released `@babel/core@7.17.0`. 
The full stack of the error (which you can see by creating an app with the template …

cra-template: temporarily add resolution for babel to work around bug

---

change/@fluentui-react-components-dba1069e-ed3c-4ca1-9128-7d9a7e928bcb.json
packages/react-components/package.json

🚨 `yarn chromatic` fails to build Storybook.
✅  `yarn chromatic` builds and releases Storybook. The `npx` script was using an outdated `chromatic` package.

Fix Storybook Publish

---

change/@fluentui-cra-template-a130326a-e7ca-434d-bb78-5c568d837747.json
change/@fluentui-cra-template-f19ad23e-0c38-418c-b102-834d12de9304.json
packages/cra-template/template.json
packages/fluentui/projects-test/src/createReactApp.ts

#21545 added a workaround for an issue causing our tests that use create-react-app to fail. (see old PR description for details)
Issue is fixed per https://github.com/facebook/create-react-app/issues/12017#issuecomment-1028615390 / https://github.com/babel/babel/issues/14229#issuecomment-1028610186. Revert workaround.
Fixes #21546

Revert cra-template workaround

---

change/@fluentui-react-components-137f8d72-db14-423b-8057-44b1dfa7857c.json
packages/react-components/package.json

seems we capture two griffels during some merge conflicts.

removed dup dependency in react-components

---

change/@fluentui-react-card-a126bdd2-10f8-4154-aac7-5cbf9f35fee7.json
change/@fluentui-react-input-34332062-0f6d-4d2a-aef7-b3e9c1e904cd.json
change/@fluentui-react-slider-52f80686-998d-4779-a397-1d083bb23670.json
packages/react-card/src/CardDescription.md
packages/react-input/src/stories/InputDescription.md
packages/react-slider/src/components/Slider/SliderDescription.md

We do not document how to import `unstable` preview components
We now show a code block with the import statement for unstable components.

Document how to import preview components

---

change/@fluentui-react-96940b77-cbb9-4e27-a121-52dde91fd023.json
packages/fluentui/react-bindings/test/styles/resolveStyles-test.ts
packages/react/src/common/testUtilities.ts
packages/react/src/components/DatePicker/DatePicker.test.tsx
packages/react/src/components/Dropdown/Dropdown.test.tsx
packages/react/src/components/ExtendedPicker/BaseExtendedPicker.test.tsx
packages/utilities/src/getPropsWithDefaults.test.ts
packages/utilities/src/safeSetTimeout.test.tsx
packages/utilities/src/setFocusVisibility.test.tsx
scripts/debug-test.js

A few tests are using either global jasmine APIs (such as *global* `spyOn`) which will stop working with [new defaults in jest 27](https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults), or deprecated jest APIs (`runTimersToTime`) that are removed in 27.
Switch to alternative/newer APIs that are already available in jest 26.
I didn't add any lint rules to ban the old APIs, so it's possible that new usage could sneak in between now and whenever we actually upgrade to jest 27. However I'm not too concerned about this because the number of new instances (if any) should be small enough that it will be easy to fix.
Related to #18442

Remove usage of jasmine and deprecated jest APIs from tests

---

change/@fluentui-react-tooltip-29b9f81e-0e54-4234-a8c6-b983ebba7116.json
packages/react-tooltip/src/components/Tooltip/Tooltip.test.tsx
packages/react-tooltip/src/components/Tooltip/useTooltip.tsx

Tooltip currently overrides aria props set on their child component. For example, the Button ends up with `aria-label="Foo"` in this scenario:
```jsx
<Tooltip content="Foo" relationship="label">
<Button aria-label="Bar">...</Button>
</Tooltip>
```
Have tooltip check for the existence of `aria-label`/`aria-labelledby` before setting either prop. Likewise, check for `aria-description`/`aria-describedby` before setting a description.
* This is a follow up to a comment on this PR: https://github.com/microsoft/fluentui/pull/21495#discussion_r795619711

Prevent Tooltip from overriding any aria-label, etc. props on its child

---

packages/fluentui/CHANGELOG.md
packages/fluentui/accessibility/src/behaviors/MenuButton/menuButtonBehavior.ts

`menuButtonBehavior` can set aria attributes to undefined value. When MenuButton is used with another component, user prop is not able to override the undefined aria attributes.
In this example: https://codesandbox.io/s/fluent-ui-example-forked-nbrh2?file=/example.tsx MenuButton is added as a contextMenu on a TreeItem, with TreeItem being the trigger. This is a very common use case. But MenuButton forces undefined aria attributes (including aria-expanded) on TreeItem, so TreeItem loses its `aria-expanded` attribute:
This is not overridable from user prop, unless user gives MenuButton a custom accessibility behavior.
This PR updates `menuButtonBehavior` to never set any aria attributes to undefined.

fix(menuButtonBehavior): do not set aria attributes when they are undefined

---

change/@fluentui-react-45e4bf9b-adec-4695-b025-ccafe5d633b8.json
packages/react/etc/react.api.md
packages/react/src/components/Dropdown/Dropdown.base.tsx
packages/react/src/components/Dropdown/Dropdown.styles.ts
packages/react/src/components/Dropdown/Dropdown.types.ts

- When an option item for a `Dropdown` are either a `header` or `divider` and given the `hidden:true` property, they are still visible:
- `header` and `divider` `Dropdown` options are no longer visible when marked as `hidden`
Fixes #19909

Dropdown: Headers and Dividers marked as hidden are no longer visible

---

change/@fluentui-react-25b07909-5295-43bd-b7ff-749c29477562.json
packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx

- The default behavior of a `ContextualMenu` is to have menu items focused on hover. The `delayUpdateFocusOnHover` prop is supposed to be a flag that prevents that behavior. However, passing that prop to `ContextualMenu` currently does not do anything. Seems like `shouldUpdateFocusOnMouseEvent` was being incorrectly set to true when `delayUpdateFocusOnHover` is `true` which resulted in the prop not working.
- Passing `delayUpdateFocusOnHover` to the `ContextualMenu` now correctly prevents focus from going to the hovered menu items. 
**CodeSandbox to demonstrate new behavior:** https://codesandbox.io/s/pr-21528-contextualmenu-hover-9ue42
Fixes ##20552

ContextualMenu: delayUpdateFocusOnHover is now working correctly so menu items are no longer focused on mouse hover

---

change/@fluentui-react-0d393c1e-1683-4e57-8df8-d9f87d796800.json
change/@fluentui-react-97e0499f-f249-4df8-9c42-b7fdb65f7f85.json
packages/react/etc/react.api.md
packages/react/src/components/Callout/Callout.types.ts
packages/react/src/components/Callout/CalloutContent.base.tsx

#21110 added `enableAriaHiddenSiblings` in several components including Callout. However, upon trying to write a test for this (after the PR was merged...oops) I noticed it wasn't being respected--this condition in Popup checks for `aria-modal`, which Callout doesn't currently pass through:
https://github.com/microsoft/fluentui/blob/3082edf3477a37c493d28f246b5217752a14b7ba/packages/react/src/components/Popup/Popup.tsx#L124-L132
I asked @smhigley about this and we decided more discussion is needed about the "right" behavior here (whether Callout should pass `aria-modal`, what the appropriate default is for `enableAriaHiddenSiblings` in that component, etc).
While writing the test I also noticed a bug where `data-*` props are being used on two different elements within Callout due to the …

Callout: Remove enableAriaHiddenSiblings (for now) and fix bug with data props

---

package.json

It was required to have `nohoist` settings for `@fluentui/make-styles` package. But as `@fluentui/make-styles` was moved out to `@griffel/core` and no longer present in out repo, these settings can be removed.

chore: remove "nohoist" for make-styles

---

change/@fluentui-react-avatar-909b616c-7314-42aa-b2f5-aecabfdd5b95.json
packages/react-avatar/src/components/Avatar/useAvatarStyles.ts

Avatar uses a box-shadow to draw its high contrast border, which works ok with the high contrast color theme, but doesn't work with Windows/Edge high contrast mode, which hides box-shadows.
Use a border on the initials/icon slot, rather than a box-shadow. Windows high contrast mode always renders borders.
* Fixes #21355

Fix Avatar high contrast border on Windows

---

change/@fluentui-react-bf05c92a-5865-4168-8b1c-6bc30f245748.json
packages/react/src/components/pickers/BasePicker.tsx
packages/react/src/components/pickers/PeoplePicker/__snapshots__/PeoplePicker.test.tsx.snap
packages/react/src/components/pickers/TagPicker/__snapshots__/TagPicker.test.tsx.snap
packages/react/src/components/pickers/__snapshots__/BasePicker.test.tsx.snap

Fixes #21656
`aria-owns` and `aria-controls` were being rendered even when there was no valid value. No impact to end users, but it causes a lot of noise in testing to the point of partners needing to turn a11y validation off. 
New behavior, aria attributes only display when they have a valid value

Only render aria properties when there is a valid value

---

change/@fluentui-react-83b3a738-2b48-4f6b-bf5a-d6ad5be98f07.json
packages/react/etc/react.api.md
packages/react/src/components/SwatchColorPicker/ColorPickerGridCell.types.ts
packages/react/src/components/SwatchColorPicker/SwatchColorPicker.base.tsx
packages/react/src/components/SwatchColorPicker/SwatchColorPicker.types.ts
packages/react/src/utilities/ButtonGrid/ButtonGridCell.tsx
packages/react/src/utilities/ButtonGrid/ButtonGridCell.types.ts

SwatchColorPicker `onChange`'s `event` parameter is undefined. Also there are some other callbacks that should have `event` parameters and don't.
Add `event` parameters to event callbacks and ensure they're passed through. Unfortunately they have to be added at the end of the parameter lists to avoid a breaking change.
(Updated version of #19650)
Fixes #19533

SwatchColorPicker: add event param to event handlers

---

change/@fluentui-react-positioning-9b11f0e0-fafc-464e-88ac-ef746c87965f.json
packages/react-components/src/Concepts/Positioning/PositioningPopperImperativeHandle.stories.tsx
packages/react-menu/src/stories/MenuAnchorToTarget.stories.tsx
packages/react-popover/src/stories/PopoverAnchorToCustomTarget.stories.tsx
packages/react-positioning/etc/react-positioning.api.md
packages/react-positioning/src/types.ts
packages/react-positioning/src/usePopper.ts

Using `<Menu positioning={{ target }} />` requires `React.useState()` (to get refs as DOM elements) call to force a double render.
Adds a `setTarget` imperative call to the `popperRef` imperative handle.
This allows users to set their own target **without** forcing a double render with `React.useState()`. `setTarget()` can be called inside `React.useEffect()` hooks, for example. The modified stories all use effects to call this API.
`onStateUpdate()` was removed `usePopper()`, as we don't it publicly it's not a breaking change. Types (`PopperOptions`, `PositioningOptions`) were also refactored to better show boundaries  between the hook and options themselves. No breaking changes in these interfaces.
Fixes #

feat: Imperative `setTarget` for `usePopper` and `positioning`

---

azure-pipelines.yml

In preparation to use our screener proxy to run vr-tests, the vr-test
story book needs to be uploaded to Azure storage similar to what is
being done for Northstar.
vr-tests storybook is not being deployed to azure in CI
vr-tests storybook is being deployed to azure in CI
[LINK TO PR STORYBOOK](https://fluentuipr.z22.web.core.windows.net/pull/21668/react-screener/index.html)
Fixes #

chore: Deploy vr-test site during CI run

---

change/@fluentui-react-d53d8331-0a23-4d37-aecb-25b73686be1c.json
packages/react/etc/react.api.md
packages/react/src/utilities/selection/SelectionZone.tsx

- When a user clicks on any part of the  `DetailsList`, that row is immediately marked as selected. However this behavior presents issues when there are already multiple rows already selected as clicking on any part of the `DetailsList` that's not the checkbox clears the previously selected rows and selects that lone clicked row.
- ### Clicking any non-checkbox part of a row clears the selection and selects that one row only:
- ![DetailsListIssue](https://user-images.githubusercontent.com/8649804/152933676-9e25cf35-f279-4216-9806-1b45d6ecdc46.gif)
- Adds a new prop called `selectionClearedOnSurfaceClick` to `SelectionZone` so now when a non-toggle element is clicked, nothing will get selected or unselected. The default behavior will have this default to `true` to …

DetailsList :Add prop to selectionZone to disable default behavior that clears selection when clicking on non-toggle surface 

---

change/@fluentui-react-components-7702cb80-2bd9-4a3b-bb4d-28a95695e9e0.json
change/@fluentui-react-input-d0f89daf-4f48-4c36-9887-d46eaa221d1d.json
change/@fluentui-react-label-8a94cbc7-e9d0-4f47-8729-14895fba88b5.json
packages/react-components/etc/react-components.api.md
packages/react-components/src/index.ts
packages/react-components/src/unstable/index.ts
packages/react-input/src/stories/Input.stories.tsx
packages/react-input/src/stories/InputDescription.md
packages/react-label/src/stories/Label.stories.tsx
packages/react-label/src/stories/LabelDescription.md
typings/storybook__addons/index.d.ts

Label is exported from `@fluentui/react-components` as almost-RC but all the input components are still unstable or not exported
Move Label to `/unstable` and update its docs description accordingly.
Update Input's docs description to include an actual explanation of the component, not just an unstable notice.
Update custom `@storybook/addons` typings to include proper typings for `docs.description.component` to get rid of the need for a cast in Input and Label stories

Move v9 Label to unstable

---

change/office-ui-fabric-react-d25edab7-544c-4ad9-b9bb-2a4bbbc4317c.json
packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx

cherry-pick of #21641
---
- When a user clicks on any part of the  `DetailsList`, that row is immediately marked as selected. However this behavior presents issues when there are already multiple rows already selected as clicking on any part of the `DetailsList` that's not the checkbox clears the previously selected rows and selects that lone clicked row.
- ### Clicking any non-checkbox part of a row clears the selection and selects that one row only:
- ![DetailsListIssue](https://user-images.githubusercontent.com/8649804/152933676-9e25cf35-f279-4216-9806-1b45d6ecdc46.gif)
- Adds a new prop called `selectionClearedOnSurfaceClick` to `SelectionZone` so now when a non-toggle element is clicked, nothing will get selected or unselected. The default behavior will have this …

[v7] DetailsList :Add prop to selectionZone to disable default behavior that clears selection when clicking on non-toggle surface

---

scripts/create-component/create-component.ts
scripts/create-component/plop-templates/src/components/{{componentName}}/use{{componentName}}Styles.ts.hbs
scripts/create-component/plop-templates/src/components/{{componentName}}/{{componentName}}.tsx.hbs

- generator produces invalid code ( type check fails, tests fail )
- generator asks if user wants to run post-processing. if user opts out he will get invalid code
- post-processing invokes unnecessary build chain
-  no asking if user want's to run post-processing
- component/package is updated and ready to go after generator run
**🎬 DEMO:**
https://user-images.githubusercontent.com/1223799/151839581-0b938baa-83b4-494d-9b5f-d4d65e7b527c.mov
Fixes #20960

fix(scripts): update create-component generator to adhere to latest changes

---

scripts/screener/screener.runner.ts

Github API client will fail if the url field does not contain a valid
url with `http` or `https` scheme

fix: Set correct url for cancel screener job API call

---

SECURITY.md

As per open source playbook, repos should include a SECURITY.md file which can be found in our repo templates
https://github.com/microsoft/repo-templates/blob/main/shared/SECURITY.md
Not sure if this was omitted on purpose or not, but I don't see any past issues about it.

Add SECURITY.md file from repo-template

---

change/@fluentui-react-b84d6012-6cba-47a0-bf2f-063e18ea34ab.json
packages/react/src/components/ComboBox/ComboBox.test.tsx
packages/react/src/components/ComboBox/ComboBox.tsx

aria-describedby and aria-labeledby were being outputed onto the container div instead of onto the internal input
aria-describedby and aria-labeledby are now skipped over when grabbing props for the outer div, and are logically rendered by the input when provided. 
Fixes #21520

Combobox native aria support for labelledby and describedby

---

change/@fluentui-react-conformance-8f7a5ab5-539c-4cbb-be77-0b1e9e42a5fa.json
packages/react-conformance/src/isConformant.ts
packages/react/src/components/Callout/Callout.test.tsx
packages/react/src/components/Callout/__snapshots__/Callout.test.tsx.snap
packages/react/src/components/Dialog/Dialog.test.tsx
packages/react/src/components/Dialog/__snapshots__/Dialog.test.tsx.snap
packages/react/src/components/Modal/Modal.test.tsx
packages/react/src/components/Modal/__snapshots__/Modal.test.tsx.snap

Callout, Dialog, and Modal's tests use a mix of enzyme, react-test-renderer, and react-dom, along with assorted odd patterns such as unnecessary snapshot testing.
Convert the tests to all use testing-library. In some cases I also tweaked what the tests were doing to be simpler or to test things more directly/effectively: for example, replacing some of the snapshot tests with direct tests of the relevant DOM.
**Please review snapshot updates with whitespace changes hidden!**
I noticed that some of the tests were having issues due to conformance tests not fully cleaning up. As a temporary workaround in react-conformance (until it's also converted to use testing-library), I added an `afterEach` which does `document.body.innerHTML = ''`.
Part of #21663

Callout, Dialog, Modal: convert tests to use testing-library

---

apps/perf-test/tasks/fluentPerfRegressions.ts

#21490 renamed packages, perf reporting is broken:

fix: perf reporting for Northstar

---

.vscode/settings.json
azure-pipelines.yml
change/@fluentui-eslint-plugin-b9154030-4181-4675-b110-63c62d547695.json
change/@fluentui-react-01f47d41-d589-464a-ada7-4ae8b9d47604.json
packages/eslint-plugin/src/utils/configHelpers.js
packages/react-examples/.storybook/preview.js
packages/react-examples/e2e/support.js
packages/react-examples/src/react/FocusTrapZone/e2e/FocusTrapZone.TabWrappingMultiFocusZone.stories.tsx
packages/react-examples/src/react/FocusTrapZone/e2e/FocusTrapZone.e2e.ts
packages/react-examples/tsconfig.json
packages/react/package.json
scripts/cypress.js

In v9 we can use cypress to run interactive tests in a real browser. This isn't possible today in v8. 
Running tests in a real browser is desirable for testing related to interactive features such as focus that aren't realistically simulated in jsdom.
Enable cypress tests for v8 and add one test for FocusTrapZone as an example.
Our cypress wrapper (`scripts/cypress.js`) was hardcoded to always load the `react-components` storybook in PR builds, so I added a `--package` option.
Since the storybook for v8 is in `react-examples`, it's easiest to also have the e2e tests and e2e-specific stories live there. Longer-term once v8 is migrated to the new build system, the e2e tests and stories could potentially be relocated to the `react` package itself.
To facilitate having e2e-only stories that …

Enable cypress for v8

---

change/@fluentui-react-accordion-ae14316f-52fa-48d7-b29f-6c7d7e47cdd6.json
packages/react-accordion/Spec.md
packages/react-accordion/src/stories/AccordionHeaders.stories.tsx

Adds warnings about lack of semantic heading element on `AccordionHeader` component by default on Storybook and Spec
Fixes #21120

doc (react-aria): Add documentation for lack of semantic heading element on `AccordionHeader` 

---

change/@fluentui-react-switch-7506c328-082e-4b5c-a8ba-667ebff4c77b.json
packages/react-switch/src/Switch.stories.tsx
packages/react-switch/src/components/Switch/useSwitchState.ts

Bug in controlled switches where renderedPosition does not change if state change only comes from state (not a click/enter)
In switch logic renderedPosition is set to undefined on `setChecked`, which then allows `currentPosition` to be based off of `checked` value vs `renderedPosition` value. With default value of `renderedPosition` at 0 or 100, incoming state changes can never affect the `currentPosition`, and it stays at that default value.
This is a bit of a bandaid as we'll probably do some major changes to the control before actual release. 
fixes #21699

Fix v9 switch bug in renderedPosition

---

change/@fluentui-react-accordion-3be4a964-94a5-4976-9db3-c6531f3964d5.json
packages/react-accordion/src/components/Accordion/useAccordion.test.ts
packages/react-accordion/src/components/Accordion/useAccordion.ts
packages/react-accordion/src/stories/AccordionMultiple.stories.tsx
packages/react-accordion/src/stories/AccordionOpenItems.stories.tsx

If `Accordion` property `multiple` is set to true, `Accordion` is allowing multiple panels to be opened as well as no panel to be opened
If `Accordion` property `multiple` is set to true, `Accordion` is allowing multiple panels to be opened but always at least one panel should be opened.
Fixes #21724

bugfix (react-accordion): solve wrong behavior on Accordion `multiple` mode

---

scripts/tasks/screener.ts

Uncomments/adds the code to scope v8 screener tests only when the
affected package graph includes the @fluentui/vr-tests project.
V8 VR tests are run for every PR
V8 VR tests are only run if `@fluentui/vr-tests` is in the affected graph. This is currently the case for v9 too until the vr-tests projects are split in #21734
Fixes partially #21070

chore: Scope v8 vr-tests

---

scripts/tasks/screener.ts

By default the `cancelScreenerRun` API sets the `cancelled` conclusion
to PRs, which doesn't actually pass CI.
This was done so that skipping (i.e. passing) was done explicitly. I
have fallen into my own trap here.
Non-necessary v8 screener runs are cancelled, which don't pass CI check
Non-necessary v8 screener runs are skipped, which pass CI check
Fixes #

fix: Skip screener check

---

.github/workflows/check-change.yml
azure-pipelines.yml
scripts/beachball/.beachballrc.base.json
scripts/beachball/index.ts

We ran `yarn checkchange` in the main pipeline that runs build.
This might be my personal problem, but I keep forgetting to add changelog files ¯\_(ツ)_/¯
From my POV there are following issues:
- it takes around 3-5 minutes before CI will reach `yarn checkchange` step
- if the step fails nothing after it will run
_This looks like a punishment to contributors_ 😁
`yarn checkchange` is moved out to a separate workflow.
- This workflow is blazing fast as it does not install packages (overall run is less than a minute) => fast check ⏱
- This workflow does not break the build pipeline => if you forgot to push change files you don't need to wait 5 minutes to see failing CI 👌
---
**New Github workflow should be marked as the required check.**

chore: move "yarn checkchange" to Github Action

---

change/@fluentui-react-accordion-da606dee-fa35-47c7-9d15-6c0f29d721af.json
packages/react-accordion/Spec.md
packages/react-accordion/src/components/Accordion/Accordion.types.ts
packages/react-accordion/src/components/Accordion/AccordionContext.ts
packages/react-accordion/src/components/Accordion/useAccordion.ts
packages/react-accordion/src/components/Accordion/useAccordionContextValues.test.ts
packages/react-accordion/src/components/Accordion/useAccordionContextValues.ts
packages/react-accordion/src/components/AccordionHeader/useAccordionHeader.test.tsx
packages/react-accordion/src/components/AccordionItem/useAccordionItem.ts
packages/react-accordion/src/stories/AccordionNavigable.stories.tsx

Accordion `navigable` props is not working properly, it should allow keyboard navigation when property is set.
1. Accordion `navigable` props is working _"properly"_, it should allow keyboard navigation when property is set.
2. Adds circular navigation by default and linear as optional.
Apparently right now we're having problems reproducing the exact [WAI-ARIA behavior from Accordion specification](https://www.w3.org/TR/wai-aria-practices/#accordion) with tabster https://github.com/microsoft/tabster/issues/111
Fixes #21725

bugfix(react-accordion): Fix navigable not working

---

apps/vr-tests-react-components/package.json
apps/vr-tests-react-components/screener.config.js
apps/vr-tests/screener.config.js
azure-pipelines.yml
scripts/gulp/tasks/screener.ts
scripts/screener/screener.types.ts
scripts/tasks/screener.ts

Screener tests don't run for only v9
New `microsoft/fluentui/react-components` screener project that stores screenshots just for v9.
The associated check is `Screener @fluentui/react-components`. The end result should be a rename of all our screener checks to follow `Screener <package name>` pattern.
Fixes partially #21070

chore: Enable v9 screener run

---

change/@fluentui-utilities-291f1e4e-88ca-4c70-903e-5de975c9a5af.json
packages/utilities/src/styled.tsx

Currently, the `concatenatedStyles` function has a reference to the props which can lead to memory leaks as other props can have references to Detached HTMLDivElements especially if the use setState such as onSelectDate in CalendarDayGrid.
Instead of using the prop argument, the style property is stored in a local variable and used within the `concatenatedStyles` function does not have a reference to the other props.

Store the styles property in a local variable so the rest of the props are not bound to the concatenatedStyles function

---

azure-pipelines.release-vnext-nightly.yml
azure-pipelines.release-vnext.yml

`yarn lage run --only` does not work it still triggers build -> triggered an issue with Lage microsoft/lage#220
Run production build before publish step so source maps are correctly generated.
Fixes #21686

fix: Run v9 production build before publish

---

change/@fluentui-react-image-c3a7ec7f-295b-4a5a-afe5-e1e353944e9e.json
packages/react-image/package.json

@fluentui/react-theme is not  a dependency of @fluentui/react-image
@fluentui/react-theme is a dependency of @fluentui/react-image
Fixes #

fix: Add react-theme as dependency to react-image

---

scripts/create-package/plop-templates-node/package.json.hbs
scripts/create-package/plop-templates-react/package.json.hbs
scripts/create-package/plopfile.ts

create-package sets new package versions to the same as the first 9.0 packaged reference.  
This sets to the latest version (e.g. 9.0.0-rc.2)
create-package sets new package version to 9.0.0-alpha.0 for converged.
Note: the package.json.hbs files were not using the packageVersion from the data object set in plopfile.ts, now they are so they pick up the correct v8 or converged initial package version.
Fixes #21793

create-package sets initial package version to alpha for converged

---

change/@fluentui-react-0871327a-3a79-40e3-a43a-e99c4c35bb64.json
packages/react/etc/react.api.md
packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx
packages/react/src/components/ContextualMenu/ContextualMenu.types.ts

- There's currently no appropriate way to wrap each menu item in a `ContextualMenu` in a custom tooltip. Using the current `contextualMenuItemAs` prop overrides the children of the menu item button and doesn't include the button itself. This results in the tooltip not rendering when a menu item button receives keyboard focus. 
- ### Tooltip doesnt render on keyboard focus: 
- A new prop called `onRenderContextualMenuItem` is now added to enable consumers to wrap the contextual menu item button in a tooltip. Now, when a menu item receives keyboard focus, the tooltip is rendered appropriately.
- ### Tooltip now renders on keyboard focus: 
Fixes #19862

ContextualMenu: Add prop that allows users to wrap a custom tooltip around each menu item button

---

azure-pipelines.release-vnext.yml

Somewhat of a mitigation for #21805
@fluentui/vr-tests-react-components had the version at 0.1.0 which mean it was never scoped for bump by publish step. There's no way to enforce this apart from failing in the release pipeline. So the syncpack check should provide some early warning in the future if there are packages that weren't bumped.

chore: Add syncpack check to v9 release pipeline

---

change/@fluentui-utilities-710b5dfd-1525-43a7-9bf6-78ebd0eb9143.json
packages/utilities/src/DelayedRender.tsx

./packages/utilities/src/DelayedRender.tsx does not render during SSR
./packages/utilities/src/DelayedRender.tsx renders during SSR
Fixes #21783

Disable delayed render during SSR

---

packages/fluentui/CHANGELOG.md
packages/fluentui/docs/src/examples/components/Popup/Visual/PopperExampleVisibilityModifiers.steps.ts
packages/fluentui/docs/src/examples/components/Popup/Visual/PopperExampleVisibilityModifiers.tsx
packages/fluentui/docs/src/examples/components/Popup/Visual/index.tsx
packages/fluentui/react-northstar/src/utils/positioner/isIntersectingModifier.ts
packages/fluentui/react-northstar/src/utils/positioner/usePopper.ts

This PR adds new Popper.js modifier called `isIntersectingModifier` to `usePopper()` hook in Fluent UI N\*.
This modifier is based on the ask from a partner team. Currently we have already used [`hide` modifier](https://popper.js.org/docs/v2/modifiers/hide/) that adds following DOM attributes based on state:
- `data-popper-reference-hidden`: This attribute gets applied to the popper when the reference element is fully clipped and hidden from view, which causes the popper to appear to be attached to nothing.
- `data-popper-escaped`: This attribute gets applied when the popper escapes the reference element's boundary (and so it appears detached).
The problem that there is no state when a popover intersects boundaries:
The partner team wants to hide popovers once they reach boundaries. This …

feat: add isIntersectingModifier to usePopper in v0

---

change/@fluentui-react-checkbox-ec315fd3-3852-463a-b6ea-62a3884cb750.json
packages/react-checkbox/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
packages/react-checkbox/src/components/Checkbox/renderCheckbox.tsx
packages/react-checkbox/src/components/Checkbox/useCheckbox.tsx
packages/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts

Checkbox's styles depend on the checked, mixed, and disabled state values. This can result in the checkbox using enabled colors if it is disabled by being inside a disabled group.
Use CSS pseudo-classes on the input slot, to change the colors of the indicator and label.

Refactor Checkbox styles to use CSS pseudo-classes

---

packages/react-storybook-addon/src/demos.stories.tsx

When running `storybook` within react-storybook-addon, user get blank storybook, which is confusing.
`storybook` renders a demo stories that interacts with addon new controls (Theme in toolbar)
https://user-images.githubusercontent.com/1223799/148911892-de58aa73-c152-4f25-b994-c5ae3399953e.mov
Relates to https://github.com/microsoft/fluentui/issues/21227 ( to demonstrate actual functionality )

docs(react-storybook-addon): add demo stories to showcase the addon controls

---

change/@fluentui-react-label-f0755fa2-4c9c-4ca5-b65c-763611f23e66.json
packages/react-label/README.md

README showed usage of React 18's `useId()` hook and used the hook incorrectly (it does not accept any arguments).
README shows usage of `@fluentui/react-utilities`' `useId()` hook. This is consistent with how IDs are generated internally in `@fluentui/react-components` and aligns with the minimum supported React version for this library which is currently `16.8.6`

Update react-label README

---

change/@fluentui-react-utilities-570f1a73-95a2-4590-a3dc-8991afafbad4.json
packages/react-utilities/src/hooks/useId.test.tsx
packages/react-utilities/src/hooks/useId.ts

The `useId()` hook has the following signature:
```ts
function useId(prefix?: string, providedId?: string): string 
```
When calling `useId()` without a prefix the hook returns a value like `"undefined123"`. This is because `prefix` is always concatenated into the returned id string with
```ts
`${prefix}${++contextValue.current}`
```
[Example Codesandbox](https://codesandbox.io/s/useid-undefined-prefix-ftvzlt?file=/src/App.js)
The signature remains the same (no API changes) but internally the hook now checks `prefix` and only concatenates it into the returned id when it is truthy. Now when calling `useId()` without a prefix the hook returns values like `"123"`.

Ignore prefix in useId() when it is falsey

---

change/@fluentui-react-ad3a0e4f-24c0-4734-a881-d47ce24dea8e.json
packages/react/src/components/Calendar/CalendarPicker/CalendarPicker.styles.ts

Fixes #21892
The month on the left is text (February 2022), but the year on the right is a button (2022). The color for that text is passed down from their parent, so custom themes work on the month text, but don't get inherited by the button.
Adding color: inherited to the button is the simplest change to properly support themes.
Before:
After:

Calendar: Fix 'year' button color when using dark themes

---

change/@fluentui-web-components-94e57592-580c-407b-ab70-e32bd7604171.json
packages/web-components/docs/api-report.md
packages/web-components/package.json
packages/web-components/src/combobox/index.ts
yarn.lock

The package dependencies in `@fluentui/web-components` are out of date. Additionally, the `<fluent-combobox>` component is missing the `delegatesFocus` configuration.
* Updates `@microsoft/fast-element` to `^1.7.0`
* Updates `@microsoft/fast-foundation` to `^2.33.6`
* Updates `@microsoft/fast-colors` to `^5.1.5`
* Updates `@microsoft/fast-web-utilities` to `^5.1.0`
* Restores missing `delegatesFocus` property configuration for `<fluent-combobox>`

Update package dependencies in web-components

---

change/@fluentui-react-842cfe69-2477-474b-a9cd-88e0930dc6ea.json
change/@fluentui-react-hooks-7b9d0375-f811-4b85-9b1d-0762b9aadd12.json
change/@fluentui-utilities-75f44cef-664f-42ec-bbe0-a6cc7ce5bf75.json
packages/react-hooks/README.md
packages/react-hooks/etc/react-hooks.api.md
packages/react-hooks/src/index.ts
packages/react-hooks/src/useConstCallback.ts
packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx
packages/react/src/components/FocusTrapZone/FocusTrapZone.tsx
packages/react/src/components/Image/Image.base.tsx
packages/react/src/components/KeytipData/useKeytipData.ts
packages/react/src/components/Layer/Layer.base.tsx
packages/react/src/components/Layer/LayerHost.tsx
packages/react/src/components/TextField/MaskedTextField/MaskedTextField.tsx
packages/react/src/utilities/useOverflow.ts
packages/utilities/etc/utilities.api.md
packages/utilities/src/index.ts
packages/utilities/src/useIsomorphicLayoutEffect.ts

Some v8 components use `useLayoutEffect`, causing warnings in SSR.
Introduce `useIsomorphicLayoutEffect` similar to v9, and replace all `useLayoutEffect` usage. `useIsomorphicLayoutEffect` calls `useEffect` (no-op) on the server and `useLayoutEffect` on the client. The implementation had to go in `@fluentui/utilities` instead of `@fluentui/react-hooks` because it relies on `_isSSR` which is intentionally not exported from utilities.
Also update some docs for the react-hooks package, and remove old `useUnmount` implementations in a couple components in favor of the react-hooks implementation.
Fixes #18916

Switch useLayoutEffect in v8 components to useIsomorphicLayoutEffect

---

azure-pipelines.release-vnext-nightly.yml

- Nightly releases currently uses the name format of `0.0.0-nightly{commitSha}{date}` which leads to disjointed looking version history names like: `0.0.0-nightlya0aef7969220220228.1`
- As discussed in the v-build sync, version history names will now follow a more readable format of `0.0.0-nightly-{year}{month}{day}-{hour}{minute}` which should lead to outputs like `0.0.0-nightly-20220228-1008.1`

chore: Update react-components nightly release name format

---

change/@fluentui-react-e2d6e05f-30c2-46fb-862b-4842bbe7a6d3.json
packages/react/src/common/testUtilities.ts
packages/react/src/components/Panel/Panel.base.tsx
packages/react/src/components/Panel/Panel.test.tsx

Currently, when `isHiddenOnDismiss` is passed in as a prop to `Panel`, `aria-hidden` is set on the root `div` and passed down to the child nodes (due to setting `enableAriaHiddenSiblings` on the `Popup`). This causes screen readers to read a blank screen when the Panel is closed.
Set `enableAriaHiddenSiblings` to false if the panel is not open. When the panel is closed with `isHiddenOnDismiss` passed in, `aria-hidden` is not set, allowing the screen reader to register the component
Fixes #21843

Panel: Only hide siblings when open

---

change/@fluentui-react-33dc3612-9a0f-4e5a-9ba5-d14a21df9855.json
packages/react/src/components/ResizeGroup/ResizeGroup.base.tsx

Fixes #21888
scrollWidth and getBoundingClientRect have different behaviors when measuring scaled content. 
https://codepen.io/micahgodbolt/pen/dyZgLeK?editors=1111
scrollWidth does not account for css scale, while bounding rect does.
getNextState was being called with content measured by getBoundingClientRect  and hidden content measured by scrollWidth, causing it to break.
This PR changes the 'hidden' content to be measured by getBoundingClientRect so that both measurements capture the calculated value of the content.

Resizegroup support CSS scaled content

---

packages/react-examples/src/react/ContextualMenu/ContextualMenu.Icon.Example.tsx

As noted in #21804, if no contextual menu items have `iconProps`, the control will not think there are any icons. This can easily be solved by passing in an empty `iconProps` object. The alternative would be to assume that any contexual menu with an item containing an `onRenderIcon`, actually did have icons (and made space for them). This feels like it'd have a high change of regression for an edge case that can easily be avoided. 
I've updated the example here to point users in the right direction, that even if there's an `onRenderIcon`, you should also include `iconProps`.
I would add a comment there, but `iconProps` isn't REQUIRED in this case, and I wouldn't want people they think they always needed to add them.

ContextualMenu: add empty iconProps to onRenderIcon example 

---

packages/react-checkbox/src/Checkbox.stories.tsx
packages/react-radio/src/stories/RadioGroup.stories.tsx
packages/react-tabs/src/stories/TabList.stories.tsx

Some components that are still under the `unstable` path in `@fluentui/react-components` had their stories under the `Components` section in storybook. This PR fixes this by moving these stories under the `Preview Components` section under which they should be going.

Moving preview components misplaced stories under correct section in storybook

---

change/@fluentui-react-1e10d5c9-bb3c-4095-b830-fc297028d7e6.json
packages/react/src/components/pickers/Suggestions/Suggestions.tsx

fixes #21912
`loadText` was being passed into a "label" span, but since there is no focusable element, the label was not being announced. Spinner takes in an `ariaLabel` prop which, if provided, renders an `aria-live`, visually hidden message.
This PR passes the `loadText` into the `ariaLabel` as well as the `label`. 
One other option would be to extend the `pickerSuggestionsProps` to allow for explicit `loadTextAriaLabel` or something, but this should probably be the default behavior, and would mean adding `searchTextAriaLabel` as well.

Pickers: Spinner has aria label properly applied

---

packages/react/src/components/Slider/Slider.test.tsx
packages/react/src/components/Slider/__snapshots__/Slider.test.tsx.snap

- v8 `Slider` tests don't use testing-library
- Convert Slider to fully use testing-library
part of #21663

Slider: convert tests to use testing-library

---

change/@fluentui-react-popover-449d9645-0e53-43c9-9a91-0ce5bc4e5fd1.json
packages/react-popover/etc/react-popover.api.md
packages/react-popover/src/common/mockUsePopoverContext.ts
packages/react-popover/src/components/Popover/Popover.types.ts
packages/react-popover/src/components/Popover/renderPopover.tsx
packages/react-popover/src/components/Popover/usePopover.ts
packages/react-popover/src/components/PopoverSurface/PopoverSurface.test.tsx
packages/react-popover/src/components/PopoverSurface/PopoverSurface.types.ts
packages/react-popover/src/components/PopoverSurface/renderPopoverSurface.tsx
packages/react-popover/src/components/PopoverSurface/usePopoverSurface.ts
packages/react-popover/src/components/PopoverTrigger/usePopoverTrigger.ts
packages/react-popover/src/popoverContext.ts

Refactor `Popover` to render  `PopoverSurface` based on the `open` value similar to `Menu`. This is due to a limitation with context-selectors: dai-shi/use-context-selector#69
It's not possible to get a ref for `PopoverSurface` or any content within `PopoverSurface` in an effect.
It's possible to get a ref for `PopoverSurface` or any content within `PopoverSurface` in an effect.
Adds a new `toggleOpen` callback to context to avoid drilling down `open` value.

refactor: PopoverSurface should be rendered from the Popover component

---

change/@fluentui-react-switch-582d3a8b-9cf7-42f4-b32c-0b5fb3e8f14b.json
change/@fluentui-react-utilities-d4dc0a30-cae7-4596-9a5c-e72b444fe765.json
packages/react-switch/etc/react-switch.api.md
packages/react-switch/src/components/Switch/useSwitchStyles.ts
packages/react-utilities/etc/react-utilities.api.md
packages/react-utilities/src/compose/types.ts

This PR adds a `SlotClassNames` helper type, as specified in RFC #21206, under `@fluentui/react-utilities` to help correctly define the slot class names object for our components, ensuring that all slots have a corresponding class name. This PR also updates the `switchClassNames` object under `@fluentui/react-switch` to use this new helper type.
Fixes part of #21847.

react-utilities: Adding helper type to define slot class names

---

change/@fluentui-react-7a038fb1-c2d9-46cf-a15c-ccff8f64d11d.json
packages/react/src/components/ContextualMenu/ContextualMenu.types.ts

fixes #21804
Adding a note to the onRenderIcon function that at least one of the items needs iconProps in order for onRenderIcon to be called.

Update onRenderIcon docs to warn of render condition

---

change/@fluentui-keyboard-keys-e85295cb-376c-4067-8d3b-79dfd84ac1e6.json
packages/keyboard-keys/package.json

A recent partner build error led to the conclusion that we are missing a `tslib` dependency in the `@fluentui/keyboard-keys` package. This PR aims to fix that by adding the missing dependency.

keyboard-keys: Adding missing tslib dependency

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-bindings/package.json
packages/fluentui/react-component-nesting-registry/package.json
packages/fluentui/react-icons-northstar/package.json
packages/fluentui/react-northstar-emotion-renderer/package.json
packages/fluentui/react-northstar-fela-renderer/package.json
packages/fluentui/react-northstar-prototypes/package.json
packages/fluentui/react-northstar-styles-renderer/package.json
packages/fluentui/react-northstar/package.json
packages/fluentui/react-telemetry/package.json

Add React 17 to peer dependencies for `@fluentui/react-northstar` and its subpackages.
Fixes #21082

chore: Support React 17 in peer deps in N*

---

change/@fluentui-react-a3741b7d-6622-4f14-a2a7-c946fad04f38.json
packages/react/etc/react.api.md
packages/react/src/components/ProgressIndicator/ProgressIndicator.base.tsx
packages/react/src/components/ProgressIndicator/ProgressIndicator.test.tsx
packages/react/src/components/ProgressIndicator/ProgressIndicator.types.ts
packages/react/src/components/ProgressIndicator/__snapshots__/ProgressIndicator.test.tsx.snap

Fixes #18351
Adds an `ariaLabel` prop to ProgressIndicator so authors can add an accessible name even if there is no visible text.

fix(Progressbar): add ariaLabel prop

---

change/@fluentui-react-components-9e580541-4783-4fe8-9998-75fc823712e5.json
packages/react-components/package.json

The `/unstable` import for `react-components` package was missing in the exports map.
Adding it for Webpack 5 to be happier and for supported imports to be explicit. :)
Fixes #21953

Adding "/unstable" export to @fluentui/react-components

---

change/@fluentui-react-c425b099-b5fd-43fa-a973-4c7474177a34.json
packages/react/src/components/Button/BaseButton.tsx

When opening a menu, focus always goes to the first element.  The prop `shouldFocusOnContainer` should be the method for overriding this.  However, the calls to _onToggleMenu hardcode `false` instead of respecting the props.
The props are respected when doing _onToggleMenu allowing a consumer to override the default focus behavior.
This shouldn't have any impact on the previous issue that was fixed since the prop is false by default.
https://github.com/microsoft/fluentui/pull/20601

Respect shouldFocusOnContainer prop when opening a menu via mouse click

---

apps/vr-tests-react-components/src/stories/Menu.stories.tsx
change/@fluentui-react-menu-1918e3b8-f0c6-43a7-982c-f778eef4ecf1.json
packages/react-menu/src/components/MenuItem/useMenuItemStyles.ts

The menu item does not align the icon slot and submenuIndicator slot content with the menu item text.
> These were created by modifying the associated stories to use the v8 icons and spans with plain text as the icon or submenuIndicator.
Menu item aligns icon and submenuIndicator slot content using flex just like button does.
This was discovered as part of writing the ContextualMenuButton shim for the v8 -> v9 upgrade.

fix(Menu): fix icon and submenuIndicator alignment for non-v9 icons

---

packages/react/src/components/Checkbox/Checkbox.test.tsx
packages/react/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap

- v8 `Checkbox` tests don't use testing-library
- Convert `Checkbox` to fully use testing-library
part of #21663

Checkbox (v8): convert tests to use testing-library

---

packages/react/src/components/Button/Button.test.tsx
packages/react/src/components/Button/__snapshots__/Button.test.tsx.snap

- v8 `Button` tests don't use testing-library
- Convert `Button` to fully use testing-library
part of #21663

Button (v8): convert tests to use testing-library

---

change/@fluentui-react-components-fd2612fd-ab61-44c8-89bf-0b66795fa1df.json
packages/react-components/package.json
packages/react-components/src/unstable/index.ts
packages/react-switch/src/stories/Switch.stories.tsx

This PR adds the `Switch` component to the `unstable` folder of the `@fluentui/react-components` package.
Fixes part of #21739

Adding Switch to @fluentui/react-components/unstable

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx

Fix focus indicator appearance when highlightFirstItemOnOpen is true while accessing from keyboard.
When you open dropdown for the first time with 'highlightFirstItemOnOpen', the first item is highlighted but missing focus indicator. 
From keyboard:
From keyboard:

fix focus indicator appearance when highlightFirstItemOnOpen is true

---

change/@fluentui-react-602dd506-4c38-43b3-97cc-323e2d5da3e4.json
packages/react/etc/react.api.md
packages/react/src/components/Layer/Layer.base.tsx
packages/react/src/components/Layer/Layer.notification.ts
packages/react/src/components/Layer/LayerHost.tsx
packages/react/src/components/Layer/LayerHost.types.ts

The `Layer` component defaults to creating an element at the end of the current document.
If ` hostId` is provided, `Layer` simply uses a query selector to find an element in the current document matching the `hostId`.
Even if the host app provides a `LayerHost` React component, it's just a glorified way to render a `<div>` with an `id`. The intent of `LayerHost` was to allow 'projection' of `Layer` into other areas, but the simple query selector is limiting.
This PR augments `LayerHost` and `Layer` so that `Layer` first tries to resolve an `ILayerHost` with a matching `hostId`, and use the provided `elementRef`. This allows `LayerHost` to be rendered into another `window`, and have the correct element passed to `Layer`. The logic falls back to the old query selector if `hostId` cannot be …

Ensure Layer uses the specific element for LayerHost, for advanced projection scenarios

---

change/@fluentui-theme-abd89837-a058-4b70-9f37-7ee3d73aca2b.json
packages/theme/package.json

It turns out some repos are consuming the v8 `@fluentui/theme` through v7 `@uifabric/styling package` references via pinning to disregard semver.
This is a problem in itself, but was working until exports maps were introduced. When @uifabric/styling imports createTheme, it gets it from `@fluentui/theme/lib/createTheme` which now breaks in a webpack 5 environment. v8 packages do not use this theme, so separately we need to remove v7, but to unblock the partial upgrade in 1JS, we need to add this entry.

@fluentui/theme missing a ./lib/createTheme export

---

change/@fluentui-utilities-cc0c03e5-dd13-492f-aeb8-a4a5db4f7097.json
packages/utilities/etc/utilities.api.md
packages/utilities/src/selection/Selection.test.ts
packages/utilities/src/selection/Selection.ts
packages/utilities/src/selection/Selection.types.ts

The `Selection` model component is critical to the functionality of `DetailsList`, `TilesList`, and other list-rendering components. Most of the time, lists are rendered first, with no items selected, and then a user performs actions to select items (usually facilitated by `SelectionZone`). In code, a host component can create a `Selection` instance, subscribe to it, and then pass it into `DetailsList` or `TilesList`, in order to receive notifications when the selection changes.
One challenge is that `DetailsList` and `TilesList` are responsible for assigning the final `items` array to `Selection`: the host does not provide it upfront. Sometimes, the caller needs to be able to set some items as selected *upfront*; however, `Selection` does not allow items which are not part of the current …

Improve Selection with more micro-management capabilities

---

packages/react-tooltip/src/stories/Tooltip.stories.tsx
packages/react-tooltip/src/stories/TooltipStyled.stories.tsx

fixes #21997
Add a simple demo showing how to style a tooltip in v9. This came about after customer was having trouble applying styles to the tooltip itself.

Add a styled demo to tooltip v9

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/themes/teams-high-contrast/components/Tooltip/tooltipContentVariables.ts

Fix `TooltipContent` colors for HC theme
Before:
After:

fix: Tooltip content color for HC theme

---

apps/perf-test-react-components/tasks/perf-test.ts

Followup to https://github.com/microsoft/fluentui/pull/21873#discussion_r818065918.
Now that `perf-test-react-components` is uploaded to the Deployed [site ](https://fluentuipr.z22.web.core.windows.net/heads/master/) for master, this PR updates the new v9 perf test package to point to that url.

perf-test v9: update URL to point to newly dedicated deploy site page specifically for package

---

change/@fluentui-react-2bbe9af4-aa2b-4cc4-b198-009db94dd912.json
packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx

#20601 fixed an accessibility issue regarding the initial focus when opening `ContextualMenus`. While doing this, a parameter was removed from the internal `openSubMenu` function. However, the calls for this function are still passing that third now unused parameter.
This PR fixes this issue by removing that third parameter from all the `openSubMenu` function calls in `ContextualMenu`.

ContextualMenu: Removing unused paramater in openSubMenu calls

---

change/@fluentui-theme-12e3f5b4-2c39-4451-9e47-b81fc7cacb6b.json
packages/theme/package.json

Found 2 more imports from @uifabric/fluent-theme which won't work with the latest @fluentui/theme due to missing exports.

Adding 2 more exports to @fluentui/theme for v7 backwards compatibility purposes.

---

README.md

We mention how we leverage GitHub Releases and point the user to the Releases page, but those have been halted.
We now point the users to the individual CHANGELOG.md files to consult changes as these will always be up to date.
Couldn't find anything related to this in the wiki, so no wiki pages need to be affected.

chore: Clarify info regarding releases/changelogs on our README

---

change/@fluentui-eslint-plugin-c78892bf-1aff-4715-aa5c-a43a942b4184.json
packages/eslint-plugin/src/configs/react.js
packages/eslint-plugin/src/utils/configHelpers.js

- eslint contains unused logic
- reverts https://github.com/microsoft/fluentui/pull/20466 as that functionality is not needed/used after vNext migrated to solution ts config
- simplified args handling in `getTypeInfoRuleOverrides`

revert: ESlint - support tsconfig excluded files

---

change/@fluentui-merge-styles-0e52ea03-88a2-4689-af55-8cb2b0d97381.json
change/@fluentui-utilities-2f935273-5b27-4eca-9620-19962f00e63a.json
packages/merge-styles/package.json
packages/utilities/package.json

In Teams we're trying to update to v8, but a number of 1js packages have deep imports unsupported by the latest v8. To unblock the upgrade, adding a minimum number exports required to unhitch a complex upgrade order.

Adding more exports to utilities/merge-styles to unhitch 1js upgrades from fluent upgrades.

---

change/@fluentui-react-tabster-4355ad2a-cb2d-4180-b282-3d54ee137d0f.json
packages/react-tabster/src/hooks/useFocusIndicatorStyle.ts

This PR fixes styles in `getFocusOutlineStyles()` function. Check comments on files for more details.

fix(react-tabster): fix styles in getFocusOutlineStyles()

---

package.json

- `yarn change` invokes beacbhall CLI.
- behind the scenes beachball creates change file(s), stages those and magically commits behind the scenes
This leads to following unexpected behaviours:
- if you have something staged that would be commited as well 🚨
- adds manual work on contributor side as in some workflows, one needs to git reset and tweak the change file message manually
- `yarn change` invokes beachball CLI with `--no-commit`
- change file(s) is generated, nothing is staged/commited behind the scenes

chore: disable beachball autocommit on change file generation

---

change/@fluentui-date-time-utilities-2308a8ce-79bb-4197-b0c0-6a29a8889460.json
packages/date-time-utilities/package.json

Fixes exports to support older version of fluent before [this commit](https://github.com/microsoft/fluentui/commit/f2f1c0ea948cc3517eeb442c05433eb0918def29) that had their date-time-utilities upgraded while the version of fluent using deep imports remained the same.
This is in association with other compat export add backs in [PR 22062](https://github.com/microsoft/fluentui/pull/22062)
This adds back the exports necessary to allow the scenario to work.

Add compat exports to date-time-utilities

---

.storybook/docs-root.css

This fixes an issue where ordered lists ol did not have numbering.  The storybook level ul rules were not scoped properly which this fixes.
One small tweak is the the light gray color of the ul bullets was too light when applied to the ol numbers, so darkened it just slightly.  Not a noticable color change from the desired look of storybook content.

Fixed ul and ol styles to allow numbering of ol

---

change/@fluentui-react-docsite-components-c92fcf60-45e3-46e8-8999-a621bc42b86b.json
packages/react-docsite-components/src/components/Markdown/Markdown.tsx
packages/react-docsite-components/src/components/Markdown/Markdown.types.ts

Markdown components on legacy doc sites fail to render after updating the `markdown-to-jsx` version in #21780.
Turns out this is because `markdown-to-jsx` declares in its types that it uses a default export, but its cjs `main` file actually assigns to `module.exports`. This would work fine with `esModuleInterop`, but we don't use that.
Import the module with `import *`. The markdown component is the default export if it exists, or the whole module if not (and cast to set the appropriate type).
I'll also make a PR with `markdown-to-jsx` to fix the root cause, but this will work around the issue for now.

Fix markdown-to-jsx import

---

apps/public-docsite-resources/config/pre-copy.json
apps/public-docsite-resources/webpack.serve.config.js
apps/theming-designer/index.html
apps/theming-designer/webpack.config.js
apps/theming-designer/webpack.serve.config.js
change/@fluentui-react-button-c43ab8d5-656a-4430-844b-fae8a2a58c0c.json
change/@fluentui-react-charting-e51a553b-83bf-43dc-8e75-a347735e28cb.json
change/@fluentui-react-docsite-components-7d1e02be-24ff-4e39-a7a0-887fa75942d5.json
change/@fluentui-react-experiments-fc9020db-737d-4f3a-9094-00c0db8e292a.json
change/@fluentui-react-monaco-editor-488835a4-0a19-4632-81cc-6ea2640a549f.json
packages/react-button/config/pre-copy.json
packages/react-charting/config/pre-copy.json
packages/react-docsite-components/config/pre-copy.json
packages/react-docsite-components/index.html
packages/react-docsite-components/src/components/CodepenComponent/CodepenComponent.tsx
packages/react-docsite-components/webpack.serve.config.js
packages/react-experiments/config/pre-copy.json
packages/react-monaco-editor/config/pre-copy.json
packages/react-monaco-editor/index.html
packages/react-monaco-editor/webpack.serve.config.js
scripts/webpack/webpack-resources.js

In #21769 I updated our React version to 16.14, but I forgot to update the version in some CDN URLs in legacy demo apps. ~~This made them fail to load.~~ EDIT: this was wrong, the actual reason the demo apps were failing to load was the update of markdown-to-jsx in an earlier PR (and fixed in #22076)--but we should still update the demo apps' react version.
Switch to including React in the legacy demo app bundles (instead of having it as an external loaded from a CDN, or from `dist` in local versions) to ensure that the version is always the same as the local version in the repo. This may not be a realistic setup for consumers and is a bit worse for build perf, but that's less of a concern since the legacy demo apps are more or less in maintenance mode now, and it's one less thing to …

Update legacy demo apps to use bundled React

---

apps/vr-tests-react-components/package.json
apps/vr-tests/package.json
yarn.lock

screener-storybook was using an old version of requestretry. After pointing this out, the team bumped the dep, and released a new version. Consuming it here.

upgrade screener-storybook

---

change/@fluentui-react-fcdb408e-5bd1-48a1-b5c6-3a9e372543bc.json
packages/react/src/components/Pivot/Pivot.base.tsx

Pivot is not applying any role to the items on overflow, which means they're inside of a `menu` but have a role of `tab` as this is applied by default.
Items sent to the overflow are applied the role of `menuitem`.
Fixes #20661

fix(react): Apply `menuitem` role to overflow items in Pivot

---

change/@fluentui-react-button-952e8e60-c355-4e57-866d-03d10d70d8d4.json
packages/react-button/src/components/CompoundButton/CompoundButton.test.tsx
packages/react-button/src/components/CompoundButton/useCompoundButton.ts

It was found that `CompoundButton` would render as `iconOnly` even if `secondaryContent` was being provided as long as `children` was not. This happened because the `iconOnly` calculation was only reusing the one in `useButton`.
This PR fixes the issue by doing the correct calculation of `iconOnly` in `useCompoundButton` and adds a test so this doesn't happen again.

CompoundButton: Fixing bug where component was iconOnly even when secondaryContent was being provided

---

.github/CODEOWNERS

Removing `dzearing` as an owner from `@fluentui/react-button` since he is no longer involved in its development.

CODEOWNERS: Removing dzearing as owner from @fluentui/react-button

---

change/@fluentui-react-b72ecaba-1b37-4eda-a00c-9501cc53b693.json
packages/react/src/components/ComboBox/ComboBox.test.tsx
packages/react/src/components/ComboBox/ComboBox.tsx
packages/react/src/components/ComboBox/ComboBox.types.ts

Right now, selecting an option in a `Combobox` or writing down an option if freeform is allowed will send `undefined` as the value of the `onChange` callback. Furthermore, in the case that state is changed while typing on a freeform `Combobox`, `onPendingValueChanged` is being called twice, first with the correct value and then with `undefined`.
This PR fixes some of these issues by always sending the correct value to the `onChange` and `onPendingValueChanged` callbacks. This PR does not fix the issue of `onPendingValueChanged` being called twice.
See [this codepen](https://codepen.io/khmakoto/pen/ZEvYqBL?editors=0010) for how the previous behavior looks like.

Combobox: Adding fixes for onChange and onPendingValueChanged callbacks

---

change/@fluentui-react-checkbox-0ec4c118-8da5-4273-8d77-d53fee032706.json
packages/react-checkbox/src/index.ts

`react-checkbox` has `export * from ...` in `src/index.ts`.
`react-checkbox` has explicitly named exports in `src/index.ts`.
#22099

Remove star exports from react-checkbox

---

change/@fluentui-react-button-a9f35e7a-9acc-43aa-8ffe-ce04b66a9b55.json
packages/react-button/src/index.ts

`react-button` has `export * from ...` in `src/index.ts`.
`react-button` has explicitly named exports in `src/index.ts`.
#22099

Removing star exports from @fluentui/react-button

---

change/@fluentui-react-card-b5427f10-a658-4cde-b635-404c560a4bed.json
change/@fluentui-react-image-ddbe4c9f-a8fe-41a8-92f2-c99744d85d5e.json
change/@fluentui-react-text-e6ab4ed2-0b42-48c8-8a28-3947b6d76b5b.json
packages/react-card/src/index.ts
packages/react-dialog/src/index.ts
packages/react-image/src/index.ts
packages/react-storybook/src/index.ts
packages/react-text/src/index.ts

Fixes Partially https://github.com/microsoft/fluentui/issues/22099
note that because following PR, there was lot of deprecated API introduced https://github.com/microsoft/fluentui/pull/21960#issuecomment-1068991851.
This is the reason why our barrel files have `deprecation` rule being turned off  in this PR.
**Q:** why didn't you turn that rule off in our local eslint configs?
**A:** because that would trigger this rule during pre-commit phase which is expensive. we have magic in our eslint-config plugin that turns type-aware checks off when run via lint-staged. I cannot easily reproduce the same behaviour per package - needs better API design

refactor: autofix no export star at index file for cxe-prg packages

---

change/@fluentui-react-button-633a115e-13c7-4d93-b2f1-a76ce33e883f.json
packages/react-button/src/index.ts

A previous PR merged with an old build that is causing master to fail because the `lint` step is erroring on deprecated `[component]ClassName` objects being exported from `@fluentui/react-button`. This PR fixes the issue by disabling the rule for those exports since they are still needed.

Disabling lint rule for deprecated [component]ClassName exports

---

change/@fluentui-react-radio-a06cb1db-d673-4da6-b4c3-444510433f50.json
packages/react-radio/etc/react-radio.api.md
packages/react-radio/src/index.ts

`react-radio` has `export * from ...` in `src/index.ts`.
`react-radio` has explicitly named exports in `src/index.ts`.
#22099

Remove star exports from react-radio

---

change/@fluentui-react-checkbox-5f3195e1-e873-494f-b453-bf74eb55dea8.json
packages/react-checkbox/etc/react-checkbox.api.md
packages/react-checkbox/src/components/Checkbox/Checkbox.types.ts

`Checkbox`'s `onChange` event type is `React.FormEvent`.
`Checkbox`'s `onChange` event type is `React.ChangeEvent`.
#21931
#21809

Align Checkbox API with other input controls

---

change/@fluentui-react-divider-a296016c-a48d-4eee-a35f-e3f92dc129de.json
packages/react-divider/src/index.ts

`react-divider` has `export * from ...` in `src/index.ts`.
`react-divider` has explicitly named exports in `src/index.ts`.
#22099

Removing star exports from @fluentui/react-divider

---

packages/react-spinbutton/src/index.ts

`react-spinbutton` has `export * from ...` in `src/index.ts`.
`react-spinbutton` has explicitly named exports in `src/index.ts`.
#22099

Remove star exports from react-spinbutton

---

change/@fluentui-react-label-ef9081a1-1ee4-4ee1-b58b-12a01b3e2dbe.json
packages/react-label/src/index.ts

`react-label` has `export * from ...` in `src/index.ts`.
`react-label` has explicitly named exports in `src/index.ts`.
#22099

Removing star exports from @fluentui/react-label

---

change/@fluentui-react-input-0394afa3-93d8-4114-8186-351ee5141788.json
packages/react-input/src/index.ts

`react-input` has `export * from ...` in `src/index.ts`.
`react-input` has explicitly named exports in `src/index.ts`.
#22099

Removing star exports from @fluentui/react-input

---

change/@fluentui-react-switch-79de723f-654c-4eba-adc9-b31e8ba303ef.json
packages/react-switch/src/index.ts

`react-switch` has `export * from ...` in `src/index.ts`.
`react-switch` has explicitly named exports in `src/index.ts`.
#22099

Removing star exports from @fluentui/react-switch

---

change/@fluentui-react-button-94a03308-210e-4d14-a9bd-a33e4aca69ae.json
packages/react-button/etc/react-button.api.md
packages/react-button/src/components/Button/Button.types.ts
packages/react-button/src/components/SplitButton/SplitButton.types.ts

The `root` slot of `Button` components is nullable, which should not be the case for any `root` slots.
This PR fixes the issue by making the `root` slot of all `Button` components non-nullable.
Fixes part of #21926

Button components: Making root a non-nullable slot

---

change/@fluentui-react-button-83582077-8826-47dd-89e1-58494886e86b.json
packages/react-button/src/components/Button/Button.types.ts
packages/react-button/src/components/Button/useButton.ts
packages/react-button/src/components/Button/useButtonStyles.ts
packages/react-button/src/components/SplitButton/useSplitButton.ts
packages/react-button/src/components/SplitButton/useSplitButtonStyles.ts

This PR deprecates the `block` prop in the `Button` component to better adhere to our consistent API across form-related components.
Fixes part of #21926

Button: Deprecating block prop

---

change/@fluentui-react-slider-74f2e75b-fa8d-4b9d-8c1a-2e6f983e72f7.json
packages/react-slider/src/index.ts

`react-slider` has `export * from ...` in `src/index.ts`.
`react-slider` has explicitly named exports in `src/index.ts`.
#22099

Removing star exports from @fluentui/react-slider

---

change/@fluentui-react-tabs-798b8aec-7f35-4265-9215-435d7b834d9a.json
packages/react-tabs/src/index.ts

`react-tabs` has `export * from ...` in `src/index.ts`.
`react-tabs` has explicitly named exports in `src/index.ts`.
#22099

Removing star exports from @fluentui/react-tabs

---

change/@fluentui-react-tooltip-2fe5f0f6-e37a-4bd0-b550-6fcfe8a6ccb1.json
packages/react-tooltip/src/index.ts

`react-tooltip` has `export * from ...` in `src/index.ts`.
`react-tooltip` has explicitly named exports in `src/index.ts`.
#22099

Removing star exports from @fluentui/react-tooltip

---

change/@fluentui-react-60213acf-3761-4496-955f-df9a1876d78a.json
packages/react/package.json

This PR fixes an issue that resulted from the inclusion of export maps in the `@fluentui/react` package that made it impossible to import the `getStyles` functions from those components. After internal discussion we agreed to include the deep import style files in the export maps for the `@fluentui/react` package to solve the issue, which is what is being done in this PR.
Fixes #22126

@fluentui/react: Adding style files to export maps

---

common/changes/office-ui-fabric-react/hotfix_03-hotfix-5.135.6_2022-03-19-06-33.json
packages/office-ui-fabric-react/src/components/Panel/Panel.tsx

Port #14945 from office-ui-fabric-react_v5.79.1 to hotfix/5.135.6
For #14945: Port #8842 to add tooltip for cancel button in Panel of office-ui-fabric-react/5.79.1

Port #14945 (Port #8842 to add tooltip for cancel button in Panel) from office-ui-fabric-react_v5.79.1 to hotfix/5.135.6

---

common/changes/office-ui-fabric-react/hotfix_04-hotfix-5.135.6_2022-03-19-06-51.json
packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardActivity.tsx
packages/office-ui-fabric-react/src/components/DocumentCard/__snapshots__/DocumentCard.test.tsx.snap

Port #14932 from office-ui-fabric-react_v5.79.1 to hotfix/5.135.6
For #14932, Port #6836 to fix typo in role attribute in DocumentCardActivity of office-ui-fabric-react/5.79.1

Port #14932 (Port #6836 to fix typo in role attribute in DocumentCardActivity) from office-ui-fabric-react_v5.79.1 to hotfix/5.135.6

---

common/changes/office-ui-fabric-react/hotfix_07-hotfix-5.135.6_2022-03-19-12-06.json
packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
packages/office-ui-fabric-react/src/components/pickers/__snapshots__/BasePicker.test.tsx.snap

Port #18078 from office-ui-fabric-react_v5.79.1 to hotfix/5.135.6
For #18078, Port #7048 to remove role 'list' from the base picker text element in BasePicker

Port #18078 (Port #7048 to remove role 'list' from the base picker text element in BasePicker) from office-ui-fabric-react_v5.79.1 to hotfix/5.135.6

---

common/changes/office-ui-fabric-react/hotfix_09-hotfix-5.135.6_2022-03-19-14-26.json
packages/office-ui-fabric-react/src/components/Nav/Nav.base.tsx
packages/office-ui-fabric-react/src/components/Nav/Nav.types.ts

Port #19707 from office-ui-fabric-react_v5.79.1 to hotfix/5.135.6
For #19707, Port #9163 to update expand button's aria label to include link name in Nav

Port #19707 (Port #9163 to update expand button's aria label to include link name in Nav) from office-ui-fabric-react_v5.79.1 to hotfix/5.135.6

---

change/@fluentui-react-avatar-8816dd26-3129-4deb-85b1-e7ec3a402bcd.json
packages/react-avatar/src/components/Avatar/useAvatarStyles.ts

The `Avatar` component had a different style for sizes 20 and 24 when compared to the design spec. This PR updates the component so that it matches the design specification of having font weight be `semibold` for sizes 20 and 24 instead of `regular`.

Avatar: Fix style for sizes 20 and 24 to have semibold fontWeight instead of regular

---

change/@fluentui-react-portal-0160db08-c837-47b2-bcc0-2016365a121c.json
packages/react-portal/src/components/Portal/Portal.types.ts
packages/react-portal/src/components/Portal/usePortalMountNode.ts

`mountNode` accepts only `HTMLDivElement`
`mountNode` accepts only `HTMLElement`

fix(Portal): update `mountNode` types to accept HTMLElement

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx
packages/fluentui/react-northstar/test/specs/components/Dropdown/Dropdown-test.tsx

Fix for Bug #21887 aria-labelledby on Dropdown is set to Dropdown itself if no id provided
The solution has been tested with the keyboard, JAWS, and NVDA.
Currently, the aria-labelledby is being passed down to the trigger button along with the id label of the trigger button. It's causing issues for some screen readers including Mac's VoiceOver.
https://codesandbox.io/s/tv5h0?module=/example.js
e.g.
`<button role="button" data-aa-class="Button" class="ui-button ui-dropdown__trigger-button" id="dropdown-trigger-button-1" type="button" aria-haspopup="true" data-toggle="true" aria-labelledby="dropdown-trigger-button-1"><span dir="auto" class="ui-button__content jg ji jj bq jk jl">Select your hero</span></button>`
If no aria-labelledby prop is provided, then it will not be …

Fix: trigger button id should no longer be used as aria label

---

packages/react-examples/src/react/Callout/Callout.Status.Example.tsx

Example has `role=status` set, and NVDA does not read dynamic `role="status"` live regions. If a team wishes the message to be read reliably, they can use `role="alert"` instead of `role="status"` in their code.
The Callout example has been updated to have `role=alert`
Fixes #

Set role to alert for Callout example so NVDA announces properly

---

packages/react-examples/src/react/Callout/Callout.Status.Example.tsx

Narrator announces elements in a live region twice, because `aria-live="assertive"` is set
Removes the `aria-live="assertive"` prop and Narrator only announces once
Fixes #

Remove aria-live prop to prevent Narrator from reading twice

---

change/@fluentui-react-56215fe1-3be0-41dd-b5fd-34e5311cb783.json
packages/react/src/components/Rating/Rating.base.tsx

When a Rating is rendered by itself (not on a page with another component that enables focus rects), it doesn't have focus outlines on keyboard interaction.
Add focus outlines to Rating itself.
Fixes [13610](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/13610)

Rating: add focus outlines

---

.github/CODEOWNERS
scripts/create-package/plopfile.ts
tools/generators/add-codeowners.spec.ts
tools/generators/add-codeowners.ts
tools/generators/migrate-converged-pkg/README.md
tools/generators/migrate-converged-pkg/index.spec.ts
tools/generators/migrate-converged-pkg/index.ts
tools/generators/migrate-converged-pkg/schema.json
tools/generators/migrate-converged-pkg/schema.ts
tools/utils-testing.ts
tools/utils.ts

When user bootstraps new package via `create-package` codeowner is not being enforced to be setup, which goes against our reviews/ownership process. 
- `create-package` asks user to select which team will be owning this new package
**DEMO:**
https://user-images.githubusercontent.com/1223799/159723793-d447e55c-9ccd-47cc-b287-c18c700f5dbd.mov
**How it works flow:**
```mermaid
graph TD
A[create-package] --> |select team that will own the package| B(nx migrate-converged-pkg)
B -->  |adds package root path + team to CODEOWNERS| C[DONE]
```
Fixes https://github.com/microsoft/fluentui/issues/21844
with this implemented, vNext packages missing owner can add codeowners by running
`yarn nx workspace-generator migrate-converged-pkg --name=@fluentui/react-<name> --owner=@microsoft/<team>`

feat: automate codeowner addition for new packages

---

packages/fluentui/CHANGELOG.md
packages/fluentui/accessibility/src/behaviors/Datepicker/datepickerBehavior.ts
packages/fluentui/react-northstar/src/components/Datepicker/Datepicker.tsx

Fixes: #20979
Add `aria-haspopup="true"` to `DatePicker` input when `allowManualInput` is set to false so screen reader will read it like:

fix: add aria-haspopup for datepicker

---

packages/react/src/components/Label/Label.test.tsx
packages/react/src/components/Label/__snapshots__/Label.test.tsx.snap

- v8 `Label` tests don't use testing-library
- Convert `Label` to fully use testing-library
part of #21663

Label (v8): convert tests to use testing-library

---

packages/react/src/components/Announced/Announced.test.tsx
packages/react/src/components/Announced/__snapshots__/Announced.test.tsx.snap

- v8 `Announced` tests don't use testing-library
- Convert `Announced` to fully use testing-library
part of #21663

Announced (v8): convert tests to use testing-library

---

apps/vr-tests-react-components/src/stories/Input.stories.tsx
change/@fluentui-react-input-8be942c5-d8d2-4caf-bd86-23435bba1a63.json
packages/react-input/Spec-styling.md
packages/react-input/etc/react-input.api.md
packages/react-input/src/components/Input/Input.types.ts
packages/react-input/src/components/Input/useInput.ts
packages/react-input/src/components/Input/useInputStyles.ts
packages/react-input/src/stories/Input.stories.tsx
packages/react-input/src/stories/InputAppearance.stories.tsx
packages/react-input/src/stories/InputContentBeforeAfter.stories.tsx
packages/react-input/src/stories/InputControlled.stories.tsx
packages/react-input/src/stories/InputDefault.stories.tsx
packages/react-input/src/stories/InputDisabled.stories.tsx
packages/react-input/src/stories/InputInline.stories.tsx
packages/react-input/src/stories/InputSize.stories.tsx
packages/react-input/src/stories/InputType.stories.tsx
packages/react-input/src/stories/InputUncontrolled.stories.tsx

Input does not conform to some of the newly-decided API patterns for all converged inputs.
API fixes:
- Change the root slot to `display: inline-flex`
- Remove `inline` prop
- Change `onChange`'s event type to `React.ChangeEvent` from `React.FormEvent`
Styling fixes:
- Add default font size for `> svg` in `contentBefore`/`contentAfter` so resizable SVG icons are the correct size by default
- Update styling in stories
Fixes #21927, part of #21847

Input API alignment and styling fixes

---

scripts/local-codepen.js

The `local-codepen` script (`yarn workspace @fluentui/react codepen`) prints out a script tag to put in the codepen, but it's not very obvious.
Add a big yellow box around the script tag in the log output to make it easier to find.
Also remove the react script tags from the output since this script is typically used to test a fix against an existing codepen, which will already have the react scripts.

Make local-codepen URL output easier to find

---

change/@fluentui-react-conformance-griffel-ff56e60b-7eed-4630-b33e-a69f6feaae95.json
packages/react-conformance-griffel/package.json

Every time someone bumps `react-conformance` it causes yarn.lock changes as that bump won't bump other packages that use it as dependency (react-conformance-griffel).
> **Additional Notes:**
> even if there was a depedent change type I think it won't be bumped... since we have different scopes with beachball for  v9/8 releases
Moving RC to `peerDependencies` to avoid this CI failure for good.
Fixes #

chore: move react-conformance to peerDeps to resolve dep issues when RC is bumped

---

packages/react/src/components/TextField/TextField.test.tsx
packages/react/src/components/TextField/__snapshots__/TextField.test.tsx.snap

- v8 `TextField` tests don't use testing-library
- Convert `TextField` to fully use testing-library
part of #21663

TextField (v8): convert tests to use testing-library

---

tools/generators/migrate-v8-pkg/README.md
tools/generators/migrate-v8-pkg/files/constants.ts__tmpl__
tools/generators/migrate-v8-pkg/index.spec.ts
tools/generators/migrate-v8-pkg/index.ts
tools/generators/migrate-v8-pkg/lib/utils.spec.ts
tools/generators/migrate-v8-pkg/lib/utils.ts
tools/generators/migrate-v8-pkg/schema.json
tools/generators/migrate-v8-pkg/schema.ts

As we agreed within v-build, we will not branch out vNext. Thus we need to come up with approach how to migrate vNext DX/tooling to v8. All the progress will be handled via automation. This is the 1st step.
- executed `yarn nx workspace-generator workspace-generator`
- new generator scaffold

feat(tools): bootstrap migrate-v8-pkg generator

---

change/@fluentui-azure-themes-e723c0d2-b2be-4910-97f8-61da88c187ef.json
packages/azure-themes/src/azure/Constants.ts
packages/azure-themes/src/azure/styles/ChoiceGroupOptions.styles.ts

Cherry picked from 7.0 branch #22227
Control was 20x20px
Control now 18x18, the dot inside is same as before. No color changes, so all 4 subthemes (light, dark, and 2 high contrasts) look good. 
Fixes devops # 13782375

Cherry picked from 7.0 branch: reducing ChoiceGroup radio button to 18px

---

change/@uifabric-azure-themes-7fe70699-a313-4a60-aff0-537c302a5170.json
change/@uifabric-experiments-bf027ce7-9e34-402a-a1e3-4e9ff62576ca.json
change/@uifabric-file-type-icons-9180bd66-bb22-4b1d-a062-9d0d84af155f.json
change/@uifabric-react-cards-9081cfcc-33f5-499b-9943-23b2181fed03.json
packages/azure-themes/src/azure/Constants.ts
packages/azure-themes/src/azure/styles/ChoiceGroupOptions.styles.ts

Control was 20x20px
Control now 18x18, the dot inside is same as before. No color changes, so all 4 subthemes (light, dark, and 2 high contrasts) look good. 
Fixes devops # 13782375

Azure Theme: Choice Group size fix 

---

change/@fluentui-react-1ad12aef-a8f5-4fc2-89d4-af3ffddd59ed.json
packages/react/src/components/Calendar/Calendar.base.tsx

Calendar component does not respect `isDayPickerVisible={false}` on very small screens. You can see [here](https://github.com/microsoft/fluentui/blob/3dbb57b1e6940df2d4039f61a35d961bcb8560c3/packages/react/src/components/Calendar/Calendar.base.tsx#L107) that `isDayPickerVisible` prop value is completely ignored when `getShowMonthPickerAsOverlay` function returns `true`. This wouldn't be a problem if [getShowMonthPickerAsOverlay](https://github.com/microsoft/fluentui/blob/3dbb57b1e6940df2d4039f61a35d961bcb8560c3/packages/react/src/components/Calendar/Calendar.base.tsx#L400-L403) took `isDayPickerVisible` into account.
Unless `showMonthPickerAsOverlay={true}`, the month picker is not shown as overlay in month-only mode (when `isDayPickerVisible={true}`). This can be easily verified in …

fix(react): respect isDayPickerVisible on mobile

---

scripts/prettier/prettier-helpers.js

Prettier is executed by a custom `exec-sync` wrapper that we have in the repo. `exec` seems to cause issues that `node` does not exist in path on windows.
```
Command failed: node E:\projects\fluentui\node_modules\prettier\bin-prettier.js --config E:\projects\fluentui\prettier.config.js --ignore-path "E:\projects\fluentui\.prettierignore" --write E:\projects\fluentui\packages\fluentui\add-a-feature.md
```
Now uses native `spawn` and `spawnSync` which is similar to another windows fix in #21509.

Use spawn for prettier runner for windows compat

---

packages/react-examples/src/react/Dropdown/Dropdown.SelectStyle.Example.tsx
packages/react-examples/src/react/Dropdown/Dropdown.doc.tsx
packages/react-examples/src/react/Dropdown/docs/DropdownBestPractices.md

Fixes [12917](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/12917)
Our current selected option style in Dropdown is very low contrast, but changing the visuals in v7/v8 has a high risk of breaking custom styles for partner teams.
This PR adds wording to the best practices docs about contrast-y selection styles, and adds an example with custom selected option styles.
Current selection styling:
New example:

fix(Dropdown examples): selected option custom style example, best practices wording

---

packages/react/src/components/Coachmark/Coachmark.test.tsx
packages/react/src/components/Coachmark/__snapshots__/Coachmark.test.tsx.snap

- v8 `Coachmark` tests don't use testing-library
- Convert `Coachmark` to fully use testing-library
part of #21663

Coachmark (v8): convert tests to use testing-library

---

change/@fluentui-react-676587fb-05b6-4230-92fc-290587f81d9d.json
packages/react/src/components/Slider/Slider.styles.ts
packages/react/src/components/Slider/__snapshots__/Slider.test.tsx.snap

new WCAG 2.1 rules specify that UI which indicate state and boundaries, needs to meet a 3:1 contrast radio. The current v8 slider styles does not match that. 
(both right side of the rail colors are below 3:1)
Proposed solution is to bump up the default grays used for the default state, and then only change the 'progress' color on hover. This was chosen to fix the problem with the least change from the original styles (rather than moving over to the v9 approach). We also are not changing the right side on hover due to no palette lighter palette colors that meet the 3:1 ratio. This split blue/gray approach matches our v9 style, so we're at least moving towards v9 styles there.
I also used palette over semantic in that the original semantic names were meaningless, and picking another random …

adjust slider styles to match contrast ratios

---

packages/react/src/components/CommandBar/CommandBar.test.tsx
packages/react/src/components/CommandBar/__snapshots__/CommandBar.test.tsx.snap

- v8 `CommandBar` tests don't use testing-library
- Convert `CommandBar` to fully use testing-library
part of #21663

CommandBar (v8): convert tests to use testing-library

---

packages/fluentui/CHANGELOG.md
packages/fluentui/docs/src/examples/components/Provider/Performance/ProviderMergeThemes.perf.tsx
packages/fluentui/react-bindings/src/styles/resolveVariables.ts
packages/fluentui/react-northstar-prototypes/src/prototypes/customToolbar/index.tsx
packages/fluentui/react-northstar/src/components/Provider/Provider.tsx
packages/fluentui/styles/src/mergeThemes.ts
packages/fluentui/styles/src/toCompactArray.ts
packages/fluentui/styles/src/types.ts
packages/fluentui/styles/test/mergeThemes/mergeComponentStyles-test.ts
packages/fluentui/styles/test/mergeThemes/mergeComponentVariables-test.ts
packages/fluentui/styles/test/mergeThemes/mergeFontFaces-test.ts
packages/fluentui/styles/test/mergeThemes/mergeSiteVariables-test.ts
packages/fluentui/styles/test/mergeThemes/mergeStaticStyles-test.ts
packages/fluentui/styles/test/mergeThemes/mergeThemeVariables-test.ts
packages/fluentui/styles/test/mergeThemes/mergeThemes-test.ts
packages/fluentui/styles/tsconfig.json
scripts/typescript/tsconfig.fluentui.json

`merge*` functions from `@fluentui/styles` do not accept variable amount of arguments, now it's fixed to two arguments.
```tsx
mergeThemes(themeA, themeB);
mergeThemes(themeA, themeB, themeC);
```
```tsx
// ✅ still works
mergeThemes(themeA, themeB);
// ⚠️ multiple theme merging should be done in a chain
mergeThemes(themeA, mergeThemes(themeB, themeC));
```
This changes are done to simplify theme merging, avoid merges that are not needed and improve performance. The main goal is to avoid theme merging on top level `Provider`:
```tsx
return <Provider theme={teamsTheme} />;
}
```
Before even in this example we were merging `teamsTheme` with `emptyTheme` that comes from default context value. After `teamsTheme` will be still processed to ensure that it's prepared, but heavy …

perf: simplify merge functions for themes

---

packages/a11y-testing/package.json
packages/a11y-testing/src/facades/ComponentTestFacade.tsx

While working on #22245 I discovered that `@fluentui/a11y-testing` (used by northstar, react-button, and react-link) still uses Enzyme.
Switch the package to use testing-library. I also simplified some of the logic in the one base file that was modified.
Part of #21663

Convert a11y-testing package to testing-library

---

apps/public-docsite/src/pages/Overviews/GetStartedPage/docs/web/GetStartedNextSteps.md
apps/public-docsite/src/pages/Overviews/ResourcesPage/docs/default/ResourcesContributionProcess.md
apps/public-docsite/src/pages/Overviews/ResourcesPage/docs/default/ResourcesDesignResources.md
apps/public-docsite/src/pages/Overviews/ResourcesPage/docs/default/ResourcesDeveloperResources.md

I noticed while working on #22266  that there was a React dev warning in the console about `class` being an invalid React attribute, coming from converted markdown files.
I don't think this happened in the past, so it may have been due to a change in `markdown-to-jsx` 6 => 7.
Update the markdown files to use `className` instead of `class` (only in the parts that will be rendered as HTML by `markdown-to-jsx`, not in code blocks).

v8 website: change class to className in markdown files

---

packages/react-textarea/src/components/Textarea/Textarea.test.tsx
packages/react-textarea/src/components/Textarea/__snapshots__/Textarea.test.tsx.snap

This PR adds basic unit tests for `Textarea`, these are mainly the same as `Input` since their behavior is similar.
Related issue: #21845

react-textarea: Adding unit tests

---

package.json
packages/fluentui/react-builder/package.json
yarn.lock

> This affects the package immer before 9.0.6. A type confusion vulnerability can lead to a bypass of https://github.com/advisories/GHSA-9qmh-276g-x5pj when the user-provided keys used in the path parameter are arrays. In particular, this bypass is possible because the condition (p === "proto" || p === "constructor") in applyPatches_ returns false if p is ['proto'] (or ['constructor']). The === operator (strict equality operator) returns false if the operands have different type.
https://github.com/advisories/GHSA-33f9-j839-rf8h

update immer version to move away from insecure version

---

change/office-ui-fabric-react-6d057a74-bcd2-45af-a63f-ff0e24a2e733.json
packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx
packages/office-ui-fabric-react/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap
packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.test.tsx

Essentially the same fix as #21468, but for `office-fabric-ui-react`'s Calendar
Originally a port of the v8 fix in #20412
fixes [13309](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/13309)

fix(Calendar) v7: move gridcell role from button to td element

---

.github/CODEOWNERS

Any `react-components` change creates an individual dependency on each of our teams to review it. Sometimes when there's a PR for package X, owned by team Y, that has changes on `react-components`, teams A and B will still be marked as reviewers.
Leveraging the parent team `fluentui-react`, PRs that change the `react-components` package will only mark one team, instead of all teams individually.
This aims to reduce noise to all teams or added responsibility to review when it's not a package other teams own.
With this change, teams are still informed of the change and it's immediately clear that any team can approve it, instead of each team individually.
This can be further leveraged for any cross team ownership to reduce other edge cases like these.
Consider this a proposal and share your …

chore: unify `react-components` ownership

---

change/@fluentui-react-conformance-785a243f-f41d-4887-ae88-a779ee586235.json
packages/react-conformance/README.md
packages/react-tooltip/src/components/Tooltip/Tooltip.test.tsx

When examining the DOM, conformance tests typically only look at the tree starting from the component root. This causes problems when trying to inspect content rendered into React Portals as Portals are typically rendered as sibling nodes the component that triggers their rendering.
Conformance tests provide a mechanism to override the root that is examined by tests by providing an override to `testInfo.getTargetElement`.
Tooltip tests already have a `queryByRoleTooltip` function to retrieve the rendered tooltip and this has been provided to the conformance test so the rendered tip can be inspected allowing the following conformance tests to be enabled:
- component-has-static-classname
- component-has-static-classnames-object
- component-has-static-classname-exported
The README in …

Enable more conformance tests for Tooltip

---

change/@fluentui-react-c438a225-3740-4f59-9009-a25fc06478c1.json
packages/react/src/components/ComboBox/ComboBox.tsx

Pull request checklist
Edge shows autofill info for ComboBox inputs having id or aria-label starting with "name", which isn't the desired behavior for combo boxes since it will result in two overlapping menus. On investigating the attributes, [aria-autocomplete flag](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-autocomplete) seems to be initialized incorrectly for the underlying [autofill](https://github.com/microsoft/fluentui/blob/83a08f167c8d8535f4e15ab2b760bec1a1a486be/packages/react/src/components/ComboBox/ComboBox.tsx#L2344). It should be "list" here rather than "none" as per the definition of the values of this attribute.
aria-autocomplete should be "list" in case of allowFreeform==true && autoComplete==false
When this attribute is changed, Edge …

Change combobox aria-autocomplete to 'list' when autoComplete is off

---

apps/public-docsite/src/pages/Controls/AvatarPage/docs/android/AvatarOverview.md
apps/public-docsite/src/pages/Controls/AvatarPage/docs/ios/AvatarOverview.md
apps/public-docsite/src/pages/Controls/AvatarPage/docs/mac/AvatarUsage.md
apps/public-docsite/src/pages/Controls/BottomNavigationPage/docs/android/BottomNavigationOverview.md
apps/public-docsite/src/pages/Controls/BottomNavigationPage/docs/ios/BottomNavigationOverview.md
apps/public-docsite/src/pages/Controls/ButtonPage/docs/android/ButtonOverview.md
apps/public-docsite/src/pages/Controls/ButtonPage/docs/ios/ButtonOverview.md
apps/public-docsite/src/pages/Controls/ButtonPage/docs/mac/ButtonOverview.md
apps/public-docsite/src/pages/Controls/CalendarPage/docs/android/CalendarOverview.md
apps/public-docsite/src/pages/Controls/ChipPage/docs/android/ChipOverview.md
apps/public-docsite/src/pages/Controls/ChipPage/docs/ios/ChipOverview.md
apps/public-docsite/src/pages/Controls/DatePickerPage/docs/mac/DatePickerUsage.md
apps/public-docsite/src/pages/Controls/DrawerPage/docs/ios/DrawerOverview.md
apps/public-docsite/src/pages/Controls/ListCellsPage/docs/android/ListCellsOverview.md
apps/public-docsite/src/pages/Controls/ListCellsPage/docs/ios/ListCellsOverview.md
apps/public-docsite/src/pages/Controls/MessageBarPage/docs/ios/MessageBarOverview.md
apps/public-docsite/src/pages/Controls/NavBarPage/docs/ios/NavBarOverview.md
apps/public-docsite/src/pages/Controls/PeoplePickerPage/docs/android/PeoplePickerOverview.md
apps/public-docsite/src/pages/Controls/PivotPage/docs/ios/PivotOverview.md
apps/public-docsite/src/pages/Controls/PopupMenuPage/docs/ios/PopupMenuOverview.md
apps/public-docsite/src/pages/Controls/SpinnerPage/docs/ios/SpinnerOverview.md
apps/public-docsite/src/pages/Controls/TooltipPage/docs/android/TooltipOverview.md
apps/public-docsite/src/pages/Controls/TooltipPage/docs/ios/TooltipOverview.md

Empty space between DisplayToggle and first line of markdown was causing the Markdown parser to fail.
I'm curious if this is a bug in the new Markdown parser, or just a bad interaction between Markdown and the custom JSX. I'll create a backlog item to look at it later. For now, working is best. https://github.com/microsoft/fluentui/issues/22349
**Before**
**After**

remove space from markdown causing broken render

---

.github/CODEOWNERS

CODEOWNERS for Facepile and Persona on the 7.0 branch are outdated.
CODEOWNERS for Facepile and Persona on the 7.0 branch are updated.

Update CODEOWNERS for Facepile and Persona in 7.0 Branch

---

.github/CODEOWNERS

CODEOWNERS for Facepile and Persona on the master branch are outdated.
CODEOWNERS for Facepile and Persona on the master branch are updated.

Update CODEOWNERS for Facepile and Persona in master branch (v8)

---

apps/public-docsite/src/components/Site/Site.tsx
change/@fluentui-react-docsite-components-a72db34a-ebc4-4048-a61b-98a23136cdc2.json
packages/react-docsite-components/src/components/App/App.tsx
packages/react-docsite-components/src/components/ExampleCard/ExampleCard.tsx
packages/react-docsite-components/src/components/ExampleCard/ExampleCard.types.ts
packages/react-docsite-components/src/components/Nav/Nav.types.ts
packages/react-docsite-components/src/components/TopNav/TopNav.tsx
packages/react-docsite-components/src/utilities/activePage.ts
packages/react-docsite-components/src/utilities/getNormalizedPath.ts
packages/react-docsite-components/src/utilities/getSiteArea.ts
packages/react-docsite-components/src/utilities/index2.ts
packages/react-docsite-components/src/utilities/router/Router.tsx

Among the various long-running issues with the website, @smhigley brought these particularly unfortunate ones to my attention again during FHL:
- The example titles aren't rendered as actual HTML headings (bad for screen reader users)
- The document title doesn't update to reflect the current page title
Make the ExampleCard titles use `h3` by default, with a prop for customization.
Updating the document title was tricky and actually had to be done in two places:
- `App.tsx` in `react-docsite-components` for the legacy demo app (as seen at aka.ms/fluentdemo)
- `Site.tsx` in `public-docsite` for the actual website (developer.microsoft.com/fluentui). 
Our custom router component already had logic to match the current hash with a route URL, and I factored that out into a `getNormalizedPath` …

v8 website: make example titles h3, update document title

---

tools/generators/migrate-converged-pkg/index.spec.ts
tools/generators/migrate-converged-pkg/index.ts

- nx introduced violation, so calling updateProject wont add implicitDependencies
- we now enforce this within migration for consistency

fix(tools): create implicitDeps field when running migrate-converged-pkg

---

packages/react-select/package.json
workspace.json

- react-select wasn't properly bootstrap thus was violating isMigrated check for vNext
- react-select is now compliant with our vNext setup

chore: migrate react-select to new DX

---

packages/fluentui/CHANGELOG.md
packages/fluentui/e2e/tests/chatMessageActionMenu-example.tsx
packages/fluentui/e2e/tests/chatMessageActionMenu.spec.ts
packages/fluentui/react-northstar/src/components/Portal/PortalInner.tsx
packages/fluentui/react-northstar/src/components/Portal/usePortalBox.ts
packages/fluentui/react-northstar/src/components/Provider/Provider.tsx
packages/fluentui/react-northstar/src/components/Provider/portalContext.ts
packages/fluentui/react-northstar/test/specs/components/Popup/Popup-test.tsx
packages/fluentui/react-northstar/test/specs/components/Portal/PortalInner-test.tsx
packages/fluentui/react-northstar/test/specs/components/Provider/Provider-test.tsx

Potentially this PR introduces a breaking change due changes in layouts, read below.
---
The goal are:
- align behavior with Fluent UI v9 for better compatibility
- pass classes to apply in a context instead on an element to unblock performance optimisations on the app level
- In `Provider` we create an element (`usePortalBox()` hook) where all portals created by `PortalInner` will be mounted
- All portals are mounted in an element created by a provider
```html
<body>
<div class="ui-provider">
<div class="ui-popup"></div>
<div class="ui-tooltip"></div>
<div class="ui-tooltip"></div>
</div>
</body>
```
- In `PortalInner` we create an element (`usePortalBox()` hook) where a portal will be mounted
- All portals are mounted in separate elements
```html
<body>
<div class="ui-provider">
<div …
```

chore: refactor Portal/Provider to use the same approach as in v9

---

scripts/just.config.ts
scripts/tasks/copy.ts
scripts/tasks/sass.ts

For every package, the `sass` task takes around 0.3-1.0 seconds in CI, even if there are no sass files. It's not much time but becomes more significant when multiplied by 70 packages. 
The delay is probably because `just-scripts` `sassTask` imports and parses various dependencies before bailing if there are no scss files.
Add an early bail-out which doesn't even initialize `sassTask()` if there are no scss files in the directory. Packages without sass now finish in < 0.01s. (With our limited number of actual packages with sass files, this probably mitigates the impact of `dart-sass` being a little slower as described in https://github.com/microsoft/fluentui/pull/22352#issuecomment-1090606556.)
Also did some minor cleanup/simplification of the copy task. (I thought about adding a bail-out …

Only initialize sass task when needed

---

packages/fluentui/react-component-event-listener/test/EventListener-test.tsx
packages/fluentui/react-northstar-fela-renderer/package.json
packages/fluentui/react-northstar-fela-renderer/test/__snapshots__/felaRenderer-test.tsx.snap
packages/fluentui/react-northstar-fela-renderer/test/felaRenderer-test.tsx
packages/fluentui/react-northstar/package.json
packages/react/src/components/ScrollablePane/ScrollablePane.test.tsx
packages/react/src/components/pickers/BasePicker.test.tsx
yarn.lock

Assorted things in tests fail with React 17. I fixed some of them already (#21032) but this PR fixes a few more.
After this PR, at least as far as the things a local `yarn test` covers, we should be unblocked from upgrading to React 17 (with the community Enzyme adapter `@wojtekmaj/enzyme-adapter-react-17`).
Add missing `act()` wrappers in the `EventListener` test.
In `@fluentui/react-northstar-fela-renderer`, replace the snapshot serializer from `jest-react-fela` with a small custom one. The old serializer relied on `htmltojsx`, which is extremely outdated (depends on React 15) and tries to import something from `react-dom` which was removed in 17.  (This fix could theoretically be contributed upstream later if someone wants, I just won't have time.)
- ScrollablePane: add a mock of a …

Fix a few more issues blocking React 17 in tests

---

packages/fluentui/CHANGELOG.md
packages/fluentui/docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx

RTL examples (files suffixed with `.rtl`) should be displayed in RTL direction by default.
The existing check in the constructor of `ComponentExample` is reset by `getDerivedStateFromProps` so we need to repeat the check there.

Ensure RTL example show up in rtl

---

apps/ts-minbar-test-react-components/src/index.ts
apps/ts-minbar-test-react/src/index.ts

- `ts-minbar-test` for both `@fluentui/react` and `@fluentui/react-components` installs the latest version of react (React 18) to the test app which is causing CI to fail.
- explicitly install React 17 to test app
Fixes #

ts-minbar-test: explicitly install react 17 to testApp

---

apps/ts-minbar-test-react-components/assets/index.tsx
packages/fluentui/projects-test/src/nextjs.ts
packages/fluentui/projects-test/src/rollup.ts
packages/fluentui/projects-test/src/typings.ts

- `@fluentui/projects-test` installs the latest version of react (React 18) which is causing CI to fail.
- Explicitly install React 17 to `@fluentui/projectst-test` app.
- This also fixes an issue with an incorrect usage of `Button` in `@fluentui/ts-minbar-test-react-components`.

projects-test: Explicitly install React 17 to package

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/themes/teams/components/Tooltip/tooltipContentStyles.ts

Tooltip has the same font-size as the general text (inherited from body)
Tooltip with font-size 12px will look smaller than the general text
Fixes #

Tooltip text size should be 12 by default

---

change/@fluentui-react-be6d794a-f2d4-4abf-8bac-137b469d95e9.json
packages/react/src/components/Panel/Panel.styles.ts
packages/react/src/components/Panel/__snapshots__/Panel.test.tsx.snap

- CSS `inherit` is broken in chromium engines when styles are dynamically re-computed ( for example changing theme )
- Commands ( Panel Header ) has inconsistent styling behaviour with Footer when item content forces scrollable behaviour
- Commands is adding empty space at the top which delays snapping behaviour/incorrectly renders colors if user re-styles Commands via `styles`
- `backgroundColor` is used instead of destructive `background`
- `inherit` is not used, re-computation works and themes and custom colors via styles slots are properly applied
https://user-images.githubusercontent.com/1223799/162282064-74bb76a5-54f7-42d3-b88f-4a4d65b96e39.mov
- Commands and Footer implement consistent behaviour when scrollable behaviour is in place
```tsx
<Panel styles={{main: { …
```

fix(react): Panel - make theming work and sticky styling consistent

---

packages/react-priority-overflow/etc/react-priority-overflow.api.md
packages/react-priority-overflow/src/components/Overflow.tsx
packages/react-priority-overflow/src/stories/CustomPriorities.stories.tsx
packages/react-priority-overflow/src/stories/Dividers.stories.tsx
packages/react-priority-overflow/src/stories/DomOrder.stories.tsx
packages/react-priority-overflow/src/stories/MinimumVisible.stories.tsx
packages/react-priority-overflow/src/stories/Pinned.stories.tsx
packages/react-priority-overflow/src/stories/PriorityWithDividers.stories.tsx
packages/react-priority-overflow/src/stories/ReverseDomOrder.stories.tsx
packages/react-priority-overflow/src/stories/Selection.stories.tsx

Overflow renders a div
Overflow takes a single child element that it clones to add the overflow container behavior.
Note: Fixed the issue with the dividers doubling up.
Updates #22313

Updated Overflow component to be divless wrapper

---

change/@fluentui-react-tabs-5399b449-6c6d-4276-97d4-22fbf60a4f9d.json
packages/react-tabs/src/components/Tab/useTabStyles.ts

Disabled tab has background inherited
Disabled tab has transparent background
Fixes #22338

Set background when tab is disabled.

---

change/@fluentui-react-tabs-f4b4f066-3119-40ac-a489-f4b940604ca8.json
packages/react-tabs/src/components/Tab/useTabStyles.ts

Small vertical tab column gap spacing needs to be updated
column gap spacing is xs (4px) per previous figma
column gap spacing is xxs (2px) per updated figma
Fixes #22334

Updated spacing based on figma change

---

change/@fluentui-react-tabs-c4411795-459a-4614-bbb0-128211b1e806.json
packages/react-tabs/src/components/Tab/useTabStyles.ts

Subtle tab background set only on hover to outdated token.
Subtle tab background uses subtle tokens per figma
Fixes #22336

Fix tab subtle background

---

packages/react/src/components/Facepile/Facepile.test.tsx
packages/react/src/components/Facepile/__snapshots__/Facepile.test.tsx.snap

- v8 `Facepile` tests don't use testing-library
- Convert `Facepile` to fully use testing-library
part of #21663

Facepile (v8): convert tests to use testing-library

---

packages/react/src/components/ColorPicker/ColorPicker.test.tsx
packages/react/src/components/ColorPicker/__snapshots__/ColorPicker.test.tsx.snap

- v8 `ColorPicker` tests don't use testing-library
- Convert `ColorPicker` to fully use testing-library
part of #21663

ColorPicker (v8): convert tests to use testing-library

---

packages/fluentui/code-sandbox/src/SandboxApp.tsx

There is no possibility to test v2 colors in sandbox app.
Add Teams Light V2 and Teams Dark V2 themes:

add v2 colors to sandbox app

---

.github/ISSUE_TEMPLATE/accessibility_issue.md
.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/feature_request.md

At the moment we identified 2 main issues when having shield duty or doing triaging of new issues:
- when creating issue, contributor has no context/missing guidance for what library in our monorepo is that issue for
- contributors are not enforced to provide proper reproduction and library version that is affected, which leads to additional time spent on our side to triage etc
- we leverage new github issues templates that provide superb UX to contributors
- we enforce proper reports and issue formats so we can effectively triage and act if needed
- we unify our bug template
- instead creating dummy issues we leverage proper UX to forward contributors to github discsussion and stack overflow
- [🔎 new bug report template](https://github.com/microsoft/fluentui/blob/180f4de91aff95981aaada2ae …

docs: setup github issues beta templates

---

change/@fluentui-react-components-40b86f61-aa0f-4126-8d2d-a3151f06f577.json
change/@fluentui-react-textarea-67fb3a48-2e9e-4fbe-be50-367d7abb703d.json
packages/react-components/package.json
packages/react-components/src/unstable/index.ts
packages/react-textarea/README.md
packages/react-textarea/package.json
packages/react-textarea/src/stories/TextareaDefault.stories.tsx

This PR introduces `react-textarea` to `react-components`, adds more detail to the readme, and adds a label to the default example.
Issues: #21845 and #22320

react-textarea: Re-exporting Textarea in react-components

---

packages/react-spinbutton/bundle-size/SpinButton.fixture.js
packages/react-spinbutton/package.json

`react-spinbutton` does not track its bundle size.
`react-spinbutton` tracks its bundle size.
- #22307
- #20930

react-spinbutton: add bundle-size script

---

.github/CODEOWNERS

`react-spinbutton` does not have CODEOWNERS.
`react-spinbutton` has CODEOWNERS.
- #22307
- #20930

react-spinbutton: add CODEOWNERS

---

packages/react-cards/config/tests.js
packages/react-icon-provider/config/tests.js
packages/react-icon-provider/src/IconProvider.test.tsx
packages/react-list/config/tests.js
packages/react-window-provider/config/tests.js
packages/react-window-provider/src/WindowProvider.test.tsx
packages/theme/config/tests.js
scripts/jest/jest-resources.js
scripts/jest/jest-setup.js
scripts/jest/setupTests.js

We're trying to move away from Enzyme, but it's still used in a lot of packages. Each of these packages will need to be updated to use a different enzyme adapter when we update to React 17. 
Some of the packages that configure enzyme in their jest setup don't actually use it at all, or only have very minimal usage.
- Remove enzyme setup from a few packages where enzyme isn't used at all
- In 2 packages with very simple tests (react-icon-provider and react-window-provider), remove enzyme setup and port to testing-library
- Add some comments and types in the jest setup code and helpers
This was part of the React 17 upgrade attempt (#22326) but can be merged now, and will simplify the actual upgrade PR a bit.
Part of #21663

Remove Enzyme usage in places it's not needed

---

change/@fluentui-font-icons-mdl2-e7773ae4-3eff-4f71-a848-89c5691e5bc0.json
packages/font-icons-mdl2/package.json
packages/font-icons-mdl2/src/index.ts

The `initializeIcon` call in font-icons-mdl2 either takes in the default cdn or a user defined URL as an argument. However, in specific cases where a user is using the bundled version of `@fluentui/react`, the default cdn is used, and the user is unable to change the CDN where the icons are served from.
This PR adds the ability for the user to modify `window.FabricConfig` that will then be able to be consumed in the bundled version of `@fluentui/react`.
Simply add a `<script>` tag above the bundled `@fluentui/react` script with the following:
`<script type="text/javascript">
window.FabricConfig = {
fontBaseUrl: 'https://cdn.gov/foo/'
}
</script>`
Fixes #22412

Update initializeIcons to add user defined URL in argument

---

change/@fluentui-react-tabs-93161aea-6653-4d44-aee3-07824d728aaa.json
packages/react-tabs/src/components/Tab/useTabStyles.ts

Subtle tab content and icon not set.
This was due to moving styles into transparent that previously were on base.
Subtle tab content and icon styles applied per figma
Related to #22336

react-tabs: Added content and icon styles to subtle appearance

---

change/@fluentui-react-d7c60de7-8e2e-4f2b-9bcb-489bf1ed51e1.json
packages/react-examples/src/react/Dropdown/Dropdown.Basic.Example.tsx
packages/react/src/components/Dropdown/Dropdown.base.tsx

If you tab to the previous/next focusable element while a `Dropdown` is open and that element is inside of a `FocusZone`, the tab will skip that element and go to the previous/next one.
Tabbing to the previous/next focusable element while a `Dropdown` is open will correctly go to that element, even if it is inside of a `FocusZone`.
Fixes #22477

Dropdown: Fixing issue where, if previous/next tabbable element is inside FocusZone then tabbing with Dropdown open will skip it

---

change/@fluentui-react-b24effe5-f9e7-4d34-b12c-7f11576dd23e.json
packages/react/src/components/Pivot/Pivot.styles.ts

fixes #20664
Some custom pivot pseudo styles meant to force pivots to be as wide as they bolded text, was spilling over into the overflow menu causing rendering issues.
Moved the styles into the "not a link in overflow" set of styles
before:
after:

Pivot: Fixed overflow render issue on focus

---

change/@uifabric-icons-388eaadd-8734-4c42-a630-e91ca6353c2f.json
packages/icons/package.json
packages/icons/src/index.ts

Cherrypick of #22411 
_Original description follows:_
The `initializeIcon` call in font-icons-mdl2 either takes in the default cdn or a user defined URL as an argument. However, in specific cases where a user is using the bundled version of `@fluentui/react`, the default cdn is used, and the user is unable to change the CDN where the icons are served from.
This PR adds the ability for the user to modify `window.FabricConfig` that will then be able to be consumed in the bundled version of `@fluentui/react`.
Simply add a `<script>` tag above the bundled `@fluentui/react` script with the following:
`<script type="text/javascript">
window.FabricConfig = {
fontBaseUrl: 'https://cdn.gov/foo/'
}
</script>`

Update initializeIcons to add user defined URL in argument (v7)

---

change/@fluentui-react-icons-mdl2-9b3f13b2-0adb-4a90-99f8-beb87634435d.json
packages/react-icons-mdl2/src/utils/SvgIcon.scss

SVG Icons, support color adjust in high contrast mode

---

tools/generators/migrate-converged-pkg/index.spec.ts
tools/generators/migrate-converged-pkg/index.ts

Currently, the generator only adds .ts files to the e2e tsconfig.
Generator will now add .ts and .tsx files to the e2e tsconfig, to support the normal use case for behavior testing of components.

fix: add .tsx to e2e tsconfig

---

packages/react-examples/src/react/Tooltip/Tooltip.Display.Example.tsx

Our global styles are overriding button background and border, so this PR adds explicit styles to this demo.
https://github.com/microsoft/fluentui/blob/master/apps/public-docsite/src/styles/_base.scss#L32-L36
These styles ensure that the border/background is visible and the demo makes sense

Add inline styles to tooltip demo to ensure button styles are visible

---

change/@fluentui-react-bb4f65ba-371a-484a-9964-955da31a5480.json
packages/react/src/components/Dialog/Dialog.base.tsx

Fixes #22218
We were checking on `dragHandleSelector` and then mutating it if it was not set, causing a re-render in which `dragHandleSelector` was always set, causing our default case to not work properly. 
This fix spreads the dragOptions into a new object before changing them, and checks the original modalProps.dragOptions instead of the mutated one.

Fixed Dialogs ability to be draggable

---

change/@fluentui-react-17f0b7da-0754-402e-b8e8-1c548364cb96.json
packages/react/etc/react.api.md
packages/react/src/components/DetailsList/DetailsList.base.tsx
packages/react/src/components/DetailsList/DetailsList.types.ts

Opened this after a conversation with a team asking about `ariaLabel` vs. `ariaLabelForGrid`.
It looks like the `shouldApplyApplicationRole` was added based on a misconception about how to solve automatic mode switching for grids in JAWS -- in practice, applying the application role in a case like this makes the experience much worse for screen reader users. I've left it for now to avoid changing behavior, but added a warning and deprecation notice.
The other change is that `ariaLabel` is moved from the wrapper (which should usually be a generic `<div>` that doesn't support naming) to the grid element, where it will actually name the grid container. Even if the application role is set, the grid node should have better or equal support for `aria-label`. I've also added a deprecation …

fix(Detailslist): update docs for `ariaLabel` and `shouldApplyApplicationRole`

---

change/@fluentui-react-753464fb-ab47-4d62-b356-63d6f2499694.json
packages/react/src/components/ComboBox/ComboBox.tsx

ComboBox is not scrolling to the selected index, instead it stays in the first item. This is due to checking the state for the pending selected index instead of using the `_getPendingSelectedIndex`.
Use `_getPendingSelectedIndex` to find the right index to jump to.
Fixes #22228

ComboBox: Fixing onScrollToItem to scroll to pending selected index

---

change/@fluentui-merge-styles-ca3053dc-44f0-4f74-ac01-921bd27865e0.json
packages/merge-styles/package.json

This PR adds missing export in package.json for ssr. This missing export wouldn't let you import `renderStatic`.
Fixes #22288

merge-styles: Adding missing export to package.json for ssr

---

change/@fluentui-react-8a577334-1bdb-4a25-b070-81e3ddb6f379.json
packages/react-examples/src/react/TeachingBubble/TeachingBubble.ButtonOrder.Example.tsx
packages/react-examples/src/react/TeachingBubble/TeachingBubble.doc.tsx
packages/react/src/components/TeachingBubble/TeachingBubbleContent.base.tsx
packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.deprecated.test.tsx.snap
packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.test.tsx.snap

This PR updates TeachingBubble's primary and secondary buttons to be in the correct order (primary left and secondary right). A new example "TeachingBubble with custom button order" was added as well to give guidance in case the old button order is needed. 
TeachingBubble has the primary button on the right, which based on its best practices it should be on the left.
The primary button is now on the left side.
Before:
After:
Fixes #21978

Updating TeachingBubble to follow best practices

---

scripts/cypress.js
scripts/cypress/plugins/index.js
scripts/storybook/webpack.config.js

With the Cypress component testing setup using `esbuild-loader`, changes to v8 components no longer triggered a rebuild because v8 doesn't use tsconfig path mapping. This made fixing component issues revealed while writing tests much more challenging (such as while working on #22500).
For now, **for v8 only**, switch back to using `ts-loader` with a webpack `resolve.alias` config. This is a bit slower but actually not too bad (compared to bundling the whole package) because only a few component files are used in e2e tests at the moment. At least to start out, I reused the v8 storybook webpack config helper because it included all the relevant aliases, loaders, etc. Open to suggestions on that. 
The other possible argument in favor of using ts-loader here is that it can transpile to ES5, …

Cypress: rebuild on file changes in v8

---

change/@fluentui-react-acfcd924-0080-4312-8cc7-8239a4d2c416.json
packages/react/src/components/Button/BaseButton.tsx

We previously updated ContextualMenu to always set focus on the first menu item to fix a Narrator bug (#20601), and minor poor experiences in other screen readers (e.g. JAWS announcing the role/name of the menu twice). Before that, it set the focus to the container on click, and to the first menu item on keyboard activation.
This is relevant to screen reader behavior, since screen readers in virtual cursor mode (and VoiceOver on macOS) send a click event to the button.
Based on conversations with partner teams, setting focus to the first menu item can create visual regressions, particularly when menuitems have a tooltip that shows on focus. Previously opening the menu with the keyboard would focus the first item and show the tooltip, but that would not happen on click.
We're reverting the …

ContextualMenu: change default focus target when opened by click event

---

change/@fluentui-react-c3dd6c69-707e-4278-8aec-854fa72b5279.json
packages/react/src/components/Nav/Nav.styles.ts
packages/react/src/components/Nav/__snapshots__/Nav.test.tsx.snap

Remove active focus styles from Chevron because link already has them

---

change/@fluentui-react-e7c88860-cc68-4ecc-9d1c-6724461f0b5f.json
packages/react/src/components/ContextualMenu/ContextualMenu.cnstyles.ts
packages/react/src/components/ContextualMenu/__snapshots__/ContextualMenu.test.tsx.snap

fixes #22137
Removed most of the focus overrides so that control would have normal high contrast focus styles. The "selected blue" high contrast color should only be used for denoting selection as in dropdown or combobox. 
This change drastically reduces the number of overrides we are doing, and fixes a number of high contrast color issues
OLD
NEW

Contextmenu high contrast styles update

---

change/@fluentui-react-5ac41ceb-4ad3-4aff-8c8f-907205be658e.json
packages/react/src/utilities/selectableOption/SelectableDroppableText.types.ts

Updated prop docs to correctly state that onRenderOption affects both regular items AND header items. onRenderItem still is the only way to affect dividers. 
Fixes #22454

Fixed onRenderOption docs to note that regular AND header types are affected

---

apps/vr-tests/src/stories/Panel.stories.tsx
change/@fluentui-react-9c0e56bd-4965-4331-a39d-3d5fc5c5a528.json
packages/react/src/components/Panel/Panel.styles.ts

Fixes #22476
Previous PR changed navigation spacing from margin to padding, but did not change the `hasCustomNavigation` margin reset, to a padding reset.
Also added VR test to ensure that this would be caught in the future.

22476 Fix panel custom navigation padding

---

packages/react-spinbutton/etc/react-spinbutton.api.md
packages/react-spinbutton/src/components/SpinButton/SpinButton.strings.ts
packages/react-spinbutton/src/components/SpinButton/SpinButton.test.tsx
packages/react-spinbutton/src/components/SpinButton/SpinButton.types.ts
packages/react-spinbutton/src/components/SpinButton/useSpinButton.tsx
packages/react-spinbutton/src/components/SpinButton/useSpinButtonStyles.ts
packages/react-spinbutton/src/index.ts
packages/react-spinbutton/src/stories/SpinButton.stories.tsx
packages/react-spinbutton/src/stories/SpinButtonBounds.stories.tsx
packages/react-spinbutton/src/stories/SpinButtonDisplayValue.stories.tsx
packages/react-spinbutton/src/stories/SpinButtonStrings.stories.tsx

1. SpinButton has some styling issues in Windows High Contrast Mode
2. Increment and decrement buttons do not have labels
1. Styling has been added for address the WHCM issues. A follow up PR will be made to make icons do this be default.
2. A `strings` prop has been added to SpinButton allowing labels be applied to the increment and decrement buttons. These strings support a token, `{step}`, that will be replaced with the value of the `step` prop when present in the string. This allows the labels to be localized as needed. By default the English localization is included.
#22307

SpinButton updates from accessibility testing

---

packages/fluentui/CHANGELOG.md
packages/fluentui/docs/src/examples/components/Chat/Content/ChatExampleReadStatus.shorthand.tsx
packages/fluentui/react-northstar/src/themes/teams/components/Chat/chatMessageReadStatusStyles.ts
packages/fluentui/react-northstar/src/themes/teams/components/Chat/chatMessageReadStatusVariables.ts

Align ReadStatus design with its usage in Teams.
* Align vertically with bottom of message body
* Set horizontal spacing based on density
* Comfy: 12px to 5px
* Compact: 3px to 4px
*Comfy*
*Compact*

Align chat read status design
