packages/fluentui/react-component-event-listener/package.json, packages/fluentui/react-component-ref/package.json
React 18 in allowed in `peerDependencies` for `@fluentui/react-component-event-listener` & `@fluentui/react-component-ref`. Unblocks https://github.com/Semantic-Org/Semantic-UI-React/issues/4354.
P.S. I tested these packages with Semantic UI React (types don't throw, event handlers work), they work with React 18.
=> chore: enable React 18 in peerDependencies for react-component-event-listener & react-component-ref

change/@fluentui-font-icons-mdl2-e8c50c7c-8ceb-4308-9be1-27a2797a7a1e.json, packages/font-icons-mdl2/src/index.ts
This PR aligns the `Window` interface in v8 font-icons-mdl2 with the interface in v7
=> Update Window interface to add FabricConfig

apps/theming-designer/src/components/FabricPalette.tsx, change/@fluentui-react-c3023df6-2bb7-4f00-a349-3e42553cce2d.json, packages/react/etc/react.api.md, packages/react/src/components/ThemeGenerator/ThemeRulesStandard.ts
This PR adds neutralSecondaryAlt to the theming designer and dedeprecates it from FabricSlots inside Theme Generator.
Theme table
Theme export
Theme table
Theme export
Fixes #22222
=> theming-designer: Adding neutralSecondaryAlt to theming-designer and removing deprecation from neutralSecondaryAlt

packages/utilities/src/object.test.ts
The test case for `@fluentui/utilities`' `mapEnumByName()` function has an assertion that is never called as the code is `.toBeFalsey` but should be `.toBeFalsey()`.
See #21599
On further consideration the assertion in question is unnecessary and the test has been rewritten to eliminate it. As `mapEnumByName()` also has a filtering feature another test case has been added to verify this functionality.
Fixes #21599
=> fluentui/utilities: update object tests

change/@fluentui-react-79ae01f0-33af-4c17-99c0-af759fff0142.json, packages/react/etc/react.api.md, packages/react/src/components/Dropdown/Dropdown.base.tsx, packages/react/src/components/Dropdown/Dropdown.test.tsx, packages/react/src/components/Dropdown/Dropdown.types.ts
A team requested a means to close the listbox popup for the Dropdown control. We currently have `dismissMenu` [on Combobox](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/ComboBox/ComboBox.tsx#L510), but not Dropdown, this PR adds the same handle to Dropdown.
=> Dropdown: add dismissMenu handle to match Combobox

apps/public-docsite/src/styles/_base.scss
Seems a new MWF set of styles was added to our page recently (Yeah bootstrap). Most of the styles aren't an issue, but this one is pretty painful and confusing for docs consumers. 
Hopefully this hack is temporary as I have opened up a ticket with the MWF team to try to resolve this.
=> Override outline added by MWF

packages/react-spinbutton/src/components/SpinButton/useSpinButton.tsx, packages/react-spinbutton/src/components/SpinButton/useSpinButtonStyles.ts
This should only be merged after #22489 is merged.
The styles for the `underline`, `filledDarker` and `filledLighter` appearances are not complete.
The styles for the `underline`, `filledDarker` and `filledLighter` appearances are complete.
#22307
=> Spin button/alternate appearances

change/@fluentui-react-5855132c-df7c-48fb-a439-ba589755f330.json, packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap, packages/react/src/components/GroupedList/GroupHeader.styles.ts
=> More friendly behavior when GroupedList header is too long

packages/react-combobox/etc/react-combobox.api.md, packages/react-combobox/src/components/Combobox/Combobox.types.ts, packages/react-combobox/src/components/Combobox/useCombobox.ts, packages/react-combobox/src/utils/dropdownKeyActions.ts
This fixes a few behavior issues in Combobox vNext:
- The popup should dismiss on blur
- clicking listbox options shouldn't move focus away from the trigger
- Tabbing away from the open listbox should select the current item and close the listbox (previously it wasn't closing the listbox)
=> react-combobox: dismiss on blur, fix tab-to-select

change/@fluentui-react-components-cfd10498-0aa4-45a0-b27f-137c646d3073.json, packages/react-components/etc/react-components.api.md, packages/react-components/src/Concepts/SSR.stories.mdx, packages/react-components/src/index.ts
Restores an export for `SSRProvider` i.e. a regression introduced in #22367.
For context: `SSRProvider` is required for SSR configuration:
=> fix: restore SSRProvider export

packages/react-examples/src/react-charting/AreaChart/AreaChart.Basic.Example.tsx, packages/react-examples/src/react-charting/AreaChart/AreaChart.CustomAccessibility.Example.tsx, packages/react-examples/src/react-charting/AreaChart/AreaChart.Multiple.Example.tsx, packages/react-examples/src/react-charting/AreaChart/AreaChart.Styled.Example.tsx, packages/react-examples/src/react-charting/GroupedVerticalBarChart/GroupedVerticalBarChart.Basic.Example.tsx, packages/react-examples/src/react-charting/GroupedVerticalBarChart/GroupedVerticalBarChart.CustomAccessibility.Example.tsx, packages/react-examples/src/react-charting/GroupedVerticalBarChart/GroupedVerticalBarChart.Styled.Example.tsx, packages/react-examples/src/react-charting/GroupedVerticalBarChart/GroupedVerticalBarChart.Truncated.Example.tsx, packages/react-examples/src/react-charting/StackedBarChart/StackedBarChart.Multiple.Example.tsx, packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.Basic.Example.tsx, packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.Callout.Example.tsx, packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.CustomAccessibility.Example.tsx, packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.Styled.Example.tsx
ARIA input field does not have an accessible name, Id attribute values are not unique,
When focus is on any graph element, screen reader announces graphic clickable.
While I am checking by using accessibility we are getting this error(Please find in attached Screen shot). After this fix I checked again by using accessibility we are not getting that error.
ARIA input field does not have an accessible name issue.
Id attribute values are not unique.
When focus is on any graph element, screen reader announces graphic clickable.
Fixes #
Code changes for ARIA input field does not have an accessible name, Id attribute values are not unique,
When focus is on any graph element, screen reader announces graphic clickable. After this code It is working fine as epected.
Files changes in 
AreaChat, …
=> ARIA input field does not have an accessible name issue

apps/ts-minbar-test-react-components/package.json, apps/upgrade-examples-v8-v9/package.json
So that react-components will get bumped on release
Fixes partially https://github.com/microsoft/fluentui/issues/22559
=> fix: Bump ts-minbar-react-components to v9

change/@fluentui-react-components-90303c8d-8d65-4d7f-b703-6e3b33ee6153.json, change/@fluentui-react-spinbutton-ccaaea73-5c10-43b2-81d0-3ec98e4a70c0.json, packages/react-components/package.json, packages/react-components/src/unstable/index.ts, packages/react-spinbutton/package.json, packages/react-spinbutton/src/stories/SpinButton.stories.tsx
`SpinButton` is not accessible via `@fluentui/react-components/unstable`
`SpinButton` is accessible via `@fluentui/react-components/unstable`
Fixes #22307
=> react-components: add SpinButton to /unstable

change/@fluentui-react-fbe29567-6419-4977-b5b2-c5b9cbf29cc1.json, packages/react/src/components/Button/BaseButton.tsx, packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx
Related to #22499
This updates ContextualMenu to also apply the same mouse focus behavior to submenu open events.
=> ContextualMenu v8: update to focus submenu containers on click or hover

packages/priority-overflow/src/overflowManager.ts, packages/react-priority-overflow/src/useOverflowContainer.ts
Updated to use an object for the overflow options in the overflow managers.
This keeps the options in sync with those passed to observe.
=> Use options object in overflow manager

packages/react/src/components/ComboBox/ComboBox.test.tsx, packages/react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap
- v8 `Combobox` tests don't use testing-library
- Convert `Combobox` to fully use testing-library
part of #21663
=> Combobox (v8): convert tests to use testing-library

change/@fluentui-react-input-db8489dc-8d86-492d-b3ee-a17d1edb7d81.json, change/@fluentui-react-spinbutton-d3163b27-fa21-4821-ac4d-217e0d3488ab.json, packages/react-input/src/components/Input/useInputStyles.ts, packages/react-spinbutton/src/components/SpinButton/useSpinButtonStyles.ts
`Input` and `SpinButton` use the CSS2 `:after` pseudo element for styling.
`Input` and `SpinButton` use the CSS3 `::after` pseudo element for styling. [Both syntaxes are acceptable](https://developer.mozilla.org/en-US/docs/Web/CSS/::after) however as we target modern evergreen browsers we should exclusively use the more recent syntax.
Fixes #22365
=> Update react-input and react-spinbutton to use ::after pseudo element

change/@fluentui-react-button-f1c210ad-d683-4e21-984c-11b5f0acd349.json, packages/react-button/src/components/Button/useButtonStyles.ts, packages/react-button/src/components/CompoundButton/useCompoundButtonStyles.ts, packages/react-button/src/components/SplitButton/stories/SplitButtonDisabled.stories.tsx, packages/react-button/src/components/SplitButton/useSplitButtonStyles.ts, packages/react-button/src/components/ToggleButton/useToggleButtonStyles.ts
There are 2 problems with buttons right now:
- `:active` styles apply even when the mouse moves away while being held from the `Buttons`.
- A number of High Contrast styles in Button could be better:
- Hovering over or clicking the buttons triggers a change in border color but not in color. Clicking on the buttons also leaves the focus border highlighted until clicking outside of the button and hovering over it again or focusing into and away from it via the keyboard.
- Disabled focusable buttons look like regular buttons.
- Checked styles for all `ToggleButton` appearances are broken in High Contrast mode, as they remain exactly as if they were unchecked.
This PR does 2 things:
- Changes all of the `:active` styles to be `:hover:active` to better reflect what we actually want to style …
=> Button: Stop applying active styles when mouse moves away while it is being held and improving styles in High Contrast mode

packages/fluentui/CHANGELOG.md, packages/fluentui/react-northstar/src/components/Tree/TreeItem.tsx
Tree was stoping propagation of all letter key key down events, even if modifiers were used.
This was preventing shortcuts to work when the focus was inside of the tree.
=> fix(Tree): Do not stop propagation of letter keys if modifier is used

change/@fluentui-react-82502621-9430-4661-8986-3836b7ee7ce6.json, packages/react/src/components/DocumentCard/DocumentCardTitle.styles.ts, packages/react/src/components/DocumentCard/__snapshots__/DocumentCard.test.tsx.snap
Fixes #22608, related to #21461
DocumentCard received a previous a11y fix to move the focus target to the title element so it would be less verbose on focus, and so the focus target would have a logical role. This PR adds visible focus styles to the title component.
=> fix(DocumentCard): add focus styles to DocumentCardTitle

change/@fluentui-react-provider-87e7f793-4dae-4986-b27d-d120a8afe8c7.json, packages/react-provider/etc/react-provider.api.md, packages/react-provider/src/components/FluentProvider/index.ts, packages/react-provider/src/components/FluentProvider/useFluentProvider.ts, packages/react-provider/src/components/FluentProvider/useFluentProviderThemeStyleTag.test.ts, packages/react-provider/src/components/FluentProvider/useFluentProviderThemeStyleTag.ts, packages/react-provider/src/index.ts
- We don't use star re-export in `@fluentui/react-provider`
- `useThemeStyleTag` was renamed to `useFluentProviderThemeStyleTag`
- `useFluentProviderThemeStyleTag` is exported from `@fluentui/react-provider`
=> feat: export useFluentProviderThemeStyleTag from @fluentui/react-provider

tools/generators/migrate-converged-pkg/index.spec.ts, tools/generators/migrate-converged-pkg/index.ts, tsconfig.base.json
migration are executed on applications, which is invalid. we don't provide yet new DX setup for apps
migration executed on application will bail out with proper message and apply only limited supported set of migrations (codeowners only atm if `--owner` provided)
=> fix(tools): don't run invalid migrations on application

tools/generators/move-packages/index.spec.ts, tools/generators/move-packages/index.ts
The `move-packages` nx generator was not updating the CODEOWNERS file with the moved package's new relative path
`move-packages` generator now updates CODEOWNERS file after package move.
Follow-up to https://github.com/microsoft/fluentui/pull/22506#discussion_r857426868
=> fix(tools): update CODEOWNERS relative path of moved package

tools/generators/migrate-converged-pkg/index.spec.ts, tools/generators/migrate-converged-pkg/index.ts, tools/generators/migrate-v8-pkg/index.spec.ts, tools/generators/migrate-v8-pkg/index.ts, tools/generators/print-stats.spec.ts, tools/generators/print-stats.ts, tools/tsconfig.tools.json, tsconfig.base.json
v8 and converged migration generator:
- implement `--stats` on its own
- implement `is*` check on its own
- don't distinguish between applications and libraries when `--stats` flag is used 
- leverages encapsulated `is*` from utils
- `printStats` is now generic function
- more terminal colors
- distinguish applications and libraries
=> refactor(tools): make --stats printer generic

yarn.lock
Bumping version of async & y18n being used to avoid prototype polution
https://github.com/advisories/GHSA-fwr7-v2mv-hh25
https://github.com/advisories/GHSA-c4w7-xm78-47vh
=> update async and y18n package versions

tools/generators/migrate-converged-pkg/index.spec.ts, tools/generators/migrate-converged-pkg/index.ts, workspace.json
- migration generator treats any package in same way
- react-conformance-griffel has status as not migrated
- migration generator sets things based on platform
- react-conformance-griffel has status as migrated
- https://github.com/microsoft/fluentui/pull/22510/files/3e82ece6493d6d4cfc7d4b83fa30c5dd585430b6#diff-53d041a38d55bd0f14d2fcfb1d909be13108d8901d833876a0c8d643c9832f67
- https://github.com/microsoft/fluentui/pull/22510/files/d89c99862b1b374572290a7b84ae2411dca75b5a#diff-8e22a885f81c0e7971ea263553a27a4b947e1973a34f649d4768472a8e59338a
=> fix(tools): differentiate migration based on platform

change/@fluentui-react-6ef35ff6-9b12-444f-873e-eb578898da24.json, packages/react-examples/src/react/ContextualMenu/ContextualMenu.Checkmarks.Example.tsx, packages/react/src/components/ContextualMenu/ContextualMenu.cnstyles.ts
Fixes #22640
ForcedColorAdust: none was unnecessary and breaking disabled icon styles in high contrast
=> Contextualmenu disabled hcm checkmarks

change/@fluentui-react-d8a0826d-8dde-4ea4-95ac-c3ee3d2f43c3.json, packages/react-experiments/src/components/MicroFeedback/__snapshots__/MicroFeedback.test.tsx.snap, packages/react-experiments/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap, packages/react-experiments/src/components/SelectedItemsList/SelectedPeopleList/__snapshots__/SelectedPeopleList.test.tsx.snap, packages/react-experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/__snapshots__/UnifiedPeoplePicker.test.tsx.snap, packages/react/src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, packages/react/src/components/Button/BaseButton.styles.ts, packages/react/src/components/Button/__snapshots__/Button.deprecated.test.tsx.snap, packages/react/src/components/Button/__snapshots__/Button.test.tsx.snap, packages/react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap, packages/react/src/components/CommandBar/__snapshots__/CommandBar.deprecated.test.tsx.snap, packages/react/src/components/CommandBar/__snapshots__/CommandBar.test.tsx.snap, packages/react/src/components/ContextualMenu/__snapshots__/ContextualMenu.test.tsx.snap, packages/react/src/components/Dialog/__snapshots__/Dialog.deprecated.test.tsx.snap, packages/react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/react/src/components/Facepile/__snapshots__/Facepile.test.tsx.snap, packages/react/src/components/Nav/__snapshots__/Nav.test.tsx.snap, packages/react/src/components/Panel/__snapshots__/Panel.test.tsx.snap, packages/react/src/components/Pivot/__snapshots__/Pivot.deprecated.test.tsx.snap, packages/react/src/components/Pivot/__snapshots__/Pivot.test.tsx.snap, packages/react/src/components/SpinButton/__snapshots__/SpinButton.test.tsx.snap, packages/react/src/components/SwatchColorPicker/__snapshots__/SwatchColorPicker.test.tsx.snap, packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.deprecated.test.tsx.snap, packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.test.tsx.snap, packages/react/src/components/pickers/PeoplePicker/__snapshots__/PeoplePicker.test.tsx.snap, packages/react/src/components/pickers/Suggestions/__snapshots__/Suggestions.test.tsx.snap, packages/react/src/components/pickers/TagPicker/__snapshots__/TagItem.test.tsx.snap, packages/react/src/components/pickers/TagPicker/__snapshots__/TagPicker.test.tsx.snap
Fixes #21677
Button's first child is always the flexContainer span, so using a star is unnecessary and causing perf issues in some situations.
=> change ie11 fix from star selector to span 

packages/fluentui/CHANGELOG.md, packages/fluentui/react-northstar/src/themes/teams-dark/components/Divider/dividerVariables.ts, packages/fluentui/react-northstar/src/themes/teams/components/Divider/dividerVariables.ts
Default @fluentui/react-northstar Divider has color #ebebeb in light theme and #3d3d3d in dark theme.
This PR updated it to use brand.border token, which has #e0e0e0 in light theme and #525252 in dark theme, same as  @fluentui/react-components Divider
Result:
=> change neutral Divider color in light and dark theme

change/@fluentui-react-4b2eeb3d-df1a-4f18-9cda-e1145636a051.json, change/@fluentui-react-83c86ed8-da9c-4d2d-b8a1-e051c49408d6.json, packages/react-experiments/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap, packages/react/src/components/Calendar/CalendarDay/CalendarDay.base.tsx, packages/react/src/components/Calendar/CalendarMonth/CalendarMonth.base.tsx, packages/react/src/components/Calendar/CalendarYear/CalendarYear.base.tsx, packages/react/src/components/ComboBox/ComboBox.tsx, packages/react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap
Reverts microsoft/fluentui#22613
See comment: https://github.com/microsoft/fluentui/pull/22613#issuecomment-1110139831
Edit: this also adds a fix for the JAWS issue of ignoring the live regions in Calendar. It turns out that JAWS doesn't respect `aria-live` on button elements, so I moved it to a span within the button.
=> Revert "Fix screen reader issues in calendar navigation buttons and combobox"

scripts/create-package/plopfile.ts, tools/generators/migrate-converged-pkg/index.spec.ts, tools/generators/migrate-converged-pkg/index.ts
- Updates `create-package` script to account for new v9 common folder.
- Updates `migrate-converged-pkg` generator's relative path imports.
Part of #22427
=> (chore) Update create-package script to account for new v9 common folder

change/@fluentui-web-components-949d9317-57e4-4c8d-9387-e6d1877892d4.json, packages/web-components/package.json, yarn.lock
Updates to the latest version of FAST dependencies.
n/a
n/a
Fixes #
=> update to latest versions of fast-element and fast-foundation for web components

apps/public-docsite-v9/.storybook/preview.js, change/@fluentui-react-components-961b7c91-fee6-4aa4-aa99-cf134e248438.json, packages/react-components/react-components/.storybook/preview.js
For SOME reason, the storybook-react-addon is not working on Mac. We didn't notice this before because we were adding a 2nd theme provider decorator from the storybook-react package. I removed that decorator seeing it as redundant (2 of them show up on PC), but this obvious broke mac development and mac deployment of chromatic. 
This PR pulls that decorator back in, and I will open an issue to track the mac compat issue with storybook-react-addons
=> Storybook: fix theme for local mac development

change/@fluentui-react-components-49a401dc-2ff5-47c7-b83e-831d44a16fde.json, package.json, packages/react-components/react-components/package.json
With the website being built out of the new public-docsite-v9 package, there's no need for the chromatic command in react-components. I also created an alias at the root to make publishing easier/more obvious. Maybe have a different name at the root? Or is it even necessary?
=> Remove chromatic command from react-components and move alias up to root

change/@fluentui-react-radio-996aa647-972f-4498-8cb5-e22527f7a82e.json, packages/react-radio/bundle-size/Radio.fixture.js, packages/react-radio/bundle-size/RadioGroup.fixture.js, packages/react-radio/package.json
`react-radio` package did not have bundle size fixtures.
`react-radio` package does have bundle size fixtures.
#19953
=> react-radio: add bundle size fixtures

change/@fluentui-react-radio-c738372a-484c-42ab-b64c-20287e3f4373.json, packages/react-radio/README.md
`react-radio` only had the generated boilerplate readme.
`react-radio` now has a readme with basic usage and links to other relevant information.
#19953
=> react-radio: write readme

tools/generators/generate-change-file.spec.ts, tools/generators/generate-change-files.ts, tools/generators/migrate-converged-pkg/index.spec.ts, tools/generators/migrate-converged-pkg/index.ts, tools/generators/migrate-converged-pkg/schema.json, tools/generators/print-stats.spec.ts, tools/utils-testing.ts, tools/utils.spec.ts, tools/utils.ts
After migration is executed, user is missing instructions regarding change files. Based on lack of user knowledge of beachball apis, if we run migration on many packages we might end up manually going through beachball prompts which tend to be very tedious manual work. 
After migration execution, if there are any changed files in particular package, generator will provide command that user should invoke on his convenience, which will create change files if needed for all packages that have been affected.
- This PR also adds more tests for tools and fixes redundant console spam created by userLogs
=> feat(tools): provide instructions how to generate change files in batch

change/@fluentui-react-components-2bd5794e-c0db-4859-9af4-86499b5eca4f.json, packages/react-components/react-components/config/api-extractor.local.json, tools/generators/move-packages/index.spec.ts, tools/generators/move-packages/index.ts
- after migration of `react-components` to `react-components` parent folder `build:local` is broken
- `local:build` works
- `move` generator has been updated to accommodate this behaviour for other packages
- updates `react-components` tsConfig override in api extractor config
Fixes #21910
=> chore(react-components): fix build:local task

.github/CODEOWNERS
`react-radio` only had group ownership in codeowners.
`react-radio` now has two people as codeowners in addition to group ownership.
#19953
=> react-radio: add codeowners

change/@fluentui-react-accordion-4b219078-bd35-477b-815a-330d208e8765.json, packages/react-accordion/src/index.ts
`react-accordion` has star exports.
`react-accordion` does not have star exports.
#22099
=> react-accordion: remove star exports

packages/priority-overflow/src/index.ts
`priority-overflow` uses star exports
`priority-overflow` does not use star exports.
#22099
=> priority-overflow: remove star exports

packages/fluentui/CHANGELOG.md, packages/fluentui/react-northstar/src/themes/teams-high-contrast/components/Tooltip/tooltipContentVariables.ts, packages/fluentui/react-northstar/src/themes/teams/components/Tooltip/tooltipContentStyles.ts, packages/fluentui/react-northstar/src/themes/teams/components/Tooltip/tooltipContentVariables.ts
Fix subtle=false style.
Before:
After
Fix pointing style.
Before:
After:
=> fix(Tooltip): fix contrast theme pointing and subtle=false style

apps/public-docsite-v9/src/Concepts/Upgrade/FromV8/Components/Button.stories.mdx, apps/public-docsite-v9/src/Concepts/Upgrade/FromV8/Components/Menu.stories.mdx, apps/public-docsite-v9/src/stories/ButtonShim.stories.tsx, apps/public-docsite-v9/src/stories/StackShim.stories.tsx
- Moved shim stories under a common shims folder (instead of Button/Shims and Stack/Shims => Shims/Button and Shims/Stack)
- Added Button upgrade doc
- Added Menu upgrade doc
Update #22314
=> Added button and menu upgrade docs

apps/public-docsite-v9/src/shims/ThemeShim/themeDuplicates.ts, apps/public-docsite-v9/src/shims/ThemeShim/v8ThemeShim.ts, apps/public-docsite-v9/src/shims/ThemeShim/v9BrandVariantsShim.ts, apps/public-docsite-v9/src/shims/ThemeShim/v9ThemeShim.ts
- added shim methods to create a v8 theme based on a v8 theme
- added shim methods to create a v9 theme based on a v8 theme
- added shim methods to create a v9 brand ramp from a v8 palette
This PR only adds the shim methods, a future PR will leverage them in documentation to show the mapping and usage.
Updates #22315
=> Ported theme shims from upgrade repo

change/@fluentui-react-label-2d71a384-d1d7-481a-981a-cca5c1d36703.json, packages/react-components/react-label/src/components/Label/useLabelStyles.ts, packages/react-components/react-label/src/stories/LabelDisabled.stories.tsx
Added styles to required slot to make it match text when disabled. This came up during a discussion with design yesterday. Figma was just updated to reflect the change.
I also updated the disabled example to include the required asterix to demonstrate that both slots change color
=> Label disabled required

change/@fluentui-react-link-004dabf8-63c0-47f6-99ef-5358546dd232.json, packages/react-components/react-link/src/components/Link/useLinkStyles.ts
The `Link` component has some styles when focused that do not adhere with the design spec (see related issues for more info).
The `Link` component styles when focused adhere to the design spec.
Fixes #22723
Fixes #22730
=> Link: Changing styles of focused links to align with design spec

change/@fluentui-react-components-0a011e91-2812-4c84-81b2-97aab3f0abc8.json, packages/react-components/react-components/etc/react-components.api.md, packages/react-components/react-components/package.json, packages/react-components/react-components/src/index.ts
Currently none of the types in `@fluentui/react-positioning` are exported from react-components.
Since we have a common `positioning` prop for all positioned components in v9, we should at least export `PositioningProps` and/or other types like `PositioningShorthandValue` that we expect consumers to use when configuring positioned components.
Fixes #21669
=> feat: re-exports positioning types at `react-components`

change/@fluentui-react-tabster-ad843a71-13a9-4633-862f-9eea9c57a59d.json, packages/react-tabster/e2e/useKeyborg.e2e.tsx, packages/react-tabster/etc/react-tabster.api.md, packages/react-tabster/src/focus/constants.ts, packages/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts, packages/react-tabster/src/focus/createFocusOutlineStyle.ts, packages/react-tabster/src/focus/index.ts, packages/react-tabster/src/hooks/index.ts, packages/react-tabster/src/hooks/useKeyboardNavAttribute.ts, packages/react-tabster/src/index.ts
`createCustomFocusIndicatorStyle` and `createFocusOutlineStyle` functions are being exported from `hooks/useFocusIndicatorStyle.ts` file, which is a legacy of the first implementation of focus indicator, which was actually a hook.
Moves `createCustomFocusIndicatorStyle` and `createFocusOutlineStyle` to `focus/createCustomFocusIndicatorStyle.ts` and `focus/createFocusOutlineStyle.ts` and delete `hooks/useFocusIndicatorStyle.ts`
This PR also resolves some typings that weren't _clear_
=> chore: moves focus indicator from hooks folder to it's own

change/@fluentui-react-components-34ab5d49-a13c-40f0-816e-7acfa0abf28e.json, packages/react-components/react-components/etc/react-components.api.md, packages/react-components/react-components/src/index.ts
`createFocusOutlineStyle` is not being exported by `@fluentui/react-components`
1. re-export `createFocusOutlineStyle`  by `@fluentui/react-components`
2. export types from focus indicator methods on `@fluentui/react-components`
=> feat: re-export `createFocusOutlineStyle` on `react-components`

yarn-ci.sh
install on CI won't fail if yarn.lock is not up to date
install on CI will fail if yarn.lock is not up to date
=> ci: enable yarn frozen lockfile during install

packages/react-components/react-card/src/stories/CardDefault.stories.tsx, packages/react-components/react-card/src/stories/SampleCard.stories.tsx
Story asset URL is still pointing to the old path
Story asset URL now pointing to /react-components/react-card
#22692
=> fix(react-card): change storybook asset url

change/@fluentui-react-tabs-f12ca354-ca30-43bf-8733-26ae7890102b.json, packages/react-components/react-tabs/src/components/Tab/useTabStyles.ts
- Selection indicators are specified to be a particular stroke width.
- We used borders rather than background for selection indicators to allow for system high contrast mode to automatically update border colors.
- The border width of the selection indicators is the stroke width / 2.0.
- Due to some stroke widths being odd numbers, this create sub-pixel border widths.
- When the border widths were rendered they ended up being floor values and so a small gap would show because the height or width was set to the stroke width.
- Set the width and height CSS values from the pending and active selection indicator to 0
Fixes #22743
=> react-tabs: fix indicator gap

change/@fluentui-react-input-e61e5457-520b-43b6-b42f-75e3b50ede61.json, packages/react-components/react-input/src/components/Input/useInputStyles.ts, packages/react-components/react-input/src/stories/InputAppearance.stories.tsx, packages/react-components/react-input/src/stories/InputContentBeforeAfter.stories.tsx, packages/react-components/react-input/src/stories/InputDefault.stories.tsx, packages/react-components/react-input/src/stories/InputDisabled.stories.tsx, packages/react-components/react-input/src/stories/InputInline.stories.tsx, packages/react-components/react-input/src/stories/InputPlaceholder.stories.tsx, packages/react-components/react-input/src/stories/InputSize.stories.tsx, packages/react-components/react-input/src/stories/InputType.stories.tsx
- Input's `contentBefore` and `contentAfter` stories did not show how to use these slots in an accessible manner.
- Placeholder story lacked a visual label, but did have `aria-label` set.
- Input's `contentBefore` and `contentAfter` demonstrate simple examples of how to use these slots accessibly.
- Placeholder story has a visual label.
- Labels used in stories have been received minor copy updates
- #21174
- #18131
Fixes #21450
=> Input: Update Content Before and After Stories, Labels on Stories

apps/public-docsite-v9/src/Concepts/Upgrade/FromV0/Components/RadioGroup.stories.mdx, apps/public-docsite-v9/src/Concepts/Upgrade/FromV8/Components/RadioGroup.stories.mdx
No migration guide from v8/v0 to v9 for Radio/RadioGroup.
Migration guide from v8/v0 to Radio/RadioGroup
Fixes #22678
=> react-radio: add migration guide

yarn.lock
upgrade yarn lock to use latest release of fabric core
After this i'll be cherrypicking to the v7 branch
=> update yarn to use latest version of fabric core

change/@fluentui-cra-template-d2c1dcf7-33f1-427f-8c95-94e1c77b959f.json, packages/cra-template/template.json
Our packages do not yet support React 18, and therefore our CRA template fails because it now defaults to React 18. This PR changes the installed version of React to 17, and allows @fluentui/react to properly be installed.
This doesn't fix #22241, but it at least helps users avoid it when installing with our template.
=> set specific version of react to be used in cra-template

packages/fluentui/CHANGELOG.md, packages/fluentui/docs/src/components/ComponentPlayground/componentGenerators.tsx, packages/fluentui/docs/src/examples/components/Embed/Slots/EmbedExampleVideo.shorthand.tsx, packages/fluentui/docs/src/examples/components/Video/Types/VideoExample.shorthand.tsx
Use `https` links in the Embed examples to fix "Unsecure Site" warnings:
fyi @TanelVari
=> Use https for Embed and Video examples

apps/public-docsite/src/SiteDefinition/SiteDefinition.tsx
This PR remove the v8 release banner from the public docsite.
Fixes #22418
=> public-docsite: Removing v8 release banner

packages/react-components/react-link/src/stories/LinkAppearance.stories.tsx, packages/react-components/react-link/src/stories/LinkDefault.stories.tsx, packages/react-components/react-link/src/stories/LinkDisabled.stories.tsx, packages/react-components/react-link/src/stories/LinkDisabledFocusable.stories.tsx, packages/react-components/react-link/src/stories/LinkInline.stories.tsx
`Link` stories didn't have `hrefs` which made them render as `buttons`.
`Link` stories now have `hrefs` (except for the render as button one) which makes them render as `a` tags and more correctly reflect their usage.
Fixes [13993](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/13993)
=> Link: Adding hrefs to all non-button stories

packages/react-examples/src/react/ContextualMenu/ContextualMenu.CustomMenuList.Example.tsx
This PR fixes the example `CustomMenuList` from ContextualMenu where filtering the menu list removes the link item. This is due to the menu item using the property `name` instead of `text`.
Link disappears out of the list after filtering the list due to using the deprecated `name` instead of `text`.
Link will not disappear after being filtered.
Fixes #21256
=> docs: Removing deprecated attribute from ContextualMenu's example

change/@fluentui-react-radio-eec73af1-4507-40ff-990d-62a0622eddeb.json, packages/react-radio/etc/react-radio.api.md, packages/react-radio/src/components/Radio/Radio.types.ts
`Radio.onChange(event, data)` results in typescript error, `data` argument is not allowed:
```
TS2322: Type '(e: ChangeEvent<HTMLInputElement>, d: RadioOnChangeData) => void' is not assignable to type 'ChangeEventHandler<HTMLInputElement> & ((ev: ChangeEvent<HTMLInputElement>, data: RadioOnChangeData) => void)'.   Type '(e: ChangeEvent<HTMLInputElement>, d: RadioOnChangeData) => void' is not assignable to type 'ChangeEventHandler<HTMLInputElement>'.  index.d.ts(2217, 9): The expected type comes from property 'onChange' which is declared here on type 'IntrinsicAttributes & Omit<ComponentProps<Partial<RadioSlots>, "input">, "size"> & { value?: string | undefined; labelPosition?: "after" | ... 1 more ... | undefined; disabled?: boolean | undefined; onChange?: ((ev: ChangeEvent<...>, data: …
```
=> fix(react-radio): Allow data argument on onChange

change/@fluentui-react-theme-9792ecee-1054-4af0-931b-e7dd60820b8f.json, packages/react-theme/src/alias/darkColor.ts, packages/react-theme/src/alias/teamsDarkColor.ts
Update alias color tokens.
**1) Brand stroke** (Dark theme slot to be Brand 100)
**2) Compound Brand Background** (Dark theme slot)
Fixes #22685
=> fix(react-theme): Update CompoundBrandBackground and BrandStroke1

apps/vr-tests-react-components/src/stories/Card.stories.tsx
Due to the moving of the package, the usage of hardcoded absolute URLs to access GitHub raw assets in our stories is using the wrong path.
Path now accounts for the `react-components/` move.
#22692
=> fix(react-card): add `react-components` to vr-tests asset path

rfcs/react-components/convergence/high-contrast-theme.md
Updates guidance for high contrast support in Fluent UI. Emphasizes that
the library supports windows high contrast mode by default and explains
the context behind the hard coded high contrast theme
=> RFC: Update High contrast mode guidance

packages/react-utilities/src/compose/types.test.ts
`Slot` is non trivial mapped type without any testing coverage
`Slot` has some type check tests coverage
This also exposes issue found in https://github.com/microsoft/fluentui/pull/22633
=> chore(react-utilities): add Slot mapped type tests

apps/public-docsite-v9/src/Concepts/Upgrade/FromV8/Components/RadioGroup.stories.mdx
- There is some inconsistency between v8 and v9 examples
- Missed from v8 ChoiceGroupOption -> v9 Radio props
- Improve consistency between v8 and v9 examples
- Add more v8->v9 prop mappings for ChoiceGroupOption -> Radio
=> react-radio: improve migration guide

packages/react-radio/src/stories/RadioGroup.stories.tsx, packages/react-radio/src/stories/RadioGroupControlledValue.stories.tsx, packages/react-radio/src/stories/RadioGroupDefault.stories.tsx, packages/react-radio/src/stories/RadioGroupDisabled.stories.tsx, packages/react-radio/src/stories/RadioGroupDisabledItem.stories.tsx, packages/react-radio/src/stories/RadioGroupHorizontal.stories.tsx, packages/react-radio/src/stories/RadioGroupHorizontalStacked.stories.tsx, packages/react-radio/src/stories/RadioGroupLabelSubtext.stories.tsx, packages/react-radio/src/stories/RadioGroupLabeled.stories.tsx, packages/react-radio/src/stories/RadioGroupRequired.stories.tsx, packages/react-radio/src/stories/RadioGroupUncontrolledValue.stories.tsx
`Radio` examples lack clear labels.
`Radio` example labels are updated to select from a list of fruits. This allows the `RadioGroup` label examples to be clearer and more realistic than "Option" while still being simple to understand.
Additionally, a new story demonstrating how to mark a group as required has been added.
Fixes #22770
=> react-radio: update labels in examples

change/@fluentui-react-popover-02cd6106-6a48-483d-91df-6df652f6b43b.json, packages/react-components/react-popover/e2e/Popover.e2e.tsx, packages/react-components/react-popover/etc/react-popover.api.md, packages/react-components/react-popover/src/common/mockUsePopoverContext.ts, packages/react-components/react-popover/src/components/Popover/Popover.types.ts, packages/react-components/react-popover/src/components/Popover/renderPopover.tsx, packages/react-components/react-popover/src/components/Popover/usePopover.ts, packages/react-components/react-popover/src/components/PopoverSurface/PopoverSurface.types.ts, packages/react-components/react-popover/src/components/PopoverSurface/renderPopoverSurface.tsx, packages/react-components/react-popover/src/components/PopoverSurface/usePopoverSurface.ts, packages/react-components/react-popover/src/popoverContext.ts, packages/react-components/react-popover/src/stories/PopoverDefault.stories.tsx
There is no way to render a Popover in DOM order
Setting the `inline` prop will render the Popover in DOM order consistent with what Menu does
=> feat: Add inline prop to Popover

packages/react-components/react-tabs/src/stories/TabList.stories.tsx, packages/react-components/react-tabs/src/stories/TabListWithPanels.stories.tsx
- Added story to demonstrate showing/hiding UI as tab selection changes
Fixes #22002
=> react-tabs: Added story for tab panels

.storybook/docs-root.css
fixes #22773
After removing z-index, the jump link pseudo element pushed the H3 up and covered the button (this often effects the code sandbox button as well).
So I reduced the offset of the psuedo element and increase the margin just enough that the H3 height stopped at the bottom of the previous example (color added for visibility)
jump links still leave space
=> Storybook: Remove z-index from show code button

apps/public-docsite-v9/src/Concepts/Upgrade/FromV0/Components/Input.stories.mdx, apps/public-docsite-v9/src/Concepts/Upgrade/FromV0/Components/RadioGroup.stories.mdx, apps/public-docsite-v9/src/Concepts/Upgrade/FromV8/Components/Input.stories.mdx
There is no upgrade guide for 
1. v8 `TextField` to v9 `Input`
2. v0 `Input` to v9 `Input`
There is an upgrade guide for 
1. v8 `TextField` to v9 `Input`
2. v0 `Input` to v9 `Input`
Fixes #22769
=> Input: Writing migration guide from v0 and v8

change/@fluentui-react-radio-28f564dd-9c08-42ff-bda1-827bf93e7d58.json, packages/react-radio/etc/react-radio.api.md, packages/react-radio/package.json, packages/react-radio/src/components/Radio/useRadio.tsx, packages/react-radio/src/components/RadioGroup/RadioGroup.tsx, packages/react-radio/src/components/RadioGroup/RadioGroup.types.ts, packages/react-radio/src/components/RadioGroup/renderRadioGroup.tsx, packages/react-radio/src/components/RadioGroup/useRadioGroup.ts, packages/react-radio/src/contexts/RadioGroupContext.ts, packages/react-radio/src/contexts/useRadioGroupContextValues.ts, packages/react-radio/src/index.ts
`RadioGroup` passes context to its render function via state.
Context is removed from `RadioGroup` state and passed into its render function as a separate object.
- [Tablist](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-tabs/src/components/TabList/TabList.tsx#L17)
Fixes #22100
=> react-radio: update context usage

change/@fluentui-react-radio-a22e2729-5ad0-485c-b919-8e7284539d2d.json, packages/react-radio/etc/react-radio.api.md, packages/react-radio/src/components/Radio/useRadio.tsx, packages/react-radio/src/components/RadioGroup/RadioGroup.test.tsx, packages/react-radio/src/components/RadioGroup/RadioGroup.types.ts, packages/react-radio/src/components/RadioGroup/useRadioGroup.ts, packages/react-radio/src/contexts/useRadioGroupContextValues.ts, packages/react-radio/src/stories/RadioGroupRequired.stories.tsx
`RadioGroup` lacks a `required` prop so each individual child `Radio` must set its `required` prop to make a group required.
`RadioGroup` has a `required` prop that is passed down to all child `Radio`s via context.
Fixes #22766
=> Radio: Add `required` prop to `RadioGroup`

change/@fluentui-react-switch-6e25e7c6-b270-4622-bd00-745aab81504f.json, packages/react-switch/src/components/Switch/useSwitchStyles.ts
Disabled `Switches` are indistinguishable from enabled ones in High Contrast mode:
Disabled `Switches` are styled using `GrayText` so they are immediately distinguishable from enabled ones in High Contrast mode:
Fixes #22815
=> Switch: Fixing disabled styles in high contrast mode

packages/react-switch/src/stories/SwitchDefault.stories.tsx
The default `Switch` story lacks a label which makes the story not accessible.
This PR adds a label to the default `Switch` story to make it accessible.
Fixes #22816
=> Switch: Adding label to Default story so that it is accessible

change/@fluentui-react-popover-bcf50908-8e7f-47c7-a52e-fc80f8804a08.json, packages/react-components/react-popover/Spec.md, packages/react-components/react-popover/e2e/Popover.e2e.tsx, packages/react-components/react-popover/src/components/Popover/Popover.types.ts, packages/react-components/react-popover/src/components/Popover/usePopover.ts
When it's specified, popover will be closed when scrolling happens outside of the popover content and trigger.
When nested popover is inside a scrollable container, scrolling can cause popup content to appear detached from trigger.
Example https://codesandbox.io/s/fluent-ui-example-forked-y6i2e3?file=/example.js
This happens because trigger element is rendered outside of scrollable container, and floatingui is not able to find the scrollable container from trigger element.
In v0 this is fixed by adding `closeOnScroll`. This PR does the same for v9.
=> react-popover: new prop `closeOnScroll` to close popover on scrolling outside

change/@fluentui-react-input-28ae7024-b1a0-4cc9-adcd-7b8a7a719c4a.json, packages/react-components/react-input/src/components/Input/useInputStyles.ts
- Updated input styles to use shared tokens from react-theme
Updates #22231
=> react-input: Updated to use new shared tokens

change/@fluentui-react-aria-0f6b0cd4-dab6-46e2-b058-e2dba0b37f18.json, packages/react-components/react-aria/src/index.ts
`react-aria` has `export * from ...` in `src/index.ts`.
`react-aria` has explicitly named exports in `src/index.ts`.
#22099
=> Removing star exports from @fluentui/react-aria

change/@fluentui-react-context-selector-7537040f-fdc5-4767-af02-d8af6be7cfbe.json, packages/react-components/react-context-selector/src/index.ts
`react-context-selector` has `export * from ...` in `src/index.ts`.
`react-context-selector` has explicitly named exports in `src/index.ts`.
#22099
=> Removing star exports from @fluentui/react-context-selector

change/@fluentui-react-menu-394468ee-99e0-459a-a148-34743656d75b.json, packages/react-components/react-menu/src/index.ts
`react-menu` has `export * from ...` in `src/index.ts`.
`react-menu` has explicitly named exports in `src/index.ts`.
#22099
=> Removing star exports from @fluentui/react-menu

change/@fluentui-react-popover-6cc52f6e-7bd8-43e4-8fb6-09c55835caaa.json, packages/react-components/react-popover/src/index.ts
`react-popover` has `export * from ...` in `src/index.ts`.
`react-popover` has explicitly named exports in `src/index.ts`.
#22099
=> Removing star exports from @fluentui/react-popover

change/@fluentui-react-portal-eb79eb2d-3fec-4001-b4a7-145f781fbaa7.json, packages/react-components/react-portal/src/index.ts
`react-portal` has `export * from ...` in `src/index.ts`.
`react-portal` has explicitly named exports in `src/index.ts`.
#22099
=> Removing star exports from @fluentui/react-portal

change/@fluentui-react-positioning-1c708a83-6c21-43a5-a086-d7efcede45ee.json, packages/react-components/react-positioning/src/index.ts
`react-positioning` has `export * from ...` in `src/index.ts`.
`react-positioning` has explicitly named exports in `src/index.ts`.
#22099
=> Removing star exports from @fluentui/react-positioning

change/@fluentui-react-shared-contexts-f4ca11af-26f3-4154-aaaf-80a1429661ac.json, packages/react-shared-contexts/src/index.ts
`react-shared-contexts` has `export * from ...` in `src/index.ts`.
`react-shared-contexts` has explicitly named exports in `src/index.ts`.
#22099
=> Removing star exports from @fluentui/react-shared-contexts

change/@fluentui-react-theme-8b4f6828-3b50-4af4-bb43-73b2ce6b3090.json, packages/react-components/react-theme/src/index.ts
`react-theme` has `export * from ...` in `src/index.ts`.
`react-theme` has explicitly named exports in `src/index.ts`.
#22099
=> Removing star exports from @fluentui/react-theme

packages/react-components/react-toolbar/src/index.ts
`react-toolbar` has `export * from ...` in `src/index.ts`.
`react-toolbar` has explicitly named exports in `src/index.ts`.
#22099
=> Removing star exports from @fluentui/react-toolbar

packages/react-components/react-select/src/index.ts
`react-select` has `export * from ...` in `src/index.ts`.
`react-select` has explicitly named exports in `src/index.ts`.
#22099
=> Removing star exports from @fluentui/react-select

packages/react-combobox/src/index.ts
`react-combobox` has `export * from ...` in `src/index.ts`.
`react-combobox` has explicitly named exports in `src/index.ts`.
#22099
=> Removing star exports from @fluentui/react-combobox

apps/vr-tests-react-components/package.json, change/@fluentui-react-components-6a2426f9-9054-47fa-98c0-88d7bc0e2992.json, change/@fluentui-react-radio-de2c632e-259d-43ad-89cf-564df759b82b.json, packages/react-components/react-components/etc/react-components.api.md, packages/react-components/react-components/etc/react-components.unstable.api.md, packages/react-components/react-components/package.json, packages/react-components/react-components/src/index.ts, packages/react-components/react-components/src/unstable/index.ts, packages/react-radio/README.md, packages/react-radio/etc/react-radio.api.md, packages/react-radio/package.json, packages/react-radio/src/contexts/index.ts, packages/react-radio/src/index.ts, packages/react-radio/src/stories/RadioGroup.stories.tsx
`Radio` and `RadioGroup` are exported from `@fluentui/react-components/unstable`
1. `Radio` and `RadioGroup` are exported from `@fluentui/react-components` and not from /unstable
2. Story location for RadioGroup is updated in Storybook
3. Radio README.md demonstrates how to import controls from `@fluentui/react-components` 
Fixes #22680
=> Radio and RadioGroup: Move to Release Candidate

apps/public-docsite-v9/src/Concepts/Upgrade/FromV0/Components/RadioGroup.stories.mdx, apps/public-docsite-v9/src/Concepts/Upgrade/FromV8/Components/RadioGroup.stories.mdx
Upgrade guide shows how to import Radio from `@fluentui/react-components/unstable`
Upgrade guide show how to import Radio from `@fluentui/react-components`
=> Radio: update v9 upgrade examples

apps/public-docsite-v9/src/Concepts/Upgrade/FromV0/Components/Label.stories.mdx, apps/public-docsite-v9/src/Concepts/Upgrade/FromV8/Components/Label.stories.mdx, packages/react-components/react-label/src/stories/LabelSize.stories.tsx, packages/react-components/react-label/src/stories/LabelStrong.stories.tsx
- Upgrade guides from v8->v9 and v0->v9.
- Fixes minor typos in label stories.
=> react-label: Adding upgrade guidance for Label and fixing minor typos in stories

change/@fluentui-react-components-7c6772c6-71f1-4dd4-bbd1-a1429d1e491c.json, packages/react-components/react-components/etc/react-components.api.md, packages/react-components/react-components/src/index.ts
`GriffelStyle` is exported from `@griffel/react` but not from `@fluentui/react-components`, meaning that people wanting to type objects to spread in `makeStyles` calls have to take a dependency on `@griffel/react`.
`GriffelStyle` is re-exported in `@fluentui/react-components`, meaning that people wanting to type objects to spread in `makeStyles` calls don't have to take a dependency on `@griffel/react`.
=> Re-exporting GriffelStyle in @fluentui/react-components

change/@fluentui-react-utilities-84a6b1af-e457-4e58-b948-078b64bc46c7.json, packages/react-components/react-utilities/src/utils/getNativeElementProps.ts, packages/react-components/react-utilities/src/utils/properties.ts
`getNativeElementProps` doesn't support [<time> element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time)
Adds `<time>` element and it's properties to `getNativeElementProps`
=> feat: add time element on nativeElementMap

change/@fluentui-react-components-cfddd7d4-0c30-425c-88bd-5fe3a4f09453.json, change/@fluentui-react-theme-84c82566-de8b-43d7-9e67-49ae3cbae176.json, packages/react-components/react-components/etc/react-components.api.md, packages/react-components/react-components/src/index.ts, packages/react-components/react-theme/etc/react-theme.api.md, packages/react-components/react-theme/src/index.ts, packages/react-components/react-theme/src/themes/ThemeTypography.stories.tsx, packages/react-components/react-theme/src/types.ts
Add `typographyStyles` story to react-theme storybook:
[Storybook preview](https://fluentuipr.z22.web.core.windows.net/pull/22832/public-docsite-v9/storybook/index.html?path=/docs/theme--typography-styles)
Also add missing export for `TypographyStyle`.
=> Docs(react-theme): Add typographyStyles story

packages/fluentui/e2e/cypress.json, packages/fluentui/e2e/tests/dialogInDialogWithDropdown.spec.ts, packages/fluentui/e2e/tests/dialogWithDropdown.spec.ts, packages/fluentui/react-northstar/src/components/Dialog/Dialog.tsx
Re-enables Dialog cypress test. 
It's disabled previously by #17483 due to flakyness. #22544 introduced cypress retry, so this PR re-enables the tests.
A small change was made to test as it was failing: Dialog dropdown list is considered not 'visible' by cypress because it was partially covered in the test. But the tests are for keyboarding, so it only needs to verify dropdown list exist.
=> chore: re-enable Dialog e2e

.github/CODEOWNERS
- 	`public-docsite-v9` will cause master branch to break on every new v9 release. If this occurs during Prague working hours, the Prague team needs to force merge the fix PR since they have no ownership of this package.
- adds `fluentui-react-build` to codeowners of `public-docsite-v9` so Prague folks are able to cleanly merge future fixes.
=> (chore): Add v-build team as codeowners of public-docsite-v9

.storybook/docs-root.css, apps/public-docsite-v9/src/DocsComponents/FluentDocsPage.stories.tsx
Fixes #22764
After https://github.com/microsoft/fluentui-storybook-addons/pull/16 is merged we can go back through the CSS file and use the classname rather than the longer compound selector
Work tracked in https://github.com/microsoft/fluentui/issues/22884
=> Fix docs page layout and reduce size of button on small screens

change/@fluentui-react-spinbutton-e9ad1dc6-db08-4425-a9a3-edbc682aa036.json, packages/react-components/react-spinbutton/etc/react-spinbutton.api.md, packages/react-components/react-spinbutton/src/components/SpinButton/SpinButton.types.ts, packages/react-components/react-spinbutton/src/index.ts
`SpinButton` exports a `SpinButtonCommons` type.
`SpinButtonCommons` is removed per: #20964
#22862
=> SpinButton: remove SpinButtonCommons type

change/@fluentui-react-84189716-76f0-46f9-baa4-5b35f632bd85.json, packages/react/src/components/ComboBox/ComboBox.tsx
**useAriaLabelAsText** indicates that the aria-label should be used as the selected display value. This was broken and this change fixes it.
Fixes #
=> Combobox - Fix useAriaLabelAsText 

change/@fluentui-react-label-345f3781-60ef-404d-bdaa-5fc22c842c21.json, packages/react-components/react-label/etc/react-label.api.md, packages/react-components/react-label/src/components/Label/Label.types.ts
This PR adds the new changes:
* Removing Commons type from Label.
=> react-label: Removing commons from Label

tools/.eslintrc.json, tools/generators/generate-change-files.ts, tools/generators/migrate-converged-pkg/index.ts, tools/generators/print-stats.spec.ts
`tools/` dont use TypeScript style rules which defeat the purpose of disabling compilation because style violations, thus we are not notified about unused identifiers in our code
`no-unused-vars` is enabled
=> chore(tools): enable unused vars lint rule and fix violations

tools/generators/migrate-converged-pkg/index.spec.ts, tools/generators/migrate-converged-pkg/index.ts
migration generator contains invalid local:build setup 
migration generator properly generates `local:build` setup
Fixes partially https://github.com/microsoft/fluentui/issues/22851
=> fix(tools): properly generate local api extractor config

apps/vr-tests-react-components/src/stories/Card.stories.tsx, change/@fluentui-react-card-87333a08-0070-46b8-9c38-a818b59814f6.json, packages/react-components/react-card/src/components/Card/useCardStyles.ts, packages/react-components/react-card/src/stories/CardAppearance.stories.tsx, packages/react-components/react-card/src/stories/SampleCard.stories.tsx
Due to the usage of `overflow: hidden`, the image doesn't fully overflow the parent and will not grow farther than the border, even though the border is transparent.
Given that we shouldn't show the content over the border, as high contrast themes show borders regardless of transparency, I've moved the border into the `::after` pseudo-element so that the border can render over the content.
This way, there's no 1px spacing on light/dark themes and the image doesn't cover the border on high contrast themes: 
#19336
=> fix(react-card): allow `CardPreview` to render under the `Card` border

change/@fluentui-react-textarea-e9a0507f-9a29-4173-b265-a78df2573681.json, packages/react-components/react-textarea/src/components/Textarea/useTextareaStyles.ts
This PR includes the following changes:
* Updates styles to use font tokens.
* This will also make sure Textarea uses the correct font family.
=> react-textarea: Update textarea styles to use font tokens.

change/@fluentui-react-spinbutton-877bc164-a733-4573-bc88-b5ccba3d20ea.json, packages/react-components/react-spinbutton/src/components/SpinButton/SpinButton.test.tsx, packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButton.tsx
`aria-valuetext` can only be set via the `displayValue` prop.
`aria-valuetext` can be set via the `displayValue` prop or directly via the `aria-valuetext` prop.
Fixes #22870
=> SpinButton: add aria-valuetext override

packages/react-components/react-theme/src/themes/ThemeSpacing.stories.tsx
Add Spacing story to react-theme storybook:
[Storybook preview](https://fluentuipr.z22.web.core.windows.net/pull/22852/public-docsite-v9/storybook/index.html?path=/docs/theme-spacing--spacing)
=> doc(react-theme): Add Spacing story

change/@fluentui-react-tabs-43ed491b-06ab-4977-abac-6df9f2a7eb88.json, packages/react-components/react-tabs/src/components/TabList/__snapshots__/TabList.test.tsx.snap, packages/react-components/react-tabs/src/components/TabList/useTabList.ts
- Updated tabster options to memorizeSelected, this ensures the selected tab is the one that receives focus when the tab list gets keyboard focus.
Updates #21594
=> react-tabs: Updated to focus on current selected tab

change/@fluentui-react-e95e14ca-cf22-42d4-9362-4a569382502e.json, packages/react/src/components/ComboBox/ComboBox.tsx
[Usable - Customer Insights - Segments>New quick segment]: List items present under "Value" combo box are not getting scrolled using keyboard.
https://powerbi.visualstudio.com/Customer360/_workitems/edit/782446
A multi-select combo box with several item does not scroll when keyboard is used.
CodePen for repro: https://codepen.io/mraveesha/pen/JjpYqLw
- The scrollToItem function uses the selected element reference
- Combobox in multi-select does not have a single selected element reference
- There is a pending selected index, but no reference for the pending element
- Added a function to find a descendant child based on a predicate.  Necessary to find options with a data-index matching the pending selected index.
- Updated scrollToItem method to find the element for scrolling when in …
=> v8 combobox: Updated to scroll to pending selected element

change/@fluentui-react-button-cd9b6fd2-8ae2-4a79-846d-b8a159c280b6.json, packages/react-components/react-button/etc/react-button.api.md, packages/react-components/react-button/src/components/Button/Button.types.ts, packages/react-components/react-button/src/components/Button/useButton.ts, packages/react-components/react-button/src/components/Button/useButtonStyles.ts, packages/react-components/react-button/src/components/CompoundButton/CompoundButton.types.ts, packages/react-components/react-button/src/components/CompoundButton/useCompoundButtonStyles.ts, packages/react-components/react-button/src/components/MenuButton/MenuButton.types.ts, packages/react-components/react-button/src/components/MenuButton/useMenuButtonStyles.ts, packages/react-components/react-button/src/components/SplitButton/useSplitButton.ts, packages/react-components/react-button/src/components/SplitButton/useSplitButtonStyles.ts, packages/react-components/react-button/src/components/ToggleButton/useToggleButtonStyles.ts
This PR removes the `Commons` type pattern in the types for all our `Button` components.
=> Removing Common types from all button components

change/@fluentui-react-checkbox-70a251eb-7216-43ee-8c4c-20d3d63cdb50.json, packages/react-components/react-checkbox/etc/react-checkbox.api.md, packages/react-components/react-checkbox/src/components/Checkbox/Checkbox.types.ts
This PR adds the following changes:
* Removes commons type from Checkbox.
* Changes `defaultvalue` to `default` in Checkbox types.
#22862
=> react-checkbox: Removing commons from Checkbox

packages/react-combobox/Spec.md, packages/react-combobox/etc/react-combobox.api.md, packages/react-combobox/src/components/Combobox/Combobox.types.ts, packages/react-combobox/src/components/Combobox/useCombobox.ts, packages/react-combobox/src/components/Listbox/Listbox.types.ts, packages/react-combobox/src/components/Listbox/__snapshots__/Listbox.test.tsx.snap, packages/react-combobox/src/components/Listbox/renderListbox.tsx, packages/react-combobox/src/components/Listbox/useListbox.ts, packages/react-combobox/src/components/Option/Option.test.tsx, packages/react-combobox/src/components/Option/Option.tsx, packages/react-combobox/src/components/Option/Option.types.ts, packages/react-combobox/src/components/Option/__snapshots__/Option.test.tsx.snap, packages/react-combobox/src/components/Option/useOption.tsx, packages/react-combobox/src/components/OptionGroup/OptionGroup.tsx, packages/react-combobox/src/contexts/ComboboxContext.ts, packages/react-combobox/src/contexts/ListboxContext.ts, packages/react-combobox/src/contexts/useComboboxContextValues.ts, packages/react-combobox/src/contexts/useListboxContextValues.ts, packages/react-combobox/src/stories/Combobox.stories.tsx, packages/react-combobox/src/stories/ComboboxCustomOptions.stories.tsx, packages/react-combobox/src/utils/OptionCollection.types.ts, packages/react-combobox/src/utils/Selection.types.ts, packages/react-combobox/src/utils/useOptionCollection.ts, packages/react-combobox/src/utils/useSelection.ts
Resolves #22055
I also added a story to show that this works when wrapping `OptionGroup` and `Option`.
The most relevant changes are in `useOptionCollection.ts` and `useOption.tsx`
=> Combobox vNext: update useOptionCollection to use DOM ordering instead of React.Children

rfcs/react-components/convergence/portal-compat.md
This RFC proposes introduce compatibility between components in different Fluent UI versions that use [`ReactDOM.createPortal()`](https://reactjs.org/docs/portals.html) via:
- usage of same values for `z-index`
- usage of separate React context to assign CSS class that handles CSS variables from Fluent UI React v9
Provides solution for #21333.
---
[**Preview**](https://github.com/layershifter/office-ui-fabric-react/blob/rfc/compat-v8-v9/rfcs/react-components/convergence/portal-compat.md)
=> RFC: Portal compatibility

change/@fluentui-react-conformance-griffel-dbbbeeb9-c536-4c69-8654-8bc9cb180ec9.json, packages/react-components/react-conformance-griffel/src/overridesWin.ts
It affects only conformance tests (`@fluentui/react-conformance-griffel`).
`mergeClasses()` implementation is mocked, but it returns `undefined`. Original `mergeClasses()` function always returns a string.
`mergeClasses()` implementation is mocked and returns the same type as an original function.
Caused issues in #22933.
=> fix: update mergeClasses() to match implementation in conformance tests

packages/fluentui/react-northstar/src/index.ts
Adds a comment so that Lage will include v0 into the affected tree
=> Experiment: Test screener scoping for v0

change/@fluentui-react-badge-b0df5892-a8d0-40c4-9f88-195a256a2af2.json, packages/react-badge/etc/react-badge.api.md, packages/react-badge/src/components/Badge/Badge.types.ts, packages/react-badge/src/components/CounterBadge/CounterBadge.types.ts, packages/react-badge/src/components/CounterBadge/useCounterBadge.ts, packages/react-badge/src/components/PresenceBadge/PresenceBadge.types.ts
Removes the commons type from all components in react-badge
=> Badge: remove commons type

.vscode/settings.json
Codeowners file is recognized as markdown in vscode which is wrong and might lead to issues
Codeowners is recognized as proper file type
Fixes https://github.com/microsoft/fluentui/pull/22909#pullrequestreview-967883338
=> chore(vscode): setup proper file asscociation for codeowners file

change/@fluentui-react-link-dbe9a9a3-2bd7-4293-ab9c-f2e04bc8b1ab.json, packages/react-components/react-link/etc/react-link.api.md, packages/react-components/react-link/src/components/Link/Link.types.ts, packages/react-components/react-link/src/components/Link/useLink.ts, packages/react-components/react-link/src/components/Link/useLinkState.ts, packages/react-components/react-link/src/components/Link/useLinkStyles.ts, packages/react-components/react-link/src/stories/LinkInline.stories.tsx
This PR removes the `Commons` type pattern in the types for our `Link` component.
=> Removing LinkCommons type in @fluentui/react-link

change/@fluentui-react-tooltip-503f3e06-eca4-40eb-a1e4-23a7e944fce0.json, packages/react-components/react-tooltip/etc/react-tooltip.api.md, packages/react-components/react-tooltip/src/components/Tooltip/Tooltip.types.ts, packages/react-components/react-tooltip/src/components/Tooltip/useTooltip.tsx
This PR removes the `Commons` type pattern in the types for our `Tooltip` component.
=> Removing TooltipCommons type in @fluentui/react-tooltip

change/@fluentui-react-card-c2de5549-5b5a-4da7-8be6-c628273c2b85.json, packages/react-components/react-card/etc/react-card.api.md, packages/react-components/react-card/src/components/Card/Card.types.ts, packages/react-components/react-card/src/components/Card/useCard.ts, packages/react-components/react-card/src/index.ts
Removes Commons type for Card, also removes the unused `focusMode` prop from CardState (looks like it was previously included only because it was in Commons)
=> Card: remove commons type

change/@fluentui-react-shared-contexts-49dda2e7-be7a-42a4-bb6f-044d15d89e00.json, packages/react-components/react-shared-contexts/.babelrc.json, packages/react-components/react-shared-contexts/.npmignore, packages/react-components/react-shared-contexts/config/api-extractor.json, packages/react-components/react-shared-contexts/config/api-extractor.local.json, packages/react-components/react-shared-contexts/package.json, packages/react-components/react-shared-contexts/tsconfig.lib.json
Applied `yarn workspace-generator migrate-converged-pkg` to ship only rolluped type definitions for:
- shared-contexts
=> feat(v9): migrate react-shared-contexts to ship rolluped only dts

change/@fluentui-eslint-plugin-83177480-e2f6-4ac0-9bf2-85d57cb5dc2a.json, package.json, packages/eslint-plugin/src/configs/react-legacy.js, packages/eslint-plugin/src/configs/react.js, yarn.lock
This PR adds new ESLint plugin for Griffel (https://github.com/microsoft/griffel/pull/99).
Griffel does not support usage of CSS shorthands, [microsoft/griffel#30](https://github.com/microsoft/griffel/issues/30#issuecomment-1045959297).
This is enforced by typings, but there are cases when they don't work as expected [microsoft/griffel#78](https://github.com/microsoft/griffel/issues/78).
Examples of **incorrect** code for this rule:
```ts
const useStyles = makeStyles({
root: {
// Causes cryptic TypeScript error
background: "red"
}
});
```
No lint errors 😕
```
packages/react-components/react-link/src/components/Link/useLinkStyles.ts
28:5  error  Usage of shorthands is prohibited  @griffel/no-shorthands
✖ 1 problem (1 error, 0 warnings)
```
=> chore: enable ESLint plugin for Griffel

change/@fluentui-react-tabs-35cfa4bc-b5ec-4b83-af69-63f5410eda03.json, packages/react-components/react-tabs/src/components/Tab/useTabStyles.ts
- Updated Tab component to use grid
- Removed the min-width of 120px from medium vertical (no longer specified in figma)
- Collapsed horiztontal/vertical styles to ensure correct content alignment.
Updates #22704
=> react-tabs: Removed flexgap from useTabStyles

change/@fluentui-react-divider-ca524fc3-b993-4480-9dba-ab97cde6f265.json, packages/react-divider/etc/react-divider.api.md, packages/react-divider/src/components/Divider/Divider.types.ts, packages/react-divider/src/components/Divider/useDivider.ts, packages/react-divider/src/components/Divider/useDividerStyles.ts
This PR removes the `Commons` type pattern in the types for our `Divider` component.
=> Removing DividerCommons type in @fluentui/react-divider

packages/react-combobox/etc/react-combobox.api.md, packages/react-combobox/src/components/ComboButton/ComboButton.types.ts, packages/react-combobox/src/components/Combobox/Combobox.types.ts, packages/react-combobox/src/components/Option/Option.types.ts
Removes commons types from Combobox, Combobutton, and Option. Also removes unneeded, unused props that were previously added to the State types through Commons, and alphabetizes props.
=> Remove Combobox commons types

change/@fluentui-react-avatar-2c5f12fa-f3d8-4d4d-ad02-eeb76cbbd25d.json, packages/react-components/react-avatar/etc/react-avatar.api.md, packages/react-components/react-avatar/src/components/Avatar/Avatar.types.ts, packages/react-components/react-avatar/src/components/Avatar/useAvatar.tsx, packages/react-components/react-avatar/src/components/AvatarGroup/AvatarGroup.types.ts, packages/react-components/react-avatar/src/components/AvatarGroup/useAvatarGroup.ts
Removes Commons type from both Avatar and AvatarGroup, and removes unused props from state.
Note: AvatarGroup will likely implement a context at some point, and then the AvatarGroupContext type would likely pick from props, and those values would be re-added to state. I've still removed them from state for now, since they're not currently used.
=> Avatar: remove commons types

change/@fluentui-react-file-type-icons-ce8d68da-748c-4919-93e9-25b4cbdf9752.json, packages/react-file-type-icons/src/index.ts
- Added export from package for FileTypeIconMap
This was previously exported through * exports, and customers deep imported it.  With the change away from * exports this was no longer available.  
Fixes #22840
=> react-file-type-icons: add export of FileTypeIconMap

scripts/create-component/plop-templates/src/components/{{componentName}}/{{componentName}}.types.ts.hbs
This PR removes the `Commons` type pattern from the template used when creating a component using our `create-component` script.
=> Removing Commons type from component creation template

.github/CODEOWNERS
Remove myself from v7 codeowners (this was already done in master).
For website stuff I changed the codeowner to the website team instead. For components I just removed myself, so now cxe-red is the owner.
=> Remove ecraig12345 from v7 codeowners

apps/public-docsite-v9/src/Concepts/Upgrade/FromV8/ComponentMapping.stories.mdx, apps/public-docsite-v9/src/Concepts/Upgrade/FromV8/Components/SpinButton.stories.mdx
v8 --> v9 upgrade guide doesn't show v8 examples.
v8 --> v9 upgrade guide shows v8 examples to compare and contrast with v9 examples.
[Preview link](https://fluentuipr.z22.web.core.windows.net/pull/22919/public-docsite-v9/storybook/index.html?path=/docs/concepts-upgrading-from-v8-components-spinbutton-upgrade--page)
=> SpinButton: improve upgrade guides

change/@fluentui-react-checkbox-45dc4e8d-6372-49fa-a2c2-5824ecb0e30e.json, packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts
The styles include the flex 'gap' property, which is not compatible with some older browsers.
Replace the flex gap property with a margin on the label.
* #22704
=> Checkbox: Refactor styles to remove usage of flex gap

change/@fluentui-react-switch-41e97da5-1bde-44dc-9a12-9f2e3f818133.json, packages/react-components/react-switch/src/components/Switch/useSwitchStyles.ts
The styles include the flex 'gap' property, which is not compatible with some older browsers.
Replace the flex gap property with a margin on the label.
* #22704
=> Switch: Refactor styles to remove usage of flex gap

change/@fluentui-react-radio-e5e0980d-9cfa-4712-bbb1-a90cc32359e1.json, packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts
The styles include the flex 'gap' property, which is not compatible with some older browsers.
Replace the flex gap property with a margin on the label.
* #22704
=> Radio: Refactor styles to remove usage of flex gap

change/@fluentui-react-input-7c36843e-3257-471f-9bfb-0dce31dae35c.json, packages/react-components/react-input/package.json, packages/react-components/react-input/src/stories/Input.stories.tsx, packages/react-components/react-input/src/stories/InputAppearance.stories.tsx, packages/react-components/react-input/src/stories/InputBestPractices.md
The `filledDarker` and `filledLighter` "Appearance" stories have insufficient contrast with their backgrounds.
1. The `filledDarker` and `filledLighter` "Appreance" stories have sufficient contrast with their backgrounds.
2. Design guidance has been added to the story.
Fixes #21449
=> Input: update appearance stories

change/@fluentui-react-checkbox-65e7ee49-bcf2-42db-9fe8-9a15999b1098.json, change/@fluentui-react-input-a16a3406-ea5c-4bcf-b22a-694ce517d2fb.json, change/@fluentui-react-label-2e736c10-36a8-439c-900e-8ec9511a2a13.json, change/@fluentui-react-link-d2e69fee-5358-48b8-98a3-9bc4ab83ecb7.json, packages/react-components/react-checkbox/.npmignore, packages/react-components/react-checkbox/config/api-extractor.json, packages/react-components/react-checkbox/package.json, packages/react-components/react-checkbox/tsconfig.lib.json, packages/react-components/react-input/.npmignore, packages/react-components/react-input/.storybook/preview.js, packages/react-components/react-input/config/api-extractor.json, packages/react-components/react-input/package.json, packages/react-components/react-input/tsconfig.lib.json, packages/react-components/react-label/.npmignore, packages/react-components/react-label/config/api-extractor.json, packages/react-components/react-label/package.json, packages/react-components/react-label/tsconfig.lib.json, packages/react-components/react-link/.npmignore, packages/react-components/react-link/config/api-extractor.json, packages/react-components/react-link/package.json, packages/react-components/react-link/tsconfig.lib.json, packages/react-components/react-select/.npmignore, packages/react-components/react-select/config/api-extractor.json, packages/react-components/react-select/package.json, packages/react-components/react-select/tsconfig.lib.json
Applied `yarn workspace-generator migrate-converged-pkg` to ship only rolluped type definitions for:
- react-checkbox
- react-input
- react-label
- react-link
- react-select
=> feat(v9): migrate checkbox,input,label,link,select to ship rolluped only dts

change/@fluentui-react-popover-553765b9-3f08-4494-9ffa-a7a039c73d13.json, packages/react-components/react-popover/etc/react-popover.api.md, packages/react-components/react-popover/src/components/Popover/Popover.types.ts, packages/react-components/react-popover/src/components/Popover/renderPopover.tsx, packages/react-components/react-popover/src/components/Popover/usePopover.ts, packages/react-components/react-popover/src/components/PopoverSurface/PopoverSurface.types.ts, packages/react-components/react-popover/src/components/PopoverTrigger/PopoverTrigger.types.ts
This PR removes the `Commons` type pattern in the types for our `Popover` component.
=> Removing PopoverCommons type in @fluentui/react-popover

change/@fluentui-react-components-0bdd7c90-41f4-40f2-9112-85230911399c.json, packages/react-components/react-components/etc/react-components.api.md, packages/react-components/react-components/src/index.ts
This PR makes the following changes:
* Re-exports AvatarSizes from react-avatar inside react-components.
=> react-components: Re-exporting AvatarSizes from react-avatar

change/@fluentui-react-86dd4237-8c0f-432e-9d60-dcc86df144ea.json, packages/react/etc/react.api.md, packages/react/src/ShimmeredDetailsList.ts, packages/react/src/components/DetailsList/DetailsColumn.styles.ts, packages/react/src/components/DetailsList/DetailsColumn.ts, packages/react/src/components/DetailsList/DetailsHeader.styles.ts, packages/react/src/components/DetailsList/DetailsHeader.ts, packages/react/src/components/DetailsList/DetailsList.styles.ts, packages/react/src/components/DetailsList/DetailsList.ts, packages/react/src/components/DetailsList/DetailsRowCheck.styles.ts, packages/react/src/components/DetailsList/DetailsRowCheck.tsx, packages/react/src/components/DetailsList/ShimmeredDetailsList.styles.ts, packages/react/src/components/DetailsList/ShimmeredDetailsList.ts, packages/react/src/components/DetailsList/index.ts
https://github.com/microsoft/fluentui/pull/21508 moved to explicit exports, this removed some exports from v8 components that could previously be deep imported.
- Updated to explicitly export previously exported for  deep imports
- Because DetailsRow exported styles, exported other styles.  Renamed getStyles to specific names to avoid collisions.  This will allow for custom styled extended components to be authored.
Fixes #22989
=> Details list fix exports

apps/public-docsite-v9/src/Concepts/Upgrade/FromV0/Components/Textarea.stories.mdx, apps/public-docsite-v9/src/Concepts/Upgrade/FromV8/Components/Textarea.stories.mdx, apps/vr-tests-react-components/package.json, change/@fluentui-react-components-0670ce15-bbdb-4308-ba27-934c4ede2548.json, change/@fluentui-react-textarea-006f5a3e-ee5f-4b7e-bd4b-06fd3d4203d5.json, packages/react-components/react-components/etc/react-components.api.md, packages/react-components/react-components/etc/react-components.unstable.api.md, packages/react-components/react-components/package.json, packages/react-components/react-components/src/index.ts, packages/react-components/react-components/src/unstable/index.ts, packages/react-components/react-textarea/README.md, packages/react-components/react-textarea/package.json
This PR makes the following changes:
* Moves Textarea exports from unstable to stable.
* Changes version of react-textarea to rc.
=> react-textarea: Move Textarea to release candidate

change/@fluentui-react-input-4ba8cfdb-9f07-45c5-8c1d-ed672b804ed5.json, packages/react-components/react-input/README.md
`react-input`'s README was incomplete.
`react-input`'s README now:
1. Provides a short summary of what the component is for
2. Shows sow to import the component
3. Show basic usage 
4. Provides links to relevant documentation
=> react-input: write readme

packages/react-combobox/src/components/Combobox/useCombobox.ts, packages/react-combobox/src/components/Listbox/useListbox.ts, packages/react-combobox/src/components/Option/useOption.tsx, packages/react-combobox/src/utils/OptionCollection.types.ts, packages/react-combobox/src/utils/Selection.types.ts, packages/react-combobox/src/utils/useOptionCollection.ts, packages/react-combobox/src/utils/useSelection.ts
When switching from `React.Children` to DOM child ordering, the option `id` attribute becoming unstable across renders broke aspects of selecting/unselecting options and calculating the `activedescendant` value on combobox open.
This PR fixes both issues, and adds a `getOptionsMatchingValue` util that will help future filtering by value.
=> Combobox: fix logic for selection and activedescendant

change/@fluentui-react-1b195929-6f94-41d0-9f13-4403c965df3a.json, packages/react/src/components/Pivot/Pivot.base.tsx
Related to #20662
A previous fix to Pivot turned the overflow popup into a semantic menu, which fixed one bug but created another -- `aria-selected` is allowed on tabs but not menuitems. This PR removes the `aria-selected` semantics if the item is rendered inside the overflow menu.
This should be fine as far as accessible semantics go, since the menu items themselves should never be selected and shouldn't need selection semantics. Once an overflowed item is chosen from the menu, it becomes part of the actual tablist.
=> fix(Pivot): aria-selected not allowed on menuitems

packages/react-examples/src/react/GroupedList/GroupedList.CustomCheckbox.Example.tsx
Fixes #21644
Previously the GroupedList custom checkbox example nested a `<Toggle>` inside a checkbox, which resulted in nested checkboxes and a11y errors (and hella weird screen reader behavior, in some instances).
This fix swaps out the `<Toggle>` component for a toggle-like icon.
=> Fix groupedlist custom checkbox example to not have nested checkboxes

packages/react-examples/src/react/OverflowSet/OverflowSet.Basic.Example.tsx, packages/react-examples/src/react/OverflowSet/OverflowSet.BasicReversed.Example.tsx, packages/react-examples/src/react/OverflowSet/OverflowSet.Custom.Example.tsx, packages/react-examples/src/react/OverflowSet/OverflowSet.Vertical.Example.tsx, packages/react-examples/src/react/ResizeGroup/ResizeGroup.OverflowSet.Example.tsx, packages/react-examples/src/react/ResizeGroup/ResizeGroup.VerticalOverflowSet.Example.tsx
Fixes an issue related to a resolved internal a11y bug.
Our OverflowSet and ResizeGroup examples were applying menu roles without any menu keyboard interaction. Looking at the examples, it looks like the menu semantics are at best unnecessary, so I removed them.
=> Remove menu roles from overflowset and resizegroup examples

change/@fluentui-react-accordion-cb404d3d-936e-4aa5-803f-ea179b52acee.json, packages/react-accordion/etc/react-accordion.api.md, packages/react-accordion/src/components/Accordion/Accordion.types.ts, packages/react-accordion/src/components/Accordion/useAccordion.ts, packages/react-accordion/src/components/AccordionHeader/AccordionHeader.types.ts, packages/react-accordion/src/components/AccordionItem/AccordionItem.types.ts, packages/react-accordion/src/components/AccordionItem/useAccordionItem.ts
While removing Commons, I noticed a couple places there was a prop on state that wasn't used, so I removed those. I also alphabetized type props.
=> Accordion: remove commons type

packages/fluentui/CHANGELOG.md, packages/fluentui/docs/src/examples/components/Avatar/Visual/AvatarStatusOverrideExample.shorthand.tsx, packages/fluentui/react-northstar/src/components/Avatar/Avatar.tsx
`Avatar` components will not longer pass via `styles` down to components. We left it for compat reasons, but it breaks styles caching.
For full context and migration plan please check #16428, #16417, #16409, #16382.
=> fix: remove deprecated branches to fix styles caching in Avatar

change/@fluentui-react-badge-51877968-a3ea-468a-b353-198c0346e1dc.json, packages/react-components/react-badge/.npmignore, packages/react-components/react-badge/config/api-extractor.json, packages/react-components/react-badge/config/api-extractor.local.json, packages/react-components/react-badge/package.json, packages/react-components/react-badge/tsconfig.lib.json
Applied `yarn nx workspace-generator migrate-converged-pkg` to ship only rolluped type definitions for:
- react-badge
=> feat(v9): migrate badge to ship rolluped only dts

packages/react-components/react-select/src/components/Select/useSelectStyles.ts
Select's "down" icon is positioned with `right: 0` causing the icon to be displayed right against the edge of Select.
Select's "down" icon is positioned with `right: tokens.spacingHorizontalMNudge` which is the same token used to pad Select's text.
Griffel automatically transforms this to `left: ...` when Select is used in a right-to-left context.
=> Select: fix icon positioning

change/@fluentui-react-spinbutton-d39a9441-b65d-4309-b07e-02e8a6516464.json, packages/react-components/react-spinbutton/src/components/SpinButton/SpinButton.test.tsx, packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButton.tsx, packages/react-components/react-spinbutton/src/utils/clamp.test.ts, packages/react-components/react-spinbutton/src/utils/clamp.ts
SpinButton allows users to type in values outside of the [min, max] range (out of bounds values) and it still allows this after this change.
After typing an out of bounds value and then using the steppers to increment/decrement the value, SpinButton allows this
value to be stepped as if it were in bounds and _not_ clamp it to the [min, max] range.
This change updates this behavior such that out of bounds values are clamped to the [min, max] range. 
Values that are less than min are clamped to min when the increment or decrement steppers or hotkeys are used. 
Values that are greater than max are clamped to max when the increment or decrement steppers or hotkeys are used.
=> SpinButton: update stepper clamping behavior

change/@fluentui-react-components-7bb589d2-fd19-4663-bea3-71732661b54e.json, packages/react-components/react-components/.storybook/main.utils.test.js
- Storybook test for `react-components` is broken in `master` branch after `react-accordion` package was moved in #22827:
- Test is fixed:
Fixes #
=> (fix): Broken storybook test in react-components fixed after accordion move

packages/react-components/react-toolbar/src/stories/Toolbar.stories.tsx, packages/react-components/react-toolbar/src/stories/ToolbarBestPractices.md, packages/react-components/react-toolbar/src/stories/ToolbarSubtle.stories.tsx, packages/react-components/react-toolbar/src/stories/ToolbarWithPopover.stories.tsx, packages/react-components/react-toolbar/src/stories/ToolbarWithTooltip.stories.tsx
Adds few `react-toolbar` stories, showing using `ToolbarButton` as icon only, combination with `Tooltip` and `Popover` and subtle variation.
=> feat: add react toolbar stories

packages/react-components/react-toolbar/etc/react-toolbar.api.md, packages/react-components/react-toolbar/src/components/Toolbar/Toolbar.types.ts, packages/react-components/react-toolbar/src/components/Toolbar/useToolbar.ts, packages/react-components/react-toolbar/src/index.ts
This PR removes the `Commons` type pattern in the types for our `Toolbar` component.
=> Removing ToolbarCommons type in @fluentui/react-toolbar

packages/react-components/react-dialog/etc/react-dialog.api.md, packages/react-components/react-dialog/src/components/Dialog/Dialog.types.ts
This PR removes the `Commons` type pattern in the types for our `Dialog` component.
=> Removing DialogCommons type in @fluentui/react-dialog

change/@fluentui-react-text-2fe193d2-52fa-42b1-b696-c6b562f8ac23.json, packages/react-components/react-text/etc/react-text.api.md, packages/react-components/react-text/src/components/Text/Text.types.ts, packages/react-components/react-text/src/components/Text/useText.ts
This PR removes the `Commons` type pattern in the types for our `Text` component.
=> Removing TextCommons type in @fluentui/react-text

packages/react-components/react-select/src/stories/Select.stories.tsx, packages/react-components/react-select/src/stories/SelectAppearance.stories.tsx, packages/react-components/react-select/src/stories/SelectBestPractices.md
Select appearance stories for filledLighter and filledDarker are not against a sufficiently contrasting background.
- Select appearance stories for filledLighter and filledDarker are against a sufficiently contrasting background.
- Adds a best practices MD file with do's and don'ts for contrast
- Adds contrast guidance to the appearance story description
#22967
=> react-select: update contrast in appearance stories

change/@fluentui-font-icons-mdl2-329545c1-bd7e-4a32-aa67-bc0f624b16a0.json, packages/font-icons-mdl2/src/index.ts
This PR updates #22411, which originally used `fontBaseUrl` to use `iconBaseUrl` to avoid a collision of the `fontBaseUrl` window variable between Icon fonts and Text fonts
=> Update window to use iconBaseUrl to prevent collision

change/@fluentui-react-button-fc2226f9-0a2b-4a6d-8fc1-af544f362a71.json, packages/react-components/react-button/etc/react-button.api.md, packages/react-components/react-button/src/components/ToggleButton/ToggleButton.types.ts
This PR removes the `ToggleButtonCommons` type pattern in the types for our `ToggleButton` component.
=> Removing ToggleButtonCommons type in @fluentui/react-button

packages/react-components/react-select/etc/react-select.api.md, packages/react-components/react-select/src/components/Select/Select.types.ts, packages/react-components/react-select/src/index.ts
This PR removes the `Commons` type pattern in the types for our `Select` component.
=> Removing SelectCommons type in @fluentui/react-select

packages/react-components/react-input/src/stories/InputAppearance.stories.tsx, packages/react-components/react-spinbutton/src/stories/SpinButtonAppearance.stories.tsx, packages/react-components/react-textarea/src/stories/TextareaAppearance.stories.tsx
Appearance stories use a white (#ffffff) label against a gray (#8a8a8a) background which only has a 3.45:1 contrast ratio that fails WCAG AA.
Appearance stories use a black (#000000) label against a gray (#8a8a8a) background which has a 6.08:1 contrast ratio that passes WCAG AA.
Used [WebAIM contrast checker](https://webaim.org/resources/contrastchecker/) to get contrast ratios.
=> Accessibility: appearance filled contrast fix

apps/public-docsite-v9/.storybook/main.utils.js, change/@fluentui-react-components-bceca457-a419-4d28-9017-f25641f217a4.json, packages/react-components/react-components/.storybook/main.utils.js
- Follow-up to TODO items to simplify `getVnextStories` util function now that all v9 packages have been moved to common folder.
Part of #22427
=> (chore) Cleanup getVnextStories function now that all v9 packages have been moved to common folder

change/@fluentui-react-provider-1a934471-371e-40d3-a414-9888ed5f7606.json, packages/react-components/react-provider/etc/react-provider.api.md, packages/react-components/react-provider/src/components/FluentProvider/FluentProvider.types.ts
This PR removes the `Commons` type pattern in the types for our `FluentProvider` component.
=> Removing FluentProviderCommons type in @fluentui/react-provider

change/@fluentui-react-components-e2f0fda9-b4ae-4ca7-a7b7-82c2bd8a34e5.json, packages/react-components/react-components/etc/react-components.api.md, packages/react-components/react-components/etc/react-components.unstable.api.md, packages/react-components/react-components/src/index.ts, packages/react-components/react-components/src/unstable/index.ts, packages/react-components/react-switch/src/stories/Switch.stories.tsx
`Switch` component is re-exported in `@fluentui/react-components/lib/unstable`.
`Switch` component is re-exported in `@fluentui/react-components.`
Fixes #22818
=> Switch: Moving component out of unstable

change/@fluentui-react-menu-885fe8d5-9fab-4126-b211-93d4f5d6d2f8.json, packages/react-components/react-menu/e2e/Menu.e2e.tsx, packages/react-components/react-menu/src/components/Menu/useMenu.tsx, packages/react-components/react-menu/src/stories/MenuDefault.stories.tsx
Context menu cannot be dismissed when its trigger is clicked
Context menu is dismissed when its trigger is clicked
Fixes #23081
=> fix: Context menu should close when its trigger is clicked

packages/react-components/react-card/src/stories/CardAppearance.stories.tsx
- No longer wrapping theme on `appearance` stories
#19336
=> chore(react-card): align stories with the rest of the library

change/@fluentui-react-focus-e173e41b-2ecf-4753-be67-84890ed731ea.json, packages/react-focus/etc/react-focus.api.md, packages/react-focus/src/components/FocusZone/FocusZone.tsx, packages/react-focus/src/components/FocusZone/FocusZone.types.ts
Resolves #20301
Interestingly, `<textarea>` has a `type` attribute that always returns the string `"textarea"`, so all that was needed was to add that to `ALLOWED_INPUT_TYPES`.
I also updated the typings for the internal functions and `props.shouldInputLoseFocusOnArrowKey` to accurately reflect the possible element types. Textarea was already returning true in `_isElementInput`, so this better reflects the current behavior.
=> Focuszone: update to treat arrow keys in textarea the same as arrow keys in input

packages/react-components/react-tabs/src/stories/TabListWithOverflow.stories.tsx
The overflow button is inclued in the tablist's arrow key behavior, but because of its role, was not included in the count and was triggering an undesired mode change when arrowing. The icon button also lacked an accessible name.
This change adds an accName, updates the role, and adds a docs note for authors.
=> react-tabs: fix a11y issues with overflow story

change/@fluentui-react-spinbutton-604f015e-1ec4-4a12-9605-e391f23730b4.json, packages/react-components/react-spinbutton/etc/react-spinbutton.api.md, packages/react-components/react-spinbutton/src/components/SpinButton/SpinButton.test.tsx, packages/react-components/react-spinbutton/src/components/SpinButton/SpinButton.types.ts, packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButton.tsx, packages/react-components/react-spinbutton/src/stories/SpinButtonControlled.stories.tsx, packages/react-components/react-spinbutton/src/stories/SpinButtonDisplayValue.stories.tsx
`value` and `defaultValue` are typed as the TS `number` type.
`value` and `defaultValue` have their types widened to `number | null`.
This change is being made based on partner feedback for wanting a reliable way to represent "no value" or "unset value".
`null` was chosen because Typescript can easily ensure users handle the null case as opposed to a value like `NaN`. `null` is also obviously a special case so it's clearer that it should be handled specially. Because `null` is a special, non-`number` value it can more simply be handled internally by SpinButton.
`undefined` cannot be used as React will interpret `value`/`defaultValue` toggling from a number to `undefined` and back as the component switching from controlled to uncontrolled (which is logged as an error). …
=> SpinButton: widen `value` type to include `null`

change/@fluentui-react-charting-5b45ec84-abc6-4c15-9c84-87011d733638.json, packages/react-charting/src/components/LineChart/eventAnnotation/EventAnnotation.tsx, packages/react-charting/src/components/LineChart/eventAnnotation/LabelLink.tsx
In The line chart Events Graph Event 3', 'Event4' and 'Event5' texts are not clearly visible in the high contrast aquatic theme.
After this fix 'Event 3', 'Event4' and 'Event5' texts are clearly visible in high contrast aquatic theme.
Fixes #
After this fix Event 3', 'Event4' and 'Event5' texts are clearly visible in high contrast in all the other themes.
=> Graph texts are not clearly visible in aquatic theme.

change/@fluentui-react-charting-93ba5b08-f672-4745-8d41-ca6e26b9db7c.json, packages/react-charting/src/components/DonutChart/DonutChart.base.tsx, packages/react-charting/src/components/LineChart/LineChart.base.tsx, packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx, packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.types.ts, packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx, packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.types.ts, packages/react-examples/src/react-charting/VerticalBarChart/VerticalBarChartPage.tsx
Currently labels in vertical bar chart are not correctly aligned with the bars.
In donut charts, a zero valued datapoint can show up.
Both of the above issues are fixed.
Fixes #
Switched from linear scale to d3 band scale which is the correct scale to be used for vertical bar charts.
For donut chart, added a filter condition to remove datapoints having 0 or less to be shown in the pie chart.
=> Aligning vertical bar labels with the bars. Preventing zero valued arcs show up in pie chart

packages/react-examples/src/react-charting/VerticalBarChart/VerticalBarChart.Dynamic.Example.tsx
The screen reader is reading "zero graphic" for all the values in the vertical bar chart dynamic graph.
After the fix, the issue is resolved in NVDA and Google chrome screen reader extension the issue is only reproducing in the narrator 
Fixes #
Earlier tooltip was hidden in the vertical bar chart dynamic graph, after this fix the data is being announced in NVDA and chrome screenreaders.
=> 0 graphic" value is read by the screen reader for all the values in vertical bar chart dynamic graph

change/@fluentui-react-image-f9c64c07-9b02-450f-969a-e2b9f3baa9b1.json, packages/react-components/react-image/src/components/Image/useImageStyles.ts
`useImageStyles` does not use the `styles[state]` pattern for props of string union types (i.e. `'string1' | 'string2' | 'string3'`) found in other components.
`useImageStyles` uses the `styles[state]` pattern for props of string union types (i.e. `'string1' | 'string2' | 'string3'`) found in other components. This improves bundle size and readability.
=> Image: Updating useImageStyles to use styles[state] pattern for props of string union types

README.md
Adds a note about the v9 release schedule with a link to the schedule
in the wiki.
=> Docs: update main readme to point to v9 release schedule

change/@fluentui-react-input-28f3decf-aea3-4965-8855-966b465cd73b.json, change/@fluentui-react-spinbutton-86cf8f69-2ee4-407a-8b1b-ce90f9978be0.json, change/@fluentui-react-textarea-17985c27-7371-4178-9cc2-322833f783d9.json, packages/react-components/react-input/src/components/Input/useInputStyles.ts, packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButtonStyles.ts, packages/react-components/react-textarea/src/components/Textarea/useTextareaStyles.ts
Additional focus ring is shown in native input/textarea element when using macOS safari.
No focus ring is shown in native input/textarea element.
Fixes #23167
=> Remove additional focus ring from `Input`, `SpinButton`, and `Textarea` when using macOS safari

change/@fluentui-react-25c59003-ab69-4806-b14b-555b3a467382.json, packages/react/package.json
The export in the `@fluentui/react` package for `PlainCard.styles` is pointing to the wrong path. Either the path changed or this never worked, but it's wrong.
We really need package linting. This could have been caught by just validating that all exports are files that exist in the pre-publish folder content.
=> Fix PlainCard export

packages/react-components/theme-designer/src/ThemeDesigner.tsx, packages/react-components/theme-designer/src/components/Component/Component.stories.tsx, packages/react-components/theme-designer/src/components/Component/Component.tsx, packages/react-components/theme-designer/src/components/Content/Content.tsx, packages/react-components/theme-designer/src/components/Nav/Nav.tsx, packages/react-components/theme-designer/src/components/Sidebar/Sidebar.tsx
Adding styles to the preexisting layout of the theme designer such that it now has a designated area for the navbar, sidebar, and content.
=> Theme Designer: starting to build out styles for layout

change/@fluentui-react-spinner-1c220f3c-62cf-44a3-93e6-86a9e5a48933.json, packages/react-components/react-spinner/src/components/Spinner/useSpinnerStyles.ts
Previously the spinner did not visually render at all on Firefox, since the `<circle>` SVG elements were missing an `r` definition. It turns out Griffel does not output the style for `r` on Firefox specifically if the units are left off (issue logged: https://github.com/microsoft/griffel/issues/119).
I verified that the spinner now renders on both Chromium and Firefox with this change (and non-0 `r` generally should have units in any case, since it's specified as `length | percentage`)
=> fix(react-spinner): fix Firefox rendering by adding px units to r

change/@fluentui-react-spinner-54d34720-9760-409c-81c7-9dcdd2268545.json, packages/react-components/react-spinner/src/components/Spinner/useSpinnerStyles.ts
Fixes #23193, adds a single media query.
Verified on Windows, works with the built-in OS animation toggle.
=> fix(react-spinner): add prefers-reduced-motion to spinner

apps/public-docsite-v9/package.json
Chromatic looks at your origin remote + your current branch to specify the branch name to publish to. Since most people use their fork in origin, this makes it difficult to publish to a consistent branch. 
This PR normalizes the branch used when we run 'chromatic' and allows the old behavior as `yarn chromatic:branch` when you want to publish using your current origin and branch name.
=> normalize the branch chromatic publishes to

change/@fluentui-react-components-52fe240d-c291-411c-8a8f-02c4d17a7bb2.json, packages/react-components/react-components/src/Migrations/Flex.Flex.stories.mdx, packages/react-components/react-components/src/Migrations/Flex.FlexItem.stories.mdx, packages/react-components/react-components/src/Migrations/Flex.Overview.stories.mdx, packages/react-components/react-components/src/Migrations/Flex.Stack.stories.mdx, packages/react-components/react-components/src/Migrations/Flex.StackItem.stories.mdx
moving the original flex migration stories from their own 'migration' heading
to upgrading v0 section
=> move v0 flex stories to migration guide of storybook

packages/react-components/react-combobox/src/stories/ComboboxAppearance.stories.tsx, packages/react-components/react-input/src/stories/InputAppearance.stories.tsx, packages/react-components/react-select/src/stories/SelectAppearance.stories.tsx, packages/react-components/react-spinbutton/src/stories/SpinButtonAppearance.stories.tsx
Appearance stories for ComboBox, Input, Select and SpinButton have adequate contrast with the background for the filledDarker and filledLighter appearances but do not use tokens for colors.
All relevant stories use tokens for colors.
The previous colors used were in the color palette but not exported as directly usable tokens. This color change has been reviewed with design.
Textarea is updated in #23190
=> Fix: Update appearance stories to use tokens

change/@fluentui-react-components-863d4794-3dd2-4e12-868e-2162affc2c4f.json, change/@fluentui-react-select-93492b0a-799b-4692-898e-a1cc3c689a34.json, packages/react-components/react-components/etc/react-components.unstable.api.md, packages/react-components/react-components/package.json, packages/react-components/react-components/src/unstable/index.ts, packages/react-components/react-select/package.json, packages/react-components/react-select/src/stories/Select.stories.tsx
Exports the `react-select` package from `react-components` as an unstable preview component
=> v9: Add Select to Preview Components

change/@fluentui-react-button-ae32d3af-7f8a-478f-ab75-159deab67465.json, packages/react-components/react-button/src/components/ToggleButton/useToggleButtonStyles.ts
`ToggleButton` High Contrast styles are the same for unchecked hover, checked rest and checked hover states.
__Unchecked hover:__
__Checked rest:__
__Checked hover:__
`ToggleButton` High Contrast styles are differentiated between unchecked hover, checked rest and checked hover states.
__Unchecked hover:__
__Checked rest:__
__Checked hover:__
We have also made sure that the focus style looks correct with the new checked rest styles:
Fixes #23072
=> ToggleButton: Differentiating hover and checked styles

apps/public-docsite-v9/src/Concepts/SSR.stories.mdx, apps/public-docsite-v9/src/Concepts/Slots.stories.mdx, apps/public-docsite-v9/src/Concepts/StylingComponents.stories.mdx, apps/public-docsite-v9/src/Concepts/Upgrade/FromV8/Components/Textarea.stories.mdx, packages/react-components/react-components/src/Concepts/Positioning/PositioningImperativeAnchorTarget.stories.tsx, packages/react-components/react-components/src/Concepts/Positioning/PositioningOffsetFunction.stories.tsx, packages/react-components/react-components/src/Concepts/Positioning/PositioningOffsetValue.stories.tsx
See comments on files directly 👇
=> docs: cleanup docs pages

packages/react-components/react-badge/src/stories/PresenceBadge.stories.tsx
We don't use spaces for components' names in the sidebar.
=> docs(react-badge): fix title in sidebar

package.json, yarn.lock
Upgrades the following dependencies:
- y18n 4.0.0 -> 4.0.3 ([CVE-2020-7774](https://github.com/advisories/GHSA-c4w7-xm78-47vh))
- ansi-regex 3.0.0 -> 3.0.1 ([CVE-2021-3807](https://github.com/advisories/GHSA-93q8-gq69-wqmw))
- ansi-regex 4.0.1 -> 4.1.1 ([CVE-2021-3807](https://github.com/advisories/GHSA-93q8-gq69-wqmw))
- requestretry 2.0.2 -> 7.0.0 (https://github.com/advisories/GHSA-hjp8-2cm3-cc45)
`screener-runner` depends on 2.0.0 but parent dependency `screener-storybook` uses 7.0.0.
- workspace-tools 0.16.2 -> 0.18.4 (https://github.com/advisories/GHSA-5875-m6jq-vf78)
Fixes #23136
=> fix: Address component governance issues

change/@fluentui-react-radio-5f7a594b-d9a0-498d-b89d-9931a9aa8ce5.json, packages/react-components/react-radio/src/stories/RadioGroupBestPractices.md
Hides "Best Practices" section under a spoiler as in other components.
=> docs(react-radio): make Best Practices collapsible

change/@fluentui-react-link-2ddae486-b8c1-4c57-9980-5f22d8b7dda7.json, packages/react-components/react-link/src/stories/Link.stories.tsx, packages/react-components/react-link/src/stories/LinkDescription.md
This PR fixes a missing dot in the description:
I also created `.md` files for description & best practices. It should be nice to fill the last one 😉
=> docs(react-link): fix missing dot, create missing files

packages/react-components/react-spinbutton/src/stories/SpinButton.stories.tsx, packages/react-components/react-spinbutton/src/stories/SpinButtonBounds.stories.tsx, packages/react-components/react-spinbutton/src/stories/SpinButtonControlled.stories.tsx, packages/react-components/react-spinbutton/src/stories/SpinButtonDisabled.stories.tsx, packages/react-components/react-spinbutton/src/stories/SpinButtonDisplayValue.stories.tsx, packages/react-components/react-spinbutton/src/stories/SpinButtonRTL.stories.tsx, packages/react-components/react-spinbutton/src/stories/SpinButtonSize.stories.tsx, packages/react-components/react-spinbutton/src/stories/SpinButtonStep.stories.tsx, packages/react-components/react-spinbutton/src/stories/SpinButtonUncontrolled.stories.tsx
SpinButton stories use CSS `flex-gap` and have shared styles preventing easy copy-paste of examples.
- Removes all instances of flex-gap from SpinButton stories
- Refactors story styles so all styles necessary for a story are included with it. Previously, the root story had global styles. This change makes it easier to look at the code to see what's happening and copy-paste as needed.
#22704
=> react-spinbutton: remove flex-gap from stories

change/@fluentui-react-avatar-1a0bc871-7b4e-4589-9019-45fb4e8a48f9.json, packages/react-components/react-avatar/src/components/Avatar/Avatar.test.tsx, packages/react-components/react-avatar/src/components/Avatar/useAvatar.tsx
The Avatar Size example had `aria-labelledby="undefined"`, caused by a lack of default label for the initials slot.
This PR adds a default `id` prop to the slot, which is then used by `aria-labelledby` when no name is provided. This should work whether the author passes in a string or slotProps with or without an explicit `id`.
=> fix(react-avatar): update Avatar initials to be used as fallback label even without author id

change/@fluentui-react-slider-07687c06-fb88-4671-a9ab-25b5a821ae42.json, packages/react-components/react-slider/src/components/Slider/useSliderStyles.ts
fixes #23149
Add specific high contrast styles for slider steps to ensure that they are visible.
before
after
=> new high contrast styles for slider steps

change/@fluentui-react-spinner-28531f36-212d-4200-8910-88a19de43989.json, packages/react-components/react-spinner/README.md, packages/react-components/react-spinner/Spec.md, packages/react-components/react-spinner/etc/react-spinner.api.md, packages/react-components/react-spinner/src/components/Spinner/Spinner.test.tsx, packages/react-components/react-spinner/src/components/Spinner/Spinner.types.ts, packages/react-components/react-spinner/src/components/Spinner/renderSpinner.tsx, packages/react-components/react-spinner/src/components/Spinner/useSpinner.tsx
This PR is to remove the `status` prop from `Spinner` and add documentation about changing the active state of `Spinner` in documentation
Fixes #23184
=> [BREAKING] Remove `status` prop in Spinner

apps/vr-tests-react-components/src/stories/Label.stories.tsx, change/@fluentui-react-label-202fb7e6-5017-4358-bb13-905f5150f2a3.json, packages/react-components/react-label/etc/react-label.api.md, packages/react-components/react-label/src/components/Label/Label.types.ts, packages/react-components/react-label/src/components/Label/useLabel.tsx, packages/react-components/react-label/src/components/Label/useLabelStyles.ts, packages/react-components/react-label/src/stories/Label.stories.tsx, packages/react-components/react-label/src/stories/LabelWeight.stories.tsx
`Label` uses the `strong` prop to render a semibold state.
`Label` uses the `weight` prop to render a semibold state.
Fixes #23222
=> [BREAKING] react-label: Rename strong prop to weight to align with Text

change/@fluentui-eslint-plugin-2c3414b0-7f2f-4207-ab2c-4f64f742f5f1.json, packages/eslint-plugin/src/configs/base.js, packages/eslint-plugin/src/configs/react.js, packages/eslint-plugin/src/rules/ban-context-export/index.js, packages/eslint-plugin/src/rules/ban-context-export/index.test.js, packages/eslint-plugin/src/utils/type-services.js
ban-context-export is part of base, thus is applied on node.js apps which is out of scope
- ban-context is applied only on web related packages in v9
- some additional refactoring to encapsulate type information acquisition within custom rules etc
Follows #23141
=> fix(eslint-plugin): move ban-context to react config from base

.codesandbox/ci.json, .devops/templates/tools.yml, package.json
- our wiki says that we support node 14 and node 16 but there are no tooling restrictions
- our CI is using 14.x
- contributors can use any version, thus run into unexpected issues
- after adding griffel lint user on node lower than 14.7 wont be able to install dependencies locally
- https://github.com/microsoft/fluentui/pull/22961/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR5966 
- we cover our wiki  node support 14 by tooling
- our ci is using explicitly 14.8.1 which is last supported version to make everything work
- we setup `"engines"` in our package.json to enforce contributors to use node versions that are LTS and latest maintenance mode (14.8.1)
- what about NodeJS v18 (Current) support - ATM we use dependencies that don't support Node 18 …
=> ci: add node.js engines restrictions/source of truth

.devcontainer/devcontainer.json, .vscode/extensions.json
We have `snapshot-tools` as recommended extension on vscode, which seems to me as a bit too opinionated, as Fluent UI monorepo doesn't require it to work properly.
Removes `snapshot-tools` as recommended extension and adds the other extensions on devcontainer to automatically install on container usage.
=> chore: Removes opinionated vscode extension recommendation

apps/public-docsite-v9/.storybook/main.utils.js, change/@fluentui-react-components-8ecebe2c-3d74-499f-8aca-ca4ed8c45f1b.json, packages/react-components/react-components/.storybook/main.utils.js, packages/react-components/react-components/etc/react-components.unstable.api.md, packages/react-components/react-components/package.json, packages/react-components/react-components/src/unstable/index.ts
`react-overflow` is not exported from `react-components`
`react-overflow` is exported from `react-components/unstable`
Fixes #23179
=> feat: Export react-overflow utilities as unstable

packages/react-components/react-divider/src/stories/DividerCustomStyles.stories.tsx
This PR removes the usage of direct colors and replaces them with tokens to show right patterns.
=> docs(react-divider): use colors instead of direct colors in the story

packages/react-components/react-badge/src/stories/CounterBadgeAppearance.stories.tsx, packages/react-components/react-badge/src/stories/CounterBadgeColor.stories.tsx, packages/react-components/react-badge/src/stories/CounterBadgeDefault.stories.tsx, packages/react-components/react-badge/src/stories/CounterBadgeDot.stories.tsx, packages/react-components/react-badge/src/stories/CounterBadgeShapes.stories.tsx, packages/react-components/react-badge/src/stories/CounterBadgeSizes.stories.tsx
This PR removes `.args` usage from stories as they are not support by our CodeSandbox export. This causes a bad issue as after the export there is nothing:
For example, https://codesandbox.io/s/vcgu1o?file=/example.tsx
=> docs(react-badge): remove .args usage in CounterBadge stories

change/@fluentui-react-tabster-a9d2f52c-1973-4333-8f19-c4566036b6d4.json, packages/react-components/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts
- `createCustomFocusIndicatorStyle ` uses `:focus-visible` to remove default browser focus outline but that pseudo-class would not be supported by our browser matrix. 
- Use `:focus` pseudo-class instead to achieve same result of removing focus outline. 
Partially fixes #23020
=> react-tabster: Remove usage of :focus-visible to conform to browser matrix

packages/react-components/theme-designer/package.json, packages/react-components/theme-designer/src/components/Content/Content.tsx, packages/react-components/theme-designer/src/components/Demo/Demo.stories.tsx, packages/react-components/theme-designer/src/components/Demo/Demo.tsx
Added the examples section to the content section of the theme designer.
=> Theme designer: FluentUI v9 scaffold content examples

change/@fluentui-react-0c3014eb-a6a2-4164-9b1c-2415ab57a8dd.json, packages/react/src/components/Button/BaseButton.tsx, packages/react/src/components/Button/SplitButton/SplitButton.styles.ts
Fixes #21334
Previously, if the root button of `SplitButton` had its width set greater than the default width of its inner content, the inner buttons did not stretch to fit the root width. This PR updates internal splitbutton styles to fix this.
Past behavior:
New behavior:
=> fix(SplitButton): update flex styles so the inner splitbutton stretches to fill the root

packages/react-components/theme-designer/package.json
- `theme-designer`'s dependencies are not automatically updated after every v9 release because it doesn't have 9.0.0 as its version which excludes it from v9 scoping. This results in having to manually upgrade its package dependencies to fix syncpack mistmatches.
- changes version scope to `9.0.0-alpha.0` so package dependencies should now get auto bumped whenever a new v9 release is made.
=> theme-designer: Update package version to 9.0.0 to auto-update package deps after new v9 releases

azure-pipelines.release-vnext-nightly.yml
Nightly releases do not run `syncpack` or the component governance checks we do for normal releases.
Added `syncpack` and component governance checks to nightly releases.
Also noticed how we're using `continueOnError: true`, perhaps we should remove this?
=> ci: align v9 release checks for v9 nightly releases

apps/public-docsite-v9/package.json, change/@fluentui-react-avatar-e8465a99-82a6-47aa-a896-aed41ea0000f.json, packages/react-components/react-avatar/.storybook/main.js, packages/react-components/react-avatar/config/api-extractor.local.json, packages/react-components/react-avatar/etc/react-avatar.api.md, packages/react-components/react-avatar/package.json, packages/react-components/react-avatar/src/AvatarGroupItem.ts, packages/react-components/react-avatar/src/components/AvatarGroupItem/AvatarGroupItem.test.tsx, packages/react-components/react-avatar/src/components/AvatarGroupItem/AvatarGroupItem.tsx, packages/react-components/react-avatar/src/components/AvatarGroupItem/AvatarGroupItem.types.ts, packages/react-components/react-avatar/src/components/AvatarGroupItem/__snapshots__/AvatarGroupItem.test.tsx.snap, packages/react-components/react-avatar/src/components/AvatarGroupItem/index.ts, packages/react-components/react-avatar/src/components/AvatarGroupItem/renderAvatarGroupItem.tsx, packages/react-components/react-avatar/src/components/AvatarGroupItem/useAvatarGroupItem.ts, packages/react-components/react-avatar/src/components/AvatarGroupItem/useAvatarGroupItemStyles.ts, packages/react-components/react-avatar/src/index.ts, packages/react-components/react-avatar/src/stories/AvatarGroupItem.stories.beta.tsx, packages/react-components/react-avatar/src/stories/AvatarGroupItemBestPractices.md, packages/react-components/react-avatar/src/stories/AvatarGroupItemDefault.stories.tsx
This PR creates the `AvatarGroupItem` component that will be used by AvatarGroup.
#22240 and #22736
=> react-avatar: Creating AvatarGroupItem component

change/@fluentui-react-select-2b040bfc-4f00-4690-a56f-cb7a66ac9aa9.json, packages/react-components/react-select/src/components/Select/useSelectStyles.ts
Adds the disabled border color to Select, to match the Input spec. Also adds that color to the down arrow icon, as well as adding HCM colors.
=> react-select: fix disabled border color, and HCM styles

change/@fluentui-react-585cf689-44c1-4b45-9155-4ac53e9339be.json, packages/react/src/components/List/List.test.tsx, packages/react/src/components/List/List.tsx
List component doesn't update when className property changes.
List component updates when className property changes.
Fixes #23125
=> Fixed bug where className changes in List props does not cause a rerender

tools/generators/add-codeowners.spec.ts, tools/generators/add-codeowners.ts
when `create-package` is invoked `migrate-converged-pkg` incorrectly copies codeowners placeholder, which creates consecutive packages with commented codeowner thus defeating its main purpose
codeowners file is updated as expected
- https://github.com/microsoft/fluentui/commit/b37857d57e72e2f0c5787411ec1dde35b9145847#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R156
- https://github.com/microsoft/fluentui/pull/23320/files#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7L167
=> fix(tools): don't add addition # when adding codeowners

change/@fluentui-react-components-1a69c62b-6d1a-41e1-8088-ad70c2eb8ce2.json, change/@fluentui-react-tabster-1cf49a3e-7aaa-4a4f-a0e7-42bacc9d2774.json, packages/react-components/react-components/src/Concepts/Accessibility/AccessibleComponents.stories.mdx, packages/react-components/react-components/src/Concepts/Accessibility/FocusIndicator.stories.mdx, packages/react-components/react-tabster/src/hooks/useKeyboardNavAttribute.ts, packages/react-components/react-tabster/src/stories/FocusIndicator.stories.mdx
There is no documentation available on how to use focus indication methods provided by `@fluentui/react-tabster`
Provides documentation under `Accessibility` about how to use and why we have a focus indication mechanism in FluentUI
=> docs(react-tabster): adds stories for focus indicator documentation

apps/vr-tests-react-components/src/stories/Card.stories.tsx, change/@fluentui-react-card-1c5d944f-4249-4cbd-8a96-9b0753d456ad.json, change/@fluentui-react-components-b30f5c5b-6e1e-4e0a-bf92-4674a1dff190.json, packages/react-components/react-card/Spec.md, packages/react-components/react-card/etc/react-card.api.md, packages/react-components/react-card/src/components/Card/Card.types.ts, packages/react-components/react-card/src/components/Card/useCard.ts, packages/react-components/react-card/src/components/Card/useCardStyles.ts, packages/react-components/react-card/src/index.ts, packages/react-components/react-card/src/stories/Card.stories.tsx, packages/react-components/react-card/src/stories/CardFocusMode.stories.tsx, packages/react-components/react-card/src/stories/CardSize.stories.tsx, packages/react-components/react-card/src/stories/SampleCard.stories.tsx, packages/react-components/react-components/etc/react-components.unstable.api.md, packages/react-components/react-components/src/unstable/index.ts
Added the `size` property which will control:
- Container padding
- Padding in-between children
- Border radius
#19336
=> feat(react-card): add `size` prop

.storybook/preview.js
We don't support the latest and greatest React 18 (#22581), so let's use at least something that is supported currently.
Fixes #23242
=> fix: use React 17 in CodeSandbox exports

apps/public-docsite-v9/package.json
Bumps dependencies after a release. This is manual fix for a known issue.
=> manual syncpack after rc.14 release

change/@fluentui-react-d3e09d56-0762-43c9-8c50-ab7284729cc6.json, packages/react-examples/src/react/DetailsList/DetailsList.CustomColumns.Example.tsx, packages/react/etc/react.api.md, packages/react/src/components/DetailsList/DetailsColumn.base.tsx, packages/react/src/components/DetailsList/DetailsColumn.test.tsx, packages/react/src/components/DetailsList/DetailsList.types.ts, packages/react/src/components/DetailsList/__snapshots__/DetailsColumn.test.tsx.snap
A column that could be sorted (e.g., has an onColumnClick function that sets the isSorted/isSortedDescending properties on the column) does not provide any indicator that it is sortable. 
A column that could be sorted can (backwards compatible, so not set by default) be made to show a sort icon (up + down arrow) and have an aria-label indicating the column could be sorted.
Fixes #21767
=> Feat: add sortable icon & aria-label on DetailsList column

.github/workflows/pr-housekeeping.yml
`add-to-milestone` action succeeds but does not add to latest milestone.
New version brings more logging, allowing us to debug why the action is misbehaving exclusively on our repo.
=> chore: update `add-to-milestone` action to latest version

change/@fluentui-react-avatar-84eb3928-ce1b-4f75-b739-5d34a7ed068f.json, change/@fluentui-react-badge-e514e2fd-0699-46c4-ad97-92cb6069877e.json, packages/react-components/react-avatar/src/components/Avatar/Avatar.test.tsx, packages/react-components/react-avatar/src/components/Avatar/useAvatar.tsx, packages/react-components/react-avatar/src/stories/AvatarBadge.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarDefault.stories.tsx, packages/react-components/react-badge/src/components/PresenceBadge/__snapshots__/PresenceBadge.test.tsx.snap, packages/react-components/react-badge/src/components/PresenceBadge/usePresenceBadge.tsx
I started to fix the Avatar Status stories by removing the explicit `aria-label`, and then realized a few other things needed to be sorted out as well. In addition to removing the `aria-label` from the stories, the primary purpose of the changes here are to future-proof our naming approach for Avatar/Badge:
- The PresenceBadge element with `aria-label` is now the root, so that if outside components pass it an `id` to use with `aria-labelledby` or `aria-describedby` (such as Avatar), then the id-referenced element is the same one as has `aria-label`. The reason this matters is pretty complex, but essentially I'm worried that a child generic element with `aria-label` may not be reliably used in the accName calculation.
- The PresenceBadge element that gets `aria-label` is no longer hidden …
=> fix(react-avatar): sort out PresenceBadge usage and attributes

change/@fluentui-react-menu-aac7f279-a6fd-4470-8446-66ec9860c2b0.json, packages/react-components/react-menu/src/components/MenuSplitGroup/useMenuSplitGroupStyles.ts
Menu uses `:before`
Menu uses `::before`
Fixes #23176
=> fix: Use modern `::before` pseudoelement

.storybook/docs-root.css
=> docs: Update the source code z-index to be 0

change/@fluentui-react-menu-9acac1a7-cc78-457e-9877-f60551efcb2a.json, packages/react-components/react-menu/src/components/MenuItem/useMenuItem.tsx, packages/react-components/react-menu/src/components/MenuItem/useMenuItemStyles.ts
For submenu indicator, use filled icon on hover:
=> fix(react-menu): submenu indicator should be filled on hover

change/@fluentui-react-menu-f51ecf4d-30df-4712-89b0-3f2e9343ca0c.json, packages/react-components/react-menu/e2e/Menu.e2e.tsx, packages/react-components/react-menu/etc/react-menu.api.md, packages/react-components/react-menu/src/components/Menu/Menu.types.ts, packages/react-components/react-menu/src/components/Menu/useMenu.tsx
Context menus should close on scroll outside. Also adds a
`closeOnScroll` prop to be consistent with `Popover` introduced in #22784
Menu with `openOnContext` does not close on scroll
Menu with `openOnContext` closes on scroll
Fixes #
=> feat: Close context menu on scroll, new closeOnScroll prop

.github/CODEOWNERS, .prettierignore
Removes `teams-prg` ownership on Accordion component
Adds CODEOWNERS file to `.prettierignore`
=> chore: removes teams-prg ownership on accordion

change/@fluentui-react-button-b1502248-3d52-496f-99be-70bf2247d014.json, packages/react-components/react-button/src/components/Button/useButtonStyles.ts
`Button` hover styles are not guaranteed to have correct contrast between background and foreground colors in High Contrast mode.
`Button` hover styles are now guaranteed to have correct contrast between background and foreground colors since we are using `HighlightText` and `Highlight` for them respectively.
I don't have a way to show a non-contrasty enough set of colors in Windows 11 but you can see how it does change when using the `Dusk` High Contrast profile:
__Before:__
__After:__
Fixes #23340
=> Button: Fixing hover styles in High Contrast mode

packages/fluentui/CHANGELOG.md, packages/fluentui/react-northstar/src/themes/teams/components/List/listItemHeaderMediaStyles.ts
listItemHeaderMediaStyle should not shrink because it's sibling elment is truncatable. When the width is not enough, previous settings will cause listItemHeaderMedia wrapped to new lines.
No related issues found.
=> fix: Setting 'flex-schrink: 0' on listItemHeaderMediaStyle 

packages/react-components/theme-designer/src/ThemeDesigner.tsx, packages/react-components/theme-designer/src/components/Content/Content.tsx, packages/react-components/theme-designer/src/components/Nav/Nav.tsx, packages/react-components/theme-designer/src/components/Sidebar/Sidebar.tsx
The states in the theme designer now obey this diagram, for the most part:
=> theme designer: fixing states

change/@fluentui-react-button-7276bbe3-2ce4-42d5-b717-c2c87e8b0c2b.json, change/@fluentui-react-button-b1502248-3d52-496f-99be-70bf2247d014.json, packages/react-components/react-button/src/components/Button/useButtonStyles.ts
#23384 fixed hover color styles in High Contrast for `Buttons`. However, we forgot to include a couple of forced color adjust overrides needed for them.
Follow up to #23384
=> Button: Adding missing forced color adjust overrides

change/@fluentui-react-button-2692d635-528d-45d6-8b33-5d98028b6060.json, change/@fluentui-react-checkbox-5f29fcf9-ff59-4c28-be1d-7b7a4a79268e.json, change/@fluentui-react-link-8aa95273-588e-44b2-a6cc-9a583e8cf800.json, packages/react-components/react-button/README.md, packages/react-components/react-button/src/components/Button/MIGRATION.md, packages/react-components/react-checkbox/MIGRATION.md, packages/react-components/react-checkbox/README.md, packages/react-components/react-checkbox/Spec.md, packages/react-components/react-link/MIGRATION.md, packages/react-components/react-link/README.md
This PR cleans up the READMEs and migration guides of `react-button` and `react-link` so they link to the storybook and reference `v9` instead of `Converged` terminology.
This PR also cleans up a bunch of things in `react-checkbox`:
- The migration guide is updated to remove WIP warnings and to more correctly reflect new types. A new `Property mapping` table across v0, v8 and v9 versions is also added.
- The README is updated to remove WIP warnings and reference importing from `react-components` instead of from `react-checkbox` in examples.
- The spec is updated to properly format tables.
=> README, spec and migration guide cleanup for react-button, react-checkbox and react-link

change/@fluentui-react-switch-6a55c865-0569-4729-81c9-4c5129b184da.json, packages/react-components/react-switch/MIGRATION.md, packages/react-components/react-switch/README.md, packages/react-components/react-switch/Spec.md
This PR cleans up a bunch of things in `react-switch`:
- The migration guide is updated to remove WIP warnings and to fix some typos.
- The README is updated to remove WIP warnings, reference importing from `react-components` instead of from `react-switch` in examples, update examples in general, and point to the spec and migration guides.
- The links to the types file and migration guides are updated in the spec.
=> README, spec and migration guide cleanup for react-switch

packages/fluentui/CHANGELOG.md, packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx, packages/fluentui/react-northstar/test/specs/components/Dropdown/Dropdown-test.tsx
Following change reoved selected value from the Dropdown label:
Fix Dropdown not annoucing placeholder/default value with VoiceOver on macOS @aubreyquinn (https://github.com/microsoft/fluentui/pull/22173)
This PR fixes the original issue by pointing aria-labelledby to the trigger button content.
Empty state:
Selected item:
Fixes #21887
=> fix(Dropdown) Return selected value to the label

change/@fluentui-react-utilities-636b4fe0-b6f1-4d47-bc86-3e31c41ff2e3.json, packages/react-components/react-utilities/etc/react-utilities.api.md, packages/react-components/react-utilities/src/compose/types.ts
Our `Slot` type does not currently support components that take no `children` prop.
`Slot` now extends `VoidFunctionComponent` to allow for such behavior.
=> feat(react-utilities): extend `Slot` to support `VoidFunctionComponents`

rfcs/shared/build-system/06-browser-support-for-v9.md
This RFC proposes a browser minbar support matrix for v9 to conform to. To get breakdown that led to this matrix, please read this [document](https://microsoft.sharepoint-df.com/teams/FluentUIInternal/_layouts/15/Doc.aspx?sourcedoc=%7B66e5f1ff-23d0-49ab-9a7d-acf3b47344f3%7D&action=edit&wd=target(Build%20system.one%7C13440648-7e78-4299-bc71-661d59756ff2%2FV9%20Browser%20Minbar%20Conclusion%7Cfe9116b5-693e-4559-aaf2-27ca7725abd2%2F)&share=IgH_8eVm0COrSZp9rPO0c0TzAZ1rnQYDmLb_8iCSF8BicSQ).
[Preview👀](https://github.com/microsoft/fluentui/pull/22889/files?short_path=6386842#diff-638684245ec063dc55bc05729c53b47175161565a02cdf30fb334a8a59fbf863)
Current global browser coverage of proposed browser matrix: **88%**
- https://browserslist.dev/?q=Y2hyb21lID49IDg0LCBmaXJlZm94ID49IDc1LCBlZGdlID49IDg0LCB …
=> RFC: Browser Support Minbar for v9

change/@fluentui-web-components-80f9d773-bd90-490e-9d09-9a7c5518fa5b.json, packages/web-components/src/_docs/design-system/color-explorer/components/color-block.ts, packages/web-components/src/_docs/design-system/color-explorer/components/swatch.ts
The Color Explorer has been recently incorporated to the web component Storybook site. We discovered the hex values were not always updating correctly.
This fixes a timing or dependency issue for evaluating the hex values for the color recipes.
=> (web-components) Fix issue loading Color Explorer values

change/@fluentui-react-535f80fc-7fe0-4cd7-8957-74ee2076c4f6.json, packages/react/src/components/DatePicker/DatePicker.base.tsx
Stops propagation on escape all the time
Only stop propagation when the picker is open and esc dismisses it.
https://github.com/microsoft/fluentui/issues/23308
=> Only stop esc propagation if the date picker is open

change/@fluentui-react-select-cf0563de-cd23-46b9-b8f9-2c807285bc89.json, packages/react-components/react-select/etc/react-select.api.md, packages/react-components/react-select/src/components/Select/Select.test.tsx, packages/react-components/react-select/src/components/Select/Select.types.ts, packages/react-components/react-select/src/components/Select/useSelect.tsx, packages/react-components/react-select/src/stories/SelectControlled.stories.tsx
Updates react-select's onChange handler to match other form controls and include the value data as the second param.
Includes tests, and updates the Controlled example as well.
=> react-select: add onChange handler with value data

change/@fluentui-react-slider-8e5f30f9-2e26-41ee-87f9-26704140ab06.json, packages/react-components/react-slider/MIGRATION.md, packages/react-components/react-slider/README.md, packages/react-components/react-slider/Spec.md
This PR cleans up a bunch of things in `react-slider`:
- The migration guide is updated to add a property mapping table between v0, v8 and v9.
- The README is updated to point to our storybook docs, reference importing from `react-components` instead of from `react-slider` in examples, and point to the spec and migration guides.
- The spec is updated to add a slots section and add links to both the types file and migration guide.
=> README, spec and migration guide cleanup for react-slider

tools/generators/migrate-converged-pkg/index.spec.ts, tools/generators/migrate-converged-pkg/index.ts
storybook setup is added to packages where its not needed
storybook is added only to packages that actually use/need storybook setup
Fixes #20724
=> fix(tools): setup/update storybook only if there stories do exist

change/@fluentui-react-divider-f4ab1379-0588-464e-922d-979cd9d023ce.json, change/@fluentui-react-slider-97c56ec3-b7a8-4325-b158-602983349bdd.json, change/@fluentui-react-switch-22e06122-91ad-46fe-b5ee-35c49c1b19ec.json, packages/react-components/react-divider/MIGRATION.md, packages/react-components/react-divider/README.md, packages/react-components/react-divider/Spec.md, packages/react-components/react-slider/README.md, packages/react-components/react-switch/README.md
This PR cleans up a bunch of things in `react-divider`:
- It updates the migration guide to put it more in line with the guides in other packages.
- The README is updated to point to our storybook docs, reference importing from `react-components`, add usage examples, and point to the spec and migration guides.
- The spec is updated to add links to both the types files and migration guide.
This PR also includes small cleanups in `react-slider` and `react-switch` READMEs.
Fixes part of #23423.
=> README, spec and migration guide cleanup for react-divider

packages/react-components/react-toolbar/src/stories/Toolbar.stories.tsx
Move `Toolbar` stories to under **Preview Components**
=> chore: move toolbar stories to preview components

rfcs/shared/build-system/ssr-testing.md
We are targeting first class support for SSR in `@fluentui/react-components`, #17893. The missing piece is automated testing to prevent our components from breaking due changes.
This RFC is focused on the implementation proposal for such test.
------
[**Rendered preview**](https://github.com/layershifter/office-ui-fabric-react/blob/rfc/ssr-testing/rfcs/shared/build-system/ssr-testing.md)
=> RFC: SSR testing for `@fluentui/react-components`

change/@fluentui-react-card-e777c74a-8a55-4940-928a-da44df8f760b.json, packages/react-components/react-card/etc/react-card.api.md, packages/react-components/react-card/src/components/Card/useCardStyles.ts
Card uses browser focus indicators
Card applies the design specific focus indicators
#19336
=> feat(react-card): add focus indicators

change/@fluentui-react-image-68ae7370-4764-401f-a213-1672d7facee0.json, packages/react-components/react-image/MIGRATION.md, packages/react-components/react-image/README.md, packages/react-components/react-image/Spec.md
This PR cleans up a bunch of things in `react-image`:
- It updates the migration guide to make it up to date with the latest information.
- The README is updated to make it more inline with our other READMEs.
- The spec is updated to add links to both the types files and migration guide.
Fixes part of #23423.
=> README, spec and migration guide cleanup for react-image

packages/react-components/theme-designer/src/ThemeDesigner.tsx, packages/react-components/theme-designer/src/components/Sidebar/Sidebar.tsx
Theme designer used to update every second when the color was being changed, making it very laggy. Now it only updates when the user clicks out of the color palette.
=> theme designer: add onBlur to color picker

change/@fluentui-react-avatar-a3217e5a-2124-4a29-980e-e97081b08cf3.json, packages/react-components/react-avatar/etc/react-avatar.api.md, packages/react-components/react-avatar/package.json, packages/react-components/react-avatar/src/components/AvatarGroup/AvatarGroup.types.ts, packages/react-components/react-avatar/src/components/AvatarGroup/renderAvatarGroup.tsx, packages/react-components/react-avatar/src/components/AvatarGroup/useAvatarGroup.tsx, packages/react-components/react-avatar/src/components/AvatarGroup/useAvatarGroupStyles.ts, packages/react-components/react-avatar/src/components/AvatarGroupItem/AvatarGroupItem.types.ts, packages/react-components/react-avatar/src/components/AvatarGroupItem/useAvatarGroupItem.ts, packages/react-components/react-avatar/src/components/AvatarGroupItem/useAvatarGroupItemStyles.ts, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupLayout.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/index.stories.beta.tsx, packages/react-components/react-avatar/src/stories/AvatarGroupItem/index.stories.beta.tsx
This PR adds the following changes:
* Removes overflow list slot and adds `role="list"` to the overflow surface.
* Adds styling for `pie`, `spread`, and `stacked` layouts.
* Note that this PR does not change the `AvatarGroupItem`, so styles might seem off.
* Adds styling to overflow button to match design spec.
* Adds Layout story.
Related #23417
=> react-avatar: Adding layout and overflow button styles to AvatarGroup

change/@fluentui-react-87609c16-e599-49cf-91e0-2ac09923a565.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx, packages/office-ui-fabric-react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Cherry-pick #19667 to 7.0
Fix Dropdown to only add ARIA live region when focused
=> Cherry-pick #19667 to 7.0

azure-pipelines.yml
There is no real reason to scope cypress tests because the `--since`
argument in lage should already help with running only affected tests
=> chore: unscope cypress E2E in CI

change/@fluentui-react-label-7c91e6ff-b4fa-4503-9f9c-2b70f5a62d15.json, packages/react-components/react-label/MIGRATION.md, packages/react-components/react-label/README.md, packages/react-components/react-label/Spec.md
This PR cleans up a bunch of things in `react-label`:
- It updates the migration guide to remove WIP warnings, add better wording and a property mapping table between v8, v0 and v9.
- The README is updated to remove WIP warnings and add links to the migration guide.
- The spec is updated to properly format tables and add a link to the types file.
Fixes part of #23423.
=> docs: README, spec and migration guide cleanup for react-label

change/@fluentui-react-textarea-089c5471-7d76-4622-b1a9-70af572fb526.json, packages/react-components/react-textarea/src/components/Textarea/useTextareaStyles.ts
Textarea doesn't have the following styles:
- `min-height` for all size variants.
- Correct font family for `large` variant.
- Vertical padding.
Textarea now has:
- `min-height` for all size variants.
- Correct font family for `large` variant.
- Vertical padding.
Fixes #23476
=> fix(react-textarea): Adding missing spacing, min-height, and font family styles

change/@fluentui-react-fbe1cb4e-6137-4002-b0f7-c14c18070af0.json, packages/react/src/components/CalendarDayGrid/CalendarDayGrid.base.tsx
Fixes [14272](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/14272)
We had a bug where using arrow keys when hitting a min/max date boundary would close the datepicker. This was caused by the key's default behavior (scroll) not being prevented when focus didn't move.
This PR sets FocusZone's `preventDefaultWhenHandled` to `true` to prevent keyboard scroll behavior when focus is within the day grid.
=> Calendar/Datepicker: preventDefault for FocusZone keys to prevent scroll

change/@fluentui-react-1c69b2a4-8b4f-43fd-bfb9-02d2307b9b4b.json, packages/react/etc/react.api.md, packages/react/src/components/DetailsList/DetailsList.base.tsx, packages/react/src/components/DetailsList/DetailsList.test.tsx, packages/react/src/components/DetailsList/DetailsList.types.ts
When a user focuses on DetailsList's header and then uses the down arrow keys to focus the first item in the list [that item is always selected when there is no other selection.](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/DetailsList/DetailsList.base.tsx#L636-L637) When navigating DetailsList users can typically use `ctrl + arrow up/down` to navigate the list without changing the selection but this does not work when moving from the header to the first item in the list.
Adds a new optional prop, `isSelectedOnFocus` to DetailsList to control whether items in the list are selected on focus. By default the value for this prop is `true` and the existing behavior of DetailsList is preserved.
When setting this value to `false` the behavior in …
=> feat: add isSelectedOnFocus prop to DetailsList

change/@fluentui-react-avatar-9515b813-271c-4458-945c-07b16c7c979b.json, packages/react-components/react-avatar/etc/react-avatar.api.md, packages/react-components/react-avatar/src/components/AvatarGroup/AvatarGroup.types.ts, packages/react-components/react-avatar/src/components/AvatarGroup/renderAvatarGroup.tsx, packages/react-components/react-avatar/src/components/AvatarGroup/useAvatarGroup.tsx, packages/react-components/react-avatar/src/components/AvatarGroupItem/AvatarGroupItem.types.ts, packages/react-components/react-avatar/src/components/AvatarGroupItem/useAvatarGroupItem.ts, packages/react-components/react-avatar/src/components/AvatarGroupItem/useAvatarGroupItemStyles.ts, packages/react-components/react-avatar/src/contexts/AvatarGroupContext.types.ts, packages/react-components/react-avatar/src/stories/AvatarGroupItem/AvatarGroupItemOverflow.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroupItem/index.stories.beta.tsx
This PR does the following:
* Adds styles to `AvatarGroupItem` for each layout.
* Makes it so `AvatarGroupItem` doesn't render as `<li>` anymore.
* Adds `avatarCount` to `AvatarGroupContext`.
#23417 #22240
=> react-avatar: Adding styles to AvatarGroupItem

change/@fluentui-react-avatar-1ba68c71-162c-4b9f-8630-535d9a4cf36c.json, change/@fluentui-react-divider-1066d1cd-c0c3-4192-b549-cb296750fb99.json, change/@fluentui-react-positioning-b99bfbf7-2838-4af8-8995-0f2deacc190a.json, change/@fluentui-react-select-b3f66604-dd5a-4167-90b2-d20de51b9559.json, change/@fluentui-react-slider-a36201c8-83ef-4fac-9ce4-79565421d5e6.json, change/@fluentui-react-tabs-1292f596-199f-4ce1-8f55-58aabf04cc25.json, change/@fluentui-react-tabster-9ce21a30-565f-44ef-b889-e3a4be30a145.json, change/@fluentui-react-textarea-575e5bf5-7a8e-41a2-bb64-db7d82cddd6a.json, packages/react-components/react-avatar/src/components/Avatar/useAvatarStyles.ts, packages/react-components/react-divider/src/components/Divider/useDividerStyles.ts, packages/react-components/react-divider/src/stories/DividerCustomStyles.stories.tsx, packages/react-components/react-positioning/src/createArrowStyles.ts, packages/react-components/react-select/src/components/Select/useSelectStyles.ts, packages/react-components/react-slider/src/components/Slider/useSliderStyles.ts, packages/react-components/react-tabs/src/components/Tab/useTabAnimatedIndicator.ts, packages/react-components/react-tabster/src/focus/createFocusOutlineStyle.ts, packages/react-components/react-textarea/src/components/Textarea/useTextareaStyles.ts
Some components in `@fluentui/react-components` are still using the older `:before` and `:after` syntax, which is fine, however we should try to wholesale use the newer `::before` and `::after`.
All components in `@fluentui/react-components` use the newer `::before` and `::after` syntax.
=> chore: Using ::before and ::after instead of :before and :after

change/@fluentui-react-avatar-d3231ec7-f72e-4a15-9ebe-873408209cd8.json, packages/react-components/react-avatar/src/components/AvatarGroup/useAvatarGroup.tsx, packages/react-components/react-avatar/src/components/AvatarGroupItem/useAvatarGroupItem.ts
* AvatarGroup does not warn if an Avatar component is used instead of AvatarGroupItem.
* AvatarGroupItem does not warn if it isn't being used inside an AvatarGroup.
* AvatarGroup now warns if a child is not of type AvatarGroupItem.
* AvatarGroupItem now warns if it isn't being used inside an AvatarGroup.
#22240
=> chore(react-avatar): Adding warnings on use of AvatarGroup and AvatarGroupItem

change/@fluentui-react-avatar-7a2b7723-c2ad-4bfb-b903-28b059b54fd6.json, packages/react-components/react-avatar/src/components/AvatarGroup/useAvatarGroupStyles.ts, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupColor.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupIndicator.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupLayout.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupMaxAvatars.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupSizePie.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupSizeSpread.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupSizeStack.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/index.stories.beta.tsx
AvatarGroup doesn't cover good examples.
AvatarGroup now has good examples.
#22240
=> docs(react-avatar): Adding more AvatarGroup stories

change/@fluentui-react-spinner-d74cede6-32bf-4475-b2a5-fc7751352506.json, change/@fluentui-react-spinner-d9447fdf-f58d-4170-a38a-ba7620ea11ad.json, packages/react-components/react-spinner/MIGRATION.md, packages/react-components/react-spinner/README.md, packages/react-components/react-spinner/Spec.md
This PR cleans up a bunch of things in `react-spinner`:
- It updates the migration guide to add a property mapping table between v8, v0 and v9.
- The README is updated to include links to the storybook, the spec and the migration guide.
- The spec is updated to add a link to the migration guide.
Fixes part of #23423.
=> docs: README, spec and migration guide cleanup for react-spinner

change/@fluentui-react-avatar-a7934ea7-fa8b-4224-af3f-0a54d4fc9b82.json, packages/react-components/react-avatar/src/components/AvatarGroup/useAvatarGroupStyles.ts
Focus indicator is not rendering with the proper colors.
`spread` and `stack` now have the correct focus indicator ring and `pie` has a custom ring on the root slot.
#22240
=> fix(react-avatar): Fixing AvatarGroup's focus indicator 

change/@fluentui-react-20264996-adc8-470e-af8c-a896ac8775c0.json, change/office-ui-fabric-react-d010c2b4-a709-45d8-9375-c90432bec8e9.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx, packages/office-ui-fabric-react/src/utilities/decorators/withResponsiveMode.tsx, packages/office-ui-fabric-react/src/utilities/hooks/useResponsiveMode.test.tsx
* set defaultMode to responsive mode provided as props, so that in error scenarios we can fallback to this mode
* change files
* use documentElement.clientWidth instead of innerWidth
* modifying useResonsiveMode.test.tsx to mock clientWidth
* fixing the dropdown test
Fixes #
=> Use ClientWidth instead of InnerWidth (#23402)

change/@fluentui-react-portal-f582a5e9-5dde-4e66-a109-c3d55fdd0bbf.json, packages/react-components/react-portal/src/components/Portal/usePortalMountNode.ts
Follow up for #22933. This PR updates `Portal` to apply `position` to create [new stacking contexts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). 
Without a stacking context these is no sense to apply `z-index` (check before & after below).
- Before https://codesandbox.io/s/affectionate-mendeleev-vr6b8x
- After https://codesandbox.io/s/mystifying-bogdan-diw11s
----
~~I also had to refactor VR tests as Screener does not handle positioning properly on initial screenshots _sometimes_. New screenshots follow the same strategy as in N* where tooltips/popovers are opened and positioning after load as a new step.~~
_Moved to #23533._
=> fix(Portal): update to create new stacking context

change/@fluentui-react-utilities-5c5c2f2d-aea2-4aeb-81aa-ddbd4dc01b0f.json, packages/react-components/react-utilities/src/hooks/useOnClickOutside.test.ts, packages/react-components/react-utilities/src/hooks/useOnClickOutside.ts
In Electron, iframe can be replaced with webview element type. This has to behave the same as iframe with regards to outside click detection.
=> Consider webview element type for outside click scenarios - v9

change/@fluentui-react-checkbox-e3435fe8-ffd4-469c-8c3d-62249afea0c3.json, packages/react-components/react-checkbox/.storybook/main.js, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxChecked.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxCircular.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxDefault.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxDisabled.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxLabelBefore.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxLabelWrapping.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxLarge.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxMixed.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxRequired.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/index.stories.tsx
Fixes #23519 
Update Checkbox stories to use index.stories.tsx entrypoint and creates new `stories/Checkbox` path
=> Convert @fluentui/react-checkbox stories to index.stories.tsx approach

packages/react-components/theme-designer/package.json, packages/react-components/theme-designer/src/components/Content/Content.tsx
Many people who have looked at the theme designer noticed that some of the colors are a bit off and still need adjustments - those are features that will be implemented and tweaked in the future. This PR adds an alert that reminds users not to expect the colors to be completely accurate.
=> theme designer: add WIP alert

change/@fluentui-react-d8a70a1c-bcd4-4dc2-a5c6-bb6c7fece86b.json, packages/react/src/components/Dropdown/Dropdown.base.tsx
`Dropdown` opens as a `Panel` on smaller screens, but this presents a problem for users of screen readers since they can't close the `Panel` as they are unable to access the backdrop to soft dismiss it.
The `Panel` that opens when `Dropdown` is used on smaller screens now has a close button that can be accessed by screen reader users. Additionally, we are still keeping the focus by default going to the option list so there is no difference to how focus currently behaves when opening the `Dropdown`.
Fixes [ADO 14028](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/14028).
=> fix: Adding close button to Dropdown list when it opens as a panel.

apps/public-docsite/src/pages/Styles/FabricIconsPage/docs/web/FabricIconsSvgUsage.md
Our docs fail to mention that you cannot set the value for an existing icon without unregistering it first.
Demo here https://codesandbox.io/s/bold-sanne-kjpxd1?file=/src/index.tsx:200-209
=> v8 website: update custom SVG usage to mention unregistering icons

change/@fluentui-react-1c69b2a4-8b4f-43fd-bfb9-02d2307b9b4b.json, change/office-ui-fabric-react-bae1fc2f-77ce-4ed2-b613-0ee749776074.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.test.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts, packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap, packages/office-ui-fabric-react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Cherry picks a change to DetailsList from `master` that adds `isSelectedOnFocus`.
Original pull request: #23467
=> Cherry Pick: DetailsList isSelectedOnFocus

.storybook/docs-root.css
Ordered list item text did not meet contrast ratio, and unordered markers were too far away from text, and broke in nested scenarios.
New marker styles inherit font size/lineheight from parent, rather than trying to manually place with fixed line height, font size, and calculated to value. 
I'm guessing the original intent was to center the marker if the text wrapped, but it isn't possible to properly center on the <li> because nested content lives inside of that element. If this becomes a design concern in the future we can look at a custom markdown renderer that wraps list item content in spans so that the span can have the marker. 
Before:
After:
=> fix contrast on ordered list and fix unordered marker layout

change/@fluentui-react-select-90ed0948-29e6-4dd8-8986-14df2d9b3158.json, packages/react-components/react-select/src/components/Select/Select.test.tsx, packages/react-components/react-select/src/components/Select/useSelect.tsx, packages/react-components/react-select/src/stories/SelectInitialValue.stories.tsx
This PR fixes two issues.
- Fixes handling of `defaultValue` in `Select` component (see #23462 for more details)
- Updates `InitialValue` story to use `defaultValue` on `<Select />` instead of `selected` on `<option />` (see #23461). It's the official approach, https://reactjs.org/docs/forms.html#the-select-tag. This issue is blocking #23457 as causes hydration errors with SSR.
Fixes #23461
Fixes #23462
=> fix(Select): handle "defaultValue"

change/@fluentui-react-checkbox-81561378-0c3f-4f50-a665-ba6f5b52f422.json, change/@fluentui-react-radio-ffb7b11e-bcc5-4b44-9efb-c358fbeeba7f.json, change/@fluentui-react-slider-98248aa5-d7bb-405e-a884-1e56297057fc.json, change/@fluentui-react-switch-208b8863-6b08-4ecb-91ca-d3689e0d6771.json, packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts, packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts, packages/react-components/react-slider/src/components/Slider/useSliderStyles.ts, packages/react-components/react-switch/src/components/Switch/useSwitchStyles.ts
The input components that have built-in labels have `user-select: 'none'` set on them with makes their text impossible to copy and prevents people from using tools like read-aloud or dictionary lookup.
The input components that have built-in labels no longer have `user-select: 'none'` set on them, eliminating the problem described above.
Fixes part of #23589
=> fix: Removing user-select: 'none' from label in input components with built-in labels

change/@fluentui-react-avatar-0172fa1d-9de1-463f-9fe9-29f20a05717b.json, packages/react-components/react-avatar/src/components/AvatarGroup/useAvatarGroupStyles.ts, packages/react-components/react-avatar/src/components/AvatarGroupItem/useAvatarGroupItemStyles.ts
Border radius is ignored for the stack layout's outline. This is due to a bug in webkit browser where `outline` ignores both `-webkit-border-radius` and `border-radius`. For more details you can take a look at the bug filed in [here](https://bugs.webkit.org/show_bug.cgi?id=20807).
Outline for stack layouts now works correctly in webkit browsers. To accomplish this, a border has to be added in an `::after` pseudo-element. This affects `useGroupChildClassName` by having to differentiate when the hook is used for the overflowButton. Mostly so that the width can be calculated correctly because the button is applied a border that is not picked up by setting `width: 100%` in the pseudo-element.
#23549 #22240
=> fix(react-avatar): Fix outline styles for stack layout in webkit browsers.

change/@fluentui-react-components-be758ba9-0ea3-4008-bf69-b7888148d832.json, packages/react-components/react-components/etc/react-components.unstable.api.md, packages/react-components/react-components/src/unstable/index.ts
This PR re-exports AvatarGroup and AvatarGroupItem in `@fluentui/react-components/unstable`.
#22240
=> chore(react-components): Re-export AvatarGroup and AvatarGroupItem in react-components/unstable

change/@fluentui-react-popover-a78f11b5-8028-4fd7-bc70-64dd01717b40.json, packages/react-components/react-popover/src/components/Popover/constants.ts, packages/react-components/react-popover/src/components/Popover/usePopover.ts, packages/react-components/react-popover/src/components/PopoverSurface/usePopoverSurfaceStyles.ts
Adds arrow padding value to the popover in the same way that `Tooltip`
does it.
Popover arrow has no padding
Popover arrow has a padding value twice the border radius of the `PopoverSurface`
Fixes #23509
=> fix: Add arrow padding to Popover arrrow

change/@fluentui-react-783fd50b-a4fd-4855-a5a4-24aa5f752db0.json, packages/react/etc/react.api.md, packages/react/src/common/React.types.ts, packages/react/src/components/Announced/Announced.types.ts, packages/react/src/components/Dialog/DialogFooter.types.ts, packages/react/src/components/DocumentCard/DocumentCardDetails.types.ts, packages/react/src/components/DocumentCard/DocumentCardStatus.types.ts, packages/react/src/components/ScrollablePane/ScrollablePane.types.ts, packages/react/src/components/Sticky/Sticky.types.ts, packages/react/src/components/pickers/BasePicker.types.ts, packages/react/src/components/pickers/Suggestions/Suggestions.types.ts
`React.Props` was used to allow clients to pass ref and key to createElement, which is no longer necessary. ClassAttributes<T> is recommended to pass ref.
React18 typing introduces a breaking change that removes this deprecation completely.
FluentUI doesn't use the deprecated type.
Fixes #22423
=> React: Remove deprecated React.props

scripts/create-component/plop-templates/src/stories/{{componentName}}/index.stories.tsx.hbs, scripts/create-component/plop-templates/src/stories/{{componentName}}/{{componentName}}Default.stories.tsx.hbs
fixes #23564
before, stories would import from ../../index
Now packages import from @fluentui/packageName
This avoids issues when needing to move stories around, and will better support future work where we publish our stories for consumption in an external website, or external storybook.
=> Chore: Update component creation to use package-based imports

azure-pipelines.yml
- In the midst of all the build failures from yesterday, this #23370 PR which was only intended for the RC branch somehow made its way to master thus causing CI pipelines to not run for PRs against master.
- PRs sent against master will now trigger CI.
=> (fix): CI now triggers against master PRs

change/office-ui-fabric-react-da6a81a9-3c32-4a49-ad2d-2520b136bdd3.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md, packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx, packages/office-ui-fabric-react/src/components/Modal/Modal.types.ts
**Cherrypick of #23563**
_Original PR description follows:_
The internal `FocusTrapZone` in `Modal` can only be customized through select knobs, which limits how much a user can customize it to their needs.
The internal `FocusTrapZone` in `Modal` can be fully customized by passing a `focusTrapZoneProps` object to `Modal`.
This PR also changes all `@defaultvalue` tags in `Modal.types.ts` to `@default`.
=> feat: Adding focusTrapZoneProps to Modal so we can customize inner FocusTrapZone

packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxChecked.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxCircular.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxDefault.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxDisabled.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxLabelBefore.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxLabelWrapping.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxLarge.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxMixed.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxRequired.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/index.stories.tsx
Follow-up to #23525.
PR updates Checkbox's storybook files to use absolute imports instead of relative imports.
=> Checkbox: Replace relative imports with absolute imports in storybook files

packages/react-components/react-divider/src/stories/Divider/DividerAlignContent.stories.tsx, packages/react-components/react-divider/src/stories/Divider/DividerAppearance.stories.tsx, packages/react-components/react-divider/src/stories/Divider/DividerCustomStyles.stories.tsx, packages/react-components/react-divider/src/stories/Divider/DividerDefault.stories.tsx, packages/react-components/react-divider/src/stories/Divider/DividerInset.stories.tsx, packages/react-components/react-divider/src/stories/Divider/DividerVertical.stories.tsx, packages/react-components/react-divider/src/stories/Divider/index.stories.tsx
Follow-up to https://github.com/microsoft/fluentui/pull/23526.
PR updates Divider's storybook files to use absolute imports instead of relative imports.
=> Divider: Replace relative imports with absolute imports in storybook files

packages/react-components/react-image/src/stories/Image/ImageBlock.stories.tsx, packages/react-components/react-image/src/stories/Image/ImageBordered.stories.tsx, packages/react-components/react-image/src/stories/Image/ImageDefault.stories.tsx, packages/react-components/react-image/src/stories/Image/ImageFallback.stories.tsx, packages/react-components/react-image/src/stories/Image/ImageFit.stories.tsx, packages/react-components/react-image/src/stories/Image/ImageShadow.stories.tsx, packages/react-components/react-image/src/stories/Image/ImageShape.stories.tsx, packages/react-components/react-image/src/stories/Image/index.stories.tsx
Follow-up to https://github.com/microsoft/fluentui/pull/23527.
PR updates Image's storybook files to use absolute imports instead of relative imports.
=> Image: Replace relative imports with absolute imports in storybook files

change/@fluentui-react-theme-sass-cbad7d6f-f322-499a-a0a1-9d4ef6e09c9b.json, packages/react-components/react-theme-sass/sass/colorPaletteTokens.scss
Follow-up for #23608 which removed some `colorPalette` tokens from `react-theme`. This PR removes those tokens from `react-theme-sass`
=> fix(react-theme-sass): Remove color palette tokens which are no longer present in react-theme

change/@fluentui-react-aria-a0b33abf-fcb4-4568-954a-fe8fea127c7c.json, packages/react-components/react-aria/.storybook/main.js
Fixes https://github.com/microsoft/fluentui/issues/23694
Update Aria storybook config to use index.stories.tsx entrypoint.
=> Convert @fluentui/react-aria stories to index.stories.tsx approach

change/@fluentui-react-avatar-4f8775b1-d717-49c5-a688-4998bc9773e3.json, packages/react-components/react-avatar/etc/react-avatar.api.md, packages/react-components/react-avatar/src/utils/getInitials.ts
As per #23577 this PR adds `@internal` to `getInitials` since it is exported in the package, but not in `@fluentui/react-components`.
#23577
=> docs(react-avatar): Adding @internal api access modifier to getInitials

change/@fluentui-react-avatar-2a79d125-b960-4f2f-9785-9234fa093640.json, packages/react-components/react-avatar/bundle-size/AvatarGroup.fixture.js, packages/react-components/react-avatar/bundle-size/AvatarGroupItem.fixture.js
This PR adds bundle size fixtures for AvatarGroup and AvatarGroupItem.
#22240
=> chore(react-avatar): Adding AvatarGroup and AvatarGroupItem bundle size fixtures

change/@fluentui-react-spinbutton-f448dee9-4572-46fd-ae20-96874f4525ca.json, packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButton.tsx
The increment and decrement buttons of our `SpinButton` component are of `type="submit"` which will not work as expected when put inside of a form.
The increment and decrement buttons of our `SpinButton` component are of `type="button"` which should work as expected when put inside of a form.
Fixes #23316
=> fix: Making increment and decrement buttons of SpinButton have 'type=button' instead of 'type=submit'

change/@fluentui-react-accordion-bcbc8c5b-15f9-4b93-a0bf-aa95f7c5e4af.json, packages/react-components/react-accordion/src/components/AccordionHeader/useAccordionHeaderStyles.ts
`AccordionHeader` has the `user-select: 'none'` style set on it, which makes its text impossible to copy and prevents people from using tools like read-aloud or dictionary lookup.
`AccordionHeader` no longer has the `user-select: 'none'` style set on it, eliminating the problem described above.
Fixes part of #23589
=> fix: Removing user-select: 'none' from AccordionHeader styles.

apps/vr-tests-react-components/src/stories/Switch.stories.tsx, change/@fluentui-react-switch-69aede67-89a3-43d5-bd02-fd516b545622.json, packages/react-components/react-switch/src/components/Switch/useSwitchStyles.ts
The thumb of the `Switch` is not vertically centered because of some wrong math when calculating the styles of the component.
The thumb of the `Switch` is now vertically centered, with the correct math being applied when calculating the styles of the component.
This PR also updates the visual regression tests for `Switch` so that they crop to the component.
Fixes #23470
=> fix: Making thumb be vertically centered in Switch

rfcs/react-components/convergence/theme-shared-colors.md
This RFC proposes to reduce number of shared color alias tokens to improve performance.
Changing the tokens would be a BREAKING CHANGE!
[PREVIEW](https://github.com/microsoft/fluentui/blob/061e1996cb0decbc1692b6608c4dcceb5c5e5be6/rfcs/react-components/convergence/theme-shared-colors.md)
=> RFC: Reduce number of shared color alias tokens

apps/public-docsite-v9/.storybook/main.utils.js
fixes #23722
Small change that will now only import index.stories.tsx files from our components
=> Change docsite glob to only pull index from react-components

apps/public-docsite/src/pages/Overviews/ResourcesPage/docs/default/ResourcesDesignResources.md
I haven't looked into all the history, but I'm guessing at one point we had a public figma plugin....
But as of today, the Figma plugin is internal only and 3rd party will hit a 404 here. I don't think the value of having the link is worth the confusion. 
fixes #23329
=> Chore: V8 Website: remove figma link from docs due to resource being private

packages/react-examples/src/react/OverflowSet/docs/OverflowSetOverview.md
In a discussion on an OverflowSet, I realized the Accessibility wording was a bit misleading. I updated the wording to both mention CommandBar's overflow feature, and also that keyboard interaction would be needed as well as semantics for e.g. a menu.
=> OverflowSet: minor docs wording update

apps/public-docsite-v9/package.json
Running start from the root runs the v9 docs in the non-docs mode, which is not what we publish to chromatic. This change will make it so you don't have to run storybook:dev from the v9 docs folder to get the correct options.
=> change v9docs start to use docs mode to replicate public view

packages/react-components/theme-designer/src/components/AccessibilityChecker/AccessibilityChecker.stories.tsx, packages/react-components/theme-designer/src/components/ColorTokens/ColorTokens.stories.tsx, packages/react-components/theme-designer/src/components/Content/Content.stories.tsx, packages/react-components/theme-designer/src/components/ExportButton/ExportLink.tsx, packages/react-components/theme-designer/src/components/Sidebar/EditTab.tsx, packages/react-components/theme-designer/src/utils/useDebounce.ts
In the header on the toolbar the Preview Light/Dark Theme in CodeSandbox now opens a new tab rather than navigating away from the app (as suggested by Geoff). ColorTokens.tsx has an updated storybook entry. Extracted out the string constants from within the render method of ExportLink.tsx (as suggested by Geoff). Added a debounce to all inputs in the edit tab of the sidebar (the color pickers & the sliders).
To-do list: https://github.com/microsoft/fluentui/projects/30?fullscreen=true
=> Theme designer: minor fixes

change/@fluentui-react-avatar-398ce0cf-a9ba-4202-bc72-488f974333c9.json, packages/react-components/react-avatar/MIGRATION-AvatarGroup.md, packages/react-components/react-avatar/README-AvatarGroup.md
This PR adds a readme and migration guide for AvatarGroup.
#22240
=> docs(react-avatar): Adding readme and migration guide for AvatarGroup

change/@fluentui-react-utilities-02a46ee6-1b76-40d0-8e0f-8233baf7d8f4.json, packages/react-components/react-utilities/src/ssr/SSRContext.tsx
This PR improves an error that can be thrown by `useIsSSR()` hook to include source and documentation link as was suggested in https://github.com/microsoft/fluentui/issues/23620#issuecomment-1162440666.
=> chore: improve error message in useIsSSR()

.github/CODEOWNERS
This PR adds @sopranopillow as code-owner for react-avatar since AvatarGroup lives in react-avatar.
#22240
=> chore: Adding AvatarGroup code-owner to react-avatar.

.vscode/settings.json, change/office-ui-fabric-react-0a2705c8-2996-4346-b525-85d4258becd8.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md, packages/office-ui-fabric-react/src/components/Persona/Persona.base.tsx, packages/office-ui-fabric-react/src/components/Persona/Persona.types.ts, packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/PeoplePickerItems/PeoplePickerItemSuggestion.tsx, packages/react-examples/src/office-ui-fabric-react/PeoplePicker/PeoplePicker.List.Example.tsx, packages/react-examples/src/office-ui-fabric-react/PeoplePicker/PeoplePicker.doc.tsx, packages/react-examples/src/office-ui-fabric-react/PeoplePicker/docs/PeoplePickerBestPractices.md, packages/react-examples/src/office-ui-fabric-react/Persona/docs/PersonaBestPractices.md
_This PR is a cherrypick of #18469 to the 7.0 branch._
**Original PR description follows:**
Currently, the tooltip/truncation behavior in Persona means we have tooltips within the dropdown of PeoplePicker. To fix that, I've made these changes:
- Add a `showOverflowTooltip` prop to Persona that defaults to `true` (the current behavior)
- Set `showOverflowTooltip` to false on the Persona used within PeoplePicker
- Update the List example of PeoplePicker to demo styles for wrapping text instead of truncating
- Add docs wording to Persona and PeoplePicker about the changes
Fixes #23480
=> fix: Adding optional way to show tooltip in Persona and removing tooltip within suggestions dropdown in PeoplePicker

change/@fluentui-react-e0874dcd-a01c-4f6a-bead-d1bc2c92f914.json, packages/react-examples/src/react/Slider/Slider.Basic.Example.tsx, packages/react/src/components/Slider/Slider.test.tsx, packages/react/src/components/Slider/useSlider.ts
Resolves #23757, [15029](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15029)
We have `ariaLabel` documented as a supported prop, but the current v8 Slider does not support it -- this PR adds support, updates our example to add a label for the first basic Slider, and maintains support for `aria-label`.
=> Slider v8: update to support ariaLabel

change/@fluentui-react-charting-1a3d2996-0eb7-41cc-9b45-6252de1ce10f.json, packages/react-charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap, packages/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap, packages/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap, packages/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap, packages/react-charting/src/components/Legends/Legends.base.tsx, packages/react-charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap, packages/react-charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap, packages/react-charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap, packages/react-charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap, packages/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChart.test.tsx.snap
The screen reader is not announcing state(Selected) when the focus is on legends.
It is announcing as 'Second 2 of 4'.
Screen reader is announcing state(Selected) when focus is on legends
=> fixed legends selected screen reader issue

azure-pipelines.release-vnext-nightly.yml, scripts/beachball/base.config.json, scripts/beachball/config.test.ts, tools/generators/version-bump/index.ts
Nightly releases were broken because `@fluentui/react` took a v9
dependency on `@fluentui/react-portal-compat-context`.
No changefiles were generated during the nightly release pipeline
because `prerelease` is a default disallowed bump type.
Additionally, since v9 no longer allows only `prerelease` change
types, the nightly pipeline has been updated to delete all existing
changefiles so that no `patch` or `minor` changefile actually tries to
release a `0.0.0` version.
=> chore: Fix nightly releases

.github/ISSUE_TEMPLATE/convergence_epic.md
The current convergence epic template has a lot of tasks who sound more like requirements (or suggestions) rather than actual tasks. This PR's purpose is to reduce the number of total tasks to a subset of more relevant ones and hopefully streamline the component development process.
Reduced the number of default task to a more concise subset. Some of the tasks that were removed from this template will be added to the [component convergence guide](https://github.com/microsoft/fluentui/wiki/Component-Convergence-Guide) as requirements.
=> refactor: reduce the size of the component convergence template

rfcs/convergence/changelog-guidelines.md
No proposal for applying breaking changes.
A new label was added to categorize breaking changes based on [Conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary), as decided during this week's tech sync.
```
BREAKING CHANGE: do new thing
```
Another possibility would be to use the exclamation mark in conjunction with the label as such:
```
feat!: do new thing
fix!: remove faulty prop
```
Originated in [#23449](https://github.com/microsoft/fluentui/pull/23449#discussion_r899348758)
=> chore: add breaking change label to changelog RFC

change/@fluentui-react-c38b13e5-4388-4234-9299-0930336bdcd1.json, packages/react/src/components/Checkbox/Checkbox.base.tsx, packages/react/src/components/Checkbox/Checkbox.test.tsx
Currently we use `aria-checked="mixed"` to represent an indeterminate checkbox, which is fine, but we can also use `indeterminate="true"` to improve browser compatibility.
This PR adds the indeterminate value to the native checkbox to reflect the isIndeterminate internal value
Fixes [#20717](https://github.com/microsoft/fluentui/issues/20717)
=> fix(Checkbox): add indeterminate value to inputRef

change/@fluentui-react-d83addbf-ad1d-483b-89b1-6de1d129de6b.json, packages/react-examples/src/react/Nav/Nav.FabricDemoApp.Example.tsx, packages/react-examples/src/react/Nav/Nav.FocusZone.Example.tsx, packages/react-examples/src/react/Nav/Nav.doc.tsx, packages/react/etc/react.api.md, packages/react/src/components/Nav/Nav.base.tsx, packages/react/src/components/Nav/Nav.types.ts
`Nav` used `FocusZone` but this `Nav` does not support related props to pass to `FocusZone`, like `defaultTabbableElement` of `FocusZone`, etc.
For example, if we want set `defaultTabbableElement` for Nav for a11y and support default landing link in `Nav`, there is no way to set it.
Added `focusZoneProps` prop for Nav and passed to `FocusZone`, so that we can support all extra props to pass to `FocusZone`.
In example of packages/react-examples/src/react/Nav/Nav.FocusZone.Example.tsx
Added `focusZoneProps` for `Nav` like below:
```ts
focusZoneProps={{
defaultTabbableElement: "a[title='MarqueeSelection']",
}}
```
When press tab, the default tabbable element will take effect, which proves the `focusZoneProps` take effect for `FocusZone` which used by `Nav`:
=> Add focusZoneProps support for Nav

.github/workflows/create-milestone.yml
Added a GH workflow that will run on the first day of the month, can also be triggered manually, and create the milestone automatically. 
This aims to avoid unnecessary errors with the `add-to-milestone` action.
Title format: "January Project Cycle Q1 2022"
Sample run: https://github.com/andrefcdias/actions-test/runs/7183696473?check_suite_focus=true
=> ci: add workflow to automatically create the monthly milestone

change/@fluentui-react-7dd046c0-8634-439c-a9bf-92c20a10be45.json, packages/react-examples/src/react/FocusTrapZone/FocusTrapZone.Box.Example.tsx, packages/react-examples/src/react/FocusTrapZone/FocusTrapZone.Nested.Example.tsx, packages/react/src/components/FocusTrapZone/FocusTrapZone.tsx
When an `iframe` is nested under a `<FocusTrapZone>`, and the `FocusTrapZone` is enabled, tabbing out of the `iframe` loops immediately back to the start of the trap zone, rather than continuing to the next element within the zone.
The issue is that when the user tabs out of an iframe, the focus briefly becomes `document.body` before it gets set to the correct element. With this change, `FocusTrapZone` checks whether the next-focused element is `document.body`, and then 'sleeps' for a moment before trying to recover focus. This ensures that the async focus update has a chance to continue out of the `iframe` and into the next element.
Fixes #20116
=> Fix FocusTrapZone tab looping out of an iframe

packages/react-components/react-theme/src/stories/Theme/ThemeColors.stories.tsx
Currently, the [Theme docs](https://react.fluentui.dev/?path=/docs/theme-theme--border-radii#colors) don't show mapping from tokens to color values for default web theme. Instead they show team light as the default light theme, which can be confusing to users expecting to see the default theme.
Add the default light theme to list of shown palettes:
=> docs(react-theme): add web light theme to colors stories

packages/react-components/react-avatar/src/stories/Avatar/AvatarActive.stories.tsx, packages/react-components/react-avatar/src/stories/Avatar/AvatarActiveAppearance.stories.tsx, packages/react-components/react-avatar/src/stories/Avatar/AvatarBadge.stories.tsx, packages/react-components/react-avatar/src/stories/Avatar/AvatarColorBrand.stories.tsx, packages/react-components/react-avatar/src/stories/Avatar/AvatarColorColorful.stories.tsx, packages/react-components/react-avatar/src/stories/Avatar/AvatarColorPalette.stories.tsx, packages/react-components/react-avatar/src/stories/Avatar/AvatarDefault.stories.tsx, packages/react-components/react-avatar/src/stories/Avatar/AvatarIcon.stories.tsx, packages/react-components/react-avatar/src/stories/Avatar/AvatarImage.stories.tsx, packages/react-components/react-avatar/src/stories/Avatar/AvatarInitials.stories.tsx, packages/react-components/react-avatar/src/stories/Avatar/AvatarName.stories.tsx, packages/react-components/react-avatar/src/stories/Avatar/AvatarSize.stories.tsx, packages/react-components/react-avatar/src/stories/Avatar/AvatarSquare.stories.tsx, packages/react-components/react-avatar/src/stories/Avatar/index.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupColor.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupDefault.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupIndicator.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupLayout.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupMaxAvatars.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupSizePie.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupSizeSpread.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupSizeStack.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/index.stories.tsx
This was missed in https://github.com/microsoft/fluentui/pull/23354. PR updates Avatar and AvatarGroup's storybook files to use absolute imports instead of relative imports. Also renames AvatarGroups index.stories file to `index.stories.tsx` instead of `index.stories.beta.tsx` to follow current convention and to prevent beachball from requiring a changefile whenever that storyfile is modified.
=> Avatar: Replace relative imports with absolute imports in storybook files

change/office-ui-fabric-react-d83addbf-ad1d-483b-89b1-6de1d129de6b.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md, packages/office-ui-fabric-react/src/components/Nav/Nav.base.tsx, packages/office-ui-fabric-react/src/components/Nav/Nav.types.ts, packages/react-examples/src/office-ui-fabric-react/Nav/Nav.FocusZone.Example.tsx, packages/react-examples/src/office-ui-fabric-react/Nav/Nav.doc.tsx
`Nav` used `FocusZone` but this `Nav` does not support related props to pass to `FocusZone`, like `defaultTabbableElement` of `FocusZone`, etc.
For example, if we want set `defaultTabbableElement` for Nav for a11y and support default landing link in `Nav`, there is no way to set it.
Added `focusZoneProps` prop for Nav and passed to `FocusZone`, so that we can support all extra props to pass to `FocusZone`.
In example of packages/react-examples/src/react/Nav/Nav.FocusZone.Example.tsx
Added `focusZoneProps` for `Nav` like below:
```ts
focusZoneProps={{
defaultTabbableElement: "a[title='MarqueeSelection']",
}}
```
When press tab, the default tabbable element will take effect, which proves the `focusZoneProps` take effect for `FocusZone` which used by `Nav`:
=> Cherry-pick logic to add focusZoneProps support for Nav #23806

change/@fluentui-eslint-plugin-ce5953c9-ee6d-4a78-98f6-74c8eb384e5e.json, packages/eslint-plugin/README.md, packages/eslint-plugin/src/index.js, packages/eslint-plugin/src/rules/no-restricted-imports/index.js, packages/eslint-plugin/src/rules/no-restricted-imports/index.test.js
- Redo of #23496 to generalize rule.
- Adds a new `no-restricted-imports` custom rule to our eslint-plugin package which will warn devs when they're importing from `forbidden` packages. If a corresponding `preferred` package import is provided, the import will be automatically fixable. 
- A follow-up PR will be made to add this rule to our v9 eslint config to prevent cross package v9 imports in storybook files.
https://user-images.githubusercontent.com/8649804/174653911-1d1db956-b93b-45cf-a3c7-b27614a94151.mp4
Fixes #21907
=> eslint-plugin: Add custom no-restricted-imports rule with fixer

packages/fluentui/CHANGELOG.md, packages/fluentui/docs/src/examples/components/Avatar/Variations/AvatarExampleSize.shorthand.tsx, packages/fluentui/react-northstar/src/components/Avatar/Avatar.tsx, packages/fluentui/react-northstar/src/components/Avatar/AvatarIcon.tsx, packages/fluentui/react-northstar/src/components/Avatar/AvatarImage.tsx, packages/fluentui/react-northstar/src/components/Avatar/AvatarLabel.tsx, packages/fluentui/react-northstar/src/components/Avatar/AvatarStatus.tsx, packages/fluentui/react-northstar/src/components/Avatar/AvatarStatusIcon.tsx, packages/fluentui/react-northstar/src/components/Avatar/AvatarStatusImage.tsx, packages/fluentui/react-northstar/src/themes/teams/components/Avatar/avatarSizes.ts
Add @fluentui/react-northstar avatar with 'medium-large' size, aligning with the v9 size 36 avatar
=> feat(Avatar): add 'medium-large' avatar (36px)

apps/ssr-tests-v9/src/utils/buildAssets.ts
PNG and JPEG extensions not supported on the loader.
```
ERR! ✘ [ERROR] No loader is configured for ".png" files: ../../packages/react-components/react-card/assets/office1.png
```
Added support for the common image types.
Unblocks #23841
=> chore(ssr-tests-v9): add `.png` and `.jpg` support on loader

packages/react-components/react-badge/src/stories/Badge/BadgeAppearance.stories.tsx, packages/react-components/react-badge/src/stories/Badge/BadgeColor.stories.tsx, packages/react-components/react-badge/src/stories/Badge/BadgeDefault.stories.tsx, packages/react-components/react-badge/src/stories/Badge/BadgeIcon.stories.tsx, packages/react-components/react-badge/src/stories/Badge/BadgeShapes.stories.tsx, packages/react-components/react-badge/src/stories/Badge/BadgeSizes.stories.tsx, packages/react-components/react-badge/src/stories/CounterBadge/CounterBadgeAppearance.stories.tsx, packages/react-components/react-badge/src/stories/CounterBadge/CounterBadgeColor.stories.tsx, packages/react-components/react-badge/src/stories/CounterBadge/CounterBadgeDefault.stories.tsx, packages/react-components/react-badge/src/stories/CounterBadge/CounterBadgeDot.stories.tsx, packages/react-components/react-badge/src/stories/CounterBadge/CounterBadgeShapes.stories.tsx, packages/react-components/react-badge/src/stories/CounterBadge/CounterBadgeSizes.stories.tsx, packages/react-components/react-badge/src/stories/PresenceBadge/PresenceBadgeDefault.stories.tsx, packages/react-components/react-badge/src/stories/PresenceBadge/PresenceBadgeOutOfOffice.stories.tsx, packages/react-components/react-badge/src/stories/PresenceBadge/PresenceBadgeSizes.stories.tsx, packages/react-components/react-badge/src/stories/PresenceBadge/PresenceBadgeStatus.stories.tsx
- updates `react-badge` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Badge: update stories to import from @fluentui/react-components

change/@fluentui-react-42e62350-c4bd-4d7e-bf80-eb79ef462001.json, packages/react/src/components/DetailsList/DetailsList.test.tsx, packages/react/src/components/List/List.test.tsx, packages/react/src/components/List/List.tsx, packages/react/src/components/List/utils/scroll.test.ts, packages/react/src/components/List/utils/scroll.ts
On mount, `List` [finds its scrollable parent](https://github.com/microsoft/fluentui/blob/master/packages/utilities/src/scroll.ts#L164) which can be an `HTMLElement` or `Window` object. `List` directly accesses `HTMLElement`'s scrolling API via properties like [`scrollTop`](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/List/List.tsx#L238) but these APIs are not directly available on `Window` (there are equivalents though).
When `List`'s scroll parent is a `Window` default values like `0` or `undefined` are returned and used in computations for scrolling.
Three new utilities have been added:
1. `getScrollHeight`: to read the scroll height of a List parent
2. `getScrollYPosition`: to read the Y scroll position of a List parent
3. `setScrollYPosition`: to …
=> list: add utilities for reading and writing scroll values

change/@fluentui-react-alert-a5405e35-1c76-4ad7-9a7d-5fb41961c52d.json, packages/react-components/react-alert/src/components/Alert/Alert.test.tsx, packages/react-components/react-alert/src/components/Alert/useAlert.tsx, packages/react-components/react-alert/src/stories/Alert/AlertAction.stories.tsx
I've added a role of `status` or `alert` based on the intent. I've also added `aria-live="assertive"` to all alerts, since my assumption is that any message important enough to use a component like Alert should probably be announced when it appears. This overrides the default live region priority of `status` while keeping `status` semantics.
=> fix(react-alert): add live region attributes based on intent

packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxChecked.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxCircular.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxDefault.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxDisabled.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxLabelBefore.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxLabelWrapping.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxLarge.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxMixed.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/CheckboxRequired.stories.tsx, packages/react-components/react-checkbox/src/stories/Checkbox/index.stories.tsx
- updates `react-checkbox` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Checkbox: update stories to import from @fluentui/react-components

packages/react-examples/src/react/DetailsList/docs/DetailsListBestPractices.md
`DetailsList` documentation does not provide any information about keyboard hotkeys. 
`DetailsList` documentation provides information about keyboard hotkeys.
The documentation describes how keyboarding works for `DetailsList` in general as well as differences in the behavior based on the current `SelectionMode` applied to `DetailsList`.
While this doesn't make `DetailsList` keyboard behavior more discoverable for end-users it should help developers integrating the control into their applications.
Related #23843
Fixes #23844
=> Docs: add keyboard info for DetailsList

change/@fluentui-react-avatar-a7db0772-2957-4fd1-a3c6-e995ae04cf46.json, packages/react-components/react-avatar/src/components/AvatarGroup/useAvatarGroupStyles.ts
Focus indicator for the pie layout was showing up as black, this turned out to be because the actual focus indicator wasn't showing up.
The focus indicator for the pie layout is now using border instead of outline and is now applied to the button.
=> fix(react-avatar): Fixing focus indicator in dark theme for pie layout

change/@fluentui-react-6b751b3a-85c1-4d87-9f8e-c8604193d9e5.json, packages/react/src/utilities/selection/SelectionZone.tsx
`SelectionZone` works by marking up descendant elements with attributes, such as `data-selection-index`, `data-selection-invoke`, and `data-selection-disabled`. However, when `SelectionZone` receives an event, it recursively checks the event target's ancestors to find whether *any* element has an appropriate attribute set to `true`, but does not have any way to 'countermand' those searches.
Added support for the `hasAttribute` check to forcibly return `false` if it encounters a closer element to a given target with the attribute explicitly set to `false` instead of `true`. This allows components which use `SelectionZone` to mark some elements up to disable certain behaviors.
One example scenario is using `data-selection-touch-invoke` on the root element of an item, but still inserting a …
=> Update SelectionZone to support disallowing behaviors

.github/CODEOWNERS
@microsoft/teams-prg does not own this package anymore, this PR updates `CODEOWNERS` to match the current state of things.
=> chore: update CODEOWNERS for react-badge

packages/react-components/react-menu/src/stories/Menu/MenuAligningWithIcons.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuAligningWithSelectableItems.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuAnchorToTarget.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuCheckboxItems.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuControlledCheckboxItems.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuControlledRadioItems.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuControllingOpenAndClose.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuCustomTrigger.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuDefault.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuGroupingItems.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuInteraction.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuMemoizedMenuItems.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuMenuItemsWithIcons.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuNestedSubmenus.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuNestedSubmenusControlled.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuRadioItems.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuRenderFunctionTrigger.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuSecondaryContentForMenuItems.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuSelectionGroup.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuSplitMenuItem.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuTriggerWithTooltip.stories.tsx, packages/react-components/react-menu/src/stories/Menu/MenuVisualDividerOnly.stories.tsx, packages/react-components/react-menu/src/stories/Menu/index.stories.tsx, packages/react-components/react-menu/src/stories/MenuList/MenuListDefault.stories.tsx, packages/react-components/react-menu/src/stories/MenuList/MenuListNestedSubmenus.stories.tsx, packages/react-components/react-menu/src/stories/MenuList/index.stories.tsx
- updates `react-menu` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Menu: update stories to import from @fluentui/react-components

apps/public-docsite-v9/src/Concepts/StylingComponents.stories.mdx
Add griffel devtools extension info to v9 'styling component' guide.
=> docs: update v9 styling guide to include griffel devtools extension link

rfcs/react-components/no-action-prop-value-standardization.md
This RFC aims to standardize what values we use in our components for cases where a prop value results in no action, i.e. defaults that apply no styles.
Currently, the approach we follow for all components is to use a string value like 'off', 'none' or 'default' for default values of a prop.
[PREVIEW 🔍](https://github.com/andrefcdias/fluentui/blob/rfc-standardize-no-action-prop-values/rfcs/react-components/no-action-prop-value-standardization.md)
#23254
=> rfc: "No action" / default property value standardization

change/@fluentui-react-components-b71ce9f6-1c6d-406f-b8ef-192483756f06.json, packages/react-components/react-components/etc/react-components.api.md, packages/react-components/react-components/src/index.ts
This PR re-exports `__css` function from Griffel. This functional is similar to `__styles` and used with CSS extraction when the Webpack loader from `@griffel/webpack-extraction-plugin` rewrites imports:
```tsx
import { makeStyles } from "@fluentui/react-components";
// ⬇️⬇️⬇️ (works now, done even in our repo)
import { __styles } from "@fluentui/react-components";
// ⬇️⬇️⬇️ (done by Webpack loader)
import { __css } from "@fluentui/react-components";
```
As `__css` is not re-exported customers will get errors:
```
TypeError: (0 , _fluentui_react_components__WEBPACK_IMPORTED_MODULE_0__.__css) is not a function
```
=> feat: re-export `__css` from Griffel

packages/react-components/react-popover/src/stories/Popover/PopoverAnchorToCustomTarget.stories.tsx, packages/react-components/react-popover/src/stories/Popover/PopoverControllingOpenAndClose.stories.tsx, packages/react-components/react-popover/src/stories/Popover/PopoverCustomTrigger.stories.tsx, packages/react-components/react-popover/src/stories/Popover/PopoverDefault.stories.tsx, packages/react-components/react-popover/src/stories/Popover/PopoverInternalUpdateContent.stories.tsx, packages/react-components/react-popover/src/stories/Popover/PopoverNestedPopovers.stories.tsx, packages/react-components/react-popover/src/stories/Popover/PopoverTrappingFocus.stories.tsx, packages/react-components/react-popover/src/stories/Popover/PopoverWithArrow.stories.tsx, packages/react-components/react-popover/src/stories/Popover/index.stories.tsx
- updates `react-popover` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Popover: update stories to import from @fluentui/react-components

packages/react-components/react-accordion/src/stories/Accordion/AccordionCollapsible.stories.tsx, packages/react-components/react-accordion/src/stories/Accordion/AccordionDefault.stories.tsx, packages/react-components/react-accordion/src/stories/Accordion/AccordionDisabled.stories.tsx, packages/react-components/react-accordion/src/stories/Accordion/AccordionExpandIcon.stories.tsx, packages/react-components/react-accordion/src/stories/Accordion/AccordionExpandIconPosition.stories.tsx, packages/react-components/react-accordion/src/stories/Accordion/AccordionHeaders.stories.tsx, packages/react-components/react-accordion/src/stories/Accordion/AccordionInline.stories.tsx, packages/react-components/react-accordion/src/stories/Accordion/AccordionMultiple.stories.tsx, packages/react-components/react-accordion/src/stories/Accordion/AccordionNavigation.stories.tsx, packages/react-components/react-accordion/src/stories/Accordion/AccordionOpenItems.stories.tsx, packages/react-components/react-accordion/src/stories/Accordion/AccordionSizes.stories.tsx, packages/react-components/react-accordion/src/stories/Accordion/AccordionWithIcon.stories.tsx, packages/react-components/react-accordion/src/stories/Accordion/index.stories.tsx
- updates `react-accordion` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Accordion: update stories to import from @fluentui/react-components

change/@fluentui-react-card-767362bb-acfe-4251-aa59-3dd01ce45c25.json, packages/react-components/react-card/etc/react-card.api.md, packages/react-components/react-card/src/components/CardPreview/CardPreview.types.ts
Slot has only `div` as permitted element.
Slot now allows `img` as an alternative element.
#19336
=> feat: extend CardPreview `logo` slot to allow `img` elements

apps/public-docsite/src/styles/_base.scss
The back to top button on the v8 website doesn't have focus styles due to us removing the MWF styles that spill into our own controls. This would add some back that match our site.
=> add focus styles to back to top button on v8 website

packages/react-components/react-provider/src/stories/Provider/FluentProviderDefault.stories.tsx, packages/react-components/react-provider/src/stories/Provider/FluentProviderDir.stories.tsx, packages/react-components/react-provider/src/stories/Provider/FluentProviderFrame.stories.tsx, packages/react-components/react-provider/src/stories/Provider/FluentProviderNested.stories.tsx, packages/react-components/react-provider/src/stories/Provider/index.stories.tsx
- updates `react-provider` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Provider: update stories to import from @fluentui/react-components

packages/react-components/react-textarea/src/stories/Textarea/TextareaAppearance.stories.tsx, packages/react-components/react-textarea/src/stories/Textarea/TextareaControlled.stories.tsx, packages/react-components/react-textarea/src/stories/Textarea/TextareaDefault.stories.tsx, packages/react-components/react-textarea/src/stories/Textarea/TextareaDisabled.stories.tsx, packages/react-components/react-textarea/src/stories/Textarea/TextareaPlaceholder.stories.tsx, packages/react-components/react-textarea/src/stories/Textarea/TextareaResize.stories.tsx, packages/react-components/react-textarea/src/stories/Textarea/TextareaSize.stories.tsx, packages/react-components/react-textarea/src/stories/Textarea/TextareaUncontrolled.stories.tsx, packages/react-components/react-textarea/src/stories/Textarea/index.stories.tsx
- updates `react-textarea` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Textarea: update stories to import from @fluentui/react-components

change/@fluentui-react-portal-compat-context-41a04c0c-0c92-40f7-af9a-d10c6af04725.json, packages/react-components/react-portal-compat-context/package.json, scripts/just.config.ts, scripts/monorepo/index.d.ts, scripts/monorepo/index.js, scripts/monorepo/isCompatibilityPackage.js
- Added isCompatibilityPackage function to just build scripts
- Set for 'fluent-compatibility' marker in package.json file for react-portal-comptability-context
- Updated to output amd for packages marked with fluent-compatibility
Fixes #23919
If there is a better way to let packages note they are v8/v9 compat packages please LMK.
=> Added mechanism for marking fluent-compatibility packages

packages/react-components/react-tabs/src/stories/TabList/TabListAppearance.stories.tsx, packages/react-components/react-tabs/src/stories/TabList/TabListDefault.stories.tsx, packages/react-components/react-tabs/src/stories/TabList/TabListDisabled.stories.tsx, packages/react-components/react-tabs/src/stories/TabList/TabListHorizontal.stories.tsx, packages/react-components/react-tabs/src/stories/TabList/TabListIconOnly.stories.tsx, packages/react-components/react-tabs/src/stories/TabList/TabListSizeMedium.stories.tsx, packages/react-components/react-tabs/src/stories/TabList/TabListSizeSmall.stories.tsx, packages/react-components/react-tabs/src/stories/TabList/TabListVertical.stories.tsx, packages/react-components/react-tabs/src/stories/TabList/TabListWithIcon.stories.tsx, packages/react-components/react-tabs/src/stories/TabList/TabListWithOverflow.stories.tsx, packages/react-components/react-tabs/src/stories/TabList/TabListWithPanels.stories.tsx, packages/react-components/react-tabs/src/stories/TabList/index.stories.tsx
- updates `react-tabs` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Tabs: update stories to import from @fluentui/react-components

packages/react-components/react-switch/src/stories/Switch/SwitchChecked.stories.tsx, packages/react-components/react-switch/src/stories/Switch/SwitchDefault.stories.tsx, packages/react-components/react-switch/src/stories/Switch/SwitchDisabled.stories.tsx, packages/react-components/react-switch/src/stories/Switch/SwitchLabel.stories.tsx, packages/react-components/react-switch/src/stories/Switch/SwitchLabelWrapping.stories.tsx, packages/react-components/react-switch/src/stories/Switch/SwitchRequired.stories.tsx, packages/react-components/react-switch/src/stories/Switch/index.stories.tsx
- updates `react-switch` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Switch: update stories to import from @fluentui/react-components

packages/react-components/react-spinner/src/stories/Spinner/SpinnerAppearance.stories.tsx, packages/react-components/react-spinner/src/stories/Spinner/SpinnerDefault.stories.tsx, packages/react-components/react-spinner/src/stories/Spinner/SpinnerLabel.stories.tsx, packages/react-components/react-spinner/src/stories/Spinner/SpinnerSize.stories.tsx, packages/react-components/react-spinner/src/stories/Spinner/index.stories.tsx
- updates `react-spinner` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Spinner: update stories to import from @fluentui/react-components

packages/react-components/react-tooltip/src/stories/Tooltip/TooltipControlled.stories.tsx, packages/react-components/react-tooltip/src/stories/Tooltip/TooltipCustomMount.stories.tsx, packages/react-components/react-tooltip/src/stories/Tooltip/TooltipDefault.stories.tsx, packages/react-components/react-tooltip/src/stories/Tooltip/TooltipInverted.stories.tsx, packages/react-components/react-tooltip/src/stories/Tooltip/TooltipPositioning.stories.tsx, packages/react-components/react-tooltip/src/stories/Tooltip/TooltipRelationshipDescription.stories.tsx, packages/react-components/react-tooltip/src/stories/Tooltip/TooltipRelationshipLabel.stories.tsx, packages/react-components/react-tooltip/src/stories/Tooltip/TooltipStyled.stories.tsx, packages/react-components/react-tooltip/src/stories/Tooltip/TooltipTarget.stories.tsx, packages/react-components/react-tooltip/src/stories/Tooltip/TooltipWithArrow.stories.tsx, packages/react-components/react-tooltip/src/stories/Tooltip/index.stories.tsx
- updates `react-tooltip` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Tooltip: update stories to import from @fluentui/react-components

change/@fluentui-react-e250f82e-f2bd-4229-899c-6ddf13a1e19a.json, packages/fluentui/react-northstar/package.json, packages/react/package.json
This PR fixes the dependency mismatches that happened after a recent bump in `@fluentui/react-portal-compat-context` using the `dependency-mismatch` nx generator.
=> chore: Fixing dependency mismatch due to @fluentui/react-portal-compat-context bump

packages/react-components/react-theme/src/stories/colors/ColorRamp.stories.tsx, packages/react-components/react-theme/src/stories/colors/ThemeColors.stories.tsx, packages/react-components/react-theme/src/stories/colors/ThemeShadows.stories.tsx, packages/react-components/react-theme/src/stories/motion-size/ThemeBorderRadii.stories.tsx, packages/react-components/react-theme/src/stories/motion-size/ThemeMotion.stories.tsx, packages/react-components/react-theme/src/stories/motion-size/ThemeSpacing.stories.tsx, packages/react-components/react-theme/src/stories/motion-size/ThemeStrokeWidths.stories.tsx, packages/react-components/react-theme/src/stories/typography/ThemeTypography.stories.tsx
- updates `react-theme` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Theme: update stories to import from @fluentui/react-components

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Adds [cypress dependencies](https://docs.cypress.io/guides/getting-started/installing-cypress#Ubuntu-Debian) to Dockerfile:
> libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
=> feats(devcontainer): adds cypress dependencies

change/@fluentui-react-7b59898b-33af-43ba-981d-96c48f4a471b.json, packages/react-examples/src/react/Nav/Nav.Basic.Example.tsx, packages/react-examples/src/react/Nav/Nav.FabricDemoApp.Example.tsx, packages/react-examples/src/react/Nav/Nav.Nested.Example.tsx, packages/react-examples/src/react/Nav/Nav.Wrapped.Example.tsx, packages/react/etc/react.api.md, packages/react/src/components/Nav/Nav.base.tsx, packages/react/src/components/Nav/Nav.types.ts
Fixes [14975](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/14975)
Using labels for state information is generally not recommended, especially since we also have `aria-expanded` communicating the expand/collapse state. Changing the label as well as the expanded state prop means that the button reads multiple times (once for the state change, and then again for the name change).
This PR deprecates `collapseAriaLabel`, and updates the label calculation to always use `expandAriaLabel` if `collapseAriaLabel` is not provided. If both or neither are provided, the behavior does not change.
Our docsite examples are also updated to only use `expandAriaLabel`
=> fix(Nav): remove separate labels for expand/collapse state

change/@fluentui-react-76f7c216-9e4b-4345-bc6a-ecc15201cdba.json, packages/react/src/components/CommandBar/CommandBar.base.tsx
`cacheKey` is used to resize `CommandBar` based on props like `items` changing. `farItems` is not included in the `cacheKey` computation so changes to `farItems` does not trigger a resize until/unless the window is resized or similar.
`CommandBar` takes `farItems` into account when computing `cacheKey` so that is properly resizes when `farItems` changes.
Fixes #23502
=> CommandBar: update cache key computation

packages/react-examples/src/react/Callout/docs/CalloutOverview.md, packages/react-examples/src/react/Dialog/docs/DialogOverview.md, packages/react-examples/src/react/Layer/docs/LayerOverview.md, packages/react-examples/src/react/Modal/docs/ModalOverview.md, packages/react-examples/src/react/Panel/docs/PanelOverview.md
Documentation for `Layer` (and components that use `Layer` under the hood) does not clearly explain how to enable event bubbling. This is an issue that has been [reported](https://github.com/microsoft/fluentui/issues/19299) a [few](https://github.com/microsoft/fluentui/issues/20009) [times](https://github.com/microsoft/fluentui/issues/20073) with respect to [React 17's changes to event delegation](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation).
`Layer` documentation is updated to clearly explain how to enable event bubbling. Components that use `Layer` under the hood link to `Layer`'s documentation.
I don't feel there is a code change to be made here as, so far, changing the event bubbling behavior has been enough to resolve this issue for consumers. …
=> Docs: Layer event bubbling with React 17

apps/public-docsite/src/components/Site/Site.tsx
At some point, #maincontent received a `role="main"`, so now the main landmark role added in our public docsite creates nested main landmarks on the site.
Removing the Site.tsx main landmark role so there is only one on the page.
=> Docsite: remove Fluent's main landmark role since higher-level main landmark was added

change/@fluentui-react-23010cf2-999a-4f0a-bcd9-b3f5e2e0ef72.json, packages/react/src/components/SpinButton/SpinButton.base.tsx, packages/react/src/components/SpinButton/SpinButton.test.tsx
In `SpinButton`, intermediate values are values that have been manually entered into the text field but not committed (i.e., `onChange` hasn't been called).
Currently, intermediate values are validated when they are stepped via the keyboard (up/down arrows) but not when stepped via the mouse (click on increment/decrement). When clicking to step an invalid intermediate value `SpinButton` gets into a bad state after it loses focus.
`SpinButton` validates intermediate values when clicking step buttons.
Fixes #23118
=> SpinButton: Improve validation handling on step (increment/decrement)

packages/react-components/react-text/src/stories/Text/Default.stories.tsx, packages/react-components/react-text/src/stories/Text/TextFont.stories.tsx, packages/react-components/react-text/src/stories/Text/TextItalic.stories.tsx, packages/react-components/react-text/src/stories/Text/TextSize.stories.tsx, packages/react-components/react-text/src/stories/Text/TextStrikeThrough.stories.tsx, packages/react-components/react-text/src/stories/Text/TextTruncate.stories.tsx, packages/react-components/react-text/src/stories/Text/TextTypography.stories.tsx, packages/react-components/react-text/src/stories/Text/TextUnderline.stories.tsx, packages/react-components/react-text/src/stories/Text/TextWeight.stories.tsx, packages/react-components/react-text/src/stories/Text/index.stories.tsx
- updates `react-text` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Text: update stories to import from @fluentui/react-components

packages/react-components/react-portal/src/stories/Portal/PortalDefault.stories.tsx, packages/react-components/react-portal/src/stories/Portal/PortalNested.stories.tsx
- updates `react-portal` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Portal: update stories to import from @fluentui/react-components

packages/react-components/react-aria/src/hooks/useARIAButton.stories.tsx
- updates `react-aria` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Aria: update stories to import from @fluentui/react-components

change/@fluentui-react-db0248f0-0d58-4c5a-9e12-24fd187cab31.json, packages/react/src/components/pickers/TagPicker/TagItem.tsx, packages/react/src/components/pickers/TagPicker/__snapshots__/TagItem.test.tsx.snap, packages/react/src/components/pickers/TagPicker/__snapshots__/TagPicker.test.tsx.snap
Fixes [14305](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/14305)
This uses sneaky `aria-labelledby` logic to get the TagPicker input to not use the "remove" text in its description calculation, while maintaining the button label of "Remove X".
Essentially by referencing the "remove" text via `aria-labelledby` instead of `aria-label`, it's not picked up in the input's `aria-describedby` calculation (taking advantage of the fact that id references aren't followed multiple levels deep).
=> fix: Tagpicker remove button labels

change/@fluentui-react-a8002da9-4136-42aa-bac3-8d4456b5f98a.json, packages/react/etc/react.api.md, packages/react/src/components/Nav/Nav.base.tsx, packages/react/src/components/Nav/Nav.types.ts
Fixes #24011
Adds a role prop to v8 Nav so teams can override the default `navigation` role to nest it within a parent navigation region.
=> Nav: add role prop

.github/CODEOWNERS
- codeowners placeholder is broken thus generating invalid codeowner when creating new packages
- codeowners placeholder is in proper format
https://github.com/microsoft/fluentui/pull/23995#pullrequestreview-1044185601
=> fix(codeowners): make codeowners work with automation again

packages/react-components/theme-designer/src/components/ColorTokens/ColorTokens.tsx, packages/react-components/theme-designer/src/components/Sidebar/Form.tsx, packages/react-components/theme-designer/src/components/Sidebar/Sidebar.tsx, packages/react-components/theme-designer/src/useThemeDesignerReducer.ts, packages/react-components/theme-designer/src/utils/toString.ts
Changing anything in the left sidebar that affects the 16 color brand ramp now resets the overrides.
=> theme designer: fixed the bug where custom theme overrides would not reset after brand ramp is changed

packages/react-components/react-combobox/src/stories/Combobox/ComboboxAppearance.stories.tsx, packages/react-components/react-combobox/src/stories/Combobox/ComboboxCustomOptions.stories.tsx, packages/react-components/react-combobox/src/stories/Combobox/ComboboxDefault.stories.tsx, packages/react-components/react-combobox/src/stories/Combobox/ComboboxGrouped.stories.tsx, packages/react-components/react-combobox/src/stories/Combobox/ComboboxMultiselect.stories.tsx, packages/react-components/react-combobox/src/stories/Combobox/ComboboxSize.stories.tsx, packages/react-components/react-combobox/src/stories/Dropdown/DropdownDefault.stories.tsx
- updates `react-combobox` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Combobox: update stories to import from @fluentui/react-components

change/@fluentui-api-docs-a3885ce3-efb6-4b85-9147-297abeee776f.json, change/@fluentui-babel-preset-global-context-7baa406d-f2d2-4966-96ef-ff94b3003b2c.json, change/@fluentui-codemods-ad8ea960-7cbd-43f2-ba00-eb2201c95709.json, change/@fluentui-jest-serializer-merge-styles-36cd8fb1-82bf-43d3-882f-fe3c26996762.json, change/@fluentui-react-conformance-3f09213e-f8d1-42f2-b4d5-720a8d07c98c.json, change/@fluentui-react-conformance-griffel-79125086-6139-41de-8d4a-a6c4a2f37fa0.json, change/@fluentui-test-utilities-c016afb9-9819-4900-9611-102670d4a5f3.json, change/@fluentui-webpack-utilities-334e5ffa-d49c-4b45-82d6-b48686b4574c.json, package.json, packages/a11y-testing/package.json, packages/api-docs/package.json, packages/codemods/bin/upgrade.js, packages/codemods/package.json, packages/jest-serializer-merge-styles/package.json, packages/react-components/babel-preset-global-context/package.json, packages/react-components/react-conformance-griffel/package.json, packages/react-conformance/package.json, packages/test-utilities/package.json, packages/webpack-utilities/just.config.ts, scripts/create-package/plop-templates-node/package.json.hbs, scripts/jest.config.js, scripts/just.config.ts, scripts/tasks/api-extractor.ts, scripts/tasks/argv.spec.ts, scripts/tasks/argv.ts, scripts/tasks/ts.ts, tools/generators/migrate-converged-pkg/index.spec.ts, tools/generators/migrate-converged-pkg/index.ts, workspace.json
- `just build` is black bock that cannot be configured on call site
- non-obvious presence of `min` generic flag and `commonJsOnly`
- `api-extractor` task run only if 2 conditions are met
just `build` task can be explicitly configured which js module type should be generated 
```sh
just-scripts build --module esm,cjs # transpiles js to ESM module and CommonJS 
just-scripts build --module esm --module cjs
```
- complete removal of `--min` and `commonJsOnly` task for broader unification and simplification
- 'api-extractor' is always executed and provides good DX to notify user if it was run at all and why
Legacy behaviours works as before with some adjustments needed that are part of this PR.
```sh
just-scripts build
```
- will generate `esm`  and `cjs` by default and `amd` (only if …
=> feat(scripts): implement explicit `--module` configuration flag for just build task

apps/public-docsite-v9/.storybook/main.js, apps/public-docsite-v9/package.json, change/@fluentui-react-components-a578581d-7c18-442c-a376-8f8547e30e6f.json, change/@fluentui-web-components-743638b6-0892-40f8-965e-56c8b2da0760.json, packages/react-components/react-components/.storybook/main.js, packages/react-components/react-components/package.json, packages/react-components/theme-designer/.storybook/main.js, packages/react-components/theme-designer/package.json, packages/web-components/.storybook/main.js, packages/web-components/package.json
we use [`storybook` deprecated CLI flags](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag) to run storybook instances
no deprecation error
=> chore(storybook): remove deprecated --static-dir CLI flag usage

change/@uifabric-date-time-35097027-415c-4e27-aa17-e0ab9da80cd3.json, change/office-ui-fabric-react-f0ac52c6-050f-4369-b9ef-0d4bbb005c43.json, packages/date-time/src/components/Calendar/CalendarYear/CalendarYear.base.tsx, packages/date-time/src/components/CalendarDayGrid/CalendarDayGrid.base.tsx, packages/date-time/src/components/CalendarDayGrid/CalendarGridDayCell.tsx, packages/date-time/src/components/WeeklyDayPicker/__snapshots__/WeeklyDayPicker.test.tsx.snap, packages/office-ui-fabric-react/src/components/Calendar/CalendarMonth.tsx, packages/office-ui-fabric-react/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap
Cherry pick to v7 of #20324, fixes Android Talkback bug.
=> v7 Calendar cherry-pick: remove explicit readonly semantics from grid and gridcells

change/@fluentui-react-b185f6f5-e21c-42b1-81d0-d1285b5e3bc6.json, packages/react/src/components/Tooltip/TooltipHost.base.tsx, packages/react/src/components/Tooltip/TooltipHost.test.tsx
Fixes [15083](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15083)
Previously, TooltipHost wasn't using `onRenderContent` for the accessible descriptive text when passed, so if a team used `onRenderContent` instead of `content`, the accessible description didn't match the visuals.
=> fix: TooltipHost uses onRenderContent prop for generating description text

change/@fluentui-react-conformance-griffel-3dd81437-a987-4472-b15c-f827662bd237.json, packages/react-components/react-conformance-griffel/src/overridesWin.ts
Updates react-griffel-conformance to use `renderOptions.container`
=> fix: Griffel conformance test should use user container for render

change/@fluentui-react-portal-compat-71d7bcf1-f43a-4506-a968-584814a7b0af.json, change/@fluentui-react-portal-compat-context-dfd86a39-651e-4b89-b9ef-71dcdf1a110f.json, packages/react-components/react-portal-compat-context/package.json, packages/react-components/react-portal-compat/package.json, scripts/just.config.ts
Disables the AMD lint-imports rule for v9
Fixes: #23107
=> chore: Disable lint-imports for v9

change/@fluentui-react-charting-0caef860-4f50-4dd7-931f-65eefe8d5139.json, packages/react-charting/src/components/LineChart/LineChart.base.tsx, packages/react-charting/src/components/LineChart/LineChart.types.ts, packages/react-examples/src/react-charting/LineChart/LineChart.Basic.Example.tsx, packages/react-examples/src/react-charting/LineChart/LineChart.CustomAccessibility.Example.tsx, packages/react-examples/src/react-charting/LineChart/LineChart.Events.Example.tsx, packages/react-examples/src/react-charting/LineChart/LineChart.Gaps.Example.tsx, packages/react-examples/src/react-charting/LineChart/LineChart.LargeData.Example.tsx, packages/react-examples/src/react-charting/LineChart/LineChart.Multiple.Example.tsx, packages/react-examples/src/react-charting/LineChart/LineChart.Styled.Example.tsx, packages/react-examples/src/react-charting/LineChart/LineChartPage.tsx
Currently, line charts are rendered by drawing 2 things.
1. Small line segments, each connecting adjacent points. For example for each of these pair of points {(x1, y1), (x2, y2)}, {(x2, y2), (x3, y3)}, {(xn-1, yn-1), (xn, yn)} there is a line segment connecting the two.
2. For each point there is a circle that represents the highlighted state. This circle gets activated whenever the mouse is hovered over this point.
This approach works fine if there are small number of data points in the line. As the number of points increase beyond 1000, the dom rendering starts becoming heavy. The performance and responsiveness of the chart starts suffering and the chart becomes very slow.
With this PR, I have enabled a path based rendering when there are larger number of datapoints.
For lines with …
=> Fix line chart rendering logic for bigger datasets having lines with more than 1000 datapoints

packages/react-components/theme-designer/src/components/Sidebar/Form.tsx, packages/react-components/theme-designer/src/components/Sidebar/Sidebar.tsx, packages/react-components/theme-designer/src/useThemeDesignerReducer.ts
Restricted the range of the hue torsion slider. Combined lightCp and darkCp sliders into vibrancy slider.
=> theme designer: change hue torsion range, change lightCp and darkCp to vibrancy

change/@fluentui-react-avatar-9e7bf365-19f5-49a7-a21a-32a26018f35d.json, packages/react-components/react-avatar/.storybook/main.js, packages/react-components/react-avatar/etc/react-avatar.api.md, packages/react-components/react-avatar/src/AvatarGroupOverflow.ts, packages/react-components/react-avatar/src/components/AvatarGroupOverflow/AvatarGroupOverflow.test.tsx, packages/react-components/react-avatar/src/components/AvatarGroupOverflow/AvatarGroupOverflow.tsx, packages/react-components/react-avatar/src/components/AvatarGroupOverflow/AvatarGroupOverflow.types.ts, packages/react-components/react-avatar/src/components/AvatarGroupOverflow/__snapshots__/AvatarGroupOverflow.test.tsx.snap, packages/react-components/react-avatar/src/components/AvatarGroupOverflow/index.ts, packages/react-components/react-avatar/src/components/AvatarGroupOverflow/renderAvatarGroupOverflow.tsx, packages/react-components/react-avatar/src/components/AvatarGroupOverflow/useAvatarGroupOverflow.ts, packages/react-components/react-avatar/src/components/AvatarGroupOverflow/useAvatarGroupOverflowStyles.ts, packages/react-components/react-avatar/src/index.ts, packages/react-components/react-avatar/src/stories/AvatarGroupOverflow/AvatarGroupOverflowBestPractices.md, packages/react-components/react-avatar/src/stories/AvatarGroupOverflow/AvatarGroupOverflowDefault.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroupOverflow/index.stories.tsx
This PR only adds what `create-component` generates. It's the boilerplate for AvatarGroupOverflow.
=> chore(react-avatar): Create AvatarGroupOverflow component boilerplate

.storybook/main.js
- buildless setup doesnt work for react-components
- buildless setup works for react-components
Fixes https://github.com/microsoft/fluentui/issues/23978
=> fix(storybook): make no-build needed for storybooks work

packages/react-components/react-select/src/stories/Select/SelectAppearance.stories.tsx, packages/react-components/react-select/src/stories/Select/SelectControlled.stories.tsx, packages/react-components/react-select/src/stories/Select/SelectDefault.stories.tsx, packages/react-components/react-select/src/stories/Select/SelectDisabled.stories.tsx, packages/react-components/react-select/src/stories/Select/SelectInitialValue.stories.tsx, packages/react-components/react-select/src/stories/Select/SelectSize.stories.tsx
- updates `react-select` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Select: update stories to import from @fluentui/react-components

change/@fluentui-react-provider-f7af8760-705e-4c2e-add0-9746ee74b04b.json, packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderThemeStyleTag.ts
fixes #23625
Two things happening here: 
1. To support React 18 we need to move to a symmetrical approach where we use useInsertionEffect to both insert the style and remove the style
2. Rather than splitting the logic for 16 vs 18, after a discussion with Shift, we are also changing the default logic to use useLayoutEffect rather than the in-render insertion. This mirrors how [emotionjs currently injects styles](https://github.com/emotion-js/emotion/blob/main/packages/react/src/global.js#L16)
=> Fluent Provider - convert to useLayoutEffect approach with useInsertionEffect when possible

change/@fluentui-react-input-23c1038e-1ff3-4630-a748-9d709d04a2ad.json, packages/react-components/react-input/src/components/Input/useInput.ts
Currently `Input` component doesn't provide an `initialValue` to `useControllableState` which ends up triggering a console error if no `defaultValue` and no `value` is provided.
Here's a reproduction: https://codesandbox.io/s/red-browser-5f4mwb?file=/index.tsx
provides empty string (`""`) as the `initialValue`, ensuring that if no `defaultValue` and no `value` is provided the actual state is controlled internally and no error will be shown in the console.
=> fix(react-input): adds proper `initialValue` to `useControllableState` on `useInput`

change/@fluentui-common-styles-caf28190-1ed1-4256-8aea-6f5a78f3558c.json, packages/common-styles/src/_effects.scss
The common-styles package (new to v8) broke out some SCSS from v7, but missed including roundedCorner4 and roundedCorner6 CSS variables. This causes breaks for folks upgrading from v7 to v8.
Added them into _effects.scss
=> Added missing roundedCorner CSS vars to common-styles

apps/vr-tests/src/stories/Modal.stories.tsx, change/@fluentui-react-0bc6cbfc-fbc5-4739-ace3-a84465da4342.json, packages/react/src/components/Modal/Modal.styles.ts, packages/react/src/components/Modal/__snapshots__/Modal.test.tsx.snap
fixes #22878
Due to moving all layers inside of a div, we can no longer rely on display: static on the layer to allow positioned content to reference the 100% width/height HTML element. 
The alternative is to keep the layouts exactly the same, but simply modify pointer event behavior on any blocking div (modal root and the layer). To do this we need to return normal click events to the main content area. 
I also added a VR test to ensure that our modeless modal does not break again due to some other change.
=> Modal: Change modeless approach to only effect pointer events, not layout

change/@fluentui-react-toolbar-a79099c9-e1bf-41a2-bfe0-d7feaadd9c48.json, packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarBestPractices.md, packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarDescription.md
The Toolbar component storybook doesn't have an unstable usage warning sign and the "Best Practices" section isn't styled up correctly.
Unstable usage warning has been added and "Best Practices" section has been styled.
Fixes #23958
=> fix(docs): fix styling on Toolbar best practices

packages/react-components/react-table/etc/react-table.api.md, packages/react-components/react-table/src/Table.ts, packages/react-components/react-table/src/TableBody.ts, packages/react-components/react-table/src/components/Table/Table.test.tsx, packages/react-components/react-table/src/components/Table/Table.tsx, packages/react-components/react-table/src/components/Table/Table.types.ts, packages/react-components/react-table/src/components/Table/__snapshots__/Table.test.tsx.snap, packages/react-components/react-table/src/components/Table/index.ts, packages/react-components/react-table/src/components/Table/renderTable.tsx, packages/react-components/react-table/src/components/Table/useTable.ts, packages/react-components/react-table/src/components/Table/useTableContextValues.test.ts, packages/react-components/react-table/src/components/Table/useTableContextValues.ts, packages/react-components/react-table/src/components/Table/useTableStyles.ts, packages/react-components/react-table/src/components/TableBody/TableBody.test.tsx, packages/react-components/react-table/src/components/TableBody/TableBody.tsx, packages/react-components/react-table/src/components/TableBody/TableBody.types.ts, packages/react-components/react-table/src/components/TableBody/__snapshots__/TableBody.test.tsx.snap, packages/react-components/react-table/src/components/TableBody/index.ts, packages/react-components/react-table/src/components/TableBody/renderTableBody.tsx, packages/react-components/react-table/src/components/TableBody/useTableBody.ts, packages/react-components/react-table/src/components/TableBody/useTableBodyStyles.ts, packages/react-components/react-table/src/index.ts, packages/react-components/react-table/src/stories/Table/Default.stories.tsx, packages/react-components/react-table/src/stories/Table/NonNativeElements.stories.tsx, packages/react-components/react-table/src/stories/Table/SizeSmall.stories.tsx, packages/react-components/react-table/src/stories/Table/SizeSmaller.stories.tsx, packages/react-components/react-table/src/stories/Table/index.stories.tsx
`TableBody` component is simply a DOM markup container.
`Table` component now creates the `TableContext` and sets the context
values from props.
Addresses #23983
=> feat: implement `Table` and `TableBody` components

packages/react-components/react-overflow/src/stories/Overflow/CustomPriorities.stories.tsx, packages/react-components/react-overflow/src/stories/Overflow/Dividers.stories.tsx, packages/react-components/react-overflow/src/stories/Overflow/DomOrder.stories.tsx, packages/react-components/react-overflow/src/stories/Overflow/MinimumVisible.stories.tsx, packages/react-components/react-overflow/src/stories/Overflow/PriorityWithDividers.stories.tsx, packages/react-components/react-overflow/src/stories/Overflow/ReverseDomOrder.stories.tsx
- updates `react-overflow` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Overflow: update stories to import from @fluentui/react-components

packages/react-components/react-storybook-addon/src/demos.stories.tsx
- updates `react-storybook-addon` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> SB Addon: update stories to import from @fluentui/react-components

packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupIndicator.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupLayout.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupMaxAvatars.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupSizePie.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupSizeSpread.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupSizeStack.stories.tsx
- updates `react-avatar` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> Avatar: update stories to import from @fluentui/react-components

change/@fluentui-react-083a26a4-f8c9-4b12-8885-9faa6227d393.json, packages/react-examples/src/react/Button/Button.Default.Example.tsx, packages/react/src/components/Fabric/Fabric.base.tsx
Follow up of #24025.
This PR applies the same type of changes made to `ThemeProvider` and `Layer` in #24025 to allow the `Fabric` component to be an element that automatically registers itself as a target to attach focus rectangles' classnames and event listeners of everything underneath it.
This PR also reverts changes made to the `Button.Default.Example.tsx` file while testing the changes in #24025.
=> feat: Making Fabric component an element to which to attach focus rects classnames and event listeners

change/@fluentui-react-hooks-99e51e0b-cdd4-49ad-af7e-7b1dbe90d868.json, packages/react-hooks/src/useAsync.ts
fixes #24041
a new Async was not being create on each useAsync call, so in React 18 strict mode Async was created, then dispose was called, then useEffect fired again, but the Async remained disposed.
=> task: useAsync, cleanup ref after hook return is called

change/@fluentui-react-card-9b222aa1-8f87-4bca-a101-bd24bcd9ba32.json, packages/react-components/react-card/src/stories/CardHeader/CardHeaderDescription.md, packages/react-components/react-card/src/stories/CardHeader/index.stories.tsx
The `CardHeader` storybook doc is missing the unstable usage warning.
Add unstable usage warning with import example.
Fixes #23952
=> fix(docs): add usage warning to CardHeader

change/@fluentui-react-64afe613-e952-4ee4-ac2a-2cab4854767d.json, packages/react/etc/react.api.md, packages/react/src/components/DetailsList/DetailsList.base.tsx, packages/react/src/components/DetailsList/DetailsRow.base.tsx, packages/react/src/components/DetailsList/DetailsRow.types.ts, packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap, packages/react/src/components/GroupedList/GroupHeader.base.tsx, packages/react/src/components/GroupedList/GroupedList.types.ts, packages/react/src/components/GroupedList/GroupedListSection.tsx
Addresses the first item in #24064
This adds a prop to DetailsRow to differentiate whether it is rendered within a DetailsList or GroupedList, so it can apply grid vs. treegrid semantics.
GroupHeader also now takes `ariaLevel` explicitly, so DetailsList can pass in an undefined value for Grouped DetailsList headers.
=> fix: DetailsList/GroupedList rows respect grid vs. tree semantic requirements

change/@fluentui-react-combobox-0037a98c-1e07-4e50-847f-79e97b510301.json, packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx, packages/react-components/react-combobox/src/components/Dropdown/Dropdown.test.tsx, packages/react-components/react-combobox/src/components/Listbox/useListbox.ts, packages/react-components/react-combobox/src/utils/ComboboxBase.types.ts, packages/react-components/react-combobox/src/utils/Selection.types.ts, packages/react-components/react-combobox/src/utils/useComboboxBaseState.ts, packages/react-components/react-combobox/src/utils/useSelection.ts, packages/react-components/react-combobox/src/utils/useTriggerListboxSlots.ts
Fixes a react-combobox bug where disabled options were getting selected with enter/space. Now enter/space works like click, where the dropdown remains open and the option is not selected.
=> fix: react-combobox -- keyboard should not select disabled options

packages/react-components/react-dialog/Spec.md, packages/react-components/react-dialog/etc/react-dialog.api.md, packages/react-components/react-dialog/src/components/Dialog/Dialog.types.ts, packages/react-components/react-dialog/src/components/Dialog/renderDialog.tsx, packages/react-components/react-dialog/src/components/Dialog/useDialog.test.ts, packages/react-components/react-dialog/src/components/Dialog/useDialog.ts, packages/react-components/react-dialog/src/components/Dialog/useDialogContextValues.ts, packages/react-components/react-dialog/src/components/DialogSurface/DialogSurface.test.tsx, packages/react-components/react-dialog/src/components/DialogSurface/DialogSurface.tsx, packages/react-components/react-dialog/src/components/DialogSurface/DialogSurface.types.ts, packages/react-components/react-dialog/src/components/DialogSurface/__snapshots__/DialogSurface.test.tsx.snap, packages/react-components/react-dialog/src/components/DialogSurface/renderDialogSurface.tsx, packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurface.ts, packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurfaceContextValues.ts, packages/react-components/react-dialog/src/components/DialogTitle/renderDialogTitle.tsx, packages/react-components/react-dialog/src/components/DialogTrigger/DialogTrigger.types.ts, packages/react-components/react-dialog/src/components/DialogTrigger/useDialogTrigger.ts, packages/react-components/react-dialog/src/contexts/dialogContext.ts, packages/react-components/react-dialog/src/contexts/dialogSurfaceContext.ts, packages/react-components/react-dialog/src/contexts/index.ts, packages/react-components/react-dialog/src/stories/DialogNested.stories.tsx, packages/react-components/react-dialog/src/utils/index.ts, packages/react-components/react-dialog/src/utils/normalizeSetStateAction.ts
1. Ensures `DialogTrigger` only has `aria-haspopup` if it's an `open` trigger.
2. Adds `role` and `aria-modal` attributes to `DialogSurface`
3. Removes `toggle` action from `DialogTrigger`
4. Wraps `DialogTitle` closeButton in a `DialogTrigger`
=> feat(react-dialog): Updates `DialogTrigger` to support `aria-haspopup` & updates dependencies

packages/react-components/react-components/src/AccessibilityScenarios/Accordion.stories.tsx, packages/react-components/react-components/src/AccessibilityScenarios/AccordionFaq.stories.tsx, packages/react-components/react-components/src/AccessibilityScenarios/Button.stories.tsx, packages/react-components/react-components/src/AccessibilityScenarios/Input.stories.tsx, packages/react-components/react-components/src/AccessibilityScenarios/Link.stories.tsx, packages/react-components/react-components/src/AccessibilityScenarios/Menu.stories.tsx, packages/react-components/react-components/src/AccessibilityScenarios/MenuSplitGroup.stories.tsx, packages/react-components/react-components/src/AccessibilityScenarios/Popover.stories.tsx, packages/react-components/react-components/src/AccessibilityScenarios/Slider.stories.tsx, packages/react-components/react-components/src/AccessibilityScenarios/SplitButton.stories.tsx, packages/react-components/react-components/src/AccessibilityScenarios/ToggleButton.stories.tsx, packages/react-components/react-components/src/AccessibilityScenarios/Tooltip.stories.tsx, packages/react-components/react-components/src/Concepts/Positioning/PositioningAnchorToTarget.stories.tsx, packages/react-components/react-components/src/Concepts/Positioning/PositioningCoverTarget.stories.tsx, packages/react-components/react-components/src/Concepts/Positioning/PositioningDefault.stories.tsx, packages/react-components/react-components/src/Concepts/Positioning/PositioningImperativeAnchorTarget.stories.tsx, packages/react-components/react-components/src/Concepts/Positioning/PositioningImperativePositionUpdate.stories.tsx, packages/react-components/react-components/src/Concepts/Positioning/PositioningOffsetFunction.stories.tsx, packages/react-components/react-components/src/Concepts/Positioning/PositioningOffsetValue.stories.tsx, packages/react-components/react-components/src/Concepts/Positioning/PositioningShorthandPositions.stories.tsx, packages/react-components/react-components/src/Concepts/Positioning/utils.stories.tsx, packages/react-components/react-components/src/Migrations/utils.stories.tsx
- updates `react-components` stories to import from `@fluentui/react-components` package suite to demonstrate best practices to users.
Part of #23846
=> react-components: update stories to import from @fluentui/react-components

change/@fluentui-react-components-848a0a6a-cdd6-4fd9-9e11-96a011548041.json, packages/react-components/react-components/etc/react-components.api.md, packages/react-components/react-components/src/index.ts
This PR re-exports `useIsomorphicLayoutEffect` from `@fluentui/react-utilities` in `@fluentui/react-components`. This allows it to be imported directly from `@fluentui/react-components` and fixes an issue with the `ThemeColors.stories.tsx` not loading because it cannot resolve that import.
=> chore: Re-exporting useIsomorphicLayoutEffect from @fluentui/react-utilities in @fluentui/react-components

change/office-ui-fabric-react-3cf6a1f4-b206-49b1-87d1-91879e08f9c0.json, change/office-ui-fabric-react-56d8b231-12d4-4bca-8131-9da8a848954b.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md, packages/office-ui-fabric-react/src/Decorators.ts, packages/office-ui-fabric-react/src/index.ts, packages/office-ui-fabric-react/src/utilities/decorators/index.ts, packages/office-ui-fabric-react/src/utilities/decorators/withViewport.tsx
v7 office-ui-fabric-react allows deep imports of withResponsiveMode and withViewport, but v7 @fluentui/react does not.
ODSP needs these exported in order to move to the modern import name.
-- exported withResponsiveMode and withViewport methods and types from @fluentui/react/Decorators
=> Added exports for decorators missing from v7

change/@fluentui-react-dialog-367c00aa-6cc7-4aef-a44a-ca4bd58bfcd7.json, packages/react-components/react-dialog/src/components/Dialog/useDialog.ts, packages/react-components/react-dialog/src/components/Dialog/useDialogContextValues.ts, packages/react-components/react-dialog/src/components/DialogBody/useDialogBody.ts, packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurface.ts, packages/react-components/react-dialog/src/components/DialogTitle/useDialogTitle.tsx, packages/react-components/react-dialog/src/contexts/dialogContext.ts, packages/react-components/react-dialog/src/stories/DialogAlert.stories.tsx, packages/react-components/react-dialog/src/stories/DialogBestPractices.md, packages/react-components/react-dialog/src/stories/DialogChangeFocus.stories.tsx, packages/react-components/react-dialog/src/stories/DialogControllingOpenAndClose.stories.tsx, packages/react-components/react-dialog/src/stories/DialogCustomTrigger.stories.tsx, packages/react-components/react-dialog/src/stories/DialogDefault.stories.tsx, packages/react-components/react-dialog/src/stories/DialogNested.stories.tsx, packages/react-components/react-dialog/src/stories/DialogNoFocusableElement.stories.tsx, packages/react-components/react-dialog/src/stories/DialogNonModal.stories.tsx, packages/react-components/react-dialog/src/stories/DialogTriggerOutsideDialog.stories.tsx
1. Adds `aria-labelledby` prop to `DialogSurface` with default `id` pointing to `DialogTitle`
2. Adds `aria-describedby` prop to `DialogSurface` with default `id` pointing to `DialogBody`
3. Adds best practices to disable `aria-describedby` in cases of complex `DialogBody`
=> feat(react-dialog): adds aria-labelledby and aria-describedby attributes

change/@fluentui-react-dialog-d2597139-d638-4882-98bd-d15e7035b8e6.json, packages/react-components/react-dialog/src/stories/DialogAlert.stories.tsx, packages/react-components/react-dialog/src/stories/DialogChangeFocus.stories.tsx, packages/react-components/react-dialog/src/stories/DialogControllingOpenAndClose.stories.tsx, packages/react-components/react-dialog/src/stories/DialogDefault.stories.tsx, packages/react-components/react-dialog/src/stories/DialogDescription.md, packages/react-components/react-dialog/src/stories/index.stories.tsx
Addresses: https://github.com/microsoft/fluentui/pull/24140#issuecomment-1199229666, as `Dialog` is still unstable and should be in `Preview Components` and no `Components` documentation.
=> fix(react-dialog): converts Dialog stories to Preview Components

apps/vr-tests-react-components/.eslintrc.json, change/@fluentui-eslint-plugin-75882078-3d30-465e-b1b8-c6ecbf8c7c71.json, packages/eslint-plugin/src/configs/react.js
- upgrades error level of `no-restricted-imports` to `error` in v9 config
- turns off `no-restricted-imports` rule for v9 vr-tests since this convention is not necessary in that package.
Part of #23846
=> chore(eslint-plugin): upgrade error level of no-restricted-imports in v9 config

change/@fluentui-react-f9e1d4e1-504b-47d8-8442-4f425d4f2ae7.json, packages/react/src/components/pickers/TagPicker/TagItem.styles.ts, packages/react/src/components/pickers/TagPicker/__snapshots__/TagItem.test.tsx.snap, packages/react/src/components/pickers/TagPicker/__snapshots__/TagPicker.test.tsx.snap
- Remove button on a `TagItem` has a focus outline with a contrast ratio of 1.425: 1 and does not meet minimum contrast ratio of 3:1.
- Remove button on a `TagItem` focus outline now meets minimum contrast ratio of 3:1. Changed the outline color to white, similar to `PrimaryButton`'s keyboard focus outline color. 
Fixes #24100
=> fix(TagPicker): focus outline for TagItem remove button now meets required contrast ratio

common/changes/office-ui-fabric-react/hotfix_12-hotfix-5.135.6_2022-07-27-05-29.json, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuButton.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/__snapshots__/ContextualMenuButton.test.tsx.snap
Port #5217 to make uncheckable contextual menu items lack the aria-checked attribute
=> Port #5217 to make uncheckable contextual menu items lack the aria-checked attribute

packages/react-components/react-table/src/components/TableHeaderCell/useTableHeaderCell.tsx
Fixes the PR race condition introduced by #24032
=> fix: TableHeaderCell should use `useAriaButtonShorthand`

change/@fluentui-react-focus-2af33127-ad63-49d2-8928-82bed1ce64d2.json, packages/react-focus/src/components/FocusZone/FocusZone.EventHandler.test.tsx, packages/react-focus/src/components/FocusZone/FocusZone.tsx
`FocusZone` currently attaches an event listener on keydown to the window, so that whenever the `tab` key is pressed all outer `FocusZone's` indexes are updated (an outer `FocusZone` is a `FocusZone` that is not within another one). This ensures tab indexes are always correct, but can cause a big performance dip since the keydown function is called even on elements that are not within `FocusZones`.
This PR fixes the issue described above by attaching the listeners to the `FocusZone` elements instead of the window. This means that there is the potential of more event listeners being on the page (one per outer `FocusZone` vs one for the window), but scopes the listeners to be called only when the event happens within one of these `FocusZones`. This has a performance benefit because indexes …
=> fix: Scope keydown event listener so that it is added to the FocusZone itself instead of the window

apps/public-docsite/src/pages/Overviews/StylesPage/StylesPage.module.scss
Depreciation notice during build of `@fluentui/public-docsite build`
```
verb @fluentui/public-docsite build |  : Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
verb @fluentui/public-docsite build |  
verb @fluentui/public-docsite build Recommendation: math.div(1, 2)
verb @fluentui/public-docsite build |  
verb @fluentui/public-docsite build More info and automated migrator: https://sass-lang.com/d/slash-div
verb @fluentui/public-docsite build |  
verb @fluentui/public-docsite build    ╷
verb @fluentui/public-docsite build |  58 │     width: calc(#{percentage(1/2)} - #{$App-padding-sm});
verb @fluentui/public-docsite build |     │                              ^^^
verb @fluentui/public-docsite build |     ╵
verb @fluentui/public-docsite build | …
```
=> replace slash with math.div as it is now deprecated and will be removed in Dart Sass 2

change/@fluentui-react-combobox-f4d9cbf9-a2e2-4f06-9968-9c6c897c1e6d.json, packages/react-components/react-combobox/src/stories/Dropdown/DropdownBestPractices.md, packages/react-components/react-combobox/src/stories/Dropdown/DropdownDescription.md
The Dropdown component storybook doesn't have an unstable usage warning sign and the "Best Practices" section isn't styled up correctly.
Unstable usage warning has been added and "Best Practices" section has been styled.
Fixes #23955
=> fix(docs): add Dropdown usage warning and style best practices

change/@fluentui-react-select-c465e31a-a10e-4945-82df-d4cef04dbf9a.json, packages/react-components/react-select/src/stories/Select/SelectBestPractices.md, packages/react-components/react-select/src/stories/Select/SelectDescription.md
The Select component storybook doesn't have an unstable usage warning sign and the "Best Practices" section isn't styled up correctly.
Unstable usage warning has been added and "Best Practices" section has been styled.
Fixes #23956
=> fix(docs): add Select usage warning and style best practices

change/@fluentui-react-aria-736d949d-2d8b-40f4-bbc4-31b8cb27f318.json, packages/react-components/react-aria/etc/react-aria.api.md, packages/react-components/react-aria/src/hooks/useARIAButton.test.tsx, packages/react-components/react-aria/src/hooks/useARIAButton.ts
Right now, `useARIAButtonProps` ignores `aria-disabled` value in favor of `disabled` or `disabledFocusable`
```ts
if (type === 'button' || type === undefined) {
return {
...rest,
'aria-disabled': disabledFocusable ? true : undefined, // 🚨
} ;
}
```
Instead of ignoring `aria-disabled`, it should be treated as if `disabledFocusable=true` has been passed, making the element focusable but still not emitting any click events.
```ts
if (type === 'button' || type === undefined) {
return {
...rest,
disabled: disabled && !disabledFocusable,
'aria-disabled': disabledFocusable ? true : ariaDisabled, // ✅
};
}
```
=> feat(react-aria): Starts treating `aria-disabled` as `disabledFocusable`

change/@fluentui-react-table-a321ce69-1698-45df-a2fd-96bf52ee9084.json, packages/react-components/react-table/etc/react-table.api.md, packages/react-components/react-table/src/components/Table/Table.test.tsx, packages/react-components/react-table/src/components/Table/Table.types.ts, packages/react-components/react-table/src/components/Table/useTable.ts, packages/react-components/react-table/src/components/Table/useTableContextValues.test.ts, packages/react-components/react-table/src/components/Table/useTableContextValues.ts, packages/react-components/react-table/src/components/TableHeaderCell/TableHeaderCell.test.tsx, packages/react-components/react-table/src/components/TableHeaderCell/TableHeaderCell.types.ts, packages/react-components/react-table/src/components/TableHeaderCell/useTableHeaderCell.tsx, packages/react-components/react-table/src/contexts/tableContext.ts, packages/react-components/react-table/src/index.ts, packages/react-components/react-table/src/stories/Table/Default.stories.tsx, packages/react-components/react-table/src/stories/Table/NonNativeElements.stories.tsx, packages/react-components/react-table/src/stories/Table/SizeSmall.stories.tsx, packages/react-components/react-table/src/stories/Table/SizeSmaller.stories.tsx, packages/react-components/react-table/src/stories/Table/Sort.stories.tsx
Removes `sortState` and associated props from `Table`. This will be
reserved for the future `DataGrid`-like component in order to keep
the `Table` as primitive as possible for the moment.
Addresses #23983
=> feat: Make sorting more primitive

.github/workflows/check-packages.yml, .github/workflows/screener-build.yml, .github/workflows/screener-run.yml
- we use custom yarn wrapper for installation
- we don't use caching
- all GH action workflows now use `yarn` directly with [caching enabled](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data)
Follows https://github.com/microsoft/fluentui/pull/24106/files#r932168118
=> ci: enable yarn install caching for all GH action workflows

.github/workflows/docsite-publish.yml
Current branch for `push` and `workflow_dispatch` events is `main` instead of `master`.
Replaced `main` branch with `master`.
=> fix(devops): change main branch name with master

scripts/create-component/plop-templates/src/components/{{componentName}}/use{{componentName}}Styles.ts.hbs
When using `create-component` the `use{{ComponentName}}Styles` template uses the old static classname instead of the new classnames object.
`create-component` now uses the new classnames object.
#23494
=> fix(create-component): Update use{{componentName}}Styles to use classnames object

scripts/create-component/create-component.ts
After creating a package with `create-package` and then using `create-component`, the recently created package won't show up. This is due to the create package removing the start script.
To avoid this when filtering the packages from `getAllPackageInfo()`, the check for the start script is removed.
=> fix(create-component): Remove start script check from create-component so a recently created package shows up in the list of packages.

change/@fluentui-react-af1de3e4-31d3-4136-8809-9f8abd9d90f6.json, packages/react/config/pre-copy.json
Looks like this bug has been here for a couple years now https://github.com/microsoft/fluentui/pull/15543
When we started pulling sass files from common-styles, we left `src/common` in the path, when it should just be `src`. This fix will make the common styles again ship with our react bundle, and not force people to install common-styles to get access to these sass files.
=> task: Fix Common style copy task in @fluentui/react

change/@fluentui-react-dialog-7e208240-ef01-4ecb-861e-2693b939b990.json, packages/react-components/react-dialog/Spec.md, packages/react-components/react-dialog/e2e/selectors.ts, packages/react-components/react-dialog/etc/react-dialog.api.md, packages/react-components/react-dialog/src/components/Dialog/Dialog.types.ts, packages/react-components/react-dialog/src/components/Dialog/renderDialog.tsx, packages/react-components/react-dialog/src/components/Dialog/useDialog.ts, packages/react-components/react-dialog/src/components/Dialog/useDialogStyles.ts, packages/react-components/react-dialog/src/stories/Dialog/DialogAlert.md, packages/react-components/react-dialog/src/stories/Dialog/DialogAlert.stories.tsx, packages/react-components/react-dialog/src/stories/Dialog/DialogBestPractices.md, packages/react-components/react-dialog/src/stories/Dialog/DialogNoFocusableElement.stories.tsx, packages/react-components/react-dialog/src/stories/Dialog/DialogNonModal.md
The background dimmed effect presented on a `modal` or `alert` `Dialog` is called `overlay` per design spec
Renames `overlay` in favor of [backdrop](https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop), which is the name used by native [dialog](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement) element
=> chore(react-dialog): renames `overlay` slot to `backdrop`

.github/workflows/docsite-publish.yml
The current `check` job in the docsite-publish workflow doesn't return `true` when doing a manual trigger, except the times when `react-components/package.json` is also changed.
This PR adds an "or" condition to the `check` job as well to make sure that manual releases go through every time.
=> fix(devops): docsite publish workflow check job output fix

change/@fluentui-react-file-type-icons-c69416e0-f17b-4199-b094-11b74b50462e.json, packages/react-file-type-icons/src/FileTypeIconMap.ts, packages/react-file-type-icons/src/initializeFileTypeIcons.tsx
- New icontype 'loop' to align to the brand (keeping 'fluid' around since it's still referenced). 
- Renaming the KFM folders (currently un-referenced) so their names are correct. 
- Cleanup of video, stream, audio icons to align to one brand. 
- Replacing the icon-generation pipeline from Adobe Illustrator to Figma. 
- Adding 20x1.5 and 64 sized icons that were previously missing (thanks to new Figma workflow!)",
- yarn change was run with these update notes added to package comments
- changes tested with experiments/storyboard/filetypeicons
- package consumers using the methods described in [readme.md](https://github.com/microsoft/fluentui/tree/master/packages/react-file-type-icons#readme) will pick up new/correct icons with no issues
- Also deployed to v7 : #24188
=> Update to UIFabric (master branch) to pick up latest filetype icon system.

change/@uifabric-file-type-icons-7846cc28-5e45-4d9c-ac7b-1eda9989ae23.json, packages/file-type-icons/src/FileTypeIconMap.ts, packages/file-type-icons/src/initializeFileTypeIcons.tsx
- New icontype 'loop' to align to the brand (keeping 'fluid' around since it's still referenced). 
- Renaming the KFM folders (currently un-referenced) so their names are correct. 
- Cleanup of video, stream, audio icons to align to one brand. 
- Replacing the icon-generation pipeline from Adobe Illustrator to Figma. 
- Adding 20x1.5 and 64 sized icons that were previously missing (thanks to new Figma workflow!)",
- yarn change was run with these update notes added to package comments
- changes tested with experiments/storyboard/filetypeicons
- package consumers using the methods described in [readme.md](https://github.com/microsoft/fluentui/tree/7.0/packages/file-type-icons#readme) will pick up new/correct icons with no issues
- Cherry pick of #24190
=> Update to UIFabric (v7 Branch) to pick up latest filetype icon system.

change/@fluentui-eslint-plugin-cbd8051e-efd7-419b-a143-1dc1316eecda.json, migrations.json, nx.json, package.json, packages/eslint-plugin/package.json, packages/eslint-plugin/src/rules/no-restricted-imports/index.test.js, packages/eslint-plugin/src/utils/configHelpers.js, scripts/create-package/plopfile.ts, tools/generators/migrate-v8-pkg/index.ts, yarn.lock
**relelease:** https://blog.nrwl.io/what-is-new-in-nx-13-10-a58d2051d73
**highlights:**
- ability to run custom plugin without build needed (will allow us to migrate `tools/`  to proper internal plugin )
- initial move to simplified dep tree with `nx` package
=> chore: migrate to nx 13.10

change/@fluentui-react-charting-bbc541d0-79af-4a9b-81e3-3c81dd0e8b88.json, packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx, packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.types.ts, packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx, packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.types.ts, packages/react-examples/src/react-charting/VerticalBarChart/VerticalBarChart.Basic.Example.tsx, packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.Basic.Example.tsx, packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.Callout.Example.tsx, packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.CustomAccessibility.Example.tsx
=> Bug 5118 For a hybrid graph, include 2px outline for the line graph

change/@fluentui-react-8eaa0012-dc28-494f-a9c8-41bbb8f24c1a.json, packages/react/etc/react.api.md, packages/react/src/components/Pivot/Pivot.base.tsx, packages/react/src/components/Pivot/Pivot.types.ts
Not applicable, this is a new functionality.
* `oveflowButtonAs` prop is added to `Pivot` component
* When `overflow` is set to `menu` and `overflowButtonAs` is provided, the component will be used for rendering overflow button instead of default `CommandButton`
Usage example: setting custom label and icon for the overflow button
Implements #24001
=> feat(Pivot): add overflowButtonAs prop

packages/react-examples/src/react/CommandBar/CommandBar.ButtonAs.Example.tsx, packages/react-examples/src/react/CommandBar/CommandBar.CommandBarButtonAs.Example.tsx, packages/react-examples/src/react/CommandBar/CommandBar.SplitDisabled.Example.tsx, packages/react-examples/src/react/ContextualMenu/ContextualMenu.Checkmarks.Example.tsx, packages/react-examples/src/react/ContextualMenu/ContextualMenu.Customization.Example.tsx, packages/react-examples/src/react/ContextualMenu/ContextualMenu.CustomizationWithNoWrap.Example.tsx, packages/react-examples/src/react/ContextualMenu/ContextualMenu.Header.Example.tsx, packages/react-examples/src/react/ContextualMenu/ContextualMenu.ScreenReader.Example.tsx, packages/react-examples/src/react/ContextualMenu/ContextualMenu.Submenu.Example.tsx
No issue, but a partner request --
We currently have docsite examples of CommandBar and ContextualMenu that include interaction-specific `aria-label` values that specify arrow key and mouse usage. Those aren't recommended, since they are not always accurate to different types of screen reader usage, so this PR removes them.
Apparently having them in our docs examples was causing the strings to get re-added in downstream products, even after they were removed 😅.
=> fix: remove misleading instructions from aria-label in examples

change/@fluentui-react-9389c81c-3bf8-4fd7-a465-31fd4a677c80.json, packages/react/src/components/Breadcrumb/Breadcrumb.styles.ts, packages/react/src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
- Focus outline on the overflowButton is not visible in high contrast mode.
- Changed `inset` to `1px` to make outline visible and to match `inset` of `Breadcrumb` items. Focus outline is now visible in high contrast mode. 
Fixes #23745
=> fix(Breadcrumb): overflowbutton focus outline now visible in HCM

change/@fluentui-react-b6625e07-abc9-46fd-a63c-bc28f8aab0ef.json, packages/react/etc/react.api.md, packages/react/src/components/Callout/Callout.test.tsx, packages/react/src/components/Callout/Callout.types.ts, packages/react/src/components/Callout/CalloutContent.base.tsx
Fixes [14807](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/14807)
Adding a `popupProps` prop to Callout allows authors to pass through props directly to the underlying `Popup` element, which allows for e.g. making a modal Callout (the original request).
Panel also uses `popupProps` and Callout already has `layerProps`, so this should be consistent with existing patterns.
=> feat: add popupProps to Callout

change/@fluentui-react-999e7752-4c0d-4b7b-97c5-c0938466f097.json, packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx
The behavior of focus rects was modified by #24025 and #24150. Those moved the focus listeners from the `window` to the `Fabric` and `Portal` root elements. This now requires focus listeners to be registered on each root element, instead of just once on the window.
Focus rects require at least one element to register the listeners by either calling `useFocusRects` or rendering a `<FocusRects />`. This is currently handled by BaseButton and a handful of other components that use focus rects. However, nothing inside of a ContextualMenu does this registering. It had previously been relying on the button that opened the menu to do the registration, but that no longer works because the menu items are inside a Layer.
Add a `<FocusRects />` node to ContextualMenuBase, to register for focus rects …
=> fix: Make focus rects visible inside of ContextualMenu

change/@fluentui-react-icons-mdl2-branded-25b2fc8e-4556-4dbd-a789-183e427bcbf1.json, packages/react-icons-mdl2-branded/package.json
The `react-icons-mdl2-branded` package has a dependency requirement for max react 17. This is preventing max bar to ts 18
Updates the max to react 18
Fixes #22895
=> Bump react icons mdl2 branded

azure-pipelines.perf-test.yml, azure-pipelines.yml, scripts/monorepo/checkIfPackagesAffected.js
Storybooks builds are not scoped so they are built even when a screener test should be skipped.
``check:affected-package`` cannot tell the difference between PR and master builds, so pushes to the master branch are always skipped as the comparing is done with origin/maste. ``check:affected-package`` will always return ``false`` in master.
Improved ``check:affected-package`` command by using an argument parser and adding an argument for PR builds.
This command is used for scoping storybooks builds.
Example:
```shell
yarn --silent check:affected-package --packages @fluentui/react --pr
```
Checks if  fluentui/react PR build packages are affected. (checks by comparing against origin/master)
```shell
yarn --silent check:affected-package --packages @fluentui/react 
```
Checks if fluentui/react …
=> Scope storybooks builds

azure-pipelines.yml
Screener start steps were conditioned by the ``skipScreener`` variable even though they should always run in order to be able to cancel unnecessary checks.
Screener start steps are no longer conditioned and always run.
Fixes #
=> Enable CI to call screener proxy

apps/ssr-tests-v9/package.json, azure-pipelines.release-vnext.yml, change/@fluentui-web-components-dc75c576-2286-4559-9849-24a5147e98ee.json, package.json, packages/web-components/package.json, scripts/package.json, scripts/ts-node-register.js, yarn.lock
- various ts-node versions are used
- ts-node doesn't adhere to single version policy standard
- ts-node perf is not the best one
- one ts-node is used adhering to single version policy
- ts-node is extremely performant as it uses `swc` under the hood (70x times faster)
=> chore: use only one ts-node and improve perfomance by using `swc` for compilation

apps/vr-tests-react-components/src/stories/Popover.stories.tsx, change/@fluentui-react-popover-20004f36-0fef-42c5-b56e-3d0f618b2371.json, packages/react-components/react-popover/e2e/Popover.e2e.tsx, packages/react-components/react-popover/src/components/Popover/usePopover.ts
When PopoverSurface is made focusable and `trapFocus` is set to true, PopoverSurface is not focused after triggering the Popover. This leads to problems where the items in a list are not focusable and the list is the only focusable item (the PopoverSurface should be the container of these items with `role=list`), and therefore nothing is focused.
Popover now checks if the PopoverSurface is focusable first and traps focus if it is. Otherwise, it has the same behavior of finding the first focusable element inside PopoverSurface.
=> fix(react-popover): Allow PopoverSurface to trap focus when it's focusable

change/@fluentui-react-textarea-c2525ad6-b2de-4fae-a3d9-f5b2fe05fab1.json, packages/react-components/react-textarea/src/components/Textarea/useTextareaStyles.ts
Quick fix for react-textarea -- since the border color style is on the root rather than the `<textarea>` element, it needs an explicit high contrast style for the disabled state.
=> fix: react-textarea uses semantic high contrast border color when disabled

change/@fluentui-react-combobox-ad1b9fd3-1e90-4f60-969e-85774341c610.json, packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx, packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx, packages/react-components/react-combobox/src/utils/ComboboxBase.types.ts, packages/react-components/react-combobox/src/utils/useComboboxBaseState.ts, packages/react-components/react-combobox/src/utils/useTriggerListboxSlots.ts
Updates Combobox to open/close on chevron click. To do so, I moved `ignoreTriggerBlur` to state, so it can be used outside the `useTriggerListboxSlots` hook.
=> react-combobox: open/close combobox on chevron icon click

apps/public-docsite-resources/src/AppDefinition.tsx, apps/public-docsite-resources/src/components/pages/PopupPage.tsx, apps/public-docsite/src/SiteDefinition/SiteDefinition.pages/Controls/web.tsx, apps/public-docsite/src/pages/Controls/PopupPage/PopupPage.doc.ts, apps/public-docsite/src/pages/Controls/PopupPage/PopupPage.tsx, packages/react-examples/src/react/Popup/Popup.Basic.Example.tsx, packages/react-examples/src/react/Popup/Popup.Modal.Example.tsx, packages/react-examples/src/react/Popup/Popup.doc.tsx, packages/react-examples/src/react/Popup/docs/PopupOverview.md
We don't publicly document Popup anywhere, and we currently have broken references to `IPopupProps` that are fixed by this PR.
It adds Popup under "Utilities" in the site nav, along with two examples:
=> feat: add Popup to public-docsite under Utilities

change/@fluentui-react-combobox-d1f4333e-0e57-4809-ad40-86df3bf5e61c.json, packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx
`master` is broken as `useCombobox` uses `useMergedEventCallbacks` hook that was removed in #24152:
`master` is green, CI is passing.
=> bugfix(Combobox): update useMergedEventCallbacks to mergeCallbacks

packages/fluentui/CHANGELOG.md, packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx, packages/fluentui/react-northstar/test/specs/components/Dropdown/Dropdown-test.tsx
See for context #24273. The problem is the result of `normalizeValue()` is incorrect for an empty string:
```js
normalizeValue('') // => ['']
```
That's why `showIndicator` check always fails.
This PR fixes `normalizeValue()` to handle empty strings as an empty value.
```js
normalizeValue('') // => []
```
Fixes #24273.
=> fix(Dropdown): handle empty string as an empty value

change/@fluentui-react-theme-sass-85b0f325-84a3-4866-ac55-5ed7015886e7.json, packages/react-components/react-theme-sass/package.json
`react-theme-sass` does not depend on `react-theme`
That is correct code-wise, the problem is with `lage` which does not consider `react-theme-sass` being affected by changes in `react-theme`. This happened in #24027.
`react-theme-sass` has dev dependency on `react-theme`
Whenever `react-theme` changes, CI runs build and tests for `react-theme-sass`.
Part of #24161
=> react-theme-sass dev-depends on react-theme

change/@fluentui-react-avatar-0a844534-f651-4b66-92c0-f9b1352ec334.json, packages/react-components/react-avatar/etc/react-avatar.api.md, packages/react-components/react-avatar/src/components/AvatarGroupItem/AvatarGroupItem.test.tsx, packages/react-components/react-avatar/src/components/AvatarGroupItem/AvatarGroupItem.types.ts, packages/react-components/react-avatar/src/components/AvatarGroupItem/useAvatarGroupItem.ts, packages/react-components/react-avatar/src/components/AvatarGroupPopover/AvatarGroupPopover.types.ts, packages/react-components/react-avatar/src/components/AvatarGroupPopover/useAvatarGroupPopover.tsx, packages/react-components/react-avatar/src/components/AvatarGroupPopover/useAvatarGroupPopoverStyles.ts
Content is rendered as a `<div>` and a role `list` is given to it. AvatarGroupItem is rendered as a `<div>` and a role `listitem` is given to it when rendered inside content.
Content is rendered as `<ul>` and AvatarGroupItem as a `<li>` when rendered inside content.
Fixes #24239
=> chore(react-avatar): Change content to render as ul and list item to render as li

change/@fluentui-react-charting-3bf299d2-26e7-45ca-bcb1-18aeabdb8b79.json, packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx, packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx, packages/react-charting/src/components/StackedBarChart/StackedBarChart.base.tsx
Accessibility tool showing error for chart title "ARIA roles used must conform to valid values"
The role should not be culture, it should be text or nothing just like other charts.
=> Culture issue in multistacked bar chart solve

apps/public-docsite-v9/src/Concepts/SSR/SSR.stories.mdx, change/@fluentui-react-components-52cc9453-6977-4504-9d2a-88769141c352.json, packages/react-components/react-components/etc/react-components.api.md, packages/react-components/react-components/src/index.ts
- Documentation page for SSR uses TypeScript
- `GriffelRenderer` type is re-exported as it's need for setup
Fixes #24164, #24158.
=> docs: update SSR page to use TypeScript snippets

apps/public-docsite-resources/src/AppDefinition.tsx, apps/public-docsite-resources/src/components/pages/DetailsList/DetailsListProportionalColumnsPage.tsx, apps/public-docsite/src/SiteDefinition/SiteDefinition.pages/Controls/web.tsx, apps/public-docsite/src/pages/Controls/DetailsListPage/DetailsListProportionalColumnsPage.doc.ts, apps/public-docsite/src/pages/Controls/DetailsListPage/DetailsListProportionalColumnsPage.tsx, packages/react-examples/src/react/DetailsList/DetailsList.doc.tsx
We have `DetailsList.ProportionalColumns.Example.tsx`, but it's not visible in docs.
We have `DetailsList.ProportionalColumns.Example.tsx` and it's **visible** in docs.
Related to #23786.
=> docs: add proportional example for DetailsList to docs

change/@fluentui-react-accordion-786c1a81-7dfb-41b9-8bea-5ada800bd5f0.json, change/@fluentui-react-link-748580a8-f10f-41b6-bf28-b2b3653c74d4.json, change/@fluentui-react-tabs-047ce97a-764d-44ff-a59b-ed7caf3e3b99.json, packages/react-components/react-accordion/src/components/AccordionHeader/__snapshots__/AccordionHeader.test.tsx.snap, packages/react-components/react-accordion/src/components/AccordionHeader/useAccordionHeader.tsx, packages/react-components/react-link/src/components/Link/useLink.ts, packages/react-components/react-tabs/src/components/Tab/__snapshots__/Tab.test.tsx.snap, packages/react-components/react-tabs/src/components/Tab/useTab.ts, packages/react-components/react-tabs/src/components/TabList/__snapshots__/TabList.test.tsx.snap
Related to #23334, I noticed that the accordion buttons were submitting a form when nested within one.
This PR adds `type="button"` by default to all button slots in `react-components` that don't already have `type` defined.
=> fix: add type=button to button slots in react-link, react-accordion, and react-tabs

change/@fluentui-react-8048a73c-6b18-40b3-93bb-2fa00248795b.json, change/@fluentui-utilities-33bf3200-95e0-49e3-9e3d-9f77e469da42.json, packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap, packages/react/src/components/GroupedList/GroupHeader.base.tsx, packages/react/src/utilities/selection/SelectionZone.tsx, packages/utilities/etc/utilities.api.md, packages/utilities/src/selection/Selection.ts, packages/utilities/src/selection/Selection.types.ts
The `SelectionZone` component currently only handles the concept of single-item selection when the user clicks on items or uses the Space key. Grouped Lists support whole-group selection, but this behavior is handled special by the Group Header using custom click-handling logic. On the plus side, this kept the SelectionZone logic modular, but on the negative side the selection behavior of Groups has never been consistent.
Notably:
1. Focusing the whole group header element and hitting Space does nothing.
2. Clicking in the white-space of a group header tries to 'invoke' the group and provides no affordance to select it.
Updated `SelectionZone` so that it checks for a new `data-selection-span` attribute applied to the same elements as `data-selection-index`, and updated Group Headers to …
=> Standardize selection behavior of Groups in SelectionZone

change/@fluentui-react-avatar-79855439-3adf-4e84-a434-f95911b3655b.json, packages/react-components/react-avatar/src/components/AvatarGroupItem/useAvatarGroupItem.ts
Screen readers read both the Avatar's aria-label and the label in the AvatarGroupItem. 
To avoid this, the label will be hidden and only the Avatar's label will be read.
#23773
=> fix(react-avatar): Set aria-hidden to AvatarGroupItem's label

change/@fluentui-react-components-847b38fb-34c3-40b2-b8d4-4c53b3027acc.json, packages/react-components/react-components/etc/react-components.unstable.api.md, packages/react-components/react-components/src/unstable/index.ts
`ToolbarButton` is not re-exported, but used in examples (stories).
`ToolbarButton` is re-exported.
Fixes #24015.
=> fix: export ToolbarButton

change/@fluentui-react-table-78287e07-9d21-47ab-9ae1-efca3ecc54d5.json, packages/react-components/react-table/etc/react-table.api.md, packages/react-components/react-table/src/hooks/types.ts, packages/react-components/react-table/src/hooks/useMultipleSelection.ts, packages/react-components/react-table/src/hooks/useSingleSelection.ts, packages/react-components/react-table/src/hooks/useSort.test.ts, packages/react-components/react-table/src/hooks/useSort.ts, packages/react-components/react-table/src/hooks/useTable.test.ts, packages/react-components/react-table/src/hooks/useTable.ts, packages/react-components/react-table/src/stories/Table/MultipleSelect.stories.tsx, packages/react-components/react-table/src/stories/Table/SingleSelect.stories.tsx, packages/react-components/react-table/src/stories/Table/Sort.stories.tsx, packages/react-components/react-table/src/stories/Table/index.stories.tsx
A lot of the row state was actually inferred from other state. This
creates an unnecessary coupling between the selection state and the
actual render data.
To impreove this, this PR adds the `rowEnhancer` concept. This allows
users to 'enhance' their rows with extra functionality or data with
access to the table state. The enhancer runs during the creation of
`rows` which means the user does not need to unnecessarily iterate over
the return of `useTable` again.
Also makes it easier to split up the different substates in the future
Addresses #24226
=> feat: Remove inferred row state and add `rowEnhancer` option

azure-pipelines.yml
Currently the builds are scoped by the published package, which can lead to some edge cases:
* vr-test package is not affected -> builds anyway
* published package is not affected but the vr-test package is
=> chore: Scope screener builds by vr-test project

change/@fluentui-react-text-01530fa1-545f-4a94-a9fb-00fa2be3dc3b.json, change/@fluentui-react-theme-bdcdae2f-8e92-4d18-b7da-d8336334caa6.json, change/@fluentui-react-theme-sass-7ddd5d89-4d81-49e6-b347-a1f779b7dbf0.json, packages/react-components/react-text/etc/react-text.api.md, packages/react-components/react-text/src/components/Text/Text.test.tsx, packages/react-components/react-text/src/components/Text/Text.types.ts, packages/react-components/react-text/src/components/Text/useTextStyles.ts, packages/react-components/react-theme-sass/sass/fontTokens.scss, packages/react-components/react-theme/etc/react-theme.api.md, packages/react-components/react-theme/src/global/fonts.ts, packages/react-components/react-theme/src/global/typographyStyles.ts, packages/react-components/react-theme/src/tokens.ts, packages/react-components/react-theme/src/types.ts
- there was no `fontWeightBold` token in react-theme
- there was no `Body2` in Typography
- all Stronger Typography variants used `fontWeightMedium`
Add `fontWeightBold` token to react theme
Add `bold` as a valid option of `weight` prop in `Text`.
Update typography to use `fontWeightBold` in all Stronger variants
Add `Body2` to Typography and also as a component to `react-text`
=> feat(react-theme): Add bold font weight

scripts/token-pipeline.ts
To update tokens in `react-theme` an engineer runs `yarn token-pipeline`. The script always clones the repo.
This is problematic when you are debugging the pipeline.
If `--design-tokens-repo=<path>` argument is passed to the script, it now uses the local copy of the repo instead of cloning it.
Related to #24161
=> chore: Add possibility to run locally-cloned token-pipeline

rfcs/shared/build-system/package-public-api.md
This RFC introduces style guide/ common approach for our packages API access modifiers that will be enforced by tooling.
[Preview 📖 👀](https://github.com/microsoft/fluentui/pull/23577/files?short_path=28b8ebf#diff-28b8ebf5a974c1a0ac4f3597aeb0b777c1b637688a0952b283f01c4c29f7b5f4)
[Tooling implementation PR 🛠](https://github.com/microsoft/fluentui/pull/23369) 
To be able to not delay v9 stable release any further we need all teams to review their packages by the end of Wednesday 22nd of June and apply following:
- if you use `@internal` modifier already, please verify that it is not exposed from package public API. If that's the case please remove it - BREAKING CHANGE in RC
- mark your package APIs with `@internal` modifier where necessary taking into consideration former bullet point
**Why …
=> docs(rfc): add api access modifiers style-guide RFC for v9

change/@fluentui-react-ca0880b1-2d51-40a5-ba98-0c357f33a91f.json, packages/react/etc/react.api.md, packages/react/src/components/ChoiceGroup/ChoiceGroup.types.ts, packages/react/src/components/ChoiceGroup/ChoiceGroupOption/ChoiceGroupOption.types.ts
ODSP upgrade to v8 requires hundreds of updates to render callbacks in ChoiceGroup because of the creation of the IChoiceGroupOptionProps.  This extends IChoiceGroupOption.  This change allows existing callbacks that take IChoiceGroupOption to continue to work without having to manually update the typing.
- Added IChoiceGroupOption as a parameter type in render callbacks for ChoiceGroup.
=> Easy choice group option props

change/@fluentui-react-6701599d-0685-4f2a-8f1e-0f9b843ebef3.json, packages/react/src/components/List/List.test.tsx, packages/react/src/components/List/List.tsx
`List` component has stale props issue and uses invalid references of `getPageSpecification()`, check https://github.com/microsoft/fluentui/issues/20319#issuecomment-1209366179 for more details.
This PR fixes an issue to use proper reference of `getPageSpecification` from actual `props`.
Fixes #20319.
=> fix(List): solve stale props problem with getPageSpecification

change/@fluentui-react-28f94bba-caa9-4aac-81af-6cf0d0cd592d.json, packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap, packages/react/src/components/GroupedList/GroupedList.base.tsx, packages/react/src/components/GroupedList/GroupedList.test.tsx
Grouped list can show old items
Grouped list does not show old items
Fixes #23135
=> Fix grouped list derived state from props

package.json, yarn.lock
We are running into lage execution issues.
Looks like the dependency chain is being incorrectly resolved which leads to undeterministic failures of pipelines
**Example:**
1. If i run `yarn lage build --since origin/master` on local machine, it will explode on `ssr-tests` `build`
2. if i run `yarn lage build --to @fluentui/ssr-tests`  it will pass the build
3. if I turn off cache `yarn lage build --since origin/master --no-cache`  it will explode on different error.... 
we use latest `lage`
`yarn lage build --since origin/master --no-cache`  passed
- https://github.com/microsoft/fluentui/pull/24279
=> chore: bump lage to fix dep tree resolution issues

change/@fluentui-react-tabster-8d97f222-b315-470d-88a0-50ab3e3b69fe.json, packages/react-components/react-tabster/package.json, packages/react-components/react-tabster/src/hooks/useKeyboardNavAttribute.ts, yarn.lock
Bumps tabster to 2.1.2 and keyborg to 1.2.1
Fixes #20892
=> chore: Bump tabster to 2.1.2

change/@fluentui-react-de587d83-1c46-488b-9d1e-e1dd10739fb1.json, change/@fluentui-react-focus-ec8c78ab-cee2-4700-b82d-5ed2aef1fd4b.json, change/@fluentui-utilities-7b6dc27b-e41a-4cdc-9041-ba28da7a3401.json, packages/react-examples/src/react-focus/FocusZone/FocusZone.Disabled.Example.tsx, packages/react-focus/etc/react-focus.api.md, packages/react-focus/src/components/FocusZone/FocusZone.tsx, packages/react-focus/src/components/FocusZone/FocusZone.types.ts, packages/react/etc/react.api.md, packages/react/src/components/OverflowSet/OverflowSet.base.tsx, packages/react/src/components/OverflowSet/OverflowSet.types.ts, packages/utilities/etc/utilities.api.md, packages/utilities/src/focus.ts
If a FocusZone contains a hidden element (especially if it's the first element), `focus` doesn't move as expected
With this PR you can pass `bypassHiddenElements` into `FocusZone.focus` and `Overflow.focus` so that focus gets set as expected
=> FocusZone: Add ability to bypass hidden elements

scripts/gulp/tasks/screener.ts, scripts/screener/screener.runner.ts, scripts/tasks/screener.ts
CI scopes storybook builds and calls the proxy to update the checks status.
CI no longer scopes storybook builds as the scoping is done by the screener proxy, which is also the one directly updating all of the checks statuses.
Addresses #24305
=> Enable screener proxy to scope and update checks

packages/fluentui/CHANGELOG.md, packages/fluentui/react-bindings/src/FocusZone/FocusTrapZone.tsx, packages/fluentui/react-bindings/test/FocusZone/FocusTrapZone-test.tsx
FocusTrapZone adds aria-hidden to only direct children of body. But when it's time to remove aria-hidden, it only tries to remove aria-hidden on FocusTrapZone element itself, even though it is not always a direct children of body. In this case the aria-hidden on the parent element is never removed.
This PR checks for parent element of FocusTrapZone and remove aria-hidden
Try: https://codesandbox.io/s/confident-rosalind-dhi2gy?file=/example.tsx
1. click on the button to open popup, notice a dialog is opened at the same time
2. dismiss dialog by clicking on 'cancel' button
3. hit 'tab' key and focus should go inside the first button 'grid-item-0' in Popup content.
4. try to navigate by right arrow key. The expected behavior is that focus move to 'grid-item-1', but the actual behavior is …
=> fix(FocusTrapZone): aria-hidden on FocusTrapZone's parent is not removed when there's multiple FTZ

change/@fluentui-react-3a375dde-2393-4e0c-84a9-8550ee6e33d1.json, packages/react/package.json
When trying to use `getStyles` on TextField, the method cannot be accessed because the styles file is not exported.
TextField `getStyles` is accessible.
This PR is related to #22161.
=> @fluentui/react: Adding TextField style file to export map

change/@fluentui-react-avatar-6c6ac0d8-779b-4863-b199-95916a602eab.json, packages/react-components/react-avatar/e2e/AvatarGroup.e2e.tsx, packages/react-components/react-avatar/src/components/AvatarGroupPopover/useAvatarGroupPopover.tsx, packages/react-components/react-avatar/src/components/AvatarGroupPopover/useAvatarGroupPopoverStyles.ts
Currently Content has most of the styles needed for the Popover Surface, this brings problems with screen readers:
* aria-modal doesn't have an aria-label.
* aria-label is in a `<ul>` therefore there are some listbox problems in Windows where the screen reader mode is changed to forms mode.
* As a side effect, the styles to handle overflow are in the wrong element.
Makes PopoverSurface focusable, moves Overflow aria-label to PopoverSurface, and moves content styles to PopoverSurface. This fixes the accessibility issues mentioned above.
#23773
=> fix: Making PopoverSurface focusable, moving Overflow aria-label to PopoverSurface, and moving content styles to PopoverSurface

change/@fluentui-react-a918e551-6867-4583-be9e-dedfa8d6b135.json, packages/react-examples/src/react/Pickers/TagPicker.Basic.Example.tsx, packages/react/etc/react.api.md, packages/react/src/components/pickers/TagPicker/TagItem.styles.ts, packages/react/src/components/pickers/TagPicker/TagPicker.tsx, packages/react/src/components/pickers/TagPicker/__snapshots__/TagItem.test.tsx.snap, packages/react/src/components/pickers/TagPicker/__snapshots__/TagPicker.test.tsx.snap
This PR starts to address the issues in #24314, fixing a bug that broke ctrl+a selection, and 'del' key deletion. This PR also fixes the styles so that they are properly driven from the is-selected class, and are applied to all items when ctrl + a is pressed.
After this PR I'll come back and look at adding click to select, which will be a bit more complicated and more of a feature add.
=> Tag Picker: fix select all and delete

change/@fluentui-react-aria-4b79e85a-b5bc-45ce-802e-9ea17f31184c.json, packages/react-components/react-aria/src/hooks/index.ts, packages/react-components/react-aria/src/hooks/useARIAButton/index.ts, packages/react-components/react-aria/src/hooks/useARIAButton/types.ts, packages/react-components/react-aria/src/hooks/useARIAButton/useARIAButton.stories.tsx, packages/react-components/react-aria/src/hooks/useARIAButton/useARIAButtonProps.test.tsx, packages/react-components/react-aria/src/hooks/useARIAButton/useARIAButtonProps.ts, packages/react-components/react-aria/src/hooks/useARIAButton/useARIAButtonShorthand.test.tsx, packages/react-components/react-aria/src/hooks/useARIAButton/useARIAButtonShorthand.ts, packages/react-components/react-aria/src/index.ts
Organizes folder structure for `useARIAButton` into a single folder, to open space for more hooks.
=> chore(react-aria): `useARIAButton` folder

change/@fluentui-react-combobox-03bbe68a-a87b-4349-99eb-17bf3c7df044.json, packages/react-components/react-combobox/src/components/Dropdown/Dropdown.test.tsx, packages/react-components/react-combobox/src/components/Dropdown/useDropdown.tsx, packages/react-components/react-combobox/src/components/Dropdown/useDropdownStyles.ts, packages/react-components/react-combobox/src/stories/Dropdown/DropdownDefault.stories.tsx
Similar to Combobox, Dropdown also moves the currently highlighted option to match typed characters. It follows a slightly different matching schema than combobox, and also doesn't need to have any value-related logic.
The desired behavior for Dropdown is:
- typing the same letter repeatedly cycles through options starting with that letter (e.g. "cc" would move first to cat, then chupacabra)
- typing a series of different letters moves to an option that matches the entire typed string (with a 500ms no-typing timeout to reset)
- typing a letter or series of letters that has no matches will clear the active option. Using arrow keys afterwards will begin again at the top.
- typing causes the dropdown to open
Dropdown now also renders the listbox when collapsed but focused, so if a user types …
=> fix: react-combobox Dropdown moves active option based on typed characters

rfcs/shared/build-system/07-package-subfolder-structure-for-v9.md, rfcs/shared/build-system/07-standard-package-structure-for-v9.md
RFC for defining a convention on how files should be organized in v9 packages.
[PREVIEW](https://github.com/microsoft/fluentui/pull/24332/files?short_path=aa0c69f#diff-aa0c69ffcf1e796ffc7b69168e9575f60caaa35981660d6ebb2b8d8e64ff1d19)
Part of #24129
=> RFC: File Organization Convention for v9 Packages

scripts/monorepo/runPublished.js
runPublished wont resolve correctly v8 related packages 
runPublished logic resolves v8 related packages
Fixes https://github.com/microsoft/fluentui/issues/24467
=> fix(scripts): make runPublished properly return v8 packages for build

change/@fluentui-react-avatar-553b43fa-6ccc-4d4b-a6e7-81b0e3803e07.json, packages/react-components/react-avatar/src/components/AvatarGroup/renderAvatarGroup.tsx, packages/react-components/react-avatar/src/components/AvatarGroupPopover/renderAvatarGroupPopover.tsx, packages/react-components/react-avatar/src/contexts/AvatarGroupContext.ts
AvatarGroup and AvatarGroupPopover use AvatarGroup's context as follows: `AvatarGroupContext.Provider`
AvatarGroup and AvatarGroupPopover now use AvatarGroup's context as it should by importing `AvatarGroupProvider`
Fixes #24447
=> chore(react-avatar): AvatarGroup context cleanup

change/@fluentui-react-06abbff8-7902-4a49-bdff-476e15c6e4fe.json, packages/react/etc/react.api.md, packages/react/src/components/ActivityItem/index.ts
Same change from v7 from https://github.com/microsoft/fluentui/pull/24473 but in v8.
This change cannot be easily cherry-picked from master to 7.0 as it is in different files and the type export is different.
=> Export activity item styles v8

change/office-ui-fabric-react-1d21c8fd-c529-4278-962a-9d9a8e7a098d.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md, packages/office-ui-fabric-react/src/components/DetailsList/index.ts
This change was done previously in v8, but differently because implicit exports were disabled. https://github.com/GeoffCoxMSFT/fluentui/commit/f43f5fa45ce881e096177e26f54072a7a2a562d5
- added top-level export of DetailsColumn getStyles as getDetailsColumnStyles
- added top-level export of DetailsHeader getStyles as getDetailsHeaderStyles
- added top-level export of DetailsList getStyles as getDetailsListStyles
- added top-level export of DetailsRow getStyles as getDetailsRowCheckStyles
- added top-level export of ShimmeredDetailsList getStyles as getShimmeredDetailsListStyles
Fixes #24455
=> Export detailslist styles

change/office-ui-fabric-react-dc2fbcb8-eb8e-4741-965b-17e26b616682.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md, packages/office-ui-fabric-react/src/components/CommandBar/index.ts
- added top-level export of CommandBar getStyles as getCommandBarStyles
- added top-level export getCommandButtonStyles
Fixes #24453
=> Exported getCommandBarStyles

change/@fluentui-react-7370dc1e-3d86-49b6-9e76-0a971d251bfa.json, packages/react/etc/react.api.md, packages/react/src/components/ContextualMenu/ContextualMenu.classNames.ts, packages/react/src/components/ContextualMenu/index.ts
- added top-level export of ContextualMenu getItemStyles as getContextualMenuItemStyles
- added top-level export of ContextualMenu getItemClassNames as getContextualMenuItemClassNames
Updates #24454
To be cherry picked to 7.0 branch.
=> Added exports for ContextualMenu getItemStyles and getItemClassNames to v8

change/@fluentui-react-input-b6dae232-bb04-4dcd-90b6-eb9272f009fe.json, packages/react-components/react-input/src/components/Input/useInputStyles.ts
Input has a box-shadow in filled appearances.
Note: I've removed the contrasting background and made the label black to differentiate the before and after.
Input does not have a box-shadow in filled appearances.
Note: I've removed the contrasting background and made the label black to differentiate the before and after.
Note: this is the only input control that has this box-shadow, here's a list of the files that have a box-shadow:
Fixes #24076
=> fix(react-input): Remove box-shadow from Input filled appearances

change/office-ui-fabric-react-e8c0506d-254b-4a43-9ea7-0fcbf01c98c2.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md, packages/office-ui-fabric-react/src/components/Layer/Layer.notification.ts, packages/office-ui-fabric-react/src/components/Layer/index.ts
- added top-level export of Layer notification methods
- added top-level export of Layer getStyles as getLayerStyles
Fixes #24456
=> Added exports from Layer notification for v7

change/@fluentui-react-7043e19d-280f-4044-a4f6-4b85b0cde742.json, packages/react/etc/react.api.md, packages/react/src/components/Layer/Layer.notification.ts, packages/react/src/components/Layer/index.ts
- added top-level export of Layer notification methods
- added top-level export of Layer getStyles as getLayerStyles
Updates #24456
=> Export layer notification methods in v8

scripts/storybook/utils.js
Fixes #24474 by using a relative path with properly swapped out separators. 
current code produced these results on PC
``` 
function config(entry = []) {
return [...entry, require.resolve('../D:\git\fluentui\packages\react-components\react-storybook-addon\src/preset/preview')];
}
function managerEntries(entry = []) {
return [...entry, require.resolve('../D:\git\fluentui\packages\react-components\react-storybook-addon\src/preset/manager')];
}
```
=> revert to relative path with proper seperator

packages/react-examples/src/react/Modal/Modal.Basic.Example.tsx, packages/react-examples/src/react/Modal/Modal.Modeless.Example.tsx
- v8 draggable modal example does not allow for text selection of the body when draggable.
- demonstrates how to use the `dragHandleSelector` option to allow custom click targeting of the `Modal` header which enables users to select text when the Modal draggable 
https://user-images.githubusercontent.com/8649804/186278654-73b16d2a-5657-4951-994d-be2b8958c197.mp4
Fixes #24469
=> docs(v8): Modal examples now target header to allow text selection when draggable

packages/react-examples/src/react/Announced/Announced.LazyLoading.Example.tsx, packages/react-examples/src/react/Image/Image.Center.Example.tsx, packages/react-examples/src/react/Image/Image.CenterContain.Example.tsx, packages/react-examples/src/react/Image/Image.CenterCover.Example.tsx, packages/react-examples/src/react/Image/Image.Contain.Example.tsx, packages/react-examples/src/react/Image/Image.Cover.Example.tsx, packages/react-examples/src/react/Image/Image.Default.Example.tsx, packages/react-examples/src/react/Image/Image.MaximizeFrame.Example.tsx, packages/react-examples/src/react/Image/Image.None.Example.tsx, packages/react-examples/src/react/MarqueeSelection/MarqueeSelection.Basic.Example.tsx, packages/react-examples/src/react/TeachingBubble/TeachingBubble.Illustration.Example.tsx, packages/react-examples/src/react/TeachingBubble/TeachingBubble.WideIllustration.Example.tsx
- Placeholder images dont render:
- now linked to the correct source using https, placeholder images now render:
=> docs(v8): usage of placeholder images now link to correct https protocol

change/office-ui-fabric-react-57c82b0b-3fee-4424-914c-f6433971e342.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md, packages/office-ui-fabric-react/src/GroupedList.ts
- added top-level exports of GroupedListUtilities to GroupedList
Fixes #24506
=> Added exports for GroupedListUtilities in v7

change/@fluentui-react-125a9967-6b56-48b1-825d-6cbc7fbcc823.json, packages/react/etc/react.api.md, packages/react/src/GroupedList.ts
- added top-level exports of GroupedListUtilities to GroupedList
Updates #24506
=> Added export of GroupedListUtilities in v8

packages/react-components/react-dialog/src/stories/Dialog/DialogAlert.stories.tsx, packages/react-components/react-dialog/src/stories/Dialog/DialogChangeFocus.stories.tsx, packages/react-components/react-dialog/src/stories/Dialog/DialogControllingOpenAndClose.stories.tsx, packages/react-components/react-dialog/src/stories/Dialog/DialogDefault.stories.tsx, packages/react-components/react-dialog/src/stories/Dialog/DialogNested.stories.tsx, packages/react-components/react-dialog/src/stories/Dialog/DialogNoFocusableElement.stories.tsx, packages/react-components/react-dialog/src/stories/Dialog/DialogScrollingLongContent.stories.tsx
`aria-label` has been added on most `DialogSurface` stories since `tabster` didn't support `aria-labelledby` attribute (which is used internally by `DialogSurface`) as a valid description.
Modifies some content from `DialogBody`
removes `aria-label` since newest version of `tabster` supports `aria-labelledby` attribute.
=> chore(react-dialog): removes aria-label from stories

.github/workflows/screener-run.yml
GHA workflows do not do anything for now since they are not triggered. In order to migrate to the workflows, testing is needed. The `screener-run.yml` workflow is triggered by the `workflow_run` event. 
Workflows triggered by the `workflow_run` event will only run if they are present on the default branch, so in order to test it(PR #24466), the new version of `screener-run.yml` needs to be on the master branch.
`screener-run.yml` will be updated but it will not influence anything running on the master branch as it will not get to actually run.
=> Update screener-run.yml workflow

packages/react-examples/src/react/Announced/Announced.LazyLoading.Example.tsx, packages/react-examples/src/react/Image/Image.Center.Example.tsx, packages/react-examples/src/react/Image/Image.CenterContain.Example.tsx, packages/react-examples/src/react/Image/Image.CenterCover.Example.tsx, packages/react-examples/src/react/Image/Image.Contain.Example.tsx, packages/react-examples/src/react/Image/Image.Cover.Example.tsx, packages/react-examples/src/react/Image/Image.Default.Example.tsx, packages/react-examples/src/react/Image/Image.MaximizeFrame.Example.tsx, packages/react-examples/src/react/Image/Image.None.Example.tsx, packages/react-examples/src/react/MarqueeSelection/MarqueeSelection.Basic.Example.tsx, packages/react-examples/src/react/TeachingBubble/TeachingBubble.Illustration.Example.tsx, packages/react-examples/src/react/TeachingBubble/TeachingBubble.WideIllustration.Example.tsx
- placeholder.com assets not loading (see [here](https://developer.microsoft.com/en-us/fluentui#/controls/web/image)) when viewed through docsite so this PR replaces them with image assets served from our CDN storage.
Follow up to #24489
Fixes #24301
=> docs(v8): replace placeholder images with assets from CDN

change/@fluentui-react-765cf0cb-5587-4d23-a713-9abf3a3ab577.json, change/@fluentui-utilities-7df700d2-c8fa-413e-8dc3-d7a8021bd475.json, packages/react/etc/react.api.md, packages/react/src/components/GroupedList/GroupHeader.base.tsx, packages/react/src/components/GroupedList/GroupedList.types.ts, packages/react/src/utilities/selection/SelectionZone.tsx, packages/utilities/etc/utilities.api.md, packages/utilities/src/selection/Selection.ts, packages/utilities/src/selection/Selection.types.ts
Revised the recent changes to enhanced Group List selection to avoid backwards-compatibility issues:
1. Made the new methods added to `ISelection` optional.
2. Preserved the existing behavior of `onRenderTitle` in `GroupHeader` and added a new `onRenderName` callback to provide the correct, targeted override.
=> Fix backwards-compatibility of Group Selection additions

scripts/screener/screener.runner.ts
In order to check if a screener test should be skipped or not, the proxy sends a GET request to the blob storage address where test apps should be deployed and checks whether the response is 200(test app deployed) or 404(test app not deployed). However, test apps from previous build will still be accessible from the same address for builds that have not uploaded test apps so the response would still be 200 instead of 404. 
The proxy receives, besides the payload used for calling the screener API, the status of the test app artifact through another field of the request body: `isArtifactPresent`, so that the proxy can instantly decide if a screener check should be skipped or not without the need for any additional requests. 
Addresses #24466
=> Add field to proxy request body

change/@fluentui-web-components-207210c9-d295-4aec-a63a-3b1d46fe9c50.json, packages/web-components/package.json, yarn.lock
Updates FAST packages to resolve issues with form constraint validation on form associated elements
Fixes #
=> update FAST packages to resolve issues with form constraint validation on form associated elements

change/@fluentui-react-combobox-0da3aa7d-1f93-4987-932b-52aaaf1e8f38.json, packages/react-components/react-combobox/src/components/Combobox/useComboboxStyles.ts, packages/react-components/react-combobox/src/components/Dropdown/useDropdownStyles.ts
Resolves part of #23926
- Fixes the hover/active border colors for the outline style
- Fixes inner content padding for the Dropdown button and Combobox input
- Updates `minWidth` so both Dropdown and Combobox are the same width by default
- Updates borders to use tokens for width
=> fix: Combobox and Dropdown hover/active borders and padding style fixes

change/@uifabric-charting-807e2156-2cf8-4462-8115-bda3e4dfbabd.json, packages/charting/src/types/IDataPoint.ts
fluentui/react-charting got 1 minor bump ahead of uifabric/charting when it was created. that version was already published, so we need to pull charting forward a minor version. Then we can fix the grouping between the two and bump 1 of them to get them in sync
=> Bump uifabric/charting to match minor version of fluentui/react-charting

change/@uifabric-charting-6d7a4b95-c260-49c4-ab19-ef3c2ae1013b.json, packages/charting/src/components/LineChart/LineChart.base.tsx
Order of lines in line chart is not correct. The last line in order of legend appears on top of other lines.
Lines appear in same order as that of legends. Lines in beginning of legend are on top of subsequent lines in the legend.
Fixes #
=> Cherry pick fix line order in line chart as per legends

change/@fluentui-react-charting-3e3805e8-7750-4654-8e75-736a660ed7b3.json, packages/react-charting/TechnicalDetails.md, packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx, packages/react-charting/src/components/CommonComponents/CartesianChart.types.ts, packages/react-charting/src/utilities/utilities.ts
Currently the dates of an axis cannot be localized using the localization support provided by javascript.
Provide support for localizing dates of axis using javascript provided toLocaleString method.
Fixes #
=> Add support for javascript date localization

apps/vr-tests-react-components/src/stories/Spinner.stories.tsx, change/@fluentui-react-theme-98ccbaf6-2736-430a-b1d6-8a28818a2bc4.json, packages/react-components/react-spinner/src/stories/Spinner/SpinnerAppearance.stories.tsx, packages/react-components/react-theme/src/alias/highContrastColorPalette.ts, packages/react-components/react-theme/src/alias/lightColorPalette.ts
1. `colorPalette*Background1` was **white** in High Contrast
2. `colorPalette*Foreground1` was **black** in High Contrast
3. `colorPalette*` colors used hardcoded **white** and **black** instead of **hcCanvas** and **hcCanvasText** in High Contrast
4. `colorPalette*Foreground1` used **Shade 10** for all Status shared colors in Light Theme
1. `colorPalette*Background1` is **hcCanvas** (resolves to black in default windows HC theme) in High Contrast
2. `colorPalette*Foreground1` is **hcCanvasText** (resolves to white in default windows HC theme) in High Contrast
3. `colorPalette*` colors now use **hcCanvas**, **hcCanvasTest** or **hcHighlight** instead of *white* and *black* for all status and persona Color Palette colors
4. `colorPaletteYellowForeground1` uses **Shade 30** in Light Theme, …
=> fix(react-theme): Swap Background1 and Foreground1 in HC color palette

.github/workflows/screener-build.yml, packages/react-components/babel-preset-global-context/src/index.ts
Temporarily logging `lage` output for debugging purposes (understand if affected packages check works properly). Locally it works as expected:
```sh
$ yarn check:affected-package --packages @fluentui/vr-tests --pr=true
false
```
For an example change:
```sh
$ yarn lage info --since origin/master
info {
info   "command": [],
info   "scope": [
info     "@fluentui/react-alert",
info     "@fluentui/theme-designer",
info     "@fluentui/react-components",
info     "@fluentui/react-portal-compat",
info     "@fluentui/ts-minbar-test-react-components",
info     "@fluentui/stress-test",
info     "@fluentui/ssr-tests-v9",
info     "@fluentui/public-docsite-v9"
info   ],
info   "packageTasks": []
info }
```
=> Update "screener-build.yml" to include lage's output

scripts/screener/screener.runner.ts
Check for existence of  environment variable `SYSTEM_PULLREQUEST_SOURCECOMMITID` in `screener.runner.ts` would break screener checks for master builds due to the `SYSTEM_PULLREQUEST_SOURCECOMMITID` environment variable not exsiting in such case.
Check has been removed and `commit` has become an optional argument for the `scheduleScreenerBuild` function.
Reverting change from PR #24345 @Hotell 
Fixes #
=> Remove check for commit existence and make it optional

change/@uifabric-icons-8a46a4cc-b4ee-402f-94e1-514ba647f024.json
We want uifabric/icons and fluentui/font-icons-mdl2 on the same version so we can then beachball sync them in v7.
This bumps the version of icons to 7.8.0 which should match font-icons-mdl2
Updated #24393
=> Change file to bump version

.github/workflows/screener-build.yml
The `environment` file used to define environment variables for each job used to make `lage` assume the whole workspace has been affected when it is not the case.
The `environment` file is deleted when it is no longer needed so that the `lage` command can return an accurate result.
Adresses build scoping issue after merging PR #24466
=> Remove downloaded artifact file after using it

apps/public-docsite/src/root.tsx, apps/public-docsite/src/utilities/createSite.tsx, change/@fluentui-public-docsite-setup-fead5804-7705-4646-842d-5bfbf4fd7a28.json, packages/public-docsite-setup/index.html
Addresses a couple issues found in #24610
Now that the CDN is immutable, each deploy has a unique URL, so core we can't just add 11.0.1 to the old core URL and get the new version...we need to update the entire URL with the build number. Fortunately, core doesn't rev all that often.
Secondly, it seems the ID that used to be on the 'back to top' button has been removed, so I updated the selector to something that SHOULD be static.
=> Website fabric core

apps/public-docsite-v9/src/shims/ThemeShim/v9ThemeShim.ts, change/@fluentui-react-avatar-bbc12538-d128-45e3-9f9b-302829fede9d.json, change/@fluentui-react-badge-749f0a23-1986-4a17-899d-be7ef2db5724.json, change/@fluentui-react-popover-38cb556a-cc08-471a-8aeb-878b78bbbbcd.json, change/@fluentui-react-spinner-3631728e-701e-46a0-a6b5-41fb4785a921.json, change/@fluentui-react-theme-591d6c0f-d093-4b79-ae3e-067b74c7c0d0.json, change/@fluentui-react-theme-sass-8ca8c7e8-cbe6-4104-b893-1de751254302.json, change/@fluentui-react-tooltip-f76bb687-2740-4cb7-a9be-63917260000f.json, packages/react-components/react-avatar/src/components/Avatar/useAvatarStyles.ts, packages/react-components/react-badge/src/components/Badge/useBadgeStyles.ts, packages/react-components/react-popover/src/components/PopoverSurface/usePopoverSurfaceStyles.ts, packages/react-components/react-spinner/src/components/Spinner/useSpinnerStyles.ts, packages/react-components/react-theme-sass/sass/colorTokens.scss, packages/react-components/react-theme/etc/react-theme.api.md, packages/react-components/react-theme/src/alias/darkColor.ts, packages/react-components/react-theme/src/alias/highContrastColor.ts, packages/react-components/react-theme/src/alias/lightColor.ts, packages/react-components/react-theme/src/alias/teamsDarkColor.ts, packages/react-components/react-theme/src/tokens.ts, packages/react-components/react-theme/src/types.ts, packages/react-components/react-tooltip/src/components/Tooltip/useTooltipStyles.ts
Rename `colorNeutralForegroundInvertedStatic` token to `colorNeutralForegroundStaticInverted` in order to match design spec.
Theoretically this would be a breaking change, but since the token was added in #24027 no FUI version has been released.
cc @spmonahan
=> fix(react-theme): Rename colorNeutralForegroundInvertedStatic token to colorNeutralForegroundStaticInverted

change/@fluentui-react-f6466949-fe16-46ab-a50a-0548dd53baef.json, change/@fluentui-style-utilities-86219b72-da1a-4e91-8042-417d42500c69.json, packages/react/src/components/pickers/PeoplePicker/PeoplePickerItems/PeoplePickerItem.styles.ts, packages/style-utilities/etc/style-utilities.api.md, packages/style-utilities/src/interfaces/IGetFocusStyles.ts, packages/style-utilities/src/styles/getFocusStyle.ts
=> Update PeoplePicker focus styles for the close button - Add borderRadius to getFocusStyle

apps/react-18-tests-v9/cypress.config.ts, apps/react-18-tests-v9/package.json, apps/react-18-tests-v9/tsconfig.cy.json, apps/react-18-tests-v9/tsconfig.json
- Adds cypress setup which will enable writing cypress tests in this package. 
- cypress test files must have `.e2e.` in its filename.
=> feat(react-18-tests-v9): Add cypress setup to enable writing cypress tests

apps/react-18-tests-v9/tsconfig.cy.json
- now correctly extends the root package `tsconfig.json` file instead of the monorepo one for the `tsconfig.cy.json` file
=> fix(react-18-tests-v9): extend correct tsconfig.json

.github/CODEOWNERS
We've removed coastal folks from the `cxe-red` alias, so it probably makes sense to add the cxe-coastal alias to the v8 react package & components.
=> chore: add cxe-coastal to @fluentui/react package and components

change/@fluentui-react-81ba3c6c-fe16-4767-bd80-1557c3a93c01.json, packages/react/etc/react.api.md, packages/react/src/components/Button/index.ts
fixes #24623
this was from a random discussion request back in may, but seeing as we explicitly do this in v9, it seems a welcome change for anyone using the v8 button.
=> Export ButtonGlobalClassNames

change/@fluentui-utilities-fb8931ea-afab-44af-af7e-729cb3a2f647.json, packages/utilities/src/useFocusRects.ts
PR #24340 modified FocusRectsContext so that the providerRef should never be undefined (the entire context is undefined if there is none). However, #24616 indicates that in some cases, providerRef can get set to undefined.
It is unclear where or how it is getting set to undefined, but perhaps one of the places that uses FocusRectsProvider can get into a bad state and/or is casting away undefined somewhere.
Add a check that the `providerRef` is not undefined before trying to use it.
* Fixes #24616
=> [v8] fix: Add check for FocusRectsProvider providerRef being undefined

apps/react-18-tests-v8/package.json, apps/react-18-tests-v8/src/components/ContextualMenu/ContextualMenuExample.tsx
- Removes `type-check` command which is causing a race condition issue in the CI pipeline causing it to fail. `type-check` command for the react-18-tests-v8 app is being ran _BEFORE_ `@fluentui/react` finishes building which causes the intermittent error below.
**Error:**
```
ERR! [@fluentui/react-18-tests-v8 type-check] ERROR DETECTED
ERR! started
ERR! hash: bfb8f2139aa5cf3cc93acad19377a674d8c10378, cache hit? false
ERR! Running /opt/hostedtoolcache/node/14.18.1/x64/bin/npm run type-check
ERR! npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1662060828967-0.16018444283984823/node but npm is using /opt/hostedtoolcache/node/14.18.1/x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
ERR! 
ERR! > …
```
=> fix(react-18-tests-v8): remove type-check command to fix CI issue

change/@fluentui-web-components-30e8b3f3-0f3e-4922-bcae-5737d66d0f0c.json, packages/web-components/src/_docs/integrations/webpack.stories.mdx
Some typos in the webpack integration instructions.
1- Removed extra filename entry in webpack.config.js
2- Import fluentCard and fluentButton instead of fastCard and fastButton respectively
=> Fix typos in webpack integration instructions

change/office-ui-fabric-react-6392d55f-1850-4bee-b31c-a0ff57e7c83f.json, packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx, packages/office-ui-fabric-react/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap
Slowly making this fix in every single version of Calendar 😅
Here's the PR for the same fix in the date-time package: https://github.com/microsoft/fluentui/pull/23990
here's the original PR in v8: https://github.com/microsoft/fluentui/pull/20324
This is the same fix, but in the office-ui-fabric-react Calendar component.
=> v7 fix: remove explicit readonly semantics from Calendar grid in office-ui-fabric-react package

change/@uifabric-file-type-icons-473eed16-0e70-4d5f-8d42-1dbda5cae347.json, change/@uifabric-icons-5a7a49fa-11d9-477c-b670-c9ed25de91ca.json
- bumped patch version of icons to match font-icons-mdl2 in v7
- bumped patch version of file-type-icons to match react-file-type-icons in v7
Updates #24648
=> Patch bump @uifabric/icons and @uifabric/file-type-icons

change/@fluentui-react-button-2869c3ac-e452-48e2-9a3c-7712ebbb999e.json, packages/react-components/react-button/src/components/Button/useButtonStyles.ts, packages/react-components/react-button/src/components/CompoundButton/useCompoundButtonStyles.ts, packages/react-components/react-button/src/stories/MenuButton/MenuButtonIcon.stories.tsx, packages/react-components/react-button/src/stories/SplitButton/SplitButtonIcon.stories.tsx
`Button` components have a `maxWidth` defined, which is a constraint that constantly needs to be overridden by developers.
`Button` components don't have a `maxWidth` defined anymore.
=> chore: Remove max-width style from Button components

change/@uifabric-icons-40124900-4bd1-48bb-8969-116bb72632e4.json, scripts/beachball/index.ts
@uifabric/icons needs a patch bump to match up with @fluentui/font-icons/mdl2
This needs to be done without the grouping on.
Grouping will be restored after a published build of 7.
=> Bump icons version without bumping font-icons-mdl2

change/@fluentui-react-3e54cdb6-be6b-43cf-98cc-d9af921c2afe.json, packages/react/etc/react.api.md, packages/react/src/components/pickers/BasePicker.tsx, packages/react/src/components/pickers/Suggestions/Suggestions.tsx, packages/react/src/components/pickers/Suggestions/Suggestions.types.ts
"Loading" (or, the host-provided loadingText property in Suggestions) is not announced by screenreaders even when fetching suggestions takes a long amount of time. There's no screenreader feedback to users that loading is occurring during this period, and no announcement that anything happened at all until results are generated.
If loading takes longer than 3000ms, announce the loadingText so screenreader users know action is ongoing.
This could also be used in the future if an extendedLoadingText is added so something like "Loading.." -> "Still loading.." might be announced later on.
To test, I used the changes in PR and also locally changed PeoplePicker.Normal.Example.tsx to increase timeout/resolvedelay, then built. Using NVDA we now see the 'loading' announcement:
```
People Picker …
```
=> Update Suggestions loading aria for extended Picker loading

change/@fluentui-react-utilities-76935223-2ad2-4d45-bb36-7bf9c363389d.json, packages/react-components/react-utilities/src/utils/properties.ts
Add the below properties to allowed properties for every html element:
[itemid](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemid)
[itemprop](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemprop)
[itemref](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemref)
[itemscope](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemscope)
[itemtype](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemtype)
=> fix(react-utilities): add microdata properties like itemType to allowed html properties

.github/workflows/screener-build.yml
Reverts microsoft/fluentui#24586
The solution for the issue concerning `lage` has been discovered and will be fixed in the PR #24606 so logging lage's output is no longer needed.
=> Revert "Update "screener-build.yml" to include lage's output"

apps/public-docsite-v9/src/Concepts/Poster/metadata.ts
Currently only `Dialog` component is present on Poster
Adds compound components from `Dialog` as it's becoming more stable, including:
1. Dialog
2. DialogTrigger
3. DialogSurface
4. DialogTitle
5. DialogBody
6. DialogActions
=> chore(public-docsite-v9): adds `Dialog` components to Poster metadata

change/@fluentui-react-dialog-ac4ee2cd-8976-4c96-8d14-cf825f633e82.json, packages/react-components/react-dialog/etc/react-dialog.api.md, packages/react-components/react-dialog/src/components/Dialog/Dialog.types.ts, packages/react-components/react-dialog/src/components/Dialog/useDialog.ts, packages/react-components/react-dialog/src/stories/Dialog/DialogNoFocusableElement.md, packages/react-components/react-dialog/src/stories/Dialog/DialogNoFocusableElement.stories.tsx
Splitting from https://github.com/microsoft/fluentui/pull/24668
A listener to the document must be added if `Escape` keydown is to be listened on some very specific cases:
1. no focusable element inside the `Dialog`
2. focus outside of `Dialog` on a `non-modal` dialog
Removes the global document listener to `Escape` keydown handling.
1. the no focusable element inside the `Dialog` is a discouraged scenario
2. on the case of focus outside of  a `non-modal` `Dialog` then `Escape` key closing the `Dialog` might no be ideal, as `Escape` can be linked with another behaviour.
=> feat(react-dialog): removes document listener to `Escape` keydown

change/@fluentui-react-dialog-5331261d-eb3b-4126-a04e-fbf6d05840ce.json, packages/react-components/react-dialog/src/components/DialogActions/useDialogActionsStyles.ts
`DialogActions` component provides an override using `.fui-Button` static class to ensure `max-width` of `Button` is not set.
https://github.com/microsoft/fluentui/blob/330aa6b960d371456667aae70cccbf116ed58cef/packages/react-components/react-dialog/src/components/DialogActions/useDialogActionsStyles.ts#L22-L24
Removes override `max-width` following up on https://github.com/microsoft/fluentui/pull/24647
Fixes #24650
=> chore(react-dialog): removes `react-button` `max-width` override

change/@fluentui-web-components-57035cee-e2e5-4b27-b1d8-9a664ff7e61d.json, packages/web-components/package.json, yarn.lock
=> update fast-foundation to resolve 24561

change/@fluentui-react-combobox-dcf36678-5acd-424c-89de-aa1363dd9e9d.json, packages/react-components/react-combobox/Spec.md, packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx, packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx, packages/react-components/react-combobox/src/components/Dropdown/Dropdown.test.tsx, packages/react-components/react-combobox/src/components/Listbox/Listbox.test.tsx, packages/react-components/react-combobox/src/utils/ComboboxBase.types.ts, packages/react-components/react-combobox/src/utils/Selection.types.ts, packages/react-components/react-combobox/src/utils/useSelection.ts
Fixes #24537
Fixes #24539
The `onSelect` event was causing type issues and getting called multiple times on Combobox because it overlaps with the native `onSelect` event.
This PR changes the prop name to `onOptionSelect`, and adds tests to combobox/dropdown in addition to the listbox tests.
=> fix: react-combobox rename onSelect to onOptionSelect to avoid native event conflict

change/@uifabric-icons-021a86fa-b129-4dff-b88b-0c41d587f9d5.json, packages/icons/package.json, scripts/beachball/index.ts
Bumped the version in package.json to have font-icons-mdl2 and icons match.  
Restored the version grouping config.
Update #24393
=> Sync icons and font-icon-mdl2 versions

change/@fluentui-react-radio-05cc89eb-04f6-4d83-ad59-96c8633a7954.json, packages/react-components/react-radio/src/components/RadioGroup/RadioGroup.types.ts, packages/react-components/react-radio/src/stories/Radio/RadioGroupRequired.stories.tsx
The documentation of RadioGroup's `required` prop is potentially confusing. It doesn't require you to select all radios--that's impossible; instead it requires that there is a selection in the group.
Clarify the documentation of RadioGroup's `required` prop.
=> Clarify the documentation of RadioGroup's `required` prop

apps/vr-tests-react-components/src/stories/Button.stories.tsx, change/@fluentui-react-button-2d7b0be2-d4e1-469e-8bf8-032018a98cfb.json, packages/react-components/react-button/src/components/Button/useButtonStyles.ts, packages/react-components/react-button/src/stories/Button/ButtonWithLongText.stories.tsx, packages/react-components/react-button/src/stories/CompoundButton/CompoundButtonWithLongText.stories.tsx, packages/react-components/react-button/src/stories/MenuButton/MenuButtonWithLongText.stories.tsx, packages/react-components/react-button/src/stories/SplitButton/SplitButtonWithLongText.stories.tsx, packages/react-components/react-button/src/stories/ToggleButton/ToggleButtonWithLongText.stories.tsx
`Button` components used to truncate long text when it was longer than the width of the button. This changed a while ago but the stories stayed in the documentation, which are effectively broken.
`Button` components now wrap long text when it is longer than the width of the button. The stories have also been updated to reflect this and visual regression tests added to test this.
As part of this change, the `min-height` styles in `Button` components have been replaced by their `padding` + `border` + `line-height` calculation equivalent so the padding is always the same independent of how many lines of text the `Button` has.
Fixes #23129
=> fix: Wrapping long text in Button components

change/@fluentui-react-utilities-3b90ac0a-38dc-4a1f-876b-613ec6eade09.json, packages/react-components/react-utilities/src/utils/getNativeElementProps.ts, packages/react-components/react-utilities/src/utils/properties.ts
Split PR from https://github.com/microsoft/fluentui/pull/24525
Adds `dialog` props to `getNativeElementProps`
=> feat(react-utilties): add dialog properties to getNativeElementProps

change/@fluentui-react-table-f0050981-47d5-4725-9d63-99142fda10f9.json, packages/react-components/react-table/etc/react-table.api.md, packages/react-components/react-table/src/components/Table/Table.types.ts, packages/react-components/react-table/src/hooks/selectionManager.ts, packages/react-components/react-table/src/hooks/types.ts, packages/react-components/react-table/src/hooks/useSelection.test.ts, packages/react-components/react-table/src/hooks/useSelection.ts, packages/react-components/react-table/src/hooks/useSort.test.ts, packages/react-components/react-table/src/hooks/useSort.ts, packages/react-components/react-table/src/hooks/useTable.ts, packages/react-components/react-table/src/index.ts, packages/react-components/react-table/src/stories/Table/MultipleSelect.stories.tsx, packages/react-components/react-table/src/stories/Table/MultipleSelectControlled.stories.tsx, packages/react-components/react-table/src/stories/Table/SingleSelect.stories.tsx, packages/react-components/react-table/src/stories/Table/SingleSelectControlled.stories.tsx, packages/react-components/react-table/src/stories/Table/SortControlled.stories.tsx, packages/react-components/react-table/src/stories/Table/index.stories.tsx
`useTable` hook now supports autoncontrolling sort and selection states
`useTable` is completely uncontrolled
`useTable` can be controlled and uncontrolled, added extra stories to that effect
Addresses #24226
=> feat: autocontrolled `useTable` hook

change/@fluentui-react-dialog-edfb588b-4236-4b7d-bb43-cc2ce8233ed3.json, packages/react-components/react-dialog/src/components/DialogActions/useDialogActionsStyles.ts, packages/react-components/react-dialog/src/components/DialogBody/useDialogBodyStyles.ts, packages/react-components/react-dialog/src/components/DialogTitle/useDialogTitleStyles.ts, packages/react-components/react-dialog/src/utils/index.ts, packages/react-components/react-dialog/src/utils/localShorthands.ts
There's a local file called `localShorthands` to provide `gridArea` shorthand that was previously unavailable by griffel
Griffel now provides `gridArea` shorthand, use it instead.
=> chore(react-dialog): remove localShorthands in favor of griffel shorthands

.github/workflows/screener-build.yml, .github/workflows/screener-run.yml
Fixes error from PR #24694 from downloading artifact from wrong workflow.
=> Fix artifact error

change/@fluentui-react-portal-compat-41d872da-79ea-43a1-b05e-1b14ac071531.json, change/@fluentui-react-tabster-9c99ffaf-f241-4958-8747-b139e37e838e.json, packages/react-components/react-portal-compat/bundle-size/PortalCompat.fixture.js, packages/react-components/react-portal-compat/cypress.config.ts, packages/react-components/react-portal-compat/e2e/PortalCompat.e2e.tsx, packages/react-components/react-portal-compat/e2e/tsconfig.json, packages/react-components/react-portal-compat/package.json, packages/react-components/react-portal-compat/src/PortalCompatProvider.test.tsx, packages/react-components/react-portal-compat/src/PortalCompatProvider.tsx, packages/react-components/react-tabster/etc/react-tabster.api.md, packages/react-components/react-tabster/src/focus/focusVisiblePolyfill.ts, packages/react-components/react-tabster/src/focus/index.ts, packages/react-components/react-tabster/src/index.ts
`@fluentui/react-portal-compat` now takes a dependency on `@fluentui/react-tabster` to apply the `focus-vislble` ponyfill. Also setup e2e tests for the portal compat package to test that the ponyfill is correctly applied.
Portal compat will not apply v9 focus outline styles
Portal compat will apply v9 focus outline styles
Fixes #24411
=> fix: Portal compat should apply `focus-visible` ponyfill

change/@fluentui-react-charting-d686895a-39e2-4755-a198-862dec13351f.json, packages/react-charting/src/components/Legends/Legends.styles.ts, packages/react-charting/src/components/Legends/__snapshots__/Legends.test.tsx.snap
Greyed out legend keys text don't match expected contrast ratio of 4.5
Greyed out legend keys text now have a contrast ratio of 4.6
=> Fix greyed out legend key contrast ratio

change/@fluentui-react-a2077894-5d42-47ef-9b1a-5c88edd0eccd.json, packages/react/src/components/Slider/useSlider.ts
When you click on a <Slider />, and the component unmounts while the mouse button is down, and you then move the mosue while the mouse button is still down, there is a null-ref in useSlider()
There is no null-ref errror, as the window `mouseMove` events are cleaned up on unmount
Fixes #24727
=> Fix null ref in use slider

change/@fluentui-react-aria-4fd3fe1f-3f59-48b1-acab-2e459a62c03d.json, packages/react-components/react-aria/etc/react-aria.api.md, packages/react-components/react-aria/src/hooks/useARIAButton/types.ts, packages/react-components/react-aria/src/index.ts
Adds 2 helper types to assist DOM element handling on scenarios that is required to know the element type. `ARIAButtonElement` and `ARIAButtonElementIntersection`. 
should be used on references definition for example.It's almost equivalent to: `HTMLButtonElement | HTMLAnchorElement | HTMLDivElement`
```ts
function useComponent(props, ref: React.Ref<ARIAButtonElement>) {}
```
should be used on cases that narrowing down the type is required, for example, an even handler declaration. It's almost equivalent to: `HTMLButtonElement & HTMLAnchorElement & HTMLDivElement`
```ts
const handleClick = (event: React.MouseEvent<ARIAButtonElementIntersection>) => {
event.currentTarget // HTMLButtonElement & HTMLAnchorElement & HTMLDivElement
}
```
=> feat: add helper types to assist DOM element handling

change/@fluentui-react-dialog-beceb7aa-8aa2-4e44-9992-df048001834d.json, packages/react-components/react-dialog/Spec.md, packages/react-components/react-dialog/e2e/DialogTitle.e2e.tsx, packages/react-components/react-dialog/e2e/selectors.ts, packages/react-components/react-dialog/etc/react-dialog.api.md, packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurfaceStyles.ts, packages/react-components/react-dialog/src/components/DialogTitle/DialogTitle.tsx, packages/react-components/react-dialog/src/components/DialogTitle/DialogTitle.types.ts, packages/react-components/react-dialog/src/components/DialogTitle/renderDialogTitle.tsx, packages/react-components/react-dialog/src/components/DialogTitle/useDialogTitle.tsx, packages/react-components/react-dialog/src/components/DialogTitle/useDialogTitleStyles.ts, packages/react-components/react-dialog/src/contexts/constants.ts, packages/react-components/react-dialog/src/stories/Dialog/DialogNoFocusableElement.stories.tsx, packages/react-components/react-dialog/src/stories/DialogTitle/DialogTitleCustomAction.md, packages/react-components/react-dialog/src/stories/DialogTitle/DialogTitleCustomAction.stories.tsx, packages/react-components/react-dialog/src/stories/DialogTitle/DialogTitleDefault.stories.tsx, packages/react-components/react-dialog/src/stories/DialogTitle/DialogTitleNoAction.md, packages/react-components/react-dialog/src/stories/DialogTitle/DialogTitleNoAction.stories.tsx, packages/react-components/react-dialog/src/stories/DialogTitle/index.stories.tsx
`DialogTitle` supports a `closeButton` slot which is used to render a button to close the dialog whenever a `Dialog` is `non-modal`.
There are cases where a custom action is desirable in the dialog title instead of just a close button.
1. Replaces `closeButton` slot for a more generic `action` slot
2. by default `action` slot will render a close button if the dialog is `non-modal`, to ensure previous behaviour
=> feat(react-dialog): replace `closeButton` to a more generic `action` slot

apps/public-docsite/src/root.tsx, apps/public-docsite/src/styles/_base.scss, change/@fluentui-public-docsite-setup-c9310141-1481-42db-9b89-3a3649aca0d9.json, packages/public-docsite-setup/index.html
I mistakenly changed the skipToMain functionality to affect the 'back to top button', which broke the former and didn't fix the latter. 
I returned the skipToMain functionality to how it was (it was not broken), and fixed the display: none selection that we were using to hide the 'back to top' button.
Fixes #24610
=> return skipToMain functionality and hide back to top button

apps/public-docsite/src/pages/HomePage/HomePage.base.tsx
Addresses internal bug 14973
Actual Result:
Heading structure is defined incorrectly in the page, `<h2>` heading is defined for the main page heading.
As of now, "Fluent UI" is defined  H2 heading ,No H1 heading is defined on this page.
Expected Result:
Heading structure should define correctly in the page, `<h1>` heading is defined for the main page heading.
So "fluent UI" should be define in H1 as the main heading of the page.
=> change homepage title to h1 instead of h2

change/@fluentui-react-charting-dfdb7954-3e89-4f57-8428-742aa68c065a.json, package.json, packages/react-charting/jest.config.js, packages/react-charting/package.json, packages/react-charting/src/components/AreaChart/AreaChart.base.tsx, packages/react-charting/src/components/AreaChart/AreaChart.test.tsx, packages/react-charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap, packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx, packages/react-charting/src/components/DonutChart/DonutChart.test.tsx, packages/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap, packages/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.test.tsx, packages/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap, packages/react-charting/src/components/HeatMapChart/HeatMapChart.test.tsx, packages/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap, packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.test.tsx, packages/react-charting/src/components/HorizontalBarChart/__snapshots__/HorizontalBarChart.test.tsx.snap, packages/react-charting/src/components/LineChart/LineChart.test.tsx, packages/react-charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap, packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.test.tsx, packages/react-charting/src/components/StackedBarChart/StackedBarChart.test.tsx, packages/react-charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap, packages/react-charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap, packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.test.tsx, packages/react-charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap, packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.test.tsx, packages/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChart.test.tsx.snap, yarn.lock
Tests for hover states do not exist
Tests if hovering over the charts renders a callout correctly
=> Add tests for hover states

change/@fluentui-react-link-ace1a119-44f0-4cac-96a5-b757d4abee30.json, packages/react-components/react-link/src/components/Link/useLinkStyles.ts
`Link` uses `border-bottom` styles for its underline.
`Link` uses `text-decoration: underline` styles for its underline, which is more inline with most implementations out there.
Fixes #24729
=> fix: Replacing bottom border styles with text decoration underline in Link

change/@fluentui-react-combobox-7bb9e1fd-dd15-4dd6-bdff-951b259e85db.json, packages/react-components/react-combobox/src/components/Combobox/__snapshots__/Combobox.test.tsx.snap, packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx, packages/react-components/react-combobox/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/react-components/react-combobox/src/components/Dropdown/useDropdown.tsx, packages/react-components/react-combobox/src/utils/useTriggerListboxSlots.ts
Resolves an item on the design review, #23926
Calculates the trigger width when the popup is opened, and sets a width style to the listbox slot.
=> fix: react-combobox listbox popup width matches trigger width

apps/vr-tests-react-components/src/stories/Button.stories.tsx, change/@fluentui-react-button-2bff9178-dae7-48c6-9b2e-4e5effb0d484.json, packages/react-components/react-button/src/components/Button/useButtonStyles.ts, packages/react-components/react-button/src/components/CompoundButton/useCompoundButtonStyles.ts, packages/react-components/react-button/src/components/SplitButton/useSplitButtonStyles.ts, packages/react-components/react-button/src/components/ToggleButton/useToggleButtonStyles.ts
This PR brings all `Button` components in line with the latest changes to token usage that have been made in the design specs. It also updates `Button` visual regression tests so they use a proper icon instead of an `X`.
=> chore: Cleaning up tokens in Button components so they better adhere to the design spec

change/@fluentui-react-8abf788f-1d0f-484c-a725-1d2fa5981f8f.json, packages/react/src/components/DetailsList/DetailsList.base.tsx, packages/react/src/components/DetailsList/DetailsRowFields.tsx, packages/react/src/components/DetailsList/__snapshots__/DetailsColumn.test.tsx.snap, packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap, packages/react/src/components/DetailsList/__snapshots__/DetailsRow.test.tsx.snap, packages/react/src/components/DetailsList/__snapshots__/ShimmeredDetailsList.test.tsx.snap
Fixes [15360](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15360)
Related to the Calendar/Datepicker fix (#20324), Talkback (more or less correctly) doesn't allow interaction with controls inside of elements with `readonly`, so the selection checkboxes and any author-provided nested form inputs in DetailsList were not interactive.
=> fix: remove readonly from DetailsList

change/@fluentui-react-components-5596cfa5-301f-4b16-81ef-f2d953a7f397.json, change/@fluentui-react-table-563b3e0b-f140-4bac-bcae-d4974090994d.json, packages/react-components/react-components/etc/react-components.unstable.api.md, packages/react-components/react-components/src/unstable/index.ts, packages/react-components/react-table/etc/react-table.api.md, packages/react-components/react-table/src/TableCellLayout.ts, packages/react-components/react-table/src/TableCellPrimaryLayout.ts, packages/react-components/react-table/src/components/TableCellLayout/TableCellLayout.test.tsx, packages/react-components/react-table/src/components/TableCellLayout/TableCellLayout.tsx, packages/react-components/react-table/src/components/TableCellLayout/TableCellLayout.types.ts, packages/react-components/react-table/src/components/TableCellLayout/__snapshots__/TableCellLayout.test.tsx.snap, packages/react-components/react-table/src/components/TableCellLayout/index.ts, packages/react-components/react-table/src/components/TableCellLayout/renderTableCellLayout.tsx, packages/react-components/react-table/src/components/TableCellLayout/useTableCellLayout.ts, packages/react-components/react-table/src/components/TableCellLayout/useTableCellLayoutStyles.ts, packages/react-components/react-table/src/components/TableCellPrimaryLayout/TableCellPrimaryLayout.test.tsx, packages/react-components/react-table/src/components/TableCellPrimaryLayout/TableCellPrimaryLayout.tsx, packages/react-components/react-table/src/components/TableCellPrimaryLayout/TableCellPrimaryLayout.types.ts, packages/react-components/react-table/src/components/TableCellPrimaryLayout/__snapshots__/TableCellPrimaryLayout.test.tsx.snap, packages/react-components/react-table/src/components/TableCellPrimaryLayout/index.ts, packages/react-components/react-table/src/components/TableCellPrimaryLayout/renderTableCellPrimaryLayout.tsx, packages/react-components/react-table/src/components/TableCellPrimaryLayout/useTableCellPrimaryLayout.ts, packages/react-components/react-table/src/components/TableCellPrimaryLayout/useTableCellPrimaryLayoutStyles.ts, packages/react-components/react-table/src/index.ts
Implements table cell layout components from #24762 to break up the aforementioned PR
=> feat: Implement table cell layout components

package.json
after trying to recreate the original hoisting problem, I was unable to repro nohoist making any difference. I am confident that the webpack alias is necessary though, so those can stay in, as well as the syncpack updates.
=> remove unnecessary nohoist for react 18 tests

change/@fluentui-react-components-27ab0583-ddc1-41ff-abe2-0ab8fe34d69b.json, packages/react-components/react-components/etc/react-components.unstable.api.md, packages/react-components/react-components/src/unstable/index.ts
This PR adds missing exports from AvatarGroup to `@fluentui/react-components/unstable`.
Fixes #24767
=> feat(react-components): Adding missing AvatarGroup exports

scripts/create-package/plop-templates-react/package.json.hbs, scripts/create-package/plopfile.ts
Newly created packages are version `9.0.0-alpha.0` by default, but disallow `prerelease` change types. This makes it so the initial release will likely be `patch` or `minor` by default, which will end up publishing a non-alpha/beta release.
Update package template beachball config to allow only `prerelease` changes by default
This came up when publishing the react-field package: https://github.com/microsoft/fluentui/pull/24235#discussion_r966517189
=> fix: Update package template beachball config to allow only 'prerelease' changes by default

.github/workflows/issues.yml
- issue is created for particular project but manual work needs to be done to properly assign project label
- based on picked project, we will automatically add proper label. 
↓↓↓
> **Note:** Adding to unified board will be done in separate PR after internal team discussion
Follows https://github.com/microsoft/fluentui/pull/22337
=> ci(github): add GH Action to add issue labels based on new GH issue template

change/@fluentui-react-charting-bb27a991-70f3-49c3-9940-6ff73c090c66.json, packages/react-charting/src/components/HeatMapChart/HeatMapChart.styles.ts, packages/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap
Heatmap chart data values in less contrasted boxes don't pass accessibility
Heatmap chart displays values in semi-bold to help less contrasted boxes
=> Fix value font-weight inside heatmap chart

apps/public-docsite-v9/src/shims/ThemeShim/v9ThemeShim.ts, change/@fluentui-react-theme-49e830f4-b491-4b83-a28a-2f0df72b97d7.json, change/@fluentui-react-theme-sass-fcd4b7d2-32f5-494a-9bb6-4f79893cd6cf.json, packages/react-components/react-combobox/src/stories/Combobox/ComboboxAppearance.stories.tsx, packages/react-components/react-input/src/stories/Input/InputAppearance.stories.tsx, packages/react-components/react-select/src/stories/Select/SelectAppearance.stories.tsx, packages/react-components/react-spinbutton/src/stories/SpinButton/SpinButtonAppearance.stories.tsx, packages/react-components/react-textarea/src/stories/Textarea/TextareaAppearance.stories.tsx, packages/react-components/react-theme-sass/sass/colorTokens.scss, packages/react-components/react-theme/etc/react-theme.api.md, packages/react-components/react-theme/src/alias/darkColor.ts, packages/react-components/react-theme/src/alias/highContrastColor.ts, packages/react-components/react-theme/src/alias/lightColor.ts, packages/react-components/react-theme/src/alias/teamsDarkColor.ts, packages/react-components/react-theme/src/tokens.ts, packages/react-components/react-theme/src/types.ts
"Appearance" stories and one VR test use a foreground color for backgrounds. This was done to achieve sufficient color contrast to meet WCAG guidance.
All instances now use a background color and still meet WCAG guidance.
Fixes #24328
=> update background color for appearance stories and vr tests

change/@fluentui-react-button-05205cf2-d4cc-414b-b0e7-dfa4d0da785a.json, packages/react-components/react-button/src/components/MenuButton/useMenuButton.tsx
While open `MenuButtons` have `aria-expanded` set to `true`, collapsed `MenuButtons` do not have `aria-expanded` set to `false`, and instead have it `undefined`. This can create some problems regarding screen reader access where users of screen readers do not realize `MenuButtons` have collapsed menus.
Collapsed `MenuButtons` now have `aria-expanded` set to `false`, correctly indicating this information for all screen readers.
Fixes #21409
=> fix: Adding 'aria-expanded=false' to collapsed MenuButtons

change/@fluentui-react-dialog-7e8df864-5916-4a65-a8e8-10c99bfe06c3.json, change/@fluentui-react-menu-6654ec9f-d860-48a1-be2c-8e8a6fd74f2d.json, change/@fluentui-react-popover-2678e585-4053-46ec-8b8c-5d73a8978dde.json, packages/react-components/react-dialog/e2e/Dialog.e2e.tsx, packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurface.ts, packages/react-components/react-menu/src/components/MenuPopover/useMenuPopover.ts, packages/react-components/react-popover/package.json, packages/react-components/react-popover/src/components/PopoverTrigger/usePopoverTrigger.ts
Multiple components might listen to `Escape`.
Those components might have their own `Escape` key dismiss behaviour. At the moment `Escape` key pressing will dismiss `Menu`, `Popover` and `Dialog`.
When interacting with multiple layout components that have behaviours associated with `Escape` pressing, conflicts might happen.
E,g: a `Menu` or a `Popover` inside a `Dialog`
```tsx
const MenuInsideDialogExample = () => {
return (
<Dialog>
<DialogTrigger>
<Button>Open dialog</Button>
</DialogTrigger>
<DialogSurface>
<Menu>
<MenuTrigger>
<Button>Toggle menu</Button>
</MenuTrigger>
<MenuPopover>
<MenuList>
<MenuItem>Item</MenuItem>
</MenuList>
</MenuPopover>
</Menu>
<DialogActions>
<DialogTrigger>
<Button>
Close
</Button>
</DialogTrigger>
</DialogActions>
</DialogSurface>
</Dialog>,
);
}
```
In …
=> bugfix: `Dialog`, `MenuPopover` and `PopoverTrigger` stops propagation on Escape keydown 

change/@fluentui-react-table-c1964582-3ba3-4333-a5b2-7ff17480683a.json, packages/react-components/react-table/etc/react-table.api.md, packages/react-components/react-table/package.json, packages/react-components/react-table/src/components/Table/useTableContextValues.ts, packages/react-components/react-table/src/components/TableBody/useTableBody.ts, packages/react-components/react-table/src/components/TableCell/useTableCell.ts, packages/react-components/react-table/src/components/TableHeader/useTableHeader.ts, packages/react-components/react-table/src/components/TableHeaderCell/useTableHeaderCell.tsx, packages/react-components/react-table/src/components/TableRow/useTableRow.ts, packages/react-components/react-table/src/contexts/tableContext.ts
The current usage of context selector doesn't bring any value. Revert to native react context instead
Fixes #
=> refactor: Stop using context selector for Table primitives

packages/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap
react-charting `test` is broken and blocks release of v9
- updated snapshots so master can be used to release v9
- Im not sure what's going on, this was introduced in following PR where pipelines passed https://github.com/microsoft/fluentui/pull/24390
=> test(react-charting): update obsolete snapshots

change/@fluentui-react-ab3b8086-f406-44cd-bef5-7782fdef2863.json, packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap, packages/react/src/components/GroupedList/GroupHeader.base.tsx
Since the most-recent changes to improve group selection have gone in, there is a bug where clicking the button to toggle group state is propagating to select the whole group.
This PR prevents a click on the toggle button from propagating to select the whole group.
=> Prevent group toggling from selecting the whole group

change/@fluentui-react-dialog-0114f836-5a96-4d93-bc7b-5da966142ed8.json, packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurfaceStyles.ts
=> bugfix(react-dialog): Adds color style to DialogSurface

change/@fluentui-react-components-7af2adef-a1c8-4aed-b2b3-0cdb7c48f10c.json, packages/react-components/react-components/etc/react-components.unstable.api.md, packages/react-components/react-components/src/unstable/index.ts
=> fix: export `tableCellActionsClassNames` from unstable

packages/fluentui/CHANGELOG.md, packages/fluentui/react-northstar/src/themes/teams/components/Dropdown/dropdownStyles.ts
When overriding :active or :hover state it mutates the style object. Style override of single Dropdown stay permanent, and the style is then applied to all unrelated Dropdowns.
Styling of one Dropdown does not leak into other Dropdowns.
=> [Northstar][Dropdown] Fix styling mutation when merging themes

apps/vr-tests-react-components/src/stories/Table.stories.tsx, change/@fluentui-react-table-d3a482b6-52de-46b3-9dee-14bff160bbe6.json, packages/react-components/react-table/etc/react-table.api.md, packages/react-components/react-table/src/components/TableCellActions/TableCellActions.types.ts, packages/react-components/react-table/src/components/TableCellActions/useTableCellActions.ts, packages/react-components/react-table/src/components/TableCellActions/useTableCellActionsStyles.ts, packages/react-components/react-table/src/components/TableRow/useTableRowStyles.ts
Adds a `visible` prop to `TableCellActions` to make it easier for users to keep the actions visible instead of manually adding a css classname.
Fixes #
=> feat: Adds `visible` prop to `TableCellActions`

change/@fluentui-react-ea32524a-6ed8-4a2c-bbda-87c6389f2dd1.json, packages/react/etc/react.api.md, packages/react/src/components/TeachingBubble/TeachingBubble.types.ts
In React 18 we need to explicitly define if a component accepts children. 
#22592
=> fix: Add explicit children prop to TeachingBubble to support React 18

change/@fluentui-react-divider-f95da959-6db2-4b33-9ec7-d3a4e44656c0.json, packages/react-components/react-divider/src/components/Divider/useDivider.ts
Customer wanted to use divider as a visual wrapper around a button. Due to role="separator", the button was marked as role="presentational" so it was ignored by narrator.
Moving props to be able to override the default values will give users escape hatches when they need to customize those values (custom orientation, custom labeledby, custom role)
=> Divider - allow default prop override

apps/vr-tests-react-components/screener.config.js, apps/vr-tests/screener.config.js, gulpfile.ts, scripts/gulp/tasks/screener.ts, scripts/gulp/tasks/vr-build.ts, scripts/gulp/tasks/vr-test.ts, scripts/screener/screener.config.js, scripts/screener/screener.states.ts, scripts/screener/screener.types.ts
Screener is now separated into two workflows for secrets encapsulation, the code to trigger the screener run is actually run on the master branch.
The current northstar screener states are generated directly before running, this means that any changes to N* screener tests in a PR will never result in updated screenshots
Update the `screener:build` gulp command to write all states to a json file and updeates the `screener:runner` gulp tasks to read states from the json file as a result of the build.
Since the entire `docs/dist` artifact is uploaded, there should be no changes needed for the pipeline
Fixes #24842
=> chore: Northstar screener should read from screenerStates.json

change/@fluentui-react-dialog-d69ce942-a1c5-4bc6-83b5-c91a69d5c2b5.json, packages/react-components/react-dialog/config/api-extractor.json, packages/react-components/react-dialog/config/api-extractor.local.json, packages/react-components/react-dialog/etc/react-dialog.api.md, packages/react-components/react-dialog/package.json, packages/react-components/react-dialog/src/DialogContent.ts, packages/react-components/react-dialog/src/components/DialogContent/DialogContent.test.tsx, packages/react-components/react-dialog/src/components/DialogContent/DialogContent.tsx, packages/react-components/react-dialog/src/components/DialogContent/DialogContent.types.ts, packages/react-components/react-dialog/src/components/DialogContent/__snapshots__/DialogContent.test.tsx.snap, packages/react-components/react-dialog/src/components/DialogContent/index.ts, packages/react-components/react-dialog/src/components/DialogContent/renderDialogContent.tsx, packages/react-components/react-dialog/src/components/DialogContent/useDialogContent.ts, packages/react-components/react-dialog/src/components/DialogContent/useDialogContentStyles.ts, packages/react-components/react-dialog/src/components/DialogSurface/DialogSurface.types.ts, packages/react-components/react-dialog/src/index.ts, packages/react-components/react-dialog/tsconfig.lib.json
1. Scaffolds `DialogContent` component with `yarn create-component`
2. bugfix: exports `DialogSurfaceElement` to ensure new API extractor validation.
=> chore(react-dialog): scaffold DialogContent component

.github/workflows/create-milestone.yml
create-milestone GHA is failing
it works again
=> ci: make create-milestone work by adding missing permissions

change/@fluentui-react-charting-3df6df5e-105a-42a8-813e-82c2bb4f5eef.json, packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
Set minimum width of 1% for multi stacked horizontal bar chart elements
Fixes #
=> Set minimum width of 1% for multi stacked horizontal bar chart

.github/workflows/docsite-publish-ghpages.yml
Current Storybook docsite is deployed to Chromatic which has an initial load time (uncached) of around 8 - 10 seconds:
This PR adds a new pipeline which deploys the Storybook docsite to Github Pages through a pipeline artifact. The initial load time (uncached) of the GH pages version is around 1 second.
=> feat(cicd): update docsite publish workflow to publish to github pages

.github/workflows/docsite-publish-chromatic.yml, .github/workflows/docsite-publish-ghpages.yml
Docsite publish workflows have the same name and it creates confusion.
Different names for each docsite publish workflow.
=> fix(cicd): rename docsite deployment github actions to have unique names

change/@fluentui-react-dialog-4c5ea8d4-22d0-4d9e-a2b6-c4730f2760c7.json, change/@fluentui-react-tooltip-cd8ed1f4-6139-4f4e-b524-3d882bce4cac.json, packages/react-components/react-dialog/e2e/Dialog.e2e.tsx, packages/react-components/react-tooltip/package.json, packages/react-components/react-tooltip/src/components/Tooltip/useTooltip.tsx
Currently  pressing `Escape` key to dismiss a `Tooltip`, will propagate a `Escape` keydown event that might trigger dismiss in more than just the `Tooltip` itself. see https://github.com/microsoft/fluentui/pull/24750
1. Stops propagating `Escape` keydown to ensure only `Tooltip` is dismissed.
2. Captures keydown event on target document, to ensure `Tooltip` escape behaviour is the first thing to be executed.
3. Adds Dialog e2e test scenario to ensure this behaviour
=> bugfix(react-tooltip): stops propagation on Escape keydown

scripts/gulp/tasks/vr-test.ts
Fixes a bug from #24865 where screener states are generated even if the artifact does not exist
=> fix: Only generate northstar screener states if the artifact is present

scripts/gulp/tasks/vr-test.ts, scripts/screener/screener.runner.ts
Follow up to #24867 , the value for the environement variable is either 'true' or 'false'
=> fix: check for string value IS_ARTIFACT_PRESENT

tsconfig.base.json
Alias for unstable was missing, which caused webpack warnings when I used Select in ui-builder app.
=> Add react-components/unstable to tsconfig aliases

azure-pipelines.release-vnext-nightly.yml
It seems that some kind of change happened with our user agents and github user is no longer set by default. So we have to do this manually
Nightly release pipeline does not set github user
Nightly release pipeline sets github user
Fixes #
=> fix: Set github user in nightly release pipeline

change/@fluentui-react-b4e5742f-312c-4c83-93ad-7da95b6de7d9.json, packages/react/etc/react.api.md, packages/react/src/components/Modal/Modal.base.tsx, packages/react/src/components/Modal/Modal.types.ts
When using the Modal component (or Dialog) the popup component that is being used under the hood cannot be configured. In cases where were need to have a different behavior for the `onRestoreFocus` method, we have no way to configure it while using either the Dialog or Modal components.
Adding the `IPopupProps` as a property of the Modal component and then passing it to the popup being used under the hood, we provide more flexibility on that popup's configuration.
=> Allowing Popup configuration on Modal component

change/@fluentui-react-components-2746a815-4cae-4351-a6fe-ad932145c33b.json, change/@fluentui-react-spinbutton-49e629e4-b86e-4b48-8b72-25cd7f0b719a.json, packages/react-components/react-components/.storybook/preview.js, packages/react-components/react-components/src/Concepts/Accessibility/AccessibleComponents.stories.mdx, packages/react-components/react-spinbutton/src/stories/SpinButton/SpinButtonAccessibility.stories.mdx, packages/react-components/react-spinbutton/src/stories/SpinButton/index.stories.tsx
This moves the SpinButton accessibility spec page to Concepts/Developer/Accessibility/Components. The goal is to have an a11y spec per component. There will also be a separate, more concise a11y author implementation section next to best practices.
There are some unrelated whitespace/formatting updates to the spinbutton a11y doc from running prettier.
=> chore: a11y docs structure update

package.json, scripts/beachball/config.test.ts, scripts/beachball/shared.config.ts, yarn.lock
Runs the generator in both v8 and v9 releases
Fixes #24207
=> chore: run dependency mismatch generator in release pipeline

tools/generators/dependency-mismatch/index.spec.ts, tools/generators/dependency-mismatch/index.ts, workspace.json
Expands the scope of the dependency mismatch generator to align dependencies in the repo even if they are not v9.
The exception here is northstar/v0, since it has a dependency on a former major of a v8 dependency
Partially addresses: #23147
=> chore: Expand scope of dependency mismatch generator

apps/stress-test/package.json, apps/stress-test/src/shared/css/RandomSelector.ts, apps/stress-test/src/shared/react/ReactSelectorTree.tsx, apps/stress-test/src/shared/react/ReactTree.tsx, apps/stress-test/src/shared/react/types.ts, apps/stress-test/src/shared/tree/RandomSelectorTreeNode.ts, apps/stress-test/src/shared/tree/RandomTree.ts, apps/stress-test/src/shared/utils/random.ts, apps/stress-test/src/shared/utils/testOptions.ts, apps/stress-test/src/shared/utils/testUtils.ts, apps/stress-test/src/shared/vanilla/VanillaSelectorTree.ts, apps/stress-test/src/shared/vanilla/VanillaTree.ts, apps/stress-test/src/shared/vanilla/types.ts, apps/stress-test/src/shared/wc/WCSelectorTree.ts, apps/stress-test/src/shared/wc/WCTree.ts, yarn.lock
Test cases are simple benchmarks.
This PR adds code for generating and rendering deep and broad DOM trees allowing us to better simulate a real application with a benchmarking tool.
Note: tree generation is "random" but done with a seedable RNG for repeatable results.
The core of this is `RandomTree` a class for generating trees with random breadth and depth. This class is generic with an API for generating specific trees. This PR adds a "selector tree" which builds of `RandomTree` to generate a tree with many selectors (CSS classes, data attributes, etc) as well as generate the selectors themselves.
`RandomTree` is UI library agnostic and can be used to generate trees for React, Web Components, vanilla DOM or any other library we care to investigate.
Building off `RandomTree` this PR …
=> Stress Test: add random tree

change/@fluentui-react-menu-5eeb5c9b-a02e-4d75-aeee-9e9fd45a5aac.json, packages/react-components/react-menu/e2e/Menu.e2e.tsx, packages/react-components/react-menu/src/components/Menu/useMenu.tsx
Regression from the refactoring in PR https://github.com/microsoft/fluentui/pull/24562, Menu no longer respects the `openOnHover` prop.
Use the `openOnHover` prop in Menu again. It defaults to `isSubmenu` but can be overridden.
* Fixes #24841
=> fix: Make Menu openOnHover prop work again

package.json, yarn.lock
Follow up of #24881 which updated beachball to a version that required ^0.27.0. The API broke multiple times between our current version of beachball and the one upgraded to.
Fixes beachball in our repo
=> chore: Bump workspace-tools to 0.27.0

change/@fluentui-react-overflow-3f2dd77e-a705-42d4-a878-308d7dd21c53.json, packages/react-components/react-overflow/config/api-extractor.json, packages/react-components/react-overflow/config/api-extractor.local.json, packages/react-components/react-overflow/package.json, packages/react-components/react-overflow/tsconfig.lib.json
Migrates `react-overflow` converged package to new DX by using the migration command:
```bash
yarn nx workspace-generator migrate-converged-pkg --name='@fluentui/react-overflow'
```
=> chore(react-overflow): update package scaffold

change/@fluentui-react-popover-37cc067c-8474-4cca-b718-d6b06ea02f96.json, packages/react-components/react-popover/config/api-extractor.json, packages/react-components/react-popover/config/api-extractor.local.json, packages/react-components/react-popover/package.json, packages/react-components/react-popover/tsconfig.lib.json
Migrates `react-popover` converged package to new DX by using the migration command:
```bash
yarn nx workspace-generator migrate-converged-pkg --name='@fluentui/react-popover'
```
=> chore(react-popover): update package scaffold

change/@fluentui-react-tooltip-851de7be-64ba-495d-af5c-88cc34d5e3e4.json, packages/react-components/react-tooltip/config/api-extractor.json, packages/react-components/react-tooltip/config/api-extractor.local.json, packages/react-components/react-tooltip/package.json, packages/react-components/react-tooltip/tsconfig.lib.json
Migrates `react-tooltip` converged package to new DX by using the migration command:
```bash
yarn nx workspace-generator migrate-converged-pkg --name='@fluentui/react-tooltip'
```
=> chore(react-tooltip): update package scaffold

package.json, scripts/github/pullRequests.ts, scripts/package.json, scripts/update-release-notes/index.ts, scripts/update-release-notes/pullRequests.ts, scripts/update-release-notes/releases.ts, scripts/update-release-notes/types.ts, yarn.lock
we use v 16.  Danger uses v18
we use v18
**NOTE:**
Lot of things changed since v16 including types... those types moves are not very well documented, so I did the best I could. If we are no 100% confident we can drop this and use v16.
- v17 breaking changes (go to the bottom to see type related notes) https://github.com/octokit/rest.js/releases/tag/v17.0.0
=> chore: bump @octokit/rest to v18

.github/triage-bot.config.json, .github/workflows/issues.yml, package.json, scripts/triage-bot/README.md, scripts/triage-bot/index.js, scripts/triage-bot/triage-bot.js, scripts/triage-bot/triage-bot.schema.json, scripts/triage-bot/triage-bot.spec.ts, scripts/triage-bot/tsconfig.json, scripts/triage-bot/types.ts, scripts/tsconfig.json, scripts/tsconfig.scripts.json, yarn.lock
we use existing github action which doesn't work and have very limited use case coverage
- we have foundation for fully customized triage-bot functionalities
- configuration provides best possible DX by leveraging json schema
- ~bump to @octokit/rest v18 ( introduces lot of changes in type space - we can remove that part from this PR )~ https://github.com/microsoft/fluentui/pull/24919
[Learn more 💡](https://github.com/microsoft/fluentui/pull/24911/files?short_path=1a288fb#diff-1a288fb5e194eed06b979b13b572880829689c431b0cb4c8cc911e4c4dc8aeb1)
Follows https://github.com/microsoft/fluentui/pull/24788
Implements https://github.com/microsoft/fluentui/pull/24817 (1. project label assignment)
=> feat(scripts): implement triage-bot module

change/@fluentui-react-avatar-e4aa8633-f04d-4761-9b6f-d7d78497c1c6.json, packages/react-components/react-avatar/etc/react-avatar.api.md, packages/react-components/react-avatar/src/components/Avatar/Avatar.test.tsx, packages/react-components/react-avatar/src/components/Avatar/Avatar.types.ts, packages/react-components/react-avatar/src/components/Avatar/renderAvatar.tsx, packages/react-components/react-avatar/src/components/Avatar/useAvatar.tsx, packages/react-components/react-avatar/src/components/Avatar/useAvatarStyles.ts, packages/react-components/react-avatar/src/stories/Avatar/AvatarActive.stories.tsx
The state of Avatar's `active` prop is conveyed visually via a highlight ring, but not conveyed to accessibility tools.
Append "active" or "inactive" to the aria label when the `active` prop is set. 
* When the Avatar is using the `aria-label` prop, simply append the string to it.
* If the Avatar needs to use `aria-labelledby`, then render a hidden span with the active label, and append the span's ID to `aria-labelledby`
There is no prop to control the strings yet; they are hardcoded for now. In the future, they will be able to be localized once we implement an i18n solution.
* Fixes #23128
=> feat: Avatar's aria label includes 'active' or 'inactive' when using the active prop

change/@fluentui-react-popover-66a51d32-93ef-481a-bef9-5595c8ef528a.json, packages/react-components/react-popover/Spec.md, packages/react-components/react-popover/e2e/Popover.e2e.tsx, packages/react-components/react-popover/src/components/PopoverSurface/PopoverSurface.test.tsx, packages/react-components/react-popover/src/components/PopoverSurface/__snapshots__/PopoverSurface.test.tsx.snap, packages/react-components/react-popover/src/components/PopoverSurface/usePopoverSurface.ts
Related to #21416
We do want to use a non-dialog role for the non-focus-trapping variant, but `complementary` isn't the best fit -- it refers specifically to content that is complementary to the main region, and on the same level as the main region in content hierarchy. That doesn't really apply to most popovers, so this PR updates it to the `group` role for the following reasons:
- Popovers may be nested, and `group` in particular enables that
- It's the lowest common accessible base role in that it is flexible in its use cases, and allows naming & exposes its bounds
- It is extremely flexible in allowed content (both in a strict spec sense, and in a general user expectation sense)
Other roles that were considered:
- `note`: it generally seems fine, but it would be weird to have nested …
=> fix: update non-focus-trap Popover role to be group

change/@fluentui-react-charting-5cb11ce8-3dd1-44a0-b5d6-86ab28f4e94c.json, packages/react-charting/src/components/TreeChart/TreeChart.base.tsx, packages/react-charting/src/components/TreeChart/TreeChart.styles.ts, packages/react-charting/src/components/TreeChart/TreeChart.types.ts, packages/react-charting/src/components/TreeChart/__snapshots__/TreeChart.test.tsx.snap, packages/react-examples/src/react-charting/TreeChart/TreeChart.ThreeLayer.Example.tsx
1. Parent node can only consist only of 2 lines of text.
2. Chart appears asymmetric in layout i.e space from left and right side is unequal.
1. For adding the third optional text line in parent node. that is added as a optional body text. When the body text is given then the rectangle is removed.
2.Secondly changes for alignment of the tree chart. 
a. So for this earlier the root node of the tree was made at screenwidth/3 which was creating the problem unequal padding from left and right.
I have fixed it by making the root node to be made at screenwidth/2.	
b. Second thing was earlier the rectangles were not symmetric in nature, as the rectangles were made using the x y coordinate, instead the x and y coordinates must be taken as centre coordinates, so that when layout width (rectangle …
=> Fixing Tree chart issues

change/@fluentui-react-2a9784d7-e2d3-40b7-93ae-e6b94ca7e231.json, packages/react/src/components/Dropdown/Dropdown.base.tsx, packages/react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
The v8 Dropdown uses keyboard focus to move between options when the popup is open, but still sets `aria-activedescendant` on the trigger. The attribute currently serves no use, since the trigger does not have focus when the popup is open.
Because `activedescendant` is based on an internally generated `id`, rendering custom options that do not receive the internal `id` results in an automated a11y test failure. This PR removes the attribute entirely to fix that issue and simplify the component.
=> fix: v8 Dropdown no longer sets incorrect and unnecessary aria-activedescendant

change/@fluentui-react-input-7cb0a348-cba2-4166-a8a0-9e173e884bd0.json, change/@fluentui-react-textarea-e5a09262-3430-4d49-b351-e92d50119fd4.json, packages/react-components/react-input/src/components/Input/Input.types.ts, packages/react-components/react-input/src/components/Input/useInput.ts, packages/react-components/react-input/src/stories/Input/InputAppearance.stories.tsx, packages/react-components/react-textarea/src/components/Textarea/Textarea.types.ts, packages/react-components/react-textarea/src/components/Textarea/useTextarea.ts, packages/react-components/react-textarea/src/components/Textarea/useTextareaStyles.ts, packages/react-components/react-textarea/src/stories/Textarea/TextareaAppearance.stories.tsx
This PR removes the filled with shadow appearance variants. This is due to the shadow appearances not being visible when used on a background that meets our contrast ratio guidelines. 
This is how our current docs show the variants:
To be able to see the shadow, a lighter background is required like this one:
This contradicts our guidelines on using a background with enough contrast ratio for accessibility requirements.
=> chore(react-input, react-textarea): Deprecating filled with shadow appearance variants

change/@fluentui-react-avatar-ad6cefba-a092-49d7-8cf6-bac42f97eb2b.json, packages/react-components/react-avatar/config/api-extractor.json, packages/react-components/react-avatar/config/api-extractor.local.json, packages/react-components/react-avatar/package.json, packages/react-components/react-avatar/tsconfig.json, packages/react-components/react-avatar/tsconfig.lib.json
Migrates the react-avatar package to use the new build experience introduced in #23369
=> chore: Migrate react-avatar to use new build

change/@fluentui-react-table-7bc36841-f472-43be-97c0-3885e7f42c1e.json, packages/react-components/react-table/config/api-extractor.json, packages/react-components/react-table/config/api-extractor.local.json, packages/react-components/react-table/package.json, packages/react-components/react-table/tsconfig.lib.json
Migrates the react-table package to use the new build experience introduced in #23369
=> chore: Migrate react-table to use new build

change/@fluentui-react-a2709ae0-6ff2-40b5-9f8c-31f7e6ac37a3.json, packages/react-examples/src/react/DetailsList/DetailsList.CustomFooter.Example.tsx, packages/react/src/components/DetailsList/DetailsList.base.tsx, packages/react/src/components/DetailsList/DetailsList.test.tsx
Fixes [15452](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15452)
We previously didn't add the footer to the rowcount calculation, which causes JAWS to not expose it with table navigation. This PR updates our `rowCount` calc to use the footer if provided, and fixes the custom footer example.
=> fix: add Detailslist footer to rowcount, fix example

change/@uifabric-styling-452e2438-8a31-4477-8900-e6fb2841f798.json, packages/styling/etc/styling.api.md, packages/styling/package.json, packages/styling/src/index.ts, packages/styling/src/styles/index.ts, packages/styling/src/styles/theme.ts
The initializeThemeInCustomizations is called from styling/index.ts which causes the index to be marked as a sideEffect in package.json and prevents tree shaking.  As well the styles/theme.ts already calls this method when that module is referenced.
Updates #24393
- Removed function call from index.ts
- Exported function from styles/index.ts
- Moved comment for function call to to styles/theme.ts
- Marked lib/styles/theme.js as the side effect in package.json
Before the method is called twice, after only once.
=> Removed the initializeThemeInCustomizations side effect from index

change/@fluentui-react-aa1768fc-3f4c-43dc-898f-1f1de8576f77.json, packages/react/etc/react.api.md, packages/react/package.json, packages/react/src/Viewport.ts, packages/react/src/index.ts, packages/react/src/utilities/decorators/withViewport.tsx
We removed decorators in v8 and are exporting those decorators in dedicated paths (like useResponsiveMode is now lib/ResponsiveMode). This change exposes useViewport using the same approach
Afterwards, this will be cherrypicked back to v7 to give users an upgrade path away from the old lib/Decorators
=> chore: export useViewport via lib/Viewport

change/@fluentui-react-charting-e0f28b46-4681-4bbd-8fff-5e32711add75.json, packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx, packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx
Fix combo line not rendering for vertical bar chart string x axis.
Fix x axis domain for data starting with non zero for vertical bar chart/ vertical stacked bar chart.
Fixes #
=> Fix combo line not rendering for vertical bar chart string x axis

packages/fluentui/docs/src/views/Introduction.tsx
Why not adding V9 link on the homepage of V0? 
-- Copy is just a placeholder --
=> add v9 link to homepage

change/@fluentui-react-aria-601b8c0d-d97a-4365-9dc5-41df68787f92.json, packages/react-components/react-aria/src/button/useARIAButtonProps.test.tsx, packages/react-components/react-aria/src/button/useARIAButtonProps.ts
```html
<Trigger>
<div tabIndex={undefined}>Custom trigger</div>
</Trigger>
```
```html
<Trigger>
<div tabIndex={undefined}>Custom trigger</div>
</Trigger>
```
=> chore(react-aria): user defined tabIndex should prevail

scripts/create-component/create-component.ts
- When creating a new component via the `create-component` script, an error will be thrown since it tries to run `build:local` which has been replaced by the `generate-api` script in #23369
- This PR fixes this issue by replacing `build:local` with `generate-api` when creating a new component with `create-component`.
=> fix(create-component): Replace build:local with new generate-api script

rfcs/shared/build-system/07-standard-package-structure-for-v9.md
- Updates **File Organization Convention for v9 Packages** RFC to reflect removal of [problematic ](https://github.com/microsoft/fluentui/issues/23976) `common/` folder and adds proposed replacement for it. Also provides a more detailed outline of how the `components/`, `utils/` and new `testing/` subfolders should be structured.
- Also adds an update to remove the `e2e/` subfolder in favor of collocating cypress tests with the implementation and unit/jest files.
[PREVIEW](https://github.com/microsoft/fluentui/pull/24543/files?short_path=aa0c69f#diff-aa0c69ffcf1e796ffc7b69168e9575f60caaa35981660d6ebb2b8d8e64ff1d19)
Follow-up to https://github.com/microsoft/fluentui/pull/24332#discussion_r952720485
Part of https://github.com/microsoft/fluentui/issues/24129
=> docs(RFC): Update File Organization Convention for v9 RFC to address other issue

change/@fluentui-react-field-3a6a0878-e060-4cc5-aa5c-9b68eed1f5f3.json, packages/react-components/react-field/Spec.md, packages/react-components/react-field/etc/react-field.api.md, packages/react-components/react-field/src/components/SwitchField/SwitchField.tsx
The SwitchField control inherits the `labelPosition` prop from Switch. However, the `label` prop goes to the field and not the Switch, and so the Switch's `labelPosition` prop has no effect.
Omit the `labelPosition` prop from SwitchField to avoid confusion.
* Fixes #24685
=> fix: Remove SwitchField's labelPosition prop, as it has no effect

change/office-ui-fabric-react-d4d38137-bba4-4a45-a5f9-d94fb3ed6ea4.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md, packages/office-ui-fabric-react/src/components/Pivot/Pivot.types.ts
ODSP needs to depend on the type unions rather than the enums as in v8 there are const enums.
- Added PivotLinkFormatType
- Added PivotLinkSizeType
Updates #24393
=> Added PivotLinkFormatType and PivotLinkSizeType

apps/vr-tests-react-components/src/stories/AvatarGroup.stories.tsx, change/@fluentui-react-avatar-4fdb06be-0dd3-462e-ade1-b57f8857ff6a.json, packages/react-components/react-avatar/src/components/AvatarGroupPopover/useAvatarGroupPopoverStyles.ts
=> fix(react-avatar): Make AvatarGroupPopover's focus indicator the same for all layouts

change/@fluentui-react-170d6594-4aee-4504-8885-b70ae2901269.json, packages/react/etc/react.api.md, packages/react/src/components/Calendar/Calendar.base.tsx, packages/react/src/components/Calendar/Calendar.types.ts
v8 calendar does not support ID prop (and v7 does). This fix helps with migration as well as consistency between components.
=> Calendar: support ID prop

change/@fluentui-react-radio-8d11e9d2-7b87-4a02-bbc2-7b443528252a.json, packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts, packages/react-components/react-switch/src/components/Switch/useSwitchStyles.ts
The hidden input in the `Radio` component covers both the indicator and the label, making any interactive elements within the label, like links, impossible to be clicked.
We also noticed that when hovering over the label of disabled `Switches`, it still showed `cursor: pointer` styles.
The hidden input in the `Radio` component now covers only the indicator and its surrounding space, not the label. This makes any interactive elements within the label, like links, possible to be clicked. We verified that clicking on the label still toggles the state of the component. We also expanded the size of the label so it covers the empty space around it that was previously being covered by the hidden input.
Hovering over the label of disabled `Switches` now shows `cursor: default` instead of `cursor: …
=> fix: Making the hidden input on Radio only cover the indicator and not also the label

change/@fluentui-react-checkbox-516aaf4f-e5f7-4b32-92ae-51f1774a29df.json, packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts
The cursor is a pointer when hovering a disabled checkbox's label.
* Use the default cursor (not pointer) on the label when the checkbox is disabled
* Simplify the styles controlling the padding between the checkbox and label
=> fix: Checkbox's label shouldn't have a pointer cursor when disabled

change/@fluentui-font-icons-mdl2-6bcb568e-9f07-40c7-9947-46b3d24f3603.json, packages/font-icons-mdl2/etc/font-icons-mdl2.api.md, packages/font-icons-mdl2/src/index.ts
- Added IconNamesImport from @fluentui/font-icons-mdl2 
Updates #24393
=> Add export icon names input v8

change/@fluentui-react-components-a03fef34-ebd4-4d4f-9203-384df97ccc9d.json, packages/react-components/react-components/src/unstable/package.json__tmpl__, tools/generators/migrate-converged-pkg/index.spec.ts, tools/generators/migrate-converged-pkg/index.ts, tools/generators/migrate-converged-pkg/schema.json, tools/types.ts, tools/utils.ts
migration generator doesn't provide setup for exports map
migration generator setups exports map including unstable API if present
Fixes partially https://github.com/microsoft/fluentui/issues/25034
=> feat(tools): add exports map support to migrate-converged-pkg generator

change/@fluentui-react-charting-6b54ee59-501e-4a48-9c6e-5d3bffc6dab0.json, packages/react-charting/README.md, packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx, packages/react-charting/src/components/CommonComponents/CartesianChart.types.ts, packages/react-charting/src/utilities/utilities.ts
Add custom date time formatter for date axis
=> Add custom date time formatter for date axis

.github/actions/build-to/action.yml, .github/workflows/docsite-publish-chromatic.yml, .github/workflows/docsite-publish-ghpages.yml
1. We don't have a reusable build action, thus having to manually write the build commands (and specific parameters) each time. 
2. `yarn build --to <workspace>` command doesn't cache the content while being ran in the pipeline, thus causing full builds on each run.
This PR adds a custom build action that can be reused everywhere else and more important, it enables [Backfill remote caching](https://github.com/microsoft/backfill#set-up-remote-cache) so that each run will only build what is invalidated (ie new). This solution makes build times for cached resources almost 50 times faster.
The long term goal is to replace this solution with something that offers better DX and scalability, such as NX.
=> ci(.github): add reusable build action

specs/Checkbox.md
wrong prop name: ariaPoisitionInSet
it is `ariaPositionInSet` now
Fixes #
=> Fixed a prop name in doc

specs/Button.md
=> Fixed a minor typo: immmediately => immediately

change/@fluentui-react-menu-be54a5cf-5794-430d-a10e-a84b223e4eef.json, packages/react-components/react-menu/e2e/Menu.e2e.tsx, packages/react-components/react-menu/src/components/Menu/useMenu.tsx
Menu triggers take focus when they're first mounted. 
This is likely a regression from #24738. Specifically, the removal of `shouldHandleKeyboardRef` from useMenu.tsx is causing it to always call `state.triggerRef.current?.focus()` when mounted.
```diff
-    if (shouldHandleKeyboardRef.current && !open) {
+    if (!open) {
if (shouldHandleTabRef.current && !state.isSubmenu) {
pressedShiftRef.current ? focusBeforeMenuTrigger() : focusAfterMenuTrigger();
} else {
state.triggerRef.current?.focus();
}
}
```
Restore the `shouldHandleKeyboardRef` check to `useMenu_unstable`.
@bsunderhus I'm not familiar with the reason that it was removed in the first place. If this is not the correct fix, please assign the issue to yourself so you can make the correct fix. Thanks!
* Fixes #24981
=> fix: Menu triggers no longer take focus when they are mounted

change/@uifabric-styling-46803f93-7053-4973-9e30-2d6f0e0fa6c8.json, packages/styling/etc/styling.api.md, packages/styling/package.json, packages/styling/src/Icons.ts, packages/styling/src/index.ts, packages/styling/src/styles/index.ts
- Undo of PR #24998 as it causes breaking tree shaking when applied to style-utilities in v8.
- Will do a separate change for handling side-effect in v7 and v8.
=> Undo PR 24998 - Removed the initializeThemeInCustomizations side effect from index 

change/@fluentui-react-persona-ddb5ba78-3b3b-4ba6-b97a-30dd9413b998.json, packages/react-components/react-persona/package.json
This PR adds the missing `bundle-size` command to run the bundle-size fixtures.
=> chore(react-persona): Add bundle-size command for bundle-size fixtures

change/@fluentui-react-table-ccf8542c-a19a-4fa9-a941-4b5fa851901f.json, packages/react-components/react-table/etc/react-table.api.md, packages/react-components/react-table/src/common/mockTableState.ts, packages/react-components/react-table/src/hooks/index.ts, packages/react-components/react-table/src/hooks/types.ts, packages/react-components/react-table/src/hooks/useSelection.test.ts, packages/react-components/react-table/src/hooks/useSelection.ts, packages/react-components/react-table/src/hooks/useSort.test.ts, packages/react-components/react-table/src/hooks/useSort.ts, packages/react-components/react-table/src/hooks/useTable.test.ts, packages/react-components/react-table/src/hooks/useTable.ts, packages/react-components/react-table/src/index.ts, packages/react-components/react-table/src/stories/Table/MultipleSelect.stories.tsx, packages/react-components/react-table/src/stories/Table/MultipleSelectControlled.stories.tsx, packages/react-components/react-table/src/stories/Table/SingleSelect.stories.tsx, packages/react-components/react-table/src/stories/Table/SingleSelectControlled.stories.tsx, packages/react-components/react-table/src/stories/Table/Sort.stories.tsx, packages/react-components/react-table/src/stories/Table/SortControlled.stories.tsx
This PR refactors the `useTable` API to be more composable. The `useTable` hook now accepts plugins that will modify/enhance the state.
Due to typescript limitations, the state is completely typed on our side and any extension that's not an officially supported plugin will need to extend types in userland. The main benefit is that future features for the table can be more SOLID through the implementation of plugins.
The plugins in theory can be order dependent, however there is no plugin that has this limitation.
All functionality was configured on the single `useTable` hook.
```ts
const {
rows,
sort: { getSortDirection, toggleColumnSort },
} = useTable({ columns, items, defaultSortState: { sortColumn: 'file', sortDirection: 'ascending' } });
```
Functionality should be composed from the …
=> BREAKING: refactor `useTable` to be composable

change/@fluentui-style-utilities-ece3f535-005e-426e-8cfa-d2727950a9cd.json, packages/style-utilities/src/Utilities.ts
- Added Utilities.ts to export utilities/index for to avoid the top-level index side effect.
Updates #24393
=> Add utilities export @fluentui/style-utilities v8

change/@fluentui-react-dialog-686635f7-4692-496c-ab3c-6acaa354e72f.json, change/@fluentui-react-menu-4f2d389f-a9b7-41f4-8a65-d4dca52a287b.json, change/@fluentui-react-popover-4839d5df-c144-43e9-9fd6-406fe50d008c.json, change/@fluentui-react-tooltip-13956a4b-4fc1-4e08-9bba-d2980714a6c5.json, change/@fluentui-react-utilities-e8e25f62-8476-4790-9aec-ffcfeef8c660.json, packages/react-components/react-dialog/etc/react-dialog.api.md, packages/react-components/react-dialog/src/components/DialogTrigger/DialogTrigger.types.ts, packages/react-components/react-dialog/src/components/DialogTrigger/useDialogTrigger.ts, packages/react-components/react-menu/etc/react-menu.api.md, packages/react-components/react-menu/src/components/MenuTrigger/MenuTrigger.types.ts, packages/react-components/react-menu/src/components/MenuTrigger/useMenuTrigger.ts, packages/react-components/react-popover/etc/react-popover.api.md, packages/react-components/react-popover/src/components/PopoverTrigger/PopoverTrigger.types.ts, packages/react-components/react-popover/src/components/PopoverTrigger/usePopoverTrigger.ts, packages/react-components/react-tooltip/etc/react-tooltip.api.md, packages/react-components/react-tooltip/src/components/Tooltip/Tooltip.types.ts, packages/react-components/react-tooltip/src/components/Tooltip/useTooltip.tsx, packages/react-components/react-tooltip/src/index.ts, packages/react-components/react-utilities/etc/react-utilities.api.md, packages/react-components/react-utilities/src/index.ts, packages/react-components/react-utilities/src/trigger/applyTriggerPropsToChildren.test.tsx, packages/react-components/react-utilities/src/trigger/applyTriggerPropsToChildren.ts, packages/react-components/react-utilities/src/trigger/getTriggerChild.test.tsx, packages/react-components/react-utilities/src/trigger/getTriggerChild.ts, packages/react-components/react-utilities/src/trigger/isFluentTrigger.ts, packages/react-components/react-utilities/src/trigger/types.ts
Currently types by trigger API are quite loose, on some cases such as on  `getTriggerChild` method a generic type would be required to ensure typings.
Makes types stricter providing a well defined `TriggerProps` types ensuring that helper methods such as `getTriggerChild` can properly infer types without the requirement of generics being necessarily provided.
=> feat(react-utilities): restricts trigger API types

change/@fluentui-react-b55536c0-811e-41b6-84dd-d1ccb7d92969.json, packages/react/src/components/Button/ButtonThemes.ts
rest:
hover:
rest:
hover:
Fixes ADO 15500
=> Split button/primary hc fix

change/@fluentui-react-components-eca314cc-3bb0-44aa-bee3-e4a10f37354c.json, packages/react-components/react-components/src/Concepts/Icons/Icon.stories.mdx
=> (docs): update Icon docs with examples

change/@fluentui-react-4ed89861-a35a-49cc-b44b-db273d7451a4.json, packages/react/src/components/CalendarDayGrid/CalendarMonthHeaderRow.tsx, packages/react/src/components/WeeklyDayPicker/__snapshots__/WeeklyDayPicker.test.tsx.snap
Currently the Calendar appends a letter to a single day header in the week (so "Thursday T" instead of "Thursday"). This is only done for the day of the week that the first day of the month falls on. This seems pretty clearly undesirable, and is fixed in this PR.
=> fix: Calendar should not append day letter to weekday headers

change/@fluentui-react-combobox-cb21bbcc-609e-40f4-9a10-0fa16f2ad882.json, packages/react-components/react-combobox/etc/react-combobox.api.md, packages/react-components/react-combobox/src/contexts/ComboboxContext.ts, packages/react-components/react-combobox/src/contexts/ListboxContext.ts, packages/react-components/react-combobox/src/index.ts
Exports context types and values from the `react-combobox` package
=> feat: export contexts from react-combobox

scripts/monorepo/getAllPackageInfo.js, scripts/monorepo/getAllPackageInfo.spec.ts, scripts/monorepo/runPublished.js, scripts/monorepo/runPublished.spec.ts, scripts/monorepo/tsconfig.json
web-components build pipeline is executed for v9 and nightly release and v8, if affected
- web-components build pipeline is not executed for v9 and nightly releases and v8
- refactored runPublished + test coverage
Super-seeds https://github.com/microsoft/fluentui/pull/24809
=> fix(scripts): don't run publish if web-components are affected

change/@fluentui-react-dialog-f651b531-21bb-4a89-823e-d8325ec32762.json, packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurface.ts, packages/react-components/react-dialog/src/components/DialogTrigger/useDialogTrigger.ts, packages/react-components/react-dialog/src/stories/Dialog/DialogBestPractices.md, packages/react-components/react-dialog/src/stories/Dialog/DialogWithForm.md, packages/react-components/react-dialog/src/stories/Dialog/DialogWithForm.stories.tsx
`aria-describedby` or `aria-labelledby` properties provided by the user for `DialogSurface` will be overridden to internal values.
1. `aria-*` properties will be properly reassigned by the user, this ensure removing `aria-describedby` by assigning it to `undefined` on scenarios where we don't want screen readers to read the body of the dialog.
2. Improves stories around form scenarios where removing `aria-describeby` is recommended
=> fix(react-dialog): make aria-* properties reassignable

.github/workflows/screener-run.yml
Adds the [action-workflow_run action](https://github.com/marketplace/actions/workflow_run-status) to automatically associate the screener-run workflow with the commit of the workflow that triggered it. This should result in the jobs showing up in PR status
=> chore: screener-run workflow should report to PR

change/@fluentui-react-button-eeea86af-7338-4688-ace7-75aa8d2fb347.json, packages/react-components/react-button/src/components/Button/useButtonStyles.ts
Style changes between states in `Button` components had no transition between them.
Style changes between states in `Button` components have a subtle transition between them according to the design spec: `all 100ms easyEase`. We are also making sure that we support the reduced motion settings by turning down the transition duration.
_Note:_ We are not really using `all` as the `transitionProperty` as that would be really expensive and are instead opting for defining only the properties that change between states, which are `background`, `border` and `color`. If more properties change between states in the future, they'll need to be added as well.
Fixes #22552
=> feat: Adding subtle transition between states on Button components

change/@fluentui-react-components-63d50c18-ab92-4fa3-ad8d-694cbf0ad99f.json, packages/react-components/react-components/bundle-size/ButtonProviderAndTheme.fixture.js
We use `Button`, `FluentProvider` & `webLightTheme` is a minimal set to show bundle size improvements. I had this fixture locally, but time to time there are requests for these numbers, so it's better to have it in `master`.
=> chore: add a bundle size fixture (Button, Provider & theme)

change/@fluentui-react-combobox-d1ed182f-ed98-446f-8cb6-4c9de248b0ff.json, packages/react-components/react-combobox/src/components/Dropdown/useDropdownStyles.ts
Fixes the Dropdown layout when no placeholder was provided from this:
to this:
=> fix: Dropdown icon layout with no placeholder/value

change/@fluentui-priority-overflow-faf497c0-15d0-4c21-b8cf-b5d7fdeafd9f.json, change/@fluentui-react-overflow-e4d1fe92-3bdb-420c-81a0-65c956db0e95.json, packages/react-components/priority-overflow/src/overflowManager.ts, packages/react-components/react-overflow/cypress.config.ts, packages/react-components/react-overflow/e2e/Overflow.e2e.tsx, packages/react-components/react-overflow/e2e/tsconfig.json, packages/react-components/react-overflow/package.json, packages/react-components/react-overflow/src/useOverflowContainer.test.ts, packages/react-components/react-overflow/src/useOverflowItem.test.tsx, packages/react-components/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts
Currently overflow items are enqueued immediately when added to the manager. This can create subtle bugs because all options are set during `.observe()`. Some of those options can alter the priority of the items in the queue.
Adds a new `observing` flag to the overflow manager and enqueues all overflow items during `observe()` any new items added while `observing` is true will be enqueued directly.
Also adds tests
Fixes #
=> fix: new overflow items should only be enqueued while observing

azure-pipelines.release-vnext-nightly.yml, tools/generators/version-bump/index.spec.ts, tools/generators/version-bump/index.ts, tools/types.ts, tools/utils.ts
=> fix: version-bump generator removes beachball disallowedChangeType config

change/@fluentui-react-field-16bb1d7a-fa7b-41d6-92ec-5e18e0669150.json, packages/react-components/react-field/src/components/CheckboxField/CheckboxField.test.tsx, packages/react-components/react-field/src/components/Field/Field.test.tsx, packages/react-components/react-field/src/components/Field/useField.tsx
Field sets the input's `id` to `undefined` if there is no field label. CheckboxField is unique in that it doesn't use the field label, but rather an internal label built into Checkbox. The Field's `id={undefined}` gets passed to the Checkbox component, which prevents it from setting a generated ID on the input element.
* Have field _always_ set a generated ID on the input component, even if there is no field label.
* Refactor useField to not set input props to `undefined` if they aren't relevant (instead they will be unset in that case)
* Add tests for these changes.
* Fixes #25072
=> fix: CheckboxField to set a generated ID on the input, to match the label's htmlFor

change/@fluentui-react-2752e34e-9f61-47b8-965c-16b9ab348583.json, packages/react-examples/src/react/Tooltip/Tooltip.Basic.Example.tsx, packages/react/src/components/Tooltip/Tooltip.base.tsx, packages/react/src/components/Tooltip/TooltipHost.base.tsx
If a `Tooltip` is triggered by focusing on the element within `TooltipHost`, and the `Tooltip` contains any interactable items, then trying to interact with these items within the `Tooltip` (for example, clicking on a link within it) will cause the `Tooltip` to close. This occurs because the `Tooltip` closes immediately on `blur`, which precedes other interactions like `focus` or `click`.
A 1ms timeout has been added before the `Tooltip` closes on blur, and a check has been added so that if anything within the `Tooltip` gets focus then the timeout is cleared. Because of the way that events queue on the browser, this ensures that we can always interact with content within the `Tooltip` before it closes on `blur`.
Fixes #24054
Fixes #25001 
PR #25138 fixes the same issue in v9+
=> fix: Tooltip should not hide if an element inside it gets focused

change/@fluentui-react-tooltip-1a523606-fad3-4e83-bd04-c3e3645d474a.json, packages/react-components/react-tooltip/src/components/Tooltip/useTooltip.tsx
If a tooltip contains a focusable item, it will hide when the user tries to interact with the focusable item (including clicking or tabbing to it).
Have the tooltip track if focus is inside, and don't hide if so.
* Fixes #24054
=> fix: The Tooltip should not hide if it gets keyboard focus

.github/workflows/screener-run.yml
Reverts microsoft/fluentui#25144
This workflow should be force merged since it always runs on the default branch (master)
=> Revert "chore: screener-run workflow should report to PR"

change/@fluentui-codemods-c926b650-7f6d-4fbe-b266-eb574a08c173.json, packages/codemods/src/codeMods/mods/configMod/configMod.mod.ts
When `@fluentui/codemods` is run, `configMod` fails because of its config is empty. **Changes from other executed codemods are not saved.**
```
npx @fluentui/codemods
...
File index.ts has had the following mods error:
name:  configMod errorData:  {
modName: 'configMod',
error: 'failed to get any mods from json. Perhaps the file is missing or malformed?'
}
```
Empty `configMod` config is considered valid, the mod is skipped.
```
npx @fluentui/codemods
...
File index.ts has had the following mods run: 
name:  configMod logdata:  [ 'No runnable mods were found in the config' ]
...
```
Fixes #19847
=> fix(codemods): Do not fail on empty configMod config

change/@fluentui-react-menu-5b06dfa2-a4e0-4c1c-8a7b-0784fe888b03.json, packages/react-components/react-menu/e2e/Menu.e2e.tsx, packages/react-components/react-menu/src/components/Menu/useMenu.tsx
#25016 missed out on a crucial condition.
keyboard handling flag was only set when the key was `Tab` this is incorrect and the keyboard handling flag should be set every time the event is a keyboard event
=> fix: Menu trigger should be focused when menu is closed with keyboard
