packages/react-components/theme-designer/src/ThemeDesigner.tsx, packages/react-components/theme-designer/src/components/Content/Content.tsx, packages/react-components/theme-designer/src/components/Demo/Demo.stories.tsx, packages/react-components/theme-designer/src/components/Demo/Demo.tsx, packages/react-components/theme-designer/src/components/TokenBoxes/TokenBoxes.stories.tsx, packages/react-components/theme-designer/src/components/TokenBoxes/TokenBoxes.tsx
Making layout fixes to the theme designer and fixing the dark mode option.
=> Theme designer: design & layout changes

change/@fluentui-react-accordion-d918d9bf-a316-4e92-b3d5-c2714f25f80f.json, packages/react-components/react-accordion/src/components/AccordionHeader/useAccordionHeaderStyles.ts, packages/react-components/react-accordion/src/components/AccordionPanel/useAccordionPanelStyles.ts, packages/react-components/react-accordion/src/stories/AccordionExpandIcon.stories.tsx
Some discrepancies were found between Design spec and Accordion implementation,
1. spacing tokens not being used
2. background color token wrong
3. line-height and font-size tokens wrong
Resolves those discrepancies
=> chore: updates Accordion to follow design spec tokens

packages/react-components/theme-designer/src/components/Nav/Nav.tsx
Continuation of https://github.com/microsoft/fluentui/pull/23360, fixed comments made on last review
=> theme designer: adding navbar

apps/vr-tests-react-components/package.json, apps/vr-tests-react-components/src/stories/Select.stories.tsx, packages/react-components/react-select/src/components/Select/Select.test.tsx, packages/react-components/react-select/src/components/Select/__snapshots__/Select.test.tsx.snap
Adds vr tests and additional component tests to the react-select package.
=> react-select: add tests

change/@fluentui-react-overflow-3c184ff8-b447-449b-ad27-e2d0e3332427.json, packages/react-components/react-overflow/src/useOverflowContainer.ts
Fixes a problem that discovered during implementation of SSR tests.
Fixes #23371.
=> fix(react-overflow): do not throw in SSR

packages/fluentui/docs/src/examples/components/Dropdown/BestPractices/DropdownBestPractices.tsx
Dont's section for v0 Dropdown
=> docs(Dropdown): Donts section

change/@fluentui-react-charting-ea7e79ed-50c5-41f2-beb6-9b3c1dc058a2.json, packages/react-charting/src/components/AreaChart/AreaChart.base.tsx, packages/react-charting/src/components/DonutChart/DonutChart.base.tsx, packages/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx, packages/react-charting/src/components/HeatMapChart/HeatMapChart.base.tsx, packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx, packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx, packages/react-charting/src/components/StackedBarChart/StackedBarChart.base.tsx, packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx, packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx, packages/react-examples/src/react-charting/HorizontalBarChart/HorizontalBarChart.CustomCallout.Example.tsx, packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.Callout.Example.tsx, packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.Styled.Example.tsx
The Hover state appears a significant distance away from the cursor
After this fix we are getting the expected result
=> Affixed hover state closer to the cursor 

change/@fluentui-react-portal-5f022d8a-1302-434f-afb4-7a56fc8e71bb.json, packages/react-components/react-portal/.babelrc.json, packages/react-components/react-portal/config/tests.js, packages/react-components/react-portal/jest.config.js, packages/react-components/react-portal/package.json, packages/react-components/react-portal/src/components/Portal/Portal.test.tsx, packages/react-components/react-portal/src/components/Portal/usePortalMountNode.ts, packages/react-components/react-portal/tsconfig.spec.json
`Portal` does not add `zIndex`.
`Portal` adds `zIndex=1000000` like Fluent UI v8, see #21774 for details.
Fixes #21333.
Related #21774.
=> feat: apply zIndex to Portal

.github/CODEOWNERS
=> add red and coastal to areas that only had dzearing

packages/react/src/components/DetailsList/__snapshots__/DetailsColumn.test.tsx.snap
- CI pipeline is broken due to snapshot mismatch after #23285 was merged.
- https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=252971&view=logs&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=8250ef03-1890-59ab-a6a8-5d0b4c2baa1b&l=22400
- Updates error causing snapshots.
=> Fix failing CI pipeline caused by snapshot mismatch

packages/react-components/theme-designer/package.json, packages/react-components/theme-designer/src/ThemeDesigner.tsx, packages/react-components/theme-designer/src/utils/colors.ts, packages/react-components/theme-designer/src/utils/getBrandTokensFromPalette.ts, yarn.lock
Inputting a key color now changes the appearance of the content.
=> theme designer: key color now generates brand ramp

packages/react-components/theme-designer/src/ThemeDesigner.tsx, packages/react-components/theme-designer/src/components/Content/Content.stories.tsx, packages/react-components/theme-designer/src/components/Demo/Demo.stories.tsx, packages/react-components/theme-designer/src/components/Demo/Demo.tsx, packages/react-components/theme-designer/src/components/Palette/Palette.stories.tsx, packages/react-components/theme-designer/src/components/Sidebar/Sidebar.tsx, packages/react-components/theme-designer/src/components/TokenBoxes/TokenBoxes.stories.tsx, packages/react-components/theme-designer/src/components/TokenBoxes/TokenBoxes.tsx, packages/react-components/theme-designer/src/utils/getBrandTokensFromPalette.ts
Many minor fixes: disabled contrast ref, radio group, filter by color token name
default values fix is incomplete
debounce or onBlur color change was not implemented, but planned for future
=> theme designer: cleanup for w4 demo

packages/react-components/react-toolbar/src/stories/Toolbar.stories.tsx
Cherry pick #23446 Toolbar change to preview components
=> chore: move toolbar stories to preview components (#23446)

rfcs/convergence/changelog-guidelines.md
[**PREVIEW LINK**](https://github.com/ling1726/fluentui/blob/rfc/changelog-changefile-guidelines/rfcs/convergence/changelog-guidelines.md)
(optional)
=> RFC: Changefile and changelog guidelines in PRs

packages/react-components/theme-designer/src/ThemeDesigner.tsx, packages/react-components/theme-designer/src/components/Sidebar/Sidebar.tsx, packages/react-components/theme-designer/src/utils/useDebounce.ts
before: color picker would only update the page once the user clicks out of the color picker
after: color picker now updates intermittently as the user is picking a color
=> theme designer: debouncing fix

packages/react-components/theme-designer/package.json, packages/react-components/theme-designer/src/components/AccessibilityChecker/AccessibilityChecker.stories.tsx, packages/react-components/theme-designer/src/components/AccessibilityChecker/AccessibilityChecker.tsx, packages/react-components/theme-designer/src/components/AccessibilityChecker/AccessibilityList.tsx, packages/react-components/theme-designer/src/components/Content/Content.tsx, packages/react-components/theme-designer/src/utils/color/interfaces.ts, packages/react-components/theme-designer/src/utils/color/shades.ts
adds a working accessibility checker, currently only checks one pair but more will be added soon
=> theme designer: accessibility checker for one token pair

packages/react-components/theme-designer/src/components/AccessibilityChecker/AccessibilityChecker.tsx, packages/react-components/theme-designer/src/components/AccessibilityChecker/AccessibilityList.tsx
Adds more pairs to the accessibility checker (and removes the one that was obviously wrong).
=> theme designer: add accessibility checker pairs

change/@fluentui-web-components-a8625b4e-2828-4ee1-9f82-5f0e14765111.json, packages/web-components/package.json, yarn.lock
Updates FAST packages to latest versions
=> update to latest stable versions of FAST packages

change/@fluentui-react-0a630999-75d4-40f7-a778-8a4b1c8811c0.json, packages/react/src/components/DetailsList/DetailsList.base.tsx, packages/react/src/components/DetailsList/__snapshots__/ShimmeredDetailsList.test.tsx.snap
Right now with placeholder data, the column is saying row 1 of zero...instead of row 1 of 1.
=> Details list correct row count when using placeholder data

change/@fluentui-react-62019bfd-162b-47e4-b2b6-cc3982f8f216.json, packages/react/etc/react.api.md, packages/react/src/components/ChoiceGroup/ChoiceGroup.base.tsx, packages/react/src/components/ChoiceGroup/ChoiceGroup.types.ts
=> Allow `null` as value for choice group selected key

change/@fluentui-react-spinbutton-2a6fa1e7-151b-471d-a18a-683c71c5e5f2.json, packages/react-components/react-spinbutton/README.md, packages/react-components/react-spinbutton/src/stories/SpinButton.stories.tsx, packages/react-components/react-spinbutton/src/stories/SpinButtonBestPractices.md, packages/react-components/react-spinbutton/src/stories/SpinButtonBounds.stories.tsx, packages/react-components/react-spinbutton/src/stories/SpinButtonDefault.stories.tsx, packages/react-components/react-spinbutton/src/stories/SpinButtonDescription.md, packages/react-components/react-spinbutton/src/stories/SpinButtonStep.stories.tsx
SpinButton stories are missing some information and their structure is inconsistent with other components in some places.
SpinButton stories have all the necessary information and are consistent with other components
Fixes #23594
=> spinbutton: clean up stories

packages/react-components/theme-designer/src/ThemeDesigner.tsx, packages/react-components/theme-designer/src/components/Content/Content.tsx, packages/react-components/theme-designer/src/components/Sidebar/Sidebar.tsx, packages/react-components/theme-designer/src/components/TokenBoxes/TokenBoxes.tsx, packages/react-components/theme-designer/src/utils/themes.ts
This PR serves to make memorization changes to the Theme Designer so that there is much less occurrences where values are passed from local state to global state and then back to local state.
Currently the sidebar is not memoized, this will be addressed in a future PR.
=> theme designer: memo changes

packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx, packages/react-components/react-combobox/src/components/Combobox/__snapshots__/Combobox.test.tsx.snap, packages/react-components/react-combobox/src/components/Listbox/Listbox.test.tsx, packages/react-components/react-combobox/src/components/Listbox/__snapshots__/Listbox.test.tsx.snap, packages/react-components/react-combobox/src/components/Option/Option.test.tsx, packages/react-components/react-combobox/src/components/Option/__snapshots__/Option.test.tsx.snap, packages/react-components/react-combobox/src/components/OptionGroup/OptionGroup.test.tsx, packages/react-components/react-combobox/src/components/OptionGroup/__snapshots__/OptionGroup.test.tsx.snap, packages/react-components/react-combobox/src/components/OptionGroup/useOptionGroup.ts
Adds tests to Option, OptionGroup, Listbox, and Combobox components.
=> react-combobox: add tests

change/@fluentui-babel-preset-global-context-71ffd454-8ebf-4ee2-a144-11b75cacaaa7.json, change/@fluentui-global-context-6b97f200-4dfb-4a32-be49-fdb19d4b8e17.json, packages/react-components/babel-preset-global-context/package.json, packages/react-components/global-context/package.json
Since both packages are feature complete and tested, they can be
released to beta
=> chore: Release global-context and babel-preset-global-context

change/@fluentui-react-select-65e60e24-a13b-416a-ae67-e050eab207a8.json, packages/react-components/react-select/etc/react-select.api.md, packages/react-components/react-select/src/index.ts
Export `SelectOnChangeData` from react-select
=> react-select: export change data type

apps/public-docsite-v9/package.json
Manually updates dependencies after 9.0.1 release.
=> update deps after 9.0.1 release

change/@uifabric-charting-9b0374eb-0d51-4006-acfc-e551e14f8543.json, packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.styles.ts
Hover state issues in horizontal bar chart styles
Fixed hover sate in a horizontal bar chart styles
=> fixing horizontal bar chart style issues

change/@fluentui-react-alert-640db5c1-33ff-4314-b504-1fb3b169e05f.json, packages/react-components/react-alert/Spec.md, packages/react-components/react-alert/bundle-size/Alert.fixture.js, packages/react-components/react-alert/etc/react-alert.api.md, packages/react-components/react-alert/package.json, packages/react-components/react-alert/src/components/Alert/Alert.test.tsx, packages/react-components/react-alert/src/components/Alert/Alert.types.ts, packages/react-components/react-alert/src/components/Alert/renderAlert.tsx, packages/react-components/react-alert/src/components/Alert/useAlert.tsx, packages/react-components/react-alert/src/components/Alert/useAlertStyles.ts, packages/react-components/react-alert/src/stories/Alert/AlertAvatar.stories.tsx, packages/react-components/react-alert/src/stories/Alert/AlertIcon.stories.tsx, packages/react-components/react-alert/src/stories/Alert/AlertIntent.stories.tsx, packages/react-components/react-alert/src/stories/Alert/index.stories.tsx
This PR adds support to render an Avatar component in place of an icon in the Alert component. 
And thank you @ling1726 for adding the bundle size fixture for the Alert component :)
=> Add support for avatar prop to the Alert component

packages/react-components/theme-designer/src/components/Sidebar/EditTab.tsx, packages/react-components/theme-designer/src/components/Sidebar/Sidebar.tsx
At Will's request: Changed the hue torsion slider to use smaller steps and a smaller range, as it was a little hard to tune it to a nice value. Added numeric inputs next to the sliders.
=> Theme Designer: EditTab edits

change/@fluentui-react-7dd046c0-8634-439c-a9bf-92c20a10be45.json, change/@uifabric-react-hooks-e0f4f811-efdd-4bdb-9df7-a6c3fea4ef96.json, packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx, packages/react-examples/src/office-ui-fabric-react/FocusTrapZone/FocusTrapZone.Box.Example.tsx, packages/react-examples/src/office-ui-fabric-react/FocusTrapZone/FocusTrapZone.Nested.Example.tsx, packages/react-hooks/etc/react-hooks.api.md, packages/react-hooks/src/index.ts, packages/react-hooks/src/useEventCallback.ts
From #23792.
Also ported over `useEventCallback` from the mainline.
=> Cherry-pick logic to handle iframes in FocusTrapZone

change/@fluentui-react-charting-1ac46906-d36b-4070-9dab-82315733eee0.json, packages/react-charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap, packages/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap, packages/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap, packages/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap, packages/react-charting/src/components/Legends/Legends.base.tsx, packages/react-charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap, packages/react-charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap, packages/react-charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap, packages/react-charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap, packages/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChart.test.tsx.snap
When focus moves to any Legends of graph, remaining Legends are not navigable with keyboard in Browse mode.
Focus is not landing on all the Legends.
When focus moves to any Legends of graph, remaining Legends should be navigable using  arrow keys in Browse mode.
Focus should land on all the legends.
=> Not able to navigate through Legends in Browse mode.

tools/generators/dependency-mismatch/README.md, tools/generators/dependency-mismatch/index.spec.ts, tools/generators/dependency-mismatch/index.ts, tools/generators/dependency-mismatch/schema.json, tools/generators/dependency-mismatch/schema.ts
Check the README.md of the generator for more details
=> chore: Generator to fix v9 dependency mismatch

change/@fluentui-react-conformance-griffel-439a1f62-408e-42fd-ad13-99a13e44c1bb.json, packages/react-components/react-conformance-griffel/package.json
=> fix: Bump react-conformance in react-conformance-griffel to 0.14.0

packages/react-components/theme-designer/src/components/ColorTokens/AccessiblePairs.ts, packages/react-components/theme-designer/src/components/ColorTokens/ColorTokens.tsx, packages/react-components/theme-designer/src/components/ColorTokens/ColorTokensList.tsx, packages/react-components/theme-designer/src/components/ColorTokens/getAccessibilityChecker.ts
Got some feedback from Ken that the accessibility issues can be confusing without context -- this provides some context as to what pairs are failing.
=> theme designer: improve clarity of contrast issues

packages/react-components/react-dialog/bundle-size/Dialog.fixture.js, packages/react-components/react-dialog/etc/react-dialog.api.md, packages/react-components/react-dialog/src/DialogTrigger.ts, packages/react-components/react-dialog/src/components/DialogTrigger/DialogTrigger.test.tsx, packages/react-components/react-dialog/src/components/DialogTrigger/DialogTrigger.tsx, packages/react-components/react-dialog/src/components/DialogTrigger/DialogTrigger.types.ts, packages/react-components/react-dialog/src/components/DialogTrigger/__snapshots__/DialogTrigger.test.tsx.snap, packages/react-components/react-dialog/src/components/DialogTrigger/index.ts, packages/react-components/react-dialog/src/components/DialogTrigger/renderDialogTrigger.tsx, packages/react-components/react-dialog/src/components/DialogTrigger/useDialogTrigger.ts, packages/react-components/react-dialog/src/index.ts
`DialogTrigger` initial implementation
=> feat(react-dialog): Dialog Trigger implementation

packages/react-components/theme-designer/src/components/Palette/Palette.tsx
Make it possible to copy hex codes from the palette.
=> theme designer: update palette with hex codes

packages/react-components/react-progress/.storybook/main.js, packages/react-components/react-progress/.storybook/preview.js, packages/react-components/react-progress/.storybook/tsconfig.json, packages/react-components/react-progress/etc/react-progress.api.md, packages/react-components/react-progress/package.json, packages/react-components/react-progress/src/Progress.ts, packages/react-components/react-progress/src/common/isConformant.ts, packages/react-components/react-progress/src/components/Progress/Progress.test.tsx, packages/react-components/react-progress/src/components/Progress/Progress.tsx, packages/react-components/react-progress/src/components/Progress/Progress.types.ts, packages/react-components/react-progress/src/components/Progress/__snapshots__/Progress.test.tsx.snap, packages/react-components/react-progress/src/components/Progress/index.ts, packages/react-components/react-progress/src/components/Progress/renderProgress.tsx, packages/react-components/react-progress/src/components/Progress/useProgress.ts, packages/react-components/react-progress/src/components/Progress/useProgressStyles.ts, packages/react-components/react-progress/src/index.ts, packages/react-components/react-progress/src/stories/Progress/ProgressBestPractices.md, packages/react-components/react-progress/src/stories/Progress/ProgressDefault.stories.tsx, packages/react-components/react-progress/src/stories/Progress/index.stories.tsx, packages/react-components/react-progress/tsconfig.json, packages/react-components/react-progress/tsconfig.lib.json
This PR is a follow up to the initial package scaffolding of `react-progress`. It adds all the necessary files to the `react-progress` folder in `react-components`. Implementation and testing PRs will follow after
=> Scaffold initial Progress files

README.md
Linked the first episode of Fluent UI Insights as @FBoucher suggested.
=> docs: include Fluent UI Insights

change/@fluentui-react-6b751b3a-85c1-4d87-9f8e-c8604193d9e5.json, change/office-ui-fabric-react-e1b7c8e7-3649-47cb-8486-86559a5edd61.json, packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx
=> Cherry-pick touch-invocation fixes to 7.0

change/@fluentui-react-avatar-70a81c8e-2570-43e8-9ff2-e6aac82ec8da.json, change/@fluentui-react-combobox-fbc7a56d-b6b6-42ea-9b06-713730cbe170.json, change/@fluentui-react-input-af3afd40-e4cf-467a-a666-c36eca8e4829.json, change/@fluentui-react-select-c37c5f03-7231-4f22-ad49-17f9ac225247.json, change/@fluentui-react-spinner-8433acd9-51e6-4dd3-a53a-f1d70cbe4190.json, change/@fluentui-react-switch-c353dfdf-0a6d-433f-87e7-88b8c26c4b13.json, change/@fluentui-react-textarea-1f27cc12-02bc-46f4-a6b2-c0e6bf51e9a6.json, packages/react-components/react-avatar/src/components/Avatar/useAvatarStyles.ts, packages/react-components/react-combobox/src/components/Combobox/useComboboxStyles.ts, packages/react-components/react-combobox/src/components/Dropdown/useDropdownStyles.ts, packages/react-components/react-input/src/components/Input/useInputStyles.ts, packages/react-components/react-select/src/components/Select/useSelectStyles.ts, packages/react-components/react-spinner/src/components/Spinner/useSpinnerStyles.ts, packages/react-components/react-switch/src/components/Switch/useSwitchStyles.ts, packages/react-components/react-textarea/src/components/Textarea/useTextareaStyles.ts
This adds reduced-motion media queries removing motion in the following places:
- spinner: inverted style
- switch
- avatar active ring
- focus underline animation for input, textarea, select, combo, dropdown
=> v9 reduced-motion media query fixes

change/@fluentui-react-charting-0c1386c4-becd-42e2-9fc3-63365f1868b7.json, packages/react-charting/src/components/TreeChart/TreeChart.base.tsx, packages/react-charting/src/components/TreeChart/TreeChart.types.ts, packages/react-charting/src/components/TreeChart/__snapshots__/TreeChart.test.tsx.snap
=> Correcting the connector length for tree diagram

packages/react-components/react-table/src/components/TableCell/TableCell.test.tsx, packages/react-components/react-table/src/components/TableCell/useTableCell.ts, packages/react-components/react-table/src/components/TableCell/useTableCellStyles.ts, packages/react-components/react-table/src/components/TableRow/TableRow.test.tsx, packages/react-components/react-table/src/components/TableRow/TableRow.types.ts, packages/react-components/react-table/src/components/TableRow/useTableRow.ts, packages/react-components/react-table/src/components/TableRow/useTableRowStyles.ts, packages/react-components/react-table/src/contexts/tableContext.ts, packages/react-components/react-table/src/contexts/types.ts, packages/react-components/react-table/src/stories/Table/Default.stories.tsx, packages/react-components/react-table/src/stories/Table/SizeSmall.stories.tsx, packages/react-components/react-table/src/stories/Table/SizeSmaller.stories.tsx, packages/react-components/react-table/src/stories/Table/index.stories.tsx
Implements `TableContext` and handle the `size` and `noNativeElements`
Addresses #23983
=> feat: implement TableContext with handling for rows + cells

change/@fluentui-react-card-25d6cc7b-1af6-4c94-a297-6758b01ba50b.json, packages/react-components/react-card/MIGRATION.md
- Added migration guide from V0 to V9
#19336
#23981
=> docs(react-card): create package migration guide from v0 to v9

change/@uifabric-charting-8e39acd4-35ce-40e8-8390-3bc48a3e7350.json, packages/charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap, packages/charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap, packages/charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap, packages/charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap, packages/charting/src/components/Legends/Legends.base.tsx, packages/charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap, packages/charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap, packages/charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap, packages/charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap, packages/charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChart.test.tsx.snap
Cherry-pick of [#23885](https://github.com/microsoft/fluentui/pull/23885)
When the focus moves to any Legends of the graph, the remaining Legends are not navigable with the keyboard in Browse mode.
Focus is not landing on all the Legends.
Legends are navigatable using arrow keys in Browse mode.
=> Charting: CherryPick #23885-Not able to navigate through Legends in Browse mode

packages/react-components/react-table/etc/react-table.api.md, packages/react-components/react-table/package.json, packages/react-components/react-table/src/TableHeader.ts, packages/react-components/react-table/src/TableHeaderCell.ts, packages/react-components/react-table/src/components/TableHeader/TableHeader.test.tsx, packages/react-components/react-table/src/components/TableHeader/TableHeader.tsx, packages/react-components/react-table/src/components/TableHeader/TableHeader.types.ts, packages/react-components/react-table/src/components/TableHeader/__snapshots__/TableHeader.test.tsx.snap, packages/react-components/react-table/src/components/TableHeader/index.ts, packages/react-components/react-table/src/components/TableHeader/renderTableHeader.tsx, packages/react-components/react-table/src/components/TableHeader/useTableHeader.ts, packages/react-components/react-table/src/components/TableHeader/useTableHeaderStyles.ts, packages/react-components/react-table/src/components/TableHeaderCell/TableHeaderCell.test.tsx, packages/react-components/react-table/src/components/TableHeaderCell/TableHeaderCell.tsx, packages/react-components/react-table/src/components/TableHeaderCell/TableHeaderCell.types.ts, packages/react-components/react-table/src/components/TableHeaderCell/__snapshots__/TableHeaderCell.test.tsx.snap, packages/react-components/react-table/src/components/TableHeaderCell/index.ts, packages/react-components/react-table/src/components/TableHeaderCell/renderTableHeaderCell.tsx, packages/react-components/react-table/src/components/TableHeaderCell/useTableHeaderCell.ts, packages/react-components/react-table/src/components/TableHeaderCell/useTableHeaderCellStyles.ts, packages/react-components/react-table/src/index.ts, packages/react-components/react-table/src/stories/Table/WithHeader.stories.tsx, packages/react-components/react-table/src/stories/Table/index.stories.tsx
Implements the table header components without sorting support.
Addresses #23983
=> feat: Implement TableHeader and TableHeaderCell components

common/changes/office-ui-fabric-react/hotfix_11-hotfix-5.135.6_2022-07-19-17-19.json, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.test.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuAnchor.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuButton.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuItemWrapper.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuItemWrapper.types.ts, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/__snapshots__/ContextualMenuAnchor.test.tsx.snap, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/__snapshots__/ContextualMenuButton.test.tsx.snap
Fix menu hierarchy in ContextualMenu
=> Fix menu hierarchy in ContextualMenu

scripts/screener/screener.runner.ts, scripts/screener/screener.types.ts
Screener proxy doesn't receive branch name, causing it to throw unexpected 400 error.
Fixes #
=> Fix ci checks

.github/workflows/screener-run.yml
Screener run workflow runs on the master branch. the triggering PR source branch.
Screener run workflow runs on the triggering PR source branch.
Addresses #24178
=> Add ref option to checkout action

change/@fluentui-react-dialog-5f33fc01-b6b6-4e63-a2dd-d8af5f8b7f4a.json, packages/react-components/react-dialog/e2e/Dialog.e2e.tsx, packages/react-components/react-dialog/e2e/DialogTitle.e2e.tsx, packages/react-components/react-dialog/e2e/DialogTrigger.e2e.tsx, packages/react-components/react-dialog/e2e/selectors.ts
=> chore(react-dialog): Adds e2e tests

apps/public-docsite/src/SiteDefinition/SiteDefinition.tsx
=> fix(public-docsite): Darkening release link to meet contrast ratio of 4.5

change/@fluentui-react-3acee2cb-5301-4925-bd41-d3a697bb7173.json, packages/react/src/Decorators.ts
Added top-level export that I missed in this PR: https://github.com/microsoft/fluentui/pull/24097
=> Top level decorators export

change/@fluentui-react-combobox-6a69ea68-dcfa-4ff2-9d4d-88e41c5d58ef.json, packages/react-components/react-combobox/src/stories/Combobox/ComboboxBestPractices.md, packages/react-components/react-combobox/src/stories/Combobox/ComboboxDescription.md
The Combobox component storybook doesn't have an unstable usage warning sign and the "Best Practices" section isn't styled up correctly.
Unstable usage warning has been added and "Best Practices" section has been styled.
Fixes #23953
=> fix(docs): add combobox usage warning and style best practices

rfcs/convergence/unified-project-board-process.md
Describes the unified board processes.
[👀 PREVIEW](https://github.com/tudorpopams/fluentui/blob/rfc/unified-board-process/rfcs/convergence/unified-project-board-process.md)
=> RFC: Unified project board process

.github/workflows/screener-build.yml, .github/workflows/screener-run.yml, azure-pipelines.yml, scripts/screener/screener.runner.ts
Reverts microsoft/fluentui#24178
The PR invertedly broke screener scoping, reverting for now to enable previous behaviour while we work on that
=> Revert "Enable screener workflows"

rfcs/react-components/convergence/provider-style-overrides.md
Addresses #23821
[**PREVIEW**](https://github.com/ling1726/fluentui/blob/rfc/provider-style-overrides/rfcs/react-components/convergence/provider-style-overrides.md)
=> RFC: Provider default style overrides

.storybook/main.js, packages/react-components/react-storybook-addon/preset.dev.js, packages/react-components/react-storybook-addon/preset.js, packages/react-components/react-storybook-addon/preset.prod.js, scripts/storybook/README.md, scripts/storybook/index.js, scripts/storybook/utils.js, scripts/storybook/utils.spec.js
- we use imperative logic to determine how workspce sb addon should be loaded
- custom addon pacakge contains no spam
- custom addons are registered via proper public API
Fixes partially https://github.com/microsoft/fluentui/issues/24169
=> feat(scripts): create workspace storybook addon plugin loader

apps/vr-tests-react-components/src/stories/AvatarGroup.stories.tsx, change/@fluentui-react-avatar-94258547-1e65-4b1f-9e2e-16e820ed3061.json, packages/react-components/react-avatar/etc/react-avatar.api.md, packages/react-components/react-avatar/src/components/AvatarGroup/AvatarGroup.tsx, packages/react-components/react-avatar/src/components/AvatarGroup/AvatarGroup.types.ts, packages/react-components/react-avatar/src/components/AvatarGroup/useAvatarGroupStyles.ts, packages/react-components/react-avatar/src/components/AvatarGroupItem/useAvatarGroupItemStyles.ts, packages/react-components/react-avatar/src/components/AvatarGroupOverflow/useAvatarGroupOverflow.tsx, packages/react-components/react-avatar/src/components/AvatarGroupOverflow/useAvatarGroupOverflowStyles.ts, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupLayout.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupSizePie.stories.tsx, packages/react-components/react-avatar/src/stories/AvatarGroup/index.stories.tsx
* Implementation for the pie layout.
* Vr-tests for pie layout.
* Stories for the pie layout.
#24238
=> feat(react-avatar): Adding pie layout implementation

README.md
=> docs(README): update link to Fluent UI Insights

change/@fluentui-react-toolbar-4eab6bb7-c564-4b4a-b148-cef54e96270f.json, packages/react-components/react-toolbar/cypress.config.ts, packages/react-components/react-toolbar/e2e/Toolbar.e2e.tsx, packages/react-components/react-toolbar/e2e/tsconfig.json, packages/react-components/react-toolbar/package.json, packages/react-components/react-toolbar/src/components/Toolbar/__snapshots__/Toolbar.test.tsx.snap, packages/react-components/react-toolbar/src/components/Toolbar/useToolbar.ts, packages/react-components/react-toolbar/src/components/ToolbarRadio/__snapshots__/ToolbarRadio.test.tsx.snap
Add basic e2e tests for `Toolbar`
=> chore: add e2e tests for toolbar

change/@uifabric-utilities-5ab4e040-7eac-4647-bb4f-b6bf55fd2122.json, change/office-ui-fabric-react-1acc2c21-2072-4890-91b8-5b710658f929.json, packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap, packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.base.tsx, packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx, packages/utilities/etc/utilities.api.md, packages/utilities/src/selection/Selection.ts, packages/utilities/src/selection/Selection.types.ts
=> Cherry-pink Group Selection rework to 7.0

.storybook/docs-root.css
fixes #22884
Much better selector
=> Docsite - simplify css query for codesandbox links now that it has a custom class

scripts/gulp/tasks/screener.ts, scripts/screener/screener.runner.ts, scripts/tasks/screener.ts
Reverts microsoft/fluentui#24384
=> Revert "Enable screener proxy to scope and update checks"

azure-pipelines.yml, scripts/gulp/tasks/screener.ts, scripts/screener/screener.runner.ts, scripts/tasks/screener.ts
CI scopes screener test builds and updates checks status.
The screener proxy does the build scoping and checks status updates, and the CI handles the case of both skipped and queued tests.
Fixes #24398
=> Remove ci scoping

azure-pipelines.yml, scripts/gulp/tasks/screener.ts, scripts/screener/screener.runner.ts, scripts/tasks/screener.ts
Reverts microsoft/fluentui#24429
=> Revert "Remove ci scoping"

change/@fluentui-stress-test-ade3b149-0fa4-434c-86c0-faee5e52bc90.json
change file was added for a private package
=> remove stress test change file

change/@fluentui-react-spinner-ec347d0a-9ed1-4c97-abe2-2ea1d37a1a6a.json, packages/react-components/react-spinner/src/components/Spinner/useSpinnerStyles.ts
=> (chore): Remove appearance conditional from Spinner slot styling

change/@fluentui-react-37b93550-3a85-497c-a536-b9a109584fca.json, packages/react/etc/react.api.md, packages/react/src/components/CommandBar/index.ts
[Same change from v7 from https://github.com/microsoft/fluentui/pull/24473](https://github.com/microsoft/fluentui/pull/24476) but in v8.
=> Exported getCommandBarStyles v8

scripts/storybook/utils.js
Fixes https://github.com/microsoft/fluentui/issues/24474
=> fix(script): make `loadWorkspaceAddon()` work on non nix environments

scripts/monorepo/runPublished.js
Follow up to https://github.com/microsoft/fluentui/pull/24472
=> fix(scripts): make runPublished ignore private packages for v9 release

change/office-ui-fabric-react-3ade7928-ac0e-4261-b5d5-4d0b57215539.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md, packages/office-ui-fabric-react/src/components/ContextualMenu/index.ts
Cherry-pick of https://github.com/microsoft/fluentui/pull/24484 from v8 to v7.
Fixes #24454
=> Added exports of ContextMenu (cherry pick)

change/@fluentui-react-6593626a-9255-466d-bbc9-d91599652fa5.json, packages/react/src/ButtonGrid.ts, packages/react/src/WindowProvider.ts
- added ButtonGrid.ts
- added WindowProvider.ts
Fixes #24513
=> Add missing packages/react OUFR exports

change/@fluentui-react-charting-0caef860-4f50-4dd7-931f-65eefe8d5139.json, packages/react-charting/README.md, packages/react-charting/TechnicalDetails.md, packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx, packages/react-charting/src/components/CommonComponents/CartesianChart.types.ts, packages/react-charting/src/components/Legends/Legends.types.ts, packages/react-charting/src/components/Sparkline/Sparkline.styles.ts, packages/react-charting/src/components/Sparkline/__snapshots__/Sparkline.test.tsx.snap, packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.types.ts, packages/react-charting/src/components/TreeChart/TreeChart.md, packages/react-examples/src/react-charting/AreaChart/AreaChartPage.tsx, packages/react-examples/src/react-charting/GroupedVerticalBarChart/GroupedVerticalBarChartPage.tsx, packages/react-examples/src/react-charting/HeatMapChart/HeatMapChartPage.tsx, packages/react-examples/src/react-charting/HorizontalBarChart/HorizontalBarChart.CustomCallout.Example.tsx, packages/react-examples/src/react-charting/HorizontalBarChart/HorizontalBarChartPage.tsx, packages/react-examples/src/react-charting/Legends/Legends.Basic.Example.tsx, packages/react-examples/src/react-charting/Legends/LegendsPage.tsx, packages/react-examples/src/react-charting/LineChart/LineChart.Basic.Example.tsx, packages/react-examples/src/react-charting/LineChart/LineChartPage.tsx, packages/react-examples/src/react-charting/MultiStackedBarChart/MultiStackedBarChartPage.tsx, packages/react-examples/src/react-charting/StackedBarChart/MultiStackedBarChart.Example.tsx, packages/react-examples/src/react-charting/StackedBarChart/StackedBarChartPage.tsx, packages/react-examples/src/react-charting/TreeChart/TreeChartPage.tsx, packages/react-examples/src/react-charting/VerticalBarChart/VerticalBarChartPage.tsx, packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChartPage.tsx
Updated documentation for Charting library.
Added details about different chart variants and their usage in the example demo site.
Fixes #
=> Update documentation for Charting library

azure-pipelines.yml, scripts/screener/screener.runner.ts, scripts/tasks/screener.ts
Uses `SKIP_SCREEER_BUILD` environment variable to determine whether a screener check should be skipped or not.
Replaced `SKIP_SCREENER_BUILD` env variable with `IS_ARTIFACT_PRESENT` and changed logic conditions where necessary in order to ensure smooth migration to GitHub Actions workflows. | #24466
=> Update env variable

scripts/storybook/utils.js
Refactor of https://github.com/microsoft/fluentui/pull/24501
=> refactor(scripts): make loadWorkspaceAddon more defensive and re-do relative posix path creation

packages/fluentui/CHANGELOG.md, packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx
`Dropdown` uses `useLayoutEffect` which causes issues with SSR
`Dropdown` uses `useIsomorphicLayoutEffect` which works across environments.
=> fix: update useLayoutEffect to useIsomorphicLayoutEffect

change/@uifabric-utilities-807e2156-2cf8-4462-8115-bda3e4dfbabd.json, change/office-ui-fabric-react-61770049-72ad-4a6a-bd6b-863b19856002.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md, packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.base.tsx, packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.types.ts, packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx, packages/utilities/etc/utilities.api.md, packages/utilities/src/selection/Selection.ts, packages/utilities/src/selection/Selection.types.ts
=> Cherry-pick: Fix backwards-compatibility of Group Selection additions

scripts/beachball/index.ts
Grouped version bumps of packages/icons and stub-packages/font-icons-mdl2.
Updates #24393
=> grouped versions of icons and font-icons-mdl2 for v7

change/@fluentui-react-file-type-icons-84694097-3fd9-44d0-b145-55735c360bda.json, packages/react-file-type-icons/src/FileTypeIconMap.ts, packages/react-file-type-icons/src/initializeFileTypeIcons.tsx
filetype icons are out of date
Updated visual for video, audio, classifier, loop, shortcut folder.
=> Update to latest CDN for filetype icons, and mapping .classifier to correct icon (master)

change/@fluentui-react-avatar-9daae4e0-30db-4bb1-8cf2-ef1d23d23e56.json, packages/react-components/react-avatar/README-AvatarGroup.md, packages/react-components/react-avatar/SPEC-AvatarGroup.md, packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupBestPractices.md, packages/react-components/react-avatar/src/stories/AvatarGroup/index.stories.tsx
Update spec to match implementation, add best practices, and update README.
Fixes #24240
=> docs(react-avatar): Update spec to match implementation, add best practices, and update README

change/@fluentui-react-441fe287-c504-4f32-816b-1f3fcebe1fd6.json, packages/react/src/components/pickers/BasePicker.styles.ts, packages/react/src/components/pickers/PeoplePicker/__snapshots__/PeoplePicker.test.tsx.snap, packages/react/src/components/pickers/TagPicker/__snapshots__/TagPicker.test.tsx.snap
fixes #22198
**before** 
**after**
=> BasePicker ellipsis styles on placeholder text

common/changes/office-ui-fabric-react/detailslist-hotfix-5.135.6_2022-08-06-12-50.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.tsx, packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.tsx, packages/office-ui-fabric-react/src/components/GroupedList/GroupSpacer.tsx, packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.tsx, packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx
Fix: unable to use table shortcut keys in grouped details list
=> [hotfix/5.135.6] Fix: unable to use table shortcut keys in grouped details list

apps/vr-tests-react-components/package.json, apps/vr-tests-react-components/src/stories/Field.stories.tsx
Implement screener tests for Field components.
* Fixes #24683
=> Implement screener tests for Field components

apps/react-18-tests-v9/package.json, change/@fluentui-react-97f81ce7-b9b5-4983-b1f8-454ffb453492.json, packages/fluentui/react-northstar/package.json, packages/react/package.json, yarn.lock
- manual version fixes to non v9 packages that depend on v9 packages after v9 release
=> fix: update version mismatches triggered by v9 release

change/@uifabric-charting-b6e8f1bb-4826-4cc0-8d7c-ca13cffd670d.json, packages/charting/src/components/Legends/Legends.base.tsx
=> Cherry pick legend overflow-indication-text role fix

.github/workflows/issues.yml
github action has Invalid json to parse
https://github.com/microsoft/fluentui/actions/runs/3077357855/jobs/4972169571#step:2:33
parseable multiline json should fix it
https://github.com/Naturalclar/issue-action/blob/master/src/index.ts#L14-L16
Follows https://github.com/microsoft/fluentui/pull/24788
=> ci(github): fix invalid json string in issues.yml

apps/ui-builder/package.json, apps/ui-builder/src/App.tsx, apps/ui-builder/src/components/ComponentList.tsx, apps/ui-builder/src/components/Knobs.tsx, apps/ui-builder/src/components/MultiTypeKnob.tsx, apps/ui-builder/src/components/NavigationPanel.tsx
Migration of UI builder to Fluent v9 pt. 1:
- ComponentsPropertiesPanel
- ComponentList
- NavigationPanel
=> Standalone UI builder - migration to v9 pt. 1

.github/workflows/issues.yml
Fixes https://github.com/microsoft/fluentui/pull/24853
=> ci(github): fix invalid json string in issues.yml v2

apps/ui-builder/src/components/InsertComponent.tsx
Improved positioning of items in Insert component dialog
=> InsertComponent - dialog items positioning

change/@fluentui-react-menu-2cb38836-7cbe-47af-9cab-68693c9866d7.json, packages/react-components/react-menu/config/api-extractor.json, packages/react-components/react-menu/config/api-extractor.local.json, packages/react-components/react-menu/package.json, packages/react-components/react-menu/tsconfig.lib.json
Migrates `react-menu` converged package to new DX by using the migration command:
```bash
yarn nx workspace-generator migrate-converged-pkg --name='@fluentui/react-menu'
```
=> chore(react-menu): update package scaffold

change/@fluentui-font-icons-mdl2-040093cc-5d07-4a07-ba09-3a992d252624.json, change/@uifabric-icons-16e00942-3d69-45da-ba97-d0509f7ffab6.json, packages/icons/etc/icons.api.md, packages/icons/src/index.ts, stub-packages/font-icons-mdl2/src/IconNames.ts
- Added IconNamesImport export from @uifabric/icons
- Added IconNames.ts lib exports from @fluentui/font-icons-mdl2 stub package
Updates #24393
=> Add export icon names input

change/@fluentui-react-experiments-c835dd62-c210-4fa6-906a-34d705f062a2.json, packages/react-experiments/package.json
=> React-experiments: add signals scss to package.json exports

change/@uifabric-charting-5ec9b927-954e-48d7-a03a-9d7d4dc15c2b.json, packages/charting/package.json, packages/charting/src/TreeChart.ts, packages/charting/src/components/TreeChart/TreeChart.base.tsx, packages/charting/src/components/TreeChart/TreeChart.md, packages/charting/src/components/TreeChart/TreeChart.styles.ts, packages/charting/src/components/TreeChart/TreeChart.test.tsx, packages/charting/src/components/TreeChart/TreeChart.tsx, packages/charting/src/components/TreeChart/TreeChart.types.ts, packages/charting/src/components/TreeChart/__snapshots__/TreeChart.test.tsx.snap, packages/charting/src/components/TreeChart/index.ts, packages/charting/src/index.ts, packages/react-examples/src/charting/TreeChart/TreeChart.ThreeLayer.Example.tsx, packages/react-examples/src/charting/TreeChart/TreeChart.ThreeLayerCompact.Example.tsx, packages/react-examples/src/charting/TreeChart/TreeChart.ThreeLayerLong.Example.tsx, packages/react-examples/src/charting/TreeChart/TreeChart.TwoLayer.Example.tsx, packages/react-examples/src/charting/TreeChart/TreeChartPage.tsx, packages/react-examples/src/charting/demo/AppDefinition.tsx, yarn.lock
Tree Chart is not available for V7 branch
Tree chart is added for v7 branch
Fixes #
=> Adding tree chart for v7 branch

apps/public-docsite-v9/src/Concepts/BuildTimeStyles.stories.mdx, apps/public-docsite-v9/src/Concepts/ChildWindow.stories.mdx, apps/public-docsite-v9/src/Concepts/Migration/FromV8/Components/Theme.stories.mdx, apps/public-docsite-v9/src/Concepts/Migration/FromV8/Troubleshooting.stories.mdx
A follow up based on suggestions in https://github.com/microsoft/fluentui/issues/24816#issuecomment-1249504537. Also fixes small typos/issues mentioned by partners.
=> docs: add notes about portal compat, fix typos

change/@fluentui-react-a2709ae0-6ff2-40b5-9f8c-31f7e6ac37a3.json, change/office-ui-fabric-react-a2709ae0-6ff2-40b5-9f8c-31f7e6ac37a3.json, packages/office-ui-fabric-react/src/Viewport.ts, packages/office-ui-fabric-react/src/index.ts, packages/react/src/Viewport.ts
effectively a cherry-pick of #24995
=> chore: export withViewport via lib/Viewport v7

change/@fluentui-react-experiments-a2709ae0-6ff2-40b5-9f8c-31f7e6ac37a3.json, stub-packages/react-experiments/src/Foundation.ts
Fix Foundation file to export correct path.
=> Fix: foundation exports correct path in v7 experiments stub

change/@fluentui-react-components-29b6499c-41f7-4d61-9122-1fb32e9fd795.json, change/@fluentui-react-persona-8c951488-b9ef-4e69-9f9e-165fa9ca68eb.json, packages/react-components/react-components/etc/react-components.unstable.api.md, packages/react-components/react-components/package.json, packages/react-components/react-components/src/unstable/index.ts, packages/react-components/react-persona/README.md, packages/react-components/react-persona/package.json, packages/react-components/react-persona/src/stories/Persona/PersonaDescription.md
This PR moves Persona to unstable and adds disclaimers of it being unstable.
Fixes #25004
=> feat(react-components): Move Persona to unstable

apps/vr-tests-react-components/package.json, apps/vr-tests-react-components/src/stories/Dialog.stories.tsx
Adds VR tests for `Dialog` components
=> chore(react-dialog): adds VR tests for Dialog components

change/@fluentui-merge-styles-0da7bc43-803f-44ac-9388-46a8fe7cc4a3.json, packages/merge-styles/src/getVendorSettings.ts
=> UserAgent giving NPE cherrypick to 7.0

.github/workflows/screener-run.yml
Reverts microsoft/fluentui#25096
=> Revert "chore: screener-run workflow should report to PR"

scripts/monorepo/runPublished.js
- release pipeline fails because bad logic of caller site
- release pipeline works
Follows https://github.com/microsoft/fluentui/pull/25095
=> fix(script): allow runPublished call from CLI

change/office-ui-fabric-react-ededfbff-be4d-49b1-993a-4a90ec34a43d.json, packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap, packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.base.tsx
Cherry pick of #24822
Fixes #23380
=> Prevent group toggling from selecting the whole group

packages/react-migration-v8-v9/src/stories/ThemeShim/createBrandVariants/index.stories.tsx
Removed sort of result on brand shim story as sort was causing 10, 100, 110, 20, ...
=> Remove sort on brand for shim

apps/stress-test/README.md, apps/stress-test/scripts/utils/configureYargs.ts
This PR improves documentation for the stress-test application based on its usage.
=> docs: Improving stress-test app documentation

packages/react-components/react-tree/package.json
Fixes mismatching versions in master
=> fix: Bump griffel in react-tree

.github/workflows/check-packages.yml
- fixes checkout is missing fetch depth
https://github.com/microsoft/fluentui/actions/runs/3283179885/jobs/5407568622
Follows https://github.com/microsoft/fluentui/pull/25171
=> ci(.github): fix check packages checkout fetch depth

change/@fluentui-react-migration-v8-v9-e1f77d05-b3f5-4c83-8d61-03fdf639bf92.json, packages/react-migration-v8-v9/package.json
##Changes
Set migration package to public and version 1.0.0
Fixes #25120
=> Publishing migration package

change/@fluentui-react-components-430535e4-3f7f-445c-a584-0b68cd1de4e3.json, packages/react-components/react-components/etc/react-components.unstable.api.md, packages/react-components/react-components/src/unstable/index.ts
Exports `@fluentui/react-table` logic hooks on `@fluentui/react-components/unstable`
=> feat: re-export react-table logic hooks

change/@uifabric-merge-styles-7568f8f0-b308-4ee8-922e-a0afc4c3f931.json, packages/merge-styles/src/Stylesheet.ts
Cherry-pick of https://github.com/microsoft/fluentui/pull/20439
This fixes a potential timing issue in createElementStyle in v7. Previously fixed in v8.
Updates #20438
=> Cherry pick create style element fix

packages/office-ui-fabric-react/src/components/Dialog/Dialog.base.tsx, packages/office-ui-fabric-react/src/components/Dialog/Dialog.types.ts, packages/office-ui-fabric-react/src/components/Dialog/DialogContent.base.tsx, packages/office-ui-fabric-react/src/components/Dialog/DialogContent.types.ts
The aria heading level of dialog is not writable.
Make the heading level of dialog is writable.
Fixes #
=> Make the aria-level of dialog title writable

packages/fluentui/react-northstar/package.json
Fixes https://uifabric.visualstudio.com/UI%20Fabric/_build/results?buildId=274100&view=logs&j=8d802004-fbbb-5f17-b73e-f23de0c1dec8&t=a5e45ad2-7904-508f-791a-1a783f6a099f
=> fix(react-northstar): resolve dependency mismatch after v9 release

.storybook/main.js, apps/vr-tests-react-components/.storybook/main.js, apps/vr-tests/.storybook/main.js, change/@fluentui-web-components-2f82b0ce-653b-4e19-9c68-2c549ccfa3e6.json, packages/react-examples/.storybook/main.js, packages/web-components/.storybook/main.js
- we send data to storybook with every storybook start
- no data are sent
- discussed 2 months ago on v-build sync
=> chore(.storybook): disable telemetry

apps/vr-tests-react-components/package.json, apps/vr-tests-react-components/src/stories/Toolbar/Toolbar.stories.tsx, apps/vr-tests-react-components/src/stories/Toolbar/utils.ts, change/@fluentui-react-toolbar-64b1b248-6519-422a-81c5-b40d63309f72.json, packages/react-components/react-toolbar/src/components/Toolbar/Toolbar.cy.tsx
Fixes: #25155
Adds few `Toolbar` CY tests
=> feat: add toolbar CY tests

change/@fluentui-react-combobox-dfd18030-9a1b-4eb5-9644-0b2e0c8d1a5a.json, packages/react-components/react-combobox/src/stories/Dropdown/DropdownAppearance.stories.tsx, packages/react-components/react-combobox/src/stories/Dropdown/DropdownCustomOptions.stories.tsx, packages/react-components/react-combobox/src/stories/Dropdown/DropdownDescription.md, packages/react-components/react-combobox/src/stories/Dropdown/DropdownGrouped.stories.tsx, packages/react-components/react-combobox/src/stories/Dropdown/DropdownMultiselect.stories.tsx, packages/react-components/react-combobox/src/stories/Dropdown/DropdownSize.stories.tsx, packages/react-components/react-combobox/src/stories/Dropdown/index.stories.tsx
Adds stories (similar to Combobox) for v9 Dropdown. I also updated the `DropdownDescription.md` to be a bit more descriptive.
=> feat: add Dropdown stories

change/office-ui-fabric-react-9292c1f9-100e-417b-87ec-23be45433af2.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md, packages/office-ui-fabric-react/src/components/Callout/Callout.test.tsx, packages/office-ui-fabric-react/src/components/Callout/Callout.types.ts, packages/office-ui-fabric-react/src/components/Callout/CalloutContent.base.tsx
Cherry pick to v7 of #24212
Adds `popupProps` to Callout in v7
=> Fluent v7 cherry pick: add popupProps to Callout

packages/fluentui/perf/src/index.tsx, scripts/webpack/webpack.config.perf.ts
=> chore: fix issues in N* perf test

change/@uifabric-charting-27f35641-cc9f-4d2b-aa5e-4dbc3239d6ba.json, packages/charting/src/components/DonutChart/Arc/Arc.tsx, packages/charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap, packages/charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx, packages/charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap, packages/charting/src/components/HeatMapChart/HeatMapChart.base.tsx, packages/charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap, packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx, packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx, packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx, packages/charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap, packages/charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap, packages/charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx, packages/charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx
=> Cherry pick browse mode wrong narration fix

apps/perf-test-react-components/package.json, apps/perf-test-react-components/src/scenarios/Persona.tsx
This PR adds the perf test for react persona.
* Related #24213
=> feat(perf-tests-react-components): Add perf test for Persona

change/@fluentui-react-charting-e13576b2-4b54-41bc-a96f-c30b8ada3470.json, packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx, packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.styles.ts, packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.types.ts, packages/react-charting/src/components/HorizontalBarChart/__snapshots__/HorizontalBarChart.test.tsx.snap
=> Adjust horizontal bar chart styles as per design

apps/vr-tests-react-components/package.json, change/@fluentui-react-components-8424262b-7f1a-4c75-908b-3b5ac38d4200.json, change/@fluentui-react-toolbar-1a67c4b6-c9b8-4924-821e-2067084b01e9.json, packages/react-components/react-components/package.json, packages/react-components/react-toolbar/package.json
Bump `@fluentui/react-toolbar` to RC
=> chore: bump react toolbar

change/office-ui-fabric-react-958eb5bc-6d4b-4099-898b-db6835440d14.json, packages/office-ui-fabric-react/src/components/Autofill/Autofill.tsx
=> v7 fix: Autofill only sets selectionRange when in focus

packages/fluentui/CHANGELOG.md
Add changelog for changes introduced on #25954
=> chore: add changelog

packages/fluentui/CHANGELOG.md
=> chore: update v0 CHANGELOG.md to merge two fixes section

packages/fluentui/docs/src/examples/components/Label/Content/LabelExampleContentCustomization.shorthand.tsx, packages/fluentui/docs/src/examples/components/List/Types/ListExampleSelectableControlled.shorthand.tsx, packages/fluentui/docs/src/examples/components/Menu/Usage/MenuExampleWithSubmenuControlled.shorthand.tsx, packages/fluentui/docs/src/examples/components/Toolbar/Visual/ToolbarExampleOverflowPositioning.shorthand.tsx, packages/fluentui/docs/src/vr-tests/Chat/Chat.stories.tsx, packages/fluentui/docs/src/vr-tests/Video/Video.stories.tsx
Fixes a few react-northstar VR tests that were either flaky or completely broken due to components being written as class components.
* Fixes #25940
* Part of #25078
=> fix(vr-tests v0): fix broken v0 VR tests

azure-pipelines.yml
- removes Screener job from pipeline.
* Part of #25078
=> chore(CI v7): Remove Screener job from pipeline

azure-pipelines.yml
- removes `Screener` step from pipeline
* Part of #25078
=> chore (CI v6): remove Screener step from pipeline

yarn.lock
replaces and fixes https://github.com/microsoft/fluentui/pull/26080
=> chore(deps): bump engine.io from 6.2.0 to 6.2.1

.github/CODEOWNERS
@tudorpopams was not added as an owner to meta and license files.
@tudorpopams is now an owner of those files.
=> fix(owners): add tudorpopams as owner to meta and license files

.github/CODEOWNERS
To enable better velocity (time to merge/count of people requested for review to unblock) this introduces temporary codeowner files change until https://github.com/microsoft/fluentui/issues/24349 is finished.
_Example of huge list of review:_
https://github.com/microsoft/fluentui/pull/26110
- https://github.com/microsoft/fluentui/issues/24349
=> chore: add new temporary rules for codeonwers

.github/CODEOWNERS
follow-up/fix of https://github.com/microsoft/fluentui/pull/26121  - make rules work in whole repo
=> chore: make temporary owner rules work with globs

.github/CODEOWNERS
follow-up/fix of https://github.com/microsoft/fluentui/pull/26123 - the order does matter 🙃
=> chore: move temporary codeowner rules to the bottom to give them highest specificity

lage.config.js
- changes to codeowners or some docs within `.github/` will trigger pipeline for all repo
- changes for codeowners etc will not trigger any build tasks on PR pipeline
=> chore: ignore more patterns for lage --since resolution

.github/CODEOWNERS
follows https://github.com/microsoft/fluentui/pull/26128
=> chore: add more temporary rules for v-build to co-own

.github/CODEOWNERS
* Fixes typo introduced in https://github.com/microsoft/fluentui/pull/26146
=> chore: fix webpack pattern typo

packages/fluentui/docs/src/components/ComponentDoc/LazyWithBabel.tsx, packages/fluentui/docs/tsconfig.json, scripts/gulp/preset.ts, tsconfig.base.v0.json
**Pre-requisite:**
- removes unnecessary gulp config
- normalizes v0 docs to use base tsconfig for aliases
Follows :
- https://github.com/microsoft/fluentui/pull/26125#discussion_r1059082593
- https://github.com/microsoft/fluentui/pull/26125#pullrequestreview-1232675155
=> chore(scripts): remove unnecessary gulp preset configuration

change/office-ui-fabric-react-6b4f8477-de7b-4b8a-9e2a-a3cc15cf5fd7.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md, packages/office-ui-fabric-react/src/components/GroupedList/GroupedListV2.tsx, packages/office-ui-fabric-react/src/components/GroupedList/index.ts
Cherry pick of #26052
* Fixes #26041
=> Cherry pick: export GroupedListV2 types

change/@fluentui-react-table-6f22423b-4f4c-45da-a1f9-d431ccfefded.json, packages/react-components/react-table/src/components/Table/Table.types.ts
=> docs: fix typo in Table.types.ts

change/@fluentui-react-table-b8515237-27e4-4cfc-98de-2a5465e31a0d.json, packages/react-components/react-table/stories/DataGrid/RowNavigation.stories.tsx, packages/react-components/react-table/stories/Table/RowNavigation.stories.tsx, packages/react-components/react-table/stories/Table/TableDescription.md, packages/react-components/react-table/stories/Table/Virtualization.stories.tsx
=> docs: Fix typos in react-table docs

change/@fluentui-react-input-68d90a7c-d6d4-4cc4-bd74-697d991fdfca.json, packages/react-components/react-input/src/components/Input/useInputStyles.ts
=> Update styling for contentBefore and contentAfter input slots

.github/CODEOWNERS
=> wc3: Update web-components code owners

packages/react-components/react-table/stories/DataGrid/CustomRowId.stories.tsx, packages/react-components/react-table/stories/DataGrid/Default.stories.tsx, packages/react-components/react-table/stories/DataGrid/MultipleSelect.stories.tsx, packages/react-components/react-table/stories/DataGrid/MultipleSelectControlled.stories.tsx, packages/react-components/react-table/stories/DataGrid/RowNavigation.stories.tsx, packages/react-components/react-table/stories/DataGrid/SelectionAppearance.stories.tsx, packages/react-components/react-table/stories/DataGrid/SingleSelect.stories.tsx, packages/react-components/react-table/stories/DataGrid/SingleSelectControlled.stories.tsx, packages/react-components/react-table/stories/DataGrid/Sort.stories.tsx, packages/react-components/react-table/stories/DataGrid/SortControlled.stories.tsx, packages/react-components/react-table/stories/DataGrid/SubtleSelection.stories.tsx, packages/react-components/react-table/stories/Table/CellActions.stories.tsx, packages/react-components/react-table/stories/Table/CellNavigation.stories.tsx, packages/react-components/react-table/stories/Table/DataGrid.stories.tsx, packages/react-components/react-table/stories/Table/Default.stories.tsx, packages/react-components/react-table/stories/Table/MultipleSelect.stories.tsx, packages/react-components/react-table/stories/Table/MultipleSelectControlled.stories.tsx, packages/react-components/react-table/stories/Table/NonNativeElements.stories.tsx, packages/react-components/react-table/stories/Table/PrimaryCell.stories.tsx, packages/react-components/react-table/stories/Table/RowNavigation.stories.tsx, packages/react-components/react-table/stories/Table/SingleSelect.stories.tsx, packages/react-components/react-table/stories/Table/SingleSelectControlled.stories.tsx, packages/react-components/react-table/stories/Table/SizeExtraSmall.stories.tsx, packages/react-components/react-table/stories/Table/SizeSmall.stories.tsx, packages/react-components/react-table/stories/Table/Sort.stories.tsx, packages/react-components/react-table/stories/Table/SortControlled.stories.tsx, packages/react-components/react-table/stories/Table/SubtleSelection.stories.tsx, packages/react-components/react-table/stories/Table/Virtualization.stories.tsx
See issues for more details
Fixes #26210
Fixes #26208
Fixes #26197
Fixes #26209
=> docs: Improve a11y for Table/DataGrid examples

change/@fluentui-react-table-fc7f861c-9979-47b5-b19d-980eb9e94719.json, packages/react-components/react-table/bundle-size/DataGrid.fixture.js, packages/react-components/react-table/bundle-size/PrimitivesOnly.fixture.js, packages/react-components/react-table/bundle-size/TableAsDataGrid.fixture.js, packages/react-components/react-table/bundle-size/TableSelectionOnly.fixture.js, packages/react-components/react-table/bundle-size/TableSortOnly.fixture.js, packages/react-components/react-table/package.json
=> chore: Add bundle size fixtures for react-table

apps/react-18-tests-v9/jest.config.js
TS errors are being reported although `diagnostic: false` is used
No TS errors are being reported 
* Fixes #
=> test(react-18-tests-v9): mute TS error reporting from packages/

package.json, yarn.lock
VR tool used to comment screenshotdiff message as an issue comment which is not resolvable
If VR tool finds there are screenshotdiff it will comment screenshotdiff message as an review comment which needs to me marked resolved for PR to be merged.
Logic
If screenshot diff found
- If issue comment exist delete issue comment
- If review comment exist update that review comment
- Else create new review comment
If no screenshot diff found
- If review comment exist delete review comment
- If issue comment exist update that issue comment
- Else create new issue comment
* Fixes #
=> Update VR screenshot diff commenting flow

change/@fluentui-priority-overflow-a99ea7f9-2163-476f-99c2-0d4de683e445.json, change/@fluentui-react-components-34489ece-96da-440b-a134-6e5cbdec8e1f.json, change/@fluentui-react-overflow-7198efe2-6f23-453f-84db-0c28f7840b55.json, packages/react-components/priority-overflow/package.json, packages/react-components/react-components/etc/react-components.api.md, packages/react-components/react-components/etc/react-components.unstable.api.md, packages/react-components/react-components/src/index.ts, packages/react-components/react-components/src/unstable/index.ts, packages/react-components/react-components/stories/AccessibilityScenarios/TabListOverflow.stories.tsx, packages/react-components/react-overflow/package.json, packages/react-components/react-overflow/stories/Overflow/Default.stories.tsx, packages/react-components/react-overflow/stories/Overflow/Dividers.stories.tsx, packages/react-components/react-overflow/stories/Overflow/MinimumVisible.stories.tsx, packages/react-components/react-overflow/stories/Overflow/OverflowByPriority.stories.tsx, packages/react-components/react-overflow/stories/Overflow/OverflowDescription.md, packages/react-components/react-overflow/stories/Overflow/Pinned.stories.tsx, packages/react-components/react-overflow/stories/Overflow/PriorityWithDividers.stories.tsx, packages/react-components/react-overflow/stories/Overflow/ReverseDomOrder.stories.tsx, packages/react-components/react-overflow/stories/Overflow/Wrapped.stories.tsx, packages/react-components/react-overflow/stories/Overflow/index.stories.tsx, packages/react-components/react-tabs/stories/Tabs/TabListWithOverflow.stories.tsx, packages/react-components/react-toolbar/stories/Toolbar/ToolbarOverflow.stories.tsx
=> Release `@fluentui/priority-overflow` and `@fluentui/overflow` as stable

scripts/tasks/src/api-extractor.ts
* Fixes https://ci.codesandbox.io/status/microsoft/fluentui/pr/26407/builds/337157
* Follows https://github.com/microsoft/fluentui/pull/26370
=> fix(scripts-tasks): unify api-extractor runs on any CI

change/@fluentui-azure-themes-4447b77a-6462-4e32-a60e-e4bcefb1be23.json, change/@fluentui-azure-themes-d4442d56-f31c-4e86-b175-7298d7d565de.json, packages/azure-themes/src/azure/Constants.ts, packages/azure-themes/src/azure/styles/SpinButton.styles.ts
The design remains the same as #26464, just using a more precise selector.
=> Azure Theme: Spinbutton CSS update

change/@fluentui-react-4b696ee3-1985-435c-a365-c961bf362032.json, packages/react/src/components/pickers/BasePicker.scss, packages/react/src/components/pickers/BasePicker.styles.ts, packages/react/src/components/pickers/BasePicker.tsx, packages/react/src/components/pickers/PeoplePicker/__snapshots__/PeoplePicker.test.tsx.snap, packages/react/src/components/pickers/TagPicker/__snapshots__/TagPicker.test.tsx.snap
fixes #26404
Without relative position there is a chance that the absolute position child will cause layout issues.
=> Add relative position to base picker

change/@fluentui-react-charting-5f4681c3-0bbb-4057-a1d3-f78544ca7021.json, packages/react-charting/src/components/DonutChart/Arc/Arc.styles.ts, packages/react-charting/src/components/DonutChart/Arc/Arc.tsx, packages/react-charting/src/components/DonutChart/Arc/Arc.types.ts, packages/react-charting/src/components/DonutChart/DonutChart.base.tsx, packages/react-charting/src/components/DonutChart/DonutChart.test.tsx, packages/react-charting/src/components/DonutChart/DonutChart.types.ts, packages/react-charting/src/components/DonutChart/Pie/Pie.styles.ts, packages/react-charting/src/components/DonutChart/Pie/Pie.tsx, packages/react-charting/src/components/DonutChart/Pie/Pie.types.ts, packages/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap, packages/react-examples/src/react-charting/DonutChart/DonutChart.Dynamic.Example.tsx, packages/react-examples/src/react-charting/DonutChart/DonutChartPage.tsx
=> Add labels to arcs in donut chart

change/@fluentui-react-charting-c7844caa-d03e-4509-9fbb-92c449da19c6.json, packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx, packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.styles.ts, packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.test.tsx, packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.types.ts, packages/react-charting/src/components/HorizontalBarChart/__snapshots__/HorizontalBarChart.test.tsx.snap, packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx, packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.styles.ts, packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.test.tsx, packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.types.ts, packages/react-charting/src/components/StackedBarChart/StackedBarChart.styles.ts, packages/react-charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap, packages/react-charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap, packages/react-examples/src/react-charting/HorizontalBarChart/HorizontalBarChart.Variant.Example.tsx, packages/react-examples/src/react-charting/HorizontalBarChart/HorizontalBarChartPage.tsx, packages/react-examples/src/react-charting/MultiStackedBarChart/MultiStackedBarChart.Variant.Example.tsx, packages/react-examples/src/react-charting/MultiStackedBarChart/MultiStackedBarChartPage.tsx
=> Add new variant to horizontal bar chart

packages/react-components/react-tree/etc/react-tree.api.md, packages/react-components/react-tree/package.json, packages/react-components/react-tree/src/TreeItemPersonaLayout.ts, packages/react-components/react-tree/src/components/TreeItemPersonaLayout/TreeItemPersonaLayout.test.tsx, packages/react-components/react-tree/src/components/TreeItemPersonaLayout/TreeItemPersonaLayout.tsx, packages/react-components/react-tree/src/components/TreeItemPersonaLayout/TreeItemPersonaLayout.types.ts, packages/react-components/react-tree/src/components/TreeItemPersonaLayout/__snapshots__/TreeItemPersonaLayout.test.tsx.snap, packages/react-components/react-tree/src/components/TreeItemPersonaLayout/index.ts, packages/react-components/react-tree/src/components/TreeItemPersonaLayout/renderTreeItemPersonaLayout.tsx, packages/react-components/react-tree/src/components/TreeItemPersonaLayout/useTreeItemPersonaLayout.ts, packages/react-components/react-tree/src/components/TreeItemPersonaLayout/useTreeItemPersonaLayoutContextValues.ts, packages/react-components/react-tree/src/components/TreeItemPersonaLayout/useTreeItemPersonaLayoutStyles.ts, packages/react-components/react-tree/src/index.ts, packages/react-components/react-tree/src/utils/tokens.ts, packages/react-components/react-tree/stories/TreeItemPersonaLayout/TreeItemPersonaLayoutDefault.stories.tsx, packages/react-components/react-tree/stories/TreeItemPersonaLayout/index.stories.tsx
Inspired on `TableCellLayout`, this PR creates `TreeItemPersonaLayout` component to separate `TreeItem` logic from presentation.
=> chore: scaffolds  TreeItemPersonaLayout component

apps/ssr-tests-v9/src/utils/visitPage.ts, package.json, scripts/puppeteer/jest.config.js, yarn.lock
* Follows https://github.com/microsoft/fluentui/pull/26375
=> chore(scripts-puppeteer): migrate to puppeteer 19

apps/public-docsite-v9/package.json
public-docsite-v9 added dependency on fluent2-theme 
Should unblock docsite publishing
=> Adding fluent2-theme dependency

packages/react-components/react-menu/stories/MenuList/MenuListCheckboxItems.stories.tsx, packages/react-components/react-menu/stories/MenuList/MenuListControlledCheckboxItems.stories.tsx, packages/react-components/react-menu/stories/MenuList/MenuListControlledRadioItems.stories.tsx, packages/react-components/react-menu/stories/MenuList/MenuListDefault.stories.tsx, packages/react-components/react-menu/stories/MenuList/MenuListNestedSubmenus.stories.tsx, packages/react-components/react-menu/stories/MenuList/MenuListRadioItems.stories.tsx, packages/react-components/react-tabs/stories/Tabs/TabListDefault.stories.tsx
Doc examples should only have one export.
=> docs: Remove extra exports

packages/react-components/react-tree/src/components/Tree/useTree.ts, packages/react-components/react-tree/src/components/TreeItem/useTreeItemStyles.ts, packages/react-components/react-tree/src/components/TreeItemLayout/useTreeItemLayoutStyles.ts, packages/react-components/react-tree/stories/Tree/TreeActions.stories.tsx, packages/react-components/react-tree/stories/Tree/TreeAppearance.stories.tsx, packages/react-components/react-tree/stories/Tree/TreeControllingOpenAndClose.stories.tsx, packages/react-components/react-tree/stories/Tree/TreeDefault.stories.tsx, packages/react-components/react-tree/stories/Tree/TreeDefaultOpenTrees.stories.tsx, packages/react-components/react-tree/stories/Tree/TreeExpandIcon.stories.tsx, packages/react-components/react-tree/stories/Tree/TreeIconAfter.stories.tsx, packages/react-components/react-tree/stories/Tree/TreeIconBefore.stories.tsx
1. Moves some styling from `TreeItem` to `TreeItemLayout`
2. Adds `TreeItemLayout` on all stories
3. Ensures `appearance` and `size` is inherited between sub trees
=> chore(react-tree): adds TreeItemLayout to all stories

.github/workflows/pr-housekeeping.yml
`add-to-milestone` was failing again. we will now use major version of that action to get latest fixes.
=> ci: use major version for add-to-milestone to get latest fixes

change/@fluentui-react-0437e436-ce0b-49ed-b3a5-5b0478c2db87.json, packages/react/src/components/ContextualMenu/ContextualMenu.cnstyles.ts, packages/react/src/components/ContextualMenu/__snapshots__/ContextualMenu.test.tsx.snap
=> Fix: Contextual menu label missing overflow hidden

.github/workflows/azure-storage-web-components.yml
- applies prettier on changes made via web-interface
- removes manual workflow as they dont work on branches
=> style: format yml workflow

apps/public-docsite-v9/README.md
Added information about `Open in CodeSandbox` button repo to README.md of public-docsite-v9l.
=> Added information about `Open in CodeSandbox` button repo

change/@fluentui-react-data-grid-react-window-4b9e5614-c8c5-40fc-a307-4e0925443ec8.json, packages/react-components/react-data-grid-react-window/package.json
Releases the package with `beta` tag since all functional requirements are implemented.
=> feat: Initial release react-data-grid-react-window

apps/vr-tests-react-components/src/stories/Field.stories.tsx, apps/vr-tests-react-components/src/stories/ProgressBar.stories.tsx, change/@fluentui-react-progress-ecf0cec4-a029-43b2-8833-989f094d2ace.json, packages/react-components/react-progress/etc/react-progress.api.md, packages/react-components/react-progress/src/components/ProgressBar/ProgressBar.types.ts, packages/react-components/react-progress/src/components/ProgressBar/useProgressBar.tsx, packages/react-components/react-progress/src/components/ProgressBar/useProgressBarStyles.ts, packages/react-components/react-progress/stories/ProgressBar/ProgressBarBestPractices.md, packages/react-components/react-progress/stories/ProgressBar/ProgressBarColor.stories.tsx, packages/react-components/react-progress/stories/ProgressBar/ProgressBarDefault.stories.tsx, packages/react-components/react-progress/stories/ProgressBar/ProgressBarDescription.md, packages/react-components/react-progress/stories/ProgressBar/ProgressBarIndeterminate.stories.tsx, packages/react-components/react-progress/stories/ProgressBar/ProgressBarMax.stories.tsx, packages/react-components/react-progress/stories/ProgressBar/ProgressBarShape.stories.tsx, packages/react-components/react-progress/stories/ProgressBar/ProgressBarThickness.stories.tsx, packages/react-components/react-progress/stories/ProgressBar/ProgressBarValidationState.stories.tsx, packages/react-components/react-progress/stories/ProgressBar/index.stories.tsx
This PR is to apply fixes from the ProgressBar bug bashes to clarify the documentation and update some styling inconsistencies.
=> chore: Progressbar documentation update

packages/react-components/react-components/stories/Concepts/Positioning/OverflowBoundaryPadding.stories.tsx
=> docs: Add design guidance for overflow padding

packages/react-components/react-migration-v0-v9/etc/react-migration-v0-v9.api.md, packages/react-components/react-migration-v0-v9/src/components/Segment/Segment.styles.ts, packages/react-components/react-migration-v0-v9/src/components/Segment/Segment.test.tsx, packages/react-components/react-migration-v0-v9/src/components/Segment/Segment.tsx, packages/react-components/react-migration-v0-v9/src/components/Segment/index.ts, packages/react-components/react-migration-v0-v9/src/index.ts, packages/react-components/react-migration-v0-v9/src/stories/SegmentShim/Description.md, packages/react-components/react-migration-v0-v9/src/stories/SegmentShim/index.stories.tsx
Add Segment Shim to V0 - V9 migration package
=> chore: add segment shim

apps/public-docsite-v9/src/Concepts/StylingComponents.stories.mdx
V9 docs introduce a link to Styles handbook
=> docs: v9 docs now mention Styling handbook

packages/react-components/react-migration-v0-v9/etc/react-migration-v0-v9.api.md, packages/react-components/react-migration-v0-v9/src/components/Slider/Slider.mixins.test.ts, packages/react-components/react-migration-v0-v9/src/components/Slider/Slider.mixins.ts, packages/react-components/react-migration-v0-v9/src/components/Slider/index.ts, packages/react-components/react-migration-v0-v9/src/index.ts, packages/react-components/react-migration-v0-v9/src/stories/SliderMixin/Description.md, packages/react-components/react-migration-v0-v9/src/stories/SliderMixin/index.stories.tsx
Add V0 slider mixins to help with V9 migration
=> chore: add slider Mixins

change/@fluentui-react-persona-09e70d42-1107-4695-9982-c3de4e03e9f4.json, change/@fluentui-react-persona-e7cf047e-313b-45ed-aae2-42a6ea1a64a9.json, packages/react-components/react-persona/src/components/Persona/usePersonaStyles.ts
Persona has many classes on its slots.
Persona has fewer classes on its slots. This is not as dramatic a change as the related Avatar PR (#26811) but it will benefit from the Avatar change as Persona renders an Avatar.
| Story | Old | New |
| --- | --- | --- |
| default | 118 | 37 |
| text alignment | 121 | 39 |
| test position | 105 | 35 |
| presence size | 58  | 30 |
| avatar size | 109 | 42 |
- #26811
- #26817
=> chore: update Persona to use makeResetStyles

change/@fluentui-web-components-f31a00b9-ac73-4bbf-841d-f03863621252.json, packages/web-components/package.json, packages/web-components/src/badge/badge.options.ts, yarn.lock
Changes within the version are here: https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/CHANGELOG.md#300-alpha25
- Fixes #
=> update fast element and foundation versions for wc-3 branch

packages/react-components/react-infobutton/docs/Spec.md
This PR adds some minor changes to the Spec to match the actual implementation. The changes are mainly accessibility related.
- Fixes #26355
=> docs(react-infobutton): Update spec to match implementation

packages/fluentui/projects-test/src/nextjs.ts
we are sending telemetry data to vercel on test runs
no data are sent
- Fixes #
=> chore(fluentui/project-test): disable nextjs telemetry

apps/public-docsite-v9/package.json, apps/recipes-react-components/package.json, apps/vr-tests-react-components/package.json
=> fix: Add codesandbox addon as dependency for apps

apps/vr-tests-react-components/package.json, change/@fluentui-react-card-c40e5dc6-c2bf-488c-b222-7ef98e0b1be9.json, change/@fluentui-react-components-ccce747e-48bb-4cfe-a1e6-3b170b7c6f42.json, packages/react-components/react-card/package.json, packages/react-components/react-components/package.json
=> feat(react-card): bump to release candidate

change/@fluentui-react-charting-11ada80b-4cd2-491f-91d5-35039a39a3fa.json, packages/react-charting/src/components/DonutChart/DonutChart.base.tsx, packages/react-charting/src/components/DonutChart/DonutChart.styles.ts, packages/react-charting/src/components/DonutChart/DonutChart.test.tsx, packages/react-charting/src/components/DonutChart/DonutChart.types.ts, packages/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap, packages/react-examples/src/react-charting/DonutChart/DonutChart.Dynamic.Example.tsx, packages/react-examples/src/react-charting/DonutChart/DonutChartPage.tsx
Width and height of DonutChart don't match the passed props
Width and height of DonutChart match the passed props
=> Fix SVG size in donut chart

packages/react-components/react-tree/etc/react-tree.api.md, packages/react-components/react-tree/src/components/TreeItem/TreeItem.types.ts, packages/react-components/react-tree/src/components/TreeItem/__snapshots__/TreeItem.test.tsx.snap, packages/react-components/react-tree/src/components/TreeItem/useTreeItemStyles.ts, packages/react-components/react-tree/src/index.ts, packages/react-components/react-tree/src/utils/tokens.ts, packages/react-components/react-tree/stories/Tree/TreeWithInlineStyle.stories.tsx, packages/react-components/react-tree/stories/Tree/TreeWithoutInlineStyle.stories.tsx, packages/react-components/react-tree/stories/Tree/Virtualization.stories.tsx, packages/react-components/react-tree/stories/Tree/index.stories.tsx
1. Opts in on using static style for the first 10 levels of the tree.
2. Allows inline style override from the user side to ensure all use cases.
3. Adds stories to properly document this behavour
=> feat(react-tree): TreeItem static style for level

change/@fluentui-react-table-820f172b-d98e-4f3f-a3a9-9abff3f29d66.json, packages/react-components/react-table/README.md
=> chore: Add README for react-table package

.github/workflows/check-packages.yml
- cherry pick https://github.com/microsoft/fluentui/pull/26813
=> ci: set fetch depth to 0 for dep-mismatch job

.github/CODEOWNERS
=> ci: make codeowners file valid

packages/react-components/react-datepicker-compat/src/components/CalendarDay/CalendarDay.tsx, packages/react-components/react-datepicker-compat/src/components/CalendarDayGrid/useCalendarDayGridStyles.ts, packages/react-components/react-datepicker-compat/src/components/CalendarYear/CalendarYear.tsx, packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx
- runs `yarn format --all` to fix files with invalid formatting causing CI pipelines to fail.
Example of failed CI build: https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=290546&view=logs&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=cc94c182-d6f4-5dae-734d-3676c12cee2a
=> fix(react-datepicker-compat): run prettier formatting to update invalid files and fix broken master

change/@fluentui-react-shared-contexts-2a428543-5453-4c0a-846b-196b5734538d.json, packages/react-components/react-shared-contexts/etc/react-shared-contexts.api.md, packages/react-components/react-shared-contexts/src/CustomStyleHooksContext/CustomStyleHooksContext.ts
- Removed checkmark custom styling hook used internally in menu
- Updates #27058
=> Removing internal menu styles hook

change/@fluentui-react-spinbutton-aae8e08f-cab6-4d00-8c59-55cbdf98d4bc.json, packages/react-components/react-spinbutton/src/components/SpinButton/SpinButton.types.ts, packages/react-components/react-spinbutton/src/components/SpinButton/renderSpinButton.tsx, packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButton.tsx
There was some commented out code and grammar issues in comments.
Commented out code is removed and one grammar issue is fixed.
=> chore: clean up SpinButton comments in source

change/@fluentui-web-components-54c7cd29-29dc-46c9-8324-465b8c1b5eac.json, packages/web-components/package.json, yarn.lock
=> update FAST dependencies

packages/react-components/react-card/stories/Card/index.stories.tsx, packages/react-components/react-card/stories/CardFooter/index.stories.tsx, packages/react-components/react-card/stories/CardHeader/index.stories.tsx, packages/react-components/react-card/stories/CardPreview/index.stories.tsx
Move cards out of Preview Components group now that card is stable.
=> docs(react-card): move card out of preview

packages/react-components/react-overflow/stories/Overflow/Vertical.stories.tsx, packages/react-components/react-overflow/stories/Overflow/index.stories.tsx
=> docs: Add vertical scenario

change/@fluentui-react-tree-d2302a0b-2907-4427-a399-61bf21221683.json, packages/react-components/react-tree/cypress.config.ts, packages/react-components/react-tree/package.json, packages/react-components/react-tree/src/components/Tree/Tree.cy.tsx, packages/react-components/react-tree/tsconfig.cy.json, packages/react-components/react-tree/tsconfig.json, packages/react-components/react-tree/tsconfig.lib.json
1. Add cypress configuration to `react-tree` package
2. Adds initial e2e tests to ensure Tre behaviours
=> chore: adds initial e2e cypress tests

packages/web-components/src/menu-item/menu-item.styles.ts, packages/web-components/src/menu-item/menu-item.ts, packages/web-components/src/menu/menu.stories.ts, packages/web-components/src/menu/menu.ts
=> Using Indent for Menu

apps/public-docsite-v9/src/Concepts/AdvancedConfiguration.stories.mdx
This PR adds a new section to "Advanced Configuration" about sorting media queries. Related to #27225.
=> docs: add section about media query sorting

apps/ssr-tests-v9/src/build.ts, apps/ssr-tests-v9/src/utils/generateEntryPoints.test.ts, apps/ssr-tests-v9/src/utils/generateEntryPoints.ts, apps/ssr-tests-v9/src/utils/getImportsFromIndexFile.ts
SSR tests did not work properly from some moment, so we got changes that are not compatible with SSR.
This PR improves ignore functionality, so we could ignore some stories and not only packages. Tests added ✅
=> chore(ssr-tests-v9): improve "ignore" functionality

change/@fluentui-react-charting-486639f0-e94f-4bd6-95ea-5023ca544688.json, packages/react-charting/src/components/AreaChart/AreaChart.base.tsx, packages/react-charting/src/components/AreaChart/AreaChart.test.tsx, packages/react-charting/src/components/AreaChart/AreaChart.types.ts, packages/react-charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap, packages/react-examples/src/react-charting/AreaChart/AreaChart.LargeData.Example.tsx, packages/react-examples/src/react-charting/AreaChart/AreaChart.Multiple.Example.tsx, packages/react-examples/src/react-charting/AreaChart/AreaChartPage.tsx
Data points in AreaChart are not accessible using keyboard
Data points in AreaChart are accessible using keyboard
=> Make area chart keyboard accessible

change/@fluentui-react-charting-e317987d-8fa3-420c-8d54-23b845313c19.json, packages/react-charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap, packages/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap, packages/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap, packages/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap, packages/react-charting/src/components/Legends/Legends.base.tsx, packages/react-charting/src/components/Legends/Legends.test.tsx, packages/react-charting/src/components/Legends/__snapshots__/Legends.test.tsx.snap, packages/react-charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap, packages/react-charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap, packages/react-charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap, packages/react-charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap, packages/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChart.test.tsx.snap
Screen reader announces wrong state information for legends
Screen reader announces correct state information for legends
=> Fix wrong narration for legend state

packages/react-charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap
=> test(react-charting): update snapshots

apps/ts-minbar-test-react/src/index.ts
- Fixes temporarily https://github.com/microsoft/fluentui/issues/27425
=> fix(ts-minbar-test-react): pin @types/react as temporary workaround for breaking changes introduced by definitely typed package

.github/CODEOWNERS
adds more granular rules to mitigate ownership of fluent-admins
=> ci: update codeowners file for v-build

change/@fluentui-web-components-23fff9de-b107-430a-b67b-d0d5f26212e1.json, packages/web-components/package.json, packages/web-components/src/index.ts, packages/web-components/src/toggle-button/define.ts, packages/web-components/src/toggle-button/index.ts, packages/web-components/src/toggle-button/toggle-button.definition.ts, packages/web-components/src/toggle-button/toggle-button.options.ts, packages/web-components/src/toggle-button/toggle-button.stories.ts, packages/web-components/src/toggle-button/toggle-button.styles.ts, packages/web-components/src/toggle-button/toggle-button.template.ts, packages/web-components/src/toggle-button/toggle-button.ts
=> add toggle button as new v3 web component

packages/react-components/react-drawer/etc/react-drawer.api.md, packages/react-components/react-drawer/src/components/Drawer/Drawer.types.ts, packages/react-components/react-drawer/src/components/Drawer/useDrawer.ts, packages/react-components/react-drawer/src/components/Drawer/useDrawerStyles.ts, packages/react-components/react-drawer/stories/Drawer/DrawerSeparator.stories.tsx, packages/react-components/react-drawer/stories/Drawer/index.stories.tsx
=> feat(react-drawer): implement a separator feature

change/@fluentui-react-card-a843b37d-b830-4092-8366-72ea1f893a33.json, packages/react-components/react-card/src/components/Card/useCardStyles.ts
Add support for High Contrast on react-card
- Fixes #27470
=> fix(react-card): add support for Windows High Contrast

change/@fluentui-react-toolbar-5faad9ba-f6d4-4d75-8d1d-6066eb81e377.json, packages/react-components/react-toolbar/package.json, packages/react-components/react-toolbar/src/components/Toolbar/renderToolbar.tsx, packages/react-components/react-toolbar/src/components/ToolbarGroup/renderToolbarGroup.tsx
Adopts `react-jsx-runtime` custom pragma on `react-toolbar`.
=> chore(react-toolbar): adopt custom JSX pragma

change/@fluentui-react-popover-23cf0582-3d79-48a6-9c84-5755ec1e89b5.json, packages/react-components/react-popover/package.json, packages/react-components/react-popover/src/components/PopoverSurface/renderPopoverSurface.tsx
Adopts `react-jsx-runtime` custom pragma on `react-popover`
=> feat(react-popover): adopt custom JSX pragma

change/@fluentui-react-data-grid-react-window-128a12e2-e75c-434a-97a2-0e7bd90cb1ae.json, packages/react-components/react-data-grid-react-window/package.json, packages/react-components/react-data-grid-react-window/src/components/DataGridBody/renderDataGridBody.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-data-grid-react-window`
=> chore(react-data-grid-react-window): adopt custom JSX pragma

change/@fluentui-react-alert-d8871ce1-c56c-4938-8322-697717c6160a.json, change/@fluentui-react-data-grid-react-window-7b969639-ce1d-417e-bc8a-07fbef28706a.json, change/@fluentui-react-dialog-a8221575-28db-40a9-9e34-fffaf0b1c9a8.json, change/@fluentui-react-menu-1936244e-b19e-46c3-b864-f0abc205741b.json, change/@fluentui-react-popover-1c3254b4-b7d6-4751-a471-21cb345897b2.json, change/@fluentui-react-provider-2698c8f2-b6a5-467a-b0b5-7acfa7061f49.json, change/@fluentui-react-table-af958513-1325-4780-aa3a-366aac56e366.json, change/@fluentui-react-toolbar-3fb5631d-7961-4f5d-833b-f67c45abb2c2.json, change/@fluentui-react-tree-331af5e5-0217-4fbb-b822-ce32d2abc90d.json, packages/react-components/react-alert/package.json, packages/react-components/react-data-grid-react-window/package.json, packages/react-components/react-dialog/package.json, packages/react-components/react-menu/package.json, packages/react-components/react-popover/package.json, packages/react-components/react-provider/package.json, packages/react-components/react-table/package.json, packages/react-components/react-toolbar/package.json, packages/react-components/react-tree/package.json
Follow up on https://github.com/microsoft/fluentui/pull/27475/files#r1168602757
=> bugfix(react-jsx-runtime): remove caret prerelease dependency

change/@fluentui-react-persona-715b7959-0b4a-4809-8352-f90cae51f735.json, packages/react-components/react-persona/package.json, packages/react-components/react-persona/src/components/Persona/renderPersona.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-persona`
=> chore(react-persona): adopt custom JSX pragma

change/@fluentui-react-infobutton-e7fc1c18-a501-42e1-9f8d-1615514e4389.json, packages/react-components/react-infobutton/package.json, packages/react-components/react-infobutton/src/components/InfoButton/renderInfoButton.tsx, packages/react-components/react-infobutton/src/components/InfoLabel/renderInfoLabel.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-infobutton`
=> chore(react-infobutton): adopt custom JSX pragma

change/@fluentui-react-accordion-0886e6c0-bf89-457f-a6c6-d81ecd0afd83.json, packages/react-components/react-accordion/package.json, packages/react-components/react-accordion/src/components/Accordion/renderAccordion.tsx, packages/react-components/react-accordion/src/components/AccordionHeader/renderAccordionHeader.tsx, packages/react-components/react-accordion/src/components/AccordionItem/renderAccordionItem.tsx, packages/react-components/react-accordion/src/components/AccordionPanel/renderAccordionPanel.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-accordion`
=> chore(react-accordion): adopt custom JSX pragma

change/@fluentui-react-radio-09d6ce4e-50b5-42eb-8eeb-48abbd376e3b.json, packages/react-components/react-radio/package.json, packages/react-components/react-radio/src/components/Radio/renderRadio.tsx, packages/react-components/react-radio/src/components/RadioGroup/renderRadioGroup.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-radio`
=> chore(react-radio): adopt custom JSX pragma

change/@fluentui-react-field-7f0d52e5-f210-49cc-ab18-b00851dae5f3.json, packages/react-components/react-field/package.json, packages/react-components/react-field/src/components/Field/renderField.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-field`
=> chore(react-field): adopt custom JSX pragma

change/@fluentui-react-button-902006f6-fd3b-4e4e-8507-e91a87a27c6a.json, packages/react-components/react-button/package.json, packages/react-components/react-button/src/components/Button/renderButton.tsx, packages/react-components/react-button/src/components/CompoundButton/renderCompoundButton.tsx, packages/react-components/react-button/src/components/MenuButton/renderMenuButton.tsx, packages/react-components/react-button/src/components/SplitButton/renderSplitButton.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-button`
=> chore(react-button): adopt custom JSX pragma

change/@fluentui-react-divider-f61b0198-f78d-46f3-8acc-760a2c09ebd3.json, packages/react-components/react-divider/package.json, packages/react-components/react-divider/src/components/Divider/renderDivider.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-divider`
=> chore(react-divider): adopt custom JSX pragma

change/@fluentui-react-combobox-c88c7426-46bc-4656-a996-cb168eab3b4f.json, packages/react-components/react-combobox/package.json, packages/react-components/react-combobox/src/components/Combobox/renderCombobox.tsx, packages/react-components/react-combobox/src/components/Dropdown/renderDropdown.tsx, packages/react-components/react-combobox/src/components/Listbox/renderListbox.tsx, packages/react-components/react-combobox/src/components/Option/renderOption.tsx, packages/react-components/react-combobox/src/components/OptionGroup/renderOptionGroup.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-combobox`
=> chore(react-combobox): adopt custom JSX pragma

change/@fluentui-react-progress-18add070-ef6f-4243-a047-9f018976ae46.json, packages/react-components/react-progress/package.json, packages/react-components/react-progress/src/components/ProgressBar/renderProgressBar.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-progress`
=> chore(react-progress): adopt custom JSX pragma

change/@fluentui-react-spinbutton-c521955b-8cc1-4786-8f8d-49f8eb81c4e5.json, packages/react-components/react-spinbutton/package.json, packages/react-components/react-spinbutton/src/components/SpinButton/renderSpinButton.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-spinbutton`
=> chore(react-spinbutton): adopt custom JSX pragma

change/@fluentui-react-virtualizer-08afe647-54bb-408b-adfc-52583d744249.json, packages/react-components/react-virtualizer/package.json, packages/react-components/react-virtualizer/src/components/Virtualizer/renderVirtualizer.tsx, packages/react-components/react-virtualizer/src/components/VirtualizerScrollView/renderVirtualizerScrollView.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-virtualizer`
=> chore(react-virtualizer): adopt custom JSX pragma

change/@fluentui-react-tree-8e9777b6-6274-44dd-b7ce-08b5886bec49.json, packages/react-components/react-tree/src/hooks/useOpenItemsState.ts
Follow up on https://github.com/microsoft/fluentui/pull/27682#discussion_r1177663928
=> chore(react-tree): updates useOpenItemsState internals

.github/CODEOWNERS
Move it to myself after discussion with @TristanWatanabe
=> chore: update codeowner of react-tag

change/@fluentui-react-monaco-editor-5e5821a7-444b-4bdc-b10c-0103cad5e0b8.json, packages/react-monaco-editor/package.json
v8 releases fail on lint error
v8 releases pass
- Fixes https://github.com/microsoft/fluentui/pull/27539
- Follows https://github.com/microsoft/fluentui/issues/27727
=> fix(react-charting): add missing dependency to fix lint violations during release

packages/react-components/react-breadcrumb/etc/react-breadcrumb.api.md, packages/react-components/react-breadcrumb/src/components/BreadcrumbLink/BreadcrumbLink.test.tsx, packages/react-components/react-breadcrumb/src/components/BreadcrumbLink/BreadcrumbLink.types.ts, packages/react-components/react-breadcrumb/src/components/BreadcrumbLink/useBreadcrumbLink.ts, packages/react-components/react-breadcrumb/src/components/BreadcrumbLink/useBreadcrumbLinkStyles.styles.ts, packages/react-components/react-breadcrumb/stories/BreadcrumbLink/BreadcrumbLinkDefault.stories.tsx
=> UI adjustments  for BreadcrumbLink component

scripts/generators/create-component/plop-templates/src/components/{{componentName}}/render{{componentName}}.tsx.hbs
Updates plop template from `create-component` generator script to use new custom jsx.
=> chore(react-jsx-runtime): update create-component plop template

packages/react-components/react-breadcrumb/src/components/Breadcrumb/Breadcrumb.test.tsx, packages/react-components/react-breadcrumb/src/components/BreadcrumbButton/BreadcrumbButton.test.tsx, packages/react-components/react-breadcrumb/src/components/BreadcrumbDivider/BreadcrumbDivider.test.tsx, packages/react-components/react-breadcrumb/src/components/BreadcrumbItem/BreadcrumbItem.test.tsx, packages/react-components/react-breadcrumb/src/components/BreadcrumbLink/BreadcrumbLink.test.tsx
=> Added more snapshot tests to the Breadcrumb component

.github/CODEOWNERS
Add 'spmonahan' to owner of List-related components.
=> chore: Updating Github CODEOWNERS file to include spmonahan as owner of List-related components

rfcs/TEMPLATE.md
No date was tracked as part of the RFC document.
There is now a date field on the RFC which will help place an RFC in time.
=> chore: update RFC template

change/@fluentui-react-migration-v0-v9-0e25a9e6-8ee2-4b03-b02f-8c36bbd82546.json, packages/react-components/react-migration-v0-v9/package.json
Initial release of @fluentui/react-migration-v0-v9
=> feat(react-v0-v9-migration): Initial release

apps/recipes-react-components/src/recipes/media-object/MediaObject.stories.mdx
This change was missing from the rework of the templates.
=> fix(recipes-react-components): Update Example to TemplateExample

packages/react-components/react-breadcrumb/stories/Breadcrumb/BreadcrumbBestPractices.md, packages/react-components/react-breadcrumb/stories/Breadcrumb/BreadcrumbDescription.md, packages/react-components/react-breadcrumb/stories/BreadcrumbButton/BreadcrumbButtonBestPractices.md, packages/react-components/react-breadcrumb/stories/BreadcrumbButton/BreadcrumbButtonDescription.md, packages/react-components/react-breadcrumb/stories/BreadcrumbDivider/BreadcrumbDividerBestPractices.md, packages/react-components/react-breadcrumb/stories/BreadcrumbDivider/BreadcrumbDividerDescription.md, packages/react-components/react-breadcrumb/stories/BreadcrumbItem/BreadcrumbItemBestPractices.md, packages/react-components/react-breadcrumb/stories/BreadcrumbItem/BreadcrumbItemDescription.md, packages/react-components/react-breadcrumb/stories/BreadcrumbLink/BreadcrumbLinkBestPractices.md, packages/react-components/react-breadcrumb/stories/BreadcrumbLink/BreadcrumbLinkDescription.md
=> Added best practices for the Breadcrumb

apps/public-docsite-v9/package.json, apps/public-docsite-v9/src/Concepts/ThemeDesigner.stories.mdx
There's no theme designer in our docs.
Theme designer has been added to our docs.th
=> feat(public-docsite-v9): Adding Theme Designer to docs

.github/CODEOWNERS
Updating code owners for charting files in react-examples folder
- Fixes #
=> Updating codeowners for the charting files in react-examples

apps/public-docsite-v9/package.json, packages/react-components/theme-designer/README.md, packages/react-components/theme-designer/package.json
Theme Designer is currently unstable as it is marked in alpha.
Theme Designer is now stable.
=> feat(theme-designer): Move theme-designer to stable

change/@fluentui-react-card-a1dedbc1-bc08-43de-bf35-2ae167697178.json, packages/react-components/react-card/src/components/Card/useCardStyles.styles.ts
=> fix: make the selected styles have higher priority

scripts/test-ssr/src/commands/main.ts
Master is 🔴 
Master is 🟢 
Issue to follow up #27957.
=> chore: disable SSR tests for @fluentui/react-datepicker-compat

apps/vr-tests-react-components/src/stories/Positioning.stories.tsx
Rework of #21878. Adds a visual tests that ensures that scroll jump after focus don't happen for positioned elements.
=> chore: Add positioning test for scroll jumps

packages/react-components/react-colorpicker-compat/package.json
- updates `@fluentui/react-conformance-griffel` and `@fluentui/react-jsx-runtime` dependencies of newly merged in package `react-colorpicker-compat` to match the rest of the repo. 
Fixes broken master branch: https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=304731&view=results
=> fix: broken master branch

azure-pipelines.yml
No SBOM on azure-pipelines.yml
SBOM on azure-pipelines.yml which is required for compliance
=> Add SBOM Manifest to azure-pipelines.yml

packages/react-components/react-toolbar/stories/Toolbar/ToolbarOverflow.stories.tsx
=> Fix typo in the documentation

change/@fluentui-react-charting-732ba88e-6417-4ecf-acf0-b9146fbbe5a2.json, packages/react-charting/src/components/HorizontalBarChartWithAxis/HorizontalBarChartWithAxis.base.tsx, packages/react-charting/src/components/HorizontalBarChartWithAxis/__snapshots__/HorizontalBarChartWithAxis.test.tsx.snap
=> Fixing bug for HBCWA for string variant

change/@fluentui-web-components-7e0e66c4-c03c-4446-b95e-c785fa75cd4f.json, packages/web-components/docs/api-report.md, packages/web-components/src/index.ts
=> feat: export fluent design system from package

change/@fluentui-react-infobutton-399b6ea2-7d94-4b6c-8efc-3068ae6d59ed.json, packages/react-components/react-infobutton/etc/react-infobutton.api.md, packages/react-components/react-infobutton/src/InfoIconLabel.ts, packages/react-components/react-infobutton/src/components/InfoIconLabel/InfoIconLabel.test.tsx, packages/react-components/react-infobutton/src/components/InfoIconLabel/InfoIconLabel.tsx, packages/react-components/react-infobutton/src/components/InfoIconLabel/InfoIconLabel.types.ts, packages/react-components/react-infobutton/src/components/InfoIconLabel/__snapshots__/InfoIconLabel.test.tsx.snap, packages/react-components/react-infobutton/src/components/InfoIconLabel/index.ts, packages/react-components/react-infobutton/src/components/InfoIconLabel/renderInfoIconLabel.tsx, packages/react-components/react-infobutton/src/components/InfoIconLabel/useInfoIconLabel.ts, packages/react-components/react-infobutton/src/components/InfoIconLabel/useInfoIconLabelStyles.styles.ts, packages/react-components/react-infobutton/src/index.ts, packages/react-components/react-infobutton/stories/InfoIconLabel/InfoIconLabelBestPractices.md, packages/react-components/react-infobutton/stories/InfoIconLabel/InfoIconLabelDefault.stories.tsx, packages/react-components/react-infobutton/stories/InfoIconLabel/index.stories.tsx
This PR creates the scaffold for InfoIconLabel which will contain the component we will export for InfoIcon's implementation.
=> chore(react-infobutton): Create InfoIconLabel component scaffold

change/@fluentui-react-migration-v8-v9-ffc4dee0-395d-4a18-b36b-6a5d0a411888.json, packages/react-components/react-migration-v8-v9/package.json
Fix dependencies mismatches after release
=> chore: upgrade dependencies version

apps/public-docsite-v9/package.json, apps/stress-test/package.json
mismatches fixed - master will be green again
- Follows https://github.com/microsoft/fluentui/pull/28345
=> fix: update dependency mismatches introduced within apps after v8 release

packages/react-components/react-toast/etc/react-toast.api.md, packages/react-components/react-toast/src/components/Toast/Toast.cy.tsx, packages/react-components/react-toast/src/state/constants.ts, packages/react-components/react-toast/src/state/types.ts, packages/react-components/react-toast/src/state/useToastController.test.ts, packages/react-components/react-toast/src/state/useToastController.ts, packages/react-components/react-toast/src/state/useToaster.ts, packages/react-components/react-toast/src/state/vanilla/index.ts, packages/react-components/react-toast/src/state/vanilla/pauseToast.ts, packages/react-components/react-toast/src/state/vanilla/playToast.ts, packages/react-components/react-toast/stories/Toast/PauseAndPlay.stories.tsx, packages/react-components/react-toast/stories/Toast/index.stories.tsx
Toasts can be imperatively paused/played using the `useToastController` hook.
=> feat: Add imperative pause/play for toasts

change/@fluentui-react-migration-v8-v9-840b190e-224c-499c-9981-b67bc149c2d9.json, packages/react-components/react-migration-v8-v9/package.json
=> chore: updates dependencies version

change/@fluentui-react-components-9e598a44-ad8f-4c55-ae2c-f4a52b0f6950.json, packages/react-components/react-components/etc/react-components.api.md, packages/react-components/react-components/src/index.ts
This PR re-exports GriffelResetStyle type.
=> feat(react-components): re-export GriffelResetStyle type

packages/react-components/react-toast/bundle-size/Toast.fixture.js, packages/react-components/react-toast/package.json
=> chore: Add bundle size fixtures for Toast

packages/react-components/react-dialog/stories/Dialog/DialogNoFocusableElement.md
Improves documentation on the `No Focusable Element` scenario, describing the case of lazy loading content
- Fixes https://github.com/microsoft/fluentui/issues/28371
=> docs(react-dialog): improves lazy loading content docs

packages/react-components/react-tree/stories/D_flatTree/Virtualization.md, packages/react-components/react-tree/stories/D_flatTree/Virtualization.stories.tsx
Improves `Virtualization` scenario documentations, to make it clear that `Tree` components by default does not support virtualization out of the box, but it does support integration with other 3rd-party libraries such as `react-window`
- Fixes #
=> docs(react-tree): improves virtualization documentation

packages/react-components/react-checkbox/docs/Spec.md
=> fix: Checkbox spec link to types

change/@fluentui-react-1bfa8a90-561a-4e64-8e83-a3c136b5cefc.json, change/@fluentui-react-datepicker-compat-b135d6a8-684d-4397-b4d6-66c1c7591b68.json, packages/react-components/react-datepicker-compat/src/components/Calendar/useCalendarStyles.styles.ts, packages/react/src/components/Calendar/Calendar.styles.ts
|v8|v9|
|---|---|
|![image](https://github.com/microsoft/fluentui/assets/5953191/3447d96d-61bc-4d87-bff3-cf5797c5f5de)|![image](https://github.com/microsoft/fluentui/assets/5953191/d10131a0-8a62-40b3-a8b9-feee705f6d43)|
|v8|v9|
|---|---|
|![image](https://github.com/microsoft/fluentui/assets/5953191/650e1c08-40f3-4214-b925-20a54d7fd913)|![image](https://github.com/microsoft/fluentui/assets/5953191/49224005-37ba-442a-a75e-dbf471d4ea8c)|
- Fixes #27948
=> fix(react-datepicker-compat, Calendar): Add hover styles for gototoday button

azure-pipelines.vrt-baseline.yml
The baseline and vrt pipeline were failing due to pipelineId.
I have added pipelineId.
- Fixes #
=> [VR-Approval-Cli] Fixed the Bug & Added the pipelineID

azure-pipelines.vrt-baseline-web-components.yml, download-vr-cli.yml
Earlier we were using the old version of vr-approval-cli to upload baseline screenshots.
This pr will use the general version of vr-approval-cli.
- Fixes #
revert this pr.
=> Onboard generalized version of VRT to upload baseline screenshots for web-components-v3

azure-pipelines.vrt-baseline-v7.yml, download-vr-cli.yml
Earlier we were using the old version of vr-approval-cli to upload baseline screenshots.
This pr will use the general version of vr-approval-cli.
- Fixes #
revert this pr.
=> Onboard generalized version of VRT to upload baseline screenshots for fluentui-v7

azure-pipelines.vrt-pr.yml
Earlier we were using the old version of vr-approval-cli for screenshots diffing.
This PR will use the latest version of vr-approval-cli.
- Fixes #
revert this pr.
=> Onboarding the generalized VRT for fluentui-v7

scripts/beachball/shared.config.ts, tools/generators/dependency-mismatch/index.spec.ts, tools/generators/dependency-mismatch/index.ts, tools/utils.ts
exec time: 45s
exec time: 4.7s
- Follows  https://github.com/microsoft/fluentui/pull/28584
=> perf(tools): make dependency-mismatch execution 90% faster and ignore */>=9.0.0-alpha versions

change/@fluentui-react-breadcrumb-preview-54642078-ea6a-4423-8ea0-f5598e93fadb.json, packages/react-components/react-breadcrumb-preview/README.md, packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/useBreadcrumbItem.ts, packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbLinkWithOverflow.stories.tsx
- MenuItem was used for overflow logic in BreadcrumbLink component
- There's new feature in Menu - MenuItemLink. I replaced it for BreadcrumbLink with overflow
- Added more content to the Readme
=> Added more content to Breadcrumb Readme and replaced MenuItem

apps/public-docsite-v9/package.json, change/@fluentui-react-tags-preview-7c233ae6-998d-44ce-811e-7f13798be096.json, packages/react-components/react-tags-preview/package.json
=> release react-tags-preview package

change/@fluentui-react-tree-c65bb12d-453d-4ee3-910d-058cfa260cd3.json, packages/react-components/react-tree/bundle-size/FlatTree.fixture.js, packages/react-components/react-tree/bundle-size/PersonaFlatTree.fixture.js, packages/react-components/react-tree/bundle-size/PersonaTree.fixture.js, packages/react-components/react-tree/bundle-size/Tree.fixture.js, packages/react-components/react-tree/package.json
Adds bundle size fixtures 
- Fixes https://github.com/microsoft/fluentui/issues/28691
=> chore: adds bundle size metrics

change/@fluentui-react-tree-b193406e-6c58-4917-87c4-ac56dfed66c7.json, packages/react-components/react-tree/src/components/TreeItemLayout/useTreeItemLayout.tsx
1. adds role `toolbar` to actions slot
2. adds horizontal keyboard navigation on actions
- Fixes #
=> feat: converts actions to be a toolbar

change/@fluentui-web-components-35d1595b-342c-400a-a331-1cb2ec426f6e.json, packages/web-components/src/menu-item/README.md
=> Chore: trigger WC CI

apps/vr-tests-react-components/package.json, apps/vr-tests-react-components/src/stories/Tree.stories.tsx
1. adds Visual Regression tests to `react-tree` visual components
- Fixes https://github.com/microsoft/fluentui/issues/28644
=> chore(react-tree): creates VR tests

change/@fluentui-react-theme-sass-dfff171a-a27b-4f09-837c-a004d44ea1a7.json, change/@fluentui-tokens-2063982d-3baa-4165-b112-f29289d8b1a9.json, packages/react-components/react-theme-sass/sass/durationTokens.scss, packages/tokens/etc/tokens.api.md, packages/tokens/src/global/durations.ts, packages/tokens/src/tokens.ts, packages/tokens/src/types.ts
Add `durationGentle` theme token.
Fixes #28715.
=> feat(tokens): add durationGentle token

change/@fluentui-react-migration-v0-v9-3419eb00-06e4-40ff-a0be-ff3c14b16bad.json, packages/react-components/react-migration-v0-v9/src/components/ItemLayout/ItemLayout.tsx
1. Migrates `react-migration-v0-v9`  package to new slot API
=> chore(react-migration-v0-v9): migrate to new slot API

change/@fluentui-react-virtualizer-5ec0e1ef-f7b0-4c31-a820-f81ef0045c4c.json, packages/react-components/react-virtualizer/src/components/Virtualizer/renderVirtualizer.tsx, packages/react-components/react-virtualizer/src/components/Virtualizer/useVirtualizer.ts, packages/react-components/react-virtualizer/src/components/VirtualizerScrollView/renderVirtualizerScrollView.tsx, packages/react-components/react-virtualizer/src/components/VirtualizerScrollView/useVirtualizerScrollView.ts, packages/react-components/react-virtualizer/src/components/VirtualizerScrollViewDynamic/renderVirtualizerScrollViewDynamic.tsx, packages/react-components/react-virtualizer/src/components/VirtualizerScrollViewDynamic/useVirtualizerScrollViewDynamic.ts
1. Migrates `react-virtualizer`  package to new slot API
=> chore(react-virtualizer): migrate to new slot API

apps/vr-tests-web-components/src/stories/avatar/avatar.stories.tsx
Add screenshot tests for `fluent-avatar`
=> chore(fluent-avatar): Add screenshot tests

packages/react-components/react-datepicker-compat/stories/DatePicker/DatePickerDescription.md
Adding a note to date picker component to clarify the scope of compat components
=> Update DatePickerDescription.md with note about compat components

packages/react-components/react-tree/stories/Tree/TreeA11y.md, packages/react-components/react-tree/stories/Tree/index.stories.tsx
1. adds all known a11y issues (https://github.com/microsoft/fluentui/issues/28785#issuecomment-1680181113) to the docs 
- Fixes #
=> doc(react-tree): adds a11y edge cases to the docs

change/@fluentui-react-tags-preview-09dbf8b9-21ed-4d52-bf01-dc6c4bf14a91.json, packages/react-components/react-tags-preview/README.md, packages/react-components/react-tags-preview/src/components/InteractionTag/InteractionTag.types.ts, packages/react-components/react-tags-preview/src/components/InteractionTagPrimary/InteractionTagPrimary.types.ts, packages/react-components/react-tags-preview/src/components/Tag/Tag.types.ts, packages/react-components/react-tags-preview/stories/InteractionTag/InteractionTagBestPractices.md, packages/react-components/react-tags-preview/stories/InteractionTag/InteractionTagDescription.md, packages/react-components/react-tags-preview/stories/Tag/TagBestPractices.md, packages/react-components/react-tags-preview/stories/TagGroup/TagGroupBestPractices.md
=> chore(react-tags-preview): add docs 

packages/web-components/src/switch/switch.spec.ts
Adds tests for Switch Component
=> Adds tests for Switch Component

apps/vr-tests-web-components/src/stories/progress-bar/progress-bar.stories.tsx
Add screenshot tests for `fluent-progress-bar`
=> chore(progress-bar): Add screenshot tests

apps/vr-tests-web-components/src/stories/label/label.stories.tsx
Add screenshot tests for `fluent-label`
=> chore(label): Add screenshot tests

apps/vr-tests-web-components/src/stories/checkbox/checkbox-indeterminate.stories.tsx, apps/vr-tests-web-components/src/stories/checkbox/checkbox.stories.tsx
Add screenshot tests for `fluent-checkbox`
=> chore(checkbox): Add screenshot tests

apps/vr-tests-web-components/src/stories/menu-list/menu-list.stories.tsx
Add screenshot tests for `fluent-menu-list`
=> chore(menu-list): Add screenshot tests

tools/workspace-plugin/src/generators/react-component/files/component/render__componentName__.tsx__tmpl__, tools/workspace-plugin/src/generators/react-component/files/component/use__componentName__.ts__tmpl__
1. updates generator to use new slot API
- Fixes #
=> chore: updates generator to use new slot API

packages/web-components/src/divider/divider.spec.ts
Adds Playwright tests for Fluent Divider web component.
=> Adds Tests For Fluent Divider Web Component 

.github/CODEOWNERS
=> chore: update CODEOWNERS to some components to tag the current owner

apps/vr-tests-web-components/package.json, change/@fluentui-web-components-2f4b6058-a642-437e-adf0-85fdeb5fe68c.json, packages/web-components/package.json
Bumping web-components-v3 to `beta` 🎉
=> feat: Bump version to beta

packages/react-components/react-tags-preview/stories/TagGroup/TagGroupDismiss.stories.tsx
Tag stories should have aria-label for dismiss on dismiss icon.
=> chore(react-tags-preview): update tagGroup dismiss story to have proper aria label

change/@fluentui-react-icons-mdl2-branded-1e32e164-92ff-49d6-8ab9-7a9c8270133b.json, packages/react-icons-mdl2-branded/src/components/VivaEngageIcon.tsx, packages/react-icons-mdl2-branded/src/index.ts
This PR is to move the `VivaEngageIcon` to the proper package.
=> feat(react-icons-mdl2-branded): Add VivaEngageIcon

change/@fluentui-react-spinner-08070866-8e5b-4438-a02f-3eeec8e27fb6.json, packages/react-components/react-spinner/src/components/Spinner/useSpinnerStyles.styles.ts
=> feat: Update Spinner appearance token

change/@fluentui-react-tags-preview-dc347c41-7d4f-4d1c-8915-938cbbadba34.json, packages/react-components/react-tags-preview/src/components/InteractionTag/useInteractionTagStyles.styles.ts, packages/react-components/react-tags-preview/src/components/InteractionTagPrimary/useInteractionTagPrimaryStyles.styles.ts, packages/react-components/react-tags-preview/src/components/InteractionTagSecondary/useInteractionTagSecondaryStyles.styles.ts, packages/react-components/react-tags-preview/src/components/Tag/useTagStyles.styles.ts
move base styles to makeResetStyles
=> chore(react-tags-preview): use makeResetStyles for base styles

apps/public-docsite-v9/src/Utilities/Motion/useMotion/index.stories.mdx, packages/react-components/react-drawer/stories/Drawer/DrawerMotionCustom.stories.tsx, packages/react-components/react-drawer/stories/Drawer/DrawerMotionDisabled.stories.tsx, packages/react-components/react-drawer/stories/Drawer/index.stories.tsx
=> docs(react-drawer): add examples on how to customize motion for Drawer

change/@fluentui-react-jsx-runtime-74cf5d31-e90b-4a38-9995-a8108bd107e2.json, packages/react-components/react-jsx-runtime/just.config.ts, packages/react-components/react-jsx-runtime/src/jsx-dev-runtime.d.ts, packages/react-components/react-jsx-runtime/src/jsx-runtime.d.ts
1. updates just build to include `.d.ts` files in the `dist` folder
- Fixes #29086
=> bugfix: fix missing types on import source

packages/react-components/react-nav-preview/etc/react-nav-preview.api.md, packages/react-components/react-nav-preview/src/NavLink.ts, packages/react-components/react-nav-preview/src/NavLinkGroup.ts, packages/react-components/react-nav-preview/src/components/NavLink/NavLink.test.tsx, packages/react-components/react-nav-preview/src/components/NavLink/NavLink.tsx, packages/react-components/react-nav-preview/src/components/NavLink/NavLink.types.ts, packages/react-components/react-nav-preview/src/components/NavLink/__snapshots__/NavLink.test.tsx.snap, packages/react-components/react-nav-preview/src/components/NavLink/index.ts, packages/react-components/react-nav-preview/src/components/NavLink/renderNavLink.tsx, packages/react-components/react-nav-preview/src/components/NavLink/useNavLink.ts, packages/react-components/react-nav-preview/src/components/NavLink/useNavLinkStyles.styles.ts, packages/react-components/react-nav-preview/src/components/NavLinkGroup/NavLinkGroup.test.tsx, packages/react-components/react-nav-preview/src/components/NavLinkGroup/NavLinkGroup.tsx, packages/react-components/react-nav-preview/src/components/NavLinkGroup/NavLinkGroup.types.ts, packages/react-components/react-nav-preview/src/components/NavLinkGroup/__snapshots__/NavLinkGroup.test.tsx.snap, packages/react-components/react-nav-preview/src/components/NavLinkGroup/index.ts, packages/react-components/react-nav-preview/src/components/NavLinkGroup/renderNavLinkGroup.tsx, packages/react-components/react-nav-preview/src/components/NavLinkGroup/useNavLinkGroup.ts, packages/react-components/react-nav-preview/src/components/NavLinkGroup/useNavLinkGroupStyles.styles.ts, packages/react-components/react-nav-preview/src/index.ts, packages/react-components/react-nav-preview/stories/NavLink/NavLinkBestPractices.md, packages/react-components/react-nav-preview/stories/NavLink/NavLinkDefault.stories.tsx, packages/react-components/react-nav-preview/stories/NavLink/index.stories.tsx, packages/react-components/react-nav-preview/stories/NavLinkGroup/NavLinkGroupBestPractices.md, packages/react-components/react-nav-preview/stories/NavLinkGroup/NavLinkGroupDefault.stories.tsx, packages/react-components/react-nav-preview/stories/NavLinkGroup/index.stories.tsx
Scaffolds NavLink and NavLinkGroup components.
=> Scaffolds NavLink and NavLinkGroup

azure-pipelines.vrt-pr.yml
- updates `client_id` to use secret variable stored in pipeline
- adds new `VR_APP_CLIENT_URL` variable and uses that instead
=> fix(VRT): update to use environment variable

azure-pipelines.vrt-pr.yml
- updates `client_id` to use secret variable stored in pipeline
- adds new `VR_APP_CLIENT_URL` variable and uses that instead
cherry-pick of #29146
=> fix(VRT v7): update to use environment variable

.github/ISSUE_TEMPLATE/convergence_epic.md
The template for the component Epic issue referenced the old method for unstable releases of components.
Update the Epic template to outline the new steps required. This is also paired with an update to the Component Implementation Guide wiki article: https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide/_compare/c62f50b76df8c13396a2b19bb6cbf13aed72d3ea
- Fixes #28466
=> chore: Update v9 Epic issue template for new package release process

packages/react-components/react-tags-preview/stories/InteractionTag/InteractionTagDismiss.stories.tsx, packages/react-components/react-tags-preview/stories/InteractionTag/InteractionTagMedia.md, packages/react-components/react-tags-preview/stories/InteractionTag/InteractionTagMedia.stories.tsx, packages/react-components/react-tags-preview/stories/Tag/TagDismiss.stories.tsx, packages/react-components/react-tags-preview/stories/TagGroup/TagGroupDismiss.stories.tsx
Add more story description. Please see the changes.
=> chore(react-tags-preview): tiny fixes on stories to make it more accessible

change/@fluentui-react-tags-preview-d2da4b4e-b770-45e4-b1b1-2f52da2d1a37.json, packages/react-components/react-tags-preview/cypress.config.ts, packages/react-components/react-tags-preview/package.json, packages/react-components/react-tags-preview/src/components/TagGroup/TagGroup.cy.tsx, packages/react-components/react-tags-preview/tsconfig.cy.json, packages/react-components/react-tags-preview/tsconfig.json, packages/react-components/react-tags-preview/tsconfig.lib.json
Add cypress test for dismiss tags
=> chore(react-tags-preview): add cypress test for dismiss

change/@fluentui-react-drawer-acebb572-ecff-43ab-a690-b88362121ae8.json, packages/react-components/react-drawer/src/components/DrawerFooter/DrawerFooter.tsx, packages/react-components/react-drawer/src/components/DrawerHeaderNavigation/DrawerHeaderNavigation.test.tsx, packages/react-components/react-drawer/src/components/DrawerHeaderTitle/DrawerHeaderTitle.test.tsx, packages/react-components/react-drawer/src/components/DrawerInline/DrawerInline.test.tsx
=> fix(react-drawer): resolve TODOs

packages/react-components/react-tags-preview/stories/InteractionTag/InteractionTagBestPractices.md, packages/react-components/react-tags-preview/stories/InteractionTag/InteractionTagDisabled.stories.tsx, packages/react-components/react-tags-preview/stories/InteractionTag/InteractionTagHasPrimaryAction.stories.tsx, packages/react-components/react-tags-preview/stories/InteractionTag/InteractionTagSize.stories.tsx, packages/react-components/react-tags-preview/stories/Tag/TagBestPractices.md, packages/react-components/react-tags-preview/stories/Tag/TagDisabled.stories.tsx
1. Capitalize first letter in tag stories
2. Remove custom heart icon in 'has primary action' story because the recommendation is to not have other actions apart from dismiss: 
- before: <img width="218" alt="image" src="https://github.com/microsoft/fluentui/assets/28751745/06b214cd-d499-459a-9225-5226e3d9e3ad">
- after: <img width="220" alt="image" src="https://github.com/microsoft/fluentui/assets/28751745/f5dd2a39-74b0-448e-a4c4-5554a193db30">
=> chore(react-tags-preview): small updates in stories

packages/react-examples/src/react-charting/HeatMapChart/HeatMapChartBasic.CustomAccessibility.Example.tsx, packages/react-examples/src/react-charting/HeatMapChart/HeatMapChartBasic.Example.tsx
=> Update heatmap chart examples

change/@fluentui-react-message-bar-preview-61fbedf2-6e27-44a3-9ab7-a8e3eac0c3c9.json, change/@fluentui-react-provider-acac6f65-b3a3-4841-885e-5ad19aa00b25.json, change/@fluentui-react-shared-contexts-4931df49-f3ed-465d-ae2d-c6fc63546694.json, packages/react-components/react-message-bar-preview/src/components/MessageBar/MessageBar.tsx, packages/react-components/react-message-bar-preview/src/components/MessageBarActions/MessageBarActions.tsx, packages/react-components/react-message-bar-preview/src/components/MessageBarBody/MessageBarBody.tsx, packages/react-components/react-message-bar-preview/src/components/MessageBarGroup/MessageBarGroup.tsx, packages/react-components/react-message-bar-preview/src/components/MessageBarTitle/MessageBarTitle.tsx, packages/react-components/react-provider/etc/react-provider.api.md, packages/react-components/react-shared-contexts/etc/react-shared-contexts.api.md, packages/react-components/react-shared-contexts/src/CustomStyleHooksContext/CustomStyleHooksContext.ts
=> fix: Add custom style hooks to MessageBar components

packages/react-components/react-message-bar-preview/stories/MessageBar/Animation.stories.tsx, packages/react-components/react-message-bar-preview/stories/MessageBar/Default.stories.tsx, packages/react-components/react-message-bar-preview/stories/MessageBar/Dismiss.stories.tsx, packages/react-components/react-message-bar-preview/stories/MessageBar/ManualLayout.stories.tsx, packages/react-components/react-message-bar-preview/stories/MessageBar/Reflow.stories.tsx, packages/react-components/react-message-bar-preview/stories/MessageBar/index.stories.tsx
* Add aria-labels to dismiss buttons
* Warn about limitations of animations
* Add subcomponent pages
Fixes #29430
=> docs: MessageBar doc improvements

tools/workspace-plugin/src/generators/react-component/files/component/__componentName__.tsx__tmpl__, tools/workspace-plugin/src/generators/react-component/index.spec.ts
=> chore: Add custom style hook to component generation templates

scripts/tasks/src/eslint.ts, tools/workspace-plugin/src/generators/react-component/index.spec.ts, tools/workspace-plugin/src/generators/react-component/index.ts
- see PR description
-  tl;dr: we will remove `stories/.gitkeep` on first component generation. This will enable eslint to run on `<project-path>/stories` as well
- removes existing gitkeep on `/stories` folder that have no purpose
- Fixes https://github.com/microsoft/fluentui/issues/29484
=> fix(scripts-tasks): don't run lint on stories/ within component package if its empty

change/@fluentui-react-message-bar-d036cd89-cf75-4640-a7f1-5953f14eff4d.json, packages/react-components/react-message-bar/README.md, packages/react-components/react-message-bar/bundle-size/Default.fixture.js, packages/react-components/react-message-bar/package.json
Also adds a usable README for the package
Addresses #22579
=> chore Add bundle size fixture for MessageBar

.codesandbox/ci.json, packages/utilities/etc/utilities.api.md, packages/utilities/src/index.ts
=> temporarily deploy utilities

change/@fluentui-react-tabster-03d5de11-4cf1-44e5-855d-a1651aa12b85.json, packages/react-components/react-tabster/package.json, yarn.lock
=> chore: bump keyborg to 2.1.0

change/@fluentui-react-charting-1907d6e0-fb40-404a-85a0-821cbba5fa69.json, packages/react-charting/src/utilities/utilities.ts
=> Fix for improper y axis scaling in LineChart

change/@fluentui-react-charting-33ba8fd5-9287-4363-9881-d8983182eb98.json, packages/react-charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap, packages/react-charting/src/components/AreaChart/__snapshots__/AreaChartRTL.test.tsx.snap, packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx, packages/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap, packages/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChartRTL.test.tsx.snap, packages/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap, packages/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChartRTL.test.tsx.snap, packages/react-charting/src/components/HorizontalBarChartWithAxis/__snapshots__/HorizontalBarChartWithAxis.test.tsx.snap, packages/react-charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap, packages/react-charting/src/components/LineChart/__snapshots__/LineChartRTL.test.tsx.snap, packages/react-charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap, packages/react-charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChartRTL.test.tsx.snap, packages/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChart.test.tsx.snap, packages/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChartRTL.test.tsx.snap
Adding a default tabbable element to fix accessibility issue bug-8860
- Fixes #
=> Adding a default tabbable element to fix accessibility issue bug-8860

change/@fluentui-react-menu-6f0df545-1e6e-4367-8795-4f5e52b260db.json, packages/react-components/react-menu/src/components/MenuItem/useMenuItemStyles.styles.ts
=> refactor: MenuItem uses makeResetStyles

change/@fluentui-react-drawer-fe9759ac-50af-4a94-8963-0e773f120bc6.json, packages/react-components/react-drawer/src/components/DrawerFooter/useDrawerFooterStyles.styles.ts, packages/react-components/react-drawer/src/components/DrawerHeader/useDrawerHeaderStyles.styles.ts, packages/react-components/react-drawer/stories/Drawer/DrawerMultipleLevels.stories.tsx, packages/react-components/react-drawer/stories/Drawer/index.stories.tsx
Creates a new Storybook example on how to create a multi-level Drawer
=> docs(react-drawer): add example of multiple levels inside one drawer

.devops/templates/compliance-job.yml, azure-pipelines.hotfix.yml, azure-pipelines.release-fluentui.yml, azure-pipelines.release-vnext-nightly.yml, azure-pipelines.release-vnext.yml, azure-pipelines.release.yml, azure-pipelines.yml
Bad pipeline code
restored pipeline code
=> Rever accidentally pushed pipeline changes

packages/react-components/react-components/stories/Concepts/FocusManagement/useArrowNavigationGoup/Axis.stories.tsx
PR flow tips:
-->
```
grid-liear - same as grid navigation, but horizontal focus will continue to flow to the next row
```
```
grid-linear - same as grid navigation, but horizontal focus will continue to flow to the next row
```
=> Fixing the mistake in useArrowNavigationGroup - axis values in the doc

change/@fluentui-react-timepicker-compat-preview-e27ebba5-b348-42a4-9883-fe63d2b03d92.json, packages/react-components/react-timepicker-compat-preview/bundle-size/TimePicker.fixture.js, packages/react-components/react-timepicker-compat-preview/package.json
=> chore(TimePicker-compat): add bundle size fixture

change/@fluentui-react-timepicker-compat-preview-d5c8ffdd-ec79-4a4f-8ef2-b6d7fffe23c3.json, packages/react-components/react-timepicker-compat-preview/cypress.config.ts, packages/react-components/react-timepicker-compat-preview/package.json, packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.cy.tsx, packages/react-components/react-timepicker-compat-preview/tsconfig.cy.json, packages/react-components/react-timepicker-compat-preview/tsconfig.json, packages/react-components/react-timepicker-compat-preview/tsconfig.lib.json
=> chore(TimePicker-compat): add cypress tests

packages/react-components/react-message-bar/docs/Spec.md
=> Spec: Adds MessageBar spec

change/@fluentui-react-components-1db49593-949c-4e0e-a89b-0ba31da355ba.json, change/@fluentui-react-portal-d0c1dba1-8f08-4acd-9eac-58093efaa838.json, packages/react-components/react-components/etc/react-components.api.md, packages/react-components/react-components/src/index.ts, packages/react-components/react-portal/etc/react-portal.api.md, packages/react-components/react-portal/src/index.ts
Exposing toMountNodeProps fn in react-components
N/A
=> Export toMountNodeProps in react-components

change/@fluentui-react-tabster-d0e2c8ee-501e-4212-8e10-b5f07715ec05.json, packages/react-components/react-tabster/package.json, yarn.lock
Improving how Tabster uncontrolled areas are handled for better interop with third party focus management tools like FocusZone.
=> Tabster 5.0.1

change/@fluentui-react-breadcrumb-6094ed11-f798-4faa-8c7d-ae1763210137.json, packages/react-components/react-breadcrumb/README.md, packages/react-components/react-breadcrumb/stories/Breadcrumb/BreadcrumbDefault.stories.tsx
Removed preview from all the links in the Breadcrumb
=> docs(breadcrumb): removed preview from all the links

packages/react-components/react-button/stories/SplitButton/SplitButtonIcon.stories.tsx, packages/react-components/react-button/stories/SplitButton/SplitButtonSizeLarge.stories.tsx, packages/react-components/react-button/stories/SplitButton/SplitButtonSizeMedium.stories.tsx, packages/react-components/react-button/stories/SplitButton/SplitButtonSizeSmall.stories.tsx, packages/react-components/react-button/stories/ToggleButton/ToggleButtonIcon.stories.tsx, packages/react-components/react-image/stories/Image/ImageBlock.stories.tsx, packages/react-components/react-image/stories/Image/ImageFit.stories.tsx, packages/react-components/react-image/stories/Image/ImageShadow.stories.tsx, packages/react-components/react-provider/stories/Provider/FluentProviderDir.stories.tsx
Example-only fixes, primarily fixing accessible name issues in buttons and images. One addition of a `lang` attribute.
Fixes several existing ADO bugs.
=> fix: Minor a11y fixes in v9 stories

change/@fluentui-react-734c4b03-6531-47d4-9218-58f598ffe321.json, packages/react/src/components/Facepile/Facepile.types.ts
We need to update Facepile component API to reflect clear usage of the components properties
Facepile component API documentation has been updated for a clear understanding of its properties
29428 issue has been closed in favor of updating Facepile component API documentation.
Not sure if we should open a new issue to track this, please suggest!
- Fixes #29428 (indirectly)
=> Updated API documentation of Facepile component.

packages/react-components/react-motions-preview/package.json, packages/react-components/react-motions-preview/src/factories/createAtom.ts, packages/react-components/react-motions-preview/src/factories/createTransition.ts, packages/react-components/react-motions-preview/src/utils/getChildElement.test.tsx, packages/react-components/react-motions-preview/src/utils/getChildElement.ts
Based on feedback from #29827 that I got from @ling1726, this improves error reporting and ensures that passed elements support ref forwarding.
=> chore(react-motions): improve error reporting on invalid elements

packages/react-components/react-motions-preview/stories/CreateAtom/index.stories.ts, packages/react-components/react-motions-preview/stories/CreateTransition/index.stories.ts, packages/react-components/react-motions-preview/stories/Motion/AtomPlayState.stories.md, packages/react-components/react-motions-preview/stories/Motion/AtomPlayState.stories.tsx, packages/react-components/react-motions-preview/stories/Motion/CreateAtom.stories.md, packages/react-components/react-motions-preview/stories/Motion/CreateAtom.stories.tsx, packages/react-components/react-motions-preview/stories/Motion/CreateTransition.stories.md, packages/react-components/react-motions-preview/stories/Motion/CreateTransition.stories.tsx, packages/react-components/react-motions-preview/stories/Motion/MotionDefault.stories.tsx, packages/react-components/react-motions-preview/stories/Motion/MotionDescription.md, packages/react-components/react-motions-preview/stories/Motion/TransitionAppear.stories.md, packages/react-components/react-motions-preview/stories/Motion/TransitionAppear.stories.tsx, packages/react-components/react-motions-preview/stories/Motion/TransitionUnmountOnExit.stories.md, packages/react-components/react-motions-preview/stories/Motion/TransitionUnmountOnExit.stories.tsx, packages/react-components/react-motions-preview/stories/Motion/index.stories.ts
This PR reworks docs for `@fluentui/react-motions-preview` and adds stories for props on components created by factories.
=> docs(react-motions): rework docs

change/@fluentui-react-aria-638d177e-fd03-461d-a021-dfa04e159ae8.json, packages/react-components/react-aria/etc/react-aria.api.md, packages/react-components/react-aria/package.json, packages/react-components/react-aria/src/activedescendant/constants.ts, packages/react-components/react-aria/src/activedescendant/index.ts, packages/react-components/react-aria/src/activedescendant/types.ts, packages/react-components/react-aria/src/activedescendant/useActiveDescendant.ts, packages/react-components/react-aria/src/activedescendant/useActivedescendant.test.tsx, packages/react-components/react-aria/src/activedescendant/useOptionWalker.ts, packages/react-components/react-aria/src/index.ts
Implements `useActivedescendant` hook that implements aria-activedescendant handling on the DOM level
=> feat: Implement aria-activedescendant utility

apps/vr-tests-react-components/src/stories/Dialog/Dialog.stories.tsx
Follows up #29878, fixes #29874.
=> chore: add VR test for Dialog (contain regression)

change/@fluentui-web-components-21819dfb-c067-4641-b129-18bd5f3ac496.json, packages/web-components/src/_docs/concepts/introduction.stories.mdx
- Fixes # https://github.com/microsoft/fluentui/issues/29843
=> Web components V3 - updating disclaimer message on storybook intro page

change/@fluentui-react-portal-0522b25d-4975-429a-9bd6-eded30f1eac0.json, packages/react-components/react-portal/src/components/Portal/usePortal.ts
=> chore: add explainer for the check in usePortal()

apps/public-docsite/src/styles/_base.scss
- Fixes regression from #25389
=> fix(public-docsite): Links must always have focus rects in hcm

packages/react-components/react-motions-preview/stories/Motion/CreatePresence.stories.md, packages/react-components/react-motions-preview/stories/Motion/CustomAtom.stories.md, packages/react-components/react-motions-preview/stories/Motion/CustomAtom.stories.tsx, packages/react-components/react-motions-preview/stories/Motion/MotionDescription.md, packages/react-components/react-motions-preview/stories/Motion/MotionLibrary.stories.md, packages/react-components/react-motions-preview/stories/Motion/MotionLibrary.stories.tsx, packages/react-components/react-motions-preview/stories/Motion/TokensUsage.stories.md, packages/react-components/react-motions-preview/stories/Motion/TokensUsage.stories.tsx, packages/react-components/react-motions-preview/stories/Motion/index.stories.ts
The PR add a library of defined motions & add examples with custom motion.
=> docs(react-motions): add library, example of a custom motion

change/@fluentui-react-timepicker-compat-preview-8a996340-b985-44de-9765-2fbe740ad83d.json, packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.types.ts, packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/useTimePicker.tsx
See title.
Related issue #30021
=> chore(TimePickerCompat): use useEventCallback instead of react useCallback

change/@fluentui-react-timepicker-compat-preview-e703395e-f499-4a2c-83e8-6c1397d39ca4.json, packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/useTimePicker.tsx
=> fix(TimePickerCompat): set autoComplete to off by default

packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/timeMath.test.ts
=> chore(TimePickerCompat): add unit test for daylight saving

change/@fluentui-react-timepicker-compat-preview-1f77ded1-cfbb-4f02-b295-0e08e58e63ff.json, packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.cy.tsx, packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.test.tsx, packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.types.ts, packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/timeMath.ts, packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/useTimePicker.tsx
Before - hourCycle prop has default value `h23`
After - hourCycle default value is undefined
=> fix(TimePickerCompat): remove default value of `hourCycle`

packages/react-components/react-timepicker-compat-preview/stories/TimePicker/TimePickerBestPractices.md
=> chore(TimePickerCompat): add best practice

packages/react-charting/src/components/DonutChart/DonutChartRTL.test.tsx, packages/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChartRTL.test.tsx, packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChartRTL.test.tsx, packages/react-charting/src/components/HorizontalBarChartWithAxis/HorizontalBarChartWithAxis.test.tsx, packages/react-charting/src/components/StackedBarChart/MultiStackedBarChartRTL.test.tsx, packages/react-charting/src/components/StackedBarChart/StackedBarChartRTL.test.tsx, packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChartRTL.test.tsx
Axe-core accessibility tests present in AreaChart, LineChart, VerticalBarChart
Axe-core accessibility tests added to:
1. DonutChart
2. GroupedVerticalBarChart
3. HorizontalbarChart
4. HorizontalBarChartWithAxis
5. StackedBarChart
6. MultiStackedBarChart
7. VerticalStackedBarChart
- Fixes #
=> Axe-core Integration into react-charting #2

change/@fluentui-react-charting-d420d655-3051-4fef-9dba-d672cec9ee6f.json, packages/react-charting/src/components/Sparkline/Sparkline.base.tsx, packages/react-charting/src/components/Sparkline/__snapshots__/Sparkline.test.tsx.snap, packages/react-charting/src/components/Sparkline/__snapshots__/SparklineRTL.test.tsx.snap
ARIA violations on sparklines
ARIA violations on sparkline chart fixed
- Fixes #29936
=> [SparklineChart] aria role fix for <path/>

change/@fluentui-react-charting-37d2e6c3-97ed-4f34-a6b2-56d21ebc05bd.json, packages/react-charting/src/components/GaugeChart/GaugeChart.base.tsx, packages/react-charting/src/components/GaugeChart/__snapshots__/GaugeChart.test.tsx.snap
ARIA violation existed on an SVG element due to presence of a presentation role
Conflicting role removed to clear out violation
- Fixes #30159
=> GaugeChart ARIA violation fix

packages/react-components/react-nav-preview/etc/react-nav-preview.api.md, packages/react-components/react-nav-preview/src/NavSubItem.ts, packages/react-components/react-nav-preview/src/components/NavSubItem/NavSubItem.test.tsx, packages/react-components/react-nav-preview/src/components/NavSubItem/NavSubItem.tsx, packages/react-components/react-nav-preview/src/components/NavSubItem/NavSubItem.types.ts, packages/react-components/react-nav-preview/src/components/NavSubItem/index.ts, packages/react-components/react-nav-preview/src/components/NavSubItem/renderNavSubItem.tsx, packages/react-components/react-nav-preview/src/components/NavSubItem/useNavSubItem.ts, packages/react-components/react-nav-preview/src/components/NavSubItem/useNavSubItemStyles.styles.ts, packages/react-components/react-nav-preview/src/index.ts, packages/react-components/react-nav-preview/stories/NavSubItem/NavSubItemBestPractices.md, packages/react-components/react-nav-preview/stories/NavSubItem/NavSubItemDefault.stories.tsx, packages/react-components/react-nav-preview/stories/NavSubItem/index.stories.tsx
Result of running `yarn create-component`
Commented out custom style hook in TSX file.
Updated to explicit exports
=> Scaffold NavSubItem component

packages/react-charting/src/components/HorizontalBarChartWithAxis/HorizontalBarChartWithAxisRTL.test.tsx, packages/react-charting/src/components/HorizontalBarChartWithAxis/__snapshots__/HorizontalBarChartWithAxisRTL.test.tsx.snap
Skipping one test cases which is causing issue in Master branch. we will raise new PR once issue got fixed.
=> Test case issue fix in HorizontalbarchartWithAxis

packages/react-charting/src/components/GaugeChart/GaugeChart.test.tsx, packages/react-charting/src/components/HeatMapChart/HeatMapChartRTL.test.tsx, packages/react-charting/src/components/PieChart/PieChartRTL.test.tsx, packages/react-charting/src/components/SankeyChart/SankeyChartRTL.test.tsx, packages/react-charting/src/components/Sparkline/SparklineRTL.test.tsx, packages/react-charting/src/components/TreeChart/TreeChart.test.tsx
axe-core accessibility test runs were throwing act() errors in terminal
axe-core tests wrapped in act() as per recommendations
- Fixes #30215
=> Fix act errors in terminal for axe-core tests

scripts/lint-staged/eslint-for-package.js, scripts/lint-staged/eslint.js
eslint issues with severity WARNING and cannot be autofixed or severity ERROR will cause commit failure.
This might get annoying especially if there are lot of warnings  in a file which contains very small amount of changes by current commit author.
only eslint issues with severity ERROR will cause commit failure 
**Additional changes:**
- some amount of code simplification
- Fixes #
=> fix(scripts-lint-staged): dont fail lint process if it contains only severity 'warn' violations and improve output format

azure-pipelines.release-fluentui.yml, scripts/fluentui-publish/index.ts
nightly and canary functionality has been removed from both CLI and ci pipeline
- Fixes https://github.com/microsoft/fluentui/issues/30220
- Partially implements https://github.com/microsoft/fluentui/issues/30265
- Follows https://github.com/microsoft/fluentui/pull/30202
=> ci: remove canary and nightly functionality from northstar

change/@fluentui-react-migration-v0-v9-f1f7af36-9864-40cc-8dad-6ad1306da991.json, packages/react-components/react-migration-v0-v9/package.json, packages/react-components/react-migration-v0-v9/src/components/Button/ButtonMigration.mixins.ts
Remove v0 dependency from v0 compat package as the import was pulling unnecessary files and running unnecessary initialization.
=> Remove v0 dependency from v0 compat package

change/@fluentui-react-menu-dbbb79b3-3319-4ab4-86d6-36495b748ff9.json, packages/react-components/react-menu/src/components/MenuItem/useMenuItemStyles.styles.ts
=> fix(MenuItem): bottom padding should be same as top padding

change/@fluentui-react-a9048d78-da7c-4392-94b8-9863b78a2885.json, packages/react/src/utilities/positioning/positioning.ts
a reminder to always use ?? when one of the values could be zero
fixes #30138
=> Fix positioning bug when point value is zero

change/@fluentui-react-positioning-56f6e5f4-0efa-4f5c-9405-b4dbd9fe283a.json, packages/react-components/react-positioning/package.json, yarn.lock
1. bumps `@floating-ui/devtools` version to latest
- Fixes #
=> chore(react-positioning): bumps @floating-ui/devtools version to latest

package.json, tools/eslint-rules/README.md, tools/eslint-rules/index.ts, tools/eslint-rules/jest.config.ts, tools/eslint-rules/package.json, tools/eslint-rules/project.json, tools/eslint-rules/tsconfig.json, tools/eslint-rules/tsconfig.lint.json, tools/eslint-rules/tsconfig.spec.json, yarn.lock
see pr title
- implements partially https://github.com/microsoft/fluentui/issues/30332
=> feat(eslint-rules): bootstrap workspace eslint rules project

packages/react-components/react-tabs/stories/Tabs/TabListWithOverflow.stories.tsx
CI is not passing 🔴 
CI is passing 🟢
=> chore: update types to fix CI

.devops/templates/deployE2E.yml
add cypress verification to bail out quickly if there are installation issues 
- Fixes #
=> ci: add cypress verify

apps/vr-tests/src/stories/react-charting/VerticalBarChart.stories.tsx
=> test(vr-tests): Adding VR test for Date Axis Vertical and stacked Vertical Bar chart

azure-pipelines-ci.yml
attempt v2 -> https://github.com/microsoft/fluentui/pull/30404
- Fixes #
=> ci: tweak false positive removal step to use glob to make it more robust

packages/react-components/react-motions-preview/stories/Motion/MotionFunctions.stories.md
=> docs(react-motions-preview): fix typo

.github/CODEOWNERS, sizeauditor.json
see PR title
After this merged, we will:
- remove SizeAuditor pipeline check  
- remove sizeauditor github app from our repo
- Follows https://github.com/microsoft/fluentui/pull/30405
- Implements partially https://github.com/microsoft/fluentui/issues/27933
=> chore: remove sizeauditor lightrail config

package.json, yarn.lock
Bumps to address `monosize-storage-azure` https://github.com/microsoft/monosize/issues/28.
=> chore: bump monosize-storage-azure

tools/workspace-plugin/src/generators/prepare-initial-release/README.md
adds complete docs regarding v9 review release flow
- Fixes #
=> docs(workspace-plugin): add complete release process flow docs

nx.json, packages/fluentui/docs/project.json
- migrate lage task dependency graph to nx
- Part of #30267
=> feat: migrate lage task dependencies to nx

change/@fluentui-react-field-20a58a74-4038-45b5-8df4-3ae8ed5eebf8.json, change/@fluentui-react-image-076e6ee8-4686-41f0-8859-5bb3d780d43a.json, change/@fluentui-react-menu-783d5a4b-4630-4cac-9c6c-02ae48786974.json, change/@fluentui-react-radio-66a43e4e-91b9-4c23-8ca1-ff2349efefe5.json, change/@fluentui-react-toolbar-49c09294-45b1-4c5b-9153-0f39230e8121.json, packages/react-components/react-field/etc/react-field.api.md, packages/react-components/react-field/src/components/Field/useFieldStyles.styles.ts, packages/react-components/react-image/etc/react-image.api.md, packages/react-components/react-image/src/components/Image/useImageStyles.styles.ts, packages/react-components/react-menu/etc/react-menu.api.md, packages/react-components/react-menu/src/components/MenuItem/useMenuItemStyles.styles.ts, packages/react-components/react-menu/src/components/MenuItemCheckbox/useMenuItemCheckboxStyles.styles.ts, packages/react-components/react-radio/etc/react-radio.api.md, packages/react-components/react-radio/src/components/Radio/useRadioStyles.styles.ts, packages/react-components/react-radio/src/components/RadioGroup/useRadioGroupStyles.styles.ts, packages/react-components/react-toolbar/etc/react-toolbar.api.md, packages/react-components/react-toolbar/src/components/ToolbarRadioButton/useToolbarRadioButtonStyles.styles.ts, packages/react-components/react-toolbar/src/components/ToolbarToggleButton/useToolbarToggleButtonStyles.styles.ts
Updates style hooks to be consistent and always return state.
Fixes #30349.
=> chore: update style hooks to return state

change/@fluentui-react-motions-preview-41532783-fcce-4fdb-9b36-d4d9ddfa5ae5.json, packages/react-components/react-motions-preview/etc/react-motions-preview.api.md, packages/react-components/react-motions-preview/src/factories/createMotionComponent.ts, packages/react-components/react-motions-preview/src/factories/createPresenceComponent.ts, packages/react-components/react-motions-preview/stories/Motion/CreateMotionComponent.stories.tsx, packages/react-components/react-motions-preview/stories/Motion/PresenceOnMotionFinish.stories.md, packages/react-components/react-motions-preview/stories/Motion/PresenceOnMotionFinish.stories.tsx, packages/react-components/react-motions-preview/stories/Motion/index.stories.ts
Does updates based on conversations in #29958 and adds `onMotionFinish()` callback to `createPresenceMotion()`.
A new story was added.
=> feat(react-motions): add `onMotionFinish()` to a component created by `createPresenceMotion()`

change/@fluentui-react-rating-preview-0010befd-90a4-4708-a3a1-bbbe4d559d5b.json, packages/react-components/react-rating-preview/src/components/Rating/useRatingStyles.styles.ts, packages/react-components/react-rating-preview/src/components/RatingItem/useRatingItemStyles.styles.ts
This PR is to add focus border styling to Rating.
=> fix: Fixing Rating focus border styling

change/@fluentui-react-virtualizer-b81528c5-8ea3-4e60-81d5-72b8fc9435a7.json, packages/react-components/react-virtualizer/etc/react-virtualizer.api.md, packages/react-components/react-virtualizer/src/components/VirtualizerScrollView/VirtualizerScrollView.types.ts, packages/react-components/react-virtualizer/src/components/VirtualizerScrollView/useVirtualizerScrollView.ts, packages/react-components/react-virtualizer/src/components/VirtualizerScrollViewDynamic/VirtualizerScrollViewDynamic.types.ts, packages/react-components/react-virtualizer/src/components/VirtualizerScrollViewDynamic/useVirtualizerScrollViewDynamic.tsx, packages/react-components/react-virtualizer/src/hooks/hooks.types.ts, packages/react-components/react-virtualizer/src/hooks/useDynamicPagination.ts, packages/react-components/react-virtualizer/src/hooks/useMeasureList.ts, packages/react-components/react-virtualizer/src/hooks/useStaticPagination.ts, packages/react-components/react-virtualizer/stories/VirtualizerScrollView/Default.stories.tsx, packages/react-components/react-virtualizer/stories/VirtualizerScrollView/SnapToAlignment.stories.tsx, packages/react-components/react-virtualizer/stories/VirtualizerScrollViewDynamic/SnapToAlignment.stories.tsx, packages/react-components/react-virtualizer/stories/VirtualizerScrollViewDynamic/index.stories.ts
No pagination available in virtualizer (index changes would break css pagination).
Custom pagination for both static and dynamic virtualizers
=> Virtualizer: Static and dynamic pagination

change/@fluentui-react-tags-3b958949-bf15-4f17-932b-73574965dd64.json, packages/react-components/react-tags/etc/react-tags.api.md, packages/react-components/react-tags/src/index.ts
1. Exports `TagGroupContextValues`
- Fixes #
=> feat(react-tags): export TagGroupContextValues type

packages/react-components/react-progress/stories/ProgressBar/ProgressBarBestPractices.md, packages/react-components/react-progress/stories/ProgressBar/ProgressBarDescription.md
=> docs(ProgressBar): fix title

change/@fluentui-react-rating-preview-3f67a734-458e-4c0f-972f-75dc7c7c55cf.json, packages/react-components/react-rating-preview/src/components/Rating/Rating.test.tsx, packages/react-components/react-rating-preview/src/components/Rating/Rating.tsx, packages/react-components/react-rating-preview/src/components/RatingDisplay/RatingDisplay.tsx, packages/react-components/react-rating-preview/src/components/RatingItem/RatingItem.tsx, packages/react-components/react-rating-preview/stories/Rating/RatingBestPractices.md, packages/react-components/react-rating-preview/stories/RatingDisplay/RatingDisplayBestPractices.md
This PR is to finish the documentation of `Rating`. Tracked with #30652
=> Update `Rating` JSDocs to remove ToDos

change/@fluentui-react-positioning-48ddaaa4-e1b9-419e-a5bb-14f175441b70.json, packages/react-components/react-positioning/etc/react-positioning.api.md, packages/react-components/react-positioning/src/types.ts, packages/react-components/react-positioning/src/usePositioning.ts
=> feat(react-positioning): allow null on positioningRef setTarget

.github/workflows/create-milestone.yml
create-milestone action is failing 
https://github.com/microsoft/fluentui/actions/runs/8104414827/job/22150975600
create-milestome works
- Fixes #
=> fix(.github): fix typos within create-milestone shell script

packages/merge-styles/etc/merge-styles.api.md, packages/merge-styles/src/EventMap.ts, packages/merge-styles/src/IStyleOptions.ts, packages/merge-styles/src/StyleOptionsState.ts, packages/merge-styles/src/Stylesheet.ts, packages/merge-styles/src/extractStyleParts.test.ts, packages/merge-styles/src/extractStyleParts.ts, packages/merge-styles/src/index.ts, packages/merge-styles/src/mergeStyleSets.ts, packages/merge-styles/src/mergeStyles.ts, packages/merge-styles/src/styleToClassName.ts, packages/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap, packages/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChartRTL.test.tsx.snap, packages/react-charting/src/components/HorizontalBarChartWithAxis/__snapshots__/HorizontalBarChartWithAxisRTL.test.tsx.snap, packages/react-charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChartRTL.test.tsx.snap, packages/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChartRTL.test.tsx.snap, packages/utilities/package.json, packages/utilities/src/customizations/customizable.tsx, packages/utilities/src/shadowDom/MergeStylesShadowRootContext.tsx
- Optimizes Stylesheet.getInstance() as this function is called often and was doing more work than necessary.
- Fixes an issue that broke memoization in customizable
- Optimizes useAdoptableStylesheet() to do less work.
=> chore: performance optimizations for shadow dom feature

change/@fluentui-react-table-c0bf5964-aa92-4b40-871f-d62e14165dcb.json, packages/react-components/react-table/src/hooks/useTableSelection.test.ts, packages/react-components/react-table/src/hooks/useTableSelection.ts, packages/react-components/react-table/stories/DataGrid/Default.stories.tsx
=> fix: allRowsSelected is false when there are no rows

change/@fluentui-react-toast-27a36992-a9ec-40c0-9e5c-b9a7538c7193.json, packages/react-components/react-toast/src/components/ToastTitle/useToastTitleStyles.styles.ts
=> fix: Use semantic colours

nx.json
nx needs explicit children specifiers `^` 
- Follows https://github.com/microsoft/fluentui/pull/30503
=> fix(nx): properly declare target dependencies with explicit `^`

rfcs/react-components/components/dev-docs.md
A proposal to update our dev docs.
Related PR scaffolding out new docs: #30483
Related Epic: #30642
=> RFC: Dev Docs

packages/react-components/react-rating-preview/docs/Spec.md
This PR is to update the `Rating` component spec. Fixes #30647.
=> Update Rating spec

CredScanSuppressions.json, azure-pipelines.release-vnext-nightly.yml
- release pipelines started failing on cred scanner error 
- see PR title
=> ci: suppress cred scanner error to make release pipelines green once again 

azure-pipelines.release-fluentui.yml
v0 pipelines are triggered on daily basis, which is not needed
- triggers are unrelated to v0 changes
- wasting resources
see PR title
- Follows https://github.com/microsoft/fluentui/pull/30704
=> ci(northstar): turn off daily release triggers

azure-pipelines.release-fluentui.yml
`npm logout` throws error if there is no user logged previously ( which is not )
- Follows https://github.com/microsoft/fluentui/pull/30704
=> ci(northstar): dont exec npm logout to avoid failures

packages/react-components/react-swatch-picker-preview/stories/ColorSwatch/ColorSwatchDefault.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerPopup.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerShape.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerSize.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerSpacing.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/index.stories.tsx
- Added stories for Size, Shape and Spacing
- Added color sets
=> docs(react-swatch-picker): Added stories for Size, Shape and Spacing

change/@fluentui-react-timepicker-compat-90f52a20-6cfc-40fd-80a1-dd3717f9c955.json, packages/react-components/react-timepicker-compat/README.md
=> docs(TimePicker): update Readme to remove unstable statement

change/@fluentui-date-time-utilities-467b9fb1-00b7-47f9-ac7e-30a692a57571.json, packages/date-time-utilities/etc/date-time-utilities.api.md, packages/date-time-utilities/src/dateMath/dateMath.ts
The fixes in this PR are caused by a breaking change in TS 5.0: [Forbidden Implicit Coercions in Relational Operators](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#forbidden-implicit-coercions-in-relationa …
=> fix(date-time-utilities): Fix build errors in TypeScript 5.3.3

packages/react-components/react-swatch-picker-preview/README.md
Added README.md for the SwatchPicker
=> docs(react-swatch-picker): Added README.md

packages/react-components/react-swatch-picker-preview/docs/MIGRATION.md, packages/react-components/react-swatch-picker-preview/docs/Spec.md
Added MIGRATION.md to the SwatchPicker
=> docs(react-swatch-picker): Added MIGRATION.md

change/@fluentui-react-teaching-popover-preview-0f97c436-4f69-4aba-9ae5-d57c19b37d4d.json, packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverCarousel/__snapshots__/TeachingPopoverCarousel.test.tsx.snap, packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverCarouselNav/__snapshots__/TeachingPopoverCarouselNav.test.tsx.snap, packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverCarouselNav/useTeachingPopoverCarouselNav.tsx, packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverCarouselNav/useTeachingPopoverCarouselNavStyles.styles.ts, packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverCarouselNavButton/__snapshots__/TeachingPopoverCarouselNavButton.test.tsx.snap, packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverCarouselNavButton/useTeachingPopoverCarouselNavButton.tsx, packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverCarouselNavButton/useTeachingPopoverCarouselNavButtonStyles.styles.ts, packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverHeader/useTeachingPopoverHeaderStyles.styles.ts, packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverTitle/useTeachingPopoverTitleStyles.styles.ts
Tabster group focus on nav container
Some focus borders had a dual outline
Arrow nav focus on nav container
Focus borders have a single outline
#30804
=> TeachingPopover: Arrow Navigation & Focus border fix

apps/public-docsite-v9/package.json, change/@fluentui-react-swatch-picker-preview-c626e7e2-4c7e-44de-bb64-55502d6edff3.json, packages/react-components/react-swatch-picker-preview/package.json
Release SwatchPicker as unstable
=> feat: release react-swatch-picker to unstable

change/@fluentui-react-swatch-picker-preview-c9f57e04-6124-4189-b3d8-1b7ce90f839d.json, packages/react-components/react-swatch-picker-preview/etc/react-swatch-picker-preview.api.md, packages/react-components/react-swatch-picker-preview/src/components/ColorSwatch/ColorSwatch.tsx, packages/react-components/react-swatch-picker-preview/src/components/ColorSwatch/useColorSwatch.tsx, packages/react-components/react-swatch-picker-preview/src/components/ImageSwatch/ImageSwatch.tsx, packages/react-components/react-swatch-picker-preview/src/components/ImageSwatch/useImageSwatch.ts, packages/react-components/react-swatch-picker-preview/src/components/SwatchPicker/SwatchPicker.cy.tsx, packages/react-components/react-swatch-picker-preview/src/components/SwatchPicker/SwatchPicker.types.ts, packages/react-components/react-swatch-picker-preview/src/components/SwatchPicker/useSwatchPicker.ts, packages/react-components/react-swatch-picker-preview/src/components/SwatchPicker/useSwatchPickerStyles.styles.ts, packages/react-components/react-swatch-picker-preview/src/contexts/swatchPicker.ts, packages/react-components/react-swatch-picker-preview/src/index.ts, packages/react-components/react-swatch-picker-preview/src/utils/renderUtils.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerDefault.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerDescription.md, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerLayout.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerPopup.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerShape.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerSpacing.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerWithTooltip.stories.tsx
- fixed comments from this PR #30600
- added mixed swatches to stories
- renamed `selectedColor` prop
- added `layout` prop instead of `grid`
=> feat(react-swatch-picker): changed API of renderingUtils

apps/public-docsite-v9/package.json, change/@fluentui-react-tag-picker-preview-1ca76440-1c73-476e-b98c-291e5d63f5eb.json, packages/react-components/react-tag-picker-preview/package.json
Releases package for `@fluentui/react-tag-picker-preview`
=> feat(react-tag-picker): release preview package

change/@fluentui-react-charting-ef57ab3b-531b-4c9b-a1d5-8545a569fb53.json, packages/react-charting/src/components/DonutChart/DonutChart.base.tsx, packages/react-charting/src/components/DonutChart/DonutChart.test.tsx, packages/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap, packages/react-charting/src/utilities/test-data.ts
Values which are very small in comparision to other values don't end up making significant angle on DonutChart for proper visual resolution
Values smaller than 1% of the initial total have been elevated to 1% of the initial total sum.
- Fixes #30034
=> DonutChart: Elevate data to 1% of initial total sum

apps/vr-tests-react-components/package.json, apps/vr-tests-react-components/src/stories/SwatchPicker/SwatchPicker.stories.tsx, apps/vr-tests-react-components/src/stories/SwatchPicker/utils.tsx
Added VR tests for the SwatchPicker
=> test(react-swatch-picker): added vr tests

apps/public-docsite-v9/package.json, change/@fluentui-react-list-preview-a24e4275-c90a-436c-aa8f-efeee32e9564.json, packages/react-components/react-list-preview/package.json
Public preview of List component.
- Releases #27382
=> feat(react-list-preview): Release preview package

packages/react-components/react-list-preview/docs/Spec.md
Updating the List spec, based on the latest API for preview.
=> chore(react-list-preview): Update spec based on latest API

change/@fluentui-react-tags-62b2fcad-e929-416b-88a0-1f6617266d80.json, packages/react-components/react-tags/src/components/InteractionTagPrimary/useInteractionTagPrimaryStyles.styles.ts, packages/react-components/react-tags/src/components/InteractionTagSecondary/useInteractionTagSecondaryStyles.styles.ts
fix #30904 
increase color contrast for brand variant InteractionTag
=> fix(InteractionTag): use color brand foreground2 for brand color instead of brand foreground 1

change/@fluentui-react-tag-picker-preview-9d99a80a-241f-4dcf-a71f-14f4a7be75b6.json, packages/react-components/react-tag-picker-preview/Spec.md
1. Adds minimal Spec file
- Fixes #
=> chore(tag-picker): adds minimal Spec.md

change/@fluentui-react-tag-picker-preview-307bb188-b6bd-4a38-ad3c-368174c17c94.json, packages/react-components/react-tag-picker-preview/etc/react-tag-picker-preview.api.md, packages/react-components/react-tag-picker-preview/package.json, packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/TagPickerControl.types.ts, packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/useTagPickerControl.tsx, packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/useTagPickerControlStyles.styles.ts, packages/react-components/react-tag-picker-preview/src/components/TagPickerInput/useTagPickerInput.tsx, packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerDefault.stories.tsx
1. adds support for `Field` component
- Fixes https://github.com/microsoft/fluentui/issues/30978
=> feature(react-tag-picker):adds support for Field component

change/@fluentui-react-jsx-runtime-005921c9-ea0e-49cc-b14c-a20f65e1d049.json, packages/react-components/react-jsx-runtime/project.json, packages/react-components/react-storybook-addon-export-to-sandbox/project.json, packages/react-components/react-storybook-addon/project.json
fixed platform tags to reflect reality. 
- Also needed for https://github.com/microsoft/fluentui/pull/30866
=> chore: update project tags to proper platform type

.vscode/extensions.json
see PR title
- Follows https://github.com/microsoft/fluentui/pull/30663
=> chore: add new recommended vscode extensions

change/@fluentui-react-tag-picker-preview-037cc1ac-dda7-4976-8fe9-05b27c0d83ed.json, packages/react-components/react-tag-picker-preview/README.md
Adds `README.md` file to project.
- Fixes #
=> chore(react-tag-picker): adds README file

change/@fluentui-react-tag-picker-preview-8f839f14-adfa-4df7-8396-133fdd49c22a.json, packages/react-components/react-tag-picker-preview/bundle-size/Package.fixture.js, packages/react-components/react-tag-picker-preview/package.json
Adds bundle-size tolling to analyze how heavy the package is
- Fixes #
=> chore(tag-picker): adds bundle-size

change/@fluentui-react-swatch-picker-preview-ae04a87f-6422-40c9-82d0-5358e1a91c56.json, packages/react-components/react-swatch-picker-preview/README.md, packages/react-components/react-swatch-picker-preview/src/components/ColorSwatch/useColorSwatchStyles.styles.ts, packages/react-components/react-swatch-picker-preview/src/components/ImageSwatch/useImageSwatchStyles.styles.ts
=> fix(react-swatch-picker): colors in HC mode

packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/ColorSwatchVariants.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/EmptySwatch.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerDefault.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerImage.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerLayout.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerPopup.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerShape.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerSize.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerSpacing.stories.tsx, packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerWithTooltip.stories.tsx
Storybook fixes for the SwatchPicker
=> docs(react-swatch-picker): storybook fixes

docs/react-v9/contributing/dev-env.md
Created a dev doc for setting up the dev environment.
Things to look for:
- Typos & grammar
- Any updates you think I should add?
- Broken links
Addresses #30642
=> docs: New dev startup doc

packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerAppearance.stories.tsx, packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerButton.stories.tsx, packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerDefault.stories.tsx, packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerDisabled.stories.tsx, packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerExpandIcon.stories.tsx, packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerFiltering.stories.tsx, packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerFreeform.stories.tsx, packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerGrouped.stories.tsx, packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerInteractionTag.stories.tsx, packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerSecondaryAction.stories.tsx, packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerSize.stories.tsx, packages/react-components/react-tag-picker-preview/stories/TagPicker/index.stories.tsx
1. improves a11y on stories
3. adds proper label to `TagPickerInput`
4. adds proper heading level
- Fixes #
=> chore(react-tag-picker): improves stories a11y

packages/react-components/react-swatch-picker-preview/src/utils/__snapshots__/renderUtils.test.tsx.snap, packages/react-components/react-swatch-picker-preview/src/utils/renderUtils.test.tsx
Added tests for render utils in a SwatchPicker
=> test(react-swatch-picker): added tests for render utils

apps/perf-test-react-components/package.json, apps/perf-test-react-components/src/scenarios/SwatchPicker.tsx
Added performance test scenario for the SwatchPicker
=> perf-app: added SwatchPicker scenario

docs/react-v9/contributing/command-cheat-sheet.md
A quick handy doc to help developers quickly understand, reference and use common CLI commands.
Test for:
- Grammatical errors
- Are the commands accurate AND relevant?
- Did I miss any you like to use? Please feel free to add on!
=> docs: command cheat sheet

packages/react-components/react-combobox/stories/Combobox/ComboboxFiltering.stories.tsx
=> Combobox filtering bug fix

packages/react-components/react-combobox/stories/Combobox/ComboboxFiltering.stories.tsx
Updates the doc example to fully control the input value instead of using a mix of controlled and uncontrolled logic
=> docs: Update combobox filtering example

change/@fluentui-react-menu-f8352325-5934-4338-af8b-470a8c36a0f6.json, change/@fluentui-react-popover-6af765e8-b0fd-4b1f-91bb-3e6e001a7cad.json, change/@fluentui-react-table-f4dd549f-a19e-4104-b566-f18303bb915a.json, change/@fluentui-react-toast-571950e7-2982-483b-af36-aa789af629dc.json, packages/react-components/react-menu/src/components/Menu/useMenu.tsx, packages/react-components/react-popover/src/components/Popover/usePopover.ts, packages/react-components/react-table/src/hooks/useTableColumnResizeMouseHandler.ts, packages/react-components/react-toast/src/components/AriaLive/useAriaLive.ts
Fixes #31093
Fixes #31094
Fixes #31092
Fixes #31091
=> refactor: use timeout and animation frame utilities

packages/react-components/react-tree/stories/Tree/TreeInlineStylingTreeItemLevel.stories.tsx
1. simplifies `InlineStylingTreeItemLevel` story
- Fixes #
=> doc(react-tree): simplifies InlineStylingTreeItemLevel story

docs/react-v9/contributing/dev-workflow.md
=> docs: fix spelling mistake in dev-workflow

docs/react-v9/contributing/command-cheat-sheet.md
=> docs: fix preview of command cheat sheet

apps/vr-tests-react-components/package.json, apps/vr-tests-react-components/src/stories/TagPicker.stories.tsx
1. adds VR tests for TagPicker
- Fixes #
=> chore(react-tag-picker): adds VR tests

tools/workspace-plugin/.eslintrc.json, tools/workspace-plugin/package.json, tools/workspace-plugin/project.json, tools/workspace-plugin/src/generators/epic-generator/index.spec.ts, tools/workspace-plugin/src/generators/migrate-converged-pkg/index.ts, tools/workspace-plugin/src/generators/migrate-v8-pkg/lib/utils.ts, tools/workspace-plugin/src/generators/move-packages/index.spec.ts, tools/workspace-plugin/src/generators/react-component/index.spec.ts, tools/workspace-plugin/src/generators/tsconfig-base-all/index.spec.ts, tools/workspace-plugin/src/generators/workspace-generator/index.spec.ts
Recently intermittent test failures started to happen caused by leaking promises etc
- https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=340958&view=logs&j=e51d397b-0a7b-5b89-4b48-0052e021371d&t=88c41216-94ff-5ca8-d686-48ce16c1eefc
- https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=340958&view=logs&j=e51d397b-0a7b-5b89-4b48-0052e021371d&t=88c41216-94ff-5ca8-d686-48ce16c1eefc
- https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=341095&view=logs&j=e51d397b-0a7b-5b89-4b48-0052e021371d&t=88c41216-94ff-5ca8-d686-48ce16c1eefc
- sets lint rules to workspace-plugin project to catch unhandled promises
- fixes lint rule errors
- <img width="741" alt="image" src="https://github.com/microsoft/fluentui/assets/1223799/38cd07b5-ecd3-4244-9c11-76 …
=> style(workspace-plugin): add thenable and promise resolving lint rules to catch promises leaks that cause issues when invoking generators

packages/react-components/react-dialog/src/components/Dialog/Dialog.cy.tsx
1. removes triple slash reference from e2e tests
- Fixes #
=> bugfix(react-dialog): remove triple slash ref

docs/react-v9/contributing/common-dev-snags.md
Esteban and CXE-Red helped unblock me today, so I thought I'd share the advice.
Ladders to #30642
=> (docs): Add doc on cleaning the repo.

change/@fluentui-react-charting-5d64441c-63ae-4ae7-aa33-c28b9f6ff1d4.json, packages/react-charting/src/components/HeatMapChart/HeatMapChart.base.tsx
Blank cells in HeatMapChart are not accessible.
=> Make blank cells in heatmap chart accessible

docs/react-v9/contributing/dev-workflow.md
Updating some docs after getting feedback from a new engineer to the team.
=> (chore)Docs: Text updates to the new dev docs

apps/public-docsite-v9/package.json, change/@fluentui-react-nav-preview-35207415-1026-46cd-8f89-9fb2f7527ee7.json, packages/react-components/react-nav-preview/package.json, packages/react-components/react-nav-preview/src/components/Nav/Nav.tsx, packages/react-components/react-nav-preview/stories/Hamburger/index.stories.tsx, packages/react-components/react-nav-preview/stories/HamburgerInNav/index.stories.tsx, packages/react-components/react-nav-preview/stories/Nav/index.stories.tsx, packages/react-components/react-nav-preview/stories/NavDrawer/NavDrawerDefault.stories.tsx, packages/react-components/react-nav-preview/stories/NavDrawerBody/index.stories.tsx, packages/react-components/react-nav-preview/stories/NavDrawerFooter/index.stories.tsx, packages/react-components/react-nav-preview/stories/NavDrawerHeader/index.stories.tsx, packages/react-components/react-nav-preview/stories/NavDrawerHeaderNav/index.stories.tsx, packages/react-components/react-nav-preview/stories/NavSectionHeader/index.stories.tsx
Publishes the nav preview package 🎉
=> chore(react-nav-preview): Publish react-nav-preview

packages/react-components/react-swatch-picker-preview/src/components/SwatchPicker/SwatchPicker.cy.tsx
Added cy tests for defaultSelected and selected state
=> test(react-swatch-picker): added cy tests for selected state

change/@fluentui-react-menu-e1cd8e82-e971-4a23-b76a-d95289214a1d.json, packages/react-components/react-menu/src/components/MenuGroupHeader/useMenuGroupHeaderStyles.styles.ts
=> fix: 8px menu section header padding

change/@fluentui-react-divider-945907e3-a189-4a97-a569-18dae68d0c9a.json, packages/react-components/react-badge/stories/Badge/BadgeIcon.stories.tsx, packages/react-components/react-divider/src/components/Divider/Divider.types.ts, packages/react-components/react-drawer/stories/Drawer/DrawerCustomSize.stories.tsx, packages/react-components/react-drawer/stories/Drawer/DrawerWithScroll.stories.tsx
Docs-only updates, no package changes.
This is related to documentation work being done with the a11y insights team, just minor cleanup & better wording.
=> fix: minor story docs updates for better accessibility information

docs/react-v9/contributing/keeping-up-with-review-requests.md
Migrating[ Keeping up with review requests](https://github.com/microsoft/fluentui/wiki/Keeping-up-with-review-requests) from the wiki. Made no file changes.
=> chore:(docs) Migrating Keeping up with review requests

change/@fluentui-react-components-1025907a-b391-4baa-a81c-53e99da650b0.json, change/@fluentui-react-dialog-fedf905d-e71a-43a1-8828-26303bc41a25.json, packages/react-components/react-components/etc/react-components.api.md, packages/react-components/react-components/src/index.ts, packages/react-components/react-dialog/etc/react-dialog.api.md, packages/react-components/react-dialog/src/index.ts
1. exports `DialogModalType` type
- Fixes https://github.com/microsoft/fluentui/issues/31520
=> chore(react-dialog): exports DialogModalType type

packages/react-components/react-migration-v0-v9/stories/GridShim/index.stories.tsx, packages/react-components/react-migration-v0-v9/stories/Input/index.stories.tsx, packages/react-components/react-migration-v0-v9/stories/List/Default.stories.tsx, packages/react-components/react-migration-v0-v9/stories/List/Navigable.stories.tsx, packages/react-components/react-migration-v0-v9/stories/List/Selectable.stories.tsx, packages/react-components/react-migration-v0-v9/stories/SliderMixin/index.stories.tsx
Docs-only changes, no package changes. Fixes a number of a11y bugs.
=> fix: v0 > v9 story accessibility updates

LICENSE
- see pr title and linked issue
- uses official template to make the bot happy https://raw.githubusercontent.com/microsoft/repo-templates/main/shared/LICENSE
- Fixes https://github.com/microsoft/fluentui/issues/31176
=> chore: update repo LICENSE

docs/react-v9/contributing/perf-testing.md
Migrates the perf testing doc from the wiki.
Adds bit about the process being recommended, but not a hard requirement.
=> chore:(docs) Adds perf testing doc

change/@fluentui-react-motion-b068209f-dd7d-43e0-a77a-f6ab0606659d.json, packages/react-components/react-dialog/library/src/components/Dialog/Dialog.test.tsx, packages/react-components/react-motion/src/factories/createPresenceComponent-jest.test.tsx, packages/react-components/react-motion/src/utils/animateAtoms.ts
Improves compat with Jest & JSDOM, so tests would pass as expected.
Fixes #31593.
=> fix(motions): improve compat for jsdom & jest

docs/react-v9/contributing/accessibility-review-checklist.md
Porting the accessibility checklist over from the old docs.
No changes to the original doc.
=> chore:(docs) Add Accessibility Review Checklist to the docs

packages/react-components/react-motion/stories/CreateMotionComponent/CreateMotionComponent.stories.tsx, packages/react-components/react-motion/stories/CreateMotionComponent/CreateMotionComponentDefault.stories.tsx, packages/react-components/react-motion/stories/CreateMotionComponent/ImperativeRefPlayState.stories.tsx, packages/react-components/react-motion/stories/CreateMotionComponent/MotionArrays.stories.tsx, packages/react-components/react-motion/stories/CreateMotionComponent/MotionFunctions.stories.tsx, packages/react-components/react-motion/stories/CreateMotionComponent/TokensUsage.stories.tsx, packages/react-components/react-motion/stories/CreatePresenceComponent/CreatePresenceComponent.stories.tsx, packages/react-components/react-motion/stories/CreatePresenceComponent/CreatePresenceComponentDefault.stories.tsx, packages/react-components/react-motion/stories/CreatePresenceComponent/PresenceAppear.stories.tsx, packages/react-components/react-motion/stories/CreatePresenceComponent/PresenceMotionArrays.stories.tsx, packages/react-components/react-motion/stories/CreatePresenceComponent/PresenceMotionFunctions.stories.tsx, packages/react-components/react-motion/stories/CreatePresenceComponent/PresenceOnMotionFinish.stories.tsx, packages/react-components/react-motion/stories/CreatePresenceComponent/PresenceUnmountOnExit.stories.tsx, packages/react-components/react-motion/stories/PresenceGroup/PresenceGroupDefault.stories.tsx
Minor polish or examples. Improves controls, layouts, look & feel to make examples consistent.
=> docs(motions): improve examples & UI in stories

packages/react-components/react-swatch-picker/stories/src/SwatchPicker/ColorSwatchVariants.stories.tsx, packages/react-components/react-swatch-picker/stories/src/SwatchPicker/EmptySwatch.stories.tsx, packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerDefault.stories.tsx, packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerImage.stories.tsx, packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerLayout.stories.tsx, packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerMixedSwatches.stories.tsx, packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerPopup.stories.tsx, packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerShape.stories.tsx, packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerSize.stories.tsx, packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerSpacing.stories.tsx, packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerWithTooltip.stories.tsx
=> docs(react-swatch-picker): fixed imports in stories

.github/ISSUE_TEMPLATE/convergence_epic.md
This has been deprecated and will be replaced in the future, based on information from @Hotell.
Until then, remove it from the checklist.
> **more context**
> https://github.com/microsoft/fluentui/pull/30836#issuecomment-2014971471
=> chore(docs): Remove requirement of performance tests from epic template

change/@fluentui-react-nav-preview-3c55352e-759a-4a43-9d28-c58093c56453.json, packages/react-components/react-nav-preview/library/src/index.ts
- Introduced https://github.com/microsoft/fluentui/pull/31646 ( `export *` within public api surface is not allowed, wondering how that passed via git commit )
- Fixes failing master
=> style(react-nav-preview): fix formatting in barel file

docs/react-v9/contributing/new-components.md
This is a direct port from the wiki.
Deleted the bottom 2/3rds which is generally covered by the component implementation guide.
=> chore:(docs) New Component doc

change/@fluentui-react-nav-preview-d6e9b504-9ca3-4bbd-8066-2e70a8efba32.json, packages/react-components/react-nav-preview/library/src/components/NavCategoryItem/useNavCategoryItem.tsx, packages/react-components/react-nav-preview/library/src/components/NavDrawer/useNavDrawer.ts, packages/react-components/react-nav-preview/library/src/components/NavItem/useNavItem.ts, packages/react-components/react-nav-preview/library/src/components/NavSubItem/useNavSubItem.ts
Makes sure the roles are correct for links.
Adds aria-current where appropriate.
=> feat:react-nav-preview Add a handful of accessibility features for Nav

packages/react-components/react-motion/stories/src/CreateMotionComponent/index.stories.ts, packages/react-components/react-motion/stories/src/CreatePresenceComponent/index.stories.ts, packages/react-components/react-motion/stories/src/PresenceGroup/index.stories.ts
Small update based on feedback:
=> docs: remove "Web" prefix

.github/github-docs-readme.md, .github/policies/botRules.yml
- see PR title
- udpated docs link to bot documentation
- Fixes #
=> ci(.github): tweak resource-management-bot to not close issues after 180 days of inactivity

change/@fluentui-web-components-1b9d3e46-3d21-40fa-839e-84141cee53b3.json, packages/web-components/docs/api-report.md, packages/web-components/src/link/link.options.ts, packages/web-components/src/link/link.template.ts, packages/web-components/src/link/link.ts
The template references Button.
The template references link
- Fixes #
=> chore: fix tsdoc for link web component template

change/@fluentui-react-combobox-89568295-fe37-4606-9f66-9925449604cf.json, packages/react-components/react-combobox/library/src/components/Listbox/useListbox.ts
master pipeline is failing
master is unblocked
- Follows https://github.com/microsoft/fluentui/pull/31787
=> style(react-combobox): turn off react-compiler lints for non compliant code

docs/react-v9/contributing/implementation-best-practices.md
Ports[ this page from the wiki.](https://github.com/microsoft/fluentui/wiki/Implementation-Best-Practices)
Checked that links still worked 🙂
=> chore:(docs) Adding implementation best practices

.github/CODEOWNERS
This will empower XC UXE to tighten up comms and review cycles on the Nav component.
=> chore: Add XC-UXE as approvers for the Nav package

docs/react-v9/contributing/dev-env.md
Many commands don't work as intended on a Windows based system. We should be clear with our contributors about the level of support the team provides for Windows and what developers can expect with it.
=> chore:(docs) Update dev env set up to include note on WSL

packages/react-components/react-virtualizer/stories/src/VirtualizerScrollView/ScrollTo.stories.tsx
Super-simple example-only fix.
Resolves an ADO issue.
=> fix: add live region around scroll index update

change/@fluentui-web-components-8463da01-415d-4abc-b544-0e93c48df6e1.json, packages/web-components/package.json
Allow imports of field through package exports
=> chore(web-components): expose field to package exports

change/@fluentui-web-components-5b51675f-fb22-4e9e-8711-727169376a26.json, packages/web-components/package.json, packages/web-components/src/index-rollup.ts, packages/web-components/src/index.ts
These were not properly exported
Fixes the export issue
- Fixes #
=> fix: export drawer and drawer body from root package and package exports

change/@fluentui-react-utilities-164cf01a-a62b-499d-b99e-60974c0496e3.json, packages/react-components/react-utilities/src/compose/types.ts
1. fixes internal `With*` types `children` verification
- Fixes #
=> chore: fix With* internal helper types 'children' verification

change/@fluentui-react-motion-acee5fd2-f48b-4d17-9f29-165066f43058.json, packages/react-components/react-motion/library/etc/react-motion.api.md, packages/react-components/react-motion/library/src/factories/createPresenceComponent.ts, packages/react-components/react-motion/library/src/index.ts, packages/react-components/react-motion/library/src/types.ts
`enter | exit` is used everywhere.
`PresenceDirection` type is introduced and used everywhere.
=> feat(motion): add PresenceDirection type

azure-pipelines.release.tools.yml
Updates to the tool's release pipeline:
- Removing the scheduled configuration to enable only manual triggers of the pipeline.
- Eliminating unnecessary code that was copied from release v8 pipeline.
=> chore: update tools release pipeline

apps/public-docsite-v9/package.json, change/@fluentui-react-motion-components-preview-ba095f16-e1da-4c33-b024-c8232ea857d5.json, packages/react-components/react-motion-components-preview/library/package.json
This PR introduces a new package `@fluentui/react-motion-components-preview` to the Fluent UI library. This package includes motion components for Fluent UI.
=> feat(motion): Publish react-motion-components-preview

packages/react-components/react-motion-components-preview/stories/src/Collapse/CollapseCustomization.stories.tsx
replace destructured motionTokens with direct references
=> patch(motion): CollapseCustomization storybook small tweak

change/@fluentui-react-menu-07183362-d936-4cc5-8dc1-994303294df1.json, change/@fluentui-react-provider-7a9e89f8-f2ac-4573-ad55-28419b51fd3d.json, change/@fluentui-react-shared-contexts-308537af-a589-439b-b4ac-8f136d9a9504.json, packages/react-components/react-menu/library/src/components/MenuItemLink/MenuItemLink.tsx, packages/react-components/react-provider/library/etc/react-provider.api.md, packages/react-components/react-shared-contexts/library/etc/react-shared-contexts.api.md, packages/react-components/react-shared-contexts/library/src/CustomStyleHooksContext/CustomStyleHooksContext.ts
1. adds custom style hook for `MenuItemLink` to ensure style overrides
- Fixes #
=> chore(react-shared-contexts): adds custom style hook for MenuItemLink

packages/react-examples/src/react-charting/HeatMapChart/HeatMapChartBasic.CustomAccessibility.Example.tsx, packages/react-examples/src/react-charting/HeatMapChart/HeatMapChartBasic.Example.tsx, packages/react-examples/src/react-charting/VerticalBarChart/VerticalBarChart.Basic.Example.tsx
The colors for heatmap examples were not meeting accessibility standards in dark mode.
The label for VBC basic example was not meeting accessibility standards in dark mode.
The accessibility issues for colors in question are now fixed.
- Fixes #
=> Fix accessibility issue in heatmap and VBC basic

change/@fluentui-react-charting-0cc26e86-f67d-477c-94cc-ae1414e2bf1f.json, packages/react-charting/src/components/Legends/Legends.base.tsx
=> Fix "aria-required-children" accessibility issue in legends

packages/react-components/react-charts-preview/src/components/Sparkline/SparklineChartUT.test.tsx, packages/react-components/react-charts-preview/src/components/Sparkline/__snapshots__/SparklineChartUT.test.tsx.snap
Sparkline chart unit testcase is not present in there.
Added the Sparkline chart unit testcase with some configuration changes.
=> Adding the Sparkline chart unit testcase into the chartsV9.

change/@fluentui-react-charting-a4d7a053-1f0f-4c3f-85e1-08a276cad15e.json, packages/react-charting/src/components/SankeyChart/SankeyChart.base.tsx, packages/react-examples/src/react-charting/SankeyChart/SankeyChart.Reflow.Example.tsx, packages/react-examples/src/react-charting/SankeyChart/SankeyChartPage.tsx, packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.Reflow.Example.tsx, packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChartPage.tsx
Added reflow examples for the following charts on the demo site to facilitate testing of behavior when zooming and resizing the window:
- SankeyChart
- VerticalStackedBarChart
=> Add chart reflow examples

.devops/templates/build-test-lint.yml, .devops/templates/deployE2E.yml, azure-pipelines-ci.yml, azure-pipelines.bundlesize.yml, azure-pipelines.vrt-pr.yml
- master pipelines are failing https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=354760&view=logs&j=f5e89eef-ad59-58c9-614d-c2fd6081e79d&t=7dd77012-753a-5f35-bf96-92957bb518f2
- master pipelines are working
- Follows https://github.com/microsoft/fluentui/pull/31949
=> ci: update pipelines to run properly after move to nx

packages/react-components/react-charts-preview/src/components/Legends/Legends.styles.ts, packages/react-components/react-charts-preview/src/components/Legends/Legends.tsx, packages/react-components/react-charts-preview/src/components/Legends/Legends.types.ts, packages/react-components/react-charts-preview/src/components/Legends/OverflowMenu.tsx, packages/react-components/react-charts-preview/stories/Legends/Legends.Overflow.stories.tsx, packages/react-components/react-charts-preview/stories/Legends/Legends.Styled.stories.tsx, packages/react-components/react-charts-preview/stories/Legends/Legends.WrapLines.stories.tsx, packages/react-components/react-charts-preview/stories/Legends/LegendsBestPractices.md, packages/react-components/react-charts-preview/stories/Legends/LegendsDefault.stories.tsx, packages/react-components/react-charts-preview/stories/Legends/LegendsDescription.md, packages/react-components/react-charts-preview/stories/Legends/index.stories.tsx
=> Legend component V9

packages/fluentui/docs/project.json, packages/fluentui/e2e/project.json, packages/fluentui/state/project.json, packages/fluentui/styles/project.json
see PR title
- Unblocks https://github.com/microsoft/fluentui/pull/32168
=> chore(react-northstar): add missing project tags and add explicit bundle dep on v9 package from v0 app

packages/react-components/react-charts-preview/src/components/CommonComponents/CartesianChart.tsx, packages/react-components/react-charts-preview/src/components/LineChart/LineChartRTL.test.tsx, packages/react-components/react-charts-preview/src/components/LineChart/__snapshots__/LineChartRTL.test.tsx.snap, packages/react-components/react-charts-preview/stories/LineChart/LineChartCustomAccessibility.stories.tsx, packages/react-components/react-charts-preview/stories/LineChart/LineChartCustomLocaleDateAxis.stories.tsx, packages/react-components/react-charts-preview/stories/LineChart/LineChartDefault.stories.tsx, packages/react-components/react-charts-preview/stories/LineChart/LineChartEvents.stories.tsx, packages/react-components/react-charts-preview/stories/LineChart/LineChartGaps.stories.tsx, packages/react-components/react-charts-preview/stories/LineChart/LineChartLargeData.stories.tsx, packages/react-components/react-charts-preview/stories/LineChart/LineChartMultiple.stories.tsx, packages/react-components/react-charts-preview/stories/LineChart/LineChartStyled.stories.tsx
Vertical and Horizontal scrolls visible by default
Scrolls will appear according to container's width and height.
- Fixes #
=> line chart Overflow fix

scripts/fluentui-publish/project.json, scripts/fluentui-publish/src/utils.spec.ts
master pipeline is failing
- master is passing
- fluentui-publish uses now nx cache inputs in order to prevent invalid test state merge as happened in this PR https://github.com/microsoft/fluentui/pull/32210. with the input said, if anything within northstar projects project.json will change in future, fluentui-publish project would be marked as affected for `test` and those test will run on CI - failing if invalid ofc === preventing getting invalid PR shipped by automation 🙌 .
- Follows https://github.com/microsoft/fluentui/pull/32210
=> chore(scripts-fluentui-publish): update failing snapshots and add automation to prevent issues in future

packages/react-components/react-charts-preview/src/components/CommonComponents/CartesianChart.tsx, packages/react-components/react-charts-preview/src/components/CommonComponents/useCartesianChartStyles.styles.ts, packages/react-components/react-charts-preview/src/components/VerticalBarChart/useVerticalBarChartStyles.styles.ts, packages/react-components/react-charts-preview/src/utilities/utilities.ts, packages/react-components/react-charts-preview/stories/VerticalBarChart/VerticalBarChartCustomAccessibility.stories.tsx, packages/react-components/react-charts-preview/stories/VerticalBarChart/VerticalBarChartDefault.stories.tsx, packages/react-components/react-charts-preview/stories/VerticalBarChart/VerticalBarChartStyled.stories.tsx
Styling issues in VBC and LineChart as compared to their V8 version.
Fixed some styling issues , VBC and LC in V9 looking almost same as V8.
- Fixes #
=> Style fixes for VBC

packages/react-components/react-charts-preview/src/components/CommonComponents/CartesianChart.tsx, packages/react-components/react-charts-preview/src/components/CommonComponents/useCartesianChartStyles.styles.ts, packages/react-components/react-charts-preview/src/components/VerticalBarChart/VerticalBarChart.tsx, packages/react-components/react-charts-preview/src/components/VerticalBarChart/useVerticalBarChartStyles.styles.ts, packages/react-components/react-charts-preview/src/utilities/utilities.ts, packages/react-components/react-charts-preview/stories/VerticalBarChart/VerticalBarChartCustomAccessibility.stories.tsx, packages/react-components/react-charts-preview/stories/VerticalBarChart/VerticalBarChartDefault.stories.tsx, packages/react-components/react-charts-preview/stories/VerticalBarChart/VerticalBarChartRotateLabels.stories.tsx, packages/react-components/react-charts-preview/stories/VerticalBarChart/VerticalBarChartStyled.stories.tsx
Line not coming on some VBC examples and Rotated X axis labels not coming in a correct way.
Fixes made for the above issues.
- Fixes #
=> Line issue and Rotated labels fix

packages/react-components/react-charts-preview/src/components/CommonComponents/CartesianChart.tsx, packages/react-components/react-charts-preview/src/components/CommonComponents/CartesianChart.types.ts, packages/react-components/react-charts-preview/src/components/CommonComponents/PopoverComponent.styles.ts, packages/react-components/react-charts-preview/src/components/CommonComponents/PopoverComponent.tsx, packages/react-components/react-charts-preview/src/components/CommonComponents/PopoverComponent.types.ts, packages/react-components/react-charts-preview/src/components/DonutChart/DonutChart.tsx, packages/react-components/react-charts-preview/src/components/DonutChart/DonutChart.types.ts, packages/react-components/react-charts-preview/src/components/LineChart/LineChart.tsx
Popover for Cartesian Charts in v9.
Created a separate component for popover and moved the popover related logic outside of Cartesian base class.
Made changes for Cartesian and Line chart.
=> Popover for Cartesian charts v9

package.json, yarn.lock
see pr title and code comments
- Follows https://github.com/microsoft/fluentui/pull/32018
=> chore: override storybook esbuild version that introduced unwanted duplicates

change/@fluentui-react-swatch-picker-8e8d2425-44a5-4d89-9e44-9c31477a8858.json, packages/react-components/react-swatch-picker/library/README.md, packages/react-components/react-swatch-picker/library/docs/Spec.md
- Removed preview from the Spec
- Fixed the link on a docsite
=> docs(react-swatch-picker): removed preview from the docs

packages/react-components/react-charts-preview/src/components/CommonComponents/CartesianChart.types.ts, packages/react-components/react-charts-preview/src/components/CommonComponents/Popover.tsx, packages/react-components/react-charts-preview/src/components/CommonComponents/Popover.types.ts, packages/react-components/react-charts-preview/src/components/DonutChart/DonutChart.tsx, packages/react-components/react-charts-preview/src/components/HorizontalBarChart/HorizontalBarChart.tsx, packages/react-components/react-charts-preview/src/components/HorizontalBarChart/HorizontalBarChart.types.ts, packages/react-components/react-charts-preview/src/components/Legends/Legends.styles.ts, packages/react-components/react-charts-preview/src/components/Legends/Legends.tsx, packages/react-components/react-charts-preview/src/components/Legends/Legends.types.ts, packages/react-components/react-charts-preview/src/components/LineChart/LineChart.tsx, packages/react-components/react-charts-preview/src/components/VerticalBarChart/VerticalBarChart.tsx, packages/react-components/react-charts-preview/src/utilities/SVGTooltipText.tsx
Fixing build errors related to popover and legends
=> Fixing build errors related to popover and legends

common/changes/office-ui-fabric-react/hotfix_6-hotfix-5.135.6_2024-08-12-07-38.json, packages/office-ui-fabric-react/src/components/Nav/Nav.base.tsx
=> fix(hotfix/5.135.6): Fix the issue which Narrator announces the name twice in the Nav

.github/CODEOWNERS
v9 docs are owned by all core teams
- Fixes #
=> chore: update codeowners for public-docsite-v9

packages/react-components/react-charts-preview/src/components/CommonComponents/Popover.types.ts, packages/react-components/react-charts-preview/src/components/DonutChart/DonutChart.types.ts, packages/react-components/react-charts-preview/src/components/HorizontalBarChart/HorizontalBarChart.types.ts, packages/react-components/react-charts-preview/src/utilities/SVGTooltipText.tsx, packages/react-components/react-charts-preview/stories/LineChart/LineChartDefault.stories.tsx, packages/react-components/react-charts-preview/stories/VerticalBarChart/VerticalBarChartDefault.stories.tsx
Migrating SVGTooltipText component in V9.
Verified and added longer axis titles for showing tooltip in line and vertical bar charts.
=> Migrating SVGTooltipText component in V9

packages/react-components/react-charts-preview/src/components/VerticalBarChart/useVerticalBarChartStyles.styles.ts, packages/react-components/react-charts-preview/stories/LineChart/LineChartDefault.stories.tsx, packages/react-components/react-charts-preview/stories/VerticalBarChart/VerticalBarChartAxisTooltip.stories.tsx, packages/react-components/react-charts-preview/stories/VerticalBarChart/VerticalBarChartDefault.stories.tsx, packages/react-components/react-charts-preview/stories/VerticalBarChart/VerticalBarChartDynamic.stories.tsx
Styling issues in Dark mode of charts
Migrated certain components to their V9 counterparts. Fixed dark mode styling issues.
- Fixes #
=> dark mode fixes

azure-pipelines.release-vnext-nightly.yml
v9 nightly pipeline was failing
> example: https://dev.azure.com/uifabric/UI%20Fabric/_build/results?buildId=357908&view=logs&j=7494ae37-3ecd-50c6-9ffe-c77a2768c545&t=e235fce0-4c08-5eb3-76ea-6a7e2ddbac54
v9 nightly pipeline works
- Fixes #
=> ci(vNext-nightly-release): fix pipeline command typos

change/@fluentui-react-charting-41e2919e-7823-4579-a692-b0432e5669cb.json, packages/react-charting/src/utilities/gradients.ts
Updated `DataVizGradientPalette.disabled` color to E6E6E6
#32328
=> [issue 32328] Update Dataviz disabled color

scripts/gulp/src/plugins/gulp-jest.ts, scripts/gulp/src/tasks/test-unit.ts, scripts/tasks/src/jest.ts
- regression introduced https://github.com/microsoft/fluentui/pull/27680/files#diff-a320ba04ce63a10a6c1ae21ffaac61efe80164e0606e41516dea22e0fe7605a0
- see PR title
- Fixes https://github.com/microsoft/fluentui/issues/32284
=> fix(scripts/*): support -u and --updateSnapshot jest cli arguments for just-scripts and gulp wrappers

change/@fluentui-react-carousel-preview-1e847dc2-49b4-4356-877d-817c57c8d2cf.json, packages/react-components/react-carousel-preview/library/etc/react-carousel-preview.api.md, packages/react-components/react-carousel-preview/library/src/components/Carousel/Carousel.types.ts, packages/react-components/react-carousel-preview/library/src/components/Carousel/useCarousel.ts, packages/react-components/react-carousel-preview/library/src/components/Carousel/useCarouselContextValues.ts, packages/react-components/react-carousel-preview/library/src/components/CarouselAutoplayButton/CarouselAutoplayButton.types.ts, packages/react-components/react-carousel-preview/library/src/components/CarouselAutoplayButton/__snapshots__/CarouselAutoplayButton.test.tsx.snap, packages/react-components/react-carousel-preview/library/src/components/CarouselAutoplayButton/useCarouselAutoplayButton.tsx, packages/react-components/react-carousel-preview/library/src/components/CarouselCard/CarouselCard.types.ts, packages/react-components/react-carousel-preview/library/src/components/CarouselCard/__snapshots__/CarouselCard.test.tsx.snap, packages/react-components/react-carousel-preview/library/src/components/CarouselCard/useCarouselCard.ts, packages/react-components/react-carousel-preview/library/src/components/CarouselContext.ts, packages/react-components/react-carousel-preview/library/src/components/CarouselContext.types.ts, packages/react-components/react-carousel-preview/library/src/components/CarouselNav/__snapshots__/CarouselNav.test.tsx.snap, packages/react-components/react-carousel-preview/library/src/components/CarouselNav/useCarouselNav.ts, packages/react-components/react-carousel-preview/library/src/components/CarouselNav/useCarouselNavStyles.styles.ts, packages/react-components/react-carousel-preview/library/src/components/CarouselNavButton/__snapshots__/CarouselNavButton.test.tsx.snap, packages/react-components/react-carousel-preview/library/src/components/CarouselNavButton/useCarouselNavButton.ts, packages/react-components/react-carousel-preview/library/src/components/CarouselNavImageButton/__snapshots__/CarouselNavImageButton.test.tsx.snap, packages/react-components/react-carousel-preview/library/src/components/CarouselNavImageButton/useCarouselNavImageButton.ts, packages/react-components/react-carousel-preview/library/src/components/CarouselSlider/__snapshots__/CarouselSlider.test.tsx.snap, packages/react-components/react-carousel-preview/library/src/components/CarouselSlider/useCarouselSlider.ts, packages/react-components/react-carousel-preview/library/src/components/useEmblaCarousel.ts, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselAutoplay.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselAutoplayControlled.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselDefault.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselFocus.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/index.stories.tsx
Carousel cards are now navigable with left/right arrow keys _if_ the card is focusable.
Carousel cards are now grouped focus to dive into cards/buttons.
=> Carousel: Accessibility Focus

packages/react-components/react-color-picker-preview/library/src/components/ColorSlider/ColorSlider.test.tsx, packages/react-components/react-color-picker-preview/library/src/components/ColorSlider/useColorSliderState.ts
- Added tests for ColorSlider
- Fixed defaultValue
=> test(react-color-picker): added tests for ColorSlider

packages/react-components/react-charts-preview/src/components/CommonComponents/CartesianChart.tsx, packages/react-components/react-charts-preview/src/components/DonutChart/DonutChart.tsx, packages/react-components/react-charts-preview/src/components/LineChart/LineChart.tsx, packages/react-components/react-charts-preview/src/utilities/colors.ts, packages/react-components/react-charts-preview/stories/VerticalBarChart/VerticalBarChartDynamic.stories.tsx
No theme change in V9. 
LineChart Multiple example:
Light Theme:
Dark theme:
- Fixes #
=> Migration of Theme in V9 charts

packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselAutoplay.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselAutoplayControlled.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselCircular.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselControlled.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselDefault.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselFocus.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselFreeLayout.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselMultipleCards.stories.tsx
Carousel buttons had minimal aria, and failed a11y checks due to being icon buttons.
Carousel buttons now have correct aria enabled.
=> React-Carousel: Add aria labels to Carousel story buttons

packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselAutoplay.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselAutoplayControlled.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselCircular.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselControlled.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselDefault.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselFocus.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselFreeLayout.stories.tsx, packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselMultipleCards.stories.tsx
Carousel nav buttons had an icon only.
Carousel nav buttons now have tooltips to describe functionality for accessibility.
=> Carousel: Add tooltips to directional nav buttons

packages/react-components/react-color-picker-preview/library/src/components/ColorSlider/useColorSlider.ts, packages/react-components/react-color-picker-preview/library/src/components/ColorSlider/useColorSliderStyles.styles.ts
No focus indicator on focusing
=> fix(react-color-picker): focus for slider

change/@fluentui-react-charts-preview-ce35d45e-2f3e-40d5-9d4d-fafddc144d92.json, packages/react-components/react-charts-preview/library/src/components/Legends/Legends.tsx
=> Fixing background for legends

change/@fluentui-react-charts-preview-b87243b7-6b47-4e0b-8637-c62b22dcce04.json, packages/react-components/react-charts-preview/library/package.json, packages/react-components/react-charts-preview/library/src/components/CommonComponents/Popover.styles.ts, packages/react-components/react-charts-preview/library/src/components/CommonComponents/Popover.tsx, packages/react-components/react-charts-preview/library/src/components/VerticalBarChart/VerticalBarChart.tsx
Fixing popover content for cartesian and Vertical bar chart.
=> Fixing popover content for cartesian and Vertical bar chart

change/@fluentui-react-tree-64a47ec2-67cf-44bb-9343-ab2a859a1b8e.json, packages/react-components/react-tree/library/src/components/TreeItemLayout/useTreeItemLayout.tsx
=> fix(TreeItemLayout): Actions should not unmount between successive mouse events

packages/react-components/react-charts-preview/library/src/components/CommonComponents/CartesianChart.tsx, packages/react-components/react-charts-preview/library/src/components/CommonComponents/Popover.tsx, packages/react-components/react-charts-preview/library/src/components/Legends/Legends.tsx, packages/react-components/react-charts-preview/library/src/components/Legends/OverflowMenu.tsx, packages/react-components/react-charts-preview/library/src/components/LineChart/LineChart.tsx, packages/react-components/react-charts-preview/library/src/components/Sparkline/Sparkline.tsx, packages/react-components/react-charts-preview/library/src/components/VerticalBarChart/VerticalBarChart.tsx, packages/react-components/react-charts-preview/library/src/components/VerticalBarChart/useVerticalBarChartStyles.styles.ts
No FocusZone in V9 charts
Replaced FocusZone used in V8 to React-Tabster in V9.
- Fixes #
=> enabled Tabster in charts

docs/react-v9/contributing/rfcs/react-components/convergence/extended-design-tokens.md
This RFC outlines implementation details for an expansion of Fluent UI React's token system to enable better cross-platform support and more intuitive and predictable customization. It is effectively adding a new component token layer to complete the original tokens proposal, which today only includes global and alias. 
It is also part of a broader effort to align and unify tokens across various implementations of Microsoft's design system. This expanded token system will also serve as a mechanism to achieve visual alignment between products and libraries implementing Fluent 2. 
Prototype PRs:
- https://github.com/microsoft/fluentui/pull/31330
- https://github.com/microsoft/fluentui/pull/32104
Testing for Bundle Size of FUIR:
- https://github.com/microsoft/fluentui/pull/31672
- …
=> RFC: Extended Design Tokens for Fluent UI React

change/@fluentui-web-components-06b40f18-d31c-4dda-9e54-3f40fe95e658.json, packages/web-components/docs/api-report.md, packages/web-components/package.json, packages/web-components/src/accordion-item/accordion-item.stories.ts, packages/web-components/src/accordion/accordion.stories.ts, packages/web-components/src/anchor-button/anchor-button.stories.ts, packages/web-components/src/avatar/avatar.spec.ts, packages/web-components/src/avatar/avatar.stories.ts, packages/web-components/src/badge/badge.stories.ts, packages/web-components/src/button/button.stories.ts, packages/web-components/src/checkbox/checkbox.stories.ts, packages/web-components/src/helpers.stories.ts
Was using old stroybook API which broke some arg controls in stories.
1. Updates arg controls to work.
2. Adds some additional descriptions for better user expereince
3. Organizes attributes, slots and attributes into arg categories.
- Fixes #
=> Fix: cleans up stories Accordion - Checkbox

packages/web-components/src/anchor-button/anchor-button.stories.ts, packages/web-components/src/drawer/drawer.stories.ts, packages/web-components/src/field/field.stories.ts, packages/web-components/src/image/image.stories.ts, packages/web-components/src/label/label.spec.ts, packages/web-components/src/label/label.stories.ts, packages/web-components/src/link/link.spec.ts, packages/web-components/src/link/link.stories.ts, packages/web-components/src/menu-button/menu-button.stories.ts, packages/web-components/src/menu/menu.stories.ts
Fixes stories so all arg controls work and better aligns with new storybook 8 API
- Fixes #
=> fix: stories drawer to menu-button

packages/web-components/src/menu-list/menu-list.stories.ts, packages/web-components/src/message-bar/message-bar.integration.spec.ts, packages/web-components/src/message-bar/message-bar.stories.ts, packages/web-components/src/progress-bar/progress-bar.spec.ts, packages/web-components/src/progress-bar/progress-bar.stories.ts, packages/web-components/src/radio-group/radio-group.stories.ts, packages/web-components/src/radio/radio.stories.ts, packages/web-components/src/rating-display/rating-display.spec.ts, packages/web-components/src/rating-display/rating-display.stories.ts, packages/web-components/src/slider/slider.stories.ts, packages/web-components/src/spinner/spinner.spec.ts, packages/web-components/src/spinner/spinner.stories.ts, packages/web-components/src/switch/switch.stories.ts
Fixes story to better align with storybook 8 api and fixes broken arg controls
- Fixes #
=> fix: stories menu-list to switch

.github/ISSUE_TEMPLATE/01-react-components-bug-report.yml, .github/ISSUE_TEMPLATE/02-react-bug-report.yml, .github/ISSUE_TEMPLATE/03-react-charting-bug-report.yml, .github/ISSUE_TEMPLATE/04-web-components-bug-report.yml, .github/ISSUE_TEMPLATE/05-tooling-bug-report.yml, .github/ISSUE_TEMPLATE/06-documentation.yml, .github/ISSUE_TEMPLATE/07-feature-request.yml
needs triage and type bug labels are not added when creating issues
- needs triage and bug labels are added
- react-components explicitly states `v9`
- Follows #25697
=> docs(.github): use labels that match github db

packages/react-charting/src/components/AreaChart/AreaChartRTL.test.tsx, packages/react-charting/src/components/AreaChart/__snapshots__/AreaChartRTL.test.tsx.snap, packages/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChartRTL.test.tsx, packages/react-charting/src/components/LineChart/LineChartRTL.test.tsx, packages/react-charting/src/components/LineChart/__snapshots__/LineChartRTL.test.tsx.snap, packages/react-charting/src/components/VerticalBarChart/VerticalBarChartRTL.test.tsx, packages/react-charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChartRTL.test.tsx.snap, packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChartRTL.test.tsx
No test case present for secondary y axis in vertical bar chart and line chart, grouped vertical bar chart, area chart.
Added 4 test cases for secondary y axis in vertical bar chart and line chart, grouped vertical bar chart, area chart.
Added a test case for dynamic x Axis in vertical bar chart.
=> Added 4 test cases for secondary y axis.

packages/react-components/react-charts-preview/library/src/components/VerticalBarChart/VerticalBarChartRTL.test.tsx, packages/react-components/react-charts-preview/library/src/components/VerticalBarChart/__snapshots__/VerticalBarChartRTL.test.tsx.snap
No testcase are presents for xAxisInnerPadding, xAxisOuterPadding in vertical bar chart.
Added a test case for dynamic x Axis (xAxisInnerPadding, xAxisOuterPadding) in vertical bar chart.
=> Added a test case for dynamic x Axis in vertical bar chart.

packages/react-components/react-charts-preview/library/src/components/CommonComponents/CartesianChart.tsx, packages/react-components/react-charts-preview/library/src/components/LineChart/LineChart.tsx, packages/react-components/react-charts-preview/library/src/components/LineChart/eventAnnotation/LabelLink.tsx, packages/react-components/react-charts-preview/library/src/utilities/utilities.ts
Event annotation lines missing in LC Event chart example.
Event annotation lines visible now.
- Fixes #
=> Charts V9 P2 bugs

packages/react-components/react-charts-preview/library/src/components/CommonComponents/CartesianChart.tsx, packages/react-components/react-charts-preview/library/src/components/LineChart/LineChart.tsx
=> Rotate label fix 

.github/ISSUE_TEMPLATE/01-react-components-bug-report.yml
=> docs(.github): add missing components to v9 template

.github/CODEOWNERS
see PR title
- Follows https://github.com/microsoft/fluentui/pull/32935#issuecomment-2379312218
=> ci: add v-build to templates owners

packages/react-components/react-charts-preview/library/src/components/Legends/Legends.tsx, packages/react-components/react-charts-preview/library/src/components/Legends/shape.tsx, packages/react-components/react-charts-preview/stories/src/Legends/Legends.WrapLines.stories.tsx
Fixed following bugs:
1. Legends wrap lines - Legends are not getting wrapped.
2. There is lot of gap between 2 legend buttons
=> Fixing Legend related bugs

packages/react-components/react-charts-preview/library/src/components/CommonComponents/Popover.tsx, packages/react-components/react-charts-preview/library/src/components/CommonComponents/Popover.types.ts, packages/react-components/react-charts-preview/library/src/components/DonutChart/DonutChart.tsx, packages/react-components/react-charts-preview/library/src/components/HorizontalBarChart/HorizontalBarChart.tsx, packages/react-components/react-charts-preview/stories/src/DonutChart/DonutChartCustomCallout.stories.tsx, packages/react-components/react-charts-preview/stories/src/HorizontalBarChart/HorizontalBarChartCustomCallout.stories.tsx
Fixing custom popover not visible bug.
Addressed comment from PR https://github.com/microsoft/fluentui/pull/32973#discussion_r1787851065
=> Fixing custom popover not visible bug

change/@fluentui-react-charting-bf4c672a-5115-4c7f-ace9-28aad8089881.json, packages/react-charting/src/components/HorizontalBarChartWithAxis/HorizontalBarChartWithAxis.base.tsx, packages/react-charting/src/utilities/utilities.ts
XSS Vulnerabilities arise when you set the html directly. This can be exploited by changing label names to reveal sensitive information like document.cookie
Consider label name "<img src = "1" onError = {()=>{alert(document.cookie)}> for example. Instead of displaying the tooltip, this would reveal the cookie when hovering over the label
Setting the text content instead helps prevent XSS attacks. Changes have been tested locally and work as expected
- Fixes #
=> XSS Vulnerability fix

packages/web-components/package.json, packages/web-components/src/horizontalbarchart/horizontalbarchart.options.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.styles.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.ts
No callout integrated to chart.
Integrated callout to multi stacked bar chart.
- Fixes #
=> added callout to multi stacked bar chart

packages/web-components/src/donut-chart/define.ts, packages/web-components/src/donut-chart/donut-chart.bench.ts, packages/web-components/src/donut-chart/donut-chart.definition.ts, packages/web-components/src/donut-chart/donut-chart.options.ts, packages/web-components/src/donut-chart/donut-chart.stories.ts, packages/web-components/src/donut-chart/donut-chart.styles.ts, packages/web-components/src/donut-chart/donut-chart.template.ts, packages/web-components/src/donut-chart/donut-chart.ts, packages/web-components/src/donut-chart/index.ts, packages/web-components/src/index-rollup.ts, packages/web-components/src/index.ts
=> Add web component for donut chart

apps/public-docsite-v9/src/Concepts/Migration/FromV8/ComponentMapping.stories.mdx
- extra line breaks
- wrong note used
- removed the extra line breaks
- updated the component note used
- Fixes #
=> Update Component Mapping in Storybook

apps/public-docsite-v9/src/Concepts/Migration/FromV8/ComponentMapping.stories.mdx
Fix icons link, and remove unneeded content from the list
- Broken icons link, and unneeded content from the list depreciated v8 comps 
- Fixed icons link, and remove unneeded content from the list depreciated v8 comps
- Fixes #
=> Update Component Mapping

packages/react-components/react-charts-preview/stories/src/DonutChart/DonutChartCustomCallout.stories.tsx, packages/react-components/react-charts-preview/stories/src/HorizontalBarChart/HorizontalBarChartCustomCallout.stories.tsx
Fixing styles for custom callout stories in light and dark mode
=> Fixing styles for custom callout stories

change/@fluentui-react-search-bc262058-7b41-42f9-beb3-dfa1f21663ab.json, packages/react-components/react-search/library/src/components/SearchBox/useSearchBoxStyles.styles.ts, packages/react-components/react-text/stories/src/Text/TextTruncate.stories.tsx
=> fix(react-searchbox): resolve ghost pointer events

packages/web-components/src/horizontalbarchart/horizontalbarchart.stories.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.styles.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.ts
No legends in chart.
Legends functional in chart now.
- Fixes #
=> Added legend functionality to Horizontal Bar chart

packages/react-components/react-charts-preview/library/src/components/Legends/useLegendsStyles.styles.ts
Fixing alignment issue of legends
=> Fixing alignment issue of legends

packages/web-components/src/donut-chart/donut-chart.options.ts, packages/web-components/src/donut-chart/donut-chart.stories.ts, packages/web-components/src/donut-chart/donut-chart.styles.ts, packages/web-components/src/donut-chart/donut-chart.template.ts, packages/web-components/src/donut-chart/donut-chart.ts, packages/web-components/src/utils/chart-helpers.ts, packages/web-components/src/utils/converters.ts
=> Add more functionalities to donut chart

packages/web-components/src/horizontalbarchart/horizontalbarchart.stories.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.styles.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.ts
No NM Variant for MultiStacked Bar chart
NM Variant of MultiStacked Bar chart
- Fixes #
=> NM Variant of MultiStacked bar chart

packages/react-components/react-charts-preview/library/etc/react-charts-preview.api.md, packages/react-components/react-charts-preview/library/src/components/CommonComponents/CartesianChart.tsx, packages/react-components/react-charts-preview/library/src/components/CommonComponents/CartesianChart.types.ts, packages/react-components/react-charts-preview/library/src/components/CommonComponents/ChartPopover.tsx, packages/react-components/react-charts-preview/library/src/components/CommonComponents/ChartPopover.types.ts, packages/react-components/react-charts-preview/library/src/components/CommonComponents/PopoverRTL.test.tsx, packages/react-components/react-charts-preview/library/src/components/CommonComponents/index.ts, packages/react-components/react-charts-preview/library/src/components/CommonComponents/useChartPopoverStyles.styles.ts, packages/react-components/react-charts-preview/library/src/components/DonutChart/DonutChart.tsx, packages/react-components/react-charts-preview/library/src/components/DonutChart/DonutChart.types.ts, packages/react-components/react-charts-preview/library/src/components/HorizontalBarChart/HorizontalBarChart.tsx, packages/react-components/react-charts-preview/library/src/components/HorizontalBarChart/HorizontalBarChart.types.ts, packages/react-components/react-charts-preview/library/src/components/LineChart/__snapshots__/LineChartRTL.test.tsx.snap, packages/react-components/react-charts-preview/library/src/components/VerticalBarChart/VerticalBarChart.tsx, packages/react-components/react-charts-preview/library/src/components/VerticalBarChart/__snapshots__/VerticalBarChartRTL.test.tsx.snap
Making changes for Popover component
=> Making changes for Popover component

packages/react-components/react-charts-preview/stories/src/DonutChart/DonutChartCustomCallout.stories.tsx, packages/react-components/react-charts-preview/stories/src/HorizontalBarChart/HorizontalBarChartCustomCallout.stories.tsx
=> Fixing build errors in V9

packages/web-components/src/horizontalbarchart/horizontalbarchart.stories.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.styles.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.ts
1. Added Horizontal Bar Chart Absolute scale variant
2. Dark mode and RTL bug fixes for MultiStacked bar chart.
- Fixes #
=> Horizontal Bar chart as Web component

packages/web-components/src/donut-chart/donut-chart.options.ts, packages/web-components/src/donut-chart/donut-chart.stories.ts, packages/web-components/src/donut-chart/donut-chart.styles.ts, packages/web-components/src/donut-chart/donut-chart.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.options.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.ts, packages/web-components/src/utils/chart-helpers.ts
- Update styles as per design
- Add high contrast and RTL styles
- Add DataVizPalette
- Implement color fallback from DataVizPalette for arcs
- Assign appropriate role and aria attributes to legends
=> Add color palette for data visualization

packages/eslint-plugin/jest.config.js, scripts/generators/.eslintrc.json, scripts/generators/package.json
Preparation for https://github.com/microsoft/fluentui/pull/33074
- Fixes #
=> chore: prepare project setup for inferred plugin enablement

packages/web-components/src/horizontalbarchart/horizontalbarchart.options.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.stories.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.ts
NM Variant of SingleBar HBC
- Fixes #
=> Single Bar HBC NM Variant

packages/web-components/src/donut-chart/donut-chart.options.ts, packages/web-components/src/donut-chart/donut-chart.stories.ts, packages/web-components/src/donut-chart/donut-chart.styles.ts, packages/web-components/src/donut-chart/donut-chart.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.options.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.ts, packages/web-components/src/utils/chart-helpers.ts
- Override default rectangular focus outline around arcs
- Wrap text inside donut
- Fix ts errors
=> Fix bugs in donut-chart web component

packages/charts/react-charts-preview/library/src/components/DonutChart/Pie/usePieStyles.styles.ts, packages/charts/react-charts-preview/library/src/components/Legends/Legends.tsx, packages/charts/react-charts-preview/library/src/components/Legends/useLegendsStyles.styles.ts
Fixed the following high contrast bugs:
1. [[V9] [Doc site][High contrast] Donut chart data do not present for all the donut charts](https://uifabric.visualstudio.com/iss/_workitems/edit/11572)
2. [[V9] [Doc site][High contrast] when we mouse over on the first legend first the legend is not getting highlighted for time for all the charts.](https://uifabric.visualstudio.com/iss/_workitems/edit/11569/)
=> Fixing High Contrast Bugs - Part 1

packages/web-components/src/donut-chart/donut-chart.options.ts, packages/web-components/src/donut-chart/donut-chart.styles.ts, packages/web-components/src/donut-chart/donut-chart.template.ts, packages/web-components/src/donut-chart/donut-chart.ts
- Move legends and tooltip to template
=> Refactor donut-chart web component

packages/web-components/src/horizontalbarchart/horizontalbarchart.styles.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.template.ts, packages/web-components/src/horizontalbarchart/horizontalbarchart.ts
- Move legends and tooltip to template
=> Refactor horizontalbarchart web component

.github/scripts/bundle-size-comment.js, .github/scripts/deploy-pr-site-status.js, .github/workflows/pr-website-deploy-comment.yml
- fixes typo of setting `outputs` for website deploy 
- no output was set  <img width="604" alt="image" src="https://github.com/user-attachments/assets/8c90e914-93c1-4576-bfe6-152f4a6f26e0">
- scripts live in valid path so workflows can load them https://github.com/microsoft/fluentui/actions/runs/11631819542/job/32393807513
- Follows https://github.com/microsoft/fluentui/pull/33188
=> ci(.github): move scripts to .github root to fix invalid paths within workflows and fix deploy url output

change/@fluentui-react-motion-components-preview-ce97692b-d797-47e0-ad42-4d0561a9f7da.json, packages/react-components/react-motion-components-preview/library/etc/react-motion-components-preview.api.md, packages/react-components/react-motion-components-preview/library/src/components/Collapse/Collapse.ts, packages/react-components/react-motion-components-preview/library/src/components/Fade/Fade.test.tsx, packages/react-components/react-motion-components-preview/library/src/components/Fade/Fade.ts, packages/react-components/react-motion-components-preview/library/src/components/Scale/Scale.ts, packages/react-components/react-motion-components-preview/library/src/index.ts, packages/react-components/react-motion-components-preview/stories/src/Collapse/CollapseExaggerated.stories.md, packages/react-components/react-motion-components-preview/stories/src/Collapse/CollapseRelaxed.stories.md, packages/react-components/react-motion-components-preview/stories/src/Collapse/CollapseRelaxed.stories.tsx, packages/react-components/react-motion-components-preview/stories/src/Collapse/index.stories.ts, packages/react-components/react-motion-components-preview/stories/src/Fade/FadeExaggerated.stories.md, packages/react-components/react-motion-components-preview/stories/src/Fade/FadeRelaxed.stories.md, packages/react-components/react-motion-components-preview/stories/src/Fade/FadeRelaxed.stories.tsx, packages/react-components/react-motion-components-preview/stories/src/Fade/index.stories.ts, packages/react-components/react-motion-components-preview/stories/src/Scale/ScaleExaggerated.stories.md, packages/react-components/react-motion-components-preview/stories/src/Scale/ScaleRelaxed.stories.md, packages/react-components/react-motion-components-preview/stories/src/Scale/ScaleRelaxed.stories.tsx, packages/react-components/react-motion-components-preview/stories/src/Scale/index.stories.ts
The component variant names for exaggerated animations are currently as follows:
- `FadeExaggerated`
- `CollapseExaggerated`
- `ScaleExaggerated`
These variants are used in code as shown:
```jsx
<FadeExaggerated visible={visible}>
{content}
</FadeExaggerated>
```
The exaggerated variant names are now updated to "Relaxed" to align with the revised variant specifications:
- `FadeExaggerated` is now `FadeRelaxed`
- `CollapseExaggerated` is now `CollapseRelaxed`
- `ScaleExaggerated` is now `ScaleRelaxed`
Example usage in code:
```jsx
<FadeRelaxed visible={visible}>
{content}
</FadeRelaxed>
```
[Fluent Motion Component Defaults / Variants Values](https://loop.cloud.microsoft/p/eyJ3Ijp7InUiOiJodHRwczovL21pY3Jvc29mdC5zaGFyZXBvaW50LWRmLmNvbS8%2FbmF2PWN6MGxNa1ltWkQxaUlVZGtPVkJhWlRGUU1tdFBWSEpxVkdKY …
=> Rename motion component variants ...Exaggerated to ...Relaxed

packages/charts/chart-web-components/src/horizontal-bar-chart/horizontal-bar-chart.stories.ts, packages/charts/chart-web-components/src/horizontal-bar-chart/horizontal-bar-chart.styles.ts, packages/charts/chart-web-components/src/horizontal-bar-chart/horizontal-bar-chart.ts
Fixed Bugs:
1. HBC: For longest bar the label is not coming.
2. HBC: Chart width is hardcoded
3. HBC: Callout getting cropped at ends of bar.
4. HBC: Focus ring on pressing tab key is coming cropped.
- Fixes #
=> bug fixes for horizontal bar chart web component

packages/charts/chart-web-components/src/donut-chart/donut-chart.ts, packages/charts/chart-web-components/src/horizontal-bar-chart/horizontal-bar-chart.template.ts, packages/charts/chart-web-components/src/horizontal-bar-chart/horizontal-bar-chart.ts
=> removed tabster dependency.

change/@fluentui-react-charts-preview-58b91aec-3ab4-4800-8840-01b596b97179.json, packages/charts/react-charts-preview/library/README.md
Update charts v9 readme with the current content
- Fixes #
=> Update charts v9 readme

apps/public-docsite-v9/.storybook/main.js, packages/charts/react-charts-preview/library/src/components/CommonComponents/ChartPopover.tsx
PR workflow for master commits is not enabled currently.
In the interim, changing chart docsite link to a demo site deployed on a PR till master workflow is fixed.
Use a self deployed docsite for charts till we get the fluent master pipeline up and running.
- Fixes #
=> chore: Update chart docsite link to a deployed pr site

packages/react-components/react-tag-picker/library/src/components/TagPicker/TagPicker.cy.tsx
=> Fix TagPicker cypress

scripts/package-manager/src/notify-on-file-changes.js
=> fix: misaligned git pull hook banner

change/@fluentui-react-dialog-10d49a9d-5b61-4278-8faa-2d5b00e5f538.json, packages/react-components/react-dialog/library/package.json, packages/react-components/react-dialog/library/src/components/DialogBackdropMotion.ts
Custom motion logic in `DialogBackdropMotion` increased code duplication and limited reusability.
Replaced `DialogBackdropMotion` implementation with the `FadeRelaxed` motion component from `@fluentui/react-motion-components-preview`, enabling consistent and reusable motion.
Analyze existing Dialog and DialogBackdrop motion implementations for compatibility with Fade motion.
- Fixes #33306
=> feat(motion): update DialogBackdropMotion to use FadeRelaxed

packages/charts/chart-web-components/src/donut-chart/donut-chart.ts
=> Update text inside Donut chart fix

packages/charts/react-charting/etc/react-charting.api.md, packages/charts/react-charting/src/index.ts, packages/charts/react-charting/src/plotly-utils.tsx, packages/react-examples/src/react-charting/LineChart/LineChart.Plotly.Example.tsx, packages/react-examples/src/react-charting/LineChart/LineChart.doc.tsx, packages/react-examples/src/react-charting/LineChart/LineChartPage.tsx, packages/react-examples/src/react-charting/LineChart/index.stories.tsx, packages/react-examples/src/react-charting/LineChart/plotly-schema-line.json, packages/react-examples/src/react-charting/LineChart/plotly-utils.tsx
Line chart plotly adapter with example
=> Line chart plotly adapter

packages/charts/react-charting/etc/react-charting.api.md, packages/charts/react-charting/src/index.ts, packages/charts/react-charting/src/plotly-utils.tsx, packages/react-examples/src/react-charting/HorizontalBarChart/HorizontalBarChart.Plotly.Example.tsx, packages/react-examples/src/react-charting/HorizontalBarChart/HorizontalBarChart.doc.tsx, packages/react-examples/src/react-charting/HorizontalBarChart/HorizontalBarChartPage.tsx, packages/react-examples/src/react-charting/HorizontalBarChart/index.stories.tsx
Rendering Horizontal bar chart with data in Plotly schema with Example
=> Rendering Horizontal bar chart with data in Plotly schema

packages/charts/chart-web-components/src/horizontal-bar-chart/horizontal-bar-chart.styles.ts, packages/charts/chart-web-components/src/horizontal-bar-chart/horizontal-bar-chart.template.ts
Fixed bugs:
1. https://uifabric.visualstudio.com/iss/_workitems/edit/11592
2. https://uifabric.visualstudio.com/iss/_workitems/edit/11589
3. https://uifabric.visualstudio.com/iss/_workitems/edit/11588
4. https://uifabric.visualstudio.com/iss/_workitems/edit/11574
5. https://uifabric.visualstudio.com/iss/_workitems/edit/11632
- Fixes #
=> high contrast bug fixes

packages/charts/chart-web-components/src/donut-chart/donut-chart.stories.ts, packages/charts/chart-web-components/src/horizontal-bar-chart/horizontal-bar-chart.stories.ts
=> Order of Stories

packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/react-examples/src/react-charting/DeclarativeChart/schema/fluent_donut.json
=> Add heatmap chart plotly adapter

packages/charts/react-charting/package.json, packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
=> Add Sankey chart Plotly Adapter

packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/react-examples/src/react-charting/DeclarativeChart/schema/fluent_gauge.json
=> Add gauge chart plotly adapter and example

change/@fluentui-react-charting-7cca2ab0-3c7f-42a3-9739-cf8ba2e5b048.json, packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
=> feat(react-charting): add plotly adapter for grouped vertical bar chart

change/@fluentui-react-tooltip-783b798d-8864-492c-a76d-bd4fdc1d0775.json, packages/react-components/react-tooltip/library/src/components/Tooltip/Tooltip.types.ts, packages/react-components/react-tooltip/library/src/components/Tooltip/useTooltip.tsx
https://github.com/user-attachments/assets/c33c52c0-2def-4ba5-b5a2-4f2813d0004a
https://github.com/user-attachments/assets/c033ebcf-671f-4efb-af13-90ecd5232654
- Fixes #31639
=> feat(react-tooltip): do not show tooltip, if it's applied to menu trigger and menu is opened

change/@fluentui-react-charting-eda70f4c-d886-4d6a-bc92-830c92031e43.json, packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
=> feat(react-charting): add plotly adapter for histogram

packages/react-components/react-color-picker-preview/stories/package.json, packages/react-components/react-color-picker-preview/stories/src/ColorPicker/index.stories.tsx
- Added `tinycolor` as dev dependency for stories
- Added subcomponents
=> docs(react-color-picker): added subcomponents

change/@fluentui-react-tabs-7a95002f-25eb-47c0-9f9b-a77ffdef753a.json, packages/react-components/react-tabs/library/src/components/Tab/useTabStyles.styles.ts
Adjust circular tab styles according to [Figma designs](https://www.figma.com/design/dK5AnDvvnSTWV9lduQWeDk/TabList?node-id=5087-9997&t=ntTTizIQg2rnQ4zY-1)
=> fix(react-tabs): adjust styles for circular tabs

packages/react-components/react-color-picker-preview/library/bundle-size/ColorArea.fixture.js, packages/react-components/react-color-picker-preview/library/bundle-size/ColorPicker.fixture.js, packages/react-components/react-color-picker-preview/library/bundle-size/ColorSlider.fixture.js
Added bundle size configuration for the ColorPicker
=> fix(react-color-picker): added bundle size configuration

apps/vr-tests-react-components/src/stories/SwatchPicker/SwatchPicker.stories.tsx, apps/vr-tests-react-components/src/stories/SwatchPicker/utils.tsx
Fixed VR tests for the SwatchPicker.
=> test(react-swatch-picker): fixed VR tests.

change/@fluentui-react-charting-db3ac682-461d-4b7b-8f24-eeb42fe5e64b.json, packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx, packages/charts/react-charting/src/components/DeclarativeChart/imageExporter.ts
=> fix(react-charting): resolve css variables in svg image data

change/@fluentui-react-charting-5e13d62c-9372-4a66-84d6-a1e6cab63291.json, packages/charts/react-charting/etc/react-charting.api.md, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx, packages/charts/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.types.tsx, packages/charts/react-charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx, packages/charts/react-charting/src/components/VerticalBarChart/VerticalBarChart.types.ts, packages/charts/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx, packages/charts/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.types.ts
=> feat(react-charting): center align bars with auto barWidth in plotly mode

change/@fluentui-react-charting-be791d81-9cfb-4576-961c-03c4f6eb85c0.json, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
=> Sankey and gauge chart fix

packages/react-components/react-carousel/stories/src/Carousel/index.stories.tsx
carousel is not following title pattern
carousel is following title pattern
- Issues exposed when using automation https://github.com/microsoft/fluentui/pull/33555
=> docs(react-carousel): normalize title creation within storybook menu

change/@fluentui-web-components-49fd3f00-10b9-4573-a6ac-bce95c8f2fe5.json, packages/web-components/src/spinner/spinner.styles.ts
=> [web-components] fix: remove logical properties to fix spinner in rtl

packages/react-components/react-dialog/stories/src/Dialog/DialogAlert.stories.tsx, packages/react-components/react-dialog/stories/src/Dialog/DialogChangeFocus.stories.tsx, packages/react-components/react-dialog/stories/src/Dialog/DialogControllingOpenAndClose.stories.tsx, packages/react-components/react-dialog/stories/src/Dialog/DialogCustomTrigger.stories.tsx, packages/react-components/react-dialog/stories/src/Dialog/DialogDefault.stories.tsx, packages/react-components/react-dialog/stories/src/Dialog/DialogFluidDialogActions.stories.tsx, packages/react-components/react-dialog/stories/src/Dialog/DialogScrollingLongContent.stories.tsx, packages/react-components/react-dialog/stories/src/Dialog/DialogTriggerOutsideDialog.stories.tsx, packages/react-components/react-dialog/stories/src/Dialog/DialogWithForm.stories.tsx
Reorders actions on `Dialog`s to give priority to primary actions
- Fixes https://github.com/microsoft/fluentui/issues/33601
=> docs: reorder buttons on footer to give priority to primary action

azure-pipelines.release.web-components.yml
Release pipeline is building the web-components package only.
Updated the Build test lint command to use `web-components` tag to allow any project marked with this tag to be built and released.
- Fixes #
=> chore(web-components): Update build tag to enable building charts web component package

change/@fluentui-chart-web-components-cfdeb418-e440-4904-9a73-4b8291c7c99d.json, change/@fluentui-chart-web-components-dfff0cf0-8ca6-4c11-aacb-bdd0e7090bbb.json, packages/charts/chart-web-components/CHANGELOG.json, packages/charts/chart-web-components/CHANGELOG.md, packages/charts/chart-web-components/package.json
web-components release pipeline failed (packages have been released to npm successfully) when pushing updates back to origin. 
This is a manual version bump in order to sync changes from CI to master with npm.
> ran via `yarn beachball bump -b upstream/master --access public --no-fetch --no-publish --no-push --no-git-tags --verbose --config ./scripts/beachball/src/release-web-components.config.js`
- Fixes #
=> release: applying package updates - web-components

change/@fluentui-react-charting-cb76b3ea-9897-40ea-8f98-241f3265bb1a.json, packages/charts/react-charting/src/components/SankeyChart/SankeyChart.base.tsx
=> fix(react-charting): Sankey chart Dark mode fix

docs/react-v9/contributing/rfcs/react-components/styles-handbook.md
Current link has a 404
New link works
- Fixes ##33653
=> Update styles-handbook.md with working URL

packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx
https://uifabric.visualstudio.com/iss/_workitems/edit/12161
fix: handle scatter plot with markers mode in plotly
=> fix: [BUG 12161] handle scatter plot with markers mode in plotly

apps/vr-tests-react-components/src/stories/Charts/DonutChart.stories.tsx, apps/vr-tests-react-components/src/stories/Charts/HorizontalBarChart.stories.tsx, apps/vr-tests-react-components/src/stories/Charts/LineChart.stories.tsx, apps/vr-tests-react-components/src/stories/Charts/VerticalBarChart.stories.tsx, apps/vr-tests/src/stories/react-charting/AreaChart.stories.tsx, apps/vr-tests/src/stories/react-charting/DonutChart.stories.tsx, apps/vr-tests/src/stories/react-charting/HeatMapChart.stories.tsx, apps/vr-tests/src/stories/react-charting/HorizontalBarChart.stories.tsx, apps/vr-tests/src/stories/react-charting/LineChart.stories.tsx, apps/vr-tests/src/stories/react-charting/Piechart.stories.tsx, apps/vr-tests/src/stories/react-charting/StackedBarChart.stories.tsx, apps/vr-tests/src/stories/react-charting/VerticalBarChart.stories.tsx
This PR resolves the following error:
=> fix(vr-tests): set a fixed value for culture prop in charts

packages/react-components/react-card/stories/src/CardFooter/CardFooterDefault.stories.tsx
No description for "More options " button. Narrator read "button".
Added `aria-label`. Narrator reads "More options button"
=> docs(react-card): added aria-label to the action button in CardFooter

packages/react-components/react-combobox/stories/src/Dropdown/DropdownAccessibility.md, packages/react-components/react-combobox/stories/src/Dropdown/DropdownActiveOptionChange.stories.tsx, packages/react-components/react-combobox/stories/src/Dropdown/DropdownAppearance.stories.tsx, packages/react-components/react-combobox/stories/src/Dropdown/DropdownClearable.stories.tsx, packages/react-components/react-combobox/stories/src/Dropdown/DropdownComplexOptions.stories.tsx, packages/react-components/react-combobox/stories/src/Dropdown/DropdownControllingOpenAndClose.stories.tsx, packages/react-components/react-combobox/stories/src/Dropdown/DropdownCustomOptions.stories.tsx, packages/react-components/react-combobox/stories/src/Dropdown/DropdownDefault.stories.tsx, packages/react-components/react-combobox/stories/src/Dropdown/DropdownDisabled.stories.tsx, packages/react-components/react-combobox/stories/src/Dropdown/DropdownField.stories.tsx, packages/react-components/react-combobox/stories/src/Dropdown/DropdownGrouped.stories.tsx, packages/react-components/react-combobox/stories/src/Dropdown/DropdownMultiselect.stories.tsx, packages/react-components/react-combobox/stories/src/Dropdown/DropdownSize.stories.tsx, packages/react-components/react-combobox/stories/src/Dropdown/DropdownTruncation.stories.tsx, packages/react-components/react-combobox/stories/src/Dropdown/index.stories.tsx
Some Dropdown docs cleanup around labelling, since someone reached out to ask about best practices.
=> docs: update outdated DropdownField mention and links, add Field story, update labelling techniques

apps/vr-tests-react-components/src/stories/Button/SplitButton.stories.tsx
=> test(Button): add SplitButton vr test

change/@fluentui-react-charting-27c31443-3ca0-4a15-a096-63b02a2e8df7.json, packages/charts/react-charting/src/utilities/SVGTooltipText.tsx
Adding transform prop to svg rect
Work item https://uifabric.visualstudio.com/iss/_workitems/edit/12235
After fix:
=> fix(react-charting): Adding transform prop to svg rect

.github/workflows/pr-vrt-comment.yml
Reverts microsoft/fluentui#33627
=> revert: ci(gha): limit privileged vrt workflow trigger branch base

.github/workflows/pr-vrt-comment.yml
=> ci: Testing VRT CI Comment workflow

change/@fluentui-react-charting-5970a5c2-cc2c-405e-b997-bb57b3774563.json, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapterUT.test.tsx, packages/charts/react-charting/src/components/DeclarativeChart/__snapshots__/DeclarativeChartRTL.test.tsx.snap, packages/charts/react-charting/src/components/DeclarativeChart/__snapshots__/PlotlySchemaAdapterUT.test.tsx.snap
Pie chart labels fix
- Fixes #
=> fix(declarative-chart): Fix Plotly Schema Adpater UT cases

yarn.lock
udpates db to get rid of warning in builds that leverage browserlist
- Fixes #
=> chore: update browserlist-db

.github/workflows/pr-vrt-comment.yml
Removed API_TOKEN which was giving error in the earlier workflow run.
=> TEST GITHUB ACTIONS VRT FLOW V1

.github/workflows/pr-vrt-comment.yml
=> Added permissions- ID-TOKEN

packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorPickerDefault.stories.tsx
Arrows of SpinButton for ColorPicker didn't work. Only keyboard changes.
Arrows work
=> fix(react-color-picker): spin button arrows for ColorPicker

.github/CODEOWNERS
=> chore: update CODEOWNERS for motion

.github/workflows/pr-vrt-poc-comment.yml
privileged workflow needs to live in main branch, otherwise it wont be triggered
- Fixes #
=> ci: add pr-vrt-poc-comment privileged pipeline for vrt reports testing

.github/workflows/pr-vrt-poc-comment.yml
=> ci: use html_url and add workflow_run debug output to pr-vrt-poc-comment workflow

change/@fluentui-react-charting-f29b6057-b08e-4d41-b79c-40784c6c5823.json, packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx
Work item: https://uifabric.visualstudio.com/iss/_workitems/edit/12465
Handle invalid plotly data
=> fix(react-charting): Handle invalid plotly data

change/@fluentui-web-components-ba96d676-f7a7-4a30-bc9f-0afbdbb1f478.json, packages/web-components/src/tree-item/tree-item.styles.ts, packages/web-components/src/tree-item/tree-item.template.ts, packages/web-components/src/tree-item/tree-item.ts, packages/web-components/src/tree/tree.stories.ts
We were not filtering for the tree-items specfically.
Added filtering to the template.
- Fixes #
=> [fix] move filter for tree-items into children directive

change/@fluentui-web-components-07245748-cbf6-49de-b1bf-13d1f545179f.json, packages/web-components/docs/web-components.api.md, packages/web-components/src/tree-item/index.ts, packages/web-components/src/tree-item/tree-item.base.ts, packages/web-components/src/tree-item/tree-item.options.ts, packages/web-components/src/tree-item/tree-item.spec.ts, packages/web-components/src/tree-item/tree-item.styles.ts, packages/web-components/src/tree-item/tree-item.template.ts, packages/web-components/src/tree-item/tree-item.ts, packages/web-components/src/tree/index.ts, packages/web-components/src/tree/tree.base.ts, packages/web-components/src/tree/tree.stories.ts, packages/web-components/src/tree/tree.template.ts, packages/web-components/src/tree/tree.ts
Style and appearance api bundled in class.
Removes style and appearance api from class.
It also removes the `badging` and `toolbar` slot and consolidates it to an `aside` slot which matches the fluent api
https://react.fluentui.dev/?path=/docs/components-tree--docs#aside
- Fixes #
=> [chore]: refactor out base classes for tree and tree-item

.github/dependabot.yml
- Fixes https://github.com/microsoft/fluentui/runs/38888565000
=> ci: fix invalid dependabot config for schedule

packages/web-components/src/tree-item/tree-item.spec.ts, packages/web-components/src/tree-item/tree-item.stories.ts, packages/web-components/src/tree/tree.stories.ts
-
Added extra test coverage for `empty` tree-item. Also added more stories
- Fixes #
=> [chore] add tree-item test and stories

.github/CODEOWNERS, tools/visual-regression-utilities/.eslintrc.json, tools/visual-regression-utilities/.swcrc, tools/visual-regression-utilities/README.md, tools/visual-regression-utilities/jest.config.ts, tools/visual-regression-utilities/package.json, tools/visual-regression-utilities/project.json, tools/visual-regression-utilities/src/TestWrapperDecorator.tsx, tools/visual-regression-utilities/src/getStoryVariant.spec.tsx, tools/visual-regression-utilities/src/getStoryVariant.tsx, tools/visual-regression-utilities/src/index.ts, tools/visual-regression-utilities/tsconfig.json, tools/visual-regression-utilities/tsconfig.lib.json, tools/visual-regression-utilities/tsconfig.spec.json, tsconfig.base.all.json, tsconfig.base.json
Creates new vrt utilities package 
- extracted from vr-tests-react-components
- updated API to support explicitly on CSF3 format
- Fixes #
=> feat(vr-utilities): implement vrt utilities package

apps/public-docsite-v9/src/Concepts/Migration/FromV8/Components/ColorPicker.stories.mdx
Migration file for the ColorPicker
#33771
=> docs(react-color-picker): added migration doc

.github/workflows/pr-vrt-poc.yml
=> ci(vrt-poc): use api result to checkout forked branch on PR

.github/workflows/pr-vrt-poc.yml
=> ci(vrt-poc): use explicit base and head for nx affected

.github/workflows/pr-vrt-comment.yml, .github/workflows/vrt-baseline.yml
- Errors in VRT | Comment on PR workflow
- Fix the issue with file paths
- Fixes #
=> Bump version to 1.0.0-test.1742488629090

change/@fluentui-react-charting-364ea844-fc47-4dc9-a1ad-5e297a214b3f.json, packages/charts/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx, packages/charts/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChartRTL.test.tsx.snap, packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.Basic.Example.tsx
=> fix(react-charting): Add scaling factor to heights of VerticalStacked bars

change/@fluentui-chart-utilities-34b36b40-164a-4734-b865-63bcf3eb8955.json, packages/charts/chart-utilities/src/PlotlySchemaConverter.ts
The scatter validation was checking for y values instead of x values.
Fixed to check for x values
- Fixes #
=> fix(chart-utilities): Fix scatter validity condition

.github/workflows/pr-vrt-comment.yml, .github/workflows/vrt-baseline.yml
- Using test release of vr-approval-cli
- Use the latest release version which has same code as the testing version
=> [vr-approval-cli] Use latest release

.github/scripts/prepare-vr-screenshots-for-upload.js, .github/workflows/pr-vrt-comment.yml
- unblocks https://github.com/microsoft/fluentui/pull/34072 
- make sure generating images passes if VRT are not affected by PR changes
- run actual VRT tool diffing only if PR contains changes affecting VRT
- Fixes #
=> ci(vrt): ensure rootDir exists if no affected vrt are part of pipeline and run vrt from privileged pipeline only if PR changes affect VRT

.github/workflows/pr-vrt-comment.yml, .github/workflows/pr-vrt.yml, .github/workflows/vrt-baseline.yml
- Triggers on `vrt-gha-testing` branch for VR Approval workflows
- Use triggers on `master` branch
=> [vr-approval] Start triggers on main branch

tools/visual-regression-assert/.eslintrc.json, tools/visual-regression-assert/src/__fixtures__/create_metadata/proj-a/package.json, tools/visual-regression-assert/src/assert.ts, tools/visual-regression-assert/src/cli.ts, tools/visual-regression-assert/src/report.ts, tools/visual-regression-assert/src/shared.ts, tools/visual-regression-assert/src/types.ts, tools/visual-regression-assert/src/update-baseline.ts, tools/visual-regression-assert/src/utils.spec.ts, tools/visual-regression-assert/src/utils.ts
- adds new `update-baseline` command to update local baseline from CI report
- makes `update-baseline` cross platform
- updates report metadata to use only configuration data starting at workspace root to make it cross platform
- Fixes #
=> feat(vra): add update-baseline cmd for updating local baseline from CI report

packages/react-components/react-table/library/src/components/DataGrid/DataGrid.cy.tsx
Updates tests to use `.click()` as the first action. It makes tests more stable and predictable.
Functionality and assertions in tests are not affected.
=> chore: update tests DataGrid.cy.tsx

.github/workflows/bundle-size.yml
addresses https://github.com/microsoft/monosize/issues/103
- Fixes #
=> ci: point bundle-size against default branch

change/@fluentui-react-charts-a45a78e5-e736-49f2-8eca-2c156fc86f34.json, packages/charts/react-charts/library/src/components/CommonComponents/CartesianChart.tsx
Secondary Y Axis margin adjustment in v9
=> fix(react-charts): Secondary Y Axis margin adjustment in v9

change/@fluentui-react-charts-8a665921-3d4a-42df-9b31-f38b6ac02932.json, packages/charts/react-charts/library/src/components/CommonComponents/CartesianChart.tsx, packages/charts/react-charts/library/src/utilities/SVGTooltipText.tsx
Add background to the SVGTooltipText
=> Add background to the SVGTooltipText

change/@fluentui-react-charts-43881eda-0978-488a-9195-6a775953cf3e.json, change/@fluentui-react-charts-56d726bb-e251-44b7-ba4f-a65f6145ac20.json, packages/charts/react-charts/library/src/components/VerticalBarChart/VerticalBarChart.tsx
Removed duplicate key warning in Vertical bar chart.
- Fixes #
=> fix(react-charts): Remove duplicate key warning

packages/web-components/src/menu-button/menu-button.stories.ts
I removed the text from icon-only
- Fixes #
=> docs(web-components)：improve IconOnly example for MenuButton

change/@fluentui-react-charts-df7f5882-3465-485d-8639-b44cc15c9cfd.json, packages/charts/react-charts/library/src/components/DeclarativeChart/DeclarativeChart.tsx, packages/charts/react-charts/library/src/components/DonutChart/Arc/Arc.tsx
Handle invalid plotly data in V9 and fixing id related error in donut chart
=> fix(react-charts): Handle invalid plotly data in V9 and fixing id related error in donut chart

.github/CODEOWNERS
CODEOWNERS file was invalid.
CODEOWNERS file is valid.
=> clean up CODEOWNERS

change/@fluentui-react-charts-1c85af63-1959-4ef3-87f0-1e628b5f8a4c.json, packages/charts/react-charts/library/etc/react-charts.api.md, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charts/library/src/components/DeclarativeChart/__snapshots__/PlotlySchemaAdapterUT.test.tsx.snap, packages/charts/react-charts/library/src/components/VerticalBarChart/VerticalBarChart.tsx, packages/charts/react-charts/library/src/components/VerticalBarChart/VerticalBarChart.types.ts
=> feat(react-charts): center align bars with auto barWidth in plotly mode

change/@fluentui-web-components-ef3e03d0-606a-4ace-949f-0fe084a5a65d.json, packages/web-components/src/avatar/avatar.styles.ts
=> fix: typo in avatar beige color

change/@fluentui-react-charts-af723f14-6638-4c66-9763-62a4dd386ebd.json, packages/charts/react-charts/library/src/components/VerticalBarChart/VerticalBarChart.tsx, packages/charts/react-charts/library/src/components/VerticalBarChart/__snapshots__/VerticalBarChartRTL.test.tsx.snap
=> fix(react-charts): remove duplicate legends + resolve overlapping bars across legends in VBC

change/@fluentui-react-charting-684962cf-650b-47f0-bc31-2b993cbfafed.json, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
work item: https://uifabric.visualstudio.com/iss/_workitems/edit/12680
- Fixes #
=> fix(react-charting): HBC With Axis bars overlapping fix

change/@fluentui-react-charting-6dfd6636-1595-44aa-80bb-4a842adc9991.json, packages/charts/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
Adding fix for Grouped Vertical bar chart error 
Work items: 
1. https://uifabric.visualstudio.com/iss/_workitems/edit/12682
2. https://uifabric.visualstudio.com/iss/_workitems/edit/12681
=> fix(react-charting): Adding fix for Grouped Vertical bar chart error 

change/@fluentui-chart-utilities-69dc0acf-176f-4ca1-aad0-08d614be94f9.json, change/@fluentui-react-charting-ffc61944-47d7-4b57-922f-f14ea8b28cbe.json, change/@fluentui-react-charts-a1121a7e-ec82-4ff5-baec-583f5539256d.json, packages/charts/chart-utilities/src/PlotlySchemaConverter.ts, packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx, packages/charts/react-charts/library/src/components/DeclarativeChart/DeclarativeChart.tsx
=> fix(charts): map stacked plotly scatter traces to area chart

change/@fluentui-react-charting-1d3dbf5f-6294-488d-bd33-a2266021c29c.json, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
=> fix(react-charting): Legends order fix

change/@fluentui-web-components-27b27577-deab-4368-b275-7a9f5c47045f.json, packages/web-components/src/tabs/tabs.ts
https://github.com/user-attachments/assets/92286bf9-b179-45dd-a405-228f878cee83
https://github.com/microsoft/fluentui/issues/34182
=> fix(web-components): fix tas animation starting position

apps/react-18-tests-v9/tsconfig.react-18.json, azure-pipelines.release-vnext-nightly.yml
- build/test/lint all vNext packages during the nightly release
- incorporate that migration packages in the integration tests
=> chore: update pipeline config for vNext nightly release

change/@fluentui-react-charting-8f6b6177-162e-4f37-a831-c5f6134d0c03.json, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx, packages/charts/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap, packages/charts/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChartRTL.test.tsx.snap
=> feat(react-charting): add support for stacked bars in GVBC

packages/web-components/src/dialog/dialog.stories.ts
=> [chore] non-modal story close button gets clipped

apps/react-18-tests-v8/package.json, packages/react/src/components/Announced/Announced.test.tsx, packages/react/src/components/Autofill/Autofill.test.tsx, packages/react/src/components/DetailsList/DetailsHeader.test.tsx, packages/react/src/components/DetailsList/DetailsList.test.tsx, packages/react/src/components/DetailsList/DetailsListV2.test.tsx, packages/react/src/components/Dropdown/Dropdown.test.tsx, packages/react/src/components/ExtendedPicker/BaseExtendedPicker.test.tsx, packages/react/src/components/FloatingPicker/BaseFloatingPicker.test.tsx, packages/react/src/components/GroupedList/GroupedListV2.test.tsx, packages/react/src/components/KeytipLayer/KeytipLayer.test.tsx, packages/react/src/components/MarqueeSelection/MarqueeSelection.test.tsx, packages/react/src/components/MessageBar/MessageBar.test.tsx, packages/react/src/components/OverflowSet/OverflowSet.test.tsx, packages/react/src/components/Panel/Panel.test.tsx, packages/react/src/components/Persona/Persona.deprecated.test.tsx, packages/react/src/components/Persona/Persona.test.tsx, packages/react/src/components/SelectedItemsList/BaseSelectedItemsList.test.tsx, packages/react/src/components/SelectedItemsList/SelectedPeopleList/SelectedPeopleList.test.tsx, packages/react/src/components/Spinner/Spinner.test.tsx, packages/react/src/components/TextField/TextField.test.tsx, packages/react/src/components/pickers/BasePicker.test.tsx, packages/react/src/components/pickers/PeoplePicker/PeoplePicker.test.tsx, packages/react/src/components/pickers/TagPicker/TagPicker.test.tsx, packages/react/src/utilities/selection/SelectionZone.test.tsx
- Follows/Needs https://github.com/microsoft/fluentui/pull/34347
- resolves missing `act()` violations in v8 tests
- before: **12800 lines issue report**  
- after:  **0 lines issue report**
- migrates projects
- react
- react-hooks
**problematic tests**
if `act` is used , they fail with react 17 - blocking current main pipeline
**failing snapshots**
These snapshots differ because `react-test-renderer` breaking changes between r17 and r18 output.
For that reason we are running jest in `updateSnapshots` mode on CI to not get false positives on test pass rate
```
FAIL react-18-tests-v8-integration ../../packages/react/src/components/pickers/BasePicker.test.tsx
FAIL react-18-tests-v8-integration ../../packages/react/src/components/Pivot/Pivot.test.tsx
FAIL react-18-tests-v8-integration …
```
=> test: resolve v8 act() issues with react 18 

packages/foundation-legacy/config/tests.js, packages/react-cards/config/tests.js, packages/react-experiments/config/tests.js, packages/react-focus/config/tests.js, packages/react-hooks/config/tests.js, packages/react-icons-mdl2/config/tests.js, packages/react/config/tests.js, packages/utilities/config/tests.js
Removes enzyme setup from projects that don't use it anymore
- Follows https://github.com/microsoft/fluentui/pull/34316, https://github.com/microsoft/fluentui/pull/34270
=> chore: remove enzyme setup from projects that dont use it anymore

change/@fluentui-web-components-d926ac2a-b697-4d51-be22-e66e76f6296d.json, packages/web-components/src/button/button.styles.ts, packages/web-components/src/toggle-button/toggle-button.styles.ts
=> [fix] focus-visible state for primary selected focus state for toggle button and primary hover button

change/@fluentui-react-charting-4ad531e6-cf9c-45e8-a512-f00b5c9ba483.json, packages/charts/react-charting/UnitTests/__snapshots__/VerticalBarChartUT.test.tsx.snap, packages/charts/react-charting/src/components/DeclarativeChart/__snapshots__/DeclarativeChartRTL.test.tsx.snap, packages/charts/react-charting/src/components/DonutChart/Arc/Arc.styles.ts, packages/charts/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap, packages/charts/react-charting/src/components/GaugeChart/GaugeChart.styles.ts, packages/charts/react-charting/src/components/GaugeChart/__snapshots__/GaugeChart.test.tsx.snap, packages/charts/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.styles.ts, packages/charts/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChartRTL.test.tsx.snap, packages/charts/react-charting/src/components/HeatMapChart/HeatMapChart.base.tsx, packages/charts/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.styles.ts, packages/charts/react-charting/src/components/HorizontalBarChart/__snapshots__/HorizontalBarChart.test.tsx.snap, packages/charts/react-charting/src/components/Sparkline/Sparkline.styles.ts, packages/charts/react-charting/src/components/Sparkline/__snapshots__/Sparkline.test.tsx.snap, packages/charts/react-charting/src/components/Sparkline/__snapshots__/SparklineRTL.test.tsx.snap, packages/charts/react-charting/src/components/StackedBarChart/MultiStackedBarChart.styles.ts, packages/charts/react-charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap, packages/charts/react-charting/src/components/TreeChart/TreeChart.styles.ts, packages/charts/react-charting/src/components/TreeChart/__snapshots__/TreeChart.test.tsx.snap, packages/charts/react-charting/src/components/VerticalBarChart/VerticalBarChart.styles.ts, packages/charts/react-charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChartRTL.test.tsx.snap, packages/charts/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.styles.ts, packages/charts/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChartRTL.test.tsx.snap
=> fix(react-charting): High Contrast fix

change/@fluentui-react-tabster-2a3251a8-c38f-44bd-9111-790b558fcb0a.json, packages/react-components/react-tabster/src/focus/focusVisiblePolyfill.test.ts, packages/react-components/react-tabster/src/focus/focusVisiblePolyfill.ts
=> Apply focus visible attribute on navigation state change

change/@fluentui-react-charting-f13be1b7-b0bb-474a-8e2a-06071302eaa9.json, packages/charts/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx, packages/charts/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChartRTL.test.tsx.snap
=> fix(react-charting): enable interaction with line points without corresponding bars in VSBC

change/@fluentui-react-conformance-e98882e2-48ef-405e-97fe-96a00a4f56fd.json, change/@fluentui-react-conformance-griffel-f6b22bcf-2bf4-4858-93e4-1b50703f54a2.json, packages/react-components/react-conformance-griffel/src/overridesWin.ts, packages/react-conformance/package.json, packages/react-conformance/src/defaultTests.tsx
- conformance packages don't work with react 18
- conformance packages work with react 18
- Follows https://github.com/microsoft/fluentui/pull/34420
=> feat(react-conformance): add react 18 support

docs/react-v9/contributing/rfcs/shared/repo-organization.md
[Read RFC 👓](https://github.com/microsoft/fluentui/pull/34193/files?short_path=6a4cbf7#diff-6a4cbf717bb27705d9cff3bb9356a63e93c984bbf9d6de7ebe24c8cd38979c1b)
- Fixes #
=> docs: new repo organization RFC

azure-pipelines.release.tools.yml, scripts/beachball/src/config.test.ts, scripts/beachball/src/utils.ts
only 1 package was being part of this release pipeline
all packages that contain tag `tools` and are not private will be releases from this pipeline
- Fixes #
=> ci(release): fix tooling release pipeline

change/@fluentui-web-components-d1ff1d4f-0315-4887-bf33-2204ececdfcc.json, packages/web-components/docs/web-components.api.md, packages/web-components/package.json, packages/web-components/src/index.ts
Tree exports were not exported form root index
Tree exports are exported form root index
- Fixes #
=> [chore]: add tree exports to main index

change/@fluentui-chart-utilities-e965d02c-dc0d-4e5d-bc22-714bc32a292e.json, packages/charts/chart-utilities/src/PlotlySchemaConverter.ts
=> Add chart type to error logs

packages/react-components/react-components/.eslintrc.json
- enables https://typescript-eslint.io/rules/no-restricted-imports/ for alpha/beta packages
- temporary workaround untill TS-Eslint ships proper fixes https://github.com/typescript-eslint/typescript-eslint/issues/11197
- Follows https://github.com/microsoft/fluentui/pull/34408
=> style(react-components): add no-restricted-imports to mitigate alpha/beta apis exposure

change/@fluentui-react-charting-cd9da8fe-7318-47a9-add3-eea65620d8f6.json, packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapterUT.test.tsx, packages/charts/react-charting/src/components/DeclarativeChart/__snapshots__/DeclarativeChartRTL.test.tsx.snap, packages/charts/react-charting/src/components/DeclarativeChart/__snapshots__/PlotlySchemaAdapterUT.test.tsx.snap
Use schema colors for other charts
=> fix(react-charting): Use schema colors for other charts

change/@fluentui-react-charting-984133fb-8726-4043-8435-3309141f7f3a.json, packages/charts/react-charting/src/components/LineChart/LineChart.base.tsx
Removed duplicate legends in line chart.
- Fixes #
=> fix(react-charting): Remove duplicate Legends

change/@fluentui-react-charting-d699db65-64c9-4b5f-b9eb-3480e3a42709.json, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charting/src/components/DeclarativeChart/__snapshots__/PlotlySchemaAdapterUT.test.tsx.snap, packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.AxisTooltip.Example.tsx, packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.SecondaryYAxis.Example.tsx
=> fix(react-charting): fix bargap issue

apps/react-18-tests-v9/src/issues.tsx
Adds more problematic use cases with ongoing react 18 support initiative. These need to be addressed before the release
- Fixes #
=> chore(react-18-tests-v9): add more issue examples

change/@fluentui-chart-utilities-29ae4fd3-dfd4-4f7a-8fae-5236c3e57364.json, change/@fluentui-react-charting-1cfc7d5f-ef01-4eee-9d5d-a063e8efc98a.json, packages/charts/chart-utilities/etc/chart-utilities.api.md, packages/charts/chart-utilities/src/PlotlySchema.ts, packages/charts/react-charting/etc/react-charting.api.md, packages/charts/react-charting/src/components/ChartTable/ChartTable.base.tsx, packages/charts/react-charting/src/components/ChartTable/ChartTable.types.ts, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
Now styles coming from plotly schema are supported in chart tables.
- Fixes #
=> feat(declarative-charts): Add styling to tables

change/@fluentui-react-charting-37e01c5a-aaf8-41ad-a8c0-a0f0c7f8fece.json, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charting/src/components/DeclarativeChart/__snapshots__/DeclarativeChartRTL.test.tsx.snap, packages/charts/react-charting/src/components/DeclarativeChart/__snapshots__/PlotlySchemaAdapterUT.test.tsx.snap, packages/charts/react-charting/src/components/DonutChart/DonutChart.base.tsx, packages/charts/react-charting/src/utilities/utilities.ts
=> fix(react-charting): pie chart blank space fix

packages/react-components/react-nav-preview/stories/src/Nav/index.stories.tsx, packages/react-components/react-nav-preview/stories/src/NavDrawer/CustomMotion.stories.tsx
This PR adds a new storybook example on how to customize NavDrawer animations. This is useful to show case how to achieve better animations within application.
=> docs(react-nav): add example on how to customize motion of NavDrawer

change/@fluentui-react-charting-aab66353-eb36-4b1c-8bfa-bc81510c70a9.json, packages/charts/react-charting/src/components/DeclarativeChart/PlotlyColorAdapter.ts
Fixing resolve color issue
Work item: https://uifabric.visualstudio.com/iss/_workitems/edit/12883/
Before:
After:
=> fix(react-charting): Fixing resolve color issue

change/@fluentui-react-charting-d442bcc6-32a1-4a67-875b-996444abc50f.json, packages/charts/react-charting/src/components/DeclarativeChart/PlotlyColorAdapter.ts, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charting/src/components/ScatterChart/ScatterChart.base.tsx
Work item: https://uifabric.visualstudio.com/iss/_workitems/edit/12861
Before:
After:
=> fix(react-charting): Fixing color issue for GVBC

change/@fluentui-react-tree-e1994951-8afe-4559-8b5b-cc8dfdceeb53.json, packages/react-components/react-accordion/library/src/components/AccordionHeader/useAccordionHeaderStyles.styles.ts, packages/react-components/react-tree/library/package.json, packages/react-components/react-tree/library/src/components/FlatTree/useFlatTreeStyles.styles.ts, packages/react-components/react-tree/library/src/components/Tree/useTreeStyles.styles.ts, packages/react-components/react-tree/library/src/components/TreeItem/useTreeItemStyles.styles.ts, packages/react-components/react-tree/library/src/components/TreeItemLayout/useTreeItemLayoutStyles.styles.ts, packages/react-components/react-tree/library/src/components/TreeItemPersonaLayout/useTreeItemPersonaLayoutStyles.styles.ts, packages/semantic-tokens/etc/semantic-tokens.api.md, packages/semantic-tokens/src/components/list/tokens.ts, packages/semantic-tokens/src/control/tokens.ts, packages/semantic-tokens/src/fluentLegacyVariants.ts, packages/semantic-tokens/src/fluentOverrides.ts, packages/semantic-tokens/src/index.ts, packages/semantic-tokens/src/legacy/tokens.ts, packages/semantic-tokens/src/legacyVariant/tokens.ts, packages/semantic-tokens/src/optional/tokens.ts
Upgrades React-Tree to extended tokens
Similar format to Accordion
Does not replace transparent or subtle w/ alpha tokens (no equivalent in semantic).
=> React-Tree: Upgrade to extended tokens

change/@fluentui-react-positioning-6076d8d4-b470-4064-b0d8-6d33d36d7a3b.json, packages/react-components/react-positioning/library/src/hooks/useSafeZoneArea/useSafeZoneArea.cy.tsx, packages/react-components/react-positioning/library/src/hooks/useSafeZoneArea/useSafeZoneArea.tsx
rAF in `useSafeZoneArea()` runs till:
- a cursor is moved to a container
- a cursor stays for `timeout` over a safe zone
rAF in `useSafeZoneArea()` runs till:
- a cursor is moved to a container
- a cursor stays for `timeout` over a safe zone
- a cursor stays for timeout over a targer
=> fix(useSafeZoneArea): stop rAF if no mouse movement happening

apps/chart-docsite/src/Introduction.mdx
Update current status of v9 charts
- Fixes #
=> docs(react-charts): Update current status for v9 charts

change/@fluentui-react-portal-72ebd77a-dbaa-4ff9-8792-58a6b8526378.json, packages/react-components/react-portal/library/package.json, packages/react-components/react-portal/library/src/components/Portal/usePortal.ts, packages/react-components/react-portal/library/src/components/Portal/usePortalMountNode.test.tsx, packages/react-components/react-portal/library/src/components/Portal/usePortalMountNode.ts, yarn.lock
Reverts microsoft/fluentui#33978
---
Fixes #34732
Re-opens #31429
See https://github.com/microsoft/fluentui/issues/34732#issuecomment-3008800341
=> Revert "chore(react-portal): support for React 19"

apps/public-docsite-v9/src/Concepts/PackageMaturityLevels.stories.mdx
Adds official docs to mitigate confusion in user land in terms of v9 packages versioning
- Fixes #
=> docs(docsite-v9): add package maturity levels docs

change/@fluentui-react-charts-48d6eb93-79c7-45bb-9717-b48939da8ee0.json, packages/charts/react-charts/library/src/components/DonutChart/Arc/Arc.tsx, packages/charts/react-charts/library/src/components/DonutChart/Arc/Arc.types.ts, packages/charts/react-charts/library/src/components/DonutChart/Arc/useArcStyles.styles.ts, packages/charts/react-charts/library/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap, packages/charts/react-charts/library/src/components/HorizontalBarChart/HorizontalBarChart.tsx, packages/charts/react-charts/library/src/components/HorizontalBarChart/__snapshots__/HorizontalBarChart.test.tsx.snap, packages/charts/react-charts/library/src/components/VerticalBarChart/VerticalBarChart.tsx, packages/charts/react-charts/library/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap, packages/charts/react-charts/library/src/components/VerticalStackedBarChart/VerticalStackedBarChart.tsx, packages/charts/react-charts/library/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChart.test.tsx.snap
Accessibility bugs fixed in v9 charts.
- Fixes #
=> fix(react-charts): Fix accessibility bugs

apps/react-17-tests-v9/project.json, apps/react-18-tests-v8/project.json, apps/react-18-tests-v9/project.json, apps/react-19-tests-v9/.swcrc, apps/react-19-tests-v9/jest-react-19.config.js, apps/react-19-tests-v9/jest.config.js, apps/react-19-tests-v9/package.json, apps/react-19-tests-v9/project.json
- adds jest setup for r19 integration tests app
- fixes remaining invalid globs in project.json inputs 
- Implements partially https://github.com/microsoft/fluentui/issues/34768
=> test(react-19-tests-v9): add test:integration setup

package.json
- see PR title
- this was kept for transition period from lage to nx for 6+months - removing 
- Fixes #
=> chore: remove deprecated npm script aliases from repo root

change/@fluentui-react-charting-b55f1a04-8733-411b-bc73-13cac2043e1f.json, packages/charts/react-charting/src/components/LineChart/LineChart.base.tsx, packages/charts/react-charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
Fixes hover card not showing y value for large data case.
- Fixes #
=> fix(react-charting): Fix hover card not coming properly for large data flow

packages/react-components/semantic-style-hooks-preview/library/etc/semantic-style-hooks-preview.api.md, packages/react-components/semantic-style-hooks-preview/library/package.json, packages/react-components/semantic-style-hooks-preview/library/src/component-styles/Persona/index.ts, packages/react-components/semantic-style-hooks-preview/library/src/component-styles/Persona/useSemanticPersonaStyles.styles.ts, packages/react-components/semantic-style-hooks-preview/library/src/component-styles/semanticStyleHooks.ts, packages/react-components/semantic-style-hooks-preview/library/src/index.ts
Add react-persona to semantic style hooks preview, convert to semantic tokens
=> add persona to semantic style hooks

change/@fluentui-react-charting-57363c4e-c2b1-4673-acee-2c1431e18c58.json, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charting/src/components/DeclarativeChart/__snapshots__/PlotlySchemaAdapterUT.test.tsx.snap, packages/charts/react-charting/src/components/LineChart/LineChart.base.tsx, packages/charts/react-charting/src/components/ScatterChart/ScatterChart.base.tsx, packages/charts/react-charting/src/utilities/scatterpolar-utils.tsx
Work item: https://uifabric.visualstudio.com/iss/_workitems/edit/13375
=> fix(react-charting): Align labels and points according to given directions and rotation in schema for scatter polar

change/@fluentui-chart-utilities-0796e2e1-6ce2-45bd-80cf-142cc11cdbf1.json, change/@fluentui-react-charting-c47c9a2c-5e3d-4a27-9012-78bbc1828485.json, packages/charts/chart-utilities/src/PlotlySchemaConverter.ts, packages/charts/react-charting/etc/react-charting.api.md, packages/charts/react-charting/src/components/CommonComponents/CartesianChart.base.tsx, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charting/src/components/GanttChart/GanttChart.base.tsx, packages/charts/react-charting/src/components/GanttChart/GanttChart.test.tsx, packages/charts/react-charting/src/components/GanttChart/GanttChart.types.ts, packages/charts/react-charting/src/components/GanttChart/__snapshots__/GanttChart.test.tsx.snap, packages/charts/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChartRTL.test.tsx.snap, packages/charts/react-charting/src/components/HorizontalBarChartWithAxis/__snapshots__/HorizontalBarChartWithAxisRTL.test.tsx.snap, packages/charts/react-charting/src/types/IDataPoint.ts
=> fix(charts): resolve minor Gantt chart bugs and optimize logic

change/@fluentui-chart-utilities-0b666c03-8128-4257-af5b-a21874fa7516.json, change/@fluentui-react-charting-778d7a01-11c7-4b7d-abaa-bd2ed5a21ad5.json, packages/charts/chart-utilities/etc/chart-utilities.api.md, packages/charts/chart-utilities/src/PlotlySchema.ts, packages/charts/chart-utilities/src/PlotlySchemaConverter.UT.test.ts, packages/charts/chart-utilities/src/PlotlySchemaConverter.ts, packages/charts/react-charting/etc/react-charting.api.md, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charting/src/components/ScatterChart/ScatterChart.base.tsx, packages/charts/react-charting/src/types/IDataPoint.ts, packages/charts/react-charting/src/utilities/utilities.ts
Work item https://uifabric.visualstudio.com/iss/_workitems/edit/13360/
=> feat(react-charting): Support additional modes

change/@fluentui-react-charts-1916b4bc-e595-453f-8bec-2fc3275a3c80.json, packages/charts/react-charts/library/src/components/AreaChart/AreaChart.tsx, packages/charts/react-charts/library/src/components/DonutChart/Arc/Arc.tsx, packages/charts/react-charts/library/src/components/DonutChart/DonutChart.tsx, packages/charts/react-charts/library/src/components/DonutChart/Pie/Pie.tsx, packages/charts/react-charts/library/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.tsx, packages/charts/react-charts/library/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap, packages/charts/react-charts/library/src/components/HorizontalBarChartWithAxis/HorizontalBarChartWithAxis.tsx, packages/charts/react-charts/library/src/components/LineChart/LineChart.tsx, packages/charts/react-charts/library/src/components/ScatterChart/ScatterChart.tsx, packages/charts/react-charts/library/src/components/VerticalBarChart/VerticalBarChart.tsx
Fixed position of callout on hovering and tab focus in different charts in v9.
- Fixes #
=> fix(react-charts): fix callout position issues

CredScanSuppressions.json, azure-pipelines.release.yml
v8 releases are constantly failing as security tools fails on invalid paths scan
v8 release work as expected
- Fixes #
=> ci: remove v0 artifacts from v8 production pipelines

change/@fluentui-react-charting-9362a2aa-07ae-4dc3-aa25-24405a6d8846.json, packages/charts/react-charting/src/components/ChartTable/ChartTable.base.tsx, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
=> fix(react-charting): change foreground color based on contrast ratio in chart table

change/@fluentui-react-charting-42e4c405-90ec-4b7d-8007-5a2a5896368b.json, packages/charts/react-charting/src/components/FunnelChart/FunnelChart.base.tsx, packages/charts/react-charting/src/components/FunnelChart/funnelGeometry.ts
Handled focus handling in Funnel chart and rectified orientation.
- Fixes #
=> fix(react-charting): focus handling in funnel chart

change/@fluentui-react-charting-55ffdf08-dd86-46ce-b553-cccc21611950.json, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
Alignment fixed for declarative funnel chart
- Fixes #
=> fix(declarative-charts): fix alignment of funnel chart

change/@fluentui-react-charting-e6904a07-aefc-4748-9863-0e5aa9a51dd9.json, packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charting/src/components/LineChart/LineChart.base.tsx, packages/charts/react-charting/src/components/ScatterChart/ScatterChart.base.tsx, packages/charts/react-charting/src/utilities/scatterpolar-utils.tsx
Without text mode:
With text mode:
=> fix(react-charting): Fixed text mode for scatter polar

change/@fluentui-chart-utilities-a546c386-b8c3-45c7-9700-713d16b74556.json, packages/charts/chart-utilities/src/PlotlySchemaConverter.ts
Routing scattergl charts to scatter charts
=> feat(react-charting): Routing scattergl charts to scatter charts

change/@fluentui-react-charts-757dbe9e-fb39-415c-ad5a-7fff63bbe1d2.json, packages/charts/react-charts/library/src/components/DeclarativeChart/DeclarativeChart.tsx, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
Corresponding v8 PR: https://github.com/microsoft/fluentui/pull/34278
- Fixes #
=> feat(react-charts): Add support for scatter polar trace type

packages/react-components/react-menu-grid-preview/stories/src/MenuGrid/MenuGridDefault.stories.tsx, packages/react-components/react-menu-grid-preview/stories/src/MenuGrid/MenuGridDescription.md, packages/react-components/react-menu-grid-preview/stories/src/MenuGrid/MenuGridGroupingItems.stories.tsx, packages/react-components/react-menu-grid-preview/stories/src/MenuGrid/index.stories.tsx
This PR adds the Grouping Items story for the MenuGrid component and modifies the Default story to remove row groups and headers there.
=> Feature(react-menu-grid-preview): Add grouping items story

change/@fluentui-react-charts-fce26034-5dec-4529-abf2-96d15dc04175.json, packages/charts/react-charts/library/src/components/VerticalStackedBarChart/VerticalStackedBarChart.tsx, packages/charts/react-charts/library/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChart.test.tsx.snap
Corresponding v8 PR: https://github.com/microsoft/fluentui/pull/34398
- Fixes #
=> fix(react-charts): enable interaction with line points without corresponding bars in VSBC

.gitignore, .vscode/mcp.json, .vscode/settings.json
Enables automatic nx mcp server enablement + autogenerated nx.instructions.md for copilot
**new tools addition**
**auto-generated instruction set** 
> always up to date with installed nx version
- Fixes #
=> chore: enable nx ai agent rules

change/@fluentui-react-charts-03eb6908-52e6-48ed-bdda-87bea799bc4f.json, packages/charts/react-charts/library/etc/react-charts.api.md, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charts/library/src/components/DeclarativeChart/__snapshots__/PlotlySchemaAdapterUT.test.tsx.snap, packages/charts/react-charts/library/src/components/DonutChart/DonutChart.types.ts
Corresponding v8 PR: https://github.com/microsoft/fluentui/pull/34473
- Fixes #
=> fix(react-charts): enable round corners in declarative charts

change/@fluentui-react-charts-0df7d702-85f0-45b8-8593-98e8b688e24a.json, packages/charts/react-charts/library/etc/react-charts.api.md, packages/charts/react-charts/library/src/components/DeclarativeChart/DeclarativeChart.tsx, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlyColorAdapter.ts, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapterUT.test.tsx, packages/charts/react-charts/library/src/components/DeclarativeChart/__snapshots__/PlotlySchemaAdapterUT.test.tsx.snap, packages/charts/react-charts/stories/src/DeclarativeChart/DeclarativeChartDefault.stories.tsx
Corresponding v8 PR: https://github.com/microsoft/fluentui/pull/34471
- Fixes #
=> feat(react-charts): Create plotly aligned colorway

change/@fluentui-react-charts-48e759ca-7499-453b-b620-1850364cdaf6.json, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charts/stories/src/HorizontalBarChartWithAxis/HorizontalBarChartWithAxisNegative.stories.tsx, packages/charts/react-charts/stories/src/HorizontalBarChartWithAxis/index.stories.tsx
1. Added HBCWith Axis negative x-axis story
2. Ported this PR: https://github.com/microsoft/fluentui/pull/34516
- Fixes #
=> feat(react-charts): Add Horizontalbarchart negative x-axis story

docs/react-v9/contributing/rfcs/shared/types-contract.md
- [Read in preview mode](https://github.com/microsoft/fluentui/pull/34762/files?short_path=f5a7e06#diff-f5a7e064989223d85fbdf8dcfc74992c52fc92dfcfb4f33b4be017e8a29d9748)
- Fixes #
=> docs(rfc): establish official FluentUI TypeScript type contract

change/@fluentui-react-charts-939f4613-36b6-48da-9418-bf7d22bf9e50.json, packages/charts/react-charts/library/src/components/ChartTable/ChartTable.tsx, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
V8 PR: https://github.com/microsoft/fluentui/pull/34560
- Fixes #
=> feat(react-charts): Add styling to tables

change/@fluentui-react-charts-69387f55-7819-4d64-bf5c-bae754fab7c2.json, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlyColorAdapter.ts, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charts/library/src/components/DeclarativeChart/__snapshots__/PlotlySchemaAdapterUT.test.tsx.snap
v8 PR: https://github.com/microsoft/fluentui/pull/34635
- Fixes #
=> feat(react-charts): support for using opacity provided in plotly schema

apps/public-docsite-v9/package.json, change/@fluentui-react-menu-grid-preview-5758ab83-6124-4e50-baf0-650ed2aaacac.json, packages/react-components/react-menu-grid-preview/library/package.json
This PR makes MenuGrid stories publicly available.
=> Feat(react-menu-grid-preview): Publish MenuGrid stories

packages/react-components/react-menu-grid-preview/stories/src/MenuGrid/MenuGridBestPractices.md, packages/react-components/react-menu-grid-preview/stories/src/MenuGrid/index.stories.tsx
This PR adds the "Best practices" section for the MenuGrid component storybook page.
=> Feat(react-menu-grid-preview): Add best practices to MenuGrid storybook

change/@fluentui-react-charts-4005037c-e67a-47ec-b25b-e8f83032be4a.json, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlyColorAdapter.ts, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charts/library/src/components/ScatterChart/ScatterChart.tsx
v8 PR: https://github.com/microsoft/fluentui/pull/34809
- Fixes #
=> fix(react-charts): reduce component size by removing duplicate code

.github/instructions/copilot.instructions.md, .vscode/mcp.json, .vscode/settings.json
Currently AI Agents struggle to figure out Fluent repo as a whole, specially when it comes to patterns, dependencies, testing and so on.
Adding instruction files helps to give context to the agents on where to find information and also about the importance of our patterns.
=> fix: improve AI agents with instructions and remove unnecessary NX MCP config

change/@fluentui-react-motion-components-preview-b00c98db-15e4-4c49-b65b-c6f527be32d7.json, packages/react-components/react-motion-components-preview/library/src/atoms/fade-atom.test.ts, packages/react-components/react-motion-components-preview/library/src/atoms/scale-atom.test.ts, packages/react-components/react-motion-components-preview/library/src/atoms/slide-atom.test.ts, packages/react-components/react-motion-components-preview/library/src/components/Scale/Scale.ts, packages/react-components/react-motion-components-preview/library/src/testing/README.md, packages/react-components/react-motion-components-preview/library/src/testing/atomTestUtils.ts, packages/react-components/react-motion-components-preview/library/src/testing/index.ts
Improves testing infrastructure for Fluent UI motion components. 
This is PR 4 of 4 in this series:
- #35076 (BaseAtomParams extraction)
- #35077 (delay support integration)  
- #35078 (opacity flickering fix)
- Added tests for scale and slide atoms 
- Added reusable testing utilities
- Now 5 of the 6 types of motion atoms are covered: fade, slide, scale, blur, rotate
- Future work: collapse atoms tests
=> test(motion): expand motion atom testing

change/@fluentui-react-charts-47962710-e13e-4bb8-bdb4-6366cc2bd138.json, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapterUT.test.tsx
v8 PR: https://github.com/microsoft/fluentui/pull/34963
- Fixes #
=> fix(react-charts): handling y object values for bar chart

change/@fluentui-react-charts-a5532530-8f6e-485d-b3a0-8193adc92df5.json, packages/charts/react-charts/library/etc/react-charts.api.md, packages/charts/react-charts/library/src/components/CommonComponents/CartesianChart.tsx, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charts/library/src/components/DeclarativeChart/__snapshots__/PlotlySchemaAdapterUT.test.tsx.snap, packages/charts/react-charts/library/src/components/ScatterChart/ScatterChart.tsx, packages/charts/react-charts/library/src/components/ScatterChart/ScatterChart.types.ts
v8 PR: https://github.com/microsoft/fluentui/pull/35006
- Fixes #
=> feat(react-charts): support string y axis in scatter chart

change/@fluentui-react-charts-00310f28-f856-48b5-926c-5c4f192e0d8b.json, packages/charts/react-charts/library/etc/react-charts.api.md, packages/charts/react-charts/library/src/components/CommonComponents/CartesianChart.tsx, packages/charts/react-charts/library/src/components/CommonComponents/CartesianChart.types.ts, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charts/library/src/types/DataPoint.ts, packages/charts/react-charts/library/src/utilities/UtilityUnitTests.test.ts, packages/charts/react-charts/library/src/utilities/utilities.ts
v8 PR: https://github.com/microsoft/fluentui/pull/35039
- Fixes #
=> feat(react-charts): add support for tickmode in declarative chart

change/@fluentui-react-charts-55f20992-9563-4a92-97b5-143b5b2bb48b.json, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charts/library/src/components/DeclarativeChart/__snapshots__/PlotlySchemaAdapterUT.test.tsx.snap
v8 PR: https://github.com/microsoft/fluentui/pull/35054
- Fixes #
=> fix(react-charts): update segment color in donut chart

change/@fluentui-react-charts-6c7aecd5-fda9-45df-8155-bacac426dc4e.json, packages/charts/react-charts/library/src/components/DonutChart/Arc/useArcStyles.styles.ts, packages/charts/react-charts/library/src/components/FunnelChart/FunnelChart.tsx, packages/charts/react-charts/library/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.tsx, packages/charts/react-charts/library/src/components/HorizontalBarChart/useHorizontalBarChartStyles.styles.ts, packages/charts/react-charts/library/src/utilities/utilities.ts, packages/charts/react-charts/stories/src/VerticalStackedBarChart/VerticalStackedBarChartDateAxis.stories.tsx
=> fix(react-charts): fix v9 charts bugs

change/@fluentui-react-charts-5f921c4a-a34f-4611-94b6-8fb14db69da7.json, packages/charts/react-charts/library/etc/react-charts.api.md, packages/charts/react-charts/library/src/components/DeclarativeChart/DeclarativeChart.tsx, packages/charts/react-charts/stories/src/DeclarativeChart/DeclarativeChartDefault.stories.tsx
Fixes React 19 type issues against public API
> NOTE: infra is not yet in master
But passing type-check pipeline for react 19 is here: 
https://github.com/microsoft/fluentui/actions/runs/17458005433/job/49580265983?pr=35022
- Implements partially https://github.com/microsoft/fluentui/issues/34768
=> fix(charts): make TS public apis compliant with react 19 types

change/@fluentui-react-utilities-cf308593-ccf3-4d5b-a102-2c5f6baae242.json, packages/react-components/react-utilities/project.json
prebuild  has cached only terminal output which has no perf benefits
prebuild is properly cached including generated output 
- Fixes #
=> chore(react-utilities): properly configure prebuild target nx cache

scripts/cypress/src/base.config.ts
> NOTE: Exploited during React Integration Tester (RIT) CLI implementation
Enables running cypress tests in parallel.
- this will be enabled/leveraged for RIT cli. 
- I tested it with current `e2e` job but it was constantly failing on 3 projects ( flaky tests - needs further investigation )
- Fixes #
=> feat(scripts-cypress): make sure webpack dev server port is unique to enable parallel execution

change/@fluentui-react-charting-a0fa82be-a954-4f1c-815a-974b6ae85527.json, change/@fluentui-react-charts-8d6a48fa-5261-4411-83cf-5e588852d212.json, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts, packages/charts/react-charts/library/src/components/ChartTable/ChartTable.tsx, packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
=> fix(charts): fixed styling in chart table

change/@fluentui-react-charts-42e40d6c-06a4-471c-902f-18a50d48d7f8.json, packages/charts/react-charts/library/src/components/AreaChart/AreaChart.tsx, packages/charts/react-charts/library/src/components/DonutChart/Arc/Arc.tsx, packages/charts/react-charts/library/src/components/DonutChart/Arc/Arc.types.ts, packages/charts/react-charts/library/src/components/DonutChart/DonutChart.tsx, packages/charts/react-charts/library/src/components/DonutChart/Pie/Pie.types.ts, packages/charts/react-charts/library/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap, packages/charts/react-charts/library/src/components/LineChart/LineChart.tsx, packages/charts/react-charts/library/src/components/ScatterChart/ScatterChart.tsx, packages/charts/react-charts/library/src/components/VerticalStackedBarChart/VerticalStackedBarChart.tsx
Fixed work items:
1. https://uifabric.visualstudio.com/iss/_workitems/edit/13466
2. https://uifabric.visualstudio.com/iss/_workitems/edit/13474
3. https://uifabric.visualstudio.com/iss/_workitems/edit/13467
- Fixes #
=> fix(react-charts): fix date format and multi selection of legends in donut chart

change/@fluentui-react-charts-29898e47-c08a-4b60-94f6-eb13eb19bf3b.json, packages/charts/react-charts/library/src/components/CommonComponents/CartesianChart.tsx, packages/charts/react-charts/library/src/utilities/utilities.ts
=> fix(react-charts): fix x-axis and y-axis tick bugs in v9 charts

packages/charts/react-charts/stories/src/SankeyChart/SankeyChartInbox.stories.tsx, packages/charts/react-charts/stories/src/SankeyChart/SankeyChartRebalance.stories.tsx
Added id property to sankey chart Inbox and rebalnce examples in v9
=> Added id property to sankey chart Inbox and rebalnce examples in v9

packages/fluentui/docs/package.json, packages/fluentui/docs/src/components/ComponentDoc/ComponentDoc.tsx, packages/fluentui/docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx, packages/fluentui/docs/src/components/DocsLayout.tsx, packages/fluentui/docs/src/components/DocsRoot.tsx, packages/fluentui/docs/src/components/ExternalExampleLayout.tsx, packages/fluentui/docs/src/components/Fader.tsx, packages/fluentui/docs/src/components/Sidebar/Sidebar.tsx, packages/fluentui/docs/src/routes.tsx, packages/fluentui/e2e/package.json, packages/fluentui/e2e/server/E2EExample.tsx, packages/fluentui/e2e/server/app.tsx, yarn.lock
Update to v6 to get it running on React 18 with Concurrent & Strict Mode.
Followed migration guide: https://reactrouter.com/6.30.1/upgrading/v5
=> chore(v0): bump react-router-dom in docs

change/@fluentui-chart-utilities-980d4981-02e5-4b0c-a7a9-ed95d4a0c396.json, change/@fluentui-react-charting-a69b1a9b-b987-4729-b3bc-4019df10e3f7.json, packages/charts/chart-utilities/src/PlotlySchemaConverter.ts, packages/charts/react-charting/src/components/ChartTable/ChartTable.styles.ts, packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
Added support for line shape coming from layout field in plotly schema.
- Fixes #
=> feat(react-charting): support line shape in line chart and VBC

packages/fluentui/react-northstar/src/components/Slider/Slider.tsx
Follow up for #35251. Fixes broken uncontrolled mode.
=> fix(v0): fix state handling in Slider
