- change/@fluentui-react-toolbar-8d721bbd-1df9-4f48-a11d-397f5e5f1f7c.json
- packages/react-components/react-toolbar/etc/react-toolbar.api.md
- packages/react-components/react-toolbar/src/components/Toolbar/Toolbar.types.ts
- packages/react-components/react-toolbar/src/components/Toolbar/ToolbarContext.ts
- packages/react-components/react-toolbar/src/components/Toolbar/useToolbarContextValues.tsx
- packages/react-components/react-toolbar/src/components/ToolbarButton/ToolbarButton.tsx
- packages/react-components/react-toolbar/src/components/ToolbarDivider/useToolbarDivider.ts
- packages/react-components/react-toolbar/src/components/ToolbarRadio/ToolbarRadio.tsx
- packages/react-components/react-toolbar/src/components/ToolbarToggleButton/ToolbarToggleButton.test.tsx
- packages/react-components/react-toolbar/src/components/ToolbarToggleButton/ToolbarToggleButton.types.ts
- packages/react-components/react-toolbar/src/components/ToolbarToggleButton/__snapshots__/ToolbarToggleButton.test.tsx.snap
- packages/react-components/react-toolbar/src/components/ToolbarToggleButton/useToolbarToggleButton.ts
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarControlledToggleButton.stories.tsx
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarDefault.stories.tsx
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarSmall.stories.tsx
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarSubtle.stories.tsx
There are currently two different toolbar context hooks:
- `useToolbarContext` - cruft hook that still exists and is being used
- `useToolbarContext_unstable` - This is the correct hook to use
This caused the toolbar selection scenarios to break because the wrong context hook was always being used.
This PR fixes the usage of context hooks and assorted typings for `ToolbarToggleButton` which were also incorrect
> fix: Toolbar context usage

- change/@fluentui-react-experiments-ddb5ba78-3b3b-4ba6-b97a-30dd9413b998.json
- stub-packages/react-experiments/config/pre-copy.json
The experiments stub package was not aliasing the Signals styles that are expose in 8.0 exports. Since the stub package only has JS exports, the compiled SCSS files needed to be copied over to access them properly.
> 7.0 - Add Signal.scss to react-experiments pre-copy

- rfcs/react-components/convergence/triggers-and-multiple-layers-of-button-handling.md
On the case of a custom component being as a trigger child, it's impossible for `useARIAButtonProps` (which is used internally) to find out if the returned element will be an actual button or not.
```html
<Trigger>
<Button>Trigger something</Button>
</Trigger>
```
That way, even for `Button`, `useARIAButtonProps` will end up providing a bunch of unnecessary props.
```html
<button onclick="fn" onkeydown="fn" onkeyup="fn" role="button" tabindex="0">Trigger something</button>
```
> RFC: Triggers and multiple layers of button handling

- change/@fluentui-react-ec99cae8-1b1d-491a-967b-e7f051ee1c72.json
- packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx
Looking deeper into focus functionality in the Contextualmenu, I realized that the original non queued approach was actually correct (each nested menu was its own contextual menu with its own context). The problem ended up being "last focused elements" either being switch to a child element (when focus returns TO a menu), or to the body (when the old menu closes). Filtering out those two cases allows the behavior to work as expected in 3+ menu depths, as well as custom UI like a textfield
> Fix: Contextual menu focus with custom UI

- change/@fluentui-react-progress-d07f157a-df1e-4b91-a34d-484fc1e640ad.json
- packages/react-components/react-progress/src/components/Progress/Progress.test.tsx
- packages/react-components/react-progress/src/components/Progress/useProgress.tsx
Progress uses a falsy test to see if it should add aria-valuemin and aria-valuemax. That results in those props not being set when the value is 0.
Change the falsy test to an `!== undefined` test.
> fix: Progress should set aria-valuemin and aria-valuemax when the value is 0

- change/@fluentui-react-dialog-1fe6ad25-f33a-4650-a51b-837a5bed695e.json
- packages/react-components/react-dialog/e2e/Dialog.e2e.tsx
- packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurface.ts
- packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurfaceStyles.ts
- packages/react-components/react-dialog/src/stories/Dialog/DialogNoFocusableElement.stories.tsx
- packages/react-components/react-dialog/src/utils/useFocusFirstElement.ts
Without the alternative of focusing on dialog surface on the case of no focusable element some screen readers are failing. As reported multiple times also, there's the case of not being able to escape from a non-modal dialog without a focusable element.
1. adds `tabIndex={-1}` to `DialogSurface`
2. focus on surface in the case of no focusable element available on dialog opening (instead of focusing on body)
3. adds default focus outline style to `DialogSurface`
4. updates no focusable element stories.
Fixes #25150
> feat: focus on surface if no focusable element is available

- change/@fluentui-react-dialog-492b7510-f518-4c17-a929-c500874ec6fc.json
- change/@fluentui-react-menu-2a082257-9573-43fe-99e1-a4ce48003c46.json
- change/@fluentui-react-popover-2a257879-7e46-4b0d-82f2-9dd83e7fcd36.json
- packages/react-components/react-dialog/etc/react-dialog.api.md
- packages/react-components/react-dialog/src/components/DialogTitle/useDialogTitle.tsx
- packages/react-components/react-dialog/src/components/DialogTrigger/DialogTrigger.test.tsx
- packages/react-components/react-dialog/src/components/DialogTrigger/DialogTrigger.types.ts
- packages/react-components/react-dialog/src/components/DialogTrigger/__snapshots__/DialogTrigger.test.tsx.snap
- packages/react-components/react-dialog/src/components/DialogTrigger/useDialogTrigger.ts
- packages/react-components/react-menu/etc/react-menu.api.md
- packages/react-components/react-menu/src/components/Menu/Menu.test.tsx
- packages/react-components/react-menu/src/components/MenuTrigger/MenuTrigger.test.tsx
- packages/react-components/react-menu/src/components/MenuTrigger/MenuTrigger.types.ts
- packages/react-components/react-menu/src/components/MenuTrigger/useMenuTrigger.ts
- packages/react-components/react-popover/etc/react-popover.api.md
- packages/react-components/react-popover/src/components/PopoverTrigger/PopoverTrigger.test.tsx
- packages/react-components/react-popover/src/components/PopoverTrigger/PopoverTrigger.types.ts
- packages/react-components/react-popover/src/components/PopoverTrigger/usePopoverTrigger.ts
Follow up on https://github.com/microsoft/fluentui/pull/24960
Implementing the `disableButtonEnhancement` property that will ensure triggers can opt out of the current behavior where child is enhanced with button-like handlers and properties
> feat: adds disableButtonEnhancement property on triggers

- change/@fluentui-react-dialog-7ebb283d-0dc2-4be2-8c48-931991ff1c06.json
- packages/react-components/react-dialog/package.json
1. add `prerelease` as disallowed change type for `react-dialog` as it was released.
2. fix `react-dialog` version
> chore(react-dialog): updates disallowed change types

- change/@fluentui-react-0f3db7f0-d444-4e3b-8082-84b9ad15e83d.json
- packages/react/README.md
Fluent v8 README states what we fully support IE11.
[IE11 has been sunset by Microsoft](https://github.com/microsoft/fluentui/wiki/Internet-Explorer-11-Sunset) and is no longer officially supported in v8 going forward (though we are not going out of our way to remove any existing support for IE).
> update browser support in fluent v8 readme

- change/@fluentui-react-dialog-973c2806-aef3-42cf-9149-111dc824187c.json
Seems #24972 snuck a bad change file into master. Dialog went from prerelease to release but did not trigger a build which would see that the type value is invalid. Now other PRs are failing.
> Update changefile for Dialog now that it is released

- change/@fluentui-react-3c5ba995-43db-46ee-80af-32fb80ce4e13.json
- packages/react/src/components/Panel/Panel.base.tsx
fixes #25218
enableAriaHiddenSiblings defaults to true, so `enableAriaHiddenSiblings={isOpen ? true : undefined}` was not turning the setting off when isOpen was false.
> Fix: Panel does not aria-hide siblings when only hidden

- packages/react-components/react-alert/stories/Alert/AlertAvatar.stories.tsx
- CI pipeline throws an error because of incorrect relative path import of a story after package move. Not caught in PR check because `type-check` on the package is not executed in that pipeline.
Error: https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=270486&view=logs&jobId=258ec178-2d8b-5611-7b9b-60c5c95dae55&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=8250ef03-1890-59ab-a6a8-5d0b4c2baa1b
- Use absolute path import
> fix(react-alert): fix incorrect relative path import and use absolute import for story

- scripts/exec-sync.js
- scripts/exec.js
When using Windows Powershell to run a script that depends on `execSync()` or `exec()` the script may fail because the `PATH` environment variable is not set. This is a case-sensitivity issue as the default name for the "path" variable is `Path` in Powershell (This can be verified by running `dir env:` in Powershell to see the list of all env vars on your system.)
[Powershell itself is generally case-insensitive](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_case-sensitivity?view=powershell-7.2) and this behavior can be observed on the PS command line:
Node also accesses env vars case-insensitively, _when you access the env vars from `process.env`_. However, Node is case-sensitive when access env vars that have been spread into an object: …
> improve windows support in execSync and exec scripts

- apps/vr-tests-react-components/src/stories/Button.stories.tsx
- change/@fluentui-react-button-9d40ec0c-0f48-4396-ae0c-330db4a060b9.json
- packages/react-components/react-button/src/components/Button/useButtonStyles.ts
`Buttons` had some different styles when rendered as `anchor` tags than when rendered as `button` tags:
`Buttons` now have the same styles whether they're rendered as `anchor` tags or `button` tags:
This PR also adds a vr test to catch this kind of inconsistencies in the future.
Fixes #23849
> fix: Fixing the styles of Buttons rendered as anchor tags

- change/@fluentui-react-charting-beea75ce-fc3b-4589-8902-28d31ef030fa.json
- packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx
- packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.styles.ts
- packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.types.ts
- packages/react-charting/src/components/HorizontalBarChart/__snapshots__/HorizontalBarChart.test.tsx.snap
- packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
- packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.styles.ts
- packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.types.ts
- packages/react-charting/src/components/StackedBarChart/StackedBarChart.base.tsx
- packages/react-charting/src/components/StackedBarChart/StackedBarChart.styles.ts
- packages/react-charting/src/components/StackedBarChart/StackedBarChart.types.ts
- packages/react-charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap
- packages/react-charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap
Chart title overflows when it is lengthy or zoomed
Chart title gets truncated with ellipsis if there is not enough space for it to be completely displayed
> Fix chart title overflow

- apps/stress-test/src/shared/react/TestMount.tsx
- lage.config.js
- package.json
- packages/react-components/react-overflow/src/useOverflowContainer.test.ts
- packages/react-migration-v8-v9/src/stories/Stack/index.stories.tsx
- packages/react-migration-v8-v9/src/stories/ThemeShim/createBrandVariants/index.stories.tsx
- scripts/exec-sync.js
- scripts/exec.js
- scripts/lint-staged/tsconfig.json
- scripts/tasks/storybook.ts
- yarn.lock
- Right now, whenever `lage type-check` is ran, only the `react-18-tests-v8` package's `type-check` executes so other packages are not getting proper type checking in local builds or CI. It seems we need to explicitly declare a `type-check` for all packages in the `lage.config` before having one scoped to just a single package to ensure proper type-checking for all packages.
- Re-enables type-check of packages in the repo
- Fixes type-check errors that were introduced to master
Fixes #25245
> fix(CI): include type-check in lage config to have all packages type checked again

- change/@fluentui-react-toolbar-646c7c94-50c8-4258-a8a9-351b877b0cd4.json
- packages/react-components/react-toolbar/src/components/ToolbarToggleButton/ToolbarToggleButton.tsx
- packages/react-components/react-toolbar/src/components/ToolbarToggleButton/useToolbarToggleButtonStyles.ts
Fix: #25157 
Update color for `ToolbarToggleButton` to match design spec when item is selected.
> fix: color for selected items in toolbar

- packages/react-components/react-card/stories/Card/CardOrientation.stories.tsx
- packages/react-components/react-card/stories/Card/CardTemplates.stories.tsx
Follow up to #25229
Fixes issue introduced by latest commit to master: https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=270905&view=logs&jobId=be0e6c0b-16d6-5408-4b39-461952619dc9&j=be0e6c0b-16d6-5408-4b39-461952619dc9&t=91e838fc-b8f7-564c-c417-9130335111f3
> fix(react-card): fix import path of asset file

- change/@fluentui-react-dialog-e8675348-6694-4ef1-a767-6c6298ea4515.json
- packages/react-components/react-dialog/src/components/DialogTitle/useDialogTitleStyles.ts
When hovering over close button in "Non Modal" example, the mouse cursor doesn't change to the typical 'pointer' cursor
When hovering over the close button, the mouse cursor is a 'pointer' 
Fixes #25131
> bugfix: adds cursor pointer style to dialog close button

- packages/fluentui/react-northstar/package.json
Fix dependencies mismatches manually after release from `@fluentui/react-components@9.5.2`
> bugfix(react-northstar): react-portal-compat-context deps mismatch

- apps/stress-test/webpack/webpack.config.ts
SWC compression breaks a React 18 feature detection.
Disable SWC compression in Webpack config in favor of Terser.
Fixes #25283
> stress-test: update webpack config

- change/@fluentui-react-18b72fa6-4c4e-4585-b65c-925cc6f1639f.json
- packages/react/src/components/Dropdown/Dropdown.base.tsx
When attempting to use onRenderList with Dropdown, it is impossible to invoke onRenderItem from the props as it's not set. This was handled in ComboBox in a similar fashion but hasn't happened in Dropdown yet.
onRenderItem (default or custom, if set) is passed onRenderContainer, so now it is possible to invoke it through props for both onRenderList and onRenderContainer, similar to what is done in ComboBox.
Fixes #12919, #3050
> Pass onRenderItem to onRenderContainer in the Dropdown component

- change/@fluentui-web-components-4bde24b4-312c-47f7-bbd5-003938181433.json
- packages/web-components/docs/api-report.md
- packages/web-components/src/anchor/anchor.styles.ts
- packages/web-components/src/button/button.styles.ts
- packages/web-components/src/combobox/combobox.stories.ts
- packages/web-components/src/combobox/combobox.styles.ts
- packages/web-components/src/number-field/number-field.styles.ts
- packages/web-components/src/search/search.styles.ts
- packages/web-components/src/select/select.stories.ts
- packages/web-components/src/select/select.styles.ts
- packages/web-components/src/styles/patterns/button.styles.ts
- packages/web-components/src/styles/patterns/input.styles.ts
- packages/web-components/src/text-area/text-area.styles.ts
- packages/web-components/src/text-field/text-field.styles.ts
Currently a few components share some common styling, but it's organized such that some attributes must be overwritten or removed if a different component `appearance` doesn't need them. This has made applying some color recipe updates that support opacity for use of mica difficult.
Following #24771 
This PR cleans up the shared styles to they are more composable and removes the need to reverse attributes that were unnecessarily set.
This update does not produce a visual difference aside from Combobox which currently is missing the focus underline treatment it should have. This PR fixes that, aside from that there are no other visual changes I found.
Anchor
Anchor HC
Button
Button HC
Inputs
Inputs HC
> (web-components) Cleaned up shared styles for button and input for improved reuse and color updates

- change/@fluentui-react-b5a6d88f-3dd6-4c28-8db1-77f85d5870f5.json
- packages/react/src/components/GroupedList/GroupedListV2.base.tsx
`GroupedListV2` does not re-render when props/state that should trigger a re-render are changed (i.e., V2's behavior does not match `GroupedList`).
`GroupedListV2` re-renders as expected.
Fixes #24992
> groupedlistv2: update getderivedstatefromprops

- apps/vr-tests-react-components/src/stories/AvatarGroup.stories.tsx
- change/@fluentui-react-avatar-45cbd570-4f1a-45a8-991c-081cd8781bdf.json
- change/@fluentui-react-components-94d4c956-05ab-4a3e-9df4-edcfa91f7a21.json
- packages/react-components/react-avatar/etc/react-avatar.api.md
- packages/react-components/react-avatar/src/components/AvatarGroupPopover/AvatarGroupPopover.types.ts
- packages/react-components/react-avatar/src/components/AvatarGroupPopover/renderAvatarGroupPopover.tsx
- packages/react-components/react-avatar/src/components/AvatarGroupPopover/useAvatarGroupPopover.tsx
- packages/react-components/react-avatar/src/index.ts
- packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupDefault.stories.tsx
- packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupIndicator.stories.tsx
- packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupLayout.stories.tsx
- packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupSizePie.stories.tsx
- packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupSizeSpread.stories.tsx
- packages/react-components/react-avatar/src/stories/AvatarGroup/AvatarGroupSizeStack.stories.tsx
- packages/react-components/react-avatar/src/stories/AvatarGroup/index.stories.tsx
- packages/react-components/react-avatar/src/utils/index.ts
- packages/react-components/react-avatar/src/utils/partitionAvatarGroupItems.test.ts
- packages/react-components/react-avatar/src/utils/partitionAvatarGroupItems.ts
- packages/react-components/react-components/etc/react-components.unstable.api.md
- packages/react-components/react-components/src/unstable/index.ts
When there are no overflow items, partitionAvatarGroupItems returns an empty array which causes the button to still show up.
`partitionAvatarGroupItems` is not exported in `react-components/unstable`.
`partitionAvatarGroupItems` now returns undefined in `overflowItems` when there are no items overflow. This will be used to check if the AvatarGroupPopover should be rendered or not.
`partitionAvatarGroupItems` is now exported in `react-components/unstable`.
> fix(react-avatar): AvatarGroupPopover is still rendered when there's no items overflowing

- apps/stress-test/scripts/commands/buildTestConfig.ts
Only pages built by the stress test app can be tested.
Any page can be tested by passing at target that starts with `http`.
> stress-test: add ability to target any url

- packages/react-examples/src/react/Callout/Callout.Basic.Example.tsx
The `Callout title` in `Callout.Basic.Example.tsx` is styled as a heading but does not behave like one.
The `Callout title` in `Callout.Basic.Example.tsx` is now a proper heading.
Fixes [15473](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15473)
> docs: Make Callout title in basic example be a proper heading.

- change/@fluentui-react-a356b1ec-2b79-42ad-b811-964c899f748c.json
- packages/react/src/components/Link/Link.styles.ts
- packages/react/src/components/Link/__snapshots__/Link.test.tsx.snap
Disabled links that did not have an href defined would show as enabled in High Contrast due to them being rendered as `button` tags. Here is how they looked in every default High Contrast theme in Windows 11:
Disabled links that do not have an href defined are now shown as disabled in High Contrast even if they are being rendered as `button` tags. Here is how they look in every default High Contrast theme in Windows 11:
Fixes [15275](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15275)
> fix: Fixing color of disabled links in High Contrast mode.

- change/@fluentui-global-context-3a76592d-05b4-4b6e-a538-86abd33e1d4c.json
- packages/react-components/global-context/.npmignore
- packages/react-components/global-context/src/global-context.cy.tsx
- packages/react-components/global-context/tsconfig.cy.json
- packages/react-components/global-context/tsconfig.json
- packages/react-components/global-context/tsconfig.lib.json
- packages/react-components/global-context/tsconfig.spec.json
- Runs `migrate-converged-pkg` which reflects updates made in #24458.
- Moves stories to `stories/` folder in the root of the package.
- Collocates any e2e tests with the component implementation and jest tests.
- removes `common/` folder and moves contents to new `testing/` folder 
- adds `docs/` folder to package root.
- Fixes linting errors
- Part of #24129
> chore(global-context): migrate to new package structure

- change/@fluentui-react-spinbutton-76d708a4-ab34-43c6-a831-8aca052df11b.json
- packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButton.tsx
- packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButtonStyles.ts
Internal SpinButton padding at "small" size does not align with other small input controls.
Internal SpinButton padding at "small" size aligns with other small input controls.
Fixes #24516
> spinbutton: update internal padding for small size

- packages/react-examples/src/react/List/List.Scrolling.Example.tsx
`List`'s scrolling example computes even/odd in two different ways which results in even/odd height calculations being mismatched.
The first method of computing even/odd is via [`nth-child(odd)`](https://github.com/microsoft/fluentui/blob/master/packages/react-examples/src/react/List/List.Scrolling.Example.tsx#L29) and [`nth-child(even)`](https://github.com/microsoft/fluentui/blob/master/packages/react-examples/src/react/List/List.Scrolling.Example.tsx#L34) in CSS which is a [1-based syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child#syntax).
The second method of even/odd computation in in Javascript via the [tried-and-true `i % 2 === 0`](https://github.com/microsoft/fluentui/blob/master/packages/react-examples/src/react/List/List.Scrolling.Example.tsx#L84) which is a …
> fix: list even/odd off-by-one issue

- change/@fluentui-react-55edf27b-cadb-4057-98bd-3e097dc780aa.json
- packages/react/src/components/DetailsList/DetailsList.base.tsx
- packages/react/src/components/DetailsList/DetailsList.test.tsx
Fixes [15391](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15391)
Adds `tabindex="0"` to the first row if `isHeaderVisible=false` is set on the parent DetailsList. This ensures tab focus will always enter the DetailsList, and go to the correct element if there is no header (normally it lands on the first header cell).
FocusZone takes care of tabindex & arrow key behavior after the first time tab enters the DetailsList.
> fix: Detailslist is still tabbable when isHeaderVisible=false

- apps/vr-tests-react-components/package.json
- change/@fluentui-react-components-e65f456e-3889-46a3-b460-22b8ca64c163.json
- change/@fluentui-react-persona-136c281a-d718-41d2-bf77-89ae7c9570b5.json
- packages/react-components/react-components/package.json
- packages/react-components/react-persona/package.json
This PR reverts Persona's release to stable and moves it back to beta. There's no need to move the exports to unstable since they are already exported in unstable.
Note: the version is `9.1.0-beta.0` since the first stable version of Persona will start in `9.1.0`.
Related #25325
> chore(react-persona, react-components, vr-tests-v9): Reverting react-persona's version to beta  

- change/@fluentui-react-persona-136c281a-d718-41d2-bf77-89ae7c9570b5.json
- change/@fluentui-react-persona-a6c9df1e-3923-4018-b1f8-b8a05f609aad.json
- packages/react-components/react-persona/package.json
This PR changes the type of a change file from #25357 to type `none` and updates beachball's configuration in Persona. This change will fix the bug introduced by #24763.
> chore(react-persona): Update beachball settings and change file's type

- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
- tools/types.ts
- setting export maps for both stable and unstable is mixed within 1 function call which breaks domain boundaries and hard migration by scope
- export maps are not set by source of truth which is presence of `main` and `module` fields
- new API `setupUnstableApi` that handles package.json and api-extractor updates for unstable API (encapsulates logic so it's easy to turn off for scoped migration runs)
- export maps are created based on `main` and `module` fields
Follows https://github.com/microsoft/fluentui/pull/25033
> feat(tools): add unstable API setup updates

- change/@fluentui-keyboard-keys-17568f3b-0c78-4d62-9a8e-3bcbfc909077.json
- change/@fluentui-priority-overflow-dbd9bb57-0b7c-4fd7-a98c-e010ee4fa3ed.json
- change/@fluentui-react-conformance-griffel-8a8f2459-c754-4132-bc30-e2c4ae5e619d.json
- change/@fluentui-react-context-selector-93df1771-1d6a-42b0-9ae9-81c69d985405.json
- packages/react-components/keyboard-keys/.npmignore
- packages/react-components/keyboard-keys/tsconfig.spec.json
- packages/react-components/priority-overflow/.npmignore
- packages/react-components/priority-overflow/tsconfig.spec.json
- packages/react-components/react-conformance-griffel/.npmignore
- packages/react-components/react-conformance-griffel/tsconfig.spec.json
- packages/react-components/react-context-selector/.npmignore
- packages/react-components/react-context-selector/tsconfig.spec.json
- Runs `migrate-converged-pkg` on `@fluentui/keyboard-keys`, `@fluentui/priority-overflow`, `@fluentui/react-context-selector` and `@fluentui/react-conformance-griffel` which reflects updates made in #24458.
- Ony minor changes to `.npmignore` and `tsconfig.spec.json` were applied to these packages.
> chore(keyboard-keys, priority-overflow, react-context-selector, react-conformance-griffel): migrate to new package structure

- change/@fluentui-web-components-db44d471-2371-4a26-bb1c-a62e881f3b81.json
- packages/web-components/package.json
- yarn.lock
This PR updates the versions of fast-element and fast-foundation, which includes an update to the event emitted from `fluent-accordion` to include the activeid.
> update fast element and foundation package versions stable

- apps/vr-tests-react-components/package.json
- change/@fluentui-react-components-24a1fd19-7047-45d2-91ae-c60cd3c5d84e.json
- packages/react-components/react-components/package.json
This PR fixes an issue with `@fluentui/react-persona` having a caret instead of being a pinned version. This is due to beta/alpha packages needing to be pinned versions.
Fixes [#25357#discussion_r1004118197](https://github.com/microsoft/fluentui/pull/25357#discussion_r1004118197)
> fix(react-persona): Changing persona's versions to pinned versions

- change/@fluentui-react-7161ec44-2213-4a2c-8b26-aacc793b05d0.json
- change/@fluentui-react-focus-e075be55-1aa4-43b0-aeb5-ffdb377f6070.json
- packages/react-focus/src/components/FocusZone/FocusZone.tsx
- packages/react/src/utilities/selection/SelectionZone.tsx
[HTML `<details>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) would not toggle when inside a `DetailsList`.
`<details>` element now toggles with both the enter and space keys.
Fixes #22135
> allow details element to be toggled inside selection and focus zones

- packages/fluentui/projects-test/src/nextjs.ts
- `next` major bump to version `13.0.0` was just [released ](https://www.npmjs.com/package/next) which is causing `projects-test` to break since it now requires a peer dependency on React 18. This PR explicitly installs the previous major version of  `next` which is version 12 to fix CI error.
Fixes error below:
```
verb @fluentui/projects-test test |  warning package.json: No license field
verb @fluentui/projects-test test |  $ /tmp/project-nextjs--1760-DcBG6QG62tc5/test-app/node_modules/.bin/next build
verb @fluentui/projects-test test |  warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
verb @fluentui/projects-test test |  Attention: Next.js now collects completely anonymous telemetry regarding usage. …
```
> fix(projects-test): explicitly install next version 12 to fix CI

- change/@fluentui-react-ecb76517-ad98-4a5e-b9ca-e853cae9a44d.json
- packages/react-cards/src/components/Card/CardItem/__snapshots__/CardItem.test.tsx.snap
- packages/react-cards/src/components/Card/CardSection/__snapshots__/CardSection.test.tsx.snap
- packages/react-cards/src/components/Card/__snapshots__/Card.view.test.tsx.snap
- packages/react-experiments/src/components/MicroFeedback/__snapshots__/MicroFeedback.test.tsx.snap
- packages/react/src/components/Stack/Stack.styles.ts
- packages/react/src/components/Stack/__snapshots__/Stack.test.tsx.snap
- packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.deprecated.test.tsx.snap
- packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.test.tsx.snap
The `Stack` component applied children selectors independently of if they really needed to be applied or not. These selectors are expensive for style recalculation and are major contributors for slowdown in that step.
Here are the results of a trace running on our v8 docsite's `Stack` page, where most of the most expensive selectors are `Stack`-related:
- rulesFastRejected: 77823
- rulesRejected: 6660
- elapsed time: 7329 microseconds
The `Stack` component now applies most children selectors only when the props indicate they are needed to be applied, which should create better style recalculation performance depending on the props passed in.
Here are the results of a trace running on our v8 docsite's `Stack` page after the change:
- rulesFastRejected: 46619
- rulesRejected: 5935
- elapsed …
> fix: Improve Stack's style recalculation performance by selectively applying children selectors

- apps/public-docsite/src/styles/_base.scss
body a[href]:focus was removing the focus outlines of the footer links. This PR uses a not(footer link class) to both omit those links from the selector, and serve as the selector to increase the link specificity for the rest of our docs.
> Website: fix focus border on UHF footer links

- .storybook/main.js
- Codesandbox exports do not work for packages that have been migrated to the new package structure in #24129
- Codesandbox now account for newly migrated v9 packages and codesandbox exports work again while still maintaining support for unmigrated packages.
Fixes #25350
> fix(docsite): codesandbox exports now working properly for newly migrated v9 packages

- change/@fluentui-react-tabster-59ed64de-6eec-46c5-b0d6-2cd22cba4d0c.json
- packages/react-components/react-tabster/etc/react-tabster.api.md
- packages/react-components/react-tabster/src/hooks/useFocusFinders.ts
Tabster don't require an `acceptCondition` function, but the `findAllFocusable` in `react-tabster` has it required.
Make `acceptCondition` parameter optional.
This is a quick fix for #25413
> fix(react-tabster): make acceptCondition optional as Tabster dont require it

- change/@fluentui-react-select-287be14f-25f7-44e5-b5a7-290b8772638a.json
- packages/react-components/react-select/src/components/Select/useSelectStyles.ts
> react-select: update styles based on design review

- change/@fluentui-react-avatar-63cc4116-6a81-4306-9fee-0415db150eae.json
- packages/react-components/react-avatar/src/components/AvatarGroupItem/useAvatarGroupItemStyles.ts
- packages/react-components/react-avatar/src/components/AvatarGroupPopover/useAvatarGroupPopoverStyles.ts
`AvatarGroup` has a gap between the outline and the Avatar/Button.
AvatarGroup doesn't have a gap anymore.
> fix(react-avatar): Remove gaps between AvatarGroupItem/OveflowButton and its outline

- change/@fluentui-react-fd0c9c49-c0d9-4b5b-8991-45f1667ef481.json
- packages/react/src/components/DatePicker/DatePicker.base.tsx
- packages/react/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
`DatePickers` were skipped within `FocusZones` because the `data-is-focusable` attribute needed for a component to work within a `FocusZone` was not passed to it.
`DatePickers` are now focusable within `FocusZones` because the `data-is-focusable` attribute is added to them in this PR.
Fixes [15509](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15509)
> fix: Allowing DatePicker to be focusable within FocusZones by default

- change/@fluentui-react-positioning-12f69b12-6e86-4415-8a0d-b34318f3b71e.json
- packages/react-components/react-positioning/etc/react-positioning.api.md
- packages/react-components/react-positioning/src/index.ts
- packages/react-components/react-positioning/src/types.ts
- packages/react-components/react-positioning/src/usePositioningMouseTarget.ts
This PR solves internal leakages from `@fluentui/react-positioning` by creating `SetVirtualMouseTarget` type and exposing it instead of exposing internal method `usePositioningMouseTarget`.
- `usePositioningMouseTarget` (❓ create new type `SetVirtualMouseTarget` and make the type external)
> fix(react-positioning): exposes new typings to avoid exposing internal methods

- change/@fluentui-react-shared-contexts-625a6ac7-63ff-4172-a2fd-a4f60b9eff2e.json
- packages/react-components/react-shared-contexts/etc/react-shared-contexts.api.md
- packages/react-components/react-shared-contexts/src/ThemeClassNameContext/ThemeClassNameContext.ts
- packages/react-components/react-shared-contexts/src/ThemeContext/ThemeContext.ts
- packages/react-components/react-shared-contexts/src/TooltipVisibilityContext/TooltipContext.ts
This PR solves internal leakages from `@fluentui/react-shared-contexts` by making their leaking internal typings and methods that are leaking to the API surface external.
- `useThemeClassName_unstable` (✅ Make it external, it's exported at react-components)
- `useTooltipVisibility_unstable` (✅ Make it external, it's exported at react-components)
- `TooltipVisibilityContextValue_unstable` (✅ Make it external)
- `ThemeContextValue_unstable` (✅ Make it external, it's part of react-provider surface API)
> fix(react-shared-contexts): exposes internal leaks used in the API surface

- change/@fluentui-react-aria-5228383f-9887-4ca8-9cc2-53527f839cbf.json
- packages/react-components/react-aria/etc/react-aria.api.md
- packages/react-components/react-aria/src/button/types.ts
- packages/react-components/react-aria/src/index.ts
This PR solves internal leakages from `@fluentui/react-aria` by making their internal typings external.
- `ARIAButtonAlteredProps` (✅ Make it external)
- `ARIAButtonElement` (✅ Make it external)
> fix(react-aria): exposes internal leaking typings

- change/@fluentui-react-context-selector-23a9c999-a4fe-4e81-849b-27a96d250a13.json
- packages/react-components/react-context-selector/etc/react-context-selector.api.md
- packages/react-components/react-context-selector/src/types.ts
This PR solves internal leakages from `@fluentui/react-context-selector` by making their leaking internal typings external.
- `ContextSelector` (✅ Make it external)
> fix(react-context-selector): exposes internal type ContextSelector

- change/@fluentui-react-dialog-a27523cc-5d13-4fd5-ac46-23fc9218bc73.json
- packages/react-components/react-dialog/etc/react-dialog.api.md
- packages/react-components/react-dialog/src/components/DialogTrigger/DialogTrigger.tsx
This PR solves internal leakages from `@fluentui/react-dialog` by inline casting `FluentTriggerComponent` usage to avoid leaking internal type.
> fix(react-dialog): removes exposing of internal type FluentTriggerComponent

- change/@fluentui-react-utilities-4b8968e2-4358-44f1-9085-11dc0120eb70.json
- packages/react-components/react-utilities/etc/react-utilities.api.md
- packages/react-components/react-utilities/src/hooks/useIsomorphicLayoutEffect.ts
- packages/react-components/react-utilities/src/hooks/useMergedRefs.ts
- packages/react-components/react-utilities/src/trigger/types.ts
This PR solves internal leakages from `@fluentui/react-utilities` by making their internal typings and methods external.
- `useIsomorphicLayoutEffect` (✅ Make it external, it's exported at react-components)
- `useMergedRefs` (✅ Make it external, it's exported at react-components)
- `TriggerProps` (✅ Make it external)
> fix(react-utilities): exposes internal methods used in API surface

- change/@fluentui-react-migration-v8-v9-3cbbe105-994c-407f-9441-2c2ce867d5f0.json
- packages/react-migration-v8-v9/config/api-extractor.json
- packages/react-migration-v8-v9/tsconfig.lib.json
Published package was missing lib and lib-commonjs code
- Updated ts.config to build to dist folder like a v8 component
> Fix migration publishing

- change/@fluentui-react-6980f88b-f6c6-426f-a469-d4db3bffadf9.json
- packages/react/src/components/Stack/Stack.styles.ts
- packages/react/src/components/Stack/Stack.types.ts
This PR moves the children selector logic in `Stack`'s styles to a local const that is referenced to avoid duplication and help reduce bundle size of the component.
Applies suggestions from [this comment](https://github.com/microsoft/fluentui/pull/25397#discussion_r1007459264) in #25397
> chore: Reducing bundle size of Stack by moving selector used in multiple places to local const

- change/@fluentui-react-tooltip-f6b6fe84-a30a-41b8-9e3c-6df347d764bb.json
- packages/react-components/react-tooltip/etc/react-tooltip.api.md
- packages/react-components/react-tooltip/src/components/Tooltip/Tooltip.tsx
This PR solves internal leakages from `@fluentui/react-tooltip` by inline casting `FluentTriggerComponent` usage to avoid leaking internal type.
> fix(react-tooltip): removes exposing of internal type FluentTriggerComponent

- change/@fluentui-react-popover-4a2a3285-fde0-4d76-ae6d-aaac8c82c420.json
- packages/react-components/react-popover/etc/react-popover.api.md
- packages/react-components/react-popover/src/components/Popover/Popover.types.ts
- packages/react-components/react-popover/src/components/PopoverTrigger/PopoverTrigger.tsx
This PR solves internal leakages from `@fluentui/react-popover` by inline casting `FluentTriggerComponent` usage to avoid leaking internal type, and adopting new `SetVirtualMouseTarget` type to avoid leaking `usePositioningMouseTarget`
- `usePositioningMouseTarget` (❓ use `SetVirtualMouseTarget`)
> fix(react-popover): removes exposing of internal type FluentTriggerComponent

- change/@fluentui-react-menu-b1450657-0808-4269-92c5-c0c54be96f02.json
- packages/react-components/react-menu/etc/react-menu.api.md
- packages/react-components/react-menu/src/components/Menu/Menu.types.ts
- packages/react-components/react-menu/src/components/MenuTrigger/MenuTrigger.tsx
This PR solves internal leakages from `@fluentui/react-menu` by inline casting `FluentTriggerComponent` usage to avoid leaking internal type, and adopting new `SetVirtualMouseTarget` type to avoid leaking `usePositioningMouseTarget`
- `usePositioningMouseTarget` (❓ use `SetVirtualMouseTarget`)
> fix(react-menu): removes exposing of internal type FluentTriggerComponent

- change/@fluentui-react-slider-6edcf23c-8a46-4642-b3e7-af380c6c87f0.json
- packages/react-components/react-slider/src/components/Slider/useSliderStyles.ts
Slider V9 is missing cursor pointer when hovering or interacting with it.
This PR adds `cursor: pointer` to the slider input and also `cursor: default` for input disabled state.
Fixes #
> V9 Slider is missing cursor pointer

- change/@fluentui-react-toolbar-c7f69f04-c3be-4906-ad8a-199030c47ebb.json
- packages/react-components/react-toolbar/package.json
- packages/react-components/react-toolbar/src/components/ToolbarRadioButton/useToolbarRadioButton.ts
`@fluentui/react-toolbar` has a dependency on `@fluentui/react-hooks`.
`@fluentui/react-toolbar` does not have a dependency on `@fluentui/react-hooks`.
> chore: fix dependencies in @fluentui/react-toolbar

- apps/public-docsite/src/pages/Controls/ButtonPage/docs/cross/ButtonOverview.md
- apps/public-docsite/src/pages/Controls/ButtonPage/docs/windows/ButtonOverview.md
- apps/public-docsite/src/pages/Controls/DrawerPage/docs/ios/DrawerOverview.md
This pull request will address a few small typos on docs pages.
(👋 @shanisebarona and I work on the Accessibility Insights team and are hoping to make contributions to FluentUI. We wanted to start with a small pull request to get acquainted with the repository.)
A few small typos.
Typos are fixed.
Fixes #
> docs: fix small typos

- change/@fluentui-react-toolbar-afed7d12-591a-462e-9ddf-b8a079a5e05a.json
- packages/react-components/react-toolbar/src/components/Toolbar/useToolbar.ts
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarControlledToggleButton.stories.tsx
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarOverflow.stories.tsx
Adding few small `Toolbar` improvements: 
* Fix `onCheckedValuesChange` not being called
* Add aria-label for overflow button items. 
* Add more meaningful value for the controlled toggle button example.
> chore: add few small toolbar improvements

- change/@fluentui-react-table-c3838956-bc8b-4f1d-bcc9-3e89d914bb6f.json
- packages/react-components/react-table/etc/react-table.api.md
- packages/react-components/react-table/src/hooks/types.ts
- packages/react-components/react-table/src/hooks/useSort.ts
```ts
const rows = sort(getRows(row) => ({...row, foo: 'foo'}))
// Error - `foo` does not exist on row
console.log(rows[0].foo)
```
```ts
const rows = sort(getRows(row) => ({...row, foo: 'foo'}))
// Supports TS intellisense
console.log(rows[0].foo)
```
> fix(useTable): sort should adapt to enhanced row types

- .github/workflows/screener-build.yml
- Current workflow setup introduced in #25108 tries to build `@fluentui/vr-tests-react-components` and all of its dependencies which slows down workflow considerably.
- only build what's needed (`@fluentui/react-storybook-addon`) to speed up workflow completion.
> fix(screener-build workflow): scope package to build for v9 VR tests to speed up perf

- scripts/tasks/api-extractor.ts
- scripts/tasks/copy.ts
- scripts/tasks/utils.ts
- `copyCompiled` task dosen't work for node packages  ( no `module` field present )
- reporting for API violations
- is hard to follow
- is printed at the beginning 
- fully manual TS config creation
- `copyCompiled` task works for both web and node packages
- improved API violations reporting
- aggregated reports
- printed at the bottom 
- `tsconfig.lib.json` is used with simple/explicit overrides
**CLI Example:**
1. Missing package dependencies rolluped files
`yarn workspace @fluentui/react-provider generate-api`
↓↓↓
2. Using internal API's  from dependencies as part of public API
`yarn workspace @fluentui/react-provider generate-api`
↓↓↓
Follows https://github.com/microsoft/fluentui/pull/23369
> feat(scripts): improve API violation reporting

- change/@fluentui-react-charting-3475ad9e-70bd-41ba-8508-fb05f00a786f.json
- packages/react-charting/src/components/AreaChart/AreaChart.base.tsx
- packages/react-charting/src/components/DonutChart/DonutChart.base.tsx
- packages/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
- packages/react-charting/src/components/HeatMapChart/HeatMapChart.base.tsx
- packages/react-charting/src/components/Legends/Legends.base.tsx
- packages/react-charting/src/components/LineChart/LineChart.base.tsx
- packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
- packages/react-charting/src/components/StackedBarChart/StackedBarChart.base.tsx
- packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx
- packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx
- Legend selection gets lost after hovering out of the overflow callout
- Legend states in chart components don't stay in sync with the Legends component. For example, in case of multiple legend selection, wrong element gets highlighted when mouse hasn't left the last deselected legend
- Three states (selectedLegend, isLegendSelected, isLegendHovered) keep track of selection and hovering on legends together
- Legends selection remains even after hovering out of the overflow callout
- Legend states in chart components and the Legends component stay in sync
- Two states (selectedLegend, activeLegend) keep track of selection and hovering on legends separately
> Fix legends selection bugs

- change/@fluentui-react-button-c452c0d5-b913-4697-906a-ab9effbe88b2.json
- packages/react-components/react-button/src/components/Button/useButtonStyles.ts
- packages/react-components/react-button/src/components/ToggleButton/useToggleButtonStyles.ts
- packages/react-components/react-button/stories/Button/ButtonAppearance.stories.tsx
- packages/react-components/react-button/stories/Button/ButtonIcon.stories.tsx
- packages/react-components/react-button/stories/Button/ButtonSize.stories.tsx
- packages/react-components/react-button/stories/CompoundButton/CompoundButtonAppearance.stories.tsx
- packages/react-components/react-button/stories/CompoundButton/CompoundButtonDefault.stories.tsx
- packages/react-components/react-button/stories/CompoundButton/CompoundButtonIcon.stories.tsx
- packages/react-components/react-button/stories/CompoundButton/CompoundButtonSize.stories.tsx
- packages/react-components/react-button/stories/MenuButton/MenuButtonIcon.stories.tsx
- packages/react-components/react-button/stories/MenuButton/MenuButtonSizeLarge.stories.tsx
- packages/react-components/react-button/stories/MenuButton/MenuButtonSizeMedium.stories.tsx
- packages/react-components/react-button/stories/MenuButton/MenuButtonSizeSmall.stories.tsx
- packages/react-components/react-button/stories/SplitButton/SplitButtonIcon.stories.tsx
- packages/react-components/react-button/stories/SplitButton/SplitButtonSizeLarge.stories.tsx
- packages/react-components/react-button/stories/SplitButton/SplitButtonSizeMedium.stories.tsx
- packages/react-components/react-button/stories/SplitButton/SplitButtonSizeSmall.stories.tsx
- packages/react-components/react-button/stories/ToggleButton/ToggleButtonAppearance.stories.tsx
- packages/react-components/react-button/stories/ToggleButton/ToggleButtonIcon.stories.tsx
The documentation on `Buttons` showed usage of icons that is not according to the design specification regarding when they should be shown as regular vs filled.
The documentation on `Buttons` now shows the correct usage of icons according to the design specification regarding when they should be shown as regular vs filled. This PR also fixes some issues with the icon color on `subtle` `Buttons` on hovered and pressed states.
Fixes #23808
> fix: Showing correct behavior for icons inside of Buttons on hover, pressed and toggle states

- change/@fluentui-react-89430e74-6347-4a7d-ad5b-9a3b5bebfc31.json
- packages/react/etc/react.api.md
- packages/react/src/components/ChoiceGroup/ChoiceGroup.types.ts
- packages/react/src/components/ChoiceGroup/ChoiceGroupOption/ChoiceGroupOption.base.tsx
- packages/react/src/components/ChoiceGroup/ChoiceGroupOption/ChoiceGroupOption.types.ts
Previous PR https://github.com/microsoft/fluentui/pull/24242 used a union of the IChoiceGroupOption and IChoiceGroupOptionProps types for the parameter in callbacks.  This was to try and avoid a breaking change between v7 and v8.  However, it forced callback definers to have to support both types.
- changed from union of params to intersection to allow callbacks to accepted either type or both
- updated ChoiceGroup to callback with the intersected object type.
> Updated ChoiceGroup to allow callbacks to define one prop type

- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
- Conditionally adds `src/testing/` subfolder to `tsconfig.spec.json` of `migrate-converged-pkg`
> fix(tools): conditionally add testing subfolder to tsconfig include glob in migrate-converged-pkg 

- change/@fluentui-react-components-a065d3d7-c686-4ce0-b520-0b1875853ca0.json
- change/@fluentui-react-table-a94f4f80-c021-4eb8-a8e3-789425aee9e2.json
- packages/react-components/react-components/etc/react-components.unstable.api.md
- packages/react-components/react-components/src/unstable/index.ts
- packages/react-components/react-table/etc/react-table.api.md
- packages/react-components/react-table/src/components/DataGrid/DataGrid.test.tsx
- packages/react-components/react-table/src/components/DataGrid/__snapshots__/DataGrid.test.tsx.snap
- packages/react-components/react-table/src/components/DataGridRow/DataGridRow.test.tsx
- packages/react-components/react-table/src/components/DataGridRow/DataGridRow.types.ts
- packages/react-components/react-table/src/components/DataGridRow/__snapshots__/DataGridRow.test.tsx.snap
- packages/react-components/react-table/src/components/DataGridRow/useDataGridRow.ts
- packages/react-components/react-table/src/hooks/createColumn.ts
- packages/react-components/react-table/src/hooks/index.ts
- packages/react-components/react-table/src/hooks/types.ts
- packages/react-components/react-table/src/hooks/useSort.test.ts
- packages/react-components/react-table/src/hooks/useTable.test.ts
- packages/react-components/react-table/src/index.ts
- packages/react-components/react-table/stories/DataGrid/Default.stories.tsx
- packages/react-components/react-table/stories/Table/MultipleSelect.stories.tsx
- packages/react-components/react-table/stories/Table/MultipleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/Table/SingleSelect.stories.tsx
- packages/react-components/react-table/stories/Table/SingleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/Table/Sort.stories.tsx
- packages/react-components/react-table/stories/Table/SortControlled.stories.tsx
- packages/react-components/react-table/stories/Table/SubtleSelection.stories.tsx
This PR makes the `ColumnDefinition` API stricter so that `compare` is now a required property.
```ts
import { ColumnDefinition } from '@fluentui/react-components/unstable;
// ⚠️ This will now error because of missing properties
const column: ColumnDefinition<Item> = [{ columnId: "column" }];
```
```ts
import { ColumnDefinition, createColumn } from '@fluentui/react-components/unstable;
// ✅ This will create the stricter column definition with defaults
const column: ColumnDefinition<Item> = [createColumn({ columnId: "column" })];
```
Fixes #25458
> feat: Implement render function for DataGridRow

- change/@fluentui-react-components-ba631a4c-e394-4ffa-b4f3-e84de4f8c733.json
- packages/react-components/react-components/.storybook/main.utils.js
- packages/react-components/react-components/.storybook/main.utils.test.js
- stories of migrated v9 packages as part of #24129 don't load when running `yarn workspace @fluentui/react-components start`
- stories of migrated v9 packages are now included
Part of #24129
> fix(react-components): stories for migrated v9 packages are included again

- azure-pipelines.bundlesize.yml
- azure-pipelines.yml
Enable build pipeline for `web-components-v3` branch so that PRs to that branch must pass the build before merging.
> Enable build pipeline for web-components-v3 branch

- change/@fluentui-react-table-7398941b-ae22-4a18-878d-1ac8e853c6ee.json
- packages/react-components/react-table/etc/react-table.api.md
- packages/react-components/react-table/src/components/DataGrid/DataGrid.test.tsx
- packages/react-components/react-table/src/components/DataGrid/DataGrid.types.ts
- packages/react-components/react-table/src/components/DataGrid/__snapshots__/DataGrid.test.tsx.snap
- packages/react-components/react-table/src/components/DataGrid/useDataGrid.ts
- packages/react-components/react-table/src/components/DataGrid/useDataGridContextValues.ts
- packages/react-components/react-table/src/components/DataGridCell/DataGridCell.test.tsx
- packages/react-components/react-table/src/components/DataGridCell/__snapshots__/DataGridCell.test.tsx.snap
- packages/react-components/react-table/src/components/DataGridCell/useDataGridCell.ts
- packages/react-components/react-table/src/components/DataGridSelectionCell/__snapshots__/DataGridSelectionCell.test.tsx.snap
- packages/react-components/react-table/src/components/DataGridSelectionCell/useDataGridSelectionCell.ts
- packages/react-components/react-table/src/contexts/dataGridContext.ts
- packages/react-components/react-table/src/index.ts
- packages/react-components/react-table/src/testing/mockDataGridContext.ts
- packages/react-components/react-table/stories/DataGrid/Default.stories.tsx
Applies `useArrowNagivationGroup` by default to `DataGrid` when the `focusMode` prop is set. Also sets correct roles for `grid
Fixes #25478 
Fixes #25477
> feat: Implement `focusMode` prop for DataGrid, apply role="grid" correctly

- change/@fluentui-react-toolbar-bac826cc-5a66-447f-ab37-f85d8df68fb9.json
- packages/react-components/react-toolbar/src/components/Toolbar/useToolbar.ts
- packages/react-components/react-toolbar/src/components/ToolbarRadioButton/ToolbarRadioButton.test.tsx
- packages/react-components/react-toolbar/src/components/ToolbarRadioButton/useToolbarRadioButton.ts
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarRadioControlled.stories.tsx
Fix `ToolbarRadio` storie and click that was being prevented
> fix: ToolbarRadio example and click event

- azure-pipelines.bundlesize.yml
I enabled the bundle size pipeline for PRs to web-components-v3 in #25529.
Unfortunately I forgot to enable it on the branch itself. For that reason the branch is missing baseline measurements.
This PR enables the pipeline on the branch.
> chore(WebComponents v3): Enable bundlesize pipeline

- apps/stress-test/package.json
- apps/stress-test/src/shared/react/TestMount.tsx
- apps/stress-test/src/shared/utils/performanceMeasure.ts
- apps/stress-test/src/shared/utils/requestPostAnimationFrame.ts
- apps/stress-test/src/shared/vanilla/TestMount.ts
- yarn.lock
`stress-test` has a function called `requestPostAnimationFrame` that allows us to measure the time between the start of the browser rendering a frame and the end. This is useful for measure style recalculation, layout and paint.
Drop `requestPostAnimationFrame` in favor of taking a dependency on `afterframe`, a library that does the same thing. This reduces the amount of code in the `stress-test` app itself and allows us to focus on the features of the tool itself.
> stress-test: add "afterframe" dependency

- change/@fluentui-react-tabs-5857fdb2-8ae6-4796-9d11-757f662e5046.json
- packages/react-components/react-tabs/etc/react-tabs.api.md
- packages/react-components/react-tabs/src/components/Tab/Tab.types.ts
- packages/react-components/react-tabs/src/components/Tab/renderTab.tsx
- packages/react-components/react-tabs/src/components/Tab/useTab.ts
- packages/react-components/react-tabs/src/components/Tab/useTabStyles.ts
- packages/react-components/react-tabs/src/components/TabList/TabList.types.ts
- packages/react-components/react-tabs/src/components/TabList/TabListContext.ts
- packages/react-components/react-tabs/src/components/TabList/__snapshots__/TabList.test.tsx.snap
- packages/react-components/react-tabs/src/components/TabList/useTabList.ts
- packages/react-components/react-tabs/src/components/TabList/useTabListContextValues.tsx
Currently tab size is based on the content within.  When a tab is selected, a bold font is used.  This causes tabs to be different sizes between unselected and selected states creating a visual movement of tabs.
This updates TabList and Tab to reserve space in unselected tabs to the content is the same size for both states.  This eliminates the visual movements of tabs.
- Added reserveSelectedTabSpace to TabList context
- Added contentReservedSpaceClassName to TabState
- Updated useTab to set contentReservedSpaceClassName based on context reserveSelectedTabSpace
- Updated useTabStyles to set contentReservedSpaceClassName style to match selected tab content style
- Updated renderTab to render content slot again with with selected tab content style and visibility:hidden
- Updates test …
> Fix: Update tabs to remain the same size between unselected and selected states

- change/@fluentui-react-spinner-9b660086-15f0-4220-970b-d21b6a1e0ed4.json
- packages/react-components/react-spinner/Spec.md
- packages/react-components/react-spinner/src/stories/Spinner/SpinnerBestPractices.md
This PR is to add more documentation about the `Spinner` behavior when `reduced-motion` is active. Fixes #25449
> chore: Add reduced-motion documentation to Spinner

- apps/stress-test/src/shared/css/injectStyles.ts
When controls under test in `stress-test` have CSS `transition` styles the style recalculation measurement becomes unreliable in Firefox. Sometimes the measurement includes the transition time (i.e., we add something like 100ms to the style recalc time) and sometimes it does not. Chromium browsers remain stable on this measurement and never measure the transition time.
Transition styles are disabled on any DOM node that matches a style injected by `stress-test`. This stabilizes Firefox's measurement and aligns it with Chromium so we're measuring the same thing in both engines.
This is taken from Chrome but Edge gives the same results.
This aligns with Chromium 👍
This does not ☹️
Measuring style recalc and layout in browsers is [somewhat …
> stress-test: disable CSS transitions on injected styles

- rfcs/shared/build-system/triage-automation.md
[👓 PREVIEW](https://github.com/microsoft/fluentui/pull/24817/files?short_path=7e93867#diff-7e938677b3fc951cde8d369feb66774ced52123fbe7766b98d2c47ee2e4525f8)
> docs(rfcs): add triage automation rfc

- change/@fluentui-react-switch-478e98a6-f6a5-411e-bcea-50c112ce9e77.json
- packages/react-components/react-switch/src/components/Switch/useSwitchStyles.ts
Since line height is not provided internally, it'll be inherited from parent, and that might cause some visual issues
https://codesandbox.io/s/react-switch-line-height-issue-5cd2w9
Introduces a line height value of `0` to `indicator` slot, to ensure this visual issue won't happen.
Fixes #25505
> bugfix(react-switch): adds line-height=0 to switch indicator slot

- change/@fluentui-react-tabster-caace24f-01b0-4a75-b0c1-286a6698b7ae.json
- packages/react-components/react-tabster/etc/react-tabster.api.md
- packages/react-components/react-tabster/src/hooks/useArrowNavigationGroup.ts
Add `both` option to useArrowNavigationGroup
> chore: add both options to useArrowNavigationGroup

- change/@fluentui-react-toolbar-ae0fefac-6a13-44eb-998c-cd16e5537a8d.json
- packages/react-components/react-toolbar/src/components/Toolbar/__snapshots__/Toolbar.test.tsx.snap
- packages/react-components/react-toolbar/src/components/Toolbar/useToolbar.ts
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarControlledToggleButton.stories.tsx
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarDefault.stories.tsx
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarRadio.stories.tsx
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarRadioControlled.stories.tsx
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarSmall.stories.tsx
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarSubtle.stories.tsx
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarVertical.stories.tsx
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarWithPopover.stories.tsx
- packages/react-components/react-toolbar/src/stories/Toolbar/ToolbarWithTooltip.stories.tsx
- packages/react-components/react-toolbar/src/stories/Toolbar/index.stories.tsx
Here is a set of improvements based on our a11y Feedback from @adamsamec
> chore: toolbar a11y improvements

- change/@fluentui-eslint-plugin-ae682cae-04ae-4e42-a4ba-cbf2525ad490.json
- change/@fluentui-react-10ceb504-58ea-4967-b2d3-daae2d632740.json
- packages/eslint-plugin/src/configs/base-legacy.js
- packages/eslint-plugin/src/configs/react-legacy.js
- packages/react/src/index.ts
1. Using esbuild, bundle @fluentui/react/lib/index.js with esbuild, but externalize `date-time-utilities`.
2. Try to import `DayOfWeek` from bundle.
It's not exported because there are multiple paths to the external library, and esbuild gives up trying to dedupe across external boundaries.
Due to expanding the root barrel index.ts star exports, paths to the exported things are now straightened out and you can now import `DayOfWeek` from the resulting bundle.
* The api extractor result validated no api shift
* There were a number of duplicates in the exports that I removed by manually removing red squiggles.
* It is possible but very unlikely that importing `{namedThing} from './SomeTopLevelThing'` could translate to more nested export * ambiguity deeper int the tree, without getting rid …
> Expand @fluentui/react root index file's export *s to uncover and fix duplicate exports.

- change/@fluentui-react-combobox-e478d812-6a6a-4b46-88a4-6a97b5dbcfbd.json
- change/@fluentui-react-input-2a9cb459-0806-4724-975c-73942f819d43.json
- change/@fluentui-react-select-ca9fbff7-be4b-431a-9be6-0f53bbc1ace7.json
- change/@fluentui-react-spinbutton-38b70b81-ebfc-45b7-862d-df3ae34b6ce6.json
- packages/react-components/react-combobox/src/components/Combobox/useComboboxStyles.ts
- packages/react-components/react-combobox/src/components/Dropdown/useDropdownStyles.ts
- packages/react-components/react-input/src/components/Input/useInputStyles.ts
- packages/react-components/react-select/src/components/Select/useSelectStyles.ts
- packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButtonStyles.ts
Fixes #24761
Adds these changes:
- Input: switches to `borderColor` disabled styling so underline retains the single border
- Select: same as Input, with the minor variation that underline + disabled needs to specify top/left/right transparent borders to override nave `<select>` styles
- SpinButton: makes filled disabled variants be the same as outline to match Input & makes the same change for the underline style. 
- Combobox & Dropdown: fix disabled styles to match Input
> fix: v9 form controls with underline should have underline-specific disabled styling

- apps/public-docsite-v9/src/Concepts/SSR/SSR.stories.mdx
We noticed that since the docs only mention NextJS, it can be confusing how to setup SSR with Fluent UI v9. The most important part being that a `SSRProvider`, `FluentProvider`, and a `RendererProvider` are needed to avoid hydration issues among others. This PR adds a `Basic setup` section to the SSR docs and mentions how to add these.
> docs(public-docsite-v9): Adding a basic setup section to the SSR docs

- apps/public-docsite-v9/src/DocsComponents/ThemePicker.stories.tsx
Whenever you select a new value in the theme picker in a storybook, the value isn't updated until you switch to another story, most likely caused by 
`addons.getChannel().emit('updateGlobals', { globals: { [THEME_ID]: themeId } });`
not triggering an update at component level.
Using a local state in the theme switcher for the current value so it always shows what's been currently selected.
> fix(storybook): fix theme picker current selection

- apps/vr-tests-react-components/src/stories/Avatar.stories.tsx
- change/@fluentui-react-avatar-9327cda3-0b08-4b5d-aaa3-48b18735285b.json
- packages/react-components/react-avatar/src/components/Avatar/useAvatarStyles.ts
The ring color for Avatar's active state is hardcoded to the brand color, but the design specifies that it should match the color of the Avatar.
Have Avatar's active ring color follow the color of the Avatar.
* Fixes #25496
> fix: Update Avatar active ring color to match base color

- apps/vr-tests-react-components/src/stories/Tabs.stories.tsx
- change/@fluentui-react-tabs-9707187f-ba5a-45f1-a521-3aac9918a416.json
- change/@fluentui-react-theme-abd73672-2ebe-4112-90fb-9219bfe2cc54.json
- packages/react-components/react-tabs/etc/react-tabs.api.md
- packages/react-components/react-tabs/src/components/Tab/Tab.test.tsx
- packages/react-components/react-tabs/src/components/Tab/Tab.types.ts
- packages/react-components/react-tabs/src/components/Tab/__snapshots__/Tab.test.tsx.snap
- packages/react-components/react-tabs/src/components/Tab/useTabStyles.ts
- packages/react-components/react-tabs/src/components/TabList/TabList.types.ts
- packages/react-components/react-tabs/stories/Tabs/TabListSizeLarge.stories.tsx
- packages/react-components/react-tabs/stories/Tabs/TabListSizeSmall.stories.tsx
- packages/react-components/react-tabs/stories/Tabs/index.stories.tsx
- packages/react-components/react-theme/src/global/typographyStyles.ts
Tabs support small and medium sizes
Tabs support small, medium, and large sizes
- added large to the size property union
- Updated tab style hook to set large styles according to figma
- Added large size to storybook
- Updated tab tests to cover large size
- Updated vr-tests to include large size
Fixes #25551
> Feature: Added large tab size to react-tabs

- packages/react-components/react-infobutton/etc/react-infobutton.api.md
- packages/react-components/react-infobutton/src/components/InfoButton/DefaultInfoButtonIcon.tsx
- packages/react-components/react-infobutton/src/components/InfoButton/DefaultInfoButtonIcons.tsx
- packages/react-components/react-infobutton/src/components/InfoButton/InfoButton.types.ts
- packages/react-components/react-infobutton/src/components/InfoButton/useInfoButton.tsx
- packages/react-components/react-infobutton/src/components/InfoButton/useInfoButtonStyles.ts
- packages/react-components/react-infobutton/src/stories/Infobutton/InfoButtonSize.stories.tsx
- packages/react-components/react-infobutton/src/stories/Infobutton/index.stories.tsx
* Updates styles to match updated design spec tokens.
* Adds High Contrast Mode styles.
* Adds `size` prop as shown in the design spec.
Related #25062
> feat(react-infobutton): Adding size prop, HCM styles, and updating styles to match design spec

- change/@fluentui-react-tabs-509e61ea-8dad-490f-9503-54f49362f231.json
- packages/react-components/react-tabs/src/components/Tab/useTabStyles.ts
- packages/react-components/react-tabs/stories/Tabs/TabListDisabled.stories.tsx
- packages/react-components/react-tabs/stories/Tabs/TabListIconOnly.stories.tsx
- packages/react-components/react-tabs/stories/Tabs/TabListSizeLarge.stories.tsx
- packages/react-components/react-tabs/stories/Tabs/TabListSizeMedium.stories.tsx
- packages/react-components/react-tabs/stories/Tabs/TabListSizeSmall.stories.tsx
- packages/react-components/react-tabs/stories/Tabs/TabListWithIcon.stories.tsx
- packages/react-components/react-tabs/stories/Tabs/TabListWithOverflow.stories.tsx
- packages/react-components/react-tabs/stories/Tabs/TabListWithPanels.stories.tsx
- Added support in tab styles for toggling between regular and filled icons
- Updated storybook to demonstrate using bundled icons
Fixes #25552
> Tabs icon toggle

- change/@fluentui-react-dialog-64415a56-f53d-498c-8000-38ce9610b103.json
- packages/react-components/react-dialog/etc/react-dialog.api.md
- packages/react-components/react-dialog/src/components/Dialog/Dialog.types.ts
https://github.com/microsoft/fluentui/blob/6ce378e366246cc7504a7adc7a49ad5c06c11f1e/packages/react-components/react-dialog/src/components/Dialog/Dialog.types.ts#L10-L33
`dialogCancel` data type refers to a scenario involving native dialog.
Since native dialogs are not supported anymore this union case becomes irrelevant. This PR removes that case.
> chore(react-dialog): removes unnecessary union case for DialogOpenChangeData

- scripts/lint-staged/eslint-for-package.js
- scripts/lint-staged/eslint.js
Fixes https://github.com/microsoft/fluentui/issues/25532
> fix(scripts): make eslint run again on pre-commit

- change/@fluentui-react-menu-18f45b88-3199-463a-8745-635943d6bccb.json
- packages/react-components/react-menu/etc/react-menu.api.md
- packages/react-components/react-menu/src/components/Menu/Menu.cy.tsx
- packages/react-components/react-menu/src/components/MenuList/MenuList.cy.tsx
- packages/react-components/react-menu/src/components/MenuTrigger/MenuTrigger.types.ts
- packages/react-components/react-menu/src/components/MenuTrigger/useMenuTrigger.ts
- packages/react-components/react-menu/src/testing/selectors.ts
Currently `aria-haspopup` and `aria-expanded` are being added on 2 scenarios:
1. a button trigger
2. a context menu trigger (which normally isn't a button)
This PR ensure the aria attributes are only added on the first scenario (the one of a button trigger).
Fixes https://github.com/microsoft/fluentui/issues/25607
Fixes https://github.com/microsoft/fluentui/issues/24902
> fix(react-menu): remove unwanted aria attributes on context menu

- change/@fluentui-react-utilities-4d6f852b-64d8-4458-a485-11c9bf778ac0.json
- packages/react-components/react-utilities/src/utils/properties.ts
Seems like `colSpan` is not included as supported attribute for `getNativeElementProps` with `th`.
https://github.com/microsoft/fluentui/blob/d1228a137bb5f28014bad869d88584ae95ba46da/packages/react-components/react-utilities/src/utils/properties.ts#L329-L332
1. Adds `colSpan` as a valid property.
Fixes https://github.com/microsoft/fluentui/issues/25612
> fix(react-table): supports colSpan property for `th`

- change/@fluentui-react-table-cff42d31-144a-4400-9165-d98d429d1abd.json
- packages/react-components/react-table/src/components/TableRow/useTableRowStyles.ts
Currently, in light mode both TableCellActions and TableSelectionCell match the color of the table row on hover. TableSelectionCell keeps the hover style when the row is clicked on, and TableCellActions matches the pressed background color.
In dark mode, both of these elements have different background colors on hover and press.
The tokens have been updated to match what the table row uses. The light mode behaviour was used as a template.
Fixes #25627
> Match hover background colors b/t table row and cell actions

- change/@fluentui-react-dialog-cfbd0be5-81c5-4351-9f00-8931078078c2.json
- packages/react-components/react-dialog/src/components/Dialog/Dialog.cy.tsx
- packages/react-components/react-dialog/src/components/Dialog/useDialog.ts
- packages/react-components/react-dialog/src/components/Dialog/useDialogContextValues.ts
- packages/react-components/react-dialog/src/components/DialogContent/useDialogContent.ts
- packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurface.ts
- packages/react-components/react-dialog/src/components/DialogTitle/DialogTitle.cy.tsx
- packages/react-components/react-dialog/src/components/DialogTrigger/DialogTrigger.test.tsx
- packages/react-components/react-dialog/src/components/DialogTrigger/__snapshots__/DialogTrigger.test.tsx.snap
- packages/react-components/react-dialog/src/components/DialogTrigger/useDialogTrigger.ts
- packages/react-components/react-dialog/src/contexts/dialogContext.ts
- packages/react-components/react-dialog/src/testing/selectors.ts
- packages/react-components/react-dialog/stories/Dialog/DialogBestPractices.md
- packages/react-components/react-dialog/stories/Dialog/DialogTriggerOutsideDialog.md
- packages/react-components/react-dialog/stories/Dialog/DialogTriggerOutsideDialog.stories.tsx
- packages/react-components/react-dialog/stories/Dialog/DialogWithForm.md
Currently `DialogTrigger` introduces `aria-haspopup` to it's child to ensure `accessibility`.
As stated  in https://github.com/microsoft/fluentui/issues/25151, we should be using `aria-expanded` instead of `aria-haspopup`
1. removes `aria-haspopup` for `DialogTrigger`
2. adds `aria-expanded` for `DialogTrigger`
3. updates stories to reflect change
4. removes `aria-describedby` from `DialogSurface`
5. adds best practices on how to properly use `aria-describedby`
Fixes https://github.com/microsoft/fluentui/issues/25151
> feat(react-dialog): removes `aria-haspopup`

- apps/public-docsite-v9/src/Concepts/Theming.stories.mdx
Fixes #25436
One-line URL change, now points to the Theme Colors page.
> fix:  v9 docs Theme link points to correct url

- change/@fluentui-utilities-6d708b55-ae70-43d3-bae5-d23b00ab9b73.json
- packages/utilities/src/object.test.ts
- packages/utilities/src/object.ts
Fixes #25371
Updates the `shallowCompare` in `@fluentui/utilities` to handle falsy values.
Previously, `shallowCompare(null, {a: 'b'})` would throw an error for trying to access `.hasOwnProperty` of `null`.
Now it does the following:
- If both compared variables are falsy it returns true regardless of if they're the same value, to preserve existing behavior. So `shallowCompare(null, undefined)` will return true (this was the case before the change).
- If one of the compared variables is falsy and the other is not, it will return false
- When both variables are truthy, the behavior is not changed
I also added some tests for `shallowCompare`, since it had none previously
> fix: handle null and undefined in @fluentui/utilities shallowCompare

- change/@fluentui-react-table-edbad8fb-57a4-46a3-94ba-b8d0e38a1944.json
- packages/react-components/react-table/etc/react-table.api.md
- packages/react-components/react-table/src/hooks/selectionManager.ts
- packages/react-components/react-table/src/hooks/types.ts
- packages/react-components/react-table/src/hooks/useSelection.test.ts
- packages/react-components/react-table/src/hooks/useSelection.ts
- packages/react-components/react-table/src/hooks/useSort.test.ts
- packages/react-components/react-table/src/hooks/useSort.ts
- packages/react-components/react-table/src/testing/mockSyntheticEvent.ts
- packages/react-components/react-table/stories/Table/MultipleSelect.stories.tsx
- packages/react-components/react-table/stories/Table/MultipleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/Table/SingleSelect.stories.tsx
- packages/react-components/react-table/stories/Table/SingleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/Table/Sort.stories.tsx
- packages/react-components/react-table/stories/Table/SortControlled.stories.tsx
- packages/react-components/react-table/stories/Table/SubtleSelection.stories.tsx
In order to support `DataGrid` easily and also conform to current library patterns, all headless table callbacks should be called with an event as first argument.
**The other arguments remain unchanged, the event argument is pushed to first place**
Affected callbacks:
* clearRows
* deselectRow
* selectRow
* toggleAllRows
* toggleRow
* setColumnSort
* toggleColumnSort
* onSelectionChange
* onSortChange
```ts
const onClick = () => {
clearRows();
deselectRow(rowId);
selectRow(rowId);
toggleAllRows();
toggleRow(rowId);
setColumnSort(columnId, 'ascending');
toggleColumnSort(columnId);
}
useTable({
items,
columns,
},
[
useSort({ onSortChange: (sortState) => console.log(sortState) }),
useSelection({ onSelectionChange: (selectedRows) => console.log(selectedRows })
]
)
```
```ts
const onClick = …
```
> BREAKING: Headless table callbacks require event

- change/@fluentui-react-table-bfaf115f-c73a-46d6-9aa3-c45d2e3d9aa7.json
- packages/react-components/react-table/src/components/TableHeader/TableHeader.test.tsx
- packages/react-components/react-table/src/components/TableHeader/useTableHeader.ts
- packages/react-components/react-table/stories/Table/MultipleSelect.stories.tsx
- packages/react-components/react-table/stories/Table/Sort.stories.tsx
- packages/react-components/react-table/stories/Table/SortControlled.stories.tsx
Setting the `sortable` prop no longer sets tabster attributes on the `TableHeader`. This reduces the scope of the primitives to have no default focus management. Now there's only one way to do keyboard navigation with primitives.
```tsx
{/* sortable will make the cells in TableHeader navigable using arrow keys */}
<Table sortable>
<TableHeader>
<TableRow>
<TableHeaderCell />
<TableHeaderCell />
<TableHeaderCell />
</TableRow>
</TableHeader>
{/* ... */}
</Table>
```
```tsx
const keyboardNavAttr = useArrowNavigationGroup({ axis: 'grid' });
{/* The user will need to apply for management themselves */}
<Table sortable {...keyboardNavAttr}>
<TableHeader>
<TableRow>
<TableHeaderCell />
<TableHeaderCell />
<TableHeaderCell />
</TableRow>
</TableHeader>
{/* ... */}
</Table>
```
> BREAKING: `sortable` prop no longer enables `TableHeader` navigation

- change/@fluentui-react-theme-a729b272-7bf6-4abe-9372-70300f8e776b.json
- packages/react-components/react-theme/src/global/spacings.ts
`spacings` was marked as exported inside the package (**it has never exported out of the package**)
`spacings` are now internal to the file to avoid confuction
> chore(react-theme): do not export spacings

- change/@fluentui-react-components-ef3d0d2f-e887-444c-90f3-ccd17ce00829.json
- change/@fluentui-react-menu-7fc995f8-caf5-41d7-8486-131d88c39883.json
- packages/react-components/react-components/etc/react-components.api.md
- packages/react-components/react-components/src/index.ts
- packages/react-components/react-menu/etc/react-menu.api.md
- packages/react-components/react-menu/src/components/Menu/Menu.test.tsx
- packages/react-components/react-menu/src/components/Menu/Menu.types.ts
- packages/react-components/react-menu/src/components/Menu/useMenu.tsx
- packages/react-components/react-menu/src/components/MenuItem/MenuItem.test.tsx
- packages/react-components/react-menu/src/components/MenuItem/useMenuItem.tsx
- packages/react-components/react-menu/src/components/MenuPopover/useMenuPopover.ts
- packages/react-components/react-menu/src/components/MenuTrigger/useMenuTrigger.ts
- packages/react-components/react-menu/src/index.ts
Currently `MenuOpenChangeData` doesn't provide a proper type system to identify which kind of event generated the request for change.
By introducing a union of types of events we're able to create a filtering mechanism that allows further customisation from the user side and a more granular knowledge of what causes the change request on a menu open event.
This approach follows a similar pattern described on `react-dialog` `DialogOpenChangeData` type.
https://github.com/microsoft/fluentui/blob/6ce378e366246cc7504a7adc7a49ad5c06c11f1e/packages/react-components/react-dialog/src/components/Dialog/Dialog.types.ts#L10-L33
1. Deprecates `MenuOpenEvents` in favor of `MenuOpenEvent` type.
a. The `MenuOpenEvents` is an union of all possible event types, the plural suggests multiplicity, not …
> feature(react-menu): improve menu open change data with union types

- scripts/tasks/copy.ts
After https://github.com/microsoft/fluentui/pull/25609, v9 packages that need to ship AMD will not ship it
v9 packages ship AMD if they have it setup
Follows https://github.com/microsoft/fluentui/pull/25609
> fix(scripts): copy amd files for ts-solution projects if they exist

- apps/public-docsite-v9/.storybook/preview.js
- apps/public-docsite-v9/src/Concepts/SSR/Nextjs.stories.mdx
- apps/public-docsite-v9/src/Concepts/SSR/Portals.stories.mdx
- apps/public-docsite-v9/src/Concepts/SSR/SSR.stories.mdx
* Updates basic setup code with comments.
* Adds a folder for SSR.
* Splits the basic setup and NextJS setup.
* This is needed since we'll add more platform setups like Gatsby.
* Splits Portal section into its own page for better visibility.
> docs(public-docsite-v9): Split Basic and NextJS setups into two pages

- apps/public-docsite/src/SiteDefinition/SiteDefinition.pages/Controls/web.tsx
- apps/public-docsite/src/pages/Controls/DetailsListPage/DetailsListGroupedV2Page.doc.ts
- apps/public-docsite/src/pages/Controls/DetailsListPage/DetailsListGroupedV2Page.tsx
- apps/public-docsite/src/pages/Controls/DetailsListPage/DetailsListLargeGroupedV2Page.doc.ts
- apps/public-docsite/src/pages/Controls/DetailsListPage/DetailsListLargeGroupedV2Page.tsx
- change/@fluentui-react-8cc34e48-8e55-4e4c-9ddb-f1f9cd3b0f3f.json
- packages/react-examples/src/react/DetailsList/DetailsList.GroupedV2.Example.tsx
- packages/react-examples/src/react/DetailsList/DetailsList.GroupedV2.Large.Example.tsx
- packages/react-examples/src/react/DetailsList/DetailsList.doc.tsx
- packages/react/etc/react.api.md
- packages/react/src/components/DetailsList/__snapshots__/DetailsListV2.test.tsx.snap
- packages/react/src/components/GroupedList/GroupedListV2.base.tsx
- packages/react/src/components/GroupedList/GroupedListV2.tsx
- packages/react/src/components/GroupedList/GroupedListV2.types.ts
The incorrect value for `aria-posinset` was set on GroupedListV2. When used in `DetailsList` `aria-rowindex` was not set and `aria-level` and `aria-posinset` were incorrectly set.
Set the correct `aria-posinset` and `aria-rowindex` values on GroupedListV2 depending on `role`.
Fixes #24795
> GroupedListV2: update aria-posinset and aria-rowindex

- change/@fluentui-react-164cba30-514e-4d2d-b6b7-d65448342050.json
- packages/react/src/components/Stack/Stack.tsx
PR #25397 introduced a way to scope the `Stack's` child selectors so they wouldn't be as expensive for performance when recalculating styles. However, it seems that, in the process, we restricted `Stack` to work only with `children` that are React elements. This PR fixes the issue so that `Stack` works with any element (with the same restrictions to using `enableScopedSelectors` still in place).
Fixes #25653
> fix: Making Stack properly render non-ReactElement children

- scripts/api-extractor/api-extractor.common.v-next.json
- scripts/tasks/api-extractor.ts
- scripts/tasks/ts.ts
- scripts/tasks/utils.spec.ts
- scripts/tasks/utils.ts
- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
- apis marked with `@internal` are physically removed from rollup-ed `index.d.ts`
- `api.md` generation works differently on CI and Local
- ci triggers it under the hood as part of `just-scripts build` 
- locally one needs to execute `build:local` or `lage build --to`
- `api.md` generation needs all dependencies to have api generated
- no apis are physically removed from rollup-ed `index.d.ts` as that adds hard to reason about issues in user land
- will be replaced by lint rule  
- `api.md` generation works the same on CI and Local
- `api.md` generation doesn't need to to generate apis for dependencies 
Replaces https://github.com/microsoft/fluentui/pull/23369
Closes https://github.com/microsoft/fluentui/issues/19360
💡 Note that this PR was merged after the declared followup. 
**Why?** …
> feat(scripts): remove @internal stripping and enable no deps build needed for api generation

- change/@fluentui-react-components-b533a13e-c80c-4f9f-a244-f2f6670310b3.json
- change/@fluentui-react-infobutton-409e40d3-73fc-4a7f-8310-df1b2db9abc3.json
- packages/react-components/react-components/etc/react-components.unstable.api.md
- packages/react-components/react-components/package.json
- packages/react-components/react-components/src/unstable/index.ts
- packages/react-components/react-infobutton/README.md
- packages/react-components/react-infobutton/package.json
- packages/react-components/react-infobutton/src/stories/Infobutton/InfoButtonDescription.md
* Add `InfoButton` to unstable.
* Change `react-infobutton` to public.
* Update documentation to being unstable.
> feat(react-components): Add InfoButton to unstable exports

- .github/CODEOWNERS
azure-themes has an outdated codeowner
azure-themes has updated codeowners
> update azure-theme codeowners

- change/@fluentui-react-combobox-b89a40be-4811-4450-b226-2355943843f7.json
- packages/react-components/react-combobox/src/stories/Dropdown/DropdownAccessibility.md
- packages/react-components/react-combobox/src/stories/Dropdown/DropdownBestPractices.md
- packages/react-components/react-combobox/src/stories/Dropdown/index.stories.tsx
Related to #24917
This adds a set of accessibility Do's/Don'ts to the Dropdown docs page, immediately after Best Practices, and links to the full spec page. The link URLs themselves depend on the related spec PR being merged first.
> feat: Dropdown a11y overview section

- change/@fluentui-react-21d08d17-38f6-4bdf-8d0e-383125edda19.json
- packages/react/src/components/FloatingPicker/BaseFloatingPicker.tsx
- packages/react/src/components/FloatingPicker/Suggestions/SuggestionsCore.tsx
Fixes #25538
Previously, the FloatingPeoplePicker had this role structure:
- list
- listitem
- option
- listitem
- option
- etc.
We want just a plain:
- listbox
- option
- option
- etc.
The `option` role already comes from the `SuggestionsItem` used internally, so this PR updates the floating control to just wrap SuggestionsItems in a `listbox` with no list/listitem roles.
> fix: FloatingPeoplePicker roles should be listbox/option

- change/@fluentui-react-bfd757de-4aad-4e5a-a85d-943c1e0b6859.json
- packages/react/etc/react.api.md
- packages/react/src/components/pickers/BasePicker.tsx
- packages/react/src/components/pickers/Suggestions/SuggestionsController.ts
Fixes #25438
The `resultsMaximumNumber` prop should limit the number of items present in the picker, even if there are more matching items for a given search string.
Currently, `resultsMaximumNumber` limits the number of items displayed for mouse users, but still allows arrow keys to access the full set of matching options.
This PR makes the following changes to fix that:
- The SuggestionsController now accepts a `maxCount` argument in its `updateSuggestions`. This keeps the 0-length check and resolving selectedIndex vs. maxCount in one place
- When BasePicker calls SuggestionsController's `updateSuggestions`, it passes in `resultsMaximumNumber` as the maxCount
The limited suggestions array needs to be reflected within SuggestionsController because that is where the …
> fix: Pickers limit keyboard nav to resultsMaximumNumber

- change/@fluentui-react-charting-ccfd96da-8e65-4550-b18b-3c45ca241de3.json
- packages/react-charting/src/components/DonutChart/DonutChart.base.tsx
Cannot focus arcs in donut chart using tab key
Can focus arcs in donut chart using tab key
> Allow focus navigation with tab key in donut chart

- change/@fluentui-react-badge-b015aa83-a8a1-4d2d-b21e-6c043231e03f.json
- packages/react-components/react-avatar/stories/Avatar/AvatarBadgeIcon.stories.tsx
- packages/react-components/react-avatar/stories/Avatar/index.stories.tsx
- packages/react-components/react-badge/src/components/PresenceBadge/presenceIcons.ts
- packages/react-components/react-badge/src/components/PresenceBadge/usePresenceBadge.tsx
The icons used in `PresenceBadge` cannot be overridden by the user, not even when overriding the `icon` slot.
The icons used in `PresenceBadge` are now only used by default but can be overridden by the user through the `icon` slot.
> fix: Allow PresenceBadge's icon to be overridden by the user

- .github/PULL_REQUEST_TEMPLATE.md
This PR updates the PR Template so that it reads `## Previous Behavior` instead of `## Current Behavior` when referring to the behavior that existed before the changes in the PR. This makes it less ambiguous as `Current` could mean the behavior before or after the PR depending on how it's used.
> chore: Updating Pull Request Template

- change/@fluentui-react-theme-6b37e9cc-8f6e-4c94-b79d-d42e1bddab74.json
- packages/react-components/react-theme/src/alias/darkColorPalette.ts
- packages/react-components/react-theme/src/alias/highContrastColorPalette.ts
- packages/react-components/react-theme/src/alias/lightColorPalette.ts
- packages/react-components/react-theme/src/alias/teamsDarkColorPalette.ts
A few `.reduce` loops do unnecessary work that increases the runtime when merging objects
The loops have been updated to mutate `acc` rather than return a new object, which avoids the need to iterate over all existing keys of `acc`.
Fixes #23633
> Fixes #23633 - Use Object.assign to reduce loop length

- scripts/storybook/utils.js
By default [recursive creation](https://nodejs.org/api/fs.html#fsmkdirsyncpath-options) is not enabled. The path being created is `dist/out-tsc`. In nix systems this seems to work even without `recursive`, however if the `dist` folder does not exist on windows this call will fail:
```shell
Error: ENOENT: no such file or directory, mkdir '/home/lingga/fluentui/dist/out-tsc'
at Object.mkdirSync (node:fs:1349:3)
at loadWorkspaceAddon (/home/lingga/fluentui/scripts/storybook/utils.js:108:8)
at Object.<anonymous> (/home/lingga/fluentui/.storybook/main.js:52:5)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load …
```
> fix(loadWorkspaceAddon): Create dist path recursively

- change/@fluentui-react-table-6c92019b-b4d2-4482-bf0c-e3564c2de0f0.json
- packages/react-components/react-table/etc/react-table.api.md
- packages/react-components/react-table/src/components/TableCell/TableCell.types.ts
- packages/react-components/react-table/src/components/TableCell/useTableCell.ts
- packages/react-components/react-table/src/components/TableCell/useTableCellStyles.ts
- packages/react-components/react-table/src/components/TableHeaderCell/useTableHeaderCellStyles.ts
- packages/react-components/react-table/src/components/TableRow/useTableRowStyles.ts
Table rows no longer determine the row height. The height styles are set of each table cell. This is actually necessary for flex layout so that the cells aren't smaller than the row.
Also fixes a bug where the header should have height 32px
Before
After
Addresses #25706
> fix: Table row height is determined by cells

- change/@fluentui-react-a50694ba-a465-4888-a8e1-81e560c8d563.json
- packages/react-examples/src/react/ComboBox/ComboBox.FreeInput.Example.tsx
- packages/react-examples/src/react/ComboBox/ComboBox.FreeSearch.Example.tsx
- packages/react-examples/src/react/ComboBox/ComboBox.doc.tsx
- packages/react/etc/react.api.md
- packages/react/src/components/ComboBox/ComboBox.test.tsx
- packages/react/src/components/ComboBox/ComboBox.tsx
- packages/react/src/components/ComboBox/ComboBox.types.ts
Resolves #19379
The current v8 combobox will never allow the user to enter text that does not match an existing option unless `allowFreeform=true`. This leaves out use cases where the combobox should not allow freeform text strings to be submitted, but allowing free user search while open/focused is still desired.
This also addresses the many quirks around autocomplete without allowFreeform.
If `allowFreeInput` is set to `true`, ComboBox allows freeform typing and backspace within the input. When the field is blurred, the value resets to the last selected value, if the string does not match an option. This matches the current behavior of the field if you type with `allowFreeform=false` without opening the listbox for the first time -- the only time free typing was allowed previously. …
> feat: add allowFreeInput to v8 ComboBox to allow typing while the combobox is in focus

- change/@fluentui-react-overflow-d916857c-b536-467d-ba22-cdd6246254c2.json
- packages/react-components/react-overflow/src/Overflow.cy.tsx
- We have been getting intermittent CI failures with a specific `Overflow` cypress test (`should notify group visibility changes correctly`).
- Examples: 
- https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=274551&view=logs&j=be0e6c0b-16d6-5408-4b39-461952619dc9&t=95e57134-5ddb-52ed-4fd2-92e8f59f6f0f
- https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=275173&view=logs&j=be0e6c0b-16d6-5408-4b39-461952619dc9&t=95e57134-5ddb-52ed-4fd2-92e8f59f6f0f
- removes a test with no assertion which seems to be the root cause of the intermittent CI failures. This removed line is trying to select a Divider that is **NOT** supposed to exist (the line after it asserting that it shouldn't exist confirms this) which is why cypress keeps timing out since it's looking …
> fix(react-overflow): Remove cypress test line causing intermittent CI failures

- change/@fluentui-react-positioning-a44227d8-ace2-477c-98b6-7b239f164aaa.json
- change/@fluentui-react-theme-sass-1f5563cb-f045-4787-ace7-3c2f1f6c51cb.json
- change/@fluentui-react-utilities-9077d172-d3c7-4615-b176-4696e60a97c4.json
- packages/react-components/react-positioning/.npmignore
- packages/react-components/react-theme-sass/.npmignore
- packages/react-components/react-utilities/.npmignore
- Runs `migrate-converged-pkg` which reflects updates made in #24458.
- Moves stories to `stories/` folder in the root of the package.
- Collocates any e2e tests with the component implementation and jest tests.
- removes `common/` folder and moves contents to new `testing/` folder 
- adds `docs/` folder to package root.
- Part of #24129
> chore(react-positioning, theme-sass, utilities): migrate to new package structure

- change/@fluentui-react-table-32493410-892f-4f58-95e3-f38c054ae05c.json
- packages/react-components/react-table/src/hooks/types.ts
- packages/react-components/react-table/src/hooks/useSelection.test.ts
- packages/react-components/react-table/src/hooks/useSelection.ts
- packages/react-components/react-table/stories/Table/MultipleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/Table/SingleSelectControlled.stories.tsx
Modifies `onSelectionChange` to be more consistent with component change callbacks since it will be used in `DataGrid`
```ts
useSelection({
selectionMode: 'multiselect',
onSelectionChange: (e, newSelectedItems) =>
setSelectedRows(newSelectedItems),
}),
```
```ts
useSelection({
selectionMode: 'multiselect',
onSelectionChange: (e, data) => 
setSelectedRows(data.selectedItems),
}),
```
> BREAKING(useTable): `onSelectionChange` returns data object

- change/@fluentui-react-menu-13a26a1d-d2f6-4a55-9113-a1a7996739d1.json
- packages/react-components/react-menu/src/components/MenuDivider/useMenuDividerStyles.ts
Updates the border style of `MenuDivider` to use `strokeWidthThin` design token
* Fixes #25097
> fix: MenuDivider thickness should be `strokeWidthThin`

- change/@fluentui-react-table-4fd95b09-8d7a-4443-ab87-47802ed452f6.json
- packages/react-components/react-table/src/components/TableCell/useTableCellStyles.ts
- packages/react-components/react-table/src/components/TableCellLayout/useTableCellLayoutStyles.ts
- packages/react-components/react-table/src/components/TableRow/useTableRowStyles.ts
- packages/react-components/react-table/src/components/TableSelectionCell/useTableSelectionCellStyles.ts
- packages/react-components/react-table/stories/Table/CellActions.stories.tsx
- packages/react-components/react-table/stories/Table/PrimaryCell.stories.tsx
Various design fixes to Table primitives
- Cell action buttons should be filled on hover/pressed in examples
- Icons in primary cells should be 24px
- Subtitle text in primary cell should be caption 1
- Checkbox/radio cell should not have gray hover state when row is selected
- Circle inside selected radio should match sizing in Radio component
- Focus state should match createFocusOutlineStyle (black border instead of blue)
* Addresses #25706
> fix: Various design fixes to Table components

- change/@fluentui-react-charting-35e5b80b-88cd-4032-9bfe-42cdeca3337c.json
- packages/react-charting/src/components/DonutChart/Arc/Arc.tsx
- packages/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap
- packages/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
- packages/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap
- packages/react-charting/src/components/HeatMapChart/HeatMapChart.base.tsx
- packages/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap
- packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx
- packages/react-charting/src/components/HorizontalBarChart/__snapshots__/HorizontalBarChart.test.tsx.snap
- packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
- packages/react-charting/src/components/StackedBarChart/StackedBarChart.base.tsx
- packages/react-charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap
- packages/react-charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap
- packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx
- packages/react-charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap
- packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx
- packages/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChart.test.tsx.snap
In browse mode, screen reader announces same information for all focusable SVG shapes
In browse mode, screen reader announces respective information for the SVG shapes
> Fix wrong narration in browse mode

- .codesandbox/ci.json
- Codesandbox CI constantly fails for v7 PRs because #25618 introduced a dependency (`d3-scale@4.0.2`) which explicitly requires the use of a `node` version >= 12. 
```
yarn install v1.22.17
$ node ./scripts/use-yarn-please.js
[1/4] Resolving packages...
[2/4] Fetching packages...
error d3-scale@4.0.2: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
{ Error: Process rejected with status code 1
at ChildProcess.<anonymous> (/app/dist/utils/exec.js:20:27)
at ChildProcess.emit (events.js:198:13)
at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12) code: 1 }
```
**Codesandbox error**: …
> fix(v7 codesandbox): fix broken codesandbox CI 

- change/@fluentui-react-combobox-9a7d0c49-3100-4295-a3c5-4a8a3095fc80.json
- change/@fluentui-react-input-6fe37858-c97b-497a-97e4-5e16767361bf.json
- change/@fluentui-react-select-5be7fa6b-231e-4073-a8ee-b288f6d0e4ef.json
- change/@fluentui-react-textarea-b18f2623-cf8d-4372-a75d-ceb940e78e1e.json
- packages/react-components/react-combobox/src/components/Combobox/useComboboxStyles.ts
- packages/react-components/react-combobox/src/components/Dropdown/useDropdownStyles.ts
- packages/react-components/react-input/src/components/Input/useInputStyles.ts
- packages/react-components/react-select/src/components/Select/useSelectStyles.ts
- packages/react-components/react-textarea/src/components/Textarea/useTextareaStyles.ts
There was no typography token for `fontSizeBase400` and regular weight, so it was manually specified in several components.
Replace uses of `fontSizeBase400` with `typographyStyles.body2`
* Fixes #23617
> chore: Replace use of fontSize tokens with typographyStyles in input controls

- change/@fluentui-react-4e35ca8e-0664-4585-9bba-af7c3bd689eb.json
- packages/react/src/components/Tooltip/TooltipHost.base.tsx
- packages/react/src/components/Tooltip/TooltipHost.test.tsx
TooltipHost calls `onRenderContent` to generate the content used for aria-describedby, but does not pass in props or a default render function. 
It appears that this was a longstanding bug, but a recent PR #24037 caused it to be hit in more cases.
TooltipHost passes props and a default render function when it calls the Tooltip's `onRenderContent` function to generate the description.
* Fixes #24107
> [v8] fix: TooltipHost calls onRenderContent without passing props

- change/@fluentui-react-f52f6ff4-6134-461e-adfb-0138a31c60d8.json
- packages/react/src/components/pickers/BasePicker.tsx
When setting the `itemLimit` on a picker to 0 and erasing all the items will cause an infinite loop.
When setting a `itemLimit` of 0 on the picker will not cause an infinite loop.
> I was unable to create a test for this. Even before my change I couldn't get a test to fail on this.
Fixes #25550
> fix: Picker infinite loop on itemLimit=0 (#25550)

- change/@fluentui-react-popover-b28938cd-f8d9-4551-8695-cead5e5bbff3.json
- packages/react-components/react-popover/src/components/Popover/usePopover.ts
Popover only invokes `onOpenChange` when the state is flipped (true -> false or vice versa).
It seems to be the correct thing to do, however it breaks in this example: https://codesandbox.io/s/determined-lalande-75x1i7?file=/example.tsx
Popover has controlled `open` state because the example tries to keep it open when pressing ESC key.
But after pressing ESC, Popover cannot be closed by clicking outside of it.
Popover uses `useControllableState`, which is not able to sync the prev state in callback setter with user state (#25748).
When pressing ESC, the user state is `open=true`, but the internal state in `useControllableState` is still `open=false`. Therefore when clicking outside, both the current and next state is `open=false`, and `onOpenChange` is not invoked. 
Always invoke …
> fix(Popover): always invoke onOpenChange regardless of prev state 

- packages/react-components/react-tree/etc/react-tree.api.md
- packages/react-components/react-tree/src/TreeItemLayout.ts
- packages/react-components/react-tree/src/components/TreeItemLayout/TreeItemLayout.test.tsx
- packages/react-components/react-tree/src/components/TreeItemLayout/TreeItemLayout.tsx
- packages/react-components/react-tree/src/components/TreeItemLayout/TreeItemLayout.types.ts
- packages/react-components/react-tree/src/components/TreeItemLayout/__snapshots__/TreeItemLayout.test.tsx.snap
- packages/react-components/react-tree/src/components/TreeItemLayout/index.ts
- packages/react-components/react-tree/src/components/TreeItemLayout/renderTreeItemLayout.tsx
- packages/react-components/react-tree/src/components/TreeItemLayout/useTreeItemLayout.ts
- packages/react-components/react-tree/src/components/TreeItemLayout/useTreeItemLayoutStyles.ts
- packages/react-components/react-tree/src/index.ts
Scaffolds `TreeItemLayout` component using
```shell
yarn create-component
```
> chore(react-tree): scaffolds TreeItemLayout

- packages/react-components/react-table/stories/DataGrid/KeyboardNavigation.stories.tsx
- packages/react-components/react-table/stories/DataGrid/MultipleSelect.stories.tsx
- packages/react-components/react-table/stories/DataGrid/MultipleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SelectionAppearance.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SingleSelect.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SingleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/DataGrid/Sort.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SortControlled.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SubtleSelection.stories.tsx
- packages/react-components/react-table/stories/DataGrid/index.stories.tsx
Adds usages examples scenarios and props
> docs: Add examples for DataGrid

- change/@fluentui-react-table-393b87fd-7546-484a-8f7f-c8bc7d2d6b08.json
- packages/react-components/react-table/src/components/Table/Table.types.ts
- packages/react-components/react-table/src/components/TableCellLayout/TableCellLayout.types.ts
- packages/react-components/react-table/src/components/TableHeaderCell/TableHeaderCell.types.ts
- packages/react-components/react-table/src/components/TableRow/TableRow.types.ts
- packages/react-components/react-table/src/components/TableSelectionCell/TableSelectionCell.types.ts
- packages/react-components/react-table/stories/Table/CellActions.stories.tsx
- packages/react-components/react-table/stories/Table/CellNavigation.stories.tsx
- packages/react-components/react-table/stories/Table/DataGrid.stories.tsx
- packages/react-components/react-table/stories/Table/MultipleSelect.stories.tsx
- packages/react-components/react-table/stories/Table/MultipleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/Table/NonNativeElements.stories.tsx
- packages/react-components/react-table/stories/Table/PrimaryCell.stories.tsx
- packages/react-components/react-table/stories/Table/SingleSelect.stories.tsx
- packages/react-components/react-table/stories/Table/SingleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/Table/Sort.stories.tsx
- packages/react-components/react-table/stories/Table/SortControlled.stories.tsx
- packages/react-components/react-table/stories/Table/SubtleSelection.stories.tsx
- packages/react-components/react-table/stories/Table/TableDescription.md
- packages/react-components/react-table/stories/Table/index.stories.tsx
- Cleanup docstrings
- Adds main component description
- Adds descriptions to relevant examples
- Adds subcomponent props
- Reorders examples
> docs: Improves `Table` documentation

- tools/generators/dependency-mismatch/index.spec.ts
- tools/generators/dependency-mismatch/index.ts
- tools/utils.ts
> fix(tools): bump northstar packages v9 deps on dep mismatch resolution

- apps/vr-tests-react-components/src/stories/AvatarGroup.stories.tsx
- change/@fluentui-react-avatar-10737738-e331-4d53-9838-22a57b7fbd90.json
- packages/react-components/react-avatar/src/components/AvatarGroupItem/useAvatarGroupItemStyles.ts
> fix(react-avatar): AvatarGroup's pie layout places inline items correctly in rtl

- rfcs/react-components/components/recipes.md
This PR updates the recipes rfc to improve its documentation and explain with more detail what the chosen solution entails.
* Fixes #25515
> docs(rfcs): Update recipes rfc with chosen option and add more details

- change/@fluentui-react-5ad3027a-0dd8-4a63-bb67-aa14172f043f.json
- packages/react/src/components/DetailsList/DetailsRow.base.tsx
Passing `data-selection-disabled` to `DetailsRow` was being overridden by internal behavior.
Passing `data-selection-disabled` to `DetailsRow` is now respected instead of being overridden by internal behavior.
* Fixes #25824
> fix: Allow data-selection-disabled to be respected by DetailsRow

- change/@fluentui-react-button-9d2cbb68-9215-4318-ad2a-99ab636a11cd.json
- change/@fluentui-react-components-b61e9cf0-13d7-4738-883a-48c34d57d26e.json
- change/@fluentui-react-tabster-d0eee5e7-8825-41d7-a50f-2737705f2e09.json
- packages/react-components/react-button/src/components/Button/useButtonStyles.ts
- packages/react-components/react-components/etc/react-components.api.md
- packages/react-components/react-components/src/index.ts
- packages/react-components/react-tabster/etc/react-tabster.api.md
- packages/react-components/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts
Fixes #25353.
This PR refactors `Button` component to use [`makeResetStyles`](https://griffel.js.org/react/api/make-reset-styles). The goal is to improve layouting performance by reducing an amount of applied CSS classes to an element.
The goal is to apply this change to all components (_I am working on RFC to explain details_), for simplicity:
- all styles that should be in base (default state) should be defined with `makeResetStyles`
- all styles for overrides (permutations for a component i.e. `disabled`, `appearance`) are defined with `makeStyles`
- Only one classname generated by `makeResetStyles` can be applied to a slot
- `makeResetStyles` allows to use CSS shorthands
- `makeResetStyles` supports [AOT](https://griffel.js.org/react/ahead-of-time-compilation/introduction) and [CSS …
> chore: refactor styles for Button

- change/@fluentui-react-charting-806735ad-55f4-4170-a545-c3c5a84e8701.json
- packages/react-charting/src/components/AreaChart/AreaChart.base.tsx
- packages/react-charting/src/components/AreaChart/AreaChart.test.tsx
- packages/react-charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap
Having single point in the area chart does not render the point
Area chart now supports having a single point in the chart.
* Fixes #
> Support single point in area chart

- apps/ssr-tests-v9/src/test.ts
- apps/ssr-tests-v9/src/utils/visitPage.test.ts
- apps/ssr-tests-v9/src/utils/visitPage.ts
We have intermittent errors in CI related to `ssr-tests-v9` and navigation. The error is related to `.goto()`, this PR decreases a timeout (that page should load in 10 seconds for sure) and adds retries. We had a similar problem before with a browser start process, so this change _might_ solve it.
---
If the error will stay, we will need to enable debugging from Puppeteer and get more logs.
> chore: add retries for navigation in ssr-tests-v9

- .storybook/main.js
- .storybook/preview.js
- change/@fluentui-react-menu-44cbedde-a909-4161-9fc6-2431911a35a0.json
- package.json
- packages/react-components/react-menu/stories/Menu/MenuDescription.md
- yarn.lock
since URLs are hosted inside of an iframe, any anchor tag is going to be relative to that iframe...just doesn't work.
with addon-links, and the decorator, we can use link in markdown, or in examples via buttons or anchor tags. 
```
<a href="#" data-sb-kind="components-button-menubutton--default">MenuButton</a>
<button data-sb-kind="components-button-menubutton--default">MenuButton</button>
// note that we use data-sb-kind and not data-sb-story
```
https://storybook.js.org/addons/@storybook/addon-links
> support cross story linking and create example in Menu story

- change/@fluentui-react-a5c36bc6-3f4e-4de1-91a8-8d2407288c7c.json
- packages/react/src/components/ComboBox/ComboBox.test.tsx
- packages/react/src/components/ComboBox/ComboBox.tsx
Passing `id` as part of a `ComboBoxOption` would not be respected, and it would instead be overridden by the automatically generated one.
Passing `id` as part of a `ComboBoxOption` is now respected over the automatically generated one. We made sure to propagate the correct value to `aria-activedescendant` when this happens. A test has been added to ensure this behavior is not broken in the future.
* Fixes #25857
> fix: Respecting user-provided ids in ComboBox options

- change/@fluentui-react-45e501d9-d10e-4a7f-af84-bcdb47113bb9.json
- packages/react/src/components/Slider/useSlider.ts
Using programmatic `focus` based on the `componentRef` of a `Slider` would not work correctly, trying and failing to focus on the non-interactive thumb.
Using programmatic `focus` based on the `componentRef` of a `Slider` now works correctly, focusing on the interactive slider-box as expected.
* Fixes #23627
> fix: Fixing Slider's programmatic focus

- change/@fluentui-react-toolbar-79a4ea5f-680e-49e7-a6ca-5348689f03d7.json
- packages/react-components/react-toolbar/src/components/ToolbarButton/ToolbarButton.tsx
Fixes: #25802 
The correct default appearance from `react-button` to be used for `ToolbarButton` is the subtle one which will respect the `pressed` and `hover` states.
> fix: Pressed and Hover states for toolbar buttons

- change/@fluentui-react-combobox-a26bff07-0272-455f-8037-654737c7b44d.json
- packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx
- packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx
Addresses an item in #25724
There was a bug in how the expand icon click interacted with close-on-blur -- it needs to not close on blur when clicking to close (which would cause it to close then open again), but should close on blur after clicking to open.
PR adds fix + test
> fix: react-combobox should close on blur after clicking expand icon

- change/@fluentui-react-combobox-9785fc76-eef9-4040-a5e7-31442cdb4644.json
- packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx
- packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx
Addresses one item of #25724
This was originally the intent, and was confirmed by the user study -- Combobox should open the popup when the user begins typing in the input.
> fix: Combobox v9 opens popup when typing in input

- change/@fluentui-react-596053a1-fb7a-4795-9268-88f2dd1fa249.json
- packages/react/src/components/SpinButton/SpinButton.styles.ts
- packages/react/src/components/SpinButton/__snapshots__/SpinButton.test.tsx.snap
In the past, the only way to change the focus state color was to know that a double class was used, and to know HOW to write styles that duplicated the className
```
isFocused && {
'&&:after': { borderColor: 'green' }
} 
```
Spin button focus was a bit duplicative and double classes were used for specificity. This change simplifies the styles, reduces the need for additional classes for specificity, and aligns the button with other inputs in high contrast mode.
> remove the unecessary extra specificity and styles in hover and focus styles

- apps/vr-tests-react-components/src/stories/Persona.stories.tsx
- change/@fluentui-react-persona-d51509e5-3996-4e3e-b326-3e4135b5b8e6.json
- packages/react-components/react-persona/src/components/Persona/usePersonaStyles.ts
Persona's text did not wrap when overflowing its container due to using `gridAutoColumns: max-content`.
Persona's text now wraps when overflowing its container.
* Related #25698 
* Fixes #25698
> fix(react-persona): Make Persona's text wrap when overflowing its container

- change/@fluentui-react-4962bfe2-335e-4e07-8fc7-036ba5850f69.json
- packages/react/src/components/Dialog/DialogFooter.styles.ts
When having a button with an icon and a button without one in `DialogFooter`, the buttons would be misaligned.
When having a button with an icon and a button without one in `DialogFooter`, the buttons are no longer misaligned.
* Fixes #25873
> fix: Make Buttons align correctly when put inside of DialogFooter

- README.md
It's only a reference URL
EP04: Foundational APIs was sending viewers to **YouTube** to watch the video
EP04: Foundational APIs is sending viewers to **Learn** to watch the video
> Update EP04 video link

- change/@fluentui-react-components-dbb0daa2-367e-4700-8822-0755f7033c6c.json
- change/@fluentui-react-menu-0855b482-9526-40c3-9209-9f961f2e8e1b.json
- packages/react-components/react-components/src/index.ts
- packages/react-components/react-menu/etc/react-menu.api.md
- packages/react-components/react-menu/src/components/Menu/Menu.types.ts
- packages/react-components/react-menu/src/components/Menu/useMenu.tsx
- packages/react-components/react-menu/src/components/Menu/useMenuContextValues.test.tsx
- packages/react-components/react-menu/src/components/Menu/useMenuContextValues.ts
- packages/react-components/react-menu/src/components/MenuGroup/useMenuGroup.ts
- packages/react-components/react-menu/src/components/MenuList/MenuList.types.ts
- packages/react-components/react-menu/src/components/MenuList/useMenuList.test.ts
- packages/react-components/react-menu/src/components/MenuList/useMenuList.ts
- packages/react-components/react-menu/src/components/MenuList/useMenuListContextValues.ts
- packages/react-components/react-menu/src/contexts/menuContext.ts
- packages/react-components/react-menu/src/contexts/menuListContext.tsx
- packages/react-components/react-menu/src/index.ts
- packages/react-components/react-menu/src/testing/mockUseMenuContext.ts
1. Removes the spreading of `props` into `MenuList` state declaration. 
2. Updates types accordingly, deprecating unnecessary properties passing down for the state
3. deprecates unused type `UninitializedMenuListState`
Together with type casting, spreading props at state is not ideal as it obscures what properties are actually required to maintain the proper usage of internal state, therefore spreading props at state should be avoided.
> chore(react-menu): removes prop spreading on MenuList state

- change/@fluentui-react-utilities-7a1e6e7c-966f-4296-8ebb-9852d61704e2.json
- packages/react-components/react-utilities/etc/react-utilities.api.md
- packages/react-components/react-utilities/src/index.ts
- packages/react-components/react-utilities/src/utils/index.ts
- packages/react-components/react-utilities/src/utils/isHTMLElement.ts
Adds new helper method `isHTMLElement` that verifies if a given `Node` is a valid `HTMLElement` by checking it's instance validity with current document (to ensure it works properly with iframes)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_realms
> feat(react-utilities): isHTMLElement helper function

- change/@fluentui-azure-themes-fe64290b-3f2d-41ad-9969-5a64dfabe50c.json
- packages/azure-themes/src/azure/AzureThemeDark.ts
- packages/azure-themes/src/azure/Constants.ts
- packages/azure-themes/src/azure/styles/ActionButton.styles.ts
- packages/react-examples/src/azure-themes/stories/Themes/Themes.stories.tsx
Removed border from rest & hover state
Reduce height to 36px
**rest**
**hovered**
**pressed**
**focus**
dark: rest, hover, pressed, focus
> 8.0 Azure Theme ActionButton style bug fix

- change/@fluentui-react-table-ce22b634-8d6d-4bbd-b632-7749310f0bf6.json
- packages/react-components/react-table/etc/react-table.api.md
- packages/react-components/react-table/src/components/DataGrid/DataGrid.types.ts
- packages/react-components/react-table/src/components/DataGrid/useDataGrid.ts
- packages/react-components/react-table/stories/DataGrid/CustomRowId.stories.tsx
- packages/react-components/react-table/stories/DataGrid/index.stories.tsx
Add the `getRowId` prop to the `DataGrid` component with usage example and documentation.
> feat: DataGrid supports custom row Ids

- change/@fluentui-react-combobox-701e29a2-ac8a-4be4-bfa7-44fb3466a96f.json
- packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx
- packages/react-components/react-combobox/src/components/Dropdown/Dropdown.test.tsx
- packages/react-components/react-combobox/src/components/Listbox/Listbox.test.tsx
- packages/react-components/react-combobox/src/components/Listbox/useListbox.ts
- packages/react-components/react-combobox/src/components/Option/__snapshots__/Option.test.tsx.snap
- packages/react-components/react-combobox/src/components/Option/useOption.tsx
Part of the changes in #25724
We currently use listbox/option for both single-select and mutli-select Combobox, Listbox, and Dropdown. Based on the usability study, menu/menuitemcheckbox semantics significantly improved screen reader usability for multiselect Combo/Dropdown, with no drawbacks.
Single-select keeps the listbox/option semantics, while multi-select uses menu/menuitemcheckbox. This change only affects screen reader (and SR + braille) users.
> feat: update Listbox and Option to use menu and menuitemcheckbox semantics for multiselect

- change/@fluentui-react-field-061c6b68-4b63-4471-9ed5-82dad697471e.json
- packages/react-components/react-field/docs/Migration.md
- packages/react-components/react-field/docs/Spec.md
The Field migration guide was part of Spec.md
Split out the migration guide to its own Migration.md file
* Epic #19627
> chore: Move Field migration guide to Migration.md

- apps/public-docsite-v9/src/Concepts/QuickStart.stories.mdx
Changed some language in our docs that were causing confusion around the state of Fluent v9 in strict mode. Original docs sounded like you had to turn off strict mode in your entire app to use v9 (which is a blocker for many adopters). 
The truth is that the issues in strict mode are mostly limited to react 18 (the SSR issue is 17/18 but almost fixed), and even in react 18, your app will still work, with the exception of the existing bugs.
> Change website language around strict mode

- .devops/templates/runpublishvrscreenshot.yml
- azure-pipelines.vrt-baseline.yml
- azure-pipelines.vrt-pr.yml
- Integrates `react-northstar` VR tests to run for baseline pipeline of new VR tool.
Part of #25078
> feat (CI): run react-northstar tests for baseline pipeline of VR tool

- azure-pipelines.vrt-baseline.yml
- PRs will now run `@fluentui/react-northstar` tests. Do not merge until #25922 is complete - once it's merged re-run PR pipeline for this
Part of #25922
> feat (CI): Enable VR Tool to run react-northstar tests for PRs

- packages/react-components/react-table/stories/Table/CellActions.stories.tsx
- packages/react-components/react-table/stories/Table/CellNavigation.stories.tsx
- packages/react-components/react-table/stories/Table/DataGrid.stories.tsx
- packages/react-components/react-table/stories/Table/Default.stories.tsx
- packages/react-components/react-table/stories/Table/MultipleSelect.stories.tsx
- packages/react-components/react-table/stories/Table/MultipleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/Table/NonNativeElements.stories.tsx
- packages/react-components/react-table/stories/Table/PrimaryCell.stories.tsx
- packages/react-components/react-table/stories/Table/SingleSelect.stories.tsx
- packages/react-components/react-table/stories/Table/SingleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/Table/SizeExtraSmall.stories.tsx
- packages/react-components/react-table/stories/Table/SizeSmall.stories.tsx
- packages/react-components/react-table/stories/Table/Sort.stories.tsx
- packages/react-components/react-table/stories/Table/SortControlled.stories.tsx
- packages/react-components/react-table/stories/Table/SubtleSelection.stories.tsx
- packages/react-components/react-table/stories/Table/Virtualization.stories.tsx
- Add `e.preventDefault` for some spacebar selection examples that were missing
- Adds aria-labels to table examples
- Adds `aria-rowindex` and `aria-rowcount` to virtualized table example
> docs: a11y fixes for `Table` examples

- change/@fluentui-react-table-6f2d8d51-2a06-4d30-84bb-01051233a5fe.json
- packages/react-components/react-table/etc/react-table.api.md
- packages/react-components/react-table/src/components/DataGridRow/DataGridRow.types.ts
The `children` type from `ComponentProps` was being intersected with the explicit `children` type declared in props, so the expected type was actually `string & CellRenderFunction | false & CellRenderFunction...`
The `children` type can only be of `CellRenderFunction`
> fix(DataGridRow): `children` type should only be render function

- change/@fluentui-react-card-9d79f524-9dc5-44c5-ab24-44afd1ece6ff.json
- packages/react-components/react-card/src/components/Card/useCard.ts
- packages/react-components/react-card/src/components/Card/useCardSelectable.ts
- packages/react-components/react-card/src/components/CardPreview/useCardPreview.ts
- packages/react-components/react-card/stories/Card/CardSelectableIndicator.stories.tsx
Card had support for some a11y attributes, and this PR adds also `aria-describedby` to this list. By default, we try to guess and correctly set the accessible tags to the selectable cards.
> fix: remove unnecessary selectable ref and add support for aria-describedby on card preview

- package.json
- yarn.lock
Bump version of storybook-addon-export-to-codesandbox. This fixes an issue with conditional rendering of a React hook, causing the storybook to crash.
More details: https://github.com/microsoft/fluentui-storybook-addons/pull/22
> chore: upgrade storybook-addon-export-to-codesandbox to patch version

- packages/react-examples/src/react/Modal/Modal.Basic.Example.tsx
- packages/react-examples/src/react/Modal/Modal.Modeless.Example.tsx
Resolves an ADO bug, small example-content-only tag fix.
> fix: v8 Modal examples use heading tags

- change/@fluentui-react-table-8a90996b-247e-47ef-9827-afa7c5daee47.json
- packages/react-components/react-table/stories/Table/CellNavigation.stories.tsx
- packages/react-components/react-table/stories/Table/DataGrid.stories.tsx
- packages/react-components/react-table/stories/Table/MultipleSelect.stories.tsx
- packages/react-components/react-table/stories/Table/MultipleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/Table/SingleSelect.stories.tsx
- packages/react-components/react-table/stories/Table/SingleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/Table/Sort.stories.tsx
- packages/react-components/react-table/stories/Table/SortControlled.stories.tsx
- packages/react-components/react-table/stories/Table/SubtleSelection.stories.tsx
- packages/react-components/react-table/stories/Table/TableDescription.md
- packages/react-components/react-table/stories/Table/Virtualization.stories.tsx
All Table examples will navigate with tab. Added warnings to keyboard navigation examples that any keyboard navigation on the primitives must use the `role="grid"` pattern.
> docs: Table examples generally navigate with tab

- change/@fluentui-react-3a53c3c8-e896-4cd0-9227-2979ec7a93c7.json
- packages/react/src/components/ComboBox/ComboBox.tsx
The first option in multiselect `Comboboxes` had a hover style applied that wasn't applied to any other option.
The first option in multiselect `Comboboxes` no longer has a unique hover style applied.
* Fixes #23645
> fix: Removing weird hover style on first option in multiselect Comboboxes

- change/@fluentui-react-table-1c69ba37-4433-4fe5-917e-0580a0f84821.json
- packages/react-components/react-table/src/components/TableHeaderCell/useTableHeaderCell.tsx
- packages/react-components/react-table/src/components/TableHeaderCell/useTableHeaderCellStyles.ts
- packages/react-components/react-table/src/components/TableSelectionCell/useTableSelectionCellStyles.ts
Focus outlines can be different colours on browsers (i.e. blue in Firefox)
Focus outlines will follow design spec
> fix: Explicit focus outline for TableHeaderCell and TableSelectionCell

- packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx
- packages/fluentui/react-northstar/src/components/Dropdown/DropdownSelectedItem.tsx
- packages/fluentui/react-northstar/test/specs/components/Dropdown/Dropdown-test.tsx
`disabled`  prop wasn't being forwarded to `DropdownSelectedItem`  therefore it was interactive while the dropdown itself was `disabled`. To fix it we are passing it forward and preventing the callbacks to be invoked when disabled.
> fix: prevent selected items to be interactive when dropdown is disabled

- apps/vr-tests-react-components/src/stories/Avatar.stories.tsx
- change/@fluentui-react-avatar-34fac678-ed67-41e8-b561-e6b3e88ada07.json
- packages/react-components/react-avatar/src/components/Avatar/Avatar.test.tsx
- packages/react-components/react-avatar/src/components/Avatar/useAvatar.tsx
When an Avatar is displaying only an image and isn't displaying initials, it also renders the icon behind the image. This was done to ensure that something is displayed while the image is loading, or if the image fails to load. However, it causes performance issues by always rendering both the icon and image.
These are the results when running the perf tests from @ling1726's PR #25776. Note: **⭐ AvatarTestV9.perf.tsx** is the one testing the scenario in the bug; the others are for comparison.
| Example                     | avg       | description                               |
| --------------------------- | --------- | ----------------------------------------- |
| ⭐ AvatarTestV9.perf.tsx   | 🟥 58.84  | v9 Avatar with `image`                    |
| AvatarTestV9NoIcon.perf.tsx | 🟩 37.93 …
> fix: Avatar shouldn't render an icon when displaying an image

- change/@fluentui-react-36e9af14-473b-452c-8618-929be8d3f6a4.json
- packages/react-examples/src/react/DetailsList/DetailsList.Grouped.Example.tsx
- packages/react/src/components/DetailsList/DetailsHeader.base.tsx
- packages/react/src/components/DetailsList/DetailsRow.base.tsx
Fixes [15721](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15721)
Previously, we fully removed the header cell with the collapse all button when the `collapseAllVisibility` was set to hidden, which resulted in an incorrect number of column headers for the content, as well as misaligned content cells, both visually and semantically.
Now when `collapseAllVisibility` is hidden, the header's collapse all button is gone, but an empty cell is present to ensure the correct number of column headers, and to have the column headers line up with their columns.
Cells in each row are also given the correct spacing and empty cells.
> fix: Grouped Detailslist's collapseAllVisibility=hidden needs correct spacers and role=cell nodes

- change/@fluentui-react-8cfa6416-9eea-4573-8625-3a956ca1b0a7.json
- packages/react/src/components/Autofill/Autofill.tsx
Fixes [14918](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/14918)
It appears iOS VoiceOver's cursor jumps to an input based on changing the selection range, even if focus is not set to the input. In practice, that meant that it was impossible to move the VO cursor away Autofill with a selection, since it would update and re-set the selection range on blur, pulling the VO cursor back to the input.
This fix only allows the selectionRange to be set when the input is in focus. This should not make a practical difference outside of VoiceOver, since the visual selection and keyboard interaction only take show up when in focus.
> fix: Autofill only sets selectionRange when in focus

- packages/fluentui/CHANGELOG.md
- packages/fluentui/accessibility/src/behaviors/Carousel/carouselBehavior.ts
- packages/fluentui/accessibility/test/behaviors/caroselBehavior-test.tsx
- packages/fluentui/react-northstar/src/components/Carousel/Carousel.tsx
- packages/fluentui/react-northstar/test/specs/components/Carousel/Carousel-test.tsx
When carousel component is used inside the focus zone, then navigation go into paddle which is not visible in the UI. 
Paddle is hidden only with CSS visibility prop:
https://www.w3schools.com/cssref/pr_class_visibility.php  
Focus zone(FZ) has function isElementVisible() in the "focusUtilities.js", but this function doesn't evaluate CSS visibility prop. 
But FZ has attribute  'data-is-visible' which should indicate if element is visible for navigation or not. 
Adding the attribute to make element not visible for FZ. 
there was not  'data-is-visible' attribute
there is 'data-is-visible=false' attribute added when paddle is hidden
> fix: Carousel fix for FZ - Adding data-is-visible prop

- change/@fluentui-react-checkbox-a337788c-cf01-4300-b7e9-9cfccba53f4c.json
- change/@fluentui-react-radio-3244b173-95d4-4d07-aaf7-21e05ff4234a.json
- packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts
- packages/react-components/react-radio/src/components/Radio/useRadioStyles.ts
Checkbox and Radio's styles include all of the styles for the checked, hover, etc. states in the base styles, and use CSS selectors to conditionally apply the styles.
* This results in a large number of classes being added to the default checkbox, because Griffel styles use a separate class for each combination of selector & property. As shown below, there are a total of **154** css classes across all of Checkbox's slots.
* This affects performance because chromium's css performance degrades with the number of classes.
Use Griffel's `makeResetStyles` to combine all of the base styles for each of Checkbox and Radio's slots into a single CSS class. Also, merge the styles for the default state into the base styles (`size: medium`, `labelPosition: after`). 
* For Checkbox, this results in an …
> chore: Update Checkbox and Radio to use griffel reset styles

- change/@fluentui-react-checkbox-f94ea0be-f27d-401f-9810-fdd8c96b2251.json
- packages/react-components/react-checkbox/bundle-size/Checkbox.fixture.js
- packages/react-components/react-checkbox/package.json
Checkbox was missing a bundle size test.
Add react-checkbox/bundle-size/Checkbox.fixture.js to enable bundle size regression testing in PRs.
> chore: Add Checkbox bundle size test

- change/@fluentui-react-charting-f2e133de-6ad2-4585-8f2b-a9115bfa9341.json
- packages/react-charting/src/components/AreaChart/AreaChart.base.tsx
- packages/react-charting/src/components/DonutChart/DonutChart.base.tsx
- packages/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
- packages/react-charting/src/components/HeatMapChart/HeatMapChart.base.tsx
- packages/react-charting/src/components/LineChart/LineChart.base.tsx
- packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
- packages/react-charting/src/components/StackedBarChart/StackedBarChart.base.tsx
- packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx
- packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx
The callout stays visible when user hovers over legends
The callout hides when user hovers over legends
> Hide callout on legend hover

- apps/vr-tests-react-components/.storybook/preview.js
- change/@fluentui-react-menu-2cb39518-350f-471e-aeac-f4077d6fe085.json
- change/@fluentui-react-popover-0462ea09-ba7e-4205-a8e5-17e62603e5de.json
- change/@fluentui-react-provider-f154ffd0-53f9-4a00-98fd-60f928e80590.json
- packages/react-components/react-menu/src/components/MenuPopover/useMenuPopoverStyles.ts
- packages/react-components/react-popover/src/components/PopoverSurface/usePopoverSurfaceStyles.ts
- packages/react-components/react-provider/etc/react-provider.api.md
- packages/react-components/react-provider/src/components/FluentProvider/FluentProvider.types.ts
- packages/react-components/react-provider/src/components/FluentProvider/useFluentProvider.ts
- packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderContextValues.test.ts
- packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderContextValues.ts
- packages/react-components/react-provider/stories/Provider/FluentProviderApplyStylesToPortals.stories.tsx
- packages/react-components/react-provider/stories/Provider/FluentProviderFrame.stories.tsx
- packages/react-components/react-provider/stories/Provider/FluentProviderPassStylesToPortals.stories.tsx
- packages/react-components/react-provider/stories/Provider/index.stories.tsx
Fixes #25528.
This PR adds `applyStylesToPortals` to `FluentProvider` that defines to whether to pass styles applied to a component down to portals or not. Before this behavior was not configurable.
I also added `applyStylesToPortals` to `apps/vr-tests-react-components/.storybook/preview.js` to ensure that our components apply proper styles and don't rely on styles from `FluentProvider`. `MenuPopover` & `PopoverSurface` have been update to include typography styles.
> feat: add `applyStylesToPortals` prop to FluentProvider

- change/@fluentui-react-combobox-fe274c54-be7a-4171-b120-9f9043f09cc4.json
- packages/react-components/react-combobox/etc/react-combobox.api.md
- packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx
- packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx
- packages/react-components/react-combobox/src/components/Dropdown/Dropdown.test.tsx
- packages/react-components/react-combobox/src/components/Listbox/Listbox.types.ts
- packages/react-components/react-combobox/src/components/Listbox/useListbox.ts
- packages/react-components/react-combobox/src/stories/Combobox/ComboboxMultiselect.stories.tsx
- packages/react-components/react-combobox/src/stories/Combobox/ComboboxMultiselectWithTags.stories.tsx
- packages/react-components/react-combobox/src/stories/Combobox/ComboboxMultiselectWithValueString.stories.tsx
- packages/react-components/react-combobox/src/stories/Combobox/index.stories.tsx
- packages/react-components/react-combobox/src/utils/ComboboxBase.types.ts
- packages/react-components/react-combobox/src/utils/Selection.types.ts
- packages/react-components/react-combobox/src/utils/useComboboxBaseState.ts
- packages/react-components/react-combobox/src/utils/useSelection.ts
- packages/react-components/react-combobox/src/utils/useTriggerListboxSlots.ts
Related to #25724, fixes the item on clearing multiselect combo's input value
We currently show the selected options as part of the input's value string, which makes typing and editing confusing at best:
Now the input value is only used for the user to type to search for options in the multiselect combobox, not for displaying the current selection:
I also added two examples showing how to create multiselect combos with custom tags (probably can be replaced when we release the taglist/pickers), and how to put the selected options in the value string, similar to the v8 behavior:
> feat: Multiselect Combobox does not display selected options in the input value

- change/@fluentui-react-components-1ec556c8-312b-4f16-8020-f39a7c56511e.json
- change/@fluentui-react-progress-de9cb16b-be85-4f69-b976-0a868ed0d472.json
- packages/react-components/react-components/etc/react-components.unstable.api.md
- packages/react-components/react-components/src/unstable/index.ts
- packages/react-components/react-progress/README.md
- packages/react-components/react-progress/etc/react-progress.api.md
- packages/react-components/react-progress/src/components/ProgressBar/ProgressBar.tsx
- packages/react-components/react-progress/src/components/ProgressBar/ProgressBar.types.ts
- packages/react-components/react-progress/src/components/ProgressBar/renderProgressBar.tsx
- packages/react-components/react-progress/src/components/ProgressBar/useProgressBar.tsx
- packages/react-components/react-progress/src/components/ProgressBar/useProgressBarStyles.ts
- packages/react-components/react-progress/src/index.ts
This PR is to remove deprecated `ProgressBar` exports from the renaming from `Progress` to `ProgressBar`. Fixes #25997
> Remove deprecated exports

- packages/react-components/react-combobox/src/stories/Combobox/ComboboxFiltering.stories.tsx
- packages/react-components/react-combobox/src/stories/Combobox/ComboboxFreeform.stories.tsx
- packages/react-components/react-combobox/src/stories/Combobox/index.stories.tsx
Adds/updates two combobox examples:
- The freeform example is updated to implement filtering options and show the freeform user-typed string as an option when no other options match.
- Added a basic Combobox filtering example, showing simple filtering by matching from the start of the string
> feat: more Combobox examples

- change/@fluentui-react-progress-14cf1ca6-4a0c-479b-b6e6-b29236c45a35.json
- packages/react-components/react-progress/src/components/ProgressBar/useProgressBarStyles.ts
This PR adds `@noflip` to `ProgressBar` animation styles to prevent styles from automatic flipping which will create less CSS/classes i.e. improves bundle size. Fixes #26028
> Add noflip to animation styling

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams/components/Button/buttonStyles.ts
Fix styles for the color when the button is `disabledFocusable` and `text`, currently when pressed it makes the color like this: 
This PR implements the fix adding the correct styles for `active`
> fix: button styles for disabledFocusable and text variation

- change/@fluentui-react-positioning-0221531c-b4a7-45c3-9194-a022fc9bb865.json
- packages/react-components/react-positioning/src/utils/writeContainerupdates.ts
Coordiates could have decimal values, this could cause bluriness
Coordinates are always rounded to whole integer values using the same rounding method [that popper v2 uses](https://github.com/floating-ui/floating-ui/blob/2893e9a8d2ebd895eb4311a8873afac62f75123e/src/utils/math.js#L4)
Fixes #25288
> fix: Coordinates should be rounded to integers

- scripts/monorepo/isConvergedPackage.js
- tools/generators/version-bump/index.spec.ts
- tools/generators/version-bump/index.ts
- tools/utils.ts
Since we now have 'v9' packages that don't necessarily have the major version v9 after #26039, we need to update the release and version bumping tools to release these kinds of packages.
After this PR `@fluentui/tokens` will be published along with other v9 packages
> chore(release): v9 packages can be determined by tags in workspace.json

- .github/CODEOWNERS
Update web-components code owners.
Individual contributors replaced by `microsoft/fui-wc` group.
@miroslavstastny and @chrisdholt are currently maintainers of the group.
> Update web-components code owners

- packages/fluentui/CHANGELOG.md
- packages/fluentui/docs/src/app.tsx
- packages/fluentui/react-bindings/src/renderer/RendererContext.ts
- packages/fluentui/react-northstar-fela-renderer/package.json
- packages/fluentui/react-northstar-fela-renderer/src/RendererProvider.tsx
- packages/fluentui/react-northstar-fela-renderer/src/createFelaRenderer.tsx
- packages/fluentui/react-northstar-fela-renderer/src/types.ts
- packages/fluentui/react-northstar-fela-renderer/test/felaRenderer-test.tsx
- yarn.lock
Fixes #25583.
This PR contains a breaking change in `@fluentui/react-northstar-fela-renderer` to allow configure `nonce` property on style tags. `createFelaRenderer()` now is a factory that accepts options:
```tsx
createFelaRenderer();
// or
createFelaRenderer({ nonce: '' })
```
```tsx
import { RendererContext } from "@fluentui/react-northstar";
import { createFelaRenderer } from "@fluentui/react-northstar-fela-renderer";
return <RendererContext.Provider value={createFelaRenderer} />;
}
```
```tsx
import { RendererContext } from "@fluentui/react-northstar";
import { createFelaRenderer } from "@fluentui/react-northstar-fela-renderer";
return <RendererContext.Provider value={createFelaRenderer()} />; // 👈 change is there
}
```
I didn't bump Fela fully as we …
> feat: add support for nonce in Fela renderer

- change/@fluentui-react-03381c14-7db9-4502-8ad9-3eea9bea4bb2.json
- packages/react/etc/react.api.md
- packages/react/src/components/GroupedList/GroupedListV2.tsx
- packages/react/src/components/GroupedList/index.ts
- packages/react/src/index.ts
Some types for `GroupedListV2` are not exported.
`GroupedListV2` props and state types are exported.
> chore: export GroupedListV2 types

- change/@fluentui-react-components-339acd12-98eb-4ed1-8be5-0b64cfc08152.json
- change/@fluentui-react-toolbar-89443f18-b94b-4c3b-9171-9dc4e4826524.json
- packages/react-components/react-components/etc/react-components.unstable.api.md
- packages/react-components/react-components/src/unstable/index.ts
- packages/react-components/react-toolbar/etc/react-toolbar.api.md
- packages/react-components/react-toolbar/src/components/ToolbarButton/index.ts
- packages/react-components/react-toolbar/src/components/ToolbarGroup/index.ts
- packages/react-components/react-toolbar/src/components/ToolbarRadioButton/index.ts
- packages/react-components/react-toolbar/src/components/ToolbarToggleButton/index.ts
- packages/react-components/react-toolbar/src/index.ts
- packages/react-components/react-toolbar/stories/Toolbar/ToolbarControlledToggleButton.stories.tsx
- packages/react-components/react-toolbar/stories/Toolbar/ToolbarDefault.stories.tsx
- packages/react-components/react-toolbar/stories/Toolbar/ToolbarFarGroup.stories.tsx
- packages/react-components/react-toolbar/stories/Toolbar/ToolbarLarge.stories.tsx
- packages/react-components/react-toolbar/stories/Toolbar/ToolbarMedium.stories.tsx
- packages/react-components/react-toolbar/stories/Toolbar/ToolbarOverflow.stories.tsx
- packages/react-components/react-toolbar/stories/Toolbar/ToolbarRadio.stories.tsx
- packages/react-components/react-toolbar/stories/Toolbar/ToolbarRadioControlled.stories.tsx
- packages/react-components/react-toolbar/stories/Toolbar/ToolbarSmall.stories.tsx
- packages/react-components/react-toolbar/stories/Toolbar/ToolbarSubtle.stories.tsx
- packages/react-components/react-toolbar/stories/Toolbar/ToolbarVertical.stories.tsx
- packages/react-components/react-toolbar/stories/Toolbar/ToolbarVerticalButton.stories.tsx
- packages/react-components/react-toolbar/stories/Toolbar/ToolbarWithPopover.stories.tsx
- packages/react-components/react-toolbar/stories/Toolbar/ToolbarWithTooltip.stories.tsx
- packages/react-components/react-toolbar/stories/Toolbar/index.stories.tsx
Exports all relevant Toolbar components and utilities
Currently toolbar docs components/types are imported from `@fluentui/react-toolbar`, this means that the sandbox example will export from `@fluentui/react-components` which will fail because the import should be from `@fluentui/react-components/unstable`
> fix: Export all relevant Toolbar components and utilities

- change/@fluentui-react-utilities-7cc076d6-144c-497a-9432-7ed6e01735ae.json
- packages/react-components/react-utilities/etc/react-utilities.api.md
- packages/react-components/react-utilities/src/utils/isHTMLElement.ts
- packages/react-components/react-utilities/src/utils/isInteractiveHTMLElement.ts
Converts guard type method `isHTMLElement` and `isInteractiveHTMLElement` to accept any kind of argument by converting it's type from `Node` to `unknown`.
Some use cases while dealing with `event.target` might require this conversion, as `event.target` typings provided by react normally are simplified to `EventTarget`
> feat(react-utilities): generalize is HTMLElement attribute to unknown

- change/@fluentui-react-b2a0ebef-487f-495f-b9b6-e90e361cb18b.json
- packages/react-experiments/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/react/src/components/ComboBox/ComboBox.tsx
- packages/react/src/components/ComboBox/ComboBox.types.ts
- packages/react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap
Previously, the chevron button had `aria-hidden=true` by default, since the input handles all keyboard interaction. Including the button in the accessibility tree effectively creates two form fields per combobox.
The issue is that Android Talkback does not allow the user to trigger a click or touch event in the input, making it impossible to expand the ComboBox with Talkback running. While this is a bug on their side, it is still a severe enough issue to make it worth changing our desktop screen reader behavior so that Talkback users are able to use the control.
The chevron button does not have `aria-hidden` by default. This can still be changed by authors using the already-existing `isButtonAriaHidden` prop.
Note -- this does not affect the tab order or the DOM.
* Fixes …
> fix: v8 ComboBox button is no longer aria-hidden by default

- azure-pipelines.yml
- removes `Screener` step from pipeline
* Part of #25078
> chore (CI v5): remove Screener step from pipeline

- change/@fluentui-react-table-808432fb-a855-4007-b789-614057e34ad1.json
- packages/react-components/react-table/etc/react-table.api.md
- packages/react-components/react-table/src/components/DataGridBody/DataGridBody.types.ts
- packages/react-components/react-table/src/components/DataGridBody/renderDataGridBody.tsx
- packages/react-components/react-table/src/components/DataGridBody/useDataGridBody.tsx
- packages/react-components/react-table/src/components/DataGridRow/DataGridRow.types.ts
- packages/react-components/react-table/src/components/DataGridRow/renderDataGridRow.tsx
- packages/react-components/react-table/src/components/DataGridRow/useDataGridRow.tsx
Components like `DataGridBody` and `DataGridRow` only accept render functions as children. These render functions were always called during the `useComponent` hook. This was unnecessary, and makes recomposition harder because data is always processed even if the recomposed component should render children differently.
The change also makes more sense from a conceptual PoV, since render functions are called in render functions .
> refactor: render function children called in component render function

- apps/public-docsite-resources/webpack.serve.config.js
- apps/public-docsite/webpack.config.js
- apps/public-docsite/webpack.serve.config.js
- apps/react-18-tests-v8/jest.config.js
- apps/react-18-tests-v8/webpack.config.js
- apps/ssr-tests/webpack.config.js
- apps/theming-designer/webpack.serve.config.js
- apps/vr-tests/.storybook/main.js
- change/@fluentui-react-83b1e053-10c3-427f-9ebe-159992e6ca02.json
- change/@fluentui-react-monaco-editor-cc0e10b0-dc27-4b7c-af7f-bcae8d5c671a.json
- packages/react-examples/.storybook/main.js
- packages/react-examples/.storybook/tsconfig.json
- packages/react-monaco-editor/webpack.serve.config.js
- packages/react/webpack.codepen.config.js
- packages/react/webpack.mf.config.js
- scripts/cypress/cypress.config.ts
- scripts/storybook/README.md
- scripts/storybook/tsconfig.json
- scripts/webpack/README.md
- scripts/webpack/getResolveAlias.js
- scripts/webpack/index.js
- scripts/webpack/storybook-webpack.config.js
- scripts/webpack/tsconfig.json
- scripts/webpack/webpack-resources.js
- `/storybook` contains mixed v8 and v9 code
- `/webpack` exposes deep imports for v8 tooling
- `/storybook` contains only v9 code
- `/webpack` uses barrel file to prevent deep imports
* Fixes partially https://github.com/microsoft/fluentui/issues/24349
> refactor(scripts): separate `/storybook` and `/webpack` and introduce barrel api within `/webpack`

- change/@fluentui-react-positioning-79cab7f0-3879-4f3b-a855-253d7bd87fec.json
- packages/react-components/react-positioning/src/createPositionManager.ts
Even though the position manager can be disposed, the debounced `forceUpdate` can still happen. This will add scroll listeners to the document without cleaning them up (the manager has already been disposed).
This PR updates the disposal of the position manager to destroy the reference to the original `forceUpdate` so that it never executes.
> fix: force update memory leak in positioning manager

- apps/public-docsite-v9/package.json
- apps/vr-tests-react-components/package.json
- change/@fluentui-react-components-d72c0cfe-6075-444c-9af6-3fa0a3ae2501.json
- packages/react-components/react-components/package.json
- sets `@fluentui/react-storybook-addon` dev dependency to a pinned version in v9, v9 docsite and v9 vr-tests packages. `@fluentui/react-storybook-addon` is still in `prerelease` and thus having it set as a caret can lead to non-deterministic resolutions.
* Fixes #25490
> chore: set @fluentui/react-storybook-addon dependency to a pinned version in various packages

- change/@fluentui-monaco-editor-4fb3039b-1e7a-4e18-a0b3-1d0e9c200bfe.json
- change/@fluentui-react-monaco-editor-87fa619c-f87b-479a-8b34-82479c930a16.json
- packages/monaco-editor/just.config.ts
- packages/react-monaco-editor/scripts/copyTypes.ts
- scripts/tasks/index.ts
packages use deep imports to `scripts/tasks`
packages dont use deep imports from `scripts/tasks`
- Fixes partially https://github.com/microsoft/fluentui/issues/24349
> chore(scripts): remove deep imports from /scripts/tasks/*

- .storybook/main.js
- scripts/storybook/utils.js
- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
- Addresses TODO items in `migrate-converged-pkg` workspace generator and removes functions no longer needed with v9 package migrations complete.
- Addresses miscellaneous TODO items in other files. 
* Part of #24129
> chore (tools): cleanup TODO items in migrate-converged-pkg generator

- apps/vr-tests-react-components/package.json
- apps/vr-tests/package.json
- package.json
- packages/fluentui/docs/package.json
* Fixes partially https://github.com/microsoft/fluentui/issues/21395
> chore: move storywright to root package json to adhere to single version policy for devDeps

- azure-pipelines.release.yml
- Automatic releases are scheduled for the v6 branch.
- Release pipeline for v6 errors out due to too many calls to the github API (example [error](https://uifabric.visualstudio.com/UI%20Fabric/_build/results?buildId=279592&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=c3091b1e-314e-512e-11db-151fdba14cd6))
- No more automatic releases, any future v6 releases will need to be triggered manually.
- Release pipeline no longer fails
> chore (CI v6): disable scheduled releases, future releases will need to be triggered manually 

- change/@uifabric-charting-1027db92-a05d-490c-bb5c-874afb13b7d9.json
- packages/charting/src/components/AreaChart/AreaChart.base.tsx
- packages/charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap
- packages/charting/src/components/CommonComponents/CartesianChart.base.tsx
- packages/charting/src/components/DonutChart/Arc/Arc.styles.ts
- packages/charting/src/components/DonutChart/Arc/Arc.tsx
- packages/charting/src/components/DonutChart/DonutChart.base.tsx
- packages/charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
- packages/charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap
- packages/charting/src/components/HeatMapChart/HeatMapChart.base.tsx
- packages/charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap
- packages/charting/src/components/LineChart/LineChart.base.tsx
- packages/charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
- packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx
- packages/charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx
- packages/charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap
- packages/charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx
- packages/charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChart.test.tsx.snap
Cherry-pick of #24903 and #25978
> Cherry-pick fix for wrong narration when legend selected

- package.json
- yarn.lock
we have loader-utils@2.0.0 in our deps because mdx-js/loader declares it as dependency via exact version. we raised issue on their repo to release patch for v1 which was closed as wont do.
Because mdx-js/loader doesn't enable using proper packages deduping by following semantic versioning principles, which would also enable anyone to resolve deps (patch,minor) on their own, we need to use yarn.resolution to force the behaviours. 
* Fixes https://github.com/microsoft/fluentui/issues/26095
> chore: set @mdx-js/loader loader-utils to 2.0.4 to mitigate critical vulnerability reported by CGC

- packages/fluentui/CONTRIBUTING.md
- scripts/gulp/tasks/docs.ts
See title. We don't use `gh-pages` for deployments in this repo.
> chore: remove unused Gulp task

- apps/public-docsite-v9/src/Concepts/AdvancedConfiguration.stories.mdx
- change/@fluentui-react-provider-b0221870-0188-4949-b08b-69ebb21956d2.json
- packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderThemeStyleTag.test.tsx
- packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderThemeStyleTag.ts
`FluentProvider` now applies the same style attributes as Griffel does:
```tsx
const renderer = createDOMRenderer(document, {
styleElementAttributes: {
nonce: "random"
}
});
ReactDOM.render(
<RendererProvider renderer={renderer}>
<FluentProvider />
</RendererProvider>
);
```
With this change we will get following in DOM:
```html
<style nonce="random" data-make-styles-bucket="d"></style>
<style nonce="random" id="fui-FluentProvider1"></style>
```
Documentation page was renamed to include also a guide on how to configure `nonce` for CSP.
- Fixes #25421
> feat: FluentProvider applies style attributes defined by a renderer

- .github/workflows/create-milestone.yml
auto assign milestone will keeps adding wrong milestone to every PR change because there is no due_date set when creating one.
for example, this PR has set October milestone -> <img width="358" alt="image" src="https://user-images.githubusercontent.com/1223799/210414244-e9d007cf-27c5-41b8-b797-85501757721c.png">
during milestone creation due_date is set this automation will work as expected
* Fixes #
> ci(github): set due_on when creating milestone to make milestone auto-assign work as expected

- change/@fluentui-react-portal-5ad76945-0626-47e1-95d8-8cdc349fbd47.json
- packages/react-components/react-portal/etc/react-portal.api.md
- packages/react-components/react-portal/src/virtualParent/elementContains.ts
- packages/react-components/react-portal/src/virtualParent/getParent.ts
- packages/react-components/react-portal/src/virtualParent/getVirtualParent.ts
- packages/react-components/react-portal/src/virtualParent/isVirtualElement.ts
- packages/react-components/react-portal/src/virtualParent/setVirtualParent.ts
- packages/react-components/react-portal/src/virtualParent/types.ts
`elementContains` only supports `HTMLElement` type for verification of parent and children. The base type for `event.target` is `Node` which is a more generic type, and it'd be a common case scenario to have `elementContains` being used with `event.target`:
```ts
// the casting is required right now as elementContains doesn't support Node
elementContains(someParentRef.current, event.target as HTMLElement)
```
Supports `Node` type for `elementContains` for both parent and children.
```ts
// no casting is required
elementContains(someParentRef.current, event.target)
```
> feat(react-portal): elementContains supports Node types

- change/@fluentui-react-3958e349-5c28-4835-b5ea-22a5886dc33f.json
- packages/react/src/utilities/ThemeProvider/renderThemeProvider.tsx
ThemeProvider adds a div in the root that may break the styles of the app, so we can use as={React.Fragment} to avoid this, like this:
but this will throw a react error:
The goal of this change is to avoid passing the theme prop to the React.Fragment by just returning the state.children in case the 
as={React.Fragment} is being set in the ThemeProvider
https://github.com/microsoft/fluentui/issues/16633
* Fixes #
> Fix react errors on ThemeProvider when as React.Fragment is set to remove the div root

- change/@fluentui-web-components-009b1050-81d9-453d-9e6a-0cdebcba8a0f.json
- packages/web-components/src/tooltip/tooltip.styles.ts
Fluent tooltip not showing triangle tip when tag is renamed
Fluent tooltip correctly shows triangle tip when tag is renamed
* Fixes #26153
> updating fluent-tooltip wc styles to support custom tag names

- change/@fluentui-react-d13203b4-5c4b-4735-a07b-79f0d4a82161.json
- packages/react/src/components/Stack/Stack.test.tsx
- packages/react/src/components/Stack/Stack.tsx
Inner `Stacks`, when passed via an HOC wrapper
```ts
const CustomStack = (props) => <Stack className="custom" {...props} />;
```
were having their `className` set to `undefined` given how we were cloning children within `Stacks`.
We now account for nested `Stacks` when cloning children by only conditionally cloning the `className` if it has been set, instead of setting it to `undefined` if it hasn't, which was causing custom classNames to be unset.
We have also added a test, so this doesn't regress in the future.
> fix: Stopping className being unset in inner Stacks

- change/@fluentui-azure-themes-f3404503-cd3e-4a43-9b11-2e42181dde23.json
- packages/azure-themes/src/azure/styles/DetailsList.styles.ts
- packages/react-examples/src/azure-themes/stories/components/detailsList.stories.tsx
Azure Theme was showing a border on all checkboxes within a DetailsList / grid, regardless of state. Per Ibiza designs, checkbox border should only appear on selected, hovered, active states and _not_ in rest/unselected state.
dark
high contrast light
high contrast dark
Note: this change is only appearing in 8.0 as products have snapped to this branch
> AzureTheme DetailsList checkbox fix

- change/@fluentui-azure-themes-7e56ebb2-3674-4f55-af98-41b8ced3ceb2.json
- packages/azure-themes/src/azure/Constants.ts
- packages/azure-themes/src/azure/styles/Checkbox.styles.ts
- packages/azure-themes/src/azure/styles/ChoiceGroupOptions.styles.ts
- packages/azure-themes/src/azure/styles/ComboBox.styles.ts
- packages/azure-themes/src/azure/styles/DropDown.styles.ts
- packages/azure-themes/src/azure/styles/TextField.styles.ts
No visual changes. Alphabetized the Azure Theme constants and renamed choiceGroupHeight to choiceFieldHeight to be applicable to multiple selection controls (choicegroup, checkbox). 
Allows partner teams like Elixir to theme their controls when Azure Theme is applied.
> Azure Theme Constants Clean Up

- change/@fluentui-react-acde88e8-7f76-4606-bf70-55d23dda62f7.json
- packages/react/src/components/pickers/BasePicker.tsx
We fire an invisible live region when selected tags are removed, but since we don't clear the text, it's discoverable with a screen reader's virtual cursor.
We can remove the live region text on a timeout so it will still fire the event and be read by screen readers, but the text will not remain in the DOM/accessibility tree in between the label and form field.
* Fixes [15715](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15715)
> fix: Pickers' live region announcement text is removed from the DOM 

- change/@fluentui-react-popover-e6c0c11d-26c7-48a2-ae7e-ef5aa0fa8829.json
- packages/react-components/react-popover/etc/react-popover.api.md
- packages/react-components/react-popover/src/components/Popover/Popover.types.ts
- packages/react-components/react-popover/src/components/Popover/usePopover.ts
When Popover opens, it automatically focuses on first focusable item in PopoverSurface.
There's no way to disable this from user side. After discussion we decide to introduce unstable prop `unstable_disableAutoFocus`
> feat(Popover): new prop unstable_disableAutoFocus to prevent auto focus on Popover open

- .storybook/preview.js
- typings/storybook__addons/index.d.ts
Previously codeblocks were processed and showed an approximation of the JSX initially rendered
This ends up removing conditionally rendered JSX, as well as hooks and other configuration
This update makes storybook use the source code verbatum so that it could be copied and pasted.
With this change, the default behavior will make the codeblocks look like this:
This adjustment will change ALL storybooks that reference this default config, but can be overriden if this behavior doesn't fit their package or individual story
> Storybook: make codeblocks default to source to more accurately show source code

- change/@fluentui-react-ad8a4cf9-019c-49a0-9d87-323f6f5f0969.json
- packages/react/src/components/pickers/Suggestions/Suggestions.types.ts
As mentioned in #24028, the footer of a suggestion listbox is not focusable. Changing this would be too disruptive to the existing pattern, so we're changing the docs to recommend not adding interactive elements to the footer (rather use it for text like error messages etc). If the user needs an interactive element, it should go inside the listbox.
> chore: Update suggestion type docs to mention not adding interactive elements to the footer

- change/@fluentui-react-components-fdd6f6e7-4e2b-4ae2-ae93-f30b682c0bba.json
- change/@fluentui-react-utilities-818cadf1-b5b0-400f-b65d-f5ff490c6fa5.json
- packages/react-components/react-components/etc/react-components.api.md
- packages/react-components/react-components/src/index.ts
- packages/react-components/react-table/stories/Table/Virtualization.stories.tsx
- packages/react-components/react-utilities/etc/react-utilities.api.md
- packages/react-components/react-utilities/src/hooks/index.ts
- packages/react-components/react-utilities/src/hooks/useScrollbarWidth.ts
- packages/react-components/react-utilities/src/index.ts
New hook that returns the width of the scrollbar in pixels of the current user agent
> feat: implement `useScrollbarWidth` utility hook

- packages/react-components/react-tabs/stories/Tabs/TabListWithOverflow.stories.tsx
- packages/react-components/react-toolbar/stories/Toolbar/ToolbarOverflow.stories.tsx
Toolbar and TabList stories are currently broken because of incorrect exports. Fix these examples for our docsite.
> docs: Fix overflow stories

- change/@fluentui-react-combobox-b1fa3ab7-ea40-4131-ba9a-4e1f7b78d110.json
- packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx
- packages/react-components/react-combobox/src/utils/useComboboxBaseState.ts
- Multiselect Combobox & Dropdown began option focus at last selected option when opened (similar to single-select combobox)
- When opened from the combobox chevron, the option keyboard focus outline still showed up
- Multiselect combo & dropdown always begin from the first option when opened (unlike single-select) -- discussed with design
- Focus visibility is reset when using the mouse to open a combobox from the chevron icon
Addresses poitns 1 & 2 in #26069
* Fixes #
> fix: v9 Combobox option focus on open updates

- change/@fluentui-react-table-2f6ac7ff-0a0f-4fcf-8515-64378641f5c3.json
- packages/react-components/react-table/src/hooks/selectionManager.ts
`Event` is redundant there as only React's event could be there.
> fix: remove Event type in selectionManager

- .storybook/docs-root.css
Improve how <code> tags look like in public docsite v9. Before, there was no differentiation between plain text and code tags, which made it hard to head props and values.
> docs: fix storybook code tag not having any highlight/monospace font

- change/@fluentui-react-combobox-9f8aba26-8e89-4812-a093-00ff3dd02053.json
- packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx
- packages/react-components/react-combobox/src/utils/useComboboxBaseState.ts
- packages/react-components/react-combobox/src/utils/useSelection.ts
- packages/react-components/react-combobox/src/utils/useTriggerListboxSlots.ts
Addresses perf bullets from #26069
- In `useCombobox`, `popupWidth` created a new object assigned to `listbox.style` every render. Now the object is created in the `useState` hook, and only updated when opened/closed.
- In `useTriggerListboxSlots`, listbox event handlers every render. Now it uses `useEventCallback`, and should only update on open/close.
- `selectOption` and `setOpen` were recreated every render, and since they are used in the combobox context, they caused options to re-render. Now they use `useCallback`.
> fix: react-combobox perf improvements

- change/@fluentui-react-d89e5599-f5a5-4701-8093-88c930b1a96a.json
- packages/react/etc/react.api.md
- packages/react/src/components/Button/BaseButton.tsx
- packages/react/src/components/ChoiceGroup/ChoiceGroup.base.tsx
Two components, Button and ChoiceGroup, directly call the `setFocusVisibility` function. This defaults to setting the className on the parent `<body>` tag unless an explicit `registeredProviders` array is passed in.
This is an issue if the provider ref in the `FocusRectsContext` is anything other than the `<body>`, as is the case on our docs site. What happens is the manual call of `setFocusVisibility` sets the focus-visible className on `<body>`, while subsequent updates through `useFocusRects` set it correctly on the element provided in the context. This means there is always a focus-visible className on `<body>` that never updates, which causes focus to always be visible.
Both components that directly call `setFocusVisibility` now pass in the `registeredProvider` from the …
> fix: Focus visibility when directly calling setFocusVisibility

- change/@fluentui-priority-overflow-a6c512bd-b2fc-4a49-8821-e3dcb2b2e162.json
- change/@fluentui-react-overflow-1516fc28-9fa1-46ea-93e4-385e94dcb66c.json
- packages/react-components/priority-overflow/src/overflowManager.ts
- packages/react-components/react-overflow/src/Overflow.cy.tsx
This fixes a regression from #25091, the updated mechanism to handle overflow menu was inadvertedly breaking the minumum visible options because it was still making items invisible without considering whether the minimum number of items was reached.
> fix: Minimum visible overflow items should be respected

- change/@fluentui-eslint-plugin-700c8d6f-1dc3-46ac-a416-d4aded1a6256.json
- packages/eslint-plugin/src/utils/configHelpers.js
- scripts/lint-staged/eslint-for-package.js
- scripts/lint-staged/eslint.js
- if linting fails on pre-commit any eslint error stdout is consumed by subprocess and nothing is printed to user besides `FAILURE`
- if you touched/created `cypress.config.ts` within your package/pr pre-commit linting will fail on `import/no-extraneous-dependencies` rule violation.
- linting failures during pre-commit are propagated to STDOUT thus reported by eslint 
- if you touched/created `cypress.config.ts` within your package/pr pre-commit linting will pass (cypress.config.ts is now part of devdependecy globs for import rule configuration)
> fix(scripts): make lint errors reporting propagate to STDOUT during pre-commit (lint-staged exec)

- change/@fluentui-react-table-b7b4e350-1297-4672-9a9d-88072c4990fa.json
- packages/react-components/react-table/etc/react-table.api.md
- packages/react-components/react-table/src/components/TableCellLayout/TableCellLayout.types.ts
- packages/react-components/react-table/src/components/TableCellLayout/__snapshots__/TableCellLayout.test.tsx.snap
- packages/react-components/react-table/src/components/TableCellLayout/renderTableCellLayout.tsx
- packages/react-components/react-table/src/components/TableCellLayout/useTableCellLayout.ts
- packages/react-components/react-table/src/components/TableCellLayout/useTableCellLayoutStyles.ts
```tsx
<TableCellLayout wrapper={{ className: 'wrapperSlot' }}>
<Component />
</TableCellLayout>
```
```tsx
<TableCellLayout content={{ className: 'contentSlot' }}>
<Component />
</TableCellLayout>
```
Fixes #26203
> BREAKING(TableCellLayout): `wrapper` slot renamed to `content`

- packages/react-components/react-tree/etc/react-tree.api.md
- packages/react-components/react-tree/package.json
- packages/react-components/react-tree/src/components/BaseTreeItem/BaseTreeItem.types.ts
- packages/react-components/react-tree/src/components/BaseTreeItem/useBaseTreeItem.ts
- packages/react-components/react-tree/src/components/Tree/Tree.types.ts
- packages/react-components/react-tree/src/components/TreeItem/TreeItem.test.tsx
- packages/react-components/react-tree/src/components/TreeItem/TreeItem.types.ts
- packages/react-components/react-tree/src/components/TreeItem/__snapshots__/TreeItem.test.tsx.snap
- packages/react-components/react-tree/src/components/TreeItem/renderTreeItem.tsx
- packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx
- packages/react-components/react-tree/src/components/TreeItem/useTreeItemStyles.ts
- packages/react-components/react-tree/stories/Tree/TreeActions.stories.tsx
1. stops using `ARIAButton` as the main root type for the `TreeItem`
2. stops supporting `Space` as an action for the `TreeItem` in consequence of not using `ARIAButton`
3. Supports proper positioning of `actions` slots
4. Supports proper navigation of `actions` slots through grouppers
5. Supports usage of `Menu` and other portals on `actions` slots
> feat(react-tree):  Actions positioning and behaviour

- change/@fluentui-react-menu-7ad515c7-ae51-477d-9289-c01f7a691b06.json
- packages/react-components/react-menu/etc/react-menu.api.md
- packages/react-components/react-menu/src/components/Menu/Menu.test.tsx
- packages/react-components/react-menu/src/components/MenuList/MenuList.types.ts
- packages/react-components/react-menu/src/components/MenuList/useMenuList.ts
- packages/react-components/react-menu/stories/Menu/MenuControlledCheckboxItems.stories.tsx
- packages/react-components/react-menu/stories/Menu/MenuControlledRadioItems.stories.tsx
- packages/react-components/react-menu/stories/MenuList/MenuListCheckboxItems.stories.tsx
- packages/react-components/react-menu/stories/MenuList/MenuListControlledCheckboxItems.stories.tsx
- packages/react-components/react-menu/stories/MenuList/MenuListControlledRadioItems.stories.tsx
- packages/react-components/react-menu/stories/MenuList/MenuListRadioItems.stories.tsx
- packages/react-components/react-menu/stories/MenuList/index.stories.tsx
Fixes the regression introduced in #25672 so that prop values win over context props with the same name.
Also removes deprecation notice on `defaultCheckedValues`  and `onCheckedValueChange` for `MenuList` which are completely reasonable to use in scenarios where `MenuList` is used standalone.
Also updates documentation so that `Menu` examples will use the selection props on the root `Menu` components. Adds selection examples for `MenuList` to be more clear about the differences between the two.
Fixes #26253
> fix: MenuList props should win over context props

- change/@fluentui-react-menu-90f8d720-d06d-48f0-a6ad-2d96810d1dfc.json
- packages/react-components/react-menu/etc/react-menu.api.md
- packages/react-components/react-menu/src/components/MenuItem/MenuItem.types.ts
- packages/react-components/react-menu/src/components/MenuItem/useMenuItem.tsx
Refer to https://github.com/microsoft/fluentui/issues/25887 for more details on the problem.
Stops supporting `ARIAButton` types on the root of the component.
* Fixes #25887
> fix(react-menu): stops using `ARIAButton` types for `MenuItem` root

- change/@fluentui-react-combobox-3d31acf9-37ca-43e4-8338-1f3ce04d8e7e.json
- change/@fluentui-react-select-f9db8e0b-3088-4a68-9179-d5821aebf0cd.json
- packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx
- packages/react-components/react-combobox/src/components/Dropdown/useDropdownStyles.ts
- packages/react-components/react-combobox/stories/Combobox/ComboboxDisabled.stories.tsx
- packages/react-components/react-combobox/stories/Combobox/index.stories.tsx
- packages/react-components/react-combobox/stories/Dropdown/DropdownDisabled.stories.tsx
- packages/react-components/react-combobox/stories/Dropdown/index.stories.tsx
- packages/react-components/react-select/src/components/Select/useSelectStyles.ts
This PR includes the following fixes for disabled states for Combobox, Dropdown, and Select:
- Select does not show hover/active styles when disabled
- Adds stories for Combobox/Dropdown disabled state
- Combobox does not open on chevron click when disabled
- Dropdown button text color when disabled
Part of #26069
> fix: Select disabled state hover style, Combobox disabled state open on chevron click

- change/@fluentui-react-checkbox-cba19a44-ae9e-485b-9089-6c7d0d4d8ce6.json
- packages/react-components/react-checkbox/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/react-components/react-checkbox/src/components/Checkbox/useCheckbox.tsx
- packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts
- packages/react-components/react-table/src/components/TableSelectionCell/__snapshots__/TableSelectionCell.test.tsx.snap
Checkbox always renders its checkmark icon, even when unchecked. It uses a universal selector in css (`> *`) to target the checkmark and set its opacity to 0 when unchecked.
Don't render the checkmark at all when unchecked, and remove the universal selector rule in CSS.
> perf: Don't render Checkbox icon when unchecked

- change/@fluentui-react-slider-2f917409-4eb9-4200-a537-14c6a2e11be2.json
- packages/react-components/react-slider/src/components/Slider/useSlider.ts
without merging refs, the user provided ref will override the default ref
https://codesandbox.io/s/component-focus-when-ref-is-set-8o77uy?file=/example.tsx
This is a fix for Slider only, but we'll need to make this change on probably any component that uses useFocusWithin
> Fix: Allow root slot refs to merge with focus refs in Slider

- change/@fluentui-azure-themes-f2eeb068-7c57-433f-9da0-60afb1302fc4.json
- packages/azure-themes/src/azure/styles/SpinButton.styles.ts
- packages/react-examples/src/azure-themes/stories/Themes/Themes.stories.tsx
- packages/react-examples/src/azure-themes/stories/components/SpinButton.stories.tsx
Spin button height was set to default Fluent height. Per Azure Theme, we need higher density controls at 24px.
Spin button now set to same height as dropdowns and textfields, 24px. 
Light theme: 
dark theme
high contrast light
high contrast dark
* Fixes #
> Azure Theme: reduced spin button height to match TextField / DropDowns at 24px height

- change/@fluentui-react-menu-9787aa9c-cdf8-41b8-a9d6-c8d7e1f3c502.json
- packages/react-components/react-menu/src/components/Menu/Menu.cy.tsx
- packages/react-components/react-menu/src/components/Menu/useMenu.tsx
- packages/react-components/react-menu/src/components/MenuPopover/useMenuPopover.ts
Removes the explicit tab handling in the Menu.
We know that React effects are sync so we always focus the menu trigger when the menu is closed. Since the browser only performs the default behaviour for Tab once events have fully bubbled up the window, the browser will move focus to the next tabbable element before/after the trigger if needed. If tab was not pressed, then we simply focus the trigger as expected.
Fixes #26164
> fix: Tab should focus the window if trigger is the last focusable element

- .github/workflows/check-packages.yml
- .github/workflows/issues.yml
We use actions that run on node 12 which triggers warnings
no warnings
> ci: bump actions/checkout to v3 to fix node12 deprecation

- change/@fluentui-react-8abc6b6c-fcb2-4ec6-b72d-d68559917073.json
- packages/react/src/components/pickers/Suggestions/Suggestions.tsx
- Encapsulated default render in a function
- Passed defaultRender to noResultsFound render callback
Fixes #24128
> Fix suggestions no results infinite loop

- change/@fluentui-react-components-628325e5-01eb-451b-81b1-938803d37d3d.json
- packages/react-components/react-components/etc/react-components.unstable.api.md
- packages/react-components/react-components/src/unstable/index.ts
There were a couple of exports in `@fluentui/react-combobox` that were not being re-exported by `@fluentui/react-components/unstable`:
- `ComboboxProvider`
- `useComboboxContextValues`
- `ListboxProvider`
- `useListboxContextValues`
The previously stated exports are now re-exported by `@fluentui/react-components/unstable`.
> chore: Re-exporting missing exports from @fluentui/react-combobox

- change/@uifabric-azure-themes-e6839196-bf0a-421f-bcb4-e859ad624f8b.json
- packages/azure-themes/src/azure/styles/DetailsList.styles.ts
Cherry picked from #26152 
Azure Theme was showing a border on all checkboxes within a DetailsList / grid, regardless of state. Per Ibiza designs, checkbox border should only appear on selected, hovered, active states and _not_ in rest/unselected state.
dark
high contrast light
high contrast dark
Note: this change is only appearing in 8.0 as products have snapped to this branch
> Cherry picked from #26152 : AzureTheme DetailsList checkbox fix 

- change/@fluentui-react-field-b2bd417e-f8c8-4fba-ab72-7f3c6e0cdfe2.json
- packages/react-components/react-field/src/components/Field/renderField.tsx
- packages/react-components/react-field/src/components/Field/useFieldStyles.ts
Fixes #26061
Because an SVG was wrapped in a parent with `display: inline`, it caused odd layout issues, despite the SVG also being styled `display: inline`. Specifically, when used within a dialog, it would trigger a vertical scrollbar in the dialog (example in the issue).
We also previously styled status text to wrap like this:
The scrollbar issue no longer happens, and now text wraps like this (checked with design, and this was the desired behavior):
> fix: react-field does not wrap SVG in inline parent

- change/@fluentui-react-combobox-9ad3f5bc-8c19-4f73-a4b3-1cd41e43e7b2.json
- packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx
- packages/react-components/react-combobox/src/components/Combobox/__snapshots__/Combobox.test.tsx.snap
- packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx
- packages/react-components/react-combobox/src/components/Dropdown/Dropdown.test.tsx
- packages/react-components/react-combobox/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/react-components/react-combobox/src/components/Dropdown/useDropdown.tsx
- packages/react-components/react-combobox/src/utils/useTriggerListboxSlots.ts
No `aria-owns`, so when the listbox popup is appended at the end of the DOM, it was not really reachable with virtual cursor/scan mode/swipe navigation
`aria-owns` is added to the root node pointing at the listbox when the listbox is not inline (it's not needed with an inline popup, since then the listbox DOM is already adjacent to the trigger).
This works for every browser but Safari.
Part of work in #26069
> fix: add aria-owns to react-combobox non-inline popups

- change/@fluentui-react-table-dc36dcfe-b403-4c89-9868-b16b05e46700.json
- packages/react-components/react-table/src/components/TableSelectionCell/TableSelectionCell.test.tsx
- packages/react-components/react-table/src/components/TableSelectionCell/__snapshots__/TableSelectionCell.test.tsx.snap
- packages/react-components/react-table/src/components/TableSelectionCell/useTableSelectionCell.tsx
While native radios change selection on focus, it can be a bad experience for keyboard users on larger widgets. If an author wants to perform an action on row select, it won't force a keyboard user to perform that action for every row between the one that they're on and the one that they want.
Fixes #26196
> fix(TableSelectionCell): Radios should not change selection on focus

- .github/CODEOWNERS
Based on v-build agreement removing all package.json files from its ownership and keeping only all common config files
> chore: remove all package.json from v-build ownership to speed-up PR review velocity

- change/@fluentui-react-infobutton-a65e9aed-2d7e-47dc-800d-4ef527235880.json
- packages/react-components/react-infobutton/etc/react-infobutton.api.md
- packages/react-components/react-infobutton/src/components/InfoButton/InfoButton.test.tsx
- packages/react-components/react-infobutton/src/components/InfoButton/InfoButton.types.ts
- packages/react-components/react-infobutton/src/components/InfoButton/useInfoButton.tsx
This PR does the following:
* Update `PopoverSurface`'s role to `note`.
* Make `Popover`'s type the regular `Popover`'s props since `ComponentProps` resolves to an undesired type for its API. This was causing a need to cast the props when the user wanted to override any of its props as such:
```
<InfoButton content="content" popover={{ appearance: "inverted"} as PopoverProps } />
```
> fix(react-infobutton): Change role of PopoverSurface to note and fix API to not require cast

- change/@fluentui-react-dialog-e4f307fd-e8fd-40ef-ad9a-1644b08ddca0.json
- packages/react-components/react-dialog/stories/Dialog/DialogNonModal.md
> chore: fix typo in Dialog docs

- change/@fluentui-fluent2-theme-8de94a1d-8f86-46ae-9a71-92747400ae1f.json
- packages/fluent2-theme/src/fluent2SharedColors.ts
- packages/fluent2-theme/src/fluent2WebDarkTheme.ts
- packages/fluent2-theme/src/fluent2WebLightTheme.ts
- Mapped the v9 global colors to the v8 shared colors creating a shared colors partial palette
- Updated both light and dark themes to pick up the new shared colors
- Added some missing palette colors in light and dark themes
- Fixed the alpha black/white color inversion in the dark theme
- Reorganized the light and dark palettes to be ordered like IPalette for readability/reconciliation
> Update fluent 2 theme to reconcile with v9

- change/@fluentui-react-components-a51180d1-0c56-4535-940f-5a4bb8cfeadd.json
- packages/react-components/react-components/etc/react-components.api.md
- packages/react-components/react-components/src/index.ts
This PR re-exports `makeResetStyles` in `@fluentui/react-components` to allow for its consumption without having to import it from `@griffel/react` directly.
> chore: Re-exporting makeResetStyles in @fluentui/react-components

- apps/vr-tests-react-components/package.json
- apps/vr-tests-react-components/src/stories/InfoButton.stories.tsx
- change/@fluentui-react-infobutton-37b75f9d-f4c1-4c94-b80c-7f1dc80591d6.json
- packages/react-components/react-infobutton/src/components/InfoButton/InfoButton.test.tsx
- packages/react-components/react-infobutton/src/components/InfoButton/useInfoButtonStyles.ts
* InfoButton didn't have vr-tests.
* InfoButton had a border when using Teams HCM due to `tokens.colorTransparentStroke`.
* InfoButton now has vr-tests.
* InfoButton no longer has a border in Teams HCM.
* Fixes #26270
> chore(react-infobutton): Add vr tests for InfoButton

- change/@fluentui-react-table-de6b4151-670a-4292-8e84-bd8a4e72f175.json
- packages/react-components/react-data-grid-react-window/etc/react-data-grid-react-window.api.md
- packages/react-components/react-data-grid-react-window/package.json
- packages/react-components/react-data-grid-react-window/src/components/DataGridBody/DataGridBody.tsx
- packages/react-components/react-data-grid-react-window/src/components/DataGridBody/DataGridBody.types.ts
- packages/react-components/react-data-grid-react-window/src/components/DataGridBody/renderDataGridBody.tsx
- packages/react-components/react-data-grid-react-window/src/components/DataGridBody/useDataGridBody.ts
- packages/react-components/react-data-grid-react-window/src/components/DataGridBody/useDataGridBodyStyles.ts
- packages/react-components/react-table/etc/react-table.api.md
- packages/react-components/react-table/src/components/DataGridBody/DataGridBody.tsx
- packages/react-components/react-table/src/components/DataGridBody/DataGridBody.types.ts
- packages/react-components/react-table/src/components/DataGridRow/DataGridRow.tsx
- packages/react-components/react-table/src/components/DataGridRow/DataGridRow.types.ts
- packages/react-components/react-table/stories/DataGrid/Default.stories.tsx
- packages/react-components/react-table/stories/DataGrid/MultipleSelect.stories.tsx
- packages/react-components/react-table/stories/DataGrid/MultipleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/DataGrid/RowNavigation.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SelectionAppearance.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SingleSelect.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SingleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/DataGrid/Sort.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SortControlled.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SubtleSelection.stories.tsx
- packages/react-components/react-table/stories/DataGrid/Virtualization.stories.tsx
Render functions arguments for DataGrid are no longer typed with any and need to be explicitly typed. The PR introduces support for generic JSX to help with this.
```diff
<DataGrid
items={items}
columns={columns}
sortable
selectionMode="multiselect"
getRowId={item => item.file.label}
onSelectionChange={(e, data) => console.log(data)}
>
<DataGridHeader>
<DataGridRow selectionCell={{ 'aria-label': 'Select all rows' }}>
-          {({ renderHeaderCell }: TableColumnDefinition<Item>) => (
-            <DataGridHeaderCell>{renderHeaderCell()}</DataGridHeaderCell>
-          )}
+          {({ renderHeaderCell }) => <DataGridHeaderCell>{renderHeaderCell()}</DataGridHeaderCell>}
</DataGridRow>
</DataGridHeader>
-      <DataGridBody>
+      <DataGridBody<Item>>
-       {({ item, rowId }: …
```
> BREAKING(DataGrid): render functions need to by typed

- change/@fluentui-react-table-df5a4037-978d-47fd-806e-51e0efbe1ea3.json
- packages/react-components/react-table/src/components/TableCell/useTableCellStyles.ts
- packages/react-components/react-table/src/components/TableCellActions/useTableCellActionsStyles.ts
- packages/react-components/react-table/src/components/TableRow/useTableRowStyles.ts
- packages/react-components/react-table/stories/Table/SelectionWithCellActions.stories.tsx
- packages/react-components/react-table/stories/Table/index.stories.tsx
Also adds a selection example with cell actions to handle event propagation
Fixes #26202
> fix(TableCellActions): Background should match rown on hover and active

- packages/react-components/react-table/stories/DataGrid/CustomRowId.stories.tsx
- packages/react-components/react-table/stories/DataGrid/Default.stories.tsx
- packages/react-components/react-table/stories/DataGrid/MultipleSelect.stories.tsx
- packages/react-components/react-table/stories/DataGrid/MultipleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/DataGrid/RowNavigation.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SelectionAppearance.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SingleSelect.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SingleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/DataGrid/Sort.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SortControlled.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SubtleSelection.stories.tsx
- packages/react-components/react-table/stories/DataGrid/Virtualization.stories.tsx
- packages/react-components/react-table/stories/Table/MultipleSelect.stories.tsx
- packages/react-components/react-table/stories/Table/MultipleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/Table/SingleSelect.stories.tsx
- packages/react-components/react-table/stories/Table/SingleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/Table/Sort.stories.tsx
- packages/react-components/react-table/stories/Table/SortControlled.stories.tsx
- packages/react-components/react-table/stories/Table/SubtleSelection.stories.tsx
- packages/react-components/react-table/stories/Table/Virtualization.stories.tsx
The intention of memoized columns was to make the code visible in `show code` button of the docsite. However this can encourage bad practices like memoizing when not necessary.
Fixes #26297
> docs: Hoist columns above react code

- packages/react-components/react-table/stories/Table/Memoization.stories.tsx
- packages/react-components/react-table/stories/Table/index.stories.tsx
Adds an example where selectable table rows are memoized. When a row's selection changes, only that affected row is re-rendered.
* Fixes #26206
> docs: Add row memoization example

- .github/ISSUE_TEMPLATE/convergence_epic.md
I have reviewed the convergence epic to verify it matches the currently intended process.
Added `bug bash` item to both the checklist and [wiki](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#bug-bash).
I also documented the [versioning workflow](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#versioning-overview):
1. component prototype might be released as `alpha`, without exporting from `react-components`.
2. after initial implementation, it is released as `beta`, re-exported from `react-components/unstable`.
3. after validation, it is released as final, re-exported from `react-components`.
This matches [Fluent UI React Component Lifecycle - DEV Community 👩‍💻👨‍💻](https://dev.to/paulgildea/fluent-ui-react-component-lifecycle-29n5).
> chore: Add bug bash to convergence checklist

- change/@fluentui-react-tabster-5065c018-0a25-4a76-9359-7f114ddf23e8.json
- packages/react-components/react-tabster/etc/react-tabster.api.md
- packages/react-components/react-tabster/src/hooks/useModalAttributes.ts
Add `id` to `useModalAttributes` to allow consumer to specify modalizer id.
This will come in handy with the tabster feature that allows multiple DOM element being in the same modalizer by sharing the same id.
> feat(react-tabster): add id to useModalAttributes options

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Chat/ChatMessage.tsx
- packages/fluentui/react-northstar/test/specs/components/Chat/ChatMessage-test.tsx
The ChatMessage action menu position in RTL languages was the same as in LTR, starting horizontally at the end of the message element.
In RTL, it should be placed at the start of the message element.
* Fixes #
> fix(react-northstar)(ChatMessage): action menu positioning in RTL

- apps/vr-tests-react-components/package.json
- apps/vr-tests-react-components/src/stories/Portal.stories.tsx
- change/@fluentui-react-portal-64ab0884-f002-4c94-aef1-124662da7cb1.json
- packages/react-components/react-portal/src/components/Portal/usePortalMountNode.ts
Fixes #25432 again
`useInsertionEffect` will run before DOM has been mounted. However, the fallback `useIsomorphicLayoutEffect` will still trigger the problem in React 17 and below.
Adds 2 different code paths for React 18 and below. React 18 will use `useInsertionEffect` which is strict mode safe. React 17 will still use `useMemo`.
This will result in extra code in the bundle but, means we are using correct API in future versions of React
> fix: Styles should be inserted on portal at render time

- change/@fluentui-web-components-25e8f64c-845e-401f-a7f8-c9472a5720df.json
- packages/web-components/docs/api-report.md
- packages/web-components/package.json
- packages/web-components/src/badge/badge.definition.ts
- packages/web-components/src/badge/badge.options.ts
- packages/web-components/src/badge/badge.stories.ts
- packages/web-components/src/badge/badge.styles.ts
- packages/web-components/src/badge/badge.template.ts
- packages/web-components/src/badge/badge.ts
- packages/web-components/src/badge/define.ts
- packages/web-components/src/badge/index.ts
- packages/web-components/src/counter-badge/counter-badge.definition.ts
- packages/web-components/src/counter-badge/counter-badge.options.ts
- packages/web-components/src/counter-badge/counter-badge.stories.ts
- packages/web-components/src/counter-badge/counter-badge.styles.ts
- packages/web-components/src/counter-badge/counter-badge.template.ts
- packages/web-components/src/counter-badge/counter-badge.ts
- packages/web-components/src/counter-badge/define.ts
- packages/web-components/src/counter-badge/index.ts
- packages/web-components/src/index.ts
- packages/web-components/src/styles/index.ts
- packages/web-components/src/styles/partials/badge.partials.ts
- packages/web-components/src/styles/partials/index.ts
Badge did not exist as a Fluent 2 aligned web component for v3.
Now it does - and so does CounterBadge!
n/a
* Fixes #
> feat: add badge and counter badge as new components

- apps/public-docsite/src/pages/Styles/Colors/palettes/Excel.tsx
Internally at Microsoft we have determined that the hex codes depicted as the product colors for Microsoft Excel require an update. The update will ensure that users get the best experience developing apps for the Excel ecosystem.
Current colors available here https://developer.microsoft.com/en-us/fluentui#/styles/web/colors/products
Excel Shade 20 #004b1c
Excel Shade 10 #0e5c2f
Excel Primary #217346
Excel Tint 10 #3f8159
Excel Tint 20 #4e9668
Excel Tint 30 #6eb38a
Excel Tint 40 #9fcdb3
Excel Tint 50 #e9f5ee
New hex color codes available here https://developer.microsoft.com/en-us/fluentui#/styles/web/colors/products
* Fixes https://github.com/microsoft/fluentui/issues/26337
> Update hex color codes for MS Excel product

- packages/react-components/react-migration-v0-v9/package.json
Fix `@fluentui/react-components` version in the `react-migration-v0-v9` package.
> fix: react components version in migration shim package

- .github/CODEOWNERS
Packages previously owned by the microsoft/fluent-date-time team are now owned by microsoft/cxe-red, updating the CODEOWNERS file to reflect this
> Update ownership of date-time packages

- change/@fluentui-react-progress-d61e18f8-f765-4611-92ed-4d9630561ce2.json
- packages/react-components/react-progress/etc/react-progress.api.md
- packages/react-components/react-progress/src/components/ProgressBar/ProgressBar.types.ts
- packages/react-components/react-progress/src/components/ProgressBar/useProgressBarStyles.ts
- packages/react-components/react-progress/stories/ProgressBar/ProgressBarDescription.md
- packages/react-components/react-progress/stories/ProgressBar/ProgressBarShape.stories.tsx
```jsx
<ProgressBar shape="rectangular" />
```
The `rectangular` shape is inconsistent with all other components which use `'rounded' | 'circular' | 'square'`
```jsx
<ProgressBar shape="square" />
```
The `shape` prop now accepts `'rounded' | 'square'`
> fix(ProgressBar): rename rectangular shape to square

- change/@fluentui-react-field-c0f37c59-769b-4ad0-abdd-a19f0986fdba.json
- packages/react-components/react-field/src/components/Field/useFieldStyles.ts
There is insufficient padding between the Field and its input component. See #26223 for more details.
Update padding of Field's label to match the visual spec.
* Fixes #26223
> fix: Update Field label padding to match spec

- change/@fluentui-react-field-5e8c8b4f-2cf4-48b1-bbff-5c5191886ff5.json
- packages/react-components/react-field/src/components/Field/useFieldStyles.ts
Components inside a Field are their natural width; not the full width of the Field's div.
The component within a field stretches to fill the whole width of the field. The field itself can be resized to the desired width of the component, label, hint, etc.
* Fixes #26224
> fix: Stretch Field components to full width

- change/@fluentui-react-field-ee01fe61-b500-4b36-a794-0fa4365aafe3.json
- packages/react-components/react-field/src/components/Field/Field.test.tsx
- packages/react-components/react-field/src/components/Field/useField.tsx
Field error messages are not announced by screen readers when they appear.
Add `role="alert"` to the field's validation message when it is an error, so that it is read by screen readers.
* Fixes #26032
> fix: Field sets role="alert" on its error message so it is announced by screen readers

- packages/react-components/react-combobox/stories/Combobox/ComboboxComplexOptions.stories.tsx
- packages/react-components/react-combobox/stories/Combobox/ComboboxFiltering.stories.tsx
- packages/react-components/react-combobox/stories/Combobox/ComboboxFreeform.stories.tsx
- packages/react-components/react-combobox/stories/Combobox/ComboboxMultiselectWithValueString.stories.tsx
- packages/react-components/react-combobox/stories/Dropdown/DropdownComplexOptions.stories.tsx
This PR only touches stories, and makes a few accessibility fixes:
- Fixes #26315 by adding a "no results found" fallback item in the filtering example
- Fixes #26317 by updating the freeform custom string option in the freeform example
- Fixes #26320 by adding better warning language for the multiselect w/ value text example
- Fixes #26314 by setting the Persona avatar to `aria-hidden`
> fix: react-combobox examples a11y updates

- change/@fluentui-react-components-07ca147c-df50-4259-9ea4-4939cedbc454.json
- packages/react-components/react-components/src/Concepts/Icons/ReactIconGrid.tsx
Adds the ability to use the search engine on
the docs page even for the "Unsized" icons.
* Fixes #
> docs: make unsized icons searchable

- change/@fluentui-react-table-c5aef9c7-f255-40b3-923f-df603517898e.json
- packages/react-components/react-table/stories/DataGrid/CustomRowId.stories.tsx
- packages/react-components/react-table/stories/DataGrid/DataGridDescription.md
- packages/react-components/react-table/stories/DataGrid/Default.stories.tsx
- packages/react-components/react-table/stories/DataGrid/MultipleSelect.stories.tsx
- packages/react-components/react-table/stories/DataGrid/MultipleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/DataGrid/RowNavigation.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SelectionAppearance.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SingleSelect.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SingleSelectControlled.stories.tsx
- packages/react-components/react-table/stories/DataGrid/Sort.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SortControlled.stories.tsx
- packages/react-components/react-table/stories/DataGrid/SubtleSelection.stories.tsx
- scripts/storybook/src/utils.js
```ts
import { PresenceBadgeStatus, Avatar, DataGridBody, DataGridRow, DataGrid, DataGridHeader, DataGridHeaderCell, DataGridCell, TableColumnDefinition, createTableColumn, SortState } from "@fluentui/react-components";
```
This PR fixes the config that was outdated.
```ts
import { PresenceBadgeStatus, Avatar } from "@fluentui/react-components";
import { DataGridBody, DataGridRow, DataGrid, DataGridHeader, DataGridHeaderCell, DataGridCell, TableCellLayout, TableColumnDefinition, createTableColumn } from '@fluentui/react-components/unstable';
```
Also fixes imports in `DataGrid` stories.
Fixes #26433
> docs: fix config for import rewrites for Storybook export

- change/@fluentui-react-components-79b19460-fc74-43b0-ab6b-93273a9373a5.json
- change/@fluentui-react-textarea-e883e997-b8a8-47fe-afd4-cef302188893.json
- packages/react-components/react-components/etc/react-components.api.md
- packages/react-components/react-components/src/index.ts
- packages/react-components/react-textarea/etc/react-textarea.api.md
- packages/react-components/react-textarea/src/components/Textarea/Textarea.types.ts
- packages/react-components/react-textarea/src/index.ts
This PR exports `TextareaOnChangeData` like in other components:
https://github.com/microsoft/fluentui/blob/c075fab840bf34761b3b8dfc2e37de1ad2ac23fc/packages/react-components/react-components/src/index.ts#L291
https://github.com/microsoft/fluentui/blob/c075fab840bf34761b3b8dfc2e37de1ad2ac23fc/packages/react-components/react-components/src/index.ts#L307
Fixes #26405
> feat: export TextareaOnChangeData type

- change/@fluentui-react-toolbar-93622f01-7cbf-4851-b29d-d944254e3166.json
- packages/react-components/react-toolbar/src/index.ts
useToolbarButtonStyles_unstable and useToolbarButton_unstable are exported as Typescript types but they are functions, not types.
useToolbarButtonStyles_unstable and useToolbarButton_unstable are exported as functions.
> fix: react-toolbar exports

- change/@fluentui-react-button-f9384ea2-7591-4d5c-88a4-44fc94e15575.json
- packages/react-components/react-button/src/components/ToggleButton/useToggleButtonStyles.ts
Fixes #26062, depends on #26089 to work for all appearance variants
The ToggleButton high contrast mode focus outline isn't showing up for two reasons:
1. The style was overridden by the second call of `createCustomFocusIndicatorStyle` for circular/small/large/etc. appearance variants, which is fixed in #26089
2. The former `highContrastFocusStyles` is never applied
I moved the styles in `highContrastFocusStyles` to the `:focus` selector within the HCM media query
> fix: Toggle button high contrast mode focus outline

- change/@fluentui-react-combobox-180e14ee-bb08-41bc-ae39-3046c6fa0c5e.json
- packages/react-components/react-combobox/src/components/Combobox/useComboboxStyles.ts
- packages/react-components/react-combobox/src/components/Dropdown/useDropdownStyles.ts
- packages/react-components/react-combobox/src/components/Listbox/useListboxStyles.ts
- The listbox popup did not have a max-height, so grew with its contents past the screen height. Now it's set to `80vh`
- box-shadow and border-radius were defined in `useListboxStyles`. Those have been moved to `useComboboxStyles` and `useDropdownStyles` so Listbox can be more easily re-used in different contexts (and because the shadow and border-radius are more tied to the popup, not the listbox)
Max-height is part of #26069
Shadow styles are part of #25866
> fix: react-combobox add listbox max-height and shift shadow style location

- change/@fluentui-fluent2-theme-943b3afc-4b98-42b7-ac96-c53550f16473.json
- packages/fluent2-theme/src/componentStyles/Button.styles.ts
Adds Fluent 2 styles for v8 SpinButton to match v9 implementation
- Rounds right top and right bottom menu button corners.
- Extends vertical divider to top and bottom of button.
Fixes #26269
> Adds Fluent 2 styles for v8 SpinButton

- packages/react-components/react-combobox/stories/Combobox/ComboboxComplexOptions.stories.tsx
- packages/react-components/react-combobox/stories/Combobox/ComboboxCustomOptions.stories.tsx
- packages/react-components/react-combobox/stories/Dropdown/DropdownComplexOptions.stories.tsx
- packages/react-components/react-combobox/stories/Dropdown/DropdownCustomOptions.stories.tsx
- packages/react-components/react-combobox/stories/Dropdown/DropdownDefault.stories.tsx
Examples-only PR. This takes care of a bunch of the examples/story items in #26069
-  Updates "JSX children" wording for complex options stories
- More detailed description for the custom options stories
- Spread the OptionGroup props in the custom options story
- Caterpillar was misspelled in the default dropdown story
> fix: react-combobox story fixes and docs wording updates

- change/@fluentui-react-combobox-b23addfc-cfb1-42ee-801e-f921ac020168.json
- packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx
- packages/react-components/react-combobox/src/utils/useComboboxBaseState.ts
There were two behavior issues with the `aria-activedescendant` calculation in combobox:
1. When the author mutated Option children while open, the active option was not recalculated
Now, when the children are changed while open and there is no current active option, combobox resets the active option.
Fixes #26316
2. A screen reader bug prevents the input value from being read while an `aria-activedescendant` association is present for JAWS & NVDA
While this should work out of the box, there's also a relatively easy fix we can do -- `aria-activedescendant` attribute (but not internal state) is cleared with left/right arrows, and it is restored with any other keyboard interaction. Home/end do not apply here, since they do listbox interactions. I left a comment by the relevant code, so if …
> fix: react-combobox activedescendant calculation updates

- change/@fluentui-react-provider-8fc63cd5-dc28-483f-8ea9-04cd91d6d69c.json
- change/@fluentui-react-utilities-e64decea-bd78-44df-85fb-6e83069ecd84.json
- packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderThemeStyleTag.ts
- packages/react-components/react-utilities/src/hooks/useId.ts
We generate our own ids and use a context to keep track of server vs client id generation.
We still have the previous behavior, but we now check if `React.useId` is available (React 18+) and use it when available. This will help fix issues with React 18+ when using SSR and/or strictmode. This is due to `React.useId` being aware of strictmode and SSR.
> **Note**: React's `useId` hook uses `:` for its generated id, this is a problem for us since we use ids as class names when loading up our theme css vars. To fix this issue, we have to add a backslash to the className when inserting it into the style tag turning `:` to `\:`.
* Fixes #23620
> fix: Update `useId` to work correctly in React 18 and React 18 strictmode

- change/@fluentui-react-32aa49c5-bacb-44c3-998b-5fe09a293db0.json
- packages/react-examples/src/react/ComboBox/docs/ComboBoxBestPractices.md
- packages/react-examples/src/react/Dropdown/docs/DropdownBestPractices.md
- packages/react/src/components/ComboBox/ComboBox.types.ts
Docs update related to a misunderstanding around `onRenderUpperContent` & `onRenderLowerContent`. I've added docs wording both to those two props, and to the best practices section of v8's Combobox and Dropdown to make it clearer that miscellaneous interactive content is not supported.
> chore: update v8 ComboBox & Dropdown docs to explicitly prohibit nested interactive content

- change/@fluentui-react-button-f3600003-d5e8-4448-b335-4a0ff4c76dfd.json
- packages/react-components/react-button/etc/react-button.api.md
- packages/react-components/react-button/src/components/Button/Button.types.ts
- packages/react-components/react-button/src/components/Button/useButton.ts
- packages/react-components/react-button/src/contexts/ButtonContext.ts
- packages/react-components/react-button/src/contexts/index.ts
- packages/react-components/react-button/src/index.ts
Inspired on `AvatarContext` implementation https://github.com/microsoft/fluentui/pull/24790. Some components such as `TableCell` require to modify `Avatar` default size. This PR creates `ButtonContext` to allow other components to modify the default size of a button (this will be required for `TreeItem`, since a `TreeItem` action will be a button that by default will be `small` sized).
> feat(react-button): creates ButtonContext

- packages/react-components/react-tree/etc/react-tree.api.md
- packages/react-components/react-tree/src/components/Tree/Tree.types.ts
- packages/react-components/react-tree/src/components/Tree/renderTree.tsx
- packages/react-components/react-tree/src/components/Tree/useTree.ts
- packages/react-components/react-tree/src/components/Tree/useTreeContextValues.ts
- packages/react-components/react-tree/src/components/TreeItem/TreeItem.types.ts
- packages/react-components/react-tree/src/components/TreeItem/__snapshots__/TreeItem.test.tsx.snap
- packages/react-components/react-tree/src/components/TreeItem/renderTreeItem.tsx
- packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx
- packages/react-components/react-tree/src/components/TreeItem/useTreeItemStyles.ts
- packages/react-components/react-tree/src/contexts/treeContext.ts
- packages/react-components/react-tree/stories/Tree/TreeActions.stories.tsx
- packages/react-components/react-tree/stories/Tree/TreeBadges.stories.tsx
- packages/react-components/react-tree/stories/Tree/TreeControllingOpenAndClose.stories.tsx
- packages/react-components/react-tree/stories/Tree/TreeDefault.stories.tsx
- packages/react-components/react-tree/stories/Tree/TreeDefaultOpenTrees.stories.tsx
- packages/react-components/react-tree/stories/Tree/TreeExpandIcon.stories.tsx
- packages/react-components/react-tree/stories/Tree/TreeIconAfter.stories.tsx
- packages/react-components/react-tree/stories/Tree/TreeIconBefore.stories.tsx
Previous implementation would require the usage of `aria-owns` to properly set and organize items on a tree, something similar to the example provided on https://www.w3.org/WAI/ARIA/apg/example-index/treeview/treeview-navigation.html
After some investigation and pairing with @smhigley the conclusion is that depending on `aria-owns` is not ideal as it is not a supported solution by all screen readers. The ideal would be to nest each subtree inside of the tree item it belongs to. as in  this example https://www.w3.org/WAI/ARIA/apg/example-index/treeview/treeview-1/treeview-1b.html 
This PR updates the `Tree` and `TreeItem` component to properly follow this structural modification.
> chore(react-tree): stops using aria-owns to organize tree

- change/@fluentui-web-components-06188225-69da-4cf6-918c-932a9ceab1b3.json
- change/@fluentui-web-components-06a3ebaf-3485-4ea9-a024-ff17305e1f88.json
- change/@fluentui-web-components-0b247950-52cb-4f3a-a1c3-9455ef090098.json
- change/@fluentui-web-components-19128575-ce2e-40b1-8a3b-8334eb585f40.json
- change/@fluentui-web-components-25e8f64c-845e-401f-a7f8-c9472a5720df.json
- change/@fluentui-web-components-7d0424dc-fe77-4d05-b911-295ca60d04fd.json
- change/@fluentui-web-components-925986c6-b42e-4db6-a621-44ff55110a4f.json
- change/@fluentui-web-components-974b7e3c-cb82-4399-8daf-f58a9a1b23ed.json
- change/@fluentui-web-components-a9829849-1747-4588-aadf-da70207d0cf0.json
- change/@fluentui-web-components-d423d05a-1b1e-422f-ab9a-afc288197681.json
- packages/web-components/CHANGELOG.json
- packages/web-components/CHANGELOG.md
- packages/web-components/package.json
Automated nightly releases have been blocked since Dec 26th, which created lot of on hold pipelines.
Enabling those this week caused probably npm release parallel race conditions leading into not release pipeline failing 
I manually ran bump on local machine via command 
`yarn beachball bump -b origin/web-components-v3 --access public --no-fetch --no-publish --no-push --no-git-tags --verbose --config ./scripts/beachball/release-web-components.config.js`
This PR are changes created by bump. This should hopefully resolve any upcoming releases
> chore(web-components): run manually bump to fix failed CI release

- change/@fluentui-web-components-cd25bca5-3470-4f00-b462-08403e27845d.json
- packages/web-components/docs/api-report.md
- packages/web-components/src/index.ts
`setTheme()` was not exported by the `@fluentui/web-components` package
Theme related functionality is now exported
> feat(web-components): export theme

- apps/ssr-tests/package.json
- apps/stress-test/package.json
- change/@fluentui-web-components-84f7b31a-225a-4684-b0fa-195c17676891.json
- package.json
- packages/web-components/package.json
- yarn.lock
- web-components is using olg tslib v1. The reasoning behind was that some OSS folks on FAST were using [Typescript v3.9](https://github.com/microsoft/tslib/releases/tag/2.0.0). 
- web-components is ignored from syncpack dependency checks which allows us to introduce deps inconsistencies 
- web-components now depend on tslib v2 to align with rest of monorepo and as previous restriction is no longer in place
- web-components is part of syncpack dep check
* Follows https://github.com/microsoft/fluentui/issues/21395
> feat(web-components): bump tslib to 2.1. to align with rest of monorepo packages

- change/@fluentui-react-avatar-29e5243e-cd62-4acb-8605-0b2f5b2d2de8.json
- change/@fluentui-react-components-cf661b97-d1aa-4af8-a344-231de7d0a8cb.json
- change/@fluentui-react-table-c53b834d-420e-4807-95cf-e9d6becd73a0.json
- packages/react-components/react-avatar/etc/react-avatar.api.md
- packages/react-components/react-avatar/src/components/Avatar/Avatar.types.ts
- packages/react-components/react-avatar/src/components/AvatarGroup/AvatarGroup.types.ts
- packages/react-components/react-avatar/src/components/AvatarGroupItem/AvatarGroupItem.types.ts
- packages/react-components/react-avatar/src/components/AvatarGroupItem/useAvatarGroupItemStyles.ts
- packages/react-components/react-avatar/src/components/AvatarGroupPopover/AvatarGroupPopover.types.ts
- packages/react-components/react-avatar/src/contexts/AvatarContext.ts
- packages/react-components/react-avatar/src/index.ts
- packages/react-components/react-avatar/stories/AvatarGroup/AvatarGroupSizePie.stories.tsx
- packages/react-components/react-avatar/stories/AvatarGroup/AvatarGroupSizeSpread.stories.tsx
- packages/react-components/react-avatar/stories/AvatarGroup/AvatarGroupSizeStack.stories.tsx
- packages/react-components/react-components/etc/react-components.api.md
- packages/react-components/react-components/src/index.ts
- packages/react-components/react-table/etc/react-table.api.md
- packages/react-components/react-table/src/components/TableCellLayout/TableCellLayout.types.ts
- packages/react-components/react-tree/etc/react-tree.api.md
- packages/react-components/react-tree/src/components/TreeItemPersonaLayout/TreeItemPersonaLayout.types.ts
This PR is a follow up on https://github.com/microsoft/fluentui/pull/26478#discussion_r1085998580
1. Marks `AvatarSizes` as deprecated in favor of `AvatarSize`
2. Updates usages of it on `react-table`
3. Updates usages of it on `react-tree`
4. Exports `AvatarSize` in react-components
> chore(react-avatar): deprecates AvatarSizes in favor of AvatarSize

- azure-pipelines.release.web-components.yml
- change/@fluentui-web-components-925986c6-b42e-4db6-a621-44ff55110a4f.json
- change/@fluentui-web-components-cd25bca5-3470-4f00-b462-08403e27845d.json
- change/@fluentui-web-components-f4ad3059-b14e-4647-bef9-7f9458e4f9ab.json
- packages/web-components/CHANGELOG.json
- packages/web-components/CHANGELOG.md
- packages/web-components/package.json
- auth for git pushes was not sufficient
- pipeline should now have proper auth for pushes 
- manual bump to mirror effects that happened on ci with release but didn't came to origin
Follows https://github.com/microsoft/fluentui/pull/26498
> ci: fix github pushes auth for release

- change/@fluentui-react-combobox-d3f9321b-0669-426c-8389-04429b748f99.json
- packages/react-components/react-combobox/src/components/Listbox/useListboxStyles.ts
- packages/react-components/react-combobox/src/components/Option/__snapshots__/Option.test.tsx.snap
- packages/react-components/react-combobox/src/components/Option/useOption.tsx
- packages/react-components/react-combobox/src/components/Option/useOptionStyles.ts
Fixes #26508
Based on design feedback, we want the multiselect checkboxes to match the Checkbox component, instead of using the icons.
Also adds a 1px transparent outline to the listbox to improve high contrast mode visibility.
> fix: update react-combobox multiselect checkbox styles to match Checkbox

- change/@fluentui-react-link-7ca1987a-7983-4dc5-a459-671fe626c214.json
- packages/react-components/react-link/src/components/Link/Link.test.tsx
- packages/react-components/react-link/src/components/Link/useLinkState.ts
```tsx
<Link tabIndex={-1} href="https://www.bing.com" />
```
⬇️⬇️⬇️
```html
<a href="https://www.bing.com" tabindex="0"></a>
```
💣 
```tsx
<Link tabIndex={-1} href="https://www.bing.com" />
```
⬇️⬇️⬇️
```html
<a href="https://www.bing.com" tabindex="-1"></a>
```
User's input should always win over our defaults ✅ 
Fixes #26313
> fix(Link): Handle "tabIndex" from user's input

- change/@fluentui-react-f1a80b64-01ed-4cb6-83c3-9495c9a74e31.json
- change/@fluentui-style-utilities-ac20774e-9182-46f1-ac57-70faa326aa8d.json
- change/@fluentui-style-utilities-e38fbe70-986a-42a7-b9d2-396683f75220.json
- packages/react/src/components/Button/SplitButton/SplitButton.styles.ts
- packages/style-utilities/etc/style-utilities.api.md
- packages/style-utilities/src/interfaces/IGetFocusStyles.ts
- packages/style-utilities/src/styles/getFocusStyle.ts
`SplitButton` renders two `button` elements inside a `div`:
```html
div
button
button
```
When the `SplitButton` is focused, `:after` pseudoelement is added to the wrapping `div` to display a focus ring around both buttons - this now captures all the events:
- when hovered, arrow mouse cursor is used instead of the pointer
- it is not possible to click the secondary button
I've added `pointer-events: none` to the focus styles so that it passes through all the mouse events.
For `SplitButton`, that means that when it is focused:
- the focus ring is displayed as before
- user can press Enter or Space to press the primary button (as before)
- user can press Alt/Option + Down Arrow to open the Menu (as before)
- user can click primary button (as before)
- user can click the secondary button …
> fix(react): No pointer events on focus ring

- packages/react-components/react-tree/etc/react-tree.api.md
- packages/react-components/react-tree/package.json
- packages/react-components/react-tree/src/components/TreeItem/TreeItem.types.ts
- packages/react-components/react-tree/src/components/TreeItem/renderTreeItem.tsx
- packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx
- packages/react-components/react-tree/src/components/TreeItem/useTreeItemContextValues.ts
Introduces `ButtonContext` around `actions` slot to ensure proper button default size value as `small` as it's required by design specs.
> feat(react-tree): uses ButtonContext to modify default button size

- apps/vr-tests-react-components/src/stories/Combobox.stories.tsx
- apps/vr-tests-react-components/src/stories/Dropdown.stories.tsx
Adds both Combobox and Dropdown VR tests (both include essentially the same tests, since the typability of combobox does not affect what would be included in snapshot tests)
> feat: add combo and dropdown vr tests

- change/@fluentui-react-persona-d5166e84-0f0c-4a5c-836f-4230ede932a3.json
- packages/react-components/react-persona/src/components/Persona/usePersonaStyles.ts
This request was made so that when using two lines only, the spacing between these lines is more cohesive with the Avatar.
> fix(react-persona): Reduce spacing between first and second line

- change/@fluentui-react-dialog-8b1f7572-249e-4619-8dcd-8688476b1763.json
- packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurfaceStyles.ts
- packages/react-components/react-dialog/src/contexts/constants.ts
Dialog used a hard coded value of `8px` for border radius.
Properly uses a token instead of a hard coded value.
* Fixes #26450
> chore: properly use tokens for border radius

- change/@fluentui-react-charting-2f20f310-a538-4c9b-b93c-be8158fe1c65.json
- packages/react-charting/src/components/LineChart/LineChart.base.tsx
- packages/react-charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
Some elements in line chart have duplicate ids
Elements in line chart have unique ids
> Fix duplicate-id accessibility issue in line chart

- package.json
- packages/fluentui/react-builder/package.json
- scripts/jest/src/jest.preset.v0.js
- scripts/jest/src/jest.preset.v0.spec.ts
- yarn.lock
- axe-core 3 and 4 are used within monorepo. 
- running tests on v0 if build snapshots are present produces double mock warnings 
- we use only axe-core 4 within monorepo (4.4.x in particular as that contains webpack 5 bug fix https://github.com/dequelabs/axe-core/blob/develop/CHANGELOG.md#bug-fixes-9)
- duplicate mocks violations warnings has been fixed in v0 tests
* Fixes https://github.com/microsoft/fluentui/issues/20799
* Follows https://github.com/microsoft/fluentui/issues/21395
> chore(react-builder): migrate to axe-core v4

- change/@fluentui-react-badge-89865f4b-4f22-47b4-ae63-6e60301303e0.json
- packages/react-components/react-badge/src/components/PresenceBadge/usePresenceBadgeStyles.ts
`border-radius` was defined with a percentage value of `50%`
Updates `border-radius` to properly use `borderRadiusCircular` token instead.
* Fixes #26450
> chore(react-badge): updates border-radius to use proper token value

- change/@uifabric-file-type-icons-b593d41a-81cf-4f36-8446-6dd7997cffb5.json
- packages/file-type-icons/README.md
- packages/file-type-icons/src/FileTypeIconMap.ts
- packages/file-type-icons/src/initializeFileTypeIcons.tsx
* filetype icons package was using old CDN URL, updated to new 1 CDN and latest version.
* clarified readme for filetype icons package
* added registration for clipchamp filetype icon
> filetype updates for loop, clipchamp [v7]

- change/@fluentui-react-file-type-icons-0c827b1a-956b-4cdd-bb59-a680ba7e2f79.json
- packages/react-file-type-icons/README.md
- packages/react-file-type-icons/src/FileTypeIconMap.ts
- packages/react-file-type-icons/src/initializeFileTypeIcons.tsx
* filetype icons package was using old CDN URL, updated to new 1 CDN and latest version.
* clarified readme for filetype icons package
* added registration for clipchamp filetype icon
> filetype updates for loop, clipchamp [master branch]

- change/@fluentui-react-efaa52aa-9b7f-4aab-8f44-65aa3b1d9807.json
- packages/react/etc/react.api.md
- packages/react/src/components/DetailsList/DetailsRow.base.tsx
- packages/react/src/components/DetailsList/DetailsRow.styles.ts
- packages/react/src/components/DetailsList/DetailsRow.types.ts
- packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
- packages/react/src/components/DetailsList/__snapshots__/DetailsListV2.test.tsx.snap
- packages/react/src/components/DetailsList/__snapshots__/DetailsRow.test.tsx.snap
There's a random 0-width static `<span role="checkbox">` at the end of every DetailsRow. It doesn't seem to do anything, and the check inside the first cell of the row already handles selection.
Because the random end-of-row checkbox is a direct child of the row, it causes an automated a11y failure (and if a screen reader user did actually navigate to it, it'd be super weird. It also doesn't have a label?).
No check.
Fixes #26330
> fix: remove invalid and unnecessary DetailsRow check

- package.json
- yarn.lock
This PR bumps the dependency. The new version fixes some of the CodeSandbox examples which were broken before.
https://github.com/microsoft/fluentui-storybook-addons/pull/26
Fixes #26181
https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/2856270
> chore: Bump storybook-addon-export-to-codesandbox to 0.8.1

- change/@fluentui-react-components-31797d7f-3bfb-4991-ab82-d4635515063a.json
- packages/react-components/react-components/etc/react-components.api.md
- packages/react-components/react-components/src/index.ts
`useFocusWithin()` hook is exported.
Fixes #25668.
> feat: re-export useFocusWithin() hook

- change/@fluentui-react-utilities-9259798e-d6da-420f-8da3-3bf377f4825b.json
- packages/react-components/react-utilities/etc/react-utilities.api.md
- packages/react-components/react-utilities/src/ssr/SSRContext.tsx
* fix the issue
* children prop now needs to be listed explicitly when defining props in React 18
* [How to Upgrade to React 18](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-typescript-definitions)
> fix: SSRProvider TypeScript definitions

- scripts/generators/generate-version-files.spec.ts
- scripts/generators/generate-version-files.ts
`generate-version-files` was not calling any logic on execution during release pipeline
`generate-version-files` properly executes logic during release
* Fixes https://github.com/microsoft/fluentui/issues/26526
> fix(scripts-generators): run generate-version-files logic on node execution

- change/@fluentui-react-components-817ab317-7384-4c3e-acaf-06eb10fa5f76.json
- change/@fluentui-react-tabs-0f215c5f-aaf8-4c1d-9283-40dac84261c3.json
- packages/react-components/react-components/etc/react-components.api.md
- packages/react-components/react-components/src/index.ts
- packages/react-components/react-tabs/etc/react-tabs.api.md
- packages/react-components/react-tabs/src/components/Tab/useTab.ts
- packages/react-components/react-tabs/src/components/Tab/useTabAnimatedIndicator.ts
- packages/react-components/react-tabs/src/components/TabList/TabList.tsx
- packages/react-components/react-tabs/src/components/TabList/TabListContext.ts
- packages/react-components/react-tabs/src/components/TabList/index.ts
- packages/react-components/react-tabs/src/components/TabList/renderTabList.tsx
- packages/react-components/react-tabs/src/components/TabList/useTabListContextValues.tsx
- packages/react-components/react-tabs/src/index.ts
- Updated react-tabs TabList context to follow same pattern as other components
- Exported context from component index
- Exported react-tabs context from react-components
This allows recomposition as the renderTabList method requires context values.
> Export react tabs context

- change/@fluentui-react-80a116b3-6d10-4c8e-9b19-923cb424f73c.json
- packages/react/src/components/Button/BaseButton.tsx
We had a timeout that set focus on the button after a touch tap. I'm not sure we actually need that, but one side effect was that for the SplitButton variant, it was re-setting focus to the trigger after the menu was opened with touch and focus set to the first item.
Focus is not called on the trigger after the timeout if the menu is open.
* Fixes [15545](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15545)
> fix: v8 SplitButton should not reset focus to trigger after opening menu

- change/@fluentui-react-94027d49-963c-4769-b134-8dc2632fe98c.json
- packages/react/src/components/Dropdown/Dropdown.styles.ts
- packages/react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
In High Contrast mode, the Button focus styles for outline offset caused it to be cut off by the edge of the Dropdown popup. The outline offset also caused the scrollbar to appear when the last option was focused. This is especially noticeable for the top/bottom options (and worse if there are only a few options in the Dropdown):
Sets the outline to be inset, so it always is visible:
* Fixes [15747](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15747)
> fix: v8 Dropdown option focus should not be cut off in HCM

- .storybook/preview.js
- package.json
- typings/storybook__addons/index.d.ts
- yarn.lock
Note: snippets will not have proper formatting till https://github.com/microsoft/fluentui-storybook-addons/pull/30.
Fixes #20367
> docs: use full source in "Show code"

- .github/workflows/pr-housekeeping.yml
* Follows https://github.com/microsoft/fluentui/pull/26581
> ci: use specific version of add-to-milestone as using v1 throws error

- .storybook/main.js
- apps/public-docsite-v9/.storybook/main.js
- apps/public-docsite-v9/README.md
- package.json
- scripts/storybook/src/index.d.ts
- scripts/storybook/src/index.js
- scripts/storybook/src/loaders/custom-loader.js
- scripts/storybook/src/rules.js
- scripts/storybook/src/rules.spec.ts
- scripts/storybook/src/utils.js
- yarn.lock
To be able to run `public-docsite-v9` one has to manually build all v8 and v0 packages. If any code is changed in v8 or v0 they again need to be re-build.
`yarn workspace @fluentui/public-docsite-v9 storybook` works without any build steps needed. Also any change in v8,v0 code will be reflected without any rebuilds.
This drastically improves DX for existing and new contributors !
- swc is now used instead of babel for ts,tsx,js transpilation and instead of Terser for minification, via https://github.com/Karibash/storybook-addon-swc
- why the swc move:
- speed 
- v8 and v0 contain code that is[impossible to transpile via babel](https://github.com/microsoft/fluentui/issues/25767) or because non trivial storybook babel-loader configuration that explodes on v0 code that uses [constructor …
> chore(public-docsite-v9): enable build-less DX for storybook

- apps/ssr-tests-v9/src/utils/getChromeVersion.ts
Most of CI failures we run into are triggered by ssr-test-v9 Timout error on browser open with puppeteer. This is temporary approach to monitor if opening it only once per pipeline for this app mitigates those intermittent errors on CI.
* Follows https://github.com/microsoft/fluentui/pull/26375
> fix(ssr-tests-v9): don't open browser twice on CI to potentially mitigate TIMEOUT issues

- apps/public-docsite-v9/package.json
docsite release fails because migration packages are not build (lage wont run those because they are not specified as dependencies
docsite have properly defined dependencies so release will succeed
* Follows https://github.com/microsoft/fluentui/pull/26571
> fix(public-docsite-v9): add migration packages as dependency to properly build when releasing

- apps/public-docsite/src/root.tsx
- change/@fluentui-public-docsite-setup-f65ab594-9c63-4e06-b925-0110463f3c03.json
- packages/public-docsite-setup/index.html
MWF styles have always caused clashes with our control styles, and after finding a clash that was nearly impossible to fix, we decided to try removing it completely from the site, as it appears to not be used by any of the site chrome.
> remove mwf styles

- change/@fluentui-eslint-plugin-9c309582-f6de-425d-bc96-c927db2786da.json
- packages/eslint-plugin/src/configs/base.js
- scripts/generators/create-component/index.ts
- tools/generators/migrate-converged-pkg/index.ts
`yarn create-component`
execution introduces sets package in invalid state:
- lint errors
- doesn't set export map correctly when executing on windows
`yarn create-component`
- empty `export {}` is being removed on 1st `create-component` execution
- `export * from` is expanded on every `create-component` run
- `migrate-converged-pkg` properly setups export maps when invoked on windows OS
- eslint-plugin `@fluentui/max-length` rule was turned off for v9 packages (it doesn't make much sense as we have prettier that will enforce line length automatically without any churn to the user (DX)
* Fixes https://github.com/microsoft/fluentui/pull/26529/commits/08c84ee99739e969e98e352d02a08fb0c8528c53
> fix(scripts-generators): make create-component work properly on windows and improve DX

- .github/workflows/azure-static-web-apps-deploy.yml
- change/@fluentui-web-components-b1d83acd-4849-4848-b056-d97f03b7c37c.json
- packages/web-components/.storybook/main.cjs
- storybook telemetry has been disabled to follow rest of monorepo setup
- web-components storybook is being deployed on every PR so reviewer can check his PR changes live
- web-components storybook is being deployed and published after merge to `web-components-v3` branch
> ci: setup web-components docsite CI/CD

- .github/workflows/azure-static-web-apps-deploy.yml
- secrets are not available on forks, thus removing those jobs
> ci: remove pull_request workflows from ASW WC

- change/@fluentui-react-infobutton-69f14ed0-88e3-4612-94cb-3734976c0c7e.json
- packages/react-components/react-infobutton/src/components/InfoButton/useInfoButton.tsx
- packages/react-components/react-infobutton/stories/Infobutton/InfoButtonWithLabel.stories.tsx
InfoButton's content was not focused when opened, this forced screen reader users to go through 2 more steps to get to content.
InfoButton's content is now focused when opened (it doesn't trap focus) so screen reader users are able to go through the text right away.
InfoButton with label example was also updated to have a more useful text.
* Related #26427
> chore(react-infobutton): Making InfoButton's content focusable and update example's text

- .devops/templates/cleanup.yml
Since component governance is forced, we should disable this step since it will remove all files from the working directory and fail component governance
> fix: Remove ReallyClean from CI pipelines

- change/@fluentui-priority-overflow-06e37a2f-4190-4541-9eba-5d513a0200da.json
- change/@fluentui-react-overflow-7c228aac-d8dc-4651-96ce-3b3b4b504c0f.json
- change/@fluentui-react-overflow-8b8469a8-30b4-4a4d-bc67-d168fd9e2362.json
- packages/react-components/priority-overflow/src/overflowManager.ts
- packages/react-components/react-overflow/etc/react-overflow.api.md
- packages/react-components/react-overflow/src/Overflow.cy.tsx
- packages/react-components/react-overflow/src/index.ts
- packages/react-components/react-overflow/src/overflowContext.ts
The dispatch process is done by analyzing the tops of the visibile and invisible queues. The update triggered after adding a new element might not be dispatched to the subscriber because the queue tops don't change. This can result in a desync between the visibility and the subscriber state.
Adds a `forceDispatch` flag which is used when new items are added while observing so that the next batched update will flush to subscribers even if queue tops don't change.
Fixes #23555
> fix: New overflow items all always dispatch updates to subscriber

- change/@fluentui-react-positioning-4bd82184-0e7b-46e8-a681-c87900b25568.json
- packages/react-components/react-positioning/src/createPositionManager.ts
Since `computePosition` is an async function, it can still resolve after the instance is destroyed.
Updates the destruction mechanism to have a [flag similar to poppver v2](https://github.com/floating-ui/floating-ui/blob/2893e9a8d2ebd895eb4311a8873afac62f75123e/src/createPopper.js#L171). This flag is used both on `forceUpdate` (to avoid memory leaks) and `computePosition` (to avoid applying outdated position).
> fix(createPositionManager): computePosition should not apply styles after destruction

- change/@fluentui-react-components-021b74de-76f6-4603-9855-fe12750eaf2e.json
- packages/react-components/react-components/etc/react-components.api.md
- packages/react-components/react-components/src/index.ts
Type was not exported
Type is exported. This type is used with slots when passing a render function.
> Export SlotRenderFunction type

- packages/react-examples/src/react/HoverCard/HoverCard.Target.Example.tsx
- packages/react-examples/src/react/HoverCard/docs/HoverCardBestPractices.md
Examples & docs only, no changes to the components
HoverCard defaults `directionalHintFixed` to `true`, which means if `directionalHint` is set, it will not adjust based on available space in the viewport. This only affects one example, the expanding HoverCard + target.
This PR explicitly sets `directionalHintFixed: false` in that example. I'm guessing there was a specific reason to pin cards to a position by default, so it seemed safer to avoid changing the default behavior, particularly in a specalized-use-case control.
I also added more documentation around both `directionalHintFixed`, and the ways in which HoverCard should not be considered an accessible mode of accessing content when used in isolation.
Fixes [15357](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15357 …
> fix: v8 HoverCard example adjusts to viewport, add a11y info to docs

- change/@fluentui-react-89173b86-4f03-440a-93e8-23c4c3569f3b.json
- packages/react/src/components/ComboBox/ComboBox.tsx
- packages/react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap
- packages/react/src/components/Dropdown/Dropdown.base.tsx
- packages/react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
We have `<Checkbox>` components for the multiselect options in Dropdown & ComboBox, which use the `<input type="checkbox">` element + `<label>`, but they override the role of the input element to be `role=option`.
VoiceOver automatically combines a label + checkbox input to be a single swipe stop, but adding `role="option"` interferes with that, so it reaches the checkbox and label text separately. Normally this wouldn't be a huge issue, but since this is used within a listbox, it is expected that everything reached within the listbox will be an option, and also the announcement of options is not much different from static text. The end result is that it is easy to assume the label itself is an option, and that the ComboBox/Dropdown isn't working because the label text doesn't respond to …
> fix: Dropdown/Combobox checkboxes have double swipe stops for some screen readers 

- change/@fluentui-react-badge-1d02e00e-35d1-4d9a-8f0e-9a522c35bd8d.json
- packages/react-components/react-badge/src/components/PresenceBadge/usePresenceBadge.tsx
- packages/react-components/react-badge/src/components/PresenceBadge/usePresenceBadgeStyles.ts
The `PresenceBadge` with `status="away"` and `outOfOffice={true}` is showing the wrong icon + color. According to the design specification it should have the same icon + color as the `status="outOfOffice"` `PresenceBadge`.
The `PresenceBadge` with `status="away"` and `outOfOffice={true}` is now showing the correct icon + color.
* Fixes part of #26036
> fix: Using correct icon and color for away + out-of-office PresenceBadge

- change/@fluentui-react-button-6070b42d-35c8-4c8a-b515-e0893216885b.json
- packages/react-components/react-button/src/components/Button/useButtonStyles.ts
- packages/react-components/react-button/src/components/CompoundButton/useCompoundButtonStyles.ts
- packages/react-components/react-button/src/components/SplitButton/useSplitButtonStyles.ts
- packages/react-components/react-button/src/components/ToggleButton/useToggleButtonStyles.ts
In HCM, we rendered all style variants with the same colors, including the primary button.
The primary button now has its own high contrast mode variant, using Highlight and HighlightText. The one exception is ToggleButton, where the primary variant stays the same as all other variants, so that the on/off states have enough of a distinction.
The PR includes tweaks for the new primary style for CompoundButton and SplitButton.
Fixes #26063
> fix: react-button high contrast mode primary variant

- change/@fluentui-react-spinbutton-1c9c635e-904e-4263-a839-99fe9fdb7ffe.json
- packages/react-components/react-spinbutton/stories/SpinButton/SpinButtonDescription.md
Storybook description for SpinButton did not include that it can also be used non-numerically
Storybook description for SpinButton includes that it can also be used non-numerically
* Fixes #26540
> Updated description for spin button

- packages/react-components/react-input/stories/Input/InputDisabled.stories.tsx
- packages/react-components/react-radio/stories/RadioGroup/RadioGroupDisabled.stories.tsx
Disabled stories for Input and RadioGroup had Label also set as disabled
Disabled stories for Input and RadioGroup had don't have Label set as disabled
* Fixes #26507
> removed disabled property from Label

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Dropdown/Dropdown.tsx
- packages/fluentui/react-northstar/test/specs/components/Dropdown/Dropdown-test.tsx
- packages/fluentui/react-northstar/test/specs/components/Dropdown/test-utils.tsx
clearable indicator was hidden and not keyboard accessible
remove aria-hidden, add key down handlers for Enter and Space
Fixes #26563 
Fixes #26258
> fix(Dropdown): Allow clear on Enter/Space press

- change/@fluentui-react-tabster-8a739d1e-a76c-4604-90e3-5ddb2d3da5fa.json
- packages/react-components/react-tabs/src/components/TabList/__snapshots__/TabList.test.tsx.snap
- packages/react-components/react-tabster/etc/react-tabster.api.md
- packages/react-components/react-tabster/src/hooks/useArrowNavigationGroup.ts
Add `unstable_hasDefault` option on `useArrowNavigationGroup` that allows user to specifies the mover group has default focusable item.
The user can assign default focusable item by:
```tsx
const defaultFocusableAttributes = useTabsterAttributes({
focusable: { isDefault: true },
});
<Button {...defaultFocusableAttributes} />
```
Related tabster PR: https://github.com/microsoft/tabster/pull/224
> feat(react-tabster): add `unstable_hasDefault` option on `useArrowNavigationGroup`

- apps/vr-tests-react-components/src/stories/Table.stories.tsx
- change/@fluentui-react-table-837a2183-555e-4693-9a8e-e3f1e89bed61.json
- packages/react-components/react-table/etc/react-table.api.md
- packages/react-components/react-table/src/components/TableCellLayout/TableCellLayout.types.ts
- packages/react-components/react-table/src/components/TableCellLayout/useTableCellLayout.ts
- packages/react-components/react-table/src/components/TableCellLayout/useTableCellLayoutStyles.ts
- packages/react-components/react-table/stories/Table/ResizableColumnsControlled.stories.tsx
- packages/react-components/react-table/stories/Table/ResizableColumnsUncontrolled.stories.tsx
User would have to implement this feature by adding custom styles
The prop `ellipsis` on `TableCellLayout` enables the ellipsis
* Fixes #26735
> feat: TableCellLayout component now supports truncate prop

- .storybook/main.js
- package.json
- yarn.lock
- storybook production builds mangle JS code
- swc generates different story names in the output 
- bumped storybook-addon-export-to-codesandbox which properly transforms production build export tokens
- mangle is turned off for storybook production build by default (via terser plugin 
). Swc minifier was mangling by default which was introducing property mangling that will cause VR test act on stories without explicit `storyName` randomly. Thus mangling is explicitly turned off within our configs as well.
* Fixes #26751
https://github.com/microsoft/fluentui-storybook-addons/pull/32
> fix(storybook): turn off mangling on production builds to provide same output as with Terser

- change/@fluentui-react-avatar-b5550fce-57c1-4cc6-8a4c-a8b22d9e4dd6.json
- packages/react-components/react-avatar/src/components/Avatar/Avatar.types.ts
Avatar's docs say the `name` is used to determine the initials displayed when there is no **icon**, which is incorrect: the initials are displayed when there is no **image**.
Fix doc comment for Avatar's `name` prop.
* Fixes #26601
> fix: Small mistake in docs for Avatar name prop

- change/@fluentui-react-provider-2dd88fac-fd7c-4313-98b8-3941d9399f42.json
- change/@fluentui-react-utilities-db7dae74-67ca-40d9-9548-f9b0965366c2.json
- packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderThemeStyleTag.ts
- packages/react-components/react-utilities/src/hooks/useId.ts
fixes #26651
When using React 18, our `useId` method calls React's `useId` conditionally.
Our `useId` method now generates the id first and then returns the string generated conditionally to avoid using the hook conditionally.
Our `useId` method now also removes colons from React 18's generated id to avoid issues when querying in JS or CSS.
* Fixes #26653
> fix(react-utilities, react-provider): Remove colons from generated id and fix hook order error in React 18

- change/@fluentui-react-charting-66596414-f3fe-4f18-a947-2f131b34c32c.json
- packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx
- packages/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChart.test.tsx.snap
Bar segments in VerticalStackedBarChart have an img role without an accessible text
Bar segments in VerticalStackedBarChart don't have an img role when the whole stack (bar) can be focused
> Fix svg-img-alt accessibility issue in vertical stacked bar chart

- change/@fluentui-react-charting-2b98d193-3938-4458-83e7-b27b31f6c8e9.json
- packages/react-charting/src/components/SankeyChart/SankeyChart.base.tsx
Node value was coming on link Hover
Link hover will show link value
* Fixes #
> Fixing wrong link hover value

- apps/public-docsite-v9/src/Concepts/StylingComponents.stories.mdx
- Removed ticks around Griffel in the introduction to make obvious it's a link
- Added a section about limitations which introduces the `shorthands` function and links to the Griffel docs
- Added missing ticks aroung `makeStyles` and `useStyles`
* Fixes #26179
> docs: Styling Component (v9) now introduces shorthands

- package.json
- yarn.lock
In 0.8.3, some of the CodeSandbox examples didn't contain dependency on fluentui.
0.8.4 fixes the issues with CodeSandbox dependencies:
- https://github.com/microsoft/fluentui-storybook-addons/pull/34
> chore: bump storybook-addon-export-to-codesandbox to 0.8.4

- change/@fluentui-react-e5a2ed84-a5b1-487d-bfc5-6fc93e0aa37a.json
- packages/react/src/components/DetailsList/DetailsRow.base.tsx
- packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
- packages/react/src/components/DetailsList/__snapshots__/DetailsListV2.test.tsx.snap
- packages/react/src/components/DetailsList/__snapshots__/DetailsRow.test.tsx.snap
For a long time, every `DetailsRow` component in a `DetailsList` has applied an override `width: ___px` rule in its root `style` attribute. This had been done in order to fix a render glitch when working with 'justified' layouts. However, the root issue was mitigated in calling apps, and instead this `width` override is producing sub-par visuals in most consumption sites of the list.
The effect has been that details rows always appear to 'under-fill' when using `fixedColumns` mode, even though the header properly stretches across the container.
Removed the override `style` attribute, so that the details rows fall back to their `min-width: 100%` rules, and thus the details rows nicely stretch across the container and align with the header.
If any components were relying on the input …
> Restore minimum width of Details List rows to be that of the container

- change/@fluentui-react-spinbutton-650c02b2-0132-46f6-8f55-dfbd03eaaa65.json
- packages/react-components/react-spinbutton/src/components/SpinButton/SpinButton.test.tsx
- packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButton.tsx
- packages/react-components/react-spinbutton/stories/SpinButton/SpinButtonBounds.stories.tsx
- packages/react-components/react-spinbutton/stories/SpinButton/SpinButtonDefault.stories.tsx
`SpinButton` supported home and end hotkeys but lacked tests for this behavior and didn't clearly document it in user-facing documentation.
- Adds test cases for home/end hotkeys
- Updates "bounds" story with information about home/end
- Updates "default" story to include min/max props so home/end behavior is observable
- Changes the "keys" import for better tree-shaking
* Fixes #26539
> Better documentation for SpinButton home/end behavior

- change/@fluentui-react-spinbutton-d1c4887c-0860-4d73-976c-52ab691a1772.json
- packages/react-components/react-spinbutton/src/components/SpinButton/SpinButton.test.tsx
- packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButton.tsx
Single digit text input may not properly update internal state, resulting in changed values not being committed on blur or "enter" press. See linked bug for details.
Internal state is correctly updated and values are committed as expected on blur, enter. Added tests for this case.
* Fixes #26741
> fix: handle single digit text input in SpinButton

- change/@fluentui-react-92e3b62a-42e0-401c-be50-be5ee1c7240e.json
- packages/react/src/components/Coachmark/Coachmark.base.tsx
- packages/react/src/components/Coachmark/PositioningContainer/PositioningContainer.tsx
fixes #25415
Resizing the page via page zoom will recalculate the position of the PositioningContainer, but it will not update the bounds passed into the container. This causes layout errors when zooming out.
This change will re-render the coachmark on page resize, passing in the correct bounds value, and ensuring the the new bounds value is used when calculating the new coachmark position.
> Coachmark reposition on page resize 

- change/@fluentui-react-menu-abe1574c-76eb-4b00-8d0e-324a355edb99.json
- packages/react-components/react-menu/src/components/MenuList/MenuList.cy.tsx
- packages/react-components/react-menu/src/components/MenuList/__snapshots__/MenuList.test.tsx.snap
- packages/react-components/react-menu/src/components/MenuList/useMenuList.ts
- packages/react-components/react-menu/stories/MenuList/MenuListDefault.stories.tsx
Since Menu needs to handle tab because it is a positionined element in a Portal, the MenuList does not need to. Disabling tabster's default handling for Tab in MenuList broke tabbing in that components.
Fixes #26776 this by only disabling tabster's Tab behaviour when the MenuList is wrapped by a Menu.
> fix: MenuList is a single tabstop

- .github/workflows/check-packages.yml
mandatory gha checks were blocked on wc-3
checks are unblocked
- Fixes #
> ci(.github): set fetch-depth on all check-packages to make action work again

- change/@fluentui-react-positioning-12d2fd1b-daef-4dc8-9886-61a7685ab3dd.json
- packages/react-components/react-positioning/src/utils/writeContainerupdates.ts
The react-positioning library uses a translate transform to position menus. Normally, the browser applies pixel snapping to the transform when the browser view is zoomed in. However, if the surface also has other effects applied, such as `backdrop-filter: blur()` as is the case in #26764, the browser seems to disable pixel snapping. This results in the popover being blurry even though the translate transform was using whole-pixel values.
Round the translate transform so that it lands on device pixels even if the browser doesn't apply pixel snapping.
Demo of the bug for testing the fix:
* Repro (no fix): https://fluentuipr.z22.web.core.windows.net/pull/26793/public-docsite-v9/storybook/index.html?path=/docs/components-popover--default#with-arrow
* With fix in this PR: …
> fix: Coordinates should be rounded to device pixels to prevent blurriness

- change/@fluentui-react-b9a960f6-2d91-47d9-95ab-3239e4940491.json
- packages/react-components/react-datepicker/src/components/CalendarDayGrid/CalendarGridDayCell.tsx
- packages/react/src/components/CalendarDayGrid/CalendarGridDayCell.tsx
`aria-current` is set to date when the day is selected.
`aria-current` is set to date when the day is today. For more information about this change, see the issue linked below and the [mdn docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current).
- Fixes #26750
> fix(Datepicker): Make aria-current date only when the day is today instead of when it's selected

- change/@fluentui-react-utilities-d78eb4e5-edce-495c-9f39-61908b540af1.json
- packages/react-components/react-utilities/src/compose/resolveShorthand.test.tsx
- packages/react-components/react-utilities/src/compose/resolveShorthand.ts
If a slot is a stable object, it gets 1 extra fluent ui className every time the component re-renders.
[beautiful-bohr-r2w8ot - codeSandbox](https://codesandbox.io/s/beautiful-bohr-r2w8ot?file=/example.tsx)
Clicking on 'force re-render' button, and observe the fluent ui className on button's icon slot increases 1 per render
This happens because:
if a slot is an object, `resolveShorthand` resolves it as itself. But instead it should resolve into a copy of the object.
> fix(resolveShorthand): resolving an object should return its copy instead of the object itself

- change/@fluentui-react-badge-bd7ce6fd-4495-46a0-9d19-6aa724e86cc7.json
- packages/react-components/react-badge/src/components/Badge/useBadgeStyles.ts
- packages/react-components/react-badge/src/components/PresenceBadge/usePresenceBadgeStyles.ts
Badges have many CSS classes on each slot.
Badge and PresenceBadge have fewer classes on their slots. CounterBadge is left unchanged as its styles won't benefit from this change. Note this improvement will compound with similar changes to Avatar and Persona.
Number of classes. In cases where there are multiple components in a story the first component is always used.
| Story | Old | New |
| --- | --- | --- |
| default | 49 | 5 |
| apperance | 49 | 5 | 
| sizes | 45 | 16 |
| shapes | 49 | 9 |
| color | 49 | 5 |
| icon | 62 | 11 |
Number of classes. In cases where there are multiple components in a story the first component is always used.
| Story | Old | New | 
| --- | --- | --- |
| default | 22 | 9 |
| sizes | 26 | 13 |
| status | 22 | 9 |
| out of office | 22 | 9 |
- #26811
- #26814
> Badge and PresenceBadge: update to use `makeResetStyles`

- change/@fluentui-react-731171c2-4a2b-4484-956b-667804fe01e2.json
- packages/react/src/components/CalendarDayGrid/CalendarDayGrid.styles.ts
- packages/react/src/components/WeeklyDayPicker/__snapshots__/WeeklyDayPicker.test.tsx.snap
Since cells are positioned and give an z-index value, the focus indicator outline in high contrast mode was getting clipped by cells after it in the DOM:
This gives cells a transparent bg in high contrast mode, so the focus and hover indicators do not get clipped. The hover and pressed styles keep their bg, so when a cell is hovered, it will still (intentionally) override any adjacent cell outlines (e.g. so hovering a cell next to a focused cell doesn't give you weird overlapping double lines):
* Fixes [15811](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15811)
> fix: v8 Calendar focus outline clipping in HCM

- change/@fluentui-react-virtualizer-f4f74084-b93e-4113-8e45-29229d62546e.json
- packages/react-components/react-virtualizer/package.json
> fix: Updating peer dependencies of react-virtualizer to support React 18

- change/@fluentui-web-components-4b3e5f7a-32b1-4a3e-9879-415aac98fc88.json
- change/@fluentui-web-components-516db34f-7e06-4348-a459-507ea3b7c881.json
- change/@fluentui-web-components-c9bafa19-7bba-4e91-a34b-ef812e450e99.json
- packages/web-components/CHANGELOG.json
- packages/web-components/CHANGELOG.md
- packages/web-components/package.json
Followed pattern from #26498 
Commands used:
` yarn beachball bump -b origin/web-components-v3 --access public --no-fetch --no-publish --no-push --no-git-tags --verbose --config ./scripts/beachball/release-web-components.config.js`
With Internet connection turned off
followed by 
`yarn change`
CI was blocked due to a failed release that published a version to npm but did not update local version number
`3.0.0-alpha.4` is already on NPM
https://www.npmjs.com/package/@fluentui/web-components/v/3.0.0-alpha.4
This fixes the repo to have the right version without updating NPM or anything else.
> Manual bump of web components version

- change/@fluentui-react-accordion-b982fc8e-4dc0-4862-a62d-7945f270b437.json
- packages/react-components/react-accordion/src/components/AccordionHeader/useAccordionHeaderStyles.ts
Convert styles from using `height` property on `button` slot to use `minHeight` instead.
- Fixes https://github.com/microsoft/fluentui/issues/26839
> bugfix(react-accordion): use min-height instead of height

- .github/CODEOWNERS
Add a catch-all rule for any newly added files that aren't already covered by existing rules.
We already have extensive rules in place covering all the important files in the repo, so we shouldn't hit this rule often. However, if we find that we're hitting this rule, we can add more rules to sub-folders. I would like to get this in place first and follow up with additional rules as we see fit.
> Update CODEOWNERS to add catch-all

- apps/ssr-tests/test/test.js
- change/@fluentui-react-095e69ed-d501-445c-aefa-a2f2ec7f8084.json
- packages/react/etc/react.api.md
- packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
- packages/react/src/components/List/List.tsx
Change to List rendering behavior lead to rendering issues in consuming controls like `TilesList`.
Reverts this PR: https://github.com/microsoft/fluentui/pull/25331
Which is the fix for this issue: https://github.com/microsoft/fluentui/issues/23925
Rollback rendering to previous behavior.
> revert: rollback List rendering change

- change/@fluentui-utilities-3e11088e-0de6-44c6-afa4-176d678d0629.json
#26821 moved the `IReactProps` interface to `@fluentui/utilities` but [the changefile](https://github.com/microsoft/fluentui/pull/26821/files#diff-39867d6dfbe2d281e0592a9029972c52836029820e71b124b41deed03e84f911) had the wrong `dependentChangeType` value so the package was not published.
Since the interface was removed from `@fluentui/react` the type is now missing and causing build errors for partners.
> fix: add change files to force package publish

- package.json
- satisfied checks are checking peer deps which are out of our controll as the issue is mostly with how 3rd party specifies their ranges
- satisfied checks are turned off on peerDeps
- Fixes #
> chore: turn off peerDeps check for satisfied calls that is causing lot of unnecessary churn

- change/@fluentui-web-components-ce5121f7-b7b0-48c8-862f-50a4684330a9.json
- packages/web-components/.storybook/preview.mjs
- packages/web-components/src/_docs/concepts/introduction.stories.mdx
Adds a landing page to the storybook docs for web-components.
The purpose of this PR is to (1) setup the stories structure and (2) add a version information to the published docsite.
👀 Open [live demo](https://fluentuipr.z22.web.core.windows.net/pull/26911/web-components/storybook/index.html?path=/docs/concepts-introduction--page).
Screenshot:
> doc(web-components): Add storybook landing page

- .github/CODEOWNERS
Change files were included in the catch-all rule `*`, resulting in most PRs requiring approval from fluentui-admins.
Update the change directory to have no codeowner specified. The change directory contains files from every package, and doesn't have a specific owner. Other code changes in a PR will still require owner approval. If a PR contains only change files, then it still requires approval from a maintainer.
> Update CODEOWNERS for change files

- change/@fluentui-react-input-85a7bc9c-40df-4a16-a935-8139ebc12873.json
- packages/react-components/react-input/src/components/Input/useInputStyles.ts
The width of the focus underline for `<Input appearance="underline" />` is 1px too wide on each side.
Reduce the width of the focus underline element to match the non-focus underline's width.
- Resolving the comment by @spmonahan: https://github.com/microsoft/fluentui/pull/26865#discussion_r1108974993
> fix: Fix the width of Input's focus border with appearance=underline

- change/@fluentui-react-f3d82f9f-d152-455c-914e-71cf2dfe554b.json
- packages/react-experiments/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/react/src/components/ComboBox/ComboBox.test.tsx
- packages/react/src/components/ComboBox/ComboBox.tsx
- packages/react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap
When the Combobox icon button isn't hidden, it should have an appropriate role and accname
- Fixes #26897
> fix: v8 Combobox role and accname for non-hidden icon button

- .github/workflows/azure-storage-web-components.yml
Web Components v3 storybook deployment silently fails.
Deploy now overwrites existing data
- Fixes #
> fix(ci): Overwrite existing data in wc storybook deploy

- change/@fluentui-react-table-94087703-4140-4a9c-8847-19940bb0fbe3.json
- packages/react-components/react-table/etc/react-table.api.md
- packages/react-components/react-table/src/hooks/types.ts
- packages/react-components/react-table/src/hooks/useTableSelection.ts
- packages/react-components/react-table/src/index.ts
`UseTableSelectionOptions` `selectedItems` was based on receiving a `Set` from the user
1. `selectedItems` and `defaultSelectedItems` now accepts a `Iterable` instead of a `Set`, which internally will be converted to a `Set`
3. exports  `UseTableSelectionOptions` type.
> chore(react-table): use `Iterable` instead of a `Set` for table selection API surface

- change/@fluentui-web-components-a862230b-9028-4c6a-8a43-3be819a6128e.json
- packages/web-components/package.json
- packages/web-components/src/image/define.ts
- packages/web-components/src/image/image.definition.ts
- packages/web-components/src/image/image.docs.md
- packages/web-components/src/image/image.options.ts
- packages/web-components/src/image/image.spec.md
- packages/web-components/src/image/image.stories.ts
- packages/web-components/src/image/image.styles.ts
- packages/web-components/src/image/image.template.ts
- packages/web-components/src/image/image.ts
- packages/web-components/src/image/index.ts
- packages/web-components/src/index.ts
This is a copy of all Image component changes into a new PR.
Previous PR with comments: #26622
Here's the component [design spec](https://www.figma.com/file/05wt6TAsEmgsCVZfPrpcWx/Image?t=uEvu1KnTefdTZHJC-6)
> Adds Image web component

- change/@fluentui-web-components-2500a738-206b-4f66-b5d5-c60924e40a5b.json
- packages/web-components/package.json
- packages/web-components/src/divider/define.ts
- packages/web-components/src/divider/divider.definition.ts
- packages/web-components/src/divider/divider.options.ts
- packages/web-components/src/divider/divider.stories.ts
- packages/web-components/src/divider/divider.styles.ts
- packages/web-components/src/divider/divider.template.ts
- packages/web-components/src/divider/divider.ts
- packages/web-components/src/divider/index.ts
- packages/web-components/src/index.ts
Adds Divider web component. 
[component spec](https://www.figma.com/file/TQO8qAOcrwU3ig2CTcan0e/Divider?node-id=0%3A1&t=YAMG4II6DeCijvGS-0)
Horizontal (default):
Horizontal with content in default position:
Horizontal flex-start:
Horizontal flex-end:
Horizontal inset:
Horizontal, brand color, with icon
Vertical:
Min-height is 20px. Storybook container is much larger than the component itself.
Vertical w content in default position:
Vertical w content, inset:
Vertical flex-start:
Vertical flex-end:
**Colors**
Strong
Brand
Subtle
> Adds Divider web component

- packages/web-components/src/menu-item/menu-item.styles.ts
- packages/web-components/src/menu-item/menu-item.ts
- packages/web-components/src/menu/menu.stories.ts
- packages/web-components/src/menu/menu.ts
> dynamically set the menu item icon attribute when icons is true for menu

- change/@fluentui-web-components-2cdbddf3-5a67-47fc-9baa-da97520b8888.json
- packages/web-components/docs/api-report.md
- packages/web-components/src/slider/slider.spec.md
I had introduced merge/rebase errors in the [previous Slider Spec PR](https://github.com/microsoft/fluentui/pull/26830), which is now closed. This is the Spec and empty folder for the Fluent Slider Web Component.
Apologies for the Github churn.
> Redo of PR of Slider spec after merge error

- apps/vr-tests-react-components/package.json
- apps/vr-tests/package.json
- azure-pipelines.vrt-baseline.yml
- azure-pipelines.vrt-pr.yml
- change/@fluentui-react-components-efef013e-42c3-4754-ad30-88a5fc4354e7.json
- packages/fluentui/docs/package.json
- packages/react-components/react-components/package.json
- scripts/storybook/src/utils.js
- scripts/storybook/src/utils.spec.js
- workspace storybook addons  need to be manually build prior to execute `build-storybook`
- this might have caused some issues as manager and preview was being build from 2 different sources (javascript / typescript)
- building storybooks on CI is slower as manual addon builds needs to happen first
- workpsace addon dont need to build manually
- manager and preview uses same bundling and same code to execute
- building storybook on CI doesn't need any pre-requirements thus fully leveraging `swc` + TS path aliases transpilation speed 
- building v0 VR storybook is no longer building whole v0 dep tree which reduces **CI time by approx 9 minutes** for v0 VR test execution
- this results in **27% faster pipeline** for VR tests
-  BEFORE: <img width="316" alt="image" …
> feat(scripts-storybook): unify workspace addon loading for dev and prod builds

- change/@fluentui-react-dialog-38f69b56-be72-4380-8325-4fa430483d93.json
- change/@fluentui-react-popover-c8f02f2c-1573-4b58-b7b2-e75b0ca9eb74.json
- packages/react-components/react-dialog/etc/react-dialog.api.md
- packages/react-components/react-dialog/src/components/Dialog/Dialog.cy.tsx
- packages/react-components/react-dialog/src/components/Dialog/Dialog.types.ts
- packages/react-components/react-dialog/src/components/Dialog/useDialog.ts
- packages/react-components/react-dialog/src/components/Dialog/useDialogContextValues.ts
- packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurface.ts
- packages/react-components/react-dialog/src/contexts/dialogContext.ts
- packages/react-components/react-dialog/src/testing/mockUseDialogContext.ts
- packages/react-components/react-popover/etc/react-popover.api.md
- packages/react-components/react-popover/src/components/Popover/Popover.cy.tsx
- packages/react-components/react-popover/src/components/Popover/Popover.types.ts
- packages/react-components/react-popover/src/components/Popover/renderPopover.tsx
- packages/react-components/react-popover/src/components/PopoverSurface/__snapshots__/PopoverSurface.test.tsx.snap
- packages/react-components/react-popover/src/components/PopoverSurface/usePopoverSurface.ts
- packages/react-components/react-popover/src/popoverContext.ts
By default `Popover` and `Dialog` would support an `inert` focus trap approach, which is similar to what is provided by native elements, such as native `dialog` where the focus would leak to the browser window after the last focusable element on the trap.
To opt out of that behavior and to simply trap the focus completely without letting it leak the property `legacyTrapfocus` was provided in `Popover`
This PR will provide fixes for both `Dialog` and `Popover` components on this matter.
1. makes the `legacyTrapFocus` behavior the default one, as native `inert` focus presents some edge cases with iframes
2. deprecates `legacyTrapFocus` property as the behavior is the default one
3. introduces `inertTrapFocus` property to opt-out of legacy trap focus behaviour in favor of native `inert` …
> feature: introduces `inertTrapfocus` property and deprecates `legacyTrapFocus`

- .github/CODEOWNERS
As per #26594, I'm updating the codeowners for recipes-react-components from fluentui-react-build to fluentui-react since this doesn't impact build directly.
- Related #26594
> chore(codeowners): Update owners from fluentui-react-build to fluentui-react

- apps/vr-tests/src/stories/TilesList.stories.tsx
Added a new visual regression test for `TilesList` to ensure that changes to `List` don't break its render behavior, which requires an upfront measurement of the content width before rendering can occur.
> Add visual regression test for TilesList

- .devops/templates/runpublishvrscreenshot.yml
- azure-pipelines.vrt-baseline.yml
- azure-pipelines.vrt-pr.yml
- Removes `shouldBuildStorybookAddon` and `shouldBuildNorthstar` variables from .yml files as the changes in #27006 makes them unnecessary. 
- Fixes #27010
> chore(VRT Pipelines): remove unneeded variables from yml files

- .vscode/settings.json
- apps/public-docsite/src/components/Site/AppThemes.ts
- change/@fluentui-fluent2-theme-b800a8a9-5bc5-4e44-9e22-4dbb916cb1aa.json
- packages/fluent2-theme/src/componentStyles/TextField.styles.ts
- packages/fluent2-theme/src/fluent2WebDarkTheme.ts
- packages/fluent2-theme/src/fluent2WebLightTheme.ts
- packages/fluent2-theme/src/index.ts
- packages/fluent2-theme/src/types.ts
The focus behavior in Fluent 2 is dramatically different than Fluent 1. This PR updates the behavior for just the text field, though there are several more input fields that will need to be touched before we're adequately aligned. This PR is more about rehydrating and learning about what needs to be done and the existing space. Subsequent PR's will both update more components and create the shared logic to do so.
Things to review for:
Are all the names clear and sensible?
Is the behavior accurate and bug free?
- known gaps: background color in dark theme, animation
This is my first PR against OUIFR in quite a while. Anything else I should pay attention to?
Before:
After:
> Updating Fluent 2 Theme TextField styles

- change/@fluentui-react-utilities-df14dd64-64ee-4c93-9065-d048bc306cb2.json
- packages/react-components/react-utilities/etc/react-utilities.api.md
- packages/react-components/react-utilities/src/compose/types.ts
To disable the usage of `children` as a property on [Void Elements](https://developer.mozilla.org/en-US/docs/Glossary/Void_element) our internal typings would mark `children` as `never`. This would work for the normal use cases of `children` and errors would pop if you tried using `children`, as expected:
When supporting slot API, `children` can receive a render function as value to allow the case of [Replacing the entire slot](https://react.fluentui.dev/?path=/docs/concepts-developer-customizing-components-with-slots--page#replacing-the-entire-slot). This is currently broken as void elements `children` props are marked as `never`:
Instead of marking `children` as never, filtering the original children value out of the types solves this problem, allowing the slot API and properly emitting …
> fix(react-utilities): adjust IntrinsicElementProps type to properly support void elements

- change/@fluentui-react-dialog-b1dd1b91-b909-4e79-96b5-6012f8e43ff5.json
- change/@fluentui-react-popover-85dddf2c-1330-4920-81af-254a7972fd9b.json
- change/@fluentui-react-tabster-a38a7a64-a7f8-484b-810b-2c29f7b34b52.json
- packages/react-components/react-popover/etc/react-popover.api.md
- packages/react-components/react-popover/src/components/Popover/Popover.types.ts
- packages/react-components/react-popover/src/components/PopoverSurface/__snapshots__/PopoverSurface.test.tsx.snap
- packages/react-components/react-tabster/src/hooks/useModalAttributes.ts
1. updates `isTrapped` flag to follow up `inertTrapFocus`
2. update `Popover` and `Dialog` components accordingly
- Follow ups on https://github.com/microsoft/fluentui/pull/26942
> chore(react-tabster): updates useModalAttributes flags

- .github/CODEOWNERS
`packages/react-icons-mdl2` did not have any codeowners defined, and so required fluentui-admins approval.
Add `cxe-red` and `cxe-coastal` as codeowners for `packages/react-icons-mdl2`.
> Add codeowners for react-icons-mdl2 package

- change/@fluentui-react-progress-dc31d0f2-6038-4cbf-bbc0-5b1aadf202c7.json
- packages/react-components/react-progress/src/components/ProgressBar/useProgressBarStyles.ts
This PR is to fix an issue where the `ProgressBar` renders with `width: 0` when its container has `display` set to flex. This was due to the default styling on `justifySelf: 'stretch'` which does not work on a flex display.
The style has been changed to have the default `width` be set to 100%.
This PR also updates the `height` styling to remove the `height` styles from the `bar` slot, so you only need to apply a style override to the `root` slot to change the default height.
Fixes #27096
> Fix styling to allow Progressbar to have width when display is flex

- change/@fluentui-react-tabs-106a456b-4f3d-457f-93f2-c6bd95ad999e.json
- packages/react-components/react-tabs/src/components/Tab/useTabStyles.ts
- Added enableOutline: true to the focus indicator in Tab to allow the focus indicator to show in high contrast mode.
Fixes #27122
Default light theme
Fixed high contrast
> Fix sev1 tabs accessibility

- change/@fluentui-web-components-91a1543a-10b0-4b10-9d32-0535f7a8e631.json
- packages/web-components/src/text/text.styles.ts
The `style` attribute is not applied to the text when `block` is set.
The `style` should be applied to the text, as it is when `block` is not set.
- Fixes #27048
> fix: [text] block breaks the style attribute

- change/@fluentui-react-window-provider-9713a8ed-37d1-474e-91c3-7e0f62ab88a4.json
- packages/react-window-provider/etc/react-window-provider.api.md
- packages/react-window-provider/src/WindowProvider.tsx
We bumped window provider to support React 18, but it seems it wasn't used in any of the components we tested, so we didn't notice the typing error here.
> Add explicit children prop to Window Provider

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams-forced-colors/componentStyles.ts
- packages/fluentui/react-northstar/src/themes/teams-forced-colors/components/SplitButton/splitButtonDividerStyles.ts
- packages/fluentui/react-northstar/src/themes/teams-forced-colors/components/SplitButton/splitButtonToggleStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/SplitButton/splitButtonToggleStyles.ts
Added the following changes so that SplitButton would display correctly in windows high contrast mode:
* Applied transparent border in forced colours theme theme for primary split buttons
* Applied transparent border in forced colours theme theme for disabled split buttons
* Created a new data-url for the toggle indicator in forced colours theme
* Add explicit system colour for the divider in forced colours theme
Fixes #27123
> fix: SplitButton should display correctly in high contrast mode

- change/@fluentui-fluent2-theme-9c27a1c0-3c80-4f47-89b5-6ac9da027257.json
- packages/fluent2-theme/src/componentStyles/SearchBox.styles.ts
- packages/fluent2-theme/src/componentStyles/TextField.styles.ts
- packages/fluent2-theme/src/componentStyles/inputStyleHelpers.utils.ts
- packages/fluent2-theme/src/index.ts
Adds Fluent 2 focus and disabled styling to SearchBox.
Extracts duplicate code to helper functions.
Before
After
> Adds Fluent 2 focus styles to search box

- change/@fluentui-fluent2-theme-04317380-4380-49b5-9a39-ba3a88d9f9de.json
- packages/fluent2-theme/src/componentStyles/Dropdown.styles.ts
- packages/fluent2-theme/src/componentStyles/TextField.styles.ts
- packages/fluent2-theme/src/componentStyles/inputStyleHelpers.utils.ts
Updates Drop Down focuse and disabled styling.
Couldn't use the previous input focus styling method because of the way focus behavior was handled.
Before:
After:
> Updates drop down to Fluent 2 focus and disabled styling

- change/@fluentui-react-menu-f76e8e18-42bd-4e30-92ec-977d7132c7aa.json
- change/@fluentui-react-positioning-0ba7f9d3-aa7a-40eb-a354-b88eb83ee05b.json
- change/@fluentui-react-radio-685f2015-ef46-4d86-bedb-154b6516ec96.json
- change/@fluentui-react-utilities-ac521080-1e70-44d9-a0d6-2293af91ef5e.json
- packages/react-components/react-menu/src/components/MenuTrigger/useMenuTrigger.ts
- packages/react-components/react-positioning/src/createPositionManager.ts
- packages/react-components/react-positioning/src/utils/toggleScrollListener.ts
- packages/react-components/react-radio/src/components/RadioGroup/useRadioGroup.ts
- packages/react-components/react-utilities/etc/react-utilities.api.md
- packages/react-components/react-utilities/src/utils/isHTMLElement.test.ts
- packages/react-components/react-utilities/src/utils/isHTMLElement.ts
1. Improves `isHTMLElement` helper method to support all `HTMLElement` classes
2. Stops using `instanceof` in favor of `isHTMLElement` on:
- `react-radio`
- `react-menu`
- `react-positioning` 
This is required as simply using `instanceof` might be problematic while operating with [multiple realms](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_realms)
Fixes https://github.com/microsoft/fluentui/issues/27159
> feat(react-utilities): isHTMLElement to support all HTMLElement classes

- change/@fluentui-react-card-0a817d2d-d46b-4895-b3bb-29566bf747fa.json
- packages/react-components/react-card/README.md
This PR fixes react-card README by removing the "preview" banner.
> docs(react-card): fix card readme description

- change/@fluentui-fluent2-theme-9fc83052-67a5-4a19-8327-ec4dfd93565d.json
- packages/fluent2-theme/src/componentStyles/Spinner.styles.ts
We hard coded the spinner size to 32px as the size prop had been deprecated, and we expected most consumers to have coded their own size via the styles prop, as was recommended by the Fluent documentation.
Turns out many folks are still using the size prop, and our hard coding broke the UX in places where small or extra small had been used:
So now we're leaving small & xSmall untouched, and just changing medium (default) and large to 32 and 36.
Vanilla Fluent:
Before Fluent 2 Theme:
After:
> [Fluent 2 theme for v8] Fix spinner sizes

- change/@fluentui-fluent2-theme-71e4fd17-0fdb-4693-b2bc-85dc055bd43c.json
- packages/fluent2-theme/src/componentStyles/SearchBox.styles.ts
- packages/fluent2-theme/src/componentStyles/SpinButton.styles.ts
- packages/fluent2-theme/src/componentStyles/TextField.styles.ts
- packages/fluent2-theme/src/componentStyles/inputStyleHelpers.utils.ts
Updating spin button to use Fluent 2 focused and disabled styles.
Updating other fields to use proper semantic slots.
Before:
After:
> [Fluent 2 Theme for v8] spin button focus styles

- .github/CODEOWNERS
adding test to react 18 test app required admin approval
would unblock PRs like this https://github.com/microsoft/fluentui/pull/26749
> Chore: Add owners to react 18 test apps

- change/@fluentui-web-components-904258a8-cd16-4d42-be2e-d6179a4afd76.json
- packages/web-components/src/accordion-item/accordion-item.styles.ts
- packages/web-components/src/accordion/accordion.styles.ts
- packages/web-components/src/avatar/avatar.styles.ts
- packages/web-components/src/divider/divider.styles.ts
- packages/web-components/src/image/image.styles.ts
- packages/web-components/src/progress-bar/progress-bar.styles.ts
- packages/web-components/src/spinner/spinner.styles.ts
- packages/web-components/src/styles/partials/badge.partials.ts
- packages/web-components/src/switch/switch.styles.ts
- packages/web-components/src/text/text.styles.ts
No CSS Containment
Adds `contain: content` to all components except Avatar which implements `contain: layout style` (paint cannot be applied due to the presence badge).
n/a
- Fixes #
> (web-components): add css containment to v3 components

- change/@fluentui-react-portal-d5ac98ba-22cc-41a1-939d-77041a362442.json
- packages/react-components/react-portal/etc/react-portal.api.md
- packages/react-components/react-portal/src/components/Portal/Portal.types.ts
- packages/react-components/react-portal/src/components/Portal/usePortal.test.ts
- packages/react-components/react-portal/src/components/Portal/usePortal.ts
- packages/react-components/react-portal/src/components/Portal/usePortalMountNode.test.ts
- packages/react-components/react-portal/src/components/Portal/usePortalMountNode.ts
Implements RFC #27009.
Now `mountNode` prop can be an object and allows to configure applied classes.
```tsx
return (
<>
{/* There usages are equal */}
<Tooltip mountNode={mountNode} />
<Tooltip mountNode={{ element: mountNode }} />
{/* Now applied classes can be configured 🔥 */}
<Tooltip mountNode={{ className }} />
</>
);
}
```
```tsx
import * as React from "react";
import {
makeStyles,
Popover,
PopoverSurface,
PopoverTrigger,
tokens
} from "@fluentui/react-components";
const useClasses = makeStyles({
mountNode: {
color: tokens.colorBrandBackground,
zIndex: 100
}
});
const classes = useClasses();
return (
<Popover mountNode={{ className: classes.mountNode }}>
<PopoverSurface>
<div />
</PopoverSurface>
</Popover>
);
}
```
Fixes #26758
> feat: accept a className in `mountNode` in `Portal`

- packages/react-components/theme-designer/package.json
- packages/react-components/theme-designer/src/colors/csswg.ts
- packages/react-components/theme-designer/src/colors/geometry.ts
- packages/react-components/theme-designer/src/colors/index.ts
- packages/react-components/theme-designer/src/colors/palettes.ts
- packages/react-components/theme-designer/src/colors/templates.ts
- packages/react-components/theme-designer/src/colors/types.ts
- packages/react-components/theme-designer/src/components/ColorTokens/getAccessibilityChecker.ts
- packages/react-components/theme-designer/src/components/Palette/Palette.tsx
- packages/react-components/theme-designer/src/utils/getBrandTokensFromPalette.ts
- yarn.lock
Soon we'll be making some adjustments to how our colors are calculated. This will require the logic used to calculate colors to be easier to modify. This PR pulls in all of the color files from the @fluentblocks/colors package https://github.com/OfficeDev/fluent-blocks/tree/next/packages/colors
> Theme designer: Move colors to local files

- .github/CODEOWNERS
The `react-file-type-icons` package had only non-maintainer codeowners listed.
Add `@microsoft/cxe-red` as a codeowner for the `react-file-type-icons` package.
> Add cxe-red as a codeowner of react-file-type-icons

- change/@fluentui-react-provider-830b9ca5-f5b6-42cd-9c8c-7ac7dce3c6ff.json
- change/@fluentui-react-tabster-15bd7e2e-e514-4577-8ce7-6df09dfa88c6.json
- packages/react-components/react-provider/src/components/FluentProvider/useFluentProvider.ts
- packages/react-components/react-tabster/etc/react-tabster.api.md
- packages/react-components/react-tabster/src/focus/focusVisiblePolyfill.ts
- packages/react-components/react-tabster/src/hooks/useFocusVisible.test.tsx
- packages/react-components/react-tabster/src/hooks/useFocusVisible.ts
Fixes #27197.
This PR extends `useFocusVisible()` to accept `options` that contains `targetDocument`. `useFluentProvider()` passes a proper instance of `targetDocument` directly to `useFocusVisible()` to avoid chicken-egg problem with React Contexts.
Before the fix `useFocusVisible()` used a `targetDocument` from `useFluent()` i.e. used a value from context. The problem is that in this case it will use always a value of parent context or a default value instead of a proper one.
> fix: useFocusVisible() should use proper document

- change/@fluentui-react-dialog-265d3f30-f8c2-4813-89cd-389f8b99d67c.json
- packages/react-components/react-dialog/src/components/DialogBody/useDialogBodyStyles.ts
This style is redundant because the DialogBody will not exceed the DialogSurface which sets the exact same maxWidth.
Removing this style will also make it easier for users to modify the width of the dialog by only neededing to override one component instead of 2.
Fixes #27222
> fix(DialogBody): Remove `maxWidth` style

- change/@fluentui-react-utilities-b426918d-10c6-4a75-ada8-22a181ac8670.json
- packages/react-components/react-utilities/src/compose/getSlots.ts
`ObjectSlotProps` would return `never` as the inference of slots defined as `Slot<ComponentProps>`
`ObjectSlotProps` returns `ComponentProps` for those cases.
As presented by @marcosmoura
> fix(getSlots): stops slotProps.slot to be typed as never

- apps/vr-tests-react-components/src/stories/Dialog/Dialog.stories.tsx
- change/@fluentui-react-dialog-aa5a8af5-a05d-460d-88d5-6126197983f6.json
- packages/react-components/react-dialog/etc/react-dialog.api.md
- packages/react-components/react-dialog/src/components/DialogActions/DialogActions.types.ts
- packages/react-components/react-dialog/src/components/DialogActions/useDialogActions.ts
- packages/react-components/react-dialog/src/components/DialogActions/useDialogActionsStyles.ts
- packages/react-components/react-dialog/stories/Dialog/DialogFluidDialogActions.md
- packages/react-components/react-dialog/stories/Dialog/DialogFluidDialogActions.stories.tsx
- packages/react-components/react-dialog/stories/Dialog/index.stories.tsx
Implements a new `fluid` prop so that the actions will span the entire width of the dialog without needing to do style overrides to the grid layout.
Fixes #27228
Fixes #27228
> feat(DialogActions): Implement `fluid` prop

- change/@fluentui-eslint-plugin-9788e3e7-808d-4201-b04e-cead71f27b9e.json
- change/@fluentui-react-utilities-851262b0-ac71-4e89-ae48-e53733715e8a.json
- packages/eslint-plugin/README.md
- packages/eslint-plugin/src/configs/react.js
- packages/eslint-plugin/src/index.js
- packages/eslint-plugin/src/rules/ban-instanceof-html-element/index.js
- packages/eslint-plugin/src/rules/ban-instanceof-html-element/index.test.js
- packages/react-components/react-components/stories/Concepts/Positioning/PositioningImperativeAnchorTarget.stories.tsx
- packages/react-components/react-utilities/etc/react-utilities.api.md
- packages/react-components/react-utilities/src/utils/isHTMLElement.test.ts
- packages/react-components/react-utilities/src/utils/isHTMLElement.ts
1. Adds new rule to ban usage of `instanceof HTMLElement` on v9 packages as they do not work properly on multi realms environment.
2. exports `isHTMLElement` as public
- Fixes #27175
> feat(eslint-plugin): rule to ban usage of instanceof HTMLElement

- packages/react-components/react-field/stories/Field/FieldDisabled.stories.tsx
- packages/react-components/react-field/stories/Field/index.stories.tsx
Field documentation does not show what a disabled control inside a field should look like.
Add a story showing a disabled control in the Field, along with a description recommending against disabling the label.
https://fluentuipr.z22.web.core.windows.net/pull/27240/public-docsite-v9/storybook/index.html?path=/docs/preview-components-field--default#disabled-control
- Fixes #26506
> chore: Add a Field story showing a disabled control inside a Field

- change/@fluentui-react-menu-417b3787-772b-41b9-90b3-9a33eb67f0eb.json
- packages/react-components/react-menu/src/components/MenuItem/useMenuItemStyles.ts
Adds styles so that disabled menuitems and their icons render correctly with gray text in high contrast mode.
Fixes #27244
> fix(MenuItem): Disabled should render correctly in high contrast mode

- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
- use `es2019` target instead of browser matrix target to unblock (for the time being) migration towards `swc` transpilation
- Part of #26170
> chore(tools): use es2019 target instead of browser matrix target

- change/@fluentui-react-switch-9ee5312c-b459-4881-a942-2c61eb55f229.json
- packages/react-components/react-switch/src/components/Switch/useSwitchStyles.ts
Adds styles so that enabled checked state are more more obvious in high contrast mode.
- Fixes #
> fix: Make checked switch more visible in high contrast mode

- change/@fluentui-react-dialog-299ad8d3-d339-460e-8e78-cb3547dab151.json
- packages/react-components/react-dialog/etc/react-dialog.api.md
- packages/react-components/react-dialog/src/components/DialogSurface/DialogSurface.types.ts
- packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurface.ts
As an implementation legacy `DialogSurface` types were supporting native dialog types, although our API never supported the usage of native dialog element.
1. Removes unsupported native dialog types
2. Generalizes type for `DialogSurfaceElement` from `HTMLDivElement` to `HTMLElement`
- Fixes #27281
> chore(react-dialog): removes native dialog types

- change/@fluentui-react-dialog-b286942f-21da-4936-947b-6daf42db80ab.json
- packages/react-components/react-dialog/src/components/DialogContent/useDialogContentStyles.ts
Without proper padding the border of focusable elements inside `DialogContent` would be lost.
- Fixes #25843
> fix(DialogContent): adds padding to allow focus visibility

- scripts/generators/create-package/plop-templates-node/package.json.hbs
- scripts/generators/create-package/plop-templates-react/package.json.hbs
- replaces unneeded `tslib` dependency from `create-package` script plop templates in favor of `@swc/helpers` which is what's used for swc transpilation.
- Part of #26170
> chore (scripts): update create-package plop templates to use swc/helpers in deps

- apps/vr-tests-react-components/package.json
- change/@fluentui-react-combobox-9a9272e4-7690-404a-a877-806c8d778178.json
- change/@fluentui-react-components-265f5023-f956-40ae-84c5-bd75add60eee.json
- packages/react-components/react-combobox/package.json
- packages/react-components/react-components/package.json
`yarn beachball sync` missed this mismatch with npm (I don't know why) so doing a manual bump.
* No changefile for @fluentui/react-combobox because it's syncing it with master
* changefile for react-components because a new release is necessary to bump react-combobox
Follow up of #27317
> Fix react-combobox mismatch after bad release

- apps/perf-test-react-components/src/scenarios/InfoButton.tsx
- apps/vr-tests-react-components/src/stories/InfoButton.stories.tsx
- change/@fluentui-react-infobutton-e5984e77-89ae-4c61-85e0-984121adb4e5.json
- packages/react-components/react-infobutton/docs/Spec.md
- packages/react-components/react-infobutton/etc/react-infobutton.api.md
- packages/react-components/react-infobutton/src/components/InfoButton/InfoButton.test.tsx
- packages/react-components/react-infobutton/src/components/InfoButton/InfoButton.types.ts
- packages/react-components/react-infobutton/src/components/InfoButton/renderInfoButton.tsx
- packages/react-components/react-infobutton/src/components/InfoButton/useInfoButton.tsx
- packages/react-components/react-infobutton/src/components/InfoButton/useInfoButtonStyles.ts
- packages/react-components/react-infobutton/src/components/InfoLabel/InfoLabel.test.tsx
- packages/react-components/react-infobutton/src/components/InfoLabel/InfoLabel.types.ts
- packages/react-components/react-infobutton/src/components/InfoLabel/useInfoLabel.ts
- packages/react-components/react-infobutton/stories/InfoLabel/InfoLabelBestPractices.md
- packages/react-components/react-infobutton/stories/InfoLabel/InfoLabelDefault.stories.tsx
- packages/react-components/react-infobutton/stories/Infobutton/InfoButtonDefault.stories.tsx
- packages/react-components/react-infobutton/stories/Infobutton/InfoButtonSize.stories.tsx
InfoButton's information slot's name is `content`.
InfoButton's information slot's name is `info`.
- Related #27118
- Fixes #27236
> chore(react-infobutton): Renaming content slot to info

- change/@fluentui-react-checkbox-4ebdfb9d-a372-4ce7-99f4-c66d376885b1.json
- packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.ts
When multiple Checkboxes are inline, the unchecked and checked ones have different alignments.
Add `vertical-align: middle` to the Checkbox, to force it to always have the same alignment.
- Fixes #27176
> fix: Fix vertical alignment of inline Checkbox when checked vs. unchecked

- change/@fluentui-react-virtualizer-32407628-78bb-4307-bbf4-d0a366f48deb.json
- packages/react-components/react-virtualizer/package.json
- packages/react-components/react-virtualizer/stories/Virtualizer/DefaultUnbounded.stories.tsx
- packages/react-components/react-virtualizer/stories/Virtualizer/MultiUnbounded.stories.tsx
- packages/react-components/react-virtualizer/stories/VirtualizerScrollView/Default.stories.tsx
`react-virtualizer` introduced a forbidden project dependency on react(v8), which caused pipeline creep ( on any v8 change all v9 project would be affected).
**Simplified Example:**
- user makes changes within `@fluentui/react`
- this triggers build/lint/test task on following packages because their dependency tree
- `@fluentui/ssr-test-v9` -->  `@fluentui/react-components` --> `@fluentui/react-virtualizer` --> `@fluentui/react`
This caused Out of memory/timeout issues for both PR pipelines and release pipelines
Example of failing PR/pipeline that triggers everything because of this: https://github.com/microsoft/fluentui/pull/27323
react v8 is no longer a v9 package direct or indirect dependency.
**Notes:** 
- We have currently no tooling in place that explicitly fails pipeline when such …
> fix(react-virtualizer): remove disallowed v9 react-fabric/v8 from dependencies to mitigate dep-tree creep

- packages/react-components/react-virtualizer/.storybook/preview-body.html
- packages/react-components/react-virtualizer/stories/Virtualizer/DefaultUnbounded.stories.tsx
- packages/react-components/react-virtualizer/stories/Virtualizer/MultiUnbounded.stories.tsx
- packages/react-components/react-virtualizer/stories/VirtualizerScrollView/Default.stories.tsx
We had a v8 ThemeProvider in the virtualizer examples (v( codebase)
ThemeProvider has been replaced with a more native storybook styling option for all Virtualizer demo containers (Max 100VH to ensure scroll viewport is window sized).
v8 theme provider caused dep tree issues (https://github.com/microsoft/fluentui/pull/27334/files) - dep tree issues have been resolved, so now just cleaning up storybook
> Remove V8 Theme Provider from virtualizer demos

- apps/ssr-tests-v9/src/test.ts
This PR disables "--hide-sidebars" option in headless Chromium to prevent false positives reported in #27357.
- Fixes #27357
> chore(ssr-tests): disable "--hide-sidebars"

- .babelrc-v9.json
- .github/CODEOWNERS
- scripts/babel/jest.config.js
- scripts/babel/preset-v9.js
- scripts/babel/preset-v9.spec.ts
- scripts/babel/types.ts
v9 packages that use babelrc preset-v9 trigger warnings caused by invalid module path created by module-resolver within griffel preset transform.
v9 packages trigger no warnings.
preset-v9 has been completely refactored to match true mappings based on `tsconfig.base.json`.
**Performance:**
Processing tsconfig json within babel execution adds some perf owerhead ( around 500ms ) but this is acceptable taking into consideration that mappings are 100% correct all the time. When griffel will migrate to linaria 4 this overhead will be mitigated as griffel will be able to transrorm swc commonjs module output.
- Fixes https://github.com/microsoft/fluentui/issues/27304
> feat(scripts-babel): implement v9 babel preset to properly resolve griffel module mappings

- scripts/tasks/src/babel.ts
Order of tasks:
- `ts:esm`
- `ts:cjs`
- `babel:postprocess` (both ESM & CJS)
- `swc:esm`
- `babel:postprocess` (only ESM)
- `swc:cjs`
Removes `lib-commonjs` from the glob as now the order of tasks is different.
- Follows https://github.com/microsoft/fluentui/pull/27250
> chore: update babel:postprocess

- rfcs/react-components/convergence/slot-children-render-function.md
Slot children render function is a complex API that is not properly supported.  https://github.com/microsoft/fluentui/issues/27089
To support this, this RFC proposes to create a custom JSX pragma to ensure slot declaration will not lose any property
and will be capable of properly rendering with children render function.
[RFC](https://github.com/microsoft/fluentui/blob/e52cb869d5290f6a645e0ab0df9c9a5885dfecd2/rfcs/react-components/convergence/slot-children-render-function.md)
[Slot children render function won't override existing children. #27089](https://github.com/microsoft/fluentui/issues/27089)
Repro: https://codesandbox.io/s/elated-babbage-46ez1w?file=/example.tsx
It's not possible to use children render function to override an entire slot, if `children` are already used. The above …
> RFC: slot children render function support

- packages/react-components/react-datepicker-compat/src/components/Calendar/Calendar.tsx
- packages/react-components/react-datepicker-compat/src/components/Calendar/useCalendarStyles.ts
- packages/react-components/react-datepicker-compat/src/components/CalendarDay/useCalendarDayStyles.ts
- packages/react-components/react-datepicker-compat/src/components/CalendarDayGrid/CalendarGridDayCell.tsx
- packages/react-components/react-datepicker-compat/src/components/CalendarDayGrid/useCalendarDayGridStyles.ts
- packages/react-components/react-datepicker-compat/src/components/CalendarPicker/useCalendarPickerStyles.ts
This PR fixes the following issues:
* When clicking grid items, there were unwanted styles left behind if while clicking you move the mouse out of the control.
* Contrast issues with high contrast and dark theme.
* Not showing current selection when the date range is month.
* Contrast issues with marked days.
* Colors didn't feel cohesive and seemed like we had two themes in one.
> fix(react-datepicker-compat): Fix theming issues with all themes and WHCM

- scripts/tasks/src/api-extractor.ts
- obsolete error messages might get printed on the local machine
- ci spam without any benefit
- no spam logs / confusing error messages with api-extractor
- Replaces https://github.com/microsoft/fluentui/pull/25678
> chore(scripts-tasks): remove not needed api-extractor task logs

- change/@fluentui-web-components-9d8d0650-6506-4332-97ba-4f96836470e2.json
- packages/web-components/package.json
- yarn.lock
Tue, 28 Mar 2023 22:14:10 GMT
- docs: add missing API docs
- fix: correct types for a break in TypeScript 5 legacy decorators
- update @microsoft/fast-element to be fixed for foundation package
- update slider changed methods to protected
- support row selection in data grid
- remove activeindicator from tabs component
- Bump @microsoft/fast-element to v2.0.0-beta.23
- Fixes #
> update fast-element to 2.0.0-beta.23 and fast-foundation to 3.0.0-alpha.27

- change/@fluentui-react-dialog-19f431ea-3879-40f6-bf2a-177d37d60310.json
- packages/react-components/react-dialog/src/components/DialogBody/useDialogBodyStyles.ts
- packages/react-components/react-dialog/src/components/DialogContent/useDialogContentStyles.ts
- packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurfaceStyles.ts
PR https://github.com/microsoft/fluentui/pull/27248  introduced a regression where the scrollbar would always be visible due to a negative margin.
1. removes declaration of the `height: 100%` from `DialogContent`, which makes height `auto`, which will properly vary `DialogContent` height taking into account the negative margin in cases where the scrollbar should be visible or not 
2. removes unnecessary `height` and  `width` styles from `DialogContent`, `DialogBody` and `DialogSurface` 
- Fixes #27347
> fix(react-dialog): DialogContent scrollbar always visible

- scripts/babel/preset-v9.js
Builds are failing on windows machines, with an error like:
```log
verb @fluentui/react-label build |  [11:12:26 AM] x Error detected while running 'babel:postprocess'
verb @fluentui/react-label build |  [11:12:26 AM] x ------------------------------------
verb @fluentui/react-label build |  [11:12:26 AM] x node:internal/modules/cjs/loader:959
verb @fluentui/react-label build |    throw err;
verb @fluentui/react-label build |    ^
verb @fluentui/react-label build |
verb @fluentui/react-label build |  Error: Cannot find module '..\..\../packages/react-components/react-theme/lib/index.js'
```
Modify the change from #27313 to use `path.resolve` to ensure the slashes are in the correct direction on Windows.
- Regression from #27313
> fix: Fix babel build error on Windows

- change/@fluentui-react-8e2d7e7a-c47a-459d-8184-f5744bc1d88e.json
- packages/react/src/components/ColorPicker/ColorPicker.styles.ts
- packages/react/src/components/ColorPicker/__snapshots__/ColorPicker.test.tsx.snap
The ColorPicker preview color is not shown in force-colors mode
forced-color-adjust: none added to preview color box style
Verified in browser emulating forced-colors
Fixes: #27333
> fix: ColorPicker preview color updated to ignore forced colors

- .devops/templates/runpublishvrscreenshot.yml
- azure-pipelines.perf-test.yml
- package.json
- scripts/executors/checkIfPackagesAffected.js
- scripts/monorepo/src/getAffectedPackages.js
- scripts/monorepo/src/index.d.ts
- scripts/monorepo/src/utils.js
- check:affected-packages implements internal `-pr` flag which is not used and also wont support configuration
- we don't have reliable CLI to report affected packages for particular branch that would also notify user about lage false positives https://github.com/microsoft/fluentui/issues/26147
- `check:affected-packages` is refactored in 2 ways:
- npm script alias changed to `check:affected`
- `--pr` flag was removed (it is not used anywhere)
- added configurable `--base` argument
- will notify user about false positives (lage issue) 
- <img width="513" alt="image" src="https://user-images.githubusercontent.com/1223799/228523339-8c88221c-1760-43e0-808b-b1d691337640.png">
**Usage:**
```sh
yarn check:affected
> Set(2) {  '@fluentui/perf-test',  '@fluentui/perf-test-react-components' }
``` …
> feat(scripts-executors): support custom base and printing all affected packages for checkIfPackagesAffected

- change/@fluentui-react-utilities-370bb4f7-0783-4acf-bd47-07b1e38dcd19.json
- packages/react-components/react-utilities/etc/react-utilities.api.md
- packages/react-components/react-utilities/src/compose/getSlots.ts
- packages/react-components/react-utilities/src/compose/types.ts
This is a bug fix! types for `SlotRenderFunction` should properly include `children` as an option, and they currently don't.
1. Adds `children` as a possible value on the properties for `SlotRenderFunction`
2. This PR is solely about type fixing no functionality will change.
https://github.com/microsoft/fluentui/issues/27089
> bugfix(react-utilities): change SlotRenderFunction signature to include children

- packages/react-components/react-combobox/stories/Combobox/index.stories.tsx
- packages/react-components/react-combobox/stories/Dropdown/index.stories.tsx
No props tables for `Option` and `Listbox` on the `Combobox` and `Dropdown` doc pages.
Props tables for `Option` and `Listbox` are available on both the `Combobox` and `Dropdown` doc pages.
> docs: add subcomponents to Combobox and Dropdown docs

- .github/CODEOWNERS
@robtaft-ms was removed from codeowners due to not being in Microsoft org
@robtaft-ms joined Microsoft org, now can be codeowner
> Update CODEOWNERS to add robtaft-ms for Azure

- packages/react-components/react-checkbox/bundle-size/CheckboxField.fixture.js
- packages/react-components/react-combobox/bundle-size/ComboboxField.fixture.js
- packages/react-components/react-input/bundle-size/InputField.fixture.js
- packages/react-components/react-progress/bundle-size/ProgressField.fixture.js
- packages/react-components/react-radio/bundle-size/RadioGroupField.fixture.js
- packages/react-components/react-select/bundle-size/SelectField.fixture.js
- packages/react-components/react-slider/bundle-size/SliderField.fixture.js
- packages/react-components/react-spinbutton/bundle-size/SpinButtonField.fixture.js
- packages/react-components/react-switch/bundle-size/SwitchField.fixture.js
- packages/react-components/react-textarea/bundle-size/TextareaField.fixture.js
There are bundle size tests that refer to the deprecated `*Field` components, which are unnecessary and make it more difficult to read bundle size reports.
Remove bundle size tests from deprecated `*Field` components.
> chore: Remove bundle size tests from deprecated *Field components

- scripts/storybook/src/loaders/custom-loader.js
- scripts/storybook/src/rules.spec.ts
- scripts/storybook/src/utils.js
[Introduction  of `extends` with custom v9 preset within `babelrc` configs](https://github.com/microsoft/fluentui/pull/27313) broke  `_processBabelLoaderOptions`, thus griffel  preset was used during storybook builds. While on pure v9 packages, things mostly still worked as expected cross project storybooks stopped working triggering following build errors:
_Failure for `@fluentui/react-migration-v8-v9`:_
- we now exclude custom `'@fluentui/scripts-babel/preset-v9'` for storybook `babel-loader`. This mitigates any issues
- identity aliases for codesandbox babel plugin has been refactored, including excluding non relevant packages from mapping
- Follows https://github.com/microsoft/fluentui/pull/27313
> fix(scripts-storybook): make sure to exclude our custom v9 babel preset from storybook babel-loader

- apps/perf-test-react-components/just.config.ts
- apps/perf-test-react-components/package.json
- apps/perf-test-react-components/tsconfig.json
- apps/perf-test-react-components/webpack.config.js
- apps/perf-test/just.config.ts
- apps/perf-test/package.json
- apps/perf-test/tsconfig.json
- apps/perf-test/webpack.config.js
- azure-pipelines.perf-test.yml
- packages/fluentui/digest/package.json
- packages/fluentui/digest/src/digest.tsx
- packages/fluentui/digest/src/webpack.config.ts
- packages/fluentui/perf-test-northstar/just.config.ts
- packages/fluentui/perf-test-northstar/package.json
- packages/fluentui/perf-test-northstar/tasks/fluentPerfRegressions.ts
- scripts/storybook/src/rules.js
<table role="table">
<thead>
<tr>
<th>Test suite</th>
<th>Build time</th>
<th>Delta</th>
<th>Test time</th>
<th>Delta</th>
</tr>
</thead>
<tbody>
<tr>
<td>react-components: Before</td>
<td>186s</td>
<td rowspan="2">+96% 🚅</td>
<td>163s</td>
<td rowspan="2"><del>-63%</del>/ after rebase 0%</td>
</tr>
<tr>
<td>react-components: After</td>
<td>8s</td>
<td><del>262s</del> / after rebase 162s</td>
</tr>
<tr>
<td>react: Before</td>
<td>134s</td>
<td rowspan="2">+92% 🚅</td>
<td>1231s</td>
<td rowspan="2"><del>-65%</del> / after rebase ~0%</td>
</tr>
<tr>
<td>react: After</td>
<td>11s</td>
<td><del>1800s</del> / after rebase 1227s</td>
</tr>
<tr>
<td>react-northstar: Before</td>
<td>490s</td>
<td rowspan="2" style="background-color: greenyellow;">+93% 🚅</td>
<td>402s</td>
<td rowspan="2" …
> perf: use path aliases and swc for test:perf tasks to improve build speeds

- change/@fluentui-web-components-cd236262-0e75-4b91-a9b2-b7b574f558b9.json
- packages/web-components/package.json
- packages/web-components/src/button/button.styles.ts
- packages/web-components/src/index.ts
- packages/web-components/src/menu-button/define.ts
- packages/web-components/src/menu-button/index.ts
- packages/web-components/src/menu-button/menu-button.definition.ts
- packages/web-components/src/menu-button/menu-button.options.ts
- packages/web-components/src/menu-button/menu-button.stories.ts
- packages/web-components/src/menu-button/menu-button.template.ts
- packages/web-components/src/menu-button/menu-button.ts
> add menu button as new component

- change/@fluentui-web-components-a397834f-fd1f-4aa4-9251-14a59eacd0c6.json
- packages/web-components/package.json
Text was out of order alphabetically
Text is organized alphabetically
- Fixes #
> fix order of web component package exports

- change/@fluentui-react-d4744099-358e-4a73-991b-8d917fc90753.json
- packages/react/src/components/ComboBox/ComboBox.test.tsx
- packages/react/src/components/ComboBox/ComboBox.tsx
This is a regression introduced in #26574, and causes the `aria-activedescendant` value to not update when arrowing through options, which makes the control fully broken for screen reader users.
The root cause is that the `currentPendingValueValidIndex` needs to take precedence as the index of the active option, but the PR updated the logic to use `selectedIndices[0]` as the primary value, while it should be the fallback value.
`aria-activedescendant` is now calculated off of `currentPendingValueValidIndex`, falling back to `selectedIndices[0]`. This is what the behavior was prior to the PR.
> fix: v8 ComboBox needs to update aria-activedescendant value

- change/@fluentui-react-dialog-4ec18194-91df-4b16-9fdd-3f79ba3bc6a0.json
- packages/react-components/react-dialog/src/components/DialogTrigger/DialogTrigger.test.tsx
- packages/react-components/react-dialog/src/components/DialogTrigger/DialogTrigger.tsx
- packages/react-components/react-dialog/src/components/DialogTrigger/__snapshots__/DialogTrigger.test.tsx.snap
- packages/react-components/react-dialog/src/components/DialogTrigger/useDialogTrigger.ts
- packages/react-components/react-dialog/stories/Dialog/DialogTriggerOutsideDialog.md
- packages/react-components/react-dialog/stories/Dialog/DialogTriggerOutsideDialog.stories.tsx
1. removes `aria-expanded` attribute from `DialogTrigger`
2. update stories accordingly
- Fixes #27371
- Fixes #27368
> feat(react-dialog): removes `aria-expanded` from `DialogTrigger`

- scripts/generators/create-package/plop-templates-react/package.json.hbs
Adds `@fluentui/react-jsx-runtime` as a dependency for `create-package` v9 generator
- Fixes #27446
> feat(react-jsx-runtime): adds runtime to create-package generator

- packages/fluentui/perf/gulp/perf.ts
- packages/fluentui/perf/gulp/shared.ts
- packages/fluentui/perf/gulp/webpack.config.ts
- packages/fluentui/perf/package.json
- packages/fluentui/perf/src/globals.ts
- packages/fluentui/perf/src/index.tsx
- packages/fluentui/perf/tsconfig.json
- packages/fluentui/perf/types.ts
- scripts/gulp/src/webpack/webpack.config.e2e.ts
- tsconfig.base.v0.json
- obsolete configs removed from webpack
- introduced `type-check` alias to run tsc
- skipLibCheck for v0 enabled
* Follows https://github.com/microsoft/fluentui/pull/26410
> chore: remove obsolete configs and decouple type-check from bundling in v0 `perf` app

- change/@fluentui-react-tabs-e7f77370-547e-4ec6-acac-40a7008f2ed6.json
- packages/react-components/react-tabs/src/components/Tab/useTab.ts
Tab overrode the onClick handler, should have merged callbacks.
- Updated Tab to merge onClick callbacks
Fixes #27427
> Merged onClick callback in Tab

- packages/react-components/react-field/docs/Spec.md
Update Field's spec.md to describe the new method of passing field state via context instead of setting props directly on the child.
- #27399
> chore: Update Field spec for FieldContext

- change/@fluentui-react-charting-b2276f17-5bf5-4574-8ed6-a32817b67107.json
- packages/react-charting/src/components/Legends/shape.tsx
The triangle shape in line chart is matching with the pyramid shape in legends and hover card.
Similarly pyramid shape in line chart is matching with triangle shape in legends and hover card.
(See Third and Fifth legends)
Triangle and pyramid in line chart match with the corresponding entries in legend and hover card.
Fixes #27483 
- Fixes #
> Fix shape of triangle and pyramid

- packages/react-components/react-progress/stories/ProgressBar/ProgressBarColor.stories.tsx
- packages/react-components/react-progress/stories/ProgressBar/ProgressBarDefault.stories.tsx
- packages/react-components/react-progress/stories/ProgressBar/ProgressBarIndeterminate.stories.tsx
- packages/react-components/react-progress/stories/ProgressBar/ProgressBarMax.stories.tsx
- packages/react-components/react-progress/stories/ProgressBar/ProgressBarShape.stories.tsx
- packages/react-components/react-progress/stories/ProgressBar/ProgressBarThickness.stories.tsx
ProgressBar stories import directly from individual packages: react-progress and react-field. This causes lint errors in unrelated PRs, such as https://github.com/microsoft/fluentui/pull/27492.
Change ProgressBar stories to import from react-components instead of individual packages.
Similar fix in react-skeleton: #27498
> fix(react-progress): Stories should import from react-components

- packages/react-components/react-progress/stories/ProgressBar/index.stories.tsx
- packages/react-components/react-skeleton/stories/Skeleton/SkeletonAnimation.stories.tsx
- packages/react-components/react-skeleton/stories/Skeleton/SkeletonAppearance.stories.tsx
- packages/react-components/react-skeleton/stories/Skeleton/SkeletonDefault.stories.tsx
- packages/react-components/react-skeleton/stories/Skeleton/SkeletonRow.stories.tsx
- packages/react-components/react-skeleton/stories/Skeleton/index.stories.tsx
Skeleton stories import directly from individual packages: react-skeleton and react-field.
Change Skeleton stories to import from react-components instead of individual packages.
Similar fix in react-progress: #27497
> fix(react-skeleton): Stories should import from react-components

- apps/vr-tests-react-components/src/stories/Field.stories.tsx
Field VR tests weren't sufficiently testing the new behavior as of:
* #27399
* Allow controls to inherit `size` via the context.
* Add additional states for most controls in a field (beyond just error).
> chore: Update Field's VR tests to test changes from FieldContext

- apps/public-docsite/src/pages/Overviews/ControlsPage/docs/windows/ControlsOverview.md
- apps/public-docsite/src/pages/Overviews/GetStartedPage/docs/cross/GetStartedOverview.md
we use 'cross' for the crossplatform links, not 'crossplatform'. Seems we missed that new spelling in a couple spots. I searched for all instances and only found these two.
> fix website links to crossplatform that are now cross

- change/@fluentui-web-components-e7330a7e-73e6-4efd-a09f-84f488b8f917.json
- packages/web-components/package.json
- packages/web-components/src/anchor/index.ts
- yarn.lock
> update stable version of fast foundation to provide bug fixes

- packages/web-components/.storybook/preview-head.html
- packages/web-components/src/text/text.stories.ts
There is no background set for stories.
It is not obvious for a component whether is uses white or transparent background:
Stories in dark theme are broken:
The stories now use `colorNeutralBackground2`, the same as FUIR9 stories.
The difference between white and transparent is visible:
Dark theme works:
> chore(storybook): set background for WC stories

- packages/react-components/react-combobox/stories/Combobox/index.stories.tsx
- packages/react-components/react-combobox/stories/Dropdown/index.stories.tsx
- packages/react-components/react-datepicker-compat/stories/DatePicker/DatePickerFirstDayOfTheWeek.stories.tsx
- packages/react-components/react-select/stories/Select/index.stories.tsx
Combobox/Dropdown stories import directly from react-combobox. This causes the lint rule `@fluentui/no-restricted-imports` to fail in unrelated PRs, such as https://github.com/microsoft/fluentui/pull/27492. (I'm not sure why the lint rule isn't failing in the main build...)
Change Combobox/Dropdown stories to import from react-components instead of react-combobox.
Similar fixes in other packages:
- #27497
- #27498
> fix(react-combobox): Stories should import from react-components

- change/@fluentui-react-utilities-b6365940-5030-4940-81cd-01dbfdf2964b.json
- packages/react-components/react-utilities/src/hooks/useOnClickOutside.test.ts
- packages/react-components/react-utilities/src/hooks/useOnClickOutside.ts
- packages/react-components/react-utilities/src/hooks/useOnScrollOutside.test.ts
- packages/react-components/react-utilities/src/hooks/useOnScrollOutside.ts
We cleanup listeners and timeouts always.
```
> Mount Popover
> useEffect() [open: false] ➡️ skip addEventListener
> unmount()
> useEffect() [open: false] ➡️ do removeEventListener
>               👆 what?!
```
We will cleanup listeners and timeouts only when it's needed.
```
> Mount Popover
> useEffect() [open: false] ➡️ skip addEventListener
> unmount()
> useEffect() [open: false] ➡️ skip removeEventListener
>               ✅
```
> fix(hooks): cleanup event listeners only when "disabled" is false

- change/@fluentui-react-charting-f2c52d6b-db33-4e09-b29c-a8aacddd7667.json
- packages/react-charting/src/components/Legends/Legends.base.tsx
Screen reader announces wrong state information for legends when multiple selection is allowed
Screen reader announces correct state information for legends when multiple selection is allowed
> Fix wrong state narration for multiple selected legends

- change/@fluentui-react-field-e9d7d534-adfe-4fc5-a7e5-5849ba7b44c9.json
- packages/react-components/react-field/etc/react-field.api.md
- packages/react-components/react-field/src/components/Field/renderField.tsx
- packages/react-components/react-migration-v0-v9/src/components/FormField/FormFieldShim.tsx
FormFieldShim relies on Field's previous behavior of setting props on its child element, to get field props passed to the v0 input controls.
With PR #27399, Field uses context to pass props to its children, instead of setting props directly on the children. Field also supports a render-props function as its child, if using a component that doesn't get props from FieldContext.
Update FormFieldShim to use a render-props function as its child, in order to merge the field's props with the child's props. This results in similar behavior from before #27399.
- #27399
> fix: Update FormFieldShim to work with Field context changes

- change/@fluentui-react-combobox-c627d0c3-82f4-4593-8a10-546a41227e16.json
- packages/react-components/react-combobox/src/utils/useComboboxPopup.ts
When the listbox popup doesn't fit below or above the trigger, it doesn't try left/right positions.
Adds before & after fallbackPositions, so now the popup will attempt to position itself first after, then before the trigger (after below & above).
- Fixes #27486
> fix: react-combobox defines fallbackPositions for popup on small screens

- apps/public-docsite-v9/package.json
- apps/vr-tests-react-components/package.json
- change/@fluentui-react-datepicker-compat-dad5035c-25c8-4eac-b53a-e758b3850e69.json
- packages/react-components/react-datepicker-compat/package.json
This PR makes `react-datepicker-compat` public for people interested in using the preview version. Note that `0.0.0-beta.0` is used since this is a compat package.
> feat(react-datepicker-compat): Make package public

- apps/ssr-tests-v9/src/utils/helpers.ts
- apps/ssr-tests-v9/src/utils/visitPage.ts
Currently React 17 throws a warning when `aria-description` prop is used, which results in SSR tests throwing error and blocking build (https://github.com/microsoft/fluentui/pull/27443)
The warning is a bug in React 17 (https://github.com/facebook/react/issues/21035) and will be removed once upgraded to React 18.
Fixes #27464
> [Feature]: allow aria-description attribute on v9

- change/@fluentui-react-cc684d1e-b561-490a-a648-47ece08bdc45.json
- packages/react/src/components/pickers/BasePicker.tsx
The Picker input does not include selected items in its name or description in the ListBelow variant. This was fixed for the regular BasePicker as part of #17723.
The ListBelow variant now uses the same `aria-describedby` approach as the regular BasePicker.
- Fixes [16181](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/16181)
> fix: BasePickerListBelow aria-describedby with values

- change/@fluentui-react-utilities-1e1f8bd6-b059-4823-9a8d-f58d44482c6e.json
- packages/react-components/react-utilities/src/compose/getSlots.ts
Slot render functions don't work. This was caused by the change to `resolveShorthand` in #27472. It now sets the render function on `SLOT_RENDER_FUNCTION_SYMBOL` instead of `children`. The existing `getSlots` function is unaware of `SLOT_RENDER_FUNCTION_SYMBOL`, and thus ignores the render function.
Make `getSlots` check for `SLOT_RENDER_FUNCTION_SYMBOL` and use that as the render function instead of `children`, if present.
- Fixes #27559
Note: This PR is a quick fix and doesn't include tests. There should be tests written that would have caught this bug. I logged this to track adding tests:
- #27566
> fix: Fix slot render functions

- change/@fluentui-react-5d4582c1-8b8f-41aa-8f38-13a0481fda22.json
- packages/react/src/components/Callout/CalloutContent.base.tsx
- packages/react/src/components/Callout/CalloutContent.styles.ts
`useMaxHeight` wouldn't check if the provided height is larger than the current bounds causing the callout to be cut off.
`useMaxHeight` now checks if the provided maxHeight is larger than the bounds and if so, calculates the correct maxHeight.
- Fixes #26966
> fix(Callout): Update useMaxHeight to check if the provided maxHeight is larger than the bounds

- apps/stress-test/package.json
- change/@fluentui-web-components-6a017afa-1d29-4967-9507-7113fd37dbb5.json
- packages/web-components/package.json
- yarn.lock
> update FAST dependencies to mitigate Safari 16.4 AdoptedStyleSheets bug

- change/@fluentui-eslint-plugin-4cb91116-336f-417b-b9d2-7f4cf3911568.json
- packages/eslint-plugin/src/configs/react.js
1. enables jsx tags on comments for react config https://github.com/gajus/eslint-plugin-jsdoc/blob/main/.README/rules/check-tag-names.md#jsxtags
> feat(eslint-plugin): enables jsxTags on comment for react config

- change/@fluentui-react-provider-01464521-6329-44ea-be05-8aa792d0462b.json
- packages/react-components/react-provider/package.json
- packages/react-components/react-provider/src/components/FluentProvider/renderFluentProvider.tsx
Adopts `react-jsx-runtime` custom pragma on `react-provider`
> feat(react-provider): adopt custom JSX pragma

- change/@fluentui-react-menu-7f4bdd51-64d7-41a9-94c9-993823b00f5d.json
- packages/react-components/react-menu/package.json
- packages/react-components/react-menu/src/components/MenuDivider/renderMenuDivider.tsx
- packages/react-components/react-menu/src/components/MenuGroup/renderMenuGroup.tsx
- packages/react-components/react-menu/src/components/MenuGroupHeader/renderMenuGroupHeader.tsx
- packages/react-components/react-menu/src/components/MenuItem/renderMenuItem.tsx
- packages/react-components/react-menu/src/components/MenuItemCheckbox/renderMenuItemCheckbox.tsx
- packages/react-components/react-menu/src/components/MenuItemRadio/renderMenuItemRadio.tsx
- packages/react-components/react-menu/src/components/MenuList/renderMenuList.tsx
- packages/react-components/react-menu/src/components/MenuPopover/renderMenuPopover.tsx
- packages/react-components/react-menu/src/components/MenuSplitGroup/renderMenuSplitGroup.tsx
Adopts `react-jsx-runtime` custom pragma on `react-menu`.
> chore(react-menu): adopt custom JSX pragma

- change/@fluentui-react-dialog-5fee8f81-b41f-4655-a1c6-5dd45a7c336e.json
- packages/react-components/react-dialog/package.json
- packages/react-components/react-dialog/src/components/Dialog/renderDialog.tsx
- packages/react-components/react-dialog/src/components/DialogActions/renderDialogActions.tsx
- packages/react-components/react-dialog/src/components/DialogBody/renderDialogBody.tsx
- packages/react-components/react-dialog/src/components/DialogContent/renderDialogContent.tsx
- packages/react-components/react-dialog/src/components/DialogSurface/renderDialogSurface.tsx
- packages/react-components/react-dialog/src/components/DialogTitle/renderDialogTitle.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-dialog`
> chore(react-dialog):  adopt custom JSX pragma

- change/@fluentui-react-alert-935473ef-6eda-4240-b022-e82946cafdee.json
- packages/react-components/react-alert/package.json
- packages/react-components/react-alert/src/components/Alert/renderAlert.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-alert`
> chore(react-alert): adopt custom JSX pragma

- change/@fluentui-react-table-d5632f83-3b3d-4361-80f7-a4af77760493.json
- packages/react-components/react-table/package.json
- packages/react-components/react-table/src/components/DataGridBody/renderDataGridBody.tsx
- packages/react-components/react-table/src/components/DataGridRow/renderDataGridRow.tsx
- packages/react-components/react-table/src/components/Table/renderTable.tsx
- packages/react-components/react-table/src/components/TableBody/renderTableBody.tsx
- packages/react-components/react-table/src/components/TableCell/renderTableCell.tsx
- packages/react-components/react-table/src/components/TableCellActions/renderTableCellActions.tsx
- packages/react-components/react-table/src/components/TableCellLayout/renderTableCellLayout.tsx
- packages/react-components/react-table/src/components/TableHeader/renderTableHeader.tsx
- packages/react-components/react-table/src/components/TableHeaderCell/renderTableHeaderCell.tsx
- packages/react-components/react-table/src/components/TableResizeHandle/renderTableResizeHandle.tsx
- packages/react-components/react-table/src/components/TableRow/renderTableRow.tsx
- packages/react-components/react-table/src/components/TableSelectionCell/renderTableSelectionCell.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-table`
> chore(react-table): adopt custom JSX pragma

- change/@fluentui-react-tree-4dc34ddd-5922-4835-8c43-5a96d8cb1a1e.json
- packages/react-components/react-tree/package.json
- packages/react-components/react-tree/src/components/Tree/renderTree.tsx
- packages/react-components/react-tree/src/components/TreeItem/renderTreeItem.tsx
- packages/react-components/react-tree/src/components/TreeItemLayout/renderTreeItemLayout.tsx
- packages/react-components/react-tree/src/components/TreeItemPersonaLayout/renderTreeItemPersonaLayout.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-tree`
> chore(react-tree): adopt custom JSX pragma

- .github/CODEOWNERS
`packages/react-examples` did not have any CODEOWNERS defined, causing it to default to FluentUI Admins
Set CODEOWNERS of `packages/react-examples` to `@microsoft/cxe-red @microsoft/cxe-coastal`.
> Add CODEOWNERS for packages/react-examples

- scripts/tasks/src/lint-imports.ts
just-scripts task `lint-imports:all` logic regexp is incorrectly capturing `export` that don't provide any module specifier. This leads into false positives as those matches are processed as part of "evaluate imports" logic.
`export` declaration matches are ignored for imports evaluation logic
- Unblocks https://github.com/microsoft/fluentui/pull/26192
> fix(scripts-tasks): avoid processing export declaration types in _evaluateImport

- change/@fluentui-react-jsx-runtime-e321b00b-0fc8-427c-bb82-36948756d961.json
- packages/react-components/react-jsx-runtime/src/createElement.ts
Follow up on https://github.com/microsoft/fluentui/pull/27472#discussion_r1166478425
1. simplifies `createElement` method
> chore(react-jsx-runtime): simplify createElement method

- packages/react-components/react-migration-v0-v9/package.json
- packages/react-components/react-migration-v0-v9/src/components/ItemLayout/ItemLayout.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-migration-v0-v9`
> chore(react-migration-v0-v9): adopt custom JSX pragma

- packages/react-components/react-breadcrumb/package.json
- packages/react-components/react-breadcrumb/src/components/Breadcrumb/renderBreadcrumb.tsx
- packages/react-components/react-breadcrumb/src/components/BreadcrumbDivider/renderBreadcrumbDivider.tsx
- packages/react-components/react-breadcrumb/src/components/BreadcrumbItem/renderBreadcrumbItem.tsx
- packages/react-components/react-breadcrumb/src/components/BreadcrumbLink/renderBreadcrumbLink.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-breadcrumb`
> chore(react-breadcrumb): adopt custom JSX pragma

- change/@fluentui-react-textarea-03d80903-c025-4a83-956a-abe2c84d21ab.json
- packages/react-components/react-textarea/package.json
- packages/react-components/react-textarea/src/components/Textarea/renderTextarea.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-textarea`
> chore(react-textarea): adopt custom JSX pragma

- change/@fluentui-react-label-146937e6-7f52-4fbc-848a-8e7c74998933.json
- packages/react-components/react-label/package.json
- packages/react-components/react-label/src/components/Label/renderLabel.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-label`
> chore(react-label): adopt custom JSX pragma

- change/@fluentui-react-avatar-1b5a14f1-cef4-4396-b5a4-264bc60ee7c7.json
- packages/react-components/react-avatar/package.json
- packages/react-components/react-avatar/src/components/Avatar/renderAvatar.tsx
- packages/react-components/react-avatar/src/components/AvatarGroup/renderAvatarGroup.tsx
- packages/react-components/react-avatar/src/components/AvatarGroupItem/renderAvatarGroupItem.tsx
- packages/react-components/react-avatar/src/components/AvatarGroupPopover/renderAvatarGroupPopover.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-avatar`
> chore(react-avatar): adopt custom JSX pragma

- change/@fluentui-react-link-863a1ef3-2fdf-4503-a91d-84e9972e2b81.json
- packages/react-components/react-link/package.json
- packages/react-components/react-link/src/components/Link/renderLink.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-link`
> chore(react-link): adopt custom JSX pragma

- change/@fluentui-react-select-34a844e1-e317-451b-94ac-ee61c2ee07c1.json
- packages/react-components/react-select/package.json
- packages/react-components/react-select/src/components/Select/renderSelect.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-select`
> chore(react-select): adopt custom JSX pragma

- change/@fluentui-react-badge-7120f87c-f58b-4261-a2c7-445a9baf3007.json
- packages/react-components/react-badge/package.json
- packages/react-components/react-badge/src/components/Badge/renderBadge.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-badge`
> chore(react-badge): adopt custom JSX pragma

- change/@fluentui-react-switch-6560a210-3e3c-499c-a295-52260caf5f93.json
- packages/react-components/react-switch/package.json
- packages/react-components/react-switch/src/components/Switch/renderSwitch.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-switch`
> chore(react-switch): adopt custom JSX pragma

- change/@fluentui-react-datepicker-compat-f143ceb3-20ad-4819-bf20-0dc080c494ef.json
- packages/react-components/react-datepicker-compat/package.json
- packages/react-components/react-datepicker-compat/src/components/DatePicker/renderDatePicker.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-date-picker-compat`
> chore(react-date-picker-compat): adopt custom JSX pragma

- packages/react-components/react-tags/package.json
- packages/react-components/react-tags/src/components/Tag/renderTag.tsx
- packages/react-components/react-tags/src/components/TagButton/renderTagButton.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-tag`
> chore(react-tag): adopt custom JSX pragma

- change/@fluentui-react-tooltip-f7819a8a-2b0f-4263-b282-9e404a88889c.json
- packages/react-components/react-tooltip/package.json
- packages/react-components/react-tooltip/src/components/Tooltip/renderTooltip.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-tooltip`
> chore(react-tooltip): adopt custom JSX pragma

- change/@fluentui-react-input-4dc6eb85-7566-479c-9795-7b7cd3e2603a.json
- packages/react-components/react-input/package.json
- packages/react-components/react-input/src/components/Input/renderInput.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-input`
> chore(react-input): adopt custom JSX pragma

- change/@fluentui-react-checkbox-56ce06ef-aca2-41a7-af59-45344a2775b5.json
- packages/react-components/react-checkbox/package.json
- packages/react-components/react-checkbox/src/components/Checkbox/renderCheckbox.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-checkbox`
> chore(react-checkbox): adopt custom JSX pragma

- change/@fluentui-react-spinner-33b862af-f85f-49a3-8cb9-46efd6771481.json
- packages/react-components/react-spinner/package.json
- packages/react-components/react-spinner/src/components/Spinner/renderSpinner.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-spinner`
> chore(react-spinner): adopt custom JSX pragma

- change/@fluentui-react-skeleton-cebc03e7-07ac-48e2-a86d-a93a1ec458cb.json
- packages/react-components/react-skeleton/package.json
- packages/react-components/react-skeleton/src/components/Skeleton/renderSkeleton.tsx
- packages/react-components/react-skeleton/src/components/SkeletonItem/renderSkeletonItem.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-skeleton`
> chore(react-skeleton): adopt custom JSX pragma

- change/@fluentui-react-slider-3c2a7f85-6134-482b-8305-55799fe4af67.json
- packages/react-components/react-slider/package.json
- packages/react-components/react-slider/src/components/Slider/renderSlider.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-slider`
> chore(react-slider): adopt custom JSX pragma

- packages/react-components/react-theme/stories/Theme/fonts/ThemeFonts.stories.tsx
The text "Font family" is appended after the font family values, making it hard to read. (ie "sans-serifFont family" instead of just "sans-serif"). This was probably added by accident as the font family is seen in the adjacent table column. 
Deleted it
> Remove extra "Font family" text

- change/@fluentui-react-dialog-ca83b070-5c3c-4820-932f-b8f686d14b66.json
- packages/react-components/react-dialog/etc/react-dialog.api.md
- packages/react-components/react-dialog/src/components/Dialog/Dialog.cy.tsx
- packages/react-components/react-dialog/src/components/Dialog/useDialog.ts
- packages/react-components/react-dialog/src/components/Dialog/useDialogContextValues.ts
- packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurface.ts
- packages/react-components/react-dialog/src/components/DialogTrigger/useDialogTrigger.ts
- packages/react-components/react-dialog/src/contexts/dialogContext.ts
- packages/react-components/react-dialog/src/testing/mockUseDialogContext.ts
1. hoists tabster `useModalAttributes` invocation from `DialogSurface` and `DialogTrigger` to `Dialog` itself to ensure race conditions
2. stops spreading of tabster modal attributes on `non-modal` dialogs
3. adds test to ensure no regressions for https://github.com/microsoft/fluentui/issues/27468
- Fixes https://github.com/microsoft/fluentui/issues/27468
> chore(react-dialog): hoist tabster modal attributes to Dialog component

- change/@fluentui-react-popover-01561782-ac6f-4d45-b87a-0dbc28755256.json
- packages/react-components/react-popover/src/components/Popover/Popover.cy.tsx
- packages/react-components/react-popover/src/components/Popover/usePopover.ts
After rollout of `inertTrapFocus` property, `legacyTrapFocus` was deprecated and its value completely ignored.
1. Ensures that `legacyTrapFocus`, although deprecated is still a valid property that will ensure the opposite behaviour of `inertTrapFocus`
2. Adds test that will ensure `legacyTrapFocus` behaviour as equivalent to the opposite of `inertTrapFocus`
- Fixes https://github.com/microsoft/fluentui/issues/27447
> bugfix: ensure legacyTrapFocus works properly

- change/@fluentui-react-components-7105e198-75d7-4c94-9f29-0708d538d53c.json
- change/@fluentui-react-tree-96da4453-4b84-41e1-97c5-ae455bf6c037.json
- packages/react-components/react-components/etc/react-components.unstable.api.md
- packages/react-components/react-components/src/unstable/index.ts
- packages/react-components/react-tree/etc/react-tree.api.md
- packages/react-components/react-tree/src/components/Tree/Tree.cy.tsx
- packages/react-components/react-tree/src/components/Tree/Tree.tsx
- packages/react-components/react-tree/src/components/Tree/Tree.types.ts
- packages/react-components/react-tree/src/components/TreeItem/TreeItem.tsx
- packages/react-components/react-tree/src/components/TreeItem/TreeItem.types.ts
- packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx
- packages/react-components/react-tree/src/contexts/treeContext.ts
- packages/react-components/react-tree/src/hooks/useFlatTree.ts
- packages/react-components/react-tree/src/hooks/useFlatTreeNavigation.ts
- packages/react-components/react-tree/src/hooks/useNestedTreeNavigation.ts
- packages/react-components/react-tree/src/hooks/useOpenItemsState.ts
- packages/react-components/react-tree/src/index.ts
- packages/react-components/react-tree/src/utils/createFlatTreeItems.ts
- packages/react-components/react-tree/src/utils/flattenTree.ts
- packages/react-components/react-tree/stories/Tree/TreeControllingOpenAndClose.stories.tsx
- packages/react-components/react-tree/stories/Tree/TreeDefaultOpenTrees.stories.tsx
- packages/react-components/react-tree/stories/Tree/Virtualization.stories.tsx
- packages/react-components/react-tree/stories/Tree/flattenTree.stories.tsx
- packages/react-components/react-tree/stories/Tree/useFlatTree.stories.tsx
- packages/react-components/react-tree/stories/TreeItem/TreeItemAddRemove.stories.tsx
- packages/react-components/react-tree/stories/TreeItem/TreeItemExpandCollapseIconOnly.stories.tsx
- packages/react-components/react-tree/stories/TreeItem/TreeItemExpandIcon.stories.tsx
The `id` attribute would be used internally to decide whether or not a tree node is opened or closed
1. Adds `value` property to work as a reference to decide wether or not a node is opened or closed
2. Uses `id` as the default value for `value` property in the default case to simplify basic usage.
```tsx
export const DefaultOpenTrees = () => {
const defaultOpenTrees = ['default-subtree-1', 'default-subtree-2', 'default-subtree-2-1'];
return (
<Tree aria-label="Tree" defaultOpenItems={defaultOpenTrees}>
<TreeItem value="default-subtree-1">
<TreeItemLayout>level 1, item 1</TreeItemLayout>
<Tree>
<TreeItem>
<TreeItemLayout>level 2, item 1</TreeItemLayout>
</TreeItem>
<TreeItem>
<TreeItemLayout>level 2, item 2</TreeItemLayout>
</TreeItem>
<TreeItem>
<TreeItemLayout>level 2, item …
```
> feat(react-tree): value property over id

- change/@fluentui-web-components-482b832c-2b9e-4712-a120-a20052caf778.json
- packages/web-components/src/image/image.stories.ts
- packages/web-components/src/image/image.styles.ts
Updates story with better placeholder images. Sets default border-radius and updates **shape** param description in the story with detail about the default border radius and available values to choose from when implementing.
When **shape**: **rounded** is selected, no border-radius is applied.
**shape** param description in the story does not provide the developer with border-radius implementation details.
Border radius styles were added, using the 4px default value for when shape: rounded is selected.
The **shape**: **rounded** description in the story now has implementation details for the developer.
- Fixes #[1043544](https://powerbi.visualstudio.com/Trident/_workitems/edit/1043544)
> Update: Modify Image Web Component Styles

- change/@fluentui-react-a7b86699-056a-47f4-bd3e-f194277114b8.json
- packages/react/src/components/pickers/BasePicker.test.tsx
- packages/react/src/components/pickers/BasePicker.tsx
BasePicker attempted to set focus to an unfocusable `<div>` when managing focus in selected tags. This stemmed from earlier changes to make the interactive element within tags the remove button.
Updated the focus selector to point to the inner button, now focus is correctly set when a tag is removed.
- Fixes [16207](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/16207)
> fix: v8 Picker had incorrect element selector when setting focus

- change/@fluentui-react-5ce5a831-eb0f-4ea3-8c98-1b3c5237cb8a.json
- packages/react-examples/src/react/ScrollablePane/ScrollablePane.DetailsList.Example.tsx
- packages/react/etc/react.api.md
- packages/react/src/components/DetailsList/DetailsList.base.tsx
- packages/react/src/components/DetailsList/DetailsList.types.ts
The DetailsList w/ fixed header & footer example did not work with virtualization, since the `data-is-scrollable` prop was not added to the new scrolling region.
Since DetailsList only allows misc props to be added in certain places, I moved the scroll area to be the FocusZone, and added `data-is-scrollable` to the focusZoneProps.
Doing this required adding classNames to the inner focusZone and selectionZone, so there was also some prop spread & type cleanup:
- the `focusZoneProps.className` prop is respected now
- DetailsList's `selectionZoneProps` should be typed as a `Partial<>`, since DetailsList already provides all the required props to SelectionZone.
- Fixes [15441](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15441)
> fix: Detailslist fixed header example virtualization, DetailsList allows className in focusZoneProps, fix typing for selectionZoneProps

- apps/public-docsite/src/SiteDefinition/SiteDefinition.tsx
- apps/public-docsite/src/pages/Controls/ControlsAreaPage.tsx
- change/@fluentui-react-docsite-components-55a098aa-b0e5-41f6-9724-d7b9f4d1ba94.json
- packages/react-docsite-components/src/components/Page/Page.module.scss
- packages/react-docsite-components/src/components/Page/Page.tsx
- packages/react-docsite-components/src/components/Page/Page.types.ts
- packages/react-docsite-components/src/components/Page/sections/BannerSection.tsx
- packages/react-docsite-components/src/components/PageHeader/PageHeader.tsx
We only have a small banner announcing v9, but other than that there's no reference to our new version.
Remove previous banner and add a banner section to the page. This banner will only be shown in the React platform's component pages.
- Fixes #27284
> feat(public-docsite): Add banner to React component pages to promote v9

- change/@fluentui-react-datepicker-compat-59a888f8-093f-449c-b49e-4f580894da5e.json
- packages/react-components/react-datepicker-compat/etc/react-datepicker-compat.api.md
- packages/react-components/react-datepicker-compat/package.json
- packages/react-components/react-datepicker-compat/src/components/DatePicker/DatePicker.types.ts
- packages/react-components/react-datepicker-compat/src/components/DatePicker/defaults.ts
- packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx
- packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePickerStyles.ts
- packages/react-components/react-datepicker-compat/src/index.ts
- packages/react-components/react-datepicker-compat/stories/DatePicker/DatePickerErrorHandling.stories.tsx
- packages/react-components/react-datepicker-compat/stories/DatePicker/index.stories.tsx
DatePicker would validate and format dates by default, but this didn't come with a way to handle errors when validating the input.
DatePicker adds a padding to the popup and therefore the padding within calendar clashes and makes the padding look too large:
DatePicker now offers `onValidateError` to provide the dev a way to know when there's an error in the validation of the input. The error may be of time `required-input`, `out-of-bounds`, and `invalid-input`.
without padding: 
Fixes #27643
> feat(react-datepicker-compat): Add error handling to DatePicker and update popup's padding

- change/@fluentui-react-tree-409b60b2-2543-40ee-9e92-f53b02cecb5d.json
- packages/react-components/react-tree/src/components/Tree/Tree.cy.tsx
- packages/react-components/react-tree/src/hooks/useFlatTree.ts
- packages/react-components/react-tree/src/hooks/useFlatTreeNavigation.ts
- packages/react-components/react-tree/src/utils/createFlatTreeItems.ts
1. Fix bugs introduced by https://github.com/microsoft/fluentui/pull/27532
- PR #27532 introduced a bug where navigation from child element to parent was unable
2. Updates test to work properly without `id`
> bugfix(react-tree): fix parent navigation after independency from id

- change/@fluentui-react-8279ee8e-b6e5-4f7f-b9e7-18a13d31e6cb.json
- packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.tsx
Checkable split buttons inside of contextual menus are not setting `aria-checked` when neither `isChecked` nor `checked` are passed in. `aria-checked` should be set to `false` if neither `isChecked` nor `checked` are passed in.
Checkable split buttons inside of contextual menus now set `aria-checked` to `false` when neither `isChecked` nor `checked` are passed in. We're also now using the `getIsChecked` function to determine that since that is what is used at the end to determine if the split button is checkable or not.
- Fixes #27594
> fix: ContextualMenuSplitButton always sets aria-checked (does not leave it undefined) when it is checkable

- change/@fluentui-react-tabs-7068398a-7522-4df1-9dfe-0313fae2c8e6.json
- packages/react-components/react-tabs/package.json
- packages/react-components/react-tabs/src/components/Tab/renderTab.tsx
- packages/react-components/react-tabs/src/components/TabList/renderTabList.tsx
1. Adopts `react-jsx-runtime` custom pragma on `react-tabs`
> chore(react-tabs): adopts custom JSX pragma

- apps/ts-minbar-test-react/src/index.ts
- change/@fluentui-react-46a490a8-de1f-44df-84dc-99f9d17a8db8.json
- packages/react/etc/react.api.md
- packages/react/src/components/Tooltip/Tooltip.types.ts
- packages/react/src/components/Tooltip/TooltipHost.types.ts
see https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64999#discussioncomment-5519075
- Reverts https://github.com/microsoft/fluentui/pull/27426
- Fixes https://github.com/microsoft/fluentui/issues/27425
> fix(react): exclude React.HTMLAttributes defined `content` prop for Tooltip and TooltipHost Prop types to mitigate @types/react breaking changes

- change/@fluentui-react-dialog-4035cb74-88c2-4411-b3ac-9e1e049e2d69.json
- packages/react-components/react-dialog/etc/react-dialog.api.md
- packages/react-components/react-dialog/src/components/DialogTitle/DialogTitle.types.ts
- packages/react-components/react-dialog/src/components/DialogTitle/__snapshots__/DialogTitle.test.tsx.snap
- packages/react-components/react-dialog/src/components/DialogTitle/useDialogTitle.tsx
- packages/react-components/react-dialog/src/components/DialogTitle/useDialogTitleStyles.ts
`DialogTitle` root element was a `div` by default. This conflicts with design spec.
1. default `DialogTitle` root element as `h2`
2. add styles to ensure no visual regressions
> bugfix(react-dialog): `DialogTitle` root as `h2` by default

- change/@fluentui-react-charting-2cf73f57-767c-4339-bfb6-152caf82ad6c.json
- packages/react-charting/src/components/LineChart/LineChart.base.tsx
- packages/react-charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
Data points in LineChart are not accessible using screen reader
Data points in LineChart are accessible using screen reader
> Make line chart screen reader accessible

- change/@fluentui-react-datepicker-compat-f7349def-c3e5-4ea0-9ca7-e2be0c852515.json
- packages/react-components/react-datepicker-compat/etc/react-datepicker-compat.api.md
- packages/react-components/react-datepicker-compat/src/components/DatePicker/DatePicker.types.ts
- packages/react-components/react-datepicker-compat/src/components/DatePicker/defaults.ts
- packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx
- packages/react-components/react-datepicker-compat/src/index.ts
- packages/react-components/react-datepicker-compat/stories/DatePicker/DatePickerErrorHandling.stories.tsx
We provided an `onValidationError` prop to support error handling.
`onValidationError` is now renamed to `onValidationResult` and now the callback is fired after each input validation. This will allows us to send an undefined error to let the user know there's no longer an issue with the input.
> fix(react-datepicker-compat): Make onValidationError onValidationResult so the error is updated when there's no longer an error

- packages/react-components/react-breadcrumb/etc/react-breadcrumb.api.md
- packages/react-components/react-breadcrumb/src/components/Breadcrumb/useBreadcrumbStyles.ts
- packages/react-components/react-breadcrumb/src/components/BreadcrumbButton/useBreadcrumbButtonStyles.ts
- packages/react-components/react-breadcrumb/src/components/BreadcrumbItem/useBreadcrumbItemStyles.ts
- packages/react-components/react-breadcrumb/stories/BreadcrumbItem/BreadcrumbItemDefault.stories.tsx
Size of icons:
Size of icons:
Spacings and color:
> UI adjustments for the Breadcrumb

- .github/CODEOWNERS
- change/@fluentui-react-conformance-9b875b33-ced4-434a-9690-448766658f08.json
- packages/react-conformance/src/isConformant.ts
- packages/react-conformance/src/types.ts
- packages/react-conformance/src/utils/createTsProgram.ts
Conformance test used within projects that use TS path aliases are slow and cause various OOMemory leaks on CI.
This is caused by:
- bad architecture / technology constraints (jest as conformance env) 
- creation of TS Program, which in case of solution config file is forced to construct huge TS tree (all cy,unit,implementation,stories)
This PR adds new generic conformance config API which needs to be used for projects with ts solution configs. By leveraging this new API we get following benchmark improvements:
**Demo:**
```diff
const defaultOptions: Partial<IsConformantOptions<TProps>> = {
+  tsConfig: { configName: 'tsconfig.spec.json' },
componentPath: require.main?.filename.replace('.test', ''),
...
}
```
**Speed metrics::**
_Legend:_
- optimization v1 = fixing react-conformance to …
> feat(react-conformance): add new TS config api to be able to specify configName and configDir

- change/@fluentui-react-tree-84a7e55a-0a40-4b0e-8bb8-a3feb88fa234.json
- packages/react-components/react-tree/etc/react-tree.api.md
- packages/react-components/react-tree/src/hooks/useFlatTree.ts
- packages/react-components/react-tree/src/hooks/useFlatTreeNavigation.ts
- packages/react-components/react-tree/src/utils/createFlatTreeItems.ts
- packages/react-components/react-tree/src/utils/flattenTree.ts
- packages/react-components/react-tree/stories/D_flatTree/TreeItemAddRemove.stories.tsx
- packages/react-components/react-tree/stories/D_flatTree/Virtualization.stories.tsx
- packages/react-components/react-tree/stories/D_flatTree/flattenTree.stories.tsx
- packages/react-components/react-tree/stories/D_flatTree/useFlatTree.stories.tsx
Current behaviour makes it harder to introduce new properties to items provided to `useFlatTree` which might be cumbersome on some scenarios, as lazy loading
Refactors hooks to ensure generic properties are passed down the line, allowing modification of the end type that'll be available by `getTreeItemProps`
> feat(react-tree): makes useFlatTree generic

- change/@fluentui-react-combobox-aa8ff159-8fa3-4a0b-acf2-8b9bad6c66b7.json
- packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx
- packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx
Out of the box, the space key always selected the current option.
Only for freeform comboboxes, a separate typing/not typing state is tracked, and when the user is typing the space key inserts a character instead of selecting an option. The conditions for this to happen are:
- If the freeform combobox is closed, space always inserts a character
- If the user's previous keyboard interaction was to insert characters into the text input, space while also insert a character
- If the user has typed, and not used up/down/page up/page down/home/end, or opened the combobox with enter or alt+down since the last typing interaction.
An example: if the user types "hello" and then space, the space character will be inserted. If the user types "hello" and then moves the text insertion character to "h" …
> feat: react-combobox space conditionally inserts character when freeform is true

- change/@fluentui-react-utilities-fa9ce15a-c1d5-4b9a-93e7-e07b2d60b837.json
- packages/react-components/react-utilities/src/hooks/useControllableState.ts
1. Simplifies `useControllableState` implementation but ensuring same functionality according to tests
> chore(react-utilities): simplifies useControllableState hook internals

- packages/react/src/components/DetailsList/DetailsList.test.tsx
- packages/react/src/components/DetailsList/DetailsListV2.test.tsx
- packages/react/src/components/Dialog/Dialog.deprecated.test.tsx
- packages/react/src/components/Dialog/Dialog.test.tsx
- packages/style-utilities/src/styles/theme.test.ts
- scripts/jest/src/jest.preset.v8.js
- scripts/jest/src/jest.preset.v8.spec.ts
Both v0 and v8 tests contain memory leaks and consume above **2GB of memory per test** !!!
> discovered while executing via raw `jest` instead `gulp`
```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
```
some amount of v8 tests leak fixed. 
With this PR, test for v8 didn't go over 2GB heap.
**Speed metrics:**
| Run type (node --expose-gc ../../node_modules/.bin/jest --runInBand --logHeapUsage --no-cache ) | max heap size (MB) | delta |
| ----------------------------------------------------------------------------------------------- | ------------------ | ----- |
| …
> test(fluentui/react): fix initial global leaks that were causing OOM issues

- apps/public-docsite-v9/package.json
- apps/vr-tests-react-components/package.json
Packages with `@fluentui/react-datepicker-compat` have pinned dependencies.
Packages with `@fluentui/react-datepicker-compat` now use caret for their dependency.
> chore: Add caret to react-datepicker-compat dependencies

- .codesandbox/ci.json
- .devops/templates/tools.yml
- .github/workflows/check-packages.yml
- .github/workflows/docsite-publish-chromatic.yml
- .github/workflows/docsite-publish-ghpages.yml
- change/@fluentui-global-context-bd251f47-0c11-4359-86a3-0ddfbab981a4.json
- package.json
- packages/react-components/global-context/src/types.ts
- yarn.lock
- we no longer support NodeJS v14
- repo Node environment constraint is now set to v16 as minimum + optional node LTS (v18)
- CI uses our lowest supported node version which is 16.18.1
- Closes #27660
> chore: migrate to NodeJS v16

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Node version was 14
Node version is 16
> chore: upgrade devcontainer node version to 16

- packages/fluentui/e2e/tsconfig.json
- packages/fluentui/perf/tsconfig.json
- packages/fluentui/projects-test/tsconfig.json
- packages/fluentui/react-northstar/jest.config.js
- packages/fluentui/react-northstar/test/specs/commonTests/extraConformanceTests.tsx
- packages/fluentui/react-northstar/test/specs/commonTests/isConformant.tsx
- packages/fluentui/react-northstar/test/specs/components/Carousel/Carousel-test.tsx
- packages/fluentui/react-northstar/test/specs/components/Dropdown/Dropdown-test.tsx
- packages/fluentui/react-northstar/tsconfig.json
- packages/fluentui/react-northstar/tsconfig.spec.json
- scripts/jest/src/jest.preset.v0.js
- scripts/jest/src/v0/setupTests.js
- tsconfig.base.v0.json
v0 uses solely babel for transpilation thus tsc is doing unnecessary work. 
TSC only purpose is type checking and emmiting declaration files. 
This give use approx **10% speed bump** as well.
1. By leveraging new conformance API(https://github.com/microsoft/fluentui/pull/27664) we get following speed bump
> NOTE: metrics from local machine - M1 pro 10 Cores, on CI it's using maxWorkers 2 so its much slower
| Run type (yarn workspace @fluentui/react-northstar jest --no-cache) | time | delta |
| ----------------------------------------------------------------------------------------------- | ------------------ | ----- |
| current                                                                                     | 150s            |       |
| with new conformance api …
> chore(v0): enable emit only dts and use new conformance test API to narrow down TS Program

- packages/react-components/react-breadcrumb/etc/react-breadcrumb.api.md
- packages/react-components/react-breadcrumb/src/index.ts
- packages/react-components/react-breadcrumb/src/utils/index.ts
- packages/react-components/react-breadcrumb/src/utils/partitionBreadcrumbItems.test.ts
- packages/react-components/react-breadcrumb/src/utils/partitionBreadcrumbItems.ts
- packages/react-components/react-breadcrumb/stories/Breadcrumb/BreadcrumbWithOverflow.stories.tsx
- packages/react-components/react-breadcrumb/stories/Breadcrumb/index.stories.tsx
- Added partition for controlled overflow menu
- Added unit tests
- Used Overflow component
- Styling will be done in the following PR
Behavior with Overflow component:
**Note:** last item should be always visible
> Added partition for controlled overflow menu

- lage.config.js
lint task doesn't depend on any other task
adding "2. add back build pre-requirement to be able to run lint ( will slow down PR pipeline )" as temporary workaround
- Fixes temporarily https://github.com/microsoft/fluentui/issues/27727
> ci: add build task back as lint pre-requirement to unblock temporarily import plugin lint rule issues

- change/@fluentui-react-experiments-cedaca06-5cf3-4161-9c45-b13850f8a5cd.json
- packages/react-experiments/package.json
Adds export for `FolderCover.scss`. Similar export updates have been done in the past, ex: to Signals.scss: https://github.com/microsoft/fluentui/commit/aa4de2b58ad22f0f093e52343380b9fc37325b21
The OneDrive web team is working on a new experimental feature which requires us to create our own `FolderCover` component, adding an export for `FolderCover.scss` in react-experiments package so that we can re-use it 1-1 in our local version.
> Add export for FolderCover.scss

- change/@fluentui-date-time-utilities-a0aecb7b-3a32-4d59-97be-5a72945950f0.json
- change/@fluentui-dom-utilities-4870503f-6c4c-4f16-8410-849213615530.json
- change/@fluentui-font-icons-mdl2-f8af1b54-c711-481b-815b-55c190d712fd.json
- change/@fluentui-foundation-legacy-720281d9-c0bb-41d4-8d52-9931182c2775.json
- change/@fluentui-keyboard-key-7468c9a0-88bd-4f5c-b8c3-19934e6abaf9.json
- change/@fluentui-merge-styles-cbfe751f-e28b-4ebd-b17e-47b4005e9ba1.json
- change/@fluentui-react-8a7d357d-1295-4e6a-a77e-790989edaac0.json
- change/@fluentui-react-focus-4161aa46-456e-4ea9-9d37-011390ee242c.json
- change/@fluentui-react-hooks-b04425c0-6bd7-451a-a420-6349bd78e2ec.json
- change/@fluentui-react-window-provider-b5677baf-4da6-4fb5-a2b5-a1ae68df3760.json
- change/@fluentui-set-version-6d49c6e7-561b-415f-9817-d602b46fd119.json
- change/@fluentui-style-utilities-29d48d59-2b54-4f53-8610-3a12c54b6b71.json
- change/@fluentui-theme-f03403c3-7350-4846-93bf-cf0067b5b68d.json
- change/@fluentui-utilities-f0ea6572-c3c2-43ec-9f30-0615063f2bb8.json
- packages/date-time-utilities/.npmignore
- packages/dom-utilities/.npmignore
- packages/font-icons-mdl2/.npmignore
- packages/foundation-legacy/.npmignore
- packages/keyboard-key/.npmignore
- packages/merge-styles/.npmignore
- packages/react-focus/.npmignore
- packages/react-hooks/.npmignore
- packages/react-window-provider/.npmignore
- packages/react/.npmignore
- packages/set-version/.npmignore
- packages/style-utilities/.npmignore
- packages/theme/.npmignore
- packages/utilities/.npmignore
- with the repo upgrade to node 16, it seems like certain packages like `lib` and `lib-amd` are not being published despite being built. This PR explicitly adds to the `.npmignore` files of `@fluentui/react` and all packages within its dependency graph so that the `lib` and `lib-amd` folders are always included.
- Fixes #27732
> fix: dont ignore lib, lib-commonjs and lib-amd files

- tools/generators/migrate-converged-pkg/index.spec.ts
- tools/generators/migrate-converged-pkg/index.ts
`.swcrc` is excluded from publishing. This PR updates only a generator, a PR that updates `.npmignore` will be done separately.
> chore: add .swcrc to .npmignore (generator)

- change/@fluentui-react-avatar-6355cdad-17ab-443b-8a0d-c8499ea34898.json
- packages/react-components/react-avatar/src/components/AvatarGroupPopover/useAvatarGroupPopoverStyles.styles.ts
- packages/react-components/react-avatar/src/utils/getInitials.ts
- packages/react-components/react-avatar/stories/AvatarGroup/AvatarGroupDefault.stories.tsx
> fix(react-avatar): AvatarGroupPopover's content now uses column direction

- change/@fluentui-react-utilities-901b0a64-6ed5-4614-b87c-d2e49d9322c2.json
- packages/react-components/react-utilities/src/hooks/useControllableState.ts
Improves documentation for `useControllableState` to ensure a better understanding of how the hook properly operates.
- https://github.com/microsoft/fluentui/issues/25748
> chore(react-utilities): updates useControllableState comments

- scripts/update-release-notes/changelogsAndTags.ts
v8 releases were broken for quite some time but because we used node 14 which was allowing unhandled promise rejections it never blocked release so nobody noticed
_Example:_
1. node 14:
https://uifabric.visualstudio.com/UI%20Fabric/_build/results?buildId=299747&view=logs&j=8d802004-fbbb-5f17-b73e-f23de0c1dec8&t=ba6db26e-7b20-5e89-5cf3-08c91a4eaf9b
2. node 16:
After we migrated to node 16, these unhandled rejections start to process exit thus failing pipelines
https://uifabric.visualstudio.com/UI%20Fabric/_build/results?buildId=301085&view=logs&j=8d802004-fbbb-5f17-b73e-f23de0c1dec8
`update-release-notes` processing for tags from git now properly works. It will also print notification on every release run so v-build has more easier troubleshooting experience.
- Follows …
> fix(scripts-update-release-notes): properly handle git for-each-ref cmd call to not fail release notes update

- packages/react-components/react-tags/etc/react-tags.api.md
- packages/react-components/react-tags/src/components/Tag/Tag.test.tsx
- packages/react-components/react-tags/src/components/Tag/Tag.types.ts
- packages/react-components/react-tags/src/components/Tag/renderTag.tsx
- packages/react-components/react-tags/src/components/Tag/useTag.tsx
- packages/react-components/react-tags/src/components/Tag/useTagStyles.styles.ts
- packages/react-components/react-tags/src/components/TagButton/TagButton.test.tsx
- packages/react-components/react-tags/src/components/TagButton/renderTagButton.tsx
- packages/react-components/react-tags/src/components/TagButton/useTagButtonStyles.styles.ts
- packages/react-components/react-tags/stories/Tag/TagDefault.stories.tsx
- packages/react-components/react-tags/stories/Tag/TagDismiss.stories.tsx
- packages/react-components/react-tags/stories/Tag/TagShape.stories.tsx
- packages/react-components/react-tags/stories/TagButton/TagButtonDefault.stories.tsx
- packages/react-components/react-tags/stories/TagButton/TagButtonDismiss.stories.tsx
- packages/react-components/react-tags/stories/TagButton/TagButtonShape.stories.tsx
Rename misspelled prop dismissable to dismissible.
Alphabetically sort some types/objects.
> react-tags: rename dismissable to dismissible

- change/@fluentui-priority-overflow-a6802865-2d8b-43e0-8ac7-09dcca1570c8.json
- change/@fluentui-react-overflow-3a8651a5-c348-403c-a0a7-eaab0b660b52.json
- packages/react-components/priority-overflow/src/overflowManager.ts
- packages/react-components/react-overflow/src/Overflow.cy.tsx
- packages/react-components/react-overflow/src/components/Overflow.tsx
Fixes #27656 which was caused by a priority queue edge case.
On initial mount the resize observer will always run. If there is already overflow then the tops of the visibility queues will be different from the initial state (all items are considered visible by default).
In the cause where there is no overflow initially the queue tops will not change, which does not trigger a dispatch to the react bindings so the `useIsOverflowItemVisible` hook will always return `false` until overflow occurs.
The fix is quite simple: set the initial value of flag `forceDispatch` to be `true` which will always trigger a dispatch for initial mount.
> fix: overflowManager should always dispatch initial state

- change/@fluentui-react-tree-e91902ae-b031-47c0-99be-2f7450c3f3f7.json
- packages/react-components/react-tree/src/utils/createFlatTreeItems.ts
Seems like some visible items are being omitted https://codesandbox.io/s/useflat-repro-forked-w04vpv?file=/example.tsx . In this example `Level 1, item 2` should be visible by default, but it's filtered out by `VisibleFlatTreeItemGenerator`
1. Ensure `VisibleFlatTreeItemGenerator` doesn't jump any visible item.
2. TODO: add tests to ensure this won't happen again
> bugfix(react-tree): fix VisibleFlatTreeItemGenerator omitting visible items

- change/@fluentui-react-utilities-3e7e29b4-ccde-4269-ac7f-8adf2333171e.json
- packages/react-components/react-utilities/src/hooks/useControllableState.ts
1. defers initialization of internal state of the `useControllableState` hook to the init method provided by `useState` hook
> feat: defers useControllableState state to initializer method

- packages/react-components/react-toast/src/components/Toast.tsx
- packages/react-components/react-toast/src/components/Toaster.tsx
- packages/react-components/react-toast/src/state/types.ts
- packages/react-components/react-toast/src/state/useToast.ts
- packages/react-components/react-toast/src/state/vanilla/toast.ts
- packages/react-components/react-toast/src/state/vanilla/toaster.ts
- packages/react-components/react-toast/stories/Toast/PauseOnHover.stories.tsx
- packages/react-components/react-toast/stories/Toast/PauseOnWindowBlur.stories.tsx
- packages/react-components/react-toast/stories/Toast/index.stories.tsx
Implements two new options:
* pauseOnWindowBlur - pauses toast timeout when window is not focused
* pauseOnHover - pauses toast when cursor enters the toast surface
Addresses  https://github.com/microsoft/fluentui/issues/27776
> feat: Implement Toast pause

- packages/react-components/react-toast/etc/react-toast.api.md
- packages/react-components/react-toast/src/components/Toast.tsx
- packages/react-components/react-toast/src/components/Toaster.tsx
- packages/react-components/react-toast/src/state/types.ts
- packages/react-components/react-toast/src/state/useToast.ts
- packages/react-components/react-toast/src/state/useToastController.ts
- packages/react-components/react-toast/src/state/useToaster.ts
- packages/react-components/react-toast/src/state/vanilla/dispatchToast.ts
- packages/react-components/react-toast/src/state/vanilla/toast.ts
- packages/react-components/react-toast/src/state/vanilla/toaster.ts
- packages/react-components/react-toast/stories/Toast/DefaultToastOptions.stories.tsx
- packages/react-components/react-toast/stories/Toast/index.stories.tsx
Allows toaster to set default options for toasts
Addresses https://github.com/microsoft/fluentui/issues/27776
> feat: Allow toast options to be configured from the toaster

- change/@fluentui-react-tree-e43c53f4-8d36-486e-a2df-4a0f3da1c4d1.json
- packages/react-components/react-tree/src/components/TreeItem/useTreeItemStyles.styles.ts
- packages/react-components/react-tree/src/components/TreeItemLayout/useTreeItemLayoutStyles.styles.ts
Currently provided column size on tree item grid `auto min-content` doesn't allow proper overflowing of the layout content
1. grid column size redefined to `minmax(0px, 100%) minmax(0px, min-content)`  that allows proper overflowing of the content
- Fixes https://github.com/microsoft/fluentui/issues/27714
> bugfix: fix horizontal overflow on tree

- packages/react-components/react-toast/etc/react-toast.api.md
- packages/react-components/react-toast/src/state/constants.ts
- packages/react-components/react-toast/src/state/types.ts
- packages/react-components/react-toast/src/state/useToastController.ts
- packages/react-components/react-toast/src/state/useToaster.ts
- packages/react-components/react-toast/src/state/vanilla/dismissAllToasts.ts
- packages/react-components/react-toast/src/state/vanilla/dismissToast.ts
- packages/react-components/react-toast/src/state/vanilla/index.ts
- packages/react-components/react-toast/src/state/vanilla/toaster.ts
- packages/react-components/react-toast/stories/Toast/CustomTimeout.stories.tsx
- packages/react-components/react-toast/stories/Toast/Default.stories.tsx
- packages/react-components/react-toast/stories/Toast/DefaultToastOptions.stories.tsx
- packages/react-components/react-toast/stories/Toast/DismissAll.stories.tsx
- packages/react-components/react-toast/stories/Toast/DismissToast.stories.tsx
- packages/react-components/react-toast/stories/Toast/MultipleToasters.stories.tsx
- packages/react-components/react-toast/stories/Toast/PauseOnHover.stories.tsx
- packages/react-components/react-toast/stories/Toast/PauseOnWindowBlur.stories.tsx
- packages/react-components/react-toast/stories/Toast/ToastPositions.stories.tsx
- packages/react-components/react-toast/stories/Toast/UpdateToast.stories.tsx
- packages/react-components/react-toast/stories/Toast/index.stories.tsx
Adds the `toasterId` prop to all Toaster components and controllers. If a Toaster has the `toasterId` prop set, then it will ignore any toast events except those with its id.
This change required splitting up the dismissing functionalities into:
- dismissToast - for single toasts
- dismissAllToasts - to dismiss all toasts
Addresses https://github.com/microsoft/fluentui/pull/27827
> feat: Implement support for multiple toaster on a page

- change/@fluentui-react-utilities-22f9b966-d085-4744-a402-a333796c653f.json
- packages/react-components/react-toast/src/state/types.ts
- packages/react-components/react-toast/src/state/useToaster.ts
- packages/react-components/react-toast/src/state/vanilla/dispatchToast.ts
- packages/react-components/react-toast/src/state/vanilla/toaster.ts
- packages/react-components/react-toast/stories/Toast/ToasterLimit.stories.tsx
- packages/react-components/react-toast/stories/Toast/index.stories.tsx
- packages/react-components/react-utilities/etc/react-utilities.api.md
- packages/react-components/react-utilities/src/index.ts
- packages/react-components/react-utilities/src/utils/index.ts
- packages/react-components/react-utilities/src/utils/priorityQueue.test.ts
- packages/react-components/react-utilities/src/utils/priorityQueue.ts
Adds the new `limit` prop to `Toaster` which will limit the number of visible toasts on the page.
This is done internally using a priority queue based on the creation date. This will also support toast priorities in the queue.
Addresses #27827
> feat: Implement limit for toast stacking

- packages/react-components/react-tags/etc/react-tags.api.md
- packages/react-components/react-tags/src/components/Tag/Tag.types.ts
- packages/react-components/react-tags/src/components/Tag/renderTag.tsx
- packages/react-components/react-tags/src/components/Tag/useTag.tsx
- packages/react-components/react-tags/src/components/Tag/useTagStyles.styles.ts
- packages/react-components/react-tags/src/components/TagButton/TagButton.types.ts
- packages/react-components/react-tags/src/components/TagButton/useTagButton.tsx
- packages/react-components/react-tags/src/components/TagButton/useTagButtonStyles.styles.ts
- packages/react-components/react-tags/src/utils/useTagContextValues.ts
- packages/react-components/react-tags/stories/Tag/index.stories.tsx
- packages/react-components/react-tags/stories/TagButton/index.stories.tsx
Before this PR, basic Tag has `dismissButton` slot to dismiss itself. This PR make the Tag itself a button that does dismiss, and changes `dismissButton` slot to `dismissIcon`. And this PR keeps TagButton unchanged - it's still two buttons.
```tsx
root: NonNullable<Slot<'div'>>;
dismissButton?: Slot<'button'>;
```
```tsx
root: NonNullable<Slot<'button'>>;
dismissIcon?: Slot<'span'>;
```
- Why this change:
In fluent v0 Pill, the focus ring is around the entire Pill. We would want the same for v9 basic Tag. Also this is useful for user with magnifier that tracks focus.
- What does this mean for #27794:
I will keep two controls Tag/TagButton instead of one Tag, and close PR 27794. Because basic Tag and TagButton have different slots. The differences are:
1. Basic Tag has dismiss icon …
> feat(react-tags): make basic Tag a button instead of div

- packages/react-components/react-toast/etc/react-toast.api.md
- packages/react-components/react-toast/src/components/Toaster.tsx
- packages/react-components/react-toast/src/index.ts
- packages/react-components/react-toast/src/state/types.ts
- packages/react-components/react-toast/src/state/vanilla/getPositionStyles.ts
- packages/react-components/react-toast/stories/Toast/Offset.stories.tsx
- packages/react-components/react-toast/stories/Toast/index.stories.tsx
Implements `offset` prop for the Toaster. The offset should be configurable for each position.
Fixes https://github.com/microsoft/fluentui/issues/27776
> feat: implement Toaster offset

- apps/recipes-react-components/.storybook/preview.js
- apps/recipes-react-components/src/DocComponents/FluentDocsContainer.stories.tsx
When rendering a recipe in the local storybook there was no FluentProvider, therefore the Fluent components weren't styled correctly.
Recipes are wrapped with a FluentProvider in the local storybook. Note that the provider is added by the local storybook, outside of the local package the change will take no effect.
> fix(recipes-react-components): Add a FluentProvider to the local storybook

- change/@fluentui-react-tabster-15456040-19ed-4576-b0d5-918ea610f2dd.json
- packages/react-components/react-tabster/package.json
- yarn.lock
1. Bumps tabster version to 4.4.0
- Fixes https://github.com/microsoft/fluentui/issues/27487
- Fixes https://github.com/microsoft/fluentui/issues/26824
> chore(react-tabster): upgrade tabster to v4.4.2

- azure-pipelines.yml
- lage.config.js
- package.json
This PR adds `test-ssr` script to "buildci" script and modifies Lage's config, so the scripts will start to run on CI.
Previous PRs: #27444, #27463, #27690
Next steps:
- Add implementation to `@fluentui/scripts-test-ssr`
- Drop testing logic from `@fluentui/ssr-tests-v9`
> chore: add test-ssr to buildci script

- package.json
- packages/react-components/babel-preset-storybook-full-source/package.json
- yarn.lock
Manually migrated to latest prettier to match nx migration deps
- Follows https://github.com/microsoft/fluentui/pull/27885
> chore: migrate to prettier 2.8.8

- change/@fluentui-react-textarea-da38b5b6-139a-42de-b425-abceddc48a77.json
- packages/react-components/react-textarea/src/components/Textarea/useTextareaStyles.styles.ts
Textarea was applying the disabled textarea styles with a selector on the wrapper.
Textarea now doesn't use a selector to apply disabled styles for the textarea.
- Fixes #27838
> fix(react-textarea): Move disabled styles in textarea selector to the textarea styles

- change/@fluentui-react-be1fc47e-c473-4abf-98b8-38adda0aab8b.json
- packages/react/src/components/Pivot/Pivot.styles.ts
- packages/react/src/components/Pivot/__snapshots__/Pivot.test.tsx.snap
The focus outline on the selected tab was not adequately distinguishable from the background (dark grey on dark blue):
The focus style for the selected link-as-tab is now an inset white outline:
- Fixes [16120](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/16120)
> fix: Pivot focus outline is visible on link-as-tab variant

- change/@fluentui-react-accordion-f25a187c-893c-4c69-a270-b1a405788277.json
- packages/react-components/react-accordion/etc/react-accordion.api.md
- packages/react-components/react-accordion/src/components/Accordion/Accordion.types.ts
- packages/react-components/react-accordion/src/components/AccordionHeader/AccordionHeader.test.tsx
- packages/react-components/react-accordion/src/components/AccordionHeader/AccordionHeader.types.ts
- packages/react-components/react-accordion/src/components/AccordionHeader/__snapshots__/AccordionHeader.test.tsx.snap
- packages/react-components/react-accordion/src/components/AccordionHeader/renderAccordionHeader.tsx
- packages/react-components/react-accordion/src/components/AccordionHeader/useAccordionHeader.tsx
- packages/react-components/react-accordion/src/components/AccordionItem/AccordionItem.types.ts
- packages/react-components/react-accordion/src/components/AccordionPanel/AccordionPanel.types.ts
AccordionHeader is broken when `expandIcon={null}` https://codesandbox.io/s/sad-taussig-s7cfkd?file=/example.tsx
1. ensures verification of nullability for the `expandIcon` slot on `renderAccordionHeader` method.
2. properly declare `Accordion` slot types to include `NonNullable` and `?` (optional) cases
3. adds test to properly map this problem
- Fixes https://github.com/microsoft/fluentui/issues/27911
> chore(react-accordion): ensures AccordionHeader expandIcon supports null

- packages/react-components/react-toast/etc/react-toast.api.md
- packages/react-components/react-toast/src/state/useToastController.ts
- packages/react-components/react-toast/stories/Toast/CustomTimeout.stories.tsx
- packages/react-components/react-toast/stories/Toast/Default.stories.tsx
- packages/react-components/react-toast/stories/Toast/DefaultToastOptions.stories.tsx
- packages/react-components/react-toast/stories/Toast/DismissAll.stories.tsx
- packages/react-components/react-toast/stories/Toast/DismissToast.stories.tsx
- packages/react-components/react-toast/stories/Toast/MultipleToasters.stories.tsx
- packages/react-components/react-toast/stories/Toast/Offset.stories.tsx
- packages/react-components/react-toast/stories/Toast/PauseOnHover.stories.tsx
- packages/react-components/react-toast/stories/Toast/PauseOnWindowBlur.stories.tsx
- packages/react-components/react-toast/stories/Toast/ToastPositions.stories.tsx
- packages/react-components/react-toast/stories/Toast/ToasterLimit.stories.tsx
- packages/react-components/react-toast/stories/Toast/UpdateToast.stories.tsx
toasterId can no longer be used from the individual control functions such as `dispatchToast`.
Instead, the useToastController should be called with the correct toasterId to return controls for a specific toaster. This should promote modular use of the API and encapsulate toaster behaviour better.
before
```ts
const { dispatch }  = useToastController();
dispatchToast('toast', { toasterId });
```
after
```ts
const { dispatch }  = useToastController(toasterId);
dispatchToast('toast');
```
> feat: useToastController should handle toasterId

- packages/react-components/react-skeleton/stories/Skeleton/SkeletonDescription.md
- packages/react-components/react-skeleton/stories/Skeleton/index.stories.tsx
`Skeleton` was promoted to stable (#27767), but it's still under "Preview". This PR fixes that:
> docs(react-skeleton): fix section and update description

- change/@fluentui-react-datepicker-compat-c7052ce3-4b8a-4668-a7ae-f569d7bf875e.json
- packages/react-components/react-datepicker-compat/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
- packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx
`aria-owns` was applied always.
`aria-owns` is now applied only when popup is open, this will fix an issue with having aria-owns linked to something undefined.
> fix(react-datepicker-compat): Only apply aria-owns when popup is rendered

- packages/react-components/react-avatar/stories/AvatarGroup/AvatarGroupTooltip.stories.tsx
- packages/react-components/react-avatar/stories/AvatarGroup/index.stories.tsx
Adds an example to AvatarGroup that show how
you can customize the tooltip of the AvatarGroupPopover.
- Fixes #27696
> docs(avatargroup): add tooltip example

- packages/react-components/react-breadcrumb/src/components/BreadcrumbDivider/useBreadcrumbDivider.tsx
- packages/react-components/react-breadcrumb/stories/BreadcrumbDivider/BreadcrumbDividerDefault.stories.tsx
> Add support for RTL divider on Breadcrumb

- change/@fluentui-react-dialog-100a6339-0f6d-4d43-ba54-f2c1475a9308.json
- packages/react-components/react-dialog/etc/react-dialog.api.md
- packages/react-components/react-dialog/src/components/DialogTitle/useDialogTitle.tsx
- packages/react-components/react-drawer/etc/react-drawer.api.md
- packages/react-components/react-drawer/src/components/DrawerHeaderTitle/useDrawerHeaderTitle.ts
```ts
export const useDialogTitle_unstable = (
props: DialogTitleProps,
ref: React.Ref<HTMLElement>
): DialogTitleState => {}
```
```ts
export const useDialogTitle_unstable = (
props: DialogTitleProps,
ref: React.Ref<HTMLDivElement>
): DialogTitleState => {}
```
1. changes `ref` argument from `HTMLElement` to `HTMLDivElement` as it's more precise to the actual root type for:
* `useDialogTitle_unstable`
* `useDrawerHeaderTitle_unstable`
> chore(react-dialog): fix useDialogTitle ref argument type

- apps/public-docsite-v9/src/Concepts/Migration/KeepingDesignConsistent.stories.mdx
Fixes #27748.
Fixes various typos, missing imports and syntax errors.
> docs(v9): fix typos in KeepingDesignConsistent.stories.mdx

- change/@fluentui-react-utilities-66d57a65-a181-4667-ba3e-a17909109d03.json
- packages/react-components/react-utilities/src/hooks/useControllableState.test.ts
- packages/react-components/react-utilities/src/hooks/useControllableState.ts
Fixes regression introduced in #27702.
New test is added for the scenario used in `DataGrid` hooks.
Fixes #27896
> fix(react-utilities): fix dispatcher behavior

- packages/react-components/react-datepicker-compat/stories/DatePicker/DatePickerErrorHandling.stories.tsx
Error handling story uses Date.now()
Error handling story doesn't use Date.now() instead it uses a specific date.
- Fixes #27957
> fix(react-datepicker-compat): Error handling story now doesn't use Date.now to avoid SSR errors

- change/@fluentui-react-card-126332c1-e2ea-4240-bec1-2d1b54240d28.json
- change/@fluentui-react-tabster-e08134a8-73c8-441b-8bd1-345e20b300a4.json
- packages/react-components/react-card/src/components/Card/useCardStyles.styles.ts
- packages/react-components/react-tabster/src/focus/createFocusOutlineStyle.ts
This PR adds basic support for CSS Variables being passed to the `createFocusOutlineStyle`.
For more context, please refer to this bug: #27954
> fix: createFocusOutlineStyle don't work with CSS variables

- change/@fluentui-react-toolbar-cd3d2025-51f1-430b-b2b1-eaa3b885de3b.json
- packages/react-components/react-toolbar/src/components/ToolbarDivider/useToolbarDividerStyles.styles.ts
ToolbarDivider didn't have proper style order, meaning that the passed styles would be overriden by the default ones.
The passed styles have priority.
- Fixes #28042
> Fix toolbar divider styles

- change/@fluentui-react-datepicker-compat-f276a459-aa9c-4f3b-bb52-ac556558e5ec.json
- packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx
`focus` function used to be part of deps to move focus to the calendar, this cause a constant move of focus to the calendar.
`focus` has been removed from the deps to stop stealing focus.
- Fixes #28009
> fix(react-datepicker-compat): Remove focus function from the deps to avoid constant move of focus

- change/@fluentui-react-combobox-05c147ce-b714-4845-8ccd-ec6268ba92cf.json
- packages/react-components/react-combobox/etc/react-combobox.api.md
- packages/react-components/react-combobox/src/Selection.ts
- packages/react-components/react-combobox/src/index.ts
> Export selection types from combobox

- apps/public-docsite-v9/src/Concepts/Migration/KeepingDesignConsistent.stories.mdx
- Updated migration design documentation to mention v8 Fluent2 theme and link to the v8 documentation.
> Updated migration documentation

- change/@fluentui-react-infobutton-674485ad-8621-45a2-92ab-bc4d3a6b9004.json
- packages/react-components/react-infobutton/etc/react-infobutton.api.md
- packages/react-components/react-infobutton/src/InfoTip.ts
- packages/react-components/react-infobutton/src/components/InfoTip/InfoTip.test.tsx
- packages/react-components/react-infobutton/src/components/InfoTip/InfoTip.tsx
- packages/react-components/react-infobutton/src/components/InfoTip/InfoTip.types.ts
- packages/react-components/react-infobutton/src/components/InfoTip/__snapshots__/InfoTip.test.tsx.snap
- packages/react-components/react-infobutton/src/components/InfoTip/index.ts
- packages/react-components/react-infobutton/src/components/InfoTip/renderInfoTip.tsx
- packages/react-components/react-infobutton/src/components/InfoTip/useInfoTip.ts
- packages/react-components/react-infobutton/src/components/InfoTip/useInfoTipStyles.styles.ts
- packages/react-components/react-infobutton/src/index.ts
- packages/react-components/react-infobutton/stories/InfoTip/InfoTipBestPractices.md
- packages/react-components/react-infobutton/stories/InfoTip/InfoTipDefault.stories.tsx
- packages/react-components/react-infobutton/stories/InfoTip/index.stories.tsx
This PR adds the InfoTip component scaffold. InfoTip is another use case of a info bubble, we currently have an InfoButton that requires the user to click a button to get the information and InfoTip provides focus/hover toggle behavior. InfoTip is useful when there's focusable items while InfoTip is useful for short text and when there's no focusable elements.
- Fixes #28070
> chore(react-infobutton): Add InfoTip component scaffold

- apps/public-docsite-v9/src/Concepts/Migration/FromV0/Components/Button.stories.mdx
The v0 to v9 `Button` migration docs referred to the `block` prop when talking about migration of the `fluid` prop in v0. The `block` prop does not exist in v9 after being deprecated and removed before the first stable version of v9.
The v0 to v9 `Button` migration docs do not reference the `block` prop anymore when talking about migration of the `fluid` prop in v0. The actual recommendation to use styles' customization to achieve this is written now.
- Fixes #27715
> chore: Updating v0 to v9 Button migration docs to remove reference to non-existent block prop

- change/@fluentui-utilities-935d72bf-a3ff-428f-b440-fe912842be69.json
- packages/utilities/src/useFocusRects.ts
When `useFocusRects` is minified with terser, the default behavior would inline the function definition for `setCallbackMap` into the call site within the hook. This would cause it to capture additional variables in its closure, which would in turn be stored by the functions on the `callbackMap` WeakMap. This can cause memory leaks for some host applications.
We use the [NOINLINE terser directive](https://github.com/terser/terser#annotations) to prevent the inlining behavior.
> Dont inline setcallbackmap with terser to prevent memory leaks

- change/@fluentui-react-conformance-09db4fc5-2f5c-4dbe-a602-2c226cff5bab.json
- packages/react-conformance/src/defaultTests.tsx
- Passing in custom classname prefix like below does **not** do anything:
```js
testOptions: {
'component-has-static-classname': {
/** Prefix for the classname, if not `fui-` */
prefix: 'fai',
},
}
```
- Passing in custom classname prefix (like the one outlined above) now works:
> fix(react-conformance): custom classname prefix test option now works 

- change/@fluentui-react-4cf263e9-5a59-4ce0-b9b1-a08d8baa5e67.json
- packages/react/src/components/Dropdown/Dropdown.styles.ts
- packages/react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
A non-HCM background style was overriding the background color in HCM, causing the text to be unreadable:
This PR resets the HCM colors for the multiselect hover selector, so it matches single-select hover (HighlightText on Highlight background)
- Fixes [15910](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15910)
> fix: v8 Dropdown multiselect option hover contrast in WHCM

- change/@fluentui-react-bf3bb0f5-64ca-4492-be5c-82e7a6808157.json
- packages/react/src/components/MessageBar/MessageBar.styles.ts
- packages/react/src/components/MessageBar/__snapshots__/MessageBar.test.tsx.snap
fixes #27749
Single line message bars are now layed out like multi line message bars when shown on small screen sizes or high zoom
> Message bar zoom

- change/@fluentui-react-combobox-a0ef5216-e89a-420a-9879-ec97275c3f1f.json
- packages/react-components/react-combobox/src/components/Option/useOptionStyles.styles.ts
The provided className for checkIcon is not added at the end, this causes issues when trying to override styles.
The provided className for checkIcon is added at the end, allowing overrides for the slot.
> fix(react-combobox): Option's checkIcon adds provided className at the end to avoid overrides

- change/@fluentui-react-dialog-f53ccc8c-8b2f-4726-8d7a-e61990a04769.json
- packages/react-components/react-dialog/src/components/DialogTitle/useDialogTitleStyles.styles.ts
For dialog's without actions the title isn't taking up the whole row. This is a regression from an earlier version.
After the change you can see the title is taking the full row as expected.
Here is also an dialog with action to show there isn't a regression
These images are taken from the story book opened by running yarn start @fluentui/react-dialog
- Fixes #28036
> Fix for dialog title not taking whole row for dialog without actions

- change/@fluentui-react-avatar-d8ee1b7d-ba8b-46a7-8aa6-bf5d84ebdbfe.json
- packages/react-components/react-avatar/src/components/Avatar/Avatar.test.tsx
- packages/react-components/react-avatar/src/components/Avatar/useAvatar.tsx
Avatar renders an image even if src is undefined `<Avatar image={{ src: undefined }} />`
Avatar no longer renders undefined image:
> fix(react-avatar): Do not render the image when src prop is undefined

- packages/react-components/react-infobutton/stories/Infobutton/InfoButtonDefault.stories.tsx
- packages/react-components/react-infobutton/stories/Infobutton/InfoButtonSize.stories.tsx
Stories didn't show the usage of InfoButton according to the guidance.
Stories now show examples following the guidance.
- Fixes #28073
> docs(react-infobutton): Update stories to show better guidance

- change/@fluentui-react-13f13391-8a93-4b11-b3c6-cfccea4fcdee.json
- packages/react/src/components/Layer/Layer.base.tsx
- packages/react/src/components/Layer/Layer.test.tsx
Focus outlines would not show up when opening a Modal, Dialog, Panel, etc. in a new Layer, since the layer contents would be under a new `FocusRectsProvider`.
Layer now checks whether the focus visible classname is present in its own context, then sets it (if applicable) on the new provider it instantiates.
- Fixes [15778](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15778)
> fix: Layer sets focus visible classname for its FocusRectsProvider

- change/@fluentui-react-cb9f45ee-a6ad-4ffc-afb6-62a53daac1fe.json
- packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx
- packages/react/src/components/ContextualMenu/ContextualMenu.test.tsx
Within sections, ContextualMenu included headers & dividers in the item index & total calculation. This causes incorrect `aria-posinset` and `aria-setsize` values.
ContextualMenu uses the same logic it does for calculating index & total outside of sections, for items within sections.
> fix: ContextualMenu indexing in sections

- apps/public-docsite-v9/.storybook/main.js
- packages/react-components/react-toast/etc/react-toast.api.md
- packages/react-components/react-toast/src/index.ts
- packages/react-components/react-toast/src/state/types.ts
- packages/react-components/react-toast/src/state/useToastController.ts
- packages/react-components/react-toast/src/state/vanilla/toaster.ts
- packages/react-components/react-toast/stories/Toast/CustomAnnounce.stories.tsx
- packages/react-components/react-toast/stories/Toast/CustomTimeout.stories.tsx
- packages/react-components/react-toast/stories/Toast/Default.stories.tsx
- packages/react-components/react-toast/stories/Toast/DefaultToastOptions.stories.tsx
- packages/react-components/react-toast/stories/Toast/DismissAll.stories.tsx
- packages/react-components/react-toast/stories/Toast/DismissToast.stories.tsx
- packages/react-components/react-toast/stories/Toast/DismissToastWithAction.stories.tsx
- packages/react-components/react-toast/stories/Toast/MultipleToasters.stories.tsx
- packages/react-components/react-toast/stories/Toast/Offset.stories.tsx
- packages/react-components/react-toast/stories/Toast/PauseOnHover.stories.tsx
- packages/react-components/react-toast/stories/Toast/PauseOnWindowBlur.stories.tsx
- packages/react-components/react-toast/stories/Toast/ToastDescription.md
- packages/react-components/react-toast/stories/Toast/ToastPositions.stories.tsx
- packages/react-components/react-toast/stories/Toast/ToasterLimit.stories.tsx
- packages/react-components/react-toast/stories/Toast/UpdateToast.stories.tsx
- packages/react-components/react-toast/stories/Toast/index.stories.tsx
Updates all the documentation examples for Toast so that they are human readable. Also adds docstring to public API
> docs: Add usable documentation

- change/@fluentui-fluent2-theme-92034fcd-61f0-459e-933b-c0457183fd4c.json
- packages/fluent2-theme/src/componentStyles/ChoiceGroupOption.styles.ts
Looks like we missed a case with choice group, and caused a nasty polish bug when an image or icon is passed to the choice group.
Before:
After:
> [FIX] Updates selection dot and label positioning for ChoiceGroupOption when an Image or Icon is present.

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams/getBorderFocusStyles.ts
Outline ignores forced colors by OS. See https://github.com/microsoft/fluentui/issues/27878 for more details.
The outline styles generated now use system `Highlight` color for outline.
- Fixes #27878
- Fixes #27877
- Fixes #27579
> fix: Outline color now respects OS force colors settings

- azure-pipelines.bundlesize.yml
[windows-2019 is not supported since 2021](https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/#windows) and suddenly started causing issues when installing jq via chocolatey. this started blocking all of our PR's
`merge` job migrated to our Ubuntu hosted pool which unifies our CI with rest of our jobs - also making this not fail randomly.
> ci: use ubuntu pool for size-auditor merge job

- change/@fluentui-react-dc639fb6-da75-4193-960d-f7e6a73c7d67.json
- packages/react-examples/src/react/DetailsList/DetailsList.Basic.Example.tsx
- packages/react/src/components/DetailsList/DetailsList.base.tsx
When a justified DetailsList is smaller in width than the available visible space the columns cannot be resized.
When a justified DetailsList is smaller in width than the available visible space the columns can be resized.
- Fixes [#26832](https://github.com/microsoft/fluentui/issues/26832)
> Re-enable DetailsList column resize

- change/@fluentui-react-datepicker-compat-39a831ff-e1f1-48df-af17-ffcd7fdf7883.json
- packages/react-components/react-datepicker-compat/src/components/DatePicker/DatePicker.cy.tsx
- packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx
When DatePicker is rendered, focus is moved to the input. This is done as a side effect of moving focus to the input when the popup is closed.
To avoid moving focus on first render, a check for first render has been added to the effect that moves focus to the input. Now the focus is moved to the input only when the popup is closed rather than on initial state as well.
- Fixes #28148
> fix(react-datepicker-compat): Do not move focus to the input on first render

- change/@fluentui-react-textarea-e76e5d43-0fae-497e-a156-61458b2edcb4.json
- packages/react-components/react-textarea/src/components/Textarea/useTextareaStyles.styles.ts
`<Textarea rows={6} />` hides the added rows.
`<Textarea rows={6} />` shows the added rows.
- Fixes #27842
> fix(react-textarea): Remove fixed height so rows prop works and add missing max-height

- change/@uifabric-charting-8aaeb60e-7c1d-4c6f-841e-49cadfe4b3a6.json
- packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap
- packages/charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap
- packages/charting/src/components/TreeChart/TreeChart.base.tsx
- packages/charting/src/components/TreeChart/__snapshots__/TreeChart.test.tsx.snap
> Disable focus on non-interactive elements

- packages/react-components/react-toast/etc/react-toast.api.md
- packages/react-components/react-toast/src/components/ToastContainer/ToastContainer.types.ts
- packages/react-components/react-toast/src/components/ToastContainer/useToastContainer.ts
- packages/react-components/react-toast/src/components/ToastTitle/ToastTitle.types.ts
- packages/react-components/react-toast/src/components/ToastTitle/useToastTitle.tsx
- packages/react-components/react-toast/src/components/ToastTitle/useToastTitleStyles.styles.ts
- packages/react-components/react-toast/src/contexts/toastContext.tsx
- packages/react-components/react-toast/src/index.ts
- packages/react-components/react-toast/src/state/types.ts
- packages/react-components/react-toast/src/state/vanilla/toaster.ts
- packages/react-components/react-toast/stories/Toast/CustomAnnounce.stories.tsx
- packages/react-components/react-toast/stories/Toast/CustomTimeout.stories.tsx
- packages/react-components/react-toast/stories/Toast/Default.stories.tsx
- packages/react-components/react-toast/stories/Toast/DefaultToastOptions.stories.tsx
- packages/react-components/react-toast/stories/Toast/DismissAll.stories.tsx
- packages/react-components/react-toast/stories/Toast/DismissToast.stories.tsx
- packages/react-components/react-toast/stories/Toast/DismissToastWithAction.stories.tsx
- packages/react-components/react-toast/stories/Toast/Intent.stories.tsx
- packages/react-components/react-toast/stories/Toast/MultipleToasters.stories.tsx
- packages/react-components/react-toast/stories/Toast/Offset.stories.tsx
- packages/react-components/react-toast/stories/Toast/PauseOnHover.stories.tsx
- packages/react-components/react-toast/stories/Toast/PauseOnWindowBlur.stories.tsx
- packages/react-components/react-toast/stories/Toast/ToastDescription.md
- packages/react-components/react-toast/stories/Toast/ToastLifecycle.stories.tsx
- packages/react-components/react-toast/stories/Toast/ToastPositions.stories.tsx
- packages/react-components/react-toast/stories/Toast/ToasterLimit.stories.tsx
- packages/react-components/react-toast/stories/Toast/UpdateToast.stories.tsx
- packages/react-components/react-toast/stories/Toast/index.stories.tsx
Hoists the `intent` prop used by the ToastTitle to the imperative API, so that default aria-live politeness can be set based on intent.
Also adds colors to the ToastTitle icon based on intent, unavailable tokens are labelled with FIXME
Addresses #26638
> feat: Hoist intent to imperative API

- packages/react-components/react-toast/src/components/ToastContainer/ToastContainer.test.tsx
- packages/react-components/react-toast/src/components/ToastContainer/ToastContainer.types.ts
- packages/react-components/react-toast/src/components/ToastContainer/useToastContainer.ts
- packages/react-components/react-toast/src/components/ToastContainer/useToastContainerContextValues.ts
- packages/react-components/react-toast/src/components/ToastTitle/ToastTitle.types.ts
- packages/react-components/react-toast/src/components/Toaster/useToaster.tsx
- packages/react-components/react-toast/src/contexts/toastContext.tsx
- packages/react-components/react-toast/src/index.ts
Fix of bug from #28224
The intent prop is not actually required because of `?` in the type. While this is true for creation, it should always be present when passed to context (even if it's undefined).
> fix: Toast intent should always be present in the context

- change/@fluentui-priority-overflow-8e128a48-5402-4886-b088-900334ce1883.json
- change/@fluentui-react-components-7b21b68d-a82b-4ee6-802c-cdbba6a8b25d.json
- change/@fluentui-react-overflow-96369afb-91ef-4417-88b6-bd79e7796730.json
- packages/react-components/priority-overflow/etc/priority-overflow.api.md
- packages/react-components/priority-overflow/src/consts.ts
- packages/react-components/priority-overflow/src/index.ts
- packages/react-components/priority-overflow/src/overflowManager.ts
- packages/react-components/priority-overflow/src/types.ts
- packages/react-components/react-breadcrumb/stories/Breadcrumb/BreadcrumbWithOverflow.stories.tsx
- packages/react-components/react-components/etc/react-components.api.md
- packages/react-components/react-components/src/index.ts
- packages/react-components/react-overflow/etc/react-overflow.api.md
- packages/react-components/react-overflow/src/Overflow.cy.tsx
- packages/react-components/react-overflow/src/components/Overflow.tsx
- packages/react-components/react-overflow/src/components/OverflowDivider/OverflowDivider.tsx
- packages/react-components/react-overflow/src/components/OverflowDivider/OverflowDivider.types.ts
- packages/react-components/react-overflow/src/constants.ts
- packages/react-components/react-overflow/src/index.ts
- packages/react-components/react-overflow/src/overflowContext.ts
- packages/react-components/react-overflow/src/types.ts
- packages/react-components/react-overflow/src/useOverflowContainer.test.ts
- packages/react-components/react-overflow/src/useOverflowContainer.ts
- packages/react-components/react-overflow/src/useOverflowDivider.ts
- packages/react-components/react-overflow/stories/Overflow/CustomDividers.stories.tsx
- packages/react-components/react-overflow/stories/Overflow/LargerDividers.stories.tsx
- packages/react-components/react-overflow/stories/Overflow/index.stories.tsx
If there are custom margins/paddings it, also, breaks overflow logic
> Overflow divider fix

- packages/react-components/react-alert/stories/Alert/AlertAction.stories.tsx
- packages/react-components/react-alert/stories/Alert/AlertAvatar.stories.tsx
small fix, just a missing `aria-label` on a dismiss icon button.
Also moved the accName of the other icon action up to the button node, which is mostly a preference, but it is slightly less verbose that way.
> fix: Alert example missing aria-label for icon

- change/@fluentui-react-tabster-83906204-6e9b-4809-a78f-8177a8ddca64.json
- packages/react-components/react-tabster/etc/react-tabster.api.md
- packages/react-components/react-tabster/package.json
- packages/react-components/react-tabster/src/hooks/useArrowNavigationGroup.ts
- yarn.lock
Upgrade tabster to latest
add grid-linear axis option
>  useArrowNavigationGroup grid-linear axis

- change/@fluentui-react-charting-1f77b865-250d-4cb3-bb5a-93fbdbf94a7c.json
- packages/react-charting/src/components/AreaChart/__snapshots__/AreaChart.test.tsx.snap
- packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx
- packages/react-charting/src/components/CommonComponents/CartesianChart.styles.ts
- packages/react-charting/src/components/CommonComponents/CartesianChart.types.ts
- packages/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap
- packages/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChart.test.tsx.snap
- packages/react-charting/src/components/HorizontalBarChartWithAxis/__snapshots__/HorizontalBarChartWithAxis.test.tsx.snap
- packages/react-charting/src/components/LineChart/LineChart.base.tsx
- packages/react-charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
- packages/react-charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap
- packages/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChart.test.tsx.snap
- packages/react-charting/src/utilities/utilities.ts
X-axis labels start overlapping when the window is zoomed in, or the window size is reduced
Scrollbar becomes visible when the viewport is smaller than the minimum width of the cartesian chart
- The minimum width is larger than it should be for some charts with string axis and 2:1 spacing
- Test cases to check if the cartesian charts are readable on smaller viewports:
- Shrink the window and reload the chart when width and height props are not provided
- Zoom in the window and reload the chart when width and height props are not provided
- Decrease the width and height props passed to the chart
> Fix overlapping axis labels on smaller viewports

- change/@fluentui-react-dialog-1d49c035-4bba-4e6d-9df2-5ed5fe7cad97.json
- packages/react-components/react-dialog/src/components/DialogActions/useDialogActionsStyles.styles.ts
- Fixes https://github.com/microsoft/fluentui/issues/27991
> react-dialog(bugfix): Ensures dialog actions stretches on breakpoints

- packages/react-components/react-dialog/stories/Dialog/DialogTriggerOutsideDialog.md
- packages/react-components/react-dialog/stories/Dialog/DialogTriggerOutsideDialog.stories.tsx
The examples shows focus restoration.
- Fixes #27962
> docs(react-dialog): update DialogTriggerOutsideDialog to include focus behavior

- change/@fluentui-react-card-e65cb71c-d483-449c-b1cb-b6b23d07f25b.json
- packages/react-components/react-card/src/components/Card/Card.cy.tsx
- packages/react-components/react-card/src/components/CardHeader/useCardHeader.ts
To enable narration of the correct element when a card is selectable, we would create a dynamic id for the CardHeader element and synchronise it with the internal checkbox aria-describedby attribute.
We now infer the value from the children element from the CardHeader `header` property (if any). In case no element is found, it'll fallback to the previous behaviour. This will allow to a more precise target for the element we use to enable narration.
> fix(react-card): infer a11y id from immediate header element

- change/@fluentui-react-dialog-46140418-eae5-48fe-beea-485764cb1dfa.json
- packages/react-components/react-dialog/src/components/DialogBody/useDialogBodyStyles.styles.ts
due to missing `grid-template-columns` the `DialogBody` doesn't properly expand it's whole size when the body is complex
1. adds `grid-tempalte-columns` to it's old value
- Fixes #
> bugfix: adds grid-template-columns to DialogBody styles to ensure grid template layout

- packages/react-components/react-drawer/stories/Drawer/DrawerCustomSize.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerInline.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerOverlayNoModal.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerPosition.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerPreventClose.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerResizable.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerResponsive.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerSeparator.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerSize.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerWithNavigation.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/index.stories.tsx
- Add missing example of Drawer overlay without backdrop (`modalType="non-modal"`)
- Overall improvements of stories to make them have same layout
> docs(react-drawer): improve drawer stories examples

- change/@fluentui-react-drawer-abefd0d8-1c44-421b-96e5-723c20a91d46.json
- packages/react-components/react-drawer/etc/react-drawer.api.md
- packages/react-components/react-drawer/src/components/Drawer/Drawer.types.ts
- packages/react-components/react-drawer/src/components/DrawerInline/DrawerInline.types.ts
- packages/react-components/react-drawer/src/components/DrawerOverlay/DrawerOverlay.types.ts
- packages/react-components/react-drawer/src/components/DrawerOverlay/useDrawerOverlay.ts
- packages/react-components/react-drawer/src/components/DrawerOverlay/useDrawerOverlayStyles.styles.ts
- packages/react-components/react-drawer/src/util/DrawerBase.types.ts
- packages/react-components/react-drawer/src/util/getDefaultDrawerProps.ts
- Fixes an issue with TS circular references by simplifying the usage of Drawer base types
- Rename and improve documentation of some types
> docs(react-drawer): improve type descriptions and fix TS circular references

- packages/react-components/react-drawer/stories/Drawer/DrawerAlwaysOpen.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerCustomSize.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerDescription.md
- packages/react-components/react-drawer/stories/Drawer/DrawerInline.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerOverlay.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerOverlayNoModal.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerPosition.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerPreventClose.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerResizable.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerResponsive.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerSeparator.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerSize.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerWithNavigation.stories.tsx
- packages/react-components/react-drawer/stories/Drawer/DrawerWithScroll.stories.tsx
Adds descriptions to every single story example.
> docs(react-drawer): add missing documentation for Drawer stories

- packages/react-components/react-dialog/stories/Dialog/DialogBestPractices.md
Adds to `Dialog` best practices the usage of `aria-label` or `aria-labelledby` if no `DialogTitle` is provided
- Fixes #27900
> [Documentation]: Add information about `aria-label` on the surface if there is no DialogTitle in the best practices.

- .codesandbox/ci.json
- .devops/templates/tools.yml
- .github/workflows/check-packages.yml
- .github/workflows/docsite-publish-chromatic.yml
- .github/workflows/docsite-publish-ghpages.yml
- apps/ts-minbar-test-react/src/index.ts
- azure-pipelines.bundlesize.yml
- package.json
- packages/react-components/global-context/src/types.ts
- packages/react/etc/react.api.md
- packages/react/src/components/Tooltip/Tooltip.types.ts
- packages/react/src/components/Tooltip/TooltipHost.types.ts
- yarn.lock
- the `web-components-v3` branch is outdated and failing certain checks in CI (particularly the bundle size checks and the ts-minbar check) which blocks PRs.
- cherry-picks changes made from: 
1) https://github.com/microsoft/fluentui/pull/27467
2) #28208
3) https://github.com/microsoft/fluentui/pull/27711
> chore(web-components-v3): cherry-pick some changes to fix CI check

- packages/react-components/react-table/stories/Table/CellActions.stories.tsx
- packages/react-components/react-table/stories/Table/PrimaryCell.stories.tsx
- packages/react-components/react-table/stories/Table/ResizableColumnsControlled.stories.tsx
- packages/react-components/react-table/stories/Table/ResizableColumnsUncontrolled.stories.tsx
- packages/react-components/react-table/stories/Table/SelectionWithCellActions.stories.tsx
Simple examples-only fix, adds `aria-label`s to buttons and label/input associations that were missing accNames in the story code.
> fix: add accNames to buttons and inputs in v9 Table example code

- change/@fluentui-react-datepicker-compat-6564eb05-a29c-443b-bede-9013941919fc.json
- change/@fluentui-react-e6a59ed9-7ac7-4d6d-a675-8815b201c9f5.json
- packages/react-components/react-datepicker-compat/src/components/Calendar/Calendar.tsx
- packages/react/src/components/Calendar/Calendar.base.tsx
When Calendar or DatePicker is used in a month-only configuration (i.e. no date picking at all, only month and year) we still had the screen reader-only selected date string include the weekday and date information.
The selected date string only includes the month and year for month-only Calendars/DatePickers in both v8 & v9 compat.
- Fixes [16425](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/16425)
> fix: Calendar uses month-only selection string when only month picker is used

- change/@fluentui-react-6c10b703-0791-4201-9290-ebec3fd9c545.json
- packages/react/src/components/Rating/Rating.base.tsx
- packages/react/src/components/Rating/Rating.test.tsx
- packages/react/src/components/Rating/__snapshots__/Rating.test.tsx.snap
Rating stars/radios would select when they received focus, rather than in response to keyboard or mouse events. This created a bug with touchscreen screen readers where it was impossible to select a rating and then swipe past the control, since swiping through the control would continue selecting stars.
Left/right/up/down/home/end/page up/page down all update the rating, as well as clicking on a specific star. This keeps the same behavior from the perspective of pointer and keyboard users, but touchscreen screen reader users can use the control in the same way as native radios.
- Fixes [16318](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/16318)
- Fixes #27818
> fix: v8 Rating should update in response to keyboard events, not focus events

- change/@fluentui-react-3572eea0-ee5a-42be-a74b-ecdc134fa6f1.json
- packages/react/src/components/ComboBox/ComboBox.tsx
- packages/react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap
- packages/react/src/components/Dropdown/Dropdown.base.tsx
- packages/react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
This PR is purely a semantic change, no behavior or style changes.
The visual line separating groups had the separator role, which isn't valid within a listbox
The div gets a `role=presentation`.
- Fixes #26949
> fix: Dropdown and Combobox do not use separator role

- change/@fluentui-utilities-e9131211-ff24-4edd-96f2-f3a4a4a68fc7.json
- packages/utilities/src/useFocusRects.ts
Passing a non-html element to the `as` prop of `ThemeProvider` made the app using it crash because `useFocusRects` would try to call the non-existent `addEventListener` function from the `current` value of the `ref` to that non-html element.
Passing a non-html element to the `as` prop of `ThemeProvider` no longer crashes the app using it. `useFocusRects` now checks for the existence of `addEventListener` in the `current` value of the `ref` and, if this doesn't exist, attaches the listeners to the window instead.
- Fixes #28016.
> fix: Checking for the existence of addEventListener on element coming from context in useFocusRects

- change/@fluentui-react-tree-816beea2-f6e6-48f9-8dbc-d3bb8c34bd02.json
- packages/react-components/react-tree/etc/react-tree.api.md
- packages/react-components/react-tree/src/components/TreeItemLayout/TreeItemLayout.types.ts
- packages/react-components/react-tree/src/components/TreeItemLayout/__snapshots__/TreeItemLayout.test.tsx.snap
- packages/react-components/react-tree/src/components/TreeItemLayout/renderTreeItemLayout.tsx
- packages/react-components/react-tree/src/components/TreeItemLayout/useTreeItemLayout.tsx
- packages/react-components/react-tree/src/components/TreeItemLayout/useTreeItemLayoutStyles.styles.ts
- packages/react-components/react-tree/src/components/TreeItemPersonaLayout/TreeItemPersonaLayout.types.ts
- packages/react-components/react-tree/src/components/TreeItemPersonaLayout/__snapshots__/TreeItemPersonaLayout.test.tsx.snap
- packages/react-components/react-tree/src/components/TreeItemPersonaLayout/renderTreeItemPersonaLayout.tsx
- packages/react-components/react-tree/src/components/TreeItemPersonaLayout/useTreeItemPersonaLayout.tsx
- packages/react-components/react-tree/src/components/TreeItemPersonaLayout/useTreeItemPersonaLayoutStyles.styles.ts
- packages/react-components/react-tree/stories/A_Tree/TreeDefault.stories.tsx
- packages/react-components/react-tree/stories/C_Layouts/TreeItemLayoutIconBefore.stories.tsx
This PR introduces following changes:
- Add content slot for children in tree item layout
- Fixes issue with alignment of tree items by removing column gap and add padding before/after icons and in the content slot
- Rename main slot in the TreeItemPersonaLayout to content to align with TreeItemLayout component
- Adds missing layout wrapper in the icon before story example
- Adds a leaf item in the default tree view
- Fixes #
> [Bug]: Tree - TreeItem leaf and branch are not aligned

- change/@fluentui-react-utilities-f1dc6a83-6fd4-4d86-a5ef-b68f5420ea11.json
- packages/react-components/react-utilities/etc/react-utilities.api.md
- packages/react-components/react-utilities/src/compose/getSlotsNext.ts
1. adds `internal` tag to jsdoc comments on `getSlotsNext`
2. add comments specifying that this method should not be used externally (just to be clear)
- Fixes #
> chore: adds internal tag on jsdocs for getSlotsNext

- change/@fluentui-react-b3b9e7bb-d031-4766-b6f1-595b8c3892b9.json
- packages/react/package.json
CSS files were not included in the list of exports of the `@fluentui/react` package.
CSS files are now included in the list of exports of the `@fluentui/react` package.
- Fixes #27356
> chore: Exporting CSS files in @fluentui/react package

- change/@fluentui-react-utilities-881a428e-b3dc-4761-8ecf-c874364e95c5.json
- packages/react-components/react-table/src/testing/mockSyntheticEvent.ts
- packages/react-components/react-utilities/src/selection/useSelection.ts
- packages/react-components/react-utilities/src/testing/mockSyntheticEvent.ts
`useSelection` event handling mechanisn stops selection state change whenever an even was prevented.
This might be problematic as we want to use spacebar keydown events for selection, and spacebar events should be prevented as they would trigger scrolling by default.
1. `useSelection` event handling mechanism doesn't stop selection state change anmore.
- Fixes #
> bugfix: removes default prevention verification on selection

- scripts/generators/create-package/index.ts
- scripts/monorepo/src/index.d.ts
- scripts/monorepo/src/tree.js
`yarn create-component` doesn't work after migration to nx 15.9 which introduced `project.json` per package instead global `workspace.json`. This change needed us to monkey patch how nx devkit is used outside nx environment, but we forgot to flush the virtual FS tree to real FS.
`yarn create-component` does work
- Follows #28032
> fix(scripts/generators): make sure to flush nx Tree outside nx context in order to write changes on physical file system

- packages/react-components/react-tags/bundle-size/InteractionTag.fixture.js
- packages/react-components/react-tags/bundle-size/TagGroup.fixture.js
Add fixture for InteractionTag and TagGroup
> react-tags: Add bundle size fixture for InteractionTag and TagGroup

- apps/vr-tests-react-components/src/stories/Toast/Toast.stories.tsx
- packages/react-components/react-toast/src/components/ToastTitle/useToastTitleStyles.styles.ts
Uses colorNeutralForegroundInverted2 for ToastTitle color.
Also adds Dark, HC, RTL tests for Toast
Before
After
> fix: ToastTitle inverted should be visible in teams high contrast

- packages/react-components/react-search/src/components/SearchBox/useSearchBoxStyles.styles.ts
This PR fixes the zoom reflow (when the screen gets squished smaller than the width of the component, the component shrinks) issue identified in #28324.
> fix(react-search): Fix zoom reflow

- change/@fluentui-react-menu-9df216cb-9a9b-4732-b0ef-3618ed48c759.json
- packages/react-components/react-menu/src/components/MenuItem/useMenuItemStyles.styles.ts
Menu item disabled was hoverable
Menu item disabled is not hoverable and has an updated cursor style.
- Fixes #28405
> MenuItem: updated styles for disabled state

- change/@fluentui-react-components-da6942fb-51ea-4e2c-8151-edf05ce372b7.json
- change/@fluentui-react-table-0f76a6d8-c171-4ce2-b9d3-2b2e74b4fa1e.json
- change/@fluentui-react-tabster-77c7124a-1b60-4c25-997b-e503878c34ee.json
- packages/react-components/react-components/etc/react-components.api.md
- packages/react-components/react-components/src/index.ts
- packages/react-components/react-table/etc/react-table.api.md
- packages/react-components/react-table/src/components/DataGrid/DataGrid.cy.tsx
- packages/react-components/react-table/src/components/DataGrid/DataGrid.types.ts
- packages/react-components/react-table/src/components/DataGrid/useDataGrid.ts
- packages/react-components/react-table/src/components/DataGrid/useDataGridContextValues.ts
- packages/react-components/react-table/src/components/DataGridCell/useDataGridCell.ts
- packages/react-components/react-table/src/components/DataGridRow/useDataGridRow.tsx
- packages/react-components/react-table/src/contexts/dataGridContext.ts
- packages/react-components/react-table/src/hooks/index.ts
- packages/react-components/react-table/src/hooks/useTableCompositeNavigation.ts
- packages/react-components/react-table/src/index.ts
- packages/react-components/react-table/src/testing/mockDataGridContext.ts
- packages/react-components/react-table/stories/DataGrid/CompositeNavigation.stories.tsx
- packages/react-components/react-table/stories/DataGrid/Default.stories.tsx
- packages/react-components/react-table/stories/DataGrid/index.stories.tsx
- packages/react-components/react-table/stories/Table/CompositeNavigation.stories.tsx
- packages/react-components/react-table/stories/Table/index.stories.tsx
- packages/react-components/react-tabster/etc/react-tabster.api.md
- packages/react-components/react-tabster/src/hooks/index.ts
- packages/react-components/react-tabster/src/hooks/useMergeTabsterAttributes.ts
- packages/react-components/react-tabster/src/index.ts
Implents a new hook `useTableCompositeNavigation` that provides the same kind of hybrid row/cell navigation provided by the [v0 table](https://fluentsite.z22.web.core.windows.net/0.66.2/components/table/definition?showCode=false&showRtl=false&showTransparent=false&showVariables=false#usage-navigable).
This hook is reused in the DataGrid with the new `composite` focusMode option.
> feat: Implement composite navigation for Table and DataGrid

- change/@fluentui-react-toast-32213210-a713-431e-96a7-befff4c5f4bb.json
- packages/react-components/react-toast/src/components/Toast/Toast.cy.tsx
- packages/react-components/react-toast/src/components/Toaster/useToaster.tsx
- packages/react-components/react-toast/stories/Toast/DismissToastWithAction.stories.tsx
- packages/react-components/react-toast/stories/Toast/ToastDescription.md
Due to facebook/react#25194, onBlur was never called when the toast was manually dismissed by focusing a trigger. Adds the `focusin` and `focusout` listeners to the HTMLElement to workaround this bug. Also adds a test to make sure that other toasts are resumed after dismiss.
Also removes the unstable warning for the component docs
> fix: Toaster should play toasts on action dismiss

- tools/generators/dependency-mismatch/index.spec.ts
as part of referenced bug investigation:
- add 1 more test case to cover v9 packages when v0,v8 deps need an update
- update test suite to use non deprecated devkit apis + `appTree` -> `tree` normalization
- Follows https://github.com/microsoft/fluentui/issues/28370
> test(tools): add more test for v9 packages with v8,v0 deps

- apps/public-docsite/src/pages/Overviews/ControlsPage/ControlsPage.tsx
Website is missing the v9 banner when looking at the controls page and in the react section.
Website now has the v9 banner in all web platform pages.
> docs(public-docsite): Add banner to controls page

- tools/generators/normalize-package-dependencies/README.md
- tools/generators/normalize-package-dependencies/index.spec.ts
- tools/generators/normalize-package-dependencies/index.ts
- tools/generators/normalize-package-dependencies/schema.json
- tools/generators/normalize-package-dependencies/schema.ts
- based on feedback the generator was simplified to run only on set ruleset without configuration options (filters)
- updates all deps within `applications`/ devDeps only within `libraries` (https://github.com/microsoft/fluentui/pull/28382#discussion_r1251704490)
- packages that use prerelase version will not use `*` but instead `>=9.0.0-alpha`, this is only option to make `yarn` pass as expected
- Follows https://github.com/microsoft/fluentui/pull/28382
- Partially implements https://github.com/microsoft/fluentui/issues/28461
> feat(tools): remove configuration filters and apply workspace dependency rules automatically withn normalize-package-dependencies generator

- change/@fluentui-react-data-grid-react-window-ea106fe9-63cf-4abb-9d28-d20283720fb5.json
- packages/react-components/react-data-grid-react-window/README.md
- packages/react-components/react-data-grid-react-window/etc/react-data-grid-react-window.api.md
- packages/react-components/react-data-grid-react-window/src/components/DataGrid/DataGrid.tsx
- packages/react-components/react-data-grid-react-window/src/components/DataGridBody/DataGridBody.tsx
- packages/react-components/react-data-grid-react-window/src/components/DataGridBody/DataGridBody.types.ts
- packages/react-components/react-data-grid-react-window/src/components/DataGridRow/DataGridRow.tsx
- packages/react-components/react-data-grid-react-window/src/index.ts
- packages/react-components/react-table/stories/DataGrid/Virtualization.stories.tsx
Deprecates this package in favour of
`@fluentui-contrib/react-data-grid-react-window` and updates documtation and README
> feat: Deprecate @fluentui/react-data-grid-react-window

- tools/generators/normalize-package-dependencies/index.spec.ts
- tools/generators/normalize-package-dependencies/index.ts
if version was set to `>=9.0.0-alpha` already and package migrated to standard versioning policy, we dont update deps nor trigger error in `verify` mode.
as we will be migrating away from pre-releases we need to update our dependency versions as well. This change to the generator adds that feature.
- Follows https://github.com/microsoft/fluentui/pull/28430
- Implements partially https://github.com/microsoft/fluentui/issues/28461
> feat(tools): update/verify packages that changed versioning approach from pre-release to standard to accommodate proper dependency definitions

- change/@fluentui-react-virtualizer-eeedf712-20cc-43fd-afc3-c4bc3ce8f9d7.json
- packages/react-components/react-virtualizer/src/components/Virtualizer/useVirtualizer.ts
- packages/react-components/react-virtualizer/src/components/Virtualizer/useVirtualizerStyles.styles.ts
- packages/react-components/react-virtualizer/src/components/VirtualizerScrollView/useVirtualizerScrollViewStyles.styles.ts
- packages/react-components/react-virtualizer/src/components/VirtualizerScrollViewDynamic/useVirtualizerScrollViewDynamicStyles.styles.ts
- packages/react-components/react-virtualizer/src/hooks/useDynamicVirtualizerMeasure.ts
- packages/react-components/react-virtualizer/stories/Virtualizer/Default.stories.tsx
- packages/react-components/react-virtualizer/stories/Virtualizer/DefaultUnbounded.stories.tsx
- packages/react-components/react-virtualizer/stories/Virtualizer/Dynamic.stories.tsx
- packages/react-components/react-virtualizer/stories/Virtualizer/Horizontal.stories.tsx
- packages/react-components/react-virtualizer/stories/Virtualizer/MultiUnbounded.stories.tsx
- packages/react-components/react-virtualizer/stories/Virtualizer/RTL.stories.tsx
- packages/react-components/react-virtualizer/stories/Virtualizer/Reversed.stories.tsx
- packages/react-components/react-virtualizer/stories/Virtualizer/ReversedHorizontal.stories.tsx
- packages/react-components/react-virtualizer/stories/VirtualizerScrollView/SnapToAlignment.stories.tsx
- packages/react-components/react-virtualizer/stories/VirtualizerScrollView/index.stories.ts
- packages/react-components/react-virtualizer/stories/VirtualizerScrollViewDynamic/Default.stories.tsx
Our start buffer had it's margin set to the wrong side, this caused it to only fire once the 'virtualized white space' had entered the screen.
On snap aligned items, this meant the user could not scroll 'backward' as the items had yet to render.
Minimum reproduceable demo of issue:
https://codesandbox.io/s/hardcore-meninsky-wkshd6?file=/example.tsx
Snap aligned items can now progress into virtualized space, a demo has been provided.
N/A
> Fix Virtualizers 'start buffer' overflow

- change/@fluentui-fluent2-theme-ef95a929-6b64-477a-a5b8-9a5b59e53221.json
- packages/fluent2-theme/src/componentStyles/Button.styles.ts
- packages/fluent2-theme/src/fluent2WebDarkTheme.ts
Fluent2 Dark Theme for V8 did not respect 'isInverted' flag and used lightmode high-contrast colors for background in some scenarios (message bar warnings etc.)
Primary button color was a slightly lighter shade in dark theme.
IsInverted: true set on Fluent 2 Dark Theme for v8, all background colors should now be appropriate lower-contrast colors.
Primary button color is the same on V8 Fluent 2 dark and light themes.
- Fixes #28455 
- Fixes #28454
> Fix contrast issues in V8 Fluent2 Dark Theme

- packages/react-components/react-search-preview/README.md
- packages/react-components/react-search-preview/stories/SearchBox/SearchBoxAppearance.stories.tsx
- packages/react-components/react-search-preview/stories/SearchBox/SearchBoxBestPractices.md
- packages/react-components/react-search-preview/stories/SearchBox/SearchBoxContentBeforeAfter.stories.tsx
- packages/react-components/react-search-preview/stories/SearchBox/SearchBoxDescription.md
- packages/react-components/react-search-preview/stories/SearchBox/SearchBoxSize.stories.tsx
Adds missing documentation (README, description, best practices) to SearchBox #26648.
> docs(react-search): Add README, description, best practices

- change/@fluentui-react-portal-e75181ac-7bf9-4b6e-a79e-2f1c3f54d5e7.json
- packages/react-components/react-portal/README.md
> Update react-components/react-portal README.md

- change/@fluentui-react-virtualizer-31fd546c-91d0-46c0-854a-9eb30822acb2.json
- packages/react-components/react-virtualizer/etc/react-virtualizer.api.md
- packages/react-components/react-virtualizer/src/components/Virtualizer/Virtualizer.types.ts
- packages/react-components/react-virtualizer/src/components/Virtualizer/useVirtualizer.ts
- packages/react-components/react-virtualizer/src/components/VirtualizerScrollView/useVirtualizerScrollView.ts
- packages/react-components/react-virtualizer/src/components/VirtualizerScrollViewDynamic/useVirtualizerScrollViewDynamic.ts
- packages/react-components/react-virtualizer/src/utilities/ImperativeScrolling/imperativeScrolling.types.ts
Users would need to use context to inject or read the virtualizers index & length, however there are many cases where you simply want access to these variables without a full context stack rewriting.
Users can now access this data from imperative ref _as well_.
Still recommend context use for interjecting/normalizing index change, or more complicated functionality pre-render.
> Expose virtualize index/length for casual use

- change/@fluentui-react-card-d34069cc-ff5d-43bc-b4c5-8e199f94b5ed.json
- packages/react-components/react-card/src/components/CardHeader/useCardHeader.ts
This PR fixes an issue with card trying to resolve the header prop before calling `resolveShorthand`. For more information, please refer to the [original bug](https://github.com/microsoft/fluentui/issues/28448#issuecomment-1624167331).
- Fixes #28448
> fix(react-card): use resolved slot instead of raw prop object

- apps/public-docsite-v9/.storybook/main.js
- apps/public-docsite-v9/package.json
- change/@fluentui-react-search-preview-1b45c3f6-0791-45a6-9c07-9e02ad62d5d7.json
- packages/react-components/react-search-preview/package.json
- packages/web-components/docs/api-report.md
- scripts/storybook/src/utils.js
This PR migrates SearchBox to preview, as part of #26648.
> Migrate react-search to preview

- change/@fluentui-react-c502b5d8-9ae6-45d0-bf60-6e087207129c.json
- packages/react/src/components/Pivot/Pivot.base.tsx
- packages/react/src/components/Pivot/__snapshots__/Pivot.test.tsx.snap
We were exposing the overflow button as a menu button rather than a tab. The pros and cons of each approach are pretty even -- in functionality it's a menubutton, but it's more expected to encounter a tab within a tablist. The reason for this change is that a menubutton within a tablist triggers an automated error, and a tab does not, and also likely does not have meaningful known user-facing drawbacks. This will also match the semantics used in v9's TabList.
The overflow button uses the tab role.
- Fixes [16426](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/16426)
> fix: Pivot overflow role uses tab
