change/@fluentui-react-5a84fff9-977e-458d-94a0-c8e5bd1c8930.json
packages/react/src/components/Button/BaseButton.tsx
packages/react/src/components/Button/Button.test.tsx
packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.tsx
packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/__snapshots__/ContextualMenuSplitButton.deprecated.test.tsx.snap
packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/__snapshots__/ContextualMenuSplitButton.test.tsx.snap

With touch, it was only possible to open the menu, and not possible to check/uncheck the primary button. Generally we require the primary action to also be in the menu, but checkable items generally cannot be checked/unchecked in the menu (and are less common controls in general).
The original impetus for the single-touch-target splitbuttons was also geared more towards icon split buttons like those in the ribbon, where the entire touch target is very small. Icon split buttons should not be toggle splits anyway, so in theory there should be less need for toggle splits to have only one touch target.
Now toggleable splitbuttons and checkable split menuitems have two separate touch targets, and can be checked/unchecked with touch.
This PR also exposes the contextual menu item's split menu …

fix: v8 SplitButton and split MenuItem have two touch targets when checkable

---

change/@fluentui-react-charting-23ac9e54-88e2-456f-abde-468868ed7d1a.json
packages/react-charting/src/components/HorizontalBarChartWithAxis/HorizontalBarChartWithAxis.base.tsx

Data for the chart:
{
y: 'String j',
x: 81000,
color: DefaultPalette.blue,
},
{
y: 'String k',
x: 19000,
color: DefaultPalette.blue,
},
- Fixes #

X bars showing incorrect data when the values are large- bug 8380

---

change/@fluentui-fluent2-theme-0e6007c6-6d99-4aaf-afc1-a22793e47026.json
packages/fluent2-theme/src/componentStyles/Spinner.styles.ts

Only two sizes (32/34px) of spinners no matter the settings:
Spinners have a v9 equivalent for the v8 available sizes.
V9 has more options for sizing, we have imitated the sizing's for the v8 size settings available.
- Fixes #26785

V8 Fluent2 Theme: Spinner sizes

---

change/@fluentui-react-f5d92ca7-54dc-4233-b320-97e9faf3f3b1.json
packages/react/src/components/KeytipLayer/KeytipLayer.base.tsx

Currently, keytips have the ability to render only for visible instances of target elements, but if there are multiple of the same registration (e.g. keytipData), the first one is always used. This can result in the keytip not being positioned correctly for the instance that's visible. Note, this is related to responsive scaling where the same control can be rendered with the same keytip tree multiple times where only one instance is visible at a time
With this change, the fetching of the keytipData will now return the instance that's associated with the corresponding visible element instance. This makes the keytipData that's used align with how keytips already choose where to be visible (e.g. which element is their target). This new code will only run if there are multiple keytips with …

Keytips: Align keytipData with visible instance for dupes

---

azure-pipelines.bundlesize.yml

lighrail doesnt work with affected builds and needs everything build on every PR.
as we enabled since some time ago, every PR that wont build all projects or has some mixup state from previous PR merged into master get following confusing metrics:
see PR title
- Follows #28231

ci(bundlesize): opt out using --since as lightrail doesnt support this behaviour and needs everything build on every PR

---

change/@fluentui-web-components-ce49d0a8-e88e-4b52-81ed-24d9badc8cab.json
packages/web-components/src/toggle-button/toggle-button.ts

The component could error out as setAttribute could be called incorrectly.
No error as we check that the $fastController is called before we invoke setAttribute.
n/a

fix(web-components): add check in toggle button to ensure setAttribute is not called before connectedCallback

---

change/@fluentui-react-file-type-icons-bf50e101-ae17-4733-ac7b-1d0fec971473.json
packages/react-file-type-icons/src/FileIconType.ts
packages/react-file-type-icons/src/getFileTypeIconProps.ts

This PR is to unblock Loop to be able to use the loopworkspace file type icons, by adding this type to the `FileIconType` enum. Fixes #28554

Add loopworkspace extension to FileIconType

---

change/@fluentui-react-menu-f1d69af6-f08c-4798-9e3e-f6b558ea2553.json
packages/react-components/react-menu/etc/react-menu.api.md
packages/react-components/react-menu/src/index.ts
packages/react-components/react-menu/src/utils/useOnMenuEnter.ts

This PR exports the `MENU_ENTER_EVENT` and the `dispatchMenuEnterEvent` utilities from `@fluentui/react-menu`. These utilities are needed in order to be able to properly use `useOnMenuMouseEnter` in most circumstances.

chore: Exporting MENU_ENTER_EVENT and dispatchMenuEnterEvent utilities from @fluentui/react-menu

---

apps/perf-test-react-components/package.json
apps/vr-tests-react-components/package.json
scripts/beachball/shared.config.ts

every release that bumps inner workspace dependency used within applications will put master in invalid state
- Fixed invalid deps
- fixed order of generators invocations on beachball release so this wont happen again
- Fixes #

fix(scripts-beachball): dont override */9.0-alpha versions specified within apps during release

---

change/@fluentui-react-button-2730412f-d6ac-4017-b757-ced56c7f214f.json
packages/react-components/react-button/src/components/Button/useButtonStyles.styles.ts
packages/react-components/react-button/src/components/CompoundButton/useCompoundButtonStyles.styles.ts
packages/react-components/react-button/src/components/MenuButton/useMenuButtonStyles.styles.ts
packages/react-components/react-button/src/components/ToggleButton/useToggleButtonStyles.styles.ts

This PR corrects the contrast of the icon on subtle buttons and text on transparent buttons in high contrast mode.
Before:
After:
Also corrects the color of the secondary text for CompoundButton.
Before:
After:
Removes the high contrast MenuButton bug that causes icons to change colors when the menu is open.
Before:
After:
Removes the high contrast ToggleButton bug that caused the Subtle and Transparent variants to have low contrast icons.
Before:
After:

fix: High contrast mode hover style icon fixes in react-button components

---

change/@fluentui-react-toolbar-3898461e-a785-43d9-9b44-149bb5a84e79.json
packages/react-components/react-toolbar/src/components/ToolbarGroup/useToolbarGroupStyles.styles.ts

An empty CSS file was generated due to the empty makeStyles call
No empty CSS file generated
- Fixes #28565

Fix empty CSS creation

---

change/@fluentui-react-dialog-b94a462e-5c88-4181-a8b8-3f1aa9068b92.json
packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurface.ts

Event listener that ensured `backdrop` functionality on click event was being added as a `defaultProp`, which could be overridden by external user by passing `backdrop={{onClick}}`, breaking backdrop behaviour
1. Makes `handleBackdropClick` an override method instead of a `defaultProp`.
- Fixes #

bugfix: moves handleBackdropClick from defaultProps to an override

---

change/@fluentui-react-conformance-f6f452eb-ff7e-4715-918a-4a62a51a7e40.json
packages/react-conformance/package.json

During migration to v9 setup (including swc use for transpilation ) we forgot to replace tslib with swc helpers
Follows https://github.com/microsoft/fluentui/pull/28215

fix(react-conformance): add @swc/helpers to deps instead of tslib as we use swc for transpilation

---

change/@fluentui-react-table-9bafa4eb-c107-4426-b422-56d0113f018b.json
packages/react-components/react-table/src/hooks/useTableSelection.test.ts
packages/react-components/react-table/src/hooks/useTableSelection.ts
packages/react-components/react-table/stories/Table/Default.stories.tsx

We took the decision to decouple the selection state from the data. This means that the selection state does not always stay in sync with the data, but the resulting output should be correct.
In this case `allSeletedRows` and `someSelectedRows` were calculated based on the size of the selected rows which was wrong, because there can be outdated values in there. Updates the `useTableSelection` hook to make sure that those states reflect the what is in the data. This will cause extra computation (which is memoized) but there is no other way to maintain consistency.
It might be possible to update `useSelection` accept the set of selectable items, but the extra computation will still need to be there.
Fixes #28456

feat: allSelectedRows and someSelectedRows should be more reliable

---

packages/react-components/react-tooltip/stories/Tooltip/TooltipIcon.stories.tsx
packages/react-components/react-tooltip/stories/Tooltip/index.stories.tsx

This PR adds a story to tooltip that shows how to build an info icon with a tooltip following an InfoIcon pattern.
- Fixes #28602

docs(react-tooltip): Add info icon + tooltip story to Tooltip stories

---

tools/generators/prepare-initial-release/index.spec.ts
tools/generators/prepare-initial-release/index.ts

re-generate `react-components.api.md` after `-preview` package is propagated to stable phase.
- Partially fixes #28471

feat(tools): re-generate react-components.api.md when preparing 1st stable release

---

change/@fluentui-react-breadcrumb-preview-947a179a-446f-4171-b318-b4d9b224559c.json
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbButton/useBreadcrumbButtonStyles.styles.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/useBreadcrumbItemStyles.styles.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbLink/useBreadcrumbLinkStyles.styles.ts
packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbItemWithOverflow.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbLinkWithOverflow.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbWithOverflow.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/index.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/BreadcrumbDivider/BreadcrumbDividerDefault.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/BreadcrumbLink/BreadcrumbLinkDefault.stories.tsx

- removed custom divider because it's not recommended to use these kinds of dividers: ![image](https://github.com/microsoft/fluentui/assets/11574680/97a07741-51c7-482e-be3d-7ef252a94cdb)
- removed paddings from BreadcrumbLink and BreadcrumbButton: 
- Divider:
- BreadcumbButton (looks almost the same, but there are no paddings)

Breadcrumb UI adjustments

---

change/@fluentui-react-75983ba2-b5ea-4e4e-9578-6fc0293ce309.json
packages/react/src/components/DatePicker/DatePicker.base.tsx

Datepicker respected `inputProps.description`, but not `inputProps.onRenderDescription` on its own. Now both props individually work to render the description
- Fixes #27021

fix: Datepicker renders input description if inputProps.onRenderDescription is set

---

change/@fluentui-react-f1224d11-1ccf-4845-805f-fe84e7b89377.json
packages/react/src/components/ComboBox/ComboBox.tsx
packages/react/src/components/pickers/BasePicker.tsx

This is primarily geared towards fixing the issue where Android resizes the window when the keyboard opens (vs. iOS, which overlays the keyboard over the window). This means that editable comboboxes and pickers always dismiss the list of options immediately after opening on focus, since the keyboard simultaneously pops up.
Android users at best must open a combobox or picker popup twice to view options. At worst, they can never use the popup -- this happens in the case of Talkback users, since Talkback shows/hides the keychain toolbar above the keyboard every time the popup opens and closes. Also for any picker/combobox implementations that do not provide a way to re-open the listbox popup while focus remains in the input.
If the Combobox or Picker's Callout detects a scroll or resize …

fix: do not dismiss editable comboboxes on scroll or resize immediately after opening

---

change/@fluentui-react-aea800d3-31d8-4c2c-a34f-9b91f4d2463d.json
packages/react/src/components/DetailsList/DetailsColumn.base.tsx
packages/react/src/components/DetailsList/DetailsColumn.test.tsx
packages/react/src/components/DetailsList/__snapshots__/DetailsColumn.test.tsx.snap
packages/react/src/components/DetailsList/__snapshots__/DetailsHeader.test.tsx.snap
packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
packages/react/src/components/DetailsList/__snapshots__/DetailsListV2.test.tsx.snap
packages/react/src/components/DetailsList/__snapshots__/DetailsRow.test.tsx.snap

We provided an out-of-the-box method to create a DetailsColumn tooltip, but that tooltip wasn't keyboard accessible or associated via `aria-describedby` (with the exception of icon columns using `column.ariaLabel`).
Now, when using `onRenderColumnHeaderTooltip`, the tooltip shows/hides on column header focus and blur, and is associated via `aria-describedby` unless the tooltip is already using the `column.ariaLabel` text since we don't want the same text as both label & description.
The reason to add `onFocus` and `onBlur` events to the columnheader node + call `.show()` and `.dismiss()` was to avoid needing to rearrange the DOM to make the TooltipHost the parent of the focusable columnheader.
- Fixes [16455](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/16455)

fix: DetailsColumn tooltip shows on focus, is associated via aria-describedby

---

change/@fluentui-priority-overflow-c98cbac7-b421-4898-a6b9-cd0cf7dfb500.json
change/@fluentui-react-overflow-87d68562-a91a-45c0-bdd9-133e3a7d2616.json
packages/react-components/priority-overflow/src/overflowManager.ts
packages/react-components/react-overflow/src/Overflow.cy.tsx
packages/react-components/react-overflow/stories/Overflow/Pinned.stories.tsx

When new items are added to the overflow manager, they are always visible by default. This might not actually be the 'correct' state especially considering priorities.
Consider and item that is added whose priority is less than the top of the invisible item queue - it should actually not be visible. This can negatively affect the overflow calculation (which is batched)
In order to avoid these other solutions for their negative perf and complexity:
* Add more logic to addItem to account for an 'invalid' state
* Call `forceUpdate` every time an item is added
This PR simply changes the logic to run the hide/show step twice. Which will resolve any new items to their correct state first. In order to improve performance a cache for the offset size was added. This improves the performance even …

fix: Overflow update should run show/hide steps twice

---

packages/react-components/react-migration-v8-v9/stories/Stack/index.stories.tsx

fixed height/width styles in the story example containers prevented content reflow, which is a WCAG requirement
stories use flexible height/width
- Fixes [15926](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/15926)

fix: StackShim story styles allow content reflow

---

change/@fluentui-react-tree-3b5f955f-0166-4e3b-85dc-82dddef56b0c.json
packages/react-components/react-tree/src/components/TreeItemLayout/useTreeItemLayout.tsx

1. makes selector slot required whenever the selection mode is defined, to ensure slot creation
- Fixes #

bugfix: selector slot required when selection mode is defined

---

apps/vr-tests-react-components/src/stories/Positioning.stories.tsx
change/@fluentui-react-positioning-bc570315-c0a5-4a0f-a762-5fb18e58b4e8.json
packages/react-components/react-positioning/src/createPositionManager.ts
packages/react-components/react-positioning/src/middleware/maxSize.ts
packages/react-components/react-positioning/src/types.ts
packages/react-components/react-positioning/src/usePositioning.ts
packages/react-components/react-positioning/src/utils/index.ts
packages/react-components/react-positioning/src/utils/normalizeAutoSize.test.ts
packages/react-components/react-positioning/src/utils/normalizeAutoSize.ts

Fix item 2 in #28623
AutoSize has several options:
```tsx
export type AutoSize = 'height' | 'height-always' | 'width' | 'width-always' | 'always' | boolean;
export interface PositioningOptions {
autoSize?: AutoSize;
}
```
`'height'` - apply max-height only when floating element overflows boundary.
`'height-always'` - apply max-height regardless of overflow.
The same goes with `true`/`'always'` and `'width'`/`'width-always'`.
There are two examples in [issue 28623 _2. Consolidate 'height'/'height-always' option_](https://github.com/microsoft/fluentui/issues/28623), explaining why we need both set of options.
Options `'always'/'height-always'/'width-always'` are now obsolete, and equivalent to `true/'height'/'width'`.
This is achieved by always applying max-height/max-width, but remove them …

feat(react-positioning): simplify maxSize options

---

change/@fluentui-react-toolbar-d17fdf5d-7561-468e-b616-f1bbe8f690d5.json
packages/react-components/react-toolbar/src/components/ToolbarButton/useToolbarButtonStyles.styles.ts

Remove margin from icon inside ToolbarButton when vertical. 
Before: 
After:

fix: remove margin from icon when ToolbarButton is vertical

---

change/@fluentui-react-tree-b70a6941-a063-49d6-a196-4dbd7abfd90c.json
packages/react-components/react-tree/etc/react-tree.api.md
packages/react-components/react-tree/src/components/FlatTree/useHeadlessFlatTree.ts
packages/react-components/react-tree/src/contexts/treeItemContext.ts
packages/react-components/react-tree/src/hooks/useRovingTabIndexes.ts
packages/react-components/react-tree/src/utils/createHeadlessTree.ts

1. improves internal headless signature by exposing `.add` method
2. renames internal parts from `flat` to `headless`
3. makes the default `value` on tree item context to be `virtualTreeRootId`
4. removes console warn for no tabbable element (since the tree can be empty...)
- Fixes #

chore: improves internal headless signature

---

change/@fluentui-react-tree-b474b0cc-81a2-48d4-b63b-268445c11d76.json
packages/react-components/react-tree/etc/react-tree.api.md
packages/react-components/react-tree/src/components/FlatTree/__snapshots__/FlatTree.test.tsx.snap
packages/react-components/react-tree/src/components/FlatTree/useFlatTreeNavigation.ts
packages/react-components/react-tree/src/components/FlatTree/useHeadlessFlatTree.ts
packages/react-components/react-tree/src/components/Tree/Tree.types.ts
packages/react-components/react-tree/src/components/Tree/__snapshots__/Tree.test.tsx.snap
packages/react-components/react-tree/src/components/Tree/useTree.ts
packages/react-components/react-tree/src/components/Tree/useTreeNavigation.ts
packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx
packages/react-components/react-tree/src/components/TreeItem/useTreeItemContextValues.ts
packages/react-components/react-tree/src/components/TreeItemLayout/useTreeItemLayout.tsx
packages/react-components/react-tree/src/contexts/treeContext.ts
packages/react-components/react-tree/src/contexts/treeItemContext.ts
packages/react-components/react-tree/src/hooks/useRootTree.ts
packages/react-components/react-tree/src/hooks/useRovingTabIndexes.ts
packages/react-components/react-tree/src/hooks/useSubtree.ts
packages/react-components/react-tree/src/utils/createHTMLElementWalker.ts
packages/react-components/react-tree/src/utils/createHeadlessTree.ts
packages/react-components/react-tree/src/utils/nextTypeAheadElement.ts

1. reduces the amount of HTMLElementWalker instances being created
2. adds `openItems` and `checkedItems` to tree callback data
3. adds `checked` state to tree item context
4. fix role `baseTree` issue
- Fixes #

feat(react-tree): adds openItems and checkedItems to tree callback data

---

change/@fluentui-react-menu-510dece4-88f8-4c7d-9e27-036a1e74d520.json
packages/react-components/react-menu/src/components/MenuItem/useMenuItemStyles.styles.ts

Use css outline for MenuItem focus ring.

fix(react-menu): use outline for menuItem focus ring

---

apps/vr-tests-react-components/package.json
apps/vr-tests-react-components/src/stories/Breadcrumb/Breadcrumb.stories.tsx
apps/vr-tests-react-components/src/stories/Breadcrumb/utils.tsx
packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbWithOverflow.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/BreadcrumbButton/index.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/BreadcrumbDivider/index.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/BreadcrumbItem/index.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/BreadcrumbLink/BreadcrumbLinkDefault.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/BreadcrumbLink/index.stories.tsx

- Added VR tests
- Move Breadcrumb stories to one folder

Added VR tests for Breadcrumb

---

change/@fluentui-react-shared-contexts-6be5add1-ce81-4471-bd65-d79d627c1a96.json
packages/react-components/react-shared-contexts/etc/react-shared-contexts.api.md
packages/react-components/react-shared-contexts/src/AnnounceContext/AnnounceContext.ts
packages/react-components/react-shared-contexts/src/AnnounceContext/index.ts
packages/react-components/react-shared-contexts/src/index.ts

This PR adds AnnounceContext for use in FAI.
This context is a top-level screen reader notification utility that can be consumed by any component and used to fire on-demand screen reader announcements.
With something as complex as chat, and especially with loading messages and uploading files, we need a way to manage and queue custom screen reader notifications. Chat messages especially need the ability to have the screen reader notification text differ from the visual text on screen, since the visual text of a message often contains more information than is necessary in a notification.
We are hosting it in FUI instead of FAI because we eventually want it in FUI, and having the context be imported from there means we won’t have to change the import every place it’s used.

feat(react-shared-contexts): add AnnounceContext

---

change/@fluentui-react-accordion-d347d71a-89ad-47dd-94e6-e739bbd01e34.json
packages/react-components/react-accordion/etc/react-accordion.api.md
packages/react-components/react-accordion/src/components/AccordionHeader/AccordionHeaderContext.ts
packages/react-components/react-accordion/src/components/AccordionHeader/index.ts
packages/react-components/react-accordion/src/index.ts

I'm working on extending the functionality of AccordionHeaderProvider in TMP and need to "override" the `renderAccordionHeader_unstable` function and add a slot. To do this, I need to render `AccordionHeaderContextProvider` as a wrapper, but currently its not exported from FluentUI.
no export
exported AccordionHeaderContextProvider
- Fixes #

Accordion: export AccordionHeaderProvider

---

packages/react-components/react-tags-preview/src/components/InteractionTag/useInteractionTagStyles.styles.ts
packages/react-components/react-tags-preview/stories/TagGroup/TagGroupOverflow.stories.tsx

Fix the left over issues on #28368 
1. InteractionTag brand variant had no style change on hover in contrast theme, now it changes text color: 
2. InteractionTag outline variant fills icon on hover and changes icon to brand color
3. Fix visual issue in Tag overflow story:
| before | after | 
| ------ | ------ |
|<img width="181" alt="image" src="https://github.com/microsoft/fluentui/assets/28751745/fc23eeba-3cec-4f06-adf1-185c2c3d0fc9">| <img width="180" alt="image" src="https://github.com/microsoft/fluentui/assets/28751745/de8ebce2-4d40-45f6-9d98-50d430410ab1"> |

fix(react-tags-preview): fix InteractionTag hover styles

---

change/@fluentui-react-positioning-86dcd6cd-76f3-4f49-b446-04e827493aa7.json
packages/react-components/react-positioning/src/middleware/maxSize.test.ts
packages/react-components/react-positioning/src/middleware/maxSize.ts

#28649 introduced `resetMaxSize`  middleware - when `autoSize` is specified, `resetMaxSize` middleware is used to reset the styles from previous life cycle and set a flag to not reset again. But the flag didn't work because of a stupid mistake in the check. This PR corrects it.

fix(react-positioning): autoSize causing position update to reach maximum

---

apps/public-docsite-v9/src/Concepts/AdvancedConfiguration.stories.mdx
change/@fluentui-react-provider-c1192c64-622d-40a5-9732-ee38cc84acef.json
packages/react-components/react-provider/src/components/FluentProvider/FluentProvider-hydrate.test.tsx
packages/react-components/react-provider/src/components/FluentProvider/FluentProvider.test.tsx
packages/react-components/react-provider/src/components/FluentProvider/useFluentProvider.test.tsx
packages/react-components/react-provider/src/components/FluentProvider/useFluentProvider.ts
packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderThemeStyleTag.ts

This PR:
- updates docs to include a section about React 18
- `FluentProvider` emits errors on if proper configuration is missing and IDs are duplicated

feat(FluentProvider): emit errors on duplicate IDs

---

change/@fluentui-react-menu-93b6b74a-3721-45f9-ab96-6f9be236abf9.json
packages/react-components/react-menu/src/components/MenuItem/useMenuItemStyles.styles.ts

revert #28685 
Why outlined focus ring is not used in this specific case:
When Menu is default open, on page load it focuses on the first item, browser will render a default `:focus-visible` ring with css `outline` styles. If we don't want this, we need to do two things:
1. set default focus ring to none by  `':focus-visible': { outlineStyle: 'none' }`
2. update our focus ring selector from  `[&data-fui-focus-visible]: style` to `[&data-fui-focus-visible]:focus: style`, to be more specific and win over the style we added in step 1.
But this brings new issue - we have consumers overriding focus ring style by using just `:focus-visible`. If we update our own focus ring selector to be more specific, it breaks their overrides.
Since we don't want focus ring on default load (which will break …

fix(react-menu): revert menuitem focus ring back to border

---

.github/ISSUE_TEMPLATE/feature-request.yml

Partners and library customers were not able to specify their feature request priority when creating one.
Added Priority dropdown to feature request template.

feat(feature-requests): Priority dropdown to feature request template

---

change/@fluentui-react-breadcrumb-preview-5bdaf6e2-9260-4dfe-ace7-09993bd79c34.json
packages/react-components/react-breadcrumb-preview/docs/Spec.md
packages/react-components/react-breadcrumb-preview/etc/react-breadcrumb-preview.api.md
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/BreadcrumbItem.test.tsx
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/BreadcrumbItem.types.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/renderBreadcrumbItem.tsx
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/useBreadcrumbItem.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/useBreadcrumbItemStyles.styles.ts
packages/react-components/react-breadcrumb-preview/stories/BreadcrumbItem/BreadcrumbItemDefault.stories.tsx

At the beginning we agreed not to have an icon for non-interactive items.
The designers asked to have icons in all the items for consistency. I, also, found a use case in Loop app that non-clickable items can have icons.
It was not possible to have icons as part of BreadcrumbItem.
Added possibility to have an icon for BreadcrumbItem

Added icon to the BreadcrumbItem

---

change/@fluentui-react-tree-7b6d4596-b8e2-46b5-a0d4-d3d4e921fce0.json
packages/react-components/react-tree/etc/react-tree.api.md
packages/react-components/react-tree/src/components/TreeItemLayout/TreeItemLayout.types.ts
packages/react-components/react-tree/src/components/TreeItemLayout/__snapshots__/TreeItemLayout.test.tsx.snap
packages/react-components/react-tree/src/components/TreeItemLayout/renderTreeItemLayout.tsx
packages/react-components/react-tree/src/components/TreeItemLayout/useTreeItemLayout.tsx
packages/react-components/react-tree/src/components/TreeItemLayout/useTreeItemLayoutStyles.styles.ts
packages/react-components/react-tree/src/components/TreeItemPersonaLayout/TreeItemPersonaLayout.types.ts
packages/react-components/react-tree/src/components/TreeItemPersonaLayout/__snapshots__/TreeItemPersonaLayout.test.tsx.snap
packages/react-components/react-tree/src/components/TreeItemPersonaLayout/renderTreeItemPersonaLayout.tsx
packages/react-components/react-tree/src/components/TreeItemPersonaLayout/useTreeItemPersonaLayout.ts
packages/react-components/react-tree/src/components/TreeItemPersonaLayout/useTreeItemPersonaLayoutStyles.styles.ts

`TreeItemLayout` and `TreeItemPersonaLayout` have a `content` slot. Seems like some collision issues are happening between the `content` slot and the props provided by root https://github.com/microsoft/fluentui/issues/28693#issuecomment-1659737176
1. Renames `content` slot to `main` to avoid collision
- Fixes https://github.com/microsoft/fluentui/issues/28693

bugfix: renames content slot to main

---

change/@fluentui-react-menu-e3ad7a8c-1083-4535-90f9-b4dc318a6dce.json
packages/react-components/react-menu/src/components/Menu/Menu.cy.tsx
packages/react-components/react-menu/src/components/MenuTrigger/useMenuTrigger.ts

`MenuTrigger` would open a menu regardless if the `contextmenu` event was prevent.
1. `MenuTrigger` doesn't open the menu if `contextmenu` event has been prevented
2. adds test to ensure behavior
- Fixes #

bugfix: disable menu opening if contextmenu event is prevented

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-component-event-listener/src/EventListener.ts

No deprecation warnings with React 18 in `EventListener` component.
- Fixes #28024

fix(EventListener): do not use `defaultProps`

---

change/@fluentui-react-breadcrumb-preview-4a519bc6-2ba9-46ca-9959-8a0ca5985548.json
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbButton/useBreadcrumbButtonStyles.styles.ts
packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbSize.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbWithOverflow.stories.tsx

Made BreadcrumbButton consistent with Item and Link

---

apps/perf-test-react-components/tsconfig.json
change/@fluentui-react-theme-sass-e2d8f9af-d82d-46c9-aa2e-c2a282d629fb.json
change/@fluentui-tokens-3fab400b-e938-422a-8e03-d509bfd2c4dc.json
packages/react-components/react-theme-sass/sass/colorPaletteTokens.scss
packages/tokens/etc/tokens.api.md
packages/tokens/src/alias/darkColorPalette.ts
packages/tokens/src/alias/highContrastColorPalette.ts
packages/tokens/src/alias/lightColorPalette.ts
packages/tokens/src/global/colorPalette.ts
packages/tokens/src/sharedColorNames.ts
packages/tokens/src/statusColorMapping.ts
packages/tokens/src/tokens.ts
packages/tokens/src/types.ts
packages/tokens/src/utils/createDarkTheme.ts
packages/tokens/src/utils/createHighContrastTheme.ts
packages/tokens/src/utils/createLightTheme.ts
packages/tokens/src/utils/createTeamsDarkTheme.ts

This PR adds status color tokens to theme `tokens` package.
It adds `success`, `warning` and `danger` tokens which are mapped:
success ➡️ `green`
warning ➡️ `orange`
danger ➡️ `cranberry`
Each status color defines 10 tokens with the following mapping in individual themes:
| token | Light | Dark | Teams HC |
|-------|-------|------|----------|
| `colorStatus${color}Background1` | tint60 | shade40 | hcCanvas | 
| `colorStatus${color}Background2` | tint40 | shade30 | hcCanvas | 
| `colorStatus${color}Background3` | primary | primary |  hcCanvasText |
| `colorStatus${color}Foreground1` | shade10 | tint30 | hcCanvasText | 
| `colorStatus${color}Foreground2` | shade30 | tint40 | hcCanvasText | 
| `colorStatus${color}Foreground3` | primary | tint20 | hcCanvasText | 
| …

feat(tokens): Add status color tokens

---

change/@fluentui-react-c9b264cb-f787-48ed-a936-6359e1efa00e.json
packages/react/src/components/TimePicker/TimePicker.test.tsx
packages/react/src/components/TimePicker/TimePicker.tsx

TimePicker selection does not work when using a locale that doesn't use the characters "am"/"pm" in the time format, such as Japanese. This happens because the TimePicker is attempting to parse the locale-formatted time string of the new value when the selection changes, using a parsing function that is not locale-aware.
Save the Date object in each of the ComboBox items used by TimePicker. When a new selection is made, use the Date object itself, rather than parsing the formatted time string.
- Fixes #28435

fix(TimePicker): Selection now works in locales that don't use "am"/"pm" in their time format

---

.github/workflows/azure-static-web-apps-deploy.yml

WC storybook deploy pipeline is broken as it uses node 18: https://github.com/microsoft/fluentui/actions/runs/5590137140/job/15140616749
The deploy pipeline uses node 16.

Use node16 in WC deploy workflow

---

change/@fluentui-react-jsx-runtime-d2a505fc-6ffc-4679-aa63-5b29dcc83f7b.json
change/@fluentui-react-utilities-18c147c2-15a4-428f-89a7-049632ab27fe.json
packages/react-components/react-jsx-runtime/src/createElement.test.tsx
packages/react-components/react-jsx-runtime/src/createElement.ts
packages/react-components/react-utilities/etc/react-utilities.api.md
packages/react-components/react-utilities/src/compose/assertSlots.test.tsx
packages/react-components/react-utilities/src/compose/assertSlots.ts
packages/react-components/react-utilities/src/compose/constants.ts
packages/react-components/react-utilities/src/compose/getSlots.ts
packages/react-components/react-utilities/src/compose/getSlotsNext.test.tsx
packages/react-components/react-utilities/src/compose/index.ts
packages/react-components/react-utilities/src/compose/isSlot.test.tsx
packages/react-components/react-utilities/src/compose/isSlot.ts
packages/react-components/react-utilities/src/compose/resolveShorthand.test.tsx
packages/react-components/react-utilities/src/compose/resolveShorthand.ts
packages/react-components/react-utilities/src/compose/slot.test.tsx
packages/react-components/react-utilities/src/compose/slot.ts
packages/react-components/react-utilities/src/compose/types.ts
packages/react-components/react-utilities/src/index.ts

This PR implements the next steps on slot API as discussed on previous RFC's and issues on this topic.
1. https://github.com/microsoft/fluentui/issues/27376
2. https://github.com/microsoft/fluentui/pull/27164
1. adds `slot` namespace that provides all methods to help create a slot
2. adds `assertSlots` method to ensure the state provided by a state hook is following proper new mechanisms
3. modifies `@fluentui/react-jsx-runtime` to properly support previous and new methods of slot creation accordingly
4. modifies `resolveShorthand` to do exactly the same thing as `slot` does
- Fixes https://github.com/microsoft/fluentui/issues/27376

feature(react-utilities): implements new slot methods (`slot` and `assertSlots`)

---

.github/workflows/azure-static-web-apps-deploy.yml

- WC storybook deployment was triggered only by change directly in `packages/web-components`
- the deployment is triggered by a change anywhere in the `packages/web-components` subtree
- it is possible to trigger the workflow manually

chore(wc): allow the CI to be triggered manually

---

apps/vr-tests-web-components/.storybook/preview.mjs
apps/vr-tests-web-components/src/stories/accordion/accordion.stories.tsx
apps/vr-tests-web-components/src/utilities/WCThemeDecorator.tsx
change/@fluentui-web-components-e7f611c9-b323-4f2d-aaed-519f0773c058.json
packages/web-components/src/theme/index.ts
packages/web-components/src/theme/set-theme.ts

Adds VR tests for `fluent-accordion` WC.
Adds Story decorator which sets light/dark theme and LTR/RTL direction for the story.

chore(fluent-accordion): Add screenshot tests

---

change/@fluentui-react-tree-d232366f-f4dc-4d83-ab71-0c1c341c1798.json
packages/react-components/react-tree/src/utils/createHeadlessTree.ts

1.  `createHeadlessTree`  ignored initial `itemType` value provided by the user on tree item creation
1. `createHeadlessTree` now respects initial `itemType` value provided by the user on tree item creation
- Fixes https://github.com/microsoft/fluentui/issues/28758

bugfix: headless tree should respect itemType

---

change/@fluentui-priority-overflow-811e9856-73dc-48a0-8707-3f65814b5c57.json
change/@fluentui-react-overflow-e570ea11-80af-458c-a5a9-392d1e17e776.json
packages/react-components/priority-overflow/src/overflowManager.ts
packages/react-components/react-overflow/src/Overflow.cy.tsx

Fixed bug with inaccurate calc

---

.github/workflows/azure-static-web-apps-deploy.yml
package.json

- Repo dependencies require node <= 16, otherwise fail to install:
- Engines allow node 16 or node 18.
Engines only allow node 16.
- Fixes CI

build(wc): Enforce node 16

---

azure-pipelines.yml
tools/workspace-plugin/src/generators/cypress-component-configuration/lib/add-files.ts
tools/workspace-plugin/src/generators/dependency-mismatch/index.ts
tools/workspace-plugin/src/generators/generate-change-file.spec.ts
tools/workspace-plugin/src/generators/generate-change-files.ts
tools/workspace-plugin/src/generators/migrate-converged-pkg/index.spec.ts
tools/workspace-plugin/src/generators/migrate-converged-pkg/index.ts
tools/workspace-plugin/src/generators/migrate-converged-pkg/lib/utils.ts
tools/workspace-plugin/src/generators/migrate-v8-pkg/lib/utils.ts
tools/workspace-plugin/src/generators/normalize-package-dependencies/index.spec.ts
tools/workspace-plugin/src/generators/normalize-package-dependencies/index.ts
tools/workspace-plugin/src/generators/prepare-initial-release/index.spec.ts
tools/workspace-plugin/src/generators/print-stats.spec.ts
tools/workspace-plugin/src/generators/print-stats.ts
tools/workspace-plugin/src/generators/rc-caret/index.ts
tools/workspace-plugin/src/generators/react-component/index.ts
tools/workspace-plugin/src/generators/react-library/index.ts
tools/workspace-plugin/src/generators/recipe-generator/index.spec.ts
tools/workspace-plugin/src/generators/tsconfig-base-all/lib/utils.ts
tools/workspace-plugin/src/generators/version-bump/index.ts
tools/workspace-plugin/src/generators/workspace-generator/index.ts
tools/workspace-plugin/src/utils.ts
tools/workspace-plugin/tsconfig.json

Fixes #28736.
Fixes #28737.
`@fluentui/workspace-plugin` didn't have `esModuleInterop` enabled, this PR enables it. Imports were updated to follow this.
The main goal is to fix `chalk` usage as `import * as chalk` does not work in the configuration of `ts-node` provided by Nx.

fix: update chalk usage in a generator

---

packages/fluentui/CHANGELOG.md
packages/fluentui/react-northstar/src/components/Toolbar/Toolbar.tsx

Warnings are triggered once `children` are defined:
```
Warning: Failed prop type: Prop `items` in `Toolbar` conflicts with props: `children`. They cannot be defined together, choose one or the other.
```
No warnings on this usage.

fix(Toolbar): remove `items` from `defaultProps`

---

change/@fluentui-react-components-456dce87-c14b-482d-8f3a-cd2e4fe113b2.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts

Export these utilities so that they can be reused for the [react-chat component](https://github.com/microsoft/fluentui-contrib/tree/main/packages/react-chat)

feat: Export useEventCallback and mergeCallbacks

---

change/@fluentui-react-breadcrumb-preview-ccc0bbee-fe68-4046-bec9-c215d548e0bf.json
packages/react-components/react-breadcrumb-preview/etc/react-breadcrumb-preview.api.md
packages/react-components/react-breadcrumb-preview/src/components/Breadcrumb/Breadcrumb.cy.tsx
packages/react-components/react-breadcrumb-preview/src/components/Breadcrumb/Breadcrumb.test.tsx
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbLink/BreadcrumbLink.test.tsx
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbLink/BreadcrumbLink.types.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbLink/useBreadcrumbLink.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbLink/useBreadcrumbLinkStyles.styles.ts

- It was possible to focus on the disabled BreadcrumbLink
- No styles for hover on a BreadcrumbLink with single icon
- Disabled BreadcrumbLink is not focusable
- Added border-bottom on hover for a BreadcrumbLink with a single icon

fix: made disabled BreadcrumbLink not focusable

---

change/@fluentui-priority-overflow-a7aa4464-bf5d-40c9-9502-4936cb1f0c3f.json
change/@fluentui-react-overflow-76164a9e-e55d-44b1-b7be-4f397c4cfa86.json
packages/react-components/priority-overflow/src/overflowManager.ts
packages/react-components/react-overflow/src/Overflow.cy.tsx
packages/react-components/react-overflow/stories/Overflow/LargerDividers.stories.tsx

Fix: flickering of items with large dividers in Overflow component

---

change/@fluentui-react-tabs-79da62f4-21a0-4398-a9dd-e850571f6a38.json
packages/react-components/react-tabs/etc/react-tabs.api.md
packages/react-components/react-tabs/src/components/Tab/Tab.types.ts
packages/react-components/react-tabs/src/components/Tab/renderTab.tsx
packages/react-components/react-tabs/src/components/Tab/useTab.ts
packages/react-components/react-tabs/src/components/Tab/useTabStyles.styles.ts
packages/react-components/react-tabs/src/components/TabList/renderTabList.tsx
packages/react-components/react-tabs/src/components/TabList/useTabList.ts

1. Migrates `react-tabs`  package to new slot API
2. adds new internal slot to stop logic from spreading into render method

chore(react-tabs): migrate to new slot API

---

change/@fluentui-react-8d5952ad-7979-4a9c-bae9-f37a22caf598.json
packages/react/src/components/DetailsList/DetailsRow.styles.ts

In the `DetailsList`, if focus is on a row and focus rectangles are visible, a Link within a cell cannot be clicked, because the events are intercepted by the `:after` element on the row.
The focus rectangles supplied by `:after` now have `pointer-events: none` so that the clicks are not intercepted.
This appears to have been a regression some time within the last several months.

Default pointer-events to 'none' for focus rectangles

---

change/@fluentui-react-utilities-adc87890-3e9b-4efb-9165-98576d3078d2.json
packages/react-components/react-utilities/src/compose/slot.test.tsx
packages/react-components/react-utilities/src/compose/slot.ts

1. console error when an invalid value is passed
2. adds tests to ensure `slot.resolveShorthand` behavior
- Fixes https://github.com/microsoft/fluentui/issues/28807

chore: slot.resolveShorthand consoles error on invalid value

---

apps/public-docsite-v9/src/Concepts/Slots/Slots.stories.mdx

1. updates documentation to use new slot API (`slot.*` and `assertSlots` methods)
2. updates documentation to refer to terms such as "shorthand" value on examples
- Fixes https://github.com/microsoft/fluentui/issues/28788

chore(public-docsite-v9): updates slot documentation

---

change/@fluentui-react-portal-compat-f3f95299-f0a8-4c7e-8de0-e104a03a11fc.json
packages/react-components/react-portal-compat/tsconfig.json

1. changes tsconfig target from `ES5` to `ES2019`
- Fixes #

chore(react-portal-compat): changes tsconfig target to ES2019

---

change/@fluentui-react-jsx-runtime-911c855a-9f72-4f62-8d13-d9f768887ada.json
packages/react-components/react-jsx-runtime/etc/react-jsx-runtime.api.md
packages/react-components/react-jsx-runtime/package.json
packages/react-components/react-jsx-runtime/src/createElement.ts
packages/react-components/react-jsx-runtime/src/jsx-dev-runtime.ts
packages/react-components/react-jsx-runtime/src/jsx-runtime.test.tsx
packages/react-components/react-jsx-runtime/src/jsx-runtime.ts
packages/react-components/react-jsx-runtime/src/jsx/createElementFromSlotComponent.ts
packages/react-components/react-jsx-runtime/src/jsx/jsxDEVFromSlotComponent.ts
packages/react-components/react-jsx-runtime/src/jsx/jsxDynamicFromSlotComponent.ts
packages/react-components/react-jsx-runtime/src/jsx/jsxStaticFromSlotComponent.ts
packages/react-components/react-jsx-runtime/src/utils/DevRuntime.ts
packages/react-components/react-jsx-runtime/src/utils/Runtime.ts
packages/react-components/react-jsx-runtime/src/utils/createCompatSlotComponent.ts
packages/react-components/react-jsx-runtime/src/utils/getMetadataFromSlotComponent.test.ts
packages/react-components/react-jsx-runtime/src/utils/getMetadataFromSlotComponent.ts
packages/react-components/react-jsx-runtime/src/utils/types.ts
tsconfig.base.all.json
tsconfig.base.json

Previously `@fluentui/react-jsx-runtime` only supported the classic mode of declaring a JSX pragma, through a signature similar to `React.createElement`
Add support for React 17's automatic JSX transform (works from React 16.14).
This PR adds support for the [new "automatic" JSX runtime from React 16.14/17+](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)
- Fixes https://github.com/microsoft/fluentui/issues/27646

feat: supports new automatic JSX runtime

---

change/@fluentui-react-breadcrumb-preview-d29e00b6-09e4-4092-abba-d4030da7d9aa.json
packages/react-components/react-breadcrumb-preview/docs/MIGRATION.md
packages/react-components/react-breadcrumb-preview/docs/Spec.md
packages/react-components/react-breadcrumb-preview/etc/react-breadcrumb-preview.api.md
packages/react-components/react-breadcrumb-preview/src/components/Breadcrumb/Breadcrumb.types.ts
packages/react-components/react-breadcrumb-preview/src/components/Breadcrumb/BreadcrumbContext.ts
packages/react-components/react-breadcrumb-preview/src/components/Breadcrumb/useBreadcrumb.ts
packages/react-components/react-breadcrumb-preview/src/components/Breadcrumb/useBreadcrumbContextValue.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbButton/BreadcrumbButton.test.tsx
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbButton/BreadcrumbButton.types.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbButton/useBreadcrumbButton.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/BreadcrumbItem.types.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/renderBreadcrumbItem.tsx
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/useBreadcrumbItem.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbLink/BreadcrumbLink.test.tsx
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbLink/BreadcrumbLink.types.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbLink/renderBreadcrumbLink.tsx
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbLink/useBreadcrumbLink.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbLink/useBreadcrumbLinkStyles.styles.ts
packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbDefault.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbFocusMode.tsx
packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbLinkWithOverflow.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/BreadcrumbButton/BreadcrumbButtonDefault.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/BreadcrumbItem/BreadcrumbItemDefault.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/BreadcrumbLink/BreadcrumbLinkDefault.stories.tsx

After discussion with design team we can have only left icon in the Breadcrumb
It was possible to have only icon and iconPosition: 'after'
Only left icon is supported.

Removed iconPosition from the Breadcrumb

---

apps/public-docsite/src/components/Site/Site.tsx
apps/public-docsite/src/utilities/cdn.ts
change/@fluentui-react-docsite-components-2a60a3d3-f60d-4f53-94b2-533d4d8a7435.json
packages/react-docsite-components/src/components/TopBanner/TopBanner.module.scss
packages/react-docsite-components/src/components/TopBanner/TopBanner.tsx
packages/react-docsite-components/src/components/TopBanner/TopBanner.types.ts
packages/react-docsite-components/src/components/TopBanner/index.ts
packages/react-docsite-components/src/index2.ts

This PR adds the top banner that points to the Fluent 2 design website. Note that this is missing adding the correct image to the cdn. The screenshot has a local placeholder.
|desktop|mobile|
|---|---|
|![image](https://github.com/microsoft/fluentui/assets/5953191/655ab681-e8f1-47ce-a086-c0cc3d228a13)|![image](https://github.com/microsoft/fluentui/assets/5953191/a46254e3-04e7-4464-901a-660e04d12e6d)|

feat(public-docsite): Add topbanner component and use it in the public docsite

---

change/@fluentui-react-virtualizer-5bc6cfeb-7159-424d-8126-dc7da21c53ff.json
packages/react-components/react-virtualizer/src/components/VirtualizerScrollView/useVirtualizerScrollView.ts
packages/react-components/react-virtualizer/src/components/VirtualizerScrollViewDynamic/useVirtualizerScrollViewDynamic.ts

We were not passing through scrollViewRef into the merged refs
ScrollViewRef prop should now be merged with container prop in scrollview virtualizers.
N/A

Virtualizer: Merge scrollref prop with container ref

---

apps/public-docsite/src/components/Site/Site.tsx
change/@fluentui-react-docsite-components-39f2229f-7780-419d-8bbf-76bdf9bbec81.json
packages/react-docsite-components/src/components/TopBanner/TopBanner.module.scss

Since header will always be on top, move top banner under top nav and remove the top clipping to the top to avoid image movement.

fix(public-docsite): Remove image clipping and move top banner under top nav to avoid header issues

---

packages/react-components/react-tree/stories/Tree/TreeDescription.md

1. Removes preview waning from the docs 
- Fixes #

chore(react-tree): removes preview warning from the docs

---

change/@fluentui-react-tree-5db5f312-385a-4073-a98c-320f5de3da2f.json
packages/react-components/react-tree/src/utils/createHeadlessTree.ts

1. bugfix: headless flat tree should allow the user to define the `itemType` value of a tree item instead of just assuming it's a `leaf`
- Fixes #

bugfix(react-tree): headless flat tree itemType manual definition

---

change/@fluentui-react-infobutton-142725f6-a65b-4ed0-b46f-2b77476a220b.json
packages/react-components/react-infobutton/src/components/InfoButton/useInfoButtonStyles.styles.ts

The cursor when hovering over the button was default (as per native behavior).
https://github.com/microsoft/fluentui/assets/5953191/d4a20111-6427-4aca-8085-f3c6629d35d1
To show that the icon is in fact a button that can be pressed, the cursor should be pointer. This should help differentiate the behavior between the tooltip variant and the popover variant.
https://github.com/microsoft/fluentui/assets/5953191/c2df8f3d-d951-49b9-986b-faaba3660c70

fix(react-infobutton): Cursor should be pointer when hovering the button to show it's a button

---

change/@fluentui-react-positioning-d46e41bd-237b-4c6e-bb3f-b3d88a836fdd.json
change/@fluentui-react-provider-7b95053b-1bc4-4f17-b3ea-c2fa43697fae.json
change/@fluentui-react-tree-33deefd7-570d-49cc-b511-97ddc809c813.json
packages/react-components/react-accordion/stories/Accordion/AccordionMultiple.stories.tsx
packages/react-components/react-components/stories/AccessibilityScenarios/Input.stories.tsx
packages/react-components/react-components/stories/Concepts/Positioning/PositioningOffsetValue.stories.tsx
packages/react-components/react-positioning/src/usePositioning.ts
packages/react-components/react-provider/src/components/FluentProvider/useFluentProviderContextValues.ts
packages/react-components/react-tree/src/components/Tree/useTree.ts

There were lint warnings for Fluent v9 controls.
No lint warnings for Fluent v9 controls.
Noticed as part of #28145

Lint: fix fluent v9 warnings

---

change/@uifabric-azure-themes-82a081ed-2e5a-43f3-a5e0-733f2476edd3.json
packages/azure-themes/src/azure/AzureColors.ts
packages/azure-themes/src/azure/styles/DetailsList.styles.ts

When unselected or selected row is tabbed into (focus state) the contrast ratio did not pass accessibility standards of 3:1. Bug states: "Luminosity ratio of the focus boundary around the "rule id row" is 1.2:1 which is less than 3:1 under "Edit Exclusion" page."
Note: light theme fix only. Other themes unaffected
Design team concluded that aligning to what is live on Fluent site is best, which is #605E5C
Source: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/compact

7.0 Details list row focus contrast a11y bug fix

---

change/@fluentui-react-search-preview-36bce77d-7b10-45d8-99df-3c4c014bc2be.json
packages/react-components/react-search-preview/etc/react-search-preview.api.md
packages/react-components/react-search-preview/src/components/SearchBox/SearchBox.types.ts
packages/react-components/react-search-preview/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
packages/react-components/react-search-preview/src/components/SearchBox/renderSearchBox.tsx
packages/react-components/react-search-preview/src/components/SearchBox/useSearchBox.tsx
packages/react-components/react-search-preview/src/components/SearchBox/useSearchBoxStyles.styles.ts

1. restructure to ensure no leak of logic from state hook to render method
2. flats all slots into type declaration and uses composition API
- Fixes https://github.com/microsoft/fluentui/issues/28778

chore(react-search-preview): migrate to new slots API

---

change/@fluentui-react-drawer-7b43baa1-25d5-44e7-8c7d-a8f4a3e8ea58.json
packages/react-components/react-drawer/docs/Spec.md
packages/react-components/react-drawer/src/components/Drawer/Drawer.cy.tsx
packages/react-components/react-drawer/src/components/DrawerInline/useDrawerInlineStyles.styles.ts
packages/react-components/react-drawer/src/util/DrawerBase.types.ts
packages/react-components/react-drawer/src/util/getDefaultDrawerProps.ts
packages/react-components/react-drawer/src/util/useDrawerBaseStyles.styles.ts
packages/react-components/react-drawer/stories/Drawer/DrawerCustomSize.stories.tsx
packages/react-components/react-drawer/stories/Drawer/DrawerInline.stories.tsx
packages/react-components/react-drawer/stories/Drawer/DrawerPosition.stories.tsx
packages/react-components/react-drawer/stories/Drawer/DrawerPreventClose.stories.tsx
packages/react-components/react-drawer/stories/Drawer/DrawerResponsive.stories.tsx
packages/react-components/react-drawer/stories/Drawer/DrawerSeparator.stories.tsx
packages/react-components/react-drawer/stories/Drawer/DrawerSize.stories.tsx
packages/react-components/react-drawer/stories/Drawer/DrawerWithNavigation.stories.tsx

This PR is a quick rename of Drawer position prop values from left/right to start/end. This is to help when in rtl.

fix: rename values of position prop from left/right to start/end

---

change/@fluentui-web-components-2eeaa976-b933-4d3c-8f63-a4a0818f1e74.json
package.json
packages/web-components/.eslintignore
packages/web-components/.eslintrc.json
packages/web-components/src/switch/switch.spec.ts
yarn.lock

- By using `test.describe.only()` in one component test, all tests for other components were ignored.
- No lint rules enforced on spec.ts
- All tests are executed
- `spec.ts` files are linted
- playwright rules added

chore: Add lint rules for playwright, enable unit tests

---

apps/vr-tests-react-components/src/stories/Tag/InteractionTagAppearances.stories.tsx
change/@fluentui-react-tags-preview-ec023340-9146-4eb3-b535-b0d3230ecbac.json
packages/react-components/react-tags-preview/src/components/InteractionTagPrimary/useInteractionTagPrimaryStyles.styles.ts
packages/react-components/react-tags-preview/src/components/InteractionTagSecondary/useInteractionTagSecondaryStyles.styles.ts
packages/react-components/react-tags-preview/src/components/Tag/useTagStyles.styles.ts

Tag should show pressed style on keyboard enter/space as well.

fix(react-tags-preview): use `:active` for pressed style instead of `:hover:active`

---

apps/public-docsite-v9/src/Concepts/Migration/FromV8/Components/Input.stories.mdx

FUIv8's `Textarea` has a "multiline" prop while FUIv9's `Input` does not. In FUIv9 we have the `Textarea` component for multiline input instead. While this is noted in the migration table toward the end of the doc it was not clearly stated at the top of the document.
In the summary section, at the top of the migration doc, adds a statement to use `Textarea` for multiline input.

docs: update input migration with more multiline information

---

apps/vr-tests-web-components/src/stories/switch/switch.stories.tsx

Add screenshot tests for `fluent-switch`

chore(switch): Add screenshot tests

---

apps/vr-tests-web-components/src/stories/text/text.stories.tsx

Add screenshot tests for `fluent-text`

chore(text): Add screenshot tests

---

packages/react-components/react-nav-preview/src/components/Nav/renderNav.tsx
packages/react-components/react-nav-preview/src/components/Nav/useNav.ts

Seems like this package has been scaffolded after the new slot API has been implemented, but before updating the scaffolding tools 🙈 (https://github.com/microsoft/fluentui/pull/28916)
1. migrates to use the new slot API
- Fixes #

chore(react-nav-preview): migrates to use new slot API

---

change/@fluentui-react-tree-bd477d26-b715-40ab-958c-bf2c1fbc5ab9.json
package.json
packages/react-components/react-tree/tsconfig.cy.json
packages/react-examples/package.json
packages/react-examples/tsconfig.cy.json
scripts/cypress/src/base.config.ts
yarn.lock

1. bumps version of `esbuild-loader` to v3.2.0
2. updates cypress configuration to use local package `./tsconfig.cy.json` instead of global tsconfig
3. adds local `tsconfig.cy.json` to `@fluentui/react-examples`
4. adds local `tsconfig.cy.json` to `@fluentui/react-tree`
[esbuild-loader@3.0.0](https://github.com/esbuild-kit/esbuild-loader/releases/tag/v3.0.0) introduces support for using the `tsconfig` path directly and it'll also respect [extends](https://www.typescriptlang.org/tsconfig#extends)
This PR makes it mandatory to have a `tsconfig.cy.json` file in the root of the package that wants to use our current `baseConfig` with `@fluentui/scripts-cypress`

chore: bumps version of esbuild-loader to v3.2.0

---

change/@fluentui-react-588a569e-53b5-4cc8-85e3-2d9c073109c2.json
packages/react/etc/react.api.md
packages/react/src/components/Autofill/Autofill.tsx

Autofill compared `this._inputElement.current === document.activeElement`, which was causing issues when used in a child window.
Autofill uses `getDocument(this._inputElement.current)`
- Fixes #27099

fix: Autofill queries the inputElement ownerDocument instead of document

---

packages/react-components/react-tree/stories/Tree/FlatTree.stories.tsx
packages/react-components/react-tree/stories/Tree/OpenItemsControlled.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeActions.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeAppearance.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeAside.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeCustomizingInteraction.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeDefault.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeDefaultOpen.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeDragAndDrop.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeExpandIcon.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeIconBeforeAndAfter.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeInfiniteScrolling.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeInlineStylingTreeItemLevel.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeLayouts.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeLazyLoading.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeManipulation.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeSelection.stories.tsx
packages/react-components/react-tree/stories/Tree/TreeSize.stories.tsx
packages/react-components/react-tree/stories/Tree/Virtualization.stories.tsx
packages/react-components/react-tree/stories/Tree/index.stories.tsx

Seems like something between our storybook code generation and codesandbox seems to break when aliasing an import, we're getting a duplicate identifier error on codesanbox when trying to open the flat tree example.
1. imports tree components from `@fluentui/react-components` instead of `@fluentui/react-tree`
- Fixes #

doc: updates doc to make it "codesandbox" compliant

---

change/@fluentui-react-utilities-75019ddc-695b-4255-9b47-0aa69be7fbcf.json
packages/react-components/react-jsx-runtime/src/interop.test.tsx
packages/react-components/react-utilities/src/compose/assertSlots.test.tsx
packages/react-components/react-utilities/src/compose/assertSlots.ts

`assertSlots` used to throw in cases such as:
1. when a slot was created with `resolveShorthand` method
2. when a slot was created by simply declaring an object with its properties
Instead of throwing, now `assertSlots` emits warn messages and mutates those slots to behave accordingly to the new API.
This ensures compatibility on use cases where the old API is alongside with the new API.
- Fixes #

bugfix: ensure interop between `assertSlots` and old API

---

packages/react-components/react-accordion/stories/Accordion/index.stories.tsx

Subcomponents were not visible in accordion story
Subcomponents and their metadata is visible in accordion story
- Fixes #28840

Accordion: added subcomponents to index story

---

change/@fluentui-azure-themes-cfae358f-02a7-46ba-8e4d-ee45180e9eb8.json
packages/azure-themes/src/azure/AzureColors.ts
packages/azure-themes/src/azure/styles/DetailsList.styles.ts

When unselected or selected row is tabbed into (focus state) the contrast ratio did not pass accessibility standards of 3:1. Bug states: "Luminosity ratio of the focus boundary around the "rule id row" is 1.2:1 which is less than 3:1 under "Edit Exclusion" page."
Note: light theme fix only. Other themes unaffected
Design team concluded that aligning to what is live on Fluent site is best, which is #605E5C
Source: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/compact
Cherry picked from [#28781](https://github.com/microsoft/fluentui/pull/28781)

8.0 Azure Theme: Details list row focus contrast a11y bug fix 

---

change/@fluentui-react-tooltip-79e44460-a719-40d8-9aeb-cc3737e454a2.json
packages/react-components/react-tooltip/etc/react-tooltip.api.md
packages/react-components/react-tooltip/src/components/Tooltip/Tooltip.types.ts
packages/react-components/react-tooltip/src/components/Tooltip/useTooltip.tsx

The KeyboardEvent object is not passed to `onVisibleChange` when the tooltip is hidden using the Escape key.
Add new field `documentKeyboardEvent` in `OnVisibleChangeData`, which is set when the visibility change happens in response to a keyboard event on the document object. Currently this only happens for the Escape key.
This allows access to the event object, which makes it possible to call `documentKeyboardEvent.preventDefault()` if needed.
- Fixes #28789

feat: Add documentKeyboardEvent to OnVisibleChangeData when Tooltip is hidden via Escape

---

change/@fluentui-react-components-b27fbad2-298f-4aac-9fe9-201f3e1f7883.json
change/@fluentui-react-table-77ca024a-803c-4ed4-9d5d-b2c4aa7d9eaa.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts
packages/react-components/react-table/etc/react-table.api.md
packages/react-components/react-table/src/index.ts

``useColumnIdContext``, ``useIsInTableHeader`` are not exposed from react-table, expose this let users implement their own datagrid header cell from primitives.
``useColumnIdContext``, ``useIsInTableHeader`` are exposed so that user can customize own DataGridHeaderCell to support different behaviour.

patch(react-table): expose DataGrid related contexts

---

packages/react-components/react-drawer/docs/Spec.md

This PR updates the Drawer spec to be more aligned with the latest developments of the react-drawer package.

docs(react-drawer): update drawer spec to be inline with changes to component

---

change/@fluentui-react-0078b842-450a-442c-b9da-1c591f0299fb.json
packages/react/src/components/KeytipLayer/KeytipLayer.base.tsx

Reverts microsoft/fluentui#28522
This is causing perf regressions with the querySelectorAll in Office online apps.

Revert "Keytips: Align keytipData with visible instance for dupes"

---

change/@fluentui-react-d1e31a08-0447-430f-8c8a-7ecdbae1691f.json
packages/react/etc/react.api.md
packages/react/src/components/Stack/Stack.tsx
packages/react/src/components/Stack/Stack.types.ts

After #25685, we no longer render null when receiving a falsy value in Stack. Instead, we render the actual child.
We keep the same behavior, but allow the previous behavior under a `doNotRenderFalsyValues` prop.
- Fixes #28970

feat(Stack): Add deprecated flag to render null when receiving a falsy value

---

change/@fluentui-react-tags-preview-94eb29aa-e1eb-4bc6-a747-23edc4f50642.json
packages/react-components/react-tags-preview/src/components/InteractionTagPrimary/useInteractionTagPrimaryStyles.styles.ts
packages/react-components/react-tags-preview/src/components/Tag/useTagStyles.styles.ts

When tag has secondary text, the primary text has `margin-top: -2px`, which overlaps with the tag border under windows high contrast:
Add a pseudo element to draw the border

fix(react-tags-preview): tag with secondary text has no top border under windows high contrast

---

change/@fluentui-react-card-97d7abde-06d9-46cc-a71a-147630a0431e.json
packages/react-components/react-card/src/components/CardHeader/useCardHeaderStyles.styles.ts

CardHeader was ignoring the content line-height by setting `grid-auto-rows`. By removing it, it automatically uses the content size to determine the height of each row.
- Fixes #28890

fix(react-card): CardHeader grid layout ignoring line-height of content

---

change/@fluentui-web-components-663811d0-6bde-44e5-8dc2-9857aea867db.json
packages/web-components/package.json

When typechecking a project that uses package exports, it is throwing an error:
```
src/browser-essentials.ts:3:26 - error TS7016: Could not find a declaration file for module '@fluentui/web-components-v3/theme.js'.
import { setTheme } from '@fluentui/web-components-v3/theme.js';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
The DTS should be correctly resolved since the package exports is pointing to the right one.

fix(web-components): Fixed pathing to types for package exports

---

.devcontainer/devcontainer.json

Updates `.devcontainer` to follow new schema https://containers.dev/supporting#visual-studio-code
- Fixes #

chore: updates .devcontainer to follow new format

---

change/@fluentui-react-popover-734b13f1-e9b6-48f6-8424-854c2b01268e.json
change/@fluentui-react-utilities-b19f3b01-374f-42a8-810c-33ad335e5e79.json
packages/fluentui/react-bindings/src/hooks/useOnIFrameFocus.ts
packages/react-components/react-popover/etc/react-popover.api.md
packages/react-components/react-popover/src/components/Popover/Popover.types.ts
packages/react-components/react-popover/src/components/Popover/usePopover.ts
packages/react-components/react-utilities/etc/react-utilities.api.md
packages/react-components/react-utilities/src/hooks/useOnClickOutside.cy.tsx
packages/react-components/react-utilities/src/hooks/useOnClickOutside.test.ts
packages/react-components/react-utilities/src/hooks/useOnClickOutside.ts

- This PR adds `closeOnIframeFocus` (defaults to `true`) to `Popover` that allows to keep popovers opened if an iframe outside a popover is focused.
- This PR adds `disabledFocusOnIframe` to options of `useOnClickOutside()` hook and covers this functionality with Cypress tests.
Fixes #28556

feat: add closeOnIframeFocus prop to Popover

---

.github/triage-bot.config.json

Bot only adds which area the issue falls into.
Bot now adds the area and a "needs: triage" label so the dev in shield can triage respectively.

chore: Make triage bot add needs triage label to new issues

---

change/@fluentui-react-dialog-255eaef7-254c-458a-8755-43716637aeb0.json
change/@fluentui-react-toast-8957c28e-fa82-41fd-9dd4-b9efd30f398e.json
packages/react-components/react-dialog/etc/react-dialog.api.md
packages/react-components/react-dialog/src/components/DialogSurface/DialogSurface.types.ts
packages/react-components/react-dialog/src/components/DialogSurface/renderDialogSurface.tsx
packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurface.ts
packages/react-components/react-toast/etc/react-toast.api.md
packages/react-components/react-toast/src/components/Toaster/Toaster.types.ts
packages/react-components/react-toast/src/components/Toaster/renderToaster.tsx
packages/react-components/react-toast/src/components/Toaster/useToaster.tsx

Follow up on https://github.com/microsoft/fluentui/issues/28865 for `DialogSurface` and `Toaster` API.
- Fixes https://github.com/microsoft/fluentui/issues/28865

feat: adds mountNode to DialogSurface and Toaster API

---

change/@fluentui-react-tags-preview-ef93566d-2d55-4b12-bf0c-06571aeda63d.json
packages/react-components/react-tags-preview/src/components/TagGroup/useTagGroup.ts

TagGroup should remember the last focused element

fix(react-tags-preview): add memorizeCurrent on TagGroup

---

change/@fluentui-react-dialog-ca3365f9-0885-4e75-989a-7a7bb419ef85.json
packages/react-components/react-dialog/src/components/DialogActions/useDialogActionsStyles.styles.ts

Seems like actions on position `start` are being positioned in the same grid position than the position `end` when the viewport reaches small size breakpoint. This causes actions to vanish
Ensures that actions position start have a different position in the grid when the viewport breakpoint is reached.
- Fixes #

bugfix: fixes DialogActions position on breakpoint

---

.github/workflows/docsite-publish-ghpages.yml
apps/public-docsite-v9/.storybook/manager.js
apps/public-docsite-v9/package.json
yarn.lock

We had no telemetry on the [React v9 docsite](https://react.fluentui.dev/).
Added [Azure Application Insights telemetry](https://learn.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview?tabs=net).

feat(docsite): add Application Insights telemetry

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Upgrades `devcontainer` configuration to use the latest debian stable release `bookworm`
- Fixes #

chore: updates devcontainer to use v16-bookworm image

---

apps/ssr-tests-v9/package.json

Currently the ssr-tests-v9 stories are located within `./src/stories/*` and the NPM task was trying to get the stories from `./stories/*`

fix(ssr-tests-v9): use correct path for ssr-tests-v9 stories

---

change/@fluentui-react-26552add-8a6c-42a8-93ca-965284270f1f.json
packages/react/src/components/KeytipLayer/KeytipLayer.base.tsx

This PR is resubmitting https://github.com/microsoft/fluentui/pull/28522 with a slight alteration to only run querySelectorAll for keytips that are visible. This will greatly reduce the number of times querySelectorAll is run
__From the original PR:_
Previous Behavior
Currently, keytips have the ability to render only for visible instances of target elements, but if there are multiple of the same registration (e.g. keytipData), the first one is always used. This can result in the keytip not being positioned correctly for the instance that's visible. Note, this is related to responsive scaling where the same control can be rendered with the same keytip tree multiple times where only one instance is visible at a time
New Behavior
With this change, the fetching of the keytipData will now …

ReAdd: Keytips: Align keytipData with visible instance for dupes

---

change/@fluentui-react-motion-preview-636e24db-8a0b-4116-99d1-001f7103748d.json
packages/react-components/react-motion-preview/package.json
packages/react-components/react-motion-preview/src/hooks/useMotion.ts
packages/react-components/react-motion-preview/src/hooks/useReducedMotion.ts

Create a new `useReducedMotion` hook to react-motion.
The goal of this hook is to detect the client has reduced motion enabled.
By applying this to the `useMotion` hook, we avoid unnecessary calculations as, when reduced motion is enabled, we can consider that no CSS Transitions/Animations should be applied.

feat(react-motion): create useReducedMotion and apply to useMotion to skip animations

---

packages/react-components/react-tags-preview/stories/TagGroup/TagGroupBestPractices.md
packages/react-components/react-tags-preview/stories/TagGroup/TagGroupDefault.stories.tsx
packages/react-components/react-tags-preview/stories/TagGroup/TagGroupDismiss.stories.tsx
packages/react-components/react-tags-preview/stories/TagGroup/TagGroupOverflow.stories.tsx
packages/react-components/react-tags-preview/stories/TagGroup/TagGroupSizes.stories.tsx

The default `Tag` is not focusable (because it should not have any action). Therefore when `TagGroup` has default `Tag` as its children, it should have `list`/`listitem` role instead of the default `toolbar` role.
- This PR added the above recommendation to best practice guide. 
- This PR also update the TagGroup stories:
1. Default/Dismiss story now has examples for both `Tag`/`InteractionTag`: 
2. Other stories are updated to use `InteractionTag` instead of `Tag`, since `Tag` needs role override.

chore(react-tags-preview): use InteractionTag for TagGroup's stories

---

change/@fluentui-react-tags-preview-ab59afeb-97d0-4574-b3c5-ba25a5a36ad0.json
packages/react-components/react-tags-preview/src/components/InteractionTagPrimary/useInteractionTagPrimaryStyles.styles.ts
packages/react-components/react-tags-preview/src/components/InteractionTagSecondary/useInteractionTagSecondaryStyles.styles.ts
packages/react-components/react-tags-preview/src/components/Tag/useTagStyles.styles.ts

Add hover/pressed style for windows high contrast on Tag/InteractionTag:
Hover dismiss icon on Tag:
| before | after |
|---| ---|
| <img width="113" alt="Screenshot 2023-08-31 at 13 42 44" src="https://github.com/microsoft/fluentui/assets/28751745/61f2d67a-2f37-491c-b75e-fbb6330f7972">| <img width="112" alt="Screenshot 2023-08-31 at 13 42 30" src="https://github.com/microsoft/fluentui/assets/28751745/4636f8d6-4035-4b7c-ac46-389cdee814ac">|
Hover InteractionTagPrimary:
| before | after |
|---| ---|
| <img width="125" alt="Screenshot 2023-08-31 at 13 31 46" src="https://github.com/microsoft/fluentui/assets/28751745/71555c23-f679-4865-a5f2-8b56b2ce33a7">| <img width="125" alt="Screenshot 2023-08-31 at 13 36 48" src="https://github.com/microsoft/fluentui/assets/28751745/2546bda7-afca-439b-8680 …

fix(react-tags-preview): add hover/pressed style for windows high contrast

---

.gitignore
package.json
yarn.lock

1. adds dependency to `swc-plugin-de-indent-template-literal` to strip indentation from template literals on build time
2. adds `.swc` cache folder to `.gitignore`
- Fixes #

chore: adds swc-plugin-de-indent-template-literal

---

packages/utilities/src/shadowDom/MergeStylesShadowRootContext.tsx

Focus rect styles are not applied to Fluent components within shadow doms
Added FocusRectProvider within MergeStylesShadowRootProvider.
https://github.com/spmonahan/fluentui/assets/69223766/0bc21347-1dd8-4e28-b76a-f644b916c68d
https://github.com/microsoft/fluentui/issues/28061

Add focus rect support in shadow dom

---

change/@fluentui-react-dialog-381cb78f-7833-41d3-a50e-d833a6089087.json
change/@fluentui-react-tree-b35c76a9-4797-4f32-b17e-e1f739b4f84d.json
change/@fluentui-react-utilities-710d0021-32c0-4b8c-8faa-04832a854ee8.json
packages/react-components/react-dialog/.swcrc
packages/react-components/react-dialog/src/components/Dialog/useDialog.ts
packages/react-components/react-dialog/src/utils/useFocusFirstElement.ts
packages/react-components/react-tree/.swcrc
packages/react-components/react-tree/src/components/FlatTree/useFlatControllableCheckedItems.ts
packages/react-components/react-tree/src/hooks/useRootTree.ts
packages/react-components/react-tree/src/utils/createHeadlessTree.ts
packages/react-components/react-utilities/.swcrc
packages/react-components/react-utilities/src/compose/assertSlots.ts
packages/react-components/react-utilities/src/compose/slot.ts
packages/react-components/react-utilities/src/hooks/useControllableState.test.ts
packages/react-components/react-utilities/src/hooks/useControllableState.ts
packages/react-components/react-utilities/src/ssr/SSRContext.tsx
packages/react-components/react-utilities/src/utils/getReactCallbackName.ts

1. adds `swc-plugin-de-indent-template-literal` to build for:
-  `@fluentui/react-dialog`
- `@fluentui/react-tree`
- `@fluentui/react-utilities`
2. improves logging
- Fixes #

chore: use swc-plugin-de-indent-template-literal for consoles

---

change/@fluentui-react-drawer-c5be950c-8d8e-4cae-8837-d0b0c22b26dc.json
packages/react-components/react-drawer/src/components/Drawer/Drawer.cy.tsx
packages/react-components/react-drawer/src/components/DrawerBody/DrawerBody.cy.tsx
packages/react-components/react-drawer/src/components/DrawerFooter/DrawerFooter.cy.tsx
packages/react-components/react-drawer/src/components/DrawerHeader/DrawerHeader.cy.tsx
packages/react-components/react-drawer/src/components/DrawerHeaderNavigation/DrawerHeaderNavigation.cy.tsx
packages/react-components/react-drawer/src/components/DrawerHeaderTitle/DrawerHeaderTitle.cy.tsx

Add E2E Cypress tests for drawer subcomponents

test(react-drawer): add render tests for drawer subcomponents

---

change/@fluentui-react-drawer-93fb2624-7aa8-4c3a-9333-635dcac41292.json
packages/react-components/react-drawer/etc/react-drawer.api.md
packages/react-components/react-drawer/src/components/DrawerHeaderTitle/DrawerHeaderTitle.types.ts
packages/react-components/react-drawer/src/components/DrawerHeaderTitle/useDrawerHeaderTitle.ts
packages/react-components/react-drawer/stories/Drawer/DrawerWithTitle.stories.tsx
packages/react-components/react-drawer/stories/Drawer/index.stories.tsx

This is a simple refactor of the `DrawerHeaderTitle` to remove Dialog dependencies.
To make the component more lightweight and simpler to reason about.
We were relying on `DialogTitle` to make `DrawerHeaderTitle`.
We now create all the slots with dependency free. This makes it easier to create the component state.
_Note: The styles are still using the `useDialogTitleStyles`, as we want the same styling to be applied._

refactor(react-drawer): change DrawerHeaderTitle slot creation while keeping the same API

---

packages/react-components/react-storybook-addon/etc/react-storybook-addon.api.md
packages/react-components/react-storybook-addon/src/constants.ts
packages/react-components/react-storybook-addon/src/preset/preview.ts

It was not possible to set a theme in story iframe.
When a theme is set in Canvas view, it is written to the URL:
Opening the story in an iframe view keeps the theme information in URL and renders the story with the expected theme:
Due to Storybook internals, the theme information in URL is not preserved when navigating between components in docs view.
List of valid theme args:
```
globals=storybook_fluentui-react-addon_theme:web-light
globals=storybook_fluentui-react-addon_theme:web-dark
globals=storybook_fluentui-react-addon_theme:teams-light
globals=storybook_fluentui-react-addon_theme:teams-dark
globals=storybook_fluentui-react-addon_theme:teams-high-contrast
```
With the correct URL, it is now possible to open the iframe stories in any theme in the production docsite.

chore(storybook): Add theme to URL

---

change/@fluentui-react-utilities-3d0f8452-1cf1-433e-9c40-cfdaae09343b.json
packages/react-components/react-utilities/src/hooks/useOnScrollOutside.test.ts
packages/react-components/react-utilities/src/hooks/useOnScrollOutside.ts

#28964 tries to add `Event` into the callback type: from `callback: (ev: MouseEvent | TouchEvent) => void` to `callback: (ev: Event | MouseEvent | TouchEvent) => void`. But it can be a breaking change and potentially block fluent ui upgrade (see this [comment on the original PR](https://github.com/microsoft/fluentui/pull/28964/files#r1310506314))
This PR resolves the same issue using type cast. It's not perfect, but not the worst. 
I plan to take the original PR to tech sync and discuss the typing issue there.

fix(react-utilities): drag scrollbar should invoke callback in `useOnScrollOutside` with event type cast

---

packages/react-components/react-datepicker-compat/stories/DatePicker/DatePickerDateBoundaries.stories.tsx
packages/react-components/react-datepicker-compat/stories/DatePicker/DatePickerErrorHandling.stories.tsx

Date shown on the input box is not correct, which is one month earlier. 
- Fixes #29070

fix(date-picker): fix month display on date-picker stories

---

change/@fluentui-react-toast-dc9d3ea5-c361-420b-ae74-a27cc995e694.json
packages/react-components/react-toast/etc/react-toast.api.md
packages/react-components/react-toast/src/components/Toaster/Toaster.types.ts
packages/react-components/react-toast/src/components/Toaster/renderToaster.tsx
packages/react-components/react-toast/src/components/Toaster/useToaster.tsx
packages/react-components/react-toast/src/components/Toaster/useToasterStyles.styles.ts
packages/react-components/react-toast/src/state/constants.ts
packages/react-components/react-toast/src/state/types.ts
packages/react-components/react-toast/src/state/vanilla/getPositionStyles.ts
packages/react-components/react-toast/stories/Toast/Offset.stories.tsx
packages/react-components/react-toast/stories/Toast/ToastPositions.stories.tsx

Adds `top` and `bottom` potision for toasts so that they are centre aligned with the viewport
Fixes #29077

feat: Add center aligned positions for Toast

---

packages/react-components/react-table/stories/Table/Virtualization.stories.tsx

Hoists the renderer in the virtualization example for the `Table` so that it is stable between renderes.
Fixes #28598

docs: Update virtualization docs to hoist renderer

---

change/@fluentui-react-components-1ad3aa57-1ce9-452a-9bf1-c63b715c3371.json
change/@fluentui-react-tree-275dcd5a-6c13-4b74-8bc7-38031fbca1c2.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts
packages/react-components/react-tree/etc/react-tree.api.md
packages/react-components/react-tree/src/components/Tree/Tree.cy.tsx
packages/react-components/react-tree/src/components/TreeItem/TreeItem.test.tsx
packages/react-components/react-tree/src/components/TreeItem/TreeItem.types.ts
packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx
packages/react-components/react-tree/src/contexts/treeContext.ts
packages/react-components/react-tree/src/hooks/useSubtree.ts
packages/react-components/react-tree/src/index.ts
packages/react-components/react-tree/stories/Tree/OpenItemControlled.stories.tsx
packages/react-components/react-tree/stories/Tree/index.stories.tsx

1. Allows control of open state per tree item
2. adds story on the new control case for nested tree
3. adds cypress test on the new control case for the nested tree
1. update `useHeadlessFlatTree` hook to support controlling the open state of a single tree item (perhaps a `useHeadlessFlatTreeItem` hook?)

feat: react-tree allows control of individual tree item open state

---

change/@fluentui-react-toast-4eae7e9f-93a7-4029-9e40-b47e89a6d12c.json
packages/react-components/react-toast/etc/react-toast.api.md
packages/react-components/react-toast/src/components/Toast/Toast.cy.tsx
packages/react-components/react-toast/src/components/Toaster/Toaster.types.ts
packages/react-components/react-toast/src/components/Toaster/renderToaster.tsx
packages/react-components/react-toast/src/components/Toaster/useToaster.tsx
packages/react-components/react-toast/src/components/Toaster/useToasterStyles.styles.ts
packages/react-components/react-toast/src/state/vanilla/getPositionStyles.test.ts
packages/react-components/react-toast/src/state/vanilla/getPositionStyles.ts
packages/react-components/react-toast/stories/Toast/Inline.stories.tsx
packages/react-components/react-toast/stories/Toast/index.stories.tsx

Adds the `inline` prop to the Toaster. This will render the toasts in DOM order instead of in a portal.
The positioning of the toasts will be relative to the closest positioned ancestor.
Fixes #29078

feat(Toaster): Adds `inline` prop

---

change/@fluentui-react-breadcrumb-preview-3e3c117d-535c-4eb4-8b75-7c46c919bc35.json
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbButton/useBreadcrumbButtonStyles.styles.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/useBreadcrumbItemStyles.styles.ts

Fix icon spacing in Breadcrumb

Fix Breadcrumb icon spacing

---

change/@fluentui-react-popover-a88a6d1a-e63c-4c03-8d58-35b1065c4396.json
change/@fluentui-react-tabster-74dae66a-2abe-42d2-87f7-515c21ea4a3e.json
packages/react-components/react-popover/src/components/Popover/Popover.cy.tsx
packages/react-components/react-popover/src/components/PopoverSurface/__snapshots__/PopoverSurface.test.tsx.snap
packages/react-components/react-popover/src/components/PopoverSurface/usePopoverSurface.ts
packages/react-components/react-tabster/src/hooks/useModalAttributes.ts

Follow up from #28613. Not applying any of the `useModalAttributes()` resulted in focus restoration not working for popovers that don't trap focus.
Now the modalizer attributes are handled from the `useModalAttributes()` hook. This way the popover will still apply the focus restoration attributes if there is no focus trap configured.

fix: don't apply modalizer attributes when focus trap isn't configured

---

change/@fluentui-react-button-7a5e0b20-4573-4154-a184-aea484f0a7b1.json
packages/react-components/react-button/src/components/Button/useButtonStyles.styles.ts

- changes hover style colors in HCM from `canvas` to `Highlight`
- Fixes #28546

fix(react-button): subtle mode hover style now visible in windows HCM

---

change/@fluentui-react-charting-ebb094dd-b52c-43f1-b604-00481d4733c0.json
packages/react-charting/src/components/DonutChart/DonutChart.base.tsx
packages/react-charting/src/components/DonutChart/DonutChart.test.tsx
packages/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap
packages/react-charting/src/components/DonutChart/__snapshots__/DonutChartRTL.test.tsx.snap

The colors in Donut and Legends don't match
Show the same palette color for item in Donut and Legends
https://github.com/microsoft/fluentui/issues/29018
- Change logic to add default paletter colors for empty dataChart props

Fix unmatch colors when props in IChartData is empty

---

packages/react-components/react-tooltip/stories/Tooltip/TooltipIcon.stories.tsx

Screen reader reads out the content of the tooltip three times.
Screen reader now reads out only one time the content. The example now uses the relationship prop in tooltip rather than applying the aria-labelledby.

fix(react-tooltip): Tooltip example should rely on relationship, not aria-labelledby

---

change/@fluentui-react-jsx-runtime-0290dc47-fd60-47c7-bc75-6d55b6beb5e6.json
scripts/tasks/src/swc.ts

We started to use new JSX pragma via comments, for example:
https://github.com/microsoft/fluentui/blob/3bf2de945735d2464b4aa4fcfccbf636a74651ef/packages/react-components/react-image/src/components/Image/renderImage.tsx#L1-L2
The problem is that these comments appeared in our artifacts:
```js
/** @jsxRuntime automatic */
/** @jsxImportSource @fluentui/react-jsx-runtime */
import { jsx as _jsx } from "@fluentui/react-jsx-runtime/jsx-runtime";
```
> https://unpkg.com/browse/@fluentui/react-image@9.1.31/lib/components/Image/renderImage.js
And it causes issues if Babel is used on `node_modules`, see https://github.com/microsoft/fluentui/issues/29126#issuecomment-1718931582
These comments are removed during build. No comments => no problems.
**Note: I haven't checked if sourcemaps still work …

fix: strip comments for JSX pragma

---

.github/CODEOWNERS

This PR adds cxe-red and cxe-coastal as owners of the mdl2-branded package to the codeowners file.

chore: Adding cxe-red and cxe-coastal as owners of mdl2-branded package

---

change/@fluentui-react-tree-fb4c3a51-f9a9-404f-afa0-ae81c66b53e9.json
packages/react-components/react-tree/src/components/FlatTree/useHeadlessFlatTree.ts
packages/react-components/react-tree/src/components/Tree/useTree.ts
packages/react-components/react-tree/src/utils/createHTMLElementWalker.ts

Removes usage of global document from `@fluentui/react-tree`
- Fixes #

chore: stop using global document on HTMLElementWalker

---

packages/react-components/react-tags-preview/stories/InteractionTag/InteractionTagHasPrimaryAction.stories.tsx
packages/react-components/react-tags-preview/stories/TagGroup/TagGroupOverflow.stories.tsx

1. add aria-hidden to TagGroup overflow story:
| Before  |  After |   
|---|---| 
|  <img width="1383" alt="image" src="https://github.com/microsoft/fluentui/assets/28751745/71f25b46-6496-487c-81b2-ccd6de86ee04"> duplicated info in a11y name, coming from avatar and tag itself  | <img width="735" alt="Screenshot 2023-09-07 at 10 50 38" src="https://github.com/microsoft/fluentui/assets/28751745/0a008938-7669-4403-808a-891f0a96dcd7"> no duplicated info  |    
2. add `TrapFocus` to InteractionTag with popover story because the popover has focusable inside:

chore(react-tags-preview): tiny fixes to make stories more accessible

---

change/@fluentui-react-motion-preview-cdbabe91-7514-4972-b59d-765ef9dc2c82.json
packages/react-components/react-motion-preview/src/hooks/useMotion.ts

Remove the dependencies that were triggering unwanted rerenders.
- Fixes #29134

fix(react-motion): only rerun hook for the dependencies triggered by parent components

---

change/@fluentui-react-drawer-77aea511-a69a-483b-9bf8-8f6be630ece6.json
packages/react-components/react-drawer/src/components/Drawer/Drawer.types.ts
packages/react-components/react-drawer/src/components/DrawerHeaderTitle/useDrawerHeaderTitle.ts

DrawerHeaderTitle would render the heading element (h2) without any id by default.
In case the DrawerHeaderTitle renders inside a DrawerOverlay, it'll get the id from the Dialog and add to the heading element. This is used for accessibility when narrating the Dialog element created by the Drawer.

fix(react-drawer): use dialog id for drawer title heading element

---

change/@fluentui-react-components-57399e77-0cc7-4a9b-ab6e-0e4c3f117c87.json
change/@fluentui-react-dialog-759f95da-5eb2-47a5-b653-5e1f74b53164.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts
packages/react-components/react-dialog/etc/react-dialog.api.md
packages/react-components/react-dialog/src/index.ts

1. exports hooks, providers and types to access internal contexts from `Dialog` and `DialogSurface`
- Fixes https://github.com/microsoft/fluentui/issues/28806

feat(react-dialog): exports contexts

---

change/@fluentui-react-tags-preview-a76c8ca9-7dd9-415d-b1d5-33e335a81b4c.json
packages/react-components/react-tags-preview/src/components/Tag/useTag.test.tsx
packages/react-components/react-tags-preview/src/components/Tag/useTag.tsx

By default Tag is a non-focusable `span`, and when it's dismissible it's a focusable `button`. 
For the default non-focusable Tag, both Voice Over + Safari and NVDA + Chrome announces "clickable" because it has a onClick handler that does nothing:
This PR adds onClick handler only when Tag is dismissible to prevent screen readers announce 'clickable'.

fix(react-tags-preview): remove onClick handler for non-dismissible Tag

---

change/@fluentui-react-tree-8a0b1f0e-38a0-4010-a3f4-4c8f6dd52a21.json
packages/react-components/react-tree/etc/react-tree.api.md
packages/react-components/react-tree/src/components/FlatTree/useFlatTree.ts
packages/react-components/react-tree/src/components/Tree/useTree.ts
packages/react-components/react-tree/src/components/Tree/useTreeContextValues.ts
packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx
packages/react-components/react-tree/src/contexts/treeContext.ts
packages/react-components/react-tree/src/hooks/useRootTree.ts
packages/react-components/react-tree/src/hooks/useSubtree.ts

1. adds `treeType` to tree context, allowing to internally identify if a tree is `nested` or `flat`. This will help to console warn the user in the case a property is missing on some specific scenarios.
- Fixes #

feat: adds treeType to tree context

---

change/@fluentui-react-dialog-baaa6fee-9c38-4506-9fb4-0cfddb5bd658.json
packages/react-components/react-dialog/src/utils/useFocusFirstElement.ts

1. `useFocusFirstElement` would warn if no focusable element is available in any environment but `production`
1. `useFocusFirstElement` warns if no focusable element is available in `development` environment only
As requested by https://github.com/microsoft/fluentui/issues/28209#issuecomment-1727308271

chore: useFocusFirstElement warns only in development

---

azure-pipelines.hotfix.yml

We need to prove our pipelines use compliant tooling. To not accidentally publish and allow for testing changes, this boolean can help us run the pipeline wihtout accidentally pushing changes.

Add testrun parameter to hotfix pipeline

---

packages/react-components/react-dialog/stories/Dialog/DialogNonModal.md

1. removes from documentation citation of `noTrapFocus` property
2. removes from documentation the addition of a global listener
3. adds to documention a note about `Escape` key press
- Fixes https://github.com/microsoft/fluentui/issues/28928

doc(react-dialog): updates non-modal dialog documentation

---

change/@fluentui-react-dialog-39510a22-5d1b-4d26-8492-07fa341c4332.json
packages/react-components/react-dialog/src/components/Dialog/Dialog.types.ts
packages/react-components/react-dialog/stories/Dialog/DialogAlert.md

1. Follow up on https://github.com/microsoft/fluentui/pull/28276#issuecomment-1728200141
* This change is due to [WAI-ARIA alertdialog pattern](https://www.w3.org/WAI/ARIA/apg/patterns/alertdialog/)  compliance. You should always be able to close a dialog by pressing the `Escape` button.
2. Updates documentation on alert dialogs
- Fixes #

doc(react-dialog): updates documentation on alert dialog escape dismiss

---

change/@fluentui-react-dialog-864397b3-e850-464f-b5f2-ae89863fed07.json
packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurfaceStyles.styles.ts

1. adds [CSS containment](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment) to `DialogSurface` styles
- Fixes https://github.com/microsoft/fluentui/issues/28612

chore(react-dialog): adds CSS containment to DialogSurface

---

apps/public-docsite-v9/src/Concepts/Slots/Slots.stories.mdx
tools/workspace-plugin/src/generators/react-component/files/component/render__componentName__.tsx__tmpl__

react-component generator render method uses the classic runtime
1. adopts automatic runtime
- Fixes #

chore: updates render method generator of react-component to use automatic runtime

---

change/@fluentui-react-provider-620bbb7d-bbdd-4ab0-b360-c0283c23c7b4.json
change/@fluentui-react-shared-contexts-ab1a52cd-3b1c-4cac-8bac-4d209e594002.json
change/@fluentui-react-tags-preview-4b267c6e-2f04-4b1a-b1c8-d4d528449128.json
packages/react-components/react-provider/etc/react-provider.api.md
packages/react-components/react-shared-contexts/etc/react-shared-contexts.api.md
packages/react-components/react-shared-contexts/src/CustomStyleHooksContext/CustomStyleHooksContext.ts
packages/react-components/react-tags-preview/src/components/InteractionTag/InteractionTag.tsx
packages/react-components/react-tags-preview/src/components/InteractionTagPrimary/InteractionTagPrimary.tsx
packages/react-components/react-tags-preview/src/components/InteractionTagSecondary/InteractionTagSecondary.tsx
packages/react-components/react-tags-preview/src/components/Tag/Tag.tsx
packages/react-components/react-tags-preview/src/components/TagGroup/TagGroup.tsx

fix #29223.
Add useCustomStyleHook_unstable to all components: InteractionTag/InteractionTagPrimary/InteractionTagSecondary, Tag, TagGroup

feat(react-tags-preview): add useCustomStyleHook_unstable to all components

---

packages/react-components/react-timepicker-compat-preview/etc/react-timepicker-compat-preview.api.md
packages/react-components/react-timepicker-compat-preview/src/TimePicker.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.test.tsx
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.tsx
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.types.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/index.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/renderTimePicker.tsx
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/useTimePicker.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/useTimePickerStyles.styles.ts
packages/react-components/react-timepicker-compat-preview/src/index.ts
packages/react-components/react-timepicker-compat-preview/stories/TimePicker/TimePickerBestPractices.md
packages/react-components/react-timepicker-compat-preview/stories/TimePicker/TimePickerDefault.stories.tsx
packages/react-components/react-timepicker-compat-preview/stories/TimePicker/index.stories.tsx

Add TimePicker component to @fluentui/react-timepicker-compat-preview using `yarn create-component`

chore(react-timepicker): scaffolding TimePicker component from template

---

change/@fluentui-react-drawer-d5851106-2615-4746-aac1-931d5e1b69f3.json
packages/react-components/react-drawer/etc/react-drawer.api.md
packages/react-components/react-drawer/src/components/DrawerOverlay/DrawerOverlay.types.ts
packages/react-components/react-drawer/src/components/DrawerOverlay/renderDrawerOverlay.tsx
packages/react-components/react-drawer/src/components/DrawerOverlay/useDrawerOverlay.ts
packages/react-components/react-drawer/src/components/DrawerOverlay/useDrawerOverlayStyles.styles.ts

`<Dialog>` was a fixed React node.
Create Dialog from slot allowing overrides.

feat(react-drawer): add support to override Dialog as slot

---

.github/CODEOWNERS

The cxe-coastal team is being merged into the cxe-red team. This updates CODEOWNERS to replace cxe-coastal entries with cxe-red.
Related:
* #29249

Replace cxe-coastal with cxe-red in codeowners

---

change/@fluentui-react-drawer-1ce8b229-ee2d-4271-87fa-317811ba7a89.json
packages/react-components/react-drawer/etc/react-drawer.api.md
packages/react-components/react-drawer/src/components/DrawerInline/useDrawerInline.ts
packages/react-components/react-drawer/src/components/DrawerOverlay/DrawerOverlay.types.ts
packages/react-components/react-drawer/src/components/DrawerOverlay/useDrawerOverlay.ts
packages/react-components/react-drawer/src/shared/DrawerBase.types.ts
packages/react-components/react-drawer/src/shared/useDrawerDefaultProps.ts

The DrawerInline had defaultOpen and open to have the same API as the DrawerOverlay, but that was unnecessary as defaultOpen was never used.
Removes defaultOpen as it had no effect.

fix(react-drawer): remove defaultOpen from DrawerInline as it had no effect

---

change/@fluentui-react-drawer-30e2677b-918d-444b-b5f3-aca797ecc5ed.json
packages/react-components/react-drawer/src/components/DrawerHeaderTitle/useDrawerHeaderTitle.ts

The Drawer was creating the title to fetch the generated id, as the dialog context was not exported by the react-dialog package.
Now that the dialog context is available publicly, it is now using the context to fetch the generated dialog id.

fix(react-drawer): use context to fetch dialog id

---

change/@fluentui-react-tags-preview-3da108b0-6f55-4670-b217-734d56287fbb.json
packages/react-components/react-tags-preview/src/components/InteractionTagPrimary/useInteractionTagPrimaryStyles.styles.ts
packages/react-components/react-tags-preview/src/components/InteractionTagSecondary/useInteractionTagSecondaryStyles.styles.ts

fix #29224.
PR #29035 added WHCM background color on hover to InteractionTag, increasing its contrast. However it changed disabled InteractionTag as well. 
This PR removes hover background for disabled InteractionTag, and keep the hover background only for normal InteractionTag.
Before:
After (no hover style):
Normal InteractionTag stays the same:

fix(react-tags-preview): remove disabled InteractionTag hover color under WHCM

---

change/@fluentui-react-card-2e76b5b0-5eb0-4302-8ff2-19391b355451.json
packages/react-components/react-card/src/components/Card/useCardSelectable.ts

Selectable cards were not using controllable state to sync the selected, defaultSelected and onChange handlers
Use controllable state to sync all props
- Fixes #29202

fix(react-card): sync controllable state for selectable cards

---

change/@fluentui-react-tree-a0c03a32-7116-4e69-9da0-e5d936c3f433.json
packages/react-components/react-tree/etc/react-tree.api.md
packages/react-components/react-tree/src/components/FlatTree/useFlatTree.ts
packages/react-components/react-tree/src/components/FlatTree/useFlatTreeNavigation.ts
packages/react-components/react-tree/src/components/FlatTree/useHeadlessFlatTree.ts
packages/react-components/react-tree/src/components/Tree/Tree.types.ts
packages/react-components/react-tree/src/components/Tree/useTree.ts
packages/react-components/react-tree/src/components/TreeItem/TreeItem.types.ts
packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx
packages/react-components/react-tree/src/contexts/treeContext.ts
packages/react-components/react-tree/src/hooks/useRootTree.ts
packages/react-components/react-tree/src/utils/createHeadlessTree.ts
packages/react-components/react-tree/stories/Tree/FlatTree.stories.tsx
packages/react-components/react-tree/stories/Tree/UseHeadlessFlatTree.stories.tsx
packages/react-components/react-tree/stories/Tree/Virtualization.stories.tsx
packages/react-components/react-tree/stories/Tree/index.stories.tsx

1. implements navigation on `FlatTree` component
2. implements opt-out mechanism to internal navigation
* to opt-out prevent default on the event that causes navigation
3. adds story for using `FlatTree` without `useHeadlessFlatTree`

feat(react-tree): flat tree supports navigation without `useHeadlessFlatTree`

---

change/@fluentui-react-tabster-1c26ce6a-008b-4296-8065-b09240c6b9ed.json
packages/react-components/react-tabster/etc/react-tabster.api.md
packages/react-components/react-tabster/src/focus/constants.ts
packages/react-components/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts
packages/react-components/react-tabster/src/focus/createFocusOutlineStyle.ts

At the moment there's no way to modify the selector internally used to indicate if an element is focused.
1. adds a `customizeSelector` method to allow the customization of the selector of focus styles
This allows the customization of  the selector, allowing ,for example, the possibility of selecting a different element on the focusing of a given element.
This is useful for the use case of `TreeItem` and `TreeItemLayout`, where the focused element will be the `TreeItem` but the outline would be better positioned if it was visible relative to the `TreeItemLayout` element inside of `TreeItem`

feat(react-tabster): adds `customizeSelector` to `createCustomFocusIndicatorStyle` method

---

change/@fluentui-react-tags-preview-442e431d-b76d-4fec-8243-1737653ffaaf.json
packages/react-components/react-tags-preview/package.json
packages/react-components/react-tags-preview/src/components/InteractionTagPrimary/InteractionTagPrimary.types.ts
packages/react-components/react-tags-preview/src/components/Tag/Tag.types.ts

update props descriptions and description in package.json

chore(react-tags-preview): update props descriptions

---

change/@fluentui-react-dialog-236fd9b3-5e8c-4368-b43b-7e2aca221162.json
packages/react-components/react-dialog/src/components/DialogActions/useDialogActionsStyles.styles.ts
packages/react-components/react-dialog/src/components/DialogBody/useDialogBodyStyles.styles.ts
packages/react-components/react-dialog/src/components/DialogContent/useDialogContentStyles.styles.ts
packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurfaceStyles.styles.ts
packages/react-components/react-dialog/src/components/DialogTitle/useDialogTitle.tsx
packages/react-components/react-dialog/src/components/DialogTitle/useDialogTitleStyles.styles.ts

Please note that this is a bugfix that was causing the `Drawer` component to render 80+ classNames for the root element.
For more context, please refer to:
- https://github.com/microsoft/fluentui/issues/29205
- https://github.com/microsoft/fluentui/pull/29263
react-dialog base components had styles created using `makeStyles`, which generate atomic classnames. That can lead to performance issues when the element has several classnames.
react-dialog now uses `makeResetStyles` to create the base styles, which creates only one className.

fix(react-dialog): use makeResetStyles for base dialog components styles

---

packages/react-examples/src/react-charting/HorizontalBarChart/HorizontalBarChart.Basic.Example.tsx
packages/react-examples/src/react-charting/HorizontalBarChart/HorizontalBarChart.Benchmark.Example.tsx
packages/react-examples/src/react-charting/HorizontalBarChart/HorizontalBarChart.CustomAccessibility.Example.tsx
packages/react-examples/src/react-charting/HorizontalBarChart/HorizontalBarChart.CustomCallout.Example.tsx
packages/react-examples/src/react-charting/HorizontalBarChart/HorizontalBarChart.Variant.Example.tsx

Reflow is not visible in horizontal bar chart examples due to their fixed width. 
Horizontal bar chart examples have a maximum width of 600px and will shrink with their container.

Remove width prop from horizontal bar chart examples

---

change/@fluentui-react-jsx-runtime-12e3e0e7-c40c-4618-9cde-9b9900895d86.json
packages/react-components/react-jsx-runtime/src/jsx/createJSX.ts

PR https://github.com/microsoft/fluentui/pull/29162 forgets to provide `source` and `self` parameters to the actual react runtime invocation 
https://github.com/microsoft/fluentui/blob/031ecaf9c383f81965aa5d057cd779f222a6d10a/packages/react-components/react-jsx-runtime/src/jsx/createJSX.ts#L24
This is not a problem in production, as those 2 parameters are only available in development, but missing them in development will cause erroneous error messages regarding static vs dynamic runtime.
1. provides `source` and `self` parameters to the react runtime.
- Fixes #

bugfix(react-jsx-runtime): react dev runtime call is missing source parameter

---

scripts/beachball/package.json
scripts/beachball/register.js
scripts/beachball/release-v8.config.js
scripts/beachball/release-vNext.config.js
scripts/ts-node/register.js

release pipeline doesn't work
- tsc is used only in transpilation mode to unblock release
- refactored ts-node calls within scripts-beachball
- Follows https://github.com/microsoft/fluentui/pull/29253

fix(scripts-ts-node): disable ts checks when invoking ts-node/register untill swc works

---

.devops/templates/tools.yml

nodeTool@0 became extremely flaky in last 3 months, more than 70% of pipeline runs because node install errors
based on [their issue board](https://github.com/microsoft/azure-pipelines-tasks/issues/17787#issuecomment-1545752409) I discovered that there is a new [`useNode@1`](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-node-v1?view=azure-pipelines) which should be more stable
- Fixes #

ci: switch to UseNode@1 from nodeTool@0 to avoid flaky node installs

---

.github/workflows/check-packages.yml
package.json

finding how to dedupe deps is not the best DX at the moment
deduping via 3rd party packages in now aliased under `yarn run dedupe` npm script alias. 
> NOTE:  `run` needs to be used explicitly as yarn v1 ships `dedupe` command ( which doesnt work as it should )
- Fixes #

ci: use custom yarn dedupe alias for local and ci dx

---

change/@fluentui-react-breadcrumb-preview-0301b962-b42e-4817-bf07-a23daeb8eaa5.json
packages/react-components/react-breadcrumb-preview/etc/react-breadcrumb-preview.api.md
packages/react-components/react-breadcrumb-preview/src/components/Breadcrumb/index.ts
packages/react-components/react-breadcrumb-preview/src/index.ts

- BreadcrumbContext wasn't exported
BreadcrumbProvider and useBreadcrumbContext are now exported
- Fixes #29259

fix: exported BreadcrumbProvider and useBreadcrumbContext

---

change/@fluentui-react-tags-preview-08da3434-ae29-4b7c-b48e-6fa0cf8a4637.json
packages/react-components/react-tags-preview/etc/react-tags-preview.api.md
packages/react-components/react-tags-preview/src/components/InteractionTag/useInteractionTag.tsx
packages/react-components/react-tags-preview/src/components/InteractionTagPrimary/useInteractionTagPrimary.ts
packages/react-components/react-tags-preview/src/components/InteractionTagSecondary/useInteractionTagSecondary.tsx
packages/react-components/react-tags-preview/src/components/Tag/useTag.tsx
packages/react-components/react-tags-preview/src/components/TagGroup/useTagGroup.ts

Update ref typing in state hook from the default `React.Ref<HTMLElement>` from template, to proper type

chore(react-tags-preview): properly type ref in state hook

---

change/@fluentui-react-d265a3da-39e3-4b9d-be1e-b0ed8a0ee1d5.json
packages/react/src/components/Stack/Stack.tsx

Values such as strings that aren't elements were not rendered when using the doNotRenderFalsyValues flag due to getting the same treatment as falsy values.
Values like the ones said before are now rendered regardless of the doNotRenderFalsyValues flag.
- Fixes #29289

fix(Stack): Allow rendering of values that aren't falsy elements and aren't valid elements

---

scripts/cypress/src/base.config.ts

Cypress test config previously did not use TsConfigPathsPlugin so it relied on code being built in CI. This is a similar approach to our storybook config
However there is an edge case encountered in #29313. Lage will run the cypress tests of depednencies which *_can depend on depedencies not in the package.json tree_* 💣💣
```
- react-message-bar-preview
- react-button
- react-tabster
- react-provider (not in package.json, but used in cypress test)
```

chore: use TsconfigPathsPlugin in cypress test config

---

change/@fluentui-utilities-2c559317-d528-4f32-8c1a-0ad2f000dc12.json
packages/utilities/src/focus.ts

This came up while helping a partner debug why focus wasn't entering `ContextualMenu` after closing & re-opening an email window. It turns out that the current implementation of `focusAsync` fails to call focus if a previous call of `focusAsync` set `targetToFocusOnNextRepaint` but didn't run `win.requestAnimationFrame` (e.g. because the window closed).
By saving the `requestAnimationFrame` and cancelling prior ids on subsequent same-animation-frame calls, we can ensure that a past not-run `focusAsync` does not prevent future focus calls.

fix: focusAsync still works even if past animationFrame fails to run

---

change/@fluentui-react-components-c4eb2fca-e103-4a84-a1b9-1e1b6273a8f8.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts

Re-exports `useFluentProviderThemeStyleTag` as public APIs should be reachable through `@fluentui/react-components`.

feat: re-export useFluentProviderThemeStyleTag

---

change/@fluentui-react-breadcrumb-preview-7e339c0f-d934-42c0-b2a7-6fb8d5459508.json
change/@fluentui-react-provider-b480c3d3-5c89-4560-a945-758668b5a2f1.json
change/@fluentui-react-shared-contexts-f0edee23-7871-47c5-b75b-1b7ba839e5df.json
packages/react-components/react-breadcrumb-preview/src/components/Breadcrumb/Breadcrumb.tsx
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbButton/BreadcrumbButton.tsx
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbDivider/BreadcrumbDivider.tsx
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/BreadcrumbItem.tsx
packages/react-components/react-provider/etc/react-provider.api.md
packages/react-components/react-shared-contexts/etc/react-shared-contexts.api.md
packages/react-components/react-shared-contexts/src/CustomStyleHooksContext/CustomStyleHooksContext.ts

None of Breadcrumb components contained custom styling hooks
Added custom styling hooks for Breadcrumb component and its sub-components
- Fixes #29257

feat(react-breadcrumb) add custom styling hooks for Breadcrumb component and its sub-components

---

change/@fluentui-react-f555a49c-e785-477a-81a4-2535a41d0724.json
packages/react/etc/react.api.md
packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx
packages/react/src/components/ContextualMenu/ContextualMenu.types.ts
packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuAnchor.tsx
packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuButton.tsx
packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuItemWrapper.types.ts
packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.tsx

Right now, command bar and context menu items only support a shared `onRender` override, which does not supply a `defaultRender` callback to use to handle nuance in context. `ICommandBarItemProps` supports a `commandBarButtonAs`, but this only works in the main command bar and not the overflow menu or normal context menus. The `contextualMenuItemAs` is only available for the `ContextualMenu` as a whole and cannot be customized per-item. It is also not composable with its default render behavior.
Updated consumption of `contextualMenuItemAs` so that behaviors compose with a per-item behavior and with the default value. Updated the interface to use `IComponentAs`, which is backwards-compatible with the existing behavior. (The whole behavior is backwards-compatible, because existing …

Support tighter overrides for Contextual Menu Items

---

apps/public-docsite-v9/src/Concepts/Migration/FromV8/ComponentMapping.stories.mdx

[Component Mapping](https://react.fluentui.dev/?path=/docs/concepts-migration-from-v8-component-mapping--page) was out of date since we've released a few components since it was updated. 
Component Mapping page is updated and now links out to the component documentation pages. 
It also links to in progress components on our public roadmap. 
- Fixes #29345

Update Component Mapping with links and latest status

---

change/@fluentui-react-button-81475034-8645-4083-8fc7-79fcd40a45df.json
packages/react-components/react-button/src/components/SplitButton/useSplitButton.ts
packages/react-components/react-button/stories/SplitButton/SplitButtonDefault.stories.tsx

No example in our storybook showed how to pass an `onClick` callback to the `primaryActionButton` slot of the `SplitButton` component.
The `Default` story for `SplitButton` now has an example of this functionality.
- Fixes #20958.

docs: Adding example of how to pass on click to primaryActionButton slot in the Default story for SplitButton

---

change/@fluentui-react-portal-compat-89771dd5-317e-4567-a861-92ddaecdbfdd.json
packages/react-components/react-portal-compat/src/PortalCompatProvider.test.tsx
packages/react-components/react-portal-compat/src/PortalCompatProvider.tsx

`PortalCompatProvider` can handle only one `fui-FluentProvider*` class from a context.
`PortalCompatProvider` can handle multiple `fui-FluentProvider*` classes from a context. This a customer scenario when additional tokens are added with `useFluentProviderThemeStyleTag()`.

fix: handle multiple classes in PortalCompatProvider

---

change/@fluentui-react-tree-28a20b5c-2da7-46ae-9716-fe0064f96cd4.json
packages/react-components/react-tree/src/components/FlatTree/useFlatTreeStyles.styles.ts
packages/react-components/react-tree/src/components/Tree/useTreeStyles.styles.ts
packages/react-components/react-tree/src/components/TreeItem/useTreeItemStyles.styles.ts
packages/react-components/react-tree/src/components/TreeItemLayout/useTreeItemLayoutStyles.styles.ts
packages/react-components/react-tree/src/components/TreeItemPersonaLayout/useTreeItemPersonaLayoutStyles.styles.ts

1. Converts usages of `makeStyles` with `makeResetStyles` to create base style for Tree components
2. removes duplicate declaration of `expandIcon` styles on `TreeItemLayout`

chore(react-tree): replace makeStyles with makeResetStyles

---

change/@fluentui-react-components-62dd54a8-eca3-46ea-a6ba-844aea837127.json
change/@fluentui-react-utilities-23bf3f01-9fbb-4ca2-84a5-18d7839c6289.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts
packages/react-components/react-utilities/etc/react-utilities.api.md
packages/react-components/react-utilities/src/compose/getIntrinsicElementProps.ts
packages/react-components/react-utilities/src/compose/index.ts
packages/react-components/react-utilities/src/compose/types.ts
packages/react-components/react-utilities/src/index.ts

The `getNativeElementProps` has some type safety issues, allowing erroneous properties to be introduced.
1. creates a method to replace `getNativeElementProps` on slot creation (`getIntrinsicElementProps`)
- Fixes https://github.com/microsoft/fluentui/issues/29311

feat: creates getIntrinsicElementProps to replace getNativeElementProps on slots creation

---

change/@fluentui-react-tree-b5db8474-a1ba-4ec8-9c42-18215b9e2632.json
packages/react-components/react-tree/src/components/TreeItem/useTreeItemStyles.styles.ts
packages/react-components/react-tree/src/components/TreeItemLayout/useTreeItemLayoutStyles.styles.ts

Focus outline is on the `TreeItem` component as this is the actual focused component, this is a problem on nested trees as the `TreeItem` will contain inside of it a subtree with more tree items
Focus outline should be on the `TreeItemLayout` component (although the actual focus is on the `TreeItem`), this way the focus will be visually on a single element even when focusing on a tree item with other tree items inside of it.
- Fixes #

chore(react-tree): delegate focus outline to layout components

---

packages/react-components/react-message-bar-preview/etc/react-message-bar-preview.api.md
packages/react-components/react-message-bar-preview/src/components/MessageBar/MessageBar.test.tsx
packages/react-components/react-message-bar-preview/src/components/MessageBar/MessageBar.types.ts
packages/react-components/react-message-bar-preview/src/components/MessageBar/useMessageBar.ts
packages/react-components/react-message-bar-preview/src/components/MessageBar/useMessageBarContextValues.ts
packages/react-components/react-message-bar-preview/src/components/MessageBarActions/MessageBarActions.tsx
packages/react-components/react-message-bar-preview/src/components/MessageBarActions/MessageBarActions.types.ts
packages/react-components/react-message-bar-preview/src/components/MessageBarActions/renderMessageBarActions.tsx
packages/react-components/react-message-bar-preview/src/components/MessageBarActions/useMessageBarActions.ts
packages/react-components/react-message-bar-preview/src/components/MessageBarActions/useMessageBarActionsContextValues.ts
packages/react-components/react-message-bar-preview/src/components/MessageBarBody/useMessageBarBody.ts
packages/react-components/react-message-bar-preview/src/contexts/messageBarContext.ts

Integrates the shared AnnounceContext to the MessageBar. The default narration should not include the container actions which is generally the 'close' button of the message bar.
Addresses: https://github.com/microsoft/fluentui/issues/22579
Related to #29371

feat: Integrate Announce context

---

packages/react-components/react-message-bar-preview/etc/react-message-bar-preview.api.md
packages/react-components/react-message-bar-preview/src/components/MessageBar/MessageBar.types.ts
packages/react-components/react-message-bar-preview/src/components/MessageBarActions/MessageBarActions.types.ts
packages/react-components/react-message-bar-preview/src/index.ts
packages/react-components/react-message-bar-preview/stories/MessageBar/Animation.stories.tsx
packages/react-components/react-message-bar-preview/stories/MessageBar/Default.stories.tsx
packages/react-components/react-message-bar-preview/stories/MessageBar/Dismiss.stories.tsx
packages/react-components/react-message-bar-preview/stories/MessageBar/Intent.stories.tsx
packages/react-components/react-message-bar-preview/stories/MessageBar/ManualLayout.stories.tsx
packages/react-components/react-message-bar-preview/stories/MessageBar/MessageBarBestPractices.md
packages/react-components/react-message-bar-preview/stories/MessageBar/MessageBarDescription.md
packages/react-components/react-message-bar-preview/stories/MessageBar/Reflow.stories.tsx
packages/react-components/react-message-bar-preview/stories/MessageBar/index.stories.tsx

Goes through all storie and code to write user-readable documentation
Addresses #22579

docs: Initial documentation pass

---

packages/react-components/react-tags/stories/InteractionTag/index.stories.tsx
packages/react-components/react-tags/stories/Tag/index.stories.tsx
packages/react-components/react-tags/stories/TagGroup/index.stories.tsx

chore: move tag stories under components

---

packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbWithTooltip.stories.tsx

Tooltip contained BreadcrumbDivider which is `li` element.
By the design there shouldn't be Breadcrumb divider, there's just `>` symbol
- Fixes #29235

fix: changed divider in the Breadcrumb with tooltip

---

apps/public-docsite-v9/package.json
change/@fluentui-react-message-bar-preview-8ae48847-7acf-499b-a330-31d94c9ceb66.json
packages/react-components/react-message-bar-preview/package.json
packages/react-components/react-message-bar-preview/stories/MessageBar/MessageBarDescription.md

Run with `yarn nx g @fluentui/workspace-plugin:prepare-initial-release --project @fluentui/react-one-preview --phase=preview` as stated in our release process https://github.com/microsoft/fluentui/wiki/new-release-process---v9-packages
Addresses https://github.com/microsoft/fluentui/issues/22579

feat: preview release

---

packages/react-components/theme-designer/src/components/Sidebar/Form.tsx

The current theme designer only performs a single contrast ratio test which is not adequate testing, and should not be represented as such.
This PR removes the a11y test UX until a solid plan can be established and implemented with regards to tokens, tooling and accessibility.
Before:
After:

Remove a11y test ux from v9 Theme Designer

---

change/@fluentui-react-button-200fdd74-ae66-410a-a525-daefec48abaa.json
packages/react-components/react-button/src/components/Button/useButtonStyles.styles.ts

Our focus behavior on buttons causes an increase in the buttons borderWidth.
While this increase is intentional design, it overflows the bounding box and can cause overlap with other items (i.e. grids)
Should have the border width increase inset so that it ensures there is no pixels outside the components bounding box.
Border width still increase on focus, however it now uses an inset shadow box to place additional width on internal side.
- Fixes #

V9 Button Focus: Move border width increase to inset

---

change/@fluentui-react-button-d89ce90d-cbf8-4b16-9a02-2d6606cea56e.json
packages/react-components/react-button/src/components/Button/useButtonStyles.styles.ts

Hover Button component with icon and appearance="subtle" and disabled state
- Fixes #29341

fix: Icon in disabled Button shouldn't change color on hover or pressed

---

change/@fluentui-react-tree-5bf1ff30-ae1d-4a2b-9c0a-11587529003a.json
packages/react-components/react-tree/etc/react-tree.api.md
packages/react-components/react-tree/src/components/Tree/Tree.types.ts
packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx

`useTreeItem` is consuming `blur`, `focus`, `mouseout`, `mouseover` and `change` event without properly invoking it's equivalent callback handler provided by `props`
1. fix event handlers to properly call `props.on__EventHandler__` 
2. fix enter key press, it should simulate a button click
3. deprecates the usage of `onOpenchange` with the event from a Enter key press, as it'll no longer be emitted
- Fixes #

bugfix(react-tree): ensure `TreeItem` emits events properly

---

apps/vr-tests-react-components/src/stories/Positioning.stories.tsx
change/@fluentui-react-positioning-938da831-77f1-4eaa-9251-f9b1fc6c6d7a.json
packages/react-components/react-positioning/src/createPositionManager.ts
packages/react-components/react-positioning/src/utils/listScrollParents.test.ts
packages/react-components/react-positioning/src/utils/listScrollParents.ts

This PR introduces `listScrollParents` which will collect every scroll parent in DOM of both target and container.
This behaviour already existed in poppver v2 https://github.com/floating-ui/floating-ui/blob/v2.x/src/dom-utils/listScrollParents.js

fix: Consider all parents as scroll parents

---

change/@fluentui-react-breadcrumb-preview-0abc23c0-2468-4cd2-96f3-99680aafa7e4.json
packages/react-components/react-breadcrumb-preview/etc/react-breadcrumb-preview.api.md
packages/react-components/react-breadcrumb-preview/src/components/Breadcrumb/Breadcrumb.types.ts
packages/react-components/react-breadcrumb-preview/src/components/Breadcrumb/BreadcrumbContext.ts
packages/react-components/react-breadcrumb-preview/src/components/Breadcrumb/renderBreadcrumb.tsx
packages/react-components/react-breadcrumb-preview/src/components/Breadcrumb/useBreadcrumbContextValue.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbButton/useBreadcrumbButton.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/BreadcrumbItem.types.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/useBreadcrumbItem.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/useBreadcrumbItemStyles.styles.ts
packages/react-components/react-breadcrumb-preview/src/index.ts
packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbDefault.stories.tsx

It was not clear if Breadcrumb is interactive or not.
Registering items via context gives opportunity to know whether Breadcrumb is interactive or not.
It's needed for managing styling in different types of Breadcrumb.
Marcos, thank you for your help with this feature

(feat) Breadcrumb - register items via context

---

packages/react-components/react-infobutton/stories/InfoLabel/InfoLabelInField.stories.tsx

Added guidance on how to fix issue where input is rendered on top of the PopoverSurface.
|before|after|
|---|---|
|![image](https://github.com/microsoft/fluentui/assets/5953191/31fea2a8-5199-407c-9335-91ac7c6e03c3)|![image](https://github.com/microsoft/fluentui/assets/5953191/db86b558-cfd4-4b44-b1d5-d93d96464bdd)|
- Fixes #27891

docs(react-infobutton): Update Field example to show how to fix the issue where the surface is rendered behind input

---

change/@fluentui-react-charting-d116410a-f17d-45c3-bef4-a87cd431d3da.json
packages/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
packages/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap
packages/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChartRTL.test.tsx.snap

Fix overlapping bars in single group

---

change/@fluentui-react-link-a0a06b2e-a83e-44b3-b2bd-f432395554c8.json
change/@fluentui-react-tabster-97c6497b-b398-446f-b711-66f7f0a76796.json
packages/react-components/react-link/src/components/Link/useLinkStyles.styles.ts
packages/react-components/react-tabster/src/focus/createCustomFocusIndicatorStyle.ts

Link component does not add styles to remove the default outline provided by browsers
1. manually add styles to remove focus outline on `focus-visible`
2. adds comments to `createCustomFocusIndicatorStyle` to make it clear that this method does not remove the outline style
- Fixes https://github.com/microsoft/fluentui/issues/29251

chore(react-link): adds style to remove default outline style

---

change/@fluentui-react-table-ac6931c6-44ed-41a2-971c-e302cfa5d0ed.json
packages/react-components/react-table/src/hooks/useMeasureElement.ts

Instead of dropping a div to measure the container size, the measurement is now done directly on the parent element of the DataGrid
Fixes #29352

fix(useTableColumnSizing): Removes the measuring div and measures parent

---

change/@fluentui-react-charting-e365c5ce-592e-422f-9329-1bee461a0dc3.json
packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx
packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.Styled.Example.tsx

…ck to stack callout still shows the single callout
The single callout/stack callout radio button behavior is not consistent.
Going from stack callout to single callout and back to stack callout still shows the single callout.
Shows the correct callout on going back to single to stack callout
- Fixes #

Fixing the issue Going from stack callout to single callout and back to stack callout still shows the single callout

---

change/@fluentui-react-message-bar-preview-499e36e9-6912-4a07-92dc-fadbf8feebef.json
packages/react-components/react-message-bar-preview/etc/react-message-bar-preview.api.md
packages/react-components/react-message-bar-preview/src/components/MessageBar/MessageBar.test.tsx
packages/react-components/react-message-bar-preview/src/components/MessageBar/MessageBar.types.ts
packages/react-components/react-message-bar-preview/src/components/MessageBar/__snapshots__/MessageBar.test.tsx.snap
packages/react-components/react-message-bar-preview/src/components/MessageBar/useMessageBar.ts
packages/react-components/react-message-bar-preview/src/components/MessageBar/useMessageBarContextValues.ts
packages/react-components/react-message-bar-preview/src/components/MessageBarTitle/__snapshots__/MessageBarTitle.test.tsx.snap
packages/react-components/react-message-bar-preview/src/components/MessageBarTitle/useMessageBarTitle.ts
packages/react-components/react-message-bar-preview/src/contexts/messageBarContext.ts

* The entire MessageBar has role `group`
* The entire MessageBar is labelled by the MessageBarTitle
Addresses #22579

fix: screenreader narration improvements

---

change/@fluentui-react-utilities-376cc497-8a87-4b13-9138-34b3479b48e3.json
packages/react-components/react-utilities/src/hooks/useOnScrollOutside.test.ts
packages/react-components/react-utilities/src/hooks/useOnScrollOutside.ts

Revert #29062
Why revert: 
When moving focus, browser can trigger scroll event and causing unwanted popover close.
In this example https://codesandbox.io/s/nervous-bush-j9qkzw?file=/example.tsx, when Tabbing to the popover trigger, popover opens. And then tab again closes the popover, while the expected behavior is popover stays open.

Revert fix: useOnScrollOutside should invoke callback on dragging scrollbar

---

change/@fluentui-react-utilities-638b8284-f061-4808-853e-5987365c9c52.json
packages/react-components/react-utilities/src/hooks/useOnScrollOutside.cy.tsx

#29062 added scroll event listener to `useOnScrollOutside`. But it is reverted in #29412 because scroll listener triggers callback on browser-initiated scroll when focus changes, and we don't want that.
This PR adds cypress test for this scenario.

chore(react-utilities): add e2e test to useOnScrollOutside

---

scripts/generators/create-package/index.ts
tools/workspace-plugin/src/generators/react-library/schema.json

The cxe-coastal team is being merged into the cxe-red team. This removes cxe-coastal as an option to pick as a codeowner.
Related:
* #29248

Remove cxe-coastal as an option for package owner in create-package script

---

change/@fluentui-react-infobutton-b36ec3f1-5811-4e2b-ac9e-306c17c23e2e.json
packages/react-components/react-infobutton/src/components/InfoButton/useInfoButtonStyles.styles.ts

The figma calls for the popover to use a font style `Caption 1` when size is small or medium, but the style is not used.
|small|medium|
|---|---|
|![image](https://github.com/microsoft/fluentui/assets/5953191/99a8e02e-21b0-48d5-9bcd-1cef4144395b)|![image](https://github.com/microsoft/fluentui/assets/5953191/640623be-5960-44dd-b739-f4b310f4d59a)|
|small|medium|
|---|---|
|![image](https://github.com/microsoft/fluentui/assets/5953191/e09b5295-308a-4faa-bc2f-a1f0f7284e27)|![image](https://github.com/microsoft/fluentui/assets/5953191/a6683fa1-93a3-46b5-915f-254ed1789bc4)|
The `Caption 1` style is now applied to the small and medium sizes.

fix(react-infobutton): Use caption 1 when size is small or medium

---

apps/vr-tests-react-components/src/stories/MessageBar/MessageBar.stories.tsx
change/@fluentui-react-message-bar-preview-35f1856a-8956-4a81-a775-34c2100a6de2.json
packages/react-components/react-message-bar-preview/etc/react-message-bar-preview.api.md
packages/react-components/react-message-bar-preview/src/components/MessageBar/MessageBar.types.ts
packages/react-components/react-message-bar-preview/src/components/MessageBar/useMessageBar.ts
packages/react-components/react-message-bar-preview/src/components/MessageBar/useMessageBarStyles.styles.ts
packages/react-components/react-message-bar-preview/stories/MessageBar/Shapes.stories.tsx
packages/react-components/react-message-bar-preview/stories/MessageBar/index.stories.tsx

Adds the shape prop to MessageBar to support both `square` and `rounded` shapes.
Addresses #22579
Fixes #29422

feat: Add shape prop to MessageBar

---

packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbWithOverflow.stories.tsx

Overflow story had unneeded onClick events
Removed unneeded events and styling

docs: refactoring of Breadcrumb Overflow story

---

change/@fluentui-react-1fc9fcd1-41d9-4c48-8e8a-4595d6d282f5.json
packages/react/src/components/DetailsList/DetailsColumn.base.tsx
packages/react/src/components/DetailsList/DetailsList.base.tsx

When `DetailsList` is set to `fixedColumn` layout mode and columns have `flexGrow: 1` and the initial render of the `DetailsList` is wider than the viewport (i.e., browser window) column widths are never calculated. This results in a `NaN` being computed downstream, corrupting column measurements.
1. Load this Codepen: https://codepen.io/seanms/pen/MWZzbLJ
2. Resize the width of the browser window such that the list is wider than the viewport (using DevTools responsive mode is a good way to do this)
3. Refresh the page so the initial render will be at this size
`DetailsList` computes column widths in the above scenario.
[Example with the fix applied](https://codesandbox.io/s/fluentui-react-8-starter-forked-nygq4r?file=/src/index.tsx&resolutionWidth=380&resolutionHeight=675).

fix: DetailsList columns render correctly when the list is wider than viewport

---

change/@fluentui-react-table-101edd5b-5a5e-4855-830d-a0f6feca0891.json
packages/react-components/react-table/src/hooks/useMeasureElement.test.tsx
packages/react-components/react-table/src/hooks/useMeasureElement.ts

Follow up fix of #29363. There should be no element cleanup anymore since, the ref is attached to the parent.
Fixes https://github.com/microsoft/fluentui/issues/29443

fix(useMeasureElement): Should not remove parent element

---

change/@fluentui-react-menu-1c0c1294-fdc5-4546-99db-70488ce9b036.json
packages/react-components/react-menu/src/components/MenuSplitGroup/useMenuSplitGroupStyles.styles.ts

Currently the MenuSplitGroup targets any first and second elements in DOM, this can cause problems when MenuItems are wrapped in components like Tooltip which will drop an span in DOM to be a virtual parent.
Updates the selector to be `nth-of-type` so that only MenuItem children are targeted.
Fixes #29125

fix: MenuSplitGroup styles should target MenuItems

---

change/@fluentui-react-charting-fdcd995e-d8b9-4952-a4a2-2674d8757d49.json
packages/react-charting/etc/react-charting.api.md
packages/react-charting/src/components/TreeChart/TreeChart.base.tsx
packages/react-charting/src/components/TreeChart/TreeChart.types.ts
packages/react-charting/src/components/TreeChart/__snapshots__/TreeChart.test.tsx.snap
packages/react-examples/src/react-charting/TreeChart/TreeChart.ThreeLayerCompactDocSite.Example.tsx
packages/react-examples/src/react-charting/TreeChart/TreeChart.ThreeLayerDocSite.Example.tsx

Tree chart not fitting in doc site
Adding new examples for Tree chart to be added in doc site.
- Fixes #

Bug9273- change for reducing width and height for tree chart such that it fits the doc site

---

change/@fluentui-react-hooks-2a9a3785-211f-4a01-8343-0dec3306fc82.json
packages/react-examples/src/react/ShadowDOM/ShadowDOM.ChildWindow.Example.tsx
packages/react-hooks/src/useTarget.ts
packages/react/etc/react.api.md
packages/react/src/components/Layer/Layer.base.tsx
packages/react/src/components/Layer/Layer.notification.ts

Components inside a shadow root would not render their layers in the shadow root, potentially breaking layout and styles.
Components inside a shadow root render their layers in the same shadow root.
- Fixes #28060

Shadow DOM layers

---

change/@fluentui-react-message-bar-preview-a6a0acb0-3fd7-4b96-b883-fbd5711cc593.json
packages/react-components/react-message-bar-preview/src/components/MessageBar/useMessageBarStyles.styles.ts
packages/react-components/react-message-bar-preview/src/components/MessageBarActions/useMessageBarActionsStyles.styles.ts
packages/react-components/react-message-bar-preview/src/components/MessageBarBody/useMessageBarBodyStyles.styles.ts
packages/react-components/react-message-bar-preview/stories/MessageBar/Intent.stories.tsx

CSS grid can cause its own padding to overflow cells. The only way to avoid this padding collapse (that I could think of) is to handle the spacing in the grid areas directly.
Fixes #29423

fix: MessageBarActions should not overflow into grid padding

---

change/@fluentui-react-tree-971f2603-bff0-4558-93ea-267be83d77cb.json
packages/react-components/react-tree/src/components/FlatTree/useFlatTree.ts
packages/react-components/react-tree/src/components/Tree/useTree.ts

1. adds a warning for the mixing of `Tree` and `FlatTree` in the same Tree. here's an example: https://github.com/microsoft/fluentui/issues/29444
- Fixes #

chore(react-tree): adds console error when mixing Tree and FlatTree components

---

apps/vr-tests-react-components/src/stories/MessageBar/MessageBar.stories.tsx
change/@fluentui-react-message-bar-preview-78af6acc-f656-41f0-9366-765337219696.json
packages/react-components/react-message-bar-preview/src/components/MessageBar/useMessageBarStyles.styles.ts
packages/react-components/react-message-bar-preview/stories/MessageBar/Intent.stories.tsx

Aligns icons with text content, and updates the itent example to start with an upper case letter, since the icons are only 'truly' aligned with an upper case letter.
Fixes #29416

fix(MessageBar): Align icons with text content

---

change/@fluentui-react-button-09a0ee22-f58e-4010-b397-57c82a77209e.json
packages/react-components/react-button/src/components/Button/useButtonStyles.styles.ts

Previously, in some instances of scaling on FireFox (including at 100%) - button border would not be uniform on focus (inset border box shadow)
All button styles should now retain the 1px border + inset 2px box shadow on all browsers
- Fixes #29417

Fix V9 Button focus inset box shadow for FireFox scaling

---

packages/react-examples/src/react-charting/LineChart/LineChart.Styled.Example.tsx
packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.Styled.Example.tsx

The legend text styles can be overridden like this:
```jsx
<LineChart
{...props}
legendProps={{
styles: {
legend: {
textTransform: 'none',
},
},
}}
/>
```

Show how to override legend text styles in examples

---

change/@fluentui-react-tree-98b121f2-403e-4504-8aef-bd3ea55c02fc.json
packages/react-components/react-tree/src/hooks/useSubtree.ts

`useSubtree` was consuming the current parent level of the tree by the root context (which is always 1)
`useSubtree` should consume the current parent level of the tree by the subtree context (which will vary depending on the level of the subtree)
- Fixes https://github.com/microsoft/fluentui/issues/29447

bugfix(react-tree): Tree indentation broken

---

change/@fluentui-react-dialog-638853b4-442a-44da-b79c-3b3071a063e3.json
change/@fluentui-react-menu-7fdfa4f1-981a-4942-b8b2-28989af08745.json
change/@fluentui-react-popover-68102fa6-ec06-4d3b-b2a9-5ef9e3f56ce1.json
change/@fluentui-react-tooltip-5d73642d-79d9-455c-b084-ee5beab476fd.json
packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurface.ts
packages/react-components/react-menu/src/components/MenuPopover/useMenuPopover.ts
packages/react-components/react-popover/src/components/PopoverTrigger/usePopoverTrigger.ts
packages/react-components/react-tooltip/src/components/Tooltip/useTooltip.tsx

Uses `stopPropagation` to stop Escape key down event to ensure no conflict between different components.
Uses `preventDefault` + verification of default prevention to ensure Escape key press is being handled properly.
- Fixes #

chore: use default prevention instead of stop propagation for Escape handling

---

change/@fluentui-react-breadcrumb-preview-11c3318a-f80b-434c-b1ae-56c133b98a7c.json
change/@fluentui-react-card-77a7f4d8-bb8a-4180-8267-0f8ea01e3090.json
change/@fluentui-react-drawer-47bfdeab-adf5-4f47-8213-763737c1449f.json
change/@fluentui-react-image-289ea7be-5325-4e6e-919e-2d79e9eeea3e.json
change/@fluentui-react-text-e3797009-3912-4e9f-ab2e-c87aedf186da.json
packages/react-components/react-breadcrumb-preview/etc/react-breadcrumb-preview.api.md
packages/react-components/react-breadcrumb-preview/src/components/Breadcrumb/useBreadcrumb.ts
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbDivider/useBreadcrumbDivider.tsx
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbItem/useBreadcrumbItem.ts
packages/react-components/react-card/src/components/Card/useCard.ts
packages/react-components/react-card/src/components/CardFooter/useCardFooter.ts
packages/react-components/react-card/src/components/CardHeader/useCardHeader.ts
packages/react-components/react-card/src/components/CardPreview/useCardPreview.ts
packages/react-components/react-drawer/src/components/DrawerBody/useDrawerBody.ts
packages/react-components/react-drawer/src/components/DrawerFooter/useDrawerFooter.ts
packages/react-components/react-drawer/src/components/DrawerHeader/useDrawerHeader.ts
packages/react-components/react-drawer/src/components/DrawerHeaderNavigation/useDrawerHeaderNavigation.ts
packages/react-components/react-drawer/src/components/DrawerHeaderTitle/useDrawerHeaderTitle.ts
packages/react-components/react-drawer/src/components/DrawerInline/useDrawerInline.ts
packages/react-components/react-image/src/components/Image/useImage.ts
packages/react-components/react-text/src/components/Text/useText.ts

Follow up on https://github.com/microsoft/fluentui/pull/29310
`getNativeElementProps` has some type safety issues, allowing erroneous properties to be introduced.
1. replaces use cases of `getNativeElementProps` with an equivalent but more restrict method `getIntrinsicElementProps`

chore: migrate from getNativeElementProps for getIntrinsicElementProps

---

change/@fluentui-react-jsx-runtime-5a65abfa-83a9-4296-a8b9-2ace31e4e547.json
packages/react-components/react-jsx-runtime/.swcrc
packages/react-components/react-jsx-runtime/package.json
packages/react-components/react-jsx-runtime/src/jsx/createJSX.ts
packages/react-components/react-jsx-runtime/src/utils/warnIfElementTypeIsInvalid.ts

Some clients are facing some issues, where multiple versions of `@fluentui/react-utilities` are installled in their dependencies and that may cause `isSlot` to errounesouly return `false` in situations it should return `true` due to the fact Symbols are unique and having different instancies of `react-utilities` running means having multiple Symbols, which means `isSlot` may fail to determine if a certain object is a slot or not.
1. Adds warning in development environment to explain the user what the problem is.
2. Adds `swc-plugin-de-indent-template-literal` plugin to `.swcrc`

chore(react-jsx-runtime): add warning for resolution problems

---

packages/react-components/react-message-bar/stories/MessageBar/MessageBarDescription.md
packages/react-components/react-message-bar/stories/MessageBar/index.stories.tsx

See title.
This manual step was added to #29510 to be automated

docs: Move MessageBar docs to stable section in docsite

---

change/@fluentui-web-components-f70c1f20-47e3-4e76-9cb0-53fef171209f.json
packages/web-components/src/switch/switch.styles.ts

Switch used a transform to move the indicator to the checked state which led to an issue where there wasn't immediate support for RTL.
This PR updates the code to leverage margin-inline-start instead which allows for this to be automatically accommodated in RTL scenarios. 
- Fixes #28933

fix(web-components): update switch to use margin for checked state to support RTL

---

packages/merge-styles/README.md
packages/merge-styles/etc/merge-styles.api.md
packages/merge-styles/src/index.ts
packages/merge-styles/src/shadowConfig.ts
packages/utilities/src/customizations/customizable.tsx
packages/utilities/src/shadowDom/MergeStylesRootContext.tsx
packages/utilities/src/shadowDom/MergeStylesShadowRootContext.tsx
packages/utilities/src/styled.tsx

Working with shadow DOM APIs is harder than it needs to be and nothing is documented.
Adds helper functions to simplify working with `merge-styles` shadow DOM APIs.
Adds documentation explaining basic usage of shadow DOM features.

feat: add helper functions and docs

---

packages/react-components/react-swatch-picker-preview/package.json

Fix dependencies after releasing a new v9 version

fix(react-swatch-picker): mismatch dependencies

---

packages/react-components/react-timepicker-compat-preview/etc/react-timepicker-compat-preview.api.md
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.types.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/timeMath.test.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/timeMath.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/useTimePicker.tsx
packages/react-components/react-timepicker-compat-preview/stories/TimePicker/TimePickerCustomTimeString.stories.tsx
packages/react-components/react-timepicker-compat-preview/stories/TimePicker/index.stories.tsx

Add a new prop `formatDateToTimeString` that allows custom time display format:

feat(TimePicker compat): new prop `formatDateToTimeString` to custom time display format

---

change/@fluentui-react-tree-006fbe59-9dfe-471f-aab7-99f77c1fb4f2.json
packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx

`TreeItem` internally converts `props.value` to string
Stops converting `props.value` to string and keep it as is.
- Fixes https://github.com/microsoft/fluentui/issues/29528

bugfix(react-tree): stop coercing numbers to string on TreeItemValue

---

packages/react-components/react-dialog/stories/Dialog/DialogTriggerOutsideDialog.md
packages/react-components/react-dialog/stories/Dialog/DialogTriggerOutsideDialog.stories.tsx

Updates the documentation to make it more clear that it is the user's responsibility to update open state once dialog is controlled by the user
- Fixes https://github.com/microsoft/fluentui/issues/29516

doc(react-dialog): update Dialog documentation on trigger outside of dialog

---

packages/react-components/react-swatch-picker-preview/etc/react-swatch-picker-preview.api.md
packages/react-components/react-swatch-picker-preview/src/components/SwatchPicker/useSwatchPicker.ts

Follow up on https://github.com/microsoft/fluentui/pull/29310
`getNativeElementProps` has some type safety issues, allowing erroneous properties to be introduced.
1. replaces use cases of `getNativeElementProps` with an equivalent but more restrict method `getIntrinsicElementProps`

chore(react-swatch-picker-preview): migrate from getNativeElementProps to getIntrinsicElementProps

---

packages/react-components/react-calendar-compat/README.md
packages/react-components/react-calendar-compat/etc/react-calendar-compat.api.md
packages/react-components/react-calendar-compat/src/index.ts

There were missing exports from the Calendar components.
All missing exports have been added to the Calendar compat package.
There's now docs about the compat components and specifically the case of Calendar not moving to slots API. 
- Fixes #29538
- Fixes #29541

feat(react-calendar-compat): Add missing Calendar exports and docs about compat components

---

change/@fluentui-react-charting-7bdc342b-897c-41f4-a785-2bed26b30f93.json
packages/react-charting/src/components/DonutChart/Arc/Arc.tsx
packages/react-charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
packages/react-charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx
packages/react-charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx
packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx

Hide bar labels of non highlighted bars

---

packages/react-components/react-infolabel-preview/etc/react-infolabel-preview.api.md
packages/react-components/react-infolabel-preview/package.json
packages/react-components/react-infolabel-preview/src/InfoButton.ts
packages/react-components/react-infolabel-preview/src/InfoLabel.ts
packages/react-components/react-infolabel-preview/src/components/InfoButton/DefaultInfoButtonIcons.tsx
packages/react-components/react-infolabel-preview/src/components/InfoButton/InfoButton.test.tsx
packages/react-components/react-infolabel-preview/src/components/InfoButton/InfoButton.tsx
packages/react-components/react-infolabel-preview/src/components/InfoButton/InfoButton.types.ts
packages/react-components/react-infolabel-preview/src/components/InfoButton/index.ts
packages/react-components/react-infolabel-preview/src/components/InfoButton/renderInfoButton.tsx
packages/react-components/react-infolabel-preview/src/components/InfoButton/useInfoButton.tsx
packages/react-components/react-infolabel-preview/src/components/InfoButton/useInfoButtonStyles.styles.ts
packages/react-components/react-infolabel-preview/src/components/InfoLabel/InfoLabel.cy.tsx
packages/react-components/react-infolabel-preview/src/components/InfoLabel/InfoLabel.test.tsx
packages/react-components/react-infolabel-preview/src/components/InfoLabel/InfoLabel.tsx
packages/react-components/react-infolabel-preview/src/components/InfoLabel/InfoLabel.types.ts
packages/react-components/react-infolabel-preview/src/components/InfoLabel/index.ts
packages/react-components/react-infolabel-preview/src/components/InfoLabel/renderInfoLabel.tsx
packages/react-components/react-infolabel-preview/src/components/InfoLabel/useInfoLabel.ts
packages/react-components/react-infolabel-preview/src/components/InfoLabel/useInfoLabelStyles.styles.ts
packages/react-components/react-infolabel-preview/src/index.ts
packages/react-components/react-infolabel-preview/stories/InfoLabel/InfoLabelBestPractices.md
packages/react-components/react-infolabel-preview/stories/InfoLabel/InfoLabelDefault.stories.tsx
packages/react-components/react-infolabel-preview/stories/InfoLabel/InfoLabelDescription.md
packages/react-components/react-infolabel-preview/stories/InfoLabel/InfoLabelInField.stories.tsx
packages/react-components/react-infolabel-preview/stories/InfoLabel/InfoLabelPatternDecision.md
packages/react-components/react-infolabel-preview/stories/InfoLabel/InfoLabelRequired.stories.tsx
packages/react-components/react-infolabel-preview/stories/InfoLabel/InfoLabelSize.stories.tsx
packages/react-components/react-infolabel-preview/stories/InfoLabel/index.stories.tsx

Copy over files from react-infobutton to react-infolabel. Nothing was changed except what's been pointer below.
- Fixes #29544

feat(react-infolabel-preview): Copy over files from react-infobutton to react-infolabel-preview

---

packages/react-components/react-infolabel-preview/src/components/InfoButton/useInfoButton.tsx

InfoButton's ref was casted to HTMLButtonElement due to making the ref change would involve a breaking change.
InfoButton's ref is now of type HTMLButtonElement.
- Fixes #29557

fix(react-infolabel-preview): InfoButton's ref should be of type HTMLButtonElement

---

.devops/templates/tools.yml
.github/workflows/check-packages.yml
.github/workflows/docsite-publish-chromatic.yml
.github/workflows/docsite-publish-ghpages.yml
package.json
yarn.lock

nodejs install within our jobs are extremely unreliable which makes whole CI very flaky.
[example of failing pipeline](https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=322792&view=results)
- we use only nodejs that is being shipped with 1es container
- yarn@1 is part of this container so there is no need to install it manually
- Fixes #

ci: use nodejs version that is preinstalled on 1es containers in order to avoid flaky pipeline issues while installing nodejs

---

change/@fluentui-react-dialog-e7703ba0-5918-4d1d-8ab6-b353dd5b2426.json
change/@fluentui-react-popover-a85665ab-54f3-46a0-aafc-a513ddfe135d.json
change/@fluentui-react-tabster-04feba9e-faa2-49d5-a828-8fd549454e5c.json
packages/react-components/react-dialog/src/components/Dialog/Dialog.cy.tsx
packages/react-components/react-popover/src/components/Popover/Popover.cy.tsx
packages/react-components/react-tabster/package.json
packages/react-components/react-tabster/src/hooks/useTabster.ts
yarn.lock

Bumps tabster version to enable support for virtual parents. e2e tests to prevet regression
Fixes #28915
Fixes #29519

fix: Tabster should support virtual parents

---

apps/public-docsite-v9/package.json
change/@fluentui-react-infolabel-preview-02b3708e-7fe6-485f-9722-ad5d9a2c4f89.json
packages/react-components/react-infolabel-preview/package.json

Release preview version of infolabel. Ran the following command: `yarn nx g @fluentui/workspace-plugin:prepare-initial-release --project @fluentui/react-one-preview --phase=preview` as shown in https://github.com/microsoft/fluentui/wiki/new-release-process---v9-packages
- Fixes #29561

chore(react-infolabel-preview): Make react-infolabel-preview public

---

apps/public-docsite-v9/package.json
change/@fluentui-react-calendar-compat-1e17bccb-24fd-4107-9285-54ba3ad1366e.json
packages/react-components/react-calendar-compat/bundle-size/Calendar.fixture.js
packages/react-components/react-calendar-compat/package.json

Calendar compat stories were not showing up due to missing dependency for calendar-compat.
Calendar compat stories now show up and bundle size fixtures were added for Calendar compat.
- Related #29438

chore(public-docsite-v9, react-calendar-compat): Add bundle size fixture for Calendar and add react-calendar-compat dependency to public-docsite-v9

---

change/@fluentui-web-components-eb7910d3-4886-4c46-a3d3-4cb448a176eb.json
packages/web-components/package.json

Menu web component definition was missing from the package.json sideEffects.
Menu web component definition is now included in the list of component definitions in package.json sideEffects.
Menu component is now properly exported.
- Fixes #[1230608](https://powerbi.visualstudio.com/Trident/_workitems/edit/1230608)

Adds Menu Component to sideEffects

---

change/@fluentui-react-charting-f831c35a-e12e-458d-9a22-de0345f66557.json
packages/react-charting/src/utilities/utilities.ts

Codepen Link for Repro purpose:
https://codepen.io/itsein/pen/qByrGNj
- Fixes #26303

Fix missing x callout custom callout

---

change/@fluentui-react-dialog-c4b3b805-3dcc-4caa-9c9e-ceb9a1580a1a.json
packages/react-components/react-dialog/etc/react-dialog.api.md
packages/react-components/react-dialog/package.json
packages/react-components/react-dialog/src/components/Dialog/renderDialog.tsx
packages/react-components/react-dialog/src/components/Dialog/useDialog.ts
packages/react-components/react-dialog/src/components/DialogSurface/DialogSurface.types.ts
packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurface.ts
packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurfaceStyles.styles.ts
packages/react-components/react-dialog/src/contexts/dialogTransitionContext.ts

1. Introduces animations to Dialog component using `react-transition-group`
- Fixes https://github.com/microsoft/fluentui/issues/28610

feat(react-dialog): adds motion to `DialogSurface`

---

change/@fluentui-react-calendar-compat-8241b3ac-9f23-473b-be97-cfbe2c70475d.json
packages/react-components/react-calendar-compat/src/components/CalendarDayGrid/CalendarGridDayCell.tsx

The classnames added/removed in day cells were the result of a makeStyles call, therefore these items contained spaces like this: `classname1 classname2 classname3`. This is an issue when using classList.add/remove since spaces are not handled, this results in an error: 
```
InvalidCharacterError
Failed to execute 'add' on 'DOMTokenList': The token provided (' ') contains HTML space characters, which are not valid in tokens.
```
The classnames used in remove/add are now sanitized by splitting through spaces.

fix(react-calendar-compat): Classnames removed and added to day cells need to be split instead of providing a string with spaces

---

packages/react-components/react-textarea/stories/Textarea/TextareaBestPractices.md

PR to add guidance about how to modify Textarea's height. This can be a little difficult due to the way Textarea is structured, so this guidance aims to give some help on how to avoid any issues.
- Fixes #29474

docs(react-textarea): Add guidance for modifying Textarea's height

---

packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.test.tsx
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/useTimePicker.tsx

This PR adds onblur event listener to TimePicker, and update `selectedTime` state when TimePicker loses focus. Similar to browser native `onChange` event

feat(TimePicker-compat): call onTimeSelect on blur

---

change/@fluentui-react-provider-1d59a37a-b2d6-4a70-b80d-0d6fe26ae7dd.json
change/@fluentui-react-shared-contexts-6914bf09-e179-4a18-a658-e430a7bcac83.json
change/@fluentui-react-toast-d1bade96-d87a-41c1-8a8a-c6bf3d154e58.json
packages/react-components/react-provider/etc/react-provider.api.md
packages/react-components/react-shared-contexts/etc/react-shared-contexts.api.md
packages/react-components/react-shared-contexts/src/CustomStyleHooksContext/CustomStyleHooksContext.ts
packages/react-components/react-toast/src/components/Toaster/Toaster.tsx

fix(react-toast): invoke useCustomStyleHook_unstable()

---

azure-pipelines.yml

- `ComponentGovernance` ADO task is failing due to `ReallyClean` task deleting everything before the pipeline completes. Removing this task enables ComponentGovernance to run correctly once again

fix(hotfix/5.135.6): Remove ReallyClean pipeline task 

---

tools/workspace-plugin/src/generators/prepare-initial-release/index.spec.ts
tools/workspace-plugin/src/generators/prepare-initial-release/index.ts

see title and referenced issue
- Fixes https://github.com/microsoft/fluentui/issues/29510

fix(workspace-plugin): fix storybook and vr-test issues wihtin prepare-initial-release generator

---

change/@fluentui-react-text-701383d5-631a-46fc-a991-276a590f6132.json
change/@fluentui-utilities-78031fb1-2f31-4c82-a6e6-921baf28c8f6.json
lage.config.js
package.json
packages/react-components/react-text/package.json
packages/utilities/package.json
scripts/tasks/src/presets.ts
scripts/tasks/src/verify-packaging.ts

we dont know 100% what we actually ship to npm. this caused a lot of headaches in the past while migrating to new major versions of nodejs or in general config tweaks ( see linked epic for more info )
- implements `verify-packaging` just-script task ( has nothing in particular with just-scripts and will be migrated to nx executor once we will start migration from lage/just).
- new task is being added to 1 v9 and 1 v8 package
- this is a pre-requirement for safe migration to node v18
- v9 (probably v8 should as well) will switch to`"files"` specifier in package.json -> thus the logic will of the task will be updated
- implements partially https://github.com/microsoft/fluentui/issues/27758

feat(scripts-task): implement initial verify-packaging task

---

change/@fluentui-react-drawer-b7d10669-1f23-47cb-bc3e-21e001e940f1.json
packages/react-components/react-drawer/src/components/DrawerInline/DrawerInline.cy.tsx
packages/react-components/react-drawer/src/components/DrawerOverlay/useDrawerOverlayStyles.styles.ts
packages/react-components/react-drawer/src/shared/useDrawerBaseStyles.styles.ts

This PR introduces two fixes for accessibility:
- Remove CSS transitions for Drawer backdrop
- Add line separator when in "high contrast" mode
- Fixes #29206

fix(react-drawer): accessibility tweaks

---

change/@fluentui-react-drawer-6f092714-b539-4d1a-a9ae-30244e5d54d9.json
packages/react-components/react-drawer/etc/react-drawer.api.md
packages/react-components/react-drawer/src/components/InlineDrawer/useInlineDrawerStyles.styles.ts
packages/react-components/react-drawer/src/components/OverlayDrawer/OverlayDrawer.types.ts
packages/react-components/react-drawer/src/components/OverlayDrawer/useOverlayDrawer.ts
packages/react-components/react-drawer/src/components/OverlayDrawer/useOverlayDrawerStyles.styles.ts
packages/react-components/react-drawer/stories/Drawer/DrawerMotionCustom.stories.tsx

Previously the motion styles for the Drawer were created by applying the logic manually.
Uses `useMotionClassNames` to simplify the logic.

feat(react-drawer): use useMotionClassNames to create drawer motion styles

---

.codesandbox/ci.json
.devops/templates/tools.yml
.github/workflows/check-packages.yml
.github/workflows/docsite-publish-chromatic.yml
.github/workflows/docsite-publish-ghpages.yml
change/@fluentui-eslint-plugin-222b39b1-1e9b-458f-8ddf-0dfef3a6717e.json
change/@fluentui-utilities-9901c7ce-5a05-4473-ab4f-ff74df9878eb.json
package.json
packages/eslint-plugin/package.json
packages/fluentui/local-sandbox/package.json
packages/utilities/src/safeSetTimeout.ts
syncpack.config.js
yarn.lock

migrate to LTS node -> 18
- please see commit messages for additional detail
- Fixes #

chore: migrate to node 18

---

change/@fluentui-react-combobox-8126d46d-4e84-4804-b216-b86e9feb4b77.json
packages/react-components/react-combobox/src/utils/ComboboxBase.types.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.test.tsx
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/useTimePicker.tsx

When typing in a freeform TimePicker and hit enter key, if the input value is not prefix of an option in the dropdown, TimePicker should submit the value as is.
However Combobox behaves differently. It is trying to set the 1st option in listbox as active option (so it will be selected on Enter key). So TimePicker is trying to clear the activeOption state set by combobox.
Before this PR, when typing an invalid option, TimePicker re-renders and re-creates new `children`, triggering [`useEffect` in `useComboboxBaseState`](https://github.com/microsoft/fluentui/blob/61d4a2910a5039af8b8509422ecfe58bc636191c/packages/react-components/react-combobox/src/utils/useComboboxBaseState.ts#L102), setting activeOption to 1st option, and it is reset to undefined by TimePicker.
This PR use set state …

fix(TimePicker-compat): fix freeform behavior + add tests

---

change/@fluentui-react-charting-bb39437e-09f9-49d3-b237-f3ed33095167.json
packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx

Work item https://uifabric.visualstudio.com/iss/_workitems/edit/9457
If Y values are zero, the callout is not displaying the values for Cartesian Charts.
Before fix:
Area Chart
Line Chart
After fix:
Area Chart
Line Chart

Fixing zero callout value not visible bug for cartesian charts

---

packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.types.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/timeMath.test.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/timeMath.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/useTimePicker.tsx
packages/react-components/react-timepicker-compat-preview/stories/TimePicker/TimePickerCustomTimeString.stories.tsx
packages/react-components/react-timepicker-compat-preview/stories/TimePicker/TimePickerDefault.stories.tsx
packages/react-components/react-timepicker-compat-preview/tsconfig.lib.json

TimePicker has `hour12: boolean` prop controls if the time format is 12-hour or 24-hour. This is the same as V8 TimePicker. But v8 TimePicker has an [open bug](https://github.com/microsoft/fluentui/issues/25041) that 24:00 and 24:30 can be displayed when 00:00 00:30 is desired. This is because `hour12: boolean` doesn't give enough control over the start and end hour of time format.
Change `hour12` prop to `hourCycle?: 'h11' | 'h12' | 'h23' | 'h24' | undefined`. This is aligned with [Intl hourCycle](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/hourCycle). 
'h11' and 'h23' start with hour 0 and go up to 11 and 23 respectively. 'h12' and 'h24' start with hour 1 and go up to 12 and 24 respectively. Also the support of Intl API is within our …

feat(TimePicker-compat): use `hourCycle` to set 12-hour/24-hour time format

---

change/@fluentui-react-charting-558ce73b-bb6f-475f-be32-1aa78f0663a0.json
packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx

Added scale factor to minHeight logic

---

packages/react-components/react-combobox/stories/Combobox/ComboboxControlled.stories.tsx
packages/react-components/react-combobox/stories/Dropdown/DropdownControlled.stories.tsx

Found a small bug in our docs, the default value wasn't properly selected in either example, as the default value was inconsistend with the option value.

docs: fix defaultSelectedOptions for Dropdown and Combobox examples

---

change/@fluentui-react-dialog-583dc616-fa6f-4401-8ee9-6f25dd159aac.json
packages/react-components/react-dialog/src/components/Dialog/renderDialog.tsx

Conditionally removes the usage of `Transition` component to disable animations on tests environments
- Fixes https://github.com/microsoft/fluentui/issues/29704

chore(react-dialog): remove animation from test environments

---

packages/react-components/react-timepicker-compat-preview/etc/react-timepicker-compat-preview.api.md
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.test.tsx
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.types.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/timeMath.test.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/timeMath.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/useTimePicker.tsx

This PR does renames and some code polish after 1st round of TimePicker code review:
Renames:
- `onTimeSelect` => `onTimeChange`
- `validateFreeFormTime` => `formatTimeStringToDate`
Code polish:
- Pick props from Combobox instead of using Omit.
- Simplify `useStableDateAnchor` hook to use one `useMemo`

chore(TimePicker-compat): renames and code polish

---

package.json

chore: restrict  node versions to 18 || 20

---

scripts/generators/generate-package-manifest.js

generate manifests adds packages that are not v8 related.
- generate manifests adds only v8 related packages and makes the contract correct
- script prints paths that have been created for better DX 
- script is now generic and can be customized via CLI in future if needed
- Fixes #

fix(scripts-generators): create manifest only from v8 monorepo packages within `generate-package-manifest` 

---

change/@fluentui-react-tree-b6e16366-ba82-402d-b48d-bf2d6449bb78.json
packages/react-components/react-tree/etc/react-tree.api.md
packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx
packages/react-components/react-tree/src/components/TreeItem/useTreeItemContextValues.ts
packages/react-components/react-tree/src/components/TreeItemLayout/TreeItemLayout.test.tsx
packages/react-components/react-tree/src/components/TreeItemLayout/useTreeItemLayout.tsx
packages/react-components/react-tree/src/components/TreeItemPersonaLayout/TreeItemPersonaLayout.test.tsx
packages/react-components/react-tree/src/contexts/treeItemContext.ts

`TreeItem` seems to be causing re-renders unnecessarily when there are no actions elements available, to ensure actions might be visible
1. Adds verification of the presence of `actions` element on the DOM, in that case re-renders might be in place
- Fixes #

chore(react-tree): stop unnecessary re-rendering when no actions are available

---

change/@fluentui-react-tree-0174e77b-7502-4cae-aaff-b17e91eb770e.json
packages/react-components/react-tree/src/components/FlatTree/useFlatTree.ts
packages/react-components/react-tree/src/components/Tree/useTree.ts

FlatTree just console error about the fact user should not be using a FlatTree as a subtree
As multiple clients were detected using FlatTree as a subtree, this PR ensure that in development FlatTree will throw if used  as a subtree
1. Throws in development if FlatTree is used as a subtree
2. Throws in development if Tree is used as a subtree of a FlatTree
- Fixes #

chore(react-tree): throws if FlatTree is used as a subtree

---

tools/workspace-plugin/src/generators/migrate-converged-pkg/index.spec.ts
tools/workspace-plugin/src/generators/migrate-fixed-versions/index.spec.ts
tools/workspace-plugin/src/generators/move-packages/index.spec.ts
tools/workspace-plugin/src/generators/rc-caret/index.spec.ts
tools/workspace-plugin/src/generators/recipe-generator/index.ts
tools/workspace-plugin/src/generators/version-bump/index.spec.ts

removes `@nx/devkit` deprecated apis that will no longer work with nx 17
```diff
-readWorkspaceConfiguration
+readNxJson
-WorkspaceConfiguration
+NxJsonConfiguration
```
- Follows https://github.com/microsoft/fluentui/pull/29617

refactor(tools): replace deprecated apis

---

packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbWithOverflow.stories.tsx
packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbWithTooltip.stories.tsx

Refactoring of Breadcrumb stories with Overflow and Tooltip examples

fix (breadcrumb): Overflow examples refactoring

---

change/@fluentui-react-drawer-f0b39b94-dc6b-447a-aae1-919873990ecb.json
packages/react-components/react-drawer/etc/react-drawer.api.md
packages/react-components/react-drawer/src/shared/DrawerBase.types.ts
packages/react-components/react-drawer/stories/Drawer/DrawerMotionCustom.stories.tsx
packages/react-components/react-drawer/stories/Drawer/index.stories.tsx

This is technically a Breaking Change, but as the package is still in preview, we can have that happening.
This change makes the `open` prop on all the main Drawer components to only accept a `boolean` value. Previously it was accepting a MotionShorthand type as well. This will be added back in the future when the react-motion package becomes stable.
For more information: https://github.com/microsoft/fluentui/pull/29711

breaking(react-drawer): open now only accepts a boolean instead of MotionShorthand

---

change/@fluentui-react-calendar-compat-b50cbe44-44ed-4b3a-9329-aa9be78d1e75.json
change/@fluentui-react-f74bc323-4380-4898-a854-205fb9b839f3.json
packages/react-components/react-calendar-compat/src/components/Calendar/Calendar.tsx
packages/react/src/components/Calendar/Calendar.base.tsx

Calendar was applying a default value `new Date()` to today which causes rerenders since it creates a new object each time when today is undefined.
Calendar now memoizes today in order to avoid rerenders

fix(react-calendar-compat, Calendar): Calendar should memoize default value since it's a new Date() to avoid rerenders

---

change/@fluentui-react-dialog-6091ac61-07dc-43d4-87d0-90f15c513098.json
packages/react-components/react-dialog/src/components/Dialog/Dialog.test.tsx
packages/react-components/react-dialog/src/components/Dialog/renderDialog.tsx
packages/react-components/react-dialog/src/components/DialogSurface/DialogSurface.types.ts
packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurfaceStyles.styles.ts
packages/react-components/react-dialog/src/contexts/dialogTransitionContext.ts

`DialogTransitionContext` is always defined and has value `entered` for test environment (#29692). However, `DialogSurface` has base style `opacity: 0`, and when transition status is `entered`, it merges style `opacity: 1`. To apply styles `DialogSurface` uses `makeResetStyles()` & `makeStyles()`, so will get following:
```css
.reset-class {
/* ... some CSS rules */
opacity: 0;
}
.atomic-class {
opacity: 1;
}
```
In this case, tests for `DialogSurface` using `jest-dom` & `.toBeVisible()` can fail. This is a `jsdom` bug - it cannot detect style override with 'opacity' nor 'visibility' (check [Stackblitz](https://stackblitz.com/edit/stackblitz-starters-ugiwec?file=package.json)). This happens because `DialogSurface` has as base style `opacity:0`: …

fix(react-dialog): set transition status to `undefined` for test environment

---

.devcontainer/Dockerfile
.devcontainer/README.md
.devcontainer/devcontainer.json
lage.config.js

- devcontainer uses node 18 ( used within codespaces )
- <img width="706" alt="image" src="https://github.com/microsoft/fluentui/assets/1223799/b8872101-1cd5-4e66-8387-6f5247849f7d">
- updated lage ignore
- Follows #29598

ci: bump devcontainer to node 18

---

change/@fluentui-react-components-3279ab16-e66a-4caa-8a97-8f0d1aa85514.json
packages/react-components/react-components/src/unstable/index.ts

See PR title
- Implements partially https://github.com/microsoft/fluentui/issues/28471

fix(react-components): mark react-tree apis as deprecated and add Deprecation heading to the /unstable module

---

tools/workspace-plugin/project.json
tools/workspace-plugin/src/generators/migrate-converged-pkg/index.spec.ts
tools/workspace-plugin/src/generators/migrate-converged-pkg/index.ts
tools/workspace-plugin/src/generators/react-library/files/package.json__tmpl__
tools/workspace-plugin/src/generators/react-library/index.spec.ts
tools/workspace-plugin/src/types.ts

features:
- migrate-converged-pkg:
- `package.json#files` property is created based on project context/setup 
bufixes:
- `migrate-converged-pkg`:
- `tsConfig` property is no longer added to conformance setup on consecutive migrate generator runs
- fixes relative path generation
- adds `styles` to export maps if specified
- `test-ssr`  npm task is added based on project context/setup instead adding it to every one
- `react-library`
- adds test for `files` 
- adds `*.md` to files 
- Follows https://github.com/microsoft/fluentui/pull/29616
- Implements partially https://github.com/microsoft/fluentui/issues/27758

feat(tools): create package.json#files based on project setup within migrate-converged-pkg generator, dont dupe tsConfig in conformance setup

---

tools/workspace-plugin/src/generators/react-component/files/component/__componentName__.tsx__tmpl__
tools/workspace-plugin/src/generators/react-component/index.spec.ts
tools/workspace-plugin/src/generators/react-library/files/package.json__tmpl__
tools/workspace-plugin/src/generators/react-library/index.spec.ts

Since all components need to support custom style hooks, adds react-shared-contexts package to dependencies during package creation
Also removes duplication of style hook in component generation
Fixes partialy #29775

chore: react-shared-contexts should be included in new package deps

---

apps/vr-tests-react-components/package.json
apps/vr-tests-react-components/src/stories/TimePicker.stories.tsx

Add VR test.
Since TimePicker is built on Combobox, the VR test focuses on TimePicker specifics and skips the tests like appearances/sizes that are tested in Combobox

chore(TimePicker-compat): add VR test

---

change/@fluentui-react-1c4645e3-a3e3-49b1-9e15-df952be33941.json
packages/react/src/components/ComboBox/ComboBox.tsx

A fix for a team requires passing in `preventDismissOnEvent` to `calloutProps` in ComboBox, but it is currently overridden by the internal `preventDismissOnEvent`. Quick fix to respect the passed-in prop.

fix: v8 ComboBox preventDismissOnEvent does not override passed-in prop

---

apps/vr-tests-react-components/src/stories/Toast/Toast.stories.tsx
change/@fluentui-react-toast-1c4a93c3-4066-4744-a222-490672ba5925.json
packages/react-components/react-toast/src/components/ToastBody/useToastBodyStyles.styles.ts
packages/react-components/react-toast/src/components/ToastTitle/useToastTitleStyles.styles.ts

The toast is a small surface even without reflow. Adds `word-wrap: break-word` to both the title and body so that the text content wraps with long text.
Before
After

fix: Toast text content should wrap

---

packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbWithOverflow.stories.tsx

- overflow count was incorrect. It showed "0 more items" when there were hidden items
- overflow count includes all the overflow items

fix(breadcrumb): overflow count in Breadcrumb stories

---

change/@fluentui-react-components-0cc81826-b8da-4ec9-bd13-7afc5a55f529.json
change/@fluentui-react-drawer-b691c676-caea-4230-b7c4-7c304bcf4b60.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts
packages/react-components/react-drawer/etc/react-drawer.api.md
packages/react-components/react-drawer/src/index.ts

The export for `useDrawerStyles_unstable` was missing from the index files in both `react-drawer` and `react-components` packages.
`useDrawerStyles_unstable` is now exported from both `react-drawer` and `react-components` packages.

chore: Export missing useDrawerStyles_unstable from react-drawer and react-components

---

change/@fluentui-react-breadcrumb-preview-99feac5c-b9dd-4c16-b451-3c2cc099992c.json
packages/react-components/react-breadcrumb-preview/package.json
packages/react-components/react-breadcrumb-preview/src/components/Breadcrumb/Breadcrumb.test.tsx
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbButton/BreadcrumbButton.test.tsx
packages/react-components/react-breadcrumb-preview/src/components/BreadcrumbButton/useBreadcrumbButton.ts
packages/react-components/react-breadcrumb-preview/stories/Breadcrumb/BreadcrumbWithTooltip.stories.tsx

We had focusable `<a>` tags with no `href`, which is semantically the same as a `<span>`. We could also potentially add `role=link`, but it seems better to render items with no `href` or explicit `as` as a `<button>`.
This also makes a minor story fix to make `<Tooltip>` directly wrap `<BreadcrumbButton>` so that the `aria-label` is being applied to the correct element.

fix: Breadcrumb uses button when no href is present, tooltip labels button

---

change/@fluentui-react-virtualizer-ce60aa55-792e-4691-b912-97ac20583078.json
packages/react-components/react-virtualizer/etc/react-virtualizer.api.md
packages/react-components/react-virtualizer/src/hooks/useIntersectionObserver.ts
packages/react-components/react-virtualizer/src/hooks/useMutationObserver.ts

IO Margin could be flipped in RTL and was incorrectly calculated by Intersection Observer.
IO Margin can now be flipped by RTL mutation and will correctly calculate margin positioning for IO events.

Handle RTL margin and mutations on useIntersectionObserver

---

packages/react-components/react-input/stories/Input/InputType.stories.tsx
packages/react-examples/src/react/TextField/TextField.Basic.Example.tsx

There were some concerns that an input with type password logged a warning in Chrome, and that it displayed the password content. This is a years old behavior by Chrome, and is just meant to recommend users to wrap password fields in a form so that they are easier to fill in with password managers.
Despite the fact that this is not an issue at all on our part [1](https://stackoverflow.com/questions/50796140/ionic-3-form-still-warning-me-password-field-is-not-contained-in-a-form) I'm adding this to avoid future reports, and it does align with how inputs are represented in frameworks like MUI.
https://stackoverflow.microsoft.com/questions/376931

chore: wrap password input in form element to avoid warning in chrome

---

change/@fluentui-react-menu-cdcb0ce7-cf9f-4e57-93a7-436d6aaacdca.json
packages/react-components/react-menu/src/components/MenuTrigger/useMenuTrigger.ts

Changes the spread order of tabster attributes so that user tabster attributes win
Fixes #29798

fix: MenuTrigger should let user override tabster attributes

---

rfcs/react-components/convergence/event-handlers-event-type.md

We encounter challenges when attempting to extend event types within callbacks without introducing breaking changes. This RFC offers potential solutions to manage such event type changes for both current stable components and future components.
[**Preview**](https://github.com/YuanboXue-Amber/fluentui/blob/event-rfc/rfcs/react-components/convergence/event-handlers-event-type.md)

RFC: Extending Event Handlers Event Typing

---

change/@fluentui-react-components-656db22e-187b-4f9c-824c-b4f38f7d0c88.json
change/@fluentui-react-overflow-b5541fe4-22bc-4699-a14a-fc7f22039bc4.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts
packages/react-components/react-overflow/etc/react-overflow.api.md
packages/react-components/react-overflow/src/index.ts
packages/react-components/react-overflow/src/useOverflowVisibility.test.tsx
packages/react-components/react-overflow/src/useOverflowVisibility.ts

Exports a hook that returns the visibility state of every single overflow item and group. This hook can be useful when the overflow menu does not contain the invidivual items but some other view derived from the state of overflow items

feat: implement useOverflowVisibility hook

---

packages/react-components/react-motions-preview/etc/react-motions-preview.api.md
packages/react-components/react-motions-preview/src/atoms/fade.ts
packages/react-components/react-motions-preview/src/atoms/index.ts
packages/react-components/react-motions-preview/src/atoms/scale.ts
packages/react-components/react-motions-preview/src/atoms/slide.ts
packages/react-components/react-motions-preview/src/atoms/tokens.ts
packages/react-components/react-motions-preview/src/index.ts
packages/react-components/react-motions-preview/src/types.ts

Add motion definitions for "atoms" (naming is WIP and will be discussed) powered by [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API).
Definitions are ported from v0 as a boilterplate and might/will change in future.
Related to #29825.

feat(react-motions): add atoms defined with WAAPI

---

packages/react-components/react-table/stories/Table/ResizableColumnsControlled.stories.tsx

Example-only fix
The remove column buttons were `<span>` elements that were not activatable with the keyboard or with a screen reader.
The buttons are exposed as buttons with unique accessible names.
I switching over to the Fluent `<Button>` control, I also tweaked the styles and spacing (previously the sort icon for the smallest column would overlap with the remove button).
- Fixes #28242

fix: v9 Table example: expose resizable column remove buttons as buttons

---

packages/react-components/react-motions-preview/etc/react-motions-preview.api.md
packages/react-components/react-motions-preview/src/atoms/fade.ts
packages/react-components/react-motions-preview/src/atoms/scale.ts
packages/react-components/react-motions-preview/src/atoms/slide.ts

Renames exports of motion atoms, so they could be accessed as `atoms.fade.enterSlow()` instead of `atoms.fade.fadeEnterSlow()`.

chore(react-motions): rename exports for atoms

---

packages/react-components/react-motions-preview/etc/react-motions-preview.api.md
packages/react-components/react-motions-preview/package.json
packages/react-components/react-motions-preview/src/factories/createAtom.test.tsx
packages/react-components/react-motions-preview/src/factories/createAtom.ts
packages/react-components/react-motions-preview/src/hooks/useIsReducedMotion.test.tsx
packages/react-components/react-motions-preview/src/hooks/useIsReducedMotion.ts
packages/react-components/react-motions-preview/src/index.ts
packages/react-components/react-motions-preview/stories/CreateAtom/CreateAtom.stories.tsx
packages/react-components/react-motions-preview/stories/CreateAtom/index.stories.ts

Adds `createAtom()` factory to animate motion atoms (static motions) defined for [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API).
```tsx
import { createAtom } from '@fluentui/react-motions-preview'
const FadeEnter = createAtom(atoms.fade.enterSlow());
return (
<FadeEnter>
<div />
</FadeEnter>
)
}
```
Related to #29821.

feat(react-motions): implement createAtom() factory

---

packages/react-components/react-motions-preview/etc/react-motions-preview.api.md
packages/react-components/react-motions-preview/src/atoms/fade.ts
packages/react-components/react-motions-preview/src/atoms/scale.ts
packages/react-components/react-motions-preview/src/atoms/slide.ts

To create a motion definition, it's required to pass a param:
```ts
atoms.fade.enterSlow({});
```
The param is optional:
```ts
atoms.fade.enterSlow();
```
Related to #29821.

fix(react-motions): make params in atoms optional

---

change/@fluentui-react-checkbox-bfbbe47e-a607-48ae-961e-2dbbb79631e1.json
packages/react-components/react-checkbox/src/components/Checkbox/useCheckboxStyles.styles.ts

Checkbox styles use the child selector `['> .${checkboxClassNames.indicator}']` to set the indicator color based on the hover/selected state of the root slot. This makes it more difficult for users to override the styles.
Set the indicator colors using CSS variables on the Checkbox root, and the indicator slot's reset styles reference the CSS variables. Existing style overrides should continue to work, as the new styles have lower specificity.
- Fixes #29778

fix: Replace child selectors with css vars in Checkbox styles

---

change/@fluentui-react-combobox-1097190e-19df-46b4-a56c-1a9ca1181ca6.json
packages/react-components/react-combobox/src/utils/useTriggerListboxSlots.ts

Combobox/Dropdown would ignore the next blur when the listbox is clicked to prevent it immediately closing while trying to click an option. However, clicking a scrollbar does not blur the input/button, so it would ignore the next blur and prevent it from closing when genuinely clicking outside the listbox.
IgnoreBlur is set to false on mouseUp, which guarantees it'll only ignore a blur that occurs between a single mousedown/mouseup.
- Fixes #29701

fix: Listbox closes on blur after scrollbar click

---

change/@fluentui-react-text-77e036bf-9a93-4a5f-989f-554ee88420a1.json
packages/react-components/react-text/etc/react-text.api.md
packages/react-components/react-text/src/components/Text/Text.types.ts

`Text` component only supports `'span' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'pre'`
1. adds support to `'strong' | 'b' | 'em' | 'i'` to `Text` component
> Note: this is not a breaking change! As the additional elements being added do not modify the current signature, as all those elements signatures (`React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>`) are already included on the current supported one
- Fixes https://github.com/microsoft/fluentui/issues/29749

feature(react-text): adds semantic elements (strong, b, em, i) to Text root signature

---

change/@fluentui-react-combobox-33ead5c4-7eb4-47ca-bc9f-49ba7aaa8db7.json
packages/react-components/react-combobox/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
packages/react-components/react-combobox/src/components/Dropdown/useDropdown.tsx

Safari has a longstanding behavior where it does not focus links and buttons when they are clicked. For Dropdown, this means that keyboard navigation doesn't work after opening them with a mouse, and that they don't close when clicking outside of the dropdown (since there is no blur event).
The button has an explicit tabindex, which allows it to get focus when clicked in Safari
- Fixes #29576

fix: v9 Dropdown in Safari gets focus when clicked

---

change/@fluentui-react-positioning-c9eff939-b458-40c9-b61f-f2017ca21de2.json
packages/react-components/react-positioning/src/middleware/matchTargetSize.test.ts
packages/react-components/react-positioning/src/middleware/matchTargetSize.ts

Floating UI middleware data is only typed for its own middleware and there is also no way to type it with user specific middleare data.
This PR fixes an error with destructuring middleware data so that the flag to avoid infinite reset loop is destructured correctly. Also updates the test to use the correct middleware data.

fix: Infinite reset loop in matchTargetSize middleware

---

packages/react-components/react-menu/stories/Menu/index.stories.tsx
packages/react-components/react-menu/stories/MenuList/index.stories.tsx

Adds `Menu` subcomponents to props table:
Fixes #29309

docs(react-menu): add subcomponents to props table

---

packages/react-components/react-storybook-addon-export-to-sandbox/src/sandbox-factory.ts
packages/react-components/react-storybook-addon-export-to-sandbox/src/sandbox-utils.ts

Switching between themes would make additional `Open in CodeSandbox` buttons to be prepended to each story container.
We now make sure that only one `Open in CodeSandbox` button exists at any time in the container.
- Fixes #29846

fix: Preventing multiple 'Open in CodeSandbox' buttons being added when switching themes

---

change/@fluentui-react-components-53e298a8-94c2-4760-ad6b-4f62f876b949.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts

`react-tabster`'s `useFocusVisible()` hook was not re-exported from `react-components`
`useFocusVisible()` is exported from `react-components`.
This helps teams using [HeadlessProvider](https://github.com/microsoft/fluentui-contrib/tree/main/packages/react-headless-provider) as they do not need to take a separate dependency on `react-tabster`.

feat: add useFocusVisible() to exports

---

.github/CODEOWNERS

Adding teams-prg to combobox as temporary owners to implement some perf and improved composability changes to the package.
These changes were discussed with @smhigley
Addresses https://github.com/microsoft/fluentui/issues/26652

chore: Add teams-prg as owners to combobox

---

change/@fluentui-react-table-dc4edf49-9bab-4948-9b2e-65636d70ef4c.json
packages/react-components/react-table/src/components/TableRow/useTableRowStyles.styles.ts

Fixes the background colour of the brand TableRow appearance when pressed.
Before
After
Fixes #29445

fix: Brand row appearance should be brandBackground2 in pressed state

---

change/@fluentui-react-menu-95a114de-8688-4d5e-8c26-30da9afd2e00.json
packages/react-components/react-menu/src/components/MenuItem/useMenuItemStyles.styles.ts

The correct color were not being used when a `MenuItem` was pressed, as specified by the design spec.
The correct colors are used when a `MenuItem` is pressed, as specified by the design spec.
- Fixes #29950

fix: Using correct colors when MenuItem is pressed

---

change/@fluentui-react-charting-35073061-577a-4d9f-a0fd-b90a60995009.json
packages/react-charting/src/components/CommonComponents/CartesianChart.base.tsx
packages/react-charting/src/utilities/utilities.ts

Since the dataset consists of integral values only, the y axis ticks should also be constrained to integral values.
- Fixes #26383

Enforce integer y axis ticks for integral datasets

---

.github/workflows/create-milestone.yml

- Create milestone workflow has been quietly broken all year due to invalid date syntax use: https://github.com/microsoft/fluentui/actions/workflows/create-milestone.yml
- the `-v` option used by the `due_on` variable is only available for the MacOS version of the `date` command which is why it kept failing in our github actions workflow which uses Linux. Using comparable `-d` option instead which generates the same expected date (last day of current month) and format.
**Example**: 
- Follow up to #26149

fix: create-milestone workflow works again

---

change/@fluentui-react-timepicker-compat-preview-251d04e7-2406-47f7-bf91-521709b2008d.json
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/useTimePickerStyles.styles.ts

fix #29882 
Combobox by default has 80vh maxHeight for listbox. This PR uses `min(80vh, 416px)` for TimePicker, showing maximum 12 item instead of a long list in large viewport:

fix(TimePickerCompat): adjust max-height on listbox

---

change/@fluentui-react-portal-757b09a6-46f6-4e6f-beca-09f6c25b1022.json
packages/react-components/react-portal/src/components/Portal/Portal.test.tsx
packages/react-components/react-portal/src/components/Portal/usePortal.ts

Currently a portal can be mounted in a DOM parent of its virtual parent span. This PR does a validation of this case and when it happens - does not set the virtual parent.
Fixes #29991

fix: Virtual parent cannot be the DOM child of mount node

---

packages/react-examples/src/react-charting/DonutChart/DonutChart.Dynamic.Example.tsx
packages/react-examples/src/react-charting/PieChart/PieChart.Dynamic.Example.tsx
packages/react-examples/src/react-charting/StackedBarChart/StackedBarChart.Dynamic.Example.tsx
packages/react-examples/src/react-charting/VerticalBarChart/VerticalBarChart.Dynamic.Example.tsx

Two solutions:
1. `alert` role: This role makes screen readers announce an element immediately after its addition to the DOM (using JavaScript). While this works in most browsers and screen readers, it must be used with extreme caution as it interrupts the screen reader's current output. It is used to communicate an important and usually time-sensitive message to the user. Alerts are assertive live regions. Setting `role="alert"` is equivalent to setting `aria-live="assertive"` and `aria-atomic="true"`. For reference: [ARIA: alert role - Accessibility | MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Alert_Role)
2. `aria-live` attribute (_implemented_): This attribute marks specific areas of the HTML as live regions, informing screen readers to announce dynamic …

Add narratable status for button actions in dynamic chart examples

---

change/@fluentui-react-avatar-a01f51ec-ec7e-4af1-ae1a-41557bd92668.json
change/@fluentui-react-components-76af5285-1f9e-46d0-984e-6ebe27c2824f.json
packages/react-components/react-avatar/etc/react-avatar.api.md
packages/react-components/react-avatar/src/components/AvatarGroupPopover/AvatarGroupPopover.tsx
packages/react-components/react-avatar/src/components/AvatarGroupPopover/index.ts
packages/react-components/react-avatar/src/components/AvatarGroupPopover/useAvatarGroupPopoverContextValues.ts
packages/react-components/react-avatar/src/index.ts
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts

The hook `useAvatarGroupPopoverContextValues` was missing from the exports causing issues when recomposing AvatarGroupPopover.
The hook is now exported in react-components and react-avatar.

feat(react-avatar, react-components): Export missing useAvatarGroupPopoverContextValues hook

---

packages/react-components/react-table/stories/DataGrid/CompositeNavigation.stories.tsx
packages/react-components/react-table/stories/DataGrid/CustomRowId.stories.tsx
packages/react-components/react-table/stories/DataGrid/Default.stories.tsx
packages/react-components/react-table/stories/DataGrid/FocusableElementsInCells.stories.tsx
packages/react-components/react-table/stories/DataGrid/MultipleSelect.stories.tsx
packages/react-components/react-table/stories/DataGrid/MultipleSelectControlled.stories.tsx
packages/react-components/react-table/stories/DataGrid/ResizableColumns.stories.tsx
packages/react-components/react-table/stories/DataGrid/SelectionAppearance.stories.tsx
packages/react-components/react-table/stories/DataGrid/SingleSelect.stories.tsx
packages/react-components/react-table/stories/DataGrid/SingleSelectControlled.stories.tsx
packages/react-components/react-table/stories/DataGrid/SubtleSelection.stories.tsx

Simple example-only fix.
Eventually, we likely want to auto-add an accName for the checkbox based on the first gridcell's text, but this at least demos how to manually add one in our examples.
- Fixes an ADO a11y issue

fix: DataGrid stories should add an accName to the checkbox

---

change/@fluentui-react-aria-aa625e96-b6ea-4a15-9d18-ae66a8bf4577.json
packages/react-components/react-aria/src/activedescendant/useActiveDescendant.ts

During the change to the next active descendant, check if it needs to be scrolled into view and do so.
Addresses #26652

feat(useActiveDescendant): Changing active descendant scrolls into view

---

packages/react-components/react-motions-preview/etc/react-motions-preview.api.md
packages/react-components/react-motions-preview/src/factories/createAtom.test.tsx
packages/react-components/react-motions-preview/src/factories/createAtom.ts
packages/react-components/react-motions-preview/src/factories/createPresence.test.tsx
packages/react-components/react-motions-preview/src/factories/createPresence.ts
packages/react-components/react-motions-preview/src/motions/atom/fade.ts
packages/react-components/react-motions-preview/src/motions/atom/scale.ts
packages/react-components/react-motions-preview/src/motions/atom/slide.ts
packages/react-components/react-motions-preview/src/types.ts
packages/react-components/react-motions-preview/stories/Motion/CustomAtom.stories.md
packages/react-components/react-motions-preview/stories/Motion/CustomAtom.stories.tsx
packages/react-components/react-motions-preview/stories/Motion/TokensUsage.stories.tsx

This PR change the signature of `AtomMotion`:
```ts
export type AtomMotion = {
keyframes: Keyframe[];
options: KeyframeEffectOptions;
}
// ⬇️⬇️⬇️
export type AtomMotion = { keyframes: Keyframe[] } & KeyframeEffectOptions;
```
This makes overrides easier, for example:
```tsx
const fadeEnterSlow = atom.fade.enterSlow();
const motion = {
keyframes: fadeEnterSlow.keyframes,
options: {
...fadeEnterSlow.options,
duration: 3000,
}
}
// ⬇️⬇️⬇️
const motion = {
...atom.fade.enterSlow(),
duration: 3000,
}
```

chore(react-motions): flatten AtomMotion type

---

change/@fluentui-react-drawer-485bb1fe-e874-4cb7-934c-6a0a7dfe36a3.json
packages/react-components/react-drawer/etc/react-drawer.api.md
packages/react-components/react-drawer/src/components/OverlayDrawer/OverlayDrawer.test.tsx
packages/react-components/react-drawer/src/components/OverlayDrawer/OverlayDrawerSurface/OverlayDrawerSurface.types.ts

this fixes an api regression, and re-adds `moutNode` to `OverlayDrawer` (note: this is a type fix, the functionality was already there)
re-adds `mountNode` via `DialogSurfaceProps`, and adds a test to prevent future regressions
- Fixes #29819

fix: react-drawer dropped mountNode prop in types

---

apps/stress-test/src/renderers/wc/btn/wcBasicButton.ts
packages/merge-styles/etc/merge-styles.api.md
packages/merge-styles/src/EventMap.ts
packages/merge-styles/src/Stylesheet.ts
packages/merge-styles/src/cloneCSSStyleSheet.ts
packages/merge-styles/src/index.ts
packages/react-charting/src/components/LineChart/__snapshots__/LineChartRTL.test.tsx.snap
packages/react-examples/src/react/ShadowDOM/ShadowHelper.tsx
packages/utilities/package.json
packages/utilities/src/shadowDom/MergeStylesRootContext.tsx
packages/utilities/src/shadowDom/MergeStylesShadowRootContext.tsx

Shadow DOM styles would not work for browsers that do not support `adoptedStylesheets`.
Shadow DOM styling works for all browsers in Fluent's browser support matrix. Additionally, we now prefer the latest version of the `adoptedStylesheets` spec which allows the array to be mutated. Previously a new array had to be set to update `adoptedStylesheets`. [Using this updated spec also works around a Safari bug](https://github.com/microsoft/fast/pull/6703).
For browsers that do not support adoptedStylesheets/constructable stylesheets we implement a polyfill that copies styles into `<style>` tags inside appropriate shadow roots. Effectively, this produces the same result as using adoptedStylesheets as elements within the shadow root are styled correctly and the styles are scoped to the shadow …

`merge-styles` `adoptedStylesheets` polyfill

---

change/@fluentui-react-timepicker-compat-preview-e00eec8c-e418-48de-bb0d-69bbcde82dc2.json
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/timeMath.test.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/timeMath.ts

Time is always formatted as `h23` format
Time is formatted according to locale
#30020

fix(TimePickerCompat): remove default time format

---

change/@fluentui-react-dialog-40d163d8-a0f0-45b2-b2fc-f62d77715206.json
packages/react-components/react-dialog/src/components/Dialog/renderDialog.tsx

See link: https://codesandbox.io/p/sandbox/recursing-wiles-4llpxn?file=%2Fsrc%2Fexample.tsx%3A47%2C42
Previously if the Dialog was rendered at the same time it was set to open, the transition would not happen.
@layershifter had a hunch that it could be as easy as adding `appear` prop, which turned out to be the case:https://reactcommunity.org/react-transition-group/transition#Transition-prop-appear
If the Dialog is rendered and opened, the transition/animation happens properly.
- Fixes #30043

fix: Dialog now transitions in on first render

---

change/@fluentui-react-link-0346db3c-ee8d-4d9e-b3a9-0c785ab3c830.json
packages/react-components/react-link/src/components/Link/Link.test.tsx
packages/react-components/react-link/src/components/Link/useLink.ts

User-provided `role` and `type` props would not be respected and would instead be overridden by the specified defaults.
All user-provided props are now respected, and unit tests have been added so that this behavior does not regress in the future.
- Fixes #30052

fix: User-provided props win over defined defaults in Link component

---

change/@fluentui-azure-themes-deca1b96-b8f7-45cf-9c2b-c8638dd68357.json
packages/azure-themes/src/azure/AzureColors.ts
packages/azure-themes/src/azure/styles/ChoiceGroupOptions.styles.ts
packages/azure-themes/src/azure/styles/DetailsList.styles.ts
packages/react-examples/src/azure-themes/stories/Themes/Themes.stories.tsx
packages/react-examples/src/azure-themes/stories/components/DetailsListCustomColumnsExample.stories.tsx
packages/react-examples/src/azure-themes/stories/components/choiceGroupWithImagesandIcons.stories.tsx

Choicegroup with icon / image bug
DetailsList selected and selected+hover link is not passing accessibility 
- Fixes #

Azure Theme  bug fixes for DetailsList with Link, and ChoiceGroup with Icon/Image

---

change/@fluentui-react-accordion-f79e18b9-613d-4ee0-898d-30372d1f65b8.json
change/@fluentui-react-aria-672ea03e-6cd4-4630-a349-bb8c065fbeaf.json
change/@fluentui-react-button-167d39fa-0523-4509-ad7b-f823f8cbafbb.json
change/@fluentui-react-table-890d6433-950c-4907-8f9d-66111412e0e5.json
packages/react-components/react-accordion/src/components/AccordionHeader/useAccordionHeader.tsx
packages/react-components/react-aria/etc/react-aria.api.md
packages/react-components/react-aria/src/button/useARIAButtonProps.test.tsx
packages/react-components/react-aria/src/button/useARIAButtonShorthand.test.tsx
packages/react-components/react-aria/src/button/useARIAButtonShorthand.ts
packages/react-components/react-aria/src/index.ts
packages/react-components/react-aria/stories/useARIAButton/index.stories.tsx
packages/react-components/react-button/src/components/Button/useButton.ts
packages/react-components/react-table/src/components/TableHeaderCell/useTableHeaderCell.tsx

With the new slot API, the `useARIAButtonShorthand` method becomes obsolete as it does more than it should.
This PR is preemptive of https://github.com/microsoft/fluentui/pull/29646 , which will deprecate `resolveShorthand`.
1. deprecates `useARIAButtonShorthand`
2. uses `useARIAButtonProps` instead
- Fixes #

feat: deprecates `useARIAButtonShorthand` in favor of new slot API compliant method

---

change/@fluentui-react-breadcrumb-2228ee26-b0d3-42d8-af23-5e24fc4f605d.json
packages/react-components/react-breadcrumb/src/utils/partitionBreadcrumbItems.test.ts
packages/react-components/react-breadcrumb/src/utils/partitionBreadcrumbItems.ts

endDisplayedItems is incorrect when numberOfItemsToHide <= 0
- Fixes #

fix:  partitionBreadcrumbItems miscalculated endDisplayedItems

---

change/@fluentui-react-components-623f5d14-335e-4a2a-aba0-b051b8cdb004.json
packages/react-components/react-components/package.json

Adds `wyw-in-js` field to `package.json` to support styles processing with WyW-in-JS compiler (https://wyw-in-js.dev/). The plan is to use this compiler for Vite/esbuild plugins (https://github.com/microsoft/griffel/pull/41) and later switch our Webpack loader to it (https://github.com/microsoft/griffel/pull/414).
The same change in Griffel, https://github.com/microsoft/griffel/pull/475.

chore(react-components): add "wyw-in-js" field for tag processor

---

change/@fluentui-react-card-45d09ab1-d545-47c9-81ab-cae4186e799f.json
packages/react-components/react-card/src/components/Card/useCard.ts

This PR fixes a regression with the card component
The focus ring was not visible and keyboard navigation was compromised
Focus ring is visible when tabbing from one card to the other

fix(react-card): interactive cards not having the focus ring when focused

---

packages/react-components/react-infobutton/docs/Spec.md
packages/react-components/react-infolabel/docs/Spec.md
packages/react-components/react-menu/docs/Spec.md
packages/react-components/react-persona/docs/Spec.md
packages/react-components/react-radio/docs/Spec.md
packages/react-components/react-table/docs/Spec.md

Images on various spec files are broken:
Use the correct relative path instead:
- ~~Fixes #~~ Haven't found one

docs: fix links to images in specs

---

change/@fluentui-react-positioning-d0679179-03e3-47de-b4ff-4810ed017ac3.json
packages/react-components/react-positioning/src/createArrowStyles.ts
packages/react-components/react-positioning/src/createSlideStyles.ts

We found a collision of the use of the `--angle` CSS variable in Fluent AI, as it was being used by both `flair` in Fluent AI and `positioning` in Fluent UI. We proceeded to add a namespace to CSS variables in Fluent AI.
This PR adds a namespace to CSS variables inside of the `react-positioning` package to avoid potential collisions when used in conjunction with other packages/in custom code.
- Follow-up from https://github.com/microsoft/fluentai/pull/1268.

fix: Add a namespace to CSS variables in react-positioning package to avoid potential collisions

---

change/@fluentui-react-charting-209f77d4-492f-4ffe-948f-1bd8220ff566.json
packages/react-charting/src/components/AreaChart/AreaChartRTL.test.tsx
packages/react-charting/src/components/LineChart/LineChart.base.tsx
packages/react-charting/src/components/LineChart/LineChartRTL.test.tsx
packages/react-charting/src/components/LineChart/__snapshots__/LineChart.test.tsx.snap
packages/react-charting/src/components/LineChart/__snapshots__/LineChartRTL.test.tsx.snap
packages/react-charting/src/components/VerticalBarChart/VerticalBarChartRTL.test.tsx

No accessibility tests were added for AreaChart, LineChart, VerticalBarChart under react-charting
Accessibilty test has been added with the help of jest-axe.
- Fixes #

Accessibility tests added to AreaChart, LineChart, VerticalBarChart

---

change/@fluentui-react-timepicker-compat-preview-925158c3-8c51-4e6d-b2a0-41d8901dd0fe.json
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.cy.tsx
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/useTimePicker.tsx

Press letter key in TimePicker input can navigate among item in listbox, but it is case sensitive.
The navigation is now case insensitive.
#29824

fix(TimePickerCompat): letter key navigation should be case insensitive

---

change/@fluentui-react-tabster-c2d3df02-d2f4-4671-a204-7585b3e81fff.json
packages/react-components/react-tabster/src/focus/createFocusOutlineStyle.ts

Sets the border colour to be `Highlight` for the standard pseudoselector based focus outline.
Before
After

fix: focus outline should have `Highlight` colour in high contrast

---

change/@fluentui-react-timepicker-compat-preview-1e940c43-3126-4f50-ac72-9404932eec88.json
packages/react-components/react-timepicker-compat-preview/package.json
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.test.tsx
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/useTimePicker.tsx

When `TimePicker` is used in `Field`, it should use Field's label for chevron icon:

fix(TimePickerCompat): provide default aria-labelledby on chevron icon when it is wrapped in Field

---

change/@fluentui-react-charting-8bd430b6-3359-4e93-86ee-92b22540b88c.json
packages/react-charting/src/utilities/utilities.ts

1. RTL Mode- Due to width issue yAxis was showing only "String" which appeared same but the other part of the word was hidden.
2.RTL Mode-  Text was trucating in reverse manner
1. yAxis same issue fixed
2. text truncation issue fixed
#29979 
#29978 
- Fixes #

fix: Horizontal chart with axis yaxis same label and truncation fixed

---

change/@fluentui-react-positioning-cfff7233-c764-432c-9a6d-bee9da68142d.json
packages/react-components/react-positioning/package.json
packages/react-components/react-positioning/src/usePositioning.ts
packages/react-components/react-positioning/src/utils/devtools.ts
yarn.lock

Follow up on https://github.com/floating-ui/floating-ui/pull/2653
1. moves from `floating-ui-devtools`, which is based on personal repo  https://github.com/bsunderhus/floating-ui-devtools
2. to `@floating-ui/devtools` which is based in official floating ui repo

chore(react-positioning): move from floating-ui-devtools to @floating-ui/devtools

---

packages/react-components/react-nav-preview/src/components/NavLink/renderNavLink.tsx
packages/react-components/react-nav-preview/src/components/NavLink/useNavLink.ts
packages/react-components/react-nav-preview/src/components/NavLinkGroup/renderNavLinkGroup.tsx
packages/react-components/react-nav-preview/src/components/NavLinkGroup/useNavLinkGroup.ts

`NavLink` and `NavLinkGroup` is using `getSlotsNext`
Migrate to new slot API as the old one will be deprecated
- Fixes #

bugfix(react-nav): slots should be declared with new slot API

---

tools/workspace-plugin/src/generators/tsconfig-base-all/index.ts

When executed via `--verify` flag, `tsconfig.base.all.json` file wasn't checked for consistency but instead doing nothing, it always wrote updated file to disk.
Because how lage works (understands project graph), this action resulted in marking every project within monorepo on every PR as affected, thus triggering whole build/test/lint pipeline for everything.
- `--verify` doesn't write anything to disk
- this **fix speeds up `BuildTestLint` pipeline** from [49min](https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=328777&view=logs&j=1e96f989-784f-546f-05bb-8f7d8dfe5399) to [15min](https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=328882&view=logs&j=258ec178-2d8b-5611-7b9b-60c5c95dae55) /  **~69% FASTER 🚅🚀**
- > this depends on your changes within …

fix(workspace-plugin): don't write changes on disk with `--verify` flag within tsconfig-base-all generator

---

packages/react-components/react-tree/stories/Tree/Virtualization.stories.tsx

1. stop using `getSlots` into `Virtualization` documentation, use `assertSlots` instead
Unblocks https://github.com/microsoft/fluentui/pull/29646

chore(react-tree): stop using old slot API on stories

---

change/@fluentui-react-combobox-0fdf2a9f-1e39-479d-abdb-d49e9a4c836a.json
packages/react-components/react-combobox/src/components/Option/useOptionStyles.styles.ts

Fix #29367 - match Combobox high contrast style to figma:
| | before | after |
|----|----|---|
| hover | <img width="321" alt="image" src="https://github.com/microsoft/fluentui/assets/28751745/d8bea622-0837-45b0-acca-064cd2038040">| <img width="299" alt="image" src="https://github.com/microsoft/fluentui/assets/28751745/574f3442-ac61-4861-accc-2c6b33ff7307">|
|multi-select hover and disabled | <img width="290" alt="image" src="https://github.com/microsoft/fluentui/assets/28751745/c42ff4f2-28b2-4622-8a03-1014e2ef3cdf"> | <img width="268" alt="image" src="https://github.com/microsoft/fluentui/assets/28751745/9691962a-ddcb-4fde-ab59-fff294d47c7a"> | 
| multi-select hover selected | <img width="275" alt="image" src="https://github.com/microsoft/fluentui/assets/28751745/2fea19b5-29f6-4750-898f-f …

fix(Combobox): make high contrast hover color accessible

---

change/@fluentui-react-breadcrumb-65d8fcef-c70f-4b03-ace4-69630ba9af7c.json
packages/react-components/react-breadcrumb/src/components/BreadcrumbButton/useBreadcrumbButtonStyles.styles.ts

BreadcrumbButton focus had incorrect border width and transition

fix(breadcrumb): BreadcrumbButton focus border has incorrent width and transition

---

packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverTitle/renderTeachingPopoverTitle.tsx

1. Stop using old slot API `getSlotsNext` in favor of new `asserSlots` API
Unblocks https://github.com/microsoft/fluentui/pull/29646

chore(react-teaching-popover): stop using old slot API

---

apps/public-docsite-v9/package.json
change/@fluentui-react-teaching-popover-preview-7c3a0833-d4f9-4b31-bc9f-e526c7c40c83.json
packages/react-components/react-teaching-popover-preview/package.json

The `@fluentui/react-teaching-popover-preview` package was not published.
Publish the preview package using the command:
```
yarn nx generate prepare-initial-release --project @fluentui/react-teaching-popover-preview --phase=preview
```
- #26639

feat: Release react-teaching-popover-preview package

---

change/@fluentui-react-datepicker-compat-b867d463-16c5-49d2-a28e-ac6dd307c83c.json
packages/react-components/react-datepicker-compat/project.json
tools/workspace-plugin/src/generators/prepare-initial-release/index.spec.ts
tools/workspace-plugin/src/generators/prepare-initial-release/index.ts
tools/workspace-plugin/src/generators/prepare-initial-release/schema.json
tools/workspace-plugin/src/generators/prepare-initial-release/schema.ts

[v9 `compat` family](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-datepicker-compat/README.md#compat-component) of packages have no automation for preparing initial release.
prepare-initial-release now supports `--phase=compat` which will prepare COMPAT package for initial release ( making it publicly available on our docsite as well )
- Fixes #

feat(workspace-plugin): add `phase=compat` support to prepare-initial-release generator

---

tools/workspace-plugin/src/generators/react-component/files/story/index.stories.tsx__tmpl__
tools/workspace-plugin/src/generators/react-component/index.spec.ts
tools/workspace-plugin/src/generators/react-component/index.ts

`nx g react-component` will always bootstrap `index.stories.tsx` with title `Preview Components/....`
`index.stories.tsx`  title is created based on package phase(preview or stable or compat)
- Follows https://github.com/microsoft/fluentui/pull/30150

feat(workspace-plugin): setup storybook barrel file based on package phase(type) within react-component generator

---

packages/react-components/react-tree/stories/Tree/Virtualization.stories.tsx
scripts/test-ssr/src/commands/main.ts
scripts/test-ssr/src/utils/getExportFromFile.ts
scripts/test-ssr/src/utils/visitPage.ts

Follow up for #30123.
- Updates the part of SSR tests that get stories exports to avoid JSX transforms, so there will be no pragma-related errors
- Fixes the story introduces in #30123
- Adds error intercepting for HTML rendering (aka SSR part)

fix(test-ssr): do not transform JSX in preparation stage

---

packages/react-examples/src/react/TimePicker/TimePicker.DateTimePicker.Example.tsx

Though a label text is visible on screen we cannot use `aria-labelledby` and point to it to resolve the `accessibility` issue. Hence, added `aria-label` for `DatePicker` and `TimePicker` components separately.
As mentioned in the issue #27817 - when focus moves to button on TimePicker in "TimePicker with DatePicker", the button is announced as "button" with no context of labels or description.
As also mentioned in the issue #27817 - when focus moves to button on TimePicker in "TimePicker with DatePicker", the button should be announced with context or a description of what the button is/does.
- Fixes: #27817

fix(27817): VoiceOver announcing dropdown for Timepicker as button

---

change/@fluentui-react-combobox-cea228ea-becc-4f56-b04f-1e6d5b72916d.json
packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx
packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx
packages/react-components/react-combobox/src/components/Dropdown/Dropdown.test.tsx
packages/react-components/react-combobox/src/components/Dropdown/useDropdown.tsx
packages/react-components/react-combobox/src/utils/ComboboxBase.types.ts
packages/react-components/react-combobox/src/utils/useComboboxBaseState.ts
packages/react-components/react-combobox/src/utils/useTriggerSlot.ts

Follow up fix from #30010
Previously `hasFocus` and `setHasFocus` were deprecated incorrectly. This caused a regressions since the Combobox/Dropdown should actually mount a listbox with `display: none` when focused.
Also adds a test and docstring to prevent future regression

fix: trigger focus should mount hidden listbox

---

change/@fluentui-react-components-65d7d4e7-165f-4208-927d-38b6bce56795.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts

OptionOnSelectData and SelectionEvents are not exported by @fluentui/react-components.
Currently only @fluentui/react-combobox exports them.
@fluentui/react-components also exports them, like the other combobox types.
Improves the developer experience.

Export combobox selection types

---

change/@fluentui-react-charting-6741ba08-9ad2-46d0-90a6-298da205529f.json
packages/react-charting/etc/react-charting.api.md
packages/react-charting/src/components/CommonComponents/CartesianChart.types.ts
packages/react-charting/src/components/DonutChart/Arc/Arc.tsx
packages/react-charting/src/components/DonutChart/DonutChart.base.tsx
packages/react-charting/src/components/DonutChart/Pie/Pie.tsx
packages/react-charting/src/components/GaugeChart/GaugeChart.base.tsx
packages/react-charting/src/components/HeatMapChart/HeatMapChart.base.tsx
packages/react-charting/src/components/PieChart/Arc/Arc.tsx
packages/react-charting/src/components/PieChart/Pie/Pie.tsx
packages/react-charting/src/components/SankeyChart/SankeyChart.base.tsx
packages/react-charting/src/types/IDataPoint.ts
packages/react-charting/src/utilities/utilities.ts

We imported the entire d3 library even though we only used a few of its functions.
Adhering to best practices by importing solely the functions utilized in the charting library. We will also monitor whether this affects the bundle size.
- Fixes #

 Importing functions which are used instead of importing complete library

---

packages/react-examples/src/react/ShadowDOM/ShadowDOM.TeachingBubble.ButtonOrder.Example.tsx
packages/react-examples/src/react/ShadowDOM/ShadowDOM.TeachingBubble.Condensed.Example.tsx
packages/react-examples/src/react/ShadowDOM/ShadowDOM.TeachingBubble.Illustration.Example.tsx
packages/react-examples/src/react/ShadowDOM/ShadowDOM.TeachingBubble.MultiStep.Example.tsx
packages/react-examples/src/react/ShadowDOM/ShadowDOM.TeachingBubble.SmallHeadline.Example.tsx
packages/react-examples/src/react/ShadowDOM/ShadowDOM.TeachingBubble.Wide.Example.tsx
packages/react-examples/src/react/ShadowDOM/ShadowDOM.TeachingBubble.WideIllustration.Example.tsx
packages/react-examples/src/react/ShadowDOM/ShadowDOM.doc.tsx
packages/utilities/package.json

We only had a single `TeachingBubble` shadow DOM example.
All `TeachingBubble` examples are demonstrated in shadow DOM.
A partner has specific need for this control in shadow DOM. Adding these examples helps us validate correctness.

docs: add shadow DOM TeachingBubble examples

---

packages/merge-styles/etc/merge-styles.api.md
packages/merge-styles/src/Stylesheet.ts
packages/merge-styles/src/cloneCSSStyleSheet.ts
packages/merge-styles/src/index.ts
packages/utilities/etc/utilities.api.md
packages/utilities/package.json
packages/utilities/src/shadowDom/MergeStylesRootContext.tsx
packages/utilities/src/shadowDom/MergeStylesShadowRootContext.tsx

Adopted stylesheets were always appended to `adoptedStylesheets`.
Adopted stylesheets are now given a sort order (the order in which they were created by `merge-styles`) and this order is maintained (from low to high) whenever sheets are adopted.
- Fixes #30080

chore: maintain style sheet sort order for all shadow roots

---

apps/ts-minbar-test-react-components/src/index.ts

every pipeline affecting v9 will fail on TS violation
example log: https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=329938&view=logs&j=e51d397b-0a7b-5b89-4b48-0052e021371d&t=88c41216-94ff-5ca8-d686-48ce16c1eefc
unblocks all our pipelines until this is fixed https://github.com/microsoft/keyborg/issues/69
- Fixes #

fix(ts-minbar-test-react-components): temporarily resolve keyborg to 2.3.0 which will pass TS check

---

change/@fluentui-react-utilities-16895967-8569-477b-9445-48da8bfd79a9.json
packages/react-components/react-utilities/src/compose/constants.ts
packages/react-components/react-utilities/src/compose/isSlot.test.tsx

Some complex projects might end up with multiple instances (not necessarily from different versions) of `react-utilities`.
In that case, `isSlot` will `erroneously` return false, causing react to throw the following error when rendering the slots.
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. 
```
#29434 added a warning on cases like this, but in large systems it's not always easy to fix.
As described in that PR, this is due to the fact Symbols are unique and having different instances of `react-utilities` running means having multiple Symbols.
Moving from `Symbol` to [`Symbol.for`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for) will share the …

fix(react-utilities): Allow `isSlot` to work with multiple utilities instances

---

change/@fluentui-react-table-40a21599-8cd7-4536-a99e-231b1f7c0c3a.json
change/@fluentui-react-tabster-741ff8ad-dac0-4784-902b-5b3eb8784832.json
packages/react-components/react-menu/src/components/MenuList/__snapshots__/MenuList.test.tsx.snap
packages/react-components/react-table/src/components/DataGrid/DataGrid.cy.tsx
packages/react-components/react-table/src/components/DataGrid/DataGrid.test.tsx
packages/react-components/react-table/src/components/DataGrid/__snapshots__/DataGrid.test.tsx.snap
packages/react-components/react-tabster/src/hooks/useArrowNavigationGroup.ts
packages/react-components/react-toolbar/src/components/Toolbar/__snapshots__/Toolbar.test.tsx.snap

Sets the `memorizeCurrent` option to be true by default  - after discussion with the team it was agreed that all controls with arrow key navigation should behave this way.
Fixes https://github.com/microsoft/fluentui/issues/30111

fix(useArrowNavigationGroup): should always memorize last focused element

---

change/@fluentui-react-positioning-29f6eb38-4af2-40f1-a095-6abef76d64f4.json
packages/react-components/react-components/stories/Concepts/Positioning/MatchTargetSize.stories.tsx
packages/react-components/react-components/stories/Concepts/Positioning/PositioningImperativePositionUpdate.stories.tsx
packages/react-components/react-menu/stories/Menu/MenuDefault.stories.tsx
packages/react-components/react-positioning/src/createPositionManager.ts
packages/react-components/react-positioning/src/utils/createResizeObserver.ts

Uses a ResizeObserver in the position manager so that a position update is triggered when the dimension of the target or container changes. This should handle most async update scenarios without needing to call `updatePosition` in userland.
The ResizeObserver will only be created when:
* both target and positioned element that refer to HTML elements
* the positionig logic is `enabled`
Practically this means that the ResizeObserver is created only when Popover/Menu/Combobox/Tooltip etc... are open. Just mounting an (unopened) Popover will not create a new ResizeObserver
Fixes #29998

feat: Update position when target or container dimensions change

---

apps/public-docsite-v9/package.json
apps/vr-tests-react-components/package.json
apps/vr-tests-react-components/src/stories/TimePicker.stories.tsx
change/@fluentui-react-timepicker-compat-44d079da-05f8-4e7e-ad30-fc70601e7267.json
change/@fluentui-react-timepicker-compat-preview-8dca177c-555d-4973-8aa1-5ea98786788c.json
packages/react-components/react-timepicker-compat-preview/etc/react-timepicker-compat-preview.api.md
packages/react-components/react-timepicker-compat-preview/package.json
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.cy.tsx
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.test.tsx
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.tsx
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/TimePicker.types.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/index.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/timeMath.test.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/timeMath.ts
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/useTimePicker.tsx
packages/react-components/react-timepicker-compat-preview/src/components/TimePicker/useTimePickerStyles.styles.ts
packages/react-components/react-timepicker-compat-preview/src/index.ts
packages/react-components/react-timepicker-compat-preview/stories/TimePicker/TimePickerControlled.stories.tsx
packages/react-components/react-timepicker-compat-preview/stories/TimePicker/TimePickerDefault.stories.tsx
packages/react-components/react-timepicker-compat-preview/stories/TimePicker/TimePickerFreeformCustomParsing.stories.tsx
packages/react-components/react-timepicker-compat-preview/stories/TimePicker/TimePickerFreeformWithErrorHandling.stories.tsx
packages/react-components/react-timepicker-compat-preview/stories/TimePicker/TimePickerWithDatePicker.stories.tsx
packages/react-components/react-timepicker-compat-preview/stories/TimePicker/index.stories.tsx
packages/react-components/react-timepicker-compat/package.json

Step 3 of #30198
After this PR, triggering a release will make react-timepicker-compat bump to 0.1.0, and show up on docsite as:

feat(TimePicker-compat): stable release 

---

scripts/gulp/src/tasks/docs.ts

see PR title
- Partially implements https://github.com/microsoft/fluentui/issues/30265

feat(scripts-gulp): replace lerna with nx

---

change/@fluentui-react-card-325187ac-9ed9-4045-bc3d-cab221a5cf74.json
packages/react-components/react-card/src/components/Card/Card.cy.tsx
packages/react-components/react-card/src/components/Card/useCard.ts
packages/react-components/react-card/src/components/Card/useCardSelectable.ts

Selectable cards were receiving focus attributes when `onClick` was provided.
Selectable cards are now not focusable to keep the focus on the internal selectable checkbox
- Fixes #30142

fix(react-card): selectable cards should not be focusable

---

change/@fluentui-react-card-8029d09b-3768-40f2-af72-ea3e8d708553.json
packages/react-components/react-card/src/components/Card/useCardStyles.styles.ts

Remove a slow CSS selector that was set sane defaults for inner children of cards. Since this "default" is the same as the browser already applies, this selector can be safely removed.
- Fixes #28281

fix(react-card): remove slow CSS selector from card styles

---

apps/vr-tests-react-components/src/stories/Positioning.stories.tsx
change/@fluentui-react-positioning-789c4f31-0af6-4da0-a7e3-0b9d6139defd.json
packages/react-components/react-positioning/src/createArrowStyles.ts

The fix is similar to #21354. The problem is that after https://github.com/kentcdodds/rtl-css-js/pull/66, `transform` value is also started to flip while it should not.
```json
{"transform":"rotate(var(--fui-positioning-angle)) translate(0, 50%) rotate(45deg)"}
```
```json
{"transform":"rotate(var(--fui-positioning-angle)) translate(0, 50%) rotate(-45deg)"}
```
Fixes #29944

fix(react-positioning): update styles to not flip in RTL

---

change/@fluentui-react-rating-preview-ae636206-2459-4510-b711-a7d79c21d554.json
packages/react-components/react-rating-preview/etc/react-rating-preview.api.md
packages/react-components/react-rating-preview/src/RatingDisplay.ts
packages/react-components/react-rating-preview/src/components/RatingDisplay/RatingDisplay.test.tsx
packages/react-components/react-rating-preview/src/components/RatingDisplay/RatingDisplay.tsx
packages/react-components/react-rating-preview/src/components/RatingDisplay/RatingDisplay.types.ts
packages/react-components/react-rating-preview/src/components/RatingDisplay/__snapshots__/RatingDisplay.test.tsx.snap
packages/react-components/react-rating-preview/src/components/RatingDisplay/index.ts
packages/react-components/react-rating-preview/src/components/RatingDisplay/renderRatingDisplay.tsx
packages/react-components/react-rating-preview/src/components/RatingDisplay/useRatingDisplay.ts
packages/react-components/react-rating-preview/src/components/RatingDisplay/useRatingDisplayStyles.styles.ts
packages/react-components/react-rating-preview/src/index.ts
packages/react-components/react-rating-preview/stories/RatingDisplay/RatingDisplayBestPractices.md
packages/react-components/react-rating-preview/stories/RatingDisplay/RatingDisplayDefault.stories.tsx
packages/react-components/react-rating-preview/stories/RatingDisplay/index.stories.tsx

This PR is to scaffold the `RatingDisplay` component. This is part of the work to split `Rating` into two components.
Fixes #30285

Scaffold RatingDisplay

---

apps/vr-tests-react-components/src/stories/DatePickerCompat.stories.tsx
change/@fluentui-react-datepicker-compat-30448161-6505-496a-926b-0b94582e4f4d.json
packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePickerStyles.styles.ts

`DatePicker`'s `Calendar` popup appears behind positioned elements when `inlinePopup={true`}.
The popup appears above positioned elements when `inlinePopup={true}`.
Adds a VR test to validate the behavior.
- Related #29185
- Fixes #30280

fix: set z-index: 1 when rendering DatePickerCompat inline

---

rfcs/react-components/components/combobox-spacebar.md

Adds an RFC around how space should behave and what options we should provide in the v9 Combobox component.
[RFC](https://github.com/microsoft/fluentui/blob/a35d2fb62b9769bd8817a32a9981275307ced96f/rfcs/react-components/components/combobox-spacebar.md)
Includes content from #27695

RFC: v9 Combobox spacebar behavior

---

change/@fluentui-react-table-5e2f49f6-00d8-4546-a260-5351fbb6a98f.json
packages/react-components/react-table/src/components/TableRow/useTableRowStyles.styles.ts

1. adds proper [system colors](https://drafts.csswg.org/css-color-4/#css-system-colors) on hover if [forced colors](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors) is active
- Fixes https://github.com/microsoft/fluentui/issues/30070

bugfix(react-table): add system colors on hover

---

change/@fluentui-react-combobox-057ab96a-491a-422f-8b6b-ee92954175ce.json
change/@fluentui-react-timepicker-compat-d303579a-543d-44b3-91c9-6902acb99b4e.json
change/@fluentui-react-timepicker-compat-preview-9339e124-bae0-4824-b7b0-7f9953091164.json
packages/react-components/react-combobox/config/tests.js
packages/react-components/react-combobox/etc/react-combobox.api.md
packages/react-components/react-combobox/package.json
packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx
packages/react-components/react-combobox/src/components/Combobox/Combobox.types.ts
packages/react-components/react-combobox/src/components/Combobox/__snapshots__/Combobox.test.tsx.snap
packages/react-components/react-combobox/src/components/Combobox/renderCombobox.tsx
packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx
packages/react-components/react-combobox/src/components/Combobox/useComboboxStyles.styles.ts
packages/react-components/react-combobox/src/components/Dropdown/Dropdown.test.tsx
packages/react-components/react-combobox/src/components/Dropdown/Dropdown.types.ts
packages/react-components/react-combobox/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
packages/react-components/react-combobox/src/components/Dropdown/renderDropdown.tsx
packages/react-components/react-combobox/src/components/Dropdown/useDropdown.tsx
packages/react-components/react-combobox/src/components/Dropdown/useDropdownStyles.styles.ts
packages/react-components/react-combobox/src/utils/ComboboxBase.types.ts
packages/react-components/react-combobox/src/utils/useComboboxBaseState.ts
packages/react-components/react-combobox/stories/Combobox/ComboboxClearable.stories.tsx
packages/react-components/react-combobox/stories/Combobox/index.stories.tsx
packages/react-components/react-combobox/stories/Dropdown/DropdownClearable.stories.tsx
packages/react-components/react-combobox/stories/Dropdown/index.stories.tsx
packages/react-components/react-combobox/tsconfig.spec.json
packages/react-components/react-timepicker-compat/etc/react-timepicker-compat.api.md
packages/react-components/react-timepicker-compat/src/components/TimePicker/TimePicker.types.ts

`Combobox` & `Dropdown` components support `clearable` prop. The functionality is implemented similarly to v0, with some changes:
- **Single select `Dropdown`** - `clearable` adds a separate button that is focusable. When clicked, the value removed and focus is moved to the main dropdown trigger button. Allow setting of `aria-label` (and other props) through slot API
- **Single select `Combobox`** - `clearable` adds an icon that is not focusable and has `aria-hidden=true`. When clicked, removes the value and focus is moved to the input
- no change for `multiselect` `Dropdown` & `Combobox` - the prop is ignored there and produces a warning when is used. Might be implemented later.
Fixes #30248.
Related to #29399.

feat(react-combobox): add clearable prop for Combobox & Dropdown

---

change/@fluentui-react-combobox-58e74f07-b299-41aa-bf94-ee56a0536b76.json
packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx
packages/react-components/react-combobox/src/components/Combobox/useInputTriggerSlot.ts

Space would select, and only insert a typeable character on freeform combos.
Space inserts a character for all Comboboxes, and only selects for Dropdown.
Related RFC: #27700 
Fixes #26361

feat: allow typeable space on all v9 comboboxes, not only freeform

---

change/@fluentui-react-tabster-a5ff55a5-f208-4b37-9982-f6ae86bf92e6.json
packages/react-components/react-tabster/src/hooks/useMergeTabsterAttributes.ts
packages/react-components/react-tabster/src/hooks/useTabsterAttributes.ts

Tabster attributes are still strings. This PR memoizes the returned spread object based on the string attribute value.
Fixes partially #29908

fix: memoize tabster attributes

---

change/@fluentui-react-table-59672add-c2fc-4179-a3c7-5d9276d3aaa0.json
packages/react-components/react-table/src/components/DataGridCell/useDataGridCell.ts
packages/react-components/react-table/src/components/DataGridHeaderCell/useDataGridHeaderCell.ts
packages/react-components/react-table/src/components/DataGridRow/useDataGridRow.tsx
packages/react-components/react-table/src/contexts/dataGridContext.ts
packages/react-components/react-table/src/hooks/useKeyboardResizing.ts
packages/react-components/react-table/src/hooks/useTableColumnResizeMouseHandler.ts
packages/react-components/react-table/src/hooks/useTableColumnResizeState.ts
packages/react-components/react-table/src/hooks/useTableColumnSizing.tsx
packages/react-components/react-table/src/hooks/useTableFeatures.ts
packages/react-components/react-table/src/hooks/useTableSort.ts
packages/react-components/react-table/stories/DataGrid/Default.stories.tsx

Improves context selector usage and memoization so that a selected row will only re-render itself and not the entire grid.
Before:
After:
Fixes #29908 when #30289

fix: DataGrid selection performance improvement

---

apps/ts-minbar-test-react-components/src/index.ts

https://github.com/microsoft/keyborg/issues/69 was fixed so we dont need this workaround anymore

revert(ts-minbar-test-react-components): temporarily resolve keyborg to 2.3.0 which will pass TS check

---

change/@fluentui-react-menu-8c0631de-665f-4cf1-bd1e-32dc87f18cd5.json
change/@fluentui-react-table-dde10f45-6b17-4c43-9117-9430691bd383.json
change/@fluentui-react-tabs-8f2916e4-2744-4e3b-bc11-e326d59ebb73.json
change/@fluentui-react-toast-8a3c1b4d-7de8-4721-8217-4b7114f3c592.json
packages/react-components/react-menu/etc/react-menu.api.md
packages/react-components/react-menu/src/components/MenuItem/MenuItem.types.ts
packages/react-components/react-table/etc/react-table.api.md
packages/react-components/react-table/src/components/TableCellLayout/TableCellLayout.types.ts
packages/react-components/react-tabs/etc/react-tabs.api.md
packages/react-components/react-tabs/src/components/Tab/Tab.types.ts
packages/react-components/react-toast/src/components/ToastContainer/ToastContainer.types.ts

As https://github.com/microsoft/fluentui/issues/29596 describes, some properties that were declared by `@types/react` were clashing with slot names, most common case would be the one involving the `content` slot.
1. omits properties declared by `@types/react` in favor of the slot names provided
- Fixes https://github.com/microsoft/fluentui/issues/29596

bugfix(react-utilities): omit IntrinsicElement props from ComponentProps that would collide with slot names

---

change/@fluentui-react-utilities-a3ed4257-d715-43f5-8585-72d1a93681d9.json
packages/react-components/react-utilities/etc/react-utilities.api.md
packages/react-components/react-utilities/src/compose/types.ts
packages/react-components/react-utilities/src/index.ts

We agreed on new event type for v9 callbacks.
Below types will be exported from react-utilities as helpers:
```ts
export type EventData<Type extends string, TEvent> =
| { type: undefined; event: React.SyntheticEvent | Event }
| { type: Type; event: TEvent };
export type EventHandler<TData extends EventData<string, unknown>> = (
ev: React.SyntheticEvent | Event,
data: TData,
) => void;
```
And they will be used for typing callbacks:
```ts
type MyComponentElement = HTMLElement;
type OnSomeEventData = (
| EventData<'click', React.MouseEvent<MyComponentElement>>
| EventData<'focus', React.FocusEvent<MyComponentElement>>
) & {
open: boolean;
};
type SomeProps = {
onSomeEvent?: EventHandler<OnSomeEventData>;
};
```
detailed proposal: https://github.com/microsoft/fluentui/blob/master/rfcs/react-c …

chore: export type EventHandler/EventData from react-utilities for typing callback props

---

change/@fluentui-react-combobox-cddae570-a33b-4aa0-a960-7b80d45ee4fc.json
packages/react-components/react-combobox/etc/react-combobox.api.md
packages/react-components/react-combobox/src/components/Dropdown/Dropdown.types.ts
packages/react-components/react-combobox/src/components/Dropdown/renderDropdown.tsx

In v9.44.3, `<Dropdown expandIcon={null} />` is allowed. But in v9.44.4 it was broken because #30033 removes the optional condition.
Allow `<Dropdown expandIcon={null} />` again and change expandIcon to optional type. Because `expandIcon: Slot<'span'>` pretends it can't be Null, but it can

fix(Dropdown): allow expandIcon to be null

---

change/@fluentui-react-components-ab114c24-9a9d-42e2-8834-4d2af7fba463.json
change/@fluentui-react-shared-contexts-9fc4180f-4a72-41c5-91aa-49564ac7d936.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts
packages/react-components/react-shared-contexts/.storybook/main.js
packages/react-components/react-shared-contexts/.storybook/preview.js
packages/react-components/react-shared-contexts/.storybook/tsconfig.json
packages/react-components/react-shared-contexts/etc/react-shared-contexts.api.md
packages/react-components/react-shared-contexts/package.json
packages/react-components/react-shared-contexts/src/AnnounceContext/AnnounceContext.ts
packages/react-components/react-shared-contexts/src/index.ts
packages/react-components/react-shared-contexts/stories/UseAnnouce/UseAnnounceDefault.stories.tsx
packages/react-components/react-shared-contexts/stories/UseAnnouce/UseAnnounceDescription.md
packages/react-components/react-shared-contexts/stories/UseAnnouce/index.stories.tsx
packages/react-components/react-shared-contexts/tsconfig.json
packages/react-components/react-shared-contexts/tsconfig.lib.json

This PR exports:
- `AnnounceProvider` to inject implementation of `announce()` function
- `useAnnounce()` to trigger announcements
Also adds documentation for `useAnnounce()`.
Sample implementation of announcer will be added separately. 
- Deprecates exports of `AnnounceProvider_unstable`, `useAnnounce_unstable` & `AnnounceContextValue_unstable` in `@fluentui/react-shared-components` in favor of "stable" exports
- Exports `AnnounceOptions` type
Related #29371.
Related #28654.

feat: export AnnounceProvider & useAnnounce()

---

change/@fluentui-eslint-plugin-c8715c3d-52d8-4b79-b0e7-279481b378f0.json
packages/eslint-plugin/src/configs/core.js
packages/eslint-plugin/src/internal.js

adding a temporary workaround to register workspace lint rules without bigger eslint configuration overhaul that will be don eventually. See referenced epic for more details
- Follows: https://github.com/microsoft/fluentui/pull/30335
- Implements partially https://github.com/microsoft/fluentui/issues/30332

feat(eslint-plugin): register @nx plugin internally in order to be able to consume our custom @nx/workspace-* lint rules

---

change/@fluentui-react-combobox-69ab1141-6687-4347-a900-c2462e72f372.json
packages/react-components/react-combobox/src/components/Listbox/useListbox.ts

Quick fix -- we don't need `aria-multiselectable` on the Listbox control since we're using `role=menu/menuitemcheckbox` instead of listbox/option.
- Fixes [ADO bug](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/18400/)

fix: remove aria-multiselectable from v9 listbox

---

change/@fluentui-react-aria-17668947-ca6a-43f9-b1b1-c3bcb189a4fd.json
change/@fluentui-react-tree-bb23b6c0-5f20-4520-a037-7a9c5f2e4b65.json
change/@fluentui-react-utilities-5a4d435a-6cf7-4e78-a675-6c447ed1df24.json
packages/react-components/react-aria/etc/react-aria.api.md
packages/react-components/react-aria/src/button/types.ts
packages/react-components/react-tree/etc/react-tree.api.md
packages/react-components/react-tree/src/contexts/treeContext.ts
packages/react-components/react-utilities/etc/react-utilities.api.md
packages/react-components/react-utilities/src/compose/deprecated/getSlots.ts
packages/react-components/react-utilities/src/compose/getIntrinsicElementProps.ts
packages/react-components/react-utilities/src/compose/types.ts
packages/react-components/react-utilities/src/index.ts
packages/react-components/react-utilities/src/utils/types.ts

Follow up on https://github.com/microsoft/fluentui/pull/29865#discussion_r1423815777
1. adds a new helper type `DistributiveOmit` which aims to provide a solution for  [Distributive Conditional type](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types) problems
2. exports `UnionToIntersection` helper type from `react-utilities`
3. `react-aria` stops redeclaring `UnionToIntersection`, uses the one from `react-utilities` instead
4. `react-tree` stops redeclaring `DistributiveOmit`, uses the one from `react-utilities` instead
- Fixes #

feat(react-utilities): helper type DistributiveOmit

---

change/@fluentui-react-aria-c3dd5226-825f-4e31-b74b-d6005d0b2d36.json
change/@fluentui-react-components-7adb099c-7955-4239-8baf-18294e26ab67.json
packages/react-components/react-aria/etc/react-aria.api.md
packages/react-components/react-aria/src/AriaLiveAnnouncer/AriaLiveAnnouncer.test.tsx
packages/react-components/react-aria/src/AriaLiveAnnouncer/AriaLiveAnnouncer.tsx
packages/react-components/react-aria/src/AriaLiveAnnouncer/AriaLiveAnnouncer.types.ts
packages/react-components/react-aria/src/AriaLiveAnnouncer/__snapshots__/AriaLiveAnnouncer.test.tsx.snap
packages/react-components/react-aria/src/AriaLiveAnnouncer/index.ts
packages/react-components/react-aria/src/AriaLiveAnnouncer/renderAriaLiveAnnouncer.tsx
packages/react-components/react-aria/src/AriaLiveAnnouncer/useAriaLiveAnnouncer.test.tsx
packages/react-components/react-aria/src/AriaLiveAnnouncer/useAriaLiveAnnouncer.ts
packages/react-components/react-aria/src/AriaLiveAnnouncer/useAriaLiveAnnouncerContextValues.ts
packages/react-components/react-aria/src/index.ts
packages/react-components/react-aria/stories/AriaLiveAnnouncer/AriaLiveAnnouncerDefault.stories.tsx
packages/react-components/react-aria/stories/AriaLiveAnnouncer/AriaLiveAnnouncerDescription.md
packages/react-components/react-aria/stories/AriaLiveAnnouncer/index.stories.tsx
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/package.json
packages/react-components/react-components/src/index.ts

Fixes #29371.
Adds a default implementation (and docs 📝 ) of the announcer to be used with [`useAnnounce()`](https://react.fluentui.dev/?path=/docs/utilities-aria-live-useannounce--default).
Main code of the announcer part is ported from Fluent \*\*, kudos to @smhigley.

feat: add AriaLiveAnnouncer component

---

packages/react-components/react-motions-preview/etc/react-motions-preview.api.md
packages/react-components/react-motions-preview/src/factories/createAtom.test.tsx
packages/react-components/react-motions-preview/src/factories/createAtom.ts
packages/react-components/react-motions-preview/src/factories/createPresence.test.tsx
packages/react-components/react-motions-preview/src/factories/createPresence.ts
packages/react-components/react-motions-preview/src/index.ts
packages/react-components/react-motions-preview/src/types.ts
packages/react-components/react-motions-preview/stories/Motion/MotionFunctions.stories.md
packages/react-components/react-motions-preview/stories/Motion/MotionFunctions.stories.tsx
packages/react-components/react-motions-preview/stories/Motion/index.stories.ts

_Inspired by #30113_
This PR add support for motions to be defined as functions, for example the following code defines collapse motion:
```tsx
const collapseMotion: PresenceMotionFn = element => {
const duration = 500;
const keyframes = [
{ opacity: 0, maxHeight: '0px', overflow: 'hidden' },
{ opacity: 1, maxHeight: `${element.scrollHeight}px`, overflow: 'hidden' },
];
return {
enter: { duration, keyframes },
exit: { duration, keyframes: [...keyframes].reverse() },
};
};
const Collapse = createPresence(collapseMotion);
```

feat(react-motions): add support for functions to be definitions

---

change/@fluentui-react-combobox-ac328fea-a08a-4799-af99-1900bb3e039f.json
packages/react-components/react-combobox/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
packages/react-components/react-combobox/src/components/Dropdown/useDropdown.tsx

Adds `type=button` to `clearButton` slot in `Dropdown`.
Fixes #30344.

fix(Dropdown): add `type=button` to `clearButton`

---

scripts/fluentui-publish/index.ts

see pr title + linked PR
- Follows https://github.com/microsoft/fluentui/pull/30202
- Partially implements https://github.com/microsoft/fluentui/issues/30265

fix(fluentui-publish): remove dist-tag leftover from options as canary was removed

---

azure-pipelines-ci.yml

disable manual removal of build assets in order to avoid master pipeline failures https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=332087&view=logs&j=df65131f-49fe-5f4e-72c0-55655bbfd745&t=ca18d1ed-e1a6-5374-a1df-e261f105c601
- Fixes #

ci: disable false positive step which started to fail master pipeline

---

change/@fluentui-react-combobox-017cd1e8-b560-439c-9ba2-83ce1fe18e3a.json
packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx
packages/react-components/react-combobox/src/components/Combobox/__snapshots__/Combobox.test.tsx.snap
packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx
packages/react-components/react-combobox/src/components/Dropdown/Dropdown.test.tsx
packages/react-components/react-combobox/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
packages/react-components/react-combobox/src/components/Dropdown/useDropdown.tsx

Was missing `aria-controls` (no real-world impact, but potential for impact in the future? `aria-controls` is weird.). Mostly relevant because it fails an automated test without it.
Added `aria-controls`, defined only when the listbox is open.
- Fixes [ADO bug](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/18401)

fix: add aria-controls to combo and dropdown

---

change/@fluentui-react-a7c9c9d5-8b9a-4bc0-bf47-e6e0e425816c.json
packages/react/src/components/DetailsList/DetailsList.base.tsx
packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
packages/react/src/components/DetailsList/__snapshots__/DetailsListV2.test.tsx.snap

Related to #25342 -- that PR fixed this same issue for when the header row is entirely absent. The issue still presents when the DetailsList header is present but not focusable (i.e. by disabling both selection and `columnActionsMode`).
The first row of the DetailsList body is now always in the tab order. When I was taking another look at the earlier fix, I realized that there's no use case when we _wouldn't_ want the first content row to be in the tab order, since the headers are a separate tab stop from the body.
- Fixes [ADO bug](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/18499)

Detailslist focusable

---

change/@fluentui-react-menu-dd8988b6-0852-4d75-8547-b751bf978365.json
packages/react-components/react-menu/src/components/MenuItem/useMenuItemStyles.styles.ts

Fixes #30171
The `:hover:active` styles in `makeResetStyles` were not overridden in the disabled styles block, so clicking a disabled menuitem had non-disabled styles when pressed.
Fixed!

fix: v9 Menuitem does not have pressed styles when disabled

---

packages/react-examples/src/react/ContextualMenu/ContextualMenu.CustomMenuList.Example.tsx

We have a ContextualMenu example showing how to customize it to add a text input before the menu items. Technically this is not an allowed parent/child role structure, though it more or less works in practice.
We still have that example, but now with warning text about the error.
- Fixes #29127

chore: add warning text to v8 ContextualMenu example

---

change/@fluentui-react-label-65a884aa-21c2-4ab3-9323-d0910642b5b9.json
packages/react-components/react-label/src/components/Label/useLabelStyles.styles.ts

In forced-colors mode (Windows high contrast), disabled labels don't appear disabled.
Use `GrayText` for disabled labels in forced-colors mode.

fix: Disabled Label should use GrayText in forced-colors mode

---

change/@fluentui-react-label-3d4b817c-0699-45e0-8c11-911b01f6a7b2.json
packages/react-components/react-label/src/components/Label/useLabelStyles.styles.ts

Label used a hardcoded px value for padding, with a TODO comment to replace with a token.
Replace the hardcoded px value with a token.

fix: Update Label to use a token for its padding, instead of a hardcoded value

---

change/@fluentui-react-positioning-f5912219-e8d2-403c-9c21-6d6df380e139.json
packages/react-components/react-positioning/src/utils/getScrollParent.ts
packages/react-components/react-positioning/src/utils/listScrollParents.ts

An infinite loop can occur in `listScrollParents` because the fallback can default to the `document` keyword.
This has only happened in a very
rare case where the `parentNode` is undefined which is actually a bug in the affected application - it's still a good reason to make this more fool proof.
* short circuit and warn when comparing different documents
* fallback should first try the `ownerDocument` before the `document`
Fixes #30407.

fix: Avoid infinite loop when comparing different documents

---

tools/workspace-plugin/generators.json
tools/workspace-plugin/src/generators/bundle-size-configuration/files/bundle-size/index.fixture.js.template
tools/workspace-plugin/src/generators/bundle-size-configuration/files/monosize.config.mjs.template
tools/workspace-plugin/src/generators/bundle-size-configuration/files/src/index.ts.template
tools/workspace-plugin/src/generators/bundle-size-configuration/generator.spec.ts
tools/workspace-plugin/src/generators/bundle-size-configuration/generator.ts
tools/workspace-plugin/src/generators/bundle-size-configuration/schema.d.ts
tools/workspace-plugin/src/generators/bundle-size-configuration/schema.json

adds new generator which setups bundle size measurements for your project
```sh
yarn nx g @fluentui/workspace-plugin:bundle-size-configuration
```
Initial setup 
initial/later setup with config override
- Implements partially https://github.com/microsoft/fluentui/issues/27933

feat(workspace-plugin): add bundle-size-configuration generator

---

change/@fluentui-react-714fcf34-c6dc-4efb-bc09-1a35babefc19.json
packages/react/src/components/Button/CommandBarButton/CommandBarButton.styles.ts
packages/react/src/components/Button/__snapshots__/Button.test.tsx.snap

Looks like this was an oversight addition in #14215, where it accidentally added a disabled color to icons for regular/enabled non-split menu items. This change still keeps the icon color disabled when the button is disabled, and does not affect split menu items.
- Fixes #29982

fix: CommandBar menu icon is not visually disabled in high contrast mode

---

change/@fluentui-react-tree-92e4762b-6aa9-40b1-9827-f9700472e561.json
packages/react-components/react-tree/src/components/Tree/Tree.test.tsx
packages/react-components/react-tree/src/components/TreeItem/TreeItem.test.tsx
packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx
packages/react-components/react-tree/src/contexts/treeContext.ts
packages/react-components/react-tree/src/hooks/useRootTree.ts

`onOpenChange` callback from root `Tree` ignores the `open` value from `TreeItem` in favor of it's internal one, this is problematic in scenarios where a `TreeItem` controls its own state
1. `onOpenChange` callback from root `Tree` ignores internal state in favor of the value provided by the `TreeItem`, it works fine if `TreeItem` is controlled/uncontrolled. If it's controlled then the value is defined by the `TreeItem` itself, if it's uncontrolled the `TreeItem` will just replicate the value provided by the root `Tree`
2. Adds test to ensure both `Tree` and `TreeItem` `onOpenChange` callbacks are synchronized if the `TreeItem` is controlled
3. Adds test to ensure that if a `TreeItem` is a leaf it'll not update it's open state on `onOpenChange`
- Fixes …

bugfix: onOpenChange inconsistent between Tree and TreeItem

---

azure-pipelines.bundlesize.yml
scripts/bundle-size-collect.js

- removes non functional SizeAuditor part of bundle size pipeline
- provides output within the pipeline to at least get some raw measurement data
- <img width="817" alt="image" src="https://github.com/microsoft/fluentui/assets/1223799/3fa1a8e1-4f29-4ec0-a354-543e0b0dfa50">
- Implements partially https://github.com/microsoft/fluentui/issues/27933

ci(bundlesize): remove lightrail and azure storage uploads as they dont work anymore

---

.github/CODEOWNERS

> Based on tech sync offline discussion
if a new RFC PR is created, all core. teams will be assigned as required to review. this adds github automation and explicit visibility ( all members of teams will get notified ) to any RFC PR.
_New flow:_
- each team needs to assign 1 member to review RFC PR on behalf of owning team within `Reviewers` Pane
- if owning team is not interested to provide any feedback
- they wont assign anyone within `Reviewers` Pane
- or they can explicitly provide comment within PR that they wont be reviewing
_Merge-ability of PR:_
After CI is green and there is at least 1 approval from 1 of the owning teams, PR can be merged. 
The rule that RFC should get at least 2 members approval still applies 
- Fixes #

chore: add all core teams as owner of rfcs/ folder

---

change/@fluentui-react-tree-2d77df3e-24cf-4465-ab45-585ec20e0e7b.json
packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx

`onFocus` and `onBlur` properties were being ignore from `TreeItem` due to a regression introduced in https://github.com/microsoft/fluentui/pull/29694
Ensures that `onFocus` and `onBlur` are properly provided to the root element for `TreeItem`
- Fixes #

bugfix(react-tree-item): regression fix for focus and blur events on TreeItem

---

change/@fluentui-react-migration-v0-v9-40c471ac-4687-4fe0-8321-043b79251c80.json
packages/react-components/react-migration-v0-v9/package.json

northstar is specified only as a devDependency but its actually being used in public api surface. (discovered https://github.com/microsoft/fluentui/pull/30251)
northstar is properly set as dependency
- Fixes #

fix(react-migration-v0-v9): add northstar to dependencies

---

change/@fluentui-react-charting-f1fedc1b-f7dc-4449-af7a-32d58ab130ae.json
packages/react-charting/src/components/SankeyChart/SankeyChart.base.tsx
packages/react-charting/src/components/SankeyChart/SankeyChart.test.tsx
packages/react-charting/src/components/SankeyChart/__snapshots__/SankeyChart.test.tsx.snap
packages/react-charting/src/components/SankeyChart/__snapshots__/SankeyChartRTL.test.tsx.snap

When the `aria-label` is generated for nodes, it generates text like:
- `link from192.168.42.72toinboxwith weight80`
- `link frominboxtoClickedwith weight30`
- `node192.168.42.72with weight80`
Those are unintelligible and are likely to be garbled by a screen reader.
Those same kinds of strings are now generated as:
- `link from 192.168.42.72 to inbox with weight 80`
- `link from inbox to Clicked with weight 30`
- `node 192.168.42.72 with weight 80`
- Fixes #

Sankey Diagram: Improving generated aria-label

---

packages/react-components/react-button/docs/SPEC.md

Link to `Button.types.ts` was leading to 404.
Now it's leading to `Button.types.ts` file.

Corrected link to Button.types.ts

---

change/@fluentui-react-e44f66af-f799-4e82-a59f-9b2056b5edbb.json
packages/react/src/components/Callout/CalloutContent.base.tsx
packages/react/src/components/Keytip/Keytip.tsx

Whenever a top edge alignment was specified as well as covering the target, the `Callout` would make wrong calculations about its height that would cause it to not render properly.
The `Callout` now calculates its height correctly under these conditions.
As part of investigating this issue, we also noticed that `calloutProps` passed to `Keytips` were not always respected, so that is a fix is also included as part of this PR.

fix: Correctly calculating height of Callout aligning to the top and covering target.

---

change/@fluentui-react-charting-4ff1470e-7359-4539-ac6d-724412f4cd67.json
packages/react-charting/src/components/AreaChart/AreaChart.base.tsx
packages/react-charting/src/components/DonutChart/Arc/Arc.styles.ts
packages/react-charting/src/components/DonutChart/__snapshots__/DonutChartRTL.test.tsx.snap
packages/react-charting/src/components/GaugeChart/GaugeChart.styles.ts
packages/react-charting/src/components/Legends/Legends.base.tsx
packages/react-charting/src/components/Legends/Legends.styles.ts
packages/react-charting/src/components/LineChart/LineChart.base.tsx
packages/react-charting/src/components/LineChart/eventAnnotation/LabelLink.tsx
packages/react-charting/src/components/Sparkline/Sparkline.styles.ts
packages/react-charting/src/components/Sparkline/__snapshots__/Sparkline.test.tsx.snap
packages/react-charting/src/components/Sparkline/__snapshots__/SparklineRTL.test.tsx.snap
packages/react-charting/src/components/TreeChart/TreeChart.styles.ts
packages/react-charting/src/components/TreeChart/__snapshots__/TreeChart.test.tsx.snap
packages/react-charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx
packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx

There was usage of non semantic colors like white and black in charting code.
These colors work fine in light mode or ideal scenarios where the foreground/background colors are represented as absolute white and black.
This starts causing an issue with Fluent v9 themes where dark mode background is not absolute black but a shade of grey.
This creates following issues in charting controls.
#30397 
#30396 
Updated the tokens to use semantic or neutral colors.
This moves the responsibility of handling color tokens to the theme.
Charts will now work seamlessly across v8 and v9 themes.
Related PR:
https://github.com/microsoft/fluentui/pull/30373
- Fixes #

Fix color tokens to render charts correctly for v9 theme

---

packages/react-components/react-combobox/stories/Dropdown/DropdownControlled.stories.tsx
packages/react-components/react-combobox/stories/Dropdown/DropdownTruncation.stories.tsx
packages/react-components/react-combobox/stories/Dropdown/index.stories.tsx

No package changes, just an example addition.
A partner asked how to truncate value text in a Dropdown, which made me think it'd be helpful to have an example showing that, + also shows how to add custom JSX to the trigger slot.

chore: add story for truncating Dropdown value text

---

apps/vr-tests-react-components/src/stories/MessageBar/MessageBar.stories.tsx
change/@fluentui-react-message-bar-bcac357a-71f0-438b-89fe-087e112ab7ec.json
packages/react-components/react-message-bar/etc/react-message-bar.api.md
packages/react-components/react-message-bar/src/components/MessageBar/MessageBar.test.tsx
packages/react-components/react-message-bar/src/components/MessageBar/MessageBar.types.ts
packages/react-components/react-message-bar/src/components/MessageBar/renderMessageBar.tsx
packages/react-components/react-message-bar/src/components/MessageBar/useMessageBar.ts
packages/react-components/react-message-bar/src/components/MessageBar/useMessageBarStyles.styles.ts

Design guidance has always considered MessageBar to include at least one action for accessibility requirements. However, there are still cases in product where MessageBar is used without any actions.
When no actions are rendered, the default secondary actions slot is no longer rendered (that provides correct spacing). In order to handle this edge case the MessageBar will render a new slot `bottomReflowSpacer` that sets the correct spacing in in the same grid area.
There should be no conflict with current secondary actions since the grid layout will render both in the same area and the spacer is just an empty div
Fixes #30461
- Fixes #

fix: MessageBar with no actions should have correct spacing

---

change/@fluentui-react-aria-4272dc51-3c77-444a-b9d3-1e40a1fc40ee.json
packages/react-components/react-aria/package.json

As https://github.com/microsoft/fluentui/pull/30345 Introduces:
https://github.com/microsoft/fluentui/blob/c39e261e7c1f7543c8f0892461597765aaca2970/packages/react-components/react-aria/src/AriaLiveAnnouncer/renderAriaLiveAnnouncer.tsx#L1-L2
`@fluentui/react-aria` required the dependency of `@fluentui/react-jsx-runtime`
1 adds `@fluentui/react-jsx-runtime` as a dependency
https://github.com/microsoft/fluentui/issues/30400#issuecomment-1928982262

chore(react-aria): adds @fluentui/react-jsx-runtime as dependency

---

apps/vr-tests-react-components/src/stories/Positioning.stories.tsx
change/@fluentui-react-positioning-ebe269b8-e0d0-4776-a5a4-994637d87db1.json
packages/react-components/react-positioning/src/createPositionManager.ts

When the dimensions of the content rect becomes 0, this is likely that the observed element has been removed from dom or hidden with `display: none`.
This can happen often with mouse hover behaviours (i.e. element disappears when mouse leaves a parent div). To avoid incorrect positioning without a target, we do nothing in these cases and force the user to update imperatively if necessary

fix: Resize heuristic should account for zero dimensions

---

tools/workspace-plugin/src/generators/bundle-size-configuration/files/bundle-size/index.fixture.js.template
tools/workspace-plugin/src/generators/bundle-size-configuration/generator.spec.ts

current setup creates fixture that will not compile 
see PR title
- Follows https://github.com/microsoft/fluentui/issues/27933

fix(workspace-plugin): dont use ecma reserved word for star import alias within bundle-size-configuration generator

---

change/@fluentui-react-charting-b5125005-397e-427f-b4d8-a674ed300d61.json
packages/react-charting/webpack.config.js

Obfuscating variable names for Tree component in charting library which reduces the packaged bundle size for charting to 462 KiB (2 KiB reduction from master).
This is required for following scenarios:
- showcase the minified bundle size (via react-charting.min.js) of the charting library as published on various external bundle measuring tools like 
https://bundlephobia.com/package/@fluentui/react-charting@5
This is used by potential consumers to choose between our charting library or the other.
We hoped to reduce the size of each component even before bundling, but that did not happen. 
Scenario: Compress, minify and mangle the min.js generated for react-charting components (taking one component at a time).
Approaches: 
1. Enabling mangling for all functions of all components: This …

[1 of N] [Size optimization] Compress charting bundle size by mangling variable names

---

change/@fluentui-react-rating-preview-73090623-b968-461d-857f-78ed02671b60.json
packages/react-components/react-rating-preview/src/components/RatingDisplay/useRatingDisplayStyles.styles.ts
packages/react-components/react-rating-preview/src/components/RatingItem/useRatingItemStyles.styles.ts

There is a vertical alignment with the label in `RatingDisplay` when `size` is set to small. This PR adds styling to fix this. 
Before: 
After:

Fix size small  label vertical stying in RatingDisplay

---

change/@fluentui-react-154ee35d-239e-4e15-8fa2-3fd2bd1104f9.json
packages/react/src/components/Coachmark/Coachmark.base.tsx
packages/react/src/components/Coachmark/Coachmark.styles.ts
packages/react/src/components/Coachmark/__snapshots__/Coachmark.test.tsx.snap

Callout would only open if a mouse move event occurred near Coachmark, this causes issues on mobile as mouse move events are not uniform. Additionally, if a mouse is already present on top of the Coachmark when it appears, it will not open until the mouse moves again.
Currently, there is no 'onClick' behavior for Coachmark, only mouse movement detection.
onClick enabled on Coachmark - this click event enables press based entry for mobile, it can also be used on desktop with a pointer style design should the mouse already be hovering over Coachmark when it appears.
- Fixes #30273

V8 Coachmark - Fix: Enable click to open Coachmark on mobile

---

change/@fluentui-react-charting-0091dd21-21f9-4537-8fd9-fbfee2e292e7.json
packages/react-charting/bundle-size/AreaChart.fixture.js
packages/react-charting/bundle-size/VerticalBarChart.fixture.js
packages/react-charting/monosize.config.mjs
packages/react-charting/package.json
yarn.lock

Monosize was not integrated for react-charting library
Integrated monosize (0.2.1) in react-charting  for AreaChart and VerticalBarChart. Using monosize-storage-azure for storage adaptor.
yarn monosize measure may not be working due to erroneous ESM URL scheming. Refer this issue for temporary workaround for testing in dev env.
https://github.com/microsoft/monosize/issues/31
- Fixes #30480

chore: Integrate microsoft/monosize in react-charting library for AreaChart and VerticalBarChart

---

change/@fluentui-react-tabster-d1ecb8a0-803a-4d33-9edd-225c1a12b51a.json
packages/react-components/react-tabster/package.json
yarn.lock

Active modal checks if an element outside of it is a virtual child of a modal before setting aria-hidden.

Tabster 6.0.1

---

packages/react-charting/bundle-size/AreaChart.fixture.js
packages/react-charting/bundle-size/ChartHoverCard.fixture.js
packages/react-charting/bundle-size/DonutChart.fixture.js
packages/react-charting/bundle-size/GaugeChart.fixture.js
packages/react-charting/bundle-size/GroupedVerticalBarChart.fixture.js
packages/react-charting/bundle-size/HeatMapChart.fixture.js
packages/react-charting/bundle-size/HorizontalBarChart.fixture.js
packages/react-charting/bundle-size/HorizontalBarChartWithAxis.fixture.js
packages/react-charting/bundle-size/Legends.fixture.js
packages/react-charting/bundle-size/LineChart.fixture.js
packages/react-charting/bundle-size/MultiStackedBarChart.fixture.js
packages/react-charting/bundle-size/PieChart.fixture.js
packages/react-charting/bundle-size/SankeyChart.fixture.js
packages/react-charting/bundle-size/Sparkline.fixture.js
packages/react-charting/bundle-size/StackedBarChart.fixture.js
packages/react-charting/bundle-size/TreeChart.fixture.js
packages/react-charting/bundle-size/VerticalBarChart.fixture.js
packages/react-charting/bundle-size/VerticalStackedBarChart.fixture.js

Monosize fixtures were added only for AreaChart and VerticalBarChart
In order to make measurements, go to react-charting directory and run `yarn monosize measure`
Monosize fixtures added for all charts
Measurements on time of PR staging:
- Fixes #

chore: Integrate Monosize into react-charting for all charts

---

change/@fluentui-react-tabster-7de2abf6-4ead-4023-b4e3-c7da63220700.json
packages/react-components/react-tabster/src/focus/focusVisiblePolyfill.ts
packages/react-components/react-tabster/src/hooks/useFocusVisible.cy.tsx

Previously the polyfill registered any activeElement on the document. This meant that when a polyfill was disposed - it would remove the focus visible attribute from elements outside of its scope.
Adds an extra check to make sure that the activeElement is in scope before registering.

fix: focus-visible polyfill should only register in scope

---

change/@fluentui-react-calendar-compat-0cf74a20-e5f5-4550-8a3a-5e74795ff1d7.json
change/@fluentui-react-datepicker-compat-a5aa1132-9ed3-4aa4-8287-2c11e3c4f9e1.json
packages/react-components/react-calendar-compat/src/components/Calendar/Calendar.tsx
packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx

Every render where a value was not provided would create a new `Date`.
`Date`s are only created when necessary.

fix: remove new Date() from prop destructuring

---

change/@fluentui-react-datepicker-compat-90ecf66d-ad92-4c24-9737-1299a1769080.json
change/@fluentui-react-fbfbd480-81b2-4336-9ba2-8318be8c27e3.json
packages/react-components/react-datepicker-compat/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
packages/react-components/react-datepicker-compat/src/components/DatePicker/useDatePicker.tsx
packages/react/src/components/DatePicker/DatePicker.base.tsx
packages/react/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap

This is a workaround for an ongoing issue where Voice Access cannot expand a combobox-like popup from a text input. Since there's no clear solution from the Voice Access or Edge side of things, it makes sense to have the Fluent DatePicker render the icon as a semantic button so that it can be activated by voice control to open the calendar popup.
DatePicker adds button semantics to the calendar icon when the control renders a text input (otherwise it is unnecessary, since the issue only arises when inputs are used as combobox triggers).
- Fixes multiple ADO issues

fix: Datepicker with input renders semantic button for voice control

---

change/@fluentui-react-menu-5263c408-028b-430c-aeac-d0dcccf716c6.json
packages/react-components/react-menu/src/components/MenuPopover/useMenuPopover.ts

Currently submenus will only stay open when the mouse enters the MenuPopover when `openOnHover` is set. The assumption was that all submenus would generally be opened with hover.
Updates the check on mouse enter for the MenuPopover so that if the MenuPopover is part of submenu, it should also stay open on mouse enter.
Fixes #30394

fix: MenuPopover should stay open for submenu even when not openOnHover

---

change/@fluentui-react-aria-98e9bbfd-117c-4485-85de-0e91928c19be.json
packages/react-components/react-aria/etc/react-aria.api.md
packages/react-components/react-aria/src/activedescendant/ActiveDescendantContext.ts
packages/react-components/react-aria/src/activedescendant/index.ts
packages/react-components/react-aria/src/activedescendant/types.ts
packages/react-components/react-aria/src/activedescendant/useActiveDescendant.ts
packages/react-components/react-aria/src/activedescendant/useActivedescendant.test.tsx
packages/react-components/react-aria/src/activedescendant/useOptionWalker.ts
packages/react-components/react-aria/src/index.ts

The active descendant API usage will (most of the time) be passed to children to use for 'focus' operations. Hoisting a context here so that it can be used by multiple controls.

feat: adds a context for active descendant

---

change/@fluentui-react-charting-e217bea5-7bc5-44cd-a606-027b5c599b2e.json
packages/react-charting/webpack.config.js

Issue: The toplevel global variable name of "FluentUIReactCharting" inside window object was getting mangled to "t" when the "toplevel" was set to true and the corresponding chart in codepen was not visible as follows.
After removing the toplevel property in mangle options (default value is false) restored the varibale name to "FluentUIReactCharting" without any impact on the generated min js size.

Fixing codepen issue for charts not opening

---

.gitignore
.verdaccio/config.yml
package.json
project.json
tools/workspace-plugin/scripts/install-verdaccio.js

- setup verdaccio within monorepo in order to easily verify/test publishing our packages.
- whole setup was generated via `nx g @nx/js:setup-verdaccio` + some manual tweaks
- verdaccio package is installed on-demand 
To start local registry run `yarn nx local-registry`
- on initial run we will dynamically install verdaccio in order to no spam our node_modules with deps we dont need for CI
- on 2nd run install step will be skipped
- Relates to #30251

feat: setup verdaccio within monorepo

---

change/@fluentui-react-utilities-f584d831-49de-41c8-95ba-8df7bcf5dbd1.json
packages/react-components/react-utilities/src/compose/assertSlots.ts

The file `assertSlots.ts` imports from `./index`, and `index.ts` exports `*` from `./assertSlots`. This was creating an import cycle and a warning message from `@rnx-kit`:
```log
warn @fluentui\react-utilities\lib-commonjs\compose\index.js
warn └── @fluentui\react-utilities\lib-commonjs\compose\assertSlots.js
warn     └── @fluentui\react-utilities\lib-commonjs\compose\index.js
warn         └── @fluentui\react-utilities\lib-commonjs\index.js
error Import cycles detected.
```
Have `assertSlots.ts` import directly from `./slot` instead of `./index`.

fix: Remove import cycle between assertSlots.ts and index.ts

---

change/@fluentui-react-rating-preview-098152fc-985c-46de-aee3-2e1e7917e969.json
packages/react-components/react-rating-preview/src/components/Rating/useRating.tsx
packages/react-components/react-rating-preview/src/components/RatingDisplay/useRatingDisplay.tsx
packages/react-components/react-rating-preview/src/components/RatingItem/useRatingItem.tsx

Components would be reassigned every render when a value was not provided.
Components are only assigned as needed.

fix: remove components from prop destructuring

---

apps/public-docsite-v9/src/Concepts/SSR/NextJSAppDir.stories.mdx

The existing Next.js documentation for app router results in behavior where styles are rendered multiple times (once in the bottom of the `<head>` and then an arbitrary number of times in the bottom of `<body>`):
Update the documentation to ensure that the styles are rendered only once:
The solution itself was suggested in [this discussion](https://github.com/vercel/next.js/discussions/49354#discussioncomment-6279917) in Next.js repo.
This should be removed once the underlying issue is uncovered and resolved (either in this library or upstream in Next.js).
N/A

Update Next.js appDir docs to prevent duplicate style renders

---

packages/react-examples/src/react-charting/StackedBarChart/StackedBarChart.Benchmark.Example.tsx

Updated color code in StackedBarChart benchmark example data
Color contrast ratio after code changes.

updated color code to stackedBarChart benchmark example data

---

change/@fluentui-react-motions-preview-806677e6-3564-4fa7-8da6-d3372a84161f.json
packages/react-components/react-motions-preview/etc/react-motions-preview.api.md
packages/react-components/react-motions-preview/src/components/PresenceGroup.test.tsx
packages/react-components/react-motions-preview/src/components/PresenceGroup.tsx
packages/react-components/react-motions-preview/src/components/PresenceGroupItemProvider.tsx
packages/react-components/react-motions-preview/src/contexts/PresenceGroupChildContext.ts
packages/react-components/react-motions-preview/src/factories/createPresenceComponent.ts
packages/react-components/react-motions-preview/src/index.ts
packages/react-components/react-motions-preview/src/utils/groups/getChildMapping.test.tsx
packages/react-components/react-motions-preview/src/utils/groups/getChildMapping.ts
packages/react-components/react-motions-preview/src/utils/groups/getNextChildMapping.test.tsx
packages/react-components/react-motions-preview/src/utils/groups/getNextChildMapping.ts
packages/react-components/react-motions-preview/src/utils/groups/mergeChildMappings.test.tsx
packages/react-components/react-motions-preview/src/utils/groups/mergeChildMappings.ts
packages/react-components/react-motions-preview/src/utils/groups/types.ts
packages/react-components/react-motions-preview/stories/PresenceGroup/PresenceGroupDefault.stories.tsx
packages/react-components/react-motions-preview/stories/PresenceGroup/PresenceGroupDescription.md
packages/react-components/react-motions-preview/stories/PresenceGroup/index.stories.ts

The factory was updated to store options that should not trigger re-renders in `optionsRef`.
This PR adds a new component called `PresenceGroup`:
> `PresenceGroup` is a component that manages a set of components created with `createPresenceComponent()` in a list. `PresenceGroup` is a state machine for managing the mounting and unmounting of components over time.
While code is mostly ported from `react-transition-group`, it has some differences: we don't rely on cloning items and rely on React context instead.
Note: `PresenceGroup` is implemented as a class component to benefit from `getDerivedStateFromProps()`. While it's possible to implement this functionality with React hooks, it will require state management tricks.
Fixes #30546.

feat(react-motions): add PresenceGroup

---

apps/vr-tests-react-components/src/stories/Spinner.stories.tsx

Spinner VR tests weren't showing the paused state correctly.
Add an animationDuration override to the tests, so the animation is not affected by the test environment's prefers-reduced-motion setting.
Add an "Animation" story with the spinner paused at 0.1s intervals.

chore: Fix Spinner VR tests to pause correctly, and add Animation test

---

apps/public-docsite-v9/src/Concepts/Migration/FromV8/Troubleshooting.stories.mdx

No new behavior.
When mixing layered v8 components (e.g., `Callout`) with layered v9 components (e.g., `Dialog`) users will often end up with inconsistent z-positioning. This is because all layered elements have `z-index: 10000` which means that document order resolves their z-positioning, which means the visual layering will depend on the order in which layers are opened.
There doesn't seem to be an obvious general case solution to this so we're documenting it to improve discoverability and shareability.
- [Example of the issue](https://[codesandbox.io/p/sandbox/affectionate-merkle-x37zg8?file=%2Fsrc%2Fexample.tsx](https://codesandbox.io/p/sandbox/affectionate-merkle-x37zg8?file=%2Fsrc%2Fexample.tsx))
- [Example of the workaround](https://[codesandbox.io/p/sandbox/black-haze-yfztt5?file=% …

docs: add troubleshooting guide for migrating layered elements

---

packages/react-components/react-nav-preview/etc/react-nav-preview.api.md
packages/react-components/react-nav-preview/src/components/Nav/Nav.types.ts
packages/react-components/react-nav-preview/src/components/Nav/useNav.ts
packages/react-components/react-nav-preview/src/components/NavCategory/useNavCategory.ts
packages/react-components/react-nav-preview/src/components/NavCategoryItem/NavCategoryItem.types.ts
packages/react-components/react-nav-preview/src/components/NavCategoryItem/useNavCategoryItem.styles.ts
packages/react-components/react-nav-preview/src/components/NavCategoryItem/useNavCategoryItem.tsx
packages/react-components/react-nav-preview/src/components/NavContext.ts
packages/react-components/react-nav-preview/src/components/NavContext.types.ts
packages/react-components/react-nav-preview/src/components/NavItem/renderNavItem.tsx
packages/react-components/react-nav-preview/src/components/NavItem/useNavItem.ts
packages/react-components/react-nav-preview/src/components/NavItem/useNavItemStyles.styles.ts
packages/react-components/react-nav-preview/src/components/NavSubItem/NavSubItem.types.ts
packages/react-components/react-nav-preview/src/components/NavSubItem/renderNavSubItem.tsx
packages/react-components/react-nav-preview/src/components/NavSubItem/useNavSubItem.ts
packages/react-components/react-nav-preview/src/components/NavSubItem/useNavSubItemStyles.styles.ts
packages/react-components/react-nav-preview/src/components/useNavContextValues.tsx
packages/react-components/react-nav-preview/stories/Nav/NavWithNestedSubItems.stories.tsx
packages/react-components/react-nav-preview/stories/Nav/NavWithNestedSubItemsWithDefaultSelection.stories.tsx
packages/react-components/react-nav-preview/stories/Nav/index.stories.tsx
packages/react-components/react-nav-preview/stories/NavSubItem/NavSubItemDefault.stories.tsx

The Nav has nesting behavior. This PR implements 2 of those behaviors:
https://github.com/microsoft/fluentui/assets/17346018/97ca8516-8da9-49c1-8107-80a28ad2b808
- Select SubItems nested within categories, and maintain that selection state when categories are opened and closed. I rinsed and repeated the same pattern from NavItem.
- When the parent of a SubItem gets closed, the parent shows as selected indicating a selected child to the user.
Note the spec indicates the CategoryItem's ability to close when it's is clicked. This behavior will come in a future PR as I bring in more props and behaviors from the accordion.
This adds a few new props to the top level nav:
- selectedCategoryValue
- defaultSelectedCategoryValue
Also adds a new optional property to our event data, categoryValue …

Adds ability for NavSubItem to select it's parent

---

change/@fluentui-react-charting-fd6cfadf-25f3-4869-923b-f6ee828c7de1.json
packages/react-charting/src/components/DonutChart/DonutChart.base.tsx
packages/react-charting/src/utilities/UtilityUnitTests.test.ts
packages/react-charting/src/utilities/__snapshots__/UtilityUnitTests.test.ts.snap
packages/react-charting/src/utilities/utilities.ts

Zero values didn't appear on legend hover inside donut
Zero values now appear on hovering over legend with data zero. This was primarily due to filtering of data by >0 condition.
- Fixes #30051

[Fix] Zero values unavailable in DonutChart plot

---

apps/vr-tests-react-components/src/stories/Spinner.stories.tsx

Previous PR #30592 didn't apply the timing to the correct element, resulting in the wrong animation frames being used in VR tests.
Apply the animation-duration to the correct element for the SVG animation.

fix(react-spinner): Correct Spinner VR test timing for SVG animation

---

packages/react-components/react-nav-preview/src/components/Nav/useNav.ts

Accordion has a 'collapsible' prop, which dictates if all its items are ever allowed to be collapsible.
Previous implementation was the default behavior from accordion, which we don't want.
This PR removes all traces of the prop and updates the default behavior to make everything always collapsible.
Before:
https://github.com/microsoft/fluentui/assets/17346018/bee31740-a62c-40fb-a236-8cdbfc6e9867
After:
https://github.com/microsoft/fluentui/assets/17346018/45cac80f-e83a-471d-bc1f-72507cda2ffe

Remove collapsible option for Nav

---

change/@fluentui-react-charting-57bfdb02-b559-4243-b1be-241d801ae8f4.json
packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx
packages/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.test.tsx

Empty array for data in VerticalStackedBarChart throws the following runtime error:
VerticalStackedBarChart renders an empty div when data array is empty.
- Fixes #30594

Fix vertical stacked bar chart rendering issue when data array is empty

---

packages/react-components/react-nav-preview/etc/react-nav-preview.api.md
packages/react-components/react-nav-preview/src/components/Nav/Nav.types.ts
packages/react-components/react-nav-preview/src/components/Nav/useNav.ts
packages/react-components/react-nav-preview/src/components/NavContext.ts
packages/react-components/react-nav-preview/src/components/NavContext.types.ts
packages/react-components/react-nav-preview/src/components/useNavContextValues.tsx
packages/react-components/react-nav-preview/stories/Nav/NavWithNestedSubItemsWithDefaultSelection.stories.tsx
packages/react-components/react-nav-preview/stories/Nav/NavWithNestedSubItemsWithDefaultSelectionSingleCategory.stories.tsx
packages/react-components/react-nav-preview/stories/Nav/index.stories.tsx

Accordion has a prop 'multiple' that controls if multiple items can be open at the same time.
We want an analogous prop, but our prop will default to true.
Adds an example to demonstrate behavior when this is false.
Recording of two relevant examples:
https://github.com/microsoft/fluentui/assets/17346018/6fe1e86d-d482-4488-b008-6c867479bad7
Child of #26649

Adding 'multiple' prop to Nav

---

packages/react-components/react-dialog/stories/Dialog/DialogActions.md
packages/react-components/react-dialog/stories/Dialog/DialogActions.stories.tsx
packages/react-components/react-dialog/stories/Dialog/index.stories.tsx

1. Adds documentation to describe better why to use `DialogActions`
2. Adds checkbox example to showcase CELA explicit acknowledgement to confirm that the user has reviewed the message (Fixes https://github.com/microsoft/fluentui/issues/30507)

docs(react-dialog): creates story for DialogActions

---

change/@fluentui-react-rating-preview-9f325e30-7f5b-430e-85bc-80a4e03999da.json
packages/react-components/react-rating-preview/src/components/RatingItem/useRatingItemStyles.styles.ts

This PR changes the `display` attribute of the `RatingItem` indicator slot from `inline-block` to `flex` so that all items can be aligned properly. This was originally not done because doing so would mean that the half value input icon would not align properly. This PR fixes that by adding a `flex: 0 0 auto` property to the half value svg so that it takes up the appropriate space.

Fix Rating icon layout

---

packages/react-components/react-nav-preview/etc/react-nav-preview.api.md
packages/react-components/react-nav-preview/src/components/Nav/Nav.types.ts
packages/react-components/react-nav-preview/src/components/NavItem/NavItem.types.ts
packages/react-components/react-nav-preview/src/components/NavItem/useNavItem.ts
packages/react-components/react-nav-preview/src/components/NavSubItem/NavSubItem.types.ts
packages/react-components/react-nav-preview/src/components/NavSubItem/useNavSubItem.ts
packages/react-components/react-nav-preview/stories/Nav/NavWithNestedSubItemsWithDefaultSelection.stories.tsx

Drafting off the MenuItemLink component.
I'm updating the types to be an anchor, instead of a button because these will all take the user somewhere.
Adding to example for testing.
Todo in a follow up PR: styling
Related parent: #26649
https://github.com/microsoft/fluentui/assets/17346018/0d17d1b2-3b18-48db-89da-dc58371c2a31

Changes NavItems and NavSubItems to be anchors

---

change/@fluentui-react-rating-preview-d2b46b99-f2b6-48df-87e9-0fba20df0cd2.json
packages/react-components/react-rating-preview/src/components/Rating/useRatingStyles.styles.ts
packages/react-components/react-rating-preview/src/components/RatingDisplay/useRatingDisplayStyles.styles.ts

Currently content wrap is not supported for `Rating` and `RatingDisplay`, so if the screen is resized, both components lose a lot of functionality. This adds a flex wrap around the `Rating` and `RatingDisplay`.

Fix: Add wrap to Rating and RatingDisplay

---

change/@fluentui-react-combobox-4683dd24-621c-4ae8-a961-cedec640fa96.json
packages/react-components/react-combobox/etc/react-combobox.api.md
packages/react-components/react-combobox/src/components/Combobox/useInputTriggerSlot.ts
packages/react-components/react-combobox/src/components/Dropdown/useButtonTriggerSlot.ts
packages/react-components/react-combobox/src/hooks/useComboboxFilter.tsx
packages/react-components/react-combobox/src/index.ts
packages/react-components/react-combobox/src/utils/useComboboxBaseState.ts
packages/react-components/react-combobox/src/utils/useListboxSlot.ts

1. exports internal hooks from combobox as they'll be required for the `react-tag-picker` package 
- Fixes #

feature(react-combobox): export internal hooks and types

---

.github/CODEOWNERS
docs/react-v9/contributing/coding-style.md
docs/react-v9/contributing/command-cheat-sheet.md
docs/react-v9/contributing/common-dev-snags.md
docs/react-v9/contributing/dev-env.md
docs/react-v9/contributing/dev-workflow.md
docs/react-v9/contributing/rfc-process.md

This PR is scaffolding our new documentation directory in the repo.
I will fast follow with individual PR's for each file, with the assigned reviewer giving me feedback.
**Related issues:**
Related RFC #30274
Related Epic #30642

Scaffold new dev docs

---

packages/react-examples/src/react/List/List.Basic.Example.tsx
packages/react-examples/src/react/List/List.Ghosting.Example.tsx
packages/react-examples/src/react/List/List.Grid.Example.tsx
packages/react-examples/src/react/List/List.Scrolling.Example.tsx

The basic list examples all use `getTheme` which does not respond to contextual theme changes, the modern v8 method for theming.
This PR updates them to use the useTheme hook. There's some rearrangement required since the styles are passed into the render functions. Sorry for the load PR.
More generally:
- Move render and style generating function to within the scope of the component.
- Apply useCallback for the renders, useMemo for the style generators.
- Tidy up some styles.
Addresses #30358

Removing 'getTheme' from BasicList examples

---

change/@fluentui-react-combobox-4683dd24-621c-4ae8-a961-cedec640fa96.json
change/@fluentui-react-combobox-6aa21ddd-0e42-47f0-a0a7-b624bfc21798.json
packages/react-components/react-combobox/etc/react-combobox.api.md
packages/react-components/react-combobox/src/index.ts
packages/react-components/react-tag-picker-preview/package.json
packages/react-components/react-tag-picker-preview/src/utils/ComboboxBase.types.ts
packages/react-components/react-tag-picker-preview/src/utils/OptionCollection.types.ts
packages/react-components/react-tag-picker-preview/src/utils/Selection.types.ts
packages/react-components/react-tag-picker-preview/src/utils/dropdownKeyActions.ts
packages/react-components/react-tag-picker-preview/src/utils/useButtonTriggerSlot.ts
packages/react-components/react-tag-picker-preview/src/utils/useComboboxBaseState.ts
packages/react-components/react-tag-picker-preview/src/utils/useInputTriggerSlot.ts
packages/react-components/react-tag-picker-preview/src/utils/useListboxSlot.ts
packages/react-components/react-tag-picker-preview/src/utils/useTriggerSlot.ts

1. Rollback from https://github.com/microsoft/fluentui/pull/30646 as those hooks are unstable and cannot be exported
2. copy hooks from `react-combobox` to `react-tag-picker-preview` package manually
- Fixes #

chore(react-combobox): rollback export of internal hooks

---

.storybook/preview.js
packages/react-components/react-storybook-addon-export-to-sandbox/src/sandbox-scaffold.spec.ts
packages/react-components/react-storybook-addon-export-to-sandbox/src/sandbox-scaffold.ts

We used Codesandbox for export.
We use Stackblitz for export.
Also bumped exports to use Vite 5 & React 18.
CodeSandbox recently changes their policies and now you have **only 10** (private by default) sandboxes, so folks in the crew have this problem:
And to avoid it, we have to manually port code to Stackblitz 👎 That's a huge PITA in our workflow.

docs: switch to Stackblitz export

---

.github/CODEOWNERS

`docs/` is applied on whole repo, which creates false positives on ownership
see PR title
- Replaces https://github.com/microsoft/fluentui/pull/30678
- Fixes https://github.com/microsoft/fluentui/pull/30483/files#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7

fix(.github): dont apply docs/ rule codeowner on whole monorepo to create false positivie ownership

---

packages/react-components/react-menu/stories/Menu/MenuAnchorToTarget.stories.tsx

The "anchor to custom target" example has an issue where the menu closes & immediately re-opens when you click either custom trigger while the menu is open. The root cause is it closes on an outside click, then re-opens on the custom trigger click.
Adds a check to the `onOpenChange` logic to not close as an outside click when clicking the custom trigger.
Related to #30588, fixes the mentioned issue in our examples

fix: Anchor to custom target example closes menu

---

packages/react-components/react-swatch-picker-preview/etc/react-swatch-picker-preview.api.md
packages/react-components/react-swatch-picker-preview/src/components/ColorSwatch/ColorSwatch.test.tsx
packages/react-components/react-swatch-picker-preview/src/components/ColorSwatch/ColorSwatch.tsx
packages/react-components/react-swatch-picker-preview/src/components/ColorSwatch/useColorSwatch.ts
packages/react-components/react-swatch-picker-preview/src/components/ColorSwatch/useColorSwatchStyles.styles.ts
packages/react-components/react-swatch-picker-preview/src/components/SwatchPicker/SwatchPicker.types.ts
packages/react-components/react-swatch-picker-preview/src/components/SwatchPicker/useSwatchPicker.ts
packages/react-components/react-swatch-picker-preview/stories/ColorSwatch/ColorSwatchDefault.stories.tsx
packages/react-components/react-swatch-picker-preview/stories/SwatchPicker/SwatchPickerDefault.stories.tsx

This UI was tested by a11y team.
This PR includes:
- new `spacing` prop
- Styles for the swatch states
The following PRs would include:
1. HC for dark theme
2. Stories

feat(swatch-picker): UI changes and spacing

---

packages/react-components/react-badge/stories/Badge/BadgeColor.stories.tsx
packages/react-components/react-badge/stories/CounterBadge/CounterBadgeColor.stories.tsx

Related to an ADO bug.
Our badge and counter badge have stories that show color-only changes, so I added a line of warning to each story about the WCAG Use of Color requirement.

docs: add text warning to badge color stories

---

packages/react-components/react-button/stories/Button/ButtonLoading.stories.tsx
packages/react-components/react-button/stories/Button/index.stories.tsx

This PR adds a story for the `Button` component that shows how to achieve a convincing loading state by customizing the contents and styles of the `Button component.
- Fixes #29724

docs: Adding story showing how to achieve a loading Button with customizations

---

change/@fluentui-react-aria-4f48a105-403c-4fc6-9ebb-5c0c1988a6ca.json
packages/react-components/react-aria/etc/react-aria.api.md
packages/react-components/react-aria/src/activedescendant/ActiveDescendantContext.ts
packages/react-components/react-aria/src/activedescendant/types.ts
packages/react-components/react-aria/src/activedescendant/useActiveDescendant.ts
packages/react-components/react-aria/src/activedescendant/useActivedescendant.test.tsx

1. provides `showAttributes` and `hideAttributes` method to `ActiveDescendantImperativeRef`
2. adds test to ensure behaviour
NVDA and JAWS have bugs that suppress reading the input value text when `aria-activedescendant` is set.
To prevent this, the HTML attribute should be removed when a user presses left/right arrows (https://github.com/microsoft/fluentui/issues/26359#issuecomment-1397759888).
- https://github.com/microsoft/fluentui/issues/26652

feat(react-aria): active descendants imperative handle to toggle attribute visibility

---

azure-pipelines.release-fluentui.yml

- old task publish artifacts are not allowed - need to switch to 1es ones
> 1ES PT blocks the common ADO publish tasks (such as PublishPipelineArtifact@1, PublishBuildArtifacts@1, ArtifactDropTask@1, ...) and requires customers to use 1ES PT outputs instead
- adding explicit dryRun mode notifications
- dont run docsite publish if `dryRun` is enabled
- Partially implements https://github.com/microsoft/fluentui/issues/30265

ci(northstar): fix release pipeline issues with publish artifact tasks and add `dryRun` mode notification step

---

rfcs/shared/build-system/08-type-checking-perf-improvements.md

[RFC 👁️](https://github.com/microsoft/fluentui/pull/30514/files?short_path=fd1f651#diff-fd1f65124cb8a5f905a337bf23e6dd67b607808793d84f21178c25c80b3a8028)
- relates to https://github.com/microsoft/fluentui/issues/30516

docs(rfcs): type-checking-perf-improvements

---

change/@fluentui-react-tabs-a844d153-94fc-48f8-9bbc-e8b518faf357.json
packages/react-components/react-tabs/src/components/Tab/useTabStyles.styles.ts

active tab indicator had z-index of 1 which caused overlap issues with floating UI like dialogs/menus.
z-index is removed.
- Fixes #30343
Note: This PR will replace another PR that is stuck without a change file: https://github.com/microsoft/fluentui/pull/30368

fix: react-tabs: Removed unnecessary zIndex from active tab indicator

---

packages/react-components/react-nav-preview/etc/react-nav-preview.api.md
packages/react-components/react-nav-preview/src/NavDrawer.ts
packages/react-components/react-nav-preview/src/components/NavDrawer/NavDrawer.test.tsx
packages/react-components/react-nav-preview/src/components/NavDrawer/NavDrawer.tsx
packages/react-components/react-nav-preview/src/components/NavDrawer/NavDrawer.types.ts
packages/react-components/react-nav-preview/src/components/NavDrawer/__snapshots__/NavDrawer.test.tsx.snap
packages/react-components/react-nav-preview/src/components/NavDrawer/index.ts
packages/react-components/react-nav-preview/src/components/NavDrawer/renderNavDrawer.tsx
packages/react-components/react-nav-preview/src/components/NavDrawer/useNavDrawer.ts
packages/react-components/react-nav-preview/src/components/NavDrawer/useNavDrawerStyles.styles.ts
packages/react-components/react-nav-preview/src/index.ts
packages/react-components/react-nav-preview/stories/NavDrawer/NavDrawerBestPractices.md
packages/react-components/react-nav-preview/stories/NavDrawer/NavDrawerDefault.stories.tsx
packages/react-components/react-nav-preview/stories/NavDrawer/index.stories.tsx

Nav will live in an inline drawer in 99% of cases.
It will have a drawer component and several nav specific providers built in.
This PR scaffolds it all out.
Result of running:
`yarn create-component`, commenting out the custom style hooks, running `yarn build` to update the API.
Part of #26649

feature: scaffold NavDrawer

---

azure-pipelines-ci.yml

- CI pipeline is failing 
- removes that step as there's no longer any files triggering a security violation
- see test[ pipeline run](https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=336022&view=results)

CI: remove failing pipeline step as it's no longer needed

---

change/@fluentui-react-infolabel-9fb527c6-057b-4966-b5e2-89d75f410b93.json
packages/react-components/react-infolabel/cypress.config.ts
packages/react-components/react-infolabel/package.json
packages/react-components/react-infolabel/src/components/InfoButton/useInfoButton.tsx
packages/react-components/react-infolabel/src/components/InfoLabel/InfoLabel.cy.tsx
packages/react-components/react-infolabel/tsconfig.cy.json

The InfoLabel popover doesn't dismiss if the InfoButton is clicked when the popover is already open. Or more accurately, it dismisses and immediately shows again. This happens because the popover gets dismissed when focus moves outside, which  happens on mouseDown on the button. Subsequently, the button's click event shows the popover again.
* Don't dismiss the popover if focus moves to the InfoButton that launched it. Instead, the popover is only dismissed when focus moves outside of _both_ the popover _and_ the button.
* Use React's onBlurCapture instead of a native focusout event, to avoid an event listener leak. (The focusout listener was never removed when the ref changed.)
- Fixes #30725

fix: InfoLabel popover dismisses if the InfoButton is clicked when it is already open

---

change/@fluentui-react-infolabel-db6aadb8-3d81-4e84-ad8d-a1e7831e4104.json
packages/react-components/react-infolabel/src/components/InfoLabel/useInfoLabel.ts

Currently, the popup (an element with `role=note`) got focus, but didn't have an explicit accessible name (it functions as a container role, so the content got read even without it).
Adds an explicit accName equal to the note's text content, using a self-referencing `aria-labelledby`. I tested to ensure we weren't introducing duplicate reading (i.e. of both the content and accName), and it appears that only partially happens with Talkback. The results are as follows (tested the announcement when opening an infolabel containing text & a link):
- macOS VO + Chrome: no difference with self-referencing label, reads text but not link when opened (i.e. reads first node/swipe target then stops)
- macOS VO + Safari: no difference, same as Chrome
- iOS VO: no difference, same as macOS
- NVDA + …

fix: add `aria-labelledby` to Infolabel note

---

.github/CODEOWNERS

Add codeowners for `apps/xplat-v9` and `react-platform-adapter` package.
This is for the cross-platform react prototype work being done on the `xplat` branch. This branch won't be merged to `master` in the near future. However, we are using PRs for work on the `xplat` branch, and need appropriate codeowners set.

[xplat] Add CODEOWNERS for xplat-v9 app and react-platform-adapter package

---

change/@fluentui-foundation-legacy-7c531b8e-750e-4b07-a50d-489529c3ca8d.json
change/@fluentui-merge-styles-42f4b3e7-c71a-4db9-9b65-cb0f47039fe6.json
change/@fluentui-style-utilities-a3584f92-b448-414f-a190-8fa3995f05aa.json
change/@fluentui-utilities-274e92d1-419a-48a6-8d3c-5174bffe5e4d.json
packages/foundation-legacy/etc/foundation-legacy.api.md
packages/foundation-legacy/src/IComponent.ts
packages/foundation-legacy/src/createComponent.tsx
packages/foundation-legacy/src/next/IComponent.ts
packages/foundation-legacy/src/next/ISlots.ts
packages/foundation-legacy/src/next/composed.tsx
packages/merge-styles/etc/merge-styles.api.md
packages/merge-styles/src/IStyleFunction.ts
packages/merge-styles/src/IStyleSet.ts
packages/merge-styles/src/concatStyleSetsWithProps.ts
packages/merge-styles/src/index.ts
packages/merge-styles/src/mergeStyleSets.test.ts
packages/merge-styles/src/mergeStyleSets.ts
packages/style-utilities/etc/style-utilities.api.md
packages/style-utilities/src/MergeStyles.ts
packages/utilities/etc/utilities.api.md
packages/utilities/src/classNamesFunction.ts
packages/utilities/src/styled.test.tsx
packages/utilities/src/styled.tsx

The type definition of IStyleSet has a circular dependency, which causes an error when used with TypeScript 5.3.
Create an `IStyleSetBase` type to act as the `extends` constraint for type arguments, and avoid a circular reference.
- Fixes #30714

fix: Update IStyleSet type to fix error when using TypeScript 5.3+

---

change/@fluentui-react-button-452be093-2c6e-402a-8a9c-52875d63bfac.json
packages/react-components/react-button/src/components/ToggleButton/useToggleButtonStyles.styles.ts

Styles for the `icon` slot of the `ToggleButton` component when it was `checked` and had a `subtle` or `transparent` appearance where not being correctly applied.
Correct styles are applied to the `icon` slot of the `ToggleButton` component when it is `checked` and has a `subtle` or `transparent` appearance.
- Fixes #30476

fix: Applying correct styles to icon when ToggleButton is checked and has a subtle or transparent appearance

---

packages/react-components/react-platform-adapter/.eslintrc.json
packages/react-components/react-platform-adapter/src/XPlatProvider/index.ts
packages/react-components/react-platform-adapter/src/index.ts
packages/react-components/react-platform-adapter/src/jsx/index.ts
packages/react-components/react-platform-adapter/src/jsx/jsxPlatformAdapter.native.ts
packages/react-components/react-platform-adapter/src/jsx/jsxPlatformAdapter.ts
packages/react-components/react-platform-adapter/src/styling/index.ts

Use of "barrel" files and `export *` prevent treeshaking when bundling with Metro.
Barrel files are removed, `@rnx-kit/no-export-all` rule is enabled.
n/a

fix: ensure package is tree-shakeable

---

apps/xplat-v9/StrictDomDemo.tsx
packages/react-components/react-button/package.json
packages/react-components/react-button/src/components/Button/useButtonStyles.styles.ts

ℹ️ Note: This is being merged into the `xplat` branch, not `master`.
Hook up Button to support cross-platform styles. Cross-plat reset styles don't support shorthands, so need to convert the styles to expand shorthands.

chore(xplat): Add xplat support to Button

---

change/@fluentui-react-tags-aa26dad6-0f14-40e2-b558-0f7d957bdb31.json
packages/react-components/react-tags/etc/react-tags.api.md
packages/react-components/react-tags/src/components/InteractionTag/useInteractionTag.tsx
packages/react-components/react-tags/src/components/Tag/useTag.tsx
packages/react-components/react-tags/src/components/TagGroup/TagGroup.types.ts
packages/react-components/react-tags/src/components/TagGroup/useTagGroup.ts
packages/react-components/react-tags/src/components/TagGroup/useTagGroupContextValues.ts
packages/react-components/react-tags/src/contexts/tagGroupContext.tsx

1. Adds `appearance` and `dismissible` to `TagGroupContext` as optional properties to ensure no breaking change
- Fixes #

feat(react-tags): adds appearance and dismissible to TagGroupContext

---

change/@fluentui-react-table-e925277a-0f22-408e-b547-82d19823c883.json
packages/react-components/react-table/src/hooks/useTableColumnResizeMouseHandler.ts
packages/react-components/react-table/src/hooks/useTableColumnSizing.tsx

See #27803 for details.
Previously when column was resized and minimum width was hit, as the cursor ends up over the column header, it would trigger a click event, resulting in an unwanted sort.
The sort is not triggered anymore, the pointer events on the header are disabled during the resizing.
- Fixes #27803

fix: DataGrid - prevent automatic sort when column resizing finishes

---

change/@fluentui-react-teaching-popover-preview-5d5a06c5-1916-45c4-bfd2-1d1ff7434363.json
packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverCarousel/__snapshots__/TeachingPopoverCarousel.test.tsx.snap
packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverCarouselNav/__snapshots__/TeachingPopoverCarouselNav.test.tsx.snap
packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverCarouselNav/useTeachingPopoverCarouselNav.tsx
packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverCarouselNavButton/__snapshots__/TeachingPopoverCarouselNavButton.test.tsx.snap
packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverCarouselNavButton/useTeachingPopoverCarouselNavButton.tsx
packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverHeader/__snapshots__/TeachingPopoverHeader.test.tsx.snap
packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverHeader/useTeachingPopoverHeader.tsx
packages/react-components/react-teaching-popover-preview/src/components/TeachingPopoverTitle/useTeachingPopoverTitle.tsx
packages/react-components/react-teaching-popover-preview/stories/TeachingPopover/TeachingPopoverBranded.stories.tsx
packages/react-components/react-teaching-popover-preview/stories/TeachingPopover/TeachingPopoverCarousel.stories.tsx
packages/react-components/react-teaching-popover-preview/stories/TeachingPopover/TeachingPopoverCarouselBranded.stories.tsx
packages/react-components/react-teaching-popover-preview/stories/TeachingPopover/TeachingPopoverCarouselText.stories.tsx
packages/react-components/react-teaching-popover-preview/stories/TeachingPopover/TeachingPopoverDefault.stories.tsx
packages/react-components/react-teaching-popover-preview/stories/TeachingPopover/TeachingPopoverDefaultBranded.stories.tsx

Updates required to pass accessibility checks, some strings in aria-labels for buttons - should we enforce this another way?
Navigation container is now a tablist role, contains tab items.
Added default aria labels to text-less buttons
Images with alt text in stories
#30804

TeachingPopover: Accessibility updates

---

change/@fluentui-react-menu-7e47016d-d354-4335-bfde-d5815e1184df.json
packages/react-components/react-menu/src/components/MenuItem/useMenuItemStyles.styles.ts

1. adds proper [system colors](https://drafts.csswg.org/css-color-4/#css-system-colors) on hover if [forced colors](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors) is active
- Fixes https://github.com/microsoft/fluentui/issues/30069

bugfix(react-menu): add system colors on hover

---

change/@fluentui-react-input-4b4f4231-067c-4139-875c-7d32e5dd5da6.json
packages/react-components/react-input/src/components/Input/useInputStyles.styles.ts

The Input control had padding on the root div, which reduced the size of the true input element, and reduced its hit target to not fill the entire space.
Combine the padding from the `root` and `input` slots onto just the `input` itself. This expands the hit target of the input to extend to the borders of the `root`.
If there is `contentBefore` or `contentAfter`, the original padding values are used to make sure everything aligns appropriately.
- Fixes #30491

chore(input): Increase hit target of input element to fill to the border

---

packages/react-components/react-tag-picker-preview/etc/react-tag-picker-preview.api.md
packages/react-components/react-tag-picker-preview/src/components/TagPicker/TagPicker.types.ts
packages/react-components/react-tag-picker-preview/src/components/TagPicker/useTagPicker.ts
packages/react-components/react-tag-picker-preview/src/components/TagPicker/useTagPickerContextValues.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/TagPickerControl.types.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/useTagPickerControl.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/useTagPickerControlStyles.styles.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerInput/TagPickerInput.types.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerInput/useTagPickerInput.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerInput/useTagPickerInputStyles.styles.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerOption/TagPickerOption.types.ts
packages/react-components/react-tag-picker-preview/src/contexts/TagPickerContext.ts
packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerDisabled.stories.tsx
packages/react-components/react-tag-picker-preview/stories/TagPicker/index.stories.tsx

1. Adds `disabled` state control to `TagPicker`
2. Adds `disabled` state control to `TagPickerInput`
3. Adds `disabled` style to `TagPickerInput` and `TagPickerControl`
4. Removes `disabled` state control from `TagPickerOption`
5. Adds story to demonstrate disabling

feat(react-tag-picker-preview): adds disabled state

---

packages/react-components/react-tag-picker-preview/etc/react-tag-picker-preview.api.md
packages/react-components/react-tag-picker-preview/src/components/TagPicker/TagPicker.types.ts
packages/react-components/react-tag-picker-preview/src/components/TagPicker/useTagPicker.ts

1. modifies `onOptionSelect` callback to ensure it follows the new Event handling pattern https://github.com/microsoft/fluentui/pull/29296

chore(react-tag-picker-preview): onOptionSelect should adopt new event handling pattern

---

packages/react-components/react-nav-preview/src/components/NavDrawer/useNavDrawer.ts
packages/react-components/react-nav-preview/stories/NavDrawer/NavDrawerDefault.stories.tsx

The Nav is likely to have at least 10 items in it, which is too many to expect a keyboard user to tab through before getting to the main content area of the page.
This PR adds tabster with a few defaults of circular and vertical.
Will consumers be able to elegantly disagree with these defaults?
https://github.com/microsoft/fluentui/assets/17346018/f242647a-a2b2-4042-ba88-fdd73bdda833
Chips away at #26649

feat: Adds Tabster to Nav

---

packages/react-components/react-platform-adapter-preview/etc/react-platform-adapter-preview.api.md
packages/react-components/react-platform-adapter-preview/src/index.ts
packages/react-components/react-platform-adapter-preview/src/utilities/isReactNative.native.ts
packages/react-components/react-platform-adapter-preview/src/utilities/isReactNative.ts
packages/react-components/react-provider/src/components/FluentProvider/renderFluentProvider.tsx

ℹ️ Note: This being merged into the `xplat` branch, not `master`.
FluentProvider renders a `<style>` tag when rendering in SSR for web. The `canUseDOM()` function to detect this case was incorrectly returning false for react native.
Add a `isReactNative()` function to explicitly check if on React Native. Update FluentProvider to not render a `<style>` tag on native.

fix(xplat): Fix FluentProvider, don't render style tag on native

---

change/@fluentui-codemods-65485060-b665-4208-aed8-3a814d1fb9f7.json
packages/codemods/src/helpers/maybe.ts
packages/codemods/src/helpers/tests/maybe.test.ts

ℹ️ **Note**: This is NOT updating the project to use TypeScript 5.3.3, and an update to the TypeScript version is not planned as part of this change. It is only fixing build errors that would occur if it were built against TypeScript …

fix(codemods): Fix build errors in TypeScript 5.3.3

---

change/@fluentui-foundation-legacy-c6b23d62-8aa6-4679-8d5d-780d48c89a89.json
packages/foundation-legacy/etc/foundation-legacy.api.md
packages/foundation-legacy/src/slots.tsx

The fixes in this PR are caused by a breaking change in TS 4.8: [Unconstrained Generics No Longer Assignable to `{}`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-8.html#unconstrained-generics-no-longer-assignabl …

fix(foundation-legacy): Fix build errors in TypeScript 5.3.3

---

change/@fluentui-react-calendar-compat-7bc02258-da6a-402e-a98a-a46856c95a7f.json
packages/react-components/react-calendar-compat/etc/react-calendar-compat.api.md
packages/react-components/react-calendar-compat/src/utils/dateMath/dateMath.ts

The fixes in this PR are caused by a breaking change in TS 5.0: [Forbidden Implicit Coercions in Relational Operators](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#forbidden-implicit-coercions-in-relationa …

fix(react-calendar-compat): Fix build errors in TypeScript 5.3.3

---

change/@fluentui-react-charting-719b158e-4752-45fd-991d-4e700d135f10.json
packages/react-charting/src/components/LineChart/LineChart.base.tsx

ℹ️ **Note**: This is NOT updating the project to use TypeScript 5.3.3, and an update to the TypeScript version is not planned as part of this change. It is only fixing build errors that would occur if it were built against TypeScript …

fix(react-charting): Fix build errors in TypeScript 5.3.3

---

change/@fluentui-react-experiments-8f55aad9-faab-465e-b18d-2aef0e760a72.json
packages/react-experiments/src/components/FloatingSuggestions/FloatingSuggestions.tsx
packages/react-experiments/src/components/FloatingSuggestions/Suggestions/SuggestionsControl.tsx
packages/react-experiments/src/components/FloatingSuggestions/Suggestions/SuggestionsCore.tsx
packages/react-experiments/src/components/PersonaCoin/PersonaCoin.view.tsx

The fixes in this PR are caused by:
1. Breaking change in TS 4.8: [Unconstrained Generics No Longer Assignable to `{}`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-8.html#unconstrained-generics-no-longer-assigna …

fix(react-experiments): Fix build errors in TypeScript 5.3.3

---

change/@fluentui-react-input-459f0da7-7e7d-4673-b9d6-e81e93766f2c.json
packages/react-components/react-input/src/components/Input/Input.test.tsx
packages/react-components/react-input/src/components/Input/useInput.ts

Reverts microsoft/fluentui#30534
The initial value of the input's controllable state is explicitly an empty string since we pass the `value` in to the native rendered `<input />` always. After the above PR an uncontrolled `Input` component _**always**_ renders a react warning because any user input will output this error in non-production environments
This is a blocking issue for any user who consumes this change and has test failures on console.error. Here's a screen recording 
If an `undefined` value is necessary as an initial value then we should create an issue to track since the change in non-trivial. We _**always**_ pass the `value` to intrinsic `input` elements and that would need to change first.

Revert "fix: Input should start with undefined, same as textarea"

---

apps/xplat-v9/README.md
packages/react-components/babel-preset-global-context/package.json
packages/react-components/react-platform-adapter-preview/package.json
yarn.lock

ℹ️ Note: This is being merged into the `xplat` branch, not `master`
After the latest merge-commit, some dependencies went out of sync and syncpack started ❌
This PR addressed that, accounting for recent changes from these commits:
* https://github.com/microsoft/fluentui/commit/6a3e6bbbf140f0b87f1fe98a8b27fd813c16aec2
* https://github.com/microsoft/fluentui/commit/d785f27214ba60429d6273db31872fabe56916d5
This is necessary 'cause `react-platform-adapter-preview` is not present in `main` branch and the babel types in `babel-preset-global-context` were added in this `xplat`-only [commit](https://github.com/microsoft/fluentui/commit/756b683a1f6d4520c3d20a0582bfb14864459d1d).
syncpack is green again.
And added a note to the Readme of xplat-v9 about this part of the keeping up with main branch …

fix(deps): fix dependencies post merge commit

---

change/@fluentui-react-accordion-60736783-aa50-492f-a93b-5557fbeebfba.json
change/@fluentui-react-utilities-73497b94-9cd3-45c2-a951-45082c5596cd.json
packages/react-components/react-platform-adapter-preview/package.json
packages/react-components/react-platform-adapter-preview/src/index.ts
packages/react-components/react-provider/src/components/FluentProvider/renderFluentProvider.tsx
packages/react-components/react-utilities/package.json
packages/react-components/react-utilities/src/ssr/canUseDOM.ts

ℹ️ Note: This is being merged into the `xplat` branch, not `master`
The `canUseDOM` utility incorrectly returns false when used with react-strict-dom.
Hardcode `canUseDOM` to return true when running on react native. There is no server-side-rendering to consider for react native.

chore(xplat): Update canUseDOM to be aware of ReactNative

---

apps/xplat-v9/README.md

ℹ️ Note: This is being merged into the `xplat` branch, not `master`
Quick PR to add a missing link to the README that I forgot from [previous PR](https://github.com/microsoft/fluentui/pull/30876).

chore(xplat readme): fix missing link

---

packages/react-components/react-tag-picker-preview/etc/react-tag-picker-preview.api.md
packages/react-components/react-tag-picker-preview/src/components/TagPicker/TagPicker.types.ts
packages/react-components/react-tag-picker-preview/src/components/TagPicker/useTagPicker.ts
packages/react-components/react-tag-picker-preview/src/components/TagPicker/useTagPickerContextValues.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerOption/TagPickerOption.types.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerOption/useTagPickerOption.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerOption/useTagPickerOptionStyles.styles.ts

1. adds `TagPickerOnOpenChangeData` type to not propagate `onOpenChange` from `ComboboxState` as that one does not follow newest pattern https://github.com/microsoft/fluentui/pull/29296
2. adds `defaultSelectedOptions` support as a valid `prop`
3. opts for `Pick` instead of `Omit` on most of the types signatures, to avoid usage of state spreading.

chore(react-tag-picker): code clean-up

---

change/@fluentui-react-spinner-503d4d53-0c62-4c35-b641-f805615cd2c8.json
packages/react-components/react-spinner/src/components/Spinner/useSpinnerStyles.styles.ts

The rotation of the SVG sometimes triggered parent scroll overflow (i.e. when rotated 45deg, the diagonal dimension is longer than the 0deg height).
Adds an `overflow: hidden` to the span wrapping the SVG
- Fixes #30610

fix: rotating SVG should not cause parent overflow

---

change/@fluentui-react-2d68c9d6-2ee1-490d-96a6-83b91e521f24.json
packages/react/src/components/GroupedList/GroupedList.base.tsx

GroupedList did not import & use `FocusRects`, so if used on its own, focus is not visible (e.g. in [this codepen](https://codepen.io/sbarrameda/pen/jOXNPvo?editors=0010)).
Note: this uses `<FocusRects>` as a component instead of `useFocusRects`, since GroupedList is still a class component.
Added FocusRects
Fixes half of this [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/18041)

fix: GroupedList initiates FocusRects

---

change/@fluentui-react-tag-picker-preview-41407ab4-eb34-417a-b086-f5c149bd0c4d.json
packages/react-components/react-tag-picker-preview/src/utils/useComboboxBaseState.ts
packages/react-components/react-tag-picker-preview/src/utils/useOptionCollection.ts
packages/react-components/react-tag-picker-preview/src/utils/useSelection.ts

Follow up on https://github.com/microsoft/fluentui/issues/26652#issuecomment-2029563676
1. removes erroneous imports from `@fluentui/react-combobox`
- Fixes #

bugfix(react-tag-picker): removes errouneous combobox imports

---

packages/react-components/react-tags/stories/TagGroup/TagGroupDismiss.stories.tsx

fix #30920
Reset button is disabled when one tag is dismissed:
Reset can only be done when all tags are dismissed
Reset can be done when one tag is dismissed

docs(react-tag): allow reset dismiss example when one tag is dismissed

---

change/@fluentui-react-accordion-7cc895ca-0a54-47c7-bbf4-7ca1d1553d65.json
packages/react-components/react-accordion/src/components/AccordionHeader/useAccordionHeaderStyles.styles.ts

There was a transparent border on the AccordionHeader button, which showed up in high contrast mode (since the transparent color is overridden). This made the focus outline barely visible (second item is focused):
There is no 1px border, so the focus outline in HCM is clearly visible, and the accordion styles match the appearance outside of forced-colors mode. This doesn't change the accordion height, since it already has a `44px` height style.
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/18624)

fix: remove border from high contrast mode to make focus more visible

---

change/@fluentui-react-search-preview-97e1e824-f803-4a7f-8912-3e6b690e70bf.json
packages/react-components/react-search-preview/etc/react-search-preview.api.md
packages/react-components/react-search-preview/src/index.ts

The `SearchBoxChangeEvent` type was not exported.
The `SearchBoxChangeEvent` is exported.
- Fixes #30869

fix: export SearchBoxChangeEvent type

---

change/@fluentui-react-tag-picker-preview-fe30a51d-a476-480c-b7b5-22c1285c35ad.json
packages/react-components/react-tag-picker-preview/etc/react-tag-picker-preview.api.md
packages/react-components/react-tag-picker-preview/src/TagPickerOptionGroup.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerList/renderTagPickerList.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerOptionGroup/TagPickerOptionGroup.test.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerOptionGroup/TagPickerOptionGroup.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerOptionGroup/TagPickerOptionGroup.types.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerOptionGroup/__snapshots__/TagPickerOptionGroup.test.tsx.snap
packages/react-components/react-tag-picker-preview/src/components/TagPickerOptionGroup/index.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerOptionGroup/renderTagPickerOptionGroup.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerOptionGroup/useTagPickerOptionGroup.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerOptionGroup/useTagPickerOptionGroupStyles.styles.ts
packages/react-components/react-tag-picker-preview/src/index.ts
packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerGrouped.stories.tsx
packages/react-components/react-tag-picker-preview/stories/TagPicker/index.stories.tsx

1. adds `TagPickerOptionGroup` component
- Fixes #

feat(react-tag-picker): adds TagPickerOptionGroup component

---

apps/public-docsite-v9/src/Concepts/QuickStart.stories.mdx

We didn't now show how to "quick start" Fluent v9 with [React 18 APIs](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis).
We show how to quick start Fluent v9 with React 18 APIs
- Fixes #30690

docs: add React 18 setup to quick start docs

---

change/@fluentui-react-combobox-a8acb294-e1c7-46f6-b291-196ddda0ffe4.json
change/@fluentui-react-tag-picker-preview-74ebb8dc-b7e3-4f37-90dc-a5780fc43f0a.json
packages/react-components/react-combobox/etc/react-combobox.api.md
packages/react-components/react-combobox/src/components/Combobox/Combobox.types.ts
packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx
packages/react-components/react-combobox/src/utils/ComboboxBase.types.ts
packages/react-components/react-combobox/src/utils/useComboboxBaseState.ts
packages/react-components/react-tag-picker-preview/etc/react-tag-picker-preview.api.md
packages/react-components/react-tag-picker-preview/src/components/TagPicker/TagPicker.types.ts
packages/react-components/react-tag-picker-preview/src/components/TagPicker/useTagPicker.ts
packages/react-components/react-tag-picker-preview/src/components/TagPicker/useTagPickerContextValues.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerInput/TagPickerInput.types.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerInput/useTagPickerInput.tsx
packages/react-components/react-tag-picker-preview/src/contexts/TagPickerContext.ts
packages/react-components/react-tag-picker-preview/src/utils/ComboboxBase.types.ts
packages/react-components/react-tag-picker-preview/src/utils/useComboboxBaseState.ts
packages/react-components/react-tag-picker-preview/src/utils/useInputTriggerSlot.ts
packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerFreeform.stories.tsx
packages/react-components/react-tag-picker-preview/stories/TagPicker/index.stories.tsx

1. moves `freeform` and `disabled` from `ComboboxProps` and `ComboboxState` to `ComboboxBaseProps` and `ComboboxBaseState`
2. moves internal `selection` logic from `useCombobox` to `useComboboxState`
3. adds `freeform` support for `TagPicker`
4. ensures modifications in `@fluentui/react-combobox` are followed on `@fluentui/react-tag-picker-preview`
- Fixes #

chore(react-combobox): move `freeform` and `disabled` to ComboboxBase types

---

change/@fluentui-react-provider-a18c5467-7dd3-413d-a1ea-e6dc40d0d731.json
packages/react-components/react-provider/src/components/FluentProvider/useFluentProvider.ts

When a FluentProvider component re-renders, the associated Style element is removed and re-inserted to the HEAD. Aside from the Perf improvement, this can lead to rendering un-styled child Components, if the Browser gets few frames between the Deletion and Insertion of the Style element.
Example, taken from PowerApps bug (No PII, All is debug-data)
Resizing triggers re-rendering of React Tree, including FluentProvider
Adding a "Break on -> Node Removal" to the Style element revealed the cause.
The root cause was passing a new Empty Object in the Props to `useFluentProviderThemeStyleTag` every time the FluentProvider re-renders.
We are now using a memoized empty Object, similar to the `EMPTY_OBJECT` which was created previously for the same issue.
N/A- There is an issue on Power Apps …

Using a memoized Empty Object for StyleTag rendererAttributes prop

---

change/@fluentui-react-card-c41da4ed-3507-468e-ba27-a40458dd122b.json
packages/react-components/react-card/src/components/CardFooter/useCardFooterStyles.styles.ts
packages/react-components/react-card/src/components/CardHeader/useCardHeaderStyles.styles.ts

Card action buttons did not adapt to the highlighted bg of hovered or selected cards:
it works!
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/18631)

fix: Card actions adopt custom high contrast mode colors

---

change/@fluentui-react-charting-d62e0aee-98a2-4b2f-88e2-4913bde0b1c7.json
packages/react-charting/src/components/DonutChart/__snapshots__/DonutChart.test.tsx.snap
packages/react-charting/src/components/DonutChart/__snapshots__/DonutChartRTL.test.tsx.snap
packages/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChart.test.tsx.snap
packages/react-charting/src/components/GroupedVerticalBarChart/__snapshots__/GroupedVerticalBarChartRTL.test.tsx.snap
packages/react-charting/src/components/HorizontalBarChart/__snapshots__/HorizontalBarChart.test.tsx.snap
packages/react-charting/src/components/StackedBarChart/__snapshots__/MultiStackedBarChart.test.tsx.snap
packages/react-charting/src/components/StackedBarChart/__snapshots__/StackedBarChart.test.tsx.snap
packages/react-charting/src/utilities/ChartHoverCard/ChartHoverCard.styles.ts

Fix colors for high contrast mode in chart hover card

---

docs/react-v9/contributing/dev-workflow.md

Created a doc for the basic dev workflow loop.
Things to look for:
- Typos & grammar
- Any updates you think I should add?
- Broken links
Addresses https://github.com/microsoft/fluentui/issues/30642

docs: New workflow doc

---

change/@fluentui-react-abae2dcb-355d-404a-90a2-df54f9744ba1.json
packages/react/src/components/Dropdown/Dropdown.styles.ts
packages/react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap

The focus outline color didn't have guaranteed contrast against the selected option bg color in high contrast mode:
fixed!
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/16200)

fix: v8 Dropdown selected option focus outline has contrast against bg

---

change/@fluentui-web-components-bf5eb75f-530a-47ce-86d7-0e1b7f5155f4.json
packages/web-components/package.json
yarn.lock

When something like a flyout was invoked from a toolbar and focus was moved manually to another node, toolbar was stealing focus.
Toolbar no longer steals focus
- Fixes #

fix(web-components): fix toolbar stealing focus when document has moved focus to another element

---

packages/react-components/react-storybook-addon-export-to-sandbox/src/sandbox-scaffold.spec.ts
packages/react-components/react-storybook-addon-export-to-sandbox/src/sandbox-scaffold.ts

Every exported example on Stackblitz has:
For context: in #30613 I updated React version to be 18, but we still were using deprecated `ReactDOM.render()` API.
No errors/warnings about deprecated APIs.
- Fixes #

fix(react-storybook-addon-export-to-sandbox): use React v18 APIs

---

change/@fluentui-react-tag-picker-preview-fd7805bc-8cca-4f4b-b0b1-65f51c89d40d.json
packages/react-components/react-tag-picker-preview/etc/react-tag-picker-preview.api.md
packages/react-components/react-tag-picker-preview/src/components/TagPickerButton/TagPickerButton.types.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/TagPickerControl.types.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerOption/TagPickerOption.types.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerOption/useTagPickerOption.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerOption/useTagPickerOptionStyles.styles.ts

1. removes unused props, like:
- `clearable` (this property makes no sense in the `TagPicker`, as clear state is delegated to `secondaryAction` responsibility
- `selected` (this might be introduced again once the selection feature is introduced)
- `multiselect` (this might be introduced again once multiselection feature is introduced)
- Fixes #

chore(react-tag-picker): removes unused props

---

change/@fluentui-react-tag-picker-preview-53df5fed-1401-407b-a8b2-1b6cdeccd079.json
packages/react-components/react-tag-picker-preview/etc/react-tag-picker-preview.api.md
packages/react-components/react-tag-picker-preview/src/components/TagPicker/TagPicker.types.ts
packages/react-components/react-tag-picker-preview/src/components/TagPicker/renderTagPicker.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPicker/useTagPicker.ts

1. adds `inline` property to `TagPicker` to follow on [`Popover`](https://react.fluentui.dev/?path=/docs/components-popover--default) signature 
- Fixes #

feat(react-tag-picker): adds inline property

---

change/@fluentui-react-aria-d78c8463-7fd5-4354-b184-3f71f64bd3ed.json
change/@fluentui-react-combobox-c3631462-01cd-4e7c-be6a-98696c644bf6.json
packages/react-components/react-aria/src/activedescendant/useOptionWalker.ts
packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx
packages/react-components/react-combobox/src/utils/useTriggerSlot.ts

`last()` wasn't implemented in Combobox, and there was a bug in the `useOptionWalker` logic, so the End key didn't correctly move the active option.
It works now, and added tests.
- Fixes an ADO a11y bug

fix: End key should move activeOption in Combobox & related controls

---

change/@fluentui-react-4cdfc125-5e0f-4177-b942-d76f800e597f.json
packages/react/src/components/pickers/PeoplePicker/PeoplePickerItems/PeoplePickerItem.styles.ts
packages/react/src/components/pickers/PeoplePicker/__snapshots__/PeoplePicker.test.tsx.snap
packages/react/src/components/pickers/TagPicker/TagItem.styles.ts
packages/react/src/components/pickers/TagPicker/__snapshots__/TagItem.test.tsx.snap
packages/react/src/components/pickers/TagPicker/__snapshots__/TagPicker.test.tsx.snap

Since focus styling is tied to the `selected` state (from the internal SelectionZone), it wasn't correctly losing the blue bg when focus left the picker:
https://github.com/microsoft/fluentui/assets/3819570/4e561c46-714a-4ad9-ae71-4d4ca64dfac8
I added a `:focus-within` selector for the tag and `:focus` selector for the remove button to ensure the focus color changes are only shown when the tag actually has keyboard focus:
https://github.com/microsoft/fluentui/assets/3819570/8e270af6-eb1a-4268-8ca1-59282bf78df3
For browsers that don't support `:focus-within` in our support matrix, the tag will still have the black outline styles.
- Fixes [ADO bug](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/16818)

fix: picker tags only show focus styling when focused

---

packages/react-components/react-nav-preview/etc/react-nav-preview.api.md
packages/react-components/react-nav-preview/src/components/NavItem/NavItem.test.tsx
packages/react-components/react-nav-preview/src/components/NavItem/NavItem.types.ts
packages/react-components/react-nav-preview/src/components/NavItem/renderNavItem.tsx
packages/react-components/react-nav-preview/src/components/NavItem/useNavItem.ts
packages/react-components/react-nav-preview/src/components/NavItem/useNavItemStyles.styles.ts
packages/react-components/react-nav-preview/stories/NavItem/NavItemDefault.stories.tsx

Adds styling for the medium size of the NavItem.
Adds selectedIcon and unSelectedIcon props.
Ladders up to #26649 
Things to check for:
Do the new icon names make sense and match standards?
Is the thing pixel perfect?
Spec:
Result:
https://github.com/microsoft/fluentui/assets/17346018/21d174bb-ca0b-4d84-a780-57a1127ed0eb

feat(react-nav-preview): Add styles to NavItem and add icon prop

---

packages/react-examples/src/react-charting/SparklineChart/SparklineChart.Basic.Example.tsx

Screen Reader couldn't detect table due to absence of role='grid' attribute
'grid' role added to table in example
https://github.com/microsoft/fluentui/assets/35366351/9dc1f52f-893e-4706-b1d8-a08c459aad16
- Fixes #30852

Add role='grid' to SparklineChart Example Table

---

apps/public-docsite/src/styles/_base.scss
packages/react-examples/src/react-charting/AreaChart/AreaChart.Basic.Example.tsx

Focus styling for AreaChart Basic example was not working (overridden by global styling)
Focus styling fixed by custom styling.
- Fixes #30853

Fix Focus styling for AreaChart Basic Example in docsite

---

change/@fluentui-react-portal-7081febf-e493-416b-86c8-63477148649e.json
packages/react-components/react-portal/src/components/Portal/__snapshots__/Portal.test.tsx.snap
packages/react-components/react-portal/src/components/Portal/usePortalMountNode.test.tsx
packages/react-components/react-portal/src/components/Portal/usePortalMountNode.ts
packages/react-components/react-portal/stories/Portal/PortalDescription.md

Add `data-portal-node` attr to DOM nodes created by `usePortalMountNode()` to avoid confusion as such questions appeared multiple times in offline discussions and in GH issues (#30860), too.

chore: add "data-portal-node" attr in usePortalMountNode()

---

tools/workspace-plugin/generators.json
tools/workspace-plugin/src/generators/split-library-in-two/files/src/index.ts.template
tools/workspace-plugin/src/generators/split-library-in-two/generator.spec.ts
tools/workspace-plugin/src/generators/split-library-in-two/generator.ts
tools/workspace-plugin/src/generators/split-library-in-two/schema.d.ts
tools/workspace-plugin/src/generators/split-library-in-two/schema.json

boilerplate via `nx g @nx/plugin:generator`

feat(workspace-plugin): scaffold `split-library-in-two` generator

---

scripts/tasks/src/type-check.ts

when `generate-api` fails it leaves project in invalid/modified state
`process.exit` will not allow failed promise to flow to `finally` thus we need to cleanup within catch
- Fixes #

fix(scripts-tasks): restore original tsconfig if type-check failed

---

change/@fluentui-react-tag-picker-preview-058f9a6b-51de-431d-8457-d32a44469a38.json
packages/react-components/react-tag-picker-preview/cypress.config.ts
packages/react-components/react-tag-picker-preview/package.json
packages/react-components/react-tag-picker-preview/src/components/TagPicker/TagPicker.cy.tsx
packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerDefault.stories.tsx
packages/react-components/react-tag-picker-preview/tsconfig.cy.json
packages/react-components/react-tag-picker-preview/tsconfig.json
packages/react-components/react-tag-picker-preview/tsconfig.lib.json

1. adds e2e tests to ensure mouse and keyboard navigation behaviours for `TagPicker`
- Fixes #

chore(react-tag): adds e2e tests

---

change/@fluentui-eslint-plugin-86be988e-5fbf-4544-90e8-7712e918b0cb.json
packages/eslint-plugin/src/configs/core.js

after `bundle-size` is added via nx generator eslint will explode on commit
no lint issues after `bundle-size` generator was invoked
- Fixes #

fix(eslint-plugin): ignore bundle-size package directory

---

change/@fluentui-react-drawer-ecbe0ab7-6a66-465a-ac31-daf11345c21c.json
change/@fluentui-react-infobutton-9b9694b6-4898-4726-9013-1cc195c28984.json
change/@fluentui-react-infolabel-bff74b1d-1607-4226-9d1d-c9dd3fd6998c.json
change/@fluentui-react-tree-2717028e-e8b4-4198-aa82-71af3425d855.json
packages/react-components/react-datepicker-compat/src/components/DatePicker/DatePicker.cy.tsx
packages/react-components/react-drawer/tsconfig.lib.json
packages/react-components/react-infobutton/src/components/InfoLabel/InfoLabel.cy.tsx
packages/react-components/react-infobutton/tsconfig.lib.json
packages/react-components/react-infolabel/src/components/InfoLabel/InfoLabel.cy.tsx
packages/react-components/react-infolabel/tsconfig.json
packages/react-components/react-infolabel/tsconfig.lib.json
packages/react-components/react-tree/src/components/FlatTree/FlatTree.cy.tsx
packages/react-components/react-tree/src/components/Tree/Tree.cy.tsx
packages/react-components/react-tree/tsconfig.json
packages/react-components/react-tree/tsconfig.lib.json

- we have invalid setup for Type checking and cypress component tests in various projects ( probably caused by not invoking cy config generator )
- all projects using cypress are properly configured 
- .d.ts generation now avoids running tsc on cypress file trees which adds some speed boost
- Also needed for https://github.com/microsoft/fluentui/pull/30866

perf: exclude cypress test files from tsc Program for `.d.ts` generation and type-checking

---

change/@fluentui-eslint-plugin-ee7a918a-238e-45f3-8a6b-18eb7ca7e02b.json
packages/cra-template/.eslintrc.json
packages/eslint-plugin/src/configs/base.js
packages/react-components/react-tag-picker-preview/src/components/TagPicker/TagPicker.cy.tsx

- see PR title
- adds new lint rule for v9 scope https://github.com/microsoft/fluentui/pull/30989 
-  using manually references is most of the time a code-smell/antipattern so we should disallow this behaviours

feat(eslint-plugin): add triple-slash-reference rule to  ban TS '///' within source code

---

packages/react-components/react-drawer/src/e2e/DrawerShared.tsx
scripts/beachball/base.config.json
scripts/beachball/config.test.ts

See PR title
As we undergo stories/ separation into separate package in order to remove circular dependencies and ability to drastically speed up type checking, we need to remove any circular dep issues within tests/e2e files ( if those would be really needed, we need to separate also test/e2e to separate project ) 
- Follows: 
- https://github.com/microsoft/fluentui/pull/30989
- https://github.com/microsoft/fluentui/pull/30988
- Mitigates issues that will be caught  https://github.com/microsoft/fluentui/pull/30866/files#diff-3b98f51b6fb208cbbe080331a4ba93f2ad00901a59570442eb765220f13f2e6aR520-R527

fix(react-drawer): remove circular dependency from cypress test files

---

change/@fluentui-react-field-b0fef346-1748-4494-95c1-40003abf4b2f.json
packages/react-components/react-field/etc/react-field.api.md
scripts/tasks/src/generate-api.ts
scripts/tasks/src/ts.ts
scripts/tasks/src/utils.ts

- `isUsingPathAliasesForDx` us not used anymore for v9 packages - refactored to make it lazy for few v0/v8 invocations
- TS path aliases are not used anymore for `d.ts` generation in v9 packages - which yields significant perf boost ( **up to 60%  faster** - based on package )
| command | Before | After |
|--------|--------|--------|
| yarn workspace @fluentui/react-drawer generate-api | 16s | 7s /  **𝚫 56% faster** |

perf(scripts-task): turn off path aliases within generate-api task, make isUsingPathAliasesForDx lazy => improve d.ts generation speed by ~60%

---

change/@fluentui-react-tree-0ebd456e-066d-4057-9b9a-d47dfacfcae0.json
packages/react-components/react-tree/src/components/TreeItem/useTreeItem.tsx

It wasn't possible to override the `aria-selected` attribute through the props, even though we encourage doing so in certain cases:
This PR now allows overriding `aria-selected`.

fix(react-tree): Allow overriding aria-selected through props

---

apps/vr-tests-react-components/src/stories/Combobox.stories.tsx
apps/vr-tests-react-components/src/stories/Dropdown.stories.tsx
change/@fluentui-react-combobox-96629c15-7cd4-4887-b3fb-10a120cb445f.json
packages/react-components/react-combobox/src/components/Combobox/useComboboxStyles.styles.ts
packages/react-components/react-combobox/src/components/Dropdown/useDropdownStyles.styles.ts

fix(react-combobox): Inline Listbox should render on top of relatively positioned elements

---

scripts/beachball/utils.ts
scripts/executors/runPublished.js
scripts/executors/runPublished.spec.ts
scripts/executors/tag-react-components.ts
scripts/generators/create-package/index.ts
scripts/monorepo/src/getAllPackageInfo.js
scripts/monorepo/src/getAllPackageInfo.spec.ts
scripts/monorepo/src/index.d.ts
scripts/monorepo/src/isConvergedPackage.js
scripts/monorepo/src/isConvergedPackage.spec.ts
scripts/monorepo/src/types.ts
scripts/monorepo/src/utils.js
scripts/tasks/src/babel.ts
scripts/tasks/src/copy.ts
scripts/tasks/src/metadata-utils.spec.ts
scripts/tasks/src/metadata-utils.ts
scripts/tasks/src/presets.ts
scripts/tasks/src/sass.ts

Using `readProjectConfiguration` api for more than 1 call is extremely expensive. This was happening in various parts of our infra:
- isConvergedPackage function
- shipsAmd
- generateConfig ( beachball ) 
- others ( see file changes )
This PR refactores critical API's in our core infra to simplify logic and make  things significantly faster 🚅🚅🚅
| command | Before | After |
|--------|--------|--------|
| yarn workspace @fluentui/scripts-beachball jest  | 31s | 0.2s  / **𝚫 99% FASTER** |
| node -r ./scripts/ts-node/register scripts/executors/tag-react-components.ts  | 22s | 0.8s  / **𝚫 96% FASTER** |
| lage build --to react-migration-v8-v9  | 241.12s | 220.16s  / **𝚫 9% FASTER** |
**running `lage build` (whole monorepo):** 
> **NOTE:**
>
> - not that not every task calls following APIs 4 …

feat(scripts-*): speed up all `isConverged`, `getAllPackageInfo` calls/usage by ~95%

---

change/@fluentui-react-tag-picker-preview-eedaf17a-87ce-42a2-99a0-73612124120c.json
packages/react-components/react-tag-picker-preview/src/components/TagPicker/useTagPicker.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerButton/useTagPickerButton.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerInput/useTagPickerInput.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerInput/useTagPickerInputStyles.styles.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerList/useTagPickerList.ts
packages/react-components/react-tag-picker-preview/src/contexts/TagPickerContext.ts
packages/react-components/react-tag-picker-preview/src/utils/tokens.ts

Previously the `input` would always occupy the next line
1. Ensures `TagPickerInput` `input` slot is properly positioned, according to design. The input should grow/shrink its size based on the amount of characters.
It should occupy a minimal space of `24px`:
But if the text content is bigger than `24px` then the input should grow to occupy the next line

feat(react-tag-picker): `TagPickerInput` input positioning

---

apps/public-docsite-v9/src/Concepts/Migration/FromV8/Components/GroupedList.stories.mdx

There is no migration guidance for moving from Fluent v8's `GroupedList` to Fluent v9.
Guidance on the various v9 components that can be migrated to from v8's `GroupedList` is provided.

docs: add basic GroupedList migration guide.

---

change/@fluentui-react-avatar-8d124f45-a88f-4f4d-9a06-bb44b2bab292.json
packages/react-components/react-avatar/src/components/Avatar/Avatar.types.ts

Avatar component JSDoc had an incorrect spelling of "needed" (was "neeeded"). 
Avatar component JSDoc has correct spelling of "needed".

docs: Fixing typo in Avatar.types.ts

---

apps/public-docsite-v9/src/Concepts/AdvancedConfiguration.stories.mdx

(screen shots grabbed from the public docs site (live))
There was a broken link
There was also a code example that didn't match the expected
(screen shots grabbed from github preview)
The link is no longer broken
The code example matches the output example of properly ordered media queries.

docs: typo on griffel link and code example using compareMediaQueries

---

change/@fluentui-react-dialog-774134d8-4643-4d4f-9824-3b87fea71437.json
packages/react-components/react-dialog/src/components/DialogBody/useDialogBodyStyles.styles.ts
packages/react-components/react-dialog/src/components/DialogContent/useDialogContentStyles.styles.ts
packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurfaceStyles.styles.ts
packages/react-components/react-dialog/src/contexts/constants.ts

Previously on small screens (height < 360px) the content in the dialog would be difficult to see and scroll, because at that point the scrolling should be on the whole surface.
New behavior fixes this by moving the overflow from body to surface when screen height is smaller than 360px.
- Fixes #31027

fix: Dialog - scroll the surface on short viewports

---

packages/react-components/react-nav-preview/src/components/NavDrawer/useNavDrawerStyles.styles.ts

Default width of the NavDrawer is 320px, spec calls for 260px. Extra pixel comes from the border.
Spec:
Before:
After:
Ladders up to #26649

feat:(react-nav-preview) Sets drawer width to 260px

---

packages/react-components/react-nav-preview/etc/react-nav-preview.api.md
packages/react-components/react-nav-preview/src/components/NavCategoryItem/NavCategoryItem.types.ts
packages/react-components/react-nav-preview/src/components/NavCategoryItem/renderNavCategoryItem.tsx
packages/react-components/react-nav-preview/src/components/NavCategoryItem/useNavCategoryItem.styles.ts
packages/react-components/react-nav-preview/src/components/NavCategoryItem/useNavCategoryItem.tsx
packages/react-components/react-nav-preview/src/components/NavItem/NavItem.test.tsx
packages/react-components/react-nav-preview/src/components/NavItem/NavItem.types.ts
packages/react-components/react-nav-preview/src/components/NavItem/renderNavItem.tsx
packages/react-components/react-nav-preview/src/components/NavItem/useNavItem.ts
packages/react-components/react-nav-preview/src/components/NavItem/useNavItemStyles.styles.ts
packages/react-components/react-nav-preview/src/components/NavSubItem/NavSubItem.types.ts
packages/react-components/react-nav-preview/src/components/NavSubItem/renderNavSubItem.tsx
packages/react-components/react-nav-preview/src/components/NavSubItem/useNavSubItem.ts
packages/react-components/react-nav-preview/src/components/NavSubItem/useNavSubItemStyles.styles.ts
packages/react-components/react-nav-preview/src/components/sharedNavStyles.styles.ts
packages/react-components/react-nav-preview/stories/NavDrawer/NavDrawerDefault.stories.tsx

Took the lessons learned from styling the NavItem and applied them to NavCategoryItem and NavSubItem.
- Added icon prop and logic to NavCategoryItem
- Applied styling from NavItem
- Overrode a few places where it needs to be slightly different.
- Adds more to NavDrawerExample which will be ported over to the main story book shortly.
- Removed 'content' slots to eliminate unnecessary DOM.
Open Question - Since I plan for these styles to be intentionally shared, so I move them to some sort of 'SharedNavStyles" folder to be more clear about intentionality?
Chips away at #26649 
https://github.com/microsoft/fluentui/assets/17346018/118cc5f0-9ac6-41f1-bce2-0cf6aff68ddf

feat(react-nav-preview): Applying styles to NavCategoryItem and NavSubItem

---

packages/react-examples/src/react-charting/AreaChart/AreaChart.CustomAccessibility.Example.tsx
packages/react-examples/src/react-charting/AreaChart/AreaChart.DataChange.Example.tsx
packages/react-examples/src/react-charting/AreaChart/AreaChart.LargeData.Example.tsx
packages/react-examples/src/react-charting/AreaChart/AreaChart.Multiple.Example.tsx
packages/react-examples/src/react-charting/AreaChart/AreaChart.Styled.Example.tsx

Focus styling for AreaChart examples was being overriden.
Focus styling was fixed for AreaChart examples. Refer PR #30907 for more details.
- Fixes #

Fix Focus styling for AreaChart examples in public docsite

---

change/@fluentui-react-combobox-c40b9f22-b188-48c8-80fb-706f1472d62d.json
packages/react-components/react-combobox/src/utils/useListboxSlot.ts

1. updates `useListBoxSlot` signature to accept more use cases of `triggerRef` type to support `TagPicker` types
- Fixes #

chore(react-combobox): fix `useListBoxSlot` signature to accept more `triggerRef` types

---

change/@fluentui-react-tags-899b8dcb-621f-4601-8b1d-d2e432278f59.json
packages/react-components/react-tags/etc/react-tags.api.md
packages/react-components/react-tags/src/components/Tag/useTag.tsx
packages/react-components/react-tags/src/components/TagGroup/TagGroup.types.ts
packages/react-components/react-tags/src/components/TagGroup/useTagGroup.ts
packages/react-components/react-tags/src/components/TagGroup/useTagGroupContextValues.ts
packages/react-components/react-tags/src/contexts/tagGroupContext.tsx

There's a requirement that Tags should have `role="option"` when used in the `TagPicker`
1. adds `role` property to `TagGroupContextValue` and ensures that TagGroup provides its role
2. `Tag` component will opt into the `option` role in the case of a tag group with the role `listbox` is present
- Fixes #

feat(react-tag): adds role to TagGroupContextValue

---

change/@fluentui-react-tag-picker-preview-7b1dad06-5aa8-4d2e-a155-f58b710e3b8e.json
packages/react-components/react-tag-picker-preview/src/components/TagPicker/TagPicker.cy.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerInput/useTagPickerInput.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerList/useTagPickerList.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerOption/useTagPickerOption.ts

1. adds proper role to `TagPickerList` and `TagPickerOption` (listbox and option)
2. ensures `Space` and `Enter` close the tag picker when selecting a tag
- Fixes #

bugfix: Space and Enter should close TagPicker when selecting

---

change/@fluentui-react-charting-61811db0-2341-482a-90db-5d55391aa75e.json
packages/react-charting/src/components/Sparkline/Sparkline.base.tsx
packages/react-charting/src/components/Sparkline/__snapshots__/Sparkline.test.tsx.snap
packages/react-charting/src/components/Sparkline/__snapshots__/SparklineRTL.test.tsx.snap

NVDA Screen reader reads graphic twice upon clicking on sparkline chart
NVDA Screen reader reads graphic once upon clicking on sparkline chart
- Fixes #30854

Fix wrong screen reader output for Sparkline Chart example

---

apps/public-docsite-v9/src/Concepts/Theming.stories.mdx

One example imported code from `@fluentui/theme` instead of `@fluentui/react-components`. This caused some confusion with users.
All examples import from `@fluentui/react-components`.

docs: improve consistency in theming examples

---

scripts/tasks/src/api-extractor.ts
scripts/tasks/src/presets.ts

- `swc:compile` is being run twice  for every `react-components:build` task 
- `api-extractor` task ends up with failure if no config is present
- <img width="505" alt="image" src="https://github.com/microsoft/fluentui/assets/1223799/39ee0faf-2f31-4e36-87e0-3472c2a809c8">
- undo typo introduced https://github.com/microsoft/fluentui/pull/31008/files#diff-6b9fd8010d1649873a9056e36874ef5494545149935c80ed533ca7aed1f27837R154
- api-extractor ends with success if no configs are present
- <img width="498" alt="image" src="https://github.com/microsoft/fluentui/assets/1223799/a6190c01-42f0-42f7-9454-81cd31a5482c">
- Fixes #

fix(scripts-tasks): don't run swc:compile task twice

---

change/@fluentui-react-tag-picker-preview-f9dc682a-010e-41b3-b068-588232aa5abc.json
packages/react-components/react-tag-picker-preview/src/components/TagPicker/TagPicker.cy.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerGroup/useTagPickerGroup.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerInput/useTagPickerInput.tsx

1. adds role `listbox` to `TagPickerGroup`
2. LeftArrow on beginning of the `TagPickerInput` should focus on the last focusable element inside `TagPickerGroup`
3. RigthArrow on the last Tag of the `TagPickerGroup` should focus trigger
4. adds tests to ensure navigation behaviours
- Fixes #

chore(react-tag-picker): ensure navigation between TagPickerGroup and TagPickerInput

---

packages/react-components/react-components/stories/Concepts/FocusManagement/useFocusableGroup/Default.stories.tsx
packages/react-components/react-components/stories/Concepts/FocusManagement/useFocusableGroup/Limited.stories.tsx
packages/react-components/react-components/stories/Concepts/FocusManagement/useFocusableGroup/LimitedTrapFocus.stories.tsx
packages/react-components/react-components/stories/Concepts/FocusManagement/useRestoreFocusSource/Default.stories.stories.tsx
packages/react-components/react-components/stories/Concepts/FocusManagement/useRestoreFocusSource/FocusRestoreHistory.stories.tsx
packages/react-components/react-components/stories/Concepts/FocusManagement/useRestoreFocusSource/UserRestoreFocus.stories.stories.tsx
packages/react-components/react-motions-preview/stories/CreateMotionComponent/CreateMotionComponent.stories.tsx
packages/react-components/react-motions-preview/stories/CreateMotionComponent/CreateMotionComponentDefault.stories.tsx
packages/react-components/react-motions-preview/stories/CreateMotionComponent/ImperativeRefPlayState.stories.tsx
packages/react-components/react-motions-preview/stories/CreateMotionComponent/TokensUsage.stories.tsx
packages/react-components/react-motions-preview/stories/CreatePresenceComponent/CreatePresenceComponent.stories.tsx
packages/react-components/react-motions-preview/stories/CreatePresenceComponent/CreatePresenceComponentDefault.stories.tsx
packages/react-components/react-motions-preview/stories/CreatePresenceComponent/MotionFunctions.stories.tsx
packages/react-components/react-motions-preview/stories/CreatePresenceComponent/PresenceAppear.stories.tsx
packages/react-components/react-motions-preview/stories/CreatePresenceComponent/PresenceOnMotionFinish.stories.tsx
packages/react-components/react-motions-preview/stories/CreatePresenceComponent/PresenceUnmountOnExit.stories.tsx
packages/react-components/react-motions-preview/stories/PresenceGroup/PresenceGroupDefault.stories.tsx

This is just some story cleanup to add missing accessible names and some high contrast styles for animations.
Fixes a few ADO bugs.

fix: minor story accessibility updates to v9 utility examples

---

packages/react-components/react-components/bundle-size/ReactComponents.fixture.js
packages/react/bundle-size/React.fixture.js

We measured bundle size for individual components but not for the entire library.
We now measure the bundle size of the entire library. This will give us better insight into how changes affect bundle size in applications as most users a likely to use many components from the library rather than a single one.
This came out of #30689 as we want to understand the overall bundle size impact of the shadow DOM feature in Fluent v8.

Meaure "all up" bundle size for `@fluentui/react` and `@fluentui/react-components`

---

change/@fluentui-react-skeleton-cbec776a-75c8-4212-8ea9-d9c565cf775e.json
packages/react-components/react-skeleton/src/components/Skeleton/Skeleton.types.ts

This PR deprecates the `width` prop in `Skeleton`. The recommended way to set the width is to use `className`. Fixes #30016

chore: deprecate width prop in Skeleton

---

.github/workflows/check-xplat.yml
apps/xplat-v9/package.json
apps/xplat-v9/stories/Button/ButtonStories.tsx
package.json
packages/react-components/react-platform-adapter-preview/package.json
yarn.lock

> [!NOTE]
> This is being merged into the `xplat` branch, not `master`
Android app crashes when trying to render `<Button shape="square">`
Bump `react-strict-dom` to 0.0.8 to fix Android app crashing when trying to render `<Button shape="square">`
n/a

chore: bump `react-strict-dom` to 0.0.8

---

change/@fluentui-react-provider-3d9b4f67-b650-4c9b-abbe-e3b734dd0f84.json
packages/react-components/react-provider/.babelrc.json
scripts/babel/preset-v9.js
scripts/babel/preset-v9.spec.ts

react-provider uses different babel setup for griffel processing
react-provider uses same babel setup for griffel.
- Fixes #

feat: unify v9 babel preset in all packages

---

.storybook/docs-root.css
packages/react-components/react-link/stories/Link/LinkAccessibility.md
packages/react-components/react-link/stories/Link/LinkAsSpan.stories.tsx
packages/react-components/react-link/stories/Link/index.stories.tsx

Docs-only PR, no package changes.
We provided an underline variant, but not guidance on why it might be needed. This PR makes 3 changes:
1. adds docs wording in an a11y section
2. adds an underline to the inline span story, since it would otherwise fail the WCAG criterion & not meet our guidance 😅
3. adds underline styles to storybook links, since it seems a little too on the nose to have a failing link style in the paragraph about not making failing link styles
has guidance!

feat: add accessibility docs to Link about color/underlines

---

change/@fluentui-react-spinbutton-9b1df688-9bc5-4b68-980b-a25a14e3c0d3.json
packages/react-components/react-spinbutton/src/components/SpinButton/useSpinButton.tsx

It was possible to get `SpinButton` buttons in the wrong visual state.
`SpinButton` buttons now show the correct visual state.
- Fixes #30234

fix: SpinButton buttons now show correct visuals at bounds

---

packages/react-components/react-motions-preview/src/factories/createPresenceComponent.test.tsx

_Moved out from a larger PR_.
- Test for `unmountOnExit` was false positive as `motion` used the same keyframes set for "exit" & "enter"
- `motion` was split to smaller objects to simplify tests & assertions

chore: refactor tests for createPresenceComponent()

---

packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerTruncatedText.stories.tsx
packages/react-components/react-tag-picker-preview/stories/TagPicker/index.stories.tsx

1. adds story showcasing how to properly handle scenarios with huge texts by using `text-overflow` on proper slots
- Fixes #

chore(react-tag-picker): adds text elliptical clipping example

---

tools/workspace-plugin/src/generators/split-library-in-two/README.md
tools/workspace-plugin/src/generators/split-library-in-two/files/src/index.ts.template
tools/workspace-plugin/src/generators/split-library-in-two/generator.spec.ts
tools/workspace-plugin/src/generators/split-library-in-two/generator.ts
tools/workspace-plugin/src/generators/split-library-in-two/schema.d.ts
tools/workspace-plugin/src/generators/split-library-in-two/schema.json

> Based on RFC https://github.com/microsoft/fluentui/pull/30514/files#diff-fd1f65124cb8a5f905a337bf23e6dd67b607808793d84f21178c25c80b3a8028R283
nx generator which will split existing STABLE UI v9 web packages into `library` and `stories` packages under the same folder name.
```
|- react-components/
|- |- react-text/
```
↓↓↓
```
|- react-components/
|- |- react-text/
|- |- |- library/
|- |- |- stories/
```
- generator also parses source AST and adds ghost dependencies as `devDependencies` to `library` project for cypress/jest test files in order to create proper dependency graph ( without this `type-check` would fail )
- CLI options:
- `project` (runs on specified  project)
- `all` (runs on all applicable projects) 

feat(workspace-plugin): implement split-library-in-two migration generator

---

scripts/tasks/src/type-check.ts

TS build mode is significantly more expensive and makes sense only with composite projects ( reference linking across whole monorepo ).
This PR changes implementation to use simple `tsc -p` against all referenced projects within project root TS solution config. As a nice benefit we don't have to override tsconfigs in order to turn off path aliases as that is being handeld by `--baseUrl` CLI override on callsite.
> `@fluentui/react-migration-v8-v9 type-check`
| Command                                                                                 | Time                   | Delta |
| --------------------------------------------------------- | ---------------- | ------|
| `tsc -b`  (current)                                                                                   |  5s          | …

feat(scripts-tasks): implement ~36% faster type-check task

---

change/@fluentui-eslint-plugin-35756908-2280-4ee6-81f0-67c716df8257.json
change/@fluentui-react-breadcrumb-ea432422-f0f1-4d52-bef7-6d476f1066e5.json
change/@fluentui-react-dialog-69502076-906b-4301-88a5-817ccfb2d1a0.json
packages/eslint-plugin/src/utils/configHelpers.js
packages/react-components/react-breadcrumb/package.json
packages/react-components/react-breadcrumb/src/components/Breadcrumb/BreadcrumbWithMenu.cy.tsx
packages/react-components/react-dialog/package.json
packages/react-components/react-dialog/src/components/Dialog/Dialog.cy.tsx
packages/react-components/react-dialog/src/components/DialogTitle/DialogTitle.cy.tsx
packages/react-components/react-tree/stories/Tree/TreeExpandIcon.stories.tsx
packages/react-components/react-virtualizer/stories/Virtualizer/Dynamic.stories.tsx
packages/react-components/react-virtualizer/stories/Virtualizer/index.stories.ts
packages/react-components/react-virtualizer/stories/VirtualizerScrollView/ScrollTo.stories.tsx
packages/react-components/react-virtualizer/stories/VirtualizerScrollView/index.stories.ts
packages/react-components/react-virtualizer/stories/VirtualizerScrollViewDynamic/ScrollTo.stories.tsx
packages/react-components/react-virtualizer/stories/VirtualizerScrollViewDynamic/index.stories.ts

relative imports are invalid/disallowed within `stories/`
- relative imports are replaced with proper absolute package imports
- leaking types from NodeJS are fixed which would fail build after we migrate projects
- cypress tests cannot contain circular dependencies - imports from `react-components` suite ( this will fail build once we migrate to `library`/`stories` projects )
- Relates to https://github.com/microsoft/fluentui/issues/30516
- Follows https://github.com/microsoft/fluentui/pull/31005

fix: remove relative imports within stories which are invalid for creating 'show docs' and circular dep imports from cypress files

---

change/@fluentui-react-toast-65c1ffc6-4887-4c29-bb82-d66c58373dda.json
packages/react-components/react-toast/src/components/ToastContainer/renderToastContainer.tsx
packages/react-components/react-toast/src/components/ToastContainer/useToastContainer.ts

Warnings with canary versions of React.
No warnings.
Fixes #30942.

fix: use "key" properly in ToastContainer

---

change/@fluentui-react-motions-preview-e2edd59f-e00a-4e90-b6a3-f2336231996e.json
packages/react-components/react-motions-preview/src/factories/createPresenceComponent.test.tsx
packages/react-components/react-motions-preview/src/factories/createPresenceComponent.ts
packages/react-components/react-motions-preview/src/hooks/useMountedState.test.tsx
packages/react-components/react-motions-preview/src/hooks/useMountedState.ts

Transition from `{ visible: false, unmountOnExit: false }` to `{ visible: true, unmountOnExit: false }` caused a re-render.
Transition from `{ visible: false, unmountOnExit: false }` to `{ visible: true, unmountOnExit: false }` does not cause a re-render.
- `mounted` state is managed by `useMountedState()` hook (covered with tests)
- `createPresenceComponent()` logic was simplified from two `useLayoutEffect()` hooks to a single one
- Additional tests & assertions added
Fixes #31135

chore: improve state handling in createPresenceComponent()

---

change/@fluentui-react-menu-76ecb79c-a3ed-4071-a8ae-7f3988c67bab.json
packages/react-components/react-menu/src/components/MenuSplitGroup/useMenuSplitGroupStyles.styles.ts

The divider bar inside the MenuSplitGroup has a height of 24px while the other elements have 20px, resulting in a different height for the Menu Item overall.
The divider bar has a height of 20px, and all menu items have the same height.
- Fixes #30958

fix: MenuSplitGroup has more height than MenuItem

---

change/@fluentui-react-motions-preview-d544a8a1-37e7-4f26-8891-8a5dc747582b.json
packages/react-components/react-motions-preview/config/tests.js
packages/react-components/react-motions-preview/src/components/PresenceGroup.test.tsx
packages/react-components/react-motions-preview/src/components/PresenceGroup.tsx
packages/react-components/react-motions-preview/src/components/PresenceGroupItemProvider.tsx
packages/react-components/react-motions-preview/src/contexts/PresenceGroupChildContext.ts
packages/react-components/react-motions-preview/src/factories/createPresenceComponent.test.tsx
packages/react-components/react-motions-preview/src/factories/createPresenceComponent.ts
packages/react-components/react-motions-preview/tsconfig.spec.json

Calls `onExit()` from a parent context to properly unmounted and fix zombie children.
Fixes #31174.

fix(PresenceGroup): cleanup children properly

---

change/@fluentui-web-components-1441c105-086f-424c-a9f3-9fbc8c070e50.json
packages/web-components/src/button/button.styles.ts

Behavior regressed for buttons with long text.
This PR ensures that buttons with long text have the text center aligned when wrapping.
- Fixes #

fix(web-components): ensure buttons with long text maintain center alignment

---

change/@fluentui-react-tabster-8b1e4e19-6b27-4d88-8afc-50de05d57187.json
packages/react-components/react-tabster/etc/react-tabster.api.md
packages/react-components/react-tabster/src/index.ts

Exposing MoverMemorizedElementEvent for the applications to be able to force forget or alter memorized elements.

Exposing MoverMemorizedElementEvent.

---

tools/workspace-plugin/src/generators/react-library/schema.json

xc-uxe will be adding more components in v9, we should support this via our generate-package script to ensure ownership is added correctly.
Resolves:
#31185

Add xc-uxe to code owners

---

change/@fluentui-react-tag-picker-preview-b2bc6960-e8e7-4c20-a833-8f458640442b.json
packages/react-components/react-tag-picker-preview/src/components/TagPicker/TagPicker.cy.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/useTagPickerControl.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/useTagPickerControlStyles.styles.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerGroup/useTagPickerGroup.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerGroup/useTagPickerGroupStyles.styles.ts

1. ensures cursor looks like a text on whole control, even on dead parts of it (everything bellow secondary action and expand icon is not used as input)
2. adds exception on cypress for false positive error about ResizeObserver (https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded , https://github.com/cypress-io/cypress/issues/20341)
- Fixes #

chore(tact-picker): ensures cursor looks like a text on whole control

---

change/@fluentui-react-tag-picker-preview-11ab6472-b215-4f46-8791-45430fdb2857.json
packages/react-components/react-tag-picker-preview/src/components/TagPickerOption/useTagPickerOption.ts

1. removes  `aria-checked` property from `TagPickerOption`
- Fixes #

chore(react-tag-picker): removes aria-checked from TagPickerOption

---

change/@fluentui-web-components-6c28acc1-a99b-4101-a17a-54d88ec1a057.json
packages/web-components/src/index.ts
packages/web-components/src/styles/partials/index.ts
packages/web-components/src/styles/partials/typography.partials.ts

Only individual tokens or the text component were available for applying typography appearances.
This PR creates new css partials which can be interpolated into components or used within stylesheets within Fluent UI and for use by those building their own custom elements using the FAST css directive.
n/a
- Fixes #

feat(web-components): create css partials for typography styles

---

change/@fluentui-react-teaching-popover-b32cb5ff-1e29-4c94-bb2d-a5ad448d78f9.json
packages/react-components/react-teaching-popover/src/components/TeachingPopoverBody/useTeachingPopoverBodyStyles.styles.ts
packages/react-components/react-teaching-popover/src/components/TeachingPopoverSurface/useTeachingPopoverSurfaceStyles.styles.ts

The arrow is off by 1px
The arrow is no longer off by 1px
Previously the `...shorthands.borderWidth('0px'),` was introduced here: https://github.com/microsoft/fluentui/pull/30270
It was done so because the items within the TeachingPopoverSurface did not align:
By changing the `boxSizing` from `'border-box'` to `'content-box'`
- Not sure if this is the right way to do things. Open to suggestions.

fix: TeachingPopover arrow off by a pixel

---

change/@fluentui-react-charting-fa376ca6-a8af-40af-b196-3960a2a15f77.json
packages/react-charting/src/components/SankeyChart/SankeyChart.base.tsx

Sometimes, sankey shows node value text outside the node rectangle. 
For example, let say we have following link from source node 1 to target node 2 with value `0.0945945945945946` (16 fraction digits)
```
{
"source": 1,
"target": 2,
"value": 0.0945945945945946
}
```
The 16+digit value is too long to display. So, if we want to round off to 2 digits, and set the `formatNumberOptions` prop as follows:
```
<SankeyChart
data={data}
accessibility={accessibilityStrings}
formatNumberOptions={{
maximumFractionDigits: 2,
}}
/>
```
For the above configuration, the issue is that sankey diagram renders the node with overlapping name and number values making it unable to read. This is due to current way of calculating the node's attributes such as the text's offset using the raw value length (which is …

Sankey diagram bug fix - Use the formatted node value instead of the raw value, to calculate text measurement.

---

package.json
scripts/storybook/src/utils.js

- adds new monorepo workspace glob ( this will trigger warnings on local machines for build react-components/unstable/package.json and react-jsx-runtime nested package.json files )
- loads stories properly from split projects

chore: register react-components nested folders to workspace and make storybook properly load split project stories 

---

packages/react-components/react-nav-preview/src/components/NavDrawer/useNavDrawerStyles.styles.ts
packages/react-components/react-nav-preview/src/components/sharedNavStyles.styles.ts

Taking advantage of Marco's recent work on Drawer.
Creating a few nav specific color tokens. Applying the background color to the Drawer.
Before:
After:
Ladders up to #26649

feat(react-nav-preview): Set Nav drawer background color

---

change/@fluentui-react-dialog-64487e2f-fbe5-47c6-9c00-05c8c37b74d7.json
packages/react-components/react-dialog/src/components/Dialog/Dialog.cy.tsx
packages/react-components/react-dialog/src/components/Dialog/useDialog.ts
packages/react-components/react-dialog/src/utils/useDisableBodyScroll.ts

See https://github.com/microsoft/fluentui/pull/31180 for more details. This might be a regression that was introduced once animations were applied to the `DialogSurface` component
https://github.com/microsoft/fluentui/assets/5483269/33e2ba69-b322-438a-8a7a-31bcd383790c
1. moves `useDisableBodyScroll` invocation from `Dialog` to `DialogSurface` (with comments on why that is not ideal and that we should move it back to `Dialog` once animations are modified)
* moving to `DialogSurface` now is required to have access to `transitionStatus` to ensure the scroll styles are properly controlled once the animations are concluded
2. modifies `useDisableBodyScroll`
* uses `makeStyles` instead of modifying `element.style` (less code)
* uses `overflow-y: clip` with fallback to `hidden` ([griffel's …

bugfix: open/close animation jumps when body is scrollable

---

change/@fluentui-react-dialog-52adabb2-b975-409b-8bc7-3747eddbd061.json
packages/react-components/react-dialog/src/components/Dialog/Dialog.cy.tsx
packages/react-components/react-dialog/src/components/Dialog/useDialog.ts

On keyboard navigation, when closing the non-modal `Dialog` the focus goes to `body`
The focus should go back to the `DialogTrigger` that opened the non-modal `Dialog`
1. Adds proper tabster modal attributes on `non-modal` dialog
2. adds e2e test to ensure this behaviour
- Fixes https://github.com/microsoft/fluentui/issues/30627

bugfix(react-dialog): ensures non-modal Dialog returns focus to trigger when closed

---

scripts/test-ssr/src/commands/main.ts
scripts/test-ssr/src/esbuild-plugin.js
scripts/test-ssr/src/utils/buildAssets.test.ts
scripts/test-ssr/src/utils/buildAssets.ts
scripts/test-ssr/src/utils/esbuild-plugin.ts

Esbuild stopped resolving TS path aliases since version 0.19 (BREAKING CHANGE)
https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#0190 / 
With this in place our SSR test are working by "accident" ( lage scheduling build task prior to executing test-ssr ),
and following pipeline issues might start happening at any time (https://github.com/microsoft/fluentui/pull/29327).
This issue started to appear in one of PR's that removes a deprecated package from the repo https://github.com/microsoft/fluentui/pull/31007
- this PR implements a custom ESbuild plugin to resolve against path aliases mittigating all the possible issues described above.
- tested against whole repo https://github.com/microsoft/fluentui/pull/31220
Even if we added `build` task as pre-requirement for `test-ssr` pipeline …

feat(test-ssr): add custom esbuild-plugin to properly resolve TS path aliases which stopped working starting esbuild 0.19

---

tools/workspace-plugin/src/generators/split-library-in-two/generator.ts
tools/workspace-plugin/src/generators/tsconfig-base-all/index.ts
tools/workspace-plugin/src/generators/tsconfig-base-all/schema.json
tools/workspace-plugin/src/generators/tsconfig-base-all/schema.ts

- Intermittent issues are still occurring on CI https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=341231&view=logs&j=e51d397b-0a7b-5b89-4b48-0052e021371d&t=88c41216-94ff-5ca8-d686-48ce16c1eefc
nx `formatFiles`  is using prettier v3 api (which is async) but we are on prettier v2 which is sync. 
While unnecessary await shouldn't  cause issues it seems it does.
This PR:
- mitigates `formatFiles` calls within split in two generator to 1
- extends `tsConfigBaseAllGenerator` api with `skipFormatting` config
- Follows https://github.com/microsoft/fluentui/pull/31217

feat(workspace-plugin): catch potential issues with running formatFiles on CI and add skipFormat config for tsConfigBaseAllGenerator

---

change/@fluentui-react-2053c5af-0a37-49f4-8a7f-a7770d2da5cb.json
packages/react-examples/src/react/List/List.Basic.Example.tsx
packages/react/src/components/List/List.tsx
packages/react/src/components/List/utils/ListDebugRenderer.ts

It was possible to get `List` into a state such that part of the visible list was not materialized. That is, there were blank spots in the list where rows should have been rendered.
In the middle of this `List` this isn't a big problem (though it's still a bug!) because users could continue scrolling to get the rows to materialize. This becomes an issue at the end of the list because there is no action the user can take to resolve the issue -- the last row(s) will never render.
`List` will force a state update after scrolling completes, ensuring the missing rows will materialize. It is still possible to have temporarily missing rows while scrolling but they will render. This is consistent with existing `List` behavior where rows some times take a few ticks to materialize.
As part of this …

Fix `List` rendering at end of `List` and add debug renderer.

---

change/@fluentui-react-dbf5be0d-3f74-47d8-b010-40e86d3fee7e.json
change/@fluentui-react-tabster-e823c5ba-242f-49ee-a806-9b7e24b81921.json
packages/react-components/react-tabster/package.json
packages/react/src/components/Layer/Layer.base.tsx
yarn.lock

Making sure V9 dialog doesn't set aria-hidden on a host element that is used as a container for V8 popups, dropdowns and menus. To address https://github.com/microsoft/fluentui/issues/30545.

Tabster 7.1.1 and v8 v9 interop improvement

---

change/@fluentui-react-5ecf88df-8c30-41f1-8a97-c0b86767af49.json
packages/react-examples/src/react/ComboBox/ComboBox.FreeInput.Example.tsx
packages/react/etc/react.api.md
packages/react/src/components/ComboBox/ComboBox.tsx
packages/react/src/components/ComboBox/ComboBox.types.ts

`ComboBox` would always match input with the options in a case insensitive way without the possibility of modifying this behavior.
A new `caseSensitive` prop is introduced to `ComboBox` in this PR, through which all internal comparisons in the logic of `ComboBox` are done in a case sensitive manner. A new example of what this behavior looks like is introduced in this PR as well.
- Fixes #30915.

feat: Add `caseSensitive` prop to `ComboBox`

---

change/@fluentui-react-virtualizer-2b9d6cc8-1a23-4f0c-82c2-2c9814ffc2ab.json
packages/react-components/react-virtualizer/src/components/Virtualizer/useVirtualizer.ts
packages/react-components/react-virtualizer/src/hooks/useDynamicPagination.ts
packages/react-components/react-virtualizer/src/hooks/useIntersectionObserver.ts
packages/react-components/react-virtualizer/src/hooks/useStaticPagination.ts
packages/react-components/react-virtualizer/stories/Virtualizer/Dynamic.stories.tsx

Used native IO and timer functions
Uses equivalent Fluent hooks.
- Fixes #31095 
- Fixes #31096

Virtualizer: Update IO/Timer to use Fluent hooks

---

change/@fluentui-react-tag-picker-preview-8f841c14-fa16-4dad-9127-cf8f050b142f.json
packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/__snapshots__/TagPickerControl.test.tsx.snap
packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/useTagPickerControl.tsx

1. makes `expandIcon` slot `aria-hidden` by default
- Fixes #

chore: make expandIcon aria-hidden by default

---

change/@fluentui-react-tag-picker-preview-f5058ed3-1d6b-48ce-add6-e1c8cd8945a8.json
packages/react-components/react-tag-picker-preview/etc/react-tag-picker-preview.api.md
packages/react-components/react-tag-picker-preview/src/components/TagPicker/TagPicker.types.ts
packages/react-components/react-tag-picker-preview/src/components/TagPicker/useTagPicker.ts
packages/react-components/react-tag-picker-preview/src/index.ts
packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerFiltering.stories.tsx
packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerSingleSelect.stories.tsx
packages/react-components/react-tag-picker-preview/stories/TagPicker/index.stories.tsx

1. adds story for single select case
2. updates `onOptionSelect` types
3. exports `onOptionSelect` and `onOpenChange` types
- Fixes #

feat(react-tag-picker): exports TagPicker event handlers types

---

scripts/storybook/src/utils.js
scripts/storybook/src/utils.spec.js

`getMetadata` will throw if dependency is not an workspace project
- `getMetadata` will throw if dependency is not an workspace project only if explicitly set via new options API.
-  internal logic of `getPackageStoriesGlob` refactored to use Array.reduce for perf and simpler logic
- Unblocks https://github.com/microsoft/fluentui/pull/31007

feat(scripts-storybook): make getMetadata throwable via config to be able to process stories glob for packages no longer present in the repo

---

change/@fluentui-react-aria-7b56d0a2-0299-4c6c-94dc-07533c23d6d6.json
packages/react-components/react-aria/src/AriaLiveAnnouncer/useAriaLiveAnnouncer.ts
packages/react-components/react-aria/src/AriaLiveAnnouncer/useAriaNotifyAnnounce.ts
packages/react-components/react-aria/src/AriaLiveAnnouncer/useDomAnnounce.ts

`ariaNotify` is a new live notification API in ARIA (ref: https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/Accessibility/AriaNotify/explainer.md). The Edge team has implemented this in canary builds of Edge and Chrome, behind a flag. The next step towards getting `ariaNotify` into the spec is to have real-world implementations to test against, which is why we agreed to test this out in Fluent & Fluent AI.
This won't change the behavior for people who haven't turned on the flag (so in practice, all our real-world customers) until `ariaNotify` is shipped as a stable feature. But it should allow us, Edge, and screen reader vendors to test how well this works as an API in practice.

feat: use ariaNotify when available for AriaLiveAnnouncer

---

change/@fluentui-react-switch-ba7b05e3-f407-4157-b014-864a2ceafb0d.json
packages/react-components/react-switch/src/components/Switch/useSwitchStyles.styles.ts

This PR fixes a visual issue with the `Switch` component in HC mode when the icon rendered is a font icon. The `<i>` tag has a black backplate in HC mode that doesn't get overridden by the color of its parent. 
Fixes #31192

Add HC styling for Switch when using font icons

---

change/@fluentui-react-provider-6a1c8b63-2e10-444f-be5c-f9c9ef20ceb4.json
change/@fluentui-react-shared-contexts-cf151f6f-4b49-4b53-9b25-4a75c2bb55f0.json
change/@fluentui-react-tag-picker-preview-857943fc-a0d5-4cb9-af10-a9237752980c.json
packages/react-components/react-provider/etc/react-provider.api.md
packages/react-components/react-shared-contexts/etc/react-shared-contexts.api.md
packages/react-components/react-shared-contexts/src/CustomStyleHooksContext/CustomStyleHooksContext.ts
packages/react-components/react-tag-picker-preview/src/components/TagPicker/TagPicker.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPicker/__snapshots__/TagPicker.test.tsx.snap
packages/react-components/react-tag-picker-preview/src/components/TagPicker/renderTagPicker.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerButton/TagPickerButton.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerButton/useTagPickerButton.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerButton/useTagPickerButtonStyles.styles.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/TagPickerControl.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/__snapshots__/TagPickerControl.test.tsx.snap
packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/useTagPickerControl.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/useTagPickerControlStyles.styles.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerGroup/TagPickerGroup.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerGroup/useTagPickerGroupStyles.styles.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerInput/TagPickerInput.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerInput/useTagPickerInput.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerInput/useTagPickerInputStyles.styles.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerList/TagPickerList.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerOption/TagPickerOption.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerOptionGroup/TagPickerOptionGroup.tsx
packages/react-components/react-tag-picker-preview/src/contexts/TagPickerContext.ts

1. adds TagPicker custom style hooks
2. removes TODO comments
3. fix style problems
4. adds `aria-expanded` back to `expandIcon`
5. adds `aria-owns` to `TagPickerControl` root
- Fixes #

chore(react-tag-picker): bug bash follow up

---

change/@fluentui-react-tag-picker-preview-6f3fa670-6d8d-4dd6-8486-e007c82bf9f1.json
packages/react-components/react-tag-picker-preview/src/components/TagPicker/TagPicker.cy.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPicker/useTagPicker.ts
packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/useTagPickerControl.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerGroup/useTagPickerGroup.ts
packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerDefault.stories.tsx

1. ensures clicks on the surface of the `TagPicker` will toggle the open state
- Fixes #

chore(react-tag-picker): ensure clicking on surface will toggle open state

---

packages/react-components/react-tag-picker-preview/src/components/TagPicker/TagPicker.cy.tsx

chore(react-tag-picker): chore: remove flaky e2e test

---

change/@fluentui-react-switch-144fd00c-f01b-4d08-b082-e733be903d67.json
packages/react-components/react-switch/src/components/Switch/useSwitchStyles.styles.ts

This fixes an issue in HC where the `Switch` indicator disappears when checked and hovered over. Fixes #31244

fix: update hover active styles in Switch

---

packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerA11y.md
packages/react-components/react-tag-picker-preview/stories/TagPicker/TagPickerBestPractices.md
packages/react-components/react-tag-picker-preview/stories/TagPicker/index.stories.tsx

1. adds Best practices
2. adds Accessibility edge cases scenarios
- Fixes #

chore(react-tag-picker): adds best practices and a11y

---

tools/workspace-plugin/src/generators/normalize-package-dependencies/index.spec.ts
tools/workspace-plugin/src/generators/normalize-package-dependencies/index.ts

- pre-release version normalization was tightly coupled to v9
- beachball incorrect bump fix was tightly coupled to v9
- pre-release version normalization is generic
- beachball incorrect bump is generic
**Perf:** not using extremely slow `readProjectConfiguration`  anymore (https://github.com/microsoft/fluentui/pull/31008)
- Needed for  https://github.com/microsoft/fluentui/pull/31288

feat(workspace-plugin): make normalize-package-dependencies generic and faster

---

change/@fluentui-react-dialog-acec3e3b-75d4-4068-824a-24264b219715.json
packages/react-components/react-dialog/src/utils/useDisableBodyScroll.styles.ts
packages/react-components/react-dialog/src/utils/useDisableBodyScroll.ts

All `makeStyles()` and `makeResetStyles()` calls should be declared in `*.styles.ts` files.

fix: move styles declared in useDisableBodyScroll() to a separate file

---

change/@fluentui-react-motions-preview-45124139-6f6d-4192-a24b-02196c3a6c42.json
packages/react-components/react-motions-preview/etc/react-motions-preview.api.md
packages/react-components/react-motions-preview/src/index.ts
packages/react-components/react-motions-preview/src/motions/motionTokens.ts
packages/react-components/react-motions-preview/stories/PresenceGroup/PresenceGroupDefault.stories.tsx

- Motion tokens (duration and easing) are defined in `@fluentui/tokens`, but are not exported there for direct consumption in JavaScript. Only the CSS variable names are exported.
- The motion tokens were copied into `@fluentui/react-motions-preview` to allow JavaScript consumption. This was deemed the least intrusive solution after a discussion of other possible approaches.
- The copied motion tokens deviated from the original in terms of some numerical values, names and structure.
- Easing curve token values in `@fluentui/react-motions-preview` are incorrect (same errors as in #29546)
- Easing curve token names do not match those in `@fluentui/tokens` (`easing___` vs. `curve___`)
- Duration and easing tokens are combined in one flat set, whereas the original has them grouped in …

fix(react-motions-preview): fix easing token values; match original names & structure

---

change/@fluentui-react-combobox-d398e5dd-1262-4606-887c-5bccc8842c7d.json
packages/react-components/react-combobox/src/components/Combobox/useCombobox.tsx

This is a small semantics-only fix; the functionality to disabled expand/collapse is already there.
When the combobox is disabled, the expand/collapse button was not also semantically disabled.
Adds `aria-disabled` to the button based on the `disabled` combobox state.
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/18707)

fix: expand button should be disabled when Combobox is disabled

---

apps/public-docsite-v9/.storybook/manager-head.html
apps/public-docsite-v9/src/Concepts/Migration/FromV0/migrate-custom-accessibility.stories.mdx
apps/public-docsite-v9/src/Concepts/StylingComponents.stories.mdx
docs/react-v9/contributing/rfcs/react-components/accessibility/accessibility.md

Several links on the documentation site, such as the styling handbook, had defunct URLs.
They now point to their respective correct locations in the repo.

fix(docs): Fixing broken links across the repository

---

change/@fluentui-react-combobox-0d7b531b-8a4d-40aa-9081-d164d87f2ba8.json
packages/react-components/react-combobox/src/components/Option/useOption.tsx

Selected Combobox and Dropdown option with "" or 0 value do not show CheckIcon.
Selected Combobox and Dropdown option with "" or 0 value show CheckIcon.
https://github.com/microsoft/fluentui/issues/30924
- Fixes #30924

Check empty string and 0 for combobox

---

change/@fluentui-react-tag-picker-preview-4dc187e5-80b6-49e0-9937-0ab7ada11736.json
packages/react-components/react-tag-picker-preview/src/components/TagPickerControl/useTagPickerControlStyles.styles.ts

While trying to solve the misuse of `paddingInline`, the padding values from right and left were inverted on https://github.com/microsoft/fluentui/pull/31272
1. reverts padding back to it's original value
- Fixes #

bugfix(react-tag-picker): fixes padding error introduced by PR 31272

---

packages/react-components/react-overflow/stories/Overflow/CustomComponent.stories.tsx
packages/react-components/react-overflow/stories/Overflow/index.stories.tsx

Fixes [#27652](https://github.com/microsoft/fluentui/issues/27652)

Docs: update the Overflow docs with information about forwarding ref when custom component is rendered

---

change/@fluentui-react-tag-picker-preview-35e06389-b8ac-46fa-a9a9-c186c3c2941e.json
packages/react-components/react-tag-picker-preview/src/components/TagPicker/TagPicker.cy.tsx
packages/react-components/react-tag-picker-preview/src/components/TagPickerInput/useTagPickerInput.tsx

1. when backspacing on `TagPickerInput`, when the caret is on the beginning of the input, the focus will move to the last tag present in `TagPickerGroup`
2. fixes issue that pressing `Space` on `TagPickerInput` would close the dropdown and delete the input
- Fixes https://github.com/microsoft/fluentui/issues/31165

chore(react-tag-picker): follow up on #31165

---

packages/react-components/react-combobox/src/components/Option/Option.test.tsx

Adds a test for the scenario from #31170.

chore: add test for Option that support empty string

---

change/@fluentui-react-combobox-70b71069-7838-4549-9c50-4ab77328e735.json
packages/react-components/react-combobox/etc/react-combobox.api.md
packages/react-components/react-combobox/src/components/Combobox/Combobox.test.tsx
packages/react-components/react-combobox/src/components/Combobox/Combobox.types.ts
packages/react-components/react-combobox/src/components/Combobox/renderCombobox.tsx

- Updated types to match implementation
- Re-arranged tests and added a new one
Fixes #31101

fix(Combobox): `expandIcon={null}` should not throw

---

scripts/cypress/src/base.config.ts

see PR title
- Fixes https://github.com/microsoft/fluentui/issues/31276

fix(scripts-cypress): mitigate esbuild-loader WARNING spam when running cypress tests

---

apps/vr-tests-web-components/.storybook/main.cjs
apps/vr-tests-web-components/package.json
apps/vr-tests-web-components/tsconfig.json
packages/web-components/.storybook/main.cjs
packages/web-components/package.json
packages/web-components/scripts/clean.js

- fixes `type-checking` issues
- cleans up wc dependencies
- cleans up wc scripts
- Unblocks https://github.com/microsoft/fluentui/pull/31288

chore: wc-3 tweaks to pass type-checking and cleanup task definitions

---

change/@fluentui-priority-overflow-fa429c3d-9437-41f4-b893-33fafeb8b65b.json
packages/react-components/priority-overflow/src/overflowManager.ts
packages/react-components/react-overflow/src/Overflow.cy.tsx

In `Overflow`, when an `OverflowItem` was removed from the container, the overflow was updated only when the queue of visible items was changed by the removal.
As a result, when an overflowing item was removed, the overflow menu was not updated. Similarly, when all overflow items were removed, the overflow menu was not removed.
Whenever `OverflowItem` is removed while the `Overflow` is in `observing` state, force dispatch is triggered to update the overflow menu. This behavior matches the add logic.
- Fixes #29509

fix(Overflow): Update overflow menu when items are removed

---

change/@fluentui-react-charting-e105accc-fa3e-466e-8341-eca4d3a8ff6f.json
packages/react-charting/src/components/Legends/Legends.base.tsx

- Pressing the up or down arrow keys while at the first or last legend button in the legends overflow callout causes the page to scroll and collapses the list.
- Pressing the tab or shift-tab keys in the callout doesn't move focus to next or previous interactive element.
- Navigating with the up or down arrow keys, or using the tab or shift-tab keys in the legends overflow callout, cycles focus through legend buttons.
When the legend overflow button is focused, pressing the enter key opens the callout, and pressing the escape key closes it.

Fix focus order issue in legends overflow callout

---

change/@fluentui-react-charting-4e7f95fa-3196-4b13-84bd-e646c674683c.json
packages/react-charting/src/components/SankeyChart/SankeyChart.base.tsx

Keyboard focus becomes trapped within the SankeyChart, preventing users from navigating out of the chart using the tab or escape keys.
Users can navigate out of the chart using the tab key.

Fix focus trap issue in sankey chart

---

change/@fluentui-react-drawer-1cda71d6-0464-4bf9-8003-329089924620.json
packages/react-components/react-drawer/src/components/OverlayDrawer/OverlayDrawer.cy.tsx
packages/react-components/react-drawer/src/components/OverlayDrawer/useOverlayDrawer.ts

This fix is a regression after changes to the Dialog component that the Drawer uses under the hood. I added a test to prevent that in the future.
The Drawer removes the page scroll when opening but it fails to restore it
Restore the page scroll after closing.
- Fixes #31334

fix(react-drawer): restore page scroll when Drawer closes

---

tools/workspace-plugin/src/generators/prepare-initial-release/index.spec.ts
tools/workspace-plugin/src/generators/prepare-initial-release/index.ts

bundle-size fixture imports are not renamed when going to stable
bundle-size fixtures imports are properly renamed
- Fixes #

fix(workspace-plugin): update import within bundle-size fixtures within prepare-intial-release generator

---

change/@fluentui-react-dialog-f8bedb1e-8ca8-4bd7-86ed-0c7623fd0368.json
packages/react-components/react-dialog/src/components/Dialog/useDialog.ts
packages/react-components/react-dialog/src/components/DialogSurface/useDialogSurface.ts
packages/react-components/react-dialog/src/utils/useDisableBodyScroll.styles.ts
packages/react-components/react-dialog/src/utils/useDisableBodyScroll.ts

1. In chromium browsers the dialog seem to jump on entering animation
2. in firefox and safari the body lock mechanism is not working (there's a condition check if the scroll bar is present, that condition is returning false negatives) https://github.com/microsoft/fluentui/blob/3855dcb9c010e463ab2e0f2524da4f36a02eccbe/packages/react-components/react-dialog/src/utils/useDisableBodyScroll.ts#L20-L23
1. moves scroll body locking mechanism from `useDialog` to `useDialogSurface` to optain access to the animation `transitionStatus` (solves issue 1.)
2. adds `overflow-y: hidden` to body (seems like in `html` element is not enough
3. modifies the condition check if the scroll bar is present https://github.com/microsoft/fluentui/pull/31377/files#diff-8f2d1997fb63aa1fca8391cd2ab72b3f776d4d80b89cf2b3 …

bugfix(react-dialog): fix scroll locking issues introduced by a regression

---

change/@fluentui-react-motions-preview-39389bb9-22be-417f-87ef-3f8fc4e752e1.json
packages/react-components/react-motions-preview/src/factories/createPresenceComponent.ts

`createPresenceComponent()` does not work with React Strict Mode.
`createPresenceComponent()` works with React Strict Mode.
> Note: `useFirstMount()` is the single reliable way on how to implement this check for React Strict Mode. Other implementations (including previous) that are based on effects won't work. Because of that I had to exclude `isFirstMount` from dependencies.
Fixes #31368.

fix(motions): use useFirstMount() in createPresenceComponent()

---

change/@fluentui-react-calendar-compat-f98806df-da6a-4f9b-a2ef-93fada7e15a0.json
packages/react-components/react-calendar-compat/src/components/CalendarDay/useCalendarDayStyles.styles.ts
packages/react-components/react-calendar-compat/src/components/CalendarPicker/useCalendarPickerStyles.styles.ts
packages/react-components/react-calendar-compat/stories/Calendar/CalendarDateBoundaries.stories.tsx

(hovering the header as you can see it's not showing up due to hover style issues)
- Fixes #31375

fix(react-calendar-compat): Make header button in overlaid month picker match the other header button's styles

---

change/@fluentui-react-motions-preview-5c42e067-2c80-4dbe-8f80-7f2ca4764b63.json
packages/react-components/react-motions-preview/src/factories/createMotionComponent.ts
packages/react-components/react-motions-preview/src/factories/createPresenceComponent.ts
packages/react-components/react-motions-preview/src/utils/animate.ts

Components that use `createMotionComponent()` or `createPresenceComponent()` will throw as `.animate()` is not supported by jsdom (https://github.com/jsdom/jsdom/issues/3429).
Components that use `createMotionComponent()` or `createPresenceComponent()` pass tests.

chore(motions): don't throw in .animate() is not defined

---

apps/vr-tests-react-components/src/stories/MessageBar/MessageBar.stories.tsx
change/@fluentui-react-message-bar-15a4f96c-8b0f-468e-a6cb-c2bd24943031.json
packages/react-components/react-message-bar/etc/react-message-bar.api.md
packages/react-components/react-message-bar/src/components/MessageBarActions/MessageBarActions.types.ts
packages/react-components/react-message-bar/src/components/MessageBarActions/useMessageBarActions.ts
packages/react-components/react-message-bar/src/components/MessageBarActions/useMessageBarActionsStyles.styles.ts

Sets `display: none` to the MessageBarActions root slot if there are no children, so that the slot does not take up space
Fixes #30331

fix: MessageBar without actions should not take up space

---

packages/react-components/react-popover/stories/Popover/PopoverAnchorToCustomTarget.stories.tsx

Previously the example relied on React refs as dependencies to a `useEffect()` call but these will never trigger the effect. The example still works but when trying to extrapolate from it and target elements that appear after the first render, the example breaks down because the effect will not be triggered.
This example takes advantage of the fact that [useMergedRefs()](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-utilities/src/hooks/useMergedRefs.ts) supports functions as refs so we can trigger the effect when the refs are set.
Using `setState()` was also considered but this will always trigger a re-render, negatively affecting performance so this pattern, while perhaps useful in some cases, is not a good example for best practices documentation. …

docs: update popover custom target story

---

change/@fluentui-web-components-82d13efa-8e97-478a-b1d9-d6b7c6f32868.json
packages/web-components/docs/api-report.md
packages/web-components/src/index.ts
packages/web-components/src/spinner/index.ts
packages/web-components/src/spinner/spinner.spec.ts
packages/web-components/src/spinner/spinner.stories.ts
packages/web-components/src/spinner/spinner.styles.ts
packages/web-components/src/spinner/spinner.template.ts
packages/web-components/src/spinner/spinner.ts

Spinner optionally could be set as a determinate progress indicator.
There is no construct for a determinate spinner, the behavior has been removed.
- Fixes #

fix(web-components): remove determinate from spinner implementation

---

change/@fluentui-react-charting-bddcfca4-84d0-4944-a0d4-453c827779c6.json
packages/react-charting/src/components/LineChart/eventAnnotation/LabelLink.tsx

Focus enabled to line chart events.
Fix verified on edge and chrome browsers.

BUG 8860200 Focus enabled to line chart events

---

change/@fluentui-react-tree-0aa4730f-3deb-451a-b469-e6a748f310d3.json
packages/react-components/react-tree/etc/react-tree.api.md
packages/react-components/react-tree/src/components/FlatTree/useHeadlessFlatTree.ts
packages/react-components/react-tree/src/index.ts
packages/react-components/react-tree/src/utils/createHeadlessTree.ts

Currently the only ways to get a headless tree item from the headless tree are:
1. by generating all the items with `.items()` method
2. by simulating a navigation and then using `.getNextNavigableItem()` method
 
1. modifies the return signature of `useHeadlessFlatTree` to include  `.getItem` method that allow trying to locate the headless tree item
- Fixes https://github.com/microsoft/fluentui/issues/30985

feat: modifies `useHeadlessFlatTree` return signature to include `getItem` method

---

change/@fluentui-react-nav-preview-36abc784-bfcc-4828-9322-11f7f4c04b7c.json
docs/react-v9/contributing/command-cheat-sheet.md
packages/react-components/react-nav-preview/etc/react-nav-preview.api.md
packages/react-components/react-nav-preview/package.json
packages/react-components/react-nav-preview/src/components/NavCategoryItem/useNavCategoryItem.tsx
packages/react-components/react-nav-preview/src/components/NavItem/NavItem.test.tsx
packages/react-components/react-nav-preview/src/components/NavItem/NavItem.types.ts
packages/react-components/react-nav-preview/src/components/NavItem/useNavItem.ts
packages/react-components/react-nav-preview/src/components/NavSubItem/NavSubItem.test.tsx
packages/react-components/react-nav-preview/src/components/NavSubItem/NavSubItem.types.ts
packages/react-components/react-nav-preview/src/components/NavSubItem/useNavSubItem.ts
packages/react-components/react-nav-preview/src/components/sharedNavStyles.styles.ts
packages/react-components/react-nav-preview/stories/NavDrawer/NavDrawerDefault.stories.tsx
packages/react-components/react-nav-preview/stories/NavSubItem/NavSubItemDefault.stories.tsx

Keyboarding broke on nav. This PR addresses the issue.
Drafted off carouselNavButton for patterns.
Changed the types of the root slot.
This also effects the semantic output of the components. If no href is present, it should be a button, otherwise it should be an anchor.
Before - notice Items with click handlers are no longer keyboard navigable.
https://github.com/microsoft/fluentui/assets/17346018/e946147e-1bed-4469-9a7f-70f38ec4a969
After - notice all items are keyboard navigable.
https://github.com/microsoft/fluentui/assets/17346018/98c44091-123a-440e-9f58-3e604651765b
Ladders to #26649 and addresses #31190 directly.

fix:(react-nav-preview) Addresses keyboarding and typing issue.

---

docs/react-v9/contributing/command-cheat-sheet.md

Adds type check command to cheat sheet.

chore:(docs) - Adds type check to command cheat sheet

---

change/@fluentui-web-components-b3fafaa6-c49f-4778-872d-2bf39a9ecab2.json
packages/web-components/src/button/button.ts

The `keydownHandler` function calls `this.press()`, which does the action but doesn't do it in the same way as described in the spec. Pressing `space` or `enter` on a button should call the `click` function.
The `keydownHandler` calls `this.click()` when the space or enter key is pressed.

(web-components) call click in button keydownHandler

---

change/@fluentui-react-combobox-a54806f1-3231-45ec-b382-a32664cad6a0.json
packages/react-components/react-combobox/etc/react-combobox.api.md
packages/react-components/react-combobox/src/components/Combobox/Combobox.types.ts
packages/react-components/react-combobox/src/components/Dropdown/Dropdown.types.ts
packages/react-components/react-combobox/src/components/Listbox/Listbox.types.ts
packages/react-components/react-combobox/src/components/Option/Option.types.ts
packages/react-components/react-combobox/src/components/OptionGroup/OptionGroup.types.ts
packages/react-components/react-combobox/src/utils/ComboboxBase.types.ts
packages/react-components/react-combobox/src/utils/OptionCollection.types.ts
packages/react-components/react-combobox/src/utils/Selection.types.ts

The documentation comments of some props in `Dropdown` and `Combobox` were not being correctly surfaced to the docsite.
This was happening because some of the comments had `/*` instead of `/**`, which is what indicates the docsite which comments to surface. This PR fixes this issue so that those comments are correctly surfaced now.
- Fixes #31252

docs: Surfacing `Dropdown` and `Combobox` prop comments to docsite

---

change/@fluentui-react-drawer-833b3b3a-a24f-4bc8-8748-7e3584d7727a.json
packages/react-components/react-drawer/etc/react-drawer.api.md
packages/react-components/react-drawer/src/components/OverlayDrawer/OverlayDrawer.types.ts
packages/react-components/react-drawer/src/components/OverlayDrawer/useOverlayDrawer.ts

This PR adds a deprecation notice for a prop that is not currently in use, but it was introduced when the component was first released.
- Fixes [#30451](https://github.com/microsoft/fluentui/issues/30451)

deprecate(react-drawer): deprecate `defaultOpen` prop as it is not being used

---

packages/web-components/src/badge/badge.stories.ts

I noticed there were no defaults args in the Badge documentation. There was also a broken story for `Badge.iconPosition` when setting it to `end` due to a `slot` attribute error (`slot="start"`).
- Added defaults and descriptions to the argType options
- Updated slot attribute on SVG to put it in the correct position (`slot="end"`).  
- Fixes #

fix(web-components): add default Badge values and fix iconPosition story

---

change/@fluentui-react-aria-9f8b5d1f-9449-49c0-b310-7cdc43927f88.json
packages/react-components/react-aria/src/AriaLiveAnnouncer/useDomAnnounce.ts

Adds cleanup for the timeout set up for `announce()`, for if the announcer is unmounted while there's an existing timeout.
Ref: https://github.com/microsoft/fluentui/pull/31251#discussion_r1586814428

fix: add cleanup for timeout in announce

---

apps/vr-tests-web-components/package.json
change/@fluentui-web-components-ea366fa4-e157-41e3-89e7-8e1153f496a6.json
packages/web-components/.storybook/main.cjs
packages/web-components/.storybook/preview.mjs
packages/web-components/.storybook/tsconfig.json
packages/web-components/package.json
packages/web-components/scripts/type-check.js
packages/web-components/src/text/text.stories.ts

- no `type-check` in place
- wrong dependency tree within vr-test for wc
- new `type-checking` command
-  fixed all type errors 
- proper dependency tree within vr-tests
- Fixes partially https://github.com/microsoft/fluentui/issues/31349

chore(web-components): implement proper type-checking command

---

apps/vr-tests-web-components/package.json
apps/vr-tests-web-components/tsconfig.json

Master pipeline fails because type issues with `vr-tests-web-components`
Because web-components use https://www.npmjs.com/package/@types/web package in order to override DOM lib types every app and library within monorepo that uses wc as dependency needs to specify `web` within tsconfig types global
- Follows https://github.com/microsoft/fluentui/pull/31423

fix(vr-tests-web-component): explicitly add @types/web and specify those within types globals in order to pass tsc

---

change/@fluentui-eslint-plugin-e10d836e-a2c8-4990-8abc-afdece98a1d8.json
package.json
packages/eslint-plugin/package.json
yarn.lock

Bumps `@griffel/eslint-plugin` to get https://github.com/microsoft/griffel/pull/562 so CSS shorthands could be actually used.

chore: bump @griffel/eslint-plugin

---

.storybook/main.js
.storybook/types.d.ts
apps/vr-tests-react-components/.storybook/main.js
apps/vr-tests-web-components/.storybook/main.cjs
apps/vr-tests/.storybook/main.js
packages/fluentui/docs/.storybook/main.js
packages/web-components/.storybook/main.cjs

see PR title
- Fixes partially https://github.com/microsoft/fluentui/issues/31349

feat: extract root storybook shared types so they can be used by  web-component domain

---

change/@fluentui-react-tabster-37512240-5808-4174-96b6-a8c571eead67.json
packages/react-components/react-tabster/package.json
yarn.lock

- CHANGELOG https://github.com/microsoft/tabster/blob/master/CHANGELOG.md#v713
- including fix for https://github.com/microsoft/tabster/issues/374.

fix(react-tabster): bump tabster  to 7.1.4 to fix useArrowNavigationGroup with non-modal Dialog

---

tools/workspace-plugin/src/generators/bundle-size-configuration/generator.ts
tools/workspace-plugin/src/generators/cypress-component-configuration/index.spec.ts
tools/workspace-plugin/src/generators/cypress-component-configuration/index.ts
tools/workspace-plugin/src/generators/cypress-component-configuration/lib/add-files.ts
tools/workspace-plugin/src/generators/prepare-initial-release/index.spec.ts
tools/workspace-plugin/src/generators/prepare-initial-release/index.ts
tools/workspace-plugin/src/generators/react-component/index.spec.ts
tools/workspace-plugin/src/generators/react-component/index.ts
tools/workspace-plugin/src/generators/react-library/index.spec.ts
tools/workspace-plugin/src/generators/react-library/index.ts
tools/workspace-plugin/src/generators/split-library-in-two/generator.spec.ts
tools/workspace-plugin/src/generators/split-library-in-two/generator.ts
tools/workspace-plugin/src/generators/split-library-in-two/schema.d.ts
tools/workspace-plugin/src/generators/split-library-in-two/schema.json
tools/workspace-plugin/src/generators/split-library-in-two/shared.ts

makes following generators work in both v9 package configuration ( old/current and new split library `root-folder/library root-folder/stories`:
- react-library
- react-component
- cypress-component-configuration
- bundle-size-configuration
- prepare-initial-release
**NOTE:** once we migrate all packages those conditional (old) behaviours implemented will be removed from all changed generators in this PR ( except  `split-library-in-two` generator )
**Additional features:**
- `react-library`
- once this is merged any new react library will start from scratch in split projects mode 
- `cypress-component-configuration`
- properly add devDependencies when invoking 
- `split-library-in-two`
- make cli log output configurable for better composability
- enable execution on preview and compat …

feat(workspace-plugin): make all react library generators work with both split project and old project setup

---

change/@fluentui-web-components-c8b47bb9-83cd-4bcc-92f6-c3fe1851402b.json
packages/web-components/scripts/type-check.js

type check emits declarations
type check wont emit anything
- Follows https://github.com/microsoft/fluentui/pull/31423

fix(web-components): add `--noEmit` for type-checking task

---

apps/perf-test-react-components/package.json
apps/perf-test-react-components/tsconfig.app.json
apps/perf-test-react-components/tsconfig.json
apps/perf-test/package.json
apps/perf-test/tsconfig.app.json
apps/perf-test/tsconfig.json
apps/public-docsite-v9/.storybook/preview.js
apps/public-docsite-v9/.storybook/tsconfig.json
apps/public-docsite-v9/tsconfig.json
apps/react-18-tests-v8/package.json
apps/react-18-tests-v8/tsconfig.react-compat-check.json
apps/react-18-tests-v9/package.json
apps/react-18-tests-v9/tsconfig.react-compat-check.json
apps/recipes-react-components/package.json
apps/ssr-tests-v9/package.json
apps/ssr-tests/package.json
apps/ssr-tests/test/test.js
apps/ssr-tests/tsconfig.json
apps/vr-tests-react-components/package.json
apps/vr-tests/package.json
packages/fluentui/perf/package.json
scripts/tasks/src/utils.ts

- applies new performant `type-check` command to all apps applicable
- normalizes some apps tsconfig setup with ts solution config pattern
- adds TS setup and type checking for ssr-test v8 app
_Applications type-checking perf improvements:_
| app | Before | After / Delta |
|--------|--------|--------|
| vr-tests | 9.37s | 2.82s / 𝚫70% 🚅|
| vr-tests-react-components | 14s | 5s / 𝚫64% 🚅|
| ssr-tests-v9 | 27.8s | 3.41s / 𝚫88% 🚅|
| recipes-react-components | 12.44s | 2.17s / 𝚫83% 🚅| 
| perf-test-react-components |  12s  | 1.33s  / 𝚫89% 🚅 |
| perf-test |  7s  | 1.74s  /  𝚫75%  🚅 |
| perf | 10.26s |  1.73s / 𝚫83% 🚅 |
- Implements partially https://github.com/microsoft/fluentui/issues/30516

feat: improve type-checking perf within  all apps

---

change/@fluentui-react-components-29682e95-1e8c-4688-9fee-0eada89b9b32.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts

re-export `DialogProvider` into `@fluentui/react-components`

chore(react-dialog): re-export DialogProvider

---

apps/recipes-react-components/tsconfig.app.json
scripts/tasks/src/type-check.ts

master is failing on type-check error
- `type-check` uses noEmit and returns only `Promise<void>` on success in order to follow just-scripts patterns
- removes `exclude` from tsconfig within recipes app which is probably main issue with failures
- Follows https://github.com/microsoft/fluentui/pull/31451

fix: make type-check task run with --noEmit and return only void Promise on success and update recipes app tsconfig

---

apps/recipes-react-components/tsconfig.app.json
apps/recipes-react-components/tsconfig.json

- see PR title
- it turns out the culprit is that recipes app didn't set `types` config property. if that's not present typescript loads all `@type/*` globals which is a antipattern and started to be problematic since `@types/web` landed to master with web-components v3 ( which is hoisted thus getting those `node_modules` issues on CI )
- Fixes https://github.com/microsoft/fluentui/pull/31456

fix(recipes-react-components): explicitly set types to not include whole @types/* globals which are cauising issues with addition of @types/web

---

apps/pr-deploy-site/package.json
apps/pr-deploy-site/tsconfig.json

one more explicit `types` set, see follows PR at the bottom
- Follows https://github.com/microsoft/fluentui/pull/31463

fix(pr-deploy-site): explicitly set types to not include whole @types/* globals which are causing issues with addition of @types/web

---

change/@fluentui-react-aria-95b07b56-fae4-4b3b-bb62-beab45149e11.json
packages/react-components/react-aria/src/activedescendant/scrollIntoView.test.ts
packages/react-components/react-aria/src/activedescendant/scrollIntoView.ts
packages/react-components/react-aria/src/activedescendant/useActiveDescendant.ts

A follow up to #30967 (forgot to commit some PR feedback changes).

chore: revert globals changes

---

change/@fluentui-react-tag-picker-014eed16-1877-4eba-9bff-52e4ccf27a00.json
packages/react-components/react-tag-picker/etc/react-tag-picker.api.md
packages/react-components/react-tag-picker/src/components/TagPickerOption/TagPickerOption.test.tsx
packages/react-components/react-tag-picker/src/components/TagPickerOption/TagPickerOption.types.ts
packages/react-components/react-tag-picker/src/components/TagPickerOption/useTagPickerOption.ts
packages/react-components/react-tag-picker/stories/TagPicker/TagPickerTruncatedText.stories.tsx

1. adds `text` property to `TagPickerOption`, equivalent to the one provided by `Option` at `@fluentui/react-combobox`
- Fixes https://github.com/microsoft/fluentui/issues/31431
- Fixes https://github.com/microsoft/fluentui/issues/31472

feat(react-tag-picker): adds text property to TagPickerOption

---

apps/react-18-tests-v9/src/Overflow.cy.tsx
change/@fluentui-eslint-plugin-7c1dd810-32a7-4f87-9ef7-3d90d20d5931.json
packages/eslint-plugin/src/configs/core.js
packages/react-components/recipes/src/templates/Example.styles.ts

Follow up for #31258 where `deprecation/deprecation` have been disabled for files that contained `shorthands.*()`.
Fixes #31318.

chore: re-enable lint rule

---

change/@fluentui-global-context-a00353a4-86ec-492f-9bda-7077a3dd1d07.json
change/@fluentui-keyboard-keys-4fc0ac6d-d752-42d1-8ad6-1845191117a8.json
change/@fluentui-priority-overflow-33169e0a-6336-4cc5-831f-e78c8b5f8a3a.json
change/@fluentui-react-context-selector-b4cbfb53-b0af-406b-92ef-357d24df232f.json
change/@fluentui-react-portal-compat-3e004cca-553c-4ac4-9bb3-af9544b0a8da.json
change/@fluentui-react-portal-compat-context-fc21d89f-8098-48d6-85f3-59721c5119a0.json
change/@fluentui-react-positioning-91dfeeca-babc-427d-8b60-30fcfb81d6e6.json
change/@fluentui-react-tabster-af8b813a-dc11-414c-83f9-9effdb3a0efa.json
change/@fluentui-react-theme-sass-bc0cc0f5-3b9f-42c6-be8f-c611ef0c21c2.json
change/@fluentui-react-utilities-9ac672b4-ff46-4345-970c-849ea54198e6.json
change/@fluentui-tokens-cb3f2d7c-453a-480d-810a-baf89c1246f3.json
packages/react-components/global-context/package.json
packages/react-components/keyboard-keys/package.json
packages/react-components/priority-overflow/package.json
packages/react-components/react-colorpicker-compat/package.json
packages/react-components/react-context-selector/package.json
packages/react-components/react-portal-compat-context/package.json
packages/react-components/react-portal-compat/package.json
packages/react-components/react-positioning/package.json
packages/react-components/react-tabster/package.json
packages/react-components/react-theme-sass/package.json
packages/react-components/react-utilities/package.json
packages/react-components/theme-designer/package.json
packages/tokens/package.json
tsconfig.base.all.json

- changes done via modified `split-in-two` generator (including dev Dependency additions to packages based on source AST )

chore: use new performant 'type-check' for v9 libaries

---

change/@fluentui-react-motions-preview-8fed56ea-bf79-45b6-966d-c8e1b83efc50.json
packages/react-components/react-motions-preview/etc/react-motions-preview.api.md
packages/react-components/react-motions-preview/src/factories/createPresenceComponent.test.tsx
packages/react-components/react-motions-preview/src/factories/createPresenceComponent.ts

This PR updates `onMotionFinish` callback to pass `null` as a first param instead of `AnimationPlaybackEvent`. The motivation is to support more complex scenarios (like grouping #31487) when there is no a single event.
```tsx
const Fade = createPresenceComponent({ /* --- */ });
<Fade
onMotionFinish={(ev: AnimationPlaybackEvent, data) => {
}}
/>
```
```tsx
const Fade = createPresenceComponent({ /* --- */ });
<Fade
onMotionFinish={(ev: null, data) => {
/* ev is "null" now */  
}}
/>
```

breaking(react-motions): remove event argument from "onMotionFinish" prop

---

apps/stress-test/README.md

App was previously removed but I kept a README to link elsewhere.
After chatting with @Hotell I learned this is an invalid entry in our monorepo and since we no longer keep it here we should just get rid of it.

chore: entirely remove stress-test app

---

change/@fluentui-react-motions-preview-dffb90ce-ff7d-44d5-8d92-31d75815ea2d.json
packages/react-components/react-motions-preview/src/factories/createMotionComponent.test.tsx
packages/react-components/react-motions-preview/src/factories/createMotionComponent.ts
packages/react-components/react-motions-preview/stories/CreateMotionComponent/CreateMotionComponent.stories.tsx
packages/react-components/react-motions-preview/stories/CreateMotionComponent/CreateMotionComponentDefault.stories.tsx
packages/react-components/react-motions-preview/stories/CreateMotionComponent/ImperativeRefPlayState.stories.tsx
packages/react-components/react-motions-preview/stories/CreateMotionComponent/TokensUsage.stories.tsx

This PR removes `iterations` prop from a component created by `createMotionComponent()`. Before `iterations` could be passed both to a `AtomMotion` and a component's props that created confusion.
```tsx
import { createMotionComponent, motionTokens } from '@fluentui/react-motions-preview';
const FadeEnter = createMotionComponent({
keyframes: [{ opacity: 0 }, { opacity: 1 }],
duration: motionTokens.durationSlow,
});
return <FadeEnter iterations={Infinity} />
}
```
```tsx
import { createMotionComponent, motionTokens } from '@fluentui/react-motions-preview';
const FadeEnter = createMotionComponent({
keyframes: [{ opacity: 0 }, { opacity: 1 }],
duration: motionTokens.durationSlow,
iterations: Infinity,
});
return <FadeEnter />
}
```

breaking(react-motions): remove `iterations` prop from createMotionComponent()

---

change/@fluentui-react-components-27f92d7e-90df-4cb6-9e56-d4d1a72d1edd.json
packages/react-components/react-components/package.json

see PR title
`@fluentui/react-components type-check` comparison speed:
| before | after |
|--------|--------|
| 57.92s | 9.59s / **𝚫 83% 🚅** | 

chore(react-components): use performant type-check target

---

.codesandbox/ci.json
.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devops/templates/tools.yml
.github/workflows/check-packages.yml
.github/workflows/docsite-publish-chromatic.yml
.github/workflows/docsite-publish-ghpages.yml
package.json

- Migrates repo to Node LTS which is v20.
- release announcement https://nodejs.org/en/blog/announcements/v20-release-announce
> [!IMPORTANT]
> - once this PR is merged you won't be able to install packages etc if you use older node that v20.
> - you can temporarily mitigate this by running `yarn install --ignore-engines`, but you should migrate to node v20
- Fixes #

ci: migrate to node 20

---

packages/react-components/react-skeleton/stories/Skeleton/index.stories.tsx

`SkeletonItem` was not documented in the props table.
`SkeletonItem` is documented in the props table.

docs: add SkeletonItem to docs prop table

---

change/@fluentui-web-components-4d0a93e1-80de-43da-be84-d6231d7f5699.json
packages/web-components/package.json
packages/web-components/src/index-rollup.ts

The `index-rollup` bundle generated didn't include the component definitions.
The generated `dist/web-components.js` and `dist/web-components.min.js` now focus on defining the components in the browser.

(web-components) Export component definitions from rollup bundle
