packages/react-components/react-toast/src/components/Toast/Toast.cy.tsx

Test had invalid selector and passed only because a toast will close.
Test has valid selector.
- Fixes #

chore: fix Toast cypress test

---

docs/react-v9/contributing/command-cheat-sheet.md
docs/react-v9/contributing/common-dev-snags.md
docs/react-v9/contributing/dev-env.md
docs/react-v9/contributing/dev-workflow.md

There is a large contingent of contributors at MSFT using vanilla windows, rather than a unix based system.
Sometimes running a `yarn build` is the right thing for them to do. 
Many developers are accustomed to yarn building regularly.
This adds it back to the docs.

chore:docs Adding back references to yarn build

---

packages/react-components/react-nav-preview/stories/NavDrawer/NavDrawerDefault.stories.tsx

Size==small is the default prop on drawer, and also the one we want for the nav.
This pr removes the unneeded assignment from the example.
Visuals are unchanged.

chore:react-nav-preview Removing unnecessary size prop

---

lint-staged.config.js
scripts/lint-staged/package.json
scripts/lint-staged/src/eslint-for-package.js
scripts/lint-staged/src/eslint.js

depends on:
`lint-staged` is broken for `/scripts` packages as it incorectly resolves file groupping to root package
- `lint-staged` works across all scenarios 
- perf is improved as well as we no longer need to fetch all projects Map from nx Daemon on every commit
- Fixes #

fix(scripts-lint-staged): correctly resolve package groupping based on provided git staged files

---

change/@fluentui-react-motions-preview-e1a364d2-4a00-430c-b330-736eaf432fd7.json
change/@fluentui-react-toast-2054e639-6e4f-4fcc-a62c-e0b0da7d9e4d.json
packages/react-components/react-motions-preview/etc/react-motions-preview.api.md
packages/react-components/react-motions-preview/src/factories/createMotionComponent.ts
packages/react-components/react-motions-preview/src/index.ts
packages/react-components/react-toast/package.json
packages/react-components/react-toast/src/components/ToastContainer/ToastContainer.test.tsx
packages/react-components/react-toast/src/components/ToastContainer/ToastContainer.types.ts
packages/react-components/react-toast/src/components/ToastContainer/ToastContainerMotion.tsx
packages/react-components/react-toast/src/components/ToastContainer/__snapshots__/ToastContainer.test.tsx.snap
packages/react-components/react-toast/src/components/ToastContainer/renderToastContainer.tsx
packages/react-components/react-toast/src/components/ToastContainer/useToastContainer.ts
packages/react-components/react-toast/src/components/ToastContainer/useToastContainerStyles.styles.ts

`@fluentui/react-toast` uses `react-transition-group`.
`@fluentui/react-toast` uses `@fluentui/react-motions-preview` 💪 
Fixes #30697.

chore: migrate Toast to new motion library

---

change/@fluentui-react-motions-preview-f7e0f94c-24bd-4fa0-bae2-886019aac40f.json
change/@fluentui-react-toast-f2e79a5a-f5e1-4b7d-b12f-470610a0840b.json
packages/react-components/react-motions-preview/etc/react-motions-preview.api.md
packages/react-components/react-motions-preview/src/factories/createMotionComponent.test.tsx
packages/react-components/react-motions-preview/src/factories/createMotionComponent.ts
packages/react-components/react-motions-preview/src/factories/createPresenceComponent.test.tsx
packages/react-components/react-motions-preview/src/factories/createPresenceComponent.ts
packages/react-components/react-motions-preview/src/types.ts
packages/react-components/react-motions-preview/stories/CreateMotionComponent/MotionFunctions.stories.md
packages/react-components/react-motions-preview/stories/CreateMotionComponent/MotionFunctions.stories.tsx
packages/react-components/react-motions-preview/stories/CreatePresenceComponent/PresenceMotionFunctions.stories.md
packages/react-components/react-motions-preview/stories/CreatePresenceComponent/PresenceMotionFunctions.stories.tsx
packages/react-components/react-toast/src/components/ToastContainer/ToastContainerMotion.tsx

This PR changes `AtomMotionFn` & `PresenceMotionFn`:
```diff
-type AtomMotionFn = (element: HTMLElement) => AtomMotion;
-type PresenceMotionFn = (element: HTMLElement) => PresenceMotion;
+type AtomMotionFn = (params: { element: HTMLElement }) => AtomMotion;
+type PresenceMotionFn = (params: { element: HTMLElement }) => PresenceMotion;
```
The motivation is to have an opportunity to extend it with additional params while `element` may not be used i.e.:
```ts
const Motion = createMotionComponent(({ someNonImplementedParam }) => {
/* --- */
});
```
```ts
const Motion = createMotionComponent(element => {
/* --- */
});
const PresenceMotion = createPresenceComponent(element => {
/* --- */
});
```
```ts
const Motion = createMotionComponent(({ element }) => {
/* --- */
});
const PresenceMotion = …
```

breaking(react-motions): AtomMotionFn & PresenceMotionFn have an object as param

---

packages/react-components/react-carousel-preview/etc/react-carousel-preview.api.md
packages/react-components/react-carousel-preview/src/components/Carousel/Carousel.tsx
packages/react-components/react-carousel-preview/src/components/Carousel/Carousel.types.ts
packages/react-components/react-carousel-preview/src/components/Carousel/useCarousel.ts
packages/react-components/react-carousel-preview/src/components/Carousel/useCarouselContextValues.ts
packages/react-components/react-carousel-preview/src/components/Carousel/useCarouselStyles.styles.ts
packages/react-components/react-carousel-preview/src/components/CarouselButton/useCarouselButton.tsx
packages/react-components/react-carousel-preview/src/components/CarouselCard/CarouselCard.types.ts
packages/react-components/react-carousel-preview/src/components/CarouselCard/__snapshots__/CarouselCard.test.tsx.snap
packages/react-components/react-carousel-preview/src/components/CarouselCard/useCarouselCard.ts
packages/react-components/react-carousel-preview/src/components/CarouselCard/useCarouselCardStyles.styles.ts
packages/react-components/react-carousel-preview/src/components/CarouselContext.ts
packages/react-components/react-carousel-preview/src/components/CarouselContext.types.ts
packages/react-components/react-carousel-preview/src/components/CarouselNav/useCarouselNav.ts
packages/react-components/react-carousel-preview/src/components/CarouselNavButton/useCarouselNavButton.ts
packages/react-components/react-carousel-preview/src/components/CarouselNavImageButton/useCarouselNavImageButton.ts
packages/react-components/react-carousel-preview/src/components/createCarouselStore.test.ts
packages/react-components/react-carousel-preview/src/components/createCarouselStore.ts
packages/react-components/react-carousel-preview/src/components/useCarouselStore.ts
packages/react-components/react-carousel-preview/src/components/useCarouselValues.ts
packages/react-components/react-carousel-preview/stories/Carousel/CarouselDefault.stories.tsx

`Carousel` supports `peeking` prop that allows to have "previous" & "next" cards in a view:
Also moves `value` (i.e. `activeValue`) to a state store, so we can build selectors based both on `value` & `values`.

feat(Carousel): implement peeking

---

docs/react-v9/contributing/accessibility-troubleshooting.md

Migrating the [accessibility trouble shooting guide](https://github.com/microsoft/fluentui/wiki/Accessibility-Troubleshooting). No changes made.

chore:(docs) Migrating Accessibility Troubleshooting

---

change/@fluentui-react-accordion-f9c02eb6-6762-46e7-8b0b-70e84ec5c265.json
change/@fluentui-react-calendar-compat-b69a9f42-7bdf-4389-bae1-53017bc02397.json
change/@fluentui-react-list-preview-dc4d6a47-7870-4690-a5e8-81b1a25c2f92.json
change/@fluentui-react-search-45a3f7ae-3db8-4b8d-856f-efbbb0766910.json
change/@fluentui-react-slider-ebfac3f4-e325-47b7-850c-b3dbd9dfc127.json
change/@fluentui-react-tree-d5c80dfa-0994-4082-9500-e9acdc7023f6.json
change/@fluentui-react-utilities-7d570c9e-82bf-48fd-84c2-7e660f079e19.json
packages/react-components/react-accordion/src/components/Accordion/useAccordion.ts
packages/react-components/react-calendar-compat/src/components/Calendar/Calendar.tsx
packages/react-components/react-list-preview/src/components/List/useList.ts
packages/react-components/react-search/src/components/SearchBox/useSearchBox.tsx
packages/react-components/react-slider/src/components/Slider/useSliderState.tsx
packages/react-components/react-tree/src/hooks/useControllableOpenItems.ts
packages/react-components/react-utilities/src/hooks/useControllableState.test.ts
packages/react-components/react-utilities/src/hooks/useControllableState.ts

Using both controlled and uncontrolled state on `useControllableState` hook would default to the state value, which is expected.
In native react elements (such as `input`) if the user provides both controlled `value` and uncontrolled `defaultValue` an error will be displayed in the console:
The element works as expected, the controlled value takes precedence, but the warning is emitted as extra information to avoid confusion from the user side (as something might be going wrong if the user is providing both)
1. consoles a warning whenever the user provide both controlled and uncontrolled state value, similar to what react does on native elements.
2. refactors `react-utilities` tests to count for the console.error
3. updates v9 packages to properly use the hook
* `react-accordion`
* …

chore(react-utilities): useControllableState warns if controlled and uncontrolled at the same time

---

change/@fluentui-react-migration-v8-v9-4e7ddd14-c033-416b-a5e7-f2a57c3ccada.json
packages/react-components/react-migration-v8-v9/src/components/Checkbox/CheckboxShim.tsx

This PR fixes a typo in the `CheckboxShim` migration example from `defualt` to `default`.

chore: Fixing typo in `CheckboxShim` migration

---

packages/react-components/react-list-preview/stories/List/ListDescription.md

Doc update, "selects" is not the right verb as that implies selection toggle. The correct verb is "move focus".

docs(react-list-preview): update the up/down arrow key behavior docs

---

change/@fluentui-react-tree-82531355-9d67-474e-b007-7fb1e6a64060.json
packages/react-components/react-tree/etc/react-tree.api.md
packages/react-components/react-tree/src/components/Tree/Tree.cy.tsx
packages/react-components/react-tree/src/components/Tree/Tree.types.ts
packages/react-components/react-tree/src/components/Tree/useTree.ts
packages/react-components/react-tree/src/hooks/useRootTree.ts
packages/react-components/react-tree/src/hooks/useRovingTabIndexes.ts
packages/react-components/react-tree/src/hooks/useTreeNavigation.ts

In the nested tree when navigating, we focus on the `TreeItem` itself and since that item includes all its children nested inside of it the browser will automatically scroll that whole item into view (see https://github.com/microsoft/fluentui/issues/31557).
1. adds `preventScroll` and `isScrollPrevented` methods to `onNavigation` data parameter. When `preventScroll` is invoked then the navigation focus will not scroll to the element while focusing (see [preventScroll](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#preventscroll))
With this feature now it's possible to maintain navigation as is while opting out of the scroll mechanism, allowing the user to create its own (in the case of https://github.com/microsoft/fluentui/issues/31557 we could just scroll into the …

feature(react-tree): preventScroll on navigation

---

change/@fluentui-web-components-3a27963c-2795-4898-8b1e-adeb72be5c72.json
packages/web-components/src/button/button.spec.ts
packages/web-components/src/button/button.styles.ts
packages/web-components/src/theme/set-theme.ts

- Bug filed for `[disabled][appearance="subtle"]` fluent-buttons where they are expected to not have a background or outline when disabled, but actually were showing a background and outline.
- Confirmed that a "fix" in https://github.com/microsoft/fluentui/commit/fa9416a9f3fefc36b2e2ee3b32ea8c038bb4d91e caused a regression where "fixed" styles were now overriding existing behavior due to cascade order.
- This exposed a false positive in our Playwright tests where CSS variables were being wiped out by the use of `setContent`.
- Discovered a "`focusabale`" typo in button styles
- Discovered a bug with `:focus-visible` not working in High Contrast Mode
- Reorganized CSS so that `[disabled]` styles cascade correctly.
- Fixed `focusabale` typo
- Removed errant `)` char from `:focus-visible` …

fix(web-components): fix disabled button styles

---

change/@fluentui-web-components-11e8a2bd-9b9b-4ffd-91ed-6e4984f9eccf.json
packages/web-components/package.json

The Menu component depends on `@floating-ui/dom` but the package is not in `web-components/package.json`, which can cause issues in build when another package depends on `@fluentui/web-components`.
Added `@floating-ui/dom` as a dependency.

build: add @floating-ui/dom as a dependency

---

change/@fluentui-react-tree-886c9d74-378a-47cd-8541-ed8067e40e4f.json
packages/react-components/react-tree/src/components/Tree/Tree.cy.tsx
packages/react-components/react-tree/src/hooks/useRovingTabIndexes.ts

1. adds `useEffect` to ensure that if no element is currently with `tabindex=0` then the roved element should be recalculated.
2. adds test to ensure behavior
- Fixes https://github.com/microsoft/fluentui/issues/31583

bugfix(react-tree): ensure roving tab index when children changes

---

.codesandbox/ci.json
package.json

Recently codesandbox pipelines started failing on every PR
_Example:_
https://github.com/microsoft/fluentui/pull/31586
Why?
I dunno 🕵️‍♂️ but it is clearly broken on their side as those pipeline Pass but show as failed within our PRs
**Action:**
- CS app was removed from repo
- this PR removes ci config
- Fixes https://github.com/microsoft/fluentui/issues/27531

ci: remove codesandbox ci

---

change/@fluentui-react-tree-c13347b6-7d03-4e17-9814-38c22c21bacd.json
packages/react-components/react-tree/etc/react-tree.api.md
packages/react-components/react-tree/src/components/TreeItemLayout/TreeItemLayout.types.ts
packages/react-components/react-tree/src/components/TreeItemLayout/useTreeItemLayout.tsx

1. adds `onVisibilityChange` method to `TreeItemLayout` `action` slot signature
- Fixes https://github.com/microsoft/fluentui/issues/31584

feature(react-tree): onVisibilityChange method to TreeItemLayout action slot

---

packages/react-components/react-motion/stories/CreateMotionComponent/index.stories.ts
packages/react-components/react-motion/stories/PresenceGroup/index.stories.ts

docs: remove "preview" label from motion stories

---

change/@fluentui-web-components-cb78e90b-9ba3-4165-8ed1-8aa132f8403e.json
packages/web-components/src/dialog/dialog.styles.ts

Unnecessary/unwanted visible border around dialogs
Moved border per Figma design spec into Forced Colors mode. 
- Fixes #

fix(web-components): update dialog border

---

.github/CODEOWNERS

see PR title + references issue
- Fixes partially https://github.com/microsoft/fluentui/issues/31615

chore: update temporarily codeowners for split-in-two migrated packages to maintain proper PR review assignemnt for outdated branches

---

apps/vr-tests-web-components/src/stories/switch/switch.stories.tsx
change/@fluentui-web-components-08ae4a29-13c9-459b-8b03-c40e270288cc.json
packages/web-components/docs/api-report.md
packages/web-components/src/checkbox/checkbox.ts
packages/web-components/src/switch/switch.spec.ts
packages/web-components/src/switch/switch.stories.ts
packages/web-components/src/switch/switch.styles.ts
packages/web-components/src/switch/switch.template.ts
packages/web-components/src/switch/switch.ts

Switch was FormAssociated without ElementInternals
This PR updates Switch to leverage ElementInternals by extending a new `BaseCheckbox` class which includes everything but the presentational attributes of Checkbox. In alignment with our current direction, this removes the label and label attributes from the Switch itself. Labels may be associated using HTML Label elements either in isolation with custom styling or by leveraging the Field component with an HTML label.

chore: update Switch to leverage ElementInternals via Checkbox

---

change/@fluentui-web-components-1fa74631-ff88-48ec-a0c6-15691f79e0a1.json
packages/web-components/src/switch/switch.styles.ts

The border color maintains the unchecked rest state color, which is incorrect. The color should match the fill in a checked state.
The border color matches the fill state as per the design file.
- Fixes #

fix: corrects the border-color for switch when in the checked state on rest

---

change/@fluentui-web-components-55475f34-e514-43d2-9e62-b2f8ce5d3cb3.json
packages/web-components/src/theme/set-theme.ts

Dynamically updating CSS properties is not working because once a property is registered you cannot register it again.
This PR adds a try/catch block to mitigate the issue and ensure that if a property has already been registered the value is updated in the DOM. In the case where something is not registered, it will use the registerProperty method. In the case it has already been registered, this will ensure the property gets updated.
- Fixes #

fix: allow updating of CSS properties when they are already defined

---

change/@fluentui-web-components-205be5a1-cc0b-4195-879b-5e7c82b5ddea.json
packages/web-components/docs/api-report.md
packages/web-components/src/divider/divider.spec.ts
packages/web-components/src/divider/divider.stories.ts
packages/web-components/src/divider/divider.template.ts
packages/web-components/src/divider/divider.ts

The ARIA role and the orientation were bound in the template using attributes
All ARIA is now managed through ElementInternals

feat: update divider to use element internals

---

change/@fluentui-react-nav-preview-4efe24c1-f391-47b9-a5fb-9ff0c615294f.json
packages/react-components/react-nav-preview/etc/react-nav-preview.api.md
packages/react-components/react-nav-preview/src/components/Nav/Nav.types.ts
packages/react-components/react-nav-preview/src/components/Nav/index.ts
packages/react-components/react-nav-preview/src/components/Nav/useNav.ts
packages/react-components/react-nav-preview/src/components/NavCategoryItem/NavCategoryItem.types.ts
packages/react-components/react-nav-preview/src/components/NavCategoryItem/useNavCategoryItem.styles.ts
packages/react-components/react-nav-preview/src/components/NavCategoryItem/useNavCategoryItem.tsx
packages/react-components/react-nav-preview/src/components/NavContext.ts
packages/react-components/react-nav-preview/src/components/NavContext.types.ts
packages/react-components/react-nav-preview/src/components/NavDrawerBody/useNavDrawerBodyStyles.styles.ts
packages/react-components/react-nav-preview/src/components/NavDrawerFooter/useNavDrawerFooterStyles.styles.ts
packages/react-components/react-nav-preview/src/components/NavDrawerHeader/useNavDrawerHeaderStyles.styles.ts
packages/react-components/react-nav-preview/src/components/NavItem/NavItem.types.ts
packages/react-components/react-nav-preview/src/components/NavItem/useNavItem.ts
packages/react-components/react-nav-preview/src/components/NavItem/useNavItemStyles.styles.ts
packages/react-components/react-nav-preview/src/components/NavSectionHeader/useNavSectionHeaderStyles.styles.ts
packages/react-components/react-nav-preview/src/components/NavSubItem/NavSubItem.types.ts
packages/react-components/react-nav-preview/src/components/NavSubItem/useNavSubItem.ts
packages/react-components/react-nav-preview/src/components/NavSubItem/useNavSubItemStyles.styles.ts
packages/react-components/react-nav-preview/src/components/sharedNavStyles.styles.ts
packages/react-components/react-nav-preview/src/components/useNavContextValues.tsx
packages/react-components/react-nav-preview/src/index.ts
packages/react-components/react-nav-preview/stories/Nav/index.stories.tsx
packages/react-components/react-nav-preview/stories/NavDrawer/NavDrawerDefault.stories.tsx
packages/react-components/react-nav-preview/stories/NavDrawer/NavDrawerSize.stories.tsx

Adds small variant to Nav, and a little more pixel pushing for alignments.
Cleaned up a duplicate item in an example.
Added a new example for size.

feat:(react-nav-preview) Adds small size variant

---

packages/react-components/react-drawer/stories/src/Drawer/DrawerBestPractices.md
packages/react-components/react-drawer/stories/src/Drawer/DrawerDefault.stories.tsx
packages/react-components/react-drawer/stories/src/Drawer/DrawerWithNavigation.stories.tsx
packages/react-components/react-drawer/stories/src/Drawer/InlineDrawer.stories.tsx

No package changes, fixes several bugs in the storybook examples:
- InlineDrawer stories & best practices docs show how to handle focus restoration
- Inline story doesn't clip left/right/bottom buttons at high zoom %
- Navigation story's drawer splits the back button out from the toolbar (not technically a compliance bug, but I agree that visually it's unexpected to need to arrow from the back button to the actions)
(Fixes several ADO a11y bugs)

fix: Drawer story accessibility fixes and docs update

---

packages/react-components/react-accordion/stories/Accordion/AccordionSizes.stories.tsx

The Accordion Size story has multiple different accordions to show the different sizes, but appears broken because they can't be collapsed when another is opened.
Add `collapsible` to the accordions in this story, and update the header text to be more descriptive. 
Note: an alternative would be to combine the sizes into a single accordion panel, but mixing sizes in a single accordion isn't recommended, and we prefer to avoid non-recommended usages in story examples.
- Fixes #31610

Update Accordion Size story to allow collapsing

---

change/@fluentui-web-components-24db3759-9402-48da-b37b-d829a7c7902a.json
packages/web-components/src/dialog-body/dialog-body.spec.ts
packages/web-components/src/dialog-body/dialog-body.template.ts

Title action would only show by default for non-modal dialogs.
Title action will show by default for both non-modal and modal dialogs. It is hidden by default for alert dialogs.
- Fixes #

fix: show default title action in dialog body for modal dialogs

---

change/@fluentui-react-motion-74754f46-cdfd-42ee-8838-8389f353b5c6.json
packages/react-components/react-motion/library/etc/react-motion.api.md
packages/react-components/react-motion/library/src/factories/createMotionComponent.ts
packages/react-components/react-motion/library/src/factories/createPresenceComponent.ts
packages/react-components/react-motion/library/src/types.ts
packages/react-components/react-motion/stories/src/CreateMotionComponent/MotionFunctionParams.stories.md
packages/react-components/react-motion/stories/src/CreateMotionComponent/MotionFunctionParams.stories.tsx
packages/react-components/react-motion/stories/src/CreateMotionComponent/index.stories.ts
packages/react-components/react-motion/stories/src/CreatePresenceComponent/PresenceMotionFunctionParams.stories.md
packages/react-components/react-motion/stories/src/CreatePresenceComponent/PresenceMotionFunctionParams.stories.tsx
packages/react-components/react-motion/stories/src/CreatePresenceComponent/index.stories.ts

Adds support for custom props (params) in motions to to `createMotionComponent()` & `createPresenceComponent()`.
```tsx
const Scale = createPresenceComponent<{ startFrom?: number }>(({ startFrom = 0.5 }) => {
const keyframes = [
{ opacity: 0, transform: `scale(${startFrom})` },
{ opacity: 1, transform: 'scale(1)' },
];
return {
enter: {
keyframes,
duration: motionTokens.durationUltraSlow,
},
exit: {
keyframes: [...keyframes].reverse(),
duration: motionTokens.durationSlow,
},
};
});
```
Fixes [#31576](https://github.com/microsoft/fluentui/issues/31576).

feat(react-motion): add support for params

---

packages/react-components/react-skeleton/stories/Skeleton/SkeletonItemShape.stories.tsx
packages/react-components/react-skeleton/stories/Skeleton/SkeletonItemSize.stories.tsx
packages/react-components/react-skeleton/stories/Skeleton/index.stories.tsx

Resolves #31222. Extended `Skeleton` story to have `SkeletonItem` examples for `size` and `shape` props. Tbh, not sure if it deserves completely separated tab, as `SkeletonItem` isn't standalone and supposed to be used as a child component of `Skeleton`.
#31222

docs(react-skeleton): extend Skeleton story with SkeletonItem examples

---

docs/react-v9/contributing/dev-env.md

We have node set on `^20.0.0 || ^22.0.0`. Updated the dev-env doc according to it.

docs(dev-env): update minimal node version

---

change/@fluentui-react-infobutton-bf89c268-c7d9-4643-a950-446a32a51e7e.json
change/@fluentui-react-motions-preview-2a7ccd1a-4e03-4c37-812f-a8abe7a8fde4.json
change/@fluentui-react-motions-preview-8fed56ea-bf79-45b6-966d-c8e1b83efc50.json
change/@fluentui-react-motions-preview-dffb90ce-ff7d-44d5-8d92-31d75815ea2d.json
change/@fluentui-react-motions-preview-e1a364d2-4a00-430c-b330-736eaf432fd7.json
change/@fluentui-react-motions-preview-f7e0f94c-24bd-4fa0-bae2-886019aac40f.json
change/@fluentui-react-search-preview-799fdb3b-d35b-4f1d-a246-2e4f524927ca.json
change/@fluentui-react-swatch-picker-preview-827150f2-7642-4787-ad58-1bfe3bbd31ec.json
change/@fluentui-react-tag-picker-preview-35e06389-b8ac-46fa-a9a9-c186c3c2941e.json
change/@fluentui-react-tag-picker-preview-4dc187e5-80b6-49e0-9937-0ab7ada11736.json
change/@fluentui-react-tag-picker-preview-7bcdff38-0f92-440f-a2e7-b36bad408a21.json
change/@fluentui-react-tag-picker-preview-f8f44d4f-94d1-47ff-818c-80bce94db23c.json
scripts/beachball/src/config.test.ts
scripts/beachball/src/utils.ts

`web-components` were not ignored within v8 release scope, thus invalid releases have been triggered every-time web-components added a change file. 
Even more confusion was added to changelog.md v8 files which  refers to web-component changes with date of web-component release.
Example:
https://github.com/microsoft/fluentui/blob/master/packages/react/CHANGELOG.md#81176 points to https://github.com/microsoft/fluentui/pull/31585/files which was released https://github.com/microsoft/fluentui/blob/master/packages/web-components/CHANGELOG.md#300-beta24
- `web-components` tagged packages are excluded from v8 `scope` 
- `web-components` tagged packages are explicitly provided to web-components release-scope without ignoring all v9 tagged packages ( which is not needed )
**Extra:**
- invalid …

fix(scripts-beachball): ignore web-components packages from v8 release scope

---

apps/vr-tests-web-components/src/stories/link/link.stories.tsx
change/@fluentui-web-components-b66f6166-9635-4438-87af-8cb454ae22d1.json
packages/web-components/docs/api-report.md
packages/web-components/package.json
packages/web-components/src/anchor-button/anchor-button.ts
packages/web-components/src/index-rollup.ts
packages/web-components/src/index.ts
packages/web-components/src/link/define.ts
packages/web-components/src/link/index.ts
packages/web-components/src/link/link.bench.ts
packages/web-components/src/link/link.definition.ts
packages/web-components/src/link/link.options.ts
packages/web-components/src/link/link.spec.ts
packages/web-components/src/link/link.stories.ts
packages/web-components/src/link/link.styles.ts
packages/web-components/src/link/link.template.ts
packages/web-components/src/link/link.ts

N/A
This PR adds link as a new web component.
- Fixes #

feat: add link as new web component

---

change/@fluentui-react-context-selector-1631f749-7a25-42ca-97eb-89acf047a9aa.json
packages/react-components/react-context-selector/src/useContextSelector.ts

`useContextSelector()` implementation relies on bail-outs if values are shallow equal:
https://github.com/microsoft/fluentui/blob/1f3d2e7acb51e03627e7355e6d73f90bd1faa7e9/packages/react-components/react-context-selector/src/useContextSelector.ts#L47-L49
However, this does not work anymore with React 18 💥
```
// Parent: render
// Child: render
// Parent: useLayoutEffect (note 1)
// Child: bail-out ✅ 
```
```
// Parent: render
// Child: render
// Parent: useLayoutEffect (note 1)
// Child: re-render 💣 
```
<details>
<summary>Note 1: useLayoutEffect</summary>
This effect propagates updates to its consumers once "Parent" gets rendered:
https://github.com/microsoft/fluentui/blob/1f3d2e7acb51e03627e7355e6d73f90bd1faa7e9/packages/react-components/react-context-selector/src/createContext.ts#L25-L34 …

fix: useContextSelector with React 18

---

change/@fluentui-react-tabster-8340f6d3-64d6-49e1-a8f9-04ea4973aa3d.json
packages/react-components/react-tabster/etc/react-tabster.api.md
packages/react-components/react-tabster/package.json
packages/react-components/react-tabster/src/hooks/useArrowNavigationGroup.ts
packages/react-components/react-tabster/src/hooks/useFocusableGroup.ts
packages/react-components/react-tabster/src/hooks/useMergeTabsterAttributes.ts
packages/react-components/react-tabster/src/hooks/useModalAttributes.ts
packages/react-components/react-tabster/src/hooks/useRestoreFocus.ts
packages/react-components/react-tabster/src/hooks/useTabsterAttributes.ts
packages/react-components/react-tabster/src/index.ts
yarn.lock

We've improved how consts and types are exported from Tabster which should improve the bundle sizes.

chore(react-tabster): bump tabster to 8.0.0 to pull the exports refactoring and improve bundle size

---

change/@fluentui-react-menu-6f394e3c-789d-463b-9292-34fbdddb0970.json
change/@fluentui-react-tabster-801c3f1f-2eb1-4c83-91fa-19a5893454ed.json
packages/react-components/react-menu/library/src/components/MenuList/__snapshots__/MenuList.test.tsx.snap
packages/react-components/react-menu/library/src/components/MenuList/useMenuList.ts
packages/react-components/react-tabster/etc/react-tabster.api.md
packages/react-components/react-tabster/src/index.ts

MenuList had ignoreKeydown for Tab to prevent Tabster from handling the Tab press. As a side effect this ignoreKeydown was affecting submenus too. This PR uses TabsterMoveFocusEvent to prevent Tabster from handling the Tab press in a particular case that doesn't affect submenus.

fix(MenuList): Removing ignoreKeydown from MenuList.

---

change/@fluentui-web-components-a05b784c-1559-4ccd-b8f2-0c5e7818fdfb.json
packages/web-components/docs/api-report.md
packages/web-components/src/avatar/avatar.spec.ts
packages/web-components/src/avatar/avatar.styles.ts
packages/web-components/src/avatar/avatar.template.ts
packages/web-components/src/avatar/avatar.ts

Avatar applies the role and color in the DOM.
Avatar uses ElementInternals for the role and setting a custom state (with attribute fallback) for colors, to avoid sprouting unnecessary attributes.
- Fixes #

feat: update Avatar to leverage ElementInternals for role and color states

---

change/@fluentui-react-motion-f8cc73b4-883a-4c0a-a9df-8df610c222ff.json
packages/react-components/react-motion/library/cypress.config.ts
packages/react-components/react-motion/library/etc/react-motion.api.md
packages/react-components/react-motion/library/package.json
packages/react-components/react-motion/library/src/factories/createMotionComponent.ts
packages/react-components/react-motion/library/src/factories/createPresenceComponent.cy.tsx
packages/react-components/react-motion/library/src/factories/createPresenceComponent.ts
packages/react-components/react-motion/library/src/types.ts
packages/react-components/react-motion/library/src/utils/animateAtoms.ts
packages/react-components/react-motion/library/tsconfig.cy.json
packages/react-components/react-motion/library/tsconfig.json
packages/react-components/react-motion/library/tsconfig.lib.json
packages/react-components/react-motion/stories/src/CreateMotionComponent/MotionLifecycleCallbacks.stories.md
packages/react-components/react-motion/stories/src/CreateMotionComponent/MotionLifecycleCallbacks.stories.tsx
packages/react-components/react-motion/stories/src/CreatePresenceComponent/PresenceLifecycleCallbacks.stories.md
packages/react-components/react-motion/stories/src/CreatePresenceComponent/PresenceLifecycleCallbacks.stories.tsx

When a motion or presence changes state or is unmounted before it finishes, the internals calls `.cancel` which does not emit a `finish` event.
Adds `onMotionCancel` to presence and motion components so that users can hook into all possible lifecycle events.
Also adds cypress test for this new callback

feat: Implement `onMotionCancel` callback handler

---

change/@fluentui-merge-styles-3328f941-f74b-4a07-8fc0-aca13cacd01f.json
packages/merge-styles/etc/merge-styles.api.md
packages/merge-styles/src/DeepPartial.ts
packages/merge-styles/src/IRawStyle.ts
packages/merge-styles/src/IStyle.ts
packages/merge-styles/src/IStyleFunction.ts
packages/merge-styles/src/IStyleOptions.ts
packages/merge-styles/src/IStyleSet.ts
packages/merge-styles/src/concatStyleSets.ts
packages/merge-styles/src/concatStyleSetsWithProps.ts
packages/merge-styles/src/index.ts
packages/merge-styles/src/mergeStyleSets.ts
packages/merge-styles/src/mergeStyles.ts
packages/merge-styles/src/shadowConfig.ts

This PR mitigates `TS2589: Type instantiation is excessively deep and possibly infinite.` Error that our users started to run into after adding opt in ShadowDom functionality into v8 styling system (https://github.com/microsoft/fluentui/pull/30689)
- new `DeepPartialV2` is used within codebase instead of problematic `DeepPartial`
- `DeepPartial` is marked `@deprecated` as we cannot remove it because it's  exposed as part of  public API
- complex repetitive union types across function overloads are aggregated to shared type for reuse and performance (https://github.com/microsoft/TypeScript/pull/42149)
- renames internally custom `Omit` to `_Omit` to be explicit about it's not from ts.lib
- some internal logic types have been fixed as well
- `isShadowConfig` type predicate internals have …

fix(merge-styles): introduce `DeepPartialV2` type to avoid infinite type instantiation and make unions declaration more performant

---

apps/react-18-tests-v9/jest.config.js
apps/react-18-tests-v9/package.json
apps/react-18-tests-v9/src/App.test.tsx
yarn.lock

Solution: add `moduleNameMapper()`
Solution: bump `@testing-library/react` for that pkg
---
Fixes #31717

fix: fix react-18-tests-v9 to run tests

---

docs/react-v9/contributing/cla.md

Ports the CLA (unchanged) from the wiki.
https://github.com/microsoft/fluentui/wiki/CLA

chore:docs Ports CLA from wiki

---

packages/react-components/react-swatch-picker/stories/src/SwatchPicker/EmptySwatch.stories.tsx
packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerPopup.stories.tsx

- aria-labels were missing buttons in EmptySwatch examples
- there were no feedback for user after button clicks
- Added aria-labels for EmptySwatch examples
- Added live regions for feedback when clicks on buttons occur
- Added grid layout for an example with popup

fix(react-swatch-picker): added aria-labels and fixed popup example

---

change/@fluentui-react-motion-e52e3064-afc3-40d1-940c-aafafe2353cf.json
packages/react-components/react-motion/library/bundle-size/PresenceGroup.fixture.js
packages/react-components/react-motion/library/bundle-size/createMotionComponent.fixture.js
packages/react-components/react-motion/library/bundle-size/createPresenceComponent.fixture.js
packages/react-components/react-motion/library/package.json

Adds new bundle size fixtures for `@fluentui/react-motion`.

chore(motion): add bundle size fixtures

---

change/@fluentui-react-calendar-compat-f38fe669-e50e-4648-9f66-ec82e13beee3.json
packages/react-components/react-calendar-compat/library/src/components/CalendarDayGrid/useCalendarDayGridStyles.styles.ts

- Focus indicator get cut off in Calendar Month selection
- Focus should be fully visible
- Removed TRANSITION_ROW_DISAPPEARANCE animation to improve performance

fix(react-calendar-compat): fixed focus indicator cut off

---

change/@fluentui-web-components-8fa1a0aa-7dd4-4129-89c3-fe350ad0fa58.json
packages/web-components/src/anchor-button/anchor-button.spec.ts
packages/web-components/src/anchor-button/anchor-button.styles.ts
packages/web-components/src/anchor-button/anchor-button.template.ts
packages/web-components/src/anchor-button/anchor-button.ts
packages/web-components/src/button/button.options.ts
packages/web-components/src/button/button.styles.ts
packages/web-components/src/button/button.ts
packages/web-components/src/compound-button/compound-button.styles.ts
packages/web-components/src/link/link.styles.ts
packages/web-components/src/link/link.template.ts
packages/web-components/src/styles/states/index.ts
packages/web-components/src/toggle-button/toggle-button.spec.ts
packages/web-components/src/toggle-button/toggle-button.styles.ts
packages/web-components/src/toggle-button/toggle-button.ts

All styling hooked off attribute selectors.
All variants now get set using custom states via ElementInternals. In the case that states are not supported, an attribute with will be added to manage those scenario. So, for `primary` buttons, if states are not supported, `state--primary` will be added.
This gives long term benefits of being able to quickly remove the attribute fallback as custom state support grows in our matrix. It also has performance parity overall when including the attributes, making way for performance wins once that can be removed.
- Fixes #

feat: use custom states for button and anchor button variants

---

change/@fluentui-web-components-ff673af3-b066-47c9-aea7-37e4558d7ace.json
packages/web-components/src/badge/badge.styles.ts
packages/web-components/src/badge/badge.ts
packages/web-components/src/counter-badge/counter-badge.styles.ts
packages/web-components/src/counter-badge/counter-badge.ts
packages/web-components/src/styles/partials/badge.partials.ts
packages/web-components/src/styles/states/index.ts

All styles are associated with attribute selectors
Styles are associated with element internals custom states where supported and fallback to a state attribute when not supported.
- Fixes #

feat: update badge to use custom states

---

change/@fluentui-react-teaching-popover-cdaeeec1-2b74-432f-a6ec-694d78207d7c.json
packages/react-components/react-teaching-popover/library/src/components/TeachingPopoverCarouselNavButton/useTeachingPopoverCarouselNavButtonStyles.styles.ts

The tabs/dots were not visible in WHCM:
- Fixes an ADO a11y issue

fix: Teaching bubble carousel tabs are visible in windows high contrast

---

change/@fluentui-react-nav-preview-71eeaf96-dc68-4684-9b39-e17f06cdd4c1.json
docs/react-v9/contributing/dev-workflow.md
packages/react-components/react-nav-preview/library/src/components/sharedNavStyles.styles.ts

Addresses icon and indicator issues in Teams HC theme and Windows High Contrast when items are selected.
Teams HC before:
Windows HC before:
Teams HC after:
Windows HC after:

fix:react-nav-preview: High contrast issues

---

azure-pipelines.release-vnext.yml
azure-pipelines.release.web-components.yml
azure-pipelines.release.yml

when release is triggered it creates commit with generic message `applying package updates`, which is not obvious for what library/framework did the release happen.
when release is triggered it creates commit with proper context about library/framework:
`release: applying package updates - <framework-name>`
- Fixes #

ci: tweak release commit message in order to easily determine what release did happen from git history

---

change/@fluentui-web-components-2f1071a4-73d5-47cf-b41f-aa1a853df46f.json
packages/web-components/docs/api-report.md
packages/web-components/src/divider/divider.spec.ts
packages/web-components/src/divider/divider.styles.ts
packages/web-components/src/divider/divider.ts
packages/web-components/src/styles/states/index.ts

Replaces attributes with Element Internals custom states by default with `state-` attribute fallbacks.
- Fixes #

feat: update divider to use custom states

---

change/@fluentui-web-components-d43a8b52-e22f-4523-af8b-a42fd90a4765.json
packages/web-components/src/spinner/spinner.spec.ts
packages/web-components/src/spinner/spinner.styles.ts
packages/web-components/src/spinner/spinner.ts
packages/web-components/src/styles/states/index.ts

This PR updates the spinner to use Element Internals custom states for presentational styling with an attribute fallback where not available.
- Fixes #

feat: update spinner to use Element Internals for presentational styling

---

change/@fluentui-web-components-024847b6-4c7b-4e23-964d-466ce50c33a5.json
packages/web-components/docs/api-report.md
packages/web-components/src/progress-bar/progress-bar.spec.ts
packages/web-components/src/progress-bar/progress-bar.styles.ts
packages/web-components/src/progress-bar/progress-bar.ts
packages/web-components/src/styles/states/index.ts

This PR updates the progress bar web component to leverage Element Internals custom states for visual styling and provides an attribute fallback where not supported.
- Fixes #

feat: update progress bar to use element internals custom states for visual states

---

change/@fluentui-web-components-e7635a3f-6231-44e9-9ab4-bc1fdb86052c.json
packages/web-components/docs/api-report.md
packages/web-components/src/label/label.spec.ts
packages/web-components/src/label/label.styles.ts
packages/web-components/src/label/label.ts

Updates label to use Element Internals custom states for styling with an attribute fallback where not supported.
- Fixes #

feat: update label to use element internals custom states for styling

---

change/@fluentui-web-components-89765cbd-e940-4368-8e9c-2e6a6aea5943.json
packages/web-components/docs/api-report.md
packages/web-components/src/image/image.spec.ts
packages/web-components/src/image/image.styles.ts
packages/web-components/src/image/image.ts

Moves styling from attributes to Element Internals custom states with an attribute fallback where not supported.
- Fixes #

feat: update image styles to use custom states

---

package.json
yarn.lock

`yarn build` was failing in at least PowerShell in Windows computers with the following error:
```
PS D:\repos\fluentui-g> yarn build
yarn run v1.23.34
$ lage build --verbose
info Lage task runner - let's make it
verb filterPackages running with dependents
info @fluentui/digest build ▶️ start 
verb @fluentui/digest build |  hash: fb570c10d91771fa150838d18b0e9f32c123ef89, cache hit? false
verb @fluentui/digest build |  Running C:\Program Files\nodejs\npm.CMD run build
info @fluentui/digest build ❌ fail
info 🏗 Summary
info
verb @fluentui/digest build failed, took 0.01s
verb @fluentui/react-northstar build:info pending, took 0.00s
verb @fluentui/a11y-testing build pending, took 0.00s
verb @fluentui/api-docs build pending, took 0.00s
verb @fluentui/codemods build pending, took 0.00s
verb …
```

chore: Updating `lage` to `v1.10.0`

---

packages/react-examples/src/react/DetailsList/DetailsList.CustomGroupHeaders.Example.tsx

Example-only fix, no package changes.
The custom group header example had a custom header/footer render function, but didn't add grid semantics to the output.
Fixed!
- Fixes an ADO issue

fix: DetailsList custom group header example uses correct semantics

---

change/@fluentui-web-components-7791704b-b516-47f9-bc44-b1e18b45a35f.json
packages/web-components/docs/api-report.md
packages/web-components/src/styles/states/index.ts
packages/web-components/src/text-input/text-input.spec.ts
packages/web-components/src/text-input/text-input.styles.ts
packages/web-components/src/text-input/text-input.ts

This PR updates text-input to use ElementInternals custom states with an attribute fallback where not supported for presentational attribute styling.
- Fixes #

feat: update text input to use custom states for presentational attributes

---

change/@fluentui-web-components-45992585-e259-47e0-b8a2-2e3746e546f1.json
packages/web-components/docs/api-report.md
packages/web-components/src/anchor-button/anchor-button.ts
packages/web-components/src/link/link.spec.ts
packages/web-components/src/link/link.styles.ts
packages/web-components/src/link/link.ts

This PR migrates link to use ElementInternals custom states with an attribute fallback for presentational attribute styling.
- Fixes #

feat: update link to use element internals custom states for presentational styling

---

change/@fluentui-react-nav-preview-527c5ff5-5fa1-4d9b-a84c-90d725ddc550.json
packages/react-components/react-nav-preview/library/src/components/sharedNavStyles.styles.ts
packages/react-components/react-nav-preview/stories/src/NavDrawer/NavDrawerDefault.stories.tsx

Adding graceful animations to the selection behavior.
I'd like to pull this out into it's own component some day for cases where the extra DOM bloat necessary (wrapper w/ css overlapping grid) is appropriate.
Updates examples to toggle link behavior to enable testing.
https://github.com/microsoft/fluentui/assets/17346018/98cb0396-0679-46ce-b40c-3e1cf4ea95cc
ladders to #26649

feat:(react-nav-preview) Selection indicator and icon animation

---

change/@fluentui-react-select-1166c4a9-ab11-4b39-be63-4dd68664630d.json
packages/react-components/react-select/library/src/components/Select/useSelectStyles.styles.ts

On Windows browsers, Select options in the underline appearance variant picked up the parent `<select>` text color style, but always have the default background color since underline has a transparent background. In dark themes, this causes them to have a light color over a light background:
Options in the underline appearance have an explicit background color set:
- Fixes an ADO issue

fix: v9 Select options in underline appearance are readable in dark themes

---

change/@fluentui-web-components-76101ff6-e6ee-43b5-8c67-f75bd0466480.json
packages/web-components/docs/api-report.md
packages/web-components/src/checkbox/checkbox.spec.ts
packages/web-components/src/checkbox/checkbox.styles.ts
packages/web-components/src/checkbox/checkbox.ts

This PR updates the Checkbox component to use Element Internals custom states for presentational styles with an attribute fallback where not supported.
- Fixes #

feat: update checkbox to use Element Internals custom states for presentational styles

---

change/@fluentui-react-aria-98a2ae86-abde-4e51-888a-d17e8e7badba.json
change/@fluentui-react-combobox-eda940fc-c0e1-4884-bfab-7b3a71b69269.json
change/@fluentui-react-tag-picker-938c2d34-5817-4f23-b592-0389cd9cd215.json
packages/react-components/react-aria/library/etc/react-aria.api.md
packages/react-components/react-aria/library/src/activedescendant/ActiveDescendantContext.ts
packages/react-components/react-aria/library/src/activedescendant/types.ts
packages/react-components/react-aria/library/src/activedescendant/useActiveDescendant.ts
packages/react-components/react-aria/library/src/activedescendant/useActivedescendant.test.tsx
packages/react-components/react-combobox/library/etc/react-combobox.api.md
packages/react-components/react-combobox/library/src/components/Dropdown/useButtonTriggerSlot.ts
packages/react-components/react-combobox/library/src/components/Listbox/Listbox.test.tsx
packages/react-components/react-combobox/library/src/components/Listbox/Listbox.types.ts
packages/react-components/react-combobox/library/src/components/Listbox/__snapshots__/Listbox.test.tsx.snap
packages/react-components/react-combobox/library/src/components/Listbox/useListbox.ts
packages/react-components/react-combobox/library/src/components/Listbox/useListboxStyles.styles.ts
packages/react-components/react-combobox/library/src/components/Option/Option.test.tsx
packages/react-components/react-combobox/library/src/contexts/ListboxContext.ts
packages/react-components/react-combobox/library/src/contexts/useComboboxContextValues.ts
packages/react-components/react-combobox/library/src/contexts/useListboxContextValues.ts
packages/react-components/react-combobox/library/src/utils/useComboboxBaseState.ts
packages/react-components/react-tag-picker/library/etc/react-tag-picker.api.md
packages/react-components/react-tag-picker/library/src/components/TagPicker/TagPicker.cy.tsx
packages/react-components/react-tag-picker/library/src/components/TagPicker/TagPicker.types.ts
packages/react-components/react-tag-picker/library/src/components/TagPicker/useTagPicker.ts
packages/react-components/react-tag-picker/library/src/components/TagPicker/useTagPickerContextValues.ts

Related to #31140 and #31235
Essentially this moves the initial `activeDescendantController` setting logic from `useComboboxBaseState` to `useListbox`, so it runs when the listbox is first renders instead of based on the change in `open` state.
That both makes combobox/dropdown `aria-activedescendant` logic a bit more straightforward (the attribute is set if the referenced option exists), and also makes a standalone listbox work.
It also moves a couple option lookup functions to the context, so that Listbox can access them (previously the `getOptionById` logic in `onFocus` wasn't working when not a standalone widget, since it didn't have access to the parent combobox's option collection).
The original issue was that listbox did not set the initial activedescendant. The first fix to that …

fix: standalone Listbox updates activedescendant correctly

---

change/@fluentui-react-checkbox-0bd07ac3-68d9-4702-a438-ddb46d25af4e.json
packages/react-components/react-checkbox/library/docs/Spec.md
packages/react-components/react-checkbox/library/etc/react-checkbox.api.md
packages/react-components/react-checkbox/library/src/components/Checkbox/Checkbox.types.ts

Indicator type is extended to accept `span`. Added warning comments about current incorrect semantics and updated the doc file to have correct semantics. 
Have to be removed in the next major. 
Partially fixes #29969

fix(react-checkbox): adjust indicator type to include span

---

.storybook/main.js
apps/public-docsite-v9/.storybook/manager-head.html

Favicon was removed or server-side routing was broken
```html
<link rel="shortcut icon" href="https://www.microsoft.com/design/fluent/assets/favicons/favicon-192.png" />
```
This url redirects with 301 to the main page
```bash
curl -Ls -o /dev/null -w %{url_effective} https://www.microsoft.com/design/fluent/assets/favicons/favicon-192.png
https://fluent2.microsoft.design/
```
fluent2.microsoft.design uses this configuration, so I made similar changes but with own Fluent UI icon
```html
<link rel="shortcut icon" type="image/x-icon" href="/favicons/favicon.ico">
```
Also I fixed url in JSDoc in storybook config
- Fixes #31606

Fix storybook favicon

---

change/@fluentui-react-tree-bd13a9b3-9413-43ea-91f2-9b58288a77d8.json
packages/react-components/react-tree/library/src/components/TreeItem/TreeItem.test.tsx
packages/react-components/react-tree/library/src/components/TreeItem/__snapshots__/TreeItem.test.tsx.snap
packages/react-components/react-tree/library/src/components/TreeItem/useTreeItem.tsx

1. A `TreeItem` will not function properly if outside of a `Tree` component, as it requires the context provided by `Tree` to work properly.
2. `openChange` is being called even if a `TreeItem` is a leaf (this might cause false negatives)
1. consoles error if no `TreeContext` has been found
2. short circuit to ensure `onOpenChange` won't be called on a `TreeItem`
- Fixes https://github.com/microsoft/fluentui/issues/31765

bugfix(react-tree): console error if `TreeItem` has no parent `Tree`

---

change/@fluentui-react-message-bar-0408d1da-e3d1-4d30-955d-7fa6120e573d.json
packages/react-components/react-message-bar/library/src/components/MessageBar/getIntentIcon.tsx

Fixes #31604. Icon was incorrect, I wonder why was not caught on visual regression. Maybe happened after update in the icon package 🤷🏻 , maybe because of the slightly confusing naming, as I first looked on other error icons, only later found dismiss ones. 
Previous behavior 
Current behavior

fix(react-message-bar): set correct icon for error state

---

docs/react-v9/contributing/conducting-meetings-style-guide.md

Ported over from the wiki. Made a few updates - basically removed the scribe role since Copilot does a good job of that and we want highly skilled developers contributing to the conversation, not
Old doc:
https://github.com/microsoft/fluentui/wiki/Conducting-Meetings-Style-Guide

chore:(docs) Adds meeting style guide

---

docs/react-v9/contributing/using-local-unpublished-version-of-the-lib-with-a-local-React-app.md

Ports [this doc on using unpublished versions of Fluent](https://github.com/microsoft/fluentui/wiki/Using-local-(unpublished)-version-of-the-lib-with-a-local-React-app) over to the dev doc folder.
Copied as is, no changes.

chore:(docs) Adds doc about using local unpublished in an app

---

change/@fluentui-react-tree-0bbd4942-7582-456a-9fdd-9027eaa0af91.json
packages/react-components/react-tree/library/src/components/FlatTree/FlatTree.cy.tsx
packages/react-components/react-tree/library/src/components/Tree/Tree.cy.tsx
packages/react-components/react-tree/library/src/components/TreeItem/useTreeItem.tsx

`left/right arrow + alt` is a native browser key command for navigating through tab history. At the moment the `TreeItem` is changing its open state and navigating when `left/right arrow + alt` is pressed.
1. `TreeItem` checks if `alt` key is pressed together with `left/right` arrow and short circuits internal logic if so.
- Fixes #

chore(react-tree): ensures history navigation keys are respected

---

apps/public-docsite-v9/.storybook/manager.js

Storybook App Insights were not being tracked.
Storybook App insights work as they should be. The problem was caused by env var being replaced verbatim at build time, so destructuring didn't work.

fix(storybook): replace env var destructuring with const

---

change/@fluentui-react-button-e2ba90aa-0fcc-468f-87bf-a3b63395b846.json
packages/react-components/react-button/library/src/components/ToggleButton/useToggleButtonStyles.styles.ts

The checked styles for the icon when the `ToggleButton` was `subtle` or `transparent` were being applied even when the button was not checked.
The checked styles for the icon when the `ToggleButton` is `subtle` or `transparent` are only applied when the button is checked.
- Fixes #31763

fix(`react-button`): Adding checked condition for icon styles when `ToggleButton` is checked + its appearance is subtle or transparent

---

change/@fluentui-web-components-13439a6e-ac52-4975-ab3f-2a620928a790.json
packages/web-components/docs/api-report.md
packages/web-components/package.json
packages/web-components/src/menu-item/menu-item.styles.ts
packages/web-components/src/menu-item/menu-item.template.ts
packages/web-components/src/menu-item/menu-item.ts
packages/web-components/src/menu-list/menu-list.spec.ts
packages/web-components/src/menu-list/menu-list.stories.ts
packages/web-components/src/menu-list/menu-list.styles.ts
packages/web-components/src/menu-list/menu-list.ts
packages/web-components/src/menu/menu.stories.ts
packages/web-components/src/menu/menu.styles.ts
packages/web-components/src/menu/menu.template.ts
packages/web-components/src/menu/menu.ts
packages/web-components/tensile.config.js

The current Menu component has a hard dependency on `@floating-ui/dom`, this is an attempt to slim that down and leverage HTML `popover` and CSS `anchor` positioning. 
Also discovered: 
- Drop-shadow bug on nested menu items
- Nested menu items not working in Safari
This component has been refactored to use HTML `popover` and CSS `anchor` positioning. HTML `popover`is polyfillable and we're able to gracefully degrade CSS `anchor`, so that's promising. 
Due to platform limitations with popover, we're unable to apply `popovertarget` to `fluent-button` (because it's not a _real_ `<button>`) which would automate some of the show/hiding focus management and ARIA-expanded work, but have included workarounds.
- Fixes #

refactor(web-components): refactor menu to popover

---

apps/public-docsite-v9/.storybook/manager.js

The Storybook platform uses `alt+down` and `alt+up` to navigate between components. And that conflicts with the dropdown list keyboard shortcuts. 
The suggested solution is to disable Storybook's keyboard shortcuts to avoid conflicts with the existing components keyboard shortcuts.
- Fixes #31363

fix(public-docsite-v9): disable storybook keyboard shortcuts

---

packages/react-components/react-storybook-addon/package.json
packages/react-components/react-storybook-addon/src/decorators/withAriaLive.tsx
packages/react-components/react-storybook-addon/src/preset/preview.ts

Creates a new decorator around stories so that an aria live announcer is included with an example.
Fixes #31504

docs: Add AriaLiveAnnouncer to all examples

---

change/@fluentui-merge-styles-80cf5b64-7950-4db5-9b45-b92cc006f2db.json
packages/merge-styles/src/styleToClassName.ts

After #31253 was merged and the `selectors` wrapper was removed from every button style, it was discovered that some style customizations were no longer working, such as the one in [this Stackblitz project](https://stackblitz.com/edit/stackblitz-starters-vi7nwj?file=package.json,src%2FApp.tsx) where the `rootFocused` style customizations are not being applied.
After some investigation, I discovered that the `selectors` wrapper forced a path within `extractRules` to actually go through the `extractSelector` process, which ensured that the pseudo selectors were being properly handled. In contrast, not applying the wrapper meant that the logic checked for the value of the pseudo selector being an object, a case that is handled correctly, but the same logic doesn't apply when the value is …

fix(`merge-styles`): Correctly processing selectors when value is a class name and they are not wrapped in `selectors` wrapper

---

packages/web-components/src/accordion/accordion.stories.ts
packages/web-components/src/anchor-button/anchor-button.stories.ts
packages/web-components/src/avatar/avatar.stories.ts
packages/web-components/src/badge/badge.stories.ts
packages/web-components/src/button/button.stories.ts
packages/web-components/src/checkbox/checkbox.stories.ts
packages/web-components/src/compound-button/compound-button.stories.ts
packages/web-components/src/counter-badge/counter-badge.stories.ts
packages/web-components/src/dialog-body/dialog-body.stories.ts
packages/web-components/src/dialog/dialog.stories.ts
packages/web-components/src/divider/divider.stories.ts
packages/web-components/src/image/image.stories.ts
packages/web-components/src/label/label.stories.ts
packages/web-components/src/link/link.stories.ts
packages/web-components/src/menu-button/menu-button.stories.ts
packages/web-components/src/menu-list/menu-list.stories.ts
packages/web-components/src/menu/menu.stories.ts
packages/web-components/src/progress-bar/progress-bar.stories.ts
packages/web-components/src/radio-group/radio-group.stories.ts
packages/web-components/src/radio/radio.stories.ts
packages/web-components/src/slider/slider.stories.ts
packages/web-components/src/spinner/spinner.stories.ts
packages/web-components/src/switch/switch.stories.ts
packages/web-components/src/tabs/tabs.stories.ts
packages/web-components/src/text-input/text-input.stories.ts
packages/web-components/src/text/text.stories.ts
packages/web-components/src/toggle-button/toggle-button.stories.ts

Each storybook module required an import of the component's `define.js` module to load the component onto the page.
These imports are no longer needed since the `preview.js` imports `index-rollup.js`, which includes all of the define modules for every component.

chore(web-components): Remove define imports from story modules

---

change/@fluentui-web-components-891d02bb-a945-4c7a-8e7b-a89567483de0.json
packages/web-components/docs/api-report.md
packages/web-components/src/text/text.spec.ts
packages/web-components/src/text/text.styles.ts
packages/web-components/src/text/text.ts

This PR updates the `Text` component to use Element Internals custom states for presentational attributes and provides an attribute fallback where not supported.
- Fixes #

feat: update text to use element internals for custom states

---

docs/react-v9/contributing/api-extractor.md

Adds and updates [API Extractor file from the wiki.](https://github.com/microsoft/fluentui/blob/54eb707c73a413a2e29e7150b2fdfd89780b4ec3/docs/react-wiki-archive/API-Extractor.md)
Adds bits on how to generate and update the file.

chore:(docs) Update API Extractor file

---

docs/react-v9/contributing/e2e-testing-with-cypress.md

Migrates end to end testing with Cypress [from the wiki ](https://github.com/microsoft/fluentui/wiki/E2E-testing-with-Cypress)to the new docs folder.
Removed references to v0 and v8.
Tested links.

chore:(docs) Migrate e2e Cypress testing doc

---

change/@fluentui-react-button-9d0e8c6a-5acc-4b52-a96f-57d04ac83672.json
packages/react-components/react-button/library/src/components/MenuButton/useMenuButton.tsx

When `MenuButton` was passed in `aria-expanded` as a string, the `useMenuButtonStyles` would incorrectly apply the expanded styles even when the value was `'false'`.
`useMenuButton` normalizes the value to always be a boolean.
- Fixes #31804

fix: MenuButton is styled correctly when aria-expanded is a string

---

change/@fluentui-react-4c9ebee6-1e61-4e67-87f3-50ef560ab2dc.json
packages/react/etc/react.api.md
packages/react/src/components/ComboBox/ComboBox.tsx
packages/react/src/components/ComboBox/ComboBox.types.ts

When using `ComboBox` inside `DetailsList` arrow navigation would get stuck on `ComboBox`. This is because the code would hit [this break](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/ComboBox/ComboBox.tsx#L2264) and then [call `stopPropagation()` and `preventDefault()` on the keyboard event](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/ComboBox/ComboBox.tsx#L2271-L2272), preventing navigation.
This PR introduces a new prop allowing users to opt in to a behavior that will skip the calls to `stopPropagation()` and `preventDefault()`.
- Fixes #29885

Add 'allowParentArrowNavigation' prop to `ComboBox`.

---

change/@fluentui-react-drawer-036ac4c0-092d-474a-aed8-6d84906978f2.json
packages/react-components/react-drawer/library/src/components/DrawerFooter/DrawerFooter.test.tsx
packages/react-components/react-drawer/library/src/components/DrawerFooter/useDrawerFooter.ts
packages/react-components/react-drawer/library/src/components/DrawerHeader/DrawerHeader.test.tsx
packages/react-components/react-drawer/library/src/components/DrawerHeader/useDrawerHeader.ts

The native `<header>` and `<footer>` elements create global landmarks unless they are wrapped by a sectioning element (not just `section`, there are a few more). Right now, `dialog` does not count as a sectioning element, though it probably should.
Till it does, we should override the auto-calculated roles for the header/footer elements.
Adds `role=none`, so header/footer elements in the Drawer are given globally scoped landmark roles.
- Fixes an [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/18697)

fix(react-drawer): do not create global header/footer roles

---

change/@fluentui-react-calendar-compat-189eebe0-2fa0-4813-850d-9719b43a9490.json
change/@fluentui-react-datepicker-compat-907ec437-a124-4e97-9b54-39587f35bd3c.json
packages/react-components/react-calendar-compat/library/etc/react-calendar-compat.api.md
packages/react-components/react-calendar-compat/library/src/components/Calendar/Calendar.tsx
packages/react-components/react-calendar-compat/library/src/components/CalendarDay/CalendarDay.tsx
packages/react-components/react-calendar-compat/library/src/components/CalendarDayGrid/CalendarDayGrid.tsx
packages/react-components/react-calendar-compat/library/src/components/CalendarDayGrid/CalendarDayGrid.types.ts
packages/react-components/react-calendar-compat/library/src/components/CalendarDayGrid/CalendarGridDayCell.tsx
packages/react-components/react-calendar-compat/library/src/components/CalendarDayGrid/CalendarGridRow.tsx
packages/react-components/react-datepicker-compat/library/src/components/DatePicker/DatePicker.cy.tsx
packages/react-components/react-datepicker-compat/library/src/components/DatePicker/useDatePicker.tsx

A stray `aria-owns` from before DatePicker was modal caused the popup to be an a11y child of the hidden tree, which made it inaccessible to screen reader users and voice control users.
Note: this is not an issue in v8, since the DatePicker there is non-modal.
Removes the `aria-owns` and fixes the breaking a11y bug. Also makes a few incremental improvements, including:
- Removes the unnecessary extra group role between the dialog and the table.
- Moves the selected date & today's date string to the table's accname
- Moves `aria-hidden` for placeholder rows to the `<tr>` element from the cells, preventing empty rows from showing in the a11y tree
- Removes unnecessary `aria-hidden` from the span inside date buttons
- Fixes #31818

fix: v9 DatePicker compat popup is not hidden from the a11y tree

---

change/@fluentui-react-list-preview-50c10fe7-4982-4036-9f14-c003dd2ce068.json
packages/react-components/react-list-preview/library/etc/react-list-preview.api.md
packages/react-components/react-list-preview/library/src/components/List/List.test.tsx
packages/react-components/react-list-preview/library/src/components/ListItem/ListItem.types.ts
packages/react-components/react-list-preview/library/src/components/ListItem/useListItem.tsx
packages/react-components/react-list-preview/stories/src/List/MultipleActionsDifferentPrimary.stories.tsx
packages/react-components/react-list-preview/stories/src/List/SingleActionSelectionDifferentPrimary.stories.tsx

Previously `onAction` callback did not receive a `value` prop.
`onAction` callback receives the `value` prop as second argument.
- Fixes #31797

feat(react-list-preview): pass value to onAction callback

---

change/@fluentui-react-tree-4db6a82c-b4bf-4f92-9645-6e06a6ff519c.json
packages/react-components/react-tree/library/src/components/TreeItem/useTreeItem.tsx

Improves the strict warning from #31766
The problematic case only applies for TreeItems that contain a subtree but aren't in a parent root tree:
```tsx
<TreeItem>
<TreeItemLayout />
<Tree />
</TreeItem
```
The warning stops developers testing the layout of individual TreeItems, and there is no safe way to know if a TreeItem has a Tree as its child without parsing children.
This PR tries to detect the problematic case by parsing output DOM aswell.

patch: improve strict warning from useTreeItem

---

change/@fluentui-react-nav-preview-f6f33648-945e-41b2-a30a-7d90332d3ca8.json
packages/react-components/react-nav-preview/library/src/components/NavCategoryItem/useNavCategoryItem.tsx

Drafting off AccordionHeader, I'm adding aria-expanded to the NavCategoryItem to indicate to screen readers that it's expanded or collapsed.

fix:(react-nav-preview) Adds aria-expanded to NavCategoryItem

---

packages/react-components/react-nav-preview/stories/src/NavDrawer/NavDrawerDefault.stories.tsx
packages/react-components/react-nav-preview/stories/src/NavDrawer/NavDrawerSize.stories.tsx

The Nav hamburger buttons should have tool tips for a11y. This PR adds them.
ladders to #26649

chore:(react-nav-preview) Add tool tips to hamburgers

---

apps/public-docsite-v9/src/Concepts/Migration/FromV8/ComponentMapping.stories.mdx

This PR updates [the v8-v9 component mapping page](https://react.fluentui.dev/?path=/docs/concepts-migration-from-v8-component-mapping--page) with the latest additions / changes.

fix(docs): update v8-v9 component mapping page

---

change/@fluentui-react-nav-preview-3f2ae530-e57c-4609-8fcf-96cb742db233.json
packages/react-components/react-nav-preview/library/etc/react-nav-preview.api.md
packages/react-components/react-nav-preview/library/src/AppNode.ts
packages/react-components/react-nav-preview/library/src/NavDivider.ts
packages/react-components/react-nav-preview/library/src/components/AppNode/AppNode.test.tsx
packages/react-components/react-nav-preview/library/src/components/AppNode/AppNode.tsx
packages/react-components/react-nav-preview/library/src/components/AppNode/AppNode.types.ts
packages/react-components/react-nav-preview/library/src/components/AppNode/__snapshots__/AppNode.test.tsx.snap
packages/react-components/react-nav-preview/library/src/components/AppNode/index.ts
packages/react-components/react-nav-preview/library/src/components/AppNode/renderAppNode.tsx
packages/react-components/react-nav-preview/library/src/components/AppNode/useAppNode.ts
packages/react-components/react-nav-preview/library/src/components/AppNode/useAppNodeStyles.styles.ts
packages/react-components/react-nav-preview/library/src/components/NavDivider/NavDivider.test.tsx
packages/react-components/react-nav-preview/library/src/components/NavDivider/NavDivider.tsx
packages/react-components/react-nav-preview/library/src/components/NavDivider/NavDivider.types.ts
packages/react-components/react-nav-preview/library/src/components/NavDivider/__snapshots__/NavDivider.test.tsx.snap
packages/react-components/react-nav-preview/library/src/components/NavDivider/index.ts
packages/react-components/react-nav-preview/library/src/components/NavDivider/renderNavDivider.tsx
packages/react-components/react-nav-preview/library/src/components/NavDivider/useNavDivider.ts
packages/react-components/react-nav-preview/library/src/components/NavDivider/useNavDividerStyles.styles.ts
packages/react-components/react-nav-preview/library/src/index.ts
packages/react-components/react-nav-preview/stories/src/AppNode/AppNodeBestPractices.md
packages/react-components/react-nav-preview/stories/src/AppNode/AppNodeDefault.stories.tsx
packages/react-components/react-nav-preview/stories/src/AppNode/index.stories.tsx
packages/react-components/react-nav-preview/stories/src/NavDivider/NavDividerBestPractices.md
packages/react-components/react-nav-preview/stories/src/NavDivider/NavDividerDefault.stories.tsx
packages/react-components/react-nav-preview/stories/src/NavDivider/index.stories.tsx

Scaffolds the App Node (combination of text + icon) and NavDivider (opinionated Divider)
Result of running `yarn create-component` and commenting out the default exports in the stories to prevent publishing.

chore:(react-nav-preview) Scaffolds AppNode and NavDivider

---

docs/react-v9/contributing/new-release-process-v9-packages.md

Migrating v9 release process from the wiki to the repo.
No changes :-)

chore:(docs) Migrate v9 release process doc

---

apps/public-docsite-v9/src/DocsComponents/FluentDocsPage.stories.tsx

Addresses #26585
For sake of simplicity, I added it similar to [v8 docs](https://github.com/microsoft/fluentui/blob/master/packages/react-docsite-components/src/components/Page/sections/ImplementationSection.tsx#L71), where it was available in case if `jsonDocs` prop isn't provided.

docs: add native props message

---

change/@fluentui-web-components-d72dcdbe-ace1-4bd1-b429-2565a3ab8c39.json
packages/web-components/src/styles/partials/badge.partials.ts

Caching local variable for `spacingHorizontalXXS`
Uses the local variable directly in the css.
This is to help do CSS Hoisting, tokens should be used in CSS not outside.

chore: use tokens directly in css for badge partial

---

change/@fluentui-web-components-d7ebd73e-6662-488f-a6c8-3715eea02229.json
packages/web-components/src/menu/menu.ts

Shift+Tab was being suppressed due to the logic of menu not accounting for the trigger being focused already when the menu was closed
Shift+Tab when the menu is closed works as expected
- Fixes #

fix: ensure menu keydown logic allows shift+tab to navigate as expected

---

packages/web-components/src/drawer/drawer.stories.ts

The stories for the `<fluent-drawer>` component used a `setTimeout()` to initialize certain story functionality, but it was getting executed on every storybook page.
This PR moves the input event listener onto the `<fluent-text-input>` element for the `CustomSize` story. Additionally, I updated the types to utilize those provided by the storybook helper module.

fix(web-components): Refactor drawer stories to use Storybook decorators

---

packages/fluentui/docs/src/index.html

We were using `polyfill.io` for adding polyfills to the documentation site
We will use `cdnjs.cloudflare.com/polyfill` for adding polyfills to the documentation site instead
- Fixes [https://github.com/microsoft/fluentui/security/advisories/GHSA-3443-vgvj-vf9g](https://github.com/microsoft/fluentui/security/advisories/GHSA-3443-vgvj-vf9g)

docs: replace polyfill.io with Cloudflare equivalent

---

change/@fluentui-react-combobox-80d33447-531e-488a-bd06-4aa351ec2915.json
packages/react-components/react-combobox/library/etc/react-combobox.api.md
packages/react-components/react-combobox/library/src/components/Combobox/useCombobox.tsx
packages/react-components/react-combobox/library/src/components/Listbox/Listbox.types.ts
packages/react-components/react-combobox/library/src/components/Listbox/useListbox.ts
packages/react-components/react-combobox/library/src/utils/ComboboxBase.types.ts
packages/react-components/react-combobox/library/src/utils/useComboboxBaseState.ts

Opening the combobox focuses on the first option. While this is fine, there are use cases where the combobox opens on focus therefore moving to the first option even though the combobox might be freeform.
To allow such use cases to work correctly, this PR adds a way to disable auto focus, but leaving autofocus as default.

feat(react-combobox): Add disableAutoFocus to Combobox and Listbox for cases when the popover is open on focus

---

change/@fluentui-react-combobox-49a36618-f887-4534-a022-f6b4fd32d199.json
packages/react-components/react-combobox/library/src/utils/useComboboxPositioning.ts

When the Combobox popup is outside the bounds of the viewport, keyboard users can arrow to an option that isn't visible. Since arrowing also moves between options rather than scrolling, there isn't a good way to get the option into view.
I'm adding this specifically to Combobox (and the other related components that use the `react-combobox` hooks) because unlike Menu and other popups, it doesn't actually move keyboard focus into the popup. Arrowing to an out-of-view MenuItem will cause the page to scroll, since keyboard focus is moving out of view.
We might consider adding this by default to Menu as well, but it's more clearly needed in Combobox because of focus remaining on the trigger element.
Combobox's popup has `autoSize: true`, which forces it to confine itself to the viewport …

fix: add autoSize to Combobox positioning

---

packages/react-components/react-migration-v8-v9/stories/MenuButtonShim/index.stories.tsx

Super-simple change, updates the `ev.shiftKey` check, which previously returned true even if `shiftKey` was false :D
Fixes an ADO issue about the menu not closing with escape.

fix: onDismiss in story correctly checks for shiftKey

---

change/@fluentui-web-components-0d6c3009-cdd8-43fb-8c57-81d2866ab734.json
packages/web-components/package.json

Previously we used to use `@microsoft/fast-foundation/utilities.js` and since `fast-foundation` is now merged into `fluentui/web-components` we don't want to carry both packages, so exporting the utilities.js is needed (so bundle bloat doesn't happen) due to sideEffected packages.
This creates `@fluentui/web-components/utilities.js`

chore: make utils a package export

---

.github/workflows/create-milestone.yml

milestone action `due_on` is not proper UTC and keeps filing agains GitHub REST API
- failing run: https://github.com/microsoft/fluentui/actions/runs/9325872420/job/25673575388
- GH REST docs: https://docs.github.com/en/rest/issues/milestones?apiVersion=2022-11-28#create-a-milestone
`due_on` is valid UTC
- Fixes #

ci(.github): resolve due_on UTC time creation issues

---

docs/react-v9/contributing/patterns/basic-recomposition.md

I had to do some recomposition for the Nav. I figured I'd help others learn some lesson's I picked up along the way.
Please review for typos, grammar, correct terminology and general flow 🙂

feat:(docs) Adds pattern doc on Basic Recomposition

---

scripts/prettier/src/prettier-helpers.js

we don't escape special characters when passing file list to prettier bin
we properly escape special characters when passing file list to prettier bin
- Unblocks https://github.com/microsoft/fluentui/pull/31202

fix(scripts-prettier): escape file names that are being passed to prettier bin via shell

---

change/@fluentui-web-components-145140b4-12da-4153-93ce-be8aa02f191b.json
packages/web-components/.storybook/preview.mjs
packages/web-components/src/_docs/developer/polyfilling.stories.mdx
packages/web-components/src/menu-item/menu-item.styles.ts

Submenus were aligning to `center` in Firefox. 
- Move submenu positioning to `start`
- Add docs for polyfilling HTML popover
- Fixes #

fix(web-components): fix menu positioning in firefox

---

change/@fluentui-web-components-8868e960-0d34-4f03-a229-48c64055ce4b.json
packages/web-components/src/text-input/text-input.spec.ts
packages/web-components/src/text-input/text-input.stories.ts
packages/web-components/src/text-input/text-input.ts

The `focusin` and `click` handlers don't allow events from slotted `start` and `end` elements to be handled.
This PR updates `focusinHandler` and `clickHandler` methods to return `true` so FAST's event binding doesn't automatically prevent default. This should allow events from start/end slotted elements to be focusable and clickable.
- Fixes #31902

fix(web-components): slotted elements within fluent-text-input can't be focused

---

change/@fluentui-web-components-e417861e-ef1b-4b4f-8c25-fef57cda85d9.json
packages/web-components/docs/api-report.md
packages/web-components/src/menu/menu.spec.ts
packages/web-components/src/menu/menu.stories.ts
packages/web-components/src/menu/menu.ts

Opening the menu component and selecting a `menuitem` with `enterkey` should trigger the menu to close unless it's a `menuitemradio` or `menuitemcheckbox`.
- Make `Menu` listen for the `change` event emitted by [menu-item.ts#L220](https://github.com/microsoft/fluentui/blob/master/packages/web-components/src/menu-item/menu-item.ts#L213-L221)
- Add tests 👍👍👍
- Fixes #31850 
Adding @mlijanto as a reviewer to verify fix for upstream usage.

fix(web-components): fix enterkey interaction on menu

---

change/@fluentui-web-components-5704d052-a860-40bb-b956-9b445a49e171.json
packages/web-components/src/theme/set-theme.ts

The default theme was not being set in Firefox. Firefox currently `SUPPORTS_ADOPTED_STYLESHEETS` but does not `SUPPORTS_REGISTER_PROPERTY`. The CSSStylesheet being adopted on the first pass was an empty stylesheet. And because there were no tokens registered, styles weren't applied.
This change will always update the stylesheet to the new theme and then adopt the stylesheet if it hasn't been adopted already.
- Fixes #

fix(web-components): fix for setTheme in Firefox

---

apps/vr-tests-web-components/src/stories/accordion/accordion.stories.tsx
change/@fluentui-web-components-bfd68275-8db7-4591-a7d9-3adfcc8ba806.json
packages/web-components/docs/api-report.md
packages/web-components/src/accordion-item/README.md
packages/web-components/src/accordion-item/accordion-item.options.ts
packages/web-components/src/accordion-item/accordion-item.spec.ts
packages/web-components/src/accordion-item/accordion-item.styles.ts
packages/web-components/src/accordion-item/accordion-item.template.ts
packages/web-components/src/accordion-item/accordion-item.ts
packages/web-components/src/accordion-item/index.ts
packages/web-components/src/accordion/accordion.spec.ts
packages/web-components/src/accordion/accordion.stories.ts
packages/web-components/src/accordion/accordion.ts
packages/web-components/src/index.ts
packages/web-components/src/styles/states/index.ts

Current accordion has unneeded and confusing features like `focusgroup` and extra slots and grouping divs inside template.
- Removed focusgroup behavior from Accordion per a11y review and parity with React implementation
- Flattened `AccordionItem` template
- Removed `end` slot in favor of consumer-supplied CSS
- Refactored `AccordionItem` CSS
- Renamed slots to be more spec-like
- Fixes #

refactor(web-components): cleanup accordion and update to elementInternals for state

---

.github/CODEOWNERS

Updates CODEOWNERS on `react-tabs`, #31581 added `teams-prg` by a mistake.
/cc @Hotell

chore: update CODEOWNERS on react-tabs

---

scripts/storybook/src/utils.js
scripts/storybook/src/utils.spec.js

> introduces https://github.com/microsoft/fluentui/pull/31893
sub-package stories are not rendered within public-docsite-v9 storybook
sub-package stories are rendered within public-docsite-v9 storybook
- Follows https://github.com/microsoft/fluentui/pull/31937

fix(scripts-storybook): make getPackageStoriesGlob properly resolve stories paths based on new project.json#name pattern

---

change/@fluentui-react-dbe02eba-3a06-40c9-8678-e553a2c2ff71.json
packages/react/src/components/Spinner/Spinner.styles.tsx
packages/react/src/components/Spinner/__snapshots__/Spinner.test.tsx.snap

When overriding a CSS shorthand that contains a CSS custom property the visuals render correctly but the actual styles injected into the CSSStyleSheet seem to be invalid.
This means that things appear correct in the primary window but when styles are copied to a child window they are broken.
[Repro example](https://stackblitz.com/edit/stackblitz-starters-ky5wha?file=index.html,script.js)
NOTE the button at the bottom of the example.
To workaround the issue all the `border-*-color` properties are written out in longhand form.

fix: update Spinner styles to work around styling bug

---

change/@fluentui-web-components-5a2991af-51c1-4e3b-b0f8-5d19cbaa2a13.json
packages/web-components/docs/api-report.md
packages/web-components/src/menu-item/menu-item.styles.ts
packages/web-components/src/menu-item/menu-item.template.ts
packages/web-components/src/menu-item/menu-item.ts
packages/web-components/src/menu-list/menu-list.spec.ts
packages/web-components/src/menu-list/menu-list.template.ts
packages/web-components/src/menu-list/menu-list.ts
packages/web-components/src/menu/menu.ts

ARIA was bound in the template and states were based on attributes
Migrates to use Element Internals for custom states and ARIA
- Fixes #

feat: convert menu list and items to use element internals

---

change/@fluentui-react-tree-12dac24a-04f5-472b-b3b6-d1fd3d82c7b4.json
packages/react-components/react-tree/library/src/components/FlatTree/FlatTree.cy.tsx
packages/react-components/react-tree/library/src/components/FlatTree/useFlatControllableCheckedItems.ts

1. ensures that `defaultState` is not provided at the same time as `state` on `useControllableState` invocation, as it'll console error https://github.com/microsoft/fluentui/pull/31461
- Fixes #

bugfix(react-tree): defaultCheckedItems conflicts with checkedItems

---

tools/workspace-plugin/src/generators/bundle-size-configuration/files/bundle-size/index.fixture.js.template
tools/workspace-plugin/src/generators/bundle-size-configuration/generator.spec.ts
tools/workspace-plugin/src/generators/bundle-size-configuration/generator.ts
tools/workspace-plugin/src/generators/cypress-component-configuration/index.spec.ts
tools/workspace-plugin/src/generators/migrate-fixed-versions/README.md
tools/workspace-plugin/src/generators/migrate-fixed-versions/index.spec.ts
tools/workspace-plugin/src/generators/migrate-fixed-versions/index.ts
tools/workspace-plugin/src/generators/prepare-initial-release/index.spec.ts
tools/workspace-plugin/src/generators/prepare-initial-release/index.ts
tools/workspace-plugin/src/generators/rc-caret/README.md
tools/workspace-plugin/src/generators/rc-caret/index.spec.ts
tools/workspace-plugin/src/generators/react-component/index.spec.ts
tools/workspace-plugin/src/generators/react-component/index.ts
tools/workspace-plugin/src/generators/react-library/files/LICENSE__tmpl__
tools/workspace-plugin/src/generators/react-library/files/README.md__tmpl__
tools/workspace-plugin/src/generators/react-library/files/docs/Spec.md__tmpl__
tools/workspace-plugin/src/generators/react-library/files/jest.config.js__tmpl__
tools/workspace-plugin/src/generators/react-library/files/package.json__tmpl__
tools/workspace-plugin/src/generators/react-library/index.spec.ts
tools/workspace-plugin/src/generators/react-library/index.ts
tools/workspace-plugin/src/generators/recipe-generator/index.spec.ts
tools/workspace-plugin/src/generators/recipe-generator/index.ts
tools/workspace-plugin/src/generators/split-library-in-two/generator.spec.ts
tools/workspace-plugin/src/generators/split-library-in-two/generator.ts
tools/workspace-plugin/src/generators/version-bump/README.md
tools/workspace-plugin/src/generators/version-bump/index.spec.ts
tools/workspace-plugin/src/generators/version-bump/index.ts
tools/workspace-plugin/src/generators/version-bump/schema.json
tools/workspace-plugin/src/generators/version-bump/schema.ts

> introduced https://github.com/microsoft/fluentui/pull/31893
all workspace generators are broken
all workspace generators work
- Follows https://github.com/microsoft/fluentui/pull/31937

fix(workspace-tools): make generators work with new project.json#name pattern which doesn't include npmScope

---

docs/react-v9/contributing/component-implementation-guide.md

Simply fixes broken example links in [component-implementation-guide](https://github.com/microsoft/fluentui/blob/master/docs/react-v9/contributing/component-implementation-guide.md) after #31579, plus a few others that had wrong path to old wiki

docs(implementation-guide): fix incorrect example links

---

change/@fluentui-react-components-ff5aa06c-fdea-44ae-81a7-0fedc3f30a15.json
change/@fluentui-react-motion-58a20a26-2ffb-45e0-965d-0a344d604779.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts
packages/react-components/react-motion/library/etc/react-motion.api.md
packages/react-components/react-motion/library/src/factories/createPresenceComponent.ts
packages/react-components/react-motion/library/src/factories/createPresenceComponentVariant.test.tsx
packages/react-components/react-motion/library/src/factories/createPresenceComponentVariant.ts
packages/react-components/react-motion/library/src/index.ts

PR adds `createPresenceComponentVariant()` that allows to customize `easing` & `duration` of a motion component created with `createPresenceComponent()`.
```ts
import { createPresenceComponentVariant } from '@fluentui/react-components';
const PresenceComponent = createPresenceComponent(/* --- */);
const PresenceVariant = createPresenceComponentVariant(PresenceComponent, {
all: { duration: 500, easing: 'ease-in-out' },
});
```

feat(motion): add createPresenceComponentVariant() factory

---

change/@fluentui-react-skeleton-b2554d76-ec3a-4c57-bd18-04e351cd08ba.json
packages/react-components/react-skeleton/library/src/components/Skeleton/Skeleton.test.tsx
packages/react-components/react-skeleton/library/src/components/Skeleton/__snapshots__/Skeleton.test.tsx.snap
packages/react-components/react-skeleton/library/src/components/Skeleton/useSkeleton.ts
packages/react-components/react-skeleton/stories/src/Skeleton/SkeletonAnimation.stories.tsx
packages/react-components/react-skeleton/stories/src/Skeleton/SkeletonAppearance.stories.tsx
packages/react-components/react-skeleton/stories/src/Skeleton/SkeletonDefault.stories.tsx
packages/react-components/react-skeleton/stories/src/Skeleton/SkeletonItemShape.stories.tsx
packages/react-components/react-skeleton/stories/src/Skeleton/SkeletonItemSize.stories.tsx
packages/react-components/react-skeleton/stories/src/Skeleton/SkeletonRow.stories.tsx

The `Skeleton` 'aria-label' default value is hardcoded in English, which can mess with locale support. This PR removes 'aria-label' as a default value and updates the `Skeleton` stories to contain 'aria-label'.
Fixes #31961

chore: remove default 'aria-label' value from Skeleton

---

change/@fluentui-react-utilities-eac70f99-2c2a-4360-930d-3c926b0b4755.json
packages/react-components/react-utilities/etc/react-utilities.api.md
packages/react-components/react-utilities/src/hooks/useMergedRefs.test.tsx
packages/react-components/react-utilities/src/hooks/useMergedRefs.ts

`useMergedRefs` does not support `null` as a proper value for its callback, although it is a possible value to be provided to a reference in React.
This generates two problems:
1. you can't pass `null` directly to the callback https://github.com/microsoft/fluentui/pull/31951/files#diff-d524dc66988c13bc9d0c1a74557845b89dd19656e8e3e90f5292d2d446fe070aR81-R86
2. you can't use it to assign into an union due to conflict on types https://github.com/microsoft/fluentui/pull/31951/files#diff-d524dc66988c13bc9d0c1a74557845b89dd19656e8e3e90f5292d2d446fe070aR70-R79
1. Adds `null` as a possible value for the callback reference, equivalent to `React.RefCallback`
2. Adds tests to ensure both breaking cases are passing now
- Fixes #

bugfix(react-utilities): fix useMergedRefs signature to include null

---

change/@fluentui-react-tabster-7873879f-bbad-4e1a-ada9-c76ac1dc61d3.json
packages/react-components/react-tabster/package.json
yarn.lock

- CHANGELOG https://github.com/microsoft/tabster/blob/master/CHANGELOG.md#v801
- including fix for https://github.com/microsoft/fluentui/issues/30556.

fix(react-tabster): bump tabster to 8.0.1 to fix memorized elements focusing

---

docs/react-v9/contributing/unstable-hooks.md

We've heard from partners that there is a lot of confusion over the `_unstable` suffix attached to many of our APIs. 
It's a source of friction and hesitation in adopting v9.
We burn a lot of time re-assuring folks that our `_unstable` API's are in fact stable.
This doc provides a vehicle to speed up and re-enforce that. Hopefully we can point people to it to save ourselves time and convince folks that we won't break `_unstable` APIs in stable packages.

chore:(docs) Adds doc explaining _unstable suffix

---

azure-pipelines.release-fluentui.yml

- service connection is not compliant and disabled
- new [service connection](https://uifabric.visualstudio.com/UI%20Fabric/_settings/adminservices?resourceId=727b1090-e447-4540-9694-3d75b5a557a6) is created and is compliant
**NOTE**: the pipeline has not been tested yet and will be done so after this is merged. If things don't work as expected, work to remedy will be done in the background through Azure
- Fixes #31906

ci(v0-release): use new service connection which uses compliant Workload Identity Federation

---

change/@fluentui-web-components-198bc628-0ffa-41a6-a30f-b159efd70210.json
packages/web-components/src/menu-item/menu-item.styles.ts

In an attempt to fix submenu fallback positioning for non-anchor-supported browsers (Safari/Firefox), I broke positioning in Edge/Chrome.
See submenu in last example in Edge/Chrome: https://web-components.fluentui.dev/?path=/docs/components-menu--menu
This scopes the position fallback position rule needed for older browsers into an `@supports not` rule to fix the regression in Edge/Chrome while still providing support to non-Anchor browsers. 
- Fixes #

fix(web-components): scope submenu fallback positioning to non-anchor browsers only

---

change/@fluentui-web-components-4354dafd-fa30-42db-9554-3dacbce93e14.json
packages/web-components/src/button/button.template.ts
packages/web-components/src/button/button.ts
packages/web-components/src/compound-button/compound-button.template.ts

fix: override tabindex attribute and default to 0

---

apps/public-docsite-v9/src/DocsComponents/FluentDocsPage.stories.tsx

fix(docsite-v9): fix layout of description

---

change/@fluentui-web-components-7af277b6-1e65-46b2-89d4-412861c9d3bb.json
packages/web-components/src/drawer-body/drawer-body.ts
packages/web-components/src/drawer/drawer.stories.ts

Found a visual regression for radio inputs on the Drawer component. 
View issue: https://web-components.fluentui.dev/?path=/docs/components-drawer--drawer
- Updates the story to use the new RadioGroup syntax.
- Refactors all Drawer stories into a single story with more control options.
1. Rolling up the stories into a single story loses a bit of context, how much context do we need? 
2. If we need more context, where should that live?
> [!NOTE]
> This exposes a defect where you can't use labels to select a radioitem inside a drawer. Unclear if this is a problem with Drawer or with RadioGroup. I filed a separate issue for that: https://github.com/microsoft/fluentui/issues/31992

chore(web-components): cleanup drawer storybook

---

change/@fluentui-react-dialog-a88dcd08-5fd2-41fa-94e6-c6175ae4980e.json
packages/react-components/react-dialog/library/etc/react-dialog.api.md
packages/react-components/react-dialog/library/src/components/Dialog/Dialog.types.ts
packages/react-components/react-dialog/library/src/components/Dialog/renderDialog.tsx
packages/react-components/react-dialog/library/src/components/Dialog/useDialog.ts
packages/react-components/react-dialog/library/src/components/DialogSurface/DialogSurface.types.ts
packages/react-components/react-dialog/library/src/components/DialogSurface/renderDialogSurface.tsx
packages/react-components/react-dialog/library/src/components/DialogSurface/useDialogSurface.ts
packages/react-components/react-dialog/library/src/components/DialogSurface/useDialogSurfaceStyles.styles.ts

`Dialog` & `DialogSurface` have built-in motion, but it's impossible to customize it.
- `Dialog` gets `surfaceMotion` slot
- `DialogSurface` gets `backdropMotion` slot
Motion slots allow to customize or replace built-in motion, see examples in #31984.
- Fixes #30603
- Fixes #31129

feat: add motion slots to Dialog

---

change/@fluentui-react-motion-components-preview-b1579edb-605b-4bec-a5dd-2d858369e7aa.json
packages/react-components/react-motion-components-preview/library/etc/react-motion-components-preview.api.md
packages/react-components/react-motion-components-preview/library/src/components/Scale/Scale.test.ts
packages/react-components/react-motion-components-preview/library/src/components/Scale/Scale.ts
packages/react-components/react-motion-components-preview/library/src/components/Scale/index.ts
packages/react-components/react-motion-components-preview/library/src/index.ts
packages/react-components/react-motion-components-preview/stories/src/Scale/ScaleCustomization.stories.md
packages/react-components/react-motion-components-preview/stories/src/Scale/ScaleCustomization.stories.tsx
packages/react-components/react-motion-components-preview/stories/src/Scale/ScaleDefault.stories.tsx
packages/react-components/react-motion-components-preview/stories/src/Scale/ScaleDescription.md
packages/react-components/react-motion-components-preview/stories/src/Scale/ScaleExaggerated.stories.md
packages/react-components/react-motion-components-preview/stories/src/Scale/ScaleExaggerated.stories.tsx
packages/react-components/react-motion-components-preview/stories/src/Scale/ScaleSnappy.stories.md
packages/react-components/react-motion-components-preview/stories/src/Scale/ScaleSnappy.stories.tsx
packages/react-components/react-motion-components-preview/stories/src/Scale/index.stories.ts

Fixes #32017.
- Implemented `Scale` component in `react-motion-components-preview`
- Added unit tests for `Scale` component
- Created stories for different scenarios including Default, Exaggerated, Snappy and Custom.
- Enhanced index and utility files to support new component.
- Documented usage and configuration in Storybook
PR adds Scale motion component:
```tsx
import { Scale } from '@fluentui/react-motion-components-preview';
function Component({ visible }) {
return (
<Scale visible={visible}>
<div style={{ background: 'lightblue' }}>Content</div>
</Scale>
);
}
```
The `Scale` component manages content presence, using scale in/out.

feat(motion): add Scale motion component

---

.github/workflows/check-tooling.yml
change/@fluentui-react-jsx-runtime-b0f83b29-f3d8-4f8b-89c9-75e48160f4cc.json
packages/react-components/react-jsx-runtime/package.json
scripts/tasks/src/api-extractor.ts
tools/workspace-plugin/src/generators/bundle-size-configuration/generator.spec.ts
tools/workspace-plugin/src/generators/bundle-size-configuration/generator.ts
tools/workspace-plugin/src/generators/bundle-size-configuration/schema.d.ts
tools/workspace-plugin/src/generators/bundle-size-configuration/schema.json
tools/workspace-plugin/src/generators/cypress-component-configuration/schema.json
tools/workspace-plugin/src/generators/prepare-initial-release/schema.json
tools/workspace-plugin/src/generators/react-component/files/component/__componentName__.tsx__tmpl__
tools/workspace-plugin/src/generators/react-component/index.spec.ts
tools/workspace-plugin/src/generators/react-component/index.ts
tools/workspace-plugin/src/generators/react-library/index.spec.ts
tools/workspace-plugin/src/generators/react-library/index.ts
tools/workspace-plugin/src/generators/split-library-in-two/generator.ts

- v9 package implementation automation flows are failing on Windows Shell ( PowerShell, cmd.exe )
- Fixes
-  windows path resolution issues within split-library-in-two generator
- uses `lage build` instead of `lage generate-api` in order to properly build assets after generator execution
- Feats
- unifies generator options to use `project` when referencing project name instead of generic/not-explicit `name`
- adds CI GHA job to test most common DEV flow on windows and linux
- introduces two new "private" variables prefixed and suffixed with `__` as part of our tooling logic in order to make integration tests for dev flow pass on ci.
**v9 flow update**
- updates `react-component` generation to not add global style hook overrides - that is responsibility of component author after promoting …

ci(.github): introduce check-tooling CI pipeline

---

change/@fluentui-react-cc5ae7ec-1f14-415d-915b-88de6d5cb7f0.json
packages/react/src/utilities/dom.ts

useWindowEx/useDocumentEx (and related methods) weren't short-circuit returning the value of the useWindow/useDocument hooks 
useWindowEx/etc now return the WindowProvider value (if set), window (if defined), or undefined (in that order). 
- Fixes #31929

Fix for WindowProvider utilities always returning window/document/undefined

---

change/@fluentui-web-components-9db7a86a-2608-4f2d-aa56-13b248a527df.json
packages/web-components/src/field/field.stories.ts
packages/web-components/src/field/field.styles.ts
packages/web-components/src/radio-group/radio-group.styles.ts

The `fluent-field` had padding baked in which goes against the component libraries principles and created awkward styling challenges for the end user.
Remove any paddings or margins from the `:host` element
- Fixes #

Fix: Removes padding from `fluent-field` host element

---

change/@fluentui-react-31dc521a-eeaf-47a8-b020-ffb9b3a9db8d.json
packages/react/src/components/ContextualMenu/ContextualMenu.test.tsx
packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.tsx

Because `item.onClick` was not passed through to the item data on the split menu item's primary button, it was not called in `onCheckmarkClick`. This resulted in the default menu-level `onItemClick` was called, and dismissed the menu instead of toggling selection:
https://github.com/microsoft/fluentui/assets/3819570/73644f29-a3f3-455e-b76e-194b193e8561
`onCheckmarkClick` calls `item.onClick` when available, still defaulting to `onItemClick` when not.
- Fixes #31817

fix(ContextualMenu): item.onClick is called when SplitMenuItem checkmark is clicked

---

docs/react-v9/contributing/rfcs/shared/build-system/stop-styles-transforms.md

The RFC proposes halting the pre-processing of styles in `@fluentui/react-components` to address CSS clashes observed when apps are bundled into multiple separate bundles.
Two options are presented:
- stopping pre-processing entirely, requiring consuming apps to handle it (breaking change) 
- shipping ESM output with unprocessed styles alongside pre-processed styles, maintaining backward compatibility, but increasing complexity and package size

RFC: Stop pre-processing styles with Griffel in `@fluentui/react-components`

---

change/@fluentui-web-components-7f113354-6b0a-4b3d-8b04-92de3da35083.json
packages/web-components/docs/api-report.md
packages/web-components/src/anchor-button/anchor-button.ts
packages/web-components/src/button/button.ts

Style specific parts of Button's API were bundled into the class. 
Style specific parts of Button's API are kept in the `Button` class while functional parts of the API are moved into a new `BaseButton` class. This allows consumers to opt out of style specifics they may not need.
- Fixes #

chore(web-components): [button] move style related api out of base class

---

azure-pipelines-ci.yml

codeql runs into timeouts every/every 2nd master pipeline run
codeql should perform drastically faster not failing CI
- Fixes #

ci: improve codeql performance by not analyzing sourcefiles that cause infinte loops in monorepo situation

---

packages/keyboard-key/jest.config.js
scripts/gulp/src/plugins/gulp-jest.ts
scripts/gulp/src/tasks/test-unit.ts
scripts/jest/src/environment.js
scripts/jest/src/jest.preset.v0.js
scripts/jest/src/jest.preset.v8.js
scripts/jest/src/shared.js
scripts/tasks/src/jest.ts

- v0,v8 have different jest setups in terms of leveraging threads on CI
- some projects run code-coverage in CI which slows down test execution by 10%
- v0,v8 uses unified `maxWorkers` setup on CI, (based on measurements it looks like ideal setup for our current CI resources )
- 💡 what about v9? 
- in my initial experiments this was also enabled for v9. looks like until all perf improvements will land this will cause CI to run over 1 hour - so not part of this PR
- code-coverage has been disabled
**Speed metrics:**
Using code-coverage (react-northstar - up to 10% slowdown)
| Run type        | time  | command                                                                    |
| --------------- | ----- | -------------------------------------------------------------------------- |
| current …

chore: unify jest maxWorkers usage on CI and turn off code coverage

---

change/@fluentui-web-components-1dc0a126-f4ed-4776-b348-eaaef1b65a6a.json
packages/web-components/src/spinner/spinner.styles.ts
packages/web-components/src/spinner/spinner.template.ts

A PR to change how we're animating the Spinner component in Fluent Web Components
It was reported this week that the Web Component spinner was animating on the main thread and not the compositor. 
Convert SVG animation to `div` animation à la the React implementation.
- Moves all spinner animation off the main thread to the compositor
- 120 layouts per second → 0 layouts per second
- 120 style recalcs per second → 0 style recalcs per second (at rest)
- No more paint flashes in `DevTools > More Tools > Rendering`
- 5~9% CPU usage → 0.2% CPU usage
- Fixes #

fix(web-components): move spinner animation off of mainthread

---

change/@fluentui-web-components-b3c312bc-fbd8-441b-94e7-fece2be539a3.json
packages/web-components/docs/api-report.md
packages/web-components/src/button/index.ts
packages/web-components/src/divider/divider.ts
packages/web-components/src/divider/index.ts
packages/web-components/src/index.ts

Style and layout API was bundled into one `Divider` class
Abstracts out Style and layout API and create `BaseDivider` class.
This PR also adds the `BaseButton` export to the `web-components/src/index` file
- Fixes #

Chore: Create Divider base class to abstract out style and layout specific api

---

change/@fluentui-eslint-plugin-c622c77c-61e2-4433-b4cf-da2ad0984040.json
change/@fluentui-react-utilities-8376a788-0cd7-4976-b302-c88844a11938.json
packages/eslint-plugin/src/rules/ban-instanceof-html-element/index.js
packages/eslint-plugin/src/rules/ban-instanceof-html-element/types.d.ts

1. removes dependency on `"@fluentui/react-utilities/src/utils/isHTMLElement"` file from `ban-instanceof-html-element` eslint rule
- Fixes #

chore(eslint-plugin): removes type dependency on @fluentui/react-utilities internals in ban-instanceof-html-element rule

---

change/@fluentui-react-motion-6948133f-0a73-49c2-9916-32dd176969ae.json
packages/react-components/react-motion/library/src/factories/createMotionComponent.test.tsx
packages/react-components/react-motion/library/src/factories/createPresenceComponent-jest.test.tsx
packages/react-components/react-motion/library/src/factories/createPresenceComponent-node.test.tsx
packages/react-components/react-motion/library/src/factories/createPresenceComponent.test.tsx
packages/react-components/react-motion/library/src/hooks/useAnimateAtoms-node.test.tsx
packages/react-components/react-motion/library/src/hooks/useAnimateAtoms.ts

`useAnimateAtoms()` checks for `win.Element.prototype.animate`. This might cause issues as it's not the same as `element.animate()`.
`useAnimateAtoms()` checks for `element.animate()`.
Fixes #32025.

fix(motion): improve Web Animations API detection in tests

---

apps/vr-tests-react-components/.storybook/preview.js
packages/react-components/react-storybook-addon/etc/react-storybook-addon.api.md
packages/react-components/react-storybook-addon/src/decorators/withAriaLive.tsx
packages/react-components/react-storybook-addon/src/decorators/withFluentProvider.tsx
packages/react-components/react-storybook-addon/src/decorators/withReactStrictMode.tsx
packages/react-components/react-storybook-addon/src/hooks.ts
packages/react-components/react-storybook-addon/src/utils/isDecoratorDisabled.ts

#31794 added a new decorator `withAriaLive()`. That decorator has conditional rendering:
https://github.com/microsoft/fluentui/blob/1c2c2003bff234ce6a4a043453479889c153a4b1/packages/react-components/react-storybook-addon/src/decorators/withAriaLive.tsx#L16
The problem is that it's implemented according to Storybook 6 docs and stories as a function:
https://github.com/microsoft/fluentui/blob/1c2c2003bff234ce6a4a043453479889c153a4b1/packages/react-components/react-storybook-addon/src/decorators/withAriaLive.tsx#L6
That causes an issue with a conditional rendering due effect order:
```
- useEffect: in story (as `withAriaLive()` call a function) [RENDER 1]
- useEffect: AriaLiveWrapper (mount) [RENDER 1]
```
This issue breaks stories that rely on `useEffect(fn, [])` as they are executed in …

fix(react-storybook-addon): transform decorator to function in withAriaLive()

---

change/@fluentui-web-components-43000c2b-1b77-4f30-ae7c-d15355739430.json
packages/web-components/docs/api-report.md
packages/web-components/src/index.ts
packages/web-components/src/progress-bar/index.ts
packages/web-components/src/progress-bar/progress-bar.ts

Style and layout API was bundled into one `ProgressBar` class
Abstracts out style and layout API and create `BaseProgressBar` class.
- Fixes #

[Chore]: Create Progress Bar base class to abstract out style and layout specific api.

---

change/@fluentui-web-components-b624c7d1-3e25-45ac-9f46-c6d808bbadfb.json
packages/web-components/docs/api-report.md
packages/web-components/src/index.ts
packages/web-components/src/spinner/index.ts
packages/web-components/src/spinner/spinner.ts

Style and layout API was bundled into one `Spinner` class
Abstracts out style and layout API and creates `BaseSpinner` class.
- Fixes #

[Chore]: Create Spinner base class to abstract out style and layout specific api.

---

change/@fluentui-web-components-664a860d-0606-46e5-9e2d-c1d7508e2e62.json
packages/web-components/docs/api-report.md
packages/web-components/src/index.ts
packages/web-components/src/theme/index.ts
packages/web-components/src/theme/set-theme.ts

The `theme` argument in `setTheme(theme)` is required to be the `Theme` type from `@fluentui/tokens`.
In order to allow custom tokens to be set in the same mechanism, we relax this type requirement, so product teams can extend and override existing themes with their own tokens.
- Fixes #

feat(web-components): relax setTheme() argument type to allow custom tokens

---

change/@fluentui-web-components-9f5b2454-7f3e-45fc-90f2-c8b18aaefa4a.json
packages/web-components/docs/api-report.md
packages/web-components/src/index.ts
packages/web-components/src/text-input/index.ts
packages/web-components/src/text-input/text-input.ts

Style and layout API was bundled into one `TextInput` class
Abstracts out style and layout API and creates `BaseTextInput` class.
- Fixes #

[chore]: create base class for text input and remove style and layout specific api

---

change/@fluentui-web-components-8019914d-618b-49e1-88de-c5249d5206f3.json
packages/web-components/docs/api-report.md
packages/web-components/src/avatar/avatar.ts
packages/web-components/src/avatar/index.ts
packages/web-components/src/index.ts

Style and layout API was bundled into one `Avatar` class.
Abstracts out style and layout API and creates `BaseAvatar` class.
`size` was purposively left out of the refactor because it currently is tightly coupled to `initials` and `name`.  Linking an issue to potentially refactor `avatar` to not couple those attributes together if we feel its necessary at a later date.
#32082
- Fixes #

[chore]: create base class for avatar and remove style and layout specific api

---

change/@fluentui-web-components-79917b03-962f-47a5-b0ec-a749ac9331c4.json
packages/web-components/docs/api-report.md
packages/web-components/src/accordion-item/accordion-item.ts
packages/web-components/src/accordion-item/index.ts
packages/web-components/src/index.ts

Style and layout API was bundled into one `AccordionItem` class.
Abstracts out style and layout API and creates `AccordionItem` class.
- Fixes #

[chore]: create base class for accordion item and remove style and layout specific api

---

jest.preset.js
scripts/jest/src/environment.js
scripts/jest/src/jest.preset.v0.js
scripts/jest/src/jest.preset.v8.js
scripts/jest/src/shared.js

We use most optimal setting for [`maxWorkers`](https://jestjs.io/docs/configuration#maxworkers-number--string) tested on various environments to gather the most optimal speed
> `lage test`
| Before | After |
|--------|--------|
| 15m 52s | 13m 14s / **𝚫 17% FASTER** |
> `nx run-many -t test -p tag:vNext --exclude 'tag:tools,apps/**'` 
| Before | After |
|--------|--------|
| 7m 15s | 4m 25s / **𝚫 40% FASTER** |
> `nx run-many -t test -p tag:v8 --exclude 'tag:vNext,apps/**'`
| Before | After |
|--------|--------|
| 2m 39s | 2m 16s / **𝚫 15% FASTER** |
> `nx run-many -t test -p tag:react-northstar --exclude 'tag:vNext,apps/**'`
| Before | After |
|--------|--------|
| 4m 44s | 4m 27s / **𝚫 6% FASTER** |
- Follows 
- https://github.com/microsoft/fluentui/pull/27680
- …

chore: improve jest speed on both local and CI

---

change/@fluentui-web-components-a4240e2c-3729-40ec-b1b1-ed2aec906127.json
packages/web-components/docs/api-report.md
packages/web-components/src/avatar/avatar.ts

`generteInitials` referenced `size` and was tightly coupled with `name` and `initial` however it was only used in the template.
Since `generteInitials` was only used in the template it's easy for us to move it out of the base class along with `size` this takes a lot of dead css out of the base set of styles. `color` is also move from the base class.
- Fixes #32082

[chore]: [avatar] move size, color and generate initials out of base class

---

azure-pipelines.vrt-baseline.yml
azure-pipelines.vrt-pr.yml
package.json
yarn.lock

- bumps `vr-approval-cli` to latest `0.4.5` and uses new `create-policy` API in VR PR pipelines which removes the need for passing client secrets
- cleans up variable names and removes `_NEW` postfix (actual variable value changes have been applied in the pipeline behind the scenes)
- Follows #31997

ci(vrt): bump vr-approval-cli to 0.4.5 and use new create policy api

---

change/@fluentui-react-search-ef1e9132-0d99-40b3-8598-04d52166921f.json
packages/react-components/react-search/library/src/components/SearchBox/useSearchBox.tsx
packages/react-components/react-search/library/src/components/SearchBox/useSearchBoxStyles.styles.ts

Padding was applied on the root therefore shortening the hit target and leaving 20px of dead space. 
I also noticed that a 14px padding was added to the content after even when it is hidden.
Padding is applied to the input instead when there's no content after to allow clicking and triggering focus.
only add the padding to the content after when it's visible.
- Fixes #32014

fix(react-search): Expand hit target when there's no content after

---

change/@fluentui-react-positioning-2c2ce771-85d7-4485-9269-448fac6cdda2.json
packages/react-components/react-positioning/etc/react-positioning.api.md
packages/react-components/react-positioning/src/createArrowStyles.ts

An arrow `div` itself renders a box with `border-radius` on one of edges.
This box is positioned in a way that it overlap with a border and will prevent appearing any "crashed angles".
---
On before `clip-path` is used to produce a proper triangle:
An `div` also uses [`background-clip`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip) that ensures that `background` from it won't be under a border on `::before` (to ensure that background will not appear on edges):
Fixes #32093.

fix(positioning): improve arrow styles implementation

---

change/@fluentui-react-accordion-67ff3ccc-c9c6-47c5-9a09-68e6d9bfe110.json
packages/react-components/react-accordion/library/etc/react-accordion.api.md
packages/react-components/react-accordion/library/package.json
packages/react-components/react-accordion/library/src/components/AccordionHeader/__snapshots__/AccordionHeader.test.tsx.snap
packages/react-components/react-accordion/library/src/components/AccordionHeader/useAccordionHeader.tsx
packages/react-components/react-accordion/library/src/components/AccordionPanel/AccordionPanel.types.ts
packages/react-components/react-accordion/library/src/components/AccordionPanel/renderAccordionPanel.tsx
packages/react-components/react-accordion/library/src/components/AccordionPanel/useAccordionPanel.ts
packages/react-components/react-accordion/library/src/components/AccordionPanel/useAccordionPanelStyles.styles.ts

- Updated dependencies in `package.json`
- Enhanced `useAccordionHeader.tsx` for collapse motion
- Added `AccordionMotion.ts`
- Updated types and rendering logic in Accordion components
- Styled `useAccordionPanelStyles.styles.ts` for animations
- Created stories custom motion Accordion
`AccordionPanel` didn't have a collapse animation
- `AccordionPanel` gets `collapseMotion` slot
Motion slots allow to customize or replace built-in motion, see examples in #31984.
- Fixes #32085

feat(motion): add collapse motion for Accordion

---

.devops/templates/runpublishvrscreenshot.yml
azure-pipelines.vrt-pr.yml

- moves `create-policy` and `Run fluentui-screenshotdiff` steps to `runpublishvrscreenshot` template to reduce duplication
- Follows #32110

ci(vrt): move VRT steps to runpublishvrscreenshot template to reduce duplication

---

apps/public-docsite-v9/package.json
change/@fluentui-react-carousel-preview-75862e4b-2f1a-48ba-9ae7-ea7011d5e40a.json
packages/react-components/react-carousel-preview/library/package.json

React-Carousel-Preview was a private package.
React-Carousel-Preview is now a public package that can be consumed and appears in public storybook previews.

Carousel: Public preview

---

change/@fluentui-react-combobox-3a0b4412-7326-4ac8-a23d-144408d18d72.json
packages/react-components/react-combobox/library/src/utils/ComboboxBase.types.ts
packages/react-components/react-combobox/stories/src/Combobox/ComboboxCustomOptions.stories.tsx
packages/react-components/react-combobox/stories/src/Combobox/ComboboxVirtualizer.stories.tsx

It was multiple times asked (#31972, #32040) about setting  `maxHeight` for `Combobox`, when the user tries to override it. I adjusted the examples to prevent further confusion and questions.

docs(react-combobox): adjust Combobox examples

---

change/@fluentui-react-search-151576f1-89e3-425a-8b4e-070acb37ef9a.json
packages/react-components/react-search/library/src/components/SearchBox/useSearchBox.tsx

`Uncaught Error: Cannot call an event handler while render` error, caused by [useEventCallback hook](https://github.com/microsoft/fluentui/blob/a00c100890d82e5133f909994dfe383e44b45782/packages/react-components/react-utilities/src/hooks/useEventCallback.ts#L19) when `autoFocus` is on.
No error 🙂 
- Fixes #31166

fix(react-search): replace useEventCallback with useCallback

---

change/@fluentui-react-combobox-d70f6062-309a-423a-9657-e1b8621c8b27.json
packages/react-components/react-combobox/library/src/components/Listbox/useListbox.ts
packages/react-components/react-combobox/library/src/utils/useComboboxBaseState.ts

Related to #31140 and #31415
Moving the activedescendant `.focus()` logic to Listbox's initial render also caused the page to attempt to scroll the active option into view before it was visible on the page (since the listbox is rendered on focus for combobox/dropdown).
Usually this doesn't do anything, but if the scrollParent isn't `null`, it can scroll the page (or closest scroll parent).
Now Listbox only calls the initial `activeDescendantController.focus()` logic if it does not have a parent context (so if rendered inline in the page, for example). Combobox & Dropdown call it when the listbox is opened, which is what happened previously.
Fixes a Teams issue raised in chat.

fix: only call activedescendant focus when combobox/dropdown is opened

---

packages/react-components/react-swatch-picker/stories/src/SwatchPicker/ColorSwatchVariants.stories.tsx
packages/react-components/react-swatch-picker/stories/src/SwatchPicker/EmptySwatch.stories.tsx
packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerBestPractices.md
packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerImage.stories.tsx
packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerMixedSwatches.stories.tsx
packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerPopup.stories.tsx
packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerWithTooltip.stories.tsx

The Empty swatch example didn't have a confirmation that the add new color/reset buttons had successfully added a new color or reset the colors.
Adds the following a11y updates:
- In the Empty example, moves focus on adding a new color or resetting as a confirmation of action
- Removes `aria-live` attributes from the ColorSwatch components (these didn't really do anything)
- Removes unnecessary `aria-label`s
- Updates a few missed labels to match content
- Minor docs wording updates
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/19222)

fix: SwatchColorPicker story a11y bug, docs wording

---

change/@fluentui-react-51415e29-94e2-48bb-b540-0e14ac4ec79f.json
packages/react-examples/src/react/DetailsList/DetailsList.KeyboardAccessibleResizeAndReorder.Example.tsx
packages/react/etc/react.api.md
packages/react/src/components/DetailsList/DetailsColumn.base.tsx
packages/react/src/components/DetailsList/DetailsColumn.types.ts
packages/react/src/components/DetailsList/DetailsList.types.ts
packages/react/src/components/DetailsList/__snapshots__/DetailsColumn.test.tsx.snap
packages/react/src/components/DetailsList/__snapshots__/DetailsHeader.test.tsx.snap
packages/react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
packages/react/src/components/DetailsList/__snapshots__/DetailsListV2.test.tsx.snap
packages/react/src/components/DetailsList/__snapshots__/DetailsRow.test.tsx.snap

No way for custom keydown handling to take place on `DetailsList` column headers
Consumers of Fluent UI can provide custom keyboard input handling for `DetailsList` headers, to address needs such as keyboard shortcut accessibility for resizing/reordering columns. Use new `IColumn` prop `onColumnKeyDown` to do so. 
Example added in `DetailsList.KeyboardAccessibleResizeAndReorder.Example.tsx`
**Demo**
- Fixes #23041

Feat(DetailsList): Add `onColumnKeyDown` prop to `IColumn` interface

---

change/@fluentui-react-table-7dd08fe8-65c4-4cad-b27f-d1a3ee6a5e7b.json
packages/react-components/react-table/library/src/hooks/types.ts

`TableProps` relies on [Discriminated Unions](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes-func.html#discriminated-unions) based on the presence of the `as` property to determine whether it's a `div` or a `table` element that is being provided. 
The discrimination is:
1. if `as` is `'table' | undefined` than `table` props are provided
2. if `as` is `div` than `div` props are provided
By using `Partial<TableProps>` we are breaking the discrimination, as the value of `undefined` for the `as` property would not give the compiler enough information to properly discriminate the value.
Here's a [playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwMoBsIwDRwMIXBAOwFMCYAFKCMAZwF84AzSkOAcgAEGUBXEmb4AHooRAIYBjGAFpuMYCmByi1VgChVMAJ5gicACqiARiiKp01OAF5EquHbiV0 …

bugfix(react-table): removes Partial from TableProps usage

---

tools/workspace-plugin/src/generators/react-library/files/jest.config.js__tmpl__
tools/workspace-plugin/src/generators/react-library/index.spec.ts

see PR title
- Follows https://github.com/microsoft/fluentui/pull/32106

feat(workspace-plugin): update react-library generator jest config to use swc

---

apps/react-18-tests-v8/cypress.config.ts
apps/react-18-tests-v8/package.json
apps/react-18-tests-v8/tsconfig.json

`e2e` targets don't run without `build`  step for all projects
https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=354795&view=logs&j=df65131f-49fe-5f4e-72c0-55655bbfd745&t=ce789735-18bf-559a-842b-052b9b2ccc06
`e2e` targets run without `build` step for all projects
- Follows https://github.com/microsoft/fluentui/pull/32172

e2e(react-18-tests-v8): setup cypress webpack to use v8 TS path aliases in order to work without build step

---

.devops/templates/deployE2E.yml

- CI pipeline runs are failing due to missing assets:
https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=354836&view=logs&j=df65131f-49fe-5f4e-72c0-55655bbfd745&t=500ae3fd-d581-5ecf-52f7-fd3683672b6b
- assets are now built before step

ci: build pr deploy site in CI runs to fix failing pipeline step

---

.devops/templates/runpublishvrscreenshot.yml
azure-pipelines.vrt-baseline.yml
package.json
yarn.lock

Today, the Azure pipelines have a dependency on `vr-approval-cli`, which is a package to detect visual diffs in screenshots and compile a report, for publishing to PRs and the like.
While not comtaining anything secret, this package is internal to Microsoft, is unlicensed for use outside of Microsoft, and cannot actually be used outside of Microsoft infrastructure. However, due to its presence as a declared dependency in `package.json`, all forks and clones of FluentUI are forced to install this unnecessary (from their perspective) package.
This change removes the declared dependency, and installs it at runtime in the Azure pipelines, instead. It is not ideal to have runtime dependencies in the pipelines, but it's less-bad than the current situation.
The ultimate goal is to package this …

chore: Remove dependency on vr-approval-cli

---

apps/public-docsite-resources/package.json
nx.json

- `verify-packaging` wont run build on project (`self`) which will fail the task 
-  https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=354914&view=logs&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=254ee48e-1503-524f-f75e-e2c69d0380f5
- https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=354990&view=logs&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=254ee48e-1503-524f-f75e-e2c69d0380f5
- `bundle` has dependency on self `build`, but when project has `bundle` task we dissallow `build` task ( only exception is public-docsite-resource which is an antipattern/hybrid between application/library )
- `verify-packaging` runs self `build` and deps `^build`
- `bundle` runs only deps `^build`
- Follows https://github.com/microsoft/fluentui/pull/31949

fix(nx): update target dependencies so all targets work as expected

---

change/@fluentui-react-tree-bd1e1754-9d0e-461f-9f53-d661b31b0a17.json
packages/react-components/react-tree/library/etc/react-tree.api.md
packages/react-components/react-tree/library/package.json
packages/react-components/react-tree/library/src/components/FlatTree/useFlatTreeStyles.styles.ts
packages/react-components/react-tree/library/src/components/Tree/Tree.types.ts
packages/react-components/react-tree/library/src/components/Tree/renderTree.tsx
packages/react-components/react-tree/library/src/components/Tree/useTreeStyles.styles.ts
packages/react-components/react-tree/library/src/components/TreeItemChevron.tsx
packages/react-components/react-tree/library/src/hooks/useRootTree.ts
packages/react-components/react-tree/library/src/hooks/useSubtree.ts

`renderTree` didn't have a collapse animation
- `renderTree` gets the new slot for collapse motion: `collapseMotion`
Motion slots allow to customize or replace built-in motion, see examples in #31984.
[Fluent Motion Component Defaults](https://loop.cloud.microsoft/p/eyJ3Ijp7InUiOiJodHRwczovL21pY3Jvc29mdC5zaGFyZXBvaW50LWRmLmNvbS8%2FbmF2PWN6MGxNa1ltWkQxaUlVZGtPVkJhWlRGUU1tdFBWSEpxVkdKYWVtbDVaazR4VDI5WGNWbDNSbXhGYTBoS1UzVllRek5qTkdjNWQyUnRZVFYxVUhaVFRHZENYMnBtVjJsdFVVNG1aajB3TVUwM1NVczNXVXd6VjFZMk5FVlBSVlUwVWtOYU4weExVMGd6V0VKUFRGSlFKbU05Sm1ac2RXbGtQVEUlM0QiLCJyIjpmYWxzZX0sInAiOnsidSI6Imh0dHBzOi8vbWljcm9zb2Z0LnNoYXJlcG9pbnQtZGYuY29tLzpmbDovci9jb250ZW50c3RvcmFnZS9DU1BfNjU0ZmRmMTktNGZlZC00M2RhLTkzYWUtMzRkYjY3MzhiMjdjL0RvY3VtZW50JTIwTGlicmFyeS9Mb29wQXBwRGF0YS9VbnRpdGxlZC5sb29wP2Q9d2MzZDcyZjgxNDk …

feat(motion): add collapse motion for Tree

---

azure-pipelines.release.yml
scripts/tasks/src/argv.ts

- adds ability to set `--production` flag via env variable
- splits `bundle` and `build` step for v8 as it was before migration 
- adds logs to verify react build assets on release 
- PERF: test/lint will use cached assets from `build` steps
- Fixes https://github.com/microsoft/fluentui/issues/32189

ci: separate build and bundle for v8 release in order to mitigate accidental clean task runs that would remove /dist assets

---

change/@fluentui-react-fix-bad-release.json

Adds a change file for Fluent v8 will push out a release when triggered.
See: #32189

chore: manually add change file to trigger new publish for v8 

---

change/@fluentui-web-components-c3806260-df2c-412f-bfb5-51398d51025e.json
packages/web-components/docs/api-report.md
packages/web-components/src/field/field.ts
packages/web-components/src/field/index.ts
packages/web-components/src/index.ts

Layout API was bundled into one `Field` class.
Abstracts out layout API and creates `BaseField` class.
- Fixes #

[chore]: abstracts layout api from field class

---

change/@fluentui-react-popover-4e04d92a-bcbe-4856-877e-9801c61d5f60.json
packages/react-components/react-popover/library/src/components/PopoverSurface/usePopoverSurfaceStyles.styles.ts

fix(Popover): fix shadows on arrows

---

apps/public-docsite-v9/project.json

If only source files of `*-stories` project are changed within a PR it wont trigger `public-docsite-v9` `build-storybook` which will end up not having storybook deployed per PR in order to review your changes
Example of issues:
https://github.com/microsoft/fluentui/pull/32176
https://github.com/user-attachments/assets/9895b8a0-3150-4089-aacb-57f80c701a6c
as we moved to nx we can leverage powerful capabilities like `implicitDependencies` definition which understands patterns set within our monorepo. This also nicely mirrors what is actually happening in real life as we load those project stories imperatively behind the scenes so they are not a direct dependency.
**Before**
**After**
- Fixes #

fix(public-docsite-v9): add all stories project as implicit dependency in order to properly trigger affected build chain

---

change/@fluentui-web-components-1b78a1eb-0122-4dd8-b56f-fd3aac7b3ef6.json
packages/web-components/docs/api-report.md
packages/web-components/package.json
packages/web-components/src/index-rollup.ts
packages/web-components/src/index.ts
packages/web-components/src/tablist/define.ts
packages/web-components/src/tablist/index.ts
packages/web-components/src/tablist/readme.md
packages/web-components/src/tablist/tablist.bench.ts
packages/web-components/src/tablist/tablist.definition.ts
packages/web-components/src/tablist/tablist.options.ts
packages/web-components/src/tablist/tablist.spec.ts
packages/web-components/src/tablist/tablist.stories.ts
packages/web-components/src/tablist/tablist.styles.ts
packages/web-components/src/tablist/tablist.template.ts
packages/web-components/src/tablist/tablist.ts
packages/web-components/src/utils/focusable-element.ts

Current Tabs web component is an assembly of three components (`-tabs`, `-tab`, and `-tabpanel`) which is very explicit but very DOM heavy and doesn't easily support scenarios like ajax'ing in content.
This new `Tablist` component is more on par with the React implementation and is much simpler in its approach, providing only the`-tab` and `-tablist` components and allowing the consumer to react to the `change` event (when the active tab changes) as necessary.

feat(web-components): add tablist

---

change/@fluentui-web-components-48c87f5d-af00-464e-8236-1bee7ec2f9c2.json
packages/web-components/project.json
packages/web-components/public/theme-switch.ts

- wc use custom target dep override that is not consistent with monorepo best practices for lates code
- this behaviour also breaks domain boundaries 
- wc project follows monorepo targetDefaults how to run `type-check` target
- if folks want we can migrate package to follow our best practices ( splitting project into two `/libary` and `/stories` - https://github.com/microsoft/fluentui/pull/31565 )
- Follows https://github.com/microsoft/fluentui/pull/32202

chore(web-components): remove type-check definition and follow repo target defaults for consistency and type-check speeds

---

change/@fluentui-react-dialog-d29eacce-56a3-4174-8f78-b577f330c2d0.json
packages/react-components/react-dialog/library/src/components/Dialog/renderDialog.tsx
packages/react-components/react-dialog/library/src/components/DialogSurface/useDialogSurface.ts
packages/react-components/react-dialog/library/src/components/MotionRefForwarder.tsx

```tsx
<Dialog>
{/* ❌ throws if `CustomComponent` does not forward a ref */}
<CustomComponent />
</Dialog>
```
```tsx
<Dialog>
{/* ✅ does not throw */}
<CustomComponent />
</Dialog>
```
A `ref` will be passed down via context to `DialogSurface` rendered by `CustomComponent`.
Fixes #31808

fix(Dialog): do not require ref forwarding

---

change/@fluentui-react-message-bar-bfb5f0c1-b637-4cbd-96e4-9ea0283c03d2.json
packages/react-components/react-message-bar/library/src/components/MessageBar/useMessageBarReflow.ts

In older browsers, such as Chrome 80, `ResizeObserverEntry.borderBoxSize` is not implemented, and returns undefined. The unguarded dereference in `useMessageBarReflow` causes a TypeError in such cases.
Added an optional chaining guard `?.` to the code, and a comment explaining the reason for it.
- Fixes #32237

Fix undefined reference in older browsers in useMessageBarReflow

---

change/@fluentui-react-card-83adc37b-ffe3-4cbd-a1f8-93b6f41549a3.json
packages/react-components/react-card/library/src/components/Card/Card.test.tsx
packages/react-components/react-card/library/src/components/Card/useCard.ts

It was impossible to have both a `focusMode=off` or `focusMode=tab-only` card with a click handler on the root. There are several reasons to do this (e.g. the card as a whole can be clicked as a larger hit target, and there's also a link or button within that does the same thing). The change in `focusMode` actually interferes with accessibility, because it makes it impossible to have a card with both a root click and enter/space handler, since a card with any `focusMode` apart from `off` will prevent enter from doing an author-defined action.
Authors already must provide a secondary method for performing any action put onto the card root, since any such actions will not be accessible to voice control, touch screen readers, etc.
This updates the default `focusMode` to be `tab-only` when …

fix: Card does not override specified focusMode based on event listeners

---

apps/public-docsite/src/pages/Controls/DetailsListPage/DetailsListKeyboardDragDropPage.doc.ts
packages/react-examples/src/react/DetailsList/DetailsList.KeyboardAccessibleResizeAndReorder.Example.tsx
packages/react-examples/src/react/DetailsList/DetailsList.doc.tsx

With the new WCAG 2.2 criterion around pointer-accessible dragging, we've had some questions about how to meet it with the v8 DetailsList. Our current keyboard-accessible example also works for the new dragging accessibility requirement, so this PR updates our docs to make that more clear.
Wording changes only (plus some auto linting updates), no code/package changes.

docs: update title of v8 keyboard-accessible drag & drop example, add docs

---

packages/react-examples/src/react/ContextualMenu/ContextualMenu.WrappingMenuItem.Example.tsx
packages/react-examples/src/react/ContextualMenu/ContextualMenu.doc.tsx

Docs-only change. Made a demo for someone, and thought it would be a good addition to the docs site as well.
Wrapping text can be a requirement for zoom and text spacing a11y criteria. We already have wrapping item text style examples for pickers and combobox/dropdown, so adding one to ContextualMenu seems to make sense.

docs: add wrapping menu item example to ContextualMenu docs

---

change/@fluentui-react-toolbar-412d5b87-74d8-44b4-8215-ab53b873e174.json
packages/react-components/react-toolbar/library/src/components/ToolbarButton/useToolbarButton.ts

TS will scream on `size` prop, but it still can be passed an affect `ToolbarButton`.
`ToolbarButton` has hardcoded size according to the design spec.
Fixes #32063.

fix(Toolbar): hardcode size of `ToolbarButton`

---

.github/workflows/docsite-publish-ghpages.yml
apps/public-docsite-v9/project.json

After [target normalization](https://github.com/microsoft/fluentui/pull/31926), apps are not allowed to specify `build` rather `bundle` or `build-storybook`. we forgot to reflect this to v9 docsite publish pipeline which is causing  [failures](https://github.com/microsoft/fluentui/actions/runs/10256997462/job/28377201953#step:5:7)
v9 publish(deploy) pipeline
- now runs only `build-storybook` target 
- this target is optimised to actually build only what is really necessary (workspace addons) instead of all fluent frameworks (v0,v8,v9)
| deploy v9 docsite | time |
|--------|--------|
| Before | 393ms |
| After | 114ms  / **𝚫 71% FASTER** | 
- Fixes #

ci: make public-docsite-v9 deploy pipeline work and make it faster

---

package.json
yarn.lock

nx workspace-plugin generators are broken because of incompatible swc dependency
Incompatible dependency `@swc-node/register` removed, nx workspace-plugin generators are working as expected
- https://github.com/swc-project/swc-node/issues/729
- reverts changes from https://github.com/microsoft/fluentui/pull/32018

fix(workspace-plugin): remove swc-node@register dependency

---

change/@fluentui-eslint-plugin-1d3bf32e-cc52-4d02-8ff0-c047c300984a.json
change/@fluentui-react-carousel-preview-0376635f-0565-4580-93eb-e8c5897fea84.json
change/@fluentui-react-drawer-272fabef-7078-4ffa-979d-dac3e8971ca1.json
change/@fluentui-react-table-2814c80d-d032-49e8-945b-c06f4746d07e.json
packages/eslint-plugin/src/configs/react-config.js
packages/react-components/react-carousel-preview/library/src/components/CarouselNavButton/useCarouselNavButtonStyles.styles.ts
packages/react-components/react-drawer/library/src/components/DrawerFooter/useDrawerFooterStyles.styles.ts
packages/react-components/react-drawer/library/src/components/DrawerHeader/useDrawerHeaderStyles.styles.ts
packages/react-components/react-table/library/src/components/TableResizeHandle/useTableResizeHandleStyles.styles.ts

We allowed pseudo elements to be selected with a single colon rather than enforce the double colon syntax.
E.g.,
```css
:after {
/ * rules here */
}
```
Pseudo elements must be selected with double colon syntax. E.g.:
```css
::after {
/* rules here */
}
```
See: https://github.com/microsoft/fluentui/pull/32077#discussion_r1705107306

chore: add "@griffel/pseudo-element-naming": "error" eslint rule

---

change/@fluentui-web-components-77c45460-67de-4189-a7f9-c04db87cf6d9.json
packages/web-components/docs/api-report.md
packages/web-components/src/index.ts
packages/web-components/src/rating-display/index.ts
packages/web-components/src/rating-display/rating-display.ts

`compact`, `size` and `color` are style and layout specific to fluent. `generateIcons` needs to exist in both the base class and extended class to keep base class functional.
moves `compact`, `size` and `color`.
- Fixes #

[chore]: [rating-display] move size, color and compact. 

---

.github/workflows/check-tooling.yml
package.json
scripts/executors/src/enquirer-types.d.ts
scripts/executors/src/start.js
scripts/executors/src/start.spec.ts
scripts/executors/src/start.ts
yarn.lock

`yarn start` provides primitive alias with not enough context to run a `yarn workspace` `start` npm script
As we migrated to [Nx](https://nx.dev/getting-started/intro), our `yarn start` experience provides significantly improved DX, taking inspiration from official NX IDE plugin - [Nx Console](https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console)
Besides providing every project `target` within the CLI we add artificial `help` target which leverages `nx show project` capabilities in order to provide comprehensive overview about the project.
https://github.com/user-attachments/assets/fa164508-820a-4ad5-a27a-1468c505ec82

feat(scripts-executors): implement new `yarn start` experience

---

.github/workflows/check-tooling.yml

tools pipeline was not triggered on huge PR that changed `tools/workspace-plugin/...` files , causing merging code that caused issues
tools pipeline will be checked for any dependency changes
- Follows https://github.com/microsoft/fluentui/pull/32254

ci: trigger check tooling pipeline on monorepo dep changes

---

.githooks/post-checkout
.githooks/post-merge
.githooks/pre-push
package.json
scripts/package-manager/src/is-ci.js
scripts/package-manager/src/notify-lockfile-changes.js
scripts/package-manager/src/postinstall.js
scripts/package-manager/src/preinstall.js
scripts/package-manager/src/use-yarn-please.js

- git hook checks are not executed on CI
- postinstall will point user to up to date docs page
- new git hook that will notify user to run `yarn install` if there has been changes in `yarn.lock` file

feat(scripts-package-manager): dont run git hooks on CI, notify user to run install if needed

---

scripts/executors/src/enquirer-types.d.ts
scripts/executors/src/start.ts
tools/eslint-rules/project.json

no targets is selected - user needs to do one additional step manually which might feel slower in comparison with original "start" UX
Based on package context the UI will pre-select most common (default) target so user don't have to type/choose just confirm the default.
https://github.com/user-attachments/assets/5f5e91dd-ae8e-4d2b-9e23-2e1cbcfec065
- Follows https://github.com/microsoft/fluentui/pull/32108

feat(script-executors): implement default target pre-selection to start CLI

---

apps/public-docsite-v9/.storybook/manager.js

After upgrading to Storybook v7, the toolbar becomes visible on the documentation site.
The Storybook toolbar is not visible on the documentation site.
- introduced at #32018

fix(public-docsite-v9): hide storybook's toolbar

---

apps/ts-minbar-test-react-components/project.json
apps/ts-minbar-test-react/project.json

- CI pipeline fails because suite packages aren't built before running `test-integration` target (see failing [pipeline run](https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=356297&view=logs&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=254ee48e-1503-524f-f75e-e2c69d0380f5))
```
test:ts-minbar-react : ✔️ Temporary directory for packed packages was created: /tmp/project-packed--13894-bQD0JZChi7fb
================================================================================
+ cd /tmp/project-packed--13894-bQD0JZChi7fb &&
npx npm-which npm
npm warn exec The following package was not found and will be installed: npm-which@3.0.1
/opt/hostedtoolcache/node/20.16.0/x64/bin/npm
+ cd /tmp/project-packed--13894-bQD0JZChi7fb &&
npm --version
10.8.1
Something went wrong setting up …
```

ci(ts-minbar-test): ensure that dependent suite packages are built before running tests 

---

change/@fluentui-react-combobox-7d75d97b-877f-4f43-92d4-cfadb37677da.json
packages/react-components/react-combobox/library/src/components/Option/useOptionStyles.styles.ts
packages/react-components/react-combobox/stories/src/Dropdown/DropdownTruncation.stories.tsx

Adds one style fix and one story.
When the text of an option was longer than could fit in the available space, the check icon would collapse:
Fixes the icon slot collapsing with `flex-shrink: 0`, and adds a story showing how to add `overflow-wrap` styles to option text.
- Fixes #32227 and #32228

fix: react-combobox check icon slot does not collapse

---

change/@fluentui-react-tag-picker-f6c70a8c-6231-41fe-baa5-ce7d1e65417a.json
packages/react-components/react-tag-picker/library/etc/react-tag-picker.api.md
packages/react-components/react-tag-picker/library/src/components/TagPicker/TagPicker.cy.tsx
packages/react-components/react-tag-picker/library/src/components/TagPicker/TagPicker.types.ts
packages/react-components/react-tag-picker/library/src/components/TagPicker/useTagPicker.ts
packages/react-components/react-tag-picker/library/src/components/TagPicker/useTagPickerContextValues.ts
packages/react-components/react-tag-picker/library/src/components/TagPickerControl/useTagPickerControl.tsx
packages/react-components/react-tag-picker/library/src/components/TagPickerInput/useTagPickerInput.tsx
packages/react-components/react-tag-picker/library/src/contexts/TagPickerContext.ts
packages/react-components/react-tag-picker/stories/src/TagPicker/TagPickerNoPopover.stories.tsx
packages/react-components/react-tag-picker/stories/src/TagPicker/index.stories.tsx

`TagPicker` right now requires the presence of `TagPickerList` as a popover to work properly.
1. ensures that `TagPicker` can be used without `TagPickerList`
* adds property `noPopover` that can be used to opt-in into this feature
2. adds stories to showcase how to use this
3. adds tests to ensure behavior
- Fixes https://github.com/microsoft/fluentui/issues/32091

feature(react-tag-picker): support TagPicker usage without TagPickerList

---

apps/ts-minbar-test-react-components/project.json
apps/ts-minbar-test-react/project.json
nx.json

issue that surfaced in https://github.com/microsoft/fluentui/pull/32269 is still present in cra project.
we now always trigger `build` on dependencies ( even if `build` target is not present at "self" -> which was the cause of not triggering anything before )
- Follows https://github.com/microsoft/fluentui/pull/32269

chore: always trigger build on dependencies for test-integration target

---

packages/react-components/babel-preset-storybook-full-source/src/__fixtures__/storybook-stories-fullsource/keep-sourcecode-spacing/output.js
packages/react-components/babel-preset-storybook-full-source/src/__fixtures__/storybook-stories-fullsource/mutilple-components/code.js
packages/react-components/babel-preset-storybook-full-source/src/__fixtures__/storybook-stories-fullsource/mutilple-components/output.js
packages/react-components/babel-preset-storybook-full-source/src/fullsource.ts

After the SB7 migration, a regression occurred where the `Positioning Components` page is not functioning correctly. This issue arises because the `PositionedComponent` is defined prior to the story component, leading the `babel-full-source-plugin` to mistakenly treat it as a story component.
The `babel-plugin-full-source` detects stories as React components that are exported using named exports.
- introduced at #32018

fix(babel-preset-storybook-full-source): use named exports for story detection

---

packages/react-components/react-migration-v0-v9/stories/src/List/ListDescription.md

This PR updates the docs for the V0 List shim, informing the user that they should go and use the V9 List directly instead.

List-Shim: update docs to steer people towards using List preview

---

azure-pipelines-pr.yml

- pipeline was renamed from `azure-pipelines.yml` to `azure-pipelines-pr.yml` in `master` branch and thus the pipeline no longer ran for this hotfix branch. Renaming to add `-pr` suffix to make it run again and unblock PRs

ci(hotfix/5.135.6): make PR checks run again

---

change/@fluentui-web-components-c8121fc1-57f4-47b4-9707-c96bd0a211fe.json
packages/web-components/src/anchor-button/index.ts
packages/web-components/src/index.ts

`BaseAnchor` wasn't being properly exported
`BaseAnchor` is now exported
- Fixes #

fix(web-components): export BaseAnchor

---

change/@fluentui-react-c4edf12d-d8dd-4265-90c4-7524b6c8f401.json
packages/react/src/components/pickers/Suggestions/Suggestions.styles.ts

The focus outline in the suggestions popup was implemented in the SuggestionItem control's styles, so since actions were not wrapped in a SuggestionItem, they had no contrast-y focus indicator (the light blue bg color does not meet 3:1 contrast against white).
I didn't want to change up the DOM of the control by wrapping the actions in a SuggestionItem, so I copy/pasted the SuggestionItem focus style over to the actionItem focus className. New visuals:
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/19656)

fix: v8 picker suggestion actions have focus outline

---

change/@fluentui-react-af6b7f2e-0fe5-41bc-97f6-f46116fb2f68.json
packages/react/package.json
scripts/executors/src/start.ts

For non generic commands we will print only `scriptContent` in order to not assume things that might be not valid
- Fixes https://github.com/microsoft/fluentui/issues/32262

fix(scripts-executors): emit script contents if invalid e2e target declaration is present

---

change/@fluentui-react-list-preview-103c8633-2761-40f0-9d31-34c94b7f4dea.json
change/@fluentui-react-tabster-b8b5ef61-c217-409a-9b04-8c3756addacd.json
packages/react-components/react-list-preview/library/src/components/ListItem/useListItem.tsx
packages/react-components/react-tabster/etc/react-tabster.api.md
packages/react-components/react-tabster/src/hooks/useMergeTabsterAttributes.ts

Casting is required when providing to `useMergedTabsterAttributes` an object that does not have proper tabster attribute, which is redundant as this is filtered by the function internally.
There's a cast on `useListItem` because of this: https://github.com/microsoft/fluentui/pull/32300/files#diff-d3287bdc67e7afdeb4149b129ca698a5a9eb873eebee2cb3fb998a99d7e46a79L179
Also on `TreeGrid`: https://github.com/microsoft/fluentui-contrib/pull/215/files#diff-3f5ba9155013655901c724d7ce54114b60eb65eae52fd62ec18981897c05f9fdR30 and `TreeGridRow`: https://github.com/microsoft/fluentui-contrib/pull/215/files#diff-716cd94658fd845cd35b2b2bb4d0bcb3d55f01a9cc3394227253be8a445b5b2cR45
1. Modifies function signature to support `Partial<Types.TabsterDOMAttribute>` instead of `Types.TabsterDOMAttribute`
- Fixes …

chore(react-tabster): ensures useMergedTabsterAttributes supports Partial attributes

---

change/@fluentui-react-tabster-cc5de3db-3b7c-4231-a070-8f3fb7ed4b21.json
packages/react-components/react-tabster/src/hooks/useMergeTabsterAttributes.test.ts
packages/react-components/react-tabster/src/hooks/useMergeTabsterAttributes.ts

1. adds tests to ensure behavior
2. reduces amount of iterations by using `reduce` instead of `map` + `filter`
3. reduces object creation by using `Object.assign` instead of spreading (super nit)
4.  reduces implementation in 10 loc
5. adds verification to ensure attributes are stable throughout runtime
- Fixes #

chore(react-tabster): nits on useMergedTabsterAttributes internals

---

apps/public-docsite-v9/src/DocsComponents/ReactIconGridLazy.tsx
apps/public-docsite-v9/src/Icons/IconsCatalog.stories.mdx

Icon catalog renders again
Fixes #32312

docs: fix icons catalog

---

change/@fluentui-web-components-a9a5cfab-dd85-4c06-9d8f-e1c5445647b2.json
packages/web-components/src/checkbox/index.ts
packages/web-components/src/index.ts

- BaseCheckbox not exported
- BaseCheckbox is exported
I went through and confirmed this is the last of the base classes that needs to be exported. 
- Fixes #

fix(web-components): export BaseCheckbox

---

change/@fluentui-react-motion-051564b3-04af-45b4-b634-c0494efb621b.json
packages/react-components/react-motion/library/etc/react-motion.api.md
packages/react-components/react-motion/library/src/contexts/MotionBehaviourContext.ts
packages/react-components/react-motion/library/src/contexts/MotionDisableContext.ts
packages/react-components/react-motion/library/src/factories/createMotionComponent.test.tsx
packages/react-components/react-motion/library/src/factories/createMotionComponent.ts
packages/react-components/react-motion/library/src/factories/createPresenceComponent.cy.tsx
packages/react-components/react-motion/library/src/factories/createPresenceComponent.test.tsx
packages/react-components/react-motion/library/src/factories/createPresenceComponent.ts
packages/react-components/react-motion/library/src/index.ts

Adds a context with a new `skip` behaviour for motions. This behaviour will **immediately complete the motion** and apply final motion styles.
> ℹ️ Note that `onMotionStart` `onMotionFinish` will still be called
Fixes #32046

feat: Add context to configure motion behaviour

---

packages/react-components/react-avatar/stories/src/Avatar/AvatarSize.stories.tsx
packages/react-components/react-avatar/stories/src/AvatarGroup/AvatarGroupSizeStack.stories.tsx
packages/react-components/react-button/stories/src/Button/ButtonBestPractices.md
packages/react-components/react-button/stories/src/SplitButton/SplitButtonSizeSmall.stories.tsx
packages/react-components/react-combobox/stories/src/Dropdown/DropdownCustomOptions.stories.tsx
packages/react-components/react-infolabel/stories/src/InfoLabel/InfoLabelBestPractices.md
packages/react-components/react-infolabel/stories/src/InfoLabel/InfoLabelSize.stories.tsx
packages/react-components/react-swatch-picker/stories/src/SwatchPicker/SwatchPickerBestPractices.md

docs-only updates, adds wording to best practices & individual stories about the new WCAG 2.2 target size criterion.

docs: add target size information to relevant v9 component docs

---

change/@fluentui-react-provider-3bd9a3d1-66ee-4ddd-a588-4705107c3820.json
change/@fluentui-react-tree-a5434551-fc6b-46b6-8aed-3f40515ba2b0.json
packages/react-components/react-provider/library/etc/react-provider.api.md
packages/react-components/react-tree/library/src/components/TreeItemLayout/TreeItemLayout.types.ts
packages/react-components/react-tree/library/src/components/TreeItemLayout/useTreeItemLayout.tsx
packages/react-components/react-tree/stories/src/Tree/TreeA11y.md
packages/react-components/react-tree/stories/src/Tree/TreeAside.stories.tsx
packages/react-components/react-tree/stories/src/Tree/TreeIconBeforeAndAfter.stories.tsx
packages/react-components/react-tree/stories/src/Tree/TreeManipulation.stories.tsx

We had `aria-hidden` attributes scattered around tree slots that hide potentially meaningful information (and a currently meaningful button) from screen reader users.
Those include:
- The `iconBefore` and `iconAfter` slots. If authors put an icon without an accName in there, it will already have `aria-hidden` because of our icon's internal logic. Adding `aria-hidden` to the slot only ends up hiding meaningful icons.
- `aside`: since this contains actions and information relevant to the user, putting `aria-hidden` on here causes user-impacting issues. The TreeManipulation story shows an example of this (the remove button, in that story) being a problem.
`aria-hidden` is not added to those slots
not logged as an issue, but a partner team had a problem caused by Tree adding `aria-hidden` to …

fix: remove unnecessary aria-hidden attributes from Tree

---

packages/react-examples/src/react-charting/GaugeChart/GaugeChart.Basic.Example.tsx
packages/react-examples/src/react-charting/GaugeChart/GaugeChart.SingleSegment.Example.tsx
packages/react-examples/src/react-charting/GroupedVerticalBarChart/GroupedVerticalBarChart.Basic.Example.tsx
packages/react-examples/src/react-charting/GroupedVerticalBarChart/GroupedVerticalBarChart.CustomAccessibility.Example.tsx
packages/react-examples/src/react-charting/HorizontalBarChart/HorizontalBarChart.Basic.Example.tsx
packages/react-examples/src/react-charting/HorizontalBarChartWithAxis/HorizontalBarChartWithAxis.Basic.Example.tsx
packages/react-examples/src/react-charting/HorizontalBarChartWithAxis/HorizontalBarChartWithAxis.StringAxisTooltip.Example.tsx
packages/react-examples/src/react-charting/MultiStackedBarChart/MultiStackedBarChart.Example.tsx
packages/react-examples/src/react-charting/StackedBarChart/MultiStackedBarChart.Example.tsx
packages/react-examples/src/react-charting/StackedBarChart/StackedBarChart.Basic.Example.tsx
packages/react-examples/src/react-charting/StackedBarChart/StackedBarChart.Dynamic.Example.tsx
packages/react-examples/src/react-charting/StackedBarChart/StackedBarChart.Multiple.Example.tsx
packages/react-examples/src/react-charting/VerticalBarChart/VerticalBarChart.AxisTooltip.Example.tsx
packages/react-examples/src/react-charting/VerticalBarChart/VerticalBarChart.Basic.Example.tsx
packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.AxisTooltip.Example.tsx
packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.Basic.Example.tsx
packages/react-examples/src/react-charting/VerticalStackedBarChart/VerticalStackedBarChart.Styled.Example.tsx

Toggle positions Enable Gradient and rounder corners are not aligned properly for all the charts.
for some charts it is in a single line, some one above the other, and for some charts there is no gap between them
Toggles for Enable Gradient and Rounded Corners are all horizontally aligned with equal space between for all chart
#32327

[issue 32327] Align positions for Toggles Enable Gradient and Rounded Corners

---

apps/vr-tests-web-components/package.json
change/@fluentui-web-components-2abbf9e1-779e-479d-b553-b2a0167723fe.json
packages/web-components/package.json
yarn.lock

Updates the `@microsoft/fast-element` dependency to the latest stable version.
- Fixes #

feat: update fast-element to latest stable version

---

change/@fluentui-react-table-75ffa08b-d69f-4cb7-8a9e-82553a971c3e.json
packages/react-components/react-table/library/src/components/TableHeaderCell/useTableHeaderCellStyles.styles.ts

Adds
* `colorNeutralForegroundHover`
* `colorNeutralForeground1Pressed`
For hover/pressed states respectively to fix high contrast issues
Before
After 
Fixes #32301

fix(TableHeaderCell): should use hover and pressed tokens

---

azure-pipelines.release-vnext.yml
azure-pipelines.release.tools.yml

Not using `--production` flag in consecutive pipeline tasks invalided cache, which might be causing possible artifacts regression that we've been publishing.
> this can happen because `lint` requires `build` , but `build` is run with `--production` first, making it run again when `lint` is executed ( every `build` removes everything - this should be removed in future )
- we use common env variable to set production mode which won't invalidate cache = making releases FASTER
- we don't run tasks on `-stories` projects during v9 release = making releases FASTER 
_TODO:_  add pipeline data comparison after we trigger release
- before (current): build 6m40s / test 4m40s / lint 10m23s
- after : TBA
- Follows https://github.com/microsoft/fluentui/pull/32195

ci(releases): properly cache build target execution between ci tasks to leverage cache and avoid accidental artifacts removal

---

apps/public-docsite-v9/src/Concepts/WebComponentsInterop/UsingFluentReactWithWebComponents.stories.mdx

Based on partner feedback it wasn't very clear that `FluentProvider` had to be in the light DOM.
The light DOM requirement is explicitly called out.

docs: clarifies FluentProvider/shadow DOM interop

---

change/@fluentui-react-carousel-preview-78c536bb-5cc0-4518-b9ee-0c6639e9fff6.json
packages/react-components/react-carousel-preview/library/etc/react-carousel-preview.api.md
packages/react-components/react-carousel-preview/library/src/components/CarouselNav/CarouselNav.tsx
packages/react-components/react-carousel-preview/library/src/components/CarouselNav/CarouselNav.types.ts
packages/react-components/react-carousel-preview/library/src/components/CarouselNav/CarouselNavContext.ts
packages/react-components/react-carousel-preview/library/src/components/CarouselNav/renderCarouselNav.tsx
packages/react-components/react-carousel-preview/library/src/components/CarouselNav/useCarouselNav.ts
packages/react-components/react-carousel-preview/library/src/components/CarouselNavButton/CarouselNavButton.types.ts
packages/react-components/react-carousel-preview/library/src/components/CarouselNavButton/useCarouselNavButton.ts
packages/react-components/react-carousel-preview/library/src/components/CarouselNavButton/useCarouselNavButtonStyles.styles.ts
packages/react-components/react-carousel-preview/library/src/components/CarouselNavImageButton/useCarouselNavImageButton.ts
packages/react-components/react-carousel-preview/stories/src/Carousel/CarouselDefault.stories.tsx

Add 'brand' appearance to buttons
Implement hover/active state in styles based on latest design
CarouselNavContext was a number (index) of buttons
No hover/active state
No appearance variants
CarouselNavContext now an object with both index and appearance
Hover active states added for both appearances

Carousel: NavButton styles and appearance

---

change/@fluentui-react-tabs-3a54a623-3c3d-41e3-93c7-4bbe197234e2.json
packages/react-components/react-tabs/library/etc/react-tabs.api.md
packages/react-components/react-tabs/library/src/components/Tab/useTabStyles.styles.ts
packages/react-components/react-tabs/library/src/index.ts

Previously, TabList did not support interactive tabs, such as a tab with a dismiss/close button to remove the tab, or a tab featuring a dropdown or search box.
The primary slot for a Tab was a button with `role=tab`. According to Aria guidelines, elements with `role=tab` should only contain presentational children.
This PR introduces the `InteractiveTab` component, which is derived from `Tab`, but instead uses a div as its root. It includes three additional slots: `button` (where `role=tab` is assigned), `beforeContent`, and `afterContent`. This design, akin to the Input component, allows users to insert interactive content before or after the tab button.
The styling hook for Tab has been segmented into sub-hooks to differentiate the application of tab button styles from indicator styles. …

feat(react-tabs): export Tab component style hooks

---

tools/workspace-plugin/.eslintrc.json
tools/workspace-plugin/executors.json
tools/workspace-plugin/package.json
tools/workspace-plugin/project.json
tools/workspace-plugin/src/executors/build/executor.spec.ts
tools/workspace-plugin/src/executors/build/executor.ts
tools/workspace-plugin/src/executors/build/schema.d.ts
tools/workspace-plugin/src/executors/build/schema.json
tools/workspace-plugin/src/executors/clean/executor.spec.ts
tools/workspace-plugin/src/executors/clean/executor.ts
tools/workspace-plugin/src/executors/clean/schema.d.ts
tools/workspace-plugin/src/executors/clean/schema.json
tools/workspace-plugin/src/executors/generate-api/executor.spec.ts
tools/workspace-plugin/src/executors/generate-api/executor.ts
tools/workspace-plugin/src/executors/generate-api/schema.d.ts
tools/workspace-plugin/src/executors/generate-api/schema.json
tools/workspace-plugin/src/executors/type-check/executor.spec.ts
tools/workspace-plugin/src/executors/type-check/executor.ts
tools/workspace-plugin/src/executors/type-check/schema.d.ts
tools/workspace-plugin/src/executors/type-check/schema.json
tools/workspace-plugin/src/executors/verify-packaging/executor.spec.ts
tools/workspace-plugin/src/executors/verify-packaging/executor.ts
tools/workspace-plugin/src/executors/verify-packaging/schema.d.ts
tools/workspace-plugin/src/executors/verify-packaging/schema.json

we will need only 5 executors to start with in order to remove just-scripts in v9 packages. This PR generates boilerplate for those.
> what about lint, e2e etc ?
>
> for lint we will migrate to direct eslint CLI invocation as we do for `jest`, `e2e` will be kept as is ( invoking binary directly ) 
- boilerplate generated via: 
`yarn nx g  @nx/plugin:executor --name <executor-name> --project workspace-plugin --nameAndDirectoryFormat derived`

feat(workspace-plugin): scaffold executors boilerplate (build,generate-api,type-check,verify-packaging,clean)

---

nx.json
scripts/api-extractor/package.json
scripts/babel/package.json
scripts/beachball/package.json
scripts/cypress/package.json
scripts/dangerjs/package.json
scripts/executors/package.json
scripts/github/package.json
scripts/gulp/package.json
scripts/jest/package.json
scripts/lint-staged/package.json
scripts/monorepo/jest.config.js
scripts/monorepo/package.json
scripts/package-manager/package.json
scripts/perf-test-flamegrill/package.json
scripts/prettier/package.json
scripts/projects-test/package.json
scripts/puppeteer/package.json
scripts/storybook/package.json
scripts/tasks/package.json
scripts/triage-bot/package.json
scripts/ts-node/package.json
scripts/update-release-notes/package.json
scripts/utils/package.json
scripts/webpack/package.json
tools/eslint-rules/project.json
tools/workspace-plugin/package.json
tools/workspace-plugin/project.json

- we don't use any nx functionality for actual task execution ( jest/gulp only )
future of our monorepo setup is via inferred project targets ( project crystal ) - https://nx.dev/concepts/inferred-tasks#inferred-tasks-project-crystal
This PR enables inferred projects for all projects within `scripts/` and `tools/` for initial testing. Once proved valid and bug free all v9 projects will be migrated as well.
**These changes are also a breaking change:** 
- `yarn workspace <package-name> <npm-script-alias>` won't work anymore for `test` and `lint` targets
- `nx run` becomes the only/unified option how to run things

chore(tools/*,scripts/*): enable nx plugins with project crystal for non production projects

---

change/@fluentui-react-teaching-popover-1b16f4a4-81fe-422a-8c82-df7ce282508f.json
packages/react-components/react-teaching-popover/library/src/components/TeachingPopoverBody/useTeachingPopoverBodyStyles.styles.ts
packages/react-components/react-teaching-popover/library/src/components/TeachingPopoverSurface/useTeachingPopoverSurfaceStyles.styles.ts

Image was hardcoded to width: 288px
TeachingPopoverSurface was incorrectly hardcoded to width:288px (should be 320px)
Image was reduced in size but overflowed when autosizing was enabled.
TeachingPopoverSurface now set to correct 320px bound width
TeachingPopoverBody now does not set a width on image, and instead lets it grow within bounds while respecting height/aspect ratio
- Fixes #32362

TeachingPopover: Fix popover width and image bounds

---

change/@fluentui-react-button-e7f98b68-84a6-495a-81fa-cc5ac0eda06f.json
packages/react-components/react-button/library/src/components/SplitButton/useSplitButtonStyles.styles.ts

The menuButton was 23px wide by default, failing the new WCAG 2.2 minimum target size requirement by 1px.
The `min-width` of the menubutton is set to `24px` for all sizes of splitbuttons. Toshie already got sign-off on the change (including for small splitbuttons) from partners, so we should be good to change the visuals.

fix: SplitButton menuButton is at least 24px wide

---

change/@fluentui-react-4910fb47-83b1-40c5-b50c-817986591a43.json
change/@fluentui-react-spinbutton-50c2d986-4df0-4438-80de-bb73d06f377d.json
packages/react-components/react-spinbutton/library/src/components/SpinButton/SpinButton.test.tsx
packages/react-components/react-spinbutton/library/src/components/SpinButton/useSpinButton.tsx
packages/react/src/components/SpinButton/SpinButton.base.tsx
packages/react/src/components/SpinButton/SpinButton.test.tsx
packages/react/src/components/SpinButton/__snapshots__/SpinButton.test.tsx.snap

We had an `aria-valuenow` attribute on native `<input>` elements in both v8 and v9 SpinButtons. This caused issues for a couple reasons:
- For a native input element, the `value` attribute is primarily used for exposing the current value to AT users, and screen reader users should always be aware of what is currently presented as the input's value in a native control
- the `aria-valuenow` attribute has mixed support when used to conflict with the native input element's value (though it's fine in other fully-ARIA-created non-native form fields)
- We weren't updating the `aria-valuenow` attribute as the user typed, so it was getting out-of-sync with the native value, exacerbating these issues.
- Narrator was announcing first the value, then the `aria-valuenow` after some value changes
No …

fix: remove aria-valuenow from native input element

---

change/@fluentui-react-carousel-preview-fd37cbb3-3f11-4223-90f6-6ad05568e151.json
packages/react-components/react-carousel-preview/library/etc/react-carousel-preview.api.md
packages/react-components/react-carousel-preview/library/src/components/Carousel/Carousel.types.ts
packages/react-components/react-carousel-preview/library/src/components/Carousel/useCarousel.ts
packages/react-components/react-carousel-preview/library/src/components/Carousel/useCarouselStyles.styles.ts
packages/react-components/react-carousel-preview/library/src/components/CarouselCard/useCarouselCard.ts
packages/react-components/react-carousel-preview/library/src/components/CarouselSlider/useCarouselSliderStyles.styles.ts
packages/react-components/react-carousel-preview/library/src/components/useEmblaCarousel.ts

Drag behavior disabled
Clicking an out of view item will jump index
Enables drag scroll behavior on carousel, will disable mouse click focus on non-visible items so that the view does not jump when grabbed from edges.
Focusing an out of view item (either by keyboard or accessibility tooling) will still enable index jump.

Carousel: Drag scroll

---

change/@fluentui-react-card-c7210dae-bb58-40a1-99ee-7334aaaa6ad7.json
change/@fluentui-react-carousel-preview-f78217f2-d0d0-4954-827d-b3c45758e8d7.json
change/@fluentui-react-checkbox-1746366e-d12f-4331-a559-41f4f5255f47.json
change/@fluentui-react-dialog-7cf46de8-6bff-4b17-a484-c87cb1a43539.json
change/@fluentui-react-drawer-c22ff307-e061-4632-a59b-cdc1791669e0.json
change/@fluentui-react-select-e83d2ef3-b053-4d9e-b8e0-5eacc561d58f.json
change/@fluentui-react-utilities-7f549d04-8b5c-4106-a0ab-2d7ded381d9f.json
packages/react-components/react-card/library/src/components/CardHeader/renderCardHeader.tsx
packages/react-components/react-carousel-preview/library/etc/react-carousel-preview.api.md
packages/react-components/react-carousel-preview/library/src/components/CarouselNavImageButton/CarouselNavImageButton.types.ts
packages/react-components/react-checkbox/library/src/components/Checkbox/renderCheckbox.tsx
packages/react-components/react-dialog/library/etc/react-dialog.api.md
packages/react-components/react-dialog/library/src/components/Dialog/Dialog.types.ts
packages/react-components/react-dialog/library/src/components/Dialog/renderDialog.tsx
packages/react-components/react-dialog/library/src/components/DialogSurface/renderDialogSurface.tsx
packages/react-components/react-drawer/library/src/components/OverlayDrawer/OverlayDrawer.types.ts
packages/react-components/react-drawer/library/src/components/OverlayDrawer/renderOverlayDrawer.tsx
packages/react-components/react-motion/library/src/slots/presenceMotionSlot.test.tsx
packages/react-components/react-select/library/src/components/Select/renderSelect.tsx
packages/react-components/react-utilities/src/compose/assertSlots.test.tsx
packages/react-components/react-utilities/src/compose/assertSlots.ts

1. adds to `assertSlot` a verification to ensure that if the slot declaration is `NonNullable` this will be respected
2. updates types accordingly on:
* `react-dialog`
* `react-checkbox`
* `react-card`
* `react-drawer`
* `react-select`
* `react-carousel-preview`
3. adds internal slots for components with motion slots. Motion slots have an incompatible signature between `Props` and `State`, on `Props` they support being nullable while in `State` a motion slot should never be nullable.
> This is a _band-aid_ 🩹🤕, not a proper solution. The problem here lies on a previous generalization where we use the same slot type declaration for both `Props` and `State` declaration. This generalization is problematic as there are differences between internal and external values. A proper solution should …

fix(react-utilities): ensures assertSlots keeps non nullables

---

tools/workspace-plugin/executors.json
tools/workspace-plugin/src/executors/clean/executor.spec.ts
tools/workspace-plugin/src/executors/clean/executor.ts
tools/workspace-plugin/src/executors/clean/schema.d.ts
tools/workspace-plugin/src/executors/clean/schema.json

> 💡 What is nx executor ? https://nx.dev/concepts/executors-and-configurations
- implements `clean` executor
- replacement npm script alias `clean`  that uses `just-scripts clean`

feat(workspace-plugin): implement clean executor

---

change/@fluentui-web-components-330ad1cf-b85e-4b1a-9495-754afccbe2e5.json
packages/web-components/src/_docs/developer/polyfilling.stories.mdx
packages/web-components/src/divider/divider.options.ts
packages/web-components/src/divider/divider.spec.ts
packages/web-components/src/divider/divider.stories.ts
packages/web-components/src/divider/divider.ts
packages/web-components/src/image/image.options.ts
packages/web-components/src/image/image.stories.ts
packages/web-components/src/image/image.ts
packages/web-components/src/index.ts
packages/web-components/src/link/index.ts
packages/web-components/src/link/link.styles.ts
packages/web-components/src/menu/menu.ts

- Missing `LinkStyles` export
- Missing `MessageBar` exports
- `default` options unnecessary
- Adds `LinkStyles` export
- Adds all `MessageBar` exports
- removes unneccesary `margin` and `padding` styles from `LinkStyles`
- removes `default` option from ComponentOptions
- fixes Baseline table in docs (broken in SB7 upgrade)
- removes unnecessary `false` assignments on `optional?: boolean = false` attributes

chore(web-components): add missing exports and cleanup options

---

packages/react-examples/src/react/DetailsList/DetailsList.Advanced.Example.tsx
packages/react-examples/src/react/DetailsList/DetailsList.CustomColumns.Example.tsx
packages/react-examples/src/react/DetailsList/DetailsList.CustomGroupHeaders.Example.tsx
packages/react-examples/src/react/DetailsList/DetailsList.DragDrop.Example.tsx
packages/react-examples/src/react/DetailsList/DetailsList.KeyboardAccessibleResizeAndReorder.Example.tsx
packages/react-examples/src/react/DetailsList/DetailsList.NavigatingFocus.Example.tsx

Underlines were not provided for links in the table and they did not have a 3:1 contrast against the other text, so it was not obvious the text in the DetailsList examples were links.
Links in DetailsList now have underlines.
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/19430)

fix(v8 DetailsList): Add underline to all links

---

change/@fluentui-web-components-46c9b695-18dc-4cad-a957-29ebaf4b1645.json
packages/web-components/src/button/button.styles.ts

- Missing Primary button appearance in forced-colors mode
- Add primary button appearance in forced-colors mode
- Improve disabled state in forced-colors mode
- Fixes #32408 
| | Before | After |
|---|---|---|
|Light | ![Screenshot 2024-08-29 at 10 33 54 AM](https://github.com/user-attachments/assets/03cd71c1-e841-43c3-a794-b7310da6ddbb) | ![Screenshot 2024-08-29 at 10 27 41 AM](https://github.com/user-attachments/assets/ec78eb2e-4164-412c-a7ed-1c84a2cea72a) |
| Dark | ![Screenshot 2024-08-29 at 10 34 04 AM](https://github.com/user-attachments/assets/9eb7a32d-6710-4dbb-a93d-6d02739cb573) | ![Screenshot 2024-08-29 at 10 27 10 AM](https://github.com/user-attachments/assets/fd3e7210-9f70-46b7-be39-283da2e41deb) |

fix(web-components): add button primary forced colors

---

change/@fluentui-react-tabs-00427f46-b6ea-45d8-989f-a7e2d94bd0bf.json
packages/react-components/react-tabs/library/src/components/Tab/useTabAnimatedIndicator.styles.ts

Tab component skips animation for falsy values.
This is valid example of usage of tab components (`value={0}`), but the animation is skiped because 
```tsx
<TabList {...props}>
<Tab value={0}>First Tab</Tab> /* <= Nullable value */
<Tab value={1}>Second Tab</Tab>
<Tab value={2}>Third Tab</Tab>
</TabList>
```
https://github.com/user-attachments/assets/888e2ea3-9241-4fc4-a7b6-1f41305094fa
The animation for the Tab component works as expected for tabs with all types of values, including the falsy ones.
https://github.com/user-attachments/assets/6235020c-620a-4080-9f0c-d91bda37b994
- Fixes #32293

fix(react-tabs): Improve animation for active tab indicator on tabs with falsy values

---

packages/react-examples/src/react/DetailsList/DetailsList.Advanced.Example.tsx
packages/react-examples/src/react/DetailsList/DetailsList.Animation.Example.tsx
packages/react-examples/src/react/DetailsList/DetailsList.Basic.Example.tsx
packages/react-examples/src/react/DetailsList/DetailsList.Compact.Example.tsx
packages/react-examples/src/react/DetailsList/DetailsList.CustomColumns.Example.tsx
packages/react-examples/src/react/DetailsList/DetailsList.Documents.Example.tsx
packages/react-examples/src/react/DetailsList/DetailsList.DragDrop.Example.tsx
packages/react-examples/src/react/DetailsList/DetailsList.KeyboardAccessibleResizeAndReorder.Example.tsx
packages/react-examples/src/react/DetailsList/DetailsList.KeyboardOverrides.Example.tsx
packages/react-examples/src/react/DetailsList/DetailsList.ProportionalColumns.Example.tsx
packages/react-examples/src/react/DetailsList/docs/DetailsListBestPractices.md

Voice control had no way of accessing the `onItemInvoked` behavior of DetailsList.
In the default DetailsList story, a clickable link was added for the file to allow voice control users to access the `onItemInvoked` behavior.
A documentation update was added for guidance on using `onItemInvoked` with a clickable element like button or link so that voice control users are also able to access it.
I removed the `onItemInvoked` behavior from stories that do not explicitly need it.
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/20670)

fix(v8 DetailsList): Stories and doc update for `onItemInvoked` prop, remove unnecessary instances

---

change/@fluentui-react-tree-c00b8f2d-0e5d-4f88-8d83-28cac9a82913.json
packages/react-components/react-tree/library/src/components/Tree/Tree.cy.tsx
packages/react-components/react-tree/library/src/components/TreeItem/useTreeItem.tsx

`TreeItem.onClick` is being called on:
1. `expandIcon` click
2. `actions` click
3. `selection` click
4. subtree click
Since https://github.com/microsoft/fluentui/pull/31766 we do not support `onOpenChange` for non branch `TreeItem`, users will have to rely more on `onClick` handler.
1. Ensures that `onClick` handler is not called if the click comes from an inner part of the `TreeITem`
2. Adds test to ensure behavior
Click events are still being emitted, we're just not calling `props.onClick` from `TreeItem` level, if you listen to the click event from another DOM element that event can still be captured as it was emitted

bugfix(react-tree): ensure onClick handler is not called on every click

---

change/@fluentui-web-components-2580bc63-8c6b-4d6e-aaa2-774cabe4b080.json
packages/web-components/package.json

The default exports for components pointed to the `define.js` files. This is convenient when you want to import the side-effectful `define()` calls for the browser. However, importing specific exports from components has to be done at the top level.
* The default exports for all components come from `<component-name>.js`
* Modules with `define()` calls can be imported at `<component-name>/define.js`
* Option exports can be imported from `<component-name>/options.js`
* Per-component template exports can be imported directly from `<component-name>/template.js`
* Per-component style exports can be imported directly from `<component-name>/styles.js`
* Per-component definitions can be imported directly from `<component-name>/definition.js`
This PR also changes the `sideEffects` array to use …

chore(web-components): Normalize exports paths

---

change/@fluentui-web-components-602be538-f67a-46e2-a2ff-4b1a0c38e5e3.json
packages/web-components/package.json

The changes introduced in #32451 changed the component exports to point to the component barrel files. This breaks current behavior for downstream users.
* `<component-name>.js` exports point to `<component-name>/define.js`
* `<component-name>/index.js` exports point to `<component-name>/index.js`

fix(web-components): restore define modules as default exports

---

change/@fluentui-web-components-fbe83ca6-95b0-48ac-a8c5-dcdd07033e4d.json
packages/web-components/docs/api-report.md
packages/web-components/src/index.ts
packages/web-components/src/textarea/index.ts
packages/web-components/src/textarea/textarea.options.ts
packages/web-components/src/textarea/textarea.ts

- No export for `TextAreasAppearanceForDisplayShadow`
- Add export for `TextAreaAppearancesForDisplayShadow`
- Removed unused `TextArea(Horizontally|Vertically)ResizableResize` options
- Removed `TextAreaResizableResize` and updated `toggleState` logic.
- Fixes #

chore(web-components): add missing export for textarea

---

change/@fluentui-react-overflow-f9979cd2-b20b-4857-97e8-4e9436f5353d.json
packages/react-components/react-overflow/library/src/useOverflowContainer.ts
packages/react-components/react-overflow/stories/src/Overflow/Default.stories.tsx

Adds an effect dependency exception to overflowManager creation in `useOverflowContainer` as it resulted in always recreating the overflowManager because the first mount flag would change.

fix(useOverflowContainer): Removes double overflowManager creation

---

apps/public-docsite-v9/src/DocsComponents/FluentDocsPage.stories.tsx
packages/react-components/react-motion/stories/src/CreateMotionComponent/index.stories.ts
packages/react-components/react-motion/stories/src/CreatePresenceComponent/index.stories.ts
packages/react-components/react-motion/stories/src/PresenceGroup/index.stories.ts

motion stories provided invalid `Meta` configuration resulting in throwing error when rendering stories 
Motion stories render
- motion stories provide valid `Meta`
- docsite-v9 adds extra `primaryStory` assertion in order to provide better DX what went wrong 
- <img width="971" alt="image" src="https://github.com/user-attachments/assets/56391be5-c737-46f1-9f2e-b07a9053221c">
- Fixes https://github.com/microsoft/fluentui/issues/32461
- Follows https://github.com/microsoft/fluentui/pull/32382

fix(docsite-v9): make motion docs work

---

packages/react-components/react-charts-preview/library/src/components/CommonComponents/Popover.tsx

Fixed the following issues:
1. Hover card is hiding the hovered point
2. LC Multiple - Hovering over the hover card is expanding the chart area.

Fixed popover size and cover target issue

---

packages/react-components/react-portal/stories/src/toMountNodeProps/index.stories.tsx
packages/react-components/react-shared-contexts/stories/src/UseAnnouce/index.stories.tsx

https://react.fluentui.dev/?path=/docs/utilities-aria-live-useannounce--docs and https://react.fluentui.dev/?path=/docs/components-portal-tomountnodeprops--docs were broken because of not valid story meta definition, `component: null` is not supported by Storybook.
Eliminate the `component: null` and include the `as Meta` type to ensure the Storybook's meta is valid.
- Fixes #32468 
- Followup for https://github.com/microsoft/fluentui/pull/32465#issuecomment-2331263715

fix(public-docsite-v9): fix toMountNodeProps and UseAnnounce broken pages

---

change/@fluentui-react-cf56ad85-cf3b-42ac-9943-864995577608.json
packages/react/src/components/ColorPicker/ColorPicker.base.tsx

Since ColorPicker never used FocusRects within its own code, it will not show focus outlines unless another v8 Fluent component also exists on the page.
Includes `<FocusRects>`
Fixes a partner bug where ColorPicker was the only remaining v8 control in the UI, and did not show focus outlines.

fix: v8 ColorPicker initializes focus outlines

---

.github/CODEOWNERS

This PR updates most packages owned by `cxe-red` with `cxe-prg` as we're transferring them.

fix(codeowners): update most packages owned by cxe-red with cxe-prg

---

packages/react-components/react-charts-preview/library/src/components/Legends/Legends.styles.ts
packages/react-components/react-charts-preview/library/src/components/Legends/OverflowMenu.tsx

Fixed the following legend related bugs:
1. Axis titles are getting cropped by legends
2. Legends overflow - Hovering over the button is showing 2 areas. One in white and one in grey. Moving from 1 selection to next resets the selection briefly

Fixed legend related bugs

---

change/@fluentui-react-tree-b6607987-a159-4abc-be0c-225294e9e8a7.json
packages/react-components/react-tree/library/etc/react-tree.api.md
packages/react-components/react-tree/library/src/components/FlatTree/useFlatTree.ts
packages/react-components/react-tree/library/src/components/FlatTree/useFlatTreeContextValues.ts
packages/react-components/react-tree/library/src/components/Tree/Tree.cy.tsx
packages/react-components/react-tree/library/src/components/Tree/useTree.ts
packages/react-components/react-tree/library/src/components/Tree/useTreeContextValues.ts
packages/react-components/react-tree/library/src/components/TreeItem/useTreeItem.tsx
packages/react-components/react-tree/library/src/contexts/treeContext.ts
packages/react-components/react-tree/library/src/hooks/useFlatTreeNavigation.ts
packages/react-components/react-tree/library/src/hooks/useRootTree.ts
packages/react-components/react-tree/library/src/hooks/useRovingTabIndexes.ts
packages/react-components/react-tree/library/src/hooks/useTreeNavigation.ts

1. Adds `forceUpdateRovingTabIndex` to `TreeContextValue`
2. `TreeItem` cleanup calls `forceUpdateRovingTabIndex` to ensure `Tree` will not face `tabIndex=-1` limbo
3. Adds tests to ensure 2 `tabIndex=-1` recover scenarios
* remove last focused treeitem
* collapse parent of last focused treeitem
- Fixes #

bugfix(react-tree): recover from tabIndex=-1 when TreeItem is removed

---

change/@fluentui-react-charting-fbf8562f-4d14-45f5-b74e-75304b828612.json
packages/react-charting/src/components/LineChart/LineChart.base.tsx

When optimizeLargeData is true, the line chart cannot have dashed lines
When optimizeLargeData is true, the line chart can have dashed lines
Created for this discussion: https://github.com/microsoft/fluentui/discussions/32449

Add strokeDasharray property when optimizeLargeData is true

---

tools/workspace-plugin/src/executors/verify-packaging/executor.spec.ts
tools/workspace-plugin/src/executors/verify-packaging/executor.ts

> 💡 What is nx executor ? https://nx.dev/concepts/executors-and-configurations
- implements `verify-packaging` executor
- replacement for npm script alias `verify-packaging` which uses `just-scripts`

feat(workspace-plugin): implement verify-packaging executor

---

change/@fluentui-react-dialog-a4232c34-ea7b-4222-a164-74574abfa9e1.json
packages/react-components/react-dialog/library/src/utils/useDisableBodyScroll.ts

When calculating whether scrollbars are present, we compare the body's clientHeight to the window's innerHeight.
In the case when this height is a fractional value, `clientHeight` rounds to the nearest integer whereas `innerHeight` always rounds down. This means when the body is set to 100% height and the browser is at a fractional height (usually due to a non-100% zoom factor), clientHeight often reports being 1 pixel taller than innerHeight. 
This causes the `scrollbar-gutter: stable` style to be added, which reserves space for the non-existent scrollbar, shifting the layout.
Repro: 
https://stackblitz.com/edit/u47vqq?file=index.html
Match `innerHeight`'s rounding behaviour by using `body.getBoundingClientRect().height` and manually rounding down.
According to mdn, …

fix (react-dialog): Use consistent rounding for clientHeight and innerHeight

---

change/@fluentui-react-drawer-6bf581dd-1ead-41a7-8f5c-1e543da04967.json
packages/react-components/react-drawer/library/src/components/DrawerBody/useDrawerBody.ts

Update scroll state when DrawerBody children content changes. This updates the Drawer state so the components can update as well.
- Fixes #32201

fix(react-drawer): update scroll state when children changes

---

tools/workspace-plugin/src/executors/clean/executor.ts
tools/workspace-plugin/src/executors/generate-api/executor.ts
tools/workspace-plugin/src/executors/type-check/executor.ts
tools/workspace-plugin/src/executors/verify-packaging/executor.ts
tools/workspace-plugin/src/utils.ts

No logs in verbose mode on CI, how long did a task execution take
This PR implements time measurement utils and integrates them with our custom executors
- when using our executors we will get measurement data on CI runs
- this output will be present only in verbose mode: (`--verbose` or `NX_VERBOSE_LOGGING=true`)
**Demo:**
- Temporary workaround for https://github.com/nrwl/nx/discussions/27712
- Implements partially #30267

feat(workspace-plugin): implement simple node measure execution utils

---

nx.json
scripts/api-extractor/project.json
scripts/babel/project.json
scripts/beachball/project.json
scripts/cypress/project.json
scripts/dangerjs/project.json
scripts/executors/project.json
scripts/fluentui-publish/project.json
scripts/generators/project.json
scripts/github/project.json
scripts/gulp/project.json
scripts/jest/project.json
scripts/lint-staged/project.json
scripts/monorepo/project.json
scripts/package-manager/project.json
scripts/perf-test-flamegrill/project.json
scripts/prettier/project.json
scripts/projects-test/project.json
scripts/puppeteer/project.json
scripts/storybook/project.json
scripts/tasks/project.json
scripts/test-ssr/project.json
scripts/triage-bot/project.json
scripts/ts-node/project.json
scripts/update-release-notes/project.json
scripts/utils/project.json
scripts/webpack/project.json

`dependsOn` for `type-check` doesn't work for projects using npm-scripts
> **Note:**  🚨 this is affecting all v9 projects
`dependsOn` works as before
- Fixes regression introduced in https://github.com/microsoft/fluentui/pull/32371/files#diff-15552e50b1b7c05b05b7ffe08ee47b5ed62b8d2039229c58972a42fd22a7381cR38

fix: make type-check target use targetDefault dependsOn definition for all monorepo projects

---

packages/react-components/react-message-bar/stories/src/MessageBar/MessageBarDescription.md

Adds a reference to the AriaLiveAnnouncer so users can know that it must be configured to announcements to function correctly

docs(MessageBar): Add reference to AriaLiveAnnouncer

---

change/@fluentui-react-nav-preview-8415b62b-8398-424c-9b31-d1ee026e9b99.json
packages/react-components/react-nav-preview/library/etc/react-nav-preview.api.md
packages/react-components/react-nav-preview/library/src/SplitNavItem.ts
packages/react-components/react-nav-preview/library/src/components/SplitNavItem/SplitNavItem.test.tsx
packages/react-components/react-nav-preview/library/src/components/SplitNavItem/SplitNavItem.tsx
packages/react-components/react-nav-preview/library/src/components/SplitNavItem/SplitNavItem.types.ts
packages/react-components/react-nav-preview/library/src/components/SplitNavItem/__snapshots__/SplitNavItem.test.tsx.snap
packages/react-components/react-nav-preview/library/src/components/SplitNavItem/index.ts
packages/react-components/react-nav-preview/library/src/components/SplitNavItem/renderSplitNavItem.tsx
packages/react-components/react-nav-preview/library/src/components/SplitNavItem/useSplitNavItem.ts
packages/react-components/react-nav-preview/library/src/components/SplitNavItem/useSplitNavItemStyles.styles.ts
packages/react-components/react-nav-preview/library/src/index.ts

Scaffolds SplitNavItem.
Result of running `yarn create-component` and removing the extra story files.

Scaffolds SplitNavItem

---

change/@fluentui-react-jsx-runtime-5bfd81c5-626e-4d33-a616-fe50df609366.json
packages/react-components/react-jsx-runtime/README.md

- see PR title
- addresses https://github.com/microsoft/fluentui/pull/32439/files#r1751562920, https://github.com/microsoft/fluentui-contrib/pull/217#discussion_r1753686793
- Fixes #

docs(jsx-runtime): improve usage guide and fix invalid links to sb docs

---

packages/web-components/src/accordion-item/accordion-item.stories.ts
packages/web-components/src/anchor-button/anchor-button.stories.ts
packages/web-components/src/avatar/avatar.stories.ts
packages/web-components/src/badge/badge.stories.ts
packages/web-components/src/button/button.stories.ts
packages/web-components/src/checkbox/checkbox.stories.ts
packages/web-components/src/compound-button/compound-button.stories.ts
packages/web-components/src/counter-badge/counter-badge.stories.ts
packages/web-components/src/dialog-body/dialog-body.stories.ts
packages/web-components/src/dialog/dialog.stories.ts
packages/web-components/src/divider/divider.stories.ts
packages/web-components/src/helpers.stories.ts

Stories used old patterns and some arg controls were broken
Fixes arg controls and updates stories to better patterns.
Adds a check to remove object-based attributes from the code sample when reset to null.\
- Fixes #

fix: stories compound-button to divider

---

change/@fluentui-react-carousel-preview-96e37f6f-4669-4470-b6a7-3c06903806f9.json
packages/react-components/react-carousel-preview/library/etc/react-carousel-preview.api.md
packages/react-components/react-carousel-preview/library/src/components/Carousel/useCarousel.ts
packages/react-components/react-carousel-preview/library/src/components/Carousel/useCarouselContextValues.ts
packages/react-components/react-carousel-preview/library/src/components/CarouselButton/useCarouselButton.tsx
packages/react-components/react-carousel-preview/library/src/components/CarouselContext.ts
packages/react-components/react-carousel-preview/library/src/components/CarouselContext.types.ts
packages/react-components/react-carousel-preview/library/src/components/CarouselNavButton/useCarouselNavButton.ts
packages/react-components/react-carousel-preview/library/src/components/useEmblaCarousel.ts

- Carousel autoplay timer would not restart on nav, causing quick page changes sometimes.
- Carousel autoplay was stopping autoplay on any control mouseover/focus (incl. accessibility software).
- Carousel autoplay timer restarts on any nav changes.
- Carousel autoplay now only stops on any control mouseover/focus of carousel cards & slider itself (not including controls).

Carousel: Ensure autoplay is reset on interactions and correctly stops on slider focus/mouseover

---

docs/react-wiki-archive/BestPractices/Using-icons.md

Previous readme pointed to old sharepoint CDN that will eventually stop working for this solution, and should not be depended upon.
New text gives correct behavior of using res-1 or res-2 cdns
- Fixes #32861

update alternative cdn text

---

change/@fluentui-react-table-a47e4abb-986f-4876-8f3b-1d94487949f6.json
packages/react-components/react-slider/stories/src/Slider/SliderControlled.stories.tsx
packages/react-components/react-table/library/src/components/TableSelectionCell/useTableSelectionCell.tsx

If authors set `selectionCell: {{ invisible: true }}` without passing any data to the `radioIndicator` or `checkboxIndicator` slots, the radio/checkbox input would not be rendered in the DOM. For some (e.g. touch) screen reader and voice control users, this means that they would not be able to select rows.
Our examples do pass in data (an `aria-label`) to the indicator slot, so the issue does not show up in our docs site. While authors _should_ always pass in an accessible name to the indicator slot they're using, it's still better to have an unnamed radio or checkbox than to have none at all.
The `radioIndicator` and `checkboxIndicator` slots render by default even with `invisible: true`. The visuals don't change (`invisible` will cause the `opacity: 0` style to be added), just the DOM. …

fix: table selection checkbox or radio should be rendered even if invisible

---

change/@fluentui-react-button-87b1b58c-f4f5-4341-b7e9-348961287b4b.json
packages/react-components/react-button/library/src/components/MenuButton/useMenuButtonStyles.styles.ts

We had a stray `:hover` style that made icons invisible on hover in expanded menubuttons:
Uses the correct color token (Highlight) for the color, which matches the color/bg color pair used in Button's hover styles
Fixes an issue found while debugging icon high contrast color issues

fix: hovered menubutton icon does not disappear

---

change/@fluentui-react-drawer-ffcd33f0-21e3-4ccc-af34-d63229d2adf8.json
packages/react-components/react-drawer/library/src/shared/drawerMotions.test.ts
packages/react-components/react-drawer/library/src/shared/drawerMotions.ts

Animations were coming from the wrong direction
Animations now play from the correct direction
- Fixes #32916

fix(react-drawer): reversed animations

---

packages/web-components/.storybook/preview.mjs
packages/web-components/src/accordion-item/accordion-item.stories.ts

The source code display isn't formatted well. It includes comment nodes and nested templating can be difficult to read. Additionally, if a story result is a document fragment, it won't render a source code block.
* The code blocks are formatted with Prettier (standalone).
* If a story returns a document fragment, it will properly render a source block.
* This PR also replaces the content of the Accordion Item story with lorem ipsum text.

fix(web-components): storybook code display formatting

---

change/@fluentui-react-carousel-preview-23a76a75-878c-485b-89c5-0677ca5831c3.json
packages/react-components/react-carousel-preview/library/src/components/CarouselButton/useCarouselButton.tsx

Carousel icons were static icons even during LTR, causing them to face opposite directions
CarouselButton icons will point the correct direction by default even in LTR

Fix: LTR icons on carousel buttons

---

common/changes/office-ui-fabric-react/hotfix_13-hotfix-5.135.6_2024-09-24-08-09.json
packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.test.tsx
packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.tsx
packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.types.ts
packages/office-ui-fabric-react/src/components/ChoiceGroup/__snapshots__/ChoiceGroup.test.tsx.snap
packages/office-ui-fabric-react/src/components/ChoiceGroup/examples/ChoiceGroup.Basic.Example.tsx

Add `ariaLabel` prop for `ChoiceGroupOption`.

fix(hotfix/5.135.6): Add ariaLabel prop for ChoiceGroupOption

---

packages/react-components/react-charts-preview/library/src/components/CommonComponents/Popover.tsx
packages/react-components/react-charts-preview/library/src/components/CommonComponents/Popover.types.ts
packages/react-components/react-charts-preview/library/src/components/DonutChart/DonutChart.tsx
packages/react-components/react-charts-preview/library/src/components/DonutChart/DonutChart.types.ts
packages/react-components/react-charts-preview/library/src/components/HorizontalBarChart/HorizontalBarChart.tsx
packages/react-components/react-charts-preview/library/src/components/HorizontalBarChart/HorizontalBarChart.types.ts
packages/react-components/react-charts-preview/stories/src/DonutChart/DonutChartCustomCallout.stories.tsx
packages/react-components/react-charts-preview/stories/src/HorizontalBarChart/HorizontalBarChartCustomCallout.stories.tsx

Custom Popover element or custom popover props can be set using props.
Fixes custom popover issues for both Donut and Horizontal bar charts.

Adding support for custom Popover

---

change/@fluentui-react-cee72ab8-f9ab-4400-949b-d38ee4fabdc6.json
packages/react/src/components/Modal/Modal.base.tsx

`Modal` animation timer was not cleared on unmount.
`Modal` animation timer is cleared on unmount.
We don't have a repro case so it's not possible to be certain this fixes the issue but it is potentially a problem regardless.
- Fixes #32965

fix: clear Modal timer on component unmount

---

change/@fluentui-web-components-0ad28ef7-3eb4-49da-a2ea-31e53af4e811.json
packages/web-components/src/text/text.styles.ts

the catch all slotted selector was setting `display: inherit`, if the host has `display: contents` set it causes some html elements (SVG) to not render. 
https://drafts.csswg.org/css-display/#unbox-svg
Removes the inheritance of the `display`
- Fixes #

fix: [fluent-text] removes display inheritance so all html elements can render

---

packages/react-components/react-charts-preview/library/src/components/CommonComponents/CartesianChart.tsx
packages/react-components/react-charts-preview/library/src/components/CommonComponents/CartesianChart.types.ts
packages/react-components/react-charts-preview/library/src/components/CommonComponents/Popover.styles.ts
packages/react-components/react-charts-preview/library/src/components/CommonComponents/Popover.tsx
packages/react-components/react-charts-preview/library/src/components/CommonComponents/Popover.types.ts
packages/react-components/react-charts-preview/library/src/components/DonutChart/DonutChart.tsx
packages/react-components/react-charts-preview/library/src/components/HorizontalBarChart/HorizontalBarChart.tsx
packages/react-components/react-charts-preview/library/src/components/LineChart/LineChart.tsx
packages/react-components/react-charts-preview/library/src/components/VerticalBarChart/VerticalBarChart.tsx

Fixed the following bugs:
1. Fixed Callout for donut and horizontal bar dont have legend vertical line. The font size and popover size are not matching v8 callout equivalent.
2. Fixed Vertical Bar all examples - x value is not showing on the callout
3. Consolidating custom popover props
4. Fixing styles for Vertical bar chart especially isCalloutForStack prop

Fixed popover related bugs for Donut, HBC and VBC

---

apps/vr-tests/.storybook/preview.js
apps/vr-tests/src/utilities/StoryVariantDecorator.tsx
apps/vr-tests/src/utilities/ThemeProviderDecorator.tsx
apps/vr-tests/src/utilities/index.ts

- certain VR tests (see VR test diff in this PR) have broken baseline snapshots due to the component not being wrapped in a `ThemeProvider`
- all v8 VR tests now have a `ThemeProvider` wrapper by default which fixes the existing broken tests
- Fixes #32946

fix(vr-tests): v8 VR tests are now wrapped with a ThemeProvider by default

---

.storybook/preview.js
change/@fluentui-react-nav-preview-b9aea238-32a9-438f-808c-724f85dd2f66.json
packages/react-components/react-nav-preview/library/etc/react-nav-preview.api.md
packages/react-components/react-nav-preview/library/package.json
packages/react-components/react-nav-preview/library/src/components/SplitNavItem/SplitNavItem.types.ts
packages/react-components/react-nav-preview/library/src/components/SplitNavItem/renderSplitNavItem.tsx
packages/react-components/react-nav-preview/library/src/components/SplitNavItem/useSplitNavItem.tsx
packages/react-components/react-nav-preview/library/src/components/SplitNavItem/useSplitNavItemStyles.styles.ts
packages/react-components/react-nav-preview/library/src/components/sharedNavStyles.styles.ts
packages/react-components/react-nav-preview/stories/src/NavDrawer/SplitNavItems.stories.tsx
packages/react-components/react-nav-preview/stories/src/NavDrawer/VariableSizedItems.stories.tsx

This pull request introduces the `SplitNavSubItem` feature to the `@fluentui/react-nav-preview` package. The changes focus on adding support for `navSubItem` within `SplitNavItem` components, updating the related styles, and modifying the storybook examples to demonstrate the new functionality. We also add optional Tooltips to the icon buttons.
AI Gen below:
This pull request introduces several enhancements and new features to the `@fluentui/react-nav-preview` package, focusing on adding support for sub-navigation items, tooltips, and other UI improvements. The changes include updates to the component props, state management, and styles to accommodate these new features.
* [`packages/react-components/react-nav-preview/library/src/components/SplitNavItem/SplitNavItem.types.ts`](diffhunk://# …

[react-nav-preview]feat: Adds SplitNav*Sub*Item

---

packages/react-components/react-charts-preview/library/src/components/CommonComponents/Popover.styles.ts
packages/react-components/react-charts-preview/library/src/components/CommonComponents/Popover.tsx
packages/react-components/react-charts-preview/library/src/components/Legends/Legends.styles.ts
packages/react-components/react-charts-preview/library/src/components/Legends/Legends.tsx
packages/react-components/react-charts-preview/library/src/components/Legends/shape.tsx

Fixed the following bug: On selecting multiple shapes in line chart variant the legend shapes are coming very big

Fixed SVG shape related bug for line chart 

---

.devops/templates/runpublishvrscreenshot.yml
azure-pipelines.vrt-baseline.yml

The current version of `vr-approval-cli` is `0.4.5` which is generating outdated URLs.
This bumps the repo to `0.4.11` which generates correct URLs.

fix: Bump vr-approval-cli package

---

change/@fluentui-react-motion-b1633b2c-174b-4a91-936d-4d761d14218d.json
change/@fluentui-react-motion-components-preview-b135985c-054b-4ade-a67f-fb34089647ab.json
packages/react-components/react-motion-components-preview/library/etc/react-motion-components-preview.api.md
packages/react-components/react-motion-components-preview/library/src/components/Collapse/Collapse.ts
packages/react-components/react-motion-components-preview/library/src/index.ts
packages/react-components/react-motion-components-preview/library/src/types.ts
packages/react-components/react-motion-components-preview/stories/src/Collapse/CollapseCustomization.stories.md
packages/react-components/react-motion-components-preview/stories/src/Collapse/CollapseCustomization.stories.tsx
packages/react-components/react-motion/library/etc/react-motion.api.md
packages/react-components/react-motion/library/src/index.ts
packages/react-components/react-motion/library/src/types.ts

- Fixes #[32893](https://github.com/microsoft/fluentui/issues/32893)
The current mechanism for creating variants of motion components, `createPresenceComponentVariant`, has several shortcomings:
1. It doesn't support motion groups, where `enter` and `exit` are arrays of motion atoms. 
a. It's also not clear what the solution would look like, to target an array item in the existed override object.
3. The override object puts variant params in a nested object structure:
a. `duration` and `easing` are nested inside  `enter: { duration: ... }`, `exit: { duration: ... }`, and optionally `all: { duration: ...}` as a shortcut. 
b. This now looks less maintainable and more complicated to teach, compared to a flat structure, where all properties are on the same level, e.g. `{ enterEasing: ..., …

refactor(motion): simplify variant creation, starting with Collapse

---

change/@fluentui-react-carousel-a4f2fe14-2f61-4182-81d9-df0672b90ed5.json
packages/react-components/react-carousel/library/etc/react-carousel.api.md
packages/react-components/react-carousel/library/src/components/CarouselCard/useCarouselCard.ts
packages/react-components/react-carousel/library/src/components/CarouselSlider/CarouselSlider.types.ts
packages/react-components/react-carousel/library/src/components/CarouselSlider/CarouselSliderContext.ts
packages/react-components/react-carousel/library/src/components/CarouselSlider/useCarouselSlider.ts

Cards could only be navigated to the first/last card then stopped, despite visual order.
Card focus set animation to jump (to prevent auto-scroll issues in browser)
Card focus can now be navigated circular (to match circular prop)
Card focus will now animate, we may add a reduced motion option in the future which will set jump to true if desired.

Carousel: Enable circular card focus and animation on focus index change

---

tools/eslint-rules/index.ts
tools/eslint-rules/project.json
tools/eslint-rules/rules/no-missing-jsx-pragma.spec.ts
tools/eslint-rules/rules/no-missing-jsx-pragma.ts

no enforcement how to use custom jsx pragma for v9 Slot API within component implementation
- enforced usage of jsx pragma for v9 Slot API, driven by new `no-missing-jsx-pragma` workspace lint rule
- we use `runtime: 'automatic'` for lint configuration which enforces to use `@jsxImportSource` 
Rule covers various use-cases driven by `runtime: <type>` configuration. For v9 we use `automatic` which produces following lint capabilities:
> see [spec file fore thorough use cases](https://github.com/microsoft/fluentui/pull/32842/files#diff-160c8e689c6e93f923ae593f7a57f99b7ba47dd7f959734b1b793b870fe47a92) 
**❌ Examples of Incorrect code:**
1. using pragma that works with runtime classic
```tsx
/** @jsxRuntime classic */
/** @jsx createElement */
// ~~~~~~~~~~~~~~~~~ 🚨
import { createElement } …
```

feat(eslint-rules): implement `no-missing-jsx-pragma`  in order to automate and unify slot API usage

---

packages/web-components/src/horizontalbarchart/horizontalbarchart.template.ts
packages/web-components/src/horizontalbarchart/horizontalbarchart.ts

Charts as Web component

---

change/@fluentui-dom-utilities-ca7c88a2-3673-4cbe-97ce-12cfd661cebc.json
packages/dom-utilities/src/getParent.ts

With the changes made in #32996, the `parentElement instanceof HTMLElement` was returning a false negative. I'm not sure if it's because it's a React node rather than a DOM element or what; regardless, it caused some behavior in Outlook to break.
Given that #32996 had three separate changes to fix the underlying TypeError, I am reverting just this portion to fix this regression.

Partially revert changes in #32996

---

packages/react-components/react-table/stories/src/DataGrid/ResizableColumnsDisableAutoFit.stories.tsx
packages/react-components/react-theme/stories/src/Theme/typography/index.stories.mdx

Fix link to redirect to the correct place (--docs instead of --default)
Fixed spelling for DataGrid w/ resizable columns
- Fixes N/A

fix(docs): Misdirected link fix, docs spelling fixes

---

.gitignore
change/@fluentui-tokens-7b6f098e-f611-4292-adb9-4c0351d335cb.json
packages/tokens/.swcrc
packages/tokens/package.json
packages/tokens/playwright.config.ts
packages/tokens/project.json
packages/tokens/scripts/server.js
packages/tokens/scripts/test-esm.html
packages/tokens/src/native-esm.spec-e2e.ts
packages/tokens/tsconfig.e2e.json
packages/tokens/tsconfig.json
packages/tokens/tsconfig.lib.json
scripts/tasks/src/swc/index.ts
scripts/tasks/src/swc/swc.ts
scripts/tasks/src/swc/types.ts
scripts/tasks/src/swc/utils.spec.ts
scripts/tasks/src/swc/utils.ts

**`@fluentui/tokens`**
- enables full path resolution when compiling with `swc`(https://github.com/swc-project/swc/issues/8742) which add `.js` extension explicitly to all imports/exports for esm and commonjs module output
- **NOTE:** this behaviour is enabled IFF `jsc.baseUrl` is present within projects `.swcrc` configuration
- implements e2e with playwright that tests native ESM in real browser
- mitigates issues (https://github.com/microsoft/fluentui/issues/30795, https://github.com/microsoft/fluentui/issues/30802) where the issue was that we transformed 3rd party exports which led to creating invalid path according to map export ( `@swc/helpers` )
- Implements https://github.com/microsoft/fluentui/issues/30634
- Replaces https://github.com/microsoft/fluentui/pull/30770
- Resolves …

feat: add explicit `.js` file extensions to all relative import/export statement within built output to support native ESM within browser

---

nx.json
tools/workspace-plugin/src/plugins/clean-plugin.spec.ts
tools/workspace-plugin/src/plugins/clean-plugin.ts
tools/workspace-plugin/src/plugins/format-plugin.spec.ts
tools/workspace-plugin/src/plugins/format-plugin.ts
tools/workspace-plugin/src/plugins/shared.ts
tools/workspace-plugin/src/plugins/testing-utils/index.ts
tools/workspace-plugin/src/plugins/testing-utils/temp-fs.ts
tools/workspace-plugin/src/plugins/type-check-plugin.spec.ts
tools/workspace-plugin/src/plugins/type-check-plugin.ts

- implements [inferred (project crystal) workspace plugins](https://nx.dev/concepts/inferred-tasks) in order to generate following task
- clean
- format, format:check
- type-check
- implements internal testing utils in order to provide testing capabilities to internal plugins 

feat(workspace-plugin): implement inferred plugins for clean,format,type-check targets

---

change/@fluentui-react-motion-components-preview-e49e73e0-27c3-4285-baf8-2ca1d7fc8efd.json
packages/react-components/react-motion-components-preview/library/src/components/Collapse/Collapse.ts
packages/react-components/react-motion-components-preview/stories/src/Collapse/CollapseDescription.md
packages/react-components/react-motion-components-preview/stories/src/Collapse/CollapseHorizontal.stories.md
packages/react-components/react-motion-components-preview/stories/src/Collapse/CollapseHorizontal.stories.tsx
packages/react-components/react-motion-components-preview/stories/src/Collapse/index.stories.ts

- `Collapse` only expands/collapses vertically, using height.
- Docs show only vertical collapse.
- A new `orientation` runtime parameter can be set to `'horizontal'`, to expand/collapse the width.
- `Collapse` default behavior is still a vertical collapse.
- Implementation code is worded generically, using `size` to stand in for either width or height. 
- Docs have a [story for horizontal collapse](https://fluentuipr.z22.web.core.windows.net/pull/32998/public-docsite-v9/storybook/index.html?path=/docs/motion-components-preview-collapse--docs#horizontal): 
- Fixes #32895
- PR https://github.com/microsoft/fluentui/pull/32999

feat(motion): Collapse `orientation` param & horizontal implementation

---

change/@fluentui-web-components-32b505fd-a856-47b9-9639-f9ce57af0ce4.json
packages/web-components/src/menu-item/menu-item.ts
packages/web-components/src/menu-list/menu-list.spec.ts

`change` custom event fires when `menu-item` becomes checked and unchecked. When role is set to `menuitemradio` and another menu-item is checked it's difficult to decern between the menu-item being checked and the menu-item being unchecked.
This change emits the current state of the checked property so a developer can properly listen for the item being checked.
- Fixes #

[fix][menu-item]: Emit current state when checked change event fires

---

change/@fluentui-web-components-941a8116-c21a-4ade-b542-db2e8a43500b.json
packages/web-components/src/button/button.styles.ts

The media query for buttons was incorrectly formatted.
The `transition-duration` property should apply to the `:host` selector when the media query matches `prefers-reduced-motion: reduce`.

fix(web-components): prefers-reduced-motion media query in button

---

yarn.lock

This PR fixes the CVE-2024-4068 vulnerability issue, by upgrading some dependencies, specially `braces` to `3.0.3`.

chore: upgrade dependencies to fix security vulnerabilities

---

change/@fluentui-react-carousel-973e8fc6-d327-490f-a135-a9100a53033c.json
package.json
packages/react-components/react-carousel/library/etc/react-carousel.api.md
packages/react-components/react-carousel/library/package.json
packages/react-components/react-carousel/library/src/components/Carousel/Carousel.types.ts
packages/react-components/react-carousel/library/src/components/Carousel/useCarousel.ts
packages/react-components/react-carousel/library/src/components/useEmblaCarousel.ts
packages/react-components/react-carousel/stories/src/Carousel/CarouselControlled.stories.tsx
packages/react-components/react-carousel/stories/src/Carousel/CarouselFirstRunExperience.stories.tsx
packages/react-components/react-carousel/stories/src/Carousel/index.stories.tsx
yarn.lock

- No fade motion present
- No example of Carousel in Modal
- New fade prop to enable fade in/out motion on carousel
- Modal story book added

Carousel: Fade and Carousel Modal example (FRE)

---

change/@fluentui-react-motion-components-preview-fe4b40ec-aa21-4a49-ad8a-b0eacc90a411.json
packages/react-components/react-motion-components-preview/library/src/components/Collapse/Collapse.test.ts
packages/react-components/react-motion-components-preview/library/src/components/Collapse/Collapse.ts
packages/react-components/react-motion-components-preview/library/src/testing/testUtils.ts

- If `animateOpacity` is`false`, the content's opacity is still set to `1` by the motion component.
- Although we'd expect the opacity to be `1` most of the time, it could be a different value and we shouldn't overwrite it when `animateOpacity` is `false`.
- If `animateOpacity` is`false`, the content's opacity is unaffected by the motion component.
- Implementation is refactored:
- Keyframes that mixed opacity with size are now separated to motion atoms for opacity and size.
- The opacity atoms are omitted from the generated motion when `animateOpacity` is `false`.
- Unit test for `Collapse` is updated to account for `enter` and `exit` being arrays of motion atoms.
- Fixes #33016

fix(Collapse): only affect opacity if `animateOpacity` is `true`

---

change/@fluentui-react-21794519-d3e0-4ade-b5f2-47752f379f80.json
packages/react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuButton.test.tsx
packages/react/src/components/KeytipData/useKeytipData.ts

In ContextualMenuItemAnchor and ContextualMenuItemButton, the `item.ariaDescription`'s `id` was overridden and not correctly associated because the `<KeytipData>` component would ignore the `ariaDescribedBy` prop and return `aria-describedby: undefined` if no keytip data was passed in.
Keytip always returns the passed-in `ariaDescribedBy` id if present.
- Fixes [ADO bug](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/17419)

fix: Keytip passes through describedBy id if passed in

---

change/@fluentui-eslint-plugin-e633733d-0e64-45b7-a37a-eea61b3caa8a.json
change/@fluentui-react-aria-f6b92f50-19e6-4c66-beaf-bdeec75f87c5.json
change/@fluentui-react-carousel-bb8b8cfa-dbb7-4094-aa50-39701e30ef7b.json
change/@fluentui-react-migration-v0-v9-f3f98053-be57-4569-9543-5160818b6385.json
change/@fluentui-react-nav-preview-bc353a18-51d4-4e8f-a44f-9be7cbe9d091.json
change/@fluentui-react-tag-picker-f9dff827-9ea3-4115-83e1-138279ba261d.json
change/@fluentui-react-teaching-popover-ee64a4be-b4cb-4d08-87f2-426507994031.json
packages/eslint-plugin/src/configs/react.js
packages/eslint-plugin/src/internal.js
packages/react-components/react-aria/library/src/AriaLiveAnnouncer/renderAriaLiveAnnouncer.tsx
packages/react-components/react-carousel/library/src/components/CarouselAutoplayButton/renderCarouselAutoplayButton.tsx
packages/react-components/react-carousel/library/src/components/CarouselButton/renderCarouselButton.tsx
packages/react-components/react-jsx-runtime/.eslintrc.json
packages/react-components/react-migration-v0-v9/library/src/components/ItemLayout/ItemLayout.tsx
packages/react-components/react-nav-preview/library/src/components/NavCategory/renderNavCategory.tsx
packages/react-components/react-nav-preview/library/src/components/NavCategoryItem/renderNavCategoryItem.tsx
packages/react-components/react-tag-picker/library/src/components/TagPickerOptionGroup/renderTagPickerOptionGroup.tsx
packages/react-components/react-teaching-popover/library/src/components/TeachingPopoverSurface/renderTeachingPopoverSurface.tsx

- see PR title
- updates affected projects including eslint-plugin react-config
- Follows https://github.com/microsoft/fluentui/pull/32838

chore: enable `@nx/workspace-no-missing-jsx-pragma` in whole monorepo

---

change/@fluentui-react-infolabel-3073ec02-8c14-4fef-976d-39ee32603aa0.json
packages/react-components/react-infolabel/library/src/components/InfoButton/useInfoButton.tsx

`e.relatedTarget` is null in Safari leading to incorrect dismissing behavior
https://github.com/user-attachments/assets/668815e3-b985-452b-85eb-6f27f8bb3c8b
https://github.com/user-attachments/assets/cd668f62-8d19-4f91-9e5e-62c40e6b3dae
- Fixes #31067

fix(react-infolabel): dismiss correctly after clicking on the infoButton in Safari

---

change/@fluentui-react-motion-components-preview-b271a894-6660-439a-aef6-8f008b144e56.json
packages/react-components/react-motion-components-preview/library/src/components/Collapse/Collapse.ts

- In the web box model, by design, setting the height of an element to zero does not affect the padding.
- Consequently, when `Collapse` has animated the height of the content element to 0, the content's padding remains visible, if `animateOpacity` is `false`.
- Also, when `animateOpacity` is `true` but `unmountOnExit` is `true`, the size of the padding is removed abruptly, causing a visual jump on unmount.
- The visual issue is visible in the [Collapse Customization story](https://react.fluentui.dev/?path=/docs/motion-components-preview-collapse--docs#customization):
- The content's padding is smoothly animated to zero automatically, using keyframes in the web animation.
- The fix is visible in the [Collapse Customization story in the preview …

fix(Collapse): handle content padding by animating it to zero

---

tools/workspace-plugin/src/plugins/clean-plugin.ts
tools/workspace-plugin/src/plugins/format-plugin.spec.ts
tools/workspace-plugin/src/plugins/format-plugin.ts
tools/workspace-plugin/src/plugins/shared.ts
tools/workspace-plugin/src/plugins/type-check-plugin.ts
tools/workspace-plugin/src/plugins/workspace-plugin.spec.ts
tools/workspace-plugin/src/plugins/workspace-plugin.ts

Implements [workspace-plugin that creates targets](https://nx.dev/concepts/inferred-tasks) based on project context in whole monorepo
- mitigates perf impact of plugin per task scenario ( see https://github.com/microsoft/fluentui/pull/33058)
- Follows https://github.com/microsoft/fluentui/pull/32393

feat(workspace-plugin): implement workspace inferred plugin

---

change/@fluentui-react-motion-components-preview-5ac64407-160d-4ad2-aaf7-e8923c092373.json
packages/react-components/react-motion-components-preview/library/etc/react-motion-components-preview.api.md
packages/react-components/react-motion-components-preview/library/src/components/Collapse/Collapse.ts
packages/react-components/react-motion-components-preview/library/src/components/Collapse/collapse-atoms.ts
packages/react-components/react-motion-components-preview/library/src/components/Collapse/collapse-types.ts
packages/react-components/react-motion-components-preview/library/src/index.ts
packages/react-components/react-motion-components-preview/stories/src/Collapse/CollapseDelayed.stories.md
packages/react-components/react-motion-components-preview/stories/src/Collapse/CollapseDelayed.stories.tsx
packages/react-components/react-motion-components-preview/stories/src/Collapse/index.stories.ts

- `Collapse` animates size (height or width) and opacity in sync: they start together and have the same duration.
- `CollapseDelayed` is a new variant that animates size and opacity separately: 
- Enter: size expands immediately, while the fade-in starts after a delay. 
- Exit: fade-out first, then size collapses after a delay.
- Added a `CollapseDelayed` example in Storybook.
- Extracted `Collapse` motion atom objects to reusable factory functions and moved them to a separate file.
- Moved `Collapse` types to a separate file as well.
- Fixes #33068

feat(Collapse): create CollapseDelayed variant

---

apps/vr-tests-react-components/src/stories/Menu/MenuItemSelectableWIthLongText.stories.tsx
change/@fluentui-react-menu-738a350f-94f7-49f4-a55a-6f5f807cf659.json
packages/react-components/react-menu/library/src/components/MenuItem/useMenuItemStyles.styles.ts
packages/react-components/react-menu/library/src/selectable/useCheckmarkStyles.styles.ts
packages/react-components/react-menu/stories/src/Menu/MenuAligningWithSelectableItems.stories.tsx

Sets `flex-shrink: 0` on icon and checkmark slots
Fixes #32979

fix: Align menu item long content with icon slots

---

change/@fluentui-react-motion-components-preview-4d993355-e9f1-49f7-93c4-a90c4af9c96d.json
packages/react-components/react-motion-components-preview/library/etc/react-motion-components-preview.api.md
packages/react-components/react-motion-components-preview/library/src/components/Fade/Fade.ts
packages/react-components/react-motion-components-preview/library/src/index.ts
packages/react-components/react-motion-components-preview/library/src/types.ts
packages/react-components/react-motion-components-preview/stories/src/Fade/FadeCustomization.stories.md
packages/react-components/react-motion-components-preview/stories/src/Fade/FadeCustomization.stories.tsx

- `Fade` motion component uses `createPresenceComponentVariant` to define variants.
- `Fade` motion component uses the new variant structure.
- Fixes #33081 
- Migrate `Scale`'s usage of `createPresenceComponentVariant`.
- Migrate unit tests that reference `createPresenceComponentVariant` and `overridePresenceMotion`.
- Delete `createPresenceComponentVariant` and `overridePresenceMotion` as unused and obsolete.

refactor(Fade): migrate to new variant structure

---

scripts/monorepo/src/getAffectedPackages.js

- see PR title
- once https://github.com/microsoft/fluentui/pull/33098 lands and we will enable the plugin it will log measurements on CI, which would create invalid json output for `getAffectedPackages`. This PR always forces non verbose mode on our API
- Follows https://github.com/microsoft/fluentui/pull/33098

fix(scripts/monorepo): silent nx verbose messages when invoking getAffectedPackages to emit valid JSON

---

apps/vr-tests-react-components/src/stories/Table/TableSubtleSelection.stories.tsx
apps/vr-tests-react-components/src/stories/Table/utils.tsx
change/@fluentui-react-table-f769575c-0588-4c39-b82a-b20389b9638a.json
packages/react-components/react-table/library/src/components/TableRow/useTableRowStyles.styles.ts
packages/react-components/react-table/library/src/components/TableSelectionCell/useTableSelectionCell.tsx

Extracts subtle selections styles in table row and applies them unconditionally always
Fixes #32904

fix: subtle selection should apply correctly to header rows

---

change/@fluentui-react-aria-a057ce6a-2aa9-4d0d-afa3-90191feb8fd4.json
change/@fluentui-react-button-cb3c039e-aafb-48df-8759-04567fadb59c.json
packages/a11y-testing/src/definitions/Link/linkBehaviorDefinition.ts
packages/a11y-testing/src/definitions/react-button/buttonAccessibilityBehaviorDefinition.ts
packages/react-components/react-aria/library/src/button/useARIAButtonProps.ts
packages/react-components/react-button/library/src/components/Button/Button.test.tsx
packages/react-components/react-button/library/src/components/Button/useButton.ts
packages/react-components/react-button/library/src/components/CompoundButton/CompoundButton.test.tsx
packages/react-components/react-button/library/src/components/MenuButton/MenuButton.test.tsx
packages/react-components/react-button/library/src/components/ToggleButton/ToggleButton.test.tsx

We've had this incorrect behavior in v9 for a while, but `<Button as="a" href={href}>` has been rendering as:
```html
<a href={href} type="button" role="button">
```
It's harmful to override the `role` of semantic links with `href` attributes for a number of reasons, primarily around screen readers no longer presenting link-specific built-in features when the role is overridden. Additionally, `type` is not a valid prop on `<a>` elements.
Also we'd been adding `tabindex` to link elements with `href` attributes, which is unnecessary.
When authors use `<Button as="a" href={href}>`, it now renders as a semantic link. The following edge cases are also handled:
- Button with `as=a` but no `href`: uses `role="button"` + `tabIndex`
- Button with `as=a`, `href`, and `disabled` or …

fix: Button with as=a and href should present as a semantic link

---

change/@fluentui-react-e3da4668-61a1-4a12-a488-fd618c230554.json
packages/react/src/components/SwatchColorPicker/ColorPickerGridCell.styles.ts
packages/react/src/components/SwatchColorPicker/__snapshots__/SwatchColorPicker.test.tsx.snap

In high contrast mode, there was not enough contrast between the white color and the background.
There is now a border around the white color in high contrast mode.
Confirmation that it works on Windows:
- Fixes [ADO bug](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/18609)

fix(v8 ColorSwatchPicker): Add border to white color in high contrast mode

---

change/@fluentui-react-overflow-a31beb0d-76b2-491e-add6-1f3fd27db85f.json
packages/react-components/react-overflow/library/etc/react-overflow.api.md
packages/react-components/react-overflow/library/src/Overflow.cy.tsx
packages/react-components/react-overflow/library/src/components/Overflow.tsx
packages/react-components/react-overflow/library/src/index.ts
packages/react-components/react-overflow/stories/src/Overflow/ListenToChanges.stories.tsx
packages/react-components/react-overflow/stories/src/Overflow/index.stories.tsx

Adds a callback to inform userland about overflow state to power features that are outside of the overflow component that need to know about overflow state.

feat: add `onOverflowChange` callback

---

change/@fluentui-web-components-cb8c9815-f5ec-4855-b020-72aec63d5760.json
packages/web-components/src/menu-item/menu-item.styles.ts
packages/web-components/src/menu/menu.styles.ts
packages/web-components/src/split-button/split-button.stories.ts

Using the old/deprecated CSS Anchor Positioning property names. (See details: https://github.com/microsoft/fluentui/pull/32987)
Update to the new ones.
Tested in Edge Canary:
- Fixes #

fix: change to new css anchor positioning properties

---

change/@fluentui-react-virtualizer-701a2cd4-bd8c-48af-a2d4-753903d62124.json
packages/react-components/react-virtualizer/library/etc/react-virtualizer.api.md
packages/react-components/react-virtualizer/library/src/components/Virtualizer/Virtualizer.types.ts
packages/react-components/react-virtualizer/library/src/components/Virtualizer/useVirtualizer.ts
packages/react-components/react-virtualizer/library/src/components/VirtualizerScrollViewDynamic/useVirtualizerScrollViewDynamic.tsx
packages/react-components/react-virtualizer/library/src/hooks/useDynamicVirtualizerMeasure.ts
packages/react-components/react-virtualizer/library/src/utilities/VirtualizerContext/VirtualizerContext.ts
packages/react-components/react-virtualizer/library/src/utilities/VirtualizerContext/types.ts
packages/react-components/react-virtualizer/stories/src/Virtualizer/Dynamic.stories.tsx
packages/react-components/react-virtualizer/stories/src/VirtualizerScrollViewDynamic/AutoMeasure.stories.tsx

Virtualizer used state to store the current scroll position in dynamically sized items to trigger a recalc of virtualizer length
Virtualizer depended on intersectionRect ratio being above zero
Virtualizer now uses a callback with new scroll position to calculate if a state update (virtualization length) update is nessecary
Virtualizer now uses isIntersecting to account for when intersectionRect may be rounded down to zero.

Virtualizer: Reduce state updates and fix intersection ratio detection

---

change/@fluentui-web-components-42dee933-09cf-43d3-84d7-c9f946dfa0cb.json
packages/web-components/src/menu/menu.styles.ts
packages/web-components/src/split-button/split-button.stories.ts

When split button is used, without additional external styles, the menu list is positioned left aligned with the split menu button.
The proper anchor positioning CSS is built-in in the component.
- Fixes #

fix: move proper menu positioning style for split button into the component css

---

packages/react-components/react-combobox/stories/src/Combobox/ComboboxVirtualizer.stories.tsx

Virtualized combobox optimized virtualization which prevented page up/down from having the DOM nodes nessecary for a full and consistent pagination.
We now render an additional ~10 items on each side of the buffer with appropriate buffer sizing for consistent re-rendering to enable standard pagination.
- Fixes #32220

Combobox: Update Virtualizer buffer sizing to accommodate page up/down

---

change/@fluentui-react-carousel-a81a3faa-36db-4ee8-b041-10bc72927e35.json
packages/react-components/react-carousel/library/etc/react-carousel.api.md
packages/react-components/react-carousel/library/src/components/Carousel/useCarousel.ts
packages/react-components/react-carousel/library/src/components/CarouselContext.types.ts
packages/react-components/react-carousel/library/src/components/pointerEvents.ts
packages/react-components/react-carousel/library/src/components/useEmblaCarousel.ts
packages/react-components/react-carousel/stories/src/Carousel/CarouselEventing.stories.tsx
packages/react-components/react-carousel/stories/src/Carousel/index.stories.tsx

Carousel was calling the index change callback on Button and Focus events only, preventing users from receiving callback information about drag events.
Drag event now correctly emits a native DOM event with type 'drag', this is driven directly by Embla engine and hence is native.

Carousel: Drag event based index callback

---

change/@fluentui-web-components-04faf08a-3fc9-47e1-bade-1f263207c6e5.json
packages/web-components/src/avatar/avatar.styles.ts
packages/web-components/src/checkbox/checkbox.styles.ts
packages/web-components/src/counter-badge/counter-badge.styles.ts
packages/web-components/src/field/field.styles.ts
packages/web-components/src/image/image.styles.ts
packages/web-components/src/label/label.styles.ts
packages/web-components/src/link/link.styles.ts
packages/web-components/src/menu-item/menu-item.styles.ts
packages/web-components/src/styles/states/index.ts
packages/web-components/src/text/text.styles.ts
packages/web-components/src/utils/element-internals.ts

States were defined as shared `css.partial` tagged template literals, which can't be tree-shaken.
Example:
```ts
const someState = css.partial`:is([state--some-state], :state(some-state))`;
const styles = css`
:host(${someState}) {
// ...
}
};
```
States are handled via a `state` function. This allows us to generate only either the `[state--{state}]` attribute selector or the `:state({state})` selector, depending on browser support. States are cached in a `Map` object so once it's generated, the cached value is returned.
```ts
const styles = css`
:host(${state('some-state')}) {
// ...
}
};
```

chore(web-components): replace state partials with state function

---

tools/workspace-plugin/src/executors/generate-api/executor.spec.ts
tools/workspace-plugin/src/executors/generate-api/executor.ts
tools/workspace-plugin/src/executors/generate-api/lib/shared.ts

on ADO `process.env.TF_BUILD` was never `true` rather `True` 🫡. 
This PR fixes this inconsistency that was affecting generate-api executor functionality on CI environment.
- Follows #30267

fix(workspace-plugin): properly resolve isCi on ADO

---

packages/web-components/docs/api-report.md
packages/web-components/src/accordion/accordion.stories.ts

Accordion story was not named so it automatically used "Docs"
Accordion story is now named "Accordion"
- Fixes #

chore: fix accordion story name

---

change/@fluentui-web-components-7bba75e2-576b-4e9f-821b-9501f016a3a6.json
packages/web-components/docs/api-report.md
packages/web-components/src/accordion-item/accordion-item.ts
packages/web-components/src/anchor-button/anchor-button.ts
packages/web-components/src/avatar/avatar.ts
packages/web-components/src/badge/badge.ts
packages/web-components/src/button/button.ts
packages/web-components/src/checkbox/checkbox.ts
packages/web-components/src/counter-badge/counter-badge.spec.ts
packages/web-components/src/counter-badge/counter-badge.ts
packages/web-components/src/divider/divider.ts
packages/web-components/src/image/image.ts
packages/web-components/src/label/label.ts
packages/web-components/src/link/link.ts
packages/web-components/src/menu-list/menu-list.spec.ts
packages/web-components/src/message-bar/message-bar.ts
packages/web-components/src/progress-bar/progress-bar.ts
packages/web-components/src/rating-display/rating-display.ts
packages/web-components/src/slider/slider.ts
packages/web-components/src/spinner/spinner.spec.ts
packages/web-components/src/spinner/spinner.ts
packages/web-components/src/tablist/tablist.spec.ts
packages/web-components/src/tablist/tablist.ts
packages/web-components/src/tabs/tabs.spec.ts
packages/web-components/src/text-input/text-input.ts
packages/web-components/src/text/text.spec.ts
packages/web-components/src/text/text.ts
packages/web-components/src/textarea/textarea.ts
packages/web-components/src/utils/element-internals.ts

For each instance where we're toggling between two states, we remove the previous state if it exists, and then apply the new state if it exists.
There are no checks to see if the new state getting checked is an allowed state for the attribute. This allows for arbitrary states to be applied, which can lead to unexpected behavior. For instance, an `appearance` attribute could be set to any value, and that value would be applied to `ElementInternals.states`.
It could also lead to state collisions, where setting something like `appearance="large"` would simultaneously be invalid ("large" is not a valid state for `appearance`), and would apply the `large` state to the `ElementInternals.states` set (`large` is a valid state for the `size` attribute, but the `size` attribute isn't set to …

chore(web-components): add hasMatchingState and swapStates functions

---

change/@fluentui-react-motion-components-preview-27662e3f-3d93-496c-8b66-b5de8fac23de.json
packages/react-components/react-motion-components-preview/library/etc/react-motion-components-preview.api.md
packages/react-components/react-motion-components-preview/library/src/components/Collapse/index.ts
packages/react-components/react-motion-components-preview/library/src/index.ts
packages/react-components/react-motion-components-preview/stories/src/Collapse/Collapse.stories.tsx
packages/react-components/react-motion-components-preview/stories/src/Collapse/CollapseDefault.stories.tsx
packages/react-components/react-motion-components-preview/stories/src/Collapse/CollapseDescription.md
packages/react-components/react-motion-components-preview/stories/src/Collapse/index.stories.ts
packages/react-components/react-motion-components-preview/stories/src/Fade/Fade.stories.tsx
packages/react-components/react-motion-components-preview/stories/src/Fade/index.stories.ts
packages/react-components/react-motion-components-preview/stories/src/Scale/Scale.stories.tsx
packages/react-components/react-motion-components-preview/stories/src/Scale/index.stories.ts

This PR updates the Collapse component documentation to clarify that it extends createPresenceComponent and inherits additional props and callbacks.
•	Added reference to createPresenceComponent props in Collapse docs.
•	Linked to the Presence Component Storybook page for further details.
- Fixes [#33132](https://github.com/microsoft/fluentui/issues/33132) [#33152](https://github.com/microsoft/fluentui/issues/33152)

fix(docs): Motion components storybook updates

---

packages/react-components/react-list-preview/stories/src/List/ListActiveElement.stories.tsx
packages/react-components/react-list-preview/stories/src/List/MultipleActionsDifferentPrimary.stories.tsx
packages/react-components/react-list-preview/stories/src/List/MultipleActionsSelection.stories.tsx
packages/react-components/react-list-preview/stories/src/List/MultipleActionsWithPrimary.stories.tsx
packages/react-components/react-list-preview/stories/src/List/SingleActionSelection.stories.tsx
packages/react-components/react-list-preview/stories/src/List/SingleActionSelectionControlled.stories.tsx
packages/react-components/react-list-preview/stories/src/List/SingleActionSelectionDifferentPrimary.stories.tsx

Updated the examples for List to fix most of the a11y issues found with the "Accessibility Insights for Web" tool.
2 remaining issues are:
on the tabster-specific elements. This is not actionable
on the selectable simple list items. This is okay, as the listbox behavior is emulated through mouse/keyboard handlers and checkbox is there only for visualization, and/or screen reader support.

Fix a11y issues in List examples

---

change/@fluentui-react-field-0ea84bed-f738-4788-87cc-114b0078db2d.json
packages/react-components/react-field/library/src/components/Field/Field.test.tsx
packages/react-components/react-field/library/src/components/Field/Field.types.ts
packages/react-components/react-field/library/src/components/Field/useField.tsx

We received an ADO bug about the `SearchBox` controlled example failing to announce the `validationMessage` for screenreaders, because the example was using `validationState="warning"`.
After communicating with Sarah, we decided that screenreaders should also announce for the warning `validationState`. The PR makes `validationState="warning"` apply `role="alert"` so it will be announced for screenreaders.
- Fixes [ADO Bug](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/22201)

fix(react-field): Add screenreader announcement for `validationMessage` if `validationState="warning"`

---

change/@fluentui-react-message-bar-dcc6ade3-1e4b-44ab-b29b-14b1cafc1320.json
packages/react-components/react-message-bar/library/src/components/MessageBar/useMessageBar.ts

I found this while investigating another bug and decided to put in a PR -- feel free to close if this is an unnecessary change.
We currently use `useAnnounce_unstable`, which is deprecated, instead of `useAnnounce`. The hooks are functionally the same. The change comes from #30328.
Use `useAnnounce`, the stable version of the old hook `useAnnounce_unstable`
N/A

chore(react-message-bar): Use `useAnnounce()` instead of the deprecated `useAnnounce_unstable()`

---

packages/react-components/react-tag-picker/stories/src/TagPicker/TagPickerAppearance.stories.tsx
packages/react-components/react-tag-picker/stories/src/TagPicker/TagPickerButton.stories.tsx
packages/react-components/react-tag-picker/stories/src/TagPicker/TagPickerDefault.stories.tsx
packages/react-components/react-tag-picker/stories/src/TagPicker/TagPickerDisabled.stories.tsx
packages/react-components/react-tag-picker/stories/src/TagPicker/TagPickerExpandIcon.stories.tsx
packages/react-components/react-tag-picker/stories/src/TagPicker/TagPickerGrouped.stories.tsx
packages/react-components/react-tag-picker/stories/src/TagPicker/TagPickerSecondaryAction.stories.tsx
packages/react-components/react-tag-picker/stories/src/TagPicker/TagPickerSize.stories.tsx
packages/react-components/react-tag-picker/stories/src/TagPicker/TagPickerTruncatedText.stories.tsx

The "No options available" option in `TagPicker` used to be just a text node, which meant it wasn't announced for screenreaders.
Using a `TagPickerOption` that cannot be selected allows for the message to be announced by screenreaders.
- Fixes [ADO Bug](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/22228)

fix(react-tag-picker): Change "No options available" from text to `TagPickerOption`

---

.github/workflows/bundle-size-comment.yml
.github/workflows/pr-website-deploy-comment.yml

- see PR title
- action inputs https://github.com/actions/download-artifact?tab=readme-ov-file#inputs
- Follows https://github.com/microsoft/fluentui/pull/33070

ci(.github): fix invalid download-artifact params

---

.github/workflows/bundle-size-base.yml
.github/workflows/pr-website-deploy-comment.yml

- az login needs token-id access https://github.com/microsoft/fluentui/actions/runs/11629896665/job/32387736735#step:6:18
- we grant permission and decouple bundle-size pipelines to separate "base" pipeline in order to safely grant permission to token-id
- Follows https://github.com/microsoft/fluentui/pull/33185

ci(.github): decouple bundle-size base CI in order to provide token-id permissions

---

.github/workflows/bundle-size-comment.yml
.github/workflows/pr-website-deploy-comment.yml

- we don't use deprecated syntax for dynamically set job outputs (https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
- web url properly points to azure website 
- Follows https://github.com/microsoft/fluentui/pull/33187

ci(.github): migrate from deprecated usage of set-output syntax and fix invalid deploy URL

---

.github/workflows/bundle-size-comment.yml
.github/workflows/pr-website-deploy-comment.yml

- resolves PR comments override each other from 2 different workflows
- resolves issues with loading custom script from file-system for comment job https://github.com/microsoft/fluentui/actions/runs/11632798450
- Follows https://github.com/microsoft/fluentui/pull/33190

ci(.github): make custom gha script accessible to workflow and don't override comments on PRs

---

.github/workflows/check-tooling.yml
scripts/executors/src/start.ts
tools/workspace-plugin/src/executors/generate-api/executor.ts

- feat: adds support to inferred projects 
- metadata retrieval for description
- target configurations unwrap into separate commands
- fix: generate-api `local` flag resolution on CI
- Follows https://github.com/microsoft/fluentui/pull/33074

feat(scripts-executors):  add inferred projects support to start experience

---

change/@fluentui-react-carousel-5e2a3d84-3b48-4b8f-b15a-96d16eeaa8b9.json
packages/react-components/react-carousel/library/src/components/CarouselCard/useCarouselCard.ts

Cards would occasionally fire a mouseDown event without a following mouseUp (if pointer moved or dragged).
This blocked focus index changes (as mouse events should not trigger index change but do cause focus).
Events were fired for mouse up/down, not pointer up/down
- Mouse detection gets reset on focus capture enabling it to capture future changes without a mouse up event
- Events now fired under pointer up/down

Carousel: Fix focus capture

---

change/@fluentui-web-components-037cbaec-4ee8-4f24-8cb7-1ae8ea8546f4.json
packages/web-components/.storybook/preview-head.html
packages/web-components/docs/api-report.md
packages/web-components/src/_docs/developer/polyfilling.stories.mdx
packages/web-components/src/index-rollup.ts
packages/web-components/src/index.ts
packages/web-components/src/tooltip/define.ts
packages/web-components/src/tooltip/index.ts
packages/web-components/src/tooltip/tooltip.definition.ts
packages/web-components/src/tooltip/tooltip.options.ts
packages/web-components/src/tooltip/tooltip.spec.ts
packages/web-components/src/tooltip/tooltip.stories.ts
packages/web-components/src/tooltip/tooltip.styles.ts
packages/web-components/src/tooltip/tooltip.template.ts
packages/web-components/src/tooltip/tooltip.ts

- No Tooltip component
- Add Tooltip component
- Follows the React `positioning` shorthands
- Does not currently implement the arrow functionality due to a Shadow DOM limitation with CSS anchor position.
> [!NOTE]
> Needs feedback! Tooltip requires CSS anchor position polyfill for older browsers but polyfill is still in-progress. 
- Closes #26697

feat(web-components): add Tooltip component

---

.github/actions/run-publish-vr-screenshot/action.yml
.github/labeler.yml
.github/workflows/bundle-size-base.yml
.github/workflows/bundle-size.yml
.github/workflows/check-packages.yml
.github/workflows/docsite-publish-ghpages.yml
.github/workflows/issues.yml
.github/workflows/pr-housekeeping.yml
.github/workflows/pr-website-deploy-comment.yml
.github/workflows/pr-website-deploy.yml
.github/workflows/pr.yml
change/@fluentui-web-components-9ecadf3f-3fd0-44c1-9abd-20a3456d8738.json
packages/web-components/src/tooltip/tooltip.ts
scripts/triage-bot/README.md

- use ubuntu-latest runner to make azure cli  work for bundle-size-comment 
- https://github.com/Azure/cli/issues/172
- **NOTE: this degrades CI (bundles size base) performance by 90% 🐌**
-  adds proper permission to update status with web site deployment
- sets retention day to for uploaded assets to minimum (1 day)
- migrates to latest core actions we use in pipelines (aligning with node v20 usage)
- [labeler](https://github.com/actions/labeler) will work again going forward 
- improves **performance of master pipelines**
-  going forward instead running all task on whole monorepo on every merge, we will run only affected projects since last succesfull merge commit passed - this should improve master runs perf **by 30%+**
- Follows https://github.com/microsoft/fluentui/pull/33191

ci(.github): prepare new pipelines for migration from ADO

---

change/@fluentui-react-tabster-eab71fef-90f6-4251-97bf-a6fdb14d98bb.json
change/@fluentui-react-tooltip-7716dcaf-b67a-4edf-a80a-b57ea86298ef.json
packages/react-components/react-tabster/etc/react-tabster.api.md
packages/react-components/react-tabster/src/hooks/index.ts
packages/react-components/react-tabster/src/hooks/useGetKeyboardNavigation.ts
packages/react-components/react-tabster/src/hooks/useIsNavigatingWithKeyboard.ts
packages/react-components/react-tabster/src/index.ts
packages/react-components/react-tooltip/library/src/components/Tooltip/useTooltip.tsx

Fixes #31862
Tooltip should not be displayed if trigger element was focused programatically.
This however does not work well when user is already in keyboard more. For example, opening a popover with focus trap moves focus programatically inside of the popover. In this case, tooltip should be shown as the interaction initiating the focus move was keyboard.

fix(Tooltip): Do not prevent showing tooltip in keyboard mode

---

change/@fluentui-react-carousel-dd4976ee-6c52-4282-a43d-55367389b1c5.json
packages/react-components/react-carousel/library/src/components/useEmblaCarousel.ts

Controlled index implementation, user adds a CarouselCard and sets index to index of newly added card (simultaneous state update).
As index is not registered at time of state change, state is not updated.
Controlled index implementation, user adds a CarouselCard and sets index to index of newly added card (simultaneous state update).
Engine will update to new card in this scenario only.

Carousel: Set controlled index to newly added cards

---

azure-pipelines.bundlesize.yml

- bundle-size base upload from master branch ( NO FORKS ) doesn't work via GHA yet, thus ADO will be necessary to keep for master runs only to update bundle diff base within azure storage. 
- Relates to https://github.com/microsoft/monosize/pull/87 and https://github.com/Azure/cli/issues/174

ci(ado): dont run bundle-size on PR which is covered by GHA

---

packages/react-examples/src/react/Coachmark/docs/CoachmarkBestPractices.md

The coach mark is not a very accessible component. There was an ADO bug filed that made us consider adding more documentation for it from an accessibility standpoint.
- Fixes [ADO Bug](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/22590)

docs(v8 coachmark): Add a11y documentation

---

change/@fluentui-react-nav-preview-bbaa31db-f4ef-4bdb-95f0-f3f749a409c9.json
packages/react-components/react-nav-preview/library/etc/react-nav-preview.api.md
packages/react-components/react-nav-preview/library/src/components/NavDrawer/NavDrawer.types.ts
packages/react-components/react-nav-preview/library/src/components/NavDrawer/useNavDrawer.ts
packages/react-components/react-nav-preview/stories/src/NavDrawer/Controlled.stories.tsx

This pull request introduces a new feature to the `NavDrawer` component by exposing a `tabbable` prop, allowing consumers to enable both tab and arrow navigation. Additionally, it includes some import adjustments to accommodate this new feature.
* Added `tabbable` prop to `NavDrawer` to enable both tab and arrow navigation. (`packages/react-components/react-nav-preview/library/src/components/NavDrawer/NavDrawer.types.ts`)
* Updated `useNavDrawer_unstable` hook to utilize the `tabbable` prop for navigation. (`packages/react-components/react-nav-preview/library/src/components/NavDrawer/useNavDrawer.ts`)
* Modified `Controlled` story to demonstrate the use of the `tabbable` prop. (`packages/react-components/react-nav-preview/stories/src/NavDrawer/Controlled.stories.tsx`)
* Added …

[react-nav-preview](feat): Allowing Nav to be navigable by tabbing

---

.github/scripts/validate-pr-number.js
.github/workflows/pr-website-deploy-comment.yml

PR ID processing is now validated within pr-website-deploy-comment workflow.
If invalid PR ID would be submitted from PR fork we would fail pipeline and not upload/comment anything
_Example of failed pipeline:_
- Fixes #

ci(.github): enable pr id validation within pr-website-deploy

---

change/@fluentui-react-drawer-f26a20ea-8196-4280-adda-bbfb8ed23c93.json
packages/react-components/react-drawer/library/etc/react-drawer.api.md
packages/react-components/react-drawer/library/package.json
packages/react-components/react-drawer/library/src/components/OverlayDrawer/OverlayDrawer.test.tsx
packages/react-components/react-drawer/library/src/components/OverlayDrawer/OverlayDrawer.types.ts
packages/react-components/react-drawer/library/src/components/OverlayDrawer/useOverlayDrawer.tsx
packages/react-components/react-drawer/library/src/components/OverlayDrawer/useOverlayDrawerStyles.styles.ts

`Drawer` `mountNode` prop only accepted `HTMLElement` as a value.
`Drawer` `mountNode` now accepts `HTMLElement` as well as an object with the `{ element, className }` format
-----
This fixes a regression introduced by the `Portal` `mountNode` format being changed.

feat(react-drawer): add support for mountNode with className

---

change/@fluentui-react-dialog-5f8bb155-a039-460c-8314-c8d28bfe9cfa.json
packages/react-components/react-dialog/library/src/components/DialogSurface/useDialogSurfaceStyles.styles.ts

Dialog is showing up with no proper style when opting-out of `surfaceMotion`
Ensures `DialogSurface` will maintain its style even when opting out of `surfaceMotion`
- Fixes https://github.com/microsoft/fluentui/issues/32433

bugfix(react-dialog): ensures dialog surface style without surfaceMotion

---

change/@fluentui-react-carousel-677bc0e8-d883-44ed-bd07-33cbb2ff2f6b.json
change/@fluentui-react-carousel-ce0e3ec0-23bb-462a-b810-87644db34d7b.json
packages/react-components/react-carousel/library/cypress.config.ts
packages/react-components/react-carousel/library/package.json
packages/react-components/react-carousel/library/src/components/Carousel/Carousel.cy.tsx
packages/react-components/react-carousel/library/tsconfig.cy.json
packages/react-components/react-carousel/library/tsconfig.json
packages/react-components/react-carousel/library/tsconfig.lib.json

No cypress support 
Cypress enabled for carousel library repo
Tested navigation and callback functionality

Carousel: Cypress component tests

---

change/@fluentui-react-combobox-cd58fbb4-facf-4aa2-8116-88f7d8f05ee9.json
packages/react-components/react-combobox/library/src/components/Combobox/Combobox.test.tsx
packages/react-components/react-combobox/library/src/components/Combobox/useCombobox.tsx
packages/react-components/react-combobox/library/src/components/Dropdown/Dropdown.test.tsx
packages/react-components/react-combobox/library/src/components/Dropdown/useDropdown.tsx

When the `Dropdown` and `Combobox` components were `clearable` and `disabled`, the clear button was still visible and interactive even though the components themselves were disabled.
When the `Dropdown` and `Combobox` components are `clearable`, if they are `disabled`, then the clear button is not visible anymore.
- Fixes #33240

fix(`react-combobox`): Clearable `Dropdowns` and `Comboboxes` do not show clear button if they are disabled

---

change/@fluentui-react-68ba4dbf-1de0-48fa-bc8d-7eae1a191d63.json
packages/react/src/components/pickers/Suggestions/SuggestionsItem.styles.ts
packages/react/src/components/pickers/Suggestions/__snapshots__/Suggestions.test.tsx.snap

The contents inside of `SuggestionItems` are moving and shifting when hovering over them, which causes a bad user experience.
The contents inside of `SuggestionItems` are now left-aligned and no longer move when hovering over them.
- Fixes #33075

fix(`react`): Left-aligning `SuggestionItem`'s contents so they do not move and shift on hover

---

packages/charts/react-charts-preview/library/src/components/CommonComponents/ChartPopover.tsx
packages/charts/react-charts-preview/library/src/components/CommonComponents/ChartPopover.types.ts
packages/charts/react-charts-preview/library/src/components/CommonComponents/useCartesianChartStyles.styles.ts
packages/charts/react-charts-preview/library/src/components/CommonComponents/useChartPopoverStyles.styles.ts
packages/charts/react-charts-preview/library/src/components/HorizontalBarChart/useHorizontalBarChartStyles.styles.ts
packages/charts/react-charts-preview/library/src/components/Legends/Legends.tsx
packages/charts/react-charts-preview/library/src/components/Legends/useLegendsStyles.styles.ts
packages/charts/react-charts-preview/library/src/components/Sparkline/useSparklineStyles.styles.ts

Fixed the following high contrast bugs for multiple charts:
1. [Bug 11575 [V9] [Doc site][High contrast] Horizontal Bar Absolute Scale data is not present on the bars.](https://uifabric.visualstudio.com/iss/_workitems/edit/11575)
2. [Bug 11579 [V9] [Doc site][High contrast] line and vertical bar charts x and y axis chart data and titles are not present](https://uifabric.visualstudio.com/iss/_workitems/edit/11579)
3. [Bug 11578 [V9] [Doc site][High contrast] sparkline row data is not present.](https://uifabric.visualstudio.com/iss/_workitems/edit/11578)
4. [Bug 11576 [V9] [Doc site][High contrast]when we toggle on User Popover Override the text is visible in white color only for all the charts...](https://uifabric.visualstudio.com/iss/_workitems/edit/11576/) 
5. [Bug 11574 [V9] [Doc …

Fixed High contrast bugs for multiple charts

---

change/@fluentui-react-infolabel-75e65619-149e-4b64-9ec9-06efe295fc27.json
packages/react-components/react-infolabel/library/src/components/InfoButton/useInfoButtonStyles.styles.ts

The popover of `InfoButton` did not have a `maxWidth` constraint, which caused the popover to extend to the width of the viewport.
The popover of `InfoButton` now has a `maxWidth` of `264px`, which matches the figma spec.
- Fixes #33245

chore(`react-infolabel`): Adding `maxWidth` to `InfoButton`'s popover to match figma spec

---

change/@fluentui-react-4726e359-06af-4ddf-baa2-635fc6b47b59.json
packages/react/src/components/SwatchColorPicker/ColorPickerGridCell.styles.ts
packages/react/src/components/SwatchColorPicker/__snapshots__/SwatchColorPicker.test.tsx.snap

With `forced-colors: active`:
With `forced-colors: active`:
- Fixes [ADO Bug](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/18609)

fix(v8 SwatchColorPicker): Add forced-color-adjust to gradients

---

change/@fluentui-react-components-1c2b6bfb-1ab8-4b00-9a20-3ccff0c4cfc8.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts

`useListboxContext_unstable` is exported from `@fluentui/react-combobox`, but not `@fluentui/react-components`
Export from `@fluentui/react-components`

chore(react-components): Export useListboxContext_unstable

---

change/@fluentui-react-tree-a886fa7c-b0f9-4646-8bd7-e9be02201229.json
packages/react-components/react-tree/library/src/components/TreeItem/useTreeItem.tsx

Currently there's no way to make a `TreeItem` unfocusable.
Ensure that the `role` attribute of the `TreeItem` root can be overridden by `props`. Now it's possible to make a `TreeItem` become unfocusable by just ensuring that it does not have the role `treeitem` (which is what is used internally by the `Tree` navigation)
- Fixes #

chore: ensure TreeItem role can be overridden by props

---

change/@fluentui-react-swatch-picker-e5e27fd6-7f1e-444e-b5bf-146b6cc0e925.json
packages/react-components/react-swatch-picker/library/package.json
packages/react-components/react-swatch-picker/library/src/components/SwatchPicker/useSwatchPicker.ts

`SwatchPicker` had no integration with the `Field` component. So when they were used together, all the expectations of correctly labeling things for accessibility were not being meant.
We have integrated the `Field`'s context with `SwatchPicker` so that when they are used together, `SwatchPicker` will be correctly labelled for accessibility.
- Fixes #33269

feat(`react-swatch-picker`): Correctly integrating `SwatchPicker` with `Field` component

---

apps/public-docsite-v9/src/Utilities/FocusManagement/useArrowNavigationGroup/CircularNavigationWithTab.stories.tsx
apps/public-docsite-v9/src/Utilities/FocusManagement/useArrowNavigationGroup/index.stories.tsx

This PR adds an example on how to achieve circular navigation with Arrow Keys and Tab together. The example is self-explanatory.

docs(useArrowNavigationGroup): add example on how to use arrows+tab for circular navigation

---

change/@fluentui-react-tree-42fe21a3-4b97-431e-b2b6-ed5e0bc00663.json
packages/react-components/react-tree/library/src/components/TreeItemLayout/useTreeItemLayout.tsx

Event listeners that ensured `actions` visibility were only being added if `actions` visibility state was uncontrolled, causing `onActionsVisibilityChange` callback to not being properly called
1. Always adds event listeners, even if `actions` visibility state is controlled, ensuring the `onActionsVisibilityChange` callback will be properly called.
2. Adds conditionals to ensure opt-out behaviour in case user prevents event
- Fixes https://github.com/microsoft/fluentui/issues/33319

bugfix(react-tree): ensure that onActionVisibilityChange is properly invoked

---

change/@fluentui-react-file-type-icons-d220b09a-74bc-4c36-a2b2-764d95a1ac82.json
packages/react-file-type-icons/src/FileTypeIconMap.ts

```onepart``` extension is mapped to ```genericfile``` (fallback) as it is not present in ```FileTypeIconMap```.
```onepart``` extension is now mapped to ```one``` extension.
- Fixes # https://github.com/microsoft/fluentui/issues/33316

fix(react-file-type-icons): Map onepart extension to onenote icon

---

change/@fluentui-react-61cfae8a-355e-4814-bf2d-073d07f4d67e.json
packages/react/src/components/Pivot/Pivot.styles.ts

After #32380 merged, there were a number of unintended consequences, one of them making overflow menu items in `Pivot` be centered instead of left-aligned.
This PR fixes this issue by left-aligning the items within `Pivot`'s overflow menu.
- Fixes #33312

fix(`react`): Left-aligning menu items in `Pivot`'s overflow menu

---

docs/react-v9/contributing/patterns/change-event-callbacks.md

Implementation of Change Event pattern to document avoiding potential breaking changes and recommended architecture.

Docs: Add 'Change Event Callback' pattern doc

---

change/@fluentui-react-search-ee89326e-8228-4cb3-911a-25ccd8ea4f8e.json
packages/react-components/react-search/library/src/components/SearchBox/useSearchBox.tsx

When the clear button is pressed, the contents of the `SearchBox` is cleared but focus remains on the clear button.
When the clear button is pressed, the contents of the `SearchBox` is cleared and focus is restored to the `SearchBox`, so users don't have to perform an extra action to begin typing in the `SearchBox` again.
N/A

fix(react-search): Restore focus to `SearchBox` after clear button is clicked

---

change/@fluentui-react-motion-80dc5fe2-1c39-41d8-921f-3e5d78554267.json
packages/react-components/react-motion/library/src/contexts/MotionBehaviourContext.ts
packages/react-components/react-motion/library/src/hooks/useIsReducedMotion.ts

The check for motion being enabled was executed in `useIsReducedMotion()` during `useEffect()` while animations are triggered in `useLayoutEffect()`. This caused animations to start always with a false positive value.
Fixes #33358.

fix(motion): respect reduced motion in createMotionComponent()

---

packages/react-components/react-tooltip/stories/src/Tooltip/TooltipWithOverflow.stories.tsx
packages/react-components/react-tooltip/stories/src/Tooltip/index.stories.tsx

Adding an additional example to our react-tooltip component, demonstrating a controlled tooltip with overflow logic. This feature was available in Fluent UI v8 through a built-in `overflowMode` prop, but it is not supported in the current v9 API, users should use `onVisibilityChange`. Partners have been asking how to replicate this functionality in v9. While the migration documentation notes the absence of overflowMode, this example aims to address the scenario. 
We can approach this in two ways: either clarify that managing tooltip with overflow is now a user responsibility (as a "by design" decision) or provide this example to guide users on implementing it. 
UPD: found that `onlyIfTruncated` example existed [before in preview version](https://github.com/behowell/fluentui/blob/4a8b91e896 …

docs(react-tooltip): add Tooltip and overflow content example

---

apps/public-docsite-v9/src/DocsComponents/ThemePicker.stories.tsx
packages/react-components/react-menu/stories/src/Menu/MenuBestPractices.md
packages/react-components/react-menu/stories/src/Menu/MenuDefault.stories.tsx

A storybook-only fix instead of the potentially breaking fix in #33342. Adds `autoSize: true` to the docs site's Theme picker that was clipped by the top of the page at high zooms/small viewport sizes, and adds that info to the Menu docs.
Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/18533)

fix: Storybook menu overflow behavior and Menu docs for autoSize

---

packages/web-components/.eslintrc.json

Warnings are displayed when viewing `packages/web-components/package.json` in VS Code.
This eslint override for JSON files stops these warnings from being displayed.

fix(web-components): eslint config for json files

---

change/@fluentui-react-charts-preview-803c5a15-3686-44e2-827f-e70720369036.json
packages/charts/react-charts-preview/library/src/components/HorizontalBarChart/useHorizontalBarChartStyles.styles.ts

`makeStyles()` is imported from `@fluentui/react-components`:
Build is broken:
There is also no dependency declared:
https://github.com/microsoft/fluentui/blob/99e5e6a9d394d6be64a58ac4ffb38b11023bcb72/packages/charts/react-charts-preview/library/package.json#L40-L49
`makeStyles()` is imported from `@griffel/react`.
Breaks my PR #33380 😭

chore(charts): fix import

---

apps/public-docsite-v9/src/Concepts/Slots/Slots.stories.mdx

There was a typo in the Slot docs.
There is not a typo in the Slot docs. Well maybe there still is, but this one is fixed.

fix typo in slot docs

---

packages/react-components/react-toast/stories/src/Toast/ToastDescription.md

There was a typo in the Toast docs.
Typo fixed!

fix(`react-toast`): Fixing `Toast` docs typo

---

packages/react-components/react-list-preview/stories/src/List/ListActiveElement.stories.tsx

Fixes HC theme in one List example, where previously the background for active element wasn't visible.

List: Fix HC theme in storybook

---

change/@fluentui-react-spinbutton-43864ed0-359e-407e-8250-36a85a8ba6b4.json
packages/react-components/react-spinbutton/library/src/components/SpinButton/SpinButton.test.tsx
packages/react-components/react-spinbutton/library/src/components/SpinButton/useSpinButton.tsx
packages/react-components/react-spinbutton/library/src/components/SpinButton/useSpinButtonStyles.styles.ts

When the value hits a min or max bound, the up or down arrow gets visually disabled and doesn't respond to interaction. It was previously not semantically disabled, so screen reader users had no indication that the buttons were disabled.
The button gets semantically disabled, which also means the extra disabled-appearance styles could be removed from `useSpinButtonStyles`, since they're covered by the Button disabled styles.
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/22192)

fix(SpinButton): up/down buttons were not semantically disabled when unclickable

---

change/@fluentui-web-components-7901265e-589d-4d51-8bb8-320a376cb79d.json
packages/web-components/docs/api-report.md
packages/web-components/src/text-input/text-input.spec.ts
packages/web-components/src/text-input/text-input.ts

Adds the `current-value` attribute and `currentValue` property to the `<fluent-text-input>` element.
- Fixes #33137

fix(web-components): add `current-value` attribute to TextInput component

---

change/@fluentui-react-virtualizer-9b989611-7a15-4cad-bb17-903e5e009e52.json
packages/react-components/react-virtualizer/library/src/components/Virtualizer/Virtualizer.types.ts
packages/react-components/react-virtualizer/library/src/components/Virtualizer/useVirtualizer.ts
packages/react-components/react-virtualizer/stories/src/Virtualizer/Dynamic.stories.tsx
packages/react-components/react-virtualizer/stories/src/VirtualizerScrollViewDynamic/AutoMeasure.stories.tsx

Consumers had to account for gap in itemSize
Consumers can now use gap property to simplify calculations

Virtualizer: Add gap property for calculation

---

packages/react-components/react-carousel/stories/src/Carousel/CarouselActionCards.stories.tsx

Consumers mentioned that an aria-label to explain custom left/right navigation controls was required
This is possible with current implementation but not shown in storybook demo.
Updated cardFocus example with aria-label to narrate navigation controls

Carousel Storybook: Add navigation guidance aria-label example

---

tools/workspace-plugin/src/generators/react-component/files/component/index.ts__tmpl__
tools/workspace-plugin/src/generators/react-component/index.spec.ts
tools/workspace-plugin/src/generators/react-component/index.ts

This PR updates the components' generator to output exact exports instead of `export *` in barrel files.
This will improve performance of current compiler in Griffel and will unblock the future one, see https://github.com/microsoft/griffel/pull/621.

chore: update generator to stop using "export *"

---

change/@fluentui-react-motion-2679d27b-fa54-468d-9a6e-88febcf5eab0.json
packages/react-components/react-motion/library/src/factories/createMotionComponent.test.tsx
packages/react-components/react-motion/library/src/factories/createPresenceComponent.test.tsx
packages/react-components/react-motion/library/src/hooks/useAnimateAtoms.ts

We use `Animation.prototype.cancel()` and `Animation:finished`, this combination causes a memory leak in Chromium: https://issues.chromium.org/u/2/issues/383016426
`.finished` is replaced by a combination of `.onfinish` & `.oncancel` callbacks.

fix(motion): avoid memory leak in Animation:finished

---

change/@fluentui-react-carousel-d45f8c82-f098-4820-9e34-31862a08f3d3.json
packages/react-components/react-carousel/library/src/components/CarouselNavButton/useCarouselNavButtonStyles.styles.ts

High contrast mode in windows overrides all background colors, causing our nav icons to be invisible
When forced colors is active, we will contrast the nav icons against the background color via blend mode and a white default color.
Default: Unaffected
Desert HC (Light HC):
Night Sky HC (Dark HC):

Carousel: High contrast Windows

---

packages/react-components/react-swatch-picker/stories/package.json
packages/react-components/react-swatch-picker/stories/src/SwatchPicker/EmptySwatch.stories.tsx

SwatchPicker used native ColorPicker in the example
SwatchPicker Empty swatch example uses ColorPicker V9

docs(react-swatch-picker): replaced native ColorPicker with V9 one.

---

change/@fluentui-react-carousel-b0491798-cc10-487f-a3c0-98bcd6016f7f.json
packages/react-components/react-carousel/library/src/components/useEmblaCarousel.ts

Default tabster element was set on index change, causing it to be missed on initial render, if the user shift-tabbed into the carousel it would go to the last card.
Carousel now sets default tab to the first card in current group on init, including controlled or alternate default start indexes.

Carousel: Set initial focus target on init

---

change/@fluentui-react-carousel-6c54eead-adb1-472f-9bdd-51f424e2c9db.json
packages/react-components/react-carousel/library/src/components/CarouselNav/useCarouselNav.ts

CarouselNav totalSlides prop was only used to initialize state
totalSlides prop now controls state without preventing undefined default behaviour
- Fixes #33442

Carousel: Set CarouselNav totalSlides to controlled

---

change/@fluentui-tokens-a1396b99-e2b7-4ab3-8c89-7d58c5b4ba8b.json
packages/tokens/src/alias/teamsFontFamilies.ts
packages/tokens/src/themes/teams/darkTheme.ts
packages/tokens/src/themes/teams/highContrastTheme.ts
packages/tokens/src/themes/teams/lightTheme.ts

Fluent Teams tokens gives preference for `Segoe UI` font family instead of local system font `-apple-system, BlinkMacSystemFont`. This is causing inconsistencies between Teams and Teams embedded applications, as they consume those token from different sources.
Updates the `fontFamilyBase` token to give preference for `-apple-system, BlinkMacSystemFont` as that is the default fonts being used on Teams
- Fixes https://github.com/microsoft/fluentui/issues/33392

bugfix(tokens): ensure teams tokens follow teams overrides for fonts

---

change/@fluentui-react-charting-4c197bf1-3dca-480d-aa17-d97a170246ff.json
packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx
packages/charts/react-charting/src/components/LineChart/LineChart.base.tsx
packages/react-examples/src/react-charting/DeclarativeChart/schema/fluent_line.json

Enabled Multi selection behaviour of Controlled legends for LineChart.
**Upcoming changes**: enable it for other charts.
- Fixes #

Enabled multi-selection of Controlled legends

---

packages/fluentui/projects-test/assets/cra/src/index.tsx
packages/fluentui/projects-test/src/createReactApp.ts
packages/fluentui/react-northstar/jest.config.js

Currently tests on CI are failing with OOM:
It looks that GC is not triggered on time for workers. This could be observed even locally:
```
PASS react-northstar test/specs/components/Box/Box-test.tsx (3686 MB heap size)
PASS react-northstar test/specs/components/Skeleton/Skeleton-test.tsx (8.947 s, 3685 MB heap size)
PASS react-northstar test/specs/components/Status/Status-test.tsx (6.757 s, 3717 MB heap size)
PASS react-northstar test/specs/components/Video/Video-test.tsx (5.27 s, 3614 MB heap size)
```
```
PASS react-northstar test/specs/components/Card/CardFooter-test.tsx (11.592 s, 703 MB heap size)
PASS react-northstar test/specs/components/Box/Box-test.tsx (911 MB heap size)
PASS react-northstar test/specs/components/Reaction/Reaction-test.tsx (11.723 s, 943 MB heap size)
PASS …
```

chore: fix N* tests

---

change/@fluentui-react-1bdbe475-2d17-453e-b058-b152322278cd.json
package.json
packages/react/etc/react.api.md
packages/react/src/components/ContextualMenu/ContextualMenu.base.tsx
yarn.lock

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-3.html 
- Partially implements #33138

chore: migrate to ts 5.3.3 

---

change/@fluentui-web-components-f87a2b96-d977-4138-8cb9-8cad4b13d8a8.json
packages/web-components/src/tooltip/tooltip.stories.ts
packages/web-components/src/tooltip/tooltip.styles.ts

* The `below-end` style for the Tooltip component was set to `below`.
* The Tooltip's shadow was not visible on Safari.
* Stories for the Tooltip component use an older Story format.
* The `below-end` style for the Tooltip component is now set to `below-end`.
* The Tooltip's shadow is now visible on Safari.
* Stories for the Tooltip component have been updated to use the new Story format and improve type safety.

fix(web-components): tooltip positioning style for 'below-end' option

---

change/@fluentui-react-charting-4a2b4230-b5e3-4cea-9777-4e1670b33156.json
packages/charts/react-charting/etc/react-charting.api.md
packages/charts/react-charting/src/components/CommonComponents/CartesianChart.base.tsx
packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
packages/charts/react-charting/src/components/HeatMapChart/HeatMapChart.base.tsx
packages/charts/react-charting/src/components/HeatMapChart/HeatMapChart.types.ts
packages/charts/react-charting/src/components/HeatMapChart/__snapshots__/HeatMapChartRTL.test.tsx.snap

Full Y Axis labels feature in Heatmap chart.
- Fixes #

Full y axis labels in Heatmap chart

---

change/@fluentui-react-da358841-feeb-4166-a7d8-e955d9e51ad7.json
packages/react/src/components/Panel/Panel.base.tsx

This pull request includes changes to the `Panel` component in the `@fluentui/react` package to fix the footer's sticky property when content changes dynamically. The most important changes include adding a `ResizeObserver` to monitor content changes and updating the footer position accordingly.
Enhancements to `Panel` component:
* Added a new event listener to the `Panel` component to update the footer's sticky property when content changes dynamically. (`change/@fluentui-react-da358841-feeb-4166-a7d8-e955d9e51ad7.json`)
Codebase improvements:
* Introduced a `_resizeObserver` property in the `PanelBase` class to observe content size changes. (`packages/react/src/components/Panel/Panel.base.tsx`)
* Ensured the `ResizeObserver` is disconnected when the component unmounts to prevent memory …

fix(Panel): Add event listener to Panel in order to update the footer's sticky property correctly when content changes dynamically

---

change/@fluentui-react-color-picker-preview-0f7e3b1e-353f-410a-8642-202d0d30d244.json
packages/react-components/react-color-picker-preview/library/src/components/ColorArea/useColorAreaStyles.styles.ts
packages/react-components/react-color-picker-preview/library/src/components/ColorSlider/useColorSliderStyles.styles.ts
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/AlphaSliderDefault.stories.tsx
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorAndSwatchPicker.stories.tsx
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorAreaDefault.stories.tsx
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorPickerDefault.stories.tsx
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorPickerPopup.stories.tsx
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorPickerShape.stories.tsx
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorSliderDefault.stories.tsx

- Added more contrast border for the thumb
- Made preview box in HC with no color adjustment

fix(react-color-picker): design of thumb

---

.github/CODEOWNERS

Right now, we have no owner for `@fluentui/react-experiments`, and changes to `@fluentui/react` semi-regularly cause snapshot updates in that package, which then requires a review from fluentui-admins. It seems to make sense to put this under `cxe-red` along with react and react-examples.
Chatted about this briefly in Teams chat as well.

chore: make cxe-red the owner of react-experiments

---

.github/actions/run-publish-vr-screenshot/action.yml
.github/scripts/prepare-vr-screenshots-for-upload.js
.github/workflows/pr-vrt-comment.yml
.github/workflows/pr-vrt.yml

> **💡 NOTE:** both of these pipelines will be disabled until we have compliant vrt tooling 
Splits/Implements VRT pipelines in 2 to follow GHA pattern on forks for future enablement.
1. generating screenshots on affected projects on Forks (works after merge)
2. running vrt diffing and commenting  from master branch (doesn't work untill we have new vrt diff tool)
**Out of scope:**
- updating baseline screenshot diffs 
- we can/will use ADO pipeline for now from master (no Forks)
- Follows https://github.com/microsoft/fluentui/pull/33070

ci: separate VRT pipelines in GHA compliant pattern for future enablement

---

change/@fluentui-eslint-plugin-react-components-1c2bc691-c857-43cf-9806-ffe8d0d058c0.json
packages/react-components/eslint-plugin-react-components/.eslintrc.json
packages/react-components/eslint-plugin-react-components/README.md
packages/react-components/eslint-plugin-react-components/etc/eslint-plugin-react-components.api.md
packages/react-components/eslint-plugin-react-components/src/index.ts
packages/react-components/eslint-plugin-react-components/src/rules/prefer-fluentui-v9.spec.ts
packages/react-components/eslint-plugin-react-components/src/rules/prefer-fluentui-v9.ts
packages/react-components/eslint-plugin-react-components/src/rules/utils/create-rule.ts
packages/react-components/eslint-plugin-react-components/tsconfig.spec.json

--
- Added new rule `prefer-fluentui-v9` to `eslint-plugin-react-components` to enforce the use of Fluent UI v9 equivalent for Fluent UI v8 components. 
- Added it to the `recommended` config.
- Updated docs
Example of output:
```
fluentui/apps/vr-tests/src/stories/Toggle.stories.tsx
4:1  warning  Avoid importing Toggle from '@fluentui/react', as this package has already migrated to Fluent UI 9. Import Switch from '@fluentui/react-components' instead  @fluentui/react-components/prefer-fluentui-v9
fluentui/apps/vr-tests/src/stories/Tooltip/Tooltip.stories.tsx
4:1  warning  Avoid importing TooltipHost from '@fluentui/react', as this package has already migrated to Fluent UI 9. Import Tooltip from '@fluentui/react-components' instead  @fluentui/react-components/prefer-fluentui-v9
```
- …

feat(eslint-plugin-react-components): add prefer-fluentui-v9 rule

---

change/@fluentui-react-94a6046f-d21a-4386-9830-79921b5d4337.json
packages/react/src/components/Stack/Stack.tsx
packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.deprecated.test.tsx.snap
packages/react/src/components/TeachingBubble/__snapshots__/TeachingBubble.test.tsx.snap

The `Stack` inner slot element didn't have a key assigned to it, which triggered an error when using React 19.
A key has been added to the `Stack` inner slot element. I tested this change in the provided StackBlitz reproduction and the error no longer occurs.
- Fixes #33461

chore: Adding key to inner slot in Stack component

---

change/@fluentui-react-color-picker-preview-cf2c2f44-2d77-4ead-b123-c81b1da98292.json
packages/react-components/react-color-picker-preview/library/src/components/ColorSlider/ColorSlider.test.tsx
packages/react-components/react-color-picker-preview/library/src/components/ColorSlider/useColorSlider.ts
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/AlphaSliderDefault.stories.tsx
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorAreaDefault.stories.tsx
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorPickerDefault.stories.tsx
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorSliderDefault.stories.tsx

Added aria-attributes for ColorPicker

feat(react-color-picker): a11y labels and behaviors

---

change/@fluentui-react-tabs-9ce35d6f-27b5-451e-aa6f-d2902a97787b.json
packages/react-components/react-tabs/library/src/components/Tab/useTabStyles.styles.ts

Tabs with `subtle-circular` and `filled-circular` appearance variants have a colored border in HC mode, making it difficult to distinguish between selected and unselected states.
This issue arises because the `tokens.colorTransparentStroke` value is not `transparent` in HC mode. 
Tabs with `subtle-circular` and `filled-circular` appearance variants now have a transparent border for all themes including HC mode.
- Fixes #33516

fix(react-tabs): update tab border color to fix issues in high contrast mode

---

change/@fluentui-web-components-fc912571-691c-494a-b4de-9a632a76a26c.json
packages/web-components/docs/api-report.md
packages/web-components/src/radio-group/radio-group.spec.ts
packages/web-components/src/radio-group/radio-group.stories.ts
packages/web-components/src/radio-group/radio-group.ts
packages/web-components/src/radio/radio.ts

When setting `radio` to disabled the radio would set checked to false. This does not behave how native radios work. However the reason we were doing this is because is the radio was checked and disabled there was no way to tab into the radio-group (this bug is also present in native radio-groups).
When navigating within `radio-group` via keyboard the change event was not being emitted
Setting disabled to a checked radio no longer unchecks the radio. However, when a user tabs into the radio-group the first nondisabled radio will get focus. This is a best of both worlds' scenario, allowing the checked and disabled state but also not breaking keyboard navigation.
Also the change event is now emitting from radio-group when you select a new radio via keyboard.
Fixes #33523 and #33546

fix: radio-group emit change with keyboard and disabled radio unchecks

---

.github/workflows/azure-static-web-apps-deploy.yml
.github/workflows/bundle-size-base.yml
.github/workflows/bundle-size-comment.yml
.github/workflows/bundle-size.yml
.github/workflows/check-packages.yml
.github/workflows/check-tooling.yml
.github/workflows/create-milestone.yml
.github/workflows/docsite-publish-ghpages.yml
.github/workflows/pr-housekeeping.yml
.github/workflows/pr-vrt-comment.yml
.github/workflows/pr-vrt.yml
.github/workflows/pr-website-deploy-comment.yml
.github/workflows/pr-website-deploy.yml
.github/workflows/pr.yml

our pipelines are triggered in forks which is unwanted behaviour
CI pipelines run only on PR's against origin repo or workflows triggered within origin
- Fixes #

ci:prevent running pipelines on forks

---

change/@fluentui-react-color-picker-preview-4f2e285e-18a9-4ad5-8543-5310072fd1e9.json
change/@fluentui-react-motion-components-preview-1e0e7b65-3a13-46be-9f9c-01fdb511c16f.json
change/@fluentui-react-nav-preview-f95778aa-ad54-4ba0-9ef8-38237de444a8.json
change/@fluentui-react-tabster-53bcacad-3ce8-4391-a3eb-72bc219d93f9.json
change/@fluentui-react-toast-b6083bc4-f97c-4ad1-a457-a150145f3543.json
change/@fluentui-react-tooltip-7be3b676-890f-4c2c-8a08-d7abf38084de.json
change/@fluentui-react-virtualizer-d6716ae8-9732-454c-9c6f-65ab98953a42.json
packages/react-components/react-color-picker-preview/library/etc/react-color-picker-preview.api.md
packages/react-components/react-motion-components-preview/library/etc/react-motion-components-preview.api.md
packages/react-components/react-nav-preview/library/etc/react-nav-preview.api.md
packages/react-components/react-tabster/src/hooks/useIsNavigatingWithKeyboard.ts
packages/react-components/react-toast/library/etc/react-toast.api.md
packages/react-components/react-tooltip/library/etc/react-tooltip.api.md
packages/react-components/react-virtualizer/library/etc/react-virtualizer.api.md

we have outdated api.md files which leaked through because of bug in build executor
- all package have up to date api.md
- invalid TSDoc pragmas are fixed
- Follows https://github.com/microsoft/fluentui/pull/33558
- Replaces https://github.com/microsoft/fluentui/pull/33562

fix: make api.md up to date

---

azure-pipelines.bundlesize.yml

If `bundle-size` task failed on bundle size baseline workflow, the monosize upload report is still executed. 
This creates invalid storage snapshot that creates false positives on PRs 
Example
- baseline pipeline that creates invalid snapshot in Storage https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=369079&view=logs&j=f5e89eef-ad59-58c9-614d-c2fd6081e79d&t=0ad640fa-3ea4-5d68-1032-aae4655c9f1f
- ![image](https://github.com/user-attachments/assets/d1363cec-13a0-4b36-8953-339f9e829544)
- PR generating false positives based on invalid snapshot https://github.com/microsoft/fluentui/pull/33599#issuecomment-2580579082
- ![image](https://github.com/user-attachments/assets/58954548-2b37-40be-8f98-3b398e1e6ea5)
upload report is executed only if all bundle-size tasks passed
- …

ci(ado): update storage baseline for bundle-size only if all bundle-size tasks passed

---

change/@fluentui-react-nav-preview-b0930295-331e-4b55-96fc-c17b84ce854b.json
packages/react-components/react-nav-preview/library/src/components/sharedNavStyles.styles.ts

Speeding up the default motion for Nav item hovers and indicators after getting customer feedback and consulting with animation SMEs.
Takes speed from 150ms -> 100ms.

(fix)[react-nav-preview): Updating Nav animation speeds

---

packages/charts/chart-web-components/src/donut-chart/donut-chart.styles.ts
packages/charts/chart-web-components/src/horizontal-bar-chart/horizontal-bar-chart.styles.ts

This PR addresses the following comment:
> Typically we use [CSS System Colors](https://developer.mozilla.org/en-US/docs/Web/CSS/system-color) for forced colors over RGB values so that we're compatible with light and dark modes.
-- https://github.com/microsoft/fluentui/pull/33084#discussion_r1909631808

Use css system colors for high contrast mode

---

change/@fluentui-react-nav-preview-f1f67efd-37ec-4bf3-a0b8-470029586904.json
packages/react-components/react-nav-preview/library/src/components/sharedNavStyles.styles.ts

Had an over the shoulder conversation with an animation SME and he suggested linear curves as the standard for hover over.

[Fix](react-nav-preview): Changing nav item hover animation curves.

---

.github/workflows/pr-vrt.yml

ci(gha): enable manual trigger for VRT and disable automatic PR trigger for testing purposes

---

change/@fluentui-react-color-picker-preview-c30cb79c-aed3-4e9b-ad55-b1f946c8c691.json
packages/react-components/react-color-picker-preview/library/src/components/ColorArea/useColorArea.ts
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/AlphaSliderDefault.stories.tsx
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorAndSwatchPicker.stories.tsx
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorAreaDefault.stories.tsx
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorPickerDefault.stories.tsx
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorPickerPopup.stories.tsx
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorPickerShape.stories.tsx
packages/react-components/react-color-picker-preview/stories/src/ColorPicker/ColorSliderDefault.stories.tsx

- When the user clicks on the `tab` key, the focus goes to the `inputY` instead of the next element.
- Color in stories in hex format
- When the user clicks on the `tab` key, the focus goes to the next element.
- Moved color in stories in one HSV format

fix(react-color-picker): focus shifts to inputY when user clicks `tab`

---

change/@fluentui-react-motion-f4c1433b-f36e-4b2c-a9bd-9b16f37489fc.json
packages/react-components/react-motion/library/etc/react-motion.api.md
packages/react-components/react-motion/library/src/hooks/useAnimateAtoms.test.tsx
packages/react-components/react-motion/library/src/hooks/useAnimateAtoms.ts
packages/react-components/react-motion/library/src/types.ts
packages/react-components/react-motion/stories/src/CreateMotionComponent/CreateMotionComponentDefault.stories.tsx
packages/react-components/react-motion/stories/src/CreateMotionComponent/CreateMotionComponentFactory.stories.tsx
packages/react-components/react-motion/stories/src/CreateMotionComponent/CreateMotionComponentFunctionParams.stories.tsx
packages/react-components/react-motion/stories/src/CreateMotionComponent/CreateMotionComponentImperativeRefPlayState.stories.tsx
packages/react-components/react-motion/stories/src/CreateMotionComponent/CreateMotionComponentTokensUsage.stories.tsx
packages/react-components/react-motion/stories/src/CreatePresenceComponent/CreatePresenceComponentReducedMotion.stories.md
packages/react-components/react-motion/stories/src/CreatePresenceComponent/CreatePresenceComponentReducedMotion.stories.tsx
packages/react-components/react-motion/stories/src/CreatePresenceComponent/index.stories.ts

No way to customize motions' behavior when reduced motion is enabled.
- Adds `reducedMotion` option to `AtomMotion` type.
- Tests added
- Story added
By default, when [reduced motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) is enabled the duration of the animation is set to `1ms` (current behavior).
`reducedMotion` allows to customize a reduced motion version of the animation:
```ts
const Motion = createPresenceComponent({
enter: {
keyframes: [
{ opacity: 0, transform: 'scale(0)' },
{ opacity: 1, transform: 'scale(1)' },
],
duration: 300,
/** 💡reduced motion will not have scale animation with a different duration */
reducedMotion: {
keyframes: [{ opacity: 0 }, { opacity: 1 }],
duration: 1000,
},
},
exit: {
/* ... */
},
});
```
> 💡Note, if …

feat(motion): add extended support for reduced motion

---

change/@fluentui-web-components-674e26a9-57d5-4147-bda1-e4a467529eaf.json
packages/web-components/project.json
packages/web-components/test/harness/vite.config.ts

The `@fluentui/tokens` package is a dependency of the `@fluentui/web-components` package.
The `tokens` package was not being built before the `e2e` task ran, which caused errors on CI (https://github.com/microsoft/fluentui/actions/runs/12755006210/job/35551157062?pr=33637)
The `project.json` configuration for the `web-components` package specifies that dependencies need to be built before the `e2e` task runs.

chore(web-components): build tokens package before running e2e tests

---

packages/icons/src/index.ts

The CDN that hosts the font icon assets will be deleted on 1/15/2025. This PR changes the base URL to point to a new CDN.

chore: Update BASEURL to new CDN

---

change/@fluentui-web-components-a03312db-25ed-42ac-8259-b9754b5afdd9.json
packages/web-components/src/switch/switch.styles.ts

A disabled Switch in high-contrast mode had no visual checked indicator.
A disabled Switch in high-contrast mode now has a `GrayText` checked indicator
- Fixes #33506

[web-components] fix: disabled switch state in high-contrast mode

---

packages/react-components/react-toolbar/stories/src/Toolbar/ToolbarSmall.stories.tsx

Docs mention the wrong padding for small size toolbar: 20px
Docs mention the correct padding applied: 4px
- Fixes #33574

Fix typo in ToolbarSmall story

---

packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts

From PR https://github.com/microsoft/fluentui/pull/33594
Adding secondary y axis for declarative charts.
Area chart:
Line chart:
Grouped Vertical bar chart:
Vertical Stacked bar chart:

Adding secondary y axis for declarative charts

---

.github/ISSUE_TEMPLATE/01-react-components-bug-report.yml

v9 issue component list is out of date
updates v9 issue component [list generated by automation](https://github.com/microsoft/fluentui/pull/33555) ( extracted from source to mirror properly our storybook docs )
- Follows https://github.com/microsoft/fluentui/issues/25697

ci: update react-components-bug-report list

---

.github/workflows/pr-vrt-comment.yml

restrict commenting workflow to be run only if event is registered against master or temporary vrt-testing branch.
✅ this will completely avoid spamming our master commit history with testing commits for vrt-commenting workflow.
- Follows https://github.com/microsoft/fluentui/pull/33606

ci(gha): limit privileged vrt workflow trigger branch base

---

change/@fluentui-react-link-3fcc87af-d93e-43d3-8c48-d38b192fd9ac.json
packages/react-components/react-link/library/src/components/Link/Link.test.tsx
packages/react-components/react-link/library/src/components/Link/useLinkState.ts
packages/react-components/react-link/stories/src/Link/LinkAsSpan.stories.tsx

Currently keyboard interaction via `Enter` and `Space` is not possible, when `Link` is rendered as `span`. 
Added explicit handling of  `Enter` and `Space` 🧢 
- Fixes #33560

fix(react-link): support Enter and Space keys interaction, if rendered as span

---

change/@fluentui-react-charting-17bc0f58-a206-47b6-b5dc-6bf008820978.json
packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx
packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchema.ts
packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts

From PR https://github.com/microsoft/fluentui/pull/33542/files?diff=split&w=0
Fixes for test app crashes for 12 schema data
Fixed schema data numbers 84, 85, 88, 91, 92, 93, 99, 100, 101, 102, 103, 107

Adding fallback and fixes for test app crashes for 12 schema data 

---

change/@fluentui-react-tooltip-4088de96-b20d-4c18-9567-9987be622dbf.json
packages/react-components/react-tooltip/library/src/components/Tooltip/useTooltip.tsx

https://github.com/user-attachments/assets/7e357c00-3f3a-48b1-acc1-5e624d22cb08
https://github.com/user-attachments/assets/7e7b43ae-99ee-4144-93cc-9ce305e0c758
- Fixes #33646

fix(react-tooltip): wrong call of useIsNavigatingWithKeyboard

---

apps/public-docsite-v9/src/Concepts/Theming.stories.mdx

Fix typo from "CCS variables" to "CSS variables"

docs(public-docsite-v9): fix typo from "CCS variables" to "CSS variables"

---

change/@fluentui-react-motion-components-preview-67537ce1-b461-4bec-bbcb-61d9202e6632.json
packages/react-components/react-motion-components-preview/library/src/atoms/fade-atom.ts
packages/react-components/react-motion-components-preview/library/src/components/Collapse/Collapse.ts
packages/react-components/react-motion-components-preview/library/src/components/Collapse/collapse-atoms.ts
packages/react-components/react-motion-components-preview/library/src/components/Fade/Fade.ts

- Duplication in enter/exit implementations in atom functions:
- opacity
- whitespace
- No fade atom function in common location
- Duplication factored out
- `fadeAtom` is in a common location; `Collapse` and `Fade` import it for reuse
- Comments and explanatory types are added as needed
- Use `fadeAtom` in other motion components wherever possible
- [MessageBarGroup.motions.tsx](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-message-bar/library/src/components/MessageBarGroup/MessageBarGroup.motions.tsx#L21) copies `fadeAtom` code; it can import it instead, after this PR.
- Fixes #33636

refactor(Collapse): streamline atom functions

---

change/@fluentui-react-components-8e070f58-09e6-4a66-bd63-bbd13b27db88.json
change/@fluentui-react-tree-b452026f-0282-4a88-a922-34c2a983c77c.json
package.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts
packages/react-components/react-tree/library/etc/react-tree.api.md
packages/react-components/react-tree/library/src/components/TreeProvider.cy.tsx
packages/react-components/react-tree/library/src/components/TreeProvider.tsx
packages/react-components/react-tree/library/src/hooks/useRovingTabIndexes.ts
packages/react-components/react-tree/library/src/index.ts

1. aadd new component `TreeRootReset`, a contextual component that resets internal `Tree` logic that decides if a subtree if part of another parent tree or not
- Fixes #

feature(react-tree): TreeRootReset component

---

change/@fluentui-react-04cc1ab9-345e-4196-a9fd-d0ad829eec9b.json
packages/react/src/components/pickers/TagPicker/TagItemSuggestion.tsx

`ITagItemSuggestionProps` extends `React.AllHTMLAttributes<HTMLElement>` which allows to put any HTMLElement props on `TagItemSuggestion`
**For example**
```
onRenderSuggestionsItem: (props: ITag) => (
<TagItemSuggestion onClick={() => console.log('click')}>{props.name}</TagItemSuggestion>
),
```
But only `styles, theme, children` were used
All HTMLElement props are passed to the div component.
- Fixes #

fix(TagItemSuggestion v8): pass rest of the props to the underlying component

---

packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
packages/charts/react-charting/src/components/DeclarativeChart/__snapshots__/DeclarativeChartRTL.test.tsx.snap
packages/charts/react-charting/src/components/DeclarativeChart/__snapshots__/PlotlySchemaAdapterUT.test.tsx.snap

1. Heatmap chart with colorScale == 'Viridis' was crashing.
2. Heatmap chart with no colorscale defined was coming in black color.
Defined a default colorScale for above cases.
Upcoming feature: Will add support for 'Viridis' colorscale.
- Fixes #

feat(declarative-chart): Add default colorScale in heatmap chart

---

packages/charts/react-charting/src/components/HorizontalBarChartWithAxis/HorizontalBarChartWithAxis.base.tsx

fix: default legend selection for Horizontal Bar Chart for declarative charts
https://uifabric.visualstudio.com/iss/_workitems/edit/12159

fix: [BUG 12159] default legend selection for Horizontal Bar Chart

---

change/@fluentui-react-tag-picker-f788c84a-933e-4291-9111-2a6187517663.json
packages/react-components/react-tag-picker/library/src/components/TagPickerOption/__snapshots__/TagPickerOption.test.tsx.snap
packages/react-components/react-tag-picker/library/src/components/TagPickerOption/useTagPickerOptionStyles.styles.ts

`secondaryContent` (in this example the text `Microsoft FTE`) is not properly positioned, according to design spec it should be on it's own separate line and with `caption1` style by default
1. move `useOptionStyles` hook to lose priority over `useTagPickerOptionStyles` internal styles
2. properly add `caption1` typography styles which were missing
- Fixes https://github.com/microsoft/fluentui/issues/33683

bugfix: secondaryContent not displaying properly

---

change/@fluentui-react-components-2c418aac-078d-45dc-ad47-4bf796a2e600.json
change/@fluentui-react-tag-picker-7ed3243d-60b5-4678-9762-f1b1722ca0fe.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts
packages/react-components/react-tag-picker/library/etc/react-tag-picker.api.md
packages/react-components/react-tag-picker/library/src/components/TagPickerControl/useTagPickerControlStyles.styles.ts
packages/react-components/react-tag-picker/library/src/index.ts
packages/react-components/react-tag-picker/stories/src/TagPicker/TagPickerSingleLine.stories.tsx
packages/react-components/react-tag-picker/stories/src/TagPicker/index.stories.tsx

Implements single line layout example:
1. modifies internal styling from `TagPickerControl` from `grid` to `flex`
2. adds story showcasing how to achieve single line layout
3. exports `TagPickerContext` hooks and types
- Fixes https://github.com/microsoft/fluentui/issues/31666

feature(react-tag-picker): single line layout

---

change/@fluentui-react-drawer-592aa752-5056-4be4-bf91-b47f98cea7d4.json
packages/react-components/react-drawer/library/src/components/DrawerBody/useDrawerBody.ts

Drawer was [forcing synchronous layout](https://web.dev/articles/avoid-large-complex-layouts-and-layout-thrashing#avoid_forced_synchronous_layouts) by reading [scrollTop, scrollHeight and clientHeight in its getScrollState() function](https://github.com/microsoft/fluentui/blob/00458f3bbe3f12c0cef556f8d8fd564ffa66983c/packages/react-components/react-drawer/library/src/components/DrawerBody/useDrawerBody.ts#L23).
This change defers the read with a `requestAnimationFrame()` so the browser can read the values from the previous frame, removing the forced synchronous layout.
No forced synchronous layout
- Fixes #33655

fix: remove forced synchronous layout in Drawer

---

apps/vr-tests-react-components/src/stories/ColorPicker/ColorPicker.stories.tsx
apps/vr-tests-react-components/src/stories/ColorPicker/utils.tsx

- Added VR tests for ColorSlider and AlphaSlider
Options:
- vertical
- transparency for AlphaSlider

test(color-picker): Added VR tests for ColorSlider and AlphaSlider

---

change/@fluentui-react-charting-ef56337f-c8bb-48ee-94f5-75abe0aa1d3b.json
packages/charts/react-charting/src/components/DeclarativeChart/imageExporter.ts

fix(react-charting): ensure text elements use the correct font-family in SVG export

---

change/@fluentui-react-color-picker-preview-0c1f8cab-ce3f-4b53-a9d0-08e7c1907218.json
packages/react-components/react-color-picker-preview/library/etc/react-color-picker-preview.api.md
packages/react-components/react-color-picker-preview/library/src/components/AlphaSlider/useAlphaSliderState.ts
packages/react-components/react-color-picker-preview/library/src/components/ColorPicker/ColorPicker.types.ts
packages/react-components/react-color-picker-preview/library/src/components/ColorSlider/useColorSlider.ts
packages/react-components/react-color-picker-preview/library/src/contexts/colorPicker.ts
packages/react-components/react-color-picker-preview/library/src/utils/createHsvColor.ts

Color was always defined in context. That caused conflict in state when user passed `defaultState`.
Color in context is undefined

fix(react-color-picker): default state of ColorPicker

---

change/@fluentui-react-charting-2caf6b30-798c-40cb-98ca-64aade9cc329.json
packages/charts/react-charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx

fix(declarative-chart): Remove Duplicate keys warning

---

change/@fluentui-react-menu-820da09f-c52a-4751-a749-7f8ca4387d65.json
packages/react-components/react-menu/library/src/components/MenuItem/MenuItem.test.tsx
packages/react-components/react-menu/library/src/components/MenuItem/__snapshots__/MenuItem.test.tsx.snap
packages/react-components/react-menu/library/src/components/MenuItem/useMenuItem.tsx
packages/react-components/react-menu/library/src/components/MenuItemCheckbox/__snapshots__/MenuItemCheckbox.test.tsx.snap
packages/react-components/react-menu/library/src/components/MenuItemRadio/__snapshots__/MenuItemRadio.test.tsx.snap
packages/react-components/react-menu/library/src/components/MenuList/MenuList.cy.tsx

Currently the MenuItem uses `onMouseEnter` to focus - this causes a nasty side effect where the menu item is focused if the menu opens and hte cursor just happens to be on top of a menuitem.
This PR changes the logic to use `onMouseMove` which requires the user to explicitly move the cursor inside the menu item
- Fixes #

fix: MenuItem is only focused when mouse cursor is moved

---

change/@fluentui-react-carousel-6f17b80c-0ebc-4bca-969c-2776de76fc80.json
packages/react-components/react-carousel/library/src/components/CarouselNavButton/useCarouselNavButton.ts
packages/react-components/react-carousel/library/src/components/CarouselNavImageButton/useCarouselNavImageButton.ts
packages/react-components/react-carousel/library/src/components/useEmblaCarousel.ts

An exception would be thrown when the CarouselSlider window was resized to be larger than the CarouselCards themselves.
When Carousel slider is set to greater width than the combined cards width, it will default to a single page navigation icon and be array safe.
- Fixes #33729

Carousel: Ensure safe indexing of carousel on resize edge case

---

change/@fluentui-react-button-82ba9b76-3c25-43aa-a6d1-32edfcf774ae.json
packages/react-components/react-button/library/src/components/SplitButton/useSplitButtonStyles.styles.ts

Current SplitButton subtle and transparent variants have a divider that does not match Figma specification.
- Fixes #33721

fix(react-button): make SplitButton divider match Figma spec

---

change/@fluentui-react-tree-21c9c828-174f-4ff3-8c60-9de46396262a.json
packages/react-components/react-tree/library/src/components/Tree/Tree.cy.tsx
packages/react-components/react-tree/library/src/components/TreeItemLayout/useTreeItemLayout.tsx

When mixing keyboard and mouse navigation while interacting with the `TreeItem` the actions lose visibility even though the `TreeItem` remains focused
Reproduction steps:
1. Focus on a treeitem with actions to make the actions visible (keyboard navigation)
2. Move your mouse in and out of the treeitem (mouse navigation)
3. The actions are not visible anymore although the treeitem remains focused
1. Ensures actions remain visible whenever `mouseout` events are launched in a focused `TreeItem`
2. add tests to ensure behaviour
- Fixes #

bugfix(react-tree): actions lose visibility when mouse and keyboard interactions are mixed

---

change/@fluentui-react-tag-picker-81e8253d-652a-423d-bd38-2f4ee36719cb.json
packages/react-components/react-tag-picker/library/src/components/TagPicker/TagPicker.test.tsx
packages/react-components/react-tag-picker/library/src/components/TagPickerControl/useTagPickerControl.tsx

The expand button was the one holdout control that didn't get semantically disabled when the control is disabled
Adds `aria-disabled`! (the functionality is already handled, only the semantics were missing)
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/24544)

fix(TagPicker): add aria-disabled to expand button when disabled

---

packages/react-components/react-carousel/stories/src/Carousel/CarouselControlled.stories.tsx
packages/react-components/react-carousel/stories/src/Carousel/CarouselFirstRunExperience.stories.tsx

A couple missing `aria-labels` in two stories
Moar `aria-label`s
- Fixes [ADO issue 1](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/24618) and [ADO issue 2](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/24615)

docs(react-carousel): add accNames to FRE dialog and autoplay button

---

change/@fluentui-react-charting-3e1ae476-d4f7-4de9-a64c-75551a66123a.json
packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx
packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchema.ts

1. Gauge chart not crashing
2. Added check for falling back to VSBC if xAxisType data is not of number type in HBCWithAxis.
- Fixes #

fix(declarative-chart): Gauge chart crash fix

---

change/@fluentui-react-tag-picker-47947df9-46a1-4b10-b5b4-30965038a3c8.json
packages/react-components/react-tag-picker/library/src/components/TagPickerOption/useTagPickerOptionStyles.styles.ts
packages/react-components/react-tag-picker/stories/src/TagPicker/TagPickerDefault.stories.tsx

PR #33689 introduced a regression whenever a `TagpickerOption` is without `secondaryContent`, this regression wasn't caught by our VR pipelines because there were no stories without `secondaryContent`
1. fix regression
2. modify default story to not include `secondaryContent` to ensure this will be caught in VR
- Fixes #

bugfix(react-tag-picker): regression from #33689

---

packages/react-components/react-avatar/stories/src/AvatarGroup/index.stories.tsx

No subcomponent props on the page
Added subcomponents props
- Fixes #32310

docs(react-avatar): Added subcomponents object to the stories

---

change/@fluentui-web-components-8e320b35-61fc-4ce1-839f-b5f03a85aa8d.json
packages/web-components/src/dropdown/dropdown.spec.ts
packages/web-components/src/dropdown/dropdown.ts

When pressing the spacebar on a Dropdown, the dropdown would open and immediately close.
The dropdown now opens when pressing the spacebar.

fix(web-components): Dropdown opens and immediately closes on space key interaction

---

change/@fluentui-react-button-cb94dc1b-6be7-4fdb-aff3-9c27f8051fa3.json
packages/react-components/react-button/library/src/components/Button/useButtonStyles.styles.ts

The `disabledFocusable` button icon does not inherit the `GrayText` system color keyword set on the button, since the icon's color is set with a higher specificity. We already handle this for things like `:hover`, it was just missing for the `disabledFocusable` state (which is different from `disabled` since we need to set the `GrayText` color manually):
```css
'@media (forced-colors: active)': {
':hover': {
color: 'Highlight',
[`& .${buttonClassNames.icon}`]: {
color: 'Highlight',
},
},
':hover:active': {
color: 'Highlight',
[`& .${buttonClassNames.icon}`]: {
color: 'Highlight',
},
},
},
},
```
The icon color is set correctly:
Fixes an issue in FAI

fix: Button sets correct disabledFocusable icon color in forced-colors mode

---

change/@fluentui-react-virtualizer-e04ca2a2-610b-4a84-afbc-0d2f74e7ee06.json
packages/react-components/react-virtualizer/library/src/components/Virtualizer/useVirtualizer.ts

Child render hook was regressed so that it wouldn't force update on child render changes.
Fixed regression, will now update on child render changes
- Fixes #33739
- Fixes #33157

Virtualizer: Ensure child render function updates children immediatly

---

.github/CODEOWNERS

owners file is invalid 
- removes invalid user handles
- adds charting to VR tests
- removes unnecessary owner declarations
- Fixes https://github.com/microsoft/fluentui/issues/31615

ci: cleanup codeowners and add charting to VR test

---

change/@fluentui-web-components-bd877b00-0d8e-4274-aa43-b5f748e419c2.json
packages/web-components/src/menu-item/menu-item.template.ts
packages/web-components/src/menu-item/menu-item.ts
packages/web-components/src/menu/menu.spec.ts

We were filtering for items that had a `elementinternals.role` set to `menu` in the `submenu` slot. This was overkill because you are explicitly setting the element to be a `submenu`. Also this is causing issues where component libraries extend or reimplement the class and template where the filtering never passses the condition and breaks the menu.
Removes the unnecessary filtering in menu-item allowing the menu to work in extended component libraries.
- Fixes #

[fix]: remove unnecessary filtering in menu-item

---

change/@fluentui-react-message-bar-c11b8cce-0b38-48e0-9b98-757e7750e80f.json
packages/react-components/react-message-bar/library/src/components/MessageBar/MessageBar.test.tsx
packages/react-components/react-message-bar/library/src/components/MessageBar/useMessageBarReflow.ts

Reverts microsoft/fluentui#33409
The fix caused a regression for multiple users - reverting now before fixing forward since the reflow logic for MessageBar is quite tricky to begin with 
Fixes #33790

Revert "fix: MessageBar auto reflow should handle document reflow with `min-content`"

---

apps/chart-docsite/.storybook/main.ts
apps/chart-docsite/.storybook/preview.tsx
apps/chart-docsite/package.json
apps/chart-docsite/project.json
apps/chart-docsite/src/DocsComponents/FluentDocsContainer.tsx
apps/public-docsite-v9/src/DocsComponents/FluentDocsContainer.stories.tsx
change/@fluentui-chart-web-components-90a92ca1-c560-43e9-a5fa-cb87c11063ec.json
change/@fluentui-react-charting-a87fd601-35db-40d1-b7b6-be6b71ea83c2.json
change/@fluentui-react-charts-preview-cbb156e6-46e4-46d2-9772-6ba9c4778669.json
packages/charts/chart-web-components/project.json
packages/charts/react-charting/project.json
packages/charts/react-charts-preview/library/project.json
packages/charts/react-charts-preview/stories/project.json
packages/react-components/react-storybook-addon/project.json
packages/react-components/react-storybook-addon/src/theme.ts

**public-docsite-v9** 
- build target executes all react-component suite deps
**charting-docs**
- depends on whole react-components v9  
- depends on projectType: application, which is forbidden ( app cannot depend on another app )
- build target suffers same issue like docsite-v9
**public-docsite-v9**
- build runs only necessary build targets of its dependencies 
- from 69 to 14 target
- speed bump 414s to 120s / **𝚫 71% FASTER**
**charting-docs**
- depends only on charting domain + shared workspace SB addons
- removes forbidden app dependencies
- build runs only necessary build targets of its dependencies 
-  from 69 to 14 targets 
-  speed bump from 361s to 75s / **𝚫 79% FASTER**
_BEFORE:_
_AFTER:_
**misc:**
- introduce new `charting` domain tag
- Fixes #

fix: resolve v9 and charting public docsite dependency issues and improve performance

---

.github/workflows/docsite-publish-ghpages.yml

v9 docsite publish is broken https://github.com/microsoft/fluentui/actions/runs/13266910006/job/37036574884
v9 docsite publish works
- Fixes #

ci: migrate to latest gh-pages actions to make v9 docsite deploy work

---

.github/workflows/pr-website-deploy.yml
apps/public-docsite-v9/.storybook/main.js
apps/public-docsite-v9/package.json

Starting 4 weeks ago pr website deploy runs started to fail with OOM errors. This issues started to appear almost on every 2nd pipeline run this week.
https://github.com/microsoft/fluentui/actions/workflows/pr-website-deploy.yml
After further troubleshooting the issue is with DocGen (via  react docgen) generation while running `storybook build` for`public-docsite-v9`
- caused by ever increasing TS code we ship as part of stories that is non trivial to parse from TS through the react-docgen ( Slot api for example ) 
This PR overrides default Image Node heap size to accomodate heavy RAM usage while building production assets for v9 docsite
> NOTE: tested multiple re-runs with 100% success https://github.com/microsoft/fluentui/actions/runs/13291099420?pr=33826
- Fixes #

fix(public-docsite-v9): increase heap size to prevent OOM failures

---

packages/react-components/react-combobox/stories/src/Combobox/ComboboxVirtualizer.stories.tsx

Combobox did not scroll to it's currently selected item as it's virtualized on open
Combobox now scrolls to item on open, relies on timeout to scroll on the stack immediately after render - I did try implement this on state change of open with useEffect, however it was calling the scrollTo prior to the open render completion.
- Fixes #31437

Combobox: Set combobox story to scroll to selected option on open

---

change/@fluentui-react-components-ad800f8d-e8e3-461f-9e10-98fdd18d2f48.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts

The Fluent implementation is better than all other versions I've seen implemented in product and supports multiwindow/iframes with better typing support that returns the type of the desired HTML element.
Exporting this so that others can share in the love

feat: export isHTMLElement from public API

---

change/@fluentui-react-cbf71cd7-350f-40b3-8bad-303f3e8a150b.json
packages/react/src/components/KeytipLayer/KeytipTree.ts

**COMPONENT ERROR: Cannot read properties of undefined (reading 'parent')**
webpack://owa/node_modules/@fluentui/react/lib/components/src/components/KeytipLayer/KeytipTree.ts parent 69
webpack://owa/node_modules/@fluentui/react/lib/components/src/components/KeytipLayer/KeytipLayer.base.tsx updateNode 520
webpack://owa/node_modules/@fluentui/utilities/src/EventGroup.ts apply 258
webpack://owa/node_modules/@fluentui/utilities/src/EventGroup.ts call 109
webpack://owa/node_modules/@fluentui/react/lib/utilities/src/utilities/keytips/KeytipManager.ts raise 107
webpack://owa/node_modules/@fluentui/react/lib/components/src/components/KeytipData/useKeytipData.ts update 35
No errors should occur when obtaining the parent node.
- Fixes #33866

fix(KeytipTree): refactor updateNode to improve parent handling

---

apps/vr-tests-react-components/.storybook/main.js
apps/vr-tests-web-components/.storybook/main.cjs
apps/vr-tests/.storybook/main.js
package.json
yarn.lock

- bump storywright to latest version to supports storyStoreV7 ( storybook 7 and 8 ) and improve Steps API DX
- https://github.com/microsoft/storywright/pull/70
- https://github.com/microsoft/storywright/pull/69
- https://github.com/microsoft/storywright/pull/71
- revert storyStorev7 disablement 
- fixes all v0 vr snapshots to proper state (700+)
- Follows https://github.com/microsoft/fluentui/pull/33783, https://github.com/microsoft/fluentui/issues/33759

chore: migrate to latest storywright which supports storyStore v7 and re-enable it within vr-tests SB setup

---

apps/vr-tests-react-components/package.json
apps/vr-tests-react-components/project.json

workspace SB addon are transpiled and consumed as expected within production storybook build that is served to storywright
- Follows https://github.com/microsoft/fluentui/pull/33825

fix(vr-tests-react-components): make sure build-storybook has all deps build assets before it runs

---

change/@fluentui-react-teaching-popover-d03a74a3-b27c-483e-88c5-5cc65d5d4da7.json
packages/react-components/react-teaching-popover/library/etc/react-teaching-popover.api.md
packages/react-components/react-teaching-popover/library/src/components/TeachingPopoverCarousel/Carousel/Carousel.tsx
packages/react-components/react-teaching-popover/library/src/components/TeachingPopoverCarousel/Carousel/Carousel.types.ts
packages/react-components/react-teaching-popover/library/src/components/TeachingPopoverCarousel/TeachingPopoverCarousel.types.ts
packages/react-components/react-teaching-popover/library/src/components/TeachingPopoverCarousel/useTeachingPopoverCarousel.ts
packages/react-components/react-teaching-popover/stories/src/TeachingPopover/TeachingPopoverCarousel.stories.tsx

Since focus stays in place and there is no `announce()` / live region change on slide changes, there's no information exposed to screen reader users when the next/previous buttons are used.
Calls `announce()` on slide changes.
There's still a tabster issue that needs to be handled before this will fully work, since right now tabster adds `aria-hidden` to the live region node when a modal dialog (like the teaching popover) is open.
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/22231)

fix(TeachingPopover): TeachingPopoverCarousel calls announce() for slide changes

---

change/@fluentui-set-version-387b41d1-8143-430e-b11f-46ccaa9f229b.json

users on Windows OS started to run into build failures caused by sourcemaps.
```
ERROR in ../../.store/@fluentui-react-window-provider@2.2.28-15ac61a2cbcde8b63c53/node_modules/@fluentui/react-window-provider/lib/version.js
Module Warning (from ../../.store/source-map-loader@4.0.1-e7a97479dfc7ed968bba/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'D:\project\.store\@fluentui-react-window-provider@2.2.28-15ac61a2cbcde8b63c53\node_modules\@fluentui\react-window-provider\src\version.ts' file: Error: ENOENT: no such file or directory, open 'D:\project\.store\@fluentui-react-window-provider@2.2.28-15ac61a2cbcde8b63c53\node_modules\@fluentui\react-window-provider\src\version.ts'
@ ../../.store/@fluentui-react-window-provider@2.2.28-15ac61a2cbcde8b63c53/node_modules/ …
```

fix(react): trigger v8 release to fix production source-maps issues

---

change/@fluentui-react-aria-f408c823-66bb-4037-9e44-2fbbd8b12345.json
change/@fluentui-react-tabster-b7fd7b03-782c-45a5-b1ff-aa78ac6fad3d.json
packages/react-components/react-aria/library/src/AriaLiveAnnouncer/useDomAnnounce.ts
packages/react-components/react-tabster/etc/react-tabster.api.md
packages/react-components/react-tabster/src/hooks/index.ts
packages/react-components/react-tabster/src/hooks/useModalAttributes.ts
packages/react-components/react-tabster/src/index.ts

Fluent v9 modals would hide live regions generated by `useAnnounce`, which prevents them from being picked up by screen readers when a modal is open.
The v9 react-tabster modal hook makes use of the tabster option to provide an opt-out from `aria-hidden`, exposed as a hook.
- Fixes [ADO issue on TeachingPopover](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/22231)

fix: useAnnounce live regions do not get aria-hidden from tabster

---

packages/react-components/react-virtualizer/stories/src/VirtualizerScrollView/Default.stories.tsx
packages/react-components/react-virtualizer/stories/src/VirtualizerScrollView/ScrollTo.stories.tsx
packages/react-components/react-virtualizer/stories/src/VirtualizerScrollView/SnapToAlignment.stories.tsx
packages/react-components/react-virtualizer/stories/src/VirtualizerScrollView/VirtualizerScrollViewAccessibility.md
packages/react-components/react-virtualizer/stories/src/VirtualizerScrollView/index.stories.ts
packages/react-components/react-virtualizer/stories/src/VirtualizerScrollViewDynamic/AutoMeasure.stories.tsx
packages/react-components/react-virtualizer/stories/src/VirtualizerScrollViewDynamic/Default.stories.tsx
packages/react-components/react-virtualizer/stories/src/VirtualizerScrollViewDynamic/ScrollLoading.stories.tsx
packages/react-components/react-virtualizer/stories/src/VirtualizerScrollViewDynamic/ScrollTo.stories.tsx
packages/react-components/react-virtualizer/stories/src/VirtualizerScrollViewDynamic/SnapToAlignment.stories.tsx
packages/react-components/react-virtualizer/stories/src/VirtualizerScrollViewDynamic/VirtualizerScrollViewDynamicAccessibility.md
packages/react-components/react-virtualizer/stories/src/VirtualizerScrollViewDynamic/index.stories.ts

Couple docs-only updates to virtualizer stories that add:
- explicit `tabindex` + `aria-label` to examples to allow keyboard scrolling & avoid having all content get read out when the scroll area is focused (some but not all browsers, e.g. Edge and Firefox, already make scroll overflow regions tabbable by default).
- add `aria-live` to the scroll-to example's text for screen reader feedback on scroll
- add a small a11y docs section to explain the `tabindex` & when it is or isn't needed
I only added these to the scroll & dynamic scroll components since the base virtualizer doesn't have the `container` node built in, but I was kinda iffy on whether the base virtualizer should have it too.
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/24616)

docs(Virtualizer): update examples for better accessibility and add a11y docs section

---

packages/react-examples/src/react/ContextualMenu/ContextualMenu.CustomMenuList.Example.tsx

This PR adds `preventDismissOnResize` to the `ContextualMenu` example that renders a `SearchBox` within the menu list. This is done to prevent the menu from being dismissed in Android devices when the keyboard is opened on focus of the `SearchBox` (which is automatically focused as the first item when the menu is opened), as this triggers a window resize event in Android devices.

docs(`react-examples`): Preventing dismiss on resize on `ContextualMenu` example that renders a `SearchBox` within its menu list

---

change/@fluentui-web-components-faa00d2e-ce58-4ae2-88af-ae49ab82bd76.json
packages/web-components/docs/web-components.api.md
packages/web-components/src/dropdown/dropdown.spec.ts
packages/web-components/src/dropdown/dropdown.ts
packages/web-components/src/listbox/listbox.ts

The `<fluent-dropdown>` web component doesn't emit a `change` event when the value is changed via user interaction.
Clicking, pressing enter, or tabbing away from the dropdown causes the dropdown to emit a `change` event when the value changes.

fix(web-components): dropdown should emit change event when value changes via user input

---

azure-pipelines.release-vnext-nightly.yml

adds support to manually trigger nightly from different branch 
**NOTE:** This is suitable for testing purposes without affecting main branch and official stable release
- Fixes #

ci: add v9 nightly releases support from branch

---

change/@fluentui-react-link-1e1b940f-ffba-4000-a504-26774a8822aa.json
packages/react-components/react-link/library/src/components/Link/Link.tsx

This pull request includes changes to the `@fluentui/react-link` package to fix an issue where the Link component was not pulling the custom style hook from the context. The most important changes include adding the custom style hook import and applying the custom style hook in the `Link` component.
Changes to `@fluentui/react-link` package:
Updates to `Link` component:
* [`packages/react-components/react-link/library/src/components/Link/Link.tsx`](diffhunk://#diff-c5fffbe659d691f587c693ef4b1d714ecf76ff44d1cd42899072224382fdcc95R7): Imported `useCustomStyleHook_unstable` from `@fluentui/react-shared-contexts`.
* [`packages/react-components/react-link/library/src/components/Link/Link.tsx`](diffhunk://#diff-c5fffbe659d691f587c693ef4b1d714ecf76ff44d1cd42899072224382fdcc95R17-R18): Applied …

Fixed Link so that it pulls customStyleHook from context

---

change/@uifabric-icons-3b4073c5-cede-4e71-9cd8-1ec204871583.json
packages/icons/src/index.ts

- A fix was made in #33639 to update the icon's base URL to the new CDN but nothing was published due to a missing change file. This PR adds a change file to trigger the publish.
- Follows #33639

chore(7.0): add change file to trigger new v7 publish

---

change/@fluentui-eslint-plugin-728becf6-2abf-400f-b3bc-7a5049b39ba9.json
package.json
packages/eslint-plugin/package.json
packages/eslint-plugin/src/configs/base.js
packages/eslint-plugin/src/configs/core.js
packages/eslint-plugin/src/utils/configHelpers.js
syncpack.config.js
yarn.lock

No browser compatibility linter rules were available.
Added `eslint-plugin-compat` to ensure browser compatibility according to [the current browser support matrix](https://react.fluentui.dev/?path=/docs/concepts-developer-browser-support-matrix--docs#full-browser-support-matrix)
- Implements #33661

feat(eslint-plugin): add browser compatibility plugin

---

apps/public-docsite-v9/src/Concepts/Positioning/PositioningCoverTarget.stories.tsx
apps/public-docsite-v9/src/Concepts/Positioning/PositioningShorthandPositions.stories.tsx

The cover & shorthand examples on the positioning docs page were clipped when the page zoomed/resized down at all:
While this could theoretically be solved by just adding a scroll overflow without changing the layout at all, the issue is that the current layout doesn't even fit within storybook at full size. So adding a scroll overflow style makes it scroll-overflow all the time, looking rather odd:
(the left margin of the story is necessary to ensure the popup has enough space to render at smaller sizes)
I updated the grid layout to be a more compact grid so it would fit within the story at full width, and also be able to scroll-overflow at smaller screens:
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/24784)

docs: update positioning examples to work with page resize

---

packages/react-components/react-tags/stories/src/InteractionTag/InteractionTagDismiss.stories.tsx
packages/react-components/react-tags/stories/src/InteractionTag/InteractionTagShape.stories.tsx
packages/react-components/react-tags/stories/src/InteractionTag/InteractionTagSize.stories.tsx
packages/react-components/react-tags/stories/src/Tag/TagAppearance.stories.tsx
packages/react-components/react-tags/stories/src/Tag/TagDisabled.stories.tsx
packages/react-components/react-tags/stories/src/Tag/TagDismiss.stories.tsx
packages/react-components/react-tags/stories/src/Tag/TagShape.stories.tsx
packages/react-components/react-tags/stories/src/Tag/TagSize.stories.tsx
packages/react-components/react-tags/stories/src/TagGroup/TagGroupDismiss.stories.tsx
packages/react-components/react-tags/stories/src/TagGroup/TagGroupSizes.stories.tsx

- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/24785)

docs: update Tag examples to reflow

---

change/@fluentui-react-tabs-855dafe2-e21a-4274-9fa5-9e20c5b28761.json
packages/react-components/react-tabs/library/src/components/Tab/useTabStyles.styles.ts

**Description of the bug in ADO:**
When using subtle-circular/filled-circular appearance in high contrast aquatic or dessert theme, it is hard to differentiate what tab is selected in the tablist.
This is mostly due to having no background color for selected tab in these theme.
| Previous behavior                                           | Screenshot | New Behavior |
| ----------------------------------------------------------- | ---------- | ------------ |
| Selected state                                              |     ![image](https://github.com/user-attachments/assets/7fb983bf-f947-4713-b305-1862ab71d2c9)    ![image](https://github.com/user-attachments/assets/07e7a118-0c5c-48f7-97ae-813f89f54483)     |     ![image](https://github.com/user-attachments/assets/4bae6a94-cf86-4e08-9434- …

fix(react tabs): Selected tab is not visible in HC on Windows

---

packages/react-components/react-motion/stories/src/Tokens/Cards.styles.ts
packages/react-components/react-motion/stories/src/Tokens/Cards.tsx

Docs-only change, adds high contrast tokens for the visual demonstrations on the motion tokens page.
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/24789)

docs: Motion tokens page supports windows high contrast

---

change/@fluentui-web-components-e9ccc14b-1620-41ad-a9bd-4732e6409007.json
packages/web-components/docs/web-components.api.md
packages/web-components/src/slider/slider.spec.ts
packages/web-components/src/slider/slider.template.ts
packages/web-components/src/slider/slider.ts

After clicking/dragging the thumb, pressing the arrow keys on keyboard doesn't move the thumb/slider value.
Clicking on the thumb puts focus on the slider, which in turn enables keyboard interaction afterward.

fix: enable keyboard interactions after cliking on thumb

---

change/@fluentui-web-components-23edc611-4d8c-4176-975a-3530019982d5.json
packages/web-components/src/button/button.styles.ts

There is no gap between button component's start/end slots and the default slot.
Button's start slot has inline-end spacing and end slot has inline-start spacing.

fix: button slots spacing

---

change/@fluentui-react-toolbar-8bb342b8-9cdc-4d1c-83e9-718c59bf4ef9.json
packages/react-components/react-toolbar/library/src/components/ToolbarRadioButton/useToolbarRadioButtonStyles.styles.ts
packages/react-components/react-toolbar/library/src/components/ToolbarToggleButton/useToolbarToggleButtonStyles.styles.ts

We overrode the color for the selected state for the Radio & ToggleButton Toolbar variants, otherwise using all styles from ToggleButton. Overriding just the selected color value meant that the color/background token pair was not a pair with guaranteed contrast, which caused the Teams high contrast theme to fail contrast checks in that state.
In Teams high contrast:
After chatting with design, we decided to go with adopting the subtle variant of the ToggleButton's styles for the selected state for radio & toggle Toolbar buttons.
New colors in teams high contrast:
The other themes end up with the same hex values, so there is no visible change.
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/24803)

fix(react-toolbar): use contrasting token pairs for radio & toggle selected states

---

packages/react-components/react-drawer/stories/src/Drawer/DrawerBestPractices.md
packages/react-components/react-drawer/stories/src/Drawer/DrawerCustomSize.stories.tsx
packages/react-components/react-drawer/stories/src/Drawer/DrawerDefault.stories.tsx
packages/react-components/react-drawer/stories/src/Drawer/DrawerMotionDisabled.stories.tsx
packages/react-components/react-drawer/stories/src/Drawer/DrawerMultipleLevels.stories.tsx
packages/react-components/react-drawer/stories/src/Drawer/DrawerPosition.stories.tsx
packages/react-components/react-drawer/stories/src/Drawer/DrawerPreventClose.stories.tsx
packages/react-components/react-drawer/stories/src/Drawer/DrawerResponsive.stories.tsx
packages/react-components/react-drawer/stories/src/Drawer/DrawerSize.stories.tsx
packages/react-components/react-drawer/stories/src/Drawer/DrawerWithNavigation.stories.tsx
packages/react-components/react-drawer/stories/src/Drawer/OverlayDrawer.stories.tsx
packages/react-components/react-drawer/stories/src/Drawer/OverlayDrawerNoModal.stories.tsx
packages/react-components/react-drawer/stories/src/Drawer/OverlayInsideContainer.stories.tsx

Most of our examples did not restore focus from the drawer when closed. This is because Drawer does not include a trigger as Dialog does, so the triggering buttons do not have the required tabster attributes to handle focus restoration. The result is that the modal drawer surface does have the tabster attrs to try to restore focus, but will send it back to some other random trigger on the page.
The docs make it seem like the goal was to automatically handle focus restoration for OverlayDrawers, but that doesn't seem possible, since it doesn't look like Drawer was designed to have the trigger as a child. Let me know if I've misunderstood how it's intended to work, though.
All our examples (aside from some inline drawers that are left as-is to demo intentional lack of focus restoration) add …

docs: add focus restoration to our examples, and update the docs to reflect authoring requirements

---

change/@fluentui-web-components-41bd9d29-ee1e-4b05-b599-add4a1718f07.json
packages/web-components/src/tablist/tablist.spec.ts
packages/web-components/src/tablist/tablist.stories.ts
packages/web-components/src/tablist/tablist.ts

The component requires developers to listen to the `change` event to handle tab selection changes and panel changes manually.
Developers can add `aria-controls` attribute to `<fluent-tab>`, and the element that `aria-controls` references to will be automatically associated to the `<fluent-tab>` element, and will show/hide (by toggling `hidden` attribute) based on selected tabs in the tab list.

feat: auto associate tabpanels with tabs

---

packages/react-components/react-color-picker-preview/library/docs/MIGRATION.md
packages/react-components/react-color-picker-preview/library/docs/Spec.md

Updated the spec and the migration docs

docs(react-color-picker): updated the spec and the migration

---

change/@fluentui-react-color-picker-preview-8713fe9e-a809-45c5-9ecc-d05c8e596a2a.json
packages/react-components/react-color-picker-preview/library/src/components/AlphaSlider/useAlphaSliderStyles.styles.ts
packages/react-components/react-color-picker-preview/library/src/components/ColorArea/useColorAreaStyles.styles.ts
packages/react-components/react-color-picker-preview/library/src/components/ColorPicker/useColorPickerStyles.styles.ts
packages/react-components/react-color-picker-preview/library/src/components/ColorSlider/useColorSliderStyles.styles.ts

Fix for thumb positioning looks weird on edges:
Talked to @gouttierre and Toshie, we decided to stay with this design which is currently in V8.
- Slider wasn't moving on edges
- Spacing is too narrow
- Slider is moving on edges
- Part of thumb is visible outside of ColorSlider and ColorArea
- Spacing is bigger between sliders and color area

fix(react-color-picker): place thumb outside of Sliders and ColorArea

---

change/@fluentui-react-search-1ad2aa86-fd4b-49da-b241-b5b55bbb02e2.json
change/@fluentui-react-shared-contexts-dad685da-3118-47dc-9bee-668dd722a0b3.json
packages/react-components/react-search/library/package.json
packages/react-components/react-search/library/src/components/SearchBox/SearchBox.tsx
packages/react-components/react-search/stories/src/SearchBox/SearchBoxDefault.stories.tsx
packages/react-components/react-shared-contexts/library/etc/react-shared-contexts.api.md
packages/react-components/react-shared-contexts/library/src/CustomStyleHooksContext/CustomStyleHooksContext.ts

Users were unable to apply CustomStyleHooks to SearchBox component.
Users can now apply CustomStyleHooks to SearchBox. The screen shots below show test cases for each component that demonstrate the ability to apply Custom Hooks. In each Custom Hook, the backgroundColor of the component was updated to 'red'. The test code will be REMOVED but can be found in [this commit](https://github.com/microsoft/fluentui/commit/25ef567d0951095e588339094d2d62d1e9448cf6)  The test code applies Custom Style Hooks to the Default styling.

Fix: SearchBox CustomStyleHook Implementation

---

change/@fluentui-react-combobox-106e472a-1ade-4d1f-bc51-5eddd30b8ecf.json
change/@fluentui-react-tag-picker-ea411c94-0c82-44e5-87ff-5d073f48599d.json
change/@fluentui-react-textarea-6305fa37-552a-4cf8-8dd6-92f2dbee276c.json
packages/react-components/react-combobox/library/src/components/Combobox/useComboboxStyles.styles.ts
packages/react-components/react-combobox/library/src/components/Dropdown/useDropdownStyles.styles.ts
packages/react-components/react-tag-picker/library/src/components/TagPickerControl/useTagPickerControlStyles.styles.ts
packages/react-components/react-textarea/library/src/components/Textarea/useTextareaStyles.styles.ts

Fixing reported issue (#33135), we have visual inconsistencies between Figma designs and our multiple input components. Those components currently do not have shared styles, so it has to be fixed on multiple places. The reported issue mention high-contrast, but it happens in all themes for outline appearance for hover, active and focus styles. Combobox & Dropdown, Textarea, TimePickerCompat (fixed by fixing combobox styles), TagPicker. 
hover in high contrast:
focus in high contrast: 
figma spec: 
- hover: 
- focus:
Updated to visually match design spec
- Fixes #33135

fix: incorrect tokens used across multiple input components

---

azure-pipelines.deprecate-package.yml

- updates Deprecate Published Package pipeline to use 1ESPT similar to other production pipelines #29702
Successful [test run](https://uifabric.visualstudio.com/UI%20Fabric/_build/results?buildId=371596&view=logs&j=7494ae37-3ecd-50c6-9ffe-c77a2768c545&t=b959630e-d70a-505e-fcef-1e91d82979e4)

chore(CI): migrate NPM Deprecate pipeline to 1ESPT

---

packages/react-examples/src/react/Button/Button.ContextualMenu.Example.tsx
packages/react-examples/src/react/List/List.Basic.Example.tsx
packages/react-examples/src/react/List/List.Ghosting.Example.tsx
packages/react-examples/src/react/List/List.Grid.Example.tsx

This fixes two minor bugs in v8 examples:
1. List examples had images with no alt attributes; now they have `alt=""`, which marks them as presentational (and is different from a missing alt)
2. The Button - ContextualMenu example had a `onDismiss` handler that prevented any dismissal with the keyboard, rather than just preventing it when the shift key was pressed, which was the intent. Now it works :D.
- Fixes 2 ADO bugs

docs: fix minor accessibility bugs in v8 example code

---

packages/react-components/react-migration-v0-v9/library/jest.config.js
packages/react-components/react-migration-v8-v9/library/jest.config.js

intermittent OOM issues started to occur more regularly  https://github.com/microsoft/fluentui/actions/runs/13795119408/job/38584776289
because v0 and v8 migration will import whole v0/v8 respectively witin the test the memory limit is reached very easily
adding memory limit to jest should prevent these OOM issues
- Follows https://github.com/microsoft/fluentui/pull/33556/files#diff-1093fac4db13e4684822c88854b913a5466e53b5b82a52d53e0e7c7e4ee04bb9

test(react-migration-v0,v8): add memory limit to make jest not fail OOM on ci

---

apps/vr-tests-react-components/src/stories/Tag/InteractionTag.stories.tsx
apps/vr-tests-react-components/src/stories/Tag/Tag.stories.tsx
change/@fluentui-react-tags-1bd0d3f5-fdd3-4ed1-958f-b083a09a07f5.json
packages/react-components/react-tags/library/etc/react-tags.api.md
packages/react-components/react-tags/library/src/components/InteractionTag/InteractionTag.types.ts
packages/react-components/react-tags/library/src/components/InteractionTag/useInteractionTag.tsx
packages/react-components/react-tags/library/src/components/InteractionTag/useInteractionTagContextValues.ts
packages/react-components/react-tags/library/src/components/InteractionTagPrimary/InteractionTagPrimary.types.ts
packages/react-components/react-tags/library/src/components/InteractionTagPrimary/useInteractionTagPrimary.ts
packages/react-components/react-tags/library/src/components/InteractionTagPrimary/useInteractionTagPrimaryStyles.styles.ts
packages/react-components/react-tags/library/src/components/InteractionTagSecondary/InteractionTagSecondary.types.ts
packages/react-components/react-tags/library/src/components/InteractionTagSecondary/useInteractionTagSecondary.tsx
packages/react-components/react-tags/library/src/components/InteractionTagSecondary/useInteractionTagSecondaryStyles.styles.ts
packages/react-components/react-tags/library/src/components/Tag/Tag.types.ts
packages/react-components/react-tags/library/src/components/Tag/useTag.tsx
packages/react-components/react-tags/library/src/components/Tag/useTagStyles.styles.ts
packages/react-components/react-tags/library/src/components/TagGroup/TagGroup.cy.tsx
packages/react-components/react-tags/library/src/components/TagGroup/TagGroup.types.ts
packages/react-components/react-tags/library/src/components/TagGroup/useTagGroup.ts
packages/react-components/react-tags/library/src/components/TagGroup/useTagGroupContextValues.ts
packages/react-components/react-tags/library/src/contexts/interactionTagContext.tsx
packages/react-components/react-tags/library/src/contexts/tagGroupContext.tsx
packages/react-components/react-tags/library/src/utils/types.ts
packages/react-components/react-tags/stories/src/InteractionTag/InteractionTagSelected.stories.tsx
packages/react-components/react-tags/stories/src/InteractionTag/index.stories.tsx
packages/react-components/react-tags/stories/src/Tag/TagSelected.stories.tsx
packages/react-components/react-tags/stories/src/Tag/index.stories.tsx
packages/react-components/react-tags/stories/src/TagGroup/TagGroupSelect.stories.tsx
packages/react-components/react-tags/stories/src/TagGroup/index.stories.tsx

Added `selected` state for Tag and InteractionTag
Variants of selected state (for testing)
First part of this feature #33738

feat(react-tag): Added `selected` state for Tag and InteractionTag

---

tools/workspace-plugin/src/generators/bundle-size-configuration/schema.json
tools/workspace-plugin/src/generators/cypress-component-configuration/schema.json
tools/workspace-plugin/src/generators/prepare-initial-release/schema.json

- NOTE: all monorepo project names exclude `npmScope` in order to mitigate churn and verbose typing
- if you decide to avoid using prompts that we ship with our generators, or `yarn nx generate` and provide `--project` name explicitly you  may by accident provide the project name with `npmScope` 
`yarn nx generate @fluentui/workspace-plugin:prepare-initial-release --project=@fluentui/react-color-picker-preview --phase=stable`
`yarn nx generate @fluentui/workspace-plugin:prepare-initial-release --project=@fluentui/react-color-picker-preview --phase=stable`
- Fixes #

feat(workspace-plugin): add generation regexp check in order to prevent running generators with invalid project name including npm scope

---

change/@fluentui-react-spinbutton-d2901e1c-c4b6-47ad-b78e-0ae03c8814f6.json
packages/react-components/react-spinbutton/library/src/components/SpinButton/useSpinButton.tsx

The basic problem is that we use `<input type="text" role="spinbutton">`, which creates tension between the native input `value` and the spinbutton role's expectation for `aria-valuenow`. Some screen readers will use `value`, and others will use `aria-valuenow`. However, if we set `aria-valuenow` with React, the timing of the update is one cycle after the native input/change happens. The result is that some screen readers (Narrator and VoiceOver) will read the previous value instead of the new value on value changes.
I previously removed the default `aria-valuetext` (which is similar to `valuenow` for the purposes of this bug) to avoid having two separate sources of providing the value, but both VO and Narrator will not use the native `value` to calculate a spinbutton value, and will …

fix: Spinbutton aria-valuenow vs native value update timing fix

---

.github/workflows/pr-vrt-comment.yml
.github/workflows/pr-vrt.yml
.github/workflows/vrt-baseline.yml

Testing out a new Github actions supported vr-approval-cli version. This has been tested in an internal EMU repository end-to-end. Changes include -
1. Bump up the vr-approval-cli version to `1.0.0-test.1742371346259`. This is a test only version and a proper release will be done after all testing has completed.
2. The Comment on PR workflow has been revamped to only run VRT when screenshots artifact is generated in original PR. This is to make sure that we can skip VRT when no screenshots were generated.
3. We also directly use github event payload to find PR number and more associated metadata for triggering workflow in Comment on PR workflow.
4. Baseline workflow was added. This will only run on `vrt-gha-testing` branch for now. 
5. Concurrency check removed from Comment on PR. Not …

Test with new vr-approval-cli version

---

change/@fluentui-chart-utilities-ac603907-8d2a-4923-b99d-97107c6d32bf.json
packages/charts/chart-utilities/webpack.config.js

This pull request includes a small change to the `webpack.config.js` file in `packages/charts/chart-utilities`. The change comments out the line that requires `webpack.serve.config` and adds a note explaining that it should be uncommented only if examples are added under the `react-examples/chart-utilities` folder.
This line, when uncommented, was breaking the release pipeline because it was failing the `webpack` step when buildilng the `chart-utilities` package.
Related to #34043.

fix(`chart-utilities`): Fixing failing webpack step in `chart-utilities` package

---

change/@fluentui-react-motion-24284c59-9a62-4f23-9c8e-4aca459271e5.json
packages/react-components/react-motion/library/src/factories/createPresenceComponent.ts
packages/react-components/react-motion/library/src/hooks/useAnimateAtoms.ts
packages/react-components/react-motion/library/src/types.ts
packages/react-components/react-motion/library/src/utils/isAnimationRunning.test.ts
packages/react-components/react-motion/library/src/utils/isAnimationRunning.ts

This PR implements interruptible motions with `createPresence()`.
> ⚠️ Heads up!
>
> This feature is experimental, please do not rely on it for your production code as APIs will change.
The main problem with CSS animations (& Web Animations) that unlike CSS transitions they don't provide a smooth way to interrupt the animation (_well, they do but_):
> If a user decides to close and open again before the close animation is complete, CSS Animations will restart at 0% while CSS transition values will keep their transit state while trying to transition back to the closed state.
> Note
> In the most cases motions are too short to notice the difference, but there are cases when it becomes noticeable.
This PR aims to improve UX. Current limitations:
- Sequences are not supported (& were not …

feat(react-motion): implement interruptible motions [experimental]

---

.github/workflows/pr-vrt-comment.yml
.github/workflows/pr-vrt.yml

- We were trying to fetch PR number from workflow_run event payload, howver it was not available in the payload for workflows triggered from forks. See https://github.com/orgs/community/discussions/25220.
- Use the PR number from artifact method
- However we validate if the head commit of the workflow_run event is same as head commit of PR to validate that the correct PR number of present in the artifact. This verification also allows us to skip vr-approval-cli if there was a push to the PR post workflow trigger.

[vr-approval] Use PR Number from artifact

---

azure-pipelines.release.yml
change/@fluentui-react-3d6721bd-6a4a-4765-8b22-10887f020883.json
change/@fluentui-react-charting-1cd013bc-87ec-4613-bd70-f4e65a6746a4.json

- Adds change files for packages from [last bad release](https://github.com/microsoft/fluentui/commit/a51bd4ada5d54ce74895ce0e63df7ffd533ca964#diff-18f2df2bf681f29d5d093df7dc7977f9adb068aad1ebbc23f4f338fde0462a86) (excluding `@fluentui/charting-utilities` since its build assets [seem correct](https://www.npmjs.com/package/@fluentui/chart-utilities?activeTab=code)). This should trigger a new publish for all packages affected by the last bad release.
- Adds success condition to publishing step as the [last release failed](https://uifabric.visualstudio.com/UI%20Fabric/_build/results?buildId=372039&view=logs&j=7494ae37-3ecd-50c6-9ffe-c77a2768c545&t=b34903f2-f316-5902-ee0a-84fbdf331090) at the build step but still published
- Follows #34044
- Fixes #34043

fix(v8): add change files to trigger new publish of v8

---

change/@fluentui-web-components-8c986d26-b108-4f9d-9fa2-41363776a5b2.json
packages/web-components/src/tablist/tablist.base.ts

`change` event emits multiple times when active tab changed.
`change` event only emit once when active tab changed

fix: emit change event on tablist only when active tab has changed

---

.eslintrc.json
apps/vr-tests-web-components/.eslintrc.json
packages/web-components/.eslintrc.json
tools/workspace-plugin/.eslintrc.json

wc doesn't follow recommended lint configuration guidelines. this ends up leaking rules execution within .json files and providing false positives
wc uses overrides for lint configuration which is future proof for flat config migrations and mitigates issues with leaking scopes from json parser.
- Replaces https://github.com/microsoft/fluentui/pull/33331/files

chore: fix web-components lint setup to avoid leaking rules to json parser scope

---

change/@fluentui-react-motion-798994c5-fba9-4fa0-8228-bd0e7a12cf8d.json
packages/react-components/react-motion/library/src/hooks/useAnimateAtoms.test.tsx
packages/react-components/react-motion/library/src/hooks/useAnimateAtoms.ts

In certain situations Chromium browsers might return `null` from `element.animate()` and Firefox may throw an error. Neither of these behaviors seems to align with [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/animate) or the spec (linked from the MDN page)
We now handle the `null` case as well as the thrown error. Test cases have been added to confirm the fix.
- Fixes #33902

Handle error cases in `element.animate()`

---

packages/react-components/react-dialog/stories/src/Dialog/DialogConfirmation.stories.tsx
packages/react-components/react-dialog/stories/src/Dialog/index.stories.tsx

(docs only change, added a story)
I've had a specific dialog accessibility question come up a few times now -- how to have screen readers auto-read a short (usually confirmation) dialog's content when focus is directly sent to a button at the end of the dialog.
I added a story w/ description showing the recommend ARIA pattern for that type of dialog.

docs: add confirmation dialog example for a11y pattern

---

scripts/package-manager/src/notify-on-file-changes.js

When both `yarn install` and `yarn nx reset` need to be run the order in which they are run is important.
The messages appear in the correct order but it was not clear to me that the order was significant.
This commit adds a message when both Yarn and nx need to be run to clarify that the order in which they run matters.

Clarify update messaging

---

.github/CODEOWNERS

This PR only updates the ownership of the React 18 tests for v8 library.
As v-build is focusing on making updates to React 18, the ownership needs to be updated.

chore: move ownership of React 18 v9 tests app

---

change/@fluentui-react-list-5af220e8-3ce1-4651-9bf6-0855a012082e.json
packages/react-components/react-list/library/src/components/ListItem/useListItem.tsx

restorer attributes passed to `ListItem` are overwriting internal tabster attributes set by the `ListItem`.
All FUI components which set tabster attributes should properly merge them with the incoming prop
Ensures external and internal tabster attributes are properly merged
- Fixes https://github.com/microsoft/fluentui/issues/33844

bugfix(react-list): ensure external tabster attributes are merged with internals

---

packages/react-components/react-list/library/src/components/List/List.cy.tsx
packages/react-components/react-tabster/src/hooks/useFocusedElementChange.cy.tsx

Cypress is very sensitive to timings. Looks that they don't handle well `useEffect()` timings which causes issues with Tabster & other effects.
`.focus()` calls were prepended with `.click()` which somehow waits enough ¯\_(ツ)_/¯

chore: fix tests in List.cy.tsx & useFocusedElementChange.cy.tsx

---

apps/react-18-tests-v9/cypress.config.ts
packages/react-components/react-toolbar/library/src/components/Toolbar/Toolbar.cy.tsx

Cypress is very sensitive to timings. Looks that they don't handle well `useEffect()` timings which causes issues with Tabster & other effects.
Chained assertions were flattened, some `.focus()` calls were replaced with `.click()` which somehow waits enough ¯\_(ツ)_/¯

chore: fix tests in Toolbar.cy.tsx

---

change/@fluentui-react-tag-picker-4a80240e-8a98-47e9-86e2-b5978a0ff4a3.json
packages/react-components/react-tag-picker/library/src/components/TagPicker/TagPicker.cy.tsx
packages/react-components/react-tag-picker/library/src/components/TagPickerControl/useTagPickerControl.tsx

Pushes layout changes (i.e. `innerRef.current?.style.setProperty()`) into a microtask queue:
- 👍 no errors from `ResizeObserver`
- 👍 better performance (single update per a frame)
Uses the advice from SO linked in the test comment.

fix(react-tag-picker): avoid "ResizeObserver loop limit exceeded" exception

---

apps/react-18-tests-v9/cypress.config.ts
packages/react-components/react-overflow/library/src/Overflow.cy.tsx

`Overflow.cy.tsx` is disabled in R18 test suite.
- `Overflow.cy.tsx` is enabled in R18 test suite
- `cy.wrap(el)` unlike `expect(Cypress.$(value).css('display'))` waits for the state with a timeout, so tests become more predictable & stable

chore: fix Overflow.cy.tsx tests

---

change/@fluentui-react-carousel-da58b311-fa0d-4937-a70c-5d21bbe27170.json
packages/react-components/react-carousel/library/src/components/useEmblaCarousel.ts

AutoplayInterval changes cause a re-init of the carousel.
We did not stop previous autoplay instances, causing the autoplay to stack timing events.
AutoplayInterval changes still re-init carousel
Now they do not stack, and will stop previous autoplay instances when Re-initialized.

Carousel: Enable dynamic autoplayInterval

---

.github/workflows/pr.yml
packages/react-components/react-list/library/src/components/List/List.cy.tsx

Currently there are flaky Cypress that fail. Due https://github.com/nrwl/nx/issues/30562 we cannot identify them.
Cypress captures screenshots for failed scenario, so by uploading them we can identify flaky tests.

chore: upload screenshots for failing tests

---

change/@fluentui-react-charting-13afcd7d-f890-49b1-8dc6-59ca95175e60.json
packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts

The value corresponding to each label was used directly to plot the pie chart.
If `labels` contain duplicates, we sum associated values or simply count occurrences if `values` is not provided. For more details, see: [Pie traces in JavaScript](https://plotly.com/javascript/reference/pie/#pie-labels)

fix(react-charting): handle blank donut chart when labels exist without corresponding values in plotly json

---

change/@fluentui-react-charts-42300240-f157-4a51-89ad-d8e994a31a28.json
packages/charts/react-charts/library/src/components/DeclarativeChart/DeclarativeChart.tsx

Dark mode theme colors for declarative charts in v9.
Before:
After:

fix(react-charts): Dark mode theme colors for declarative charts in v9

---

change/@fluentui-react-charts-e55ab3f2-a848-4cee-abef-5548469f52f5.json
packages/charts/react-charts/library/src/components/ScatterChart/ScatterChart.tsx
packages/charts/react-charts/stories/src/ScatterChart/ScatterChartDefault.stories.tsx

Enabling multiple legend selection for Scatter Chart in v9.

fix(react-charts): Enabling multiple legend selection for Scatter Chart in v9

---

.github/workflows/pr.yml
apps/react-18-tests-v9/README.md
apps/react-18-tests-v9/package.json
apps/react-18-tests-v9/project.json
apps/react-18-tests-v9/tsconfig.react-18.json

- adds new `type-check:integration` target to execute properly scoped `@types/react@18` against all v9 story files
- adds new workflow job which executes react 18 specific integration tests without affecting rest of pipelines
**NOTE:** the intent to see the job failing is EXPECTED to have transparent metric tracking progress of making v9 compatible with react 18
- Fixes #

feat: setup react 18 integration type checking

---

.github/workflows/pr.yml
apps/react-18-tests-v9/.eslintrc.json
apps/react-18-tests-v9/README.md
apps/react-18-tests-v9/cypress-react-18.config.ts
apps/react-18-tests-v9/package.json
apps/react-18-tests-v9/project.json

moves repo cypress integration tests against react 18 to unified react-18 job
- mitigates perf hit to main e2e pipeline
- moves react 18 tests agains all cypress v9 files to new `react_18_integration` job
- scoped metric for react 18 migration
- runs cypress outside nx runner scope to get full error logs https://github.com/nrwl/nx/issues/30562
- uses summaries for nicer outputs https://github.com/microsoft/fluentui/actions/runs/14358190753?pr=34212#summary-40252580079
- Fixes #

feat: setup react 18 integration e2e outside main pipeline

---

change/@fluentui-react-swatch-picker-9a3c1595-b8f0-4556-889c-6c515243b67b.json
packages/react-components/react-swatch-picker/library/src/components/ColorSwatch/useColorSwatchStyles.styles.ts

Partners ask. For custom small sizes original design of `selected` state looks not accessible:

fix(react-swatch-picker): design change of selected state for ColorSwatch

---

apps/vr-tests-react-components/src/stories/Badge/BadgeSize.stories.tsx
apps/vr-tests-react-components/src/stories/Badge/utils.ts
change/@fluentui-react-badge-4691165c-bbe4-4d80-b499-d48e64a95426.json
packages/react-components/react-badge/library/src/components/Badge/useBadgeStyles.styles.ts

This reverts commit 72acd40b2319325eb725760888185a2fabdd46e7.
Initially it had `minWidth: <size>`, later was [changed](https://github.com/microsoft/fluentui/pull/27489) to `minWidth: max-content` and `width: <badge size>` to prevent the badge from shrinking smaller than the content. Although, this is introducing bugs and inconsistent behavior in Safari with other browsers. I suggest, we can revert this change to make behavior more predictable and if needed, users can handle it by themselves. 
Badge has `width: 20px` and `minWidth: max-content`
Badge has only `minWidth: <size>`. 
- Fixes #34089

Revert "fix(react-badge): Use min-width: max-content on Badge

---

apps/react-18-tests-v8/package.json
apps/react-18-tests-v9/cypress-react-18.config.ts
apps/react-18-tests-v9/package.json
package.json
scripts/cypress/src/base.config.ts
yarn.lock

Currently, the React 18 v9 test app uses the same Cypress version as the rest of the repo, which is still on React 17.
This PR bumps Cypress only for the integration test for the React 18 v9 test app. This makes the integration tests to run on latest Cypress, which makes it easier for us to spot issues before bumping the whole repository to latest Cypress

tests(e2e): upgrade Cypress to version 14 for React 18 v9 tests

---

packages/react-components/react-tree/library/src/components/Tree/Tree.cy.tsx

Updates tests to use `.click()` as the first action. It makes tests more stable and predictable.
Functionality and assertions in tests are not affected.

chore: update tests in Tree.cy.tsx and enable in R18 suite

---

packages/react-components/react-tag-picker/library/src/components/TagPicker/TagPicker.cy.tsx

Updates tests to use `.click()` as the first action. It makes tests more stable and predictable. Makes tests to run on OSX as avoid specific OS hotkeys (replaced with `{moveStart}`, `{selectAll}`).
Functionality and assertions in tests are not affected.
- https://github.com/microsoft/fluentui/issues/33173

chore: improve stability of TagPicker.cy.tsx, pass tests on OSX

---

packages/semantic-tokens/etc/semantic-tokens.api.md
packages/semantic-tokens/package.json
packages/semantic-tokens/scripts/legacyTokens.ts
packages/semantic-tokens/scripts/tokenGen.ts
packages/semantic-tokens/src/components/focus/tokens.ts
packages/semantic-tokens/src/components/link/tokens.ts
packages/semantic-tokens/src/control/tokens.ts
packages/semantic-tokens/src/legacy/tokens.ts

Currently, webpack tree shakes fluentui/tokens package, however, ESBuild does not.
By flat exporting the deprecated fallback tokens, we ensure that any direct imports of fluentui/semantic-tokens will be tree shaken by default in all build systems.

Semantic-tokens: Flat export deprecated tokens (Tree shakability in ESBuild)

---

packages/react-components/react-carousel/stories/src/Carousel/CarouselActionCards.stories.tsx

Carousel container would blowout on thin views (mobile) on grid story
Carousel container now contains based on max view width as expected
- Fixes #33744

fix (react-carousel): Update carousel story container to be responsive

---

change/@fluentui-react-charts-2efa7f19-884c-4d88-9a48-b75502f5c98e.json
packages/charts/react-charts/library/src/components/CommonComponents/CartesianChart.tsx
packages/charts/react-charts/library/src/components/HeatMapChart/__snapshots__/HeatMapChartRTL.test.tsx.snap
packages/charts/react-charts/library/src/utilities/__snapshots__/UtilityUnitTests.test.ts.snap
packages/charts/react-charts/library/src/utilities/utilities.ts

Ported Full Y axis labels in Heatmap chart change to v9.
- Fixes #

fix(react-charts): Full YAxis labels in Heatmap chart

---

change/@fluentui-web-components-05138dd2-442b-4395-9b03-37eed7665793.json
packages/web-components/src/tree-item/tree-item.base.ts
packages/web-components/src/tree-item/tree-item.spec.ts
packages/web-components/src/tree-item/tree-item.stories.ts
packages/web-components/src/tree-item/tree-item.template.ts
packages/web-components/src/tree/tree.base.ts
packages/web-components/src/tree/tree.spec.ts
packages/web-components/src/tree/tree.stories.ts
packages/web-components/src/tree/tree.template.ts

This PR fixes several issues
1. If a tree item is selected clicking the selected item unselects it
2. If a sub item was set to be initially selected it was hidden if its parent tree items weren'y explicity set to expanded
3. If a item was set to initially selected the intially selected item would not unselect when a new item was selected
4. If a sub item was selected and you focused the tree then hit `shift+tab` it would focus the parent item, then if you focused the tree again it would focus the parent item and not the selected item
1. clicking an item no longer toggles selection
2. If a sub item is insitally set to selected it automatically expands all parent tree items
3. Initially selected items unselect when I new item is selected
4. If no items are selected the first tree item gets …

[fix] tree-item bugs

---

change/@fluentui-react-components-2a9d64d4-7c5d-4507-9d09-f0abba5ad631.json
package.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts

This pull request includes updates to the `@fluentui/react-components` package to re-export the `CellRenderFunction` type from `@fluentui/react-table`.
The most important changes include:
* Added import statement for `CellRenderFunction` from `@fluentui/react-table` in `packages/react-components/react-components/etc/react-components.api.md`.
* Added export statement for `CellRenderFunction` in `packages/react-components/react-components/etc/react-components.api.md`.
* Added `CellRenderFunction` to the export type list in `packages/react-components/react-components/src/index.ts`.

chore: Re-exporting `CellRenderFunction` from `@fluentui/react-components`

---

change/@fluentui-react-link-934b9c1a-08e7-4b38-a2cf-518acb9dd861.json
packages/react-components/react-link/library/package.json
packages/react-components/react-link/library/src/components/Link/useLinkStyles.styles.ts

Updates React-link to use semantic tokens
To be landed after https://github.com/microsoft/fluentui/pull/34217
Extended tokens branch will be PR'd against master to validate via bundle size tool.
React-link used existing fluentui/tokens set
React-link now uses fluentui/semantic-tokens set

Semantic-Tokens: React-Link

---

packages/semantic-tokens/scripts/fluentOverrides.ts
packages/semantic-tokens/scripts/legacyTokens.ts

Duplicate legacy tokens would get re-exported
There was no way to define a token as 'has inline fallbacks'
Duplicate legacy tokens only get exported once
Any tokens set to 'null' are inferred to have inline fallbacks and should not be overwritten with other fallbacks (use inline instead).

Handle duplicate tokens and enable null for f2 overrides

---

change/@fluentui-react-charting-c468de78-207f-4410-8bc9-181d0c77d894.json
packages/charts/react-charting/src/components/Legends/Legends.styles.ts

Work item: https://uifabric.visualstudio.com/iss/_workitems/edit/12233/
Fixed legends disappear when hovering over the scrollbar in more legends. 
The legend overflow container can be scrolled without crashing on hovering on the scrollbar as follow:

fix(react-charting): Fixed legends disappear when hovering over the scrollbar in more legends

---

.github/workflows/pr.yml
apps/react-18-tests-v8/.eslintrc.json
apps/react-18-tests-v8/cypress-react-18.config.ts
apps/react-18-tests-v8/cypress.config.ts
apps/react-18-tests-v8/package.json
apps/react-18-tests-v8/project.json
apps/react-18-tests-v8/tsconfig.react-18.json

- adds type-check and e2e integration against v8 assets / follows https://github.com/microsoft/fluentui/pull/34247
- excludes react-charting and react-experiments for type-check integration for now
- new pipeline check 
- Fixes #

feat(react-18-tests-v8): add r18 integration pipelines for v8

---

packages/react-components/react-badge/stories/src/Badge/BadgeAppearance.stories.tsx
packages/react-components/react-badge/stories/src/Badge/BadgeColorVsAppearance.stories.tsx
packages/react-components/react-badge/stories/src/Badge/index.stories.tsx

Follow up of this PR: #34172
Usage of `outline-subtle` and `ghost-subtle` was confusing. The design team confirmed that it should be used only on brand background.
- Added an example of color/appearance used together.
- Changed order of `appearance` options so there are at the same order as in example
#34167
- Fixes #34254

docs(react-badge): added example of Color and Appearance together.

---

apps/public-docsite-v9/src/DocsComponents/ReactIconGrid.stories.tsx
apps/public-docsite-v9/src/Icons/IconsDefault.stories.tsx

There was an `aria-label` on a generic `div` in the icons catalog, but the icons themselves didn't have an accName. I've removed the div `aria-label` that wasn't doing anything, and added one to the `Icon`s themselves (which also exposes them as images).
The Basic example also was missing accNames, which are now added; the other examples all already have them.
accNames everywhere!
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/27982)

docs(Icon): add accNames to icon catalog and overview examples

---

change/@fluentui-react-tabster-c4068b76-08f7-4e2e-8824-563cce54c661.json
packages/react-components/react-tabster/src/hooks/useTabster.ts

We use `useLayoutEffect()` instead of `useEffect()`. It's needed to ensure that Tabster modules are initialized before Tabster will read DOM attributes.
See #34314 for context.
Fixes #34314

fix(react-tabster): use useLayoutEffect() for Tabster creation

---

change/@fluentui-react-aria-a9664252-df01-49d7-9074-980bcbd33fd7.json
packages/react-components/react-aria/library/src/AriaLiveAnnouncer/useAriaNotifyAnnounce.ts

The `ariaNotify` browser API has been through some continuing spec updates; this PR updates our internal implementation (behind a support check) to match the current API.
(as a note on why this is changing -- our `ariaNotify` implementation in Fluent is part of our work with Edge and the ARIA WG to help proof out the new `ariaNotify` feature by providing concrete testable use cases so it can become stable in the spec & get wide browser support. Continuing updates to the spec & implementation are expected, and shouldn't affect partner teams since `ariaNotify` support is behind a flag)

fix: update fluent ariaNotify implementation to match new API

---

change/@fluentui-react-6547c0c2-af77-4383-adb6-0d4f426c9964.json
packages/react/etc/react.api.md
packages/react/src/components/pickers/BasePicker.styles.ts
packages/react/src/components/pickers/BasePicker.tsx
packages/react/src/components/pickers/BasePicker.types.ts
packages/react/src/components/pickers/Suggestions/Suggestions.styles.ts
packages/react/src/components/pickers/Suggestions/__snapshots__/Suggestions.test.tsx.snap

The scroll-into-view behavior of picker suggestion items wasn't working properly at small or zoomed-in screen sizes because of the conflicting overflow behavior of Callout and Suggestions.
When pickers had greater than 300px + header/footer space for the callout containing the suggestions, everything works fine because the Suggestions control is the only one with scroll overflow because of its 300px max-height. At smaller screen sizes, both the inner Callout component and the Suggestions control had overflow styles:
This is caused by Callout also having scroll overflow logic for small screen sizes, since that's the component that handles positioning within the viewport. However, since scrolling is handled within Suggestions because focus doesn't actually enter the Callout, this causes …

fix: v8 Picker suggestions handle scroll overflow at small screen sizes

---

change/@fluentui-react-tabs-74f15f82-3c33-4e73-8abe-9ef2d9c3d35c.json
packages/react-components/react-tabs/library/src/components/Tab/useTabStyles.styles.ts
packages/react-components/react-tabs/stories/src/Tabs/TabListAppearance.stories.tsx

While the text of the selected item is technically semi-bold for the subtle-circular variant (the 3rd), it's very subtle:
Now the subtle-circular selected tab has `Highlight` as the border-color:
I also updated the example to have the 3rd tab be selected by default, so the default-selected tab is not the disabled tab.
- Fixes a partner ADO issue

fix(Tablist): subtle-circular appearance variant shows selected tab in high contrast

---

apps/public-docsite-v9/src/DocsComponents/FluentDocsPage.stories.tsx

fix(public-docsite-v9): add spacing between additional info section items

---

change/@fluentui-foundation-legacy-4fc6c4ad-d979-43c8-9a95-76a0c18d68d8.json
change/@fluentui-react-experiments-076a9937-dd8b-4254-ab9e-14b0d7767f7f.json
change/@fluentui-react-icons-mdl2-17cc26d9-27b2-4524-a440-327754df1cd3.json
packages/foundation-legacy/src/slots.test.tsx
packages/foundation-legacy/tsconfig.json
packages/react-cards/src/components/Card/CardItem/CardItem.test.tsx
packages/react-cards/src/components/Card/CardSection/CardSection.test.tsx
packages/react-experiments/src/components/PersonaCoin/PersonaCoin.test.tsx
packages/react-experiments/src/components/SelectedItemsList/SelectedItemsList.test.tsx
packages/react-experiments/src/components/SelectedItemsList/SelectedPeopleList/SelectedPeopleList.test.tsx
packages/react-experiments/src/components/Sidebar/Sidebar.test.tsx
packages/react-experiments/src/components/Slider/Slider.test.tsx
packages/react-experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/UnifiedPeoplePicker.test.tsx
packages/react-experiments/src/components/UnifiedPicker/UnifiedPicker.test.tsx
packages/react-experiments/tsconfig.json
packages/react-icons-mdl2/src/utils/createSvgIcon.test.tsx
packages/react-icons-mdl2/tsconfig.json
packages/utilities/src/asAsync.test.tsx
packages/utilities/src/createMergedRef.test.tsx
packages/utilities/src/customizations/Customizer.test.tsx
packages/utilities/src/customizations/customizable.test.tsx
packages/utilities/src/customizations/useCustomizationSettings.test.tsx
packages/utilities/src/extendComponent.test.tsx
packages/utilities/src/initializeComponentRef.test.tsx
packages/utilities/src/safeRequestAnimationFrame.test.tsx
packages/utilities/src/safeSetTimeout.test.tsx
packages/utilities/src/setFocusVisibility.test.tsx
packages/utilities/src/styled.test.tsx
packages/utilities/src/useFocusRects.test.tsx

Follows #34270 to refactor v8 tests to remove enzyme
**Test migrated**
- utilities
- react-experiments
- react-icons-mdl2
- react-cards
- foundation-legacy
**Type issues resolved**
- changes in react-experiments,foundation-legacy and react-icons-mdl2 triggered TSC errors in test files and implementation files. This PR adjust the configs to make `tsc` deterministic and without errors
- Fixes #

test: migrate tests from enzyme to testing-library/react-test-renderer

---

change/@fluentui-react-charting-742b0fc0-7183-487c-ae50-b76bd8270a6d.json
packages/charts/react-charting/src/components/LineChart/eventAnnotation/LabelLink.tsx

Screen reader does not announce the name or role for events in LineChart.
Screen reader announces the event labels in LineChart and identifies them as buttons.

fix(react-charting): set button role for event labels in line chart

---

apps/react-18-tests-v8/package.json

v8 `type-check:integration` provides false positives
v8 `type-check:integration` runs as expected against public API interface of v8 used within react-examples stories
- Fixes #

fix(r18-tests-v8): add all dependencies to properly run type-check:integration target agains public API within stories

---

.github/workflows/pr.yml
apps/react-18-tests-v8/.eslintrc.json
apps/react-18-tests-v8/config/tests.js
apps/react-18-tests-v8/jest-react-18.config.js
apps/react-18-tests-v8/jest.config.js
apps/react-18-tests-v8/package.json
apps/react-18-tests-v8/project.json
apps/react-18-tests-v8/src/components/ContextualMenu/ContextualMenuExample.test.tsx
apps/react-18-tests-v9/jest.config.js
apps/react-18-tests-v9/package.json
apps/react-19-tests-v9/jest.config.js
apps/react-19-tests-v9/package.json
yarn.lock

- Needs enzyme removal https://github.com/microsoft/fluentui/pull/34270
- adds new `test:integration` target which executes against source test files in react 18 context
- setups jest testing against v8 `react` and `react-hooks` projects
- Fixes #

feat(react-18-tests-v8): setup test:integration to run jest test against r18

---

change/@fluentui-web-components-90fcfd91-50b7-4219-8f26-726a1976519b.json
packages/web-components/package.json

F2 tokens were only exported from `@fluentui/web-components` root index which caused challenges with linting rules that require Named Imports. Adding `@fluentui/web-components/index.js` then broke other build tools because that resolves to `/dist/esm/index/define.js` (which doesn't exist).
Add a `./theme/*.js` export rule to allow us to export `@fluentui/web-components/theme/design-tokens.js`
- Fixes #

feat(web-components): add endpoint for F2 token exports

---

change/@fluentui-react-tabs-f8ad7559-f4e1-4c25-9c8b-910ddf5eabe0.json
packages/react-components/react-tabs/library/src/components/Tab/useTabStyles.styles.ts

Related to #34294, it came up that it makes more sense for the filled variant to have a border in the unselected state than for filled-subtle to have one. Currently only filled-subtle has one because of the hover style.

fix: Tab filled (not filled-subtle) appearance has border in WHCM

---

change/@fluentui-react-charting-c87b89f1-fec8-4243-bbb1-3df37d7513e0.json
packages/charts/react-charting/src/components/HorizontalBarChartWithAxis/HorizontalBarChartWithAxis.base.tsx
packages/charts/react-charting/src/components/HorizontalBarChartWithAxis/__snapshots__/HorizontalBarChartWithAxis.test.tsx.snap
packages/charts/react-charting/src/components/HorizontalBarChartWithAxis/__snapshots__/HorizontalBarChartWithAxisRTL.test.tsx.snap
packages/charts/react-charting/src/utilities/__snapshots__/UtilityUnitTests.test.ts.snap
packages/charts/react-charting/src/utilities/utilities.ts
packages/react-examples/src/react-charting/DeclarativeChart/schema/fluent_donut.json

Horizontal bar chart with axis did not support negative y values. They were filtered out
Added support for negative y values.
Also honoring the user provided yMin and yMax properties.
- Fixes #

feat(react-charting): Enable negative Y support for horizontal bar chart

---

packages/react-components/react-color-picker/stories/src/ColorPicker/ColorPickerDefault.stories.tsx

- Maximum 6 symbols HEX support
- Alpha channel wasn't updating when HEX was changing
- Support of HEX8
- Alpha channel is changing when HEX is updated

docs(react-color-picker): added HEX8 support and fixed hex/alpha change

---

change/@fluentui-web-components-d531c495-234e-434c-8df1-5e11c0ea1532.json
packages/web-components/.storybook/docs-root.css
packages/web-components/src/drawer-body/drawer-body.styles.ts
packages/web-components/src/drawer/drawer.stories.ts

Story had text that would not theme
Text is not necessary for story so removed.
- Fixes #

[fix] remove non-theming text from drawer stories

---

change/@fluentui-web-components-4d430b96-9653-4166-8f37-1be12ad9cfb8.json
packages/web-components/src/dialog/dialog.spec.ts
packages/web-components/src/dialog/dialog.template.ts

Dialog cancel event was set to preventDefault when dialog type was set to alert causing the user to have to hit escape twice.
Verified escape should close alert dialogs and that this behavior matches the react implementation. Also removed test that asseted it shouldn't (Even though it did when you hit wscape a second time)
- Fixes #

[fix]: Hitting escape once should close alert dialog

---

apps/public-docsite/src/pages/Overviews/ResourcesPage/docs/default/ResourcesDesignResources.md

The documentation page contains broken Figma links that use redirects which are no longer working:
- Web UI Kit: https://aka.ms/FluentToolkits/Web/Figma
- iOS UI Kit: https://aka.ms/FluentToolkits/iOS/Figma
- Android UI Kit: https://aka.ms/FluentToolkits/Android/Figma
- Figma Toolkits landing: https://aka.ms/figmatoolkit
Updated all broken Figma links to point directly to their destinations:
- Web UI Kit: https://www.figma.com/community/file/836828295772957889/microsoft-fluent-2-web
- iOS UI Kit: https://www.figma.com/community/file/836833645402438850/microsoft-fluent-2-ios
- Android UI Kit: https://www.figma.com/community/file/836835062056249539/microsoft-fluent-android
- Figma Toolkits landing: removed
- Fixes #34287

Fix broken Figma links in Resources Design Resources page

---

packages/web-components/.storybook/docs-root.css

[fix]: storybook style was preventing dialog text from theming

---

change/@fluentui-test-utilities-ff572d4d-e62d-46fa-8b51-5dd02dab7ed5.json
packages/react/src/components/DetailsList/DetailsList.test.tsx
packages/react/src/components/DetailsList/DetailsListV2.test.tsx
packages/test-utilities/README.md
packages/test-utilities/src/safeMount.ts

- replaces previously abstracted `safeMount` with direct RTL usage
- officially deprecates `safeMount` in `@fluentui/testing-utilities` package as it cannot be removed because we cannot major bump v8 packages 
- Follows https://github.com/microsoft/fluentui/pull/34270

feat: deprecate `safeMount` and remove its abstractions in react project tests

---

change/@fluentui-react-carousel-4bb9f3b6-bcf9-4a88-9583-34578c45712c.json
packages/react-components/react-carousel/library/src/components/CarouselNavButton/useCarouselNavButtonStyles.styles.ts

- Brand color variants of the react-carousel were using Brand button colors, these are compliant due to foreground text contrast, without text, the contrast of colors against neutral background are below 3:1 and invalid.
We keep unselected state as neutral, and moved brand color to 'brandColorCompound' to ensure it passes contrast in any theme:

React-Carousel: Ensure compliant brand variant contrast

---

packages/web-components/src/spinner/spinner.stories.ts

The inverted story example was using a themeable background. The inverted spinner style stays the same across light and dark theme so the solution is to just hard code the background in the story example. Used the blue from the figma file and the react example.
- Fixes #

[fix] inverted spinner story to not theme background

---

docs/react-v9/contributing/rfcs/react-components/positioning-customizations.md

This RFC proposes a new API for customizing positioning options for all components that use the `usePositioning()` hook. The API is based on React Context and allows overriding any positioning option for any component.
[Link](https://github.com/layershifter/office-ui-fabric-react/blob/rfc/shared-positioning/docs/react-v9/contributing/rfcs/react-components/positioning-customizations.md)

RFC: Shared positioning customizations

---

change/@fluentui-chart-utilities-d46fc54f-f5e8-4331-bf00-9762d98d2f59.json
change/@fluentui-react-charting-350f0257-a4a6-444a-b884-23b5fa5b2a0e.json
change/@fluentui-react-charts-e29b43fc-d0fa-4720-8c5f-a4d0e5c75a45.json
packages/charts/chart-utilities/etc/chart-utilities.api.md
packages/charts/chart-utilities/src/PlotlySchema.ts
packages/charts/chart-utilities/src/PlotlySchemaConverter.ts
packages/charts/chart-utilities/src/index.ts
packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx
packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapter.ts

The best effort fallback to try to render chart as a line was causing issues for some charts like waterfall, funnel and 3D charts.
Removed the fallback to line check since we anyways have the fallback to static images now.
Also enabled scatter chart for `markers+text` mode
Verified in test app.
- Fixes #

fix(chart-utilities): Make unsupported chart type check stricter

---

apps/vr-tests-react-components/src/stories/Positioning/Positioning.stories.tsx
change/@fluentui-react-components-7e29c1a9-70bb-4a47-bb47-8744bee0fbc2.json
change/@fluentui-react-positioning-7e4ac846-b14b-4560-9ec4-c2dd2725bff4.json
packages/react-components/react-components/etc/react-components.api.md
packages/react-components/react-components/src/index.ts
packages/react-components/react-positioning/etc/react-positioning.api.md
packages/react-components/react-positioning/src/PositioningConfigurationContext.ts
packages/react-components/react-positioning/src/index.ts
packages/react-components/react-positioning/src/middleware/offset.ts
packages/react-components/react-positioning/src/types.ts
packages/react-components/react-positioning/src/usePositioning.ts
packages/react-components/react-positioning/src/usePositioningOptions.ts
packages/react-components/react-positioning/src/utils/devtools.ts

Implements https://github.com/microsoft/fluentui/pull/34271, exports `PositioningConfigurationProvider` that could be used to configure positioning for a components inside its tree.
```tsx
import {
PositioningConfigurationProvider,
type PositioningConfigurationFn,
type PositionOptions,
} from '@fluentui/react-components';
// Default autoSize settings for specific component classes
const DEFAULT_AUTO_SIZE_OVERRIDE: Record<string, PositionOptions['autoSize']> = {
'fui-PopoverSurface': true,
'fui-Tooltip': 'width',
};
const configurePositioning: PositioningConfigurationFn = ({
container /* The element being positioned */,
arrow /* The arrow element, if present */,
options /* User-provided options for this instance */,
}) => {
// Note: a smarter check might be needed here
const …
```

feat: implement shared positioning config

---

apps/react-18-tests-v9/.swcrc
apps/react-18-tests-v9/jest-react-18.config.js
apps/react-18-tests-v9/jest.config.js
apps/react-18-tests-v9/package.json
apps/react-18-tests-v9/project.json

Adds `test:integration` to react-18-tests-v9 application
- this target will execute all production packages `test` targets against react 18
- most of the current failures are caused by `@fluentui/react-conformance` and `@fluentui/react-conformance-griffel` 🚨
_current status:_
- Fixes #

test(react-18-tests-v9): add test:integration target

---

change/@fluentui-react-carousel-d08a816f-8021-43fa-b405-b5d9ab780ca4.json
packages/react-components/react-carousel/library/src/components/Carousel/Carousel.types.ts
packages/react-components/react-carousel/library/src/components/CarouselButton/useCarouselButton.tsx
packages/react-components/react-carousel/library/src/components/useEmblaCarousel.ts

- If there is not enough content to loop, the carousel correctly prevents looping (prevents visual glitches)
- The carousel buttons do not adhere to this state, so clicking the button when trailing does nothing.
- Same carousel behavior
- Buttons now disable themselves when trailing and looping is not possible
- Listeners now provide 'canLoop' as an additional optional boolean

Carousel: Ensure buttons are disabled if not enough content to loop

---

packages/eslint-plugin/package.json
scripts/beachball/src/config.test.ts

- moving package back to `private` to mitiage any further releases until it's being rewritten to up to date state
- also will mitigate further invalid release bumps caused by beachball not  differentiating between dependencies and devDependencies causing unwanted releases and release bumps
- eg 1: react-conformance was supposed to be released as patch https://github.com/microsoft/fluentui/commit/8edf93c4c635df8f4c9fb36ed317a48e30262555#diff-4c5686f9d1e728be6e92ba6827bfacaef1a7f123504a994d849424f3694fbfba but because eslint-plugin was bumped as minor and dependant change type was minor it overrode the bump of conformace package, making a new release  which says based on semver that it has breaking changes - it does not
-  eg 2: react-storybook-addon package didn't contain any change-files, …

feat(eslint-plugin): move project to private to stop further npm releases

---

change/@fluentui-react-progress-7802143c-d54f-4bd3-9e8e-075ca4cff496.json
packages/react-components/react-progress/library/package.json
packages/react-components/react-progress/library/src/components/ProgressBar/useProgressBarStyles.styles.ts
packages/semantic-tokens/etc/semantic-tokens.api.md
packages/semantic-tokens/src/components/progress/tokens.ts
packages/semantic-tokens/src/control/tokens.ts
packages/semantic-tokens/src/fluentOverrides.ts
packages/semantic-tokens/src/legacy/tokens.ts

No visual regression
This pull request introduces a new feature for a Progress Bar component in `@fluentui/react-progress` and refactors the styling system to use semantic tokens for improved consistency and maintainability. The most important changes include the addition of the Progress Bar feature, updates to the styling definitions to replace hardcoded values with semantic tokens, and the extension of the semantic tokens library to support these changes.
* Added a new Progress Bar feature, including metadata for versioning and release notes in `@fluentui/react-progress`.
* Updated `useProgressBarStyles.styles.ts` to replace hardcoded token values with semantic tokens for properties like `backgroundColor` and `borderRadius`, ensuring consistency across themes. …

Semantic Tokens: Progress Bar

---

change/@fluentui-react-nav-preview-596583ea-bfcb-49c8-b127-ac61c5781a41.json
packages/react-components/react-nav-preview/library/src/components/sharedNavStyles.styles.ts

The icons disappeared when selected and unselected in Safari.
The icons no longer disappear when selected and unselected in Safari.
- Fixes [Partner Bug](https://office.visualstudio.com/OC/_workitems/edit/10129155)

fix(react-nav-preview): Fix icon animation in Safari by animating opacity instead of display

---

packages/semantic-tokens/etc/semantic-tokens.api.md
packages/semantic-tokens/scripts/tokenGen.ts
packages/semantic-tokens/src/components/focus/tokens.ts
packages/semantic-tokens/src/fluentOverrides.ts
packages/semantic-tokens/src/legacy/tokens.ts

NULL was skipped originally, but new casing sensitivity prevented us from catching null tokens
Now remove null tokens
We also ignore 'unset' for any tokens with proper fallbacks in place.
Updated link to use the correct focus token

Extended-tokens: Fix regressions from new JSON refactor

---

packages/react-components/react-link/library/src/components/Link/useLinkStyles.styles.ts

Previously we used 'ctrlFocusOuterStroke' for link focus state
After confirming with other component specs, it was confirmed this should be using `ctrlFocusInnerStroke`

Extended-tokens: Fix link focus reference (changed in latest JSON update)

---

change/@fluentui-web-components-44b1b6b4-87b6-43a1-ab12-7c09fceb3bc6.json
packages/web-components/package.json

The Custom Elements Manifest is not included in the package exports. This means that users cannot import and use the CEM features and plugins to add functionality in their projects.
The file is now included in the exports.
- Fixes #

Add CEM to package exports

---

packages/react-components/react-nav-preview/stories/src/Nav/NavAccessibility.md
packages/react-components/react-nav-preview/stories/src/Nav/NavDescription.md
packages/react-components/react-nav-preview/stories/src/Nav/index.stories.tsx
packages/react-components/react-nav-preview/stories/src/NavDrawer/Basic.stories.tsx

no a11y docs, and no `aria-expanded` on the inline toggle (it's in preview, so this makes sense, just getting on top of adding the a11y docs b/c it got tested)
Adds `aria-expanded` for the inline Nav toggle button, and docs for it + a few other a11y docs points (what I could think of off the top of my head, we can add more later).
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/27004)

docs(Nav): add a11y docs and update Basic example with aria-expanded

---

change/@fluentui-web-components-f3428123-2fef-418d-86e5-1266218f1b6e.json
packages/web-components/src/menu/menu.ts

When menu is toggled, JavaScript always focus on the menu list, even when the menu is being closed. This could cause the page to jump to the bottom in Safari (possibly because the focused element (menu list) is no longer visible), this only happens when the menu's closure is animated.
JavaScript only manages focus when the menu is being opened.

fix: manage focus only when menu is open

---

change/@fluentui-web-components-a43a8034-1ec2-4583-853b-890ff7506ccd.json
packages/web-components/docs/web-components.api.md
packages/web-components/src/dialog-body/dialog-body.ts
packages/web-components/src/drawer-body/drawer-body.template.ts
packages/web-components/src/drawer-body/drawer-body.ts
packages/web-components/src/drawer/drawer.spec.ts
packages/web-components/src/drawer/drawer.stories.ts

Previously implementation of drawer would require you to call the close event on the click event of the element slotted into the close slot
Now you no longer need to call the close event on the drawer (though you still can). This matches the new api for dialog with this PR.
Dialog PR:
https://github.com/microsoft/fluentui/pull/34469.
- Fixes #

[fix]: add click event for close slot for drawer

---

change/@fluentui-web-components-848fb759-1e01-4df2-b8c8-dea81d054999.json
packages/web-components/src/compound-button/compound-button.styles.ts

Primary and disabled compound-button text colors did not meet the minimum contrast ratio in Windows high contrast mode.
Compound-button text colors now meet the minimum contrast ratio in Windows high contrast mode.

fix: compound-button text colors in Windows high contrast mode

---

apps/react-18-tests-v9/.eslintrc.json
apps/react-18-tests-v9/src/issues.tsx
apps/react-18-tests-v9/tsconfig.app.json
apps/react-18-tests-v9/tsconfig.react-18.json

adds examples causing following error:
`Type '{}' is not assignable to type 'ReactNode'`
with Root cause in `WithSlotRenderFunction` type 
- Fixes #

feat(react-18-v9): add more type issues examples

---

packages/react-components/react-utilities/src/compose/types.ts
packages/react-components/react-utilities/src/utils/types.ts

This pull request introduces a new utility type, `ReactVersionDependent`, to handle compatibility between React versions 18+ and earlier. It also updates existing `WithSlotRenderFunction` to leverage this utility to support Slots API for both React 17 and React 18+.

feat: react 18 slots conditional types for WithSlotRenderFunction

---

packages/web-components/src/progress-bar/progress-bar.stories.ts

There was no accessible labels on the storybook examples for the progress bar validations states.
Adds accessible labels
- Fixes #

[fix] add accessible labels to vaildation progreeBar stories

---

change/@fluentui-web-components-52c0d036-67c0-48ab-b1a8-4de0ea9d7137.json
packages/web-components/src/rating-display/rating-display.spec.ts
packages/web-components/src/rating-display/rating-display.styles.ts

Rating-display icon colors used different tokens than the React version. This resulted in a mismatch between the icon colors in the dark theme.
The rating-display icon color tokens now match the React version, ensuring consistency across themes.

fix: updated rating-display icon color tokens to match the React version

---

change/@fluentui-web-components-bcec3960-1a82-4919-8a79-515c6dbd38cd.json
packages/web-components/src/dialog/dialog.spec.ts
packages/web-components/src/dialog/dialog.stories.ts
packages/web-components/src/dialog/dialog.ts

Clicking certain elements in a dialog caused the click event to be prevented.
Clicking on labels in `<fluent-field>` for dialogs allows the associated input to be focused.

fix(web-components): dialog click events prevent default

---

change/@fluentui-chart-utilities-91030aba-267f-46a0-8da5-c1fc09d3774c.json
change/@fluentui-react-charting-1dba4621-fdda-4bca-8a2d-5bed378a8503.json
packages/charts/chart-utilities/etc/chart-utilities.api.md
packages/charts/chart-utilities/src/PlotlySchema.ts
packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts

Use colorscale for heatmap charts.
Fixes 710, 712, 716, 717, 718, 721 in test app.
Work item: https://uifabric.visualstudio.com/iss/_workitems/edit/12850/

Use colorscale for heatmap charts

---

change/@fluentui-web-components-bad3fcd8-7b1d-4f0f-85f6-157f57075cdc.json
packages/web-components/src/dialog-body/dialog-body.stories.ts
packages/web-components/src/dialog-body/dialog-body.styles.ts
packages/web-components/src/dialog/dialog.stories.ts

The dialog did not have an acccesible name. The dialog should use a header tag for its title.
Added aria label to storybook examples and added neccessary styling to support header tags in title slot.
- Fixes #

[fix]: Accessible name for dialog

---

change/@fluentui-react-tree-3750526e-3cbb-4a16-aaea-f901f9af2ace.json
packages/react-components/react-tree/library/src/components/TreeItemLayout/useTreeItemLayoutStyles.styles.ts

`:active` styles on `TreeItemLayout` is not being properly applied, `:hover` styles is taking precedence.
Inverts order of `:active` and `:hover` declaration on `TreeItemLayout` styles to ensure `:active` takes precedence over hover
- Fixes https://github.com/microsoft/fluentui/issues/34554

chore(react-tree): re-introduces active state style to TreeItemLayout

---

change/@fluentui-react-charts-25fbe741-5ba7-4997-b827-0c8d2b3547ae.json
packages/charts/react-charts/library/src/components/GaugeChart/useGaugeChartStyles.styles.ts

Previously useGaugeChartStyles was not merging fields from props.styles, which made the GaugeChart's styles prop ineffective. 
With this fix, the GaugeChart's styles prop now properly applies custom styles to the chart. The useGaugeChartStyles hook correctly merges user-provided styles with default styles, allowing for full customization of the chart's appearance.
- Fixes #

fix(gaugechart): fix gauge chart style hook to merge style from props

---

change/@fluentui-react-nav-preview-386d75e9-e200-487e-8d69-03ff4dc5ffe4.json
packages/react-components/react-nav-preview/library/src/components/AppItem/useAppItemStyles.styles.ts
packages/react-components/react-nav-preview/library/src/components/NavDrawerHeader/useNavDrawerHeaderStyles.styles.ts
packages/react-components/react-nav-preview/library/src/components/sharedNavStyles.styles.ts

The original focus outline fix changed two things:
- Added a 2px top margin to `AppItem`s, and added a -2px top margin to the drawer header.
- Added zIndex to NavItem focus and active states
Neither of these behaviors are ideal, unfortunately. If for example a partner wants to include more than one `AppItem` inside their `Nav`, they would have an extra 2px margin on their second `AppItem`. If they didn't want to include an `AppItem` or wanted to add it somewhere besides the top of the `Nav`, the first item in the `Nav` would be cut off.
For the added zIndex: as Mason said, we don't want to bake in z indexes to shared components because product code often has their own z indexing strategy that can clash with ours.
A safer approach with less potential impact to partners to fixing the issue …

fix(react-nav): Inset focus outlines to fix focus borders being cut off.

---

packages/react-components/react-datepicker-compat/stories/src/DatePicker/DatePickerControlled.stories.tsx
packages/react-components/react-radio/stories/src/RadioGroup/RadioGroupControlledValue.stories.tsx

These are very low-severity a11y issues, but easy fixes:
1. In the RadioGroup Controlled example, the "clear selection" button uses `disabledFocusable` instead of `disabled`, so when it's activated it doesn't cause focus to be lost and jump elsewhere.
2. In the Datepicker Controlled example, using previous/next date buttons triggers an `announce` as a confirmation of action for screen reader users
- Resolves two ADO bugs

docs: Minor a11y cleanup in two v9 stories

---

change/@fluentui-react-color-picker-874b61c9-eeae-4d2e-a3a1-a8220e5a4154.json
packages/react-components/react-color-picker/library/README.md

Removed line from the preview stage: "These are not production-ready components and **should never be used in product**..."

docs(react-color-picker): removed line from preview stage

---

change/@fluentui-react-tags-f462d7a3-2afd-45c7-8922-ab92af7124ec.json
packages/react-components/react-tags/library/src/components/InteractionTagPrimary/useInteractionTagPrimaryStyles.styles.ts
packages/react-components/react-tags/library/src/components/InteractionTagSecondary/useInteractionTagSecondaryStyles.styles.ts
packages/react-components/react-tags/library/src/components/Tag/useTagStyles.styles.ts

Selected tags are not visually distinguishable from unselected tags in high contrast:
Fixed!
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/29016)

fix: selected Tag and InteractionTag styles are visible in high contrast mode

---

apps/public-docsite-v9/src/Concepts/ReactVersionSupport.stories.mdx
apps/public-docsite-v9/src/Concepts/SupportedPlatforms.stories.mdx

- add official platform support docs including React Versions
- deployed site https://fluentuipr.z22.web.core.windows.net/pull/34599/public-docsite-v9/storybook/index.html?path=/docs/concepts-developer-supported-platforms--docs
- Fixes #

feat(public-docsite-v9): add official platform support docs including React Versions

---

change/@fluentui-react-tag-picker-7980ff9b-a205-4ac9-a45d-b3043836e532.json
packages/react-components/react-tag-picker/library/src/components/TagPicker/useTagPicker.ts

At the moment whenever the user tries to re-select the same option, the option is unselected. This happens because we're using `Combobox` logic internally to implement `TagPicker` logic, but this is a bit problematic in this scenario as `Combobox` supports toggling the selected data on the "option select event", meanwhile `TagPicker` only allows selection on the "option select event", to unselect a tag should be clicked manually, it does not involve the combobox logic
1. adds conditional logic to ensure internal combobox state will not be updated in this scenario. Instead, `onOptionsSelect` should be invoked with the current `selectedOptions` with no modifications
- Fixes https://github.com/microsoft/fluentui/issues/33305

chore(react-tag-picker): ensure no toggle behaviour when re-selecting already selected data

---

packages/web-components/src/checkbox/checkbox.stories.ts
packages/web-components/src/dropdown/dropdown.stories.ts
packages/web-components/src/radio-group/radio-group.stories.ts
packages/web-components/src/switch/switch.stories.ts

The error messages used in various "Required" stories are using the deprecated flag message feature, which isn't accessible.
The custom flag messages are removed in favor of the browser's built-in error messages.

chore(web-components): remove flag message fields from Required stories

---

change/@fluentui-react-carousel-5bea8031-da60-462f-aeb4-305af1343099.json
packages/react-components/react-carousel/library/src/components/pointerEvents.ts
packages/react-components/react-carousel/stories/src/Carousel/CarouselControlled.stories.tsx

- Carousel attached listeners to the target document
- Carousel listeners were not being removed on unmount
- Carousel drag events were not firing correctly when index was controlled, and index changed multple times in a single drag event
- Carousel attaches listeners to the container node itself, reducing listener surface
- Carousel now correctly removes listeners on unmount
- Carousel now correctly waits to disable 'drag' state until carousel 'settles', this ensures that drag events are always captured in controlled index scenarios - this may cause some additional indexing events to fire, however these are technically correct as until 'settled' a drag is considered in-progress.
- Fixes #34658

React-Carousel: Ensure listeners get unmounted and handle controlled drag

---

packages/semantic-tokens/utils/fluentOverrides.test.ts

fluentOverrides tested tokens before they were deduped, which caused the test to fail for the new simplified shadow tokens
fluentOverrides tests the output from dedupeShadowTokens

update fluentOverrides test to dedupe shadow tokens first

---

change/@fluentui-web-components-0a49c8c8-8b69-4f58-9b89-0a49aa649199.json
packages/web-components/src/progress-bar/progress-bar.base.ts
packages/web-components/src/progress-bar/progress-bar.spec.ts

#34674 broken the component in Firefox and Safari when the `value` attribute is missing.
Fixed the bug and added test.

fix: progress bar when value is missing in firefox and safari

---

change/@fluentui-react-charting-b78e126b-c353-4fdc-a92f-42ceb011bee9.json
packages/charts/react-charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx
packages/charts/react-charting/src/components/VerticalStackedBarChart/__snapshots__/VerticalStackedBarChartRTL.test.tsx.snap

fix(react-charting): correct bar height rendering for values less than 1 in VSBC

---

change/@fluentui-react-utilities-3d0ba736-f8f5-48de-9e50-e526b755d952.json
packages/react-components/react-utilities/src/hooks/useOnClickOutside.ts

pollDuration was 1000ms
pollDuration is now shortened to 100ms, users should not notice any obvious delay now.
- Fixes #

feat: shorten pollDuration to 100ms

---

change/@fluentui-web-components-d129a012-34ca-4275-83f1-64b0f37715d0.json
packages/web-components/docs/web-components.api.md
packages/web-components/src/index.ts
packages/web-components/src/tab/index.ts
packages/web-components/src/tab/tab.options.ts
packages/web-components/src/tab/tab.styles.ts
packages/web-components/src/tablist/tablist.base.ts
packages/web-components/src/tablist/tablist.spec.ts
packages/web-components/src/tablist/tablist.stories.ts
packages/web-components/src/tablist/tablist.styles.ts
packages/web-components/src/tablist/tablist.template.ts

When slotting in a start or end slot into tab the UI was broken, the start and end slot stacked above and below the tab content
The start and end slots now layout horizontally also in vertical orientation the text will now align if any tab has a start slot.
- Fixes #

[fix]: vertical tablist and start and end slots in tabs were broken

---

change/@fluentui-react-motion-ea2e7c9b-8a6a-4c18-b5a8-b065abac4258.json
packages/react-components/react-motion/library/etc/react-motion.api.md
packages/react-components/react-motion/library/src/factories/createPresenceComponent.test.tsx
packages/react-components/react-motion/library/src/factories/createPresenceComponent.ts
packages/react-components/react-motion/stories/src/CreatePresenceComponent/CreatePresenceComponentInAndOut.stories.md
packages/react-components/react-motion/stories/src/CreatePresenceComponent/CreatePresenceComponentInAndOut.stories.tsx
packages/react-components/react-motion/stories/src/CreatePresenceComponent/index.stories.ts

* There was no easy way to use one of a presence's `enter` or `exit` motions in isolation.
* E.g. we have a two-way `<Fade>` component, but how would a one-way fade be implemented and used?
* This PR adds `In` and `Out` static methods to the `Presence` component for playing enter and exit motions in isolation. 
* So for the existing `<Fade>` presence, we can now invoke `<Fade.In>` and `<Fade.Out>` as one-way motion components.
* This feature is given to all transitions created with `createPresenceComponent`.
```
// Create a presence component
const MyFade = createPresenceComponent({
enter: {
keyframes: [{ opacity: 0 }, { opacity: 1 }],
duration: 4000,
},
exit: {
keyframes: [{ opacity: 1 }, { opacity: 0 }],
duration: 2000,
},
});
```
Now in JSX, the fade-in and fade-out can be used …

feat(motion): Presence enter & exit motions can be used separately with `.In` & `.Out` 

---

apps/react-18-tests-v9/src/components/Portal/Portal.cy.tsx
change/@fluentui-react-tabster-79753e32-1543-432e-9d29-94091d5aaf9a.json
packages/react-components/react-tabster/src/focus/focusVisiblePolyfill.ts

Fixes a regression introduced in #33978
The portal element was updated to use a HTMLElement proxy. This means that the disposal function that tries to delete a 'hidden' property a HTMLElement does not actually do anything.
This PR updates the disposal to set an explicit value

fix(focusVisiblePolyfill): Strict mode compat after portal changes

---

packages/react-components/react-portal/stories/project.json
packages/react-components/react-positioning/stories/project.json
packages/react-components/react-table/stories/project.json
packages/react-components/react-tag-picker/stories/project.json
scripts/test-ssr/README.md
scripts/test-ssr/src/cli.ts
scripts/test-ssr/src/commands/main.ts

- introduces a new `exclude` CLI flag to support excluding specific story files or patterns during server-side rendering (SSR) tests.
- refactors `main` into atomic functions to encapsulate major steps
- updates project `test-ssr` target where applicable to use `--exclude` rather then hardcoded config within the CLI
- Implements https://github.com/microsoft/fluentui/issues/32191

feat(test-ssr): implement `--exclude` flag

---

change/@fluentui-react-menu-ec4c6227-fd16-4811-9405-63bc55a2e65e.json
packages/react-components/react-menu/library/etc/react-menu.api.md
packages/react-components/react-menu/library/src/components/Menu/Menu.cy.tsx
packages/react-components/react-menu/library/src/components/Menu/Menu.types.ts
packages/react-components/react-menu/library/src/components/Menu/useMenu.tsx
packages/react-components/react-menu/library/src/components/MenuTrigger/useMenuTrigger.ts

This PR a regression in the behavior of `.hoverDelay` after #34457: the previous PR switched to `mouseover` events while `setOpen()` in `useMenu()` was not updated to handle this event.
https://github.com/user-attachments/assets/8417aabc-2ea4-4552-9e9b-8b778cdbac9e
https://github.com/user-attachments/assets/d1b63e8d-0b2e-44f1-b0b8-5cfe421ae1e9
---
`MenuItem` should trigger an instant opening of a `Menu` (i.e. ignore `.hoverDelay`) if an event comes from a safe zone timeout. To do so:
- Updated the `setOpen` method to include an `ignoreHoverDelay` flag
- Added `openedViaSafeZoneRef` to track safe zone interactions 
Also reduced the safe zone timeout from 1500ms to 1000ms for quicker responsiveness based on feedback (we should make this configurable?).
Tests added.

fix(react-menu): fix regression with ".hoverDelay" handling

---

tools/workspace-plugin/src/plugins/workspace-plugin.ts

adding/modifying monosize configs wont invalidate the cache for `bundle-size` target
adding/modifying monosize configs properly invalidates the cache for `bundle-size` target
- Fixes #

fix(workspace-plugin): add proper input cache globs for bundle-size target

---

change/@fluentui-react-menu-838fbd3c-a5f1-4cee-986e-5ed3232d6691.json
packages/react-components/react-menu/library/src/components/MenuItem/useMenuItemStyles.styles.ts
packages/react-components/react-menu/stories/src/Menu/MenuMultilineItems.stories.tsx
packages/react-components/react-menu/stories/src/Menu/MenuSecondaryContentForMenuItems.stories.tsx

Disabled `secondaryText` has different font size. Had hover+active state in HCM when it shouldn't. Did not have disabled appearance in storybook.
Disabled `subText` did not have disabled appearance, not in HCM either. Had hover+active state in HCM. Had hover+active state in HCM when it shouldn't. Did not have disabled appearance in storybook.
- Fixes N/A

fix(react-menu): Fix disabled styles for `secondaryContent` and `subText`

---

change/@fluentui-react-charting-8bb4759f-7a9e-4281-bb8f-a0da9c0f3e99.json
packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx

Responsive container is not working for funnel chart.
This issue is blocking all upcoming releases.
Disabled responsive container for funnel chart to unblock releases.
- Fixes #

fix(react-charting): Disable responsive container for funnel in Declarative Chart

---

packages/charts/react-charts/library/bundle-size/AreaChart.fixture.js
packages/charts/react-charts/library/bundle-size/HeatMapChart.fixture.js
packages/charts/react-charts/library/bundle-size/HorizontalBarChartWithAxis.fixture.js
packages/charts/react-charts/library/bundle-size/SankeyChart.fixture.js
packages/charts/react-charts/library/bundle-size/ScatterChart.fixture.js
packages/charts/react-charts/library/bundle-size/VerticalStackedBarChart.fixture.js

Add fixture.js for remaining charts to calculate monosize of components.
- Fixes #

fix(react-charts): Add fixture.js for remaining charts to calculate monosize

---

scripts/cypress/src/base.config.ts

local mode works (make sure to run `yarn nx reset` once you update from latest master
- Fixes https://github.com/microsoft/fluentui/issues/34800

fix(scripts-cypress): resolve specPattern from projectRoot

---

tools/workspace-plugin/src/executors/generate-api/executor.spec.ts
tools/workspace-plugin/tsconfig.lib.json
tools/workspace-plugin/tsconfig.spec.json

- fixtures were created under same folder which caused race conditions
- `__fixtures__` were included in type-check by accident - causing intermittent failures when type-check was executed before test was able to cleanup / https://github.com/microsoft/fluentui/actions/runs/16219241365/job/45795583521?pr=34748
- fixtures are created under unique folder, preventing any clashes
- tests are deterministic in multiple workers
- `__fixtures__` are excluded from type-check
- Fixes #

chore(workspace-plugin): make generate-api executor test deterministic and ignore any __fixtures__ from type checking

---

change/@fluentui-chart-utilities-8a0d537b-e58b-4ddd-af21-2022c3c47f6b.json
packages/charts/chart-utilities/src/DecodeBase64Data.UT.test.ts
packages/charts/chart-utilities/src/DecodeBase64Data.ts

Work item: https://uifabric.visualstudio.com/iss/_workitems/edit/13376
Works for all below shape formats in schema:
1. "shape": "10, 10"
2. "shape": "[10, 10]"
3. "shape": [10, 10]
Before:
After:

fix(chart-utilities): Decode data in provided shape if present in schema

---

change/@fluentui-react-charts-3fc1c48b-d36a-4617-8ce7-5735727c1ae6.json
packages/charts/react-charts/library/src/components/HorizontalBarChart/HorizontalBarChart.tsx
packages/charts/react-charts/library/src/components/HorizontalBarChart/__snapshots__/HorizontalBarChart.test.tsx.snap
packages/charts/react-charts/library/src/utilities/FocusableTooltipText.tsx

When control comes to each bar, focus ring and callout was not coming together.
Focus ring and callout appears together when control reaches each bar on pressing tab key.
- Fixes #

fix(react-charts): HBC Focus ring fix

---

change/@fluentui-react-charting-bb40eae9-21c2-4187-9ef4-db96ed00a8bf.json
packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
packages/charts/react-charting/src/components/DeclarativeChart/__snapshots__/PlotlySchemaAdapterUT.test.tsx.snap

yMin yMax properties are not honored for declarative chart for VSBC.
- Fixes #

fix(react-charting): Support min max for VSBC in plotly

---

change/@fluentui-react-toolbar-697073d8-9508-4810-999d-7a02bbf83a87.json
packages/react-components/react-toolbar/library/src/components/ToolbarButton/useToolbarButtonStyles.styles.ts
packages/react-components/react-toolbar/library/src/components/ToolbarRadioButton/useToolbarRadioButtonStyles.styles.ts
packages/react-components/react-toolbar/library/src/components/ToolbarToggleButton/useToolbarToggleButtonStyles.styles.ts

Styles overrides can't be applied. 
- Styles overrides can be applied
- Fixes order of style hooks
Fixes https://github.com/microsoft/fluentui/issues/34850.

fix(react-toolbar): properly apply overrides in `ToolbarRadioButton`, `ToolbarToggleButton` & `ToolbarButton`

---

docs/react-v9/contributing/README.md

This PR adds a README as a table of contents for the `docs/react-v9/contributing` folder, making the documentation more discoverable for developers new to working with Fluent UI v9.
- The `docs/react-v9/contributing` folder contained 22 documentation files with no central README.md file to provide an overview of the contents.
- Added a new README.md in the `docs/react-v9/contributing` folder that:
- Includes a brief introduction explaining the purpose of the directory
- Organizes the 22 documentation files into logical categories
- Provides concise but informative descriptions for each link
- Makes subfolders discoverable under "Additional Resources"

[Docs]: Add README table of contents for v9 contributing docs folder

---

change/@fluentui-react-tabs-a4a4d97e-57aa-45af-a514-efc3c99c6417.json
packages/react-components/react-tabs/library/src/components/Tab/useTabStyles.styles.ts

**SMALL**
<p>
</p> 
**MEDIUM** 
<p>
</p> 
**LARGE** 
<p>
</p> 
Updated circular sizes according Figma spec: 
- small: 24px
- medium: 32px
- large: 40px 
- Fixes #34854

fix(react-tabs): fix circular tab sizes according to Figma spec

---

change/@fluentui-web-components-b2a89aae-6b5a-4370-b067-b7acead85419.json
packages/web-components/src/slider/slider.spec.ts
packages/web-components/src/slider/slider.ts

When `orientation="vertical"` and `dir="rtl"`, sliding the thumb down would increase the value, which is the opposite of the design and the visual affordance (darker track color below the thumb indicates the value).
Align value to visual/design.

fix: vertical slider in rtl has the opposite of value than the visual

---

packages/react-components/semantic-style-hooks-preview/library/etc/semantic-style-hooks-preview.api.md
packages/react-components/semantic-style-hooks-preview/library/package.json
packages/react-components/semantic-style-hooks-preview/library/src/component-styles/Search/index.ts
packages/react-components/semantic-style-hooks-preview/library/src/component-styles/Search/useSemanticSearchStyles.styles.ts
packages/react-components/semantic-style-hooks-preview/library/src/component-styles/semanticStyleHooks.ts
packages/react-components/semantic-style-hooks-preview/library/src/index.ts

This pull request introduces a new set of semantic styles for the `SearchBox` component, enabling consistent and customizable styling across different states and sizes. The changes include the creation of a dedicated styling file, integration of the new styles into the semantic style hooks registry, and updates to the exports for better accessibility.
* [`packages/react-components/semantic-style-hooks-preview/library/src/component-styles/Search/useSemanticSearchStyles.styles.ts`](diffhunk://#diff-1d07cad6e7eec6ed6980a538f3eb1fc70db7dba9f42088fa31d209b4b5cede5eR1-R172): Added a comprehensive set of styles for the `SearchBox` component, including support for different sizes (`small`, `medium`, `large`) and states (`focused`, `disabled`). These styles utilize Fluent UI tokens and semantic …

Extended Tokens: Search

---

change/@fluentui-react-menu-45270348-52b5-4989-bde5-28a68bc7338d.json
packages/react-components/react-menu/library/src/components/MenuTrigger/useMenuTrigger.ts

This pull request introduces a feature enhancement to the `@fluentui/react-menu` package, adding support for `event.isDefaultPrevented()` in the `onKeyDown` handler. This change ensures better event handling by allowing developers to prevent default behaviors more effectively:
```tsx
import * as React from "react";
import {
Button,
Menu,
MenuTrigger,
MenuList,
MenuItem,
MenuPopover,
} from "@fluentui/react-components";
export const Default = () => (
<Menu>
<MenuTrigger disableButtonEnhancement>
<Button
onKeyDown={(ev) => {
if (ev.key === "ArrowDown") {
ev.preventDefault();
}
}}
>
Toggle menu
</Button>
</MenuTrigger>
<MenuPopover>
<MenuList>
<MenuItem>New </MenuItem>
<MenuItem>New Window</MenuItem>
<MenuItem disabled>Open File</MenuItem>
<MenuItem>Open Folder</MenuItem>
</MenuList> …
```

feat(Menu): add event.isDefaultPrevented() to `onKeyDown`

---

change/@fluentui-web-components-e1e8293a-32b0-4a2a-909d-9f110901c6c4.json
packages/web-components/src/dialog-body/dialog-body.styles.ts
packages/web-components/src/dialog/dialog.styles.ts

Dialog content was inaccessible on 1280x1024 @ 400% zoom. 
Removed 24px margin on top/bottom of dialog (matches Fluent React implementation) and put position sticky rules for dialog body inside a min-height media query (based on min-viewport height 480px)
- Internally tracked

a11y: remove vertical margins on dialog to support 400% zoom

---

change/@fluentui-react-b45b6d89-5982-4205-be05-5fa7e439605f.json
packages/react/src/components/pickers/PeoplePicker/PeoplePickerItems/PeoplePickerItem.styles.ts

- Fixes [Bug 26432](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/26432): [Fluent UI] [Web] [PeoplePicker]: In Aquatic and Desert mode, Contrast ratio for the selected people picker text is less than 4.5:1 once user navigate to the buttons.

fix(v8 PeoplePicker): Add WHCM styles to the `PeoplePickerItem` remove button

---

packages/react-components/react-menu-grid-preview/library/etc/react-menu-grid-preview.api.md
packages/react-components/react-menu-grid-preview/library/src/components/MenuGrid/useMenuGrid.ts
packages/react-components/react-menu-grid-preview/library/src/components/MenuGridCell/useMenuGridCell.ts
packages/react-components/react-menu-grid-preview/library/src/components/MenuGridRow/useMenuGridRow.ts
packages/react-components/react-menu-grid-preview/library/src/components/MenuGridRowGroup/useMenuGridRowGroup.ts
packages/react-components/react-menu-grid-preview/library/src/components/MenuGridRowGroupHeader/useMenuGridRowGroupHeader.ts

This PR fixes ref typings in the `MenuGrid` components.

Fix(react-menu-grid-preview): Proper typings

---

apps/react-17-tests-v9/package.json
apps/react-17-tests-v9/tsconfig.react-17.json
apps/react-18-tests-v9/package.json
apps/react-18-tests-v9/tsconfig.react-18.json
apps/react-19-tests-v9/package.json
apps/react-19-tests-v9/tsconfig.react-19.json

- adds `grid-preview` to integration apps deps as it cause type-checks to fail https://github.com/microsoft/fluentui/actions/runs/16574493283/job/46875280246?pr=34923
- enables COMPAT packages to be type-checked against React 19 - these packages need to pass as well ( we have this for R17,R18 already )
- Fixes #

fix(react-integration): add missing grid-preview, unify ts configs and run type-check on compat packages against R19

---

change/@fluentui-react-link-b7b54d14-d92f-4d02-8e55-c440294dfe7f.json
packages/react-components/react-link/library/src/components/Link/useLinkStyles.styles.ts

Tokens used for the `inverted` Link variant did not align with the Figma specification:
- The code used `colorBrandForegroundInverted*` tokens
- Figma used `colorNeutralForegroundInvertedLink*` tokens
Figma: https://www.figma.com/design/ZhYpaByCXhprTWpF2097yE/Link?node-id=1105-3387&t=98NVbCUII05TFmti-4
The `inverted` Link variant tokens are now consistent between the component and Figma.
- Fixes #34911

fix(react-link): update inverted link styles to use neutral color tokens

---

change/@fluentui-react-56e83488-6ea7-4087-afed-2b573fdc1637.json
packages/react/src/components/pickers/Suggestions/SuggestionsItem.styles.ts
packages/react/src/components/pickers/Suggestions/__snapshots__/Suggestions.test.tsx.snap

v8 Picker SuggestionItems handle high contrast hover styles split between the parent `SuggestionItem` and inner content`PeoplePickerItemSuggestion` (a wrapper around Persona). However, there's an issue where the `PeoplePickerItemSuggestion` doesn't span the width of `SuggestionItem`, which leaves an area at the right of the item where the hover color styles are mismatched:
This is exacerbating a high contrast color caching issue in Edge around adding/removing `forced-color-adjust: none`, where the browser isn't updating the colors when the mouse fully leaves the item:
https://github.com/user-attachments/assets/d7b5f502-9d5a-4b2a-a83f-14d4d40e57eb
The inner content spans the entire width, which also bypasses the Edge issue.
- Fixes [ADO …

fix: v8 picker suggestion items color issue on hover in WHCM

---

change/@fluentui-web-components-341d48dd-0e45-43a4-9cc0-b9199ac88b92.json
packages/web-components/src/button/button.base.ts

`document.createElement('fluent-button')` throws the following error:
```
Uncaught NotSupportedError: Failed to execute 'createElement' on 'Document': The result must not have attributes
```
Because `tabIndex` is set in `disabledChanged()` which can be called before button is connected.
Only set `tabIndex` (and the `tabindex` attribute) when button is connected.

fix: avoid setting tabindex before button is connected

---

change/@fluentui-react-toast-9e344401-110b-45ba-b662-d3cf788d8705.json
packages/react-components/react-toast/library/src/components/Toast/Toast.cy.tsx
packages/react-components/react-toast/library/src/components/Toaster/useToaster.tsx

Fixes an issue where a user provided keydown handler would override the internal handler. This would stop Escape from dismissing toasts

fix: Toaster should merge user onKeyDown handler

---

change/@fluentui-react-storybook-addon-70139255-9dde-438f-9c7b-0370acee7afa.json
packages/react-components/react-storybook-addon/src/docs/FluentDocsPage.tsx

https://github.com/user-attachments/assets/630e6a0f-3edd-477e-8632-bdcec2da7f58
Slot info is preserved on consecutive page re-render

fix(react-storybook-addon): resolve dissapearing Slot Info message on consecutive page re-renders

---

packages/react-examples/src/react/PeoplePicker/PeoplePicker.List.Example.tsx
packages/react/src/components/pickers/PeoplePicker/PeoplePickerItems/PeoplePickerItemSuggestion.tsx

Fix style resolution in example story so that the PeoplePickerItemSuggestion's persona's styles are no longer overriden incorrectly.
- Fixes [Bug 30154](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/30154): [Fluent UI V8][People Pickers-List People Picker with Wrapped Item text][high contrast]: The persons details are not clearly visible in high contrast themes when it receives keyboard focus.

fix(v8 PeoplePicker): Fix PeoplePicker wrapped list example's hover styles

---

packages/react-components/react-dialog/library/src/components/DialogBody/useDialogBodyStyles.styles.ts
packages/react-components/react-dialog/library/src/components/DialogSurface/useDialogSurfaceStyles.styles.ts

Some small leftover changes in dialog styles snuck through to tokens branch, removing to prevent any core changes.

fix(extended-tokens): Remove core style modifications in extended tokens branch

---

change/@fluentui-react-charts-e332a260-4741-4fac-af8d-ccadbc08ce92.json
packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
packages/charts/react-charts/library/src/components/DeclarativeChart/PlotlySchemaAdapterUT.test.tsx
packages/charts/react-charts/library/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.tsx

Corresponding v8 PR: https://github.com/microsoft/fluentui/pull/34556
https://github.com/microsoft/fluentui/pull/34530
- Fixes #

fix(react-charts): Use schema colorscale for gvbc

---

change/@fluentui-react-positioning-baea89b5-496c-4cff-90cd-c1d34b305be6.json
packages/react-components/react-positioning/library/package.json
yarn.lock

Bumps up to two patch versions from [0.2.1 to 0.2.3](https://github.com/floating-ui/floating-ui/blob/master/packages/devtools/CHANGELOG.md#023) 
- Fixes #35043

chore: bump floating-ui/devtools to 0.2.3

---

change/@fluentui-react-toolbar-1a7ca97a-977c-45b8-9c84-a783f6428017.json
packages/react-components/react-toolbar/library/etc/react-toolbar.api.md
packages/react-components/react-toolbar/library/src/components/ToolbarGroup/ToolbarGroup.types.ts
packages/react-components/react-toolbar/library/src/components/ToolbarGroup/useToolbarGroup.ts
packages/react-components/react-toolbar/library/src/components/ToolbarGroup/useToolbarGroupStyles.styles.ts

`ToolbarGroup` does not have any styles, which breaks dividers inside.
`ToolbarGroup` has the same styles as `Toolbar` now (except `padding`).
Fixes #34738

fix(Toolbar): apply styles for ToolbarGroup

---

apps/public-docsite-v9/src/Concepts/UnprocessedStyles.stories.mdx

adds official docs for griffel RAW style consumption
- https://fluentuipr.z22.web.core.windows.net/pull/34969/public-docsite-v9/storybook/index.html?path=/docs/concepts-developer-unprocessed-styles--docs
- Follows #34853

docs(docsite-v9): add official RAW modules support docs

---

azure-pipelines.deprecate-package.yml
azure-pipelines.hotfix.yml
azure-pipelines.release-vnext.yml
azure-pipelines.release.tools.yml
azure-pipelines.release.web-components.yml
azure-pipelines.release.yml

Small improvement of moving from variables to parameters for dryMode, so checkbox is immediately visible during pipeline triggering process 
UPD: this should fix our dryMode as well, because of the conflict between YAML defined dryRun variable in devops /templates and Azure UI the variable is overwritten

ci: move dryRun from variables to parameters

---

azure-pipelines.release.yml

```shell
Azure Pipelines doesn't allow the "condition" property on a template reference step. 
Only "template" and "parameters" are valid at that level. 
To conditionally include a template step, use a compile-time template expression instead.
```

ci: run publish-website template conditionally

---

change/@fluentui-react-motion-components-preview-9340526b-fb7c-4bad-bbf1-18815127216d.json
packages/react-components/react-motion-components-preview/library/src/atoms/fade-atom.test.ts
packages/react-components/react-motion-components-preview/library/src/atoms/fade-atom.ts

This PR implements the solution for opacity flickering that occurs when using the fadeAtom with delays.
This problem was evident in a different PR for the upcoming `Stagger` component.
- Add fill parameter to fadeAtom with default value of 'both' to prevent opacity flickering
- Maintain backwards compatibility with optional fill parameter
When using fadeAtom with delays, there was visual flickering where the element would briefly show its original opacity before the animation started. The fill 'both' mode ensures that during the delay period and after completion, the element maintains proper opacity values.
- All existing tests continue to pass
- New test suite for fadeAtom functionality
- Tests verify default fill mode behavior and custom fill mode override capability
- Builds on #35076 …

fix(motion): prevent opacity flickering in fadeAtom with fill mode both

---

change/@fluentui-react-tags-ed80a9a9-6af8-429d-858e-89dbb0133796.json
packages/react-components/react-tags/library/src/components/Tag/useTag.tsx

The default button type was submit, which could cause unexpected behavior when TagPicker was used inside a form
The default button type is now button

fix(react-tags): set default button type if dismissible 

---

change/@fluentui-react-table-6820f12e-0e91-48c5-8c1e-d1a171333a45.json
packages/react-components/react-table/library/src/components/DataGridRow/DataGridRow.test.tsx
packages/react-components/react-table/library/src/components/DataGridRow/useDataGridRow.tsx
packages/react-components/react-table/library/src/components/DataGridRow/useDataGridRowStyles.styles.ts
packages/react-components/react-table/library/src/components/DataGridSelectionCell/DataGridSelectionCell.test.tsx
packages/react-components/react-table/library/src/components/DataGridSelectionCell/useDataGridSelectionCell.ts

The radio was visually hidden but had a `disabled` prop added. The `disabled` state was semantically incorrect, and the radio also lacked an accessible name (and wasn't visually present) despite being exposed in the a11y tree. Since the radio is both invisible and not interactable, it should not be in the a11y tree at all.
The radio has `display: none`, removing it from the a11y tree.
- Fixes #34583 and an [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workitems/edit/24838)

fix(DataGrid): single-select radio input should be fully hidden, not disabled

---

apps/react-17-tests-v9/config/support/commands.js
apps/react-17-tests-v9/config/support/component.js
apps/react-17-tests-v9/cypress-react-17.config.ts
scripts/cypress/src/support/commands.js

`scripts-cypress` includes conditional loading based of features based on Cypress versions in order to be able to keep 1 source of truth for integration and normal cypress testing
- reverts r17-tests-v9 cypress changes https://github.com/microsoft/fluentui/pull/34985 by encapsulation
- exposed during https://github.com/microsoft/fluentui/pull/35022
- Fixes #

feat(cypress): make 'press' command work in cypress 13/react 17 and undo setup in r17-tests-v9

---

change/@fluentui-web-components-cae6cbef-0947-42e6-8459-4d3b2c3ec471.json
packages/web-components/docs/web-components.api.md
packages/web-components/src/dropdown/dropdown.base.ts
packages/web-components/src/dropdown/dropdown.definition.ts
packages/web-components/src/dropdown/dropdown.stories.ts
packages/web-components/src/dropdown/dropdown.template.ts
packages/web-components/src/listbox/listbox.template.ts
packages/web-components/src/listbox/listbox.ts
packages/web-components/src/option/option.spec.ts
packages/web-components/src/option/option.ts
packages/web-components/src/utils/request-idle-callback.ts

The `<fluent-dropdown>` component used manual slot assignment and event-driven descendant tracking. This meant certain dropdown actions were tied to a listener for a custom `connected` event fired by a descendant `<fluent-listbox>` component. When the event fired, the parent dropdown would directly assign the listbox to the default slot. This also assumed that the listbox's `<fluent-option>` components were also connected and ready, which may not always be the case. This led to timing issues between all three nested components.
* Removes the [`slotAssignment: "manual"`](https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow#slotassignment) shadow option from the Dropdown definition.
* Removes the `connected` custom event emitted by the Listbox component during its …

fix(web-components): remove dropdown manual slot assignment

---

change/@fluentui-web-components-a63e0ca8-4de2-4db4-b527-89b8ffadc945.json
packages/web-components/docs/web-components.api.md
packages/web-components/src/tree-item/tree-item.base.ts
packages/web-components/src/tree-item/tree-item.template.ts
packages/web-components/src/tree/tree.base.ts
packages/web-components/src/tree/tree.template.ts

In Tree and TreeItem templates, we use `slotted` directive with `elements()` filter to make sure the assigned elements are TreeItems, which also involved using `FluentDesignSysmte.prefix`. But using `FluentDesignSystem` makes it impossible for other libraries to reused the template since they may have different prefixes in their element names.
Switching to using `slotchange` event and filter the assigned elements before assigning them to `childTreeItems` property. `slotchange` event is a browser built-in event, so more robust. This also eliminate the need of using `FluentDesignSystem.prefix`, which means libraries can reuse the template.

refactor: replace slotted with slotchange

---

change/@fluentui-web-components-653c92a3-be49-44a6-851a-d52d144efe5b.json
packages/web-components/package.json
packages/web-components/src/listbox/listbox.ts
packages/web-components/src/utils/request-idle-callback.ts

The `waitForConnectedDescendants` function could loop indefinitely if undefined custom elements are present. Additionally, the `requestIdleCallback` ponyfill doesn't fully shim the native function.
The `waitForConnectedDescendants` function:
* checks with `:not(:defined)` instead of `*`
* runs the callback routine when the `timeRemaining()` hits 0, to account for situations where custom elements which will never be defined are present
* Provides export paths for the modules in the `dist/esm/utils` directory

fix(web-components): use defined in querySelector for requestIdleCallback

---

change/@fluentui-react-list-ac029cf6-2a1e-4edb-a427-de93bbfad634.json
packages/react-components/react-list/library/etc/react-list.api.md
packages/react-components/react-list/library/src/components/ListItem/ListItem.types.ts
packages/react-components/react-list/library/src/components/ListItem/useListItem.tsx
packages/react-components/react-list/library/src/components/ListItem/useListItemStyles.styles.ts
packages/react-components/react-list/stories/src/List/SingleActionSelectionDifferentPrimary.stories.tsx

Previously pointer would be used even if the selection was disabled and there was no other action passed.
Currently pointer is set to "default" when selection is disabled for the item and no `onAction` callback is present.

List: default cursor for items with disabled selection

---

change/@fluentui-react-charting-43e9af9f-0688-4320-bb12-7fa920daebf0.json
packages/charts/react-charting/etc/react-charting.api.md
packages/charts/react-charting/src/components/DeclarativeChart/DeclarativeChart.tsx
packages/charts/react-charting/src/components/DeclarativeChart/PlotlyColorAdapter.ts
packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapter.ts
packages/charts/react-charting/src/components/DeclarativeChart/PlotlySchemaAdapterUT.test.tsx
packages/charts/react-charting/src/components/DeclarativeChart/__snapshots__/DeclarativeChartRTL.test.tsx.snap
packages/charts/react-charting/src/components/DeclarativeChart/__snapshots__/PlotlySchemaAdapterUT.test.tsx.snap
packages/charts/react-charting/src/components/DonutChart/DonutChart.base.tsx
packages/charts/react-charting/src/components/DonutChart/DonutChart.types.ts

Work item https://uifabric.visualstudio.com/iss/_workitems/edit/13444/
fix(react-charting): Fixing donut colors and segment orders
Fixed all below test app examples:
261, 306, 392, 393, 395, 396, 575, 576, 577, 578, 585, 588, 750, 816, 831
Fixes the following:
1. Sorting by value and assigning colors in that order
2. Changing the direction of rendering from clockwise to anticlockwise
3. Picking the last item from array of data for single plot from the schema for rendering
4. Considering negative numbers in total value calculation while calculating segment percentages

fix(react-charting): Fixing donut colors and segment orders

---

change/@fluentui-react-d23e2624-d5ec-4f8a-a317-1c7b9d11141e.json
packages/react/src/components/DetailsList/DetailsRow.base.tsx

Arrowing up/down within a DetailsList row would move between items in the row instead of between rows (can only repro on examples with multiple focusable items in each row, such as the Advanced example).
This was caused by a mistake in the check for `focusZoneProps.direction`:
```js
focusZoneProps ? focusZoneProps.direction : FocusZoneDirection.horizontal
```
Since `focusZoneProps` is always defined in `DetailsRow` props even if only as an empty object, the check never actually used `FocusZoneDirection.horizontal` as the default / fallback value. This causes `FocusZone` to use both up/down and left/right arrows to move between items within the row.
Fixed, up/down arrow keys in DetailsList always move between rows.
- Fixes [ADO issue](https://dev.azure.com/microsoftdesign/fluent-ui/_workite …

fix(DetailsList): DetailsRow correctly falls back to horizontal FocusZone

---

change/@fluentui-web-components-287ac194-c9c2-4cc2-8a00-d30740e0eff6.json
packages/web-components/src/switch/switch.stories.ts
packages/web-components/src/switch/switch.styles.ts

Switch Checked in forced-colors mode didn't show focus ring due to a bug in the story but where it has `slot="input"` which disables the focus ring and yields the behavior to `<fluent-field>` when slotted.
- Remove `slot="input"` to restore focus state
- Improve focus ring style by adding `outline-offset: 1px` (it was blending into the Highlight colro
- Fixes #

[web-components][fix] fix missing focus state in forced colors on checked switch

---

change/@fluentui-react-table-3104ff6a-619f-46a0-8313-2fa905c419cf.json
packages/react-components/react-table/library/etc/react-table.api.md
packages/react-components/react-table/library/src/components/DataGridHeaderCell/DataGridHeaderCell.test.tsx
packages/react-components/react-table/library/src/components/DataGridHeaderCell/DataGridHeaderCell.types.ts
packages/react-components/react-table/library/src/components/DataGridHeaderCell/__snapshots__/DataGridHeaderCell.test.tsx.snap
packages/react-components/react-table/library/src/components/DataGridHeaderCell/useDataGridHeaderCell.ts
packages/react-components/react-table/library/src/components/TableHeaderCell/__snapshots__/TableHeaderCell.test.tsx.snap
packages/react-components/react-table/library/src/components/TableHeaderCell/useTableHeaderCell.tsx
packages/react-components/react-table/stories/src/DataGrid/FocusableElementsInCells.stories.tsx

There were two issues preventing authors from adding their own buttons to DataGrid header cells:
1. It broke arrow key navigation through cells in the grid, as well as not allowing keyboard users to access the inner buttons
2. The `useARIAButtonProps` hook messes with default enter/space key > click behavior, making it impossible to activate the buttons with the keyboard even if you can focus them
We've had a few requests for being able to add custom buttons to header cells (e.g. a menu button and info button / InfoLabel most recently), and it's a pretty common pattern. While we can't currently support that together with the sortable column button behavior, we can support it for non-sortable columns.
Adds `focusMode` as a prop to `DataGridHeaderCell` following the pattern of …

feat: DataGrid header cells can contain interactive controls

---

change/@fluentui-priority-overflow-09409455-f841-4490-8f29-242e315804df.json
change/@fluentui-react-overflow-9b148d37-5471-4fe4-8c62-6bd3775221c5.json
packages/react-components/priority-overflow/etc/priority-overflow.api.md
packages/react-components/priority-overflow/src/overflowManager.ts
packages/react-components/priority-overflow/src/types.ts
packages/react-components/react-breadcrumb/stories/src/Breadcrumb/BreadcrumbWithOverflow.stories.tsx
packages/react-components/react-overflow/library/etc/react-overflow.api.md
packages/react-components/react-overflow/library/src/components/Overflow.tsx
packages/react-components/react-overflow/library/src/useOverflowContainer.test.ts
packages/react-components/react-overflow/library/src/useOverflowContainer.ts

OverflowMenu is not included in occupiedSize.
Overflow component contains only visible overflow items or hidden ones, but hidden because they don't fit the container.
If menu has default hidden items then overflowMenu is not included into calculation.
I added a new optional prop `hasHiddenItems`.
- Fixes #34442

fix(priority-overflow): overflowMenuSize included in occupiedSize

---

change/@fluentui-react-menu-grid-preview-9ac68dd6-389b-4ee4-8b63-9a26d47f1f73.json
packages/react-components/react-menu-grid-preview/library/package.json
packages/react-components/react-menu-grid-preview/library/src/components/MenuGridCell/useMenuGridCell.ts

This PR adds changes so that MenuGrid submenu of MenuList enables navigation using Left or Right arrow key between MenuGrid cell action and MenuGrid row. This fixes the previous incorrect behavior where this arrow key navigation caused closing of the MenuGrid submenu.

Fix(react-menu-grid-preview): Allow navigation in MenuGrid submenu of MenuList

---

change/@fluentui-web-components-d6848271-8fd4-4c70-b050-42ffd9063fb0.json
packages/web-components/custom-elements-manifest.config.js
packages/web-components/package.json
yarn.lock

There was a bug in the CEM analyzer tool where attributes were not being written to the name field when `@attr({})` was passed arguments, becaus eit explicitly looked for `attribute: ...` when arguments were passed.
https://github.com/open-wc/custom-elements-manifest/pull/314
The new version ^0.10.7 has the patch and writes the manifest correctly
- Fixes #

[fix] bump cem analyzer tool to properly write name field

---

apps/rit-tests-v9/src/react-19/components/Tooltip.cy.tsx
change/@fluentui-react-tooltip-61b2e251-ccc8-4eb9-83e4-fff3cb927190.json
packages/react-components/react-tooltip/library/src/components/Tooltip/private/useTooltipTimeout.ts
packages/react-components/react-tooltip/library/src/components/Tooltip/useTooltip.tsx

Alternative approach to #34331
Tooltip uses a custom utilitiy useTimeout (useBrowserTimer) to manage the timer that delays showing the Tooltip. This utility creates the timer through an imperative function, but clears the timer in a useEffect cleanup function. This results in the tooltip never being shown if it is unmounted and remounted after the Tooltip was triggered but before it was shown. This can happen in StrictMode for a component that receives initial focus when it is created, such as a MenuItem.
Tooltip uses it's inner `useTooltipTimeout` hook, which is based on previous `useTimeout` hook from `react-utilities` implementation with a additional check for a real unmount, making this hook StrictMode aware.
- Fixes #34296

fix(react-tooltip): show tooltip correctly under strict mode

---

apps/rit-tests-v8/src/shared/components/ContextualMenu/ContextualMenuExample.cy.tsx
apps/rit-tests-v8/tsconfig.lib.json
apps/rit-tests-v9/tsconfig.lib.json
packages/eslint-plugin/src/configs/react-legacy.js
packages/react-examples/cypress.config.ts
packages/react-examples/src/react/FocusTrapZone/e2e/FocusTrapZone.e2e.tsx

- update `rit-tests-v8` and `rit-tests-v9` tsconfig.lib.json to ignore cypress tests when type-checking,
-  enforce `@fluentui/scripts-cypress` in Cypress tests for v8
- Fixes #

chore: setup no-restricted-imports for cypress tess within react-legacy and resolve issues within apps/rit-tests-v*
