package.json, src/components/DetailsList/DetailsList.tsx
=> 0.36.2 - Fix errant imports

src/components/DetailsList/DetailsList.tsx
Fixes an error that appears when loading a detailsList.
=> Fixed detailsList onRowDidMount callback

src/components/Button/Button.tsx
Remove errant props that generates warnings, as per #44
=> Fix issue #44

src/components/Button/Button.tsx
This reverts commit 97a0bd17e125512e4936bd36803903c1cb35bd2d.
Going for a more proper and robust fix instead.
=> Revert "Fix issue #44 (#46)"

src/components/DatePicker/DatePicker.tsx
This is the fix for https://github.com/OfficeDev/office-ui-fabric-react/issues/20
=> Update 'formattedDate' if Date Picker's 'value' is changed via props.

src/demo/components/App/App.scss, src/demo/components/App/App.tsx
Removing an unnecessary media query in css.
=> Demo app now renders better in ie 9.

src/components/DetailsList/DetailsHeader.tsx, src/components/DetailsList/DetailsList.tsx, src/components/GroupedList/Group.tsx, src/components/GroupedList/GroupHeader.tsx, src/components/GroupedList/GroupedList.Props.ts, src/components/GroupedList/GroupedList.tsx
1. fix column alignment based on group nesting depth
2. fix expand/collapse all
3. add a setting to prevent selection of collapsed groups
=> grouped list bug fixes for column alignment, expand/collapse all and selection

src/components/Dropdown/Dropdown.tsx
=> Recognize dropdown as tabable by the focus utility function

src/components/Nav/Nav.Props.ts, src/components/Nav/Nav.tsx, src/demo/pages/NavPage/examples/Nav.Basic.Example.tsx
Re-submit the request with new branch to avoid the messy merge that has nothing to do with this changes.
=> Adding key, target attributes to INavLInk interface

src/components/DocumentCard/DocumentCard.scss
This will fix accessibility issues for the Document Card in themes with light text and dark backgrounds.
=> Themable background for DocumentCard

src/common/BaseComponent.ts, src/components/DetailsList/index.ts, src/components/GroupedList/Group.tsx, src/components/GroupedList/GroupHeader.tsx, src/components/ProgressIndicator/ProgressIndicator.Props.ts, src/components/ProgressIndicator/ProgressIndicator.scss, src/components/ProgressIndicator/ProgressIndicator.tsx, src/demo/components/PropertiesTable/PropertiesTable.tsx, src/demo/utilities/parser/InterfaceParserHelper.ts, src/utilities/selection/SelectionZone.tsx
Also in this review, updating the DetailsList and documentation generation code to group required/optional/deprecated properties.
=> ProgressIndicator: deprecating "title" and renaming to "label", adding "className"

src/components/GroupedList/GroupHeader.scss, src/components/GroupedList/GroupHeader.tsx, src/components/GroupedList/GroupedList.scss
- Added tag icon for animation
- Updated ChevronDown icon size per design specs
- Fixed code review issues from closed PR #117
=> Adding drag and drop animation to GroupList

src/common/_themeOverrides.scss
Adding a theme slot already in use.
=> Add $ms-color-neutralPrimaryAlt

src/components/GroupedList/GroupHeader.scss
- Updated expand icon position
- Changed icon sizes to use icon size ramp
=> GroupedList MDL2 Updates.

src/components/DatePicker/DatePicker.scss, src/components/TextField/TextField.scss
- Fixed calendar icon spacing
- Added padding to error message
- Added cursor pointer to datepicker inputfield
- Vertically centered dates and month buttons
- Removed unused float
=> Fixed DatePicker bugs. Removed unused float.

src/components/SearchBox/SearchBox.scss, src/components/SearchBox/SearchBox.tsx
- Fixed Clear button
- Fixed input text padding
- Fixed error message padding
- Fixed text overlapping icon
- Updated hover styles
=> SearchBox: Fixed clear button. Updated styles.

src/common/_fabricExtraIcons.scss, src/components/DetailsList/DetailsHeader.tsx
Added SortUp and SortDown icons to _fabricExtraIcons and change DetailsHeader.tsx to include new icons
=> Change DetailsList sort icons to SortUp and SortDown from Up and Down

package.json, src/components/Nav/Nav.Props.ts, src/components/Nav/Nav.tsx, src/demo/pages/NavPage/examples/Nav.Basic.Example.tsx
=> Nav component need to have aria label

src/components/Check/Check.scss, src/components/Check/Check.tsx, src/components/DetailsList/DetailsHeader.scss, src/components/DetailsList/DetailsRow.scss
New MDL2 checkmark icon for details list.  Screenshots below
Row hover
Checkmark hover
Selected
=> New MDL2 check, switched from SVG circle to css

src/components/PeoplePicker/PeoplePicker.scss
Fix people picker so corners are rounded
=> Fix border radius on people picker persona component

src/components/Slider/Slider.tsx
Fix slider doesn't update slider thumb position when value prop is updated.
=> Slider now updates thumb position when value prop is updated

.travis.yml, gulpfile.js, package.json, src/components/Breadcrumb/Breadcrumb.tsx, src/components/DetailsList/index.ts, src/components/List/List.Props.ts, src/components/List/List.tsx, src/demo/components/PropertiesTable/PropertiesTable.tsx, src/demo/pages/NavPage/examples/Nav.Basic.Example.tsx, src/demo/utilities/pageroute.ts, src/utilities/eventGroup/EventGroup.ts
This integrates the latest build tools, which enables custom builds of typescript to be used. I've bumped to 2.0, which will get rid of the merge warnings. :)
=> Update typescript to 2.0

src/components/Breadcrumb/Breadcrumb.scss
set breadcrumb chevron line height to 1
=> Fix breadcrumb-chevron line height

src/demo/pages/CheckboxPage/CheckboxPage.tsx, src/demo/pages/ChoiceGroupPage/ChoiceGroupPage.tsx, src/demo/pages/CommandBarPage/CommandBarPage.tsx, src/demo/pages/ContextualMenuPage/ContextualMenuPage.tsx, src/demo/pages/DatePickerPage/DatePickerPage.tsx, src/demo/pages/DetailsListPage/DetailsListPage.tsx, src/demo/pages/DialogPage/DialogPage.tsx, src/demo/pages/DocumentCardPage/DocumentCardPage.tsx, src/demo/pages/DropdownPage/DropdownPage.tsx, src/demo/pages/Facepile/FacepilePage.tsx, src/demo/pages/LabelPage/LabelPage.tsx, src/demo/pages/LayerPage/LayerPage.tsx, src/demo/pages/LinkPage/LinkPage.tsx, src/demo/pages/MessageBarPage/MessageBarPage.tsx, src/demo/pages/NavPage/NavPage.tsx, src/demo/pages/OverlayPage/OverlayPage.tsx, src/demo/pages/PanelPage/PanelPage.tsx, src/demo/pages/PeoplePickerPage/PeoplePickerPage.tsx, src/demo/pages/PersonaPage/PersonaPage.tsx, src/demo/pages/PivotPage/PivotPage.tsx, src/demo/pages/ProgressIndicatorPage/ProgressIndicatorPage.tsx, src/demo/pages/SearchBoxPage/SearchBoxPage.tsx, src/demo/pages/SliderPage/SliderPage.tsx, src/demo/pages/SpinnerPage/SpinnerPage.tsx, src/demo/pages/TextFieldPage/TextFieldPage.tsx, src/demo/pages/TogglePage/TogglePage.tsx
Added bestPractices prop to components to show header on pages
=> add missing best practices prop to component pages

README.md
Responds to #297 by adjusting the link.
=> Fix broken tutorial link in readme

src/components/Nav/Nav.Props.ts, src/components/Nav/Nav.tsx, src/demo/components/App/AppState.ts
Same PR, just had some fast-forwarding mishaps that needed a fresh new PR. Comments were addressed from the last one.
https://github.com/OfficeDev/office-ui-fabric-react/pull/290
=> Keep track of internally updated selectedKey in Nav, add keys for Nav items in AppState example pages

src/components/Link/Link.scss
Quick change to make the element selector lowercase, to be consistent with our CSS elsewhere.
=> Change BUTTON to button

src/components/ContextualMenu/ContextualMenu.tsx, src/components/Popup/Popup.tsx
Also fixed an issue where popup would focus the previous item too soon on dismiss.
=> Fixed: an issue where contextualmenu onclick passed incorrect information

src/components/pickers/Suggestions/Suggestions.tsx
Fixed an issue where react would give a warning because an item didn't have a key.
=> Fix: React warning for suggestions item not having key

src/components/Nav/Nav.tsx
Add null/undefined object check for link and group object passed in.
=> Protect render function from bogus data

src/demo/pages/OverlayPage/OverlayPage.tsx, src/demo/pages/OverlayPage/examples/Overlay.Dark.Example.tsx, src/demo/pages/OverlayPage/examples/Overlay.Example.scss, src/demo/pages/OverlayPage/examples/Overlay.Light.Example.tsx
Fixes #358 by documenting the dark variant of the Callout.
I encountered a bug while adding in the code example for the dark variant, and have opened up #360 to track issue.
=> Overlay: Add dark variant

src/components/MarqueeSelection/MarqueeSelection.tsx
Firefox raises mousedown events when clicking on the scroll thumb in a scrollable div. We need to measure where the click occurs in this case to avoid starting marquee selection.
=> MarqueeSelection: selection no longer starts when clicking on scroll thumb in Firefox.

src/demo/pages/OverlayPage/OverlayPage.tsx
Adds Overlay Dark variant example code to component page
=> Add overlay dark example code

src/demo/components/ComponentPage/ComponentPage.scss, src/demo/components/ExampleCard/ExampleCard.scss
RTL support for component page
=> Add RTL mixins for ComponentPage and ExampleCard components

.vscode/settings.json, src/components/pickers/BasePicker.Props.ts, src/components/pickers/BasePicker.tsx, src/components/pickers/PeoplePicker/PeoplePickerItems/SelectedItemDefault.tsx, src/components/pickers/Suggestions/Suggestions.Props.ts, src/components/pickers/Suggestions/Suggestions.scss, src/components/pickers/Suggestions/Suggestions.tsx, src/demo/pages/PickersPage/examples/PeoplePicker.Types.Example.tsx
=> Adding: Pickers loading spinner and text

src/components/Facepile/Facepile.Props.ts, src/components/Facepile/Facepile.tsx
I need this for writing tests downstream.
=> add automation id for Facepile member button

src/components/Dropdown/Dropdown.Props.ts, src/components/Dropdown/Dropdown.tsx
Allow support for rendering custom drop down options
=> Render a custom drop down item

src/components/Callout/Callout.Props.ts, src/components/Callout/Callout.scss, src/components/Callout/CalloutContent.tsx, src/components/ContextualMenu/ContextualMenu.tsx, src/components/TeachingBubble/TeachingBubble.tsx, src/demo/pages/CalloutPage/examples/Callout.Directional.Example.tsx, src/demo/pages/ContextualMenuPage/examples/ContextualMenu.Directional.Example.tsx
This fixes a bad issue where the beak width was not related to the actual beak width.
=> Breaking Change/Deprecate: Change callout beak to use BeakWidth instead of BeakStyle

src/components/DocumentCard/DocumentCardTitle.scss, src/components/DocumentCard/DocumentCardTitle.tsx
=> Update DocumentCard title font

src/demo/pages/ButtonPage/ButtonPage.tsx
=> Fix Button Anchor Example code

src/utilities/hoist.ts
Augment documentation of hoist
=> Augment documentation of hoist

src/components/GroupedList/GroupedList.Props.ts
Updating the relative path for the List import to match the other instances of where it is imported (resolve to d.ts file instead of resolving to a folder)
=> updating relative path of List import in GroupedList.Props.ts

src/components/TeachingBubble/TeachingBubble.scss
RTL now puts close button on the opposite side.
=> Use RTL mixin for close button position

src/components/Dialog/DialogFooter.tsx
Fixes #448 by making sure that children is always an array.
=> Made sure that an array was always passed into map function

src/components/DetailsList/DetailsList.Props.ts, src/components/DetailsList/DetailsList.tsx, src/components/DetailsList/DetailsRow.tsx, src/demo/pages/DetailsListPage/examples/DetailsList.Advanced.Example.tsx
Per request from partners, we can now hide checkboxes in detailslist.
=> DetailsList: now supports CheckboxVisibility.hidden

src/components/Spinner/Spinner.scss
Based on comments from our designer Seyit and Colton.
=> Updated spinner animation-timing-function

ghdocs/BESTPRACTICES.md
After going through a scrub of the components, we're adjusting the guidance for naming conventions to props. Jon's PR addresses some of the fixes but we have some more cleanup to do.
=> Updates to best practices.

src/components/MessageBar/MessageBar.scss, src/components/MessageBar/MessageBar.tsx, src/demo/pages/MessageBarPage/examples/MessageBar.Basic.Example.tsx
=> Adding in padding for message bar, fixing overflow issue, and other minor problems.

src/components/ContextualMenu/ContextualMenu.scss, src/components/ContextualMenu/ContextualMenu.test.tsx
=> Contextual menu/scrollbar bug

packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx, packages/office-ui-fabric-react/src/demo/pages/DatePickerPage/examples/DatePicker.Input.Example.tsx
If you pass in a null value to DatePicker now, it won't throw a React warning in console.
=> DatePicker: handle null value.

packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.scss, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.scss, packages/office-ui-fabric-react/src/demo/pages/CommandBarPage/examples/data.ts
Related: https://github.com/OfficeDev/office-ui-fabric-react/issues/463
=> CommandBarItem: Changed css to support disabled.

README.md, common/changes/miwhea-update-cdn-references_2016-11-21-21-21.json, ghdocs/README.md, packages/examples/todo-app/index.html, packages/office-ui-fabric-react/README.md
The CDN location has moved. This PR updates references within three README files and the todo-app example to point to the new location.
The CDN links have been verified, no additional testing is required.
=> Update CDN references to new location

common/changes/slider-button-fix_2016-11-21-19-13.json, packages/office-ui-fabric-react/src/components/Slider/Slider.Props.ts, packages/office-ui-fabric-react/src/components/Slider/Slider.test.tsx, packages/office-ui-fabric-react/src/components/Slider/Slider.tsx, packages/office-ui-fabric-react/src/demo/pages/SliderPage/examples/Slider.Basic.Example.tsx
Slider now has `type='button'` by default.
Slider no longer submits a form (has the appropriate `type` attribute.)
=> Slider button fix

common/changes/toggle-label_2016-11-22-18-10.json, packages/office-ui-fabric-react/src/components/Toggle/Toggle.Props.ts, packages/office-ui-fabric-react/src/components/Toggle/Toggle.test.tsx, packages/office-ui-fabric-react/src/components/Toggle/Toggle.tsx
`Toggle` no longer requires the `label` property and conditionally renders it.
`Toggle` continues to function.
=> Toggle: label now optional, className moved to container.

packages/examples/todo-app/src/components/Todo.tsx, packages/office-ui-fabric-react/src/common/StoreHost.tsx, packages/office-ui-fabric-react/src/common/connect.tsx, packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.test.tsx, packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.tsx, packages/office-ui-fabric-react/src/components/Button/Button.tsx, packages/office-ui-fabric-react/src/components/Callout/Callout.test.tsx, packages/office-ui-fabric-react/src/components/Callout/Callout.tsx, packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx, packages/office-ui-fabric-react/src/components/Check/Check.tsx, packages/office-ui-fabric-react/src/components/ColorPicker/ColorPicker.tsx, packages/office-ui-fabric-react/src/components/ColorPicker/ColorRectangle.tsx, packages/office-ui-fabric-react/src/components/ColorPicker/ColorSlider.tsx, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsRowFields.tsx, packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardActions.tsx, packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardActivity.tsx, packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardPreview.tsx, packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardTitle.tsx, packages/office-ui-fabric-react/src/components/Fabric/Fabric.tsx, packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx, packages/office-ui-fabric-react/src/components/Layer/LayerHost.tsx
I just ran the auto formatting through all the source files so that we can have consistent spacing and not have a bunch of noise in other PRs.
=> Fixing all the space formatting (Thanks VSCode!)

common/changes/dropdown-fixfix_2016-11-26-21-51.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.Props.ts, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx, packages/office-ui-fabric-react/src/demo/pages/DropdownPage/examples/Dropdown.Basic.Example.tsx
Fixing the recent change that caused a regression where passing in a new "disabled" value was not updating state.
=> Dropdown: disabled now respects changes.

LICENSE, README.md, common/changes/update-license_2016-11-29-17-38.json, packages/office-ui-fabric-react/LICENSE, packages/office-ui-fabric-react/README.md, packages/office-ui-fabric-react/Third Party Notices.txt
Updates the link to the asset license and clarifies that it covers both fonts and icons.
=> Update asset license link and wording

packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.test.tsx, packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx
SelectionZone no longer infinite loops when clicking on an area outside of body.
=> SelectionZone: Removing infinite loop.

common/changes/update-shrinkwrap_2016-12-04-16-32.json, common/npm-shrinkwrap.json, common/temp_modules/npmx-todo-app/package.json, package.json, packages/office-ui-fabric-react/CHANGELOG.json, packages/office-ui-fabric-react/CHANGELOG.md
Just keeping dependencies fresh. Also bumping npmx to test changelog generation.
=> Updating dependencies in shrinkwrap

common/changes/tabbable-fix_2016-12-05-19-48.json, packages/office-ui-fabric-react/src/utilities/focus.test.tsx, packages/office-ui-fabric-react/src/utilities/focus.ts
isElementTabbable should return true if the element has role=button or tabIndex >= 0.
Added tests to cover these cases as well as a bunch of others.
=> isElementTabbable: Adding some edge cases to the helper to not deselect in unexpected cases.

common/changes/slider-fix_2016-12-09-02-00.json, packages/office-ui-fabric-react/src/components/Slider/Slider.tsx
Slider now supports up (increase), down (decrease), home (min), and end (max)
=> Slider: added up/down/home/end keyboard support.

common/changes/bfix-onRenderRow_2016-12-10-20-42.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.Props.ts, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx
- [x ] Include a change request file if publishing (Run `npmx change` to generate it.)
Pass `defaultRender` to DetailsList `onRenderRow` prop
=> Pass defaultRender to DetailsList onRenderRow

README.md, ghdocs/TESTING.md
Adding in a file for more information on how to test.
=> ReadMe: Update to include information about how to test.

common/changes/autofill-improvements_2016-12-30-22-08.json, packages/office-ui-fabric-react/src/components/pickers/AutoFill/BaseAutoFill.Props.ts, packages/office-ui-fabric-react/src/components/pickers/AutoFill/BaseAutoFill.test.tsx, packages/office-ui-fabric-react/src/components/pickers/AutoFill/BaseAutoFill.tsx
Greatly improved the way that BaseAutoFill handles autofill, arrow keys, and deletion.
=> BaseAutoFill: Made many improvements

common/changes/wdo3650-change-log-typo-fix_2017-01-03-23-48.json, packages/office-ui-fabric-react/CHANGELOG.json
=> Change log typo fix

common/changes/contextualmenu-implemementbounds_2017-01-04-22-45.json, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx
Made it so that contextualmenu correctly passes bounds to callout
=> Contextualmenu implemementbounds

common/changes/contextualmenu-fixscrollbar-ie_2017-01-05-01-42.json, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.scss
Change ms-contextualmenu-link to block so it displays properly in ie.
=> Contextualmenu: Change ms-contextualmenu-link to block so it displays properly in ie.

common/changes/nav-classname_2017-01-05-14-09.json, packages/office-ui-fabric-react/src/components/Nav/Nav.Props.ts, packages/office-ui-fabric-react/src/components/Nav/Nav.tsx
Allow className prop to Nav for custom styling.
=> Nav: add className option to allow styling for top-level container

common/changes/contextualmenu-add-headers_2017-01-06-19-47.json, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.Props.ts, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.scss, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.test.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx, packages/office-ui-fabric-react/src/demo/pages/ContextualMenuPage/ContextualMenuPage.tsx, packages/office-ui-fabric-react/src/demo/pages/ContextualMenuPage/examples/ContextualMenu.Basic.Example.tsx, packages/office-ui-fabric-react/src/demo/pages/ContextualMenuPage/examples/ContextualMenu.Header.Example.tsx
Added in the ability to give the contextualmenu headers. Now you pass if you pass in an item type of ContextualMenuItemType.Header it will create a header.
=> ContextualMenu: Added the ability to create header items

common/changes/feature-ratingControl_2017-01-10-03-59.json, packages/office-ui-fabric-react/src/Rating.ts, packages/office-ui-fabric-react/src/components/Rating/Rating.Props.ts, packages/office-ui-fabric-react/src/components/Rating/Rating.scss, packages/office-ui-fabric-react/src/components/Rating/Rating.test.tsx, packages/office-ui-fabric-react/src/components/Rating/Rating.tsx, packages/office-ui-fabric-react/src/components/Rating/index.ts, packages/office-ui-fabric-react/src/demo/components/App/AppState.ts, packages/office-ui-fabric-react/src/demo/pages/RatingPage/RatingPage.tsx, packages/office-ui-fabric-react/src/demo/pages/RatingPage/examples/Rating.Basic.Example.scss, packages/office-ui-fabric-react/src/demo/pages/RatingPage/examples/Rating.Basic.Example.tsx, packages/office-ui-fabric-react/src/index.ts
New star-rating component resembling http://getmwf.com/components/content/rating.html. Component was built following angeal's redlines from Februrary, focusing on the input part for now. 
I've left out the count mentioned, not sure whether this should be part of the component
- A11Y looks good now.
=> New component: Rating

common/changes/contextualmenu-submenuiconprops_2017-01-09-23-00.json, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.Props.ts, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.scss, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx
Added submenuIconProps to allow customization.
(optional)
=> ContextualMenu: Added submenuIconProps to allow customization.

packages/office-ui-fabric-react/src/demo/pages/LayerPage/examples/Layer.Hosted.Example.tsx
Minor documentation update for Layer; no publish required.
=> Layer example: Fixing layer doc.

common/changes/leddie24-dropdown-classname-prop_2017-01-16-18-38.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.Props.ts, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx
Adds `className` prop to component for adding custom class name.
=> Dropdown: Add className prop

common/changes/contextualmenu-undefinedicon_2017-01-19-20-32.json, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx
Fix bug where an icon would have ms-icon--undefined in it's classname'
=> ContextualMenu: fix bug where an icon would have ms-icon--undefined in it's classname'

common/changes/suggestions-noresultserror_2017-01-20-18-34.json, packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx
Fixed Error if noResultsText was not passed to suggestions
=> Suggestions: Fixed Error if noResultsText was not passed to suggestions

common/changes/pickers-fixmultipledelete_2017-01-20-22-09.json, packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
Fixed a bug where you could not delete multiple selected items
=> Pickers: Fixed a bug where you could not delete multiple selected items

common/changes/tooltip-dimiss_2017-01-23-09-28.json, packages/office-ui-fabric-react/src/components/Tooltip/TooltipHost.tsx
TooltipHost uses Callout control internally which exposes onDismiss handler that is now wired to dismiss the tooltipHost. 
http://codepen.io/mdahamiwal/pen/MJmNmW
=> Tooltip: dimiss on scroll

packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.tsx, packages/office-ui-fabric-react/src/demo/pages/DetailsListPage/examples/DetailsList.Advanced.Example.tsx, packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx
Implemented onItemContextMenu for DetailsList component. This property in on the IDetailsListProps interface, but not currently used. This property is passed down to the DetailsRow as a prop and tied to the oncontextmenu event for the div of the row.
Also, updated the Advanced DetailsList example to show usage of this property.
(optional)
=> Implemented onItemContextMenu on DetailsList.

packages/office-ui-fabric-react/src/components/Calendar/Calendar.scss, packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx
=> Calendar: Fixes unwanted scroll bars on months with exactly 4 weeks

common/changes/separate-button-sass-fixes_2017-01-25-16-36.json, packages/office-ui-fabric-react/src/components/Button/Button.Props.ts, packages/office-ui-fabric-react/src/components/Button/Button.tsx, packages/office-ui-fabric-react/src/components/Button/ButtonCore/ButtonCore.scss, packages/office-ui-fabric-react/src/demo/pages/ButtonPage/ButtonPage.tsx, packages/office-ui-fabric-react/src/demo/pages/ButtonPage/examples/Button.Hero.Example.tsx
Restore hero button and alias normal button to default button
=> Restore hero button and alias normal button to default button

common/changes/leddie24-js-component-links_2017-01-30-22-50.json, packages/office-ui-fabric-react/src/demo/pages/BreadcrumbPage/BreadcrumbPage.tsx, packages/office-ui-fabric-react/src/demo/pages/ButtonPage/ButtonPage.tsx, packages/office-ui-fabric-react/src/demo/pages/CalloutPage/CalloutPage.tsx, packages/office-ui-fabric-react/src/demo/pages/CheckboxPage/CheckboxPage.tsx, packages/office-ui-fabric-react/src/demo/pages/ChoiceGroupPage/ChoiceGroupPage.tsx, packages/office-ui-fabric-react/src/demo/pages/CommandBarPage/CommandBarPage.tsx, packages/office-ui-fabric-react/src/demo/pages/ContextualMenuPage/ContextualMenuPage.tsx, packages/office-ui-fabric-react/src/demo/pages/DatePickerPage/DatePickerPage.tsx, packages/office-ui-fabric-react/src/demo/pages/DialogPage/DialogPage.tsx, packages/office-ui-fabric-react/src/demo/pages/DropdownPage/DropdownPage.tsx, packages/office-ui-fabric-react/src/demo/pages/Facepile/FacepilePage.tsx, packages/office-ui-fabric-react/src/demo/pages/LabelPage/LabelPage.tsx, packages/office-ui-fabric-react/src/demo/pages/LinkPage/LinkPage.tsx, packages/office-ui-fabric-react/src/demo/pages/ListPage/ListPage.tsx, packages/office-ui-fabric-react/src/demo/pages/MessageBarPage/MessageBarPage.tsx, packages/office-ui-fabric-react/src/demo/pages/OverlayPage/OverlayPage.tsx, packages/office-ui-fabric-react/src/demo/pages/PanelPage/PanelPage.tsx, packages/office-ui-fabric-react/src/demo/pages/PeoplePickerPage/PeoplePickerPage.tsx, packages/office-ui-fabric-react/src/demo/pages/PersonaPage/PersonaPage.tsx, packages/office-ui-fabric-react/src/demo/pages/PivotPage/PivotPage.tsx, packages/office-ui-fabric-react/src/demo/pages/ProgressIndicatorPage/ProgressIndicatorPage.tsx, packages/office-ui-fabric-react/src/demo/pages/SearchBoxPage/SearchBoxPage.tsx, packages/office-ui-fabric-react/src/demo/pages/SpinnerPage/SpinnerPage.tsx, packages/office-ui-fabric-react/src/demo/pages/TextFieldPage/TextFieldPage.tsx, packages/office-ui-fabric-react/src/demo/pages/TogglePage/TogglePage.tsx
Updates component page links to point to new JS site (if applicable)
=> Update React component pages with links to JS component equivalent

common/changes/fix-import_2017-01-31-00-15.json, packages/office-ui-fabric-react/src/Utilities.ts, packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/PeoplePickerItems/SelectedItemDefault.tsx, packages/office-ui-fabric-react/src/demo/components/ExampleCard/ExampleCard.tsx, packages/office-ui-fabric-react/src/demo/pages/CommandBarPage/examples/CommandBar.Basic.Example.tsx, packages/office-ui-fabric-react/src/demo/pages/FocusZonePage/examples/FocusZone.List.Example.tsx, packages/office-ui-fabric-react/src/demo/pages/FocusZonePage/examples/FocusZone.Photos.Example.tsx, packages/office-ui-fabric-react/src/demo/pages/ListPage/examples/List.Basic.Example.tsx, packages/office-ui-fabric-react/src/demo/pages/MarqueeSelectionPage/examples/MarqueeSelection.Basic.Example.tsx, packages/office-ui-fabric-react/src/demo/pages/PeoplePickerPage/examples/PeoplePicker.Types.Example.tsx, packages/office-ui-fabric-react/src/demo/pages/ProgressIndicatorPage/examples/ProgressIndicator.Basic.Example.tsx, packages/office-ui-fabric-react/src/demo/pages/RatingPage/examples/Rating.Basic.Example.tsx
This basically just tweaks the export path of utilities to export from the specific index file instead of from the default export since AMD bundlers aren't smart enough to parse package.json for the main entry.
=> Updating import of utilities to be AMD friendly

common/changes/leddie24-commandbar-hover_2017-01-26-20-25.json, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.scss
CommandBarItem is missing hover state effects.  Changes background and color on hover.
=> CommandBar: Add hover state to ms-CommandBarItem

common/changes/peoplepicker-demo-improvements_2017-02-02-20-37.json, packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/PeoplePickerItems/PickerItemsDefault.scss, packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/PeoplePickerItems/SelectedItemWithMenu.tsx, packages/office-ui-fabric-react/src/demo/pages/PeoplePickerPage/examples/PeoplePickerExampleData.ts
PeoplePicker: Improve demo page and the way menuitembelow works
=>  PeoplePicker: Improve demo page and the way menuitembelow works

common/changes/dropdownfixees_2017-02-02-14-17.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.Props.ts, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx, packages/office-ui-fabric-react/src/demo/pages/DropdownPage/examples/Dropdown.Basic.Example.tsx
- Added ariaLabel prop to dropdown component
- Fixed dropdown component id prop not being used.
=> Dropdown: changes to include id and ariaLabel

common/changes/textfield-cleanup_2017-02-02-21-19.json, packages/office-ui-fabric-react/src/components/TextField/TextField.Props.ts, packages/office-ui-fabric-react/src/components/TextField/TextField.tsx
Merging some of the cleanup from PR #264
=> TextField: minor doc cleanup

package.json, rush.json
=> Updating rush 1.5.1

common/changes/eliblock-fixFacepileImport_2017-02-03-06-20.json, packages/office-ui-fabric-react/src/components/Facepile/Facepile.tsx
Just tweaking a couple imports in Facepile to make them resolve correctly under an AMD/RequireJS environment.
=> Updating Facepile imports to be AMD friendly

common/changes/basebutton-renderchildren_2017-02-03-23-08.json, packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx
BaseButton fixed a bug so it correctly renders children
(optional)
=> BaseButton: Make it correctly render children

common/changes/button-fix_2017-02-07-01-42.json, packages/office-ui-fabric-react/src/components/Button/ButtonCore/ButtonCore.scss, packages/office-ui-fabric-react/src/components/TeachingBubble/TeachingBubble.scss
Reverting some button css quirks.
=> Button: addressing alignment issues.

common/changes/panel-fix_2017-02-07-20-17.json, packages/office-ui-fabric-react/gulpfile.js, packages/office-ui-fabric-react/src/components/Panel/Panel.test.tsx, packages/office-ui-fabric-react/src/components/Panel/Panel.tsx
A recent regression is preventing onDismiss from being called, and the unit tests were replaced with tests for onDismissed. This was not intended.
=> Panel: onDismiss correctly executed

packages/office-ui-fabric-react/src/demo/utilities/parser/EnumParserHelper.ts
This is a patch requested by @dzearing to fix the autodoc parser.
=> (Autodoc) Add support for enums with values assigned

apps/fabric-website/src/pages/Interstitials/FabricJSPage.tsx
Update link on JS interstitial page to link to Fabric JS Website
=> Change button on JS interstitial page to point to Fabric JS Website

common/changes/master_2017-02-09-21-21.json, packages/office-ui-fabric-react/src/components/Button/ButtonCore/ButtonCore.scss, packages/office-ui-fabric-react/src/components/Button/ButtonCore/ButtonCoreVars.scss, packages/office-ui-fabric-react/src/components/Button/CommandButton/CommandButton.scss, packages/office-ui-fabric-react/src/components/Button/CompoundButton/CompoundButton.scss, packages/office-ui-fabric-react/src/components/Button/DefaultButton/DefaultButton.scss, packages/office-ui-fabric-react/src/components/Button/IconButton/IconButton.scss, packages/office-ui-fabric-react/src/components/Button/PrimaryButton/PrimaryButton.scss
Ever since buttons were refactored and split apart to inherit from button base, they suffered from various specificity issues resulting in various layout bugs. The most prominent of these bugs is that even in the "example" app, disabled states were not being applied correctly to the various types of buttons.
This change attempts to address this issue.
Button
=> Button: Address various layout bugs to do with specificity.

common/changes/wdo3650-panel-jitter-bug-fix_2017-02-10-01-00.json, packages/office-ui-fabric-react/src/components/Panel/Panel.scss
Bug fix for panel animation jitter. Removal of unused CSS in panel.
=> Panel Animation Jitter Fix

apps/fabric-examples/package.json, apps/fabric-website/package.json, apps/todo-app/package.json, common/changes/fix-react-typings_2017-02-13-07-41.json, common/npm-shrinkwrap.json, common/temp_modules/rush-example-app-base/package.json, common/temp_modules/rush-fabric-examples/package.json, common/temp_modules/rush-fabric-website/package.json, common/temp_modules/rush-office-ui-fabric-react/package.json, common/temp_modules/rush-ssr-tests/package.json, common/temp_modules/rush-todo-app/package.json, common/temp_modules/rush-utilities/package.json, packages/office-ui-fabric-react/package.json, packages/utilities/package.json
This removes all `@types/react` and `@types/react-dom` from dependencies which is causing problems downstream.
=> Remove react typings as dependencies.

packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
Removed the offending .then resolver inside the if statement on the updateValue method.  This was causing a run time error of trying to invoke a nonexistent .then method.
(optional)
=> Bug Fix BasePicker.tsx

package.json
Making sure the rush regression is fixed before committing.
=> Bumping rush version

common/changes/leddie24-datepicker-no-props_2017-02-07-19-46.json, packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.Props.ts, packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx
Makes props optional so DatePicker works without them ``<DatePicker />``
=> DatePicker: Component works without props

apps/fabric-examples/src/pages/CalloutPage/examples/Callout.Directional.Example.tsx
Callout direction example was missing an onDismiss callback.
=> Fixed direction example of callout to include proper onDismiss callback

common/changes/wdo3650-Breadcrumb-guidelines-alignment_2017-02-16-23-09.json, packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.scss
Aligning Breadcrumb to design guidance and fix for chevron position at smaller breakpoints
=> Breadcrumb Design Guidelines Alignment

packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.tsx
Fixed by removing the troubling attribute "aria-sort" from the button element.
=> remove aria-sort from button element

common/changes/people-picker-button-padding_2017-02-16-17-28.json, packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.scss
Return suggested items to original padding values, add display block to
fix following space due to inline-block
=> Fixed suggested items padding

common/changes/component-css-breadcrumb_2017-02-18-23-01.json, packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.scss, packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.tsx
Updates style rules to be local scoped instead of global.
No styles were changed.
No existing class names were removed.
=> CSS modules: Breadcrumb

common/changes/textfield-aria-overrides_2017-02-22-16-24.json, packages/office-ui-fabric-react/src/components/TextField/TextField.tsx
native aria props should be down the order to allow override externally.
(optional)
=> Textfield allow aria overrides

common/changes/master_2017-02-22-02-05.json, packages/office-ui-fabric-react/src/components/Pivot/Pivot.scss, packages/office-ui-fabric-react/src/components/Pivot/Pivot.tsx
Module-ify CSS for Pivot control.
=> Pivot css module.

apps/fabric-website/index.html, common/npm-shrinkwrap.json, common/temp_modules/rush-example-app-base/package.json, common/temp_modules/rush-fabric-examples/package.json, common/temp_modules/rush-fabric-website/package.json, common/temp_modules/rush-ssr-tests/package.json, common/temp_modules/rush-todo-app/package.json, packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.scss, packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.tsx
Update Searchbox CSS Modules
Converted Searchbox to use CSS Modules
Searchbox in example apps.
=> Adding Searchbox css modules

common/changes/toggle-type-aria_2017-03-01-15-26.json, packages/office-ui-fabric-react/src/components/Toggle/Toggle.Props.ts, packages/office-ui-fabric-react/src/components/Toggle/Toggle.tsx
Support for providing aria attributes to toggle component, 
Fixes type='button' that got regressed in #1050 
(optional)
=> Toggle: fix for button type and support for aria attributes

apps/fabric-examples/src/pages/PivotPage/examples/Pivot.IconCount.Example.tsx, common/changes/feature-customPivotLink_2017-03-01-01-12.json, packages/office-ui-fabric-react/src/components/Pivot/Pivot.tsx, packages/office-ui-fabric-react/src/components/Pivot/PivotItem.Props.ts
Supports passing in a custom renderer for pivot links. For example, to show additional annotations
=> Pivot: support custom rendering of pivot links

packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.scss
=> Fixed breadcrumb overflow bg on hover

common/changes/dialog-ariaempty_2017-02-28-07-59.json, packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx, packages/office-ui-fabric-react/src/components/Panel/Panel.tsx
don't define aria-* attributes if values are not available.
(optional)
=> Dialog: Empty aria attribute fixes

common/changes/791_CommandBarHCShift_2017-03-01-22-42.json, common/changes/791_CommandBarHCShift_2017-03-02-18-40.json, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.scss
=> #791 Fixes command bar button layout shifting on hover in HighContrast mode

packages/office-ui-fabric-react/src/components/TextField/TextField.tsx
Fix _onInputChange handler in TextField.tsx to call this._adjustInputHeight rather than just refer to it.
(optional)
=> Fix "autoAdjustHeight not working"

apps/fabric-examples/tsconfig.json, apps/fabric-website/tsconfig.json, apps/todo-app/tsconfig.json, packages/example-app-base/tsconfig.json, packages/office-ui-fabric-react/tsconfig.json, packages/utilities/tsconfig.json
This fixes the TypeScript build perf issue.
=> Removing no-emit-on-error.

common/changes/base-button-mix-rootProps_2017-03-08-18-39.json, packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx
=> Mixed rootProps with props

packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/PeoplePickerItems/PickerItemsDefault.scss, packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.scss
Changed the resting background of people back to white, updated the margin.
(optional)
=> Fixed grey color in people items, and added margin.

common/changes/leddie24-commanbar-disabled-aria_2017-03-09-00-38.json, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.tsx
CommandBar: Set aria-disabled="true" for disabled menu items
=> CommandBar: Set aria-disabled='true' for Disabled Menu Items 

common/changes/1084_ChoiceGroupAriaDisabled_2017-03-09-20-37.json, packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.tsx
ChoiceGroup: Adds aria-disabled attribute to disabled label and field
ChoiceGroup
=> #1084 Adds aria-disabled attribute to disabled label and field

common/changes/1080_DropDownAriaDisabled_2017-03-10-00-36.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx
=> #1083 -- Sets aria-disabled attribute for disabled DropDown component

common/changes/1183_PivotUnderline_2017-03-10-00-26.json, packages/office-ui-fabric-react/src/components/Pivot/Pivot.scss
Fixes Pivot underline not visible in High Contrast mode
Pivot
=> #1183 -- Fixes Pivot underline not visible in High Contrast mode

apps/fabric-examples/src/AppDefinition.tsx, apps/fabric-website/src/components/ColorTable/ColorTable.module.scss, apps/fabric-website/src/components/ColorTable/ColorTable.tsx, common/changes/general-style-fixes_2017-03-15-18-46.json, packages/office-ui-fabric-react/src/components/Button/BaseButton.scss, packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.scss, packages/office-ui-fabric-react/src/components/TextField/TextField.scss, packages/office-ui-fabric-react/src/components/TextField/TextField.tsx
DetailsList: header buttons now use background: transparent, and have the right font styling. 
TextField and Button: ms-u-screenReaderOnly styling dependency removed, mixing in the right styles from core to remove the dependency.
=> DetailsList,TextField,Button: minor style fixes.

apps/fabric-examples/src/pages/TooltipPage/TooltipPage.tsx, apps/fabric-examples/src/pages/TooltipPage/examples/Tooltip.Basic.Example.tsx, common/changes/master_2017-03-22-15-55.json, packages/office-ui-fabric-react/src/components/Tooltip/TooltipHost.Props.ts, packages/office-ui-fabric-react/src/components/Tooltip/TooltipHost.tsx
Updated TooltipHost, fixed improperly typed CalloutProps and mixed them into Tooltip properly
Verify that Callout props can be passed into the Tooltip Host and are properly mixed into the callout.
=> Fixed CalloutProps in TooltipHost

common/changes/callout-scroll-to-close-false_2017-03-23-15-47.json, packages/office-ui-fabric-react/src/components/Callout/Callout.Props.ts, packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx
Added isClosedOnScroll param that can be set to false
=> Added isClosedOnScroll param that can be set to false

package.json
Package.json scripts update to ensure we're using local rush for building and such.
=> Fixing package.json scripts.

common/changes/callout-scroll-to-close-false_2017-03-23-15-47.json, packages/office-ui-fabric-react/src/components/Callout/Callout.Props.ts, packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx
Update callout prop to preventDismissOnScroll
=> Updated callout prop to be exception rather than rule

common/changes/update-textfield-validation_2017-03-23-00-58.json, packages/office-ui-fabric-react/src/components/TextField/TextField.Props.ts, packages/office-ui-fabric-react/src/components/TextField/examples/TextField.ErrorMessage.Example.tsx
I fixed the documentation so it is more obvious that you can directly set errorMessage (fixed comments and added an example).
=> TextField: Update documentation, fix promise revalidation

common/changes/documentcardactivity-persona_2017-03-27-20-23.json, packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardActivity.tsx
=> Documentcardactivity persona

common/changes/fix-personaconst_2017-03-29-21-36.json, packages/office-ui-fabric-react/src/components/Persona/PersonaConsts.ts
=> PersonaConsts style import is now AMD compliant

ghdocs/BESTPRACTICES.md
Add requirement for explicit return types for methods declared in `.Props.ts` interfaces.
=> Best Practices: Add requirement for explicit return types for methods declared in `.Props.ts` interfaces.

common/changes/update-list-role_2017-03-27-10-22.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx, packages/office-ui-fabric-react/src/components/List/List.tsx
I added an undefined check for the role setting in List and set it to null explicitly for DetailsList, since it's following the grid pattern.
=> List, DetailsList: Update aria role

common/changes/tooltip-longtip_2017-04-03-21-15.json, packages/office-ui-fabric-react/src/components/Tooltip/Tooltip.scss
=> ToolTip - Fix for tooltip truncated in caseof long text that is not space separated

common/changes/joschect-base-pickerfixes_2017-04-05-03-13.json, packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx, packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx
Made several fixes to the base picker. It now correctly selects items, focus them correctly, and no long has an incorrectly implemented componentWillReceiveProps function.
(optional)
=> BasePicker: Several fixes to selection annd focus

common/changes/progressIndicator-a11y_2017-04-04-08-03.json, packages/office-ui-fabric-react/src/components/ProgressIndicator/ProgressIndicator.Props.ts, packages/office-ui-fabric-react/src/components/ProgressIndicator/ProgressIndicator.tsx
Adding option to pass aria-valuetext for progressbar role. https://www.w3.org/TR/wai-aria/roles#progressbar
(optional)
=> ProgressIndicator: Support for aria-valuetext

common/changes/users-cschleid-demo2_2017-03-29-00-28.json, packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx
=> GroupedList: Pass props to nested group

common/changes/fix-warn_2017-04-05-18-27.json, packages/utilities/src/warn.ts
Clarifying missing typings in file.
=> Fixing warn.ts typings

common/changes/fix-npmstart_2017-04-06-17-25.json, packages/office-ui-fabric-react/src/common/VisualTest.ts, packages/office-ui-fabric-react/visualtestindex.html
Fixed npm start by moving visual test page from index.html to visualtestindex.html
(optional)
=> NpmStart: Fixed npm start by moving visual test page from index.html to visualtestindex.html

common/changes/master_2017-04-05-22-09.json, packages/office-ui-fabric-react/src/components/MessageBar/MessageBar.scss
Adds borders to MessageBox Component in HighContrast Mode
MessageBox
=> MessageBar: Adds borders in high contrast mode

packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx
Menu items now specified as role="menu"
DropDown
=> #1449 -- Menu items now specified as role="menu"

common/changes/facepile-button-size_2017-04-11-17-43.json, packages/office-ui-fabric-react/src/components/Facepile/Facepile.scss, packages/office-ui-fabric-react/src/components/Persona/Persona.scss
Firefox requires explicit height/width to render persona button properly. Also extrasmall initials size was incorrect.
=> Updated facepile button to fix firefox bug

packages/office-ui-fabric-react/src/components/Facepile/Facepile.scss
Fixes weird extra padding in FireFox
FacePile: AddButton
(optional)
=> #1465 -- FacePile: Fixes unique inner padding for addButton in FF

common/changes/1486_DetailList_ButtonClipped_2017-04-11-21-44.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.scss
DetailsList: Fixes clipped button inside Details List
See screen shot
Details List buttons
=> #1486 -- DetailsList: Fixes clipped button inside Details List

common/changes/textfield-fix-icon-positioning_2017-04-11-21-23.json, packages/office-ui-fabric-react/src/components/TextField/TextField.scss, packages/office-ui-fabric-react/src/components/TextField/TextField.tsx, packages/office-ui-fabric-react/src/components/TextField/examples/TextField.Basic.Example.tsx
Add CSS to properly position a provided icon within a TextField
(optional)
=> Textfield: fix icon positioning

common/changes/master_2017-04-11-22-55.json
Submitting rush change for PR: #1478 
(That was a fix for #1448 )
(optional)
=> Rush Change for ChoiceGroup CSS fix

common/changes/commandbar-support-links_2017-04-11-21-37.json, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.tsx, packages/office-ui-fabric-react/src/components/CommandBar/examples/data.ts
=> Added support for href in commandbar

common/changes/master_2017-04-13-16-48.json, packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx
=> Fixed focuszone to stop eating spacebar presses in input fields

common/changes/users-navneetg-fixcalloutdefaultgap_2017-04-19-23-18.json, packages/office-ui-fabric-react/src/components/Callout/Callout.Props.ts, packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx, packages/office-ui-fabric-react/src/components/Callout/examples/Callout.Directional.Example.tsx, packages/office-ui-fabric-react/src/components/Tooltip/Tooltip.tsx
- [] Includes tests
Updating default gapSpace for Callout and Tooltip to 0
=> Updating default gapSpace for callout and tooltip to 0

common/changes/message-bar-mouse-events_2017-04-24-16-03.json, packages/office-ui-fabric-react/src/components/MessageBar/MessageBar.scss
=> Message bar mouse events

packages/office-ui-fabric-react/src/components/Tooltip/TooltipHost.tsx
=> Fix bad merge

apps/fabric-website/index.html, apps/fabric-website/src/components/DONavigation/DONavigation.tsx, apps/fabric-website/src/root.tsx, apps/fabric-website/webpack.site.config.js
=> Updating website to create bundles named by the version.

packages/office-ui-fabric-react/src/components/TextField/examples/TextField.Basic.Example.tsx
=> Updated textfield examples fixes #1648

apps/fabric-website/package.json, apps/todo-app/package.json, common/npm-shrinkwrap.json, common/temp_modules/rush-example-app-base/package.json, common/temp_modules/rush-example-component/package.json, common/temp_modules/rush-fabric-website/package.json, common/temp_modules/rush-office-ui-fabric-react/package.json, common/temp_modules/rush-styling/package.json, common/temp_modules/rush-todo-app/package.json, common/temp_modules/rush-utilities/package.json, packages/example-app-base/package.json, packages/example-component/package.json, packages/office-ui-fabric-react/package.json, packages/styling/package.json, packages/utilities/package.json
Issue tracked here:
https://github.com/Microsoft/TypeScript/issues/15546
=> Backing out typescript bump, reverting to 2.2.2, due to breaking changes

common/changes/pivot-padding-override_2017-05-03-22-04.json, packages/office-ui-fabric-react/src/components/Pivot/Pivot.scss
=> Pivot: increased specificty to fix button styles overriding pivot styles

packages/styling/src/examples/AnimationTile.tsx
minor tweak that doesn't need to be published, for addressing a lint error when updating to the new tslint.
=> Fixing lint error.

common/changes/minimonthfixes_2017-05-08-22-52.json, packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx
- [x ] New feature, bugfix, or enhancement
Minor miss in my last change, forgot to change today to todaysDate.
(optional)
=> Date picker: Use todaysDate instead of today in _getWeeks

apps/fabric-website/webpack.site.config.js
=> Changing the chunk names so the file versions are easily identifiable in a list

apps/fabric-website/index.html
Updates dogfood links so they dont cache on a daily basis.
Dogfood servers.
=> Updating the dogfood links on the fabric website to update instantly as apposed to daily.

common/changes/datepicker-disabled-support_2017-05-15-10-45.json, packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.Props.ts, packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx
Add `disabled` prop support to `DatePicker`.
Can't create change file:
```sh
MacBook-Pro-Igor:office-ui-fabric-react ibook$ rush change
Rush Multi-Package Build Tool 2.5.0 - http://aka.ms/rush
Found configuration in /Users/ibook/Projects/SJ/office-ui-fabric-react/rush.json
No change file is needed.
```
=> DatePicker: added 'disabled' prop support

apps/fabric-website/package.json
=> Version patch test

common/changes/button-aria-expanded_2017-05-16-18-38.json, packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx
Added aria-expanded if button has props.menuProps. Changes from false to true when opened
=> Button: Added aria-expanded if props.menuProps

common/changes/787_SearchBoxOutlineHC_2017-05-17-20-15.json, packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.scss
SearchBox: Adds outlines to SearchBox in HC modes
SearchBox
=> #787 - Adds outlines to SearchBox in HC modes

packages/office-ui-fabric-react/tslint.json, packages/styling/src/styles/AnimationStyles.ts, packages/styling/src/styles/DefaultFontStyles.ts, packages/styling/src/utilities/mergeStyleSets.ts, packages/utilities/src/dom.ts, tslint.json
=> fixing build break with lint errors.

common/changes/searchbox-high-contrast_2017-05-18-16-34.json, packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.scss
=> Searchbox: Updated border styles to better support high contrast mode

packages/utilities/api/utilities.api.ts, packages/utilities/config/api-extractor.json, packages/utilities/src/Async.ts, packages/utilities/src/BaseComponent.ts, packages/utilities/src/Customizer.tsx, packages/utilities/src/DelayedRender.tsx, packages/utilities/src/autobind.ts, packages/utilities/src/dom.ts, packages/utilities/src/focus.ts, packages/utilities/src/hoist.ts, packages/utilities/src/object.ts, packages/utilities/src/overflow.ts, packages/utilities/src/properties.ts, packages/utilities/src/warn.ts
This turns on api lint for the utilities package.
Now when you build, you'll see the changes to the api baseline in the /api folder. 
I'm checking in as-is. There are a number of apis that are not commented or that the tool is generating warnings from. These should be fixed, but let's get this on now so that we can catch things like an api being removed or parameters being change.d
=> Adding api lint for the utilities package.

common/npm-shrinkwrap.json, common/package.json, common/temp_modules/rush-example-app-base/package.json, common/temp_modules/rush-example-component/package.json, common/temp_modules/rush-fabric-website/package.json, common/temp_modules/rush-office-ui-fabric-react/package.json, common/temp_modules/rush-ssr-tests/package.json, common/temp_modules/rush-test-bundle-button/package.json, common/temp_modules/rush-todo-app/package.json, common/temp_modules/rush-utilities/package.json
=> Updating shrinkwrap.

common/changes/@uifabric/styling/fixes_2017-05-30-23-57.json, common/changes/@uifabric/styling/fixes_2017-05-31-00-44.json, common/changes/office-ui-fabric-react/fixes_2017-05-30-23-57.json, common/changes/office-ui-fabric-react/fixes_2017-05-31-00-44.json, packages/office-ui-fabric-react/src/components/pickers/BasePicker.Props.ts, packages/styling/src/classNames/IconClassNames.ts, packages/styling/src/examples/IconTile/IconTile.tsx, packages/styling/src/glamorExports.ts, packages/styling/src/index.ts
This addresses the typescript typings break in picker. :(
=> Reverts the accidentally added prop from the picker PR.

apps/component-demo/package.json, apps/test-bundle-button/package.json, common/config/rush/npm-shrinkwrap.json, common/config/rush/pinned-versions.json
While the project was all building with ts 2.2.2, making sure all things are still locked to 2.2.2.
=> Locking to ts 2.2.2.

common/changes/@uifabric/utilities/ssr_2017-06-01-05-06.json, packages/utilities/src/dom.test.ts, packages/utilities/src/dom.ts, packages/utilities/src/language.ts
The utilities `getWindow` and `getDocument` now check types on the corresponding objects before accessing them.
=> Updating getWindow/getDocument to be ssr happy.

common/changes/office-ui-fabric-react/panel-fix-large-size_2017-06-01-02-48.json, packages/office-ui-fabric-react/src/components/Panel/Panel.tsx
Fix a logic error in applying styles to the Panel when the props call for a `large` Panel
(optional)
=> Panel: fix large size

common/changes/office-ui-fabric-react/miwhea-dragdrophelper-tslint_2017-06-02-20-06.json, packages/office-ui-fabric-react/src/utilities/dragdrop/DragDropHelper.tsx
Fixes two TSLint warnings.
No functional changes, so no testing required.
=> DragDropHelper: Fix TSLint warnings

common/changes/@uifabric/example-app-base/create-app-params_2017-06-05-23-32.json, common/changes/@uifabric/utilities/create-app-params_2017-06-05-23-32.json, packages/example-app-base/src/utilities/createApp.tsx
Allow the header links and name to be passed in as optional params to createApp
=> ExampleApp: Allow the header links and name to be passed in as optional params to createApp

common/changes/@uifabric/styling/createtheme_2017-06-06-01-00.json, packages/styling/src/utilities/index.ts
Adding createTheme to exports, for scenarios where you want to create a customized theme.
=> Adding createTheme to styling exports.

common/changes/@uifabric/example-app-base/toggle-cursor-pointer_2017-06-09-21-07.json, common/changes/@uifabric/fabric-website/toggle-cursor-pointer_2017-06-09-21-07.json, common/changes/@uifabric/styling/toggle-cursor-pointer_2017-06-09-21-07.json, common/changes/@uifabric/utilities/toggle-cursor-pointer_2017-06-09-21-07.json, common/changes/office-ui-fabric-react/toggle-cursor-pointer_2017-06-09-21-07.json, packages/office-ui-fabric-react/src/components/Toggle/Toggle.styles.ts
I think `cursor: pointer` on Toggle got lost in the move to `glamor`. Added it back in.
=> Toggle: add 'cursor: pointer'

apps/component-demo/package.json, apps/fabric-website/package.json, apps/todo-app/package.json, common/changes/@uifabric/example-app-base/font-fix_2017-06-14-00-05.json, common/changes/@uifabric/fabric-website/font-fix_2017-06-14-00-05.json, common/changes/@uifabric/styling/font-fix_2017-06-14-00-05.json, common/changes/office-ui-fabric-react/font-fix_2017-06-14-00-05.json, common/config/rush/npm-shrinkwrap.json, packages/example-app-base/package.json, packages/office-ui-fabric-react/package.json, packages/styling/src/styles/DefaultFontStyles.ts, packages/styling/src/utilities/theme.ts
This change brings in core 7.1.2, which adds "Segoe UI" to the font fallbacks.
Also extending `FabricConfig` support to allow for both `fontBaseUrl` and `theme` to be defined, which will be used at bundle load time for overriding the default settings.
=> Updating the fonts to use Segoe UI, also to be override-able on load.

common/changes/office-ui-fabric-react/dropdown-doc-updates_2017-06-09-17-21.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.Props.ts, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx, packages/office-ui-fabric-react/src/components/Dropdown/DropdownPage.tsx, packages/office-ui-fabric-react/src/components/Dropdown/examples/Dropdown.Basic.Example.scss, packages/office-ui-fabric-react/src/components/Dropdown/examples/Dropdown.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/Dropdown/examples/Dropdown.Custom.Example.tsx
=> Dropdown: Fixed onRenderPlaceHolder, added data prop to items, updated docs

common/changes/@uifabric/styling/styling-no-implicit-any_2017-06-16-00-30.json, packages/styling/src/classNames/ColorClassNames.ts, packages/styling/src/classNames/IconClassNames.ts, packages/styling/src/examples/AnimationTile/AnimationTile.tsx, packages/styling/src/examples/ColorPage/ColorPage.tsx, packages/styling/src/examples/FontPage/FontPage.tsx, packages/styling/src/examples/IconTile/IconTile.tsx, packages/styling/src/glamorExports.ts, packages/styling/src/styles/DefaultFontStyles.ts, packages/styling/src/utilities/buildClassMap.ts, packages/styling/src/utilities/mergeStyleSets.ts, packages/styling/src/utilities/theme.ts, packages/styling/tsconfig.json
Enable the "no-implicit-any" typescript compiler setting in the styling package.
=> Enable No Implicit Any in the styling package

common/changes/office-ui-fabric-react/breadcrumb-bug-fix_2017-06-21-16-20.json, packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.tsx
=> Breadcrumb bug fix

common/changes/office-ui-fabric-react/toggle-fix-form-submit_2017-06-21-18-54.json, packages/office-ui-fabric-react/src/components/Toggle/Toggle.test.tsx, packages/office-ui-fabric-react/src/components/Toggle/Toggle.tsx
=> Toggle fix form submit

common/changes/office-ui-fabric-react/fixes_2017-06-23-03-41.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.tsx, packages/office-ui-fabric-react/src/components/Image/Image.tsx
Spotted some regressions in DetailsRow from the PR that merged a few hours ago.
=> DetailsRow: Fixing some issues with the previous publish.

common/changes/office-ui-fabric-react/persona-fix_2017-06-26-23-05.json, packages/office-ui-fabric-react/src/components/Persona/Persona.tsx
Addressed a persona bug recently introduced which is causing regressions in the sizing logic.
=> Persona fix: cover is not being respected.

packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.tsx, packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.Props.ts, packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx, packages/utilities/api/utilities.api.ts, packages/utilities/src/focus.ts
On the details list left arrow enters focus onto the elements in the row but right arrow does not exit focus back to the row. This change fixes that.
The details list
=> Focus Utility: Allow focus parent

common/changes/office-ui-fabric-react/underlined-textfield-error_2017-06-19-15-55.json, packages/office-ui-fabric-react/src/components/TextField/TextField.scss, packages/office-ui-fabric-react/src/components/TextField/TextField.tsx, packages/office-ui-fabric-react/src/components/TextField/examples/TextField.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/TextField/examples/TextField.ErrorMessage.Example.tsx
=> Textfield: Fixed layout of underlined textfield with error

common/changes/@uifabric/utilities/rtl-fix_2017-06-28-23-42.json, packages/utilities/src/rtl.test.ts, packages/utilities/src/rtl.ts
Simplifying the rtl helpers to allow the caller to manage persistence and to remove the risk of using localstorage at the wrong time.
=> Removing localstorage persistence from rtl helpers.

common/changes/office-ui-fabric-react/FixDetailsListCustomColumnsExample_2017-06-29-19-29.json, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.CustomColumns.Example.tsx
Add 'event' as the first param for onColumnClick handler to match the param order.
(optional)
=> Fix details list custom columns example

common/changes/office-ui-fabric-react/cschleiden-patch-1_2017-06-29-18-03.json, packages/office-ui-fabric-react/src/components/Button/DefaultButton/DefaultButton.styles.ts
=> Button: Revert font-weight change to semi-bold

common/changes/office-ui-fabric-react/dialog-allow-blocking-close-button_2017-06-29-22-30.json, packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx
Allow `dialogContentProps` to override all defaults inferred from `IDialogProps`.
(optional)
=> Dialog: allow blocking close button

common/changes/office-ui-fabric-react/fix-details-row-cell-size_2017-07-05-18-22.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.scss
Make the details row cells stretch to the total height of the row using flexbox.
Details row cells
=> Fix details row cell size

common/changes/office-ui-fabric-react/amd-import_2017-07-08-05-35.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.tsx
=> Amd import

package.json, rush.json
This should fix windows issues building some of the projects.
=> Update rush to 3.0.11.

common/changes/office-ui-fabric-react/master_2017-07-17-17-45.json, packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
- Removes `onBlur` to fix `onSuggestionClick` prevention
- Adds `onBlur` functionality to `dismissSuggestions`
=> Fixing onBlur prevents onSuggestionClick (with change file)

packages/office-ui-fabric-react/src/components/Modal/ModalPage.tsx
This fixes the Dialogue link from the Modal component documentation page.
=> Fix link to dialog

common/changes/office-ui-fabric-react/textfield-disabled_2017-07-19-16-10.json, packages/office-ui-fabric-react/src/components/TextField/TextField.scss
=> Textfield disabled

common/changes/office-ui-fabric-react/2017-07-21-14-26.json, packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx, packages/office-ui-fabric-react/src/components/Button/Button.test.tsx
=> Fix application of aria properties on BaseButton. #2270

common/changes/office-ui-fabric-react/contextual-button-styles_2017-07-21-18-33.json, packages/office-ui-fabric-react/src/components/Button/BaseButton.classNames.ts, packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx, packages/office-ui-fabric-react/src/components/Button/Button.Props.ts, packages/office-ui-fabric-react/src/components/Button/CommandButton/CommandButton.styles.ts, packages/office-ui-fabric-react/src/components/Button/DefaultButton/DefaultButton.styles.ts, packages/office-ui-fabric-react/src/components/Button/IconButton/IconButton.styles.ts, packages/office-ui-fabric-react/src/components/Button/PrimaryButton/PrimaryButton.styles.ts, packages/office-ui-fabric-react/src/components/Button/SplitButton/SplitButton.Props.ts, packages/office-ui-fabric-react/src/components/Button/SplitButton/SplitButton.styles.ts
=> Button: Support expanded styles for contextual buttons

scripts/updateReleaseNotes.js
=> Changed realsenotes prerelease to false

common/changes/office-ui-fabric-react/checkbox-label-size_2017-07-24-20-52.json, packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.styles.ts
=> Checkbox label size

common/changes/@uifabric/styling/icon-update-2.38_2017-07-26-18-00.json, common/changes/office-ui-fabric-react/icon-update-2.38_2017-07-26-18-00.json, packages/office-ui-fabric-react/src/components/Icon/IconName.ts, packages/styling/src/styles/DefaultFontStyles.ts, packages/styling/src/styles/IconCodes.ts
Adds the following icons to Fabric React
FilterSolid
GridViewSmall
GridViewMedium
GridViewLarge
ThisPc
MailUndelivered
MailTentative
MailTentativeMirrored
MailReminder
IRMReply
IRMReplyMirrored
IRMForward
IRMForwardMirrored
ReceiptUndelivered
ReceiptTentative
ReceiptTentativeMirrored
Inbox
VoicemailRM
EventAccepted
EventTentative
EventTentativeMirrored
EventDeclined
(optional)
=> Icon update 2.38

common/changes/office-ui-fabric-react/oufr-strict-null3_2017-07-24-21-40.json, packages/office-ui-fabric-react/src/components/ActivityItem/ActivityItem.tsx, packages/office-ui-fabric-react/src/components/Button/BaseButton.classNames.ts, packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx, packages/office-ui-fabric-react/src/components/Calendar/Calendar.Props.ts, packages/office-ui-fabric-react/src/components/Calendar/Calendar.test.tsx, packages/office-ui-fabric-react/src/components/Calendar/Calendar.tsx, packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx, packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.tsx, packages/office-ui-fabric-react/src/components/ColorPicker/ColorRectangle.tsx, packages/office-ui-fabric-react/src/components/ColorPicker/ColorSlider.tsx, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.test.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Checkmarks.Example.tsx, packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.Props.ts, packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.tsx, packages/office-ui-fabric-react/src/components/MessageBar/MessageBar.Props.ts, packages/office-ui-fabric-react/src/components/MessageBar/MessageBar.tsx, packages/office-ui-fabric-react/src/components/ResizeGroup/ResizeGroup.test.tsx, packages/office-ui-fabric-react/src/components/ResizeGroup/ResizeGroup.tsx, packages/office-ui-fabric-react/src/components/SwatchColorPicker/examples/SwatchColorPicker.Basic.Example.tsx, packages/office-ui-fabric-react/src/utilities/decorators/withResponsiveMode.tsx, packages/office-ui-fabric-react/src/utilities/positioning.ts
More typecasts to get us on the path towards enabling "strictNullChecks". There are still ~150 more errors to fix after this PR. 
(optional)
=> More strictNullCheck fixes for office-ui-fabric-react

common/changes/office-ui-fabric-react/checkbox-label-align_2017-07-27-22-02.json, packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.styles.ts
Added text-align: left style to Checkbox. Checkbox renders a button which defaults to centered text
=> Checkbox label align

common/changes/@uifabric/styling/phkuo-invertedTheme_2017-07-24-21-01.json, packages/styling/src/interfaces/ITheme.ts, packages/styling/src/interfaces/IThemeSettings.ts, packages/styling/src/styles/theme.ts
Theming: add settings to the interface so we can track things like whether the current theme is inverted
(optional)
=> Theming: add settings to the interface

common/changes/office-ui-fabric-react/message-bar-updates_2017-07-28-19-04.json, packages/office-ui-fabric-react/src/components/MessageBar/MessageBar.scss, packages/office-ui-fabric-react/src/components/MessageBar/MessageBar.tsx
These changes don't affect the look of the current component, but it will affect it once it hits our website. Here's how the page should look after these changes go out
=> Message bar updates

common/changes/office-ui-fabric-react/overflowSet-updates_2017-07-28-17-25.json, packages/office-ui-fabric-react/src/components/OverflowSet/OverflowSet.Props.ts, packages/office-ui-fabric-react/src/components/OverflowSet/OverflowSet.scss, packages/office-ui-fabric-react/src/components/OverflowSet/OverflowSet.tsx
These are some of the overflowSet updates that I've needed for the upcoming command bar. Seems logical to pull them in sooner than later so that we don't get too far out of sync. 
(optional)
=> Overflow set updates

common/changes/office-ui-fabric-react/master_2017-08-01-11-35.json, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx
Fixes ContextualMenu issue where icons are not displayed.
=> Fixing ContextualMenu icon issue #2336

common/changes/office-ui-fabric-react/datepicker-icon-size_2017-08-02-16-51.json, packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.scss
=> Datepicker icon size

common/changes/office-ui-fabric-react/elcraig-nav_2017-08-09-22-35.json, packages/office-ui-fabric-react/src/components/Nav/Nav.tsx
Fixes sublink padding bug introduced by previous change.
=> Nav: fix bug with sublink padding

common/changes/@uifabric/styling/firefox-focus-style_2017-08-11-16-42.json, packages/styling/src/styles/getFocusStyle.ts
=> getFocusStyle: Add -moz-focus-inner to fix outline bug

.vscode/settings.json, apps/fabric-website/package.json, apps/fabric-website/src/root.tsx, common/config/rush/npm-shrinkwrap.json
Just some minor misc fixes, want to ensure the build still passes.
* Updated shrinkwrap
* Updated vscode settings to reduce cpu usage (at least on macs)
* Fixed a package dependency in website
=> Fixing shrinkwrap, vscode settings, etc.

apps/fabric-website/src/components/App/AppState.tsx, apps/fabric-website/src/pages/Components/TooltipComponentPage.tsx
Adding the tooltip to the website
=> Added tooltip to website

common/changes/@uifabric/experiments/experiments-remove-unused-variables_2017-08-23-00-57.json, packages/experiments/src/components/CommandBar/examples/CommandBar.Basic.Example.tsx, packages/experiments/src/components/Tile/Tile.Props.ts, packages/experiments/src/components/Tile/Tile.tsx, packages/experiments/src/components/Tile/TilePage.tsx, packages/experiments/src/components/Tile/examples/Tile.Document.Example.tsx, packages/experiments/src/components/Tile/examples/Tile.Media.Example.tsx, packages/experiments/src/components/TilesList/TilesList.tsx, packages/experiments/src/components/TilesList/examples/ExampleHelpers.tsx, packages/experiments/src/components/TilesList/examples/TilesList.Basic.Example.tsx, packages/experiments/src/components/TilesList/examples/TilesList.Document.Example.tsx, packages/experiments/src/components/TilesList/examples/TilesList.Media.Example.tsx, packages/experiments/tslint.json
Removed suppression of tslint unused variables rule from Experiments package and removed unused variables to pass tslint
=> Removed unused variables in experiments pkg to pass tslint

common/changes/@uifabric/experiments/experiments-max-line-length_2017-08-23-00-37.json, packages/experiments/src/components/CommandBar/CommandBar.Props.ts, packages/experiments/src/components/CommandBar/CommandBarPage.tsx, packages/experiments/src/components/TilesList/TilesListPage.tsx, packages/experiments/src/demo/GettingStartedPage.tsx, packages/experiments/tslint.json
Removed suppression of tslint max line length rule from Experiments package, and broke up large lines or inserted tslint:disable comments to pass tslint
=> Break up long lines or disable max line length in Experiments pkg to pass tslint

common/changes/@uifabric/experiments/experiments-self-close_2017-08-23-00-41.json, packages/experiments/src/components/CommandBar/CommandBarPage.tsx, packages/experiments/src/components/TilesList/TilesListPage.tsx, packages/experiments/tslint.json
Removed suppression of tslint self-close rule from Experiments package and self-closed all empty elements to pass tslint
=> Self-closed empty elements in experiments pkg to pass tslint

common/changes/@uifabric/experiments/experiments-typedef_2017-08-23-00-24.json, packages/experiments/src/components/CommandBar/CommandBar.tsx, packages/experiments/src/components/CommandBar/CommandBarPage.tsx, packages/experiments/src/components/CommandBar/CommandBarPage.visualtest.tsx, packages/experiments/src/components/CommandBar/examples/CommandBar.Basic.Example.tsx, packages/experiments/src/components/Tile/Tile.tsx, packages/experiments/src/components/Tile/TilePage.tsx, packages/experiments/src/components/Tile/examples/Tile.Document.Example.tsx, packages/experiments/src/components/Tile/examples/Tile.Media.Example.tsx, packages/experiments/src/components/TilesList/TilesList.tsx, packages/experiments/src/components/TilesList/TilesListPage.tsx, packages/experiments/src/components/TilesList/examples/ExampleHelpers.tsx, packages/experiments/src/components/TilesList/examples/TilesList.Basic.Example.tsx, packages/experiments/src/components/TilesList/examples/TilesList.Document.Example.tsx, packages/experiments/src/components/TilesList/examples/TilesList.Media.Example.tsx, packages/experiments/src/demo/GettingStartedPage.tsx, packages/experiments/src/demo/index.tsx, packages/experiments/tslint.json
Removed suppression of tslint typedef rule from Experiments package and added missing typedefs to call signatures to pass tslint
=> Added missing typedefs to call signatures in experiments pkg to pass tslint

common/changes/@uifabric/utilities/array-fix_2017-08-23-23-20.json, packages/utilities/src/array.ts
Per PR feedback, reverting a change to createArray.
=> createArray: undo of optional for callback.

packages/experiments/src/components/CommandBar/CommandBar.tsx, packages/office-ui-fabric-react-tslint/tslint.json, packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx, packages/office-ui-fabric-react/src/components/Calendar/CalendarMonth.tsx, packages/office-ui-fabric-react/src/components/CommandBar/examples/CommandBar.Customization.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.NavigatingFocus.Example.tsx, packages/office-ui-fabric-react/src/components/Icon/Icon.tsx, packages/office-ui-fabric-react/src/components/Overlay/examples/Overlay.Light.Example.tsx, packages/office-ui-fabric-react/src/components/Pivot/Pivot.tsx, packages/office-ui-fabric-react/src/components/ResizeGroup/examples/ResizeGroup.OverflowSet.Example.tsx, packages/office-ui-fabric-react/src/components/SpinButton/examples/SpinButton.Stateful.Example.tsx, packages/office-ui-fabric-react/src/components/SwatchColorPicker/SwatchColorPicker.tsx, packages/office-ui-fabric-react/src/components/Tooltip/TooltipHost.tsx, packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/PeoplePickerItems/SelectedItemWithMenu.tsx, packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/examples/PeoplePicker.Types.Example.tsx, packages/office-ui-fabric-react/src/components/pickers/Suggestions/SuggestionsController.ts
=> Private methods without underscores should break the build

packages/office-ui-fabric-react-tslint/tslint.json
Disabled jsx-no-multiline-js in Fabric tslint.json per discussion with David
=> Disabled jsx-no-multiline-js in Fabric tslint.json

common/changes/@uifabric/experiments/experiments-jsx-ban-props_2017-08-24-01-54.json, packages/experiments/src/components/TilesList/TilesList.tsx, packages/experiments/src/components/TilesList/examples/TilesList.Basic.Example.tsx, packages/experiments/src/components/TilesList/examples/TilesList.Document.Example.tsx, packages/experiments/src/components/TilesList/examples/TilesList.Media.Example.tsx, packages/experiments/tslint.json, packages/office-ui-fabric-react-tslint/tslint.json
Inserted disable jsx-ban-props lines to experiments pkg to pass tslint
=> Inserted disable jsx-ban-props lines to experiments pkg to pass tslint

common/changes/@uifabric/utilities/chrisgo-find-to-utilities_2017-08-24-17-19.json, packages/utilities/src/array.test.ts, packages/utilities/src/array.ts
Adds a find function to the array utilities. Modeled after ES6 [array.prototype.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)
=> Utilities: Add find function for arrays

packages/experiments/src/components/CommandBar/CommandBar.tsx, packages/experiments/src/components/CommandBar/CommandBarPage.tsx, packages/experiments/src/components/CommandBar/CommandBarPage.visualtest.tsx, packages/experiments/src/components/CommandBar/examples/CommandBar.Basic.Example.tsx, packages/experiments/src/components/Tile/Tile.tsx, packages/experiments/src/components/Tile/examples/Tile.Document.Example.tsx, packages/experiments/src/components/Tile/examples/Tile.Media.Example.tsx, packages/experiments/src/components/TilesList/TilesList.tsx, packages/experiments/src/components/TilesList/examples/TilesList.Document.Example.tsx, packages/experiments/src/components/TilesList/examples/TilesList.Media.Example.tsx, packages/experiments/src/components/signals/Signals.tsx, packages/experiments/src/demo/AppDefinition.tsx, packages/experiments/src/demo/GettingStartedPage.tsx, packages/experiments/tslint.json
Re-enable tslint rule no-any and fix uses of any in experiments package
=> Re-enable tslint rule no-any and fix uses of any in experiments package

common/changes/office-ui-fabric-react/pickers-inputprops-bugfix_2017-08-25-19-07.json, packages/office-ui-fabric-react/src/components/pickers/BasePicker.Props.ts
=> Pickers inputprops bugfix

common/changes/@uifabric/styling/theming-add-accentcolor_2017-08-28-23-41.json, packages/styling/src/interfaces/IPalette.ts, packages/styling/src/styles/DefaultPalette.ts, packages/styling/src/styles/theme.ts
Add support for an accent color
(optional)
=> Theming/styling: add accent color slot

common/changes/@uifabric/experiments/tile-selection_2017-08-28-23-06.json, packages/experiments/src/components/Tile/Tile.Props.ts, packages/experiments/src/components/Tile/Tile.tsx
This change fixes a minor module reference issue by the `Tile` module in Experiments.
=> Fix module references by Tile in Experiments

common/changes/@uifabric/utilities/rename-removeElement_2017-08-28-16-30.json, packages/utilities/src/array.test.ts, packages/utilities/src/array.ts
Renaming the recently added removeElement utility method to removeIndex to align with the findIndex name. 
(optional)
=> Utilities: Rename removeElement

packages/example-app-base/src/components/App/App.tsx, packages/example-app-base/src/components/ExampleCard/ExampleCard.tsx, packages/example-app-base/src/components/PropertiesTable/PropertiesTable.tsx, packages/example-app-base/src/components/PropertiesTable/PropertiesTableSet.tsx, packages/example-app-base/src/utilities/createApp.tsx, packages/example-app-base/src/utilities/data.ts, packages/example-app-base/src/utilities/debugging.ts, packages/example-app-base/tslint.json
Re-enable tslint rule 'no-any' and fix uses of `any` in example-app-base
=> Re-enable tslint rule no-any and fix uses of any in example-app-base

apps/fabric-website/index.html, apps/fabric-website/package.json, apps/fabric-website/webpack.serve.config.js, common/config/rush/npm-shrinkwrap.json
The following updates will allow us to test our local build of the website in the production environment by passing the url to any given fabric-website.js file.
=> Website development updates

apps/fabric-website/index.html, apps/fabric-website/package.json, apps/fabric-website/webpack.serve.config.js, apps/fabric-website/webpack.uhf.serve.config.js
Added a new config file for the uhf header
Update index.html with the changes
Added new script and command (npm run startuhf)
Changed the name of the file to fabric-site.js vs fabric-website.js
=> UHF header testing polish

common/changes/office-ui-fabric-react/betrue-18pxCheck_2017-08-30-17-53.json, packages/office-ui-fabric-react/src/components/Check/Check.scss
- [x ] Include a change request file using `$ npm run change`
Increased size of selection check to 18px. It was too small for proper selection.
=> Changed size of check to 18px.

apps/fabric-website/package.json, common/changes/@uifabric/fabric-website/fix-publish_2017-08-31-15-14.json, common/config/rush/npm-shrinkwrap.json
Add @types/node dependency to fabric-website
(optional)
=> Fix publish build

common/changes/@uifabric/example-app-base/example-app-base-persist_2017-08-31-16-13.json, common/config/rush/npm-shrinkwrap.json, packages/example-app-base/package.json, packages/example-app-base/src/components/Header/Header.tsx, packages/example-app-base/src/components/PropertiesTable/PropertiesTable.tsx, packages/utilities/src/rtl.ts
Persist RTL setting in example app base
=> Persist RTL setting in example-app-base

common/changes/@uifabric/styling/master_2017-08-31-16-34.json, common/changes/office-ui-fabric-react/master_2017-08-31-16-34.json, packages/office-ui-fabric-react/src/components/Icon/IconName.ts, packages/styling/src/styles/IconCodes.ts
=> Add FullWidth icon

common/changes/@uifabric/utilities/utilities_change_2017-09-01-17-22.json, packages/utilities/src/rtl.ts
Change #2691 didn't add a change file for the utilities package. This PR fixes that.
=> Add change file for RTL Utilities changes

packages/office-ui-fabric-react/src/components/DatePicker/examples/DatePicker.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.CustomColumns.Example.tsx, packages/office-ui-fabric-react/src/components/Dialog/examples/Dialog.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/Dialog/examples/Dialog.Blocking.Example.tsx, packages/office-ui-fabric-react/src/components/Dialog/examples/Dialog.LargeHeader.Example.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Click.Example.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Example.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.FocusOnCustomElement.Example.tsx, packages/office-ui-fabric-react/src/components/Modal/examples/Modal.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/Panel/examples/Panel.Custom.Example.tsx, packages/office-ui-fabric-react/src/components/Panel/examples/Panel.LargeFixed.Example.tsx, packages/office-ui-fabric-react/src/components/Pivot/examples/Pivot.OnChange.Example.tsx, packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/examples/PeoplePicker.Types.Example.tsx, packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx, packages/office-ui-fabric-react/src/components/pickers/examples/Picker.CustomResult.Example.tsx, packages/office-ui-fabric-react/src/components/pickers/examples/TagPicker.Basic.Example.tsx, packages/office-ui-fabric-react/src/utilities/decorators/withContainsFocus.tsx, packages/office-ui-fabric-react/tslint.json
Re-enable 'jsx-no-bind' tslint rule and implement autobind where needed
=> Re-enabled 'jsx-no-bind' tslint rule in Fabric pkg

packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx, packages/office-ui-fabric-react/src/components/Calendar/Calendar.tsx, packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx, packages/office-ui-fabric-react/src/components/Calendar/examples/Calendar.Inline.Example.tsx, packages/office-ui-fabric-react/src/components/Panel/Panel.tsx, packages/office-ui-fabric-react/src/utilities/dateMath/DateMath.ts, packages/office-ui-fabric-react/tslint.json
Re-enable 'triple-equals' tslint rule in Fabric pkg
=> Re-enable 'triple-equals' tslint rule in Fabric pkg

common/changes/@uifabric/example-app-base/update-example-app-base-deps_2017-09-01-18-33.json, common/config/rush/npm-shrinkwrap.json, packages/example-app-base/package.json
In order to make sure the example apps inside the fabric-react repo get the changes to make RTL flipping actually work, we need to update the shrinkwrap to get the latest version of @uifabric/utilities
=> Update shrinkwrap to get example-app-base RTL fixes

apps/fabric-website/src/data/brand-icons-monochrome.json, apps/fabric-website/src/pages/Styles/BrandIconsPage/BrandIconsPage.module.scss, apps/fabric-website/src/pages/Styles/BrandIconsPage/BrandIconsPage.tsx, common/changes/@uifabric/fabric-website/brand-icons-page_2017-09-01-22-47.json, common/changes/office-ui-fabric-react/brand-icons-page_2017-09-01-22-47.json
Updated documentation to reflect previously updated monochrome icon set. Cleaned up alignment on some rogue p tags.
(optional)
=> Brand icons page cleanup

common/changes/office-ui-fabric-react/dropdown-state_2017-09-05-17-45.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.scss
Updated dropdown state styles to match the XD specs. Refactored related code to share high contrast states.
(optional)
=> Update dropdown state styles to match XD spec

apps/fabric-website/index.html, common/changes/@uifabric/fabric-website/new-spinner-gif_2017-09-01-18-13.json
Added new spinner gif to CDN. Now referencing it. Meant to mimic our Fabric spinner component.
(optional)
=> Updated website's initial loading spinner gif to mimic the Fabric spinner component

packages/office-ui-fabric-react/src/components/Breadcrumb/BreadcrumbPage.tsx, packages/office-ui-fabric-react/src/components/Breadcrumb/BreadcrumbPage.visualtest.tsx, packages/office-ui-fabric-react/src/components/Breadcrumb/examples/Breadcrumb.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/Breadcrumb/examples/Breadcrumb.Static.Example.tsx, packages/office-ui-fabric-react/src/components/Button/Button.test.tsx, packages/office-ui-fabric-react/src/components/Button/ButtonPage.tsx, packages/office-ui-fabric-react/src/components/Button/ButtonPage.visualtest.tsx, packages/office-ui-fabric-react/src/components/Button/examples/Button.Anchor.Example.tsx, packages/office-ui-fabric-react/src/components/Button/examples/Button.Icon.Example.tsx, packages/office-ui-fabric-react/src/components/Button/examples/Button.ScreenReader.Example.tsx, packages/office-ui-fabric-react/src/components/Button/examples/Button.Swap.Example.tsx, packages/office-ui-fabric-react/src/components/Calendar/CalendarPage.tsx, packages/office-ui-fabric-react/src/components/Callout/Callout.test.tsx, packages/office-ui-fabric-react/src/components/Callout/CalloutPage.tsx, packages/office-ui-fabric-react/src/components/Callout/examples/Callout.Cover.Example.tsx, packages/office-ui-fabric-react/src/components/Callout/examples/Callout.Directional.Example.tsx, packages/office-ui-fabric-react/src/components/Checkbox/CheckboxPage.tsx, packages/office-ui-fabric-react/src/components/Checkbox/CheckboxPage.visualtest.tsx, packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroupPage.tsx, packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroupPage.visualtest.tsx, packages/office-ui-fabric-react/src/components/ColorPicker/ColorPickerPage.tsx, packages/office-ui-fabric-react/src/components/ComboBox/ComboBoxPage.tsx, packages/office-ui-fabric-react/src/components/CommandBar/CommandBarPage.tsx, packages/office-ui-fabric-react/src/components/CommandBar/examples/CommandBar.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/CommandBar/examples/CommandBar.Customization.Example.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuPage.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Checkmarks.Example.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Customization.Example.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Directional.Example.tsx
=> Third pass fixing 'jsx-alignment' for tslint in Fabric pkg

packages/office-ui-fabric-react/src/VisualTestRoot.tsx, packages/office-ui-fabric-react/src/components/ActivityItem/ActivityItem.tsx, packages/office-ui-fabric-react/src/components/Breadcrumb/examples/Breadcrumb.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/Breadcrumb/examples/Breadcrumb.Static.Example.tsx, packages/office-ui-fabric-react/src/components/Button/Button.test.tsx, packages/office-ui-fabric-react/src/components/Button/ButtonPage.tsx, packages/office-ui-fabric-react/src/components/Button/examples/Button.Action.Example.tsx, packages/office-ui-fabric-react/src/components/Callout/examples/Callout.Nested.Example.tsx, packages/office-ui-fabric-react/src/components/ChoiceGroup/examples/ChoiceGroup.Custom.Example.tsx, packages/office-ui-fabric-react/src/components/ChoiceGroup/examples/ChoiceGroup.Icon.Example.tsx, packages/office-ui-fabric-react/src/components/ComboBox/examples/ComboBox.CustomStyled.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Documents.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.DragDrop.Example.tsx, packages/office-ui-fabric-react/src/components/Dialog/Dialog.test.tsx, packages/office-ui-fabric-react/src/components/Dropdown/examples/Dropdown.Custom.Example.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Click.Example.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Example.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.FocusOnCustomElement.Example.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Nested.Example.tsx, packages/office-ui-fabric-react/src/components/HoverCard/examples/HoverCard.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/HoverCard/examples/HoverCard.Target.Example.tsx
Third pass removing unused variables from Fabric pkg
=> Third pass removing unused variables from Fabric pkg

packages/office-ui-fabric-react/src/components/DatePicker/DatePickerPage.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsListPage.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.CustomColumns.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.CustomGroupHeaders.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Documents.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.NavigatingFocus.Example.tsx, packages/office-ui-fabric-react/src/components/Dialog/Dialog.test.tsx, packages/office-ui-fabric-react/src/components/Dialog/DialogPage.tsx, packages/office-ui-fabric-react/src/components/Dialog/DialogPage.visualtest.tsx, packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardPage.tsx, packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardPage.visualtest.tsx, packages/office-ui-fabric-react/src/components/DocumentCard/examples/DocumentCard.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/DocumentCard/examples/DocumentCard.Compact.Example.tsx, packages/office-ui-fabric-react/src/components/DocumentCard/examples/DocumentCard.Complete.Example.tsx, packages/office-ui-fabric-react/src/components/Dropdown/DropdownPage.tsx, packages/office-ui-fabric-react/src/components/Facepile/Facepile.test.tsx, packages/office-ui-fabric-react/src/components/Facepile/FacepilePage.tsx, packages/office-ui-fabric-react/src/components/Facepile/FacepilePage.visualtest.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZonePage.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Click.Example.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Example.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.FocusOnCustomElement.Example.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Nested.Example.tsx, packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.test.tsx, packages/office-ui-fabric-react/src/components/FocusZone/FocusZonePage.tsx, packages/office-ui-fabric-react/src/components/FocusZone/examples/FocusZone.List.Example.tsx, packages/office-ui-fabric-react/src/components/FocusZone/examples/FocusZone.Photos.Example.tsx
=> Fourth pass fixing 'jsx-alignment' for tslint in Fabric pkg

packages/office-ui-fabric-react/src/components/GroupedList/GroupedListPage.tsx, packages/office-ui-fabric-react/src/components/Icon/IconPage.tsx, packages/office-ui-fabric-react/src/components/Image/ImagePage.tsx, packages/office-ui-fabric-react/src/components/Label/LabelPage.tsx, packages/office-ui-fabric-react/src/components/Layer/LayerPage.tsx, packages/office-ui-fabric-react/src/components/Layer/examples/Layer.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/Layer/examples/Layer.Hosted.Example.tsx, packages/office-ui-fabric-react/src/components/Link/LinkPage.tsx, packages/office-ui-fabric-react/src/components/List/ListPage.tsx, packages/office-ui-fabric-react/src/components/List/examples/List.Grid.Example.tsx, packages/office-ui-fabric-react/src/components/List/examples/List.Scrolling.Example.tsx, packages/office-ui-fabric-react/src/components/MarqueeSelection/examples/MarqueeSelection.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/MessageBar/MessageBarPage.tsx, packages/office-ui-fabric-react/src/components/MessageBar/examples/MessageBar.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/Modal/ModalPage.tsx, packages/office-ui-fabric-react/src/components/Nav/NavPage.tsx, packages/office-ui-fabric-react/src/components/Nav/examples/Nav.FabricDemoApp.Example.tsx, packages/office-ui-fabric-react/src/components/OverflowSet/examples/OverflowSet.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/OverflowSet/examples/OverflowSet.Custom.Example.tsx, packages/office-ui-fabric-react/src/components/Overlay/OverlayPage.tsx, packages/office-ui-fabric-react/src/components/Overlay/examples/Overlay.Dark.Example.tsx, packages/office-ui-fabric-react/src/components/Panel/Panel.test.tsx, packages/office-ui-fabric-react/src/components/Panel/PanelPage.tsx, packages/office-ui-fabric-react/src/components/Panel/examples/Panel.Footer.Example.tsx, packages/office-ui-fabric-react/src/components/Panel/examples/Panel.SmallRight.Example.tsx, packages/office-ui-fabric-react/src/components/Persona/PersonaPage.tsx, packages/office-ui-fabric-react/src/components/Persona/examples/Persona.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/pickers/PickersPage.tsx, packages/office-ui-fabric-react/src/components/pickers/examples/Picker.CustomResult.Example.tsx, packages/office-ui-fabric-react/src/components/pickers/examples/TagPicker.Basic.Example.tsx
Fifth pass fixing 'jsx-alignment' for tslint in Fabric pkg
=> Fifth pass fixing 'jsx-alignment' for tslint in Fabric pkg

common/changes/office-ui-fabric-react/scrolltoindex_2017-09-07-18-51.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.Props.ts, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx, packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.Props.ts, packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.tsx
Add the `scrollToIndex` method to DetailsList and GroupedList.
=> Add scrollToIndex to GroupedList, DetailsList

common/changes/office-ui-fabric-react/message-bar-truncation_2017-09-11-22-15.json, packages/office-ui-fabric-react/src/components/MessageBar/MessageBar.scss
Added word-break to message bar
(optional)
=> MessageBar: Added word-break to fix long word bug

common/changes/@uifabric/styling/master_2017-09-12-17-03.json, common/changes/office-ui-fabric-react/master_2017-09-12-17-03.json, packages/office-ui-fabric-react/src/components/Button/PrimaryButton/PrimaryButton.tsx, packages/styling/src/classNames/IconClassNames.ts, packages/styling/src/styles/getFocusStyle.ts
Fixing circular dependencies in PrimarButton and @uifabric/styling areas. 
None as long as builds fine.
=> Fixing circular dependencies in imports

common/changes/@uifabric/styling/more-vertical_2017-09-13-00-53.json, common/changes/office-ui-fabric-react/more-vertical_2017-09-13-00-53.json, packages/office-ui-fabric-react/src/components/Icon/IconName.ts, packages/styling/src/styles/IconCodes.ts
=> Adding MoreVertical icon.

packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Advanced.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Compact.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.CustomColumns.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.CustomGroupHeaders.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Documents.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.DragDrop.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Grouped.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.NavigatingFocus.Example.tsx, packages/office-ui-fabric-react/src/components/DocumentCard/examples/DocumentCard.Complete.Example.tsx, packages/office-ui-fabric-react/src/components/Dropdown/examples/Dropdown.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/Facepile/examples/Facepile.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/Facepile/examples/Facepile.Overflow.Example.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Click.Example.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Example.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.FocusOnCustomElement.Example.tsx
Third pass removing lambda expressions from jsx in Fabric for tslint
=> Third pass removing lambda expressions from jsx in Fabric

packages/styling/src/utilities/icons.ts
Warn when re-registering an icon that has already been registered.
(optional)
=> Warn when reregistering icons

common/changes/@uifabric/styling/v-krbrow-activity-icon-font_2017-09-15-16-17.json, common/changes/@uifabric/utilities/v-krbrow-activity-icon-font_2017-09-15-16-17.json, common/changes/office-ui-fabric-react/v-krbrow-activity-icon-font_2017-09-15-16-17.json, packages/office-ui-fabric-react/src/components/ActivityItem/ActivityItem.styles.ts
Decreasing the font size of icons in ActivityItems. This was requested by design after reviewing how ActivityItems actually looked in use.
=> Changing font size of activity icons

common/changes/@uifabric/experiments/layout-group-tweaks_2017-09-12-23-22.json, packages/experiments/src/components/LayoutGroup/LayoutGroup.props.ts, packages/experiments/src/components/LayoutGroup/LayoutGroup.tsx, packages/experiments/src/components/LayoutGroup/examples/LayoutGroup.Basic.Example.tsx
=> Layout group tweaks

common/changes/office-ui-fabric-react/master_2017-09-18-20-37.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx
Paren was in the wrong place breaking the logic
(optional)
=> Dropdown selected

packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.test.tsx, packages/office-ui-fabric-react/src/components/FocusZone/examples/FocusZone.List.Example.tsx, packages/office-ui-fabric-react/src/components/FocusZone/examples/FocusZone.Photos.Example.tsx, packages/office-ui-fabric-react/src/components/GroupedList/examples/GroupedList.Custom.Example.tsx, packages/office-ui-fabric-react/src/components/HoverCard/examples/HoverCard.Target.Example.tsx, packages/office-ui-fabric-react/src/components/Image/Image.test.tsx, packages/office-ui-fabric-react/src/components/Layer/examples/Layer.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/Layer/examples/Layer.Hosted.Example.tsx, packages/office-ui-fabric-react/src/components/List/examples/List.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/List/examples/List.Grid.Example.tsx, packages/office-ui-fabric-react/src/components/List/examples/List.Scrolling.Example.tsx, packages/office-ui-fabric-react/src/components/MarqueeSelection/examples/MarqueeSelection.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/MessageBar/examples/MessageBar.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/Nav/examples/Nav.FabricDemoApp.Example.tsx, packages/office-ui-fabric-react/src/components/OverflowSet/examples/OverflowSet.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/OverflowSet/examples/OverflowSet.Custom.Example.tsx
Third pass removing lambda expressions from jsx in Fabric for tslint
=> Fourth pass removing lambda expressions from jsx in Fabric

common/changes/office-ui-fabric-react/modal-docs_2017-09-19-18-46.json, packages/office-ui-fabric-react/src/components/Modal/examples/Modal.Basic.Example.scss
=> Modal: Updated padding in example to fix RTL support

apps/fabric-website/src/components/App/App.scss, apps/fabric-website/src/components/PageHeader/PageHeader.module.scss, apps/fabric-website/src/pages/BlogPage/BlogPage.module.scss, apps/fabric-website/src/pages/HomePage/HomePage.module.scss, apps/fabric-website/src/pages/HomePage/HomePage.tsx, apps/fabric-website/src/pages/ResourcesPage/ResourcesPage.module.scss, apps/fabric-website/src/styles/_variables.scss, common/changes/@uifabric/fabric-website/visual-bug-fixes_2017-09-18-22-20.json
This addresses bugs filed internally for the current website dogfood environment:
- Extended angle on Blog and Resources pages to fit new app width
- Added more specific link selectors to target link colors on the Homepage
- Component page header is now sticking to the top, no more gap leftover from previous header
(optional)
=> Visual bug fixes related to UHF for website

common/changes/office-ui-fabric-react/custom_dropdown_chevron_2017-09-19-20-39.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.Props.ts, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx, packages/office-ui-fabric-react/src/components/Dropdown/examples/Dropdown.Basic.Example.scss, packages/office-ui-fabric-react/src/components/Dropdown/examples/Dropdown.Custom.Example.tsx
allow 'chevron down' icon on Dropdown to be customized by adding onRenderChevronDownIcon prop
(optional)
=> allow 'chevron down' icon on Dropdown to be customized

apps/fabric-website/src/pages/GetStarted/GetStartedPage.tsx, common/changes/@uifabric/fabric-website/trello-regression_2017-09-20-18-17.json
This PR regressed: https://github.com/OfficeDev/office-ui-fabric-react/pull/2576
(optional)
=> Removed Trello reference from Get Started page on website - regression

packages/experiments/src/components/Tile/Tile.tsx, packages/office-ui-fabric-react/src/components/Check/Check.scss, packages/office-ui-fabric-react/src/components/Check/Check.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsRowCheck.tsx
This change cherry-picks fixes made to the Check control for immediate use by certain consumers.
=> Cherry-pick Check hotfixes

common/changes/office-ui-fabric-react/phkuo-themeGeneratorBackground_2017-09-22-20-51.json, packages/office-ui-fabric-react/src/components/ThemeGenerator/ThemeGeneratorPage.tsx
The website is set up a bit differently than localhost. Have the website also change the background as the theme changes, and then undo theming changes when you leave the page.
(optional)
=> Theme Generator: have the bg change with theme

common/changes/office-ui-fabric-react/phkuo-themeGeneratorHeadings_2017-09-23-00-44.json, packages/office-ui-fabric-react/src/components/ThemeGenerator/ThemeGeneratorPage.scss
Make sure headings on the Theme Generator page theme so they don't become invisible on dark backgrounds. (They don't currently theme because the base styles aren't using the right theme variable.)
(optional)
=> Theme Generator: have headings theme

apps/fabric-website/src/pages/ResourcesPage/ResourcesPage.tsx, common/changes/office-ui-fabric-react/contextualmenu-toolkit_2017-09-22-23-36.json, common/config/rush/npm-shrinkwrap.json, packages/office-ui-fabric-react/src/common/_semanticColorVariables.scss, packages/office-ui-fabric-react/src/components/Button/examples/Button.Split.Example.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuPage.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Customization.Example.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Directional.Example.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Icon.Example.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Section.Example.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Submenu.Example.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenuExample.scss
- Changed link to external toolkit to the zip
- Split button height was still off, so trying again
- Contextual menu changes to be clearer for the user and closer to the toolkit, result of each example on the page here:
(optional)
=> ContextualMenu examples - syncing with toolkit - plus a couple small website bugs

common/config/rush/npm-shrinkwrap.json, packages/merge-styles/README.md, packages/merge-styles/package.json, packages/merge-styles/src/IRawStyleBase.ts, packages/merge-styles/src/IStyle.ts, packages/merge-styles/src/Stylesheet.ts, packages/merge-styles/src/fontFace.ts, packages/merge-styles/src/index.ts, packages/merge-styles/src/styleToClassName.test.ts, packages/merge-styles/src/styleToClassName.ts, packages/merge-styles/src/transforms/provideUnits.ts, packages/merge-styles/src/transforms/rtlifyRules.test.ts, packages/merge-styles/src/transforms/rtlifyRules.ts, packages/utilities/package.json
This pulls in all of the merge-styles changes from 5.0 into master.
The package is not automatically published so no change file is needed.
=> Latest merge-styles updates.

packages/office-ui-fabric-react-tslint/tslint.json
One of the rules was misconfigured and not working correctly.
=> tslint tweak

common/changes/office-ui-fabric-react/checkbox-toolkit_2017-09-28-18-01.json, packages/office-ui-fabric-react/src/components/Checkbox/CheckboxPage.tsx, packages/office-ui-fabric-react/src/components/Checkbox/examples/Checkbox.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/Checkbox/examples/Checkbox.ImplementationExamples.tsx
- Separated out basic checkbox from other dev-specific implementation examples. Simplified default checkbox.  
- Fixed spacing between examples ('px' was missing from marginTop: '10px')
**Before:**
**After:**
(optional)
=> Separated out basic checkbox example from other dev-specific implementation examples

common/changes/@uifabric/example-app-base/example-app-base-fabric-upgrade_2017-09-28-23-51.json, common/config/rush/npm-shrinkwrap.json, packages/example-app-base/package.json
Example app base was still on fabric 4.*!
=> Upgrade example-app-base to Fabric 5.0

apps/vr-tests/src/stories/Callout.stories.tsx, apps/vr-tests/src/stories/Label.stories.tsx, apps/vr-tests/src/stories/Link.stories.tsx, apps/vr-tests/src/stories/MessageBar.stories.tsx, apps/vr-tests/src/stories/Toggle.stories.tsx, apps/vr-tests/src/utilities/FabricDecorator.tsx
Added stories for Callout, Label, Link, MessageBar, and Toggle
=> Stories - Callout, Label, Link, MessageBar, and Toggle

apps/fabric-website/src/pages/GetStarted/GetStartedPage.module.scss, apps/fabric-website/src/pages/GetStarted/GetStartedPage.tsx, apps/fabric-website/src/pages/ResourcesPage/ResourcesPage.tsx, apps/fabric-website/src/pages/Styles/BrandIconsPage/BrandIconsPage.module.scss, apps/fabric-website/src/pages/Styles/ColorsPage/ColorsPage.module.scss, apps/fabric-website/src/pages/Styles/ColorsPage/ColorsPage.tsx, common/changes/@uifabric/fabric-website/general-website-bugs_2017-10-02-22-18.json, common/changes/office-ui-fabric-react/general-website-bugs_2017-10-02-22-18.json, packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.styles.ts, packages/office-ui-fabric-react/src/components/ComboBox/examples/ComboBox.Basic.Example.scss, packages/office-ui-fabric-react/src/components/TextField/TextFieldPage.tsx, packages/office-ui-fabric-react/src/components/TextField/examples/TextField.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/TextField/examples/TextField.Borderless.Example.tsx, packages/office-ui-fabric-react/src/components/TextField/examples/TextField.ErrorMessage.Example.tsx, packages/office-ui-fabric-react/src/components/TextField/examples/TextField.Examples.scss, packages/office-ui-fabric-react/src/components/TextField/examples/TextField.ImplementationExamples.tsx, packages/office-ui-fabric-react/src/components/TextField/examples/TextField.Multiline.Example.tsx, packages/office-ui-fabric-react/src/components/TextField/examples/TextField.Placeholder.Example.tsx, packages/office-ui-fabric-react/src/components/TextField/examples/TextField.Underlined.Example.tsx
- Updated ResourcePage text per convo with Laura and Angela
- Reordered TextField page to give priority to design guidance examples due to a newly added dev example
- improved padding and spacing for TextField and ComboBox examples
- Fixed padding on ColorsPage, and made other similar changes on other pages more RTL friendly-
- Synced ComboBox error message spacing to be like TextField, per design specs, reference issue #2894 
(optional)
=> Visual bug fixes for website, mostly text and spacing updates

apps/fabric-website/src/components/App/AppState.tsx, apps/fabric-website/src/pages/Components/IconComponentPage.tsx, common/changes/@uifabric/fabric-website/icon-page-website_2017-10-03-15-54.json
Added Icon component to the website. I plan to add a link to this page in this PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/2998
(optional)
=> Adding Icon component page to the website

common/changes/office-ui-fabric-react/positioning-eventfix_2017-10-06-20-21.json, packages/office-ui-fabric-react/src/utilities/positioning.ts
Fix an issue where beak would appear misaligned when click event was passed in as target.
(optional)
=> Positioning: Fix improper beak placement with events

apps/fabric-website/src/root.tsx, common/changes/@uifabric/fabric-website/website-promise-polyfill_2017-10-11-19-14.json
Add Promise polyfill to fix https://github.com/OfficeDev/office-ui-fabric-react/issues/3070
=> Add promise polyfill to fabric website

common/changes/office-ui-fabric-react/chrisgo-getItemClassNames_2017-10-12-00-35.json, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.Props.ts, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx
The classNames arguments to getItemClassNames are optional. This PR updates the typings of getItemClassNames to reflect that
=> ContextualMenu: Update the typings on getItemClassNames

ghdocs/TESTING.md
Add VR section to testing docs
=> Add VR section to testing docs

common/changes/office-ui-fabric-react/fix-slider-rounding_2017-10-13-17-25.json, packages/office-ui-fabric-react/src/components/Slider/Slider.tsx
Fix rounding issue when `steps` is < 1
=> Slider: Fix rounding issue

apps/vr-tests/src/stories/Slider.stories.tsx, common/changes/office-ui-fabric-react/fix-slider-css_2017-10-13-22-57.json, packages/office-ui-fabric-react/src/components/Slider/Slider.scss
https://github.com/OfficeDev/office-ui-fabric-react/issues/3112#issuecomment-336494529
Update Slider label CSS so it doesn't break lines if the value is large. Fix stories for Slider too so it displays properly.
=> Slider: fix css

common/changes/office-ui-fabric-react/phkuo-finalSemanticSlots_2017-10-17-00-50.json, packages/office-ui-fabric-react/src/common/_semanticColorVariables.scss, packages/office-ui-fabric-react/src/common/_semanticSlots.scss, packages/office-ui-fabric-react/src/common/_themeOverrides.scss
Theming: add SASS variables for semantic theming to support legacy scenarios
(optional)
=> Theming: add SASS variables for semantic theming to support legacy scenarios

common/changes/office-ui-fabric-react/fabric-react-core_2017-10-16-19-47.json, common/config/rush/npm-shrinkwrap.json, packages/office-ui-fabric-react/package.json
Updated the website: https://github.com/OfficeDev/office-ui-fabric-react/pull/3124
Now updating Fabric React.
(optional)
=>  Updated fabric react's fabric core package version

common/changes/office-ui-fabric-react/brwatt-sticky-fix_2017-10-18-23-12.json, packages/office-ui-fabric-react/src/components/Sticky/Sticky.tsx
isStickyTop and isStickyBottom can change in the same update so they should b handled separately.
=> Fix minor state update bug with Sticky

common/changes/@uifabric/experiments/phkuo-themingDoc_2017-10-19-00-40.json, common/changes/@uifabric/fabric-website/phkuo-themingDoc_2017-10-19-00-40.json, common/changes/@uifabric/jest-serializer-merge-styles/phkuo-themingDoc_2017-10-19-00-40.json, common/changes/@uifabric/merge-styles/phkuo-themingDoc_2017-10-19-00-40.json, common/changes/@uifabric/styling/phkuo-themingDoc_2017-10-19-00-40.json, common/changes/office-ui-fabric-react/phkuo-themingDoc_2017-10-19-00-40.json, ghdocs/Theming.md
Add a high level overview of the Theming feature as a whole. Specifics are avoided and linked to instead, in order to avoid repetition and to maintain high level overview.
(optional)
=> Theming: add high level documentation for whole feature

common/changes/office-ui-fabric-react/add-check_2017-10-20-05-59.json, packages/office-ui-fabric-react/src/Icons.ts, packages/office-ui-fabric-react/src/index.ts
Exporting Check. Also adding Icons export file. 
Also removing the unpkg reference for icons since we have them on the cdn now.
=> Adding some top level exports

common/changes/office-ui-fabric-react/dropdown-docs_2017-10-17-18-29.json, packages/office-ui-fabric-react/src/components/Dropdown/DropdownPage.tsx
Added `ISelectableDroppableText` to Dropdown docs page
=> Docs: Add ISelectableDroppableText to Dropdown docs page

packages/office-ui-fabric-react/src/components/Persona/__snapshots__/Persona.test.tsx.snap, packages/office-ui-fabric-react/src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
Updated Jest snapshots to fix build
=> Jest: Update snapshots

common/changes/@uifabric/jest-serializer-merge-styles/jest-docs_2017-10-20-18-25.json, packages/jest-serializer-merge-styles/README.md
Collected some notes from PRs and emails that helped me figure out how work with jest and added them to the README.
(optional)
=> Jest: Added some usage and update notes to docs

common/changes/@uifabric/example-app-base/example-app-fix_2017-10-25-01-29.json, packages/example-app-base/src/components/App/App.scss, packages/example-app-base/src/components/Header/Header.scss
Minor css tweak to example app base to remove rounded corners.
=> Example app css tweak

common/changes/office-ui-fabric-react/button-pass-ondismiss_2017-10-23-23-22.json, packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx
Previously onDismiss was overwritten by the button's _onToggleMenu function.
(optional)
=> Button pass ondismiss

.github/CODEOWNERS
~~- [ ] Addresses an existing issue: Fixes #0000~~
~~- [ ] Include a change request file using `$ npm run change`~~
Add a couple of interested owners for the PersonaCoin component file(s)
Nothing
=> Add code owners for PersonaCoin component

ghdocs/Accessibility.md
Document our policies and best practices for supporting accessibility. I've left keyboard and focus as a todo since I'm not familiar in that area, I'll leave it to someone else to fill that in.
(optional)
=> Documentation: Accessibility policies and best practices

apps/vr-tests/src/stories/Button.stories.tsx, common/changes/office-ui-fabric-react/button-icon-flexgrow_2017-10-30-21-43.json, packages/office-ui-fabric-react/src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, packages/office-ui-fabric-react/src/components/Button/BaseButton.styles.ts, packages/office-ui-fabric-react/src/components/Button/__snapshots__/Button.test.tsx.snap, packages/office-ui-fabric-react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap, packages/office-ui-fabric-react/src/components/Nav/__snapshots__/Nav.test.tsx.snap, packages/office-ui-fabric-react/src/components/SpinButton/__snapshots__/SpinButton.test.tsx.snap
Icons, and icon placeholders were flex-shrinking when text was too long.
=> Button icon flexgrow

common/changes/office-ui-fabric-react/button-onMenuClick_2017-10-31-17-19.json, packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx, packages/office-ui-fabric-react/src/components/Button/Button.Props.ts, packages/office-ui-fabric-react/src/components/Button/examples/Button.ContextualMenu.Example.tsx
=> Button on menu click

common/changes/@uifabric/experiments/experiments-fix_2017-11-01-18-07.json, packages/experiments/src/components/SelectedItemsList/examples/SelectedPeopleList.Basic.Example.tsx
Fixed an import that was causing the lib folder in experiments to be structured weird
=> Experiments: Fix import that was causing build issue

apps/vr-tests/src/stories/Persona.stories.tsx, common/changes/office-ui-fabric-react/fix-persona_2017-11-05-22-16.json, packages/office-ui-fabric-react/src/components/Persona/Persona.tsx, packages/office-ui-fabric-react/src/components/Persona/PersonaCoin.tsx, packages/office-ui-fabric-react/src/components/Persona/PersonaConsts.ts
A recent change broke existing PersonaSize values. This adds the support back to avoid breaking partners, and updates the screenshot tests to validate.
=> Persona: respecting PersonaSize legacy values.

common/changes/office-ui-fabric-react/commandBar-whitespace_2017-11-06-16-36.json, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.tsx, packages/office-ui-fabric-react/src/components/CommandBar/__snapshots__/CommandBar.test.tsx.snap
=> Command bar whitespace

common/changes/office-ui-fabric-react/checkmark-icon_2017-11-01-22-37.json, packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts, packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.tsx
Add the ability to render a custom icon for a checkbox by exposing the icon props
=> Checkbox: Expose icon props for the check mark

packages/office-ui-fabric-react/src/components/Calendar/CalendarPage.tsx, packages/office-ui-fabric-react/src/components/Calendar/examples/Calendar.Inline.Example.tsx
Add Calendar with date boundary example. No api or functional change.
None.
=> Add Calendar with date boundary example

common/changes/office-ui-fabric-react/person-edge-polish_2017-11-06-16-27.json, packages/office-ui-fabric-react/src/components/Persona/Persona.scss, packages/office-ui-fabric-react/src/components/Persona/Persona.tsx, packages/office-ui-fabric-react/src/components/Persona/PersonaPage.tsx, packages/office-ui-fabric-react/src/components/Persona/examples/Persona.Alternate.Example.tsx, packages/office-ui-fabric-react/src/components/Persona/examples/Persona.CustomRender.Example.tsx, packages/office-ui-fabric-react/src/components/Persona/examples/Persona.Initials.Example.tsx, packages/office-ui-fabric-react/src/components/Persona/examples/PersonaExample.scss
- Improved spacing between examples.
- Added DirectionalHint for Tooltip so that it can handle wide elements.
(optional)
=> Person: Polish documentation and custom variants

common/changes/@uifabric/utilities/chf-2017-11-utilities_NewVersion_Publish_2017-11-08-01-02.json, packages/utilities/src/focus.ts
=> Publish a new version of utilities

common/changes/@uifabric/experiments/maxlus-trendingIcon_2017-10-31-22-12.json, packages/experiments/src/components/signals/Signals.scss, packages/experiments/src/components/signals/Signals.tsx
Moves the trending icon down a bit to better align in details list.
(optional)
=> Fix alignment for trending icon in list

.travis.yml, common/config/rush/command-line.json, common/config/rush/npm-shrinkwrap.json, package.json, packages/example-app-base/src/components/App/App.tsx, rush.json
This brings Fabric onto the LTS version of node and latest npm/rush. Let's see how the CI takes it.
=> Bumping rush to 4.0, npm and node dependencies as well

common/changes/office-ui-fabric-react/virtualizedComboBoxFocus_2017-11-08-21-51.json, packages/office-ui-fabric-react/src/components/ComboBox/VirtualizedComboBox.tsx
Make VirtualizedComboBox implement IComboBox interface, and call through to ComboBox reference.
=> Add ComboBox public functions to VirtualizedComboBox

common/changes/@uifabric/utilities/fix-ids_2017-11-09-01-35.json, packages/experiments/src/components/CommandBar/__snapshots__/CommandBar.test.tsx.snap, packages/office-ui-fabric-react/src/components/Button/__snapshots__/Button.test.tsx.snap, packages/office-ui-fabric-react/src/components/Facepile/__snapshots__/Facepile.test.tsx.snap, packages/office-ui-fabric-react/src/components/SwatchColorPicker/__snapshots__/SwatchColorPicker.test.tsx.snap, packages/utilities/src/object.ts
Object/getId: Fix it so it correctly returns a string instead of a number.
(optional)
=> Object/getId: Fix it so it correctly returns a string instead of a number.

.travis.yml, common/config/rush/npm-shrinkwrap.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx, packages/office-ui-fabric-react/src/components/Label/Label.base.tsx, packages/office-ui-fabric-react/src/components/Label/Label.checklist.ts, packages/office-ui-fabric-react/src/components/Label/Label.styles.ts, packages/office-ui-fabric-react/src/components/Label/Label.test.tsx, packages/office-ui-fabric-react/src/components/Label/Label.tsx, packages/office-ui-fabric-react/src/components/Label/Label.types.ts, packages/office-ui-fabric-react/src/components/Label/index.ts, packages/office-ui-fabric-react/src/components/Toggle/Toggle.base.tsx, packages/office-ui-fabric-react/src/components/Toggle/Toggle.checklist.ts, packages/office-ui-fabric-react/src/components/Toggle/Toggle.styles.ts, packages/office-ui-fabric-react/src/components/Toggle/Toggle.test.tsx, packages/office-ui-fabric-react/src/components/Toggle/Toggle.tsx, packages/office-ui-fabric-react/src/components/Toggle/Toggle.types.ts, packages/office-ui-fabric-react/src/components/Toggle/index.ts, packages/office-ui-fabric-react/src/demo/ComponentStatus/ComponentStatus.tsx, packages/office-ui-fabric-react/src/demo/ComponentStatus/ComponentStatus.types.ts, packages/styling/src/utilities/classNamesFunction.ts
Toggle changes:
* Now Toggle has a Toggle.base unstyled implementation.
* Styles from .classNames moved to getStyles
* Added `as` to control the root for Toggle.
Same with Label.
=> 6.0: Toggle update

common/changes/office-ui-fabric-react/choicegroupRTL_2017-11-13-20-08.json, packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.scss
=> Choicegroup rtl

common/changes/office-ui-fabric-react/fix-header-ariapopup_2017-11-16-22-54.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.tsx
Move aria-haspopup to correct element. Aria-haspopup needs to be on the element that is focused, not on the container.
(optional)
=> DetailsHeader: Fix aria-haspopup

apps/fabric-website/README.md, apps/fabric-website/src/pages/GetStarted/GetStartedPage.tsx, apps/fabric-website/src/pages/HomePage/HomePage.tsx, apps/fabric-website/src/pages/Styles/BrandIconsPage/BrandIconsPage.tsx, common/changes/@uifabric/fabric-website/asset-license_2017-11-16-22-54.json
Updated links for the asset license to match latest version on the cdn.
(optional)
=> Website: Updated asset license to latest version

common/changes/@uifabric/example-app-base/brwatt-fix-commandbar-growth-6_2017-11-16-23-25.json, common/changes/@uifabric/experiments/brwatt-fix-commandbar-growth-6_2017-11-16-23-25.json, common/changes/@uifabric/merge-styles/brwatt-fix-commandbar-growth-6_2017-11-16-23-25.json, common/changes/@uifabric/styling/brwatt-fix-commandbar-growth-6_2017-11-16-23-25.json, common/changes/@uifabric/utilities/brwatt-fix-commandbar-growth-6_2017-11-16-23-25.json, common/changes/office-ui-fabric-react/brwatt-fix-commandbar-growth-6_2017-11-16-23-25.json, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.tsx
Make sure commands get added/removed in the correct order. The commands were being added to the end of the overflow list instead of the beginning. This change fixes that.
=> Fixes #3352 - Make sure commands get added/removed in the correct order

common/changes/@uifabric/experiments/brwatt-fix-commandbar-growth_2017-11-16-21-50.json, packages/experiments/src/components/CommandBar/CommandBar.tsx
Make sure commands get added/removed in the correct order. The commands were being added to the end of the overflow list instead of the beginning. This change fixes that.
=>  Fixes #3352 - Make sure commands get added/removed in the correct order

apps/fabric-website/src/components/App/AppState.tsx, apps/fabric-website/src/pages/Components/ActivityItemComponentPage.tsx, apps/fabric-website/src/pages/Components/CalendarComponentPage.tsx, apps/fabric-website/src/pages/Components/HoverCardComponentPage.tsx, apps/fabric-website/src/pages/Components/OverflowSetComponentPage.tsx, apps/fabric-website/src/pages/Components/ScrollablePaneComponentPage.tsx, apps/fabric-website/src/pages/Components/TeachingBubbleComponentPage.tsx, common/changes/@uifabric/fabric-website/v-edwliu-addComponentsToFabricWebsite_2017-11-17-23-07.json, common/changes/office-ui-fabric-react/v-edwliu-addComponentsToFabricWebsite_2017-11-17-23-07.json, packages/office-ui-fabric-react/src/components/HoverCard/HoverCardPage.tsx, packages/office-ui-fabric-react/src/components/OverflowSet/OverflowSetPage.tsx, packages/office-ui-fabric-react/src/components/ScrollablePane/ScrollablePanePage.tsx, packages/office-ui-fabric-react/src/components/TeachingBubble/TeachingBubblePage.tsx
Adds components to fabric-website:
- ActivityItem
- Calendar
- HoverCard
- OverflowSet
- ScrollablePane
- TeachingBubble
(optional)
=> Add missing components to fabric-website

common/changes/office-ui-fabric-react/persona-fontsize_2017-11-18-00-59.json, packages/office-ui-fabric-react/src/components/Persona/Persona.scss
=> Persona: Changed size40's font back to 14px

packages/experiments/README.md
Fixes small typos & grammar details for experiments README.
=> Fix typos for experiments README

common/changes/@uifabric/experiments/brwatt-fix-external-signal_2017-11-27-22-57.json, packages/experiments/src/components/signals/Signals.tsx
This adds the correct icon and correctly styles the component to meet the desired design.
=> Correctly styles the external signal component

common/changes/office-ui-fabric-react/tecambri-panelhiddenondismiss_2017-11-29-21-30.json, packages/office-ui-fabric-react/src/components/Panel/Panel.scss, packages/office-ui-fabric-react/src/components/Panel/Panel.tsx, packages/office-ui-fabric-react/src/components/Panel/Panel.types.ts, packages/office-ui-fabric-react/src/components/Panel/PanelPage.tsx, packages/office-ui-fabric-react/src/components/Panel/examples/Panel.HiddenOnDismiss.Example.tsx
Panel: Allow capability to hide panel on dismiss, instead of destroying it (isHiddenOnDismiss)
Panel
=> Panel: When dismissed, allow the capability to hide the visibility of the panel

common/changes/@uifabric/styling/phloh-localized-ui-fonts_2017-11-29-21-50.json, packages/styling/src/styles/fonts.ts
Changed font references of Yu Gothic, Microsoft Yahei, Microsoft Jhenghei --> Yu Gothic UI, Microsoft Yahei UI, Microsoft Jhenghei UI
(optional)
=>  Use UI fonts instead of non-UI fonts (CJK)

apps/vr-tests/package.json, apps/vr-tests/src/stories/Fonts.stories.tsx
This change adds visual regression tests for our various localized font stacks, as requested by @mikewheaton on #3481
=> Create visual regression tests for the font stacks

packages/styling/package.json
Package publishing partially succeeded in the overnight build. This means subsequent builds will fail since the version numbers in master don't match the truth in npm. This makes them align by updating the styling package
=> Fix the build

common/changes/office-ui-fabric-react/3497_2017-12-04-19-02.json, packages/office-ui-fabric-react/src/components/Button/ButtonThemes.ts
Updates the Default Button colors to match the design spec.
=> Update a couple button colors to match design

apps/fabric-website/src/pages/Components/ScrollablePaneComponentPage.tsx, common/changes/@uifabric/fabric-website/v-edwliu-fixScrollablePanePage_2017-12-04-18-18.json
Fix website bug, fix incorrect page title for ScrollablePane
(optional)
=> Rename ScrollBox to ScrollablePane on fabric-website

common/changes/office-ui-fabric-react/master_2017-12-07-08-45.json, packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
If u set itemLimit for picker, when u pick last item input is removed. So we need this check
=> bug fix: check for input is exist

common/changes/@uifabric/experiments/chrisgo-fix-experiments_2017-12-08-17-37.json, packages/experiments/src/components/Coachmark/CoachmarkPage.tsx, packages/experiments/src/components/PositioningContainer/PositioningContainer.tsx, packages/experiments/src/components/PositioningContainer/PositioningContainer.types.ts, packages/experiments/src/components/PositioningContainer/PositioningContainerPage.tsx, packages/experiments/src/components/PositioningContainer/examples/PositioningContainer.Basic.Example.tsx
=> Experiments: Fix build breaks

common/changes/office-ui-fabric-react/stzh-detailslist_2017-12-11-21-06.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx
=> Fix DetailsList.onRenderMissingItem doesn't render missing item

common/changes/office-ui-fabric-react/link-pressed_2017-12-14-18-24.json, packages/office-ui-fabric-react/src/components/Link/Link.scss
The selectors for the pressed state needed to be more specific.
(optional)
=> Link: Fix for pressed state

common/changes/office-ui-fabric-react/lingge-persona-className_2017-12-15-09-01.json, packages/office-ui-fabric-react/src/components/Persona/PersonaCoin.tsx
=> Make PersonaCoin respect class passed from coinProps

apps/fabric-website/src/components/Nav/Nav.types.ts, apps/fabric-website/src/pages/PageStyles.module.scss, apps/fabric-website/src/styles/_variables.scss, common/changes/@uifabric/fabric-website/uhf-comments_2017-12-14-19-19.json
When adopting the UHF, we needed super specific variables and selectors to ensure UHF styles did not conflict with our own. These comments go further to explain those nuances.
(optional)
=> Website: More descriptive comments about UHF specificity

common/changes/office-ui-fabric-react/lingge-BasePicker-update-state-unmount-check_2017-12-15-05-43.json, packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
=> Base Picker: check unmount state when updating suggestion list

.github/CODEOWNERS
updating the code owners file to add me and Johanna as code owners of the datemath and datevalues utilities. running 'npm run change' comes back with 'No change file is needed'
(optional)
=> adding johanna and john as code owners of the datemath utilities

common/changes/office-ui-fabric-react/magellan-ratingFocus_2018-01-04-21-53.json, packages/office-ui-fabric-react/src/components/Rating/Rating.tsx, packages/office-ui-fabric-react/src/components/Rating/__snapshots__/Rating.test.tsx.snap, packages/office-ui-fabric-react/src/components/Rating/examples/Rating.Basic.Example.tsx
Sets defaultActiveElement to the initial rating for the Rating component.
Added isFocusable to the Rating focusZone for consistent keyboard movement behavior.
=> Rating: focus issues

common/changes/@uifabric/merge-styles/master_2018-01-10-15-59.json, packages/merge-styles/src/styleToClassName.test.ts, packages/merge-styles/src/styleToClassName.ts
=> Do not emit style rules for properties with a value of undefined.

CONTRIBUTING.md
Added a few more sections to CONTRIBUTIONS.md
=> Adding more clarity to component contributions

common/changes/office-ui-fabric-react/miwhea-npm-publish-all-examples_2018-01-17-18-02.json, packages/office-ui-fabric-react/.npmignore
Updates `.gitignore` for the main package to include all TSX files within example folders. This fixes an issue where `Checkbox.ImplementationExamples.tsx` was not being published because it didn't match the usual `.Example.tsx` pattern.
=> Publish all example files to NPM

common/changes/office-ui-fabric-react/baseautofill-fixexpanded_2018-01-16-19-31.json, packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx, packages/office-ui-fabric-react/src/components/pickers/__snapshots__/BasePicker.test.tsx.snap
BasePicker: Fix accessibility bug where it always has aria-expanded=true
(optional)
=> BasePicker: Fix accessibility bug where it always has aria-expanded=true

common/changes/office-ui-fabric-react/fix-persona-withtooltipchange_2018-01-18-01-39.json, packages/office-ui-fabric-react/src/components/Persona/Persona.tsx, packages/office-ui-fabric-react/src/components/Persona/__snapshots__/Persona.test.tsx.snap
Persona: Fix a bug where secondary text would take space even though there was no text
(optional)
=> Persona: Fix a bug where secondary text would take space even though there was no text

packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts
Added the options for selectionMode enum in DetailsList.types.ts so they will display in JSDoc.
N/A
=> Addressing Issue #146 DetailsList: Include documentation of SelectionMode options

common/changes/@uifabric/styling/betrue-darkenSectionDivider_contextualMenu_2018-01-19-19-20.json, common/changes/office-ui-fabric-react/betrue-darkenSectionDivider_contextualMenu_2018-01-19-19-20.json, packages/office-ui-fabric-react/src/common/_semanticSlots.scss, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.styles.ts, packages/styling/src/styles/theme.ts
- [x ] Include a change request file using `$ npm run change`
Updated divider color from neutralLight to neutralTertiaryAlt.
=> Adjusted divider color to neutralTertiaryAlt for visibility.

common/changes/office-ui-fabric-react/v-krbrow-list-link-fix_2018-01-24-20-49.json, packages/office-ui-fabric-react/src/components/Button/ButtonPage.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsListPage.tsx
Fixes broken links in detailsList and button pages.
=> Fixing some broken links in documentation pages

packages/office-ui-fabric-react/src/components/pickers/BasePicker.scss
Reverting height on picker input because it's breaking the screener tests.
Make sure screener is passing.
=> Fixing height on picker input

common/changes/office-ui-fabric-react/fix-callout-scrollbar_2018-01-26-22-47.json, packages/office-ui-fabric-react/src/components/Callout/CalloutContent.base.tsx, packages/office-ui-fabric-react/src/components/Popup/Popup.tsx
Fix a bug where the scrollbar would show when it shouldn't.
(optional)
=> Callout: Fix scrollbar

common/changes/@uifabric/experiments/fixRenderForSelectedPeopleList_2018-01-30-19-13.json, packages/experiments/src/components/ExtendedPicker/examples/ExtendedPeoplePicker.Basic.Example.tsx, packages/experiments/src/components/SelectedItemsList/BaseSelectedItemsList.tsx, packages/experiments/src/components/SelectedItemsList/BaseSelectedItemsList.types.ts, packages/experiments/src/components/SelectedItemsList/SelectedPeopleList/SelectedPeopleList.tsx
- Make selection optional (default/fallback selection created if props.selection is null)
- Change render typedef to any, to allow use with lower versions of types/react
=> BaseSelectedListMake selection optional, Change render to any

common/changes/office-ui-fabric-react/ActivityItemEx-mergestyles_2018-01-31-00-28.json, packages/office-ui-fabric-react/src/components/ActivityItem/ActivityItemPage.tsx, packages/office-ui-fabric-react/src/components/ActivityItem/examples/ActivityItem.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/ActivityItem/examples/ActivityItem.Compact.Example.tsx, packages/office-ui-fabric-react/src/components/ActivityItem/examples/ActivityItem.Example.scss, packages/office-ui-fabric-react/src/components/ActivityItem/examples/ActivityItem.Example.styles.ts, packages/office-ui-fabric-react/src/components/ActivityItem/examples/ActivityItem.Persona.Example.tsx
Converted ActivityItemExample to use mergeStyles instead of SCSS.
N/A
=> ActivityItemExample mergeStyles Converstion

common/changes/office-ui-fabric-react/searchBoxBase-export_2018-02-01-23-56.json, packages/office-ui-fabric-react/src/components/SearchBox/index.ts
=> Search box base export

common/changes/office-ui-fabric-react/callout-rtlpositionfix_2018-02-07-01-43.json, packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts
Callout/Positioning: Fix RTL bug where alignment would be lost for some directionalhints
(optional)
=> Callout/Positioning: Fix RTL bug where alignment would be lost for some directionalhints

package.json
Add update-snapshots script to root of project so we don't have to `cd packages/office-ui-fabric-react && npm run update-snapshots`
=> Add update-snapshots script to project root.

apps/vr-tests/src/stories/Image.css, apps/vr-tests/src/stories/Image.stories.tsx
Found some bad css in the screenshot tests which was breaking the coin changes.
=> Fixes the screener tests to not fail with Persona/Picker scrollbars.

common/changes/office-ui-fabric-react/fabric-button-overflow_2018-02-14-00-59.json, packages/office-ui-fabric-react/src/components/Fabric/Fabric.classNames.ts
=> Fabric button overflow

common/changes/office-ui-fabric-react/searchbox-test_2018-02-14-19-03.json, packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.base.tsx, packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.test.tsx, packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.types.ts
Adding unit test to validate clearButtonProps.onClick is respected, adjusting previous commit to not override it.
=> SearchBox: Adding unit test.

common/changes/office-ui-fabric-react/nero120-pull-request-3942-autoAdjustTextboxHeight.json
=> ChangeFile for 3942

packages/office-ui-fabric-react/src/components/Button/examples/Button.Default.Example.tsx
Correcting mistyping error of 'Butjon' to 'Button' in button component text attribute.
=> Correcting mistype error

common/changes/office-ui-fabric-react/cammandbar-test-removelog_2018-02-17-01-35.json, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.test.tsx
Cleaning up a console.log in CommandBar.test.tsx that I noticed while updating snapshots.
=> Cleaning Up Console Log in CommandBar Test

common/changes/office-ui-fabric-react/rating-type_2018-02-21-04-05.json, packages/office-ui-fabric-react/src/components/Rating/Rating.base.tsx, packages/office-ui-fabric-react/src/components/Rating/__snapshots__/Rating.test.tsx.snap
Adding `type=button` to Rating buttons.
=> Rating type

common/changes/office-ui-fabric-react/enable-no-inferable-types_2018-02-22-07-17.json, packages/office-ui-fabric-react/src/components/Autofill/Autofill.tsx, packages/office-ui-fabric-react/src/components/Calendar/Calendar.tsx, packages/office-ui-fabric-react/src/components/Callout/Callout.test.tsx, packages/office-ui-fabric-react/src/components/Callout/CalloutContent.base.tsx, packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.test.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.DragDrop.Example.tsx, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx, packages/office-ui-fabric-react/src/components/Fabric/Fabric.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.FocusOnCustomElement.Example.tsx, packages/office-ui-fabric-react/src/components/Image/Image.base.tsx, packages/office-ui-fabric-react/src/components/Nav/Nav.base.tsx, packages/office-ui-fabric-react/src/components/ProgressIndicator/examples/ProgressIndicator.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.test.tsx, packages/office-ui-fabric-react/src/components/TextField/TextField.test.tsx, packages/office-ui-fabric-react/tslint.json
=> Enable no inferable types

common/changes/office-ui-fabric-react/fix-contextualmenuutilityimport_2018-02-23-22-18.json, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItem.tsx
=> ContextualMenu: Fix ContextualMenuUtility imports

common/changes/@uifabric/example-app-base/magellan-fixDetailsListFocusTest_2018-02-24-00-36.json, common/changes/@uifabric/experiments/magellan-fixDetailsListFocusTest_2018-02-24-00-36.json, common/changes/@uifabric/fabric-website/magellan-fixDetailsListFocusTest_2018-02-24-00-36.json, common/changes/@uifabric/file-type-icons/magellan-fixDetailsListFocusTest_2018-02-24-00-36.json, common/changes/@uifabric/icons/magellan-fixDetailsListFocusTest_2018-02-24-00-36.json, common/changes/@uifabric/styling/magellan-fixDetailsListFocusTest_2018-02-24-00-36.json, common/changes/@uifabric/variants/magellan-fixDetailsListFocusTest_2018-02-24-00-36.json, common/changes/office-ui-fabric-react/magellan-fixDetailsListFocusTest_2018-02-24-00-36.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.test.tsx
Mock element visiblity to fix tests.
=> [DetailsList] Fixed focus test

common/changes/office-ui-fabric-react/ScrollablePane_2018-02-26-14-25.json, packages/office-ui-fabric-react/src/components/ScrollablePane/ScrollablePane.base.tsx
=> Allow ScrollablePane to accept native properties.

common/changes/office-ui-fabric-react/master_2018-02-27-10-02.json, common/changes/office-ui-fabric-react/master_2018-02-27-10-47.json, packages/office-ui-fabric-react/src/components/Check/Check.base.tsx, packages/office-ui-fabric-react/src/components/Check/Check.styles.ts, packages/office-ui-fabric-react/src/components/Check/Check.tsx, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.tsx
Uses relative reference to @uifabric packages instead of direct reference.
(optional)
=> Fixing direct references to @uifabric which breaks AMD

common/changes/office-ui-fabric-react/master_2018-02-27-21-34.json, packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.scss
Fixed the css selector for the groupedHeader chevron.
=> GroupedList: Fixed chevron animation

common/changes/office-ui-fabric-react/disabledLink_2018-02-28-23-53.json, packages/office-ui-fabric-react/src/components/Link/Link.base.tsx
Makes sure that disabled links are focusable, say "disabled", and are not navigable.
=> Disabled link

common/changes/office-ui-fabric-react/label-for-breadcrumb_2018-02-23-00-57.json, packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.tsx, packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.types.ts
Add aria-label 'More items' to Breadcrumb overflow button
=> added More items aria label

common/changes/office-ui-fabric-react/suggestionElement_2018-03-02-01-56.json, packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
Check for null reference before checking value of this.suggestionElement
=> add check for when this.suggestionElement may be undefined

packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.CustomColumns.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Documents.Example.tsx
fieldName in DetailList's IColumn is optional
=> fieldName optional

common/changes/office-ui-fabric-react/magellan-commandItemWidthNull_2018-02-28-21-58.json, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.tsx
=> CommandBar: Fixed null commandItemWidths

common/changes/office-ui-fabric-react/users-samuelmtimbo-fixlistresize_2018-03-03-00-16.json, packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx
Correct ref string from "list" to "_list".
GroupedListSection
=> Use correct _list ref string

common/changes/@uifabric/experiments/amyngu-clearInput_2018-03-06-18-05.json, packages/experiments/src/components/ExtendedPicker/BaseExtendedPicker.tsx
Expose clear input on BaseExtendedPicker
=> Add clear input for BaseExtendedPicker

packages/merge-styles/README.md
Missing quote and closing tags for formatting syntax
=> Docs: Fix formatting in merge-styles readme

common/changes/office-ui-fabric-react/master_2018-03-06-15-27.json, packages/office-ui-fabric-react/src/components/Link/Link.styles.ts, packages/office-ui-fabric-react/src/components/Link/__snapshots__/Link.test.tsx.snap
=> Change text color from Highlight to HighlightText in several cases.

common/changes/@uifabric/utilities/master_2018-03-09-00-06.json, common/changes/office-ui-fabric-react/master_2018-03-09-00-06.json, packages/office-ui-fabric-react/src/utilities/decorators/withResponsiveMode.tsx, packages/utilities/src/customizable.tsx, packages/utilities/src/hoistStatics.ts, packages/utilities/src/index.ts
Added `hoistStatics()` function for use with decorators to fix broken statics issue, and added the function to the customizable and withResponsiveMode decorators.
=> Add hoistStatics Function to Utilities Package 

common/changes/@uifabric/variants/phkuo-fixVariantsVersion_2018-03-08-02-36.json, packages/variants/package.json
Fix version of variants package, should start at 1....
(optional)
=> Fix variants version

package.json, rush.json
This will publish `@uifabric/variants`. Also bumps rush.
=> Bumping rush, adjusting config.

apps/todo-app/src/components/TodoForm.tsx, ghdocs/BESTPRACTICES.md, packages/example-app-base/src/components/Highlight/Highlight.tsx, packages/experiments/src/components/CommandBar/CommandBar.base.tsx, packages/experiments/src/components/FloatingPicker/BaseFloatingPicker.tsx, packages/experiments/src/components/SelectedItemsList/SelectedPeopleList/Items/EditingItem.tsx, packages/experiments/src/components/SelectedItemsList/SelectedPeopleList/Items/ExtendedSelectedItem.tsx, packages/experiments/src/components/VirtualizedList/VirtualizedList.tsx, packages/office-ui-fabric-react-tslint/tslint.json, packages/utilities/src/DelayedRender.tsx
=> Prefer inferred types for createRef

packages/experiments/src/components/ExtendedPicker/BaseExtendedPicker.tests.tsx, packages/experiments/src/components/ExtendedPicker/examples/ExtendedPeoplePicker.Basic.Example.tsx, packages/experiments/src/components/SelectedItemsList/SelectedPeopleList/Items/SelectedItemWithContextMenu.tsx, packages/office-ui-fabric-react/src/components/Callout/CalloutContent.base.tsx, packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.tsx, packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.tsx, packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.tsx, packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.types.ts, packages/office-ui-fabric-react/src/components/Coachmark/PositioningContainer/PositioningContainer.tsx, packages/office-ui-fabric-react/src/components/Coachmark/examples/Coachmark.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/ColorPicker/ColorRectangle.tsx, packages/office-ui-fabric-react/src/components/ColorPicker/ColorSlider.tsx, packages/office-ui-fabric-react/src/components/ComboBox/VirtualizedComboBox.tsx, packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.tsx
=> Some more create ref

.github/CODEOWNERS
=> adding carlos perez to owners of file-type-icons

common/changes/@uifabric/utilities/customizable-fix-imprt_2018-03-13-01-14.json, packages/utilities/src/customizable.tsx
Customizable: fix import so it works with AMD. Currently amd will fail because specific files are not given, just the root directory.
(optional)
=> Customizable: fix import so it works with AMD

apps/fabric-website/src/components/Nav/Nav.module.scss, common/changes/@uifabric/fabric-website/left-nav-mobile_2018-03-13-18-48.json
Left nav was showing up in mobile - some recent logic changes must have reverted this. This hides it again.
(optional)
=> Website: Hide left nav on mobile

common/changes/office-ui-fabric-react/magellan-enableTextfieldScroll_2018-03-14-22-27.json, packages/office-ui-fabric-react/src/components/TextField/TextField.scss, packages/office-ui-fabric-react/src/components/TextField/examples/TextField.Multiline.Example.tsx
Enabled cursor events on disabled textfields.
=> TextField: Enabled scroll and resize when disabled

common/changes/office-ui-fabric-react/users-demarcey-linkBaseExport_2018-03-13-19-59.json, packages/office-ui-fabric-react/src/components/Link/index.ts
Export LinkBase from index.ts, so that consumers don't have to have imports like:
**import { LinkBase } from "OfficeFabric/components/Link/Link.base";**
(optional)
=> Add LinkBase to exports.

common/changes/@uifabric/variants/phkuo-fixVariantsImport_2018-03-16-22-09.json, packages/variants/src/variants.ts
change imports so it works with amd
(optional)
=> Variants: fix imports

.github/CODEOWNERS
removing Johanna and adding Sathish.
(optional)
=> removing Johanna from Fabric codeowners, adding Sathish

common/changes/@uifabric/variants/phkuo-addNeutralVariant_2018-03-21-23-26.json, packages/variants/src/index.ts, packages/variants/src/variants.ts
Add the neutral variant. Background is a light shade of gray by default.
(optional)
=> Variants: add neutral variant

common/changes/office-ui-fabric-react/dropdown_2018-03-22-17-22.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx
Fixing a small bug in keypress logic.
=> Dropdown: should use

common/changes/office-ui-fabric-react/aditima-dropdown_2018-03-22-23-33.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx
- [X ] Addresses an existing issue: Fixes #4331
- [X ] Include a change request file using `$ npm run change`
Skip disabled items when keyboarding to find the next item to select
(optional)
=> Dropdown: do not select disabled items on keydown

README.md
/cc @oengusmacinog @dzearing
Adds docs on how to run SSR-like (non-browser) tests that use Fabric components without crashing.
This feels like very specific information that should be in a dedicated .md file other than README.md... but I don't see one about testing Fabric components (the [wiki page](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Testing) seems specific to running tests as a contributor). Would love guidance on where to move in this PR :)
=> Mentioned SSR testing under tests

packages/experiments/src/components/signals/Signal.tsx, packages/experiments/src/components/signals/SignalField.tsx, packages/experiments/src/components/signals/Signals.scss, packages/experiments/src/components/signals/Signals.tsx
This change fixes a couple of minor issues impacting the rendering of `Signals`.
=> Fix errors in Signal styles

common/changes/@uifabric/experiments/signals_2018-03-27-00-11.json
Added a missing change file from the previous Signals change.
=> Fix Signals versioning

.github/CODEOWNERS
=> ChoiceGroup: Adding Sri as codeowner

common/changes/office-ui-fabric-react/fix-searchbox-field-background_2018-04-05-01-38.json, packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.styles.tsx, packages/office-ui-fabric-react/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
Change the SearchBox field background color to `semanticColors.inputBackground`.
=> Fix SearchBox field background color

common/changes/office-ui-fabric-react/jspurlin-FocusTrapZoneAddKeyDownHandler_2018-04-07-01-29.json, packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx, packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.types.ts
Add KeyDown callback (in line with FocusZone)
Verified the keydown handler works as expected
=> FocusTrapZone: Add key down handler

common/changes/@uifabric/experiments/v-vibr-Shimmer-DetailsList-Application_Example_2018-04-10-19-59.json, packages/experiments/src/components/Shimmer/examples/Shimmer.Application.Example.tsx, packages/experiments/src/components/Shimmer/examples/Shimmer.Example.scss
Quick change of the application example in Shimmer page to apply changes in DetailsList.
=> Shimmer: application example page to use DetailsList

common/changes/@uifabric/experiments/fix-experiments_2018-04-11-04-33.json, packages/experiments/src/components/Shimmer/ShimmerLine/ShimmerLine.base.tsx
Shimmerline seems to have added a bad import! :(
=> Experiments has a bad import. Fixing.

common/changes/office-ui-fabric-react/susu-link-style-insterface-fix_2018-03-30-08-45.json, packages/office-ui-fabric-react/src/components/Link/Link.types.ts
If I understand the code correctly, there is a typo in the interface. This PR is to fix it.
=> Link: fix the style interface

.github/stale.yml
Slow down stale bot until we complete our April triage sprint.
=> Slow down stale

common/changes/office-ui-fabric-react/master_2018-04-04-05-56.json, packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardTitle.test.tsx
Added a couple tests for the DocumentCardTitle
(optional)
=> Documentcardtitle title tests

packages/office-ui-fabric-react/src/components/ProgressIndicator/ProgressIndicator.base.tsx, packages/office-ui-fabric-react/src/components/ProgressIndicator/ProgressIndicator.styles.ts, packages/office-ui-fabric-react/src/components/ProgressIndicator/ProgressIndicator.tsx, packages/office-ui-fabric-react/src/components/ProgressIndicator/ProgressIndicator.types.ts, packages/office-ui-fabric-react/src/components/ProgressIndicator/index.ts
- Create styles file.
- Split ProgressIndicator into styled and base file
- Create/expand interfaces
=> ProgressIndicator: convert to mergeStyles - part 1

common/changes/office-ui-fabric-react/fix-index-imports_2018-04-18-16-26.json, packages/office-ui-fabric-react/src/components/Persona/Persona.base.tsx
Fixed an index import in `PersonaCoin`.
=> Fix more index imports

common/changes/office-ui-fabric-react/hotfix-unintended-changes-in-dropdown_2018-04-19-22-49.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.scss
Turns out I accidentally committed a small style change to Dropdown (experimenting with fixing an issue) when doing mass changes to docs.
=> Revert unintended changes in Dropdown from #4512

common/changes/@uifabric/utilities/master_2018-04-20-20-06.json
Added a missing changefile so the inputMask utility could publish.
=> Added changefile for inputmask utility change

common/changes/office-ui-fabric-react/fix-calloutbasic-example_2018-04-20-18-49.json, packages/office-ui-fabric-react/src/components/Callout/examples/Callout.Basic.Example.tsx
=> CalloutExample: Fix basic callout example so it correctly positions.

ghdocs/Contributing/NewComponent.md
=> Fix a typo in NewComponent.md

common/changes/office-ui-fabric-react/revert-list-isEqual-change_2018-04-30-18-45.json, packages/office-ui-fabric-react/src/components/List/List.tsx
Revert using isEqual utility in the List component's shouldComponentUpdate method.
=> Revert isEqual change in List props check

common/changes/office-ui-fabric-react/amyngu-peoplePickerFixes_2018-05-03-22-20.json, packages/office-ui-fabric-react/src/components/ExtendedPicker/BaseExtendedPicker.tsx, packages/office-ui-fabric-react/src/components/FloatingPicker/BaseFloatingPicker.tsx
- Remove requirement that suggestions are shown on focus
- Show suggestions when input is clicked
- Remove unneeded focusZone
- Only validate input for non-empty queryString
=> ExtendedPicker fixes

apps/fabric-website/src/pages/ResourcesPage/ResourcesPage.tsx, common/changes/@uifabric/fabric-website/add-fabric-sketch-toolkit_2018-05-03-23-04.json
Add links to the Fabric sketch toolkit to the resources page.
=> Add fabric sketch toolkit links

apps/ssr-tests/package.json, common/config/rush/npm-shrinkwrap.json, common/config/rush/pinned-versions.json, scripts/package.json
Seems that something went bad in the recent `npm run generate`.
This should fix `npm start`.
=> Fixing npm start.

apps/fabric-website/package.json, apps/ssr-tests/package.json, apps/test-bundle-button/package.json, apps/todo-app/package.json, apps/vr-tests/package.json, packages/example-app-base/package.json, packages/experiments/package.json, packages/file-type-icons/package.json, packages/icons/package.json, packages/jest-serializer-merge-styles/package.json, packages/merge-styles/package.json, packages/office-ui-fabric-react-tslint/package.json, packages/office-ui-fabric-react/package.json, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx, packages/styling/package.json, packages/utilities/package.json, packages/variants/package.json, scripts/package.json
Manual bump all non-published packages to 6.0
=> Manual bump all non-published packages to 6.0

common/changes/office-ui-fabric-react/remove-positioningdeprecations_2018-05-06-19-54.json, packages/office-ui-fabric-react/src/components/Callout/Callout.tsx, packages/office-ui-fabric-react/src/components/Callout/Callout.types.ts, packages/office-ui-fabric-react/src/components/Callout/CalloutContent.base.tsx, packages/office-ui-fabric-react/src/components/Callout/CalloutContent.styles.ts, packages/office-ui-fabric-react/src/components/Coachmark/PositioningContainer/PositioningContainer.tsx, packages/office-ui-fabric-react/src/components/Coachmark/PositioningContainer/PositioningContainer.types.ts, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.styles.ts, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts, packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Customization.Example.tsx, packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Icon.Example.tsx, packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts, packages/office-ui-fabric-react/src/utilities/positioning/positioning.types.ts
Remove all the deprecated props from positioning and associated components
(optional)
=> Remove positioningdeprecations

common/changes/office-ui-fabric-react/joschect-fix-gapspace_2018-05-10-23-06.json, packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts, packages/office-ui-fabric-react/src/utilities/positioning/positioning.types.ts
Fixes an issue where callouts wouldn't position properly if they had no beak.
(optional)
=> Positioning: Fix gapspace

common/changes/office-ui-fabric-react/pivot-fix_2018-05-15-06-12.json, packages/office-ui-fabric-react/src/components/Pivot/Pivot.base.tsx
Addresses #4827.
It seems that pivots aren't rendering in minified scenarios. Addressing.
=> Pivot fix for minified scenarios

common/changes/@uifabric/experiments/ahackett-atpicon515_2018-05-15-18-07.json, packages/experiments/src/components/signals/Signals.tsx
=> Use new icon for MalwareDetected signal icon

common/changes/@uifabric/experiments/master_2018-05-15-20-33.json, packages/experiments/src/components/Nav/Nav.styles.ts, packages/experiments/src/components/Nav/Nav.tsx, packages/experiments/src/components/Nav/NavToggler.tsx, packages/experiments/src/components/Nav/SlimNav.tsx
Description of changes
Added support to navigate expanded Nav component through up and down arrow keys.
Focus areas to test
Keyboard support for the expanded Nav component. Use arrow keys to navigate through the nav items.
=> Experiments/Nav accessibility: keyboard support to navigate through nav items

common/changes/office-ui-fabric-react/fix-some-docs_2018-05-15-19-23.json, packages/office-ui-fabric-react/src/components/SwatchColorPicker/SwatchColorPickerPage.tsx
SwatchColorPicker was using the Spinner markdown files.
=> Fix SwatchColorPicker docs

common/changes/@uifabric/styling/fix-amd-issue_2018-05-16-19-48.json, packages/styling/src/styles/getGlobalClassNames.ts
=> Fix amd issue import issue (#4882)

apps/fabric-website/src/pages/ResourcesPage/ResourcesPage.tsx, common/changes/@uifabric/fabric-website/update-sharepoint-xd-toolkit-link_2018-05-18-22-03.json
=> Update sharepoint xd toolkit link

.github/CODEOWNERS
=> Remove @cschleiden as Rating code owner

common/changes/@uifabric/styling/phkuo-semantics_2018-05-21-23-05.json, common/changes/office-ui-fabric-react/phkuo-semantics_2018-05-21-23-05.json, packages/office-ui-fabric-react/src/common/_semanticSlots.scss, packages/styling/src/interfaces/ISemanticColors.ts, packages/styling/src/styles/theme.ts
Do a little house-cleaning for semantic slots:
- re-order SASS semantic slots to match ISemanticColors
- add in missing semantic slot SASS variables
- put semantic slots in ISemanticColors into the right categories
- correctly deprecate a semantic slot
(optional)
=> Clean up semantic slots

common/changes/@uifabric/variants/phkuo-updateVariants_2018-05-22-16-59.json, packages/variants/src/variants.ts
Update variants algorithm to match newest designs.
(optional)
=> Variants: update algorithm

common/changes/office-ui-fabric-react/fix-stickypane-ie_2018-05-24-23-33.json, packages/office-ui-fabric-react/src/components/ScrollablePane/ScrollablePane.base.tsx
Remove Array.From in to fix it in IE
(optional)
=> StickyPane: fix Array.from in Ie

common/changes/office-ui-fabric-react/amyngu-updateWillReceiveProps_2018-05-29-22-30.json, packages/office-ui-fabric-react/src/components/ExtendedPicker/BaseExtendedPicker.tsx
Update local floatingPickerProps and selectedItemsListProps on receiving new props.
=> [BaseExtendedPicker] Update local properties when receiving props

.github/stale.yml
Stalebot's comments now point to the wiki (previous link now 404's since the md file was removed).
=> Update stalebot comments to point to wiki.

common/changes/office-ui-fabric-react/message-bar-hc_2018-06-01-16-16.json, packages/office-ui-fabric-react/src/components/MessageBar/MessageBar.scss
- Addresses an existing issue: Fixes #4936 
- Include a change request file using `$ npm run change`
- Microsoft Alias (if you have one): 
See issue for full description. 
(optional)
=> MessageBar: More visible HC color for dismiss and expand buttons

.github/ISSUE_TEMPLATE.md
- Addresses an existing issue: Fixes #0000
- Include a change request file using `$ npm run change`
- Microsoft Alias (if you have one): 
Add link to Fabric CodePen template to Issue template.
n/a
=> Add Fabric template to issue template.

package.json
The previous precommit hook caused tslint and prettier to run in parallel which could cause conflicts.
This change corrects that by running tslint after and specify prettier to run for js, json files separately.
=> Precommit fix

.prettierignore, package.json
Remove .json files from prettier
Add `common/changes` to ignored directories
=> Ignore common/changes and don't prettify json files

apps/fabric-website/tslint.json, apps/todo-app/tslint.json, common/changes/@uifabric/example-app-base/deprecation_2018-06-06-06-49.json, common/changes/@uifabric/experiments/deprecation_2018-06-06-06-49.json, common/changes/@uifabric/fabric-website/deprecation_2018-06-06-06-49.json, common/changes/@uifabric/styling/deprecation_2018-06-06-06-49.json, common/changes/@uifabric/utilities/deprecation_2018-06-06-06-49.json, common/changes/office-ui-fabric-react/deprecation_2018-06-06-06-49.json, packages/example-app-base/tslint.json, packages/experiments/tslint.json, packages/office-ui-fabric-react-tslint/tslint.json, packages/office-ui-fabric-react/tslint.json, packages/styling/tslint.json, packages/utilities/tslint.json
This adds it to be on by default, but excludes it in projects. That allows us to remove the exclusions one package at a time and fix issues related.
=> Deprecation lint rule!

packages/experiments/src/components/fluent/styles/FluentStylesPage.tsx, packages/experiments/src/components/fluent/styles/examples/FluentStyles.Basic.Examples.tsx, packages/experiments/src/components/fluent/styles/examples/FluentStylesButton.Basic.Examples.tsx, packages/experiments/src/components/fluent/styles/examples/FluentStylesLink.Basic.Examples.tsx
components for buttons and link for fluent styles example
=> components for buttons and link for fluent styles example

.github/CODEOWNERS
[ ] Addresses an existing issue: Fixes #0000
[ ] Include a change request file using `$ npm run change`
(optional)
=> Add kkjeer as code owner for charting package

common/changes/office-ui-fabric-react/temp-disable-component-example-tests_2018-06-11-18-29.json, packages/office-ui-fabric-react/src/components/ComponentExamples.test.tsx
[ ] Addresses an existing issue: Fixes #0000
[ ] Include a change request file using `$ npm run change`
Temporarily disable component example snapshots until update-snapshot arg is honored.
(optional)
=> Temporarily disable component example snapshot tests

rush.json
In order to assist further development of a better doc site, we need to publish the demo pages.
(optional)
=> publishes the demo package

common/changes/office-ui-fabric-react/move-reset-ids_2018-06-12-23-51.json, packages/office-ui-fabric-react/src/components/ComponentExamples.test.tsx, packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Grouped.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Shimmer.Application.Example.tsx.shot
#5053 exposed a minor issue with ID resetting. This PR moves calls to resetId to increase deterministic behavior across code changes. This only affected one snapshot test (Shimmer, which was already merged in with #5053) but will help prevent unnecessary ID thrashing in the future.
n/a
=> Component Example Snapshots: More deterministic ID behavior

apps/demo/webpack.config.js, common/changes/@uifabric/demo/fixprod_2018-06-14-15-37.json
fixes prod build for release
(optional)
=> fixes prod build for release

README.md, scripts/deploy-github-status.js
See #5227 - just updateing readme about windows users
(optional)
=> update readme with warning about windows users on npm 6.1.0

common/changes/office-ui-fabric-react/teams-theme_2018-06-18-20-32.json, packages/office-ui-fabric-react/src/customizations/TeamsCustomizations.tsx
This adds a placeholder Teams customization set as an example.
=> Adding teams theme

common/changes/office-ui-fabric-react/amyngu-fixClearInput_2018-06-19-22-18.json, packages/office-ui-fabric-react/src/components/ExtendedPicker/BaseExtendedPicker.tsx
Fix clear input, as we should be calling into the autofill clear, to correctly set the autofill display text
=> BaseExtendedPicker: Fix clear input

common/changes/@uifabric/experiments/ChoiceGroupStylesProps_2018-06-20-20-51.json, packages/experiments/src/components/fluent/FluentStyles.ts
Updated ChoiceGroup FluentStyles to include 'checked' style prop
=> Updated ChoiceGroup FluentStyles to include style props

common/changes/@uifabric/experiments/fluentstyles-rating-slider_2018-06-20-22-19.json, packages/experiments/src/components/fluent/FluentStyles.ts, packages/experiments/src/components/fluent/styles/FluentStylesPage.tsx, packages/experiments/src/components/fluent/styles/examples/FluentStyles.Rating.Example.tsx, packages/experiments/src/components/fluent/styles/examples/FluentStyles.Slider.Example.tsx
Added examples for slider and rating to FluentStyles page.  No styles changes.
Also, cleaned up FluentStyles.ts comments.
=> Fluent experiment: Slider, Rating

common/changes/@uifabric/experiments/fluentstyles-label_2018-06-20-21-35.json, common/changes/office-ui-fabric-react/fluentstyles-label_2018-06-20-21-35.json, packages/experiments/src/components/fluent/FluentStyles.ts, packages/experiments/src/components/fluent/styles/FluentStylesPage.tsx, packages/experiments/src/components/fluent/styles/examples/FluentStyles.Label.Example.tsx, packages/office-ui-fabric-react/src/components/Label/Label.tsx
Updated Label component to take styles through getStyles function, and added example in experiments to demonstrate applying Fluent styles on Label.
=> Fluent experiment: Label

common/changes/office-ui-fabric-react/textfield-color_2018-06-21-20-55.json, packages/office-ui-fabric-react/src/components/TextField/TextField.scss
Fixes placeholder color for TextField.
=> Textfield placeholder color adjusted

common/changes/office-ui-fabric-react/messagebar-classnames_2018-06-21-18-54.json, packages/office-ui-fabric-react/src/components/MessageBar/MessageBar.styles.ts, packages/office-ui-fabric-react/src/components/MessageBar/__snapshots__/MessageBar.test.tsx.snap, packages/office-ui-fabric-react/src/components/__snapshots__/MessageBar.Basic.Example.tsx.shot
=> Messagebar classnames

common/changes/office-ui-fabric-react/pivot-fix_2018-06-22-00-25.json, packages/office-ui-fabric-react/src/components/Pivot/Pivot.base.tsx
Pull request checklist:
Addresses an existing issue: Fixes #5101
This addresses the comments so we can close the other PR.
=> Pivot: updating typing check

rush.json
Making the dashboard grid layout available for use with the package, for partner teams who need to use cards to build new dashboard
=> Make dashboard-grid-layout available through package

common/changes/office-ui-fabric-react/remove_extra_space_from_personaInitialsColorToHexCode_magenta_2018-06-22-00-32.json, packages/office-ui-fabric-react/src/components/Persona/PersonaInitialsColor.ts
Remove space from personaInitialsColorToHexCode magenta case
=> Remove space from personaInitialsColorToHexCode magenta case

common/changes/@uifabric/experiments/jg-update-snapshots_2018-06-22-15-29.json, packages/experiments/src/components/Recommendation/__snapshots__/Recommendation.test.tsx.snap
Update experiment snapshots to fix CI issue caused by collision of #5252 and #5261.
n/a
=> Update experiment snapshots

common/changes/office-ui-fabric-react/groupedListAriaLabel_2018-06-18-20-59.json, packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.tsx, packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.types.ts, packages/office-ui-fabric-react/src/components/GroupedList/examples/GroupedList.Custom.Example.tsx
GroupedList: add expandCollapseButtonProps prop to GroupHeader so an aria-label can be included.
=> Grouped list aria label

rush.json
=> Fix shouldPublish flag

common/changes/office-ui-fabric-react/jg-update-snapshots-facepile_2018-06-23-01-32.json, packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.AddFace.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Overflow.Example.tsx.shot
Update snapshots causing CI to fail due to collision of #5320 and #5314.
n/a
=> Update Facepile snapshots

common/changes/@uifabric/charting/master_2018-06-20-23-30.json, packages/charting/src/LineChart.ts, packages/charting/src/components/LineChart/LineChart.base.tsx, packages/charting/src/components/LineChart/LineChart.styles.ts, packages/charting/src/components/LineChart/LineChart.tsx, packages/charting/src/components/LineChart/LineChart.types.ts, packages/charting/src/components/LineChart/LineChartPage.tsx, packages/charting/src/components/LineChart/examples/LineChart.Basic.Example.tsx, packages/charting/src/components/LineChart/examples/LineChart.Styled.Example.tsx, packages/charting/src/components/LineChart/index.ts, packages/charting/src/demo/AppDefinition.tsx, packages/charting/src/index.ts
Line chart addition to charting family
=> Adding Linechart to the charting package

packages/dashboard-grid-layout/src/components/DashboardGridLayout/DashboardGridLayout.tsx, packages/dashboard-grid-layout/webpack.config.js, packages/dashboard-grid-layout/webpack.serve.config.js
The style loader was being used in a way which required users of the library to include the loader as well. Removing the hard dependency.
=> Dashboard grid layout: improved css loading of RGL styling

common/changes/@uifabric/charting/package-fixes_2018-06-28-22-08.json, common/changes/@uifabric/dashboard-grid-layout/package-fixes_2018-06-28-22-08.json, packages/charting/package.json, packages/dashboard-grid-layout/package.json, rush.json
Updating rush.json to enable publishing.
=> Enabling publishing for charting and gridlayout.

common/changes/@uifabric/webpack-utils/noawait_2018-06-29-17-23.json, packages/webpack-utils/src/fabricAsyncLoader.ts
replaced await for ie compat syntax - but still needs promise
(optional)
=> replaced await for ie compat syntax - but still needs promise

common/changes/office-ui-fabric-react/2018-07-03-10-07.json, packages/office-ui-fabric-react/src/components/Pivot/Pivot.base.tsx
Don't consume KeyPress event when it's not needed.
Pivot component.
=> Pivot: Fix Firefox shortcut to change browser tabs

common/changes/@uifabric/dashboard-grid-layout/master_2018-07-03-21-15.json
Change log to trigger dashboard-grid-layout package publish
=> Change log to trigger dashboard-grid-layout package publish

packages/office-ui-fabric-react/src/components/Modal/docs/ModalOverview.md
=> docs: fix sentence in Modal docs

common/changes/office-ui-fabric-react/port-panel-fix-to-5.0_2018-07-05-22-38.json, packages/office-ui-fabric-react/src/components/Callout/__snapshots__/Callout.test.tsx.snap, packages/office-ui-fabric-react/src/components/Popup/Popup.tsx
=> Port panel fix to 5.0

common/changes/@uifabric/experiments/master_2018-07-06-21-41.json, packages/experiments/src/components/Card/Chart/Chart.tsx, packages/experiments/src/components/Card/Chart/Chart.types.ts
Changing imports to point to correct package for charting in Dashboard Card.
(optional)
=> Changing Dataviz charts imports in React Dashboard Card.

common/changes/@uifabric/experiments/miwhea-fluent-depths-update_2018-07-09-15-16.json, packages/experiments/src/components/fluent/FluentDepths.ts, packages/experiments/src/components/fluent/FluentStyles.ts
Updates to the latest Fluent depths and moves these into their own file to match the pattern set by type, colors, etc.
=> Fluent experiment: Update to latest depths

common/changes/office-ui-fabric-react/headerfix_2018-07-10-23-55.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.base.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.styles.ts, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.test.tsx, packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsHeader.test.tsx.snap, packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap, packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsRow.test.tsx.snap
Header for Screener - Flattens styles & apply "px" in a padding def
(optional)
=> Header fix for Screener - Flattens styles & apply "px" in a padding def

common/changes/office-ui-fabric-react/textfield-merge_2018-07-11-06-33.json, packages/office-ui-fabric-react/src/components/TextField/TextField.tsx
There was another super old PR sitting around without a change file. Adding it and fixing a minor issue with it to get it resolved.
=> TextField: now respects id prop.

apps/vr-tests/src/stories/CommandBar.stories.tsx, common/changes/office-ui-fabric-react/commandbar-iconOnly_2018-07-10-23-13.json, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.base.tsx
Setting text as undefined rather than empty string 
Also updated visual tests to catch icononly styling
(optional)
=> Commandbar icon only

common/changes/@uifabric/experiments/chartbug_2018-07-11-23-03.json, packages/experiments/src/components/Card/Chart/Chart.tsx, packages/experiments/src/components/Card/Chart/Chart.types.ts, packages/experiments/src/components/Card/examples/Card.Large.Basic.Example.tsx
Fixed imports in card and added horizontal bar chart support
=> Card: fix import and consume horizontal chart

common/changes/@uifabric/dashboard/rglstyling_2018-07-13-21-43.json, packages/dashboard/config/pre-copy.json, packages/dashboard/src/components/Card/Card.styles.ts, packages/dashboard/src/components/Card/Card.tsx, packages/dashboard/src/components/Card/Card.types.ts, packages/dashboard/src/components/Card/CardFrame/CardFrame.styles.ts, packages/dashboard/src/components/Card/CardFrame/CardFrame.tsx, packages/dashboard/src/components/Card/CardFrame/CardFrame.types.ts, packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayout.css, packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayout.tsx, packages/dashboard/src/components/DashboardGridLayout/examples/DashboardGridLayout.Example.scss
Improved card shadows, added support for href in card titles and more css fixes
=> Dashboard grid layout card shadows, card title href and css fixes

common/changes/office-ui-fabric-react/panel-dismiss_2018-07-13-13-03.json, packages/office-ui-fabric-react/src/components/Panel/Panel.tsx
Cherry-pick Panel fixes to `5.0`.
=> Fix element containment check for Panel light-dismiss (#5552)

common/changes/office-ui-fabric-react/revert-callout-dismiss_2018-07-16-18-24.json, packages/office-ui-fabric-react/src/components/Callout/CalloutContent.base.tsx
This reverts commit 544de4b27714a42cb4c11bb762cd0f6a7ea5367e.
(optional)
=> Revert "Callout blur listener and dismissOnBlur  (#5313)"

common/changes/office-ui-fabric-react/fix-picker-mutatingstate_2018-07-16-23-17.json, packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
Fix an issue where the picker would mutate state by making it setstate explicitly.
(optional)
=> BasePicker: Fix state mutation by making it an explicit state change.

common/changes/office-ui-fabric-react/details-accessibility_2018-06-01-20-15.json, common/changes/office-ui-fabric-react/details-accessibility_2018-06-20-22-18.json, packages/office-ui-fabric-react/src/components/Check/Check.scss, packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts, packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsRowFields.tsx, packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsHeader.test.tsx.snap, packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
The DetailsList fixes for accessibility are missing int he 5.0 release of Fabric.
=> Port DetailsList accessibility fixes to 5.0

common/changes/office-ui-fabric-react/amyngu-fixFloatingPickerBugs_2018-07-17-19-06.json, packages/office-ui-fabric-react/src/components/FloatingPicker/BaseFloatingPicker.tsx, packages/office-ui-fabric-react/src/components/FloatingPicker/Suggestions/SuggestionsControl.tsx
- Remove updateSuggestionsVisible on updateSuggestionWithZeroState
- Change suggestionsControl to store internal state for suggestions, so on willRecieveProps we can update the selected item with the new suggestions accordingly
=> FloatingPicker: fix a few bugs

scripts/deploy-github-status.js
changed the deploy message to be the right URL
(optional)
=> changed the deploy message to be the right URL

common/changes/office-ui-fabric-react/combobox-directionHintFixedFalse_2018-07-20-18-00.json, packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
Combobox: Dropdown will now \"drop up\" if there isn't enough space below
(optional)
=> Combobox direction hint fixed false

common/changes/office-ui-fabric-react/amyngu-fixAriaExpanded_2018-07-20-17-02.json, packages/office-ui-fabric-react/src/components/ExtendedPicker/BaseExtendedPicker.tsx, packages/office-ui-fabric-react/src/components/__snapshots__/ExtendedPeoplePicker.Basic.Example.tsx.shot
Fix aria-expanded for BaseExtendedPicker
=> Fix aria-expanded for BaseExtendedPicker

common/changes/office-ui-fabric-react/textfield-searchOnEmpty_2018-07-20-20-01.json, packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.base.tsx, packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.test.tsx, packages/office-ui-fabric-react/src/components/SearchBox/examples/SearchBox.FullSize.Example.tsx
=> Textfield search on empty

common/changes/office-ui-fabric-react/fixCoachmarksArrayKey_2018-07-10-17-38.json, packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.tsx
Add key prop to array in render function of Coachmark
(optional)
=> Coachmark: Add key prop to array in render

common/changes/@uifabric/charting/StackedChart_2018-07-12-11-30.json, packages/charting/src/StackedBarChart.ts, packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx, packages/charting/src/components/StackedBarChart/StackedBarChart.styles.ts, packages/charting/src/components/StackedBarChart/StackedBarChart.tsx, packages/charting/src/components/StackedBarChart/StackedBarChart.types.ts, packages/charting/src/components/StackedBarChart/StackedBarChartPage.tsx, packages/charting/src/components/StackedBarChart/examples/StackedBarChart.Basic.Example.tsx, packages/charting/src/components/StackedBarChart/index.ts, packages/charting/src/demo/AppDefinition.tsx
Adding Stacked Bar  chart to charting package
(optional)
=> Adding Stacked Bar  chart to charting package

apps/fabric-website-resources/src/AppDefinition.tsx, common/changes/@uifabric/fabric-website-resources/master_2018-07-23-18-35.json
Fixes an issue with demo website that have a duplicate key in the list of components
(optional)
=> Fixes an issue with demo website that have a duplicate key in the list of components

common/changes/@uifabric/dashboard/fixpackage_2018-07-24-18-52.json, packages/dashboard/webpack.config.js
Dashboard package was pointing to use dashboard-grid-layout package in webpack
=> Fix dashboard package webpack issue

common/changes/office-ui-fabric-react/master_2018-07-24-20-10.json, packages/office-ui-fabric-react/src/components/Facepile/examples/Facepile.Examples.scss
=> Fix issue #5662

.github/CODEOWNERS
Add myself as code owner of apps/fabric-website so I'm notified of pull requests as I work on the site.
=> Make @jordandrako code owner for fabric-website

common/changes/office-ui-fabric-react/commandbar-tooltipprops_2018-07-25-17-42.json, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.base.tsx, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.types.ts
=> Able to pass in tooltipHostProps to commandBar item

common/changes/office-ui-fabric-react/fixStickyFooterDetailsList2_2018-07-25-23-46.json, packages/office-ui-fabric-react/src/components/ScrollablePane/ScrollablePane.base.tsx
Move notifySubscribers to fix Sticky footer with DetailsList
(optional)
=> Fix mutationObserver for ScrollablePane

common/changes/office-ui-fabric-react/cliffkoh-bugfix5680_2018-07-26-18-08.json, packages/office-ui-fabric-react/src/components/Layer/examples/Layer.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/Layer/examples/Layer.Customized.Example.tsx, packages/office-ui-fabric-react/src/components/__snapshots__/Layer.Customized.Example.tsx.shot
Note: bug #5680 does not repro on localhost so I cannot directly test - but I believe this should fix the issue. Also fixed another example that was broken.
(optional)
=> Fix bug #5680 - Layer documentation page busted because of focustrapzone pulling focus

common/changes/@uifabric/charting/chartimports_2018-07-27-21-15.json, packages/charting/src/components/DonutChart/DonutChart.base.tsx, packages/charting/src/components/DonutChart/DonutChart.types.ts, packages/charting/src/components/DonutChart/examples/DonutChart.Basic.Example.tsx, packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx, packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.tsx, packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.types.ts, packages/charting/src/components/HorizontalBarChart/examples/HorizontalBarChart.Basic.Example.tsx, packages/charting/src/components/LineChart/LineChart.base.tsx, packages/charting/src/components/LineChart/LineChart.tsx, packages/charting/src/components/LineChart/LineChart.types.ts, packages/charting/src/components/LineChart/examples/LineChart.Styled.Example.tsx, packages/charting/src/components/PieChart/PieChart.base.tsx, packages/charting/src/components/PieChart/PieChart.tsx, packages/charting/src/components/PieChart/PieChart.types.ts, packages/charting/src/components/PieChart/examples/PieChart.Basic.Example.tsx, packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx, packages/charting/src/components/StackedBarChart/StackedBarChart.tsx, packages/charting/src/components/StackedBarChart/StackedBarChart.types.ts, packages/charting/src/components/StackedBarChart/examples/StackedBarChart.Basic.Example.tsx, packages/charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx, packages/charting/src/components/VerticalBarChart/VerticalBarChart.types.ts, packages/charting/src/components/VerticalBarChart/examples/VerticalBarChart.Basic.Example.tsx
Fixing bad imports and broken theming in some charts
=> Charting: Fixing bad imports and broken theming in some charts

common/changes/@uifabric/foundation/jg-foundation-webpack-config_2018-08-01-17-05.json, packages/foundation/webpack.config.js
Add a webpack config so foundation can be used on CodePen.
n/a
=> Foundation: Add webpack config

common/changes/@uifabric/styling/eventsNewSemanticSlots_2018-07-27-22-42.json, common/changes/@uifabric/variants/eventsNewSemanticSlots_2018-08-01-22-46.json, common/changes/office-ui-fabric-react/eventsNewSemanticSlots_2018-07-27-22-42.json, common/changes/office-ui-fabric-react/eventsNewSemanticSlots_2018-08-01-22-46.json, packages/office-ui-fabric-react/src/common/_semanticSlots.scss, packages/styling/src/interfaces/ISemanticColors.ts, packages/styling/src/styles/theme.ts, packages/variants/src/variants.ts
Adds 5 new semantic slots: actionLink, actionLinkHovered, cardBackground, bodyStandoutBackground, variantBorder
=> New semantic slots (ref: Events WebPart)

common/changes/@uifabric/dashboard/autofontsize_2018-08-01-23-09.json, packages/dashboard/src/components/Recommendation/Recommendation.tsx, packages/dashboard/src/components/Recommendation/__snapshots__/Recommendation.test.tsx.snap, packages/dashboard/src/components/Recommendation/examples/Recommendation.Basic.Example.tsx
Enable recommendation card header text auto sizing by using Auto-FontSize package
(optional)
=> Add auto-fontsize to recommendation card

common/changes/@uifabric/foundation/jg-fix-foundation-dep_2018-08-02-22-16.json, packages/foundation/package.json
Add tslib dependency to Foundation package.
n/a
=> Foundation: Add tslib dependency

common/changes/@uifabric/dashboard/master_2018-08-03-18-55.json, packages/dashboard/src/components/Card/Chart/Chart.tsx, packages/dashboard/src/components/Card/examples/Card.Chart.DonutAndPie.Example.tsx, packages/dashboard/src/components/Card/examples/Card.Chart.LineAndVerticalBar.Example.tsx, packages/dashboard/src/components/Card/examples/Card.Chart.StackedBar.Example.tsx
Passing down card width and height to charts. So that the charts scale themselves accordingly.
=> Passing down card width and height to charts.

common/changes/@uifabric/dashboard/fixbuild_2018-08-03-21-59.json, common/config/rush/npm-shrinkwrap.json, packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayout.types.ts
Dashboard uses react-grid-layout with current layout of type Layout[], updating to fix build
=> Dashboard causing build to break due to type mismatch

.github/CODEOWNERS
=> Remove @cschleiden from CODEOWNERS

common/changes/office-ui-fabric-react/bug5738_2018-08-03-01-34.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx, packages/office-ui-fabric-react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Fixed the issue + added tests.
(optional)
=>  Dropdown: You can no longer use the arrow keys to change the selected items in a  disabled Dropdown. (#5738)

apps/fabric-website-resources/src/AppDefinition.tsx, common/changes/@uifabric/fabric-website-resources/bug5817_2018-08-06-18-04.json
=> Fix duplicate key

common/changes/office-ui-fabric-react/commandBar-focus-disabled_2018-08-06-20-16.json, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.base.tsx
=> Disabled CommandBar are now focusable by default

common/changes/office-ui-fabric-react/dnd_2018-08-04-04-02.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.base.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.styles.ts, packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.ts, packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.types.ts, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.base.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.styles.ts, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.types.ts, packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsHeader.test.tsx.snap, packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap, packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsRow.test.tsx.snap, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.DragDrop.Example.tsx, packages/office-ui-fabric-react/src/components/ThemeGenerator/ThemeGenerator.doc.tsx
Fixes #5791. I cannot repro the first symptom of the border not fading away on my side. I've verified that the gripper didn't show up as you hover. I've addressed here in this PR. The subcomponentstyles function cannot handle hover state as a prop - this state comes from CSS itself. This means we had to do some global name styling for the gripper only.
(optional)
=> fixes the gripper vertical bar disappearance

common/changes/@uifabric/charting/header_2018-08-07-20-33.json, common/changes/@uifabric/dashboard/header_2018-08-07-20-33.json, common/changes/@uifabric/example-app-base/header_2018-08-07-20-33.json, common/changes/@uifabric/experiments/header_2018-08-07-20-33.json, common/changes/@uifabric/fabric-website-resources/header_2018-08-07-20-33.json, common/changes/@uifabric/fabric-website/header_2018-08-07-20-33.json, common/changes/@uifabric/styling/header_2018-08-07-20-33.json, common/changes/@uifabric/variants/header_2018-08-07-20-33.json, common/config/rush/npm-shrinkwrap.json, packages/dashboard/package.json, packages/dashboard/src/components/Card/CardHeader/CardHeader.tsx, packages/dashboard/src/components/Recommendation/Recommendation.tsx, packages/dashboard/src/components/Recommendation/__snapshots__/Recommendation.test.tsx.snap
Update Auto-FontSize package to 1.0.9
(optional)
=> Update Auto-FontSize package to 1.0.9

apps/vr-tests/src/stories/Checkbox.stories.tsx, common/changes/office-ui-fabric-react/bug5816_2018-08-08-18-23.json, packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.base.tsx, packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.styles.ts, packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.types.ts, packages/office-ui-fabric-react/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap, packages/office-ui-fabric-react/src/components/Checkbox/examples/Checkbox.ImplementationExamples.tsx, packages/office-ui-fabric-react/src/components/__snapshots__/Callout.Directional.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Checkbox.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Checkbox.ImplementationExamples.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/ContextualMenu.Directional.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.CustomFooter.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Grouped.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Layer.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Layer.Customized.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Layer.Hosted.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/MarqueeSelection.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Persona.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/ResizeGroup.OverflowSet.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/TagPicker.Basic.Example.tsx.shot
=> Checkbox: Now aligns to spec when text wraps to multiple lines (#5816)

apps/vr-tests/src/stories/Button.stories.tsx, apps/vr-tests/src/stories/Toggle.stories.tsx
=> Fix typos in screener tests

common/changes/@uifabric/styling/default-typography-tests_2018-08-07-18-22.json, packages/styling/src/styles/theme.test.ts
=> Default typography tests

common/changes/office-ui-fabric-react/codepen_2018-08-14-23-14.json, common/config/rush/npm-shrinkwrap.json, package.json, packages/office-ui-fabric-react/package.json, packages/office-ui-fabric-react/webpack.codepen.config.js, scripts/local-codepen.js, scripts/package.json
All we have to do now is:
```
npm run codepen
```
go to codepen to paste in a view script tags and we can test out the changes live on codepen!
(optional)
=> Local WDS instance codepen! 

apps/vr-tests/src/stories/DetailsList.stories.tsx, common/changes/office-ui-fabric-react/detailsListWithGroup_2018-08-14-18-51.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.test.tsx, packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
The `selectionMode` of GroupedLists inside a DetailsList should be `SelectionMode.none` if `checkboxVisibility` is hidden. This PR also adds a unit test.
Before:
After:
=> DetailsList: Group checkboxes should not show if CheckboxVisibility is hidden

common/changes/@uifabric/dashboard/dashboardfixes_2018-08-15-19-26.json, packages/dashboard/src/components/Card/BodyText/BodyText.styles.ts, packages/dashboard/src/components/Card/BodyText/BodyText.tsx, packages/dashboard/src/components/Card/BodyText/BodyText.types.ts, packages/dashboard/src/components/Card/CardFrame/CardFrame.styles.ts, packages/dashboard/src/components/Card/Chart/Chart.tsx, packages/dashboard/src/components/Card/Chart/Chart.types.ts, packages/dashboard/src/components/Card/Layout/Layout.styles.ts, packages/dashboard/src/components/Card/Layout/Layout.tsx, packages/dashboard/src/components/Card/Layout/Layout.types.ts, packages/dashboard/src/components/Card/examples/Card.Chart.MultiStackedBar.Example.tsx, packages/dashboard/src/components/Card/examples/Card.Chart.StackedBar.Example.tsx, packages/dashboard/src/components/Recommendation/Recommendation.styles.ts, packages/dashboard/src/components/Recommendation/Recommendation.tsx, packages/dashboard/src/components/Recommendation/RecommendationPage.tsx, packages/dashboard/src/components/Recommendation/examples/Recommendation.Dlp.Example.tsx, packages/dashboard/src/components/Recommendation/examples/Recommendation.MultiStackedBarChart.Example.tsx, packages/dashboard/src/components/Recommendation/examples/RecommendationExamples.Common.ts, packages/dashboard/src/components/Recommendation/examples/index.ts
1. Fix body text styles and card frame overflow
2. Include lastupdatedon text for dataviz component
3. Update recommendation card component based on latest card frame
4. Add Recommendation card examples with MultiStackedBarChart.
=> M365 Dashboard card styling changes

common/changes/office-ui-fabric-react/jg-fix-array-find_2018-08-16-16-01.json, packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.base.tsx
Fix bug that errors on Array.find as it does not exist in IE11.
=> ChoiceGroup: Replace Array.find usage

common/changes/@uifabric/dashboard/ThumbnailListTargetIssueFix_2018-08-16-11-48.json, packages/dashboard/src/components/Card/ThumbnailList/ThumbnailList.styles.ts
Thumbnail List click target sizes Issue fix
=> Thumbnail List hover target width issue fix

common/changes/office-ui-fabric-react/multiexport_2018-08-17-17-05.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.ts
Fixes #5971 by removing extra export
(optional)
=> remove extra export that is not needed inside DetailsList

common/changes/@uifabric/variants/removeOpacityFunctionFromVariants_2018-08-17-19-51.json, packages/variants/src/variants.ts
Removes opacity function and import from color utilities from variants.ts. Temporary fix to address bundle size regression for ODSP
=> Remove opacity function from variants

common/changes/@uifabric/variants/removeOpacityFunctionFromVariants_2018-08-17-19-51.json, packages/variants/src/variants.ts
Cherry picked from https://github.com/OfficeDev/office-ui-fabric-react/pull/5978
=> Remove opacity function from variants5.0

common/changes/office-ui-fabric-react/button-styles-updates_2018-08-21-18-52.json, packages/office-ui-fabric-react/src/components/Button/BaseButton.classNames.ts, packages/office-ui-fabric-react/src/components/Button/Button.types.ts
Added labelHovered and fixed menuIconCheckedHovered ButtonStyles
(optional)
=>  Added labelHovered and fixed menuIconCheckedHovered ButtonStyles

common/changes/office-ui-fabric-react/commandbar-docs_2018-08-21-18-06.json, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.types.ts, packages/office-ui-fabric-react/src/components/CommandBar/examples/CommandBar.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/CommandBar/examples/CommandBar.ButtonAs.Example.tsx, packages/office-ui-fabric-react/src/components/__snapshots__/CommandBar.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/CommandBar.ButtonAs.Example.tsx.shot
Addition work is needed to fix original issue, but out of the scope of shield. That issue is #6015
(optional)
=> Commandbar docs

common/changes/@uifabric/dashboard/bugFixCard_2018-08-22-04-11.json, packages/dashboard/src/components/Card/ActionBar/ActionBar.tsx, packages/dashboard/src/components/Card/ActionBar/ActionBar.types.ts, packages/dashboard/src/components/Card/BodyText/BodyText.styles.ts, packages/dashboard/src/components/Card/CardFrame/CardFrame.styles.ts, packages/dashboard/src/components/Card/CardFrame/CardFrame.tsx, packages/dashboard/src/components/Card/CardFrame/CardFrame.types.ts, packages/dashboard/src/components/Card/CardHeader/CardHeader.styles.ts, packages/dashboard/src/components/Card/Layout/Layout.styles.ts, packages/dashboard/src/components/Card/Layout/Layout.tsx, packages/dashboard/src/components/MultiCount/MultiCountStyles.ts
CSS changes to card components. Fixing font issues and other components content and flex issues.
(optional)
=> Bug fix card

common/changes/office-ui-fabric-react/picker-accessibilityfixes_2018-08-17-22-09.json, packages/office-ui-fabric-react/src/components/__snapshots__/PeoplePicker.Types.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/TagPicker.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/pickers/BasePicker.test.tsx, packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx, packages/office-ui-fabric-react/src/components/pickers/BasePicker.types.ts, packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx, packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.types.ts, packages/office-ui-fabric-react/src/components/pickers/Suggestions/SuggestionsController.ts, packages/office-ui-fabric-react/src/components/pickers/Suggestions/__snapshots__/Suggestions.test.tsx.snap, packages/office-ui-fabric-react/src/components/pickers/__snapshots__/BasePicker.test.tsx.snap
1. Fixes the first element not being read off.
2. Fixes tabbing through the picker and having the first item automatically suggestions
3. Fixes problem where a user couldn't tell what items were already selected.
4. Fixes an issue where scan mode wouldn't correctly navigate to the list element.
5. Fixes the suggestion classname props not being passed all the way through.
6. Fixes the pickers so it is now correctly labeled as a combobox.
Also, removes the wait time for the loading icon to appear, it will now appear immediately instead of first waiting a few miliseconds. This makes it appear to work more cleanly.
Things that should already work: 
1. Being able to add an aria-label to the input element will fix an issue when instructions are not read out. Add the aria-label to input props. …
=> A variety of picker fixes

common/changes/@uifabric/dashboard/HeaderCSSFix_2018-08-22-21-08.json, packages/dashboard/src/components/Card/Layout/Layout.styles.ts
CSS fix for header component of the card
(optional)
=> Header css fix

common/changes/@uifabric/dashboard/fontFixForCard_2018-08-22-21-33.json, packages/dashboard/src/components/Card/CardFrame/CardFrame.styles.ts, packages/dashboard/src/components/MultiCount/MultiCountStyles.ts
font fix for card components
(optional)
=> Font fix for card

common/changes/@uifabric/dashboard/rollingBackActionBarPrimaryFeature_2018-08-23-17-17.json, packages/dashboard/src/components/Card/ActionBar/ActionBar.tsx, packages/dashboard/src/components/Card/ActionBar/ActionBar.types.ts
Rolling back primary action functionality of the action bar.
(optional)
=> Rolling back action bar primary feature

apps/fabric-website-resources/package.json, common/changes/@uifabric/charting/master_2018-08-23-02-06.json, common/changes/@uifabric/fabric-website-resources/master_2018-08-23-02-06.json, common/changes/@uifabric/utilities/master_2018-08-23-02-06.json, common/changes/office-ui-fabric-react/master_2018-08-23-02-06.json, packages/charting/package.json, packages/office-ui-fabric-react/package.json, packages/utilities/package.json
=> Fix too restrictive @types/prop-types that are also incorrectly listed as dependencies

common/changes/@uifabric/merge-styles/Issue-6069_2018-08-24-15-46.json, packages/merge-styles/src/IRawStyleBase.ts
Adds `justifySelf` to `IRawStyleBase`
First attempt at PR for this project, my excuses in case I've missed something.
=> Adds 'justifySelf' to IRawStyleBase (Fixes #6069)

common/changes/@uifabric/styling/5.0_2018-08-24-12-56.json, common/changes/@uifabric/variants/5.0_2018-08-24-12-56.json, common/changes/office-ui-fabric-react/5.0_2018-08-24-12-56.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.scss, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.tsx
Column drag drop drop hint ICON change
Cherry picking changes from below PR:
https://github.com/OfficeDev/office-ui-fabric-react/pull/5835/files
=> Drophint ICON change for column drag and drop

common/changes/office-ui-fabric-react/stickyCurrElemNullCheck_2018-08-24-23-59.json, packages/office-ui-fabric-react/src/components/Sticky/Sticky.tsx
`currElem` needs another null check, since the while updates it.
=> Sticky: currElem null check

common/changes/@uifabric/variants/variantThemeFunctionFix_2018-08-23-16-57.json, packages/variants/src/variants.ts
Fixes makeThemeFromPartials function to create theme in steps, so:
1. Updates palette with variant logic
2. Updates semantic slots using values from updated variant palette
3. Fills rest of the theme in
Tested creating neutral and strong variants, verified correct values for bodyBackground (explicitly defined exception to palette logic) and link (should follow palette logic)
=> Variant Theme creation fix

common/changes/@uifabric/variants/variantThemeFunctionFix5.0_2018-08-27-16-17.json, common/changes/@uifabric/variants/variantThemeFunctionFix_2018-08-23-16-57.json, packages/variants/src/variants.ts
Cherry picked from https://github.com/OfficeDev/office-ui-fabric-react/pull/6047
=> Variant theme function fix5.0

common/changes/@uifabric/dashboard/fixCssIssuesCard_2018-08-27-21-44.json, packages/dashboard/src/components/Card/ActionBar/ActionBar.styles.ts, packages/dashboard/src/components/Card/CardFrame/CardFrame.styles.ts
CSS fix for dashboard card component. Changes to action bar overflow button and card title in the card frame.
(optional)
=> Fix css issues card

apps/vr-tests/src/stories/DocumentCard.stories.tsx, common/changes/office-ui-fabric-react/documentcard-icon_2018-08-27-17-06.json, packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCard.scss, packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardActions.tsx
updates to view count icon spacing to spec in documentcard
(optional)
=> [DocumentCard] updates to view count icon spacing to spec in documentcard

common/changes/office-ui-fabric-react/combobox_2018-08-28-22-15.json, packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.styles.ts, packages/office-ui-fabric-react/src/components/ComboBox/__snapshots__/ComboBox.deprecated.test.tsx.snap, packages/office-ui-fabric-react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap, packages/office-ui-fabric-react/src/components/__snapshots__/ComboBox.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/ComboBox.CustomStyled.Example.tsx.shot
makes the input field styled by theme colors
(optional)
=> makes the input field styled by theme colors

common/changes/@uifabric/experiments/miwhea-fluent-color-updates_2018-08-28-17-58.json, packages/experiments/src/components/fluent/FluentColors.ts
Adds three new colors and corrects the `red30` name to `red20`.
=> Fluent experiment: Update Shared palette

common/changes/@uifabric/charting/donutChartWithLegends_2018-08-28-16-46.json, common/changes/@uifabric/dashboard/donutChartWithLegends_2018-08-28-16-46.json, packages/charting/src/components/DonutChart/Arc/Arc.styles.ts, packages/charting/src/components/DonutChart/Arc/Arc.tsx, packages/charting/src/components/DonutChart/Arc/Arc.types.ts, packages/charting/src/components/DonutChart/DonutChart.base.tsx, packages/charting/src/components/DonutChart/DonutChart.styles.ts, packages/charting/src/components/DonutChart/DonutChart.types.ts, packages/charting/src/components/DonutChart/DonutChartPage.tsx, packages/charting/src/components/DonutChart/Pie/Pie.tsx, packages/charting/src/components/DonutChart/Pie/Pie.types.ts, packages/charting/src/components/DonutChart/examples/DonutChart.Basic.Example.tsx, packages/charting/src/components/DonutChart/examples/DonutChart.Dynamic.Example.tsx, packages/charting/src/components/DonutChart/index.ts, packages/charting/src/components/Legends/Legends.base.tsx, packages/charting/src/components/Legends/Legends.types.ts, packages/charting/src/components/Legends/examples/LegendsBasicExample.tsx, packages/charting/src/components/Legends/examples/LegendsOverflowExample.tsx, packages/dashboard/src/components/Card/CardPage.tsx, packages/dashboard/src/components/Card/Chart/Chart.tsx, packages/dashboard/src/components/Card/examples/Card.Chart.Donut.Example.tsx, packages/dashboard/src/components/Card/examples/Card.Chart.DonutAndPie.Example.tsx
Donunt Chart with legend and hover behavior 
(optional)
=> Donut chart with legends

common/changes/@uifabric/experiments/master_2018-08-23-18-17.json, common/changes/office-ui-fabric-react/master_2018-08-23-18-17.json, packages/experiments/src/components/fluent/styles/examples/FluentStyles.Checkbox.Example.tsx, packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.test.tsx, packages/office-ui-fabric-react/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap, packages/office-ui-fabric-react/src/components/Checkbox/examples/Checkbox.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/Checkbox/examples/Checkbox.ImplementationExamples.tsx, packages/office-ui-fabric-react/src/components/__snapshots__/Checkbox.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Checkbox.ImplementationExamples.tsx.shot
=> [Accessibility] Checkbox: Should use 'aria-labelledby' instead of 'aria-describedby'

common/changes/office-ui-fabric-react/popup_2018-08-29-18-58.json, packages/office-ui-fabric-react/src/components/Panel/Panel.base.tsx, packages/office-ui-fabric-react/src/components/Panel/Panel.doc.tsx, packages/office-ui-fabric-react/src/components/Panel/Panel.types.ts, packages/office-ui-fabric-react/src/components/Panel/examples/Panel.PreventDefault.Example.tsx, packages/office-ui-fabric-react/src/components/Popup/Popup.tsx, packages/office-ui-fabric-react/src/components/__snapshots__/Panel.PreventDefault.Example.tsx.shot
make escape key do prevent default first before calling ondismiss callback
(optional)
=> make escape key do prevent default first before calling ondismiss callback

common/changes/office-ui-fabric-react/master20180828_2018-08-28-10-03.json, packages/office-ui-fabric-react/src/components/DocumentCard/__snapshots__/DocumentCard.test.tsx.snap, packages/office-ui-fabric-react/src/components/Persona/Persona.test.tsx, packages/office-ui-fabric-react/src/components/Persona/PersonaCoin/PersonaCoin.base.tsx, packages/office-ui-fabric-react/src/components/Persona/PersonaCoin/__snapshots__/PersonaCoin.test.tsx.snap, packages/office-ui-fabric-react/src/components/Persona/__snapshots__/Persona.test.tsx.snap, packages/office-ui-fabric-react/src/components/__snapshots__/DocumentCard.Complete.Example.tsx.shot
The callback onRenderCoin, if passed, will be called irrespective of imageUrl being present or not.
This will further decide to render the Image component or not based on imageUrl being present or not.
(optional)
=> onRenderCoin to be called irrespective of  imageUrl being present or not

common/changes/@uifabric/charting/DonutChartAlignIssue_2018-08-30-06-34.json, packages/charting/src/components/DonutChart/DonutChart.base.tsx, packages/charting/src/components/DonutChart/DonutChart.styles.ts, packages/charting/src/components/DonutChart/examples/DonutChart.Basic.Example.tsx, packages/charting/src/components/DonutChart/examples/DonutChart.Dynamic.Example.tsx
Added responsive to donut chat for center alignment.
(optional)
=> Donut chart align issue

common/changes/office-ui-fabric-react/jspurlin-ComboBoxUpdateSelectedStyling_2018-08-30-19-15.json, packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
Fix a regression around determining the selected option which was introduced by PR: #6142 
Verified that the styling is back to rendering correctly when the menu is expanded
=> ComboBox: update isOptionSelected logic to fix styling

common/changes/@uifabric/charting/fixbuild_2018-08-30-22-08.json, common/changes/@uifabric/dashboard/fixbuild_2018-08-30-22-08.json, packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx, packages/charting/src/components/HorizontalBarChart/examples/HorizontalBarChart.Basic.Example.tsx, packages/dashboard/src/components/Card/examples/Card.Large.Basic.Example.tsx
Include a change request file using `$ npm run change`
fixing the usages of horizontalDataPoint; fixes build
(optional)
=> fixing the usages of horizontalDataPoint; fixes build

common/changes/@uifabric/dashboard/CardCSSIssues_2018-08-31-10-23.json, packages/dashboard/src/components/Card/CardFrame/CardFrame.styles.ts, packages/dashboard/src/components/Card/Layout/Layout.styles.ts
Added line Height for card title , removed right padding for contentArea 1 & 2 and added top 13px to contentArea2
(optional)
=> Card css issues

common/changes/@uifabric/dashboard/cardNoHoverWhenDragDisabled_2018-08-30-21-46.json, packages/dashboard/src/components/Card/CardFrame/CardFrame.styles.ts
Removed hover effect from dashboard card title when dragging is disabled.
=> Dashboard: Non-draggable card should not have a hover effect

common/changes/@uifabric/dashboard/sectionsCommon_2018-09-03-10-14.json, packages/dashboard/src/components/Card/Card.types.ts, packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayout.css, packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayout.styles.ts, packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayout.tsx, packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayout.types.ts, packages/dashboard/src/components/DashboardGridLayout/DashboardGridSectionLayout.tsx, packages/dashboard/src/components/DashboardGridLayout/examples/DashboardGridLayout.Sections.Example.tsx, packages/dashboard/src/components/DashboardGridLayout/examples/DashboardGridLayout.SectionsNonCollapse.Example.tsx, packages/dashboard/src/components/Section/EditSections.styles.ts, packages/dashboard/src/components/Section/EditSections.tsx, packages/dashboard/src/components/Section/Section.styles.ts, packages/dashboard/src/components/Section/Section.tsx, packages/dashboard/src/components/Section/Section.types.ts, packages/dashboard/src/components/Section/SectionPage.tsx, packages/dashboard/src/components/Section/SectionTitleTextField.tsx, packages/dashboard/src/components/Section/examples/EditSections.Example.tsx, packages/dashboard/src/components/Section/examples/Section.Basic.Example.tsx, packages/dashboard/src/demo/AppDefinition.tsx, packages/dashboard/src/index.ts, packages/dashboard/src/utilities/DashboardGridLayoutUtils.ts, packages/dashboard/src/utilities/index.ts
Initial checkin to add the edit sections common control.
=> Add and Edit Sections common control

common/changes/@uifabric/charting/DonutChartAlignIssue_2018-08-30-06-34.json, packages/charting/src/components/DonutChart/DonutChart.base.tsx, packages/charting/src/components/DonutChart/DonutChart.styles.ts, packages/charting/src/components/DonutChart/examples/DonutChart.Basic.Example.tsx, packages/charting/src/components/DonutChart/examples/DonutChart.Dynamic.Example.tsx
Donut chart legend overflow issue fixed
=> Donut chart legend overflow issue fixed

common/changes/@uifabric/dashboard/hoverBehaviourMultiCount_2018-09-04-16-48.json, packages/dashboard/src/components/MultiCount/MultiCount.tsx, packages/dashboard/src/components/MultiCount/MultiCount.types.ts, packages/dashboard/src/components/MultiCount/MultiCountStyles.ts
Hover behavior for Multicount component completed, introduced on-click listener on each row and corresponding cursor.
Needs annotation text no-wrap CSS fix and change of icon to SVG.
(optional)
=> Introducing hover behaviour and onclick for multicount component

common/changes/@uifabric/dashboard/multiCountSvg_2018-09-05-01-45.json, packages/dashboard/src/components/MultiCount/MultiCount.tsx, packages/dashboard/src/components/MultiCount/MultiCount.types.ts, packages/dashboard/src/components/MultiCount/MultiCountStyles.ts, packages/dashboard/src/components/MultiCount/NegativeStateChange.ts, packages/dashboard/src/components/MultiCount/NoStateChange.ts, packages/dashboard/src/components/MultiCount/PositiveChangeState.ts
Changing existing fabric icons to SVG's.
(optional)
=> Multi count svg

common/changes/@uifabric/dashboard/master_2018-09-05-17-33.json, packages/dashboard/src/components/Card/Layout/Layout.styles.ts
=> Fix content area clipping in card because of overflow set to hidden

common/changes/@uifabric/dashboard/gridListTextWrapIssue_2018-09-05-06-15.json, packages/dashboard/src/components/Card/GridList/GridList.styles.ts
In gird list text wrap issue is fixed.
(optional)
=> Grid list text wrap issue

common/changes/@uifabric/charting/LineChartHoverIssue_2018-09-05-07-07.json, packages/charting/src/components/LineChart/LineChart.base.tsx, packages/charting/src/components/LineChart/LineChart.styles.ts, packages/charting/src/components/LineChart/examples/LineChart.Multiple.Example.tsx
Line chart hover issue and x-axis text styles.
(optional)
=> Line chart hover issue

common/changes/office-ui-fabric-react/master_2018-09-05-17-43.json, packages/office-ui-fabric-react/src/components/GroupedList/GroupFooter.styles.ts
adding a scope for groupedlist footer link styles
(optional)
=> adding a scope for groupedlist footer link styles

common/changes/@uifabric/dashboard/addSaveProp_2018-09-06-17-23.json, packages/dashboard/src/components/Section/EditSections.tsx, packages/dashboard/src/components/Section/Section.types.ts
=> Add save prop

common/changes/@uifabric/dashboard/horizentalbarchartdashbaord_2018-09-06-09-41.json, packages/dashboard/src/components/Card/Chart/Chart.tsx, packages/dashboard/src/components/Card/examples/Card.Large.Basic.Example.tsx
Horizontal bar chart example page issue fix
(optional)
=> Horizontal bar chart example page issue fix

common/changes/office-ui-fabric-react/choicegroup_2018-09-06-20-06.json, packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.base.tsx, packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.doc.tsx, packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.types.ts, packages/office-ui-fabric-react/src/components/ChoiceGroup/examples/ChoiceGroup.Label.Example.tsx, packages/office-ui-fabric-react/src/components/__snapshots__/ChoiceGroup.Label.Example.tsx.shot
Choicegroup: added a customizable ariaLabelledBy prop
(optional)
=> Choicegroup: added a customizable ariaLabelledBy prop

common/changes/@uifabric/charting/stackedBarChartFixes_2018-09-06-18-52.json, packages/charting/src/components/Legends/Legends.base.tsx, packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx, packages/charting/src/components/StackedBarChart/MultiStackedBarChart.styles.ts, packages/charting/src/components/StackedBarChart/MultiStackedBarChart.types.ts, packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx, packages/charting/src/components/StackedBarChart/StackedBarChart.styles.ts, packages/charting/src/components/StackedBarChart/StackedBarChart.types.ts
Changing interaction behavior between legends and multi-stacked and single stacked bar chart. Changing styling and opacity for interactions.
ISOLATION state:
(optional)
=> Stacked bar chart interaction changes and css modifications

common/changes/office-ui-fabric-react/jspurlin-ComboBoxFixZeroSelectedKey_2018-09-06-22-05.json, packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.test.tsx, packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
This finishes the change that was stated with #5705 and simplifies it a bit. Looks like prettier changed updated formatting as well
Verified that 0 is a valid selectedKey and/or defaultSelectedKey and no other behavior changed. Also added a unit test for this case
=> ComboBox: Allow 0 as a valid selectedKey/defaultSelectedKey

common/changes/office-ui-fabric-react/dropdown_2018-09-06-22-29.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.types.ts, packages/office-ui-fabric-react/src/utilities/selectableOption/SelectableDroppableText.types.ts
Dropdown: making sure the onchange typing is sound with div element attribute
(optional)
=> Dropdown: making sure the onchange typing is sound with div element attribute

common/changes/@uifabric/dashboard/addCardNodes_2018-09-06-22-25.json, packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayout.types.ts, packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayoutPage.tsx, packages/dashboard/src/components/DashboardGridLayout/DashboardGridSectionLayout.tsx, packages/dashboard/src/components/DashboardGridLayout/examples/DashboardGridLayout.Sections.WithCardNodes.Example.tsx, packages/dashboard/src/utilities/DashboardGridLayoutUtils.ts
section dashboard
section dashboard
=> Allow section dashboard to take JSX element as child cards

common/changes/office-ui-fabric-react/nav_2018-09-06-19-08.json, packages/office-ui-fabric-react/src/components/Nav/examples/Nav.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/__snapshots__/Nav.Basic.Example.tsx.shot
Nav: fix nav example to use onLinkClick instead
(optional)
=> Nav: fix nav example to use onLinkClick instead

common/changes/office-ui-fabric-react/jg-fix-master-snapshots_2018-09-07-14-56.json, packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Advanced.Example.tsx.shot
Seems to have been caused by the merge of #6184 which hadn't had a merge in a week.
(optional)
=> Fix master snapshots

common/changes/@uifabric/dashboard/cardTitleColor_2018-09-07-00-32.json, packages/dashboard/src/components/Card/CardFrame/CardFrame.tsx
Changing card title color on active and hover state
(optional)
=> Card title color

common/changes/@uifabric/dashboard/hovercardSizeFix_2018-09-06-19-10.json, packages/dashboard/src/components/MultiCount/MultiCount.tsx, packages/dashboard/src/components/MultiCount/MultiCount.types.ts, packages/dashboard/src/components/MultiCount/MultiCountStyles.ts, packages/dashboard/src/components/MultiCount/examples/MultiCount.Example.tsx
Adding custom message prop for multicount component and adding it to the hover card. Changes to support hovercard height dynamically based on content
(optional)
=> Hovercard size fix

common/changes/@uifabric/dashboard/cardCSSFixes_2018-09-07-16-36.json, packages/dashboard/src/components/Card/CardFrame/CardFrame.tsx
Updating card title line height in card frame.
(optional)
=> Card css fixes

common/changes/@uifabric/dashboard/recommhead_2018-09-07-20-16.json, packages/dashboard/src/components/Recommendation/Recommendation.styles.ts, packages/dashboard/src/components/Recommendation/Recommendation.tsx
=> Update recommendation card header text settings

common/changes/@uifabric/charting/timto-stacked_2018-09-07-05-50.json, packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx, packages/charting/src/components/StackedBarChart/StackedBarChart.types.ts, packages/charting/src/components/StackedBarChart/StackedBarChartPage.tsx, packages/charting/src/components/StackedBarChart/examples/StackedBarChart.BaseBar.Example.tsx
StackedBarChart:
Show bar background if all data point data value is 0 or undefined
(optional)
=> StackBarChart show background if all data point is 0

common/changes/office-ui-fabric-react/key_2018-09-08-20-06.json, packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx
This just gets rid of an extraneous array when returning a normal item
(optional)
=> Fixed Key not found issue with contextualmenu with custom onRender function

common/changes/@uifabric/charting/donutInteractions_2018-09-11-12-06.json, packages/charting/src/components/DonutChart/DonutChart.base.tsx
selected arc highlight and interaction between legend and chart issue fix
(optional)
####Screenshot
=> Donut interactions between legends and chart issue fix 

apps/fabric-website/src/pages/GetStarted/GetStartedPage.tsx, common/changes/@uifabric/fabric-website/patch-1_2018-09-11-19-06.json
=> Fix typo in docs

common/changes/@uifabric/charting/donutChartCalloutFollowBehaviour_2018-09-11-22-31.json, packages/charting/src/components/DonutChart/Arc/Arc.tsx, packages/charting/src/components/DonutChart/DonutChart.base.tsx, packages/charting/src/components/DonutChart/Pie/Pie.tsx
Changes so that the callout component comes next to the cursor. This fixes the flickering issue as well.
(optional)
=> Donut chart callout follow behaviour

common/changes/@uifabric/dashboard/multiCountIconProp_2018-09-12-00-16.json, packages/dashboard/src/components/MultiCount/MultiCount.tsx, packages/dashboard/src/components/MultiCount/MultiCount.types.ts, packages/dashboard/src/components/MultiCount/MultiCountStyles.ts, packages/dashboard/src/components/MultiCount/examples/MultiCount.Example.tsx
Adding prop that disables the change indicator icon. Changed styles accordingly if a user chooses not to display icon.
(optional)
=> Multi count icon prop

common/changes/@uifabric/dashboard/cardBugsFixes_2018-09-11-23-11.json, packages/dashboard/src/components/Card/BodyText/BodyText.styles.ts, packages/dashboard/src/components/Card/Layout/Layout.styles.ts, packages/dashboard/src/components/Card/ThumbnailList/ThumbnailList.styles.ts
bug fixes for body text component, small size card, and thumbnail list.
(optional)
=> Card bugs fixes

common/changes/office-ui-fabric-react/chiechan-addSpinButtonSnapShotTest_2018-09-12-01-00.json, packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.test.tsx, packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx, packages/office-ui-fabric-react/src/components/SpinButton/__snapshots__/SpinButton.test.tsx.snap
Added a snapshot test for the spin button and added simplified SpinButton aria-valuenow logic from previous PR.
The aria valuenow used in spin button still works as intended in project page and we now have snapshot tests.
=> SpinButton: Added SpinButton snapshot and simplified ariaValueNow logic

common/changes/@uifabric/dashboard/multicountCSS_2018-09-12-21-47.json, packages/dashboard/src/components/MultiCount/MultiCount.tsx, packages/dashboard/src/components/MultiCount/MultiCount.types.ts, packages/dashboard/src/components/MultiCount/MultiCountStyles.ts
Changing overflow behavior for the Multicount component.
(optional)
=> overflow behaviour change

common/changes/@uifabric/dashboard/exposeSizeMapping_2018-09-12-17-13.json, packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayout.types.ts, packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayoutBase.tsx, packages/dashboard/src/components/DashboardGridLayout/DashboardGridSectionLayout.tsx, packages/dashboard/src/components/Section/Section.styles.ts, packages/dashboard/src/components/Section/Section.tsx, packages/dashboard/src/components/Section/Section.types.ts, packages/dashboard/src/utilities/DashboardGridLayoutUtils.ts
=> Expose size mapping prop and fix the section title style

common/changes/@uifabric/utilities/vibailly-customizableTypings_2018-09-12-14-19.json, packages/utilities/src/customizable.tsx
Make the customizable class accept stateless components
=> better typing for input of customizable

common/changes/office-ui-fabric-react/arkgupta-DragDropUnitTests_2018-09-10-13-47.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.base.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.test.tsx
Added tests for testing the functionality of column reordering using drag-drop. Added various tests for dragstart, dragover, dragend and drop events.
(optional)
=> Unit tests for testing basic functionalities in drag-drop for column reorder

common/changes/@uifabric/dashboard/chartsFlexBehaviour_2018-09-13-19-22.json, packages/dashboard/src/components/Card/Chart/Chart.styles.ts, packages/dashboard/src/components/Card/Chart/Chart.tsx, packages/dashboard/src/components/Card/Chart/Chart.types.ts
Changing styling of wrapper class element that wraps all the charts in the card component.
(optional)
=> Charts flex behaviour

common/changes/@uifabric/charting/stackedBarChartCallout_2018-09-12-23-50.json, packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx, packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx
Changes to the stacked bar chart, so that callout follows the cursor.
(optional)
=> Stacked bar chart callout

common/changes/@uifabric/dashboard/dashboardCardComponentCSS_2018-09-14-00-57.json, packages/dashboard/src/components/Card/CardHeader/CardHeader.styles.ts, packages/dashboard/src/components/Card/CardHeader/CardHeader.tsx, packages/dashboard/src/components/MultiCount/MultiCount.tsx, packages/dashboard/src/components/MultiCount/MultiCountStyles.ts
Changed CSS for card header. Added tooltip and disabled icon in hovercard of the multicount component upon passing appropriate prop.
(optional)
=> Dashboard card component css

common/changes/@uifabric/dashboard/timto-fixre_2018-09-14-17-58.json, common/changes/@uifabric/dashboard/timto-fixre_2018-09-14-18-19.json, packages/dashboard/src/components/Recommendation/Recommendation.styles.ts, packages/dashboard/src/components/Recommendation/Recommendation.tsx, packages/dashboard/src/components/Recommendation/Recommendation.types.ts, packages/dashboard/src/components/Section/Section.styles.ts
Update Recommendation centerDataVisualization flex layout css
(optional)
=> Update Recommendation centerDataVisualization flex layout css

common/changes/@uifabric/experiments/jg-refactor-foundation_2018-09-13-22-36.json, common/changes/@uifabric/foundation/jg-refactor-foundation_2018-09-13-22-36.json, packages/experiments/src/Foundation.ts, packages/experiments/src/components/CollapsibleSection/CollapsibleSection.ts, packages/foundation/src/createComponent.tsx
Refactor Foundation to remove code duplication, ease props typing, and make option parameter definition more consistent.
=> Foundation: Refactoring

common/changes/office-ui-fabric-react/edwl-2018-09-panelHTMLAttributes_2018-09-17-22-04.json, packages/office-ui-fabric-react/src/components/Panel/Panel.types.ts
Extends Panel props to HTMLAttributes
(optional)
=> Panel: Extend Props to HTMLAttributes

common/changes/@uifabric/dashboard/fixdragonmenubutton_2018-09-20-18-31.json, packages/dashboard/src/components/Card/CardFrame/CardFrame.tsx, packages/dashboard/src/components/DashboardGridLayout/examples/DashboardGridLayout.Sections.Example.tsx
Disabled dragging the card from the menu button and link
=> Fixdragonmenubutton

common/changes/@uifabric/utilities/nidurak-contextualMenuAsV2_2018-09-20-18-47.json, common/changes/office-ui-fabric-react/nidurak-contextualMenuAsV2_2018-09-20-18-47.json, packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.doc.tsx, packages/office-ui-fabric-react/src/components/CommandBar/examples/CommandBar.CommandBarButtonAs.Example.tsx, packages/office-ui-fabric-react/src/components/__snapshots__/CommandBar.CommandBarButtonAs.Example.tsx.shot, packages/utilities/src/IComponentAs.ts
Continuation of https://github.com/OfficeDev/office-ui-fabric-react/pull/6354
Add example of using CommandBarButtonAs with coachmarks and add IComponentAsProps
CommandBar and IComponentAs
=> Add example of using CommandBarButtonAs with coachmarks and add IComponentAsProps

packages/office-ui-fabric-react/src/components/Button/Button.types.ts
Fixes a typo in IButtonStyles rootFocused documentation
=> Fixing typo in IButtonStyles rootFocused documentation

common/changes/@uifabric/dashboard/bugfix_2553886_2018-09-21-09-18.json, packages/dashboard/src/components/Card/CardHeader/CardHeader.styles.ts
change lineHeight for card headerText
(optional)
=>  change lineHeight for card headerText

apps/vr-tests/package.json, apps/vr-tests/screener.local.config.js, common/config/rush/npm-shrinkwrap.json
=> updated screener version, changed local tests to have static branch name

common/changes/office-ui-fabric-react/snapshot_2018-09-21-18-50.json, packages/office-ui-fabric-react/src/components/__snapshots__/CommandBar.CommandBarButtonAs.Example.tsx.shot
a weird build break is occurring because the snapshots are not updated. I believe the regression was introduced here:
https://github.com/OfficeDev/office-ui-fabric-react/commit/5a9d043cf59bcbac41a513f5e2d5c146f162cd9d
(optional)
=> update snapshot to fix build break

common/changes/@uifabric/dashboard/master_2018-09-19-19-44.json, packages/dashboard/src/components/Card/GridList/GridList.styles.ts, packages/dashboard/src/components/Card/GridList/GridList.tsx, packages/dashboard/src/components/Card/GridList/GridList.types.ts
Adding props that take bolding for the content in each cell of gridlist
=> Adding props that take bolding for the content in each cell of gridlist

common/changes/@uifabric/dashboard/cardOverflowIssue_2018-09-26-11-53.json, packages/dashboard/src/components/Card/CardFrame/CardFrame.styles.ts, packages/dashboard/src/components/Card/Layout/Layout.styles.ts
card content overflow issue in edge fix
(optional)
=> Card overflow issue

common/changes/@uifabric/charting/donutChartLegendsPadding_2018-09-26-11-50.json, packages/charting/src/components/DonutChart/DonutChart.base.tsx
donut chart spacing between  legends and chartissue fix
(optional)
=> Donut chart legends padding

common/changes/@uifabric/charting/responsiveLineChart_2018-09-25-23-17.json, packages/charting/src/components/LineChart/LineChart.base.tsx, packages/charting/src/components/LineChart/LineChart.styles.ts, packages/charting/src/components/LineChart/LineChart.types.ts, packages/charting/src/components/LineChart/examples/LineChart.Basic.Example.tsx, packages/charting/src/components/LineChart/examples/LineChart.Multiple.Example.tsx, packages/charting/src/components/LineChart/examples/LineChart.Styled.Example.tsx
1)Making the line chart responsive
2) Correcting flex behavior
3)Smoothing ends of lines to make the intersection between lines smooth
Single line chart with numeric axis:
Single line chart with string axis:
Multiple line chart:
Multiple line chart with isolation state:
(optional)
=> Responsive line chart

common/changes/@uifabric/dashboard/thumbnailListSpacingIssue_2018-09-28-06-46.json, packages/dashboard/src/components/Card/ThumbnailList/ThumbnailList.styles.ts
solved the spacing issue of thumbnail List.
(optional)
=> Thumbnail list spacing issue

common/changes/@uifabric/dashboard/addingCallbacksForInstrumentation_2018-10-01-23-54.json, packages/dashboard/src/components/Card/Card.tsx, packages/dashboard/src/components/Card/Card.types.ts, packages/dashboard/src/components/Card/CardFrame/CardFrame.tsx, packages/dashboard/src/components/Card/CardFrame/CardFrame.types.ts, packages/dashboard/src/components/Card/examples/Card.Chart.LineAndVerticalBar.Example.tsx
Adding callback upon clicking on the card title. This callback is optional and will not disturb the existing cards in any way.
(optional)
=> Adding callbacks for instrumentation

apps/vr-tests/package.json, common/config/rush/npm-shrinkwrap.json
=> Screener bump

common/changes/@uifabric/dashboard/hrefForMulticount_2018-10-03-18-51.json, packages/dashboard/src/components/MultiCount/MultiCount.tsx, packages/dashboard/src/components/MultiCount/MultiCount.types.ts, packages/dashboard/src/components/MultiCount/MultiCountStyles.ts
Adding href for Multicount. Removing row level href and adding a single prop to the entire component.
(optional)
=> Href for multicount

apps/vr-tests/screener.config.js
When new stories are merged into master, the master branch kicks off a build and runs the tests again to create new baselines. By default if there are any new baselines, the job will fail and require a user to go in and accept those changes.  While those changes are waiting to be accepted, all other PRs (which are rebased with master) will have those same errors. This causes a TON of confusion and friction.
Adding "alwaysAcceptBaseBranch" means that these tests will automatically pass and new baselines will be created. Since these baselines were already accepted up PR approval, we do not need this additional gate.
=> Added alwaysAcceptBaseBranch  true

apps/fabric-website/src/components/FluentMessageBar/FluentMessageBar.tsx, apps/fabric-website/src/root.tsx, common/changes/@uifabric/fabric-website/miwhea-add-fluent-message-bar_2018-10-05-20-50.json
Adds a MessageBar to the top of the page linking to the [Fluent for Fabric preview site](https://aka.ms/fabric-preview).
=> Website: Add link to Fluent for Fabric

common/changes/@uifabric/experiments/sidebar-in-index_2018-10-08-18-33.json, packages/experiments/src/index.ts
=> Add sidebar to experiments index file

common/changes/office-ui-fabric-react/master_2018-10-08-18-58.json, packages/office-ui-fabric-react/src/components/Nav/Nav.base.tsx, packages/office-ui-fabric-react/src/components/Nav/Nav.doc.tsx, packages/office-ui-fabric-react/src/components/Nav/Nav.types.ts, packages/office-ui-fabric-react/src/components/Nav/docs/NavDos.md, packages/office-ui-fabric-react/src/components/Nav/examples/Nav.CustomGroupHeaders.Example.tsx, packages/office-ui-fabric-react/src/components/__snapshots__/Nav.CustomGroupHeaders.Example.tsx.shot
Adds a custom group header renderer function property similar to the pattern used by the group links.  Allows for group header customization that can not be done with styling alone.
Group header rendering for nav component
=> Nav: Add custom group header render function property to allow for custom group headers

common/changes/@uifabric/example-app-base/keytip-examples-tidy_2018-10-09-20-00.json, common/changes/office-ui-fabric-react/keytip-examples-tidy_2018-10-09-20-00.json, packages/example-app-base/src/components/ExampleCard/ExampleCard.scss, packages/office-ui-fabric-react/src/components/Keytip/Keytips.doc.tsx, packages/office-ui-fabric-react/src/components/Keytip/docs/KeytipOverview.md, packages/office-ui-fabric-react/src/components/Keytip/examples/Keytips.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/Keytip/examples/Keytips.Button.Example.tsx, packages/office-ui-fabric-react/src/components/Keytip/examples/Keytips.Overflow.Example.tsx, packages/office-ui-fabric-react/src/components/__snapshots__/Keytips.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Keytips.Button.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Keytips.Overflow.Example.tsx.shot
Adds additional spacing within examples (via new ExampleCard utility classes) and clarifies some functionality in the text.
Before:
After:
Before:
After:
=> Keytip: Tidy up examples

common/changes/@uifabric/merge-styles/api-extractor-merge-styles_2018-10-10-18-38.json, packages/merge-styles/etc/merge-styles.api.ts, packages/merge-styles/package.json, packages/merge-styles/src/IRawStyleBase.ts, packages/merge-styles/src/Stylesheet.ts, packages/merge-styles/src/concatStyleSets.ts, packages/merge-styles/src/mergeStyleSets.ts
Enable the api-extractor task for the merge-styles package.
(optional)
=> Api extractor merge styles

common/changes/office-ui-fabric-react/fix-dropdown_2018-09-12-18-16.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx
Fixes the issue where the correctly selected item wouldn't be scrolled to.
(optional)
=> Dropdown: Fix issue where dropdown wouldn't scroll to correct option

common/changes/office-ui-fabric-react/v-vibr-IconButton_Color_2018-09-28-19-52.json, packages/office-ui-fabric-react/src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, packages/office-ui-fabric-react/src/components/Button/IconButton/IconButton.styles.ts, packages/office-ui-fabric-react/src/components/Button/__snapshots__/Button.test.tsx.snap, packages/office-ui-fabric-react/src/components/TeachingBubble/__snapshots__/TeachingBubble.test.tsx.snap, packages/office-ui-fabric-react/src/components/__snapshots__/Breadcrumb.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Breadcrumb.Static.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Button.Icon.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/Button.Split.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/CommandBar.CommandBarButtonAs.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/DocumentCard.Complete.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/MessageBar.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/OverflowSet.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/TextField.CustomRender.Example.tsx.shot
Adding color to IconButton and change the color slot for hovered state as described in issue mentioned above.
Should also fix this [Issue](https://github.com/SharePoint/sp-dev-docs/issues/2350)
@phkuo @betrue-final-final  There are several other states for IconButton in this file... are they up for a change too?
=> IconButton: add color to IconButton so it can be themed.

common/changes/office-ui-fabric-react/shimmerDetailList-export_2018-10-12-15-30.json, packages/office-ui-fabric-react/src/index.ts
=> Added shimmeredDetailList to top level index file

apps/vr-tests/src/stories/Slider.stories.tsx, common/changes/office-ui-fabric-react/master_2018-10-12-04-20.json, packages/office-ui-fabric-react/src/components/Slider/Slider.base.tsx
=> Slider: Support scenario where min and max are the same value

common/changes/@uifabric/merge-styles/joeday-cssGridFixes_2018-10-12-20-25.json, packages/merge-styles/src/IRawStyleBase.ts
Adds properties to complete the CSS Grid spec 
(optional)
=> Add missing CSS Grid properties

.travis.yml, common/config/rush/npm-shrinkwrap.json, scripts/package.json, scripts/tasks/jest.js
=> Adding Codecov integration

common/changes/office-ui-fabric-react/scrollablepane-test_2018-10-15-18-37.json, packages/office-ui-fabric-react/src/components/ScrollablePane/ScrollablePane.base.tsx, packages/office-ui-fabric-react/src/components/ScrollablePane/ScrollablePane.test.tsx, packages/office-ui-fabric-react/src/components/ScrollablePane/__snapshots__/ScrollablePane.test.tsx.snap
Just adding a test... it had NO tests... :(
=> ScrollablePane: added test

packages/tslint-rules/README.md
Some documentation on how to setup tslint-rules
=> Documentation - tslint-rules project setup

common/changes/@uifabric/experiments/micahgodbolt-patch-1_2018-10-16-19-45.json, packages/experiments/README.md
=> Update Experiments README.md

common/changes/office-ui-fabric-react/v-vibr-DetailsHeader_2018-10-16-00-33.json, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.styles.ts, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts, packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap, packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsRow.test.tsx.snap, packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/ShimmeredDetailsList.test.tsx.snap
=> DetailsList: 2 new style regions.

common/changes/office-ui-fabric-react/update-input-aria-activedecent-label_2018-10-15-20-08.json, packages/office-ui-fabric-react/src/components/ExtendedPicker/BaseExtendedPicker.tsx, packages/office-ui-fabric-react/src/components/FloatingPicker/BaseFloatingPicker.tsx, packages/office-ui-fabric-react/src/components/FloatingPicker/Suggestions/SuggestionsControl.tsx, packages/office-ui-fabric-react/src/components/FloatingPicker/Suggestions/SuggestionsCore.tsx, packages/office-ui-fabric-react/src/components/__snapshots__/ExtendedPeoplePicker.Basic.Example.tsx.shot
Update input aria-activedescendant label when user use arrow keys to navigate through the suggestions items, so that the narrator will announce the correct information on the suggestions.
=> update input aria-activedescendant label

common/changes/@uifabric/theme-samples/jg-fix-release-build_2018-10-18-19-00.json, packages/theme-samples/src/index.ts
Fix release build errors exposed by version script by adding index file:
```
2018-10-18T12:17:49.2432263Z (undefined) Entry module not found: Error: Can't resolve './lib/index.js' in 'D:\a\1\s\packages\theme-samples'
2018-10-18T12:17:49.2436353Z (undefined) Entry module not found: Error: Can't resolve './lib/index.js' in 'D:\a\1\s\packages\theme-samples'
2018-10-18T12:17:49.2436928Z [@uifabric/theme-samples 12:17:49] Error: webpack (1.434s): Webpack failed with 2 error(s).
```
=> Release Build Fix

README.md
=> Add semver policy

apps/vr-tests/src/stories/Panel.stories.tsx
Fix Panel stories so that two snapshots don't have the same name. The second one should be 'click', as it comes after a click event.
=> Panel: Fix Panel Stories

common/changes/office-ui-fabric-react/spinner_5.0_2018-10-19-02-25.json, packages/office-ui-fabric-react/src/components/Spinner/Spinner.styles.tsx
Cherry-pick of #6724.
(optional)
=> 5.0 - Fix spinner vibration

common/changes/@uifabric/fluent-theme/fluent-toggle_2018-10-19-21-34.json, packages/fluent-theme/src/fluent/styles/Toggle.styles.ts
Updates Toggle styles to match the latest design.
=> Fluent Theme: Update Toggle styles

common/changes/@uifabric/fluent-theme/v-vibr-FluentFixes_2018-10-19-21-24.json, packages/fluent-theme/src/fluent/styles/Breadcrumb.styles.ts, packages/fluent-theme/src/fluent/styles/Checkbox.styles.ts, packages/fluent-theme/src/fluent/styles/ChoiceGroupOption.styles.ts, packages/fluent-theme/src/fluent/styles/Dropdown.styles.ts, packages/fluent-theme/src/fluent/styles/TextField.styles.ts
Address some feedback on Dropdown and Breadcrumb
Update styles for TextField
=> Fluent Theme: Add TextField fluent styles plus some fixes

common/changes/@uifabric/fluent-theme/v-vibr-LinkFluent_2018-10-20-00-40.json, packages/fluent-theme/src/fluent/FluentStyles.ts, packages/fluent-theme/src/fluent/styles/Link.styles.ts
Updates the Link styles in fluent package
=> Fluent Theme: updating Link styles

apps/fabric-website-resources/index.html, common/changes/@uifabric/charting/cliffkoh-fixDemoSite_2018-10-23-03-28.json, common/changes/@uifabric/dashboard/cliffkoh-fixDemoSite_2018-10-23-03-28.json, common/changes/@uifabric/experiments/cliffkoh-fixDemoSite_2018-10-23-03-28.json, common/changes/@uifabric/fabric-website-resources/cliffkoh-fixDemoSite_2018-10-23-03-28.json, common/changes/@uifabric/styling/cliffkoh-fixDemoSite_2018-10-23-03-28.json, packages/charting/index.html, packages/dashboard/index.html, packages/experiments/index.html, packages/styling/index.html
My PR in #6766 was a little sloppy and made things worse. Sorry about that. This should fix things. Tested across multiple packages. Will verify with the PR deploy too.
=> Fix demo site not being able to load.

common/changes/office-ui-fabric-react/picker-accessibilityfixes_2018-08-17-22-09.json, packages/office-ui-fabric-react/src/components/__snapshots__/PeoplePicker.Types.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/TagPicker.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/pickers/BasePicker.test.tsx, packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx, packages/office-ui-fabric-react/src/components/pickers/BasePicker.types.ts, packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.scss, packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx, packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.types.ts, packages/office-ui-fabric-react/src/components/pickers/Suggestions/SuggestionsController.ts, packages/office-ui-fabric-react/src/components/pickers/Suggestions/__snapshots__/Suggestions.test.tsx.snap, packages/office-ui-fabric-react/src/components/pickers/__snapshots__/BasePicker.test.tsx.snap
=> Port in accessibility fixes from master

common/changes/@uifabric/fluent-theme/v-vib-RatingFluent_2018-10-23-01-31.json, packages/fluent-theme/src/fluent/FluentStyles.ts, packages/fluent-theme/src/fluent/styles/Rating.styles.ts
Updates the Rating component fluent styles.
=> Fluent Theme: Rating fluent style updates

common/changes/@uifabric/charting/lineChartEdgeCases_2018-10-23-22-36.json, common/changes/@uifabric/dashboard/lineChartEdgeCases_2018-10-23-22-36.json, packages/charting/src/components/LineChart/LineChart.base.tsx, packages/charting/src/components/LineChart/LineChart.types.ts, packages/charting/src/components/LineChart/examples/LineChart.Basic.Example.tsx, packages/charting/src/components/LineChart/examples/LineChart.Multiple.Example.tsx, packages/charting/src/components/LineChart/examples/LineChart.Styled.Example.tsx, packages/dashboard/src/components/Card/Chart/Chart.tsx
Adding support to line chart when a user passes no data to it. Making same changes in Dashboard card component. Removing unwanted div tags in chart wrapper in the card.
(optional)
=> Line chart edge cases

apps/fabric-website-resources/src/AppDefinition.tsx, common/changes/@uifabric/fabric-website-resources/organize-navigation_2018-10-24-15-53.json
Organizes the left navigation for the development site (the one that shows on `npm start` from the root of the project). Moves components from extended to basic and alphabetizes them.
No functional changes.
=> Organize navigation for development site

common/changes/office-ui-fabric-react/master_2018-10-25-04-20.json, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx
=> Add onFocus on dropdown

common/changes/office-ui-fabric-react/correct-typo-in-DocumentCardActivity_2018-10-24-19-37.json, packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardActivity.tsx, packages/office-ui-fabric-react/src/components/DocumentCard/__snapshots__/DocumentCard.test.tsx.snap, packages/office-ui-fabric-react/src/components/__snapshots__/DocumentCard.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/DocumentCard.Compact.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/DocumentCard.Complete.Example.tsx.shot
I fixed a typo Don made me aware of in the DocumentCardActivity component. Since i last touched that line (by reformatting the code style) he reached out to me. 
(optional)
=> Correct typo in document card activity

common/changes/office-ui-fabric-react/updateApi-for-layerProps_2018-10-25-22-48.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts, packages/office-ui-fabric-react/tslint.json, packages/tslint-rules/tslint.json
=> update oufr api for layerProps

common/changes/office-ui-fabric-react/docs-update_2018-10-26-14-12.json, packages/office-ui-fabric-react/src/components/DetailsList/docs/DetailsListOverview.md, packages/office-ui-fabric-react/src/components/List/docs/ListOverview.md
Updates the documentation wrt using the data-is-scrollable attribute for List and DetailsList.
=> List/DetailsList updates to documentation.

.github/CODEOWNERS
Update codeowners file. Unfortunately there doesn't seem to be a way to test this without checking this change in...
=> Update codeowners for Calendar components

common/changes/office-ui-fabric-react/calendarExampleDescriptions_2018-10-30-00-16.json, packages/office-ui-fabric-react/src/components/Calendar/Calendar.doc.tsx
Updates the Calendar descriptions to account for the addition of the year picker.
(optional)
=> Calendar: update example descriptions

common/changes/@uifabric/fluent-theme/v-vibr-SpinButtonConversion_2018-10-30-01-58.json, packages/fluent-theme/src/fluent/FluentStyles.ts, packages/fluent-theme/src/fluent/styles/SpinButton.styles.ts
Adding fluent styles to SpinButton.
=> Fluent Theme: SpinButton fluent styles

common/changes/@uifabric/charting/HoverCard_HorizontalBarChart_2018-10-31-06-38.json, packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx, packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.styles.ts, packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.types.ts
added hover card for horizontal bar chart
(optional)
=> hover card for horizontal bar chart

common/changes/office-ui-fabric-react/jg-remove-warning_2018-11-01-00-51.json, packages/office-ui-fabric-react/src/index.ts
Remove outdated import warning from index file.
=> Remove Import Warning

common/changes/@uifabric/charting/legendsHoverCardUpdate_2018-11-02-00-16.json, packages/charting/src/components/Legends/Legends.base.tsx
Using new props of hovercard for legends component. Removing timeout which was introduced as a temporary fix for scaling of hovercard as per content in it.
(optional)
=> Legends hover card update

common/changes/@uifabric/dashboard/hoverCardFabricFix_2018-11-06-01-09.json, packages/dashboard/src/components/MultiCount/MultiCount.tsx
fixing the change in hovercard behavior caused due to updating fabric version in dashboard package by fabric bot.
(optional)
=> Hover card fabric fix

common/changes/office-ui-fabric-react/nav-linkAs_2018-11-06-22-58.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts, packages/office-ui-fabric-react/src/components/Nav/Nav.base.tsx, packages/office-ui-fabric-react/src/components/Nav/Nav.types.ts
https://codepen.io/micahgodbolt/pen/EOVXGQ?editors=1010
(optional)
=> Nav: Added linkAs to support custom links (including React Router)

common/changes/office-ui-fabric-react/7016-panel_2018-11-07-21-18.json, packages/office-ui-fabric-react/src/components/Panel/docs/PanelDos.md
Just added a bit of doc for panel
(optional)
=> Fixes #6950: adds a doc about mid with of panel

common/changes/@uifabric/charting/linechartPropsUpdate_2018-11-07-22-31.json, common/changes/@uifabric/dashboard/linechartPropsUpdate_2018-11-07-23-11.json, packages/charting/src/components/LineChart/LineChart.base.tsx, packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx, packages/charting/src/components/StackedBarChart/MultiStackedBarChart.types.ts, packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx, packages/charting/src/components/StackedBarChart/StackedBarChart.types.ts, packages/dashboard/src/components/Card/ActionBar/ActionBar.tsx, packages/dashboard/src/components/Card/CardFrame/CardFrame.tsx
Update to line chart to re-render on prop updates and addition of new prop to the stacked and multi-stacked bar chart
(optional)
=> Linechart props update

scripts/create-package.js
The create-package script now adds shouldPublish: false and comments out versionPolicy: 'lockedMajor' in rush.json.
(optional)
=> Create package fix

common/changes/@uifabric/fluent-theme/v-vibr-Pivot_2018-11-08-02-15.json, packages/fluent-theme/src/fluent/FluentStyles.ts, packages/fluent-theme/src/fluent/styles/Pivot.styles.ts
Adds styles for Pivot when it rendered as link. For Tabs currently there are no changes in the toolkit.
=> Fluent Theme: add styles for Pivot

common/changes/office-ui-fabric-react/doccard-focus_2018-11-08-19-17.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts, packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCard.tsx, packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCard.types.ts, packages/office-ui-fabric-react/src/components/DocumentCard/__snapshots__/DocumentCard.test.tsx.snap, packages/office-ui-fabric-react/src/components/__snapshots__/DocumentCard.Basic.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/DocumentCard.Compact.Example.tsx.shot, packages/office-ui-fabric-react/src/components/__snapshots__/DocumentCard.Complete.Example.tsx.shot
- [C] Include a change request file using `$ npm run change`
DocumentCard now has a focus method.
=> DocumentCard: focus method added

common/changes/office-ui-fabric-react/7029-button_2018-11-08-19-11.json, packages/office-ui-fabric-react/src/components/Button/examples/Button.Split.Example.styles.ts, packages/office-ui-fabric-react/src/components/__snapshots__/Button.Split.Example.tsx.shot
button: Updates the example to have a better looking style for custom split button
=> button: Updates the example to have a better looking style for custom split button

common/changes/office-ui-fabric-react/master_2018-11-08-01-50.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts, packages/office-ui-fabric-react/src/components/Facepile/Facepile.base.tsx, packages/office-ui-fabric-react/src/components/Facepile/Facepile.types.ts
- [ x] Include a change request file using `$ npm run change`
Added keytip functionality for personas in Facepile.
Facepile
=> Add keytip to Facepile members

common/changes/office-ui-fabric-react/master_2018-11-08-07-06.json, packages/office-ui-fabric-react/src/components/Persona/PersonaCoin/PersonaCoin.base.tsx
Original the issue was fixed by https://github.com/OfficeDev/office-ui-fabric-react/pull/6584 for version 6.x 
and i created a PR to fix the issue in 5.x
https://github.com/OfficeDev/office-ui-fabric-react/pull/7027
The fix contains in https://github.com/OfficeDev/office-ui-fabric-react/pull/6584 is not good enough in some cases, as a result of that i created this PR to improve it.
=> Improve fix to persona coin initials bug to align with fix for 5.x

common/changes/office-ui-fabric-react/master_2018-11-02-12-50.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts, packages/office-ui-fabric-react/src/components/Dialog/Dialog.base.tsx, packages/office-ui-fabric-react/src/components/Dialog/Dialog.types.ts, packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx, packages/office-ui-fabric-react/src/components/Modal/Modal.types.ts
Allow defining layer props when creating a Dialog or a Modal
=> Modal: Allow defining layer props

common/changes/@uifabric/fluent-theme/fluent-ComboBox_2018-11-09-02-26.json, packages/fluent-theme/src/fluent/styles/ComboBox.styles.ts
Adds fluent styles to ComboBox.
=> Fluent Theme: add fluent styles for ComboBox

common/changes/@uifabric/charting/edgeCasesStackedBarChart_2018-11-13-19-14.json, packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx, packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx
Changes to chart to add an empty bar for the specific use case. Also changes to stacked bar chart to handle Nan and infinity cases.
(optional)
=> Edge cases stacked bar chart

apps/vr-tests/src/stories/ScrollablePane.stories.tsx, common/changes/office-ui-fabric-react/edwl-2018-11-fixScrollablePaneVR_2018-11-15-20-52.json, packages/office-ui-fabric-react/src/utilities/exampleData.ts
Fix screener test to not use randomly generated lorem ipsum text.
(optional)
=> Fix ScrollablePane screener test to not use randomly generated text

common/changes/office-ui-fabric-react/v-vibr-HoverCardDeadCode_2018-11-16-02-52.json, packages/office-ui-fabric-react/src/components/HoverCard/ExpandingCard.styles.ts, packages/office-ui-fabric-react/src/components/HoverCard/PlainCard/PlainCard.styles.ts
Removing the selector targeting the Callout to actually apply the intended style. Needs design signoff as this was in the code for some time and I can't seem to find redlines for this.
Add some screener test before merge to ensure a future regression.
=> HoverCard: remove unnecessary selector.

common/changes/office-ui-fabric-react/master_2018-11-16-03-40.json, packages/office-ui-fabric-react/src/components/ProgressIndicator/ProgressIndicator.styles.ts, packages/office-ui-fabric-react/src/components/ProgressIndicator/__snapshots__/ProgressIndicator.test.tsx.snap, packages/office-ui-fabric-react/src/components/__snapshots__/ProgressIndicator.Indeterminate.Example.tsx.shot
Changes transparent color used in the linear-gradient of the running `backgroundImage` in the indeterminate animation.
**Before:** https://gyazo.com/ea57d644d37847d52da62127b917ac08
**After:** https://gyazo.com/53838b96d204fb2273efa15f79f21ee5
=> ProgressIndicator: fix transparent color for Safari

common/changes/@uifabric/fluent-theme/fluent-CommandBar_2018-11-15-22-30.json, packages/fluent-theme/src/fluent/FluentStyles.ts, packages/fluent-theme/src/fluent/styles/CommandBar.styles.ts
Adding some changes in the height and lateral padding of the `CommandBar` for fluent theme after confirming with @betrue-final-final.
=> Fluent-theme: Add some minor changes to CommandBar as part of fluent effort.

common/changes/office-ui-fabric-react/phkuo-addSassAccent_2018-11-22-00-59.json, packages/office-ui-fabric-react/src/common/_themeOverrides.scss
Add SASS var for accent palette slot.
=> Theming: add SASS var for accent slot

common/changes/office-ui-fabric-react/chf-2018-11-fileCard_expandTimeLog_2018-11-14-21-57.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts, packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.base.tsx, packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.types.ts
=> Add a callback function to log the expand time of hover card

common/changes/office-ui-fabric-react/cliffkoh-doc_2018-11-28-01-47.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts, packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.types.ts
Adds missing documentation to responsiveMode dropdown prop. 
(optional)
=> Add documentation to Dropdown prop

common/changes/office-ui-fabric-react/syncScroll_2018-11-27-13-32.json, packages/office-ui-fabric-react/src/components/Sticky/Sticky.tsx
Calling syncScroll after forceUpdate for sticky
(optional)
=> Sync scroll

common/changes/office-ui-fabric-react/fixCheckboxComment_2018-11-28-21-53.json, packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.base.tsx
Just found this as I was walking through documentation work.
(optional)
=> Checkbox: fix checkbox constructor comment

common/changes/@uifabric/experiments/pagination1113_2018-11-14-01-42.json, packages/experiments/src/Pagination.ts, packages/experiments/src/components/Pagination/PageNumber.tsx, packages/experiments/src/components/Pagination/PageNumber.types.ts, packages/experiments/src/components/Pagination/Pagination.base.tsx, packages/experiments/src/components/Pagination/Pagination.styles.ts, packages/experiments/src/components/Pagination/Pagination.tsx, packages/experiments/src/components/Pagination/Pagination.types.ts, packages/experiments/src/components/Pagination/PaginationPage.tsx, packages/experiments/src/components/Pagination/examples/Pagination.Buttons.Basic.Example.tsx, packages/experiments/src/components/Pagination/examples/Pagination.ComboBox.Example.tsx, packages/experiments/src/components/Pagination/examples/Pagination.Customization.Example.tsx, packages/experiments/src/components/Pagination/examples/Pagination.Customization.Round.Example.tsx, packages/experiments/src/components/Pagination/index.ts, packages/experiments/src/demo/AppDefinition.tsx
initial checkin of pagination control into experiment package
pagination
=> Add Pagination component to @uifabric/experiments

common/changes/@uifabric/styling/2018-11-30-01-38.json, packages/styling/etc/styling.api.ts
#7154 was missing an update to the `styling.api.ts` file.
=> Update styling api file

common/changes/@uifabric/fluent-theme/fluent-persona_2018-12-01-08-47.json, packages/fluent-theme/src/fluent/FluentStyles.ts, packages/fluent-theme/src/fluent/styles/Persona.styles.ts
Adds styles for Persona to the Fluent theme.
=> Fluent theme: Add Persona styles

common/changes/@uifabric/experiments/pagination-export_2018-12-07-04-31.json, packages/experiments/src/index.ts
Can't pull it into codepen without a top level export
=> Pagination: export component from top level export

common/changes/office-ui-fabric-react/rating-icon_2018-12-06-18-26.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts, packages/office-ui-fabric-react/src/components/Rating/Rating.base.tsx, packages/office-ui-fabric-react/src/components/Rating/Rating.types.ts, packages/office-ui-fabric-react/src/components/Rating/examples/Rating.Basic.Example.tsx, packages/office-ui-fabric-react/src/components/__snapshots__/Rating.Basic.Example.tsx.shot
1. Add an optional icon property to RatingStar
2. Pass icon property through from Rating to RatingStar
3. Update documentation to indicate that "FavoriteStarFill" is the default icon value
(optional)
=> Rating icon

common/changes/@uifabric/dashboard/XCompaction_2018-12-07-22-48.json, packages/dashboard/src/components/DashboardGridLayout/DashboardCompaction.ts, packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayout.types.ts, packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayoutBase.tsx
Pull request checklist
Description of changes
Added support to automatically compact cards horizontally whenever there is a change in the card layout.
Focus areas to test
Drag and drop a card and expect the card to be compacted horizontally (to the left)
=> @uifabric\dashboard - Added support to automatically compact cards horizontally

common/changes/office-ui-fabric-react/jg-fix-master-build_2018-12-10-17-52.json, packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.base.tsx
This [commit](https://github.com/OfficeDev/office-ui-fabric-react/commit/e9dbbf09c51976d6258fd60c21d49f3b78508801) broke the build. This PR fixes it.
(optional)
=> Fix Master build

common/changes/@uifabric/example-app-base/jg-fix-example-dropdowns_2018-12-10-22-28.json, packages/example-app-base/src/components/ExampleCard/ExampleCard.tsx
Fix Example dropdown regression in `ExampleCard` due to changes introduced by #7326.
(optional)
=> Examples: Fix dropdowns

common/changes/@uifabric/example-app-base/isCollapsible_2018-12-12-23-28.json, common/changes/office-ui-fabric-react/isCollapsible_2018-12-12-23-28.json, packages/example-app-base/src/components/PropertiesTable/PropertiesTable.tsx, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx, packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Documents.Example.tsx, packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Shimmer.Example.tsx
I noticed that we have "collapsible" in all other places in the code, but we have "isCollapsable" as a property of IColumn (spelled with an "a"), which is not consistent. This PR adds some coherence.
(optional)
=> DetailsList: Add isCollapsible and deprecate isCollapsable

common/changes/@uifabric/dashboard/rtlSupportForDashboardGridLayout_2018-12-14-18-24.json, packages/dashboard/src/components/Card/Card.tsx, packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayoutBase.tsx
Adding RTL support to DGL. Setting card's content to RTL when necessary. 
(optional)
=> Rtl support for dashboard grid layout

common/changes/office-ui-fabric-react/patch-1_2018-12-17-10-08.json, packages/office-ui-fabric-react/src/components/Pivot/docs/PivotDonts.md
=> Correct typo in PivotDonts.md

common/changes/@uifabric/dashboard/setupBannerMinorUpdates_2018-12-20-23-54.json, packages/dashboard/src/components/SetupBanner/SetupBanner.styles.ts, packages/dashboard/src/components/SetupBanner/SetupBanner.tsx, packages/dashboard/src/components/SetupBanner/SetupBanner.types.ts
Dashboard: Minor RTL improvement and bug fix in setup banner
=> Dashboard: Minor RTL improvement and bug fix in setup banner

.github/CODEOWNERS
Adding veeray and chankev as codeowners for Dashboard and charting package.
(optional)
=> adding veeray and chankev as codeowners

apps/vr-tests/src/stories/HorizontalStack.stories.tsx, apps/vr-tests/src/stories/VerticalStack.stories.tsx
=> Fixed typing in Stack story

common/changes/office-ui-fabric-react/focus-zone-respect-keydown_2018-12-27-09-31.json, packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.test.tsx, packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx
Always respect keydown handler even it is inner FoucsZone.
FocusZone keydown logic.
=> Always respect keydown handler even it is inner FoucsZone.

common/changes/office-ui-fabric-react/fix-controlledpicker_2018-12-28-01-49.json, packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
Fix an issue where suggestions wouldn't dismiss with controlled pickers.
(optional)
=> Fix suggestions not dismissing with controlled picker item limit.

apps/vr-tests/package.json, apps/vr-tests/tsconfig.json, scripts/tasks/ts.js
We now run a tsc build which should help catch and prevent #7483.
(optional)
=> Add Tsc build to vr-tests

common/changes/@uifabric/dashboard/tooltipForNav_2018-12-28-09-45.json, packages/dashboard/src/components/Nav/NavLink.tsx, packages/dashboard/src/components/Nav/NavToggler.tsx, packages/dashboard/src/components/Nav/examples/Nav.Example.tsx
Add tooltip for navbar expended button
(optional)
=> Add tooltip for navbar expended button

apps/vr-tests/src/stories/VerticalStack.stories.tsx, common/changes/@uifabric/experiments/stackVRTests_2019-01-03-19-47.json
Stack: Adding vertical stack wrapping test to vr-tests.
=> Stack: Adding vertical stack wrapping test to vr-tests.

common/changes/office-ui-fabric-react/high-contrast-dialog-border_2019-01-04-13-05.json, packages/office-ui-fabric-react/src/components/Dialog/Dialog.styles.ts, packages/office-ui-fabric-react/src/components/Modal/Modal.styles.ts
Fixed typo in `Modal.styles.ts`.
Added similar behavior to `Dialog.styles.ts`.
=> High contrast dialog border

common/changes/office-ui-fabric-react/kisiebel-expose-datepicker-tabindex_2018-12-21-22-41.json, packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts, packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.base.tsx, packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.types.ts
Exposes the tabIndex of the TextField in the DatePicker
=> DatePicker tabIndex
