microsoft/fluentui

- common/changes/office-ui-fabric-react/choicegroup_2019-01-04-02-15.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts
- packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.base.tsx
- packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.types.ts
exposes focus method via IChoiceGroup
ChoiceGroupBase implements IChoiceGroup
(optional)
> adding focus method to ichoicegroup

- common/changes/office-ui-fabric-react/slider-number-format_2019-01-04-19-23.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts
- packages/office-ui-fabric-react/src/components/Slider/Slider.base.tsx
- packages/office-ui-fabric-react/src/components/Slider/Slider.test.tsx
- packages/office-ui-fabric-react/src/components/Slider/Slider.types.ts
- packages/office-ui-fabric-react/src/components/Slider/examples/Slider.Basic.Example.scss
- packages/office-ui-fabric-react/src/components/Slider/examples/Slider.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Slider.Basic.Example.tsx.shot
Addresses #7526.
Introduces a new optional prop on the `Slider` component called `valueFormat`. It is a function that can be used to format the value label.
> Allow number format for slider

- common/changes/office-ui-fabric-react/commandbar2_2019-01-08-19-27.json
- packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.base.tsx
During the codereview of #7557, there was a point that the PR was completely green and I merged before noticing a new block coming through. This PR addresses that last point.
(optional)
> CommandBar: minor perf improvement in computeCacheKey

- common/changes/@uifabric/dashboard/updateGridListCursor_2019-01-08-10-51.json
- packages/dashboard/src/components/Card/GridList/GridList.tsx
update the grid list cursor to pointer when it is clickable.
(optional)
> Update grid list cursor

- .github/CODEOWNERS
Signing @kenotron & @ecraig12345 up for some core build ownership
(optional)
> Add @kenotron and @ecraig12345 as code owners on some core build stuff

- common/changes/office-ui-fabric-react/snapshots_2019-01-12-01-58.json
- packages/office-ui-fabric-react/src/components/pickers/Suggestions/__snapshots__/Suggestions.test.tsx.snap
Somehow a snapshot update was missed in some previous PR, and that was failing all builds. Checking in an updated snapshot.
> Update snapshot which was failing build

- common/changes/office-ui-fabric-react/keco-fix-datepicker-test_2019-01-12-04-29.json
- packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.test.tsx
Fixes failing DatePicker test which uses `document.querySelector`.
(optional)
> Fix failing DatePicker test

- apps/fabric-website/README.md
- common/changes/@uifabric/fabric-website/fabric-website_2019-01-14-22-26.json
Update the instructions for building fabric-website to include `npm run buildfast` to build dependencies.
> Update fabric-website readme

- common/changes/office-ui-fabric-react/documentcard-basic-example-href-change_2019-01-14-18-37.json
- packages/office-ui-fabric-react/src/components/DocumentCard/examples/DocumentCard.Basic.Example.tsx
Changed href in example to bing.com
(optional)
> Changed href in DocumentCard basic example to bing

- package.json
Build: Making npm install build to `@uifabric/experiments` instead of to `@uifabric/fabric-website-resources`.
> Build: Making npm install build to @uifabric/experiments

- common/changes/office-ui-fabric-react/yimwu-documentcard5_2019-01-16-05-41.json
- packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCard.tsx
- packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCard.types.ts
- [X ] Include a change request file using `$ npm run change`
Cherry pick commit 5d4bfd9: DocumentCard: add optional aria role property to allow override the default aria role.
(optional)
> Cherry pick commit 5d4bfd9: DocumentCard: add optional aria role property to allow override the default aria role.

- common/changes/office-ui-fabric-react/miwhea-facepile-listbox_2019-01-17-17-06.json
- packages/office-ui-fabric-react/src/components/Facepile/Facepile.base.tsx
- packages/office-ui-fabric-react/src/components/Facepile/__snapshots__/Facepile.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.AddFace.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Overflow.Example.tsx.shot
Adds the [ARIA listbox role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role) to the list of members.
> Facepile: Add listbox role to members list

- common/changes/@uifabric/experiments/stackDocs_2019-01-17-23-09.json
- packages/experiments/src/components/Stack/Stack.types.ts
Updating `Stack.types` so that props comments meet the standard and addressing feedback that came in API review.
> Stack: Updating Stack.types comments to meet standard

- common/changes/office-ui-fabric-react/kisiebel-callout-prevent-dismiss-on-resize_2019-01-17-21-53.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts
- packages/office-ui-fabric-react/src/components/Callout/Callout.types.ts
- packages/office-ui-fabric-react/src/components/Callout/CalloutContent.base.tsx
Exposes an optional preventDismissOnResize prop for the Callout component
> preventDismissOnResize Callout prop

- common/changes/office-ui-fabric-react/khoa-breadcrumb-border-fix_2019-01-18-01-15.json
- packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.styles.ts
- packages/office-ui-fabric-react/src/components/__snapshots__/Breadcrumb.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Breadcrumb.Static.Example.tsx.shot
see issue comments for more details about the issue.
> Breadcrumb - fixing double rectangle on focus

- common/changes/@uifabric/dashboard/bugfix_2776120_2019-01-18-13-41.json
- packages/dashboard/src/components/Card/ThumbnailList/ThumbnailList.styles.ts
add focus border for thumbnailList
(optional)
####screenshot
> add focus border for thumbnailList

- common/changes/@uifabric/dashboard/bugfix_2775844_2019-01-18-13-51.json
- packages/dashboard/src/components/Card/Layout/Layout.tsx
Remove extra hidden elements in gridList when gridList rows is empty
(optional)
> Remove extra hidden elements in gridList when gridList is empty

- apps/fabric-website/src/components/Nav/Nav.tsx
- common/changes/@uifabric/experiments/jg-more-typing-helpers_2019-01-18-17-12.json
- common/changes/@uifabric/fabric-website/jg-more-typing-helpers_2019-01-18-17-12.json
- packages/experiments/src/components/Accordion/Accordion.styles.ts
- packages/experiments/src/components/Accordion/Accordion.types.ts
- packages/experiments/src/components/Button/Button.types.tsx
- packages/experiments/src/components/CollapsibleSection/CollapsibleSection.types.ts
- packages/experiments/src/components/CollapsibleSection/CollapsibleSectionTitle.styles.ts
- packages/experiments/src/components/CollapsibleSection/CollapsibleSectionTitle.types.ts
- packages/experiments/src/components/CollapsibleSection/examples/CollapsibleSection.Styled.Example.tsx
- packages/experiments/src/components/Persona/Vertical/VerticalPersona.styles.ts
- packages/experiments/src/components/PersonaCoin/PersonaCoin.styles.ts
- packages/experiments/src/components/PersonaCoin/PersonaCoin.types.ts
- packages/experiments/src/components/Toggle/Toggle.types.ts
- packages/experiments/src/components/Toggle/examples/Toggle.Tokens.Function.Example.tsx
- packages/experiments/src/theming/examples/Themes.tsx
I missed some typing helpers in #7711 due to incomplete search criteria. This PR takes care of the rest of them.
(optional)
> Slots/Tokens: More typing helpers

- common/changes/@uifabric/experiments/tile-click_2019-01-22-18-02.json
- packages/experiments/src/components/Tile/Tile.tsx
Enhancement to #7736 offered by @JasonGore to preserve bundle size.
> Optimization for Tile click element selection

- common/changes/@uifabric/dashboard/detailpanel2_2019-01-23-00-37.json
- packages/dashboard/src/components/DetailPanel/Body/ConfirmationResult.tsx
- packages/dashboard/src/components/DetailPanel/Body/DetailPanelPivotBody.tsx
- packages/dashboard/src/components/DetailPanel/Body/DetailTile.tsx
- packages/dashboard/src/components/DetailPanel/Body/MessageBanner.tsx
- packages/dashboard/src/components/DetailPanel/DetailPanel.tsx
- packages/dashboard/src/components/DetailPanel/DetailPanel.types.ts
- packages/dashboard/src/components/DetailPanel/DetailPanelAnalyticsContext.tsx
- packages/dashboard/src/components/DetailPanel/DetailPanelPage.tsx
- packages/dashboard/src/components/DetailPanel/Examples/DetailPanel.L2Content.Example.tsx
- packages/dashboard/src/components/DetailPanel/Examples/DetailPanel.Pivot.Example.tsx
- packages/dashboard/src/components/DetailPanel/Footer/ActionBar.tsx
- packages/dashboard/src/components/DetailPanel/Header/Header.tsx
> DetailPanel: add with analytics handler

- common/changes/@uifabric/dashboard/edwl-2019-01-fixDashboardReadme_2019-01-22-19-35.json
- packages/dashboard/README.md
Fix title of README.md to show correct title of Dashboard.
Fix link to Card component.
(optional)
> Fix title for README.md for dashboard package

- packages/office-ui-fabric-react/src/components/ActivityItem/__snapshots__/ActivityItem.test.tsx.snap
- packages/office-ui-fabric-react/src/components/DocumentCard/__snapshots__/DocumentCard.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Facepile/__snapshots__/Facepile.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Image/Image.styles.ts
- packages/office-ui-fabric-react/src/components/Persona/__snapshots__/Persona.test.tsx.snap
> Fix Image not shown in RTL language.

- common/changes/office-ui-fabric-react/edwl-2019-01-fixCoachmarkMouseMove_2019-01-23-00-11.json
- packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.base.tsx
Changes mouseover event in Coachmark from pageX/Y to clientX/Y
Video below for demonstration:
https://streamable.com/fdbsv
(optional)
> Coachmark: Fix mouseover event to properly expand component's contents

- common/changes/@uifabric/azure-themes/master_2019-01-24-00-37.json
- packages/azure-themes/src/azure/Constants.ts
- packages/azure-themes/src/azure/styles/ComboBox.styles.ts
- packages/azure-themes/src/azure/styles/DropDown.styles.ts
- packages/azure-themes/src/azure/styles/IconButton.styles.ts
Minor styling updates to dropdown / combobox / iconbutton
N/A
> Azure themes - minor styling updates

- common/changes/@uifabric/dashboard/master_2019-01-24-19-15.json
- common/config/rush/shrinkwrap.yaml
- packages/dashboard/package.json
- packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayout.types.ts
- packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayoutBase.tsx
- packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayoutWithAddCardPanel/DashboardGridLayoutWithAddCardPanel.tsx
- packages/dashboard/src/components/DashboardGridLayout/DashboardGridSectionLayout.tsx
- packages/dashboard/src/components/DashboardGridLayout/examples/DashboardGridLayout.DragApi.Example.tsx
- packages/dashboard/src/components/DashboardGridLayout/examples/DashboardGridLayout.Example.tsx
- packages/dashboard/src/components/DashboardGridLayout/examples/DashboardGridLayout.Sections.Example.tsx
- packages/dashboard/src/components/DashboardGridLayout/examples/DashboardGridLayout.Sections.WithCardNodes.Example.tsx
- packages/dashboard/src/components/DashboardGridLayout/examples/DashboardGridLayout.SectionsNonCollapse.Example.tsx
- packages/dashboard/src/components/Section/Section.types.ts
- packages/dashboard/src/components/Section/examples/EditSections.Customization.Example.tsx
- packages/dashboard/src/components/Section/examples/EditSections.Example.tsx
- packages/dashboard/src/utilities/DashboardGridLayoutUtils.ts
I published the forked `react-grid-layout` github repo to `react-grid-layout-fabric`. This is a temporary measure, and I hope that we can reach out to the author to accept our changes in future.
(optional)
> replaced the use of react-grid-layout from a github commit to a published artifact

- common/changes/@uifabric/dashboard/detailpanel3_2019-01-24-21-18.json
- packages/dashboard/src/components/DetailPanel/DetailPanel.Base.tsx
- packages/dashboard/src/components/DetailPanel/Examples/DetailPanel.Pivot.Example.tsx
- packages/dashboard/src/components/DetailPanel/Utils.ts
>  Fix DetailPanel mainContent lifecycle event

- common/changes/@uifabric/fluent-theme/fluent-DropdownFixItems_2019-01-25-01-47.json
- packages/fluent-theme/src/fluent/styles/Dropdown.styles.ts
> Fluent-theme: fixing some misalignment in dropdown items

- common/changes/@uifabric/azure-themes/master_2019-01-25-17-23.json
- packages/azure-themes/src/azure/styles/Panel.styles.ts
- packages/azure-themes/src/azure/styles/TeachingBubble.styles.ts
Minor style changes to azure theme dialog/teachingBubble close button
N/A
> Azure Themes - Additional button color fixes for dialog / teachingbubble

- common/changes/@uifabric/dashboard/DGLCardID_2019-01-23-12-35.json
- packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayoutWithAddCardPanel/DashboardGridLayoutWithAddCardPanel.tsx
- packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayoutWithAddCardPanel/DashboardGridLayoutWithAddCardPanel.types.ts
- packages/dashboard/src/components/DashboardGridLayout/examples/DGLWithAddCardPanel.Example.tsx
- packages/dashboard/src/components/DetailPanel/DetailPanel.styles.ts
Add cardId for dashboardGridLayout onLayoutChange to get which card is added to dashboard
(optional)
>  Add cardId for dashboardGridLayout onLayoutChange

- common/changes/@uifabric/dashboard/detailpanel4_2019-01-28-23-09.json
- packages/dashboard/src/components/DetailPanel/BaseContainer.tsx
- packages/dashboard/src/components/DetailPanel/DetailPanel.styles.ts
- packages/dashboard/src/components/DetailPanel/DetailPanel.types.ts
- packages/dashboard/src/components/DetailPanel/Examples/DetailPanel.Pivot.Example.tsx
- Fix detail panel custom width issue
- Fix detail panel tiles css issue 
- Add jsx.element support to detail panel tile message
(optional)
> DetailPanel fixes

- common/changes/@uifabric/experiments/stackIEBug_2019-01-30-00-59.json
- packages/experiments/src/components/Stack/Stack.styles.ts
- packages/experiments/src/components/Stack/__snapshots__/Stack.test.tsx.snap
Stack: Fixing IE11 wrapping bug reproed in 'Horizontal Stack - Wrapping - Nested' example.
> Stack: Fixing IE11 wrapping bug reproed in 'Horizontal Stack - Wrapping - Nested' example

- common/changes/@uifabric/dashboard/user-v-dikish-optionalIdProps_2019-01-29-23-51.json
- packages/dashboard/src/components/Card/Card.types.ts
- packages/dashboard/src/components/Card/CompoundButtonStack/CompoundButtonStack.types.ts
- packages/dashboard/src/components/Card/GridList/GridList.types.ts
- packages/dashboard/src/components/Card/ThumbnailList/ThumbnailList.types.ts
adding id props to dashboard components for analytics
> Optional Id props

- common/changes/@uifabric/azure-themes/rkessler-updateShimmer_2019-01-31-16-23.json
- packages/azure-themes/src/azure/AzureColors.ts
- packages/azure-themes/src/azure/AzureStyleSettings.ts
- packages/azure-themes/src/azure/AzureThemeDark.ts
- packages/azure-themes/src/azure/AzureThemeLight.ts
- packages/azure-themes/src/azure/IAzureSemanticColors.ts
- packages/azure-themes/src/azure/styles/DocumentCard.styles.ts
- packages/azure-themes/src/azure/styles/Overlay.styles.ts
- [ X] Include a change request file using `$ npm run change`
(optional)
> Azure-themes Package -- add documentcard styles, update shimmer  styling

- common/changes/office-ui-fabric-react/u-mahuangh-types-cleanup_2019-02-01-18-23.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts
- packages/office-ui-fabric-react/src/components/FloatingPicker/BaseFloatingPicker.tsx
- packages/office-ui-fabric-react/src/components/FloatingPicker/Suggestions/SuggestionsCore.tsx
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
Removes a few unnecessary uses of any & unneeded type casts in Extended People Picker
> Clean up some types in ExtendedPicker

- common/changes/@uifabric/dashboard/detailpanel6_2019-02-01-23-11.json
- packages/dashboard/src/components/DetailPanel/DetailPanel.Base.tsx
DetailPanel: fix content load error on L2 content mode
(optional)
> DetailPanel: fix content load error on L2 content mode

- common/changes/office-ui-fabric-react/snapshots_2019-02-05-00-28.json
- packages/office-ui-fabric-react/src/components/__snapshots__/Callout.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ContextualMenu.Persisted.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Fabric.Example.tsx.shot
for some reason snapshot changes were required and was checked in without error.
(optional)
> Snapshots: Fixing build break after snapshot changes

- common/changes/office-ui-fabric-react/hideCommandBarCompositeList_2019-02-02-01-31.json
- packages/dashboard/src/components/CompositeList/CompositeList.styles.ts
- packages/dashboard/src/components/CompositeList/CompositeList.tsx
- packages/dashboard/src/components/CompositeList/CompositeList.types.ts
Hide command bar from CompositeList if no commands exist
> Hide command bar from CompositeList when no commands exist

- common/changes/office-ui-fabric-react/master_2019-02-07-00-18.json
- packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsHeader.test.tsx.snap
Somehow a snapshot got out of date in master and was failing builds. Checking in an updated snapshot.
> Add missing snapshot update to fix build

- common/changes/@uifabric/experiments/verticalpersona_2019-02-07-14-03.json
- packages/experiments/src/components/Persona/Vertical/VerticalPersona.styles.ts
- packages/experiments/src/components/Persona/Vertical/__snapshots__/VerticalPersona.test.tsx.snap
**Before:**
**After:**
(optional)
> Fixed the VerticalPersona not wrapping text properly in IE

- common/changes/@uifabric/date-time/calendar_2019-02-08-16-21.json
- common/changes/office-ui-fabric-react/calendar_2019-02-08-16-21.json
- packages/date-time/src/components/Calendar/Calendar.base.tsx
- packages/date-time/src/components/Calendar/CalendarDay/CalendarDay.base.tsx
- packages/date-time/src/components/Calendar/CalendarMonth/CalendarMonth.base.tsx
- packages/date-time/src/components/Calendar/CalendarYear/CalendarYear.base.tsx
- packages/office-ui-fabric-react/src/components/Calendar/Calendar.tsx
- packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx
- packages/office-ui-fabric-react/src/components/Calendar/CalendarMonth.tsx
- packages/office-ui-fabric-react/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap
Calendar: adding type="button" in Calendar buttons so they don't submit by default inside forms
(optional)
> Calendar: adding type="button" in Calendar buttons

- common/changes/office-ui-fabric-react/focuszone-active_2019-02-12-00-45.json
- packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.test.tsx
- packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx
Reverting a change to avoid calling onActiveItemChanged too frequently, and adding tests to make sure it's called.
> Focuszone: onActiveItemChanged now fires

- common/changes/office-ui-fabric-react/issue7503_2019-02-12-06-04.json
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.test.tsx
Adds a unit test covering the scenario reported in #7503.
Note that I cannot actually repro the issue and the codepen provided in #7503 is not a repro of the issue, but regardless add previously non-existent unit tests for precisely this scenario.
Also cleaned up typings and in so doing got rid of some unnecessary use of `!` postfix operator.
(optional)
> Add unit tests and cleanup typings in DetailsList

- common/changes/@uifabric/dashboard/IdForThumbnailItemAction_2019-02-13-13-18.json
- packages/dashboard/src/components/Card/ThumbnailList/ThumbnailList.types.ts
Add Ids for thumbnail item actions
(optional)
> Add Ids for thumbnail item actions

- common/changes/office-ui-fabric-react/jg-7960-dropdown-doc_2019-02-13-19-28.json
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.types.ts
Clarify use of `defaultSelectedKey` vs. `defaultSelectedKeys` props in documentation.
n/a
> Dropdown: Clarify defaultSelectedKeys prop doc

- common/changes/office-ui-fabric-react/keco-detailscolumn-nulls_2019-02-14-01-35.json
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.base.tsx
This removes unnecessary null assertions in `DetailsColumn` to improve code correctness. This is particularly useful as we prepare for refactor. It also helps the community that may be learning by reading OUFR source.
- Branch should compile
- Tests should pass as part of CI
> DetailsColumn: Remove unnecessary null assertions

- apps/fabric-website/src/redirects.ts
- apps/fabric-website/src/root.tsx
- common/changes/@uifabric/fabric-website/redirects_2019-02-14-04-09.json
Because people might still be using old URL links and bookmarks. We need to do redirects.
(optional)
> Redirects defunct URL to new

- common/changes/office-ui-fabric-react/keco-null-assert-2_2019-02-14-17-41.json
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.test.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.CustomFooter.Example.tsx
- packages/office-ui-fabric-react/src/components/List/List.tsx
Follow-up of #7994 which removes the remainder of unnecessary null assertions in the `*List` component, a DetailsList example, and DetailsList test code that do not require code refactor.
- PR CI should succeed
- Build should succeed
> List, DetailsList test, and DetailsList example: Remove unnecessary null assertions

- apps/vr-tests/src/stories/Panel.stories.tsx
- common/changes/office-ui-fabric-react/robv-add_custom_left_panel_2019-02-14-18-14.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts
- packages/office-ui-fabric-react/src/components/Panel/Panel.base.tsx
- packages/office-ui-fabric-react/src/components/Panel/Panel.doc.tsx
- packages/office-ui-fabric-react/src/components/Panel/Panel.styles.ts
- packages/office-ui-fabric-react/src/components/Panel/Panel.types.ts
- packages/office-ui-fabric-react/src/components/Panel/examples/Panel.CustomLeft.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Panel.CustomLeft.Example.tsx.shot
Add support for custom width, left anchored panels
(optional)
> Add support for custom width, left anchored panels

- .github/CODEOWNERS
…Button components.
Modifying CODEOWNERS file to add codeowners to the Stack and the new Button components.
(optional)
> Modifying CODEOWNERS file to add codeowners to the Stack and the new Button components

- .github/CODEOWNERS
Add myself as codeowner for List, GroupedList and DetailsList components & example paths.
(optional)
> Add KevinTCoughlin as CODEOWNER to List, DetailsList, and GroupedList component and doc paths

- apps/ssr-tests/package.json
- apps/test-bundles/webpack.config.js
- common/config/rush/common-versions.json
- common/config/rush/shrinkwrap.yaml
- scripts/package.json
Upgrading bundle things in its own PR.
> Upgrading webpack, webpack-cli, bundle-analyzer

- common/changes/office-ui-fabric-react/keco-groupedlist-type-improvements_2019-02-19-22-32.json
- packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx
- packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx
This pull-request tightens some of the types used across `GroupedList` and `GroupedListSection` which were `any` in an effort to improve type-safety and developer friendliness.
- This should build
- The existing tests should pass
- There should _not be_ any public API changes
> GroupedList / GroupedListSection: Improve typings

- common/changes/office-ui-fabric-react/issue8063_2019-02-22-04-50.json
- packages/office-ui-fabric-react/src/components/Persona/Persona.types.ts
Persona: Augment documentation for `optionalText` and `tertiaryText` to be more useful.
> Persona: Augment documentation for `optionalText` and `tertiaryText` to be more useful.

- common/changes/@uifabric/experiments/stackDoc_2019-02-22-18-19.json
- packages/experiments/src/Stack.ts
Stack: Making doc block in `Stack.ts` in the `experiments` package so that @deprecated is recognized
(optional)
> Stack: Making doc block in `Stack.ts` in the `experiments` package so that @deprecated is recognized

- .github/CODEOWNERS
Add myself to various components as codeowner.
> CODEOWNERS: JasonGore

- .github/CODEOWNERS
Updating codeowners
(optional)
> Adding myself as a SpinButton owner

- .github/CODEOWNERS
Adding me as a code owner of certain components.
(optional)
> CODEOWNERS: @khmakoto

- .github/CODEOWNERS
In response to @dzearing his email I'm adding myself to the Persona component.
> All your persona are belong to us :)

- common/changes/@uifabric/dashboard/AddCardPanelIssues_2019-02-18-12-41.json
- packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayoutWithAddCardPanel/DashboardGridLayoutWithAddCardPanel.tsx
- packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayoutWithAddCardPanel/DashboardGridLayoutWithAddCardPanel.types.ts
- packages/dashboard/src/components/DashboardGridLayout/DashboardGridSectionLayout.tsx
- packages/dashboard/src/components/DashboardGridLayout/examples/DGLWithAddCardPanel.Example.tsx
* Fix issue with 1st time cards not rendered on dashboard
* Fix issue with onLayoutChange calling 
(optional)
> Add card panel issues

- common/changes/@uifabric/dashboard/wizardTitle_2019-02-27-18-58.json
- packages/dashboard/src/components/Wizard/PanelWizard.Base.tsx
- packages/dashboard/src/components/Wizard/SetupWizard.Base.tsx
- packages/dashboard/src/components/Wizard/SetupWizard.styles.ts
- packages/dashboard/src/components/Wizard/SetupWizard.types.ts
- packages/dashboard/src/components/Wizard/Wizard.styles.ts
- packages/dashboard/src/components/Wizard/Wizard.types.ts
- packages/dashboard/src/components/Wizard/examples/FullParentWizard.Example.tsx
- packages/dashboard/src/components/Wizard/examples/PanelWizard.Example.tsx
- packages/dashboard/src/components/Wizard/examples/SetupWizard.SubSteps.Example.tsx
- packages/dashboard/src/components/Wizard/examples/SetupWizard.WizardComplete.Example.tsx
- packages/dashboard/src/components/Wizard/examples/WizardExample.Base.tsx
- [x ] Include a change request file using `$ npm run change`
Making title element optional as SetupWizard design has no title
> Wizard title - make it optional prop

- common/changes/office-ui-fabric-react/cliffkoh-fixHiddenBytes_2019-02-28-06-08.json
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
Remove hidden bytes in combobox that was driving @dzearing nuts. 
(optional)
> Remove easter egg of hidden bytes

- common/changes/office-ui-fabric-react/keco-list-any-types_2019-03-01-01-23.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts
- packages/office-ui-fabric-react/src/components/List/List.tsx
- packages/office-ui-fabric-react/src/components/List/List.types.ts
This pull-request is a continuation of the work started in #8043. The changes improve the typings across ***List** components that are currently typed as `any`. The goal is to improve type-safety and developer friendliness of these components.
- Build should succeed
- Tests should succeed
> DetailsList / List: Improve typings

- common/changes/@uifabric/dashboard/setupwizard_2019-03-01-00-43.json
- packages/dashboard/src/components/Wizard/Wizard.utils.ts
> Make the stepToShow parameter take effect on footerAction

- common/changes/office-ui-fabric-react/edwl-2019-02-addNativePropsBreadcrumb_2019-02-28-19-57.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts
- packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.base.tsx
- packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.test.tsx
- packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.types.ts
Adds native props support to Breadcrumb
(optional)
> Add native props to Breadcrumb

- common/changes/office-ui-fabric-react/edwl-2019-03-fixChoiceGroupStyles_2019-03-04-19-35.json
- packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroupOption/ChoiceGroupOption.styles.ts
- packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroupOption/__snapshots__/ChoiceGroupOption.test.tsx.snap
Adjust disabled checked styles
**BEFORE**
**AFTER**
(optional)
> ChoiceGroup: Fix disabled selected styles

- common/changes/@uifabric/utilities/fix-extra-import_2019-03-05-02-34.json
- packages/utilities/src/index.ts
Utilities had an extra export, removing.
> Fix extra export

- common/changes/@uifabric/dashboard/add-wizard-to-index_2019-03-05-01-15.json
- packages/dashboard/src/components/Wizard/index.ts
- packages/dashboard/src/index.ts
- [ x] Include a change request file using `$ npm run change`
Added wizard to dashboard package index
> Add wizard to index

- common/changes/@uifabric/example-app-base/cliffkoh-issue8197_2019-03-05-18-50.json
- common/changes/@uifabric/experiments/cliffkoh-issue8197_2019-03-05-18-50.json
- packages/example-app-base/src/utilities/parser/Parse.ts
- packages/experiments/src/components/Shimmer/examples/Shimmer.Application.Example.tsx
- packages/experiments/src/components/Tile/examples/Tile.Document.Example.tsx
- packages/experiments/src/components/Tile/examples/Tile.Folder.Example.tsx
- packages/experiments/src/components/Tile/examples/Tile.Media.Example.tsx
Text/Stack: Fix issue where key documentation pieces were missing
(optional)
> Text/Stack: Fix issue where key documentation pieces were missing

- common/changes/office-ui-fabric-react/react-deprecation-pivot-redux_2019-02-19-20-48.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts
- packages/office-ui-fabric-react/src/components/Pivot/Pivot.base.tsx
* Remove pivot's use of `componentWillReceiveProps`
* Remove `links` from state
* Render selected pivot item deterministically **(NB: Does change previous unintended behavior.)**
> Pivot - remove deprecated lifecycle method

- common/changes/@uifabric/dashboard/detail_2019-03-05-20-21.json
- common/changes/@uifabric/dashboard/detail_2019-03-05-21-54.json
- packages/dashboard/src/components/DetailPanel/BaseContainer.tsx
- packages/dashboard/src/components/DetailPanel/DetailPanel.Base.tsx
- packages/dashboard/src/components/DetailPanel/DetailPanel.types.ts
- packages/dashboard/src/components/DetailPanel/Examples/DetailPanel.Basic.Example.tsx
- packages/dashboard/src/components/DetailPanel/Header/Header.tsx
- packages/dashboard/src/components/DetailPanel/Utils.ts
DetailPanel: Allow persona header set image icon 
(optional)
> DetailPanel: Allow persona header set image icon 

- apps/vr-tests/src/stories/Signals.stories.tsx
- common/changes/@uifabric/experiments/huaxi-follow-color_2019-03-06-04-06.json
- packages/experiments/src/components/signals/Signals.scss
- [x ] Include a change request file using `$ npm run change`
updated signal icon - follow button's color
> follow signal icon should use lighter dark color

- common/changes/office-ui-fabric-react/edwl-2019-03-removeConsoleLog_2019-03-06-19-14.json
- packages/office-ui-fabric-react/src/components/Tooltip/examples/Tooltip.Absolute.Position.Example.tsx
Removes console log in example
(optional)
> remove console log in Tooltip example

- common/changes/office-ui-fabric-react/keco-cleanup-list-examples_2019-03-07-01-28.json
- packages/office-ui-fabric-react/src/components/List/examples/List.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/List/examples/List.Ghosting.Example.tsx
- packages/office-ui-fabric-react/src/components/List/examples/List.Scrolling.Example.tsx
Cleans-up the List examples' typings. Discovered while experimenting with List variations...
- CI should pass
- Tests should pass
- Examples should work as they did before this change
> List Examples: Clean-up typings

- .vscode/launch.json
changefile not required according to `npm run change`
Adds a launch task for running a single test.
I was finding it cumbersome to run every test on every iteration of trying to debug my tests in #8258, so i added this vscode launch task to make it easier.
> add vscode launch task for running a single test

- common/changes/@uifabric/dashboard/user-v-dikish-DashboardGridLayout_2019-03-11-23-34.json
- packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayoutWithAddCardPanel/DashboardGridLayoutWithAddCardPanel.tsx
Fixed dashboard grid layout example for low resolution screen
> User/v dikish/dashboard grid layout

- common/changes/@uifabric/dashboard/ddd_2019-03-11-23-28.json
- packages/dashboard/src/components/DetailPanel/BaseContainer.tsx
- packages/dashboard/src/components/DetailPanel/Body/DetailPanelPivotBody.tsx
- packages/dashboard/src/components/DetailPanel/Body/DetailPanelPivotItem.tsx
- packages/dashboard/src/components/DetailPanel/DetailPanel.Base.tsx
- packages/dashboard/src/components/DetailPanel/DetailPanel.types.ts
- packages/dashboard/src/components/DetailPanel/Examples/DetailPanel.Pivot.Example.tsx
DetailPanel: Update allow Message Banner to show inside or/and outside Pivot
(optional)
> DetailPanel: Update allow Message Banner to show inside or/and outside Pivot

- common/changes/office-ui-fabric-react/joschect-fix-base-button-hidden_2019-03-11-19-01.json
- packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx
- packages/office-ui-fabric-react/src/components/Button/Button.test.tsx
> BaseButton: Clone props so they don't get mutated.

- common/changes/@uifabric/dashboard/dep-update_2019-03-12-23-26.json
- common/config/rush/shrinkwrap.yaml
- packages/dashboard/package.json
> Dashboard dependency update

- common/changes/office-ui-fabric-react/v-vibr-HoverCardTarget_2019-03-12-21-50.json
- packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.base.tsx
Reassigning the native event listeners to a new target in case it is updated through props.
> HoverCard: update native event listeners in case target prop changes.

- common/changes/office-ui-fabric-react/edwl-2019-03-fixNavSelection_2019-03-08-22-49.json
- packages/office-ui-fabric-react/src/components/Nav/Nav.base.tsx
- packages/office-ui-fabric-react/src/components/Nav/Nav.test.tsx
Only check URL/location.has if state.selectedKey is undefined.
(optional)
> Nav: Fix selection state

- common/changes/@uifabric/utilities/remove-unused_2019-03-14-15-58.json
- packages/utilities/src/customizations/Customizer.tsx
> Remove unused variables and types from Customizer

- rush.json
After some discussion we decided it doesn't need to be published.
> Don't publish codepen loader

- common/changes/@uifabric/dashboard/timtong2_2019-03-14-16-41.json
- packages/dashboard/src/components/DetailPanel/DetailPanel.styles.ts
- packages/dashboard/src/components/DetailPanel/Examples/DetailPanel.Pivot.Example.tsx
DetailPanel: Enable overflow handling on Tiles
(optional)
> DetailPanel: Enable overflow handling on Tiles

- rush.json
Rush 5.6.0 will allow us to fix #7253
> Update rush version to 5.6.0

- .github/ISSUE_TEMPLATE/accessibility_issue.md
> Create Accessibility Issue Template

- common/changes/office-ui-fabric-react/dropdown-docs_2019-03-18-18-25.json
- packages/office-ui-fabric-react/src/components/Dropdown/docs/DropdownOverview.md
Updating dropdown readme to mention/link to focus discussion.
> Dropdown: Update readme to include links/comments about focus behavior

- apps/fabric-website/index.html
- common/changes/@uifabric/fabric-website/edwl-2019-03-addFabricVerQueryParam_2019-03-15-22-00.json
Adds query parameter to check for fabric query parameter. 
(optional)
> Add query param to fabric-website/index.html to check for v5 vs v6.

- common/changes/@uifabric/experiments/yudon-tooltipbug0315_2019-03-15-23-05.json
- packages/experiments/src/components/Pagination/Pagination.base.tsx
Miraj.Patel@microsoft.com reached out about this bug.
Experiment package, pagination component
> fix a bug in the tooltip of last page button in pagination component, experiment package

- README.md
[README] README callout re Fabric 7
> [README] README callout re Fabric 7

- common/changes/@uifabric/dashboard/cardHeaderBorderFix_2019-03-15-11-00.json
- packages/dashboard/src/components/Card/CardFrame/CardFrame.styles.ts
Dashboard Card Header ellipsis accessibility. 
Dashboard card header ellipsis border is missing right and bottom on tab accessibility.
Dashboard
> Card header border fix

- .github/CODEOWNERS
A `Card` component exists in the dashboard package, so I'm scoping my ownership to the `react-cards` package one.
(optional)
> Updating codeowners file

- common/changes/office-ui-fabric-react/more-bc-removal_2019-03-19-04-21.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts
- packages/office-ui-fabric-react/src/components/Icon/Icon.base.tsx
- packages/office-ui-fabric-react/src/components/Icon/Icon.tsx
- packages/office-ui-fabric-react/src/components/Image/Image.base.tsx
Removes BaseComponent from Icon.
> Icon: remove BaseComponent usage.

- common/changes/@uifabric/migration/bin_2019-03-19-19-03.json
- packages/migration/package.json
Fixing a typo in the bin script so that one can actually run `npx @uifabric/migration ...`
(optional)
> [Migration] Bin shebang fix 

- apps/fabric-website/index.html
- common/changes/@uifabric/fabric-website/edwl-2019-03-remoteTemplateLiteral_2019-03-20-01-17.json
Remove template literal to support IE 11
(optional)
> Remove template literal in index of fabric-website

- common/changes/office-ui-fabric-react/u-mahuangh-move-replaeItem-selectedItemsList_2019-03-19-21-46.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.ts
- packages/office-ui-fabric-react/src/components/SelectedItemsList/BaseSelectedItemsList.tsx
- packages/office-ui-fabric-react/src/components/SelectedItemsList/SelectedPeopleList/SelectedPeopleList.tsx
- ~~[ ] Addresses an existing issue: Fixes #0000~~
Moves replaceItem from selectedPeopleList and into BaseItemList (since the behaviour is usable by non-persona data types).
SelectedPeoplelist
> Move "replaceItem" to BaseitemList

- common/changes/office-ui-fabric-react/textfield-prefix-ie11_2019-03-20-18-20.json
- packages/office-ui-fabric-react/src/components/TextField/TextField.styles.tsx
- packages/office-ui-fabric-react/src/components/TextField/__snapshots__/TextField.deprecated.test.tsx.snap
- packages/office-ui-fabric-react/src/components/TextField/__snapshots__/TextField.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/TextField.Prefix.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/TextField.PrefixAndSuffix.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/TextField.Suffix.Example.tsx.shot
> Textfield prefix ie11

- common/changes/@uifabric/dashboard/addCardPanelDragIssue_2019-03-21-13-31.json
- packages/dashboard/src/components/DashboardGridLayout/DashboardGridLayoutWithAddCardPanel/DashboardGridLayoutWithAddCardPanel.tsx
Fix issue with add card from panel using drag and drop
- while using in M365Admin face a issue using drag and drop card
- This will fix drag and drop card from panel to dashboard issue
(optional)
> Add card panel drag issue

- apps/fabric-website/index.html
- common/changes/@uifabric/fabric-website/edwl-2019-03-fixMissingHyphenFabricWebsite_2019-03-21-19-11.json
Adds missing hyphen to fix incorrect path for config script
(optional)
> Add missing hyphen in index.html for fabric-website

- .gitignore
- common/changes/@uifabric/migration/bin2_2019-03-21-22-16.json
- packages/migration/.npmignore
- packages/migration/bin/migrate.js
Apparently gitignore ignored the bin script all this time!
(optional)
> Apparently gitignore ignored the bin script all this time!

- common/changes/@uifabric/migration/rename_2019-03-22-15-57.json
- packages/migration/bin/migrate.js
- packages/migration/bin/migration.js
- packages/migration/package.json
This also fixes the issue where it is looking for the wrong file in the bin script
(optional)
> Rename migrate.js to migration.js to match the package name

- common/changes/@uifabric/dashboard/user-v-dikish-DashboardCardTabIndex_2019-03-22-18-49.json
- packages/dashboard/src/components/Card/ActionBar/ActionBar.tsx
- packages/dashboard/src/components/Card/ActionBar/ActionBar.types.ts
- packages/dashboard/src/components/Card/Card.tsx
- packages/dashboard/src/components/Card/Card.types.ts
- packages/dashboard/src/components/Card/Layout/Layout.tsx
- packages/dashboard/src/components/Card/Layout/Layout.types.ts
expose FocuseZone component props in dashboard Card component
> expose FocuseZone component props in dashboard Card component

- apps/perf-test/src/App.tsx
- apps/perf-test/src/Measurer.tsx
- apps/perf-test/src/Scenarios.tsx
Minor updates for the perf-test package.
> Perf test package cleanup

- .github/CODEOWNERS
Adding Text and Announced to the codeowners file.
(optional)
> Update codeowners file - add Text and Announced

- common/changes/@uifabric/merge-styles/updateAPIFiles_2019-03-26-21-59.json
- common/changes/@uifabric/utilities/updateAPIFiles_2019-03-26-21-59.json
- common/changes/office-ui-fabric-react/updateAPIFiles_2019-03-26-21-59.json
- packages/merge-styles/etc/merge-styles.api.md
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/utilities/etc/utilities.api.md
Need to update a few of the API files due to some api-extractor 7 changes.
(optional)
> Update api files

- apps/fabric-website/src/pages/HomePage/HomePage.tsx
- common/changes/@uifabric/fabric-website/edwl-2019-03-removeUnusedStateHomePage_2019-03-27-00-21.json
Remove unused state in HomePage and fix formatting for fabricVersionOptions to be more readable
(optional)
> Remove unused state in HomePage.tsx

- common/changes/@uifabric/dashboard/AddCardHeaderClick_2019-03-27-11-34.json
- packages/dashboard/src/components/Card/CardHeader/CardHeader.styles.ts
- packages/dashboard/src/components/Card/CardHeader/CardHeader.tsx
- packages/dashboard/src/components/Card/CardHeader/CardHeader.types.ts
- packages/dashboard/src/components/Card/Layout/Layout.tsx
- packages/dashboard/src/components/Card/examples/Card.Small.Basic.Example.tsx
Add Click event for card header and provide a prop for dashboard card
(optional)
> Add Click event for card header and provide a prop for dashboard card

- apps/fabric-website/src/components/App/AppState.tsx
- apps/fabric-website/src/pages/Components/KeytipsComponentPage.tsx
- common/changes/@uifabric/fabric-website/keytips_2019-03-27-17-34.json
Keytips: Adding component page to AppState
(optional)
> Keytips: Adding component page to AppState

- common/changes/office-ui-fabric-react/v-vibr-HoverCardInstantDismissFunction_2019-03-27-05-27.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/ComponentExamples.test.tsx
- packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.base.tsx
- packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.doc.tsx
- packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.test.tsx
- packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.types.ts
- packages/office-ui-fabric-react/src/components/HoverCard/examples/HoverCard.InstantDismiss.Example.tsx
Adding an instant dismissal method to the HoverCard class
Adding a unit test for the new behavior
Adding an example to demo its usage
> HoverCard: public instant dismiss method

- apps/vr-tests/screener.config.js
- azure-pipelines.yml
Crossing fingers that this fixes screener by using the right target branch env variable.
(optional)
> Fix screener: change the pull request target for screener

- common/changes/office-ui-fabric-react/shield-PickerRole_2019-03-28-20-32.json
- packages/office-ui-fabric-react/src/components/__snapshots__/Announced.SearchResults.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/PeoplePicker.Types.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/TagPicker.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
- packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/__snapshots__/PeoplePicker.test.tsx.snap
- packages/office-ui-fabric-react/src/components/pickers/TagPicker/__snapshots__/TagPicker.test.tsx.snap
- packages/office-ui-fabric-react/src/components/pickers/__snapshots__/BasePicker.test.tsx.snap
ARIA `role="list"` must contain one or more list items ([link](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/List_role#Description))
Conditionally render the list only if we have already selected items.
> Pickers: conditionally render the list of selected items.

- common/changes/office-ui-fabric-react/shield-MaskedTextField_2019-03-29-01-09.json
- packages/office-ui-fabric-react/src/components/TextField/MaskedTextField/MaskedTextField.test.tsx
- packages/office-ui-fabric-react/src/components/TextField/MaskedTextField/MaskedTextField.tsx
When the `MaskedTextField` is used as a controlled input it was failing to update the value properly.
> MaskedTextField: fixing the controlled behavior

- common/changes/office-ui-fabric-react/fix-dual-menurole_2019-03-29-18-06.json
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Button.ContextualMenu.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ContextualMenu.Persisted.Example.tsx.shot
ContextualMenu: Remove unneeded extra role=menu
(optional)
> ContextualMenu: Remove unneeded extra role=menu

- scripts/just-task.js
> Re-add 'dev' task

- common/changes/office-ui-fabric-react/buttonTypo_2019-04-03-00-05.json
- packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx
Button: Adding missing parenthesis in `ev.stopPropagation`.
(optional)
> Button: Adding missing parenthesis in ev.stopPropagation function call

- apps/fabric-website/src/pages/HomePage/HomePage.tsx
- common/changes/@uifabric/fabric-website/edwl-2019-04-fixHomePageVersionCheck_2019-04-02-22-32.json
HomePage needs to check sessionStorage to get correct fabricVer
(optional)
> HomePage: Version check for sessionStorage for fabricVer value

- packages/migration/src/migration.ts
- packages/migration/src/mods/7.0.0/warnSliderValuePositionRemoved.ts
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Slider/Slider.base.tsx
Remove a deprecated export, provide a codemod.
> Warning for slider ValuePosition removal, make Slider component controllable.

- common/changes/@uifabric/react-cards/cardHighContrast_2019-04-03-17-36.json
- packages/react-cards/src/components/Card/Card.styles.ts
- packages/react-cards/src/components/Card/Card.types.ts
- packages/react-cards/src/components/Card/CardItem/__snapshots__/CardItem.test.tsx.snap
This PR adds High Contrast support for the `Card` component.
__Before:__
<p align="center">
</p>
__After:__
<p align="center">
</p>
(optional)
> Card: Supporting High Contrast mode

- common/changes/@uifabric/dashboard/lightdismiss_2019-04-05-22-50.json
- packages/dashboard/src/components/DetailPanel/DetailPanel.Base.tsx
- packages/dashboard/src/components/DetailPanel/DetailPanel.types.ts
- packages/dashboard/src/components/DetailPanel/Examples/DetailPanel.Basic.Example.tsx
- packages/dashboard/src/components/DetailPanel/Examples/DetailPanel.L2Content.Example.tsx
- packages/dashboard/src/components/DetailPanel/Examples/DetailPanel.Pivot.Example.tsx
DetailPanel: Update typo property name: onDetailPanelDimiss -> onDetailPanelDismiss
Add example of use light dismiss
(optional)
> DetailPanel: Update typo property name: onDetailPanelDimiss -> onDetailPanelDismiss

- apps/pr-deploy-site/config/pre-copy.json
- apps/pr-deploy-site/index.html
- apps/pr-deploy-site/package.json
Add perf-app to 'pr-deploy-site' to get deployed for each pull request. This is do enable perf regression tests. These would identify relative perf regressions between new and existing changes.
The app gets deployed.
Successful: http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/8642/merge/perf-test/index.html
> Deploy perf app

- scripts/tasks/webpack.js
`npm run start` will listen on all hosts, allowing testing build from other machines (and notably other operating systems)
> Webpack listens on all hosts

- common/changes/@uifabric/dashboard/ScreenReaderSupportForIcons_2019-04-09-10-58.json
- packages/dashboard/src/components/DetailPanel/BaseContainer.tsx
added screen reader support for nav bar icons in the detail panel ( with pivot)
> Screen reader support for icons

- azure-pipelines.yml
Add perf-test to azure pipeline such that perf numbers are generated and stored for further analysis.
See the task ran successfully in the PR pipeline
> Update azure pipline to run perf-test after deploy

- scripts/tasks/webpack.js
This reverts commit 2259f2d360a7b0d2419924ca766dccd8cbda8508.
This didn't work as well as I expected on Windows.
> Revert "Webpack listens on all hosts (#8639)"

- apps/fabric-website-resources/webpack.config.js
- common/changes/@uifabric/fabric-website-resources/deploy_2019-04-11-23-45.json
apparently demo-app.js isn't being generated because now we use rush buildci without production flag.
(optional)
> Deploy demo-app.js for demo site

- common/changes/@uifabric/experiments/buttonFixes_2019-04-12-03-46.json
- packages/experiments/src/components/Button/SplitButton/SplitButton.styles.ts
- packages/experiments/src/components/Button/SplitButton/SplitButton.view.tsx
While working on trying to replicate some multiline ribbon buttons there were some styling issues that were found. This PR addresses those issues.
(optional)
> Button: Styling fixes to issues found while working on Multiline Ribbon buttons

- azure-pipelines.yml
- scripts/tasks/perf-test.js
> Add "GithubPRComment" task to azure pipeline

- common/changes/office-ui-fabric-react/jdh-controlled-panel_2019-04-11-23-59.json
- packages/office-ui-fabric-react/src/components/Panel/Panel.base.tsx
- packages/office-ui-fabric-react/src/components/Panel/Panel.doc.tsx
- packages/office-ui-fabric-react/src/components/Panel/Panel.test.tsx
- packages/office-ui-fabric-react/src/components/Panel/Panel.types.ts
- packages/office-ui-fabric-react/src/components/Panel/examples/Panel.Controlled.Example.tsx
- packages/office-ui-fabric-react/src/components/Panel/examples/Panel.HandleDismissTarget.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Panel.Controlled.Example.tsx.shot
> Panel visibility controllable.

- common/changes/office-ui-fabric-react/zababbit-AddingDataParameterToComboBox_2019-04-11-21-55.json
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
Add the data parameter as part of ComboBoxOptionWrapper. This will be passed into shallowCompare so that shallowCompare will return true when a new icon has been dynamically set from script#. This will cause the rendering code to be re-ran when the icon changes allowing the dynamically set icon to populate. For more information, feel free to reach out to me here or zababbit@microsoft.com
> Adding data parameter to combo box

- packages/experiments/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.styles.ts
- packages/office-ui-fabric-react/src/components/ComboBox/__snapshots__/ComboBox.deprecated.test.tsx.snap
- packages/office-ui-fabric-react/src/components/ComboBox/__snapshots__/ComboBox.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.styles.ts
- packages/office-ui-fabric-react/src/components/__snapshots__/ChoiceGroup.Custom.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ComboBox.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ComboBox.Controlled.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ComboBox.CustomStyled.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ComboBox.Toggles.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ComboBox.Virtualized.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Basic.Example.tsx.shot
Fixing some missed styles for placeholders in ComboBox and Dropdown
> Fabric 7.0: Fixing placeholder styles in Dropdown and ComboBox

- common/changes/@uifabric/date-time/date-time_2019-04-15-16-51.json
- packages/date-time/etc/date-time.api.md
- packages/date-time/src/Calendar.ts
- packages/date-time/src/components/Calendar/Calendar.types.ts
- packages/date-time/src/components/Calendar/examples/Calendar.Button.Example.tsx
- packages/date-time/src/components/Calendar/examples/Calendar.Inline.Example.tsx
- packages/date-time/src/index.ts
- packages/date-time/webpack.serve.config.js
Also tweaked webpack serve alias to support importing from date-time package
> Date-time: Update top level export to include calendar

- common/changes/@uifabric/experiments/docs_2019-04-15-22-39.json
- common/changes/@uifabric/react-cards/docs_2019-04-15-22-39.json
- packages/experiments/src/components/Button/ButtonPage.tsx
- packages/experiments/src/components/Button/docs/ButtonDonts.md
- packages/experiments/src/components/Button/docs/ButtonDos.md
- packages/experiments/src/components/Button/docs/ButtonOverview.md
- packages/react-cards/src/components/Card/docs/CardOverview.md
This PR adds `Overview`, `Dos` and `Dont's` documentation to the experimental `Button` component and `Overview` documentation to the `Card` component.
(optional)
>  Button and Card: Updating docs (overview, dos and don'ts).

- azure-pipelines.yml
> fabric-7 - re-enable a11y tests

- common/changes/@uifabric/example-app-base/fixsite_2019-04-18-02-42.json
- packages/example-app-base/src/index.ts
re-export with wildcards in webpack in two separate levels screws up the sideEffect stuff. WP incorrectly marks certain modules as unused.
(optional)
> Fix website: this fixes up the sideeffect bug in webpack

- common/changes/@uifabric/experiments/improvements_2019-04-18-00-06.json
- common/changes/@uifabric/react-cards/improvements_2019-04-18-00-06.json
- packages/experiments/src/components/Button/Button.types.tsx
- packages/react-cards/src/components/Card/Card.styles.ts
- packages/react-cards/src/components/Card/Card.types.ts
- packages/react-cards/src/components/Card/CardItem/__snapshots__/CardItem.test.tsx.snap
Button: Removing `undefined` from `cursor` token definition.
Card: Adding `cursor` as a token and giving it the correct default styling.
(optional)
> Button and Card: cursor token improvements

- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Toggle/Toggle.base.tsx
> [Toggle] remove use of deprecated react lifecycle method.

- apps/fabric-website/webpack.serve.config.js
> Fix fabric-website loading of legacy package

- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.base.tsx
> [Checkbox] Remove deprecated react lifecycle method.

- common/changes/office-ui-fabric-react/pickers-fix-aria-describedby_2019-04-18-00-58.json
- packages/office-ui-fabric-react/src/components/__snapshots__/Announced.SearchResults.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/PeoplePicker.Types.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/TagPicker.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
- packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/__snapshots__/PeoplePicker.test.tsx.snap
- packages/office-ui-fabric-react/src/components/pickers/TagPicker/__snapshots__/TagPicker.test.tsx.snap
- packages/office-ui-fabric-react/src/components/pickers/__snapshots__/BasePicker.test.tsx.snap
Pickers: Fix issue where described by had invalid id
(optional)
> Pickers: Fix issue where described by had invalid id

- common/changes/@uifabric/experiments/tokensDocs_2019-04-18-22-56.json
- common/changes/@uifabric/react-cards/tokensDocs_2019-04-18-22-56.json
- common/changes/office-ui-fabric-react/tokensDocs_2019-04-18-22-56.json
- packages/experiments/src/components/Button/Button.types.tsx
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Stack/Stack.types.ts
- packages/react-cards/src/components/Card/Card.types.ts
Adding documentation for token docs in Button, Card and Stack.
(optional)
> Adding documentation for token docs in Button, Card and Stack

- common/changes/@uifabric/styling/edwl-2019-04-removeScrollablePaneZIndex_2019-04-18-23-00.json
- common/changes/office-ui-fabric-react/edwl-2019-04-removeScrollablePaneZIndex_2019-04-18-23-00.json
- packages/office-ui-fabric-react/src/components/ScrollablePane/ScrollablePane.styles.ts
- packages/office-ui-fabric-react/src/components/ScrollablePane/__snapshots__/ScrollablePane.test.tsx.snap
- packages/styling/etc/styling.api.md
- packages/styling/src/styles/zIndexes.ts
Removes z index from scrollablepane
(optional)
> Remove scrollablePane z index

- common/changes/@uifabric/azure-themes/rkessler-updateReadme_2019-04-19-23-00.json
- packages/azure-themes/README.md
Updates readme with more expansive and accurate information.
NA
> Update azure-theme readme

- common/changes/office-ui-fabric-react/textfield-validate_2019-04-19-23-55.json
- packages/office-ui-fabric-react/src/components/TextField/TextField.base.tsx
- packages/office-ui-fabric-react/src/components/TextField/TextField.types.ts
Clarify the documentation of some TextField properties, especially ones related to validation.
> TextField documentation updates

- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/ScrollablePane/ScrollablePane.base.tsx
- packages/office-ui-fabric-react/src/components/ScrollablePane/ScrollablePane.tsx
- packages/office-ui-fabric-react/src/components/ScrollablePane/ScrollablePane.types.ts
- packages/office-ui-fabric-react/src/components/ScrollablePane/examples/ScrollablePane.Default.Example.tsx
- packages/office-ui-fabric-react/src/components/Sticky/Sticky.tsx
> Remove use of legacy context

- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.base.tsx
> [Breadcrumb] Remove deprecated lifecycle method

- scripts/tasks/perf-test.js
Fixing issue of adding or removing scenarios from perf app that would throw and break the build.
It will be safe to do so now. Numbers for a missing scenario from either master or pr would show as '...'.
(optional)
> Allow for discrepancies between master and pr scenario content

- common/changes/office-ui-fabric-react/fabric-7-layer-context_2019-04-22-20-20.json
- packages/office-ui-fabric-react/src/components/Layer/Layer.test.tsx
- packages/office-ui-fabric-react/src/components/Layer/examples/Layer.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Layer.Basic.Example.tsx.shot
> Fabric 7 layer context

- scripts/templates/create-component/EmptyTypes.mustache
- scripts/templates/create-component/EmptyTypesStateless.mustache
- scripts/templates/create-component/EmptyView.mustache
When Text was promoted to OUFR, a couple of the paths in the create component script were invalidated. This PR fixes them.
> Create Component Script: Fix errors due to Text promotion.

- common/changes/@uifabric/utilities/isfocusvisible_2019-04-24-18-25.json
- packages/utilities/etc/utilities.api.md
- packages/utilities/src/index.ts
- packages/utilities/src/setFocusVisibility.test.ts
- packages/utilities/src/setFocusVisibility.ts
> Make isFocusVisible toggleable by user

- common/changes/office-ui-fabric-react/teachingbubble-target_2019-04-23-18-51.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Callout/Callout.types.ts
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts
- packages/office-ui-fabric-react/src/components/TeachingBubble/TeachingBubble.base.tsx
- packages/office-ui-fabric-react/src/components/TeachingBubble/TeachingBubble.types.ts
- packages/office-ui-fabric-react/src/components/TeachingBubble/examples/TeachingBubble.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/TeachingBubble/examples/TeachingBubble.Condensed.Example.tsx
- packages/office-ui-fabric-react/src/components/TeachingBubble/examples/TeachingBubble.Illustration.Example.tsx
- packages/office-ui-fabric-react/src/components/TeachingBubble/examples/TeachingBubble.SmallHeadline.Example.tsx
- packages/office-ui-fabric-react/src/components/TeachingBubble/examples/TeachingBubble.WideIllustration.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/TeachingBubble.Condensed.Example.tsx.shot
Callout/TeachingBubble: Make a new "Target" type to help unify the various consumers of callout.
(optional)
> Callout/TeachingBubble: Make "Target" type and use that for teaching bubble

- common/changes/office-ui-fabric-react/focuszoneprops-add-tobreadcrumb_2019-04-23-01-05.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.base.tsx
- packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.types.ts
Add in focuszone props to breadcrumb to give more control to consumers.
(optional)
> Breadcrumb: add focuszoneprops

- common/changes/office-ui-fabric-react/fixSeparatorExample_2019-04-25-23-37.json
- packages/office-ui-fabric-react/src/components/Separator/examples/Separator.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Separator.Basic.Example.tsx.shot
The empty example should be empty. :)
(optional)
> Separator: fix empty example

- common/changes/office-ui-fabric-react/variable-name_2019-04-27-11-10.json
- packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts
> Fixed typo in position utility

- common/changes/office-ui-fabric-react/jg-fix-master-jd_2019-04-29-22-19.json
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.SeparateNoSelectedKey.Example.tsx.shot
Fix master due to merge of #8638.
> Fix master build by updating snapshots

- common/changes/@uifabric/example-app-base/fixLinksForDemoSite_2019-04-29-23-50.json
- packages/example-app-base/src/components/ApiReferencesTable/ApiReferencesTable.tsx
These changes should fix the api reference table links for the fabric demo and pr deploy sites!
(optional)
> Fix links for fabric demo & pr deploy site

- common/changes/office-ui-fabric-react/master_2019-04-30-17-17.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/FloatingPicker/BaseFloatingPicker.types.ts
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.types.ts
Fix type issue in onRemoveSuggestion for item.
(optional)
> Fix type for BasePicker onRemoveSuggestion api

- common/changes/office-ui-fabric-react/add-in-basepicker-protected_2019-04-30-16-07.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
BasePicker: Add back in typedsuggestion class property
(optional)
> BasePicker: Add back in typedsuggestion class property

- common/changes/office-ui-fabric-react/breadcrumb_2019-04-30-21-23.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.base.tsx
- packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.types.ts
Fix a casing mistake. The incorrectly-cased type is still exported from the original (also incorrect) location, so it won't break people.
> Add IBreadcrumbData, deprecate IBreadCrumbData

- .gitignore
- apps/fabric-website/index.html
- apps/fabric-website/just-task.js
- apps/fabric-website/package.json
- apps/fabric-website/scripts/createFlightConfig.js
- apps/fabric-website/webpack.config.js
- apps/pr-deploy-site/index.html
- apps/pr-deploy-site/package.json
- common/changes/@uifabric/fabric-website/site-deploy_2019-05-01-18-23.json
- common/config/rush/shrinkwrap.yaml
- scripts/just-task.js
- scripts/just.js
- scripts/package.json
Applies the changes from the `website-update` branch to master so we can all enjoy this enhancement right away.
(optional)
> Site deploy: this is the one for for master branch

- common/changes/@uifabric/example-app-base/website-update-mdl-theme-selection_2019-05-01-00-51.json
- packages/example-app-base/src/components/ExampleCard/ExampleCard.tsx
> [fabric-website] Theme picker renders MDL2 styles.

- common/config/rush/shrinkwrap.yaml
Thanks Rush / PNPM!
(optional)
> fixing shrinkwrap to only install one copy of just-task

- common/config/rush/shrinkwrap.yaml
- scripts/package.json
- scripts/tasks/perf-test.js
Add t-test to perf-comment to evaluate statistical significance of sampled variation.
Perf comment shows up new column for p-value evaluation
> Add p-value evaluation to perf-comment

- apps/fabric-website/src/pages/Controls/FluentThemePage/docs/web/FluentThemeOverview.md
- apps/fabric-website/src/pages/Overviews/GetStartedPage/GetStartedPage.tsx
- apps/fabric-website/src/pages/Overviews/GetStartedPage/docs/web/GetStartedDevelop.md
- common/changes/@uifabric/example-app-base/getting-started_2019-05-03-00-14.json
- common/changes/@uifabric/fabric-website/getting-started_2019-05-02-23-43.json
- packages/example-app-base/src/components/CodeSnippet/CodeSnippet.tsx
- packages/example-app-base/src/components/Markdown/MarkdownCode.tsx
I have created several ways we can bootstrap UI Fabric. This updates the getting started with something useful.
(optional)
> Getting started - copy from wiki page

- apps/fabric-website/src/components/Site/Site.tsx
- apps/fabric-website/src/components/Site/SiteMessageBar.tsx
- apps/fabric-website/src/components/Site/customizations.ts
- apps/fabric-website/src/pages/Controls/DatePickerPage/docs/android/DateTimePickerImplementation.md
- apps/fabric-website/src/pages/Controls/DatePickerPage/docs/ios/DateTimePickerImplementation.md
- apps/fabric-website/src/pages/Controls/PersonaPage/docs/android/PersonaImplementation.md
- apps/fabric-website/src/pages/Controls/PersonaPage/docs/ios/PersonaImplementation.md
- apps/fabric-website/src/pages/Controls/ProgressIndicatorPage/docs/ios/ProgressIndicatorImplementation.md
- apps/fabric-website/src/pages/Overviews/ControlsPage/docs/web/ControlsOverview.md
- packages/example-app-base/src/components/ExampleCard/ExampleCard.styles.ts
- packages/example-app-base/src/components/ExampleCard/ExampleCard.tsx
- packages/example-app-base/src/utilities/customizations.ts
- Add message bar on home page pointing to HIG
- Hide scheme dropdown on public site
- Fix example code size, and button styles while code is shown
- Minor fixes to iOS and Android control docs
> [new website] More bug fixes

- common/changes/@uifabric/api-docs/publishApiDocs_2019-05-03-17-07.json
- packages/api-docs/README.md
- rush.json
> Publish @uifabric/api-docs

- apps/fabric-website/homepage.htm
- common/changes/@uifabric/fabric-website/devhost_2019-05-03-20-27.json
First off, the file was out of sync from the odxip location. I copied that over and then ported the logic surrounding devhost and load retry with no compress from the recent work I did with index.html
(optional)
> ported logic for devhost from index.html to homepage.htm

- apps/fabric-website/src/components/Site/Site.module.scss
- apps/fabric-website/src/pages/Overviews/ResourcesPage/docs/default/ResourcesContributionProcess.md
- apps/fabric-website/src/pages/Overviews/ResourcesPage/docs/default/ResourcesDesignResources.md
- apps/fabric-website/src/pages/Overviews/ResourcesPage/docs/default/ResourcesDeveloperResources.md
- common/changes/@uifabric/example-app-base/website-content-and-bug-fixes_2019-05-03-23-16.json
- common/changes/@uifabric/fabric-website/website-content-and-bug-fixes_2019-05-03-23-16.json
- packages/example-app-base/src/components/LoadingComponent/LoadingComponent.tsx
- packages/example-app-base/src/components/Page/Page.module.scss
Fixes:
- Sticky elements: Left nav and side rail need max-height to stick to the top.
- Footer flashing: LoadingComponent needed min-height so footer wouldn't be above the fold for .2s
- Some Resources content adjustment
> Website content and bug fixes

- common/changes/@uifabric/example-app-base/apiReferencesTableClassesFix_2019-05-04-00-03.json
- packages/example-app-base/src/components/ApiReferencesTable/ApiReferencesTable.tsx
Only render methods and members tables for classes if they are not empty.
Before:
After:
> ApiReferencesTable: fix class tables

- scripts/tasks/perf-test.js
> Add tvalue to perf stats

- apps/fabric-website/src/components/Nav/Nav.module.scss
- apps/fabric-website/src/pages/HomePage/HomePage.styles.ts
- apps/fabric-website/src/styles/_reset.scss
- common/changes/@uifabric/example-app-base/website-reset_2019-05-06-04-05.json
- common/changes/@uifabric/fabric-website/website-reset_2019-05-06-04-05.json
- packages/example-app-base/src/components/SideRail/SideRail.styles.ts
- packages/example-app-base/src/components/SideRail/SideRail.tsx
- packages/example-app-base/src/components/SideRail/SideRail.types.ts
global CSS reset was breaking shared navigation
> Removing global css reset from website

- apps/a11y-tests/src/tests/__snapshots__/Button.test.ts.snap
- apps/test-bundles/webpack.config.js
…or can tell us about changes in baseline.
Button: Adding experimental Button to test-bundles so that size-auditor can tell us about changes in baseline.
(optional)
> Button: Adding experimental Button to test-bundles so that size-auditor can tell us about changes in baseline

- apps/test-bundles/package.json
- apps/test-bundles/webpack.config.js
…nt potential breaks.
Adding @uifabric/experiments as a dependency in test-bundles to prevent potential breaks.
(optional)
> Adding @uifabric/experiments as a dependency in test-bundles to prevent potential breaks.

- apps/fabric-website/.npmignore
- common/changes/@uifabric/fabric-website/fix-md-imports_2019-05-08-22-21.json
- common/changes/office-ui-fabric-react/fix-md-imports_2019-05-08-22-21.json
- packages/office-ui-fabric-react/.npmignore
Some components, like Announced, have multiple directories for their .md files which are not currently included in the npm package like the rest of the .md files, this will now include nested .md files.
> Include markdown nested within docs folders

- common/changes/@uifabric/foundation/fix-duplicate-export_2019-05-08-15-57.json
- packages/foundation/src/index.ts
> Remove duplicate export from foundation

- common/changes/@uifabric/experiments/toggleButtons_2019-05-08-23-09.json
- packages/experiments/src/components/Button/Button.styles.ts
- packages/experiments/src/components/Button/Button.test.tsx
- packages/experiments/src/components/Button/Button.types.tsx
- packages/experiments/src/components/Button/ButtonPage.tsx
- packages/experiments/src/components/Button/MenuButton/MenuButton.types.tsx
- packages/experiments/src/components/Button/SplitButton/SplitButton.types.tsx
- packages/experiments/src/components/Button/examples/Button.Toggle.Example.tsx
This PR adds the `toggle` functionality to the new `Button`, making the necessary styling changes and adding an example and snapshot tests.
(optional)
> Button: Adding toggle/checked functionality to Button

- common/changes/office-ui-fabric-react/pb-hidden-option_2019-05-02-01-22.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.styles.ts
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.styles.ts
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.types.ts
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Advanced.Example.tsx.shot
- packages/office-ui-fabric-react/src/utilities/selectableOption/SelectableOption.types.ts
Added support to hidden options in combo box and dropdown components.
(optional)
> Add support for hidden options in dropdown and combo box

- common/changes/office-ui-fabric-react/export-responsive-mode_2019-05-08-23-53.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Dialog/DialogContent.types.ts
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.types.ts
> Export ResponsiveMode

- apps/vr-tests/package.json
- apps/vr-tests/src/stories/Card.stories.tsx
Adding vr-tests for the `Card` component.
(optional)
> Card: Adding vr-tests

- common/changes/@uifabric/experiments/jg-create-component-hooks_2019-05-09-17-08.json
- common/changes/@uifabric/foundation/jg-create-component-hooks_2019-05-09-17-08.json
- common/config/rush/common-versions.json
- packages/experiments/package.json
- packages/experiments/src/components/Button/examples/Button.Example.tsx
- packages/foundation/etc/foundation.api.md
- packages/foundation/src/IComponent.ts
- packages/foundation/src/createComponent.tsx
- scripts/templates/create-component/EmptyComponent.mustache
- scripts/templates/create-component/EmptyState.mustache
- scripts/templates/create-component/EmptyStateTest.mustache
- scripts/templates/create-component/EmptyTypes.mustache
- scripts/templates/create-component/EmptyTypesStateless.mustache
- scripts/templates/create-component/EmptyView.mustache
- scripts/templates/create-component/EmptyViewTest.mustache
Update create component script due to changes in #8931. Change involve converting state and state tests from class component approach to new functional hooks approach.
> Create Component Script: Update for State & Hooks Approach

- common/changes/@uifabric/styling/edwl-2019-05-fixThemeEffects_2019-05-09-23-32.json
- packages/styling/src/styles/theme.ts
Add misssing `_theme.effects` to `legacyLoadTheme`
(optional)
> Add _theme.effects to legacyLoadTheme

- common/changes/office-ui-fabric-react/dropdown-combobox-openonfocus_2019-05-02-17-40.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.test.tsx
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx
- packages/office-ui-fabric-react/src/utilities/selectableOption/SelectableDroppableText.types.ts
Dropdown/combobox: Add new prop to openonfocus. Additionally fix a bunch of dropdown tests that were giving false positives.
(optional)
> Dropdown/combobox: Add new prop to openonfocus

- package.json
- NA Include a change request file using `$ npm run change`
> Fix postinstall steps.

- apps/fabric-website/src/pages/HomePage/HomePage.styles.ts
- common/changes/@uifabric/fabric-website/fix-home-page-ie11_2019-05-13-22-04.json
> Fix IE11 home page styles

- package.json
Add root level update-a11y command for updating a11y snapshots easier.
(optional)
> a11y-tests: Add root level update-a11y command

- apps/pr-deploy-site/chiclet-test.html
- apps/pr-deploy-site/config/pre-copy.json
Adds the Chiclet test page to `pr-deploy-site` to be used to pull [open graph tags](http://ogp.me/) for the Chiclet demo page.
> pr-deploy-site: add Chiclet test page

- common/changes/office-ui-fabric-react/nav-8582_2019-05-14-20-28.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Nav/Nav.base.tsx
1. Refactor `Nav` to put all `isCollapsed?` logic in one place
2. Remove caching of computed values and pull from the authoritative source whenever possible
> Nav respects changes to collapsedByDefault

- apps/fabric-website/just-task.js
- apps/fabric-website/package.json
- apps/fabric-website/scripts/createFlightConfig.js
- azure-pipelines.release.yml
- common/changes/@uifabric/fabric-website/release_2019-05-14-19-10.json
- test.sh
Looks like we can shave 11 minutes on build step. We should use Linux OS for builds so that we can have more buffer from the 60 minute max on hosted agents
(optional)
> New release YML file for transitioning to Linux build for build speed

- common/changes/office-ui-fabric-react/fix-checkbox-outline_2019-05-15-20-42.json
- packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.styles.ts
- packages/office-ui-fabric-react/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/Callout.Directional.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Checkbox.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Checkbox.Other.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ContextualMenu.Directional.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dialog.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dialog.Modeless.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/MarqueeSelection.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Modal.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Modal.Modeless.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/PeoplePicker.Types.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Persona.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ResizeGroup.OverflowSet.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Horizontal.Configure.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Vertical.Configure.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/TagPicker.Basic.Example.tsx.shot
Render focus outline when focused.
> [Checkbox] Fix outline on focus.

- common/changes/@uifabric/charting/LineChartXAxisTextALignment_2019-05-14-10-05.json
- packages/charting/src/components/LineChart/LineChart.base.tsx
> Line chart x axis text alignment

- common/changes/office-ui-fabric-react/messagebar-icon-aria_2019-05-16-22-35.json
- packages/office-ui-fabric-react/src/components/MessageBar/MessageBar.base.tsx
- packages/office-ui-fabric-react/src/components/MessageBar/__snapshots__/MessageBar.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/MessageBar.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/MessageBar.Styled.Example.tsx.shot
Hide message bar icon from ARIA tree
> [MessageBar] aria hidden for message bar icon

- apps/fabric-website/src/SiteDefinition/SiteDefinition.pages/Styles/web.tsx
- common/changes/@uifabric/fabric-website/fix-styles-colors-route_2019-05-17-21-35.json
Instead of adding the component on the category definition, add it as a hidden page.
Navigate to '#/styles/web/colors'
> Fix left nav not showing on #/styles/web/colors

- apps/vr-tests/src/stories/Toggle.stories.tsx
- common/changes/office-ui-fabric-react/v-khhuy-toggle-add-element-labels_2019-05-17-21-31.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Toggle/Toggle.test.tsx
- packages/office-ui-fabric-react/src/components/Toggle/Toggle.types.ts
- packages/office-ui-fabric-react/src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Toggle/examples/Toggle.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Toggle.Basic.Example.tsx.shot
A request was made to give Toggle the ability to use a JSX Element for the label prop
> Toggle: add JSX Element type to label

- common/changes/office-ui-fabric-react/defaultFix_2019-05-21-23-16.json
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRowFields.tsx
- packages/office-ui-fabric-react/src/utilities/selectableOption/SelectableDroppableText.types.ts
Correcting a defaultvalue tag. cc(@joschect who introduced it in #8927)
> Documentation tiny fix: @default vs @defaultvalue tag in ISelectableDroppableTextProps

- apps/fabric-website/src/components/Nav/Nav.tsx
- common/changes/office-ui-fabric-react/fabric-7_2019-05-22-01-16.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.CustomMenuList.Example.tsx
- packages/office-ui-fabric-react/src/components/FloatingPicker/PeoplePicker/examples/FloatingPeoplePicker.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.base.tsx
- packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.types.ts
- packages/office-ui-fabric-react/src/components/SearchBox/examples/SearchBox.Small.Example.tsx
Re-do of #9171 as it got messed up due to a confusing merge.
> SearchBox: pass event to onChange

- scripts/just.config.js
Make sure just test is running for node-lib
(optional)
> adding back jest tests for node-libs

- common/changes/office-ui-fabric-react/rating-state_2019-05-23-17-32.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Rating/Rating.base.tsx
- packages/office-ui-fabric-react/src/components/Rating/Rating.test.tsx
remove deprecated lifecycle methods, always controlled
controlled-ness
> Rating: remove deprecated lifecycle methods, always controlled

- common/changes/@uifabric/migration/codemods_2019-05-24-18-20.json
- common/config/rush/shrinkwrap.yaml
- packages/migration/package.json
- packages/migration/src/cli/cli.test.ts
- packages/migration/src/cli/cli.ts
- packages/migration/src/index.ts
- packages/migration/src/migration.ts
- packages/migration/src/mods/7.0.0/renameReactDeprecated.ts
- packages/migration/src/mods/7.0.0/warnDetailsRowCheckIsSelectedRemoved.ts
- packages/migration/src/mods/7.0.0/warnSliderValuePositionRemoved.ts
> Migration: Non-destructive by default

- common/changes/@uifabric/migration/create-ref-mod_2019-05-25-00-12.json
- common/config/rush/shrinkwrap.yaml
- packages/migration/fixtures/7.0.0/createRef.tsx
- packages/migration/fixtures/README.md
- packages/migration/package.json
- packages/migration/src/mods/7.0.0/createRefFromReact.ts
- packages/migration/src/tests/cli.test.ts
- packages/migration/src/tests/mods/7.0.0/__snapshots__/createRefFromReact.test.ts.snap
- packages/migration/src/tests/mods/7.0.0/createRefFromReact.test.ts
- packages/migration/src/tests/mods/utils/index.ts
> CodeMod: Remove createRef imports from OUFR.

- common/changes/@uifabric/experiments/buttonUniqueId_2019-05-24-21-45.json
- packages/experiments/src/components/Button/Button.types.tsx
Button: Adding `uniqueId` prop.
(optional)
> Button: Adding uniqueId prop

- apps/perf-test/src/Scenarios.tsx
- apps/perf-test/webpack.serve.config.js
This PR adds some scenarios to the perf-tests package to test out the perf in the old and new `Button` in its `default`, `primary`, `menu` and `split` variants.
(optional)
> Button: Adding more scenarios to perf-tests

- .github/CODEOWNERS
Remove people who have never contributed or only very minimally contributed from the CODEOWNERS file.
Also directly add @lorejoh12 as a reviewer (in addition to OfficeDev/uifabric-calendar) for date-time stuff so it's more obvious who to talk to.
> Remove inactive people from codeowners

- common/changes/@uifabric/migration/combobox-props-mod_2019-05-28-19-45.json
- common/changes/@uifabric/migration/combobox-props-mod_2019-05-28-21-00.json
- packages/migration/fixtures/7.0.0/combobox.tsx
- packages/migration/fixtures/7.0.0/searchbox.tsx
- packages/migration/src/index.ts
- packages/migration/src/migration.ts
- packages/migration/src/mods/7.0.0/comboboxOnChangedPropsChange.ts
- packages/migration/src/mods/7.0.0/comboboxPropsChange.ts
- packages/migration/src/mods/7.0.0/comboboxValuePropChange.ts
- packages/migration/src/mods/7.0.0/searchBoxPropsArgs.ts
- packages/migration/src/mods/7.0.0/warnSliderValuePositionRemoved.ts
- packages/migration/src/tests/mods/7.0.0/__snapshots__/comboboxPropsChange.test.ts.snap
- packages/migration/src/tests/mods/7.0.0/comboboxPropsChange.test.ts
- packages/migration/src/tests/mods/7.0.0/createRefFromReact.test.ts
- packages/migration/src/tests/mods/7.0.0/searchBoxOnChangeProp.test.ts
- packages/migration/src/tests/mods/utils/index.ts
Codemod to update props for `ComboBox`.
> ComboBox props codemod

- common/changes/@uifabric/charting/charting-build_2019-05-29-19-30.json
- packages/charting/just.config.js
Call the preset function in charting's just.config.js so the build works.
> Fix charting build

- common/changes/office-ui-fabric-react/fix-dropdownselect_2019-05-29-17-43.json
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx
fix issue where dropdown wouldn't respect the selectedkey(s) prop
(optional)
> Dropdown: fix issue where dropdown wouldn't respect the selectedkey(s) prop

- common/changes/@uifabric/migration/nav-codemod_2019-05-29-19-41.json
- packages/migration/fixtures/7.0.0/nav.tsx
- packages/migration/src/mods/7.0.0/navToLegacy.ts
- packages/migration/src/tests/mods/7.0.0/__snapshots__/createRefFromReact.test.ts.snap
- packages/migration/src/tests/mods/7.0.0/__snapshots__/navPackageMove.test.ts.snap
- packages/migration/src/tests/mods/7.0.0/navPackageMove.test.ts
- packages/migration/src/util/MoveImports.ts
codemod for `@uifabric/legacy`
> Nav: Codemod for move to @uifabric/legacy

- common/changes/office-ui-fabric-react/fix-dropdown_2019-06-03-16-25.json
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx
Fix issue where dropdown on change wasn't called.
The regression was introduced in pr #9263 
(optional)
> Dropdown: fix on change

- common/changes/@uifabric/experiments/fishibru-AddPublishSignal_2019-06-03-17-19.json
- packages/experiments/src/components/signals/Signals.scss
- packages/experiments/src/components/signals/Signals.tsx
- packages/experiments/src/components/signals/examples/Signals.Basic.Example.tsx
Description of changes
- Signal added to show if a given page has been updated and needs republishing.
> added a signal for use of pages need republishing

- common/changes/office-ui-fabric-react/Coachmark_2019-06-03-23-26.json
- packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.base.tsx
- packages/office-ui-fabric-react/src/components/Coachmark/examples/Coachmark.Basic.Example.tsx
> Coachmark: fix defaulting of the color to pull from theme

- apps/dom-tests/src/index.tsx
Fixes an incorrect import path in `dom-tests`
(optional)
> dom-tests: fix import path

- common/changes/office-ui-fabric-react/edwl-2019-06-fixPlaceholderIconRender_2019-06-04-00-50.json
- packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx
Render placeholder icon if string iconName is empty string
(optional)
> Update BaseButton to render placeholder icon if string is empty

- common/changes/@uifabric/merge-styles/jg-fix-ts35-issues_2019-06-04-15-55.json
- common/changes/office-ui-fabric-react/jg-fix-ts35-issues_2019-06-04-15-55.json
- packages/merge-styles/etc/merge-styles.api.md
- packages/merge-styles/src/IStyleSet.ts
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/DetailsList/ShimmeredDetailsList.types.ts
Fix TypeScript issues found in reference project provided in #9280. These same issues were previously fixed in `fabric-7` branch (one exactly the same, one indirectly via props change.)
> Fix TypeScript 3.5 Issues

- apps/fabric-website/src/styles/_base.scss
- common/changes/@uifabric/fabric-website/fix-style-typo_2019-06-05-19-40.json
There was a typo in my feedback button classname. These changes are difficult to test locally :(
> UHF style overrides: Fix class typo

- common/changes/@uifabric/utilities/selection-import_2019-06-05-22-12.json
- packages/utilities/src/index.ts
Fixed an import which breaks AMD bundlers.
> Fix ./index import from Selection

- scripts/templates/create-page/EmptyDoc.mustache
- scripts/templates/create-page/EmptyPageBase.mustache
Somehow references to fabric-website-internal made it into the script template. This replaces the imports and repo links with the right strings.
> Fix create-page script

- common/changes/@uifabric/date-time/lorejoh12-dateTimeStyleImprovements_2019-06-06-18-38.json
- packages/date-time/src/components/Calendar/Calendar.styles.ts
- packages/date-time/src/components/Calendar/CalendarDay/CalendarDay.styles.ts
- packages/date-time/src/components/Calendar/CalendarMonth/CalendarMonth.base.tsx
- packages/date-time/src/components/Calendar/CalendarPicker/CalendarPicker.styles.ts
- packages/date-time/src/components/Calendar/CalendarPicker/CalendarPicker.types.ts
- packages/date-time/src/components/Calendar/CalendarYear/CalendarYear.base.tsx
Upgrading styles to conform to former OUFR designs
(optional)
> adding styling fixes for regressions from OUFR conversion

- common/changes/@uifabric/example-app-base/example-fonts_2019-06-07-00-27.json
- packages/example-app-base/src/components/ComponentPage/ComponentPage.styles.ts
- packages/example-app-base/src/components/ExampleCard/ExampleCard.styles.ts
- packages/example-app-base/src/components/FeedbackList/FeedbackList.styles.ts
- packages/example-app-base/src/components/Header/Header.styles.ts
- packages/example-app-base/src/components/Markdown/MarkdownParagraph.tsx
- packages/example-app-base/src/components/PropertiesTable/PropertiesTableSet.styles.ts
- packages/example-app-base/src/components/SideRail/SideRail.styles.ts
Since Vitalie has reverted the change that made each font size (such as "medium") bigger, revert my "fix" to that change in example-app-base.
> Revert example-app-base font changes

- common/changes/@uifabric/migration/fabric-7_2019-06-07-20-00.json
- common/config/rush/shrinkwrap.yaml
- packages/migration/package.json
> Migration: bump version of riceburn

- common/changes/@uifabric/charting/lineChartFirefoxIssue_2019-06-10-10-36.json
- packages/charting/src/components/LineChart/examples/LineChart.Multiple.Example.tsx
- packages/charting/src/components/LineChart/examples/LineChart.Styled.Example.tsx
- Fix Line chart Firefox issue
- example we pass need to be correct format which is supported to all browsers 
####screenshot
(optional)
> Fix Line chart Firefox issue 

- apps/a11y-tests/src/tests/__snapshots__/ComponentExamples.test.tsx.snap
> Update a11y tests

- common/changes/@uifabric/experiments/removeShimmer_2019-05-03-00-01.json
- common/changes/@uifabric/styling/fontRemap_2019-06-06-00-04.json
- common/changes/office-ui-fabric-react/personaInitialColorsRemapAndNew_2019-05-02-00-05.json
- common/changes/office-ui-fabric-react/removeShimmerFomDetailsList_2019-05-07-00-03.json
- common/changes/office-ui-fabric-react/shimmerDetailsListPropsRemoval_2019-04-14-00-02.json
Adding manually some change files to better document some of the changes I've made against ` fabric-7` branch.
> Fabric 7: Add some change files for breaking changes

- common/changes/office-ui-fabric-react/issue9385_2019-06-10-22-19.json
- packages/office-ui-fabric-react/src/components/Stack/examples/Stack.Horizontal.HorizontalAlign.Example.tsx
- packages/office-ui-fabric-react/src/components/Stack/examples/Stack.Horizontal.Spacing.Example.tsx
- packages/office-ui-fabric-react/src/components/Stack/examples/Stack.Horizontal.VerticalAlign.Example.tsx
- packages/office-ui-fabric-react/src/components/Stack/examples/Stack.Horizontal.Wrap.Example.tsx
- packages/office-ui-fabric-react/src/components/Stack/examples/Stack.Horizontal.WrapAdvanced.Example.tsx
- packages/office-ui-fabric-react/src/components/Stack/examples/Stack.Horizontal.WrapNested.Example.tsx
- packages/office-ui-fabric-react/src/components/Stack/examples/Stack.Vertical.HorizontalAlign.Example.tsx
- packages/office-ui-fabric-react/src/components/Stack/examples/Stack.Vertical.VerticalAlign.Example.tsx
- packages/office-ui-fabric-react/src/components/Stack/examples/Stack.Vertical.Wrap.Example.tsx
- packages/office-ui-fabric-react/src/components/Stack/examples/Stack.Vertical.WrapAdvanced.Example.tsx
- packages/office-ui-fabric-react/src/components/Stack/examples/Stack.Vertical.WrapNested.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Horizontal.HorizontalAlign.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Horizontal.Spacing.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Horizontal.VerticalAlign.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Horizontal.Wrap.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Horizontal.WrapAdvanced.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Horizontal.WrapNested.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Vertical.HorizontalAlign.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Vertical.VerticalAlign.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Vertical.Wrap.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Vertical.WrapAdvanced.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Vertical.WrapNested.Example.tsx.shot
CSS performance is improved when the rightmost selector in a compound selector matches the fewest number of elements. CSS class names, as opposed to tag names are therefore preferred as the last selector. For more info see:
https://www.stevesouders.com/blog/2009/06/18/simplifying-css-selectors/
https://stackoverflow.com/questions/5797014/why-do-browsers-match-css-selectors-from-right-to-left
Sample code for Stack control
> Improve Stack sample code for performance

- apps/fabric-website/webpack.config.js
- apps/fabric-website/webpack.uhf.serve.config.js
- common/changes/@uifabric/fabric-website/react-bundle_2019-06-12-16-16.json
Bundling the exact react version that works with the site so that there's no mismatched react versions deployed to the livesite. 
(optional)
> React bundled with the website

- common/changes/office-ui-fabric-react/issue9408_2019-06-12-18-00.json
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts
- packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Documents.Example.tsx
Updated DetailsList example code to provide getKey prop. This is needed to make selection work correctly when sorting and filtering are enabled.
(optional)
> Update DetailsList example to make selection work correctly when sorting / filtering

- common/changes/@uifabric/charting/multipleStackedBarLegendDup_2019-06-07-07-29.json
- packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/examples/MultiStackedBarChart.Example.tsx
Package:- **Charting** 
Merging the legends with similar legend(name) and color in Multi Stacked Bar Chart.
Charting ==> StackedBarChart ==> Multiple StackedBarCharts
> Resolved the issue of the legends repeating even with same color and legend

- common/changes/@uifabric/api-docs/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/azure-themes/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/charting/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/codepen-loader/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/date-time/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/example-app-base/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/experiments/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/fabric-website-resources/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/fabric-website/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/file-type-icons/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/fluent-theme/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/foundation/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/icons/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/jest-serializer-merge-styles/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/merge-styles/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/migration/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/prettier-rules/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/react-cards/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/styling/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/test-utilities/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/theme-samples/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/tslint-rules/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/utilities/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/variants/rush-down_2019-06-13-17-38.json
- common/changes/@uifabric/webpack-utils/rush-down_2019-06-13-17-38.json
- common/changes/office-ui-fabric-react/rush-down_2019-06-13-17-38.json
v7.x published without changefiles. Root cause is fixed with fa84fcc8dd7fa806d740e354e7bba95ab5183de4 and this will allow republishing.
> Changefiles to publish patch release and regain minified versions.

- package.json
#9437 highlighted an issue with checkchange checking against master instead of 6.0. This PR fixes that.
> 6.0: Fix Rush change check.

- apps/fabric-website/src/pages/Overviews/ResourcesPage/docs/default/ResourcesDeveloperResources.md
- common/changes/@uifabric/fabric-website/vibraga-entrypoint_2019-06-15-06-17.json
Adding some links to the fabric website resources page to serve as entry points to documentation.
> Fabric website: add documentation entry points.

- apps/fabric-website/src/SiteDefinition/SiteDefinition.tsx
- apps/fabric-website/src/pages/HomePage/HomePage.base.tsx
- common/changes/@uifabric/example-app-base/jahnp-update-naming_2019-06-18-17-24.json
- common/changes/@uifabric/fabric-website/jahnp-update-naming_2019-06-18-17-24.json
- packages/example-app-base/src/utilities/baseDefinition.tsx
For now, we need to rename instances of "Microsoft UI Fabric" to "UI Fabric".
> Temporary name update

- common/changes/office-ui-fabric-react/fix-combobox-styling_2019-06-19-23-00.json
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.styles.ts
- packages/office-ui-fabric-react/src/components/__snapshots__/ComboBox.Basic.Example.tsx.shot
Combobox: Fix styling to correctly allow rootChecked to get passed in.
(optional)
> Combobox: Fix styling

- common/changes/@uifabric/utilities/hotfix-merge-styles_2019-06-21-01-54.json
- packages/utilities/src/classNamesFunction.ts
A report escalated about missing null check in the new style optimization. Adding.
> Adding a null check to the caching to deal with missing stylesheet objects

- common/changes/@uifabric/styling/6.0_2019-06-19-23-32.json
- packages/styling/src/interfaces/ISemanticTextColors.ts
Updating comments of errorText, warningText, and successText.
(optional)
> Fabric 6: Updating comments of text color semantic slots.

- common/changes/office-ui-fabric-react/mapol-persona-dual-presence_2019-06-13-19-39.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Persona/Persona.base.tsx
- packages/office-ui-fabric-react/src/components/Persona/Persona.doc.tsx
- packages/office-ui-fabric-react/src/components/Persona/Persona.types.ts
- packages/office-ui-fabric-react/src/components/Persona/PersonaCoin/PersonaCoin.base.tsx
- packages/office-ui-fabric-react/src/components/Persona/PersonaCoin/__snapshots__/PersonaCoin.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Persona/PersonaConsts.tsx
- packages/office-ui-fabric-react/src/components/Persona/PersonaPresence/PersonaPresence.base.tsx
- packages/office-ui-fabric-react/src/components/Persona/PersonaPresence/PersonaPresence.styles.ts
- packages/office-ui-fabric-react/src/components/Persona/PersonaPresence/PersonaPresence.test.tsx
- packages/office-ui-fabric-react/src/components/Persona/PersonaPresence/__snapshots__/PersonaPresence.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Persona/__snapshots__/Persona.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Persona/examples/Persona.Presence.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Persona.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Persona.CustomRender.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Persona.Presence.Example.tsx.shot
- scripts/tasks/lint-imports.js
This is a cherry-pick of #9451 to 6.0
(optional)
> Cherry pick dual presence

- common/changes/@uifabric/fluent-theme/v-mare-Spinner-fluent-updates_2019-06-24-17-30.json
- packages/fluent-theme/src/fluent/FluentStyles.ts
- packages/fluent-theme/src/fluent/styles/Spinner.styles.ts
- [] Addresses an existing issue: #7121 
Updated Spinner margin size and label font size to match fluent toolkit.
(optional)
> Spinner: fluent updates

- common/changes/@uifabric/styling/semantic_slots1_2019-06-21-22-05.json
- packages/styling/etc/styling.api.md
- packages/styling/src/interfaces/ISemanticTextColors.ts
- packages/styling/src/styles/theme.ts
Initially only made this change in 6.0 to fix an a11y bug in sharepoint, porting it over to master/7.0 too now. 
(optional)
> Semantic slots: added successText. 

- apps/fabric-website/src/pages/HomePage/HomePage.base.tsx
- common/changes/@uifabric/fabric-website/website7again_2019-06-27-18-57.json
Somehow I checked this part in to 5.0 and 6.0 but forgot it for master...?
> Add Fabric 7 to website version selector

- common/changes/@uifabric/charting/DonutchartLegendsIssue_2019-06-25-13-12.json
- packages/charting/src/components/DonutChart/DonutChart.base.tsx
> Donutchart legends issue

- common/changes/office-ui-fabric-react/6075-ListGhostingTypeChecking_2019-06-27-14-28.json
- packages/office-ui-fabric-react/src/components/List/examples/List.Ghosting.Example.tsx
- Added interfaces to theme and classNames in Ghosting Example
> 6075-List Ghosting Example Type Checking

- apps/fabric-website/src/SiteDefinition/SiteDefinition.tsx
- apps/fabric-website/src/pages/HomePage/HomePage.base.tsx
- common/changes/@uifabric/example-app-base/jahnp-update-v6-naming_2019-06-27-20-27.json
- common/changes/@uifabric/fabric-website/jahnp-update-v6-naming_2019-06-21-23-32.json
- packages/example-app-base/src/utilities/baseDefinition.tsx
Carries over the temporary name change from #9496 to 6.0
> Temporary name update - 6

- common/changes/office-ui-fabric-react/keco-fix-groupshowall_2019-06-27-19-58.json
- packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.test.tsx
- packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx
Cherry-pick of https://github.com/OfficeDev/office-ui-fabric-react/pull/9610 to fix https://github.com/OfficeDev/office-ui-fabric-react/issues/9561.
cc: @dliu120
> [6.0] GroupedList: Fix "Show All" not rendering all items in a section

- apps/a11y-tests/src/tests/__snapshots__/ComponentExamples.test.tsx.snap
Build is broken, update snapshots
(optional)
> Build recovery: update snapshots

- common/changes/office-ui-fabric-react/splitmenubutton-props_2019-07-01-23-32.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx
- packages/office-ui-fabric-react/src/components/Button/Button.types.ts
Add in experimental props to provide support for very specific split button scenarios.
(optional)
> add in split menu props

- common/changes/@uifabric/experiments/buttonSemanticSlots_2019-07-01-23-45.json
- common/changes/@uifabric/styling/buttonSemanticSlots_2019-07-01-23-45.json
- common/changes/office-ui-fabric-react/buttonSemanticSlots_2019-07-01-23-45.json
- packages/experiments/src/components/Button/Button.styles.ts
- packages/experiments/src/components/Button/SplitButton/SplitButton.styles.ts
- packages/office-ui-fabric-react/src/components/Button/ButtonThemes.ts
- packages/styling/src/styles/theme.ts
This PR updates some of the `Button` styling to use the correct `semanticColors` as well as updating some of the `semanticColors` to use the `palette` colors corresponding to the correct Fluent configuration.
(optional)
> Button: Updating semantic slots

- packages/tsx-editor/package.json
- packages/tsx-editor/src/components/Editor.tsx
- packages/tsx-editor/src/components/Editor.types.ts
- packages/tsx-editor/src/demo/App.tsx
Editor component rewritten using hooks
Dependencies changed to avoid build failures
(optional)
> Updating tsx-editor component and dependencies

- change/office-ui-fabric-react-2019-07-02-16-29-11-fix-extendedpicker-tests.json
- packages/office-ui-fabric-react/src/components/ExtendedPicker/BaseExtendedPicker.test.tsx
- packages/office-ui-fabric-react/src/components/ExtendedPicker/__snapshots__/BaseExtendedPicker.test.tsx.snap
> ExtendedPicker: Fix tests

- packages/lists/README.md
- packages/lists/package.json
- packages/lists/src/components/FixedList/FixedList.tsx
- packages/lists/src/components/FixedList/FixedList.types.ts
- packages/lists/src/components/Viewport/Viewport.tsx
- packages/lists/src/components/Viewport/Viewport.types.ts
- packages/lists/src/components/Viewport/useDebouncedTimeout.ts
- packages/lists/src/components/Viewport/useDecouncedTimeout.ts
- packages/lists/src/components/Viewport/usePreviousValue.ts
Initial implementation of:
- `Viewport` for defining a scroll container
- `FixedList` for rendering a collection of items with virtualization inside a `Viewport`, where the assumption is that all items have the same fixed height
We aren't yet publishing the `@uifabric/lists` package so a change file was not requested.
> @uifabric/lists: Add Viewport and FixedList component

- common/changes/office-ui-fabric-react/panel-height_2019-06-27-20-36.json
- packages/office-ui-fabric-react/src/components/Layer/Layer.styles.ts
* Use absolute positioning instead of viewport for Layer styles
* Update TextField snapshots
* Add change file
* Revert unwanted TextField snapshot changes
(optional)
> Cherry-pick Panel beneath header (#9612) into 6.0

- change/office-ui-fabric-react-2019-07-03-12-34-04-buttonExampleUpdate.json
- packages/office-ui-fabric-react/src/components/Button/examples/Button.Default.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Button.Default.Example.tsx.shot
This PR updates the `Button` example to make it less confusing for screen readers as discussed in #9685.
(optional)
>  Button: Updating example to make it less confusing to screen readers

- common/changes/office-ui-fabric-react/marygans-fluentRating_2019-06-26-22-31.json
- packages/office-ui-fabric-react/src/components/Rating/Rating.styles.ts
- packages/office-ui-fabric-react/src/components/Rating/__snapshots__/Rating.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/Rating.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Rating.ButtonControlled.Example.tsx.shot
Updated the rating rest state icon color to match current Fabric design spec in toolkit
**Before**
**After**
> Rating: Fluent Updates

- change/office-ui-fabric-react-2019-07-04-13-34-32-nasabek-fixAligmentProblem.json
- common/changes/office-ui-fabric-react/nasabek-fixAligmentProblem_2019-06-25-23-13.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx
- packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.types.ts
when we Set focus to a specific child, we should recalculate the alignment depend on its position
> fix the vertical alignment problem

- apps/fabric-website/src/pages/HomePage/HomePage.base.tsx
- common/changes/@uifabric/fabric-website/6.0_2019-07-03-00-57.json
Fix the version selector some more...
> Fix website version selection (v6 edition)

- change/office-ui-fabric-react-2019-07-02-13-25-32-panelOverlayProps.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Panel/Panel.base.tsx
- packages/office-ui-fabric-react/src/components/Panel/Panel.types.ts
This PR adds `overlayProps` as a property in `Panel` to allow for further customization of the component. 
(optional)
>  Panel: Adding Overlay props.

- change/office-ui-fabric-react-2019-07-08-14-24-41-marygans-fixPR.json
- packages/office-ui-fabric-react/src/components/Pivot/__snapshots__/Pivot.deprecated.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Pivot/__snapshots__/Pivot.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/Keytips.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Fabric.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.IconCount.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Large.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.OnChange.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Override.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Remove.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Separate.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.SeparateNoSelectedKey.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Tabs.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.TabsLarge.Example.tsx.shot
Fixing Master branch broken state due to stale PR:9595
> Updating Snapshots: fixing master branch broken state due to stale PR

- change/office-ui-fabric-react-2019-07-08-18-27-16-shield-pickersSuggestionRef.json
- packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx
Making a targeted fix to unblock product rollout (Word-online).
> Pickers: fixes suggestions ref react warning.

- change/office-ui-fabric-react-2019-07-08-17-41-20-master.json
- packages/office-ui-fabric-react/src/components/Nav/Nav.styles.ts
- packages/office-ui-fabric-react/src/components/Nav/__snapshots__/Nav.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/Nav.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Nav.CustomGroupHeaders.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Nav.Nested.Example.tsx.shot
Fixes focus border in HC mode for every Nav item.
> Nav: focus border in HC mode.Nav

- change/office-ui-fabric-react-2019-07-03-16-12-51-dropdownChevronAriaHidden.json
- common/changes/office-ui-fabric-react/dropdownChevronAriaHidden6.0_2019-07-09-22-27.json
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx
Cherry picks Dropdown changes from https://github.com/OfficeDev/office-ui-fabric-react/pull/9728 into 6.0.
(optional)
> [cherry-pick 6.0] Dropdown: add aria hidden attribute to icon (#9728)

- change/office-ui-fabric-react-2019-07-09-11-41-53-marygans-pivotColors.json
- packages/office-ui-fabric-react/src/components/Pivot/Pivot.styles.ts
- packages/office-ui-fabric-react/src/components/Pivot/__snapshots__/Pivot.deprecated.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Pivot/__snapshots__/Pivot.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/Keytips.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Fabric.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.IconCount.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Large.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.OnChange.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Override.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Remove.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Separate.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.SeparateNoSelectedKey.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Tabs.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.TabsLarge.Example.tsx.shot
Updated pivot hover background to neutralLighter from white to match design spec.
> Pivot: Update hover background color

- common/changes/office-ui-fabric-react/hotfix-marquee-selection_2019-07-10-21-57.json
- packages/office-ui-fabric-react/src/components/MarqueeSelection/MarqueeSelection.base.tsx
Cherry-pick of #9762 to `6.0`.
> [Cherry-pick] Fix Marquee selection clobbering Selection events

- change/office-ui-fabric-react-2019-07-10-16-59-11-shield-shadesFunctionClamp.json
- packages/office-ui-fabric-react/src/utilities/color/shades.ts
Reuse of an already existing `clamp` function in OUFR utilities.
> OUFR utilities: reuse an existing clamp function

- packages/tsx-editor/src/components/Editor.tsx
- packages/tsx-editor/src/components/Editor.types.ts
Changed import path to allow for access to monaco languages in addition to editor. JSX tags no longer resulting in errors and model disposed after use.
(optional)
> Quick fix to editor for multiple instance management and JSX tags

- change/@uifabric-experiments-2019-07-10-13-57-10-chicletFixes.json
- packages/experiments/src/components/Chiclet/ChicletPage.tsx
- packages/experiments/src/components/Chiclet/ChicletXsmall.styles.tsx
- packages/experiments/src/components/Chiclet/__snapshots__/ChicletXsmall.test.tsx.snap
- packages/experiments/src/components/Chiclet/examples/Chiclet.Basic.Example.tsx
- packages/experiments/src/components/Chiclet/examples/Chiclet.Breadcrumb.Example.tsx
- packages/experiments/src/components/Chiclet/examples/Chiclet.Footer.Example.tsx
- packages/experiments/src/components/Chiclet/examples/Chiclet.Xsmall.Example.tsx
- packages/experiments/src/components/Chiclet/examples/Chiclet.Xsmall.Footer.Example.tsx
This PR has some small cosmetic changes to the Chiclet examples.
* adjusts the XSmall Chiclet title height
* makes the examples Function Components
* uses the Text control to render text in the footer examples
* changes the sample urls and names
(optional)
> [@uifabric/experiments] Chiclet: small changes to examples

- change/office-ui-fabric-react-2019-07-04-13-34-32-nasabek-fixAligmentProblem.json
- common/changes/office-ui-fabric-react/nasabek-fixAligmentProblem_2019-06-25-23-13.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx
- packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.types.ts
This PR is a cherrypick of #9534 into the Fabric 6.0 branch to fix vertical alignment in the `FocusZone` component.
(optional)
> FocusZone:  Cherry pick Fix the vertical alignment problem

- apps/perf-test/src/scenarioNames.js
- apps/perf-test/tasks/flamegraph/flamebearer.js
- apps/perf-test/tasks/flamegraph/helpers.js
- apps/perf-test/tasks/flamegraph/index.html
- apps/perf-test/tasks/flamegraph/viz.js
- apps/perf-test/tasks/perf-test.js
Improvements to Flamegraphs:
- Add ability to filter out Framework and System calls.
- Always show descendants regardless of width.
- Always make descendants show hover info and clickable regardless of width.
- Recalculate percentages when changing the top level function displayed.
> Perf Test: Flamegraph Improvements

- apps/vr-tests/package.json
- common/config/rush/shrinkwrap.yaml
> Bumping screener packages

- apps/vr-tests/package.json
- common/config/rush/shrinkwrap.yaml
> Bumping screener packages (cherrypick of #9853 into Fabric 6)

- change/@uifabric-date-time-2019-07-17-17-02-56-lorejoh12-addingTouchWeeklyDayPicker.json
- packages/date-time/src/components/WeeklyDayPicker/WeeklyDayPicker.base.tsx
- packages/date-time/src/components/WeeklyDayPicker/WeeklyDayPicker.styles.ts
Adding touch control for navigation in weekly day picker.
Draft PR because I'm generating a build link to make sure it works before publishing. :)
(optional)
> Adding touch for navigation in WeeklyDayPicker

- change/office-ui-fabric-react-2019-07-19-11-46-31-details-basecomponent.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Check/Check.base.tsx
- packages/office-ui-fabric-react/src/components/Check/Check.types.ts
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRowCheck.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRowFields.tsx
Removing BaseComponent inheritance in Details____ components, and converting a couple of extremely simple stateless class components to function components.
Also replacing bind() usage in Details____ files with lambda functions.
> DetailsList: Remove BaseComponent inheritance and some unnecessary class components

- change/office-ui-fabric-react-2019-07-19-09-38-23-fix-layer-example.json
- packages/office-ui-fabric-react/src/components/Layer/examples/Layer.Customized.Example.tsx
LayerExample: Fix it so that panel dismisses properly.
(optional)
> LayerExample: Fix it so that panel dismisses properly.

- change/office-ui-fabric-react-2019-07-21-23-15-27-details-cleanup.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.types.ts
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.types.ts
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRowFields.types.ts
- packages/office-ui-fabric-react/src/utilities/dragdrop/DragDropHelper.tsx
Addressing assorted minor issues I noticed while looking into DetailsRow perf--mainly cleaner DragDropHelper initialization handling and removing things from state that don't need to be there. Probably won't have much/any impact on perf. (This was originally part of a larger change, but I pulled it out to make the parts of the change easier to review.)
> Details____ general cleanup

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- azure-pipelines.release.yml
- package.json
- scripts/just.config.js
- scripts/tasks/generate-package-manifest.js
- yarn.lock
Some workflows from dependent teams rely on rush.json from the past that listed all the projects in one go. I'm using this change to start publishing an alternate .json file that contain the same info in different format for those consumers.
(optional)
> adds generate-package-manifest task, update just-task and other post lerna world fun

- change/office-ui-fabric-react-2019-07-22-13-52-55-combobox-disabled.json
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
> Multiselect ComboBox options should respect disabled setting

- common/changes/office-ui-fabric-react/panel-classnames-recalc_2019-06-26-00-10.json
- common/changes/office-ui-fabric-react/panel-remove-windowheight_2019-07-02-01-32.json
- packages/office-ui-fabric-react/src/components/Panel/Panel.base.tsx
- packages/office-ui-fabric-react/src/components/Panel/Panel.styles.ts
- packages/office-ui-fabric-react/src/components/Panel/__snapshots__/Panel.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Panel/examples/Panel.Scroll.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Panel.HiddenOnDismiss.Example.tsx.shot
Cherry picks of panel bug fixes requested by @kkjeer 
(optional)
> Cherry pick PRs #9654 and #9580 into 6.0

- change/office-ui-fabric-react-2019-07-23-08-22-05-choicegroup-type.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.test.tsx
- packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.types.ts
- packages/office-ui-fabric-react/src/components/ChoiceGroup/__snapshots__/ChoiceGroup.test.tsx.snap
Expanding typings to include input attributes.
> ChoiceGroup: Updating typings for options to include input attributes.

- change/office-ui-fabric-react-2019-07-24-19-12-32-vibraga-ShimmeredDetailsList-onRenderMissingItem.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/DetailsList/ShimmeredDetailsList.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/ShimmeredDetailsList.types.ts
> ShimmeredDetailsList: enable execution of additional logic before rendering the shimmer row.

- apps/vr-tests/package.json
- apps/vr-tests/screener.config.js
- apps/vr-tests/screener.local.config.js
- common/config/rush/npm-shrinkwrap.json
> Bumping screener packages (cherrypick of #9853 into Fabric 5).

- azure-pipelines.yml
Disable deprecated version of perf-test to prevent CI timeouts.
> 6.0: Disable Perf Test

- package.json
- scripts/package.json
- yarn.lock
Beachball has some new usability changes with this bump:
1. customized change file hint
2. additional message when change file is already in the local branch
3. indication of generated and committed change files
4. manually create change files with command line args
5. disabled major as an allowed change type in our repo!
(optional)
> Bumps beachball for usability upgrades

- change/@uifabric-azure-themes-2019-07-25-11-05-53-master.json
- packages/azure-themes/README.md
Fixed Typo in Azure Theme README
(optional)
> Fix Typo in README (s)

- change/@uifabric-example-app-base-2019-07-26-18-53-25-vibraga-MessageBar-strog-variant-theme.json
- packages/example-app-base/src/components/ApiReferencesTable/ApiReferencesTable.tsx
- packages/example-app-base/src/components/ApiReferencesTable/ApiReferencesTableSet.tsx
- packages/example-app-base/src/components/ComponentPage/ComponentPage.tsx
- packages/example-app-base/src/utilities/createDemoApp.tsx
Replacing deprecated `Stack` props to remove the console warning in the browser
> Example-app-base: replace deprecated Stack props

- change/office-ui-fabric-react-2019-07-26-13-41-47-dropdown-fix.json
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx
- packages/office-ui-fabric-react/src/components/Panel/Panel.types.ts
Dropdown: Panel now dismisses in small widths
> Dropdown: Panel now dismisses in small widths

- common/changes/office-ui-fabric-react/hotfix-6.0-details-animations_2019-07-29-03-55.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRowFields.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRowFields.types.ts
- packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
- packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsRow.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/Announced.BulkOperations.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Announced.QuickActions.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Advanced.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Animation.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Compact.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.CustomColumns.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.CustomFooter.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.CustomGroupHeaders.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.CustomRows.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Documents.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.DragDrop.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Grouped.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Grouped.Large.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.NavigatingFocus.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/FocusZone.List.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/HoverCard.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/HoverCard.PlainCard.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/HoverCard.Target.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Text.Ramp.Example.tsx.shot
Cherry-pick of #9949 to `6.0` branch.
> [Cherry-pick] Fix cell animations so they only trigger on valid cell key changes

- apps/a11y-tests/src/tests/ComponentExamples.test.tsx
This PR extends each a11y test's timeout to 20 secs (same with #9616 on master).
(optional)
> a11y-tests: Extend each component's testing deadline

- change/office-ui-fabric-react-2019-07-02-15-24-59-reedpa-morecomboboxoptions.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Callout/Callout.types.ts
- packages/office-ui-fabric-react/src/components/Callout/CalloutContent.base.tsx
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.types.ts
Add new ways for callers to control the behavior of the combo box.
Cherry-pick from master branch.
> Add new ways for callers to control the behavior of the combo box 

- change/@uifabric-experiments-2019-07-30-10-32-51-cliffkoh-persona.json
- change/office-ui-fabric-react-2019-07-25-13-59-00-master.json
- packages/experiments/src/components/SelectedItemsList/SelectedPeopleList/__snapshots__/SelectedPeopleList.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Persona/Persona.styles.ts
- packages/office-ui-fabric-react/src/components/Persona/PersonaCoin/__snapshots__/PersonaCoin.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Persona/__snapshots__/Persona.deprecated.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Persona/__snapshots__/Persona.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/Persona.Alternate.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Persona.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Persona.Colors.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Persona.CustomCoinRender.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Persona.CustomRender.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Persona.Initials.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Persona.Presence.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Persona.UnknownPersona.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/SelectedPeopleList.Controlled.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Shimmer.LoadData.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/__snapshots__/PeoplePicker.test.tsx.snap
Fix the issue reported in #9939 by removing unnecessary nesting.
Codepen after fix:
Codepen before fix:
> Persona: Fix styles issue caused by unnecessary nesting

- scripts/updateReleaseNotes.js
This should loop through all releases (instead of just the first one) to update the notes
(optional)
> Fixing release notes: make sure to loop all notes to release

- .github/CODEOWNERS
Update code owners file for the `sizeauditor.json` file
(optional)
> update code owners for sizeauditor.json file

- change/office-ui-fabric-react-2019-07-29-13-10-42-command-bar-expose-datadidrender.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.base.tsx
- packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.types.ts
Cherry picking #9979 into 6.0 so it can be consumed in AI Builder.
> Fabric 6: Cherry pick - Command bar expose datadidrender

- package.json
- scripts/package.json
- yarn.lock
Bumps beachball in this branch to pick out the correct upstream remote  
(optional)
> bumps beachball to include a fix to pick out the correct upstream

- apps/fabric-website/src/pages/Overviews/GetStartedPage/docs/web/GetStartedDevelopSimple.md
- apps/fabric-website/src/pages/Overviews/GetStartedPage/docs/web/GetStartedOverview.md
- change/@uifabric-fabric-website-2019-08-07-13-39-25-vibraga-markdown-bookmarks-fix.json
Fix some markdown bookmarks to enable click navigation to the bookmarked sections.
> Fabric webiste: fix some markdown bookmarks

- change/office-ui-fabric-react-2019-07-22-13-08-40-t-mashia-add_ariaLabelForToggleAllGroupsButton.json
- change/office-ui-fabric-react-2019-08-07-15-55-26-t-mashia-add_ariaLabelForToggleAllGroupsButton_cherrypick.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.CustomGroupHeaders.Example.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Grouped.Large.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.CustomGroupHeaders.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Grouped.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Grouped.Large.Example.tsx.shot
Cherry picked PR #10056 into version 6.0
(Added detailsHeaderProp to IDetailsListProps to allow for additional properties of details headers to be rendered.)
(optional)
> T mashia/add aria label for toggle all groups button cherrypick

- change/@uifabric-experiments-2019-08-08-18-20-20-chicletPreviewStylingFix.json
- packages/experiments/src/components/Chiclet/ChicletCard.base.tsx
- packages/experiments/src/components/Chiclet/ChicletXsmall.base.tsx
- packages/experiments/src/components/Chiclet/__snapshots__/Chiclet.test.tsx.snap
- packages/experiments/src/components/Chiclet/examples/Chiclet.Xsmall.Footer.Example.tsx
Fixes a bug where the preview image would overflow
(optional)
> Chiclet: Preview image fix

- change/@uifabric-api-docs-2019-08-09-13-30-02-upgradeApiExtractor.json
- packages/api-docs/package.json
- scripts/package.json
- yarn.lock
Upgrades `api-extractor-model`, `api-extractor`, and `tsdoc` versions.
(optional)
> Upgrade api extractor

- apps/vr-tests/src/stories/Pivot.stories.tsx
- change/office-ui-fabric-react-2019-08-12-08-37-15-pivot-styles.json
- packages/office-ui-fabric-react/src/components/Pivot/Pivot.styles.ts
- packages/office-ui-fabric-react/src/components/Pivot/__snapshots__/Pivot.deprecated.test.tsx.snap
- packages/office-ui-fabric-react/src/components/Pivot/__snapshots__/Pivot.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/Keytips.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Fabric.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.IconCount.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Large.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.OnChange.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Override.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Remove.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Separate.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.SeparateNoSelectedKey.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Tabs.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.TabsLarge.Example.tsx.shot
Adds consistent margin for children of the pivot item content.
> Pivot styles: addressing margin issue.

- change/office-ui-fabric-react-2019-08-12-15-42-07-v-mare-Searchbox-update-fluent-styles.json
- packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.styles.tsx
- packages/office-ui-fabric-react/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/FloatingPeoplePicker.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/OverflowSet.Custom.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/SearchBox.CustomIcon.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/SearchBox.Disabled.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/SearchBox.FullSize.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/SearchBox.Small.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/SearchBox.Underlined.Example.tsx.shot
Cherrypick of changes made in #10041 
Ports the fluent changes from #9736 and #9611 to Fabric 7 master
> Searchbox: fluent update

- change/@uifabric-merge-styles-2019-08-14-10-13-40-jg-mergeStyles-doc-fix.json
- packages/merge-styles/README.md
I've consolidated the mergeStyles documentation by deleting the page from the wiki and updating the [wiki sidebar to point to the mergeStyle package's README](https://github.com/OfficeDev/office-ui-fabric-react/wiki).
This PR just brings over some very minor changes that contributors had made to the wiki page.
> mergeStyles: README update

- change/@uifabric-styling-2019-08-16-13-46-14-master.json
- packages/styling/src/styles/theme.ts
Fix a typing issue. The `value` doesn't always have `indexOf` (if it's a number, for instance).
> Fix theming error

- change/@uifabric-styling-2019-08-16-15-38-54-phkuo-fixThemingAgain.json
- packages/styling/src/styles/theme.ts
Fix the font size variables generated for legacy theming.
> Theming: Fix generation of font size variables for legacy theming

- package.json
- scripts/package.json
- yarn.lock
This addresses a strange bug that crop up if local & remote change files do not match up:
https://github.com/microsoft/beachball/issues/110
(optional)
> bump beachball to make yarn change more accurate

- change/@uifabric-migration-2019-08-18-22-42-32-vibraga-migration-enhancement.json
- packages/migration/fixtures/7.0.0/textfield.tsx
- packages/migration/src/migration.ts
- packages/migration/src/mods/7.0.0/colorPickerWarnRemovedProps.ts
- packages/migration/src/mods/7.0.0/comboboxOnChangedPropsChange.ts
- packages/migration/src/mods/7.0.0/comboboxValuePropChange.ts
- packages/migration/src/mods/7.0.0/createRefFromReact.ts
- packages/migration/src/mods/7.0.0/renameReactDeprecated.ts
- packages/migration/src/mods/7.0.0/searchBoxPropsArgs.ts
- packages/migration/src/mods/7.0.0/textFieldRenameProps.ts
- packages/migration/src/mods/7.0.0/textFieldWarnRemovedProps.ts
- packages/migration/src/mods/7.0.0/warnAutobindRemoved.ts
- packages/migration/src/mods/7.0.0/warnDetailsRowCheckIsSelectedRemoved.ts
- packages/migration/src/mods/7.0.0/warnSliderValuePositionRemoved.ts
- packages/migration/src/tests/mods/7.0.0/__snapshots__/textfieldPropsChange.test.ts.snap
- packages/migration/src/tests/mods/7.0.0/textfieldPropsChange.test.ts
- packages/migration/src/util/getMessages.ts
- Making some changes to the messaging infrastructure to bring more hints into the console output. (Open to any suggestions on the vocabulary used and/or any improvements 😄)
- Fix TextField rename props codemod and add test for it.
> Migration package messaging changes plus fix TextField codemod.

- change/office-ui-fabric-react-2019-08-15-09-40-27-fix-autofill-notupdating-value.json
- packages/office-ui-fabric-react/src/components/Autofill/Autofill.test.tsx
- packages/office-ui-fabric-react/src/components/Autofill/Autofill.tsx
- packages/office-ui-fabric-react/src/components/Autofill/Autofill.types.ts
Fixes an issue where value would not be set correctly by autofill.
(optional)
> Autofill: Fix issue where value would not be set correctly

- change/office-ui-fabric-react-2019-08-21-10-23-05-fix-panel-function-typing.json
- packages/office-ui-fabric-react/src/components/Panel/examples/Panel.Navigation.Example.tsx
Panel Example: Fix panel example function typing
(optional)
> Panel Example: Fix panel example function typing

- common/config/rush/shrinkwrap.yaml
- scripts/package.json
beachball bump to contain the bug fix in how it detects whether you need change files or not.
(optional)
> updates the beachball dep to fix change checks

- package.json
- scripts/scrub.js
Add the `scrub` cleanup script to 6.0.
> Add scrub script to 6.0

- change/office-ui-fabric-react-2019-08-12-11-27-26-feat-add-presenceTitle-prop.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Persona/Persona.base.tsx
- packages/office-ui-fabric-react/src/components/Persona/Persona.types.ts
- packages/office-ui-fabric-react/src/components/Persona/PersonaCoin/PersonaCoin.base.tsx
- packages/office-ui-fabric-react/src/components/Persona/PersonaPresence/PersonaPresence.base.tsx
Add a prop `presenceTitle` to `Persona` component. See #10122 for details.
> Add presenceTitle prop (cherry-pick of #10122)

- common/config/rush/shrinkwrap.yaml
- packages/fluent-theme/CHANGELOG.md
- packages/office-ui-fabric-react/CHANGELOG.md
- scripts/package.json
There was a bug in how beachball creates CHANGELOG.md. This has been addressed in beachball 1.12.0. This PR also cleans up the goop inside existing CHANGELOG.md 
(optional)
> Bumps beachball in 6.0 to fix changelog formatting bug

- change/office-ui-fabric-react-2019-08-16-14-33-49-v-mare-Checkbox-indeterminate-size-reduction.json
- packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.styles.ts
- packages/office-ui-fabric-react/src/components/__snapshots__/Checkbox.Other.Example.tsx.shot
Refactoring some of the styles to reduce component size
> Checkbox: Refactor indeterminate styles for size reduction

- README.md
Add a comma in README (and test size auditor)
I have a `Do Not Merge` label. Let's not merge this time. I am running out of typos.
> Add comma in README

- change/office-ui-fabric-react-2019-08-28-15-44-15-typo-in-Autofill.json
- packages/office-ui-fabric-react/src/components/Autofill/Autofill.tsx
Fix a typo (and test the PR flow in Size Auditor)
> Fix typo in Autofill

- azure-pipelines.bundlesize.yml
Add Size Auditor support back to `master`. The new updates to Size auditor require a field that takes in the source URL of the repository. This has been tested and verified against the `6.0` branch.
(optional)
> Resume size auditor check for master branch

- .vscode/settings.json
- change/@uifabric-experiments-2019-08-29-15-39-11-docs.json
- packages/experiments/README.md
Update the experiments readme with instructions about how to build.
Update formatting options in the VS Code settings.
> Update experiments docs and VS Code settings

- common/config/rush/shrinkwrap.yaml
- scripts/monorepo/findGitRoot.js
- scripts/package.json
- scripts/tasks/generate-version-files.js
Same as this: https://github.com/OfficeDev/office-ui-fabric-react/pull/10342
but for 6.0 branch
(optional)
> fixing generation script for set-version since beachball conversion

- change/office-ui-fabric-react-2019-09-04-10-20-51-v-mare-Nav-update-example-aria.json
- packages/office-ui-fabric-react/src/components/Nav/examples/Nav.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/Nav/examples/Nav.CustomGroupHeaders.Example.tsx
- packages/office-ui-fabric-react/src/components/Nav/examples/Nav.FabricDemoApp.Example.tsx
- packages/office-ui-fabric-react/src/components/Nav/examples/Nav.Nested.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Nav.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Nav.CustomGroupHeaders.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Nav.Nested.Example.tsx.shot
Adds aria-labels to Nav component examples to resolve a11y issue request
> Nav: Added aria-labels to examples

- change/office-ui-fabric-react-2019-09-09-13-49-16-fix-controlled-combobox.json
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.test.tsx
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
Fix controlled combobox so it doesn't mutate state.
(optional)
> Fix controlled combobox

- change/@uifabric-azure-themes-2019-09-09-14-03-10-master.json
- packages/azure-themes/src/azure/styles/DetailsList.styles.ts
> Azure theme - DetailsList checkbox visual alignment fix

- change/office-ui-fabric-react-2019-09-10-13-20-05-fix-combobox-mutateprops.json
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.test.tsx
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
Combobox: Fix issue where it would mutate props/state
(optional)
> Combobox: Fix issue where it would mutate props/state

- apps/vr-tests/src/stories/Persona.stories.tsx
- change/office-ui-fabric-react-2019-08-16-13-01-08-eddrost-Persona_PersonaSize_addition.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Persona/Persona.styles.ts
- packages/office-ui-fabric-react/src/components/Persona/Persona.types.ts
- packages/office-ui-fabric-react/src/components/Persona/PersonaCoin/PersonaCoin.styles.ts
- packages/office-ui-fabric-react/src/components/Persona/PersonaConsts.tsx
- packages/office-ui-fabric-react/src/components/Persona/PersonaPresence/PersonaPresence.styles.ts
- packages/office-ui-fabric-react/src/components/Persona/examples/Persona.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Persona.Basic.Example.tsx.shot
This PR adds a new size to the PersonaSize enum. The use-case is for Yammer's GroupAvatar in a group feed.
> Persona: Adding size120 to PersonaSize enum, updating API.

- change/office-ui-fabric-react-2019-09-05-13-49-23-v-mare-Slider-cherry-pick.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Slider/Slider.base.tsx
- packages/office-ui-fabric-react/src/components/Slider/Slider.test.tsx
- packages/office-ui-fabric-react/src/components/Slider/Slider.types.ts
Cherry picked functionality from Fabric 7 to Fabric 6
> Slider: onChanged prop logs Keyboard event

- change/@uifabric-charting-2019-09-13-22-14-18-charting-readme.json
- packages/charting/README.md
Update readme of charting package
> Update readme of charting package

- change/office-ui-fabric-react-2019-09-09-10-46-19-keco-calendarmonth-string-ref.json
- packages/office-ui-fabric-react/src/components/Calendar/CalendarMonth.tsx
Cherry-pick of https://github.com/OfficeDev/office-ui-fabric-react/pull/10393 for `6.0`.
- CI should pass
- DateTime / Calendar should behave as before particularly regarding `focus`.
> [6.0] Cherry-pick CalendarMonth React string ref for #10378

- change/office-ui-fabric-react-2019-09-19-13-57-35-autofillChromeIME.json
- packages/office-ui-fabric-react/src/components/Autofill/Autofill.tsx
My last PR #10432 introduced an issue for IME in other browsers, so scoping my previous change to JUST IE
Pickers, Autofill
> Autofill: Fix IME for non IE11 browsers

- change/@uifabric-merge-styles-2019-09-17-12-28-11-concat-props.json
- change/@uifabric-styling-2019-09-17-12-28-11-concat-props.json
- change/@uifabric-utilities-2019-09-17-12-28-11-concat-props.json
- packages/merge-styles/README.md
- packages/merge-styles/etc/merge-styles.api.md
- packages/merge-styles/src/concatStyleSetsWithProps.test.ts
- packages/merge-styles/src/concatStyleSetsWithProps.ts
- packages/merge-styles/src/index.ts
- packages/styling/etc/styling.api.md
- packages/styling/src/MergeStyles.ts
- packages/utilities/src/styled.tsx
Adding a helper to concatenate style sets given props to resolve them.
See unit tests for examples.
> Adding a helper to concat styles:

- change/office-ui-fabric-react-2019-09-18-15-10-54-teachingbubble-a11y.json
- packages/office-ui-fabric-react/src/components/TeachingBubble/TeachingBubbleContent.base.tsx
- packages/office-ui-fabric-react/src/components/TeachingBubble/__snapshots__/TeachingBubble.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/CommandBar.CommandBarButtonAs.Example.tsx.shot
Specify aria role for teaching bubble's heading.
> Teachingbubble a11y

- change/office-ui-fabric-react-2019-09-20-10-23-25-jg-8654-remove-randomize.json
- packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Nested.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/FocusTrapZone.Nested.Example.tsx.shot
Since the `Randomize` function [isn't really a valid use case](https://github.com/OfficeDev/office-ui-fabric-react/blob/676a4717a195fbd83e14738563a0aa2faddfc1b6/packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Nested.Example.tsx#L86) and causes focusing issues affecting accessibility (#8654), this PR removes it.
> FocusTrapZone example: Remove Randomize function

- apps/fabric-website/src/pages/Styles/Colors/palettes/palettes.tsx
- change/@uifabric-fabric-website-2019-09-20-11-27-20-website-update-colors.json
Update to PowerApps theme color
> Website: Update to PowerApps theme color 

- change/office-ui-fabric-react-2019-09-20-15-03-54-typo-combobox-docs.json
- packages/office-ui-fabric-react/src/components/Button/Button.types.ts
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.types.ts
Small typo fixes in Button and ComboBox docs
> Typo combobox docs

- change/office-ui-fabric-react-2019-09-19-14-14-30-teachingbubble-a11y-10504.json
- packages/office-ui-fabric-react/src/components/TeachingBubble/examples/TeachingBubble.Illustration.Example.tsx
- packages/office-ui-fabric-react/src/components/TeachingBubble/examples/TeachingBubble.WideIllustration.Example.tsx
Add `alt` tags to example images.
> Teachingbubble a11y 10504

- change/office-ui-fabric-react-2019-09-23-16-49-48-callout-example-update.json
- packages/office-ui-fabric-react/src/components/Callout/examples/Callout.FocusTrap.Example.tsx
- packages/office-ui-fabric-react/src/components/Callout/examples/CalloutExample.scss
Fixes number 5 of #8616
Updated callout example with more straightforward example with better narrator support.
> Callout example update - more accessible examples

- change/@uifabric-tsx-editor-2019-09-24-18-07-41-u-anhw-ie-regex.json
- packages/tsx-editor/src/transpiler/exampleParser.ts
- packages/tsx-editor/src/transpiler/exampleTransform.ts
Demo pages in IE were not rendering due to IE not supporting RegExp constructors that take in expressions :(
- Demo pages on IE
> IE Friendly Regex

- change/office-ui-fabric-react-2019-09-24-14-56-04-pivot-10585.json
- packages/office-ui-fabric-react/src/components/Pivot/examples/Pivot.Remove.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Remove.Example.tsx.shot
> Pivot 10585

- change/office-ui-fabric-react-2019-09-24-16-44-08-pivot-10583.json
- packages/office-ui-fabric-react/src/components/Pivot/examples/Pivot.IconCount.Example.tsx
- packages/office-ui-fabric-react/src/components/Pivot/examples/Pivot.Separate.Example.tsx
- packages/office-ui-fabric-react/src/components/Pivot/examples/Pivot.SeparateNoSelectedKey.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.IconCount.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.Separate.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Pivot.SeparateNoSelectedKey.Example.tsx.shot
> Pivot 10583

- change/@uifabric-merge-styles-2019-08-02-11-43-22-themed-rtl.json
- change/@uifabric-styling-2019-08-02-11-43-22-themed-rtl.json
- change/@uifabric-utilities-2019-08-02-11-43-22-themed-rtl.json
- packages/merge-styles/etc/merge-styles.api.md
- packages/merge-styles/src/IStyleOptions.ts
- packages/merge-styles/src/StyleOptionsState.ts
- packages/merge-styles/src/Stylesheet.test.ts
- packages/merge-styles/src/Stylesheet.ts
- packages/merge-styles/src/extractStyleParts.test.ts
- packages/merge-styles/src/fontFace.ts
- packages/merge-styles/src/index.ts
- packages/merge-styles/src/keyframes.test.ts
- packages/merge-styles/src/keyframes.ts
- packages/merge-styles/src/mergeCss.test.ts
- packages/merge-styles/src/mergeCssSets.test.ts
- packages/merge-styles/src/mergeStyleSets.ts
- packages/merge-styles/src/mergeStyles.test.ts
- packages/merge-styles/src/mergeStyles.ts
- packages/merge-styles/src/server.test.ts
- packages/merge-styles/src/styleToClassName.test.ts
- packages/merge-styles/src/styleToClassName.ts
- packages/merge-styles/src/transforms/rtlifyRules.test.ts
- packages/merge-styles/src/transforms/rtlifyRules.ts
- packages/styling/etc/styling.api.md
- packages/styling/src/interfaces/ITheme.ts
- packages/utilities/src/classNamesFunction.ts
- Accepts an RTL boolean to specify direction
- Pulls RTL access into a single location, removes dependency on state
- Accepts an RTL boolean to specify direction
- Pulls RTL access into a single location, removes dependency on state
This *does* increase bundle size of downstream components. Given the goal is to introduce a new API and keep backwards compat, this does not seem avoidable. I have deeper breakdown for anyone interested.
> mergeStyle[Sets]WithOptions accepts options

- apps/fabric-website/src/pages/Overviews/ResourcesPage/docs/default/ResourcesDesignResources.md
- change/@uifabric-fabric-website-2019-09-27-07-34-32-resource-update.json
This is #10639 with a change file (not sure if i can easily add a change file to Angelas PR.
> Resource update

- change/office-ui-fabric-react-2019-09-30-15-02-24-fix-teachingbubble-example.json
- packages/office-ui-fabric-react/src/components/TeachingBubble/TeachingBubble.doc.tsx
Teachingbubble: Fix illustration example
(optional)
> Teachingbubble: Fix illustration example

- change/office-ui-fabric-react-2019-09-30-17-32-14-users-nicul-fixingbooleanrender.json
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRowFields.tsx
> Fixing boolean rendering in list

- change/@uifabric-utilities-2019-10-02-16-57-45-fix-callout.json
- change/office-ui-fabric-react-2019-10-02-16-57-45-fix-callout.json
- packages/office-ui-fabric-react/src/components/Callout/CalloutContent.base.tsx
- packages/utilities/etc/utilities.api.md
- packages/utilities/src/Async.ts
> 6.0 cherrypick: Addressing regression: Callout with event as target now has less errors.

- change/@uifabric-tsx-editor-2019-10-04-16-48-22-editor-live.json
- packages/tsx-editor/src/utilities/isEditorSupported.ts
Turn the live example editor on by default! (leaving an option to turn it off)
> Enable editor by default

- change/office-ui-fabric-react-2019-10-07-13-54-11-fix-anchor-positions.json
- packages/office-ui-fabric-react/src/components/Callout/CalloutContent.base.tsx
- packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts
Callout and HoverCard: Fix anchor positions
(optional)
> Callout and HoverCard: Fix anchor positions

- change/office-ui-fabric-react-2019-10-09-08-09-39-revert-responsive-mode-change.json
- packages/office-ui-fabric-react/src/components/__snapshots__/Announced.QuickActions.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Callout.Cover.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Callout.Directional.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Coachmark.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ContextualMenu.Directional.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Required.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/PeoplePicker.Types.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Horizontal.Configure.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Vertical.Configure.Example.tsx.shot
- packages/office-ui-fabric-react/src/utilities/decorators/withResponsiveMode.tsx
Cherrypick of withResponsiveMode fix.
> Cherrypick: withResponsiveMode: fixing timing issue to resolve componentRef sooner.

- change/office-ui-fabric-react-2019-10-10-13-29-40-apply-className-on-DetailsHeaderBase.json
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.base.tsx
Apply className on DetailsHeaderBase.
> Apply className on DetailsHeaderBase

- .vscode/extensions.json
Adding extension for TSLint. Although it's getting deprecated, so added a comment as reminder to remove
> VSCode: add TSLint extension

- apps/perf-test/package.json
- apps/perf-test/src/index.scenarios.tsx
- apps/perf-test/tasks/perf-test.js
- yarn.lock
Consume new version of flamegrill adding metrics to flamegraphs:
> Perf Test: Consume new version of flamegrill with metrics

- change/@uifabric-file-type-icons-2019-10-08-14-41-23-caperez-oct_filetypeicon_mappings.json
- packages/file-type-icons/src/FileTypeIconMap.ts
- files with the applicable extension
> filetypeicon mappings for Calendar, Contact, Fluid, PowerBI Data Source

- change/office-ui-fabric-react-2019-10-14-15-13-25-temp.json
- packages/office-ui-fabric-react/src/components/TextField/TextField.styles.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/DatePicker.Disabled.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/TextField.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/TextField.Borderless.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/TextField.Multiline.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/TextField.PrefixAndSuffix.Example.tsx.shot
Textfield: Fix disabled text color
(optional)
> Textfield: Fix disabled text color

- change/office-ui-fabric-react-2019-10-16-15-42-28-dropdownAria.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.types.ts
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.types.ts
- packages/office-ui-fabric-react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/Callout.Cover.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Callout.Directional.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ChoiceGroup.Custom.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Coachmark.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ContextualMenu.Directional.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DatePicker.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DatePicker.WeekNumbers.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Controlled.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.ControlledMulti.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Custom.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Error.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Required.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Overflow.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/PeoplePicker.Types.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ResizeGroup.OverflowSet.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Horizontal.Configure.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Horizontal.WrapAdvanced.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Vertical.Configure.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Vertical.WrapAdvanced.Example.tsx.shot
- packages/office-ui-fabric-react/src/utilities/selectableOption/SelectableDroppableText.types.ts
This PR makes a number of changes on the `Dropdown's` use of aria values to bring it closer to the W3 ARIA standard.
(optional)
> Dropdown: Bringing accessibility up to W3 ARIA standards

- change/office-ui-fabric-react-2019-10-15-13-43-17-hotfix-6.0-list-virtualization.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx
- packages/office-ui-fabric-react/src/components/List/List.tsx
- packages/office-ui-fabric-react/src/components/List/List.types.ts
Cherry-picked #10819 to the `6.0` branch.
> [Cherry-pick] Fix cases where List virtualization causes stale data to render

- scripts/postinstall.js
Fixing a typo and changing grammar of the message a little bit.
(optional)
> Build: Changing 'all dependencies installed' message

- change/office-ui-fabric-react-2019-10-17-14-36-43-fix-dropdown.json
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx
- packages/office-ui-fabric-react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/Callout.Cover.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Callout.Directional.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ChoiceGroup.Custom.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Coachmark.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ContextualMenu.Directional.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DatePicker.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DatePicker.WeekNumbers.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Controlled.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.ControlledMulti.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Custom.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Error.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Required.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Overflow.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/PeoplePicker.Types.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ResizeGroup.OverflowSet.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Horizontal.Configure.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Horizontal.WrapAdvanced.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Vertical.Configure.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Vertical.WrapAdvanced.Example.tsx.shot
Dropdown: fix a few of the aria regressions introduced by #10873.
(optional)
> Dropdown: fix a few of the aria regressions introduced by #10873

- apps/theming-designer/src/components/Samples/index.tsx
- change/office-ui-fabric-react-2019-10-18-10-18-03-master.json
- packages/office-ui-fabric-react/src/components/CommandBar/examples/CommandBar.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/CommandBar/examples/CommandBar.ButtonAs.Example.tsx
- packages/office-ui-fabric-react/src/components/CommandBar/examples/CommandBar.CommandBarButtonAs.Example.tsx
- packages/office-ui-fabric-react/src/components/CommandBar/examples/CommandBar.SplitDisabled.Example.tsx
Fix typo in examples.
(optional)
> Fix typo in examples

- change/office-ui-fabric-react-2019-10-21-16-58-16-fix-closebuttoncolor.json
- packages/office-ui-fabric-react/src/components/pickers/TagPicker/TagItem.styles.ts
TagPicker: Fix item close button color
(optional)
> TagPicker: Fix item close button color

- change/office-ui-fabric-react-2019-10-16-21-36-43-bug-fix-tagpicker.json
- packages/office-ui-fabric-react/src/components/__snapshots__/Announced.SearchResults.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/PeoplePicker.Types.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/TagPicker.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.styles.ts
- packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/__snapshots__/PeoplePicker.test.tsx.snap
- packages/office-ui-fabric-react/src/components/pickers/TagPicker/TagItem.styles.ts
- packages/office-ui-fabric-react/src/components/pickers/TagPicker/TagPicker.test.tsx
- packages/office-ui-fabric-react/src/components/pickers/TagPicker/__snapshots__/TagPicker.test.tsx.snap
Added missing font and theme color on input text and TagItem text
> Pickers: add missing fonts and fix color

- change/office-ui-fabric-react-2019-10-22-13-20-23-master.json
- packages/office-ui-fabric-react/src/components/pickers/TagPicker/__snapshots__/TagPicker.test.tsx.snap
Noticed these tests failing in #10934
> Update tagpicker snapshots

- change/office-ui-fabric-react-2019-10-23-11-58-08-keco-detailsrow-focusable-config.json
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx
Cherry-pick of https://github.com/OfficeDev/office-ui-fabric-react/pull/10951 since the Partner team is still on Fabric `6.x`.
- CI should pass.
> Cherry-pick PR #10951

- change/office-ui-fabric-react-2019-10-21-17-50-26-panel-colors.json
- packages/office-ui-fabric-react/src/components/Panel/Panel.styles.ts
Use semantic colors in Panel instead of palette colors.
> Panel: Use semantic colors

- azure-pipelines.hotfix.yml
This adds a pipeline definition for hotfixes - this hotfix can be used to generate a tarball drop which will be deployed if approved in the release pipeline
*Using this build pipeline requires a variable*
If `targetNpmVersion` isn't set, it will fail:
https://uifabric.visualstudio.com/UI%20Fabric/_build/results?buildId=35924
> Adds a hotfix pipeline definition

- apps/fabric-website/src/pages/Overviews/ResourcesPage/docs/default/ResourcesDesignResources.md
- change/@uifabric-fabric-website-2019-10-31-11-45-26-jahnp-update-sharepoint-toolkit.json
The SharePoint Design team are adding a new Figma toolkit. This PR adds an aka.ms link to the toolkit on the Resources page.
> Update SharePoint toolkit

- change/office-ui-fabric-react-2019-10-22-11-35-07-10931-dropdown-alert.json
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx
Set role=alert on error messages in `Dropdown`
> 10931 dropdown alert

- change/office-ui-fabric-react-2019-11-04-11-52-25-typescript-3.7-fix.json
- packages/office-ui-fabric-react/src/utilities/positioning/positioning.types.ts
> [6.0] Remove circular import in positioning.types.d.ts

- change/office-ui-fabric-react-2019-11-04-12-19-31-details-column.json
- packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx
- packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx
- packages/office-ui-fabric-react/src/components/List/List.tsx
Cherry-pick of https://github.com/OfficeDev/office-ui-fabric-react/pull/11064 for `6.0`.
- CI should pass.
> [Cherry-pick] DetailsList column header resize fix for 6.0

- change/office-ui-fabric-react-2019-11-05-14-09-04-fix-contextualmenu-escape.json
- packages/office-ui-fabric-react/src/components/Button/Button.test.tsx
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx
ContextualMenu: Fix escape not dismissing
(optional)
> ContextualMenu: Fix escape not dismissing

- apps/fabric-website/src/styles/_base.scss
- change/@uifabric-fabric-website-2019-11-04-15-27-32-10952-website-high-contrast.json
- Fix the left-hand navigation by omitting the gradient background
- Fix several buttons by fielding the high contrast selector
> 10952 website high contrast

- change/office-ui-fabric-react-2019-09-18-17-13-10-teachingbubble-a11y-10506.json
- packages/office-ui-fabric-react/src/components/TeachingBubble/TeachingBubbleContent.base.tsx
- packages/office-ui-fabric-react/src/components/TeachingBubble/__snapshots__/TeachingBubble.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/CommandBar.CommandBarButtonAs.Example.tsx.shot
TeachingBubble: Wrap contents in a FocusTrapZone to better support keyboard navigation.
> TeachingBubble: Wrap contents in a FocusTrapZone to better support keyboard navigation.

- change/@uifabric-azure-themes-2019-11-05-19-01-35-xinyan-cc.json
- packages/azure-themes/src/azure/styles/Checkbox.styles.ts
**Appearance after this PR**
(optional)
> Checkbox: Correct the checked checkbox background in Azure light theme.

- .github/ISSUE_TEMPLATE/accessibility_issue.md
I've noticed multiple issues containing template comments this week:
I've updated the template to prevent this from occurring, along with some other minor updates.
> Issue Template: Minor updates

- change/office-ui-fabric-react-2019-11-08-15-31-29-jg-11085-hovercard-doc.json
- packages/office-ui-fabric-react/src/components/HoverCard/docs/HoverCardOverview.md
- packages/office-ui-fabric-react/src/components/HoverCard/examples/HoverCard.Target.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/HoverCard.Target.Example.tsx.shot
Clarify hotKey specification and definition for example.
> HoverCard: Clarify hotKey in documentation

- change/office-ui-fabric-react-2019-11-07-13-19-08-jg-11121-remove-autocomplete-doc.json
- packages/office-ui-fabric-react/src/components/SearchBox/docs/SearchBoxBestPractices.md
- packages/office-ui-fabric-react/src/components/SearchBox/docs/SearchBoxDonts.md
- packages/office-ui-fabric-react/src/components/SearchBox/docs/SearchBoxDos.md
- packages/office-ui-fabric-react/src/components/SearchBox/docs/new/SearchBoxBestPractices.md
Remove autocomplete documentation as feature is not supported.
> SearchBox: Remove unsupported autocomplete documentation

- change/@uifabric-example-app-base-2019-11-12-17-58-52-api-links.json
- packages/example-app-base/src/components/ApiReferencesTable/ApiReferencesTableSet.tsx
- packages/example-app-base/src/components/ApiReferencesTable/ApiReferencesTableSet.types.ts
- packages/example-app-base/src/components/ApiReferencesTable/tokenResolver.test.ts
- packages/example-app-base/src/components/ApiReferencesTable/tokenResolver.ts
#11126 broke the API reference links. This PR fixes them and adds a test.
> Fix API reference links and add test

- change/@uifabric-example-app-base-2019-11-05-17-20-24-platform-picker-high-contrast.json
- packages/example-app-base/src/components/PlatformPicker/PlatformPicker.module.scss
- packages/example-app-base/src/components/PlatformPicker/PlatformPicker.tsx
- packages/example-app-base/src/styles/_mixins.scss
Adds high contrast support to platform picker.
> Platform picker high contrast

- change/@uifabric-file-type-icons-2019-11-12-15-58-26-icon24.json
- packages/file-type-icons/src/initializeFileTypeIcons.tsx
Adds a new icon size to match what's already in #11119 
@maxwellred - FYI  
(optional)
> Adds a new file icon size of 24

- change/@uifabric-experiments-2019-11-07-20-24-43-kelkhadiri-cherrypick.json
- packages/experiments/src/components/MicroFeedback/MicroFeedback.types.ts
- packages/experiments/src/components/MicroFeedback/MicroFeedback.view.tsx
Cherry-pick from [#11112](https://github.com/OfficeDev/office-ui-fabric-react/pull/11112)
> [Cherry pick] Added ariaLabel to microfeedback component

- change/office-ui-fabric-react-2019-11-14-05-47-50-dropdown-aria-example.json
- packages/office-ui-fabric-react/src/components/Dropdown/examples/Dropdown.Required.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Required.Example.tsx.shot
Added missing aria label to website dropdown example
> Dropdown: added aria label to website example

- change/office-ui-fabric-react-2019-11-14-08-58-05-picker-border-fix.json
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.styles.ts
Updating disabled border color from transparent in order to match the disabled background-color to prevent it from looking like it changes in size.
> Picker: Updating disabled border color

- change/@uifabric-utilities-2019-11-13-19-56-02-v-mare-MarqueeSelection-horizontal-scroll-feature.json
- change/office-ui-fabric-react-2019-11-13-19-56-02-v-mare-MarqueeSelection-horizontal-scroll-feature.json
- packages/office-ui-fabric-react/src/components/MarqueeSelection/MarqueeSelection.base.tsx
- packages/utilities/src/AutoScroll.ts
Added ability to horizontally scroll while dragging the MarqueeSelection to the left or right of the selectable area.
> MarqueeSelection: Add horizontal scrolling

- change/office-ui-fabric-react-2019-10-22-16-52-31-facePileFix.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Facepile/Facepile.base.tsx
- packages/office-ui-fabric-react/src/components/Facepile/Facepile.types.ts
- packages/office-ui-fabric-react/src/components/Facepile/examples/Facepile.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/Facepile/examples/Facepile.Overflow.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Overflow.Example.tsx.shot
> Cherry pick Facepile accessibility updates to fabric 6

- change/office-ui-fabric-react-2019-11-22-01-23-31-cliffkoh-test.json
- packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.base.tsx
- packages/office-ui-fabric-react/src/components/Checkbox/examples/Checkbox.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Checkbox.Basic.Example.tsx.shot
> Wiser labels

- change/office-ui-fabric-react-2019-11-22-13-14-51-master.json
- packages/office-ui-fabric-react/src/components/Checkbox/examples/Checkbox.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Checkbox.Basic.Example.tsx.shot
> Fix label typos

- change/@uifabric-example-data-2019-11-27-11-53-32-facepile-cursor-styles.json
- change/office-ui-fabric-react-2019-11-27-11-53-32-facepile-cursor-styles.json
- packages/example-data/src/facepile.ts
- packages/office-ui-fabric-react/src/components/Facepile/Facepile.styles.ts
- packages/office-ui-fabric-react/src/components/Facepile/__snapshots__/Facepile.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Overflow.Example.tsx.shot
Removed unncessary cursor: pointer styles as it made non actionable personas look like buttons, whereas buttons already had pointer styles. 
(optional)
> Facepile cursor styles

- change/office-ui-fabric-react-2019-11-24-22-43-58-master.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Nav/Nav.types.ts
- [ X] Include a change request file using `$ yarn change`
Added an additional field to INavLinkGroup, this is now on par with INavLink
(optional)
> Add Data Prop to INavLinkGroup

- change/office-ui-fabric-react-2019-12-03-15-10-20-virtualized_combobox.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/ComboBox/VirtualizedComboBox.tsx
Adding focus with shouldOpenOnFocus and asyncFocus to VirtualizedComboBox.
(optional)
> VirtualizedComboBox: implement focus(shouldOpenOnFocus, asyncFocus).

- apps/fabric-website/src/pages/Styles/LocalizationPage/LocalizationPage.tsx
- apps/fabric-website/src/pages/Styles/LocalizationPage/docs/web/LocalizationRTL.md
- change/@uifabric-fabric-website-2019-12-02-15-06-04-rtlDocumentation.json
Our Localization documentation regarding RTL did not reflect the current state of the library. This PR updates it so that it does.
(optional)
> Updating RTL documentation

- change/@uifabric-file-type-icons-2019-12-04-16-34-43-azbanduk-add-stream-icon.json
- packages/file-type-icons/src/FileIconType.ts
> added stream to file type icons

- change/@uifabric-file-type-icons-2019-12-04-16-17-47-azbanduk-6.0-stream-icon.json
- change/@uifabric-file-type-icons-2019-12-04-16-23-06-azbanduk-6.0-stream-icon.json
- packages/file-type-icons/src/FileIconType.ts
> added stream icon to 6.0

- apps/fabric-website/src/pages/Controls/DatePickerPage/docs/android/DateTimePickerImplementation.md
- apps/fabric-website/src/pages/Controls/DatePickerPage/docs/android/DateTimePickerOverview.md
- change/@uifabric-fabric-website-2019-12-05-18-39-48-willdo-date-time-picker-updates.json
Updated DateTimePicker documentation to reflect the latest changes in the demo and source code.
(optional)
> Fabric Android Date Time Picker Documentation Updates

- change/office-ui-fabric-react-2019-12-06-13-32-38-combobox-multiselect-fixes.json
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.test.tsx
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/ComboBox.Basic.Example.tsx.shot
> Combobox: multi-select does not clear index on selection. Selected and checked properly supported

- change/@uifabric-react-cards-2019-12-10-10-38-30-cardNavigation.json
- packages/react-cards/etc/react-cards.api.md
- packages/react-cards/src/components/Card/Card.types.ts
- packages/react-cards/src/components/Card/Card.view.tsx
- packages/react-cards/src/components/Card/CardItem/__snapshots__/CardItem.test.tsx.snap
- packages/react-cards/src/components/Card/CardSection/__snapshots__/CardSection.test.tsx.snap
- packages/react-cards/src/components/Card/__snapshots__/Card.view.test.tsx.snap
- packages/react-cards/src/components/Card/examples/Card.Configure.Example.tsx
- packages/react-cards/src/components/Card/examples/Card.Horizontal.Example.tsx
- packages/react-cards/src/components/Card/examples/Card.Vertical.Example.tsx
This PR adds tab stops and `keydown` implementations on clickable `Cards` so that we have correct keyboard interaction on them.
(optional)
> Card: Adding keyboard navigation and interaction on clickable Cards and fixing example styling

- change/office-ui-fabric-react-2019-11-26-16-44-32-pickers-forcecomplete.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.test.tsx
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.types.ts
- packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx
Cherry picking [Pickers forcecomplete](https://github.com/OfficeDev/office-ui-fabric-react/commit/5303972717b3babd7ae668470c84886f371a85c5) from master to V6
> Pickers forcecomplete (#11317)

- change/office-ui-fabric-react-2019-12-12-10-18-09-toggle-div-in-button.json
- packages/office-ui-fabric-react/src/components/Toggle/Toggle.base.tsx
- packages/office-ui-fabric-react/src/components/Toggle/Toggle.styles.ts
- packages/office-ui-fabric-react/src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/ColorPicker.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ComboBox.Toggles.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Documents.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.DragDrop.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Grouped.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Error.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/FocusTrapZone.Box.Click.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/FocusTrapZone.Box.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/FocusTrapZone.Box.FocusOnCustomElement.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/FocusTrapZone.FocusZone.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/FocusTrapZone.Nested.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Keytips.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Keytips.Button.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Layer.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Layer.Customized.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Layer.Hosted.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/PeoplePicker.Types.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Shimmer.Application.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Shimmer.LoadData.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/TextField.ErrorMessage.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Toggle.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Toggle.CustomLabel.Example.tsx.shot
> Toggle: Change div inside button to be a span

- change/office-ui-fabric-react-2019-12-12-20-04-49-snapshots.json
- packages/office-ui-fabric-react/src/components/__snapshots__/Tooltip.Overflow.Example.tsx.shot
Fix snapshot update conflict of my PR #10901 which added a Toggle to a Tooltip example and @micahgodbolt's PR #11445 which changed the Toggle's DOM.
> Fix snapshot conflict

- change/office-ui-fabric-react-2019-12-12-14-59-46-contextMenu-example.json
- packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.CustomizationWithNoWrap.Example.tsx
- packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenuExample.scss
The button text was implying multiple selection, which this example was not properly set up for. It's not essential to the example so I made it more generic. 
(optional)
> ContextualMenu: Fix accessibility issue in example

- change/@uifabric-experiments-2019-12-13-10-36-12-doc-fixes.json
- change/office-ui-fabric-react-2019-12-13-10-36-12-doc-fixes.json
- packages/experiments/src/components/FloatingSuggestions/FloatingSuggestions.types.ts
- packages/office-ui-fabric-react/src/components/FloatingPicker/BaseFloatingPicker.types.ts
- packages/office-ui-fabric-react/src/components/TextField/examples/TextField.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/TextField/examples/TextField.CustomRender.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/TextField.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/TextField.CustomRender.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.types.ts
Fix minor accessibility issues in TextField docs.
Fix typos in picker docs.
> Minor TextField and picker doc fixes

- change/@uifabric-utilities-2019-12-12-12-10-04-rtl-update.json
- change/office-ui-fabric-react-2019-12-12-12-10-04-rtl-update.json
- packages/office-ui-fabric-react/.vscode/settings.json
- packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.base.tsx
- packages/office-ui-fabric-react/src/components/Check/Check.styles.ts
- packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.base.tsx
- packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.styles.ts
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItem.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.base.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx
- packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.base.tsx
- packages/office-ui-fabric-react/src/components/MarqueeSelection/MarqueeSelection.base.tsx
- packages/office-ui-fabric-react/src/components/Panel/Panel.base.tsx
- packages/office-ui-fabric-react/src/components/Persona/PersonaCoin/PersonaCoin.base.tsx
- packages/office-ui-fabric-react/src/components/ProgressIndicator/ProgressIndicator.styles.ts
- packages/office-ui-fabric-react/src/components/ScrollablePane/ScrollablePane.base.tsx
- packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.styles.tsx
- packages/office-ui-fabric-react/src/components/Shimmer/Shimmer.styles.ts
- packages/office-ui-fabric-react/src/components/Slider/Slider.base.tsx
- packages/office-ui-fabric-react/src/components/Slider/Slider.styles.ts
- packages/office-ui-fabric-react/src/components/pickers/TagPicker/TagItem.styles.ts
- packages/utilities/etc/utilities.api.md
- packages/utilities/src/rtl.test.ts
- packages/utilities/src/rtl.ts
> getRTL uses RTL flag on theme if present.

- change/office-ui-fabric-react-2019-12-13-16-31-16-contextualmenu-group-label.json
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx
- packages/office-ui-fabric-react/src/components/ContextualMenu/__snapshots__/ContextualMenu.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/ContextualMenu.Basic.Example.tsx.shot
> ContextualMenu: Associate group with header to improve narrator

- change/@uifabric-utilities-2019-12-16-09-21-31-focustrapzone-select.json
- packages/utilities/src/focus.test.tsx
- packages/utilities/src/focus.ts
> Focus: add select to be a focusable target

- azure-pipelines.bundlesize.yml
Size auditor recently broke on PRs with $(Build.SourceVersionMessage) no longer resolving. This PR attempts to fix these issues.
Relevant Info:
https://developercommunity.visualstudio.com/content/problem/857818/cannot-read-buildsourceversionmessage-when-check-i.html
> Size Auditor: Fix failures on PRs

- change/office-ui-fabric-react-2019-12-17-13-31-42-picker-button-label.json
- packages/office-ui-fabric-react/src/components/pickers/examples/Picker.CustomResult.Example.tsx
- packages/office-ui-fabric-react/src/components/pickers/examples/TagPicker.Basic.Example.tsx
> TagPicker: Add aria-label to examples

- change/office-ui-fabric-react-2019-11-20-15-57-32-master.json
- packages/office-ui-fabric-react/src/components/Tooltip/Tooltip.styles.ts
> align color system

- change/@uifabric-file-type-icons-2019-12-20-17-13-33-azbanduk-stream-icon-patch.json
- packages/file-type-icons/src/getFileTypeIconProps.ts
> added stream in getFileTypeIconProps

- change/office-ui-fabric-react-2020-01-02-15-15-03-callout-docs.json
- packages/office-ui-fabric-react/src/components/Callout/Callout.types.ts
> Callout: update directionalHintForRTL comment to be accurate

- change/@uifabric-utilities-2020-01-03-15-20-10-get-class-names-ltr.json
- packages/utilities/src/classNamesFunction.test.ts
- packages/utilities/src/classNamesFunction.ts
Fix for LTR theme being rendered in global RTL context.
> getClassNames: fix for LTR in RTL context.

- change/office-ui-fabric-react-2020-01-02-16-16-10-fix-picker-multiselect.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
Consolidate some of the picker completion logic. It brings keyboard selection in line with mouse selection of items. It also fixes a bug where pressing enter rapidly would result in the same item being selected many times.
(optional)
> Pickers: fix issue where same option would be selected repeatedly.

- change/office-ui-fabric-react-2020-01-07-10-21-50-button-menuitemcheckbox.json
- packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx
- packages/office-ui-fabric-react/src/components/Button/Button.test.tsx
> Button: Use aria-checked for checkbox and menuitemcheckbox roles

- package.json
`ssr-test` tests are failing due to icon re-registration. I can't repro this error locally but this may be due to tests running with `lerna --parallel` introduced by #11574. This PR reverts back to `lerna --stream` for now to see if it fixes the `ssr-test` failure.
> Release Build: Fix ssr-test failure

- change/office-ui-fabric-react-2020-01-13-15-11-26-xgao-fix-contextual-menu-keyboard.json
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuAnchor.tsx
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuButton.tsx
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.tsx
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/__snapshots__/ContextualMenuAnchor.deprecated.test.tsx.snap
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/__snapshots__/ContextualMenuAnchor.test.tsx.snap
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/__snapshots__/ContextualMenuButton.deprecated.test.tsx.snap
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/__snapshots__/ContextualMenuButton.test.tsx.snap
- packages/office-ui-fabric-react/src/components/ContextualMenu/__snapshots__/ContextualMenu.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/ContextualMenu.Basic.Example.tsx.shot
set `data-is-focusable` based if the item is disabled or not
> ContextualMenu: Fix disabled item being focusable

- change/office-ui-fabric-react-2020-01-10-17-25-19-xgao-command-bar-fix.json
- packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.base.tsx
- packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.test.tsx
- packages/office-ui-fabric-react/src/components/CommandBar/__snapshots__/CommandBar.test.tsx.snap
Add empty check along with existing null check on `farItems` prop
> CommandBar: Do not render empty div if farItems prop is empty array

- change/@uifabric-charting-2020-01-23-15-54-53-user-v-satgar-stackedBarChartAccessability.json
- packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx
Make chart content accessible using keyboard.  
stacked bar chart accessibility using keyboard and mouse. 
(optional)
> Provided accessibility for stacked bar chart

- change/office-ui-fabric-react-2020-01-13-09-02-40-focuszone-listener-fix.json
- packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx
Cherrypicking focuszone leak fix to Fabric 6.
> Cherrypicking focuszone fix to fabric6.

- change/office-ui-fabric-react-2020-01-28-17-41-21-dropdownHighContrast.json
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.styles.ts
- packages/office-ui-fabric-react/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/Callout.Cover.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Callout.Directional.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ChoiceGroup.Custom.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Coachmark.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ContextualMenu.Directional.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DatePicker.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DatePicker.WeekNumbers.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Controlled.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.ControlledMulti.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Custom.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Error.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Dropdown.Required.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Overflow.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ResizeGroup.OverflowSet.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Horizontal.Configure.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Horizontal.WrapAdvanced.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Vertical.Configure.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Stack.Vertical.WrapAdvanced.Example.tsx.shot
A number of High Contrast issues were outlined for the `Dropdown` component in #11807 and, while investigating it, some others were encountered. This PR fixes them.
__Before:__
__After:__
(optional)
> Dropdown: Fixing various High Contrast issues

- change/office-ui-fabric-react-2019-12-20-15-40-23-EditingItem-new-styles.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/SelectedItemsList/SelectedPeopleList/Items/EditingItem.styles.ts
- packages/office-ui-fabric-react/src/components/SelectedItemsList/SelectedPeopleList/Items/EditingItem.tsx
- packages/office-ui-fabric-react/src/components/SelectedItemsList/SelectedPeopleList/Items/EditingItem.types.ts
- packages/office-ui-fabric-react/src/components/SelectedItemsList/index.ts
Added style and types file for EditingItem component.
Adding semanticColors for theme support.
(optional)
> Editing item new styles

- change/office-ui-fabric-react-2020-01-09-12-35-47-mapol-10860.json
- packages/office-ui-fabric-react/src/components/Facepile/Facepile.base.tsx
- packages/office-ui-fabric-react/src/components/Facepile/__snapshots__/Facepile.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.AddFace.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Facepile.Overflow.Example.tsx.shot
Fixes accessibility  bug #10860 in Facepile
Facepile accessibility
> Use default semantic html instead of aria attributes and roles

- scripts/fluent-import/index.js
This change doesn't DO anything, but allows me to have a script handy to import just the raw package code from FUI repo and study differences in deps.
(optional)
> FUI move part 1: initialize a package import script

- change/office-ui-fabric-react-2020-02-04-12-57-13-defaultPreventedFabricFix.json
- packages/office-ui-fabric-react/src/components/Panel/Panel.base.tsx
Removing errant () from ev.defaultPrevented()
tested light dismiss in the example environment
> ev.defaultPrevented is not a function, remove errant ()

- common/changes/office-ui-fabric-react/hotfix-AddFocus2Nav-office-ui-fabric-react-5.0_2020-01-22-05-26.json
- packages/office-ui-fabric-react/src/components/Nav/Nav.base.tsx
- packages/office-ui-fabric-react/src/components/Nav/Nav.types.ts
Add focus to Nav component and this fix was ported from d1ef1ac (#10310)
(optional)
Cherry-picker from https://github.com/OfficeDev/office-ui-fabric-react/commit/a62910a58bec8368b07fef875ac27bfeab63668c
> Add focus to Nav. Porting from #10310 (#11758)

- change/@uifabric-styling-2020-02-07-11-50-01-semantic_colors_page.json
- packages/styling/src/interfaces/ISemanticColors.ts
It's become clear that users are getting confused about the status of our semantic slots/palette slots usage. Consistent adoption of one over the other hasn't happened yet across the Fabric codebase due to many reasons, one being we haven't polished the semantic slots offering. We've done some polishes and some updates to use semantic slots over palette slots but not all. And we're currently working on making a better design token system overall with the new version of Fluent. In the meantime, this clarification can help our users understand this status. 
(optional)
> ISemanticColors: adding clarification to Fabric site.

- change/office-ui-fabric-react-2020-02-10-15-36-57-xgao-dropdown-interface.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.types.ts
Fix the interfaces since now we are on higher TS version
> Dropdown: fix SubComponentStyles interfaces

- .github/CODEOWNERS
Adding a bit of protection from folks making manual changes to this directory /packages/fluentui so far.
(optional)
> adding a codeowner bit for FUI code

- change/@fluentui-react-focus-2020-02-12-09-42-06-pkg-publish.json
- packages/react-focus/package.json
This should publish the initial package.
> react-focus: publishing package.

- change/office-ui-fabric-react-2020-02-12-09-56-12-list-leak-fix.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/List/List.tsx
Cherrypicking list leak fix into 6.0
> Cherrypicking List leak fix into 6.0

- azure-pipelines.yml
- dangerfile.ts
- yarn.lock
Activate Fluent's approved dependency script.
Initial commits confirmed Danger will error (can be seen in comment history.)
I was able to force compliance by temporarily adding the following `resolutions` to root `package.json` and then running `yarn` to update `yarn.lock`. After `yarn.lock` is updated and removing `resolutions`, `yarn` must be run one more time.
```
"css-in-js-utils": "3.0.0",
"fela": "10.6.1",
"fela-bindings": "10.6.1",
"fela-dom": "10.6.1",
"fela-plugin-placeholder-prefixer": "10.6.1",
"fela-plugin-prefixer": "10.6.1",
"fela-tools": "10.6.1",
"jest-fela-bindings": "10.6.1",
"jest-react-fela": "10.6.1",
"react-fela": "10.6.1"
```
> Fluent: Activate approved dependency script

- README.md
> Updatd docs related to npm

- packages/fluentui/code-sandbox/package.json
- packages/fluentui/e2e/e2eApi.ts
- packages/fluentui/e2e/tests/toolbarMenuOverflow-example.tsx
- packages/fluentui/e2e/tests/toolbarMenuOverflow-test.ts
- packages/fluentui/e2e/tests/toolbarMenuOverflowWrapped-example.tsx
- packages/fluentui/e2e/tests/toolbarMenuOverflowWrapped-test.ts
- packages/fluentui/react/src/components/Chat/ChatItem.tsx
- packages/fluentui/react/src/components/Chat/ChatMessage.tsx
- packages/fluentui/react/src/components/Chat/chatItemContext.ts
- packages/fluentui/react/src/components/Toolbar/Toolbar.tsx
- packages/fluentui/react/src/utils/getElementProp.ts
- packages/fluentui/react/src/utils/index.ts
performing an update to the latest FUI codebase
(optional)
> Updating FUI code from latest FUI master

- .github/CODEOWNERS
Adding myself as the codeowner to `react-focus/FocusZone` to be able to iterate quickly.
(optional)
> Separating code owners of oufr FocusZone and react-focus FocusZone

- dangerfile.ts
- packages/fluentui/CHANGELOG.md
- scripts/dangerjs/checkChangelog.ts
- scripts/fluent-import/index.js
- scripts/tsconfig.json
The change here is that all the packages/fluentui need to be accompanied by a change in the packages/fluentui/CHANGELOG.md (since this repo now has two libraries, we cannot put this in the root).
(optional)
> Added FUI changelog checker for Fabric

- change/office-ui-fabric-react-2020-02-19-17-52-40-xgao-mem-leak.json
- packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx
Fix mem leak caused by reference to a closure was not cleared 
(optional)
> FocusZone: fix memory leak caused by closure

- azure-pipelines.release-fluentui.yml
- scripts/config.ts
> fix(build): release public docsite from CI

- .github/CODEOWNERS
With the influx of new code, we need to make sure the code owner triggers for the right set of files. This change makes it so that the CODEOWNERS are more specific about which package triggers what.
(optional)
> being more specific with the codeowner file changes

- packages/fluentui/CHANGELOG.md
- packages/fluentui/code-sandbox/package.json
- packages/fluentui/docs/src/prototypes/table/InteractiveTable.tsx
- packages/fluentui/docs/src/prototypes/table/index.tsx
- packages/fluentui/react/src/components/Dropdown/DropdownItem.tsx
- packages/fluentui/react/src/themes/teams/components/Dropdown/dropdownItemStyles.ts
- packages/fluentui/react/src/themes/teams/components/Dropdown/dropdownVariables.ts
- packages/fluentui/react/src/themes/teams/components/Icon/svg/icons/index.ts
- packages/fluentui/react/src/themes/teams/components/Icon/svg/icons/survey.tsx
- packages/fluentui/react/src/themes/teams/components/Icon/svg/icons/survey20px.tsx
- packages/fluentui/react/test/specs/components/Dropdown/DropdownItem-test.tsx
Performing a minor update import from Seattle afternoon time in preparation for the archival in microsoft/fluent-ui-react repo.
(optional)
> Updated from Fluent UI master (2/25/20, 3pm Seattle) 

- change/@uifabric-experiments-2020-02-20-13-35-18-u-sanredd-FloatingSuggestionsComposite.json
- packages/experiments/src/components/FloatingSuggestionsComposite/FloatingSuggestions.styles.ts
- packages/experiments/src/components/FloatingSuggestionsComposite/FloatingSuggestions.tsx
- packages/experiments/src/components/FloatingSuggestionsComposite/FloatingSuggestions.types.ts
- packages/experiments/src/components/FloatingSuggestionsComposite/FloatingSuggestionsItem/FloatingSuggestionsItem.styles.ts
- packages/experiments/src/components/FloatingSuggestionsComposite/FloatingSuggestionsItem/FloatingSuggestionsItem.tsx
- packages/experiments/src/components/FloatingSuggestionsComposite/FloatingSuggestionsItem/FloatingSuggestionsItem.types.ts
- packages/experiments/src/components/FloatingSuggestionsComposite/FloatingSuggestionsList/FloatingSuggestionsList.styles.ts
- packages/experiments/src/components/FloatingSuggestionsComposite/FloatingSuggestionsList/FloatingSuggestionsList.tsx
- packages/experiments/src/components/FloatingSuggestionsComposite/FloatingSuggestionsList/FloatingSuggestionsList.types.ts
- packages/experiments/src/components/FloatingSuggestionsComposite/index.ts
- packages/experiments/src/components/FloatingSuggestionsComposite/utils/getNextSuggestionIndex.ts
- packages/experiments/src/components/FloatingSuggestionsComposite/utils/getPreviousSuggestionIndex.ts
New composite FloatingSuggestions component, to be used in UnifiedPicker.
Existing FloatingSuggestions component is same as FloatingPicker in fundamental components.
This component is very simple and there si no complex logic in this component, every thing is driven by data coming in, for ex: To show or hide the FloatingSuggestions the component takes a boolean, also to highlight the suggestion isSelected Boolean need to be modified from parent component.
Tested with local component, it works fine.
This is not the final code for this component, its just under development, might change based on requirements for UnifiedPicker.
next steps:
1. Remove existing FloatingSuggestions class component and point dependencies to new FloatingSuggestions composite component.
2. Modify SelectedItemsList …
> Add composite FloatingSuggestions component

- specs/Button.md
- specs/Checkbox.md
- specs/Icon.md
- specs/Link.md
- specs/Menu.md
- specs/Slider.md
Move specs from archived fluent repo.
> Fluent: Move specs from fluent repo

- change/office-ui-fabric-react-2020-02-26-10-32-31-xgao-toggle-role.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/Toggle/Toggle.types.ts
menuitemcheckbox should be allowed on toggle
(optional)
> Toggle: allow menuitemcheckbox role

- specs/README.md
This PR adds a README to the specs folder that briefly describes what should be expected from each spec and makes a note that these are a WIP at the moment that should be disregarded until a formal announcement is made so we don't confuse people.
(optional)
> Adding README file to specs folder

- azure-pipelines.cache.yml
- azure-pipelines.yml
Here we re-enable the pipelines to be all self-hosted and now use gulp-cache to greater effect.
I think this brings it down from 39 to 27minutes... there are more opportunities to drive it down even further.
(optional)
> Faster builds via better gulp-cache

- apps/perf-test/tasks/fluentPerfRegressions.ts
- packages/fluentui/perf-test/tasks/perf-test.ts
Now that Fluent code is live in repo, enable regression analysis for PRs.
> Fluent: Enable regression analysis

- .github/CODEOWNERS
#12051 made paths more specific so that components existing in both Fabric and Fluent wouldn't conflict. However, some paths were screwed up in the process. This PR fixes this issue.
(optional)
> CODEOWNERS: Fixing some specific paths

- packages/fluentui/docs/src/components/Sidebar/Sidebar.tsx
Previous link was broken 😭 
(optional)
> docs: fix CHANGELOG url in Sidebar

- .github/CODEOWNERS
> chore: update CODEOWNERS for FluentUI v0

- azure-pipelines.perf-test.yml
Fix parameter checks in perf test pipeline.
> Perf Test: Fix parameter check

- change/office-ui-fabric-react-2020-03-02-11-33-05-xgao-fix-type.json
- packages/office-ui-fabric-react/src/components/ScrollablePane/examples/ScrollablePane.DetailsList.Example.tsx
Fix typing errors in ScrollablePane example code if `strictFunctionTypes: true` is set.
(optional)
> ScrollablePane example: fix strict function type errors

- apps/fabric-website/homepage.htm
- apps/fabric-website/index.html
- change/@uifabric-fabric-website-2020-02-27-15-27-17-joschemd-working.json
Added Application Insights telemetry to public fabric site
(optional)
> Added ApplicationInsights to public site to enable usage tracking

- apps/test-bundles/just.config.ts
- apps/test-bundles/package.json
- apps/test-bundles/webpack.config.js
- yarn.lock
Since we added the experiments/button to the size auditor, it has doubled our time in build. This is now the "long pole". We should make sure that we methodically scale out these kinds of tests (with parallel-webpack) so that we do not limit ourselves to the number of test bundles in the future.
(optional)
> Speed up test-bundle build with parallel-webpack

- packages/fluentui/docs/src/examples/components/Toolbar/Visual/ToolbarExampleVariables.shorthand.tsx
- packages/fluentui/react/src/components/Toolbar/ToolbarDivider.tsx
- packages/fluentui/react/src/components/Toolbar/ToolbarMenuItem.tsx
- packages/fluentui/react/src/themes/teams/components/Toolbar/toolbarRadioGroupStyles.ts
This PR was extracted from #12203 to check that there will be no changes during refactor. Add a visual test for `variables` nesting in `Toolbar`. Also fixes a minor issue in `ToolbarMenuItem` with passing `variables` down.
> docs(Toolbar): add visual test for variables nesting

- common/changes/office-ui-fabric-react/details-accessibility_2018-06-01-20-15.json
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRowFields.tsx
- packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsHeader.test.tsx.snap
- packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
Port DetailsList accessibility fixes from #5599 by cherry-pick commit cb88f22deaf10f1003d3db2ac1d16fa3cc216bc4
> Fix DetailsList accessibility and add more ARIA hooks (#5066)

- package.json
- scripts/package.json
- yarn.lock
> bump beachball with scoped publish fix

- packages/fluentui/react/src/themes/teams/components/Menu/menuItemStyles.ts
Picked from #12241. This PR simplifies a ternary expression in our styles to make it more readable.
I created a CodeSandbox with unit tests to be sure that result will be the same:
https://codesandbox.io/s/dank-cloud-os0kj
> chore(Menu): refactor styles for MenuItem in Teams theme

- packages/fluentui/docs/src/examples/components/Alert/commonScreenerSteps.ts
See title, required for #12246 as we perform there styles changes.
> chore(Alert): add a screenshot test for focused & hovered `dismissAction`

- change/@uifabric-charting-2020-03-02-19-08-55-user-v-ragor-LineChartAccessibility.json
- packages/charting/src/components/LineChart/LineChart.base.tsx
- packages/charting/src/components/LineChart/LineChart.styles.ts
Add keyboard interaction and screenreader support for Line chart and Multi line chart 
Line chart hover and focus on the lines
> User/v ragor/line chart accessibility

- packages/fluentui/CHANGELOG.md
- packages/fluentui/docs/src/examples/components/Avatar/Variations/AvatarExampleSize.shorthand.tsx
- packages/fluentui/docs/src/examples/components/Avatar/Variations/AvatarExampleSquare.shorthand.tsx
- packages/fluentui/docs/src/examples/components/Avatar/Variations/index.tsx
- packages/fluentui/react/src/components/Avatar/Avatar.tsx
- packages/fluentui/react/src/themes/teams/components/Avatar/avatarStyles.ts
- packages/fluentui/react/src/themes/teams/components/Avatar/avatarVariables.ts
- packages/fluentui/react/src/themes/teams/types.ts
> feat(Avatar): added square prop

- packages/fluentui/docs/src/examples/components/Menu/Types/MenuExamplePointing.shorthand.steps.ts
- packages/fluentui/docs/src/examples/components/Menu/Types/MenuExampleUnderlined.shorthand.steps.ts
> chore(Menu): add more visual tests

- packages/fluentui/docs/src/examples/components/Menu/Variations/MenuExampleVerticalPrimary.shorthand.steps.ts
Add visual test for Menu (vertical & primary) for #12241.
> chore: add visual test for Menu (vertical & primary)

- packages/fluentui/react/gulpfile.ts
- scripts/gulp/tasks/test-unit.ts
This PR updates existing Gulp tasks to fix them.
> chore(scripts): fix "jest:watch" command

- change/office-ui-fabric-react-2020-03-17-10-57-51-master.json
- packages/office-ui-fabric-react/src/utilities/color/colors.ts
Remove duplicated import - was causing issues in tests in odsp-next
> Remove Duplicated Export

- change/@uifabric-azure-themes-2020-03-17-15-00-49-azure-updates.json
- packages/azure-themes/.storybook/main.js
- packages/azure-themes/.storybook/manager.js
- packages/azure-themes/.storybook/preview.js
- packages/azure-themes/package.json
- packages/azure-themes/src/stories/Themes/Themes.tsx
- scripts/storybook/generateStoriesFromExamples.js
Adding `yarn start` to `azure-themes` package for the Azure Portal design team to work with.
> Azure theme: Adding storybook support

- change/@uifabric-charting-2020-03-06-11-00-41-user-v-sivsar-StackedAndMultiStackedbarAccesiblity.json
- packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx
-[x] https://uifabric.visualstudio.com/iss/_workitems/edit/1164 
when we are focusing the data-segment of the chart we are reading information present in callout .
stacked bar chart and multistacked bar chart
https://drive.google.com/file/d/1c4tpc-RGMYY25o4M5ZrB_Sv8Lf4elWiE/view?usp=sharing
https://drive.google.com/file/d/1HTElK8BFEQETBBEdzcfyxk03gh9S9MjZ/view?usp=sharing
NOTE:- please download the videos from the above link if they aren't processed
> Stacked and multi stacked bar accessibility

- packages/fluentui/.browserslistrc
Adds browserlist config lost during react-northstar repo migration.
Fixes #12287.
> Fix(build): add browserlist lost during react-northstar repo move

- change/@uifabric-charting-2020-03-19-18-43-28-user-v-satgar-donutChartcalloutScreenreader.json
- packages/charting/src/components/DonutChart/Arc/Arc.tsx
- packages/charting/src/components/DonutChart/Arc/Arc.types.ts
- packages/charting/src/components/DonutChart/DonutChart.base.tsx
- packages/charting/src/components/DonutChart/Pie/Pie.tsx
- packages/charting/src/components/DonutChart/Pie/Pie.types.ts
Add support for screen reader when hover on Donut chart
Donut chart hover Sectors of Donut
> Add support for screen reader when hovering on donut chart

- change/@uifabric-charting-2020-03-23-11-32-32-user-v-satgar-Bug_3927790.json
- packages/charting/src/components/DonutChart/DonutChart.base.tsx
- packages/charting/src/components/DonutChart/DonutChart.types.ts
- packages/charting/src/components/DonutChart/examples/DonutChart.Basic.Example.tsx
- packages/charting/src/components/Legends/Legends.base.tsx
- packages/charting/src/components/Legends/Legends.types.ts
- packages/charting/src/components/Legends/examples/Legends.Overflow.Example.tsx
- packages/charting/src/components/LineChart/LineChart.base.tsx
- packages/charting/src/components/LineChart/LineChart.types.ts
- packages/charting/src/components/LineChart/examples/LineChart.Basic.Example.tsx
- packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/MultiStackedBarChart.types.ts
- packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/StackedBarChart.types.ts
- packages/charting/src/components/StackedBarChart/examples/MultiStackedBarChart.Example.tsx
expose prop for overflow items text in legends
Legends and legends overflow items
> expose prop for overflow items text in legends

- apps/vr-tests/src/stories/Fonts.stories.tsx
- change/@uifabric-styling-2020-03-23-20-16-34-font-fix.json
- change/office-ui-fabric-react-2020-03-23-20-16-34-font-fix.json
- packages/office-ui-fabric-react/src/components/Text/examples/Text.Weights.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/Text.Weights.Example.tsx.shot
- packages/styling/src/styles/DefaultFontStyles.ts
It seems the bold font weight has been missing for some time from the font-face definitions.
Before:
After:
> Styling: adding bold font weight definition

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Button/Button.tsx
Add `propTypes` check for `inverted` prop in `Button`.
(optional)
> fix(Button): add inverted to propTypes check

- .github/CODEOWNERS
Updates due to changing focus and to reduce PR emails a bit.
> CODEOWNER updates

- packages/fluentui/accessibility/src/behaviors/Card/cardBehavior.ts
- packages/fluentui/docs/src/examples/components/Card/Slots/index.tsx
`Card` was added in parallel to lint config changes. This PR fixes lint issues in its sources.
> chore(Card): lint files

- change/@fluentui-react-focus-2020-03-25-15-36-37-reactFocusReadme.json
- packages/react-focus/README.md
react-focus: Updating README to reflect package purpose.
> react-focus: Updating README to reflect package purpose

- apps/fabric-website/src/SiteDefinition/SiteDefinition.tsx
- change/@uifabric-fabric-website-2020-03-30-13-55-53-website-banner-update.json
- change/office-ui-fabric-react-2020-03-30-13-55-53-website-banner-update.json
- packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/ContextualMenu.Basic.Example.tsx.shot
> Website banner update

- change/office-ui-fabric-react-2020-03-27-15-36-07-update-pending-comment.json
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.types.ts
Combobox: Update docs to make onPendingValueChanged more clear
(optional)
> Combobox: Update docs to make onPendingValueChanged more clear

- packages/fluentui/CHANGELOG.md
- packages/fluentui/accessibility/src/behaviors/Table/gridRowBehavior.ts
- packages/fluentui/accessibility/src/behaviors/Table/gridRowNestedBehavior.ts
- packages/fluentui/accessibility/test/behaviors/gridRowBehavior-test.tsx
- packages/fluentui/docs/src/prototypes/table/SelectableTable.tsx
- packages/fluentui/docs/src/prototypes/table/index.tsx
- packages/fluentui/react-northstar/src/components/Table/TableRow.tsx
Adding prototype for selectable table in Fluent UI v0
(optional)
> chore(Table): Add selectable table prototype

- change/office-ui-fabric-react-2020-04-01-12-22-09-fix-typo.json
- packages/office-ui-fabric-react/src/components/Pivot/Pivot.base.tsx
> Pivot: fixing typo in comment

- change/@uifabric-charting-2020-03-26-19-19-23-user-v-satgar-PBI_4052037.json
- packages/charting/src/components/DonutChart/Arc/Arc.styles.ts
- packages/charting/src/components/DonutChart/Arc/Arc.tsx
- packages/charting/src/components/DonutChart/Arc/Arc.types.ts
- packages/charting/src/components/DonutChart/DonutChart.base.tsx
- packages/charting/src/components/DonutChart/DonutChart.types.ts
- packages/charting/src/components/DonutChart/Pie/Pie.tsx
- packages/charting/src/components/DonutChart/Pie/Pie.types.ts
- packages/charting/src/components/DonutChart/examples/DonutChart.Basic.Example.tsx
- packages/charting/src/components/DonutChart/examples/DonutChart.Dynamic.Example.tsx
Add string inside Donut chart 
Donut chart
> Add string inside Donut chart

- packages/office-ui-fabric-react/src/components/pickers/PickerItem.types.ts
> Fixed spelling of 'whether'

- packages/fluentui/CHANGELOG.md
- packages/fluentui/docs/src/examples/components/Alert/commonScreenerSteps.ts
- packages/fluentui/react-northstar/src/components/Alert/Alert.tsx
- packages/fluentui/react-northstar/src/components/Alert/AlertDismissAction.tsx
- packages/fluentui/react-northstar/src/index.ts
- packages/fluentui/react-northstar/src/themes/teams-dark/componentVariables.ts
- packages/fluentui/react-northstar/src/themes/teams-dark/components/Alert/alertDismissActionVariables.ts
- packages/fluentui/react-northstar/src/themes/teams-high-contrast/componentVariables.ts
- packages/fluentui/react-northstar/src/themes/teams-high-contrast/components/Alert/alertDismissActionVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/componentStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/componentVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Alert/alertDismissActionStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Alert/alertDismissActionVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Alert/alertStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Alert/alertVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Alert/dismissIndicatorUrl.ts
- packages/fluentui/react-northstar/test/specs/components/Alert/Alert-test.tsx
- packages/fluentui/react-northstar/test/specs/components/Alert/AlertDismissAction-test.tsx
> feat(Alert): remove icon dependency

- change/office-ui-fabric-react-2020-04-02-14-20-31-fix-example-updates.json
- packages/office-ui-fabric-react/src/components/Divider/examples/VerticalDivider.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/Divider/examples/VerticalDivider.Custom.Example.tsx
- packages/office-ui-fabric-react/src/components/SearchBox/examples/SearchBox.CustomIcon.Example.tsx
- packages/office-ui-fabric-react/src/components/SearchBox/examples/SearchBox.Disabled.Example.tsx
- packages/office-ui-fabric-react/src/components/SearchBox/examples/SearchBox.FullSize.Example.tsx
- packages/office-ui-fabric-react/src/components/SearchBox/examples/SearchBox.Small.Example.tsx
- packages/office-ui-fabric-react/src/components/SearchBox/examples/SearchBox.Underlined.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/VerticalDivider.Basic.Example.tsx.shot
Updated `Searchbox` and `Divider` examples to functional components.
The example pages for the search box and the `Divider`.
> Updating Searchbox and Divider examples to use function components

- packages/fluentui/docs/src/components/ComponentDoc/ComponentSourceManager/ComponentSourceManager.ts
- packages/fluentui/docs/src/examples/components/Popup/Visual/index.tsx
Fixes paths for examples that were introduced in #12536.
(optional)
> docs: fix broken paths

- README.md
> Simplified Readme to include neccessary details

- packages/fluentui/docs/src/examples/components/SvgIcon/Playground.tsx
> docs: small updates to SvgIcon playground

- packages/fluentui/docs/src/views/FAQ.tsx
> feat(docs): add FAQ for adding new icons

- packages/fluentui/react-northstar/src/themes/teams/components/Popup/popupContentVariables.ts
Fixes a regression introduced in #12514. Still wondered that it was not captured by Screener 😨 
As it was not released yet, no changelog entries.
(optional)
> fix(Popup): update sizes for pointing break

- packages/fluentui/perf-test/stories/Icon.perf.tsx
> fix(perf): update icon perf test

- change/office-ui-fabric-react-2020-04-07-15-19-00-update-contextmenuitem-docs.json
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts
> ContextualMenu: Update docs to make text behavior more clear

- change/office-ui-fabric-react-2020-04-07-16-18-40-fix-combobox-activedescendant.json
- packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
Combobox: Fix an issue where getActiveDescendantValue would sometimes return <listId>-listundefined
(optional)
> Combobox: Fix issue where getActiveDescendantValue would sometimes return -listundefined

- azure-pipelines.perf-test.yml
- scripts/tasks/fluentui-publish.js
- Use `@fluentui/react-northstar_vX.Y.Z` tag for react-northstar released versions.
- Tag perf data for release builds.
> fix(build): correctly tag stats for react-northstar public builds

- change/@uifabric-experiments-2020-04-08-16-51-22-experiments-readme.json
- packages/experiments/README.md
Update the instructions for testing local changes to experiments.
(While the readme change is valid, the main purpose is actually to generate a change file for testing an edge case in #12558...)
> Update experiments testing instructions

- change/office-ui-fabric-react-2020-04-08-13-49-26-add-arialabel-custom-column.json
- packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.CustomColumns.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.CustomColumns.Example.tsx.shot
DetailsList: Add missing aria label to example
(optional)
> DetailsList: Add missing aria label to example

- apps/perf-test/src/scenarioIterations.js
- apps/perf-test/src/scenarios/ComboBox.tsx
- apps/perf-test/src/scenarios/Panel.tsx
- apps/perf-test/src/scenarios/Persona.tsx
- apps/perf-test/src/scenarios/TagPicker.tsx
Added basic tests for: ComboBox, Panel, TagPicker, Persona
(optional)
> add a few more perf tests

- packages/fluentui/docs-components/src/knobs/defaultComponents.tsx
- packages/fluentui/docs-components/src/knobs/types.ts
- packages/fluentui/docs-components/src/knobs/useNumberKnob.ts
Add option to set min, max and step on number knob
(optional)
> chore(knob) add option to set min, max and step on number knob

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams/components/Card/cardStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Card/cardVariables.ts
Add shadow styles for Card component for rest, hover, disabled, selected and pressed states via variables
Rest:
Hover:
> feat(Card): Add shadow styles 

- change/@uifabric-charting-2020-04-09-17-46-57-user-v-satgar-verticalbarchart.json
- packages/charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx
- packages/charting/src/components/VerticalBarChart/VerticalBarChart.styles.ts
- packages/charting/src/components/VerticalBarChart/VerticalBarChart.types.ts
- packages/charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap
- packages/charting/src/components/VerticalBarChart/examples/VerticalBarChart.Basic.Example.tsx
- packages/charting/src/types/IDataPoint.ts
Add Callout and Legends for vertical bar chart
Vertical bar chart on focus and on hover
> Verticalbar chart: Add Callout and Legends for vertical bar chart

- apps/fabric-website/src/utilities/location.ts
- change/@uifabric-fabric-website-2020-04-14-13-55-47-website-static.json
These pages won't build statically if they are assuming window is present
> Website: check for window before testing location

- apps/pr-deploy-site/package.json
- change/@uifabric-charting-2020-04-15-15-55-30-xgao-sync.json
- package.json
- packages/charting/package.json
update package to published versions by running `beachball sync`, fix publishing
(optional)
> Fix publishing by syncing package version

- package.json
- scripts/package.json
- yarn.lock
Bump to latest which includes fix for `beachball sync` command
(optional)
> bump beachball to latest

- change/@fluentui-react-icons-2020-04-15-21-40-36-publish-icons.json
- packages/react-icons/package.json
Updating package.json to publish react-icons.
> Publishing react-icons package.

- README.md
Removing Smarter Apps as section does not exist in README - just goes no where.
(optional)
> Removing Smarter Apps as section does not exist

- packages/fluentui/CHANGELOG.md
- packages/fluentui/accessibility/src/behaviors/Card/cardBehavior.ts
- packages/fluentui/accessibility/src/behaviors/Card/cardChildrenFocusableBehavior.ts
- packages/fluentui/accessibility/src/behaviors/Card/cardFocusableBehavior.ts
- packages/fluentui/accessibility/src/behaviors/Card/cardMultipleFocusableBehavior.ts
- packages/fluentui/accessibility/src/behaviors/index.ts
- packages/fluentui/accessibility/test/behaviors/behavior-test.tsx
- packages/fluentui/docs/src/examples/components/Card/BestPractices/CardBestPractices.tsx
- packages/fluentui/docs/src/examples/components/Card/Performance/CardMinimal.perf.tsx
- packages/fluentui/docs/src/examples/components/Card/Slots/CardExampleBody.tsx
- packages/fluentui/docs/src/examples/components/Card/Slots/CardExampleFooter.tsx
- packages/fluentui/docs/src/examples/components/Card/Slots/CardExampleHeader.tsx
- packages/fluentui/docs/src/examples/components/Card/Slots/CardExamplePreview.tsx
- packages/fluentui/docs/src/examples/components/Card/Usage/CardExampleFocusable.steps.ts
- packages/fluentui/docs/src/examples/components/Card/Usage/CardExampleFocusable.tsx
- packages/fluentui/docs/src/examples/components/Card/Usage/CardExampleFocusableChildren.tsx
- packages/fluentui/docs/src/examples/components/Card/Usage/CardExampleSimple.tsx
- packages/fluentui/docs/src/examples/components/Card/Usage/CardExampleWithPreview.tsx
- packages/fluentui/docs/src/examples/components/Card/Usage/index.tsx
- packages/fluentui/docs/src/examples/components/Card/Variations/CardExampleCentered.tsx
- packages/fluentui/docs/src/examples/components/Card/Variations/CardExampleFluid.tsx
- packages/fluentui/docs/src/examples/components/Card/Variations/CardExampleHorizontal.tsx
- packages/fluentui/docs/src/examples/components/Card/Variations/CardExampleSize.tsx
- packages/fluentui/docs/src/views/IconViewer.tsx
- packages/fluentui/react-northstar/src/components/Card/Card.tsx
- packages/fluentui/react-northstar/src/themes/teams/components/Card/cardStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Card/cardVariables.ts
- packages/fluentui/react-northstar/test/specs/components/Card/Card-test.tsx
> feat(Card): Add OnClick prop and styles

- apps/perf-test/src/scenarioIterations.js
- apps/perf-test/src/scenarios/ContextualMenu.tsx
I see some perf issues with ContextualMenu. before I fixing them, first adding a perf test to capture baseline
(optional)
> Add perf test for ContextualMenu

- package.json
- scripts/package.json
- yarn.lock
Bump to latest, including some fixes for publishing:
https://github.com/microsoft/beachball/pull/323
https://github.com/microsoft/beachball/pull/324
https://github.com/microsoft/beachball/pull/325
(optional)
> bump beachball to latest (contains fixes for publish)

- packages/fluentui/docs/src/examples/components/Popup/Types/PopupCustomTargetExample.shorthand.tsx
`trigger` and `children` should not be used simultaneously. 
(optional)
> docs: fix in PopupCustomTargetExample

- apps/fabric-website/src/components/Nav/Nav.tsx
- change/@uifabric-example-app-base-2020-04-17-11-45-55-window-issues.json
- change/@uifabric-fabric-website-2020-04-17-11-45-55-window-issues.json
- packages/example-app-base/src/components/SideRail/SideRail.tsx
- packages/example-app-base/src/utilities/jumpToAnchor.ts
> Website: guard against window and location not being available

- apps/fabric-website/src/pages/Controls/AvatarPage/docs/ios/AvatarImplementation.md
- apps/fabric-website/src/pages/Controls/BottomNavigationPage/docs/ios/BottomNavigationImplementation.md
- apps/fabric-website/src/pages/Controls/ButtonPage/docs/ios/ButtonImplementation.md
- apps/fabric-website/src/pages/Controls/ChipPage/docs/ios/ChipImplementation.md
- apps/fabric-website/src/pages/Controls/DatePickerPage/docs/ios/DateTimePickerImplementation.md
- apps/fabric-website/src/pages/Controls/DrawerPage/docs/ios/DrawerImplementation.md
- apps/fabric-website/src/pages/Controls/ListCellsPage/docs/ios/ListCellsImplementation.md
- apps/fabric-website/src/pages/Controls/NavBarPage/docs/ios/NavBarImplementation.md
- apps/fabric-website/src/pages/Controls/PersonaPage/docs/ios/PersonaImplementation.md
- apps/fabric-website/src/pages/Controls/PivotPage/docs/ios/PivotImplementation.md
- apps/fabric-website/src/pages/Controls/PopupMenuPage/docs/ios/PopupMenuImplementation.md
- apps/fabric-website/src/pages/Controls/SeparatorPage/docs/ios/SeparatorImplementation.md
- apps/fabric-website/src/pages/Controls/ShimmerPage/docs/ios/ShimmerImplementation.md
- apps/fabric-website/src/pages/Controls/SpinnerPage/docs/ios/SpinnerImplementation.md
- apps/fabric-website/src/pages/Controls/TextPage/docs/ios/TextImplementation.md
- apps/fabric-website/src/pages/Controls/TooltipPage/docs/ios/TooltipImplementation.md
update all the iOS document links to the new GitHub
> update to new github link

- change/@uifabric-charting-2020-04-17-18-04-06-user-v-satgar-Bug_4097990.json
- packages/charting/src/components/LineChart/LineChart.base.tsx
Fix issue line chart 'Tool tip' is displayed top of the page throgh accessibility
Line chart access lines through keyboard
> Fix issue line chart 'Tool tip' is displayed top of the page throgh accessibility

- apps/fabric-website/src/SiteDefinition/SiteDefinition.pages/Controls/ios.tsx
- apps/fabric-website/src/pages/Controls/MessageBarPage/MessageBarPage.doc.ts
- apps/fabric-website/src/pages/Controls/MessageBarPage/MessageBarPage.tsx
- apps/fabric-website/src/pages/Controls/MessageBarPage/docs/ios/MessageBarImplementation.md
- apps/fabric-website/src/pages/Controls/MessageBarPage/docs/ios/MessageBarOverview.md
- apps/fabric-website/src/pages/Controls/PillButtonBarPage/PillButtonBarPage.doc.ts
- apps/fabric-website/src/pages/Controls/PillButtonBarPage/PillButtonBarPage.tsx
- apps/fabric-website/src/pages/Controls/PillButtonBarPage/docs/PillButtonBarRelated.md
- apps/fabric-website/src/pages/Controls/PillButtonBarPage/docs/ios/PillButtonBarImplementation.md
- apps/fabric-website/src/pages/Controls/PillButtonBarPage/docs/ios/PillButtonBarOverview.md
- apps/fabric-website/src/pages/Controls/PivotPage/docs/PivotRelated.md
> add pillbarbutton and notification view documentation for iOS

- change/@fluentui-react-focus-2020-04-22-16-32-37-preventDefaultWhenHnadledComment.json
- packages/react-focus/src/components/FocusZone/FocusZone.types.ts
`FocusZone`: Updating comment for `preventDefaultWhenHandled` prop to be consistent across both versions.
(optional)
> FocusZone: Updating comment for preventDefaultWhenHandled prop

- apps/fabric-website/src/pages/Controls/AvatarPage/docs/ios/AvatarOverview.md
- apps/fabric-website/src/pages/Controls/BottomNavigationPage/docs/ios/BottomNavigationOverview.md
- apps/fabric-website/src/pages/Controls/ButtonPage/docs/ios/ButtonOverview.md
- apps/fabric-website/src/pages/Controls/ChipPage/docs/ios/ChipOverview.md
- apps/fabric-website/src/pages/Controls/DatePickerPage/docs/ios/DateTimePickerOverview.md
- apps/fabric-website/src/pages/Controls/DrawerPage/docs/ios/DrawerOverview.md
- apps/fabric-website/src/pages/Controls/ListCellsPage/docs/ios/ListCellsOverview.md
- apps/fabric-website/src/pages/Controls/NavBarPage/docs/ios/NavBarImplementation.md
- apps/fabric-website/src/pages/Controls/NavBarPage/docs/ios/NavBarOverview.md
- apps/fabric-website/src/pages/Controls/PersonaPage/docs/ios/PersonaOverview.md
- apps/fabric-website/src/pages/Controls/PillButtonBarPage/docs/ios/PillButtonBarOverview.md
- apps/fabric-website/src/pages/Controls/PivotPage/docs/ios/PivotOverview.md
- apps/fabric-website/src/pages/Controls/PopupMenuPage/docs/ios/PopupMenuOverview.md
- apps/fabric-website/src/pages/Controls/SeparatorPage/docs/ios/SeparatorOverview.md
- apps/fabric-website/src/pages/Controls/ShimmerPage/docs/ios/ShimmerOverview.md
- apps/fabric-website/src/pages/Controls/SpinnerPage/docs/ios/SpinnerOverview.md
- apps/fabric-website/src/pages/Controls/TextPage/docs/ios/TextOverview.md
- apps/fabric-website/src/pages/Controls/TooltipPage/docs/ios/TooltipOverview.md
> update images in iOS

- apps/fabric-website/src/pages/Overviews/GetStartedPage/docs/android/GetStartedOverview.md
- apps/fabric-website/src/pages/Overviews/GetStartedPage/docs/ios/GetStartedOverview.md
- apps/fabric-website/src/pages/Overviews/ResourcesPage/docs/default/ResourcesDesignResources.md
- apps/fabric-website/src/pages/PageTemplates/TemplatePage/docs/default/TemplateBestPractices.md
- apps/fabric-website/src/pages/PageTemplates/TemplatePage/docs/default/TemplateCustom.md
- packages/example-app-base/src/components/ComponentPage/ComponentPage.styles.ts
- packages/example-app-base/src/components/ComponentPage/ComponentPage.tsx
- packages/example-app-base/src/components/ComponentPage/ComponentPage.types.ts
- packages/example-app-base/src/components/Page/Page.tsx
- packages/example-app-base/src/components/Page/sections/BestPracticesSection.tsx
- packages/fluentui/docs/src/components/ComponentDoc/ComponentBestPractices.tsx
- packages/fluentui/eslint-plugin/rules/no-visibility-modifiers/index.js
- scripts/templates/create-page/EmptyBestPractices.mustache
- scripts/templates/create-page/EmptyCustom.mustache
> Changing website titles to sentence case 

- apps/fabric-website/src/pages/Controls/SpinnerPage/docs/ios/SpinnerOverview.md
> add spinner images

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-bindings/src/hooks/useAccessibility.ts
- packages/fluentui/react-bindings/test/hooks/useAccessibility-test.tsx
- packages/fluentui/react-northstar/src/components/SplitButton/SplitButton.tsx
- packages/fluentui/react-northstar/src/components/Table/TableRow.tsx
Allow childBehaviors to be applied using useAccessibility hook
> RFC(useAccessibility): Add child behavior to useAccessibility hook, variant A

- change/@uifabric-charting-2020-04-29-10-21-11-user-v-sivsar-addinghovercarddismmisdelay.json
- packages/charting/src/components/Legends/Legends.base.tsx
Addresses an issue: Fixes https://office.visualstudio.com/OC/_queries/edit/4115327/
adding dismiss delay to prevent hover card from getting dismissed when mouse moves out of the text
legends
> User/v sivsar/addinghovercarddismmisdelay

- scripts/gulp/tasks/test-projects.ts
Currently the CI is breaking with the latest rollup version `2.7.5`. This PR set the fixed version to `2.7.3` ( last compatible ) temporally.
(optional)
> chore(TestProjects): Set fixed rollup version - CI

- azure-pipelines.release.yml
error: https://uifabric.visualstudio.com/UI%20Fabric/_build/results?buildId=70401&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=c3091b1e-314e-512e-11db-151fdba14cd6
this is broken due to we downgraded `ts-node` to v7 and `--dir` is not supported
(optional)
> fix updateReleaseNotes script path

- apps/fabric-website/src/data/brand-icons-products.json
- apps/fabric-website/src/pages/Styles/OfficeBrandIconsPage/OfficeBrandIconsPage.tsx
- change/@uifabric-fabric-website-2020-04-29-22-04-47-icon-page-update.json
> Website: Update Icon Product Page

- apps/fabric-website/src/data/brand-icons-products.json
- change/@uifabric-fabric-website-2020-05-01-08-34-29-icon-typo.json
> Website: Update 'forms' text on icon page

- change/@fluentui-react-next-2020-05-01-14-15-09-feat-toggle.json
- packages/react-next/etc/react-next.api.md
- packages/react-next/src/Toggle.ts
- packages/react-next/src/components/Toggle/Toggle.base.tsx
- packages/react-next/src/components/Toggle/Toggle.deprecated.test.tsx
- packages/react-next/src/components/Toggle/Toggle.doc.tsx
- packages/react-next/src/components/Toggle/Toggle.styles.ts
- packages/react-next/src/components/Toggle/Toggle.test.tsx
- packages/react-next/src/components/Toggle/Toggle.tsx
- packages/react-next/src/components/Toggle/Toggle.types.ts
- packages/react-next/src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
- packages/react-next/src/components/Toggle/docs/ToggleDonts.md
- packages/react-next/src/components/Toggle/docs/ToggleDos.md
- packages/react-next/src/components/Toggle/docs/ToggleOverview.md
- packages/react-next/src/components/Toggle/docs/new/ToggleBestPractices.md
- packages/react-next/src/components/Toggle/docs/new/ToggleOverview.md
- packages/react-next/src/components/Toggle/examples/Toggle.Basic.Example.tsx
- packages/react-next/src/components/Toggle/examples/Toggle.CustomLabel.Example.tsx
- packages/react-next/src/components/Toggle/index.ts
This change does not modify Toggle; it simply moves it to react-next for better diffing in the actual conversion PR.
> Copying Toggle to react-next, in preparation for converting to function component

- packages/fluentui/react-northstar/src/components/Accordion/Accordion.tsx
Prevents creating a new ref all renders
(optional)
> fix(Accordion): Control itemsRef

- packages/fluentui/CHANGELOG.md
- packages/fluentui/docs/src/examples/components/Card/Usage/CardExampleContextMenu.tsx
- packages/fluentui/docs/src/examples/components/Card/Usage/index.tsx
Add example for Card component with context menu
> docs(Card): example with context menu

- change/office-ui-fabric-react-2020-05-04-11-34-34-fixDragDrop.json
- packages/office-ui-fabric-react/src/components/MarqueeSelection/MarqueeSelection.base.tsx
#12722 introduced a change to the `Point` interface. However, this change broke drag and drop functionality in `MarqueeSelection` because of a missing update. This PR fixes that issue by making such update in `MarqueeSelection.base.tsx`.
(optional)
> MarqueeSelection: Fixing drag and drop functionality

- change/@fluentui-react-focus-2020-05-04-13-23-25-missingPointReferences.json
- change/office-ui-fabric-react-2020-05-04-13-23-25-missingPointReferences.json
- packages/office-ui-fabric-react/src/components/Keytip/examples/KeytipSetup.ts
- packages/office-ui-fabric-react/src/utilities/positioning.test.ts
- packages/react-focus/src/components/FocusZone/FocusZone.tsx
Adding a bunch of missed changes in #12722.
(optional)
> Adding missing changes due to move from IPoint to Point

- change/@uifabric-file-type-icons-2020-05-05-12-12-18-caperez-refresh_tiletype_salt.json
- packages/file-type-icons/src/initializeFileTypeIcons.tsx
> refresh tiletype icon url salt to bust thru the can cache.

- change/@uifabric-charting-2020-05-06-17-42-37-user-v-satgar-Task_4142485.json
- packages/charting/src/components/DonutChart/DonutChart.base.tsx
- packages/charting/src/components/DonutChart/DonutChart.types.ts
- packages/charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
- packages/charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.types.tsx
- packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.base.tsx
- packages/charting/src/components/HorizontalBarChart/HorizontalBarChart.types.ts
- packages/charting/src/components/LineChart/LineChart.base.tsx
- packages/charting/src/components/LineChart/LineChart.types.ts
- packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/MultiStackedBarChart.types.ts
- packages/charting/src/components/StackedBarChart/StackedBarChart.base.tsx
- packages/charting/src/components/StackedBarChart/StackedBarChart.types.ts
- packages/charting/src/components/StackedBarChart/examples/StackedBarChart.Basic.Example.tsx
- packages/charting/src/components/VerticalBarChart/VerticalBarChart.base.tsx
- packages/charting/src/components/VerticalBarChart/VerticalBarChart.types.ts
- packages/charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.base.tsx
- packages/charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.types.ts
Expose a prop for to disable  tooltips in charts  
(optional)
> Charting package: Expose prop for hide tooltips in charts

- apps/fabric-website/src/pages/Controls/PopupMenuPage/docs/ios/PopupMenuOverview.md
popupmenu controller darkmode image wasn't loading properly
> fix misspelled filename

- change/office-ui-fabric-react-2020-05-07-10-39-52-fix-example6-corrections.json
- packages/office-ui-fabric-react/src/components/Announced/examples/Announced.SearchResults.Example.tsx
- packages/office-ui-fabric-react/src/components/Calendar/examples/Calendar.Button.Example.tsx
- packages/office-ui-fabric-react/src/components/Calendar/examples/Calendar.Inline.Example.tsx
- packages/office-ui-fabric-react/src/components/Callout/examples/Callout.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/Callout/examples/Callout.Directional.Example.tsx
- packages/office-ui-fabric-react/src/components/Callout/examples/Callout.FocusTrap.Example.tsx
Cleaned up the code for Callout, Announced, and Calendar examples.
Callout, Announced, and Calendar
> Cleaning up Callout, Announced, and Calendar examples

- .github/CODEOWNERS
Update code owners for `react-next` components based on recent convergence work distribution.
(optional)
> Update code owners for react-next components

- change/@fluentui-react-next-2020-05-11-13-47-57-feat-link.json
- packages/react-next/etc/react-next.api.md
- packages/react-next/src/Link.ts
- packages/react-next/src/components/Link/Link.base.tsx
- packages/react-next/src/components/Link/Link.doc.tsx
- packages/react-next/src/components/Link/Link.styles.ts
- packages/react-next/src/components/Link/Link.test.tsx
- packages/react-next/src/components/Link/Link.tsx
- packages/react-next/src/components/Link/Link.types.ts
- packages/react-next/src/components/Link/__snapshots__/Link.test.tsx.snap
- packages/react-next/src/components/Link/docs/LinkDonts.md
- packages/react-next/src/components/Link/docs/LinkDos.md
- packages/react-next/src/components/Link/docs/LinkOverview.md
- packages/react-next/src/components/Link/docs/new/LinkBestPractices.md
- packages/react-next/src/components/Link/docs/new/LinkOverview.md
- packages/react-next/src/components/Link/examples/Link.Basic.Example.tsx
- packages/react-next/src/components/Link/index.ts
This change does not modify Link; it simply moves it to react-next for better diffing in the actual conversion PR.
> Copying Link to react-next, in preparation for converting to function component

- packages/fluentui/react-northstar/src/components/Box/Box.tsx
- packages/fluentui/react-northstar/src/components/List/ListItem.tsx
Reimplement applicable parts (Box, ListItem) of #13093 in react-northstar_v0.47.x
(optional)
> fix(FocusZone): RFC components

- change/office-ui-fabric-react-2020-03-17-07-47-55-patch-1.json
- packages/office-ui-fabric-react/src/components/Nav/examples/Nav.Basic.Example.tsx
> Nav: fix Basic Example type error

- change/@uifabric-charting-2020-05-14-12-20-17-user-v-satgar-Bug_4154248.json
- packages/charting/src/components/StackedBarChart/MultiStackedBarChart.base.tsx
MultiStackedBarChart: Fix breaking chart when focus on bars through keyboard
Multi Stacked Bar chart accessibility using mouse and keyboard
> MultiStackedBarChart: Fix breaking chart when focus on bars through keyboard

- apps/fabric-website/src/pages/HomePage/HomePage.styles.ts
- change/@uifabric-fabric-website-2020-05-14-18-45-24-website-visited-fix.json
> Website: fixed visited link styles

- apps/vr-tests/package.json
- packages/fluentui/perf-test/package.json
Fix dep version mismatches apparently introduced by beachball in 2e7ff83935d73005b876a1fcace30c7457201f91...?
> Fix dep mismatches

- apps/fabric-website/src/pages/Overviews/ResourcesPage/docs/default/ResourcesDeveloperResources.md
- change/@uifabric-fabric-website-2020-05-15-13-12-47-website-url-fix.json
old dev.office.com links were dead. Updated URLs to current location of pages.
> Website url fix

- packages/fluentui/docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
- packages/fluentui/docs/src/components/ComponentDoc/ComponentExample/ComponentExampleTitle.tsx
Adds a hidden label for component example source code so that it is easier to find the source code in their preferred IDE for screen reader users.
> docs(Examples): Add hidden text for example source name

- apps/fabric-website/src/pages/Overviews/GetStartedPage/docs/ios/GetStartedOverview.md
- change/@uifabric-fabric-website-2020-05-18-09-58-18-hyshin-update_getstartedpage_ios.json
Minor sentence update in iOS Get Started Page
(optional)
> minor updates on iOS get started page

- .github/CODEOWNERS
Removing phkuo as a codeowner of Toggle.
(optional)
> Removing phkuo as a codeowner of Toggle

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams-dark/colors.ts
- packages/fluentui/react-northstar/src/themes/teams-high-contrast/colors.ts
- packages/fluentui/react-northstar/src/themes/teams/colors.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Card/cardStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Card/cardVariables.ts
Update styles for selected card
> feat(Card): Refactor card styles + update selected styles

- apps/fabric-website/src/pages/Controls/TextPage/TextPage.tsx
- change/@uifabric-fabric-website-2020-05-21-15-27-13-text-update.json
Updated description of the fontSize property on Text. Associated changes: microsoft/fluentui-react-native#222
Cross platform control pages of Fluent website, specifically Text.
> Update cross platform text documentation for fontSize prop

- apps/test-bundles/package.json
- apps/test-bundles/webpack.config.js
add `react-compose` package to size auditor
(optional)
> add react-compose to size auditor

- packages/fluentui/CHANGELOG.md
- packages/fluentui/accessibility/src/behaviors/Loader/loaderBehavior.ts
- packages/fluentui/accessibility/src/behaviors/index.ts
- packages/fluentui/react-northstar/src/components/Loader/Loader.tsx
- packages/fluentui/react-northstar/src/themes/teams/components/Loader/loaderStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/types.ts
- packages/fluentui/react-northstar/test/specs/components/Loader/Loader-test.tsx
This PR converts `Loader` component to be functional. Restricting props set that will be passed to styles functions.
Related to #12237
| `Loader`    |
| --------- |
| `inline` |
| `labelPosition` |
| `size` |
(optional)
> chore(Loader): Convert to RFC

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/components/Portal/PortalInner.tsx
Converting `PortalInner` from class component to functional. 
Related to #12237
(optional)
> chore(PortalInner): Convert to RFC

- packages/fluentui/code-sandbox/src/KnobsSnippet.tsx
- packages/fluentui/docs-components/src/knobs/useKnob.ts
- packages/fluentui/docs/src/components/ComponentPlayground/ComponentPlayground.tsx
- packages/fluentui/docs/src/components/VariableResolver/VariableResolver.tsx
- packages/fluentui/docs/src/components/VariableResolver/useClassNamesListener.ts
- packages/fluentui/docs/src/components/VariableResolver/useEnhancedRenderer.ts
- packages/fluentui/docs/src/examples/components/Provider/Usage/ProviderExampleTarget.tsx
- packages/fluentui/docs/src/prototypes/CopyToClipboard/CopyToClipboard.tsx
- packages/fluentui/docs/src/prototypes/EditorToolbar/PortalWindow.tsx
- packages/fluentui/docs/src/prototypes/EditorToolbar/index.tsx
- packages/fluentui/docs/src/prototypes/mentions/MentionsEditor.tsx
- packages/fluentui/docs/src/prototypes/table/ResponsiveTableContainer.tsx
- packages/fluentui/react-bindings/src/hooks/useStateManager.ts
- packages/fluentui/react-bindings/test/hooks/useStateManager-test.tsx
- packages/fluentui/react-component-event-listener/src/useEventListener.ts
- packages/fluentui/react-component-nesting-registry/src/hooks/useNestingAuto.ts
- packages/fluentui/react-component-nesting-registry/src/hooks/useNestingChild.ts
- packages/fluentui/react-component-nesting-registry/src/hooks/useNestingRoot.ts
- packages/fluentui/react-northstar/src/components/Accordion/Accordion.tsx
- packages/fluentui/react-northstar/src/components/Animation/Animation.tsx
- packages/fluentui/react-northstar/src/components/Carousel/Carousel.tsx
- packages/fluentui/react-northstar/src/components/List/List.tsx
- packages/fluentui/react-northstar/src/components/Menu/Menu.tsx
- packages/fluentui/react-northstar/src/components/Popup/Popup.tsx
- packages/fluentui/react-northstar/src/utils/positioner/Popper.tsx
- scripts/eslint/index.js
- scripts/package.json
- yarn.lock
This PR enables `eslint-plugin-react-hooks` for v0 to catch possible issues with dependencies.
(optional)
> chore: enable eslint-plugin-react-hooks for v0

- change/@fluentui-react-next-2020-05-20-19-12-25-slider-hook.json
- packages/react-next/etc/react-next.api.md
- packages/react-next/src/components/Slider/Slider.base.tsx
- packages/react-next/src/components/Slider/Slider.types.ts
- packages/react-next/src/components/Slider/useSlider.ts
Part1 of moving state out of slider into a useSlider hook. I'm intentionally leaving the slide, thumb, slide value, for the next iteration to help reduce the amount that is happening in this change.
#ElectricSlide
> Slider hook part 1.

- apps/perf-test/package.json
- apps/perf-test/src/scenarios/ButtonNext.tsx
- apps/test-bundles/package.json
- apps/test-bundles/webpack.config.js
- apps/vr-tests/package.json
- apps/vr-tests/src/stories/ButtonNext.stories.tsx
…ton.
This PR adds `@fluentui/react-button` to the list of packages that are checked in `test-bundles` and adds perf and VR tests for the `Button` component inside `@fluentui/react-button`.
(optional)
> Button: Adding bundle, perf and VR tests for Button in @fluentui/react-button

- .github/CODEOWNERS
add Xu as perf-test code co-owner
(optional)
> add Xu as perf-test code co-owner

- packages/fluentui/CHANGELOG.md
- packages/fluentui/docs/src/examples/components/Toolbar/Visual/ToolbarExampleCompose.shorthand.tsx
- packages/fluentui/react-northstar/src/components/Toolbar/Toolbar.tsx
> feat(Toolbar): use compose()

- packages/fluentui/docs-components/src/knobs/useKnob.ts
This PR removes `initialValue` from `useKnob` array of deps to fix this behavior:
(optional)
> fix(UseKnob): Prevent infinity update

- change/@uifabric-utilities-2020-05-27-16-51-42-autocapitalize-property-bug.json
- packages/utilities/src/properties.ts
Added autoCapitalize property to inputProperties and textAreaProperties
> Add autoCapitalize property

- packages/fluentui/docs/src/examples/components/Table/Performance/TableManyItems.perf.tsx
- packages/fluentui/docs/src/examples/components/Table/Performance/index.tsx
- packages/fluentui/docs/src/examples/components/Table/Usage/TableExampleStatic.shorthand.tsx
- packages/fluentui/docs/src/examples/components/Table/Usage/TableExampleStatic.tsx
- packages/fluentui/docs/src/examples/components/Table/index.tsx
This PR:
- makes visible existing example
- adds new perf test case
- cleanups example from useless keys
(optional)
> docs(Table): add perf example, make visible existing

- change/@fluentui-react-next-2020-05-27-15-57-39-slider-hook-too.json
- packages/react-next/src/components/Slider/Slider.base.tsx
- packages/react-next/src/components/Slider/__snapshots__/Slider.test.tsx.snap
- packages/react-next/src/components/Slider/useSlider.ts
> SliderNext: Completely pull state out to be slot-like

- change/@fluentui-react-next-2020-05-28-11-44-39-feat-dropdown.json
- packages/react-next/src/components/Dropdown/Dropdown.base.tsx
- packages/react-next/src/components/Dropdown/Dropdown.doc.tsx
- packages/react-next/src/components/Dropdown/Dropdown.styles.ts
- packages/react-next/src/components/Dropdown/Dropdown.test.tsx
- packages/react-next/src/components/Dropdown/Dropdown.ts
- packages/react-next/src/components/Dropdown/Dropdown.types.ts
- packages/react-next/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/react-next/src/components/Dropdown/docs/DropdownDonts.md
- packages/react-next/src/components/Dropdown/docs/DropdownDos.md
- packages/react-next/src/components/Dropdown/docs/DropdownOverview.md
- packages/react-next/src/components/Dropdown/docs/new/DropdownBestPractices.md
- packages/react-next/src/components/Dropdown/docs/new/DropdownOverview.md
- packages/react-next/src/components/Dropdown/examples/Dropdown.Basic.Example.tsx
- packages/react-next/src/components/Dropdown/examples/Dropdown.Controlled.Example.tsx
- packages/react-next/src/components/Dropdown/examples/Dropdown.ControlledMulti.Example.tsx
- packages/react-next/src/components/Dropdown/examples/Dropdown.Custom.Example.tsx
- packages/react-next/src/components/Dropdown/examples/Dropdown.Error.Example.tsx
- packages/react-next/src/components/Dropdown/examples/Dropdown.Required.Example.tsx
- packages/react-next/src/components/Dropdown/index.ts
- packages/react-next/src/components/Dropdown/utilities/DropdownSizePosCache.test.ts
- packages/react-next/src/components/Dropdown/utilities/DropdownSizePosCache.ts
This change does not modify `Dropdown`; it simply moves it to react-next for better diffing in the actual conversion PR.
> Copying Dropdown to react-next, in preparation for converting to function component

- scripts/just.config.ts
- scripts/storybook/webpack.config.js
Makes the classnames easier to read in storybook.
> fixing an issue with the module classnames

- change/office-ui-fabric-react-2020-06-01-18-12-24-aria-check-menuitemradio.json
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuButton.tsx
Fixes https://github.com/microsoft/fluentui/issues/13432
(optional)
> Add Aria-checked if role is menuitemradio

- packages/fluentui/digest/package.json
- packages/fluentui/perf-test/package.json
- scripts/package.json
- yarn.lock
Bump version of just-scripts to include https://github.com/microsoft/just/pull/385
> Update just-scripts version to fix warning during sass build step

- packages/fluentui/docs/src/examples/components/Tree/Usage/TreeTitleCustomizationExample.shorthand.steps.ts
- packages/fluentui/docs/src/examples/components/Tree/Usage/TreeTitleCustomizationExample.shorthand.tsx
- packages/fluentui/react-northstar/src/components/Tree/TreeItem.tsx
This PR updates the `Tree` to work with the current implementation. 
(optional)
> fix(Tree): Fix example

- change/@fluentui-react-button-2020-06-02-22-50-23-fix-optimize-class-resolver.json
- change/@fluentui-react-compose-2020-06-02-22-50-23-fix-optimize-class-resolver.json
- packages/react-button/src/components/Button/Button.scss
- packages/react-button/src/components/Button/Button.tsx
- packages/react-compose/etc/react-compose.api.md
- packages/react-compose/src/appendClasses.ts
- packages/react-compose/src/createClassResolver.test.ts
- packages/react-compose/src/createClassResolver.ts
- packages/react-compose/src/resolveClasses.ts
This change moves most of the class parsing logic to compose time. Experimenting with optimizations before we kick in memoization.
> Perf: adjust `createClassResolver` to do more logic as compose time vs runtime

- change/office-ui-fabric-react-2020-06-04-11-32-02-stackDeprecatedTokens.json
- packages/office-ui-fabric-react/src/components/Stack/Stack.types.ts
Stack: Clarifying deprecated message of props replaced by tokens.
(optional)
> Stack: Clarifying deprecated message of props replaced by tokens

- .github/ISSUE_TEMPLATE/question.md
> Update SO tags

- apps/perf-test/src/scenarioIterations.js
- apps/perf-test/src/scenarios/PivotNext.tsx
Making the Pivot and PivotNext scenario exactly the same for better comparison
(optional)
> Pivot: match PivotNext perf test scenario with current

- change/@fluentui-react-compose-2020-06-05-16-02-40-xgao-compose-classes.json
- packages/react-compose/etc/react-compose.api.md
- packages/react-compose/src/mergeComposeOptions.ts
- packages/react-compose/src/types.ts
Update compose classes option to be array
(optional)
> compose: Update classes option to allow array

- apps/perf-test/src/scenarioRenderTypes.js
- apps/perf-test/tasks/perf-test.ts
Add re-render perf test for ThemeProvider
(optional)
> Add re-render perf test for ThemeProvider

- change/@uifabric-experiments-2020-06-03-06-47-23-u-nebhatna-floatingUnitTests.json
- packages/experiments/src/components/FloatingSuggestionsComposite/FloatingSuggestionsComposite.test.tsx
- packages/experiments/src/components/FloatingSuggestionsComposite/__snapshots__/FloatingSuggestionsComposite.test.tsx.snap
- packages/office-ui-fabric-react/src/components/FloatingPicker/BaseFloatingPicker.test.tsx
Adding unit tests for floatingsuggestioncomposite component.
(optional)
> Adding unit tests for floatingsuggestioncomposite component.

- change/@fluentui-react-button-2020-06-11-11-35-22-toggleButtonNewTokens.json
- packages/react-button/package.json
- packages/react-button/src/components/ToggleButton/ToggleButton.scss
#13416 updated the css variable names of `Button` but didn't for `ToggleButton`, which broke the `checked` styling. This PR fixes that issue by renaming the css variables in `ToggleButton` as well.
(optional)
> ToggleButton: Updating to new css variables

- specs/Datepicker.md
> spec(Datepicker): add datepicker spec draft

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-bindings/src/styles/convertCssTimeToNumber.ts
- packages/fluentui/react-bindings/test/styles/convertCssTimeToNumber-test.ts
added tests for decimal values
(optional)
> perf(Animation): improve convertCssTimeToNumber perf

- change/@fluentui-react-compose-2020-06-11-12-21-55-xgao-checkbox-useState.json
- change/@fluentui-react-next-2020-06-11-12-21-55-xgao-checkbox-useState.json
- packages/react-compose/etc/react-compose.api.md
- packages/react-compose/src/compose.ts
- packages/react-compose/src/mergeComposeOptions.ts
- packages/react-compose/src/types.ts
- packages/react-next/etc/react-next.api.md
- packages/react-next/src/components/Checkbox/Checkbox.base.tsx
- packages/react-next/src/components/Checkbox/Checkbox.tsx
- packages/react-next/src/components/Checkbox/useCheckbox.ts
- packages/react-next/src/components/Toggle/useToggle.ts
- compose: pass forwarded ref as param in state option
- Checkbox: use state option and move Icon out of Base component
(optional)
> Checkbox: use state option and move Icon out of Base component

- apps/perf-test/src/scenarios/ButtonNext.tsx
Perf-test: pass tokens prop in ButtonNext.
(optional)
> Perf-test: pass tokens prop in ButtonNext

- change/@uifabric-experiments-2020-06-09-14-19-46-u-nebhatna-uppUnitTests.json
- packages/experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/UnifiedPeoplePicker.test.tsx
- packages/experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/__snapshots__/UnifiedPeoplePicker.test.tsx.snap
- packages/experiments/src/components/UnifiedPicker/UnifiedPicker.test.tsx
- packages/experiments/src/components/UnifiedPicker/__snapshots__/UnifiedPicker.test.tsx.snap
Adding unit tests for unifiedpicker and unifiedpeoplepicker
UnifiedPeoplePicker tests are just specific to testing persona items in unified picker
(optional)
> Adding unit tests for unifiedpicker and unifiedpeoplepicker

- change/@uifabric-styling-2020-06-16-18-05-06-phkuo-newRoundedCorners.json
- change/office-ui-fabric-react-2020-06-16-18-05-06-phkuo-newRoundedCorners.json
- packages/office-ui-fabric-react/src/common/_effects.scss
- packages/styling/etc/styling.api.md
- packages/styling/src/interfaces/IEffects.ts
- packages/styling/src/styles/DefaultEffects.ts
Designers are using some new rounded corner values that should be part of the theme.
> Theming: Add new rounded corner values

- change/office-ui-fabric-react-2020-06-16-09-19-45-react-icon-branch.json
- packages/office-ui-fabric-react/src/components/Icon/Icon.base.tsx
- packages/office-ui-fabric-react/src/components/Icon/Icon.test.tsx
- packages/office-ui-fabric-react/src/components/Icon/__snapshots__/Icon.test.tsx.snap
Add logic to allow children prop to pass through to the Icon component, write unit tests for Icon component, and update icon snapshots
(optional)
> Icon: Rendering children if passed down as props and adding snapshot tests for these scenarios

- .codesandbox/ci.json
This is a test PR to see how the codesandbox CI works.
> Adding codesandbox integration to CI

- change/@uifabric-charting-2020-06-17-18-20-34-user-v-sivsar-charts-accesibility.json
- packages/charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.styles.ts
- packages/charting/src/components/Legends/Legends.styles.ts
- packages/charting/src/components/LineChart/LineChart.base.tsx
- packages/charting/src/components/LineChart/LineChart.styles.ts
- packages/charting/src/components/StackedBarChart/StackedBarChart.styles.ts
- packages/charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap
- packages/charting/src/components/VerticalStackedBarChart/VerticalStackedBarChart.styles.ts
added css fixes to the charts, in both normal and high contrast mode..
**line chart before fix normal mode**
**line chart after fix normal mode**
**line chart before fix white on black mode**
**line chart after fix white on black mode**
**line chart before fix  black on white mode**
**line chart after fix black on white mode**
**stacked bar chart before fix normal mode**
**stacked bar chart after fix normal mode**
**stacked bar chart before fix white on black mode**
**stacked bar chart after fix white on black mode**
**stacked bar chart before fix black on white mode**
**stacked bar chart after fix black on white mode**
**grouped vertical bar chart before fix normal mode**
**grouped vertical bar chart after fix normal mode**
**grouped vertical bar chart before fix white on black mode** …
> css fixes in charts for both normal and high contrast mode

- packages/fluentui/react-telemetry/src/TelemetryTable.tsx
- packages/fluentui/react-telemetry/src/styles.ts
- packages/fluentui/react-telemetry/src/useTelemetryColumns.tsx
This PR improves styling a bit and adds `5` & `10` options to pagination options.
(optional)
> fix(Telemetry): improve styling

- change/@uifabric-charting-2020-06-18-14-51-55-user-v-jasha-bug#4221191.json
- packages/charting/src/components/DonutChart/DonutChart.base.tsx
Doughnut chart, accessibility updated to circular way(clock wise and anti clockwise)
Doughnut chart
###Before fix
> Doughnut chart - circular accessibility updated.

- change/@uifabric-charting-2020-06-19-11-00-59-user-v-jasha-bug#4221194.json
- packages/charting/src/components/DonutChart/DonutChart.base.tsx
Doughnut chart target alignment updated
Doughnut chart.
> Doughnut chart target alignment updated.

- change/@fluentui-react-next-2020-06-22-16-27-55-xgao-fix-build.json
- packages/react-next/src/components/SelectedItemsList/SelectedPeopleList/Items/ExtendedSelectedItem.tsx
- packages/react-next/src/components/SelectedItemsList/examples/SelectedPeopleList.Basic.Example.tsx
- packages/react-next/src/components/SelectedItemsList/examples/SelectedPeopleList.Controlled.Example.tsx
Fix [broken build](https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=85230&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=cb33ee24-f492-54d2-727a-ae0a7bb84b2c)
(optional)
> Fix incorrect button imports (broken build)

- .codesandbox/ci.json
Add more packages needed for codesandbox examples to config
> Adding more packages to codesandbox config

- packages/fluentui/docs/package.json
- packages/fluentui/docs/src/components/VariableResolver/VariableResolver.tsx
- packages/fluentui/docs/src/components/VariableResolver/useEnhancedRenderer.ts
- yarn.lock
This PR fixes "Theme it" feature that was broken in #13602 as `Renderer` interface and functionality changed.
(optional)
> docs: fix theme it feature

- change/@uifabric-file-type-icons-2020-06-22-11-41-59-caperez-filetype_cortex_and_shortcut.json
- packages/file-type-icons/src/FileTypeIconMap.ts
- packages/file-type-icons/src/initializeFileTypeIcons.tsx
> revving CDN url and adding 2 filetype icons

- change/@fluentui-react-button-2020-06-11-12-43-47-xgao-mergeProps-typing.json
- change/@fluentui-react-compose-2020-06-11-12-43-47-xgao-mergeProps-typing.json
- change/@fluentui-react-next-2020-06-11-12-43-47-xgao-mergeProps-typing.json
- packages/react-button/etc/react-button.api.md
- packages/react-button/src/components/Button/Button.types.tsx
- packages/react-button/src/components/Button/ButtonBase.tsx
- packages/react-button/src/components/ToggleButton/ToggleButton.types.ts
- packages/react-compose/etc/react-compose.api.md
- packages/react-compose/src/mergeProps.ts
- packages/react-compose/src/types.ts
- packages/react-next/etc/react-next.api.md
- packages/react-next/src/components/Checkbox/Checkbox.base.tsx
- packages/react-next/src/components/Checkbox/Checkbox.types.ts
Include typings for slots and slotProps in mergeProps typing and fixes in its use cases.
(optional)
> Include typings for slots and slotProps in mergeProps typing

- change/@fluentui-react-button-2020-06-22-23-09-48-fix-button-styles.json
- change/@fluentui-react-button-2020-06-22-23-10-29-fix-button-styles.json
- packages/react-button/etc/react-button.api.md
- packages/react-button/src/components/Button/Button.scss
- packages/react-button/src/components/Button/Button.types.tsx
- packages/react-button/src/components/Button/ButtonBase.tsx
* adding `tokens` to handled props
* adding `boxShadow` to tokens
* adjusting sizing tokens
> react-button: minor tweaks to Button

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-builder/package.json
- packages/fluentui/react-builder/src/utils/codeToTree.ts
react-northstar docsite was broken in IE11 due to UI Builder using `@babel/core` which does not work in IE11.
Switched to `@babel/standalone`
- docsite loads in IE11
> fix(Docs) fix UI Builder loading in IE11

- azure-pipelines.bundlesize.yml
Remove unneeded steps from size auditor CI
(optional)
> Remove unneeded steps from size auditor CI

- change/@uifabric-experiments-2020-06-25-13-18-22-u-nebhatna-fixImports.json
- packages/experiments/src/components/UnifiedPicker/UnifiedPicker.tsx
Thanks Elizabeth for pointing out but we are incorrectly importing a file possibly causing it to failing getting download in node_modules as part of experiments package download.
(optional)
> UnifiedPicker - Fixing failing import package

- change/office-ui-fabric-react-2020-05-27-20-15-46-peoplepicker-duplicates.json
- packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/examples/PeoplePicker.Compact.Example.tsx
- packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/examples/PeoplePicker.LimitedSearch.Example.tsx
- packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/examples/PeoplePicker.List.Example.tsx
- packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/examples/PeoplePicker.Normal.Example.tsx
- packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/examples/PeoplePicker.PreselectedItems.Example.tsx
- packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/examples/PeoplePicker.ProcessSelection.Example.tsx
Fix PeoplePicker examples so the duplicates issue is resolved
> Fix examples to properly remove duplicates

- change/office-ui-fabric-react-2020-06-25-16-57-56-passEventSpinButton.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx
- packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.types.ts
There is no way for a caller of spin button to determine if the spinner was incremented or decremented by mouse or keyboard.  We already have all the event information so this allows us to pass it through
> Plumb event information through for spin button increment/decrement

- packages/fluentui/docs/src/prototypes/FormValidation/FormHooks.tsx
- packages/fluentui/docs/src/prototypes/FormValidation/Formik.tsx
Remove `required` from form components in the `Form Prototype`
(optional)
> fix(FormPrototype): remove required

- change/@uifabric-charting-2020-06-29-12-58-39-user-v-gorraj-Bug_4221810.json
- packages/charting/src/components/Legends/Legends.base.tsx
Legends: Fix Incorrect role is defined for lagend overflow items
It will fix this issue https://office.visualstudio.com/OC/_workitems/edit/4221810 
Legends over flow items in screen reader
> Legends: Fix Incorrect role is defined for lagend overflow items

- change/office-ui-fabric-react-2020-06-29-17-18-59-xgao-high-contrast-fix-3.json
- packages/office-ui-fabric-react/src/components/Nav/Nav.styles.ts
- packages/office-ui-fabric-react/src/components/Nav/__snapshots__/Nav.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/Nav.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Nav.CustomGroupHeaders.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/Nav.Nested.Example.tsx.shot
**Before**:
**After**:
on focused:
(optional)
> High Contrast in Edge Chromium: fix Nav

- change/office-ui-fabric-react-2020-06-29-15-40-13-xgao-high-contrast-fix-2.json
- packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroupOption/ChoiceGroupOption.styles.ts
- packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroupOption/__snapshots__/ChoiceGroupOption.test.tsx.snap
- packages/office-ui-fabric-react/src/components/__snapshots__/ChoiceGroup.Basic.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ChoiceGroup.Controlled.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ChoiceGroup.Custom.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ChoiceGroup.Icon.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ChoiceGroup.Image.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ChoiceGroup.Label.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/ColorPicker.Basic.Example.tsx.shot
> High Contrast in Edge Chromium: fix ChoiceGroup.

- change/office-ui-fabric-react-2020-06-30-13-46-39-xgao-high-contrast-fix-4.json
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.cnstyles.ts
- packages/office-ui-fabric-react/src/components/__snapshots__/ContextualMenu.Basic.Example.tsx.shot
Before fix:
After fix:
(optional)
> High Contrast in Edge Chromium: Fix ContextualMenu

- apps/vr-tests/package.json
- apps/vr-tests/src/stories/ButtonNext.stories.tsx
Button: Adding story of Button using styled icon from react-icons via tokens.
(optional)
> Button: Adding story of Button using styled icon from react-icons via tokens

- change/@uifabric-charting-2020-06-26-12-35-30-user-v-sivsar-removeBenchMarkAndTarget.json
- packages/charting/src/components/StackedBarChart/examples/StackedBarChart.Benchmark.Example.tsx
removing benchmark data, and target data from the stacked bar chart
stacked bar chart
**before fix**
**after fix**
> remove bench mark and target

- packages/fluentui/ability-attributes/schema.json
- packages/fluentui/docs/src/examples/components/Form/Usage/FormExampleErrorAndSuccessful.tsx
Adds validation for form components and `FormField`
(optional)
> feat(Schema): Add validation for forms and form components

- packages/fluentui/docs/package.json
- packages/fluentui/e2e/package.json
- yarn.lock
| package                 | current | new   |
|-------------------------|---------|-------|
| react-router-dom        | 5.0.1   | 5.2.0 |
| @types/react-router-dom | 4.3.4   | 5.1.5 |
> Update react-router-dom in @fluentui/docs and @fluentui/e2e packages

- packages/fluentui/react-northstar/src/themes/teams/components/SplitButton/splitButtonStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/SplitButton/splitButtonVariables.ts
> SplitButton - Padding 12px on the sides. Added a variable for minWidth.

- change/@uifabric-charting-2020-07-03-18-35-08-user-v-jasha-LineChartScreenReaderIssue.json
- packages/charting/src/components/LineChart/LineChart.base.tsx
Issue: 
While navigating through narrator, callout data not reading properly.
Added unique id's to callout and cirlce's of line chart
Line chart - accessibility
> Line chart - callout and circle ID's updated.

- change/office-ui-fabric-react-2020-07-07-14-34-22-fix-removing-console-log.json
- packages/office-ui-fabric-react/src/components/MarqueeSelection/examples/MarqueeSelection.Basic.Example.tsx
Removing console.log from `MarqueeSelection.Basic.Example.tsx`
> Removing console.log from MarqueeSelection Example

- change/@uifabric-file-type-icons-2020-07-07-21-15-24-linked-folder-icon.json
- packages/file-type-icons/src/FileIconType.ts
- packages/file-type-icons/src/getFileTypeIconProps.ts
Add a special folder (linked folder) icon support.
(optional)
> Linked folder icon

- change/@fluentui-codemods-2020-07-09-09-45-38-codemods-maybe.json
- packages/codemods/src/codeMods/mods/componentToCompat/componentToCompat.mod.ts
- packages/codemods/src/codeMods/mods/officeToFluentImport/officeToFluentImport.mod.ts
- packages/codemods/src/codeMods/mods/personaToAvatar/personaToAvatar.mod.ts
- packages/codemods/src/codeMods/types.ts
- packages/codemods/src/maybe.ts
- packages/codemods/src/modRunner/runnerUtilities.ts
- packages/codemods/src/modRunner/tests/mocks/MockMods/CodeMod.mock.ts
- packages/codemods/src/modRunner/tests/modRunner.test.ts
- packages/codemods/src/upgrade.ts
Maybe makes it very easy to transform and deal with possibly undefined values. It can greatly help clarify and streamline chains of code that operate on something that may or may not exist.
(optional)
> CodeMods: Implement Maybe to help deal with null/undefined checks.

- apps/fabric-website/src/utilities/svgIcons.tsx
- change/@uifabric-fabric-website-2020-07-09-12-45-48-website-icon-fix.json
SVG icons had hard coded ids. made them unique.
> Website icon fix - give icons unique IDs

- packages/fluentui/react-northstar/src/themes/teams/components/Chat/chatMessageStyles.ts
> fix(ChatMessage): remove auto width

- .github/CODEOWNERS
This updates the code owners of packages/foundation. Jason is focused on broader eng systems work. Seems like it makes sense to move this to David and Mak. They are familiar with the area. Note this will likely be replaced by some of the new work around how we build components. 
@JasonGore is this reasonable?
@dzearing and @khmakoto are you ok picking this up?
N/A
> Update CODEOWNERS for packages/foundation

- apps/fabric-website/src/pages/HomePage/HomePage.base.tsx
- apps/fabric-website/src/root.tsx
- apps/fabric-website/src/utilities/svgIcons.tsx
- apps/fabric-website/src/utilities/svgIconsColor.tsx
- change/@uifabric-fabric-website-2020-07-10-09-31-11-website-hook-fix.json
Fixes bug in #13967
useId is only valid in react components. our icons are just functions returning jsx elements for the registerIcons function
> Website hook fix

- apps/fabric-website/src/data/responsive-breakpoints.json
- change/@uifabric-fabric-website-2020-07-13-20-44-33-patch-1.json
> docs: fix spelling mistake

- apps/vr-tests/src/stories/Card.stories.tsx
- change/@uifabric-react-cards-2020-07-09-15-20-23-cardFocus.json
- packages/react-cards/etc/react-cards.api.md
- packages/react-cards/src/components/Card/Card.styles.ts
- packages/react-cards/src/components/Card/Card.types.ts
The `Card` component didn't provide focus styling when it was defined as clickable. This PR fixes that issue.
(optional)
> Card: Fixing focus styling

- change/@fluentui-react-next-2020-07-13-15-50-02-xgao-react-next-release-notes.json
- packages/react-next/release.md
update (manually maintained) release notes for `react-next`
(optional)
> react-next: update release notes

- change/@fluentui-codemods-2020-07-13-15-24-23-fix-maybe.json
- packages/codemods/src/maybe.ts
- packages/codemods/src/modRunner/maybe.test.ts
> Codemods: Maybe's functions weren't correctly bound to the object. Also add in test

- packages/fluentui/react-northstar/src/components/Form/FormCheckbox.tsx
- packages/fluentui/react-northstar/src/components/Form/FormRadioGroup.tsx
- packages/fluentui/react-northstar/src/components/Form/FormSlider.tsx
- packages/fluentui/react-northstar/src/themes/teams/componentVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Form/formFieldStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Form/formFieldVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Form/formLabelStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Form/formLabelVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Form/formMessageStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Form/formMessageVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Form/formStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Form/formVariables.tsx
- packages/fluentui/react-northstar/src/themes/teams/components/Input/inputLabelStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Input/inputLabelVariables.ts
Small styles fixes for forms, form field and form components
(optional)
> fix(Form): small styles changes

- packages/fluentui/CHANGELOG.md
- packages/fluentui/docs/src/examples/components/SplitButton/Slots/SplitButtonToggleButtonExample.shorthand.tsx
Fix menu open controlled state example
**Before**
**After**
> Chore(Splitbutton): Fix docsite example

- change/@uifabric-charting-2020-07-15-12-11-05-user-v-sivsar-CalloutUSeTheming.json
- packages/charting/src/utilities/ChartHoverCard/ChartHoverCard.base.tsx
- packages/charting/src/utilities/ChartHoverCard/ChartHoverCard.styles.ts
- packages/charting/src/utilities/ChartHoverCard/ChartHoverCard.tsx
- packages/charting/src/utilities/ChartHoverCard/ChartHoverCard.types.ts
wrapping the chard card content in styled component and removed static theme from the style file
callout content in chart
> chart hover card content component wrapped in styled component

- change/@fluentui-codemods-2020-07-15-00-09-39-maybe-then-return.json
- packages/codemods/src/codeMods/utilities/props.ts
- packages/codemods/src/maybe.ts
- packages/codemods/src/modRunner/maybe.test.ts
> Maybe: Improve then return and remove thenMaybe

- change/@fluentui-react-focus-2020-07-16-09-08-52-xgao-fix-publish-3.json
- change/@uifabric-react-hooks-2020-07-16-09-08-52-xgao-fix-publish-3.json
- change/office-ui-fabric-react-2020-07-16-09-08-52-xgao-fix-publish-3.json
- packages/office-ui-fabric-react/package.json
- packages/react-focus/package.json
- packages/react-hooks/package.json
Fix publish by syncing with published versions
(optional)
> Fix publish by syncing with published versions

- change/office-ui-fabric-react-2020-07-16-17-39-41-xgao-panel-dismiss-event.json
- packages/office-ui-fabric-react/src/components/Panel/Panel.base.tsx
pass missing event to onDismiss
(optional)
> Panel: pass missing event to onDismiss

- apps/fabric-website/src/styles/_base.scss
- change/@uifabric-fabric-website-2020-07-17-13-21-23-fix-youtube.json
Hiding unnecessary link from the site footer, while we understand the right fix.
> Removing unnecessary link from website footer

- change/@uifabric-charting-2020-07-17-14-37-38-master.json
- packages/charting/src/components/SankeyChart/SankeyChart.styles.ts
Charting: Fix sankey chart dark mode text not visble properly
Sankey chart darkmode
> Charting: Fix sankey chart dark mode text not visble properly

- change/office-ui-fabric-react-2020-07-17-09-23-46-xgao-details-row.json
- packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx
Only register event when selection is defined. Fix is on line 87.
(optional)
> DetailsList: fix exception in DetailsRow when selection is undefined.

- change/@uifabric-experiments-2020-07-20-12-34-01-u-nebhatna-fixPasteLogic.json
- packages/experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/examples/UnifiedPeoplePicker.Example.tsx
- packages/experiments/src/components/UnifiedPicker/UnifiedPicker.tsx
Fixing a bug in paste logic in unifiedpicker.
Updating the example to set the array useState hooks correctly.
(optional)
> [UnifiedPicker] Fixing the paste logic and updating the example

- change/@fluentui-react-next-2020-07-21-20-26-28-react-next-copy-Callout.json
- packages/react-next/etc/react-next.api.md
- packages/react-next/src/Callout.ts
- packages/react-next/src/components/Callout/Callout.doc.tsx
- packages/react-next/src/components/Callout/Callout.test.tsx
- packages/react-next/src/components/Callout/Callout.tsx
- packages/react-next/src/components/Callout/Callout.types.ts
- packages/react-next/src/components/Callout/CalloutContent.base.tsx
- packages/react-next/src/components/Callout/CalloutContent.styles.ts
- packages/react-next/src/components/Callout/CalloutContent.test.tsx
- packages/react-next/src/components/Callout/CalloutContent.tsx
- packages/react-next/src/components/Callout/FocusTrapCallout.tsx
- packages/react-next/src/components/Callout/FocusTrapCallout.types.ts
- packages/react-next/src/components/Callout/__snapshots__/Callout.test.tsx.snap
- packages/react-next/src/components/Callout/docs/CalloutDonts.md
- packages/react-next/src/components/Callout/docs/CalloutDos.md
- packages/react-next/src/components/Callout/docs/CalloutOverview.md
- packages/react-next/src/components/Callout/examples/Callout.Basic.Example.tsx
- packages/react-next/src/components/Callout/examples/Callout.Cover.Example.tsx
- packages/react-next/src/components/Callout/examples/Callout.Directional.Example.tsx
- packages/react-next/src/components/Callout/examples/Callout.FocusTrap.Example.tsx
- packages/react-next/src/components/Callout/examples/Callout.Status.Example.tsx
- packages/react-next/src/components/Callout/index.ts
- packages/react-next/src/components/Modal/Modal.base.tsx
> [Callout] Copy OUFR code to react-next

- apps/codesandbox-react-next-template/tsconfig.json
- apps/codesandbox-react-northstar-template/tsconfig.json
- apps/codesandbox-react-template/tsconfig.json
updates tsconfig.json file to remove comments and look more similar to other tsconfig.json files
(optional)
> update codesandbox templates' tsconfig.json

- change/@uifabric-experiments-2020-07-17-10-04-45-unifiedpickeraccessibilityfixes.json
- packages/experiments/src/components/SelectedItemsList/SelectedItemsList.test.tsx
- packages/experiments/src/components/SelectedItemsList/SelectedItemsList.tsx
- packages/experiments/src/components/SelectedItemsList/SelectedPeopleList/__snapshots__/SelectedPeopleList.test.tsx.snap
- packages/experiments/src/components/SelectedItemsList/__snapshots__/SelectedItemsList.test.tsx.snap
- packages/experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/__snapshots__/UnifiedPeoplePicker.test.tsx.snap
- packages/experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/examples/UnifiedPeoplePicker.Example.tsx
- packages/experiments/src/components/UnifiedPicker/UnifiedPicker.tsx
- packages/experiments/src/components/UnifiedPicker/__snapshots__/UnifiedPicker.test.tsx.snap
Fixing three errors given by the edge accessibility tooling
> UnifiedPicker accessibility fixes

- change/@uifabric-experiments-2020-07-17-23-30-30-eslint-hooks-experiments.json
- packages/experiments/.eslintrc.json
- packages/experiments/package.json
- packages/experiments/src/components/Button/MenuButton/MenuButton.state.ts
- packages/experiments/src/components/CollapsibleSection/CollapsibleSection.state.tsx
- packages/experiments/src/components/SelectedItemsList/Items/CopyableItem.tsx
- packages/experiments/src/components/SelectedItemsList/Items/EditableItem.tsx
- packages/experiments/src/components/SelectedItemsList/Items/ItemWithContextMenu.tsx
- packages/experiments/src/components/SelectedItemsList/Items/TriggerOnContextMenu.tsx
- packages/experiments/src/components/SelectedItemsList/SelectedItemsList.tsx
- packages/experiments/src/components/SelectedItemsList/SelectedPeopleList/Items/SelectedPersona.tsx
- packages/experiments/src/components/Toggle/Toggle.state.ts
- packages/experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/UnifiedPeoplePicker.tsx
Enable `eslint-plugin-react-hooks` "rules of hooks" lint rules in `@uifabric/experiments`.
Most of the issues were in the SelectedItemsList and UnifiedPicker, where I'll need @nebhatna's help verifying the fixes or in some cases figuring out the right fix.
> Enable "rules of hooks" lint rules in experiments

- packages/fluentui/react-builder/src/components/Designer.tsx
- packages/fluentui/react-builder/src/components/GetShareableLink.tsx
- packages/fluentui/react-builder/src/components/Toolbar.tsx
- packages/react-next/src/components/Dropdown/Dropdown.types.ts
- packages/react-next/src/components/Dropdown/docs/DropdownOverview.md
This PR adds the options to `download` or `upload` json tree for UI builder
(optional)
> feat(builder): download/upload

- change/@fluentui-react-next-2020-07-27-18-44-10-feat-moving-teachingBubble.json
- packages/react-next/src/components/TeachingBubble/TeachingBubble.base.tsx
- packages/react-next/src/components/TeachingBubble/TeachingBubble.deprecated.test.tsx
- packages/react-next/src/components/TeachingBubble/TeachingBubble.doc.tsx
- packages/react-next/src/components/TeachingBubble/TeachingBubble.styles.ts
- packages/react-next/src/components/TeachingBubble/TeachingBubble.test.tsx
- packages/react-next/src/components/TeachingBubble/TeachingBubble.ts
- packages/react-next/src/components/TeachingBubble/TeachingBubble.types.ts
- packages/react-next/src/components/TeachingBubble/TeachingBubbleContent.base.tsx
- packages/react-next/src/components/TeachingBubble/TeachingBubbleContent.ts
- packages/react-next/src/components/TeachingBubble/__snapshots__/TeachingBubble.deprecated.test.tsx.snap
- packages/react-next/src/components/TeachingBubble/__snapshots__/TeachingBubble.test.tsx.snap
- packages/react-next/src/components/TeachingBubble/docs/TeachingBubbleBestPractices.md
- packages/react-next/src/components/TeachingBubble/docs/TeachingBubbleDonts.md
- packages/react-next/src/components/TeachingBubble/docs/TeachingBubbleDos.md
- packages/react-next/src/components/TeachingBubble/docs/TeachingBubbleOverview.md
- packages/react-next/src/components/TeachingBubble/examples/TeachingBubble.Basic.Example.tsx
- packages/react-next/src/components/TeachingBubble/examples/TeachingBubble.Condensed.Example.tsx
- packages/react-next/src/components/TeachingBubble/examples/TeachingBubble.Illustration.Example.tsx
- packages/react-next/src/components/TeachingBubble/examples/TeachingBubble.MultiStep.Example.tsx
- packages/react-next/src/components/TeachingBubble/examples/TeachingBubble.SmallHeadline.Example.tsx
- packages/react-next/src/components/TeachingBubble/examples/TeachingBubble.Wide.Example.tsx
- packages/react-next/src/components/TeachingBubble/examples/TeachingBubble.WideIllustration.Example.tsx
- packages/react-next/src/components/TeachingBubble/index.ts
This change does not modify `TeachingBubble`; it simply moves it into react-next for better diffing in the actual conversion PR.
> Copying TeachingBubble to react-next, in preparation for converting to a function component

- .github/CODEOWNERS
Adding Roman (pompomon) to code owners for date-time and OUFR Calendar. Also creating new line for date-time-utilities.
(optional)
> adding Roman to codeowners for date time

- change/@fluentui-react-next-2020-07-21-21-40-07-function-react-next-release.json
- packages/react-next/RELEASE_NOTES.md
Add a general comment to the `react-next` release notes about the change to refs as relating to function component migrations.
(optional)
> Add general comment about refs in function components

- change/office-ui-fabric-react-2020-07-28-13-25-07-grouped-list-keyboard.json
- packages/office-ui-fabric-react/src/components/DetailsList/__snapshots__/DetailsList.test.tsx.snap
- packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.base.tsx
- packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx
- packages/office-ui-fabric-react/src/components/GroupedList/examples/GroupedList.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.CustomGroupHeaders.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Grouped.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.Grouped.Large.Example.tsx.shot
- packages/office-ui-fabric-react/src/components/__snapshots__/GroupedList.CustomCheckbox.Example.tsx.shot
> GroupedList: Added built in keyboard support

- change/office-ui-fabric-react-2020-06-30-17-25-40-suggestion-list-clipping-fix.json
- packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.styles.ts
- packages/office-ui-fabric-react/src/components/pickers/Suggestions/__snapshots__/Suggestions.test.tsx.snap
This adds a noop transform that forces hardware acceleration.
> Suggestion list clipping fix

- change/@uifabric-charting-2020-07-24-19-25-31-user-v-gorraj-TSK_4323726.json
- packages/charting/src/components/SankeyChart/SankeyChart.base.tsx
- packages/charting/src/components/SankeyChart/SankeyChart.styles.ts
- packages/charting/src/components/SankeyChart/SankeyChart.types.ts
- packages/charting/src/components/SankeyChart/examples/SankeyChart.Basic.Example.tsx
Charting: Add Accessibility support for Sankey chart
Sankey chart
> Charting: Add Accessibility support for Sankey chart

- packages/fluentui/react-builder/src/components/List.tsx
> Fixed search after adding Tree

- packages/web-components/README.md
Fixed a missing close html tag on the readme page for the web components package.
> Added missing close script tag

- packages/fluentui/react-builder/src/components/ComponentTree.tsx
- packages/fluentui/react-builder/src/components/Designer.tsx
> Component Tree Styling

- packages/web-components/docs/api-report.md
- packages/web-components/package.json
- packages/web-components/src/accordion/accordion-item/index.ts
- packages/web-components/src/accordion/index.ts
- packages/web-components/src/anchor/index.ts
- packages/web-components/src/badge/index.ts
- packages/web-components/src/button/index.ts
- packages/web-components/src/card/index.ts
- packages/web-components/src/checkbox/index.ts
- packages/web-components/src/dialog/index.ts
- packages/web-components/src/divider/index.ts
- packages/web-components/src/flipper/index.ts
- packages/web-components/src/menu-item/index.ts
- packages/web-components/src/menu/index.ts
- packages/web-components/src/progress/progress-ring/index.ts
- packages/web-components/src/progress/progress/index.ts
- packages/web-components/src/radio-group/index.ts
- packages/web-components/src/radio/index.ts
- packages/web-components/src/slider-label/index.ts
- packages/web-components/src/slider/index.ts
- packages/web-components/src/switch/index.ts
- packages/web-components/src/tabs/index.ts
- packages/web-components/src/tabs/tab-panel/index.ts
- packages/web-components/src/tabs/tab/index.ts
- packages/web-components/src/text-area/index.ts
- packages/web-components/src/text-field/index.ts
- packages/web-components/src/tree-item/index.ts
- packages/web-components/src/tree-view/index.ts
- yarn.lock
Exposed styles for FAST web components and updated the version for `fast-foundation` and `fast-element` dependencies.
(optional)
> fix: export web component styles

- change/@uifabric-charting-2020-07-31-14-54-32-user-v-jasha-refreshIssueInGVBChart.json
- packages/charting/src/components/GroupedVerticalBarChart/GroupedVerticalBarChart.base.tsx
Charting: Grouped vertical bar chart refresh issue in admin controls
Grouped vertical bar chart
> Charting: Grouped vertical bar chart refresh issue in admin controls

- change/@fluentui-web-components-2020-08-06-14-14-52-users-chhol-fix-unpkg-link-from-publish.json
- packages/web-components/README.md
- packages/web-components/rollup.config.js
Fixes an issue where the rollup build didn't match the unpkg config.
> fix: update rollup config and incorrect readme import

- azure-pipelines.perf-test.yml
- azure-pipelines.yml
This adds scoped flag to the build + test + lint stage while moving the perf-test to be triggered after the deploy step. 
(optional)
> scoped build + test + lint; moved the trigger of perf-test after deploy job

- specs/Skeleton.md
Add `Skeleton` spec
(optional)
> docs(Skeleton): add Skeleton spec

- change/@fluentui-react-compose-2020-08-10-01-04-21-fix-ref-check.json
- packages/react-compose/src/next/mergeProps.ts
Ran into a missing typecheck issue integrating Button into Ribbon. Addressing.
> next mergeProps: Adding a typecheck

- change/@fluentui-react-compose-2020-08-10-01-04-21-fix-ref-check.json
- packages/react-compose/src/next/mergeProps.ts
Apparently `typeof null` is `object`.
> Fixing another type check

- change/office-ui-fabric-react-2020-08-04-19-44-40-add-restorer-tocontextualmenu.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx
- packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts
> ContextualMenu: Add focusrestorer override

- change/@fluentui-web-components-2020-08-08-13-34-32-users-chhol-fix-accor-examples.json
- packages/web-components/src/accordion/fixtures/base.html
Fixes an issue where the expand and collapse slots of the accordion were incorrectly applied.
(optional)
> chore: fix accordion web component examples

- azure-pipelines.perf-test.yml
- azure-pipelines.release-fluentui.yml
- azure-pipelines.release.yml
- azure-pipelines.yml
> Target new pool for CI

- azure-pipelines.release-fluentui.yml
- azure-pipelines.release.yml
Revert portion of #14474 while dependencies are investigated.
> Use self host ubuntu pool for release.

- packages/fluentui/CHANGELOG.md
- packages/fluentui/docs/src/examples/components/Skeleton/Variations/SkeletonExampleComponents.tsx
- packages/fluentui/react-northstar/src/components/Skeleton/Skeleton.tsx
- packages/fluentui/react-northstar/src/components/Skeleton/SkeletonAvatar.tsx
- packages/fluentui/react-northstar/src/index.ts
- packages/fluentui/react-northstar/src/themes/teams/componentStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/componentVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Skeleton/skeletonAvatarStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Skeleton/skeletonAvatarVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Skeleton/skeletonVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Skeleton/utils/animations.ts
- packages/fluentui/react-northstar/test/specs/components/Skeleton/SkeletonAvatar-test.tsx
This PR adds `SkeletonAvatar` boilerplate 
(optional)
> feat(SkeletonAvatar): add SkeletonAvatar component

- change/office-ui-fabric-react-2020-08-12-11-50-56-pickers-to-concurrentmode.json
- packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md
- packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx
Pickers: Update to remove deprecated lifecycle methods and enable concurrent mode
(optional)
> Pickers: Update to remove deprecated lifecycle methods and enable concurrent mode

- packages/fluentui/react-northstar/src/components/Chat/Chat.tsx
- packages/fluentui/react-northstar/src/components/Chat/ChatMessageHeader.tsx
- packages/fluentui/react-northstar/src/index.ts
- packages/fluentui/react-northstar/test/specs/components/Chat/ChatMessageHeader-test.tsx
We were missing tests for `ChatMessageHeader` and some small mistakes on it
(optional)
> fix(ChatMessageHeader): Add ChatMessageHeader test and proper fixes

- packages/fluentui/react-northstar/src/components/Dropdown/DropdownSearchInput.tsx
- packages/fluentui/react-northstar/test/specs/components/Dropdown/DropdownSearchInput-test.tsx
We were missing tests for `DropdownSearchInput`
(optional)
> fix(DropdownSearchInput): add tests and proper fixes

- change/@fluentui-codemods-2020-08-20-15-29-37-cm-improve-logging.json
- packages/codemods/src/codeMods/mods/componentToCompat/compatHelpers.ts
- packages/codemods/src/codeMods/mods/configMod/configMod.ts
- packages/codemods/src/codeMods/mods/officeToFluentImport/officeToFluentImport.mod.ts
- packages/codemods/src/codeMods/tests/configMod/configMod.test.ts
- packages/codemods/src/codeMods/tests/utilities/importUtils.test.ts
- packages/codemods/src/codeMods/types.ts
- packages/codemods/src/codeMods/utilities/imports.ts
- packages/codemods/src/helpers/result.ts
- packages/codemods/src/modRunner/runnerUtilities.ts
- packages/codemods/src/upgrade.ts
> CodeMods: Improve logging and implement more result.

- packages/fluentui/react-northstar/src/components/Chat/ChatMessage.tsx
Hot fix for handled prop
(optional)
> fix(ChatMessage): add prop to proptypes

- change/@uifabric-experiments-2020-08-20-11-13-32-u-nebhatna-dragDropFix.json
- packages/experiments/src/components/SelectedItemsList/SelectedPeopleList/Items/SelectedPersona.tsx
- packages/experiments/src/components/SelectedItemsList/SelectedPeopleList/__snapshots__/SelectedPeopleList.test.tsx.snap
- packages/experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/__snapshots__/UnifiedPeoplePicker.test.tsx.snap
> SelectedItemsList - fix infinite loop and some optimizations

- change/office-ui-fabric-react-2020-08-20-12-46-18-groupedListExamplesWithStrictFunctionTypes.json
- packages/office-ui-fabric-react/src/components/GroupedList/examples/GroupedList.Basic.Example.tsx
- packages/office-ui-fabric-react/src/components/GroupedList/examples/GroupedList.Custom.Example.tsx
- packages/office-ui-fabric-react/src/components/GroupedList/examples/GroupedList.CustomCheckbox.Example.tsx
This PR fixes the errors that were arising in the `GroupedList` component examples when the `strictFunctionTypes` rule was turned on in the `tsconfig`.
(optional)
> GroupedList: Fixing errors in the examples that are triggered when the tsconfig strictFunctionTypes rule is turned on

- change/@uifabric-utilities-2020-07-24-13-09-30-debounce-type-definition.json
- packages/utilities/etc/utilities.api.md
- packages/utilities/src/Async.test.ts
- packages/utilities/src/Async.ts
…clude a better inferred type for the throttled/debounced function
Updating the type definitions for the Async.debounce and Async.throttle to include more correct type inference of the throttled/debounced function.
Types around existing usages.
> Async.debounce / Async.throttle Type Updates

- change/@fluentui-react-next-2020-08-24-16-43-20-xgao-fix-build-2.json
- packages/react-next/package.json
`@fluentui/react-window-provider` in `react-next` is out of sync
(optional)
> Fix build: sync package version

- change/@fluentui-react-theme-provider-2020-08-25-12-30-38-xgao-themeprovider-theme-typing.json
- change/@fluentui-theme-2020-08-25-12-30-38-xgao-themeprovider-theme-typing.json
- packages/react-theme-provider/src/getTokens.ts
- packages/theme/src/types/Theme.ts
fix Theme and Partialtheme typing
(optional)
> ThemeProvider: fix Theme and PartialTheme typing

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-builder/src/components/Designer.tsx
Removes url parameters when user switches to store view.
> Removes url parameters after switch to store - UI builder

- change/@uifabric-charting-2020-08-25-13-40-14-user-v-sivsar-allowFocusTOLegendsBYDefault_1.json
- packages/charting/src/components/Legends/Legends.base.tsx
- packages/charting/src/components/Legends/Legends.types.ts
- packages/charting/src/components/Legends/examples/Legends.Basic.Example.tsx
- packages/charting/src/components/Legends/examples/Legends.Overflow.Example.tsx
- packages/charting/src/components/Legends/examples/Legends.WrapLines.Example.tsx
- packages/charting/src/components/VerticalBarChart/__snapshots__/VerticalBarChart.test.tsx.snap
making the legends focusable  by default
legends
> making legends focus by default.

- packages/fluentui/CHANGELOG.md
- packages/fluentui/e2e/e2eApi.ts
- packages/fluentui/e2e/tests/menuDismissScroll-example.tsx
- packages/fluentui/e2e/tests/menuDismissScroll-test.ts
- packages/fluentui/react-northstar/src/components/Menu/MenuItem.tsx
This PR will make that opened menus close at page scroll.
(optional)
> feat(Menu): dismiss menu on scroll

- change/@uifabric-experiments-2020-08-27-12-29-09-upforwardref.json
- packages/experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/UnifiedPeoplePicker.tsx
- packages/experiments/src/components/UnifiedPicker/UnifiedPeoplePicker/examples/UnifiedPeoplePicker.Example.tsx
- packages/experiments/src/components/UnifiedPicker/UnifiedPicker.tsx
Set up forwardRef and two new function on the UnifiedPicker, clearInput and focus, so callers can call those functions
> use forwardRef for the UnifiedPicker

- packages/fluentui/docs/src/examples/components/Button/Performance/ButtonOverridesMiss.perf.tsx
- packages/fluentui/docs/src/examples/components/Button/Performance/ButtonUseCss.perf.tsx
- packages/fluentui/docs/src/examples/components/Button/Performance/ButtonUseCssNesting.perf.tsx
- packages/fluentui/e2e/tests/popupWithCloseInContent-test.ts
- packages/fluentui/e2e/tsconfig.json
This PR makes few small changes to existing tests.
> chore: disable test, add iterations to existing

- specs/Datepicker.md
Adding documentation for FabricUI vs. FluentUI datepicker differences.
> Adding FabricUI vs. FluentUI Datepicker Differences

- packages/fluentui/CHANGELOG.md
- packages/fluentui/react-northstar/src/themes/teams-dark/colors.ts
- packages/fluentui/react-northstar/src/themes/teams-high-contrast/colors.ts
- packages/fluentui/react-northstar/src/themes/teams/colors.ts
This PR adds `foreground5` and `foreground6`
(optional)
> feat(theme): add new foreground colors

- packages/fluentui/react-northstar/src/themes/teams-high-contrast/componentVariables.ts
- packages/fluentui/react-northstar/src/themes/teams-high-contrast/components/Skeleton/skeletonVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/colors.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Skeleton/skeletonVariables.ts
- packages/fluentui/react-northstar/src/themes/teams/components/Skeleton/utils/animations.ts
Update `Skeleton` colors 
(optional)
> fix(Skeleton): fix colors

- packages/fluentui/docs/src/examples/components/Chat/Usage/ChatExampleInScrollable.shorthand.tsx
- packages/fluentui/docs/src/examples/components/Toolbar/Visual/ToolbarExampleVariables.shorthand.tsx
Similar to #14845. Tries to make positions stable and avoid continuous regressions.
> chore: try different positioning for examples

- change/@fluentui-react-compose-2020-09-01-17-42-22-fix-mergeProps.json
- packages/react-compose/src/next/mergeProps.test.tsx
- packages/react-compose/src/next/mergeProps.ts
> mergeProps: less bugs, more tests

- packages/fluentui/CHANGELOG.md
- packages/fluentui/docs/src/examples/components/TextArea/Variations/TextAreaExampleAutoHeight.shorthand.tsx
- packages/fluentui/docs/src/examples/components/TextArea/Variations/index.tsx
- packages/fluentui/react-northstar/src/components/TextArea/TextArea.tsx
- packages/fluentui/react-northstar/src/themes/teams/components/TextArea/textAreaStyles.ts
- packages/fluentui/react-northstar/src/themes/teams/components/TextArea/textAreaVariables.ts
This reverts commit cf1345362e61a87854b23a7af1ee49f3f37f7167.
Revert #14860 as we should discuss to define how to implement and maintain it 
(optional)
> Revert "feat(TextArea): Add autoAdjustHeight (#14860)"
